### DISCUSSION TITLE
Disaster recovery with Storage and `/var/lib/rook` only

### DISCUSSION THREAD

**Discussion by M-Gregoire** [rook/rook#10742] [General]
Hello everyone,

I'm a bit desperate and I'm seeking for some help. I've mistakenly changed the namespace `rook` was running in, which made flux (fluxcd.io) prune all the previous `rook-ceph` namespace, deleting all resources inside, and attempting to recreate the `ceph-cluster` inside a new namespace. 

I've immediately reverted back the namespace to `rook-ceph` in the Helm Chart, but all the resources (Including secrets) where recreated from scratch.

Being the dummy I am, I don't have any backup of my k8s cluster state at hand, I have:

- The full drive which contains all my Ceph data (relevant config):
```
      storage:
        useAllDevices: false
        useAllNodes: false
        nodes:
          - name: "<my-node>"
            devices:
              - name: "/dev/disk/by-id/<id-here>"
```
- The `/var/lib/rook` folder I saved right after the incident

This is a 1 mon / 1 mgr setup on 1 machine.

Note: The new ceph operator fails with:
```
 2022-08-18 18:54:25.187125 E | clusterdisruption-controller: cephcluster "rook-ceph/" seems to be deleted, not requeuing until triggered again  
```

Do I have any hope of getting my data back? Just being able to mount the CephBlockPools would be a life saver.

Any help would be greatly appreciated.
