### DISCUSSION TITLE
why all pg of the pool on one osd?

### DISCUSSION THREAD

**Discussion by zhucan** [rook/rook#10764] [Q&A] [answered]
**pool.yaml**
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool1
  namespace: rook-ceph
spec:
  crushRoot: root-1c0374fa-054f-48ff-b784-5d206a71453a
  erasureCoded:
    codingChunks: 0
    dataChunks: 0
  failureDomain: host
  mirroring:
    mode: image
  parameters:
    compression_mode: none
  quotas: {}
  replicated:
    requireSafeReplicaSize: true
    size: 3
  statusCheck:
    mirror:
      interval: 1m0s
```

**ceph osd tree:**

```
[root@rook-node02 /]# ceph osd tree
ID  CLASS  WEIGHT  TYPE NAME                                                  STATUS  REWEIGHT  PRI-AFF
-3              0  root root-1c0374fa-054f-48ff-b784-5d206a71453a                                      
-6              0      host rook-node01-355e4da0-76b8-4edb-bdae-40898c3cb852                           
 0    hdd       0          osd.0                                                  up   1.00000  1.00000
 3    hdd       0          osd.3                                                  up   1.00000  1.00000
-4              0      host rook-node02-70371911-2c73-4caf-b531-0ca0f2f099ee                           
 2    hdd       0          osd.2                                                  up   1.00000  1.00000
 5    hdd       0          osd.5                                                  up   1.00000  1.00000
-5              0      host rook-node03-8253fc7c-4246-4f86-b959-7c4908b5e6db                           
 1    hdd       0          osd.1                                                  up   1.00000  1.00000
 4    hdd       0          osd.4                                                  up   1.00000  1.00000
-1              0  root default  
```

**ceph osd df:**
```
[root@rook-node02 /]# ceph osd df 
ID  CLASS  WEIGHT  REWEIGHT  SIZE     RAW USE  DATA     OMAP     META     AVAIL    %USE  VAR   PGS  STATUS
 0    hdd       0   1.00000  100 GiB  5.9 MiB  828 KiB      0 B  5.1 MiB  100 GiB  0.01  0.98    1      up
 3    hdd       0   1.00000  100 GiB  5.9 MiB  828 KiB      0 B  5.1 MiB  100 GiB  0.01  0.98    0      up
 2    hdd       0   1.00000  100 GiB  5.9 MiB  828 KiB      0 B  5.1 MiB  100 GiB  0.01  0.97    0      up
 5    hdd       0   1.00000  100 GiB  5.9 MiB  828 KiB      0 B  5.1 MiB  100 GiB  0.01  0.97    0      up
 1    hdd       0   1.00000  100 GiB  6.9 MiB  824 KiB      0 B  6.1 MiB  100 GiB  0.01  1.14   33      up
 4    hdd       0   1.00000  100 GiB  5.9 MiB  828 KiB      0 B  5.1 MiB  100 GiB  0.01  0.98    0      up
                      TOTAL  600 GiB   37 MiB  4.8 MiB  5.7 KiB   32 MiB  600 GiB  0.01                   
MIN/MAX VAR: 0.97/1.14  STDDEV: 0
```

status of ceph cluster:
```
[root@rook-node02 /]# ceph -s 
  cluster:
    id:     efbcf016-153d-46fb-b130-285a72fba32a
    health: HEALTH_WARN
            Reduced data availability: 32 pgs inactive
            Degraded data redundancy: 33 pgs undersized
 
  services:
    mon: 3 daemons, quorum a,b,c (age 3h)
    mgr: a(active, since 3h), standbys: b
    osd: 6 osds: 6 up (since 6m), 6 in (since 3h); 1 remapped pgs
 
  data:
    pools:   2 pools, 33 pgs
    objects: 0 objects, 0 B
    usage:   37 MiB used, 600 GiB / 600 GiB avail
    pgs:     96.970% pgs not active
             32 undersized+peered
             1  active+undersized+remapped
```

**pool details:**
```
[root@rook-node02 /]# ceph osd pool ls detail
pool 1 'device_health_metrics' replicated size 3 min_size 1 crush_rule 1 object_hash rjenkins pg_num 1 pgp_num 1 autoscale_mode on last_change 62 flags hashpspool stripe_width 0 pg_num_max 32 pg_num_min 1 application mgr_devicehealth
pool 2 'replicapool1' replicated size 3 min_size 2 crush_rule 2 object_hash rjenkins pg_num 32 pgp_num 32 autoscale_mode on last_change 67 flags hashpspool stripe_width 0 compression_mode none application rbd
```

Create a cephblockpool with the pool.yaml, all of the pg on one osd, why?
