### DISCUSSION TITLE
Pod are unable to mount PVC

### DISCUSSION THREAD

**Discussion by panteparak** [rook/rook#11209] [Q&A] [answered]
I have a fresh k3s cluster running Rook Ceph. All Pods including Mgr Mon OSD etc are running fine and Ceph cluster is Healthy. However, when I tried to mount a PVC to a pod, I kept getting errors. I have tried both RBD and CephFs. Both produce the same error.

Both PVC has been provisioned successfully. with `Status: Bound`.

Rook cluster are deployed via Helm Chart
**k3s: v1.25.2+k3s1**
OS: Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-52-generic x86_64), 20.04.5 LTS (GNU/Linux 5.4.0-131-generic x86_64) (Tried both OS Version)
Rook: 1.10.4
Ceph: v17.2

```
Name:          task-pvc-fs
Namespace:     default
StorageClass:  rook-cephfs
Status:        Bound
Volume:        pvc-cbad6e62-49be-4feb-886e-47b17f5356c7
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
               volume.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       task-pv-pod-fs
Events:        <none>
```

csi-cephfsplugin
```
E1026 04:09:43.422884       1 utils.go:210] ID: 782 Req-ID: 0001-0009-rook-ceph-0000000000000001-d77241ee-5494-11ed-a5cd-7a3eb6bbec3a GRPC error: rpc error: code = Internal desc = an error (exit status 32) occurred while running mount args: [-t ceph 10.43.206.139:3300:/volumes/csi/csi-vol-d77241ee-5494-11ed-a5cd-7a3eb6bbec3a/570927b8-ed15-49a6-aa9d-d6081d39c0a6 /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/319bf46a5b7ced5757539cc0f021346e07f55daa46e57fc505cdbc5d051517d1/globalmount -o name=csi-cephfs-node,secretfile=/tmp/csi/keys/keyfile-1304688413,mds_namespace=ceph-filesystem,_netdev] stderr: unable to get monitor info from DNS SRV with service name: ceph-mon
2022-10-26T04:08:43.390+0000 7f40b1d1ff40 -1 failed for service _ceph-mon._tcp
mount error: no mds server is up or the cluster is laggy
E1026 04:12:45.693565       1 nodeserver.go:273] ID: 786 Req-ID: 0001-0009-rook-ceph-0000000000000001-d77241ee-5494-11ed-a5cd-7a3eb6bbec3a failed to mount volume 0001-0009-rook-ceph-0000000000000001-d77241ee-5494-11ed-a5cd-7a3eb6bbec3a: an error (exit status 32) occurred while running mount args: [-t ceph 10.43.206.139:3300:/volumes/csi/csi-vol-d77241ee-5494-11ed-a5cd-7a3eb6bbec3a/570927b8-ed15-49a6-aa9d-d6081d39c0a6 /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/319bf46a5b7ced5757539cc0f021346e07f55daa46e57fc505cdbc5d051517d1/globalmount -o name=csi-cephfs-node,secretfile=/tmp/csi/keys/keyfile-144649761,mds_namespace=ceph-filesystem,_netdev] stderr: unable to get monitor info from DNS SRV with service name: ceph-mon
2022-10-26T04:11:45.606+0000 7f0ad0573f40 -1 failed for service _ceph-mon._tcp
mount error: no mds server is up or the cluster is laggy
 Check dmesg logs if required.
E1026 04:12:45.693667       1 utils.go:210] ID: 786 Req-ID: 0001-0009-rook-ceph-0000000000000001-d77241ee-5494-11ed-a5cd-7a3eb6bbec3a GRPC error: rpc error: code = Internal desc = an error (exit status 32) occurred while running mount args: [-t ceph 10.43.206.139:3300:/volumes/csi/csi-vol-d77241ee-5494-11ed-a5cd-7a3eb6bbec3a/570927b8-ed15-49a6-aa9d-d6081d39c0a6 /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/319bf46a5b7ced5757539cc0f021346e07f55daa46e57fc505cdbc5d051517d1/globalmount -o name=csi-cephfs-node,secretfile=/tmp/csi/keys/keyfile-144649761,mds_namespace=ceph-filesystem,_netdev] stderr: unable to get monitor info from DNS SRV with service name: ceph-mon
2022-10-26T04:11:45.606+0000 7f0ad0573f40 -1 failed for service _ceph-mon._tcp
mount error: no mds server is up or the cluster is laggy
```

Helm CephCluster values
```
operatorNamespace: rook-ceph

monitoring:
  enabled: false
  rulesNamespace: rook-ceph
configOverride: |
    [global]
    osd_pool_default_min_size = 1
    osd_pool_default_size = 1
    mon_warn_on_pool_no_redundancy = false

    [osd]
    osd osd_min_pg_log_entries = 50
    osd osd_max_pg_log_entries = 500
    osd_memory_target_autotune = true
    # osd_memory_target = 2G
    # autotune_memory_target_ratio = 0.7
    mds_cache_memory_limit = 2G
    osd_scrub_auto_repair = true

toolbox:
  enabled: true

cephClusterSpec:
  # disruptionManagement:
  #   manageMachineDisruptionBudgets: false
  #   managePodBudgets: false

  cephVersion:
    # image: ceph/ceph:v15.2.7
    image: quay.io/ceph/ceph:v17.2
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: true
  continueUpgradeAfterChecksEvenIfNotHealthy: true
  priorityClassNames:
    mgr: storage-operator-tier
    mon: storage-agent-tier
    osd: storage-agent-tier
    rbdmirror: storage-agent-tier
  mon:
    count: 1
    allowMultiplePerNode: false

  mgr:
    count: 1
    modules:
    - name: pg_autoscaler
      enabled: true
  network:
    connections:
      encryption:
        enabled: false
      compression:
        enabled: true

  dashboard:
    enabled: true
    ssl: false

  resources:
    osd:
      requests:
        cpu: "500m"
        memory: "200Mi"
      limits:
        cpu: "2000m"
        memory: "2G"

  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/storage-cluster
              operator: Exists
    mon:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
    mgr:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    config:
      osdsPerDevice: "2"
    nodes:
      - name: "k8s-worker0"
        devices:
          - name: "sdb"
          - name: "nvme0n1"
            config:
              osdsPerDevice: "4"
          - name: "nvme1n1"
            config:
              osdsPerDevice: "4"
cephBlockPools:
  - name: ceph-block
    spec:
      replicated:
        size: 1
        requireSafeReplicaSize: false
      failureDomain: osd
    storageClass:
      enabled: true
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      isDefault: true
      name: rook-ceph-block
      parameters:
        imageFormat: "2"
        imageFeatures: layering
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
        csi.storage.k8s.io/fstype: ext4

cephFileSystems:
  - name: ceph-filesystem
    spec:
      metadataPool:
        replicated:
          size: 1
          requireSafeReplicaSize: false
      dataPools:
        - replicated:
            size: 1
      preserveFilesystemOnDelete: true
      metadataServer:
        activeCount: 1
        activeStandby: true
    storageClass:
      name: rook-cephfs
      enabled: true
      reclaimPolicy: Delete
      parameters:
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
        csi.storage.k8s.io/fstype: ext4

cephObjectStores:
  - name: asia-southeast-1
    spec:
      metadataPool:
        replicated:
          size: 1
      dataPool:
        replicated:
          size: 1
          requireSafeReplicaSize: false
      gateway:
        instances: 1
        port: 80
        securePort: 443
        endpoint: 
        priorityClassName: storage-agent-tier
      healthCheck:
        bucket:
          disabled: false
          interval: 60s 
      preservePoolsOnDelete: true
    storageClass:
      enabled: true
      name: rook-ceph-bucket
      reclaimPolicy: Delete
      parameters:
        region: asia-southeast-1
        objectStoreNamespace: rook-ceph
```

```
  cluster:
    id:     b04d6c95-c62a-4a84-9507-3bc1a5a6fb8f
    health: HEALTH_OK
 
  services:
    mon: 1 daemons, quorum a (age 23m)
    mgr: a(active, since 21m)
    mds: 1/1 daemons up, 1 hot standby
    osd: 10 osds: 10 up (since 20m), 10 in (since 21m)
 
  data:
    volumes: 1/1 healthy
    pools:   12 pools, 353 pgs
    objects: 62 objects, 695 KiB
    usage:   147 MiB used, 3.6 TiB / 3.6 TiB avail
    pgs:     353 active+clean
 
  io:
    client:   4.7 KiB/s rd, 341 B/s wr, 5 op/s rd, 0 op/s wr
```

All Pods are running and Healthy
```
NAME                                                    READY   STATUS      RESTARTS   AGE   IP              NODE          NOMINATED NODE   READINESS GATES
csi-cephfsplugin-f4xpl                                  2/2     Running     0          21m   192.168.3.128   k8s-master0   <none>           <none>
csi-cephfsplugin-kx9dz                                  2/2     Running     0          21m   192.168.3.130   k8s-worker0   <none>           <none>
csi-cephfsplugin-provisioner-898bfbc7d-2hrvm            5/5     Running     0          21m   10.233.0.6      k8s-master0   <none>           <none>
csi-cephfsplugin-provisioner-898bfbc7d-hsdjd            5/5     Running     0          21m   10.233.1.5      k8s-worker0   <none>           <none>
csi-rbdplugin-4vcr2                                     2/2     Running     0          21m   192.168.3.130   k8s-worker0   <none>           <none>
csi-rbdplugin-provisioner-567f546b99-djjbv              5/5     Running     0          21m   10.233.0.5      k8s-master0   <none>           <none>
csi-rbdplugin-provisioner-567f546b99-rqbdl              5/5     Running     0          21m   10.233.1.4      k8s-worker0   <none>           <none>
csi-rbdplugin-pwkd8                                     2/2     Running     0          21m   192.168.3.128   k8s-master0   <none>           <none>
rook-ceph-crashcollector-k8s-master0-57c997c694-gb95x   1/1     Running     0          20m   10.233.0.10     k8s-master0   <none>           <none>
rook-ceph-crashcollector-k8s-worker0-7bc66c6694-jw48r   1/1     Running     0          17m   10.233.1.21     k8s-worker0   <none>           <none>
rook-ceph-mds-ceph-filesystem-a-66bfff78f4-2sflm        2/2     Running     0          17m   10.233.1.20     k8s-worker0   <none>           <none>
rook-ceph-mds-ceph-filesystem-b-5f79c96599-sr44m        2/2     Running     0          16m   10.233.1.22     k8s-worker0   <none>           <none>
rook-ceph-mgr-a-58947d6cd9-zt54k                        2/2     Running     0          20m   10.233.0.9      k8s-master0   <none>           <none>
rook-ceph-mon-a-86f774f4cc-xqf9b                        2/2     Running     0          21m   10.233.0.8      k8s-master0   <none>           <none>
rook-ceph-operator-64457874b-5lpp9                      1/1     Running     0          23m   10.233.1.2      k8s-worker0   <none>           <none>
rook-ceph-osd-0-984b5798f-fdzgj                         2/2     Running     0          19m   10.233.1.17     k8s-worker0   <none>           <none>
rook-ceph-osd-1-6f8c75c878-sqjmm                        2/2     Running     0          19m   10.233.1.12     k8s-worker0   <none>           <none>
rook-ceph-osd-2-8686688988-lw7q7                        2/2     Running     0          19m   10.233.1.19     k8s-worker0   <none>           <none>
rook-ceph-osd-3-5ccd458887-z6p4f                        2/2     Running     0          19m   10.233.1.14     k8s-worker0   <none>           <none>
rook-ceph-osd-4-64d76799b-6mqd6                         2/2     Running     0          19m   10.233.1.15     k8s-worker0   <none>           <none>
rook-ceph-osd-5-7cf6f8448c-fqwt9                        2/2     Running     0          19m   10.233.1.13     k8s-worker0   <none>           <none>
rook-ceph-osd-6-5c88bfb9c6-xsstv                        2/2     Running     0          19m   10.233.1.9      k8s-worker0   <none>           <none>
rook-ceph-osd-7-6895c55bb9-4hfm7                        2/2     Running     0          19m   10.233.1.11     k8s-worker0   <none>           <none>
rook-ceph-osd-8-5b589f7ccd-hrb7f                        2/2     Running     0          19m   10.233.1.16     k8s-worker0   <none>           <none>
rook-ceph-osd-9-649b66d9df-752gz                        2/2     Running     0          19m   10.233.1.18     k8s-worker0   <none>           <none>
rook-ceph-osd-prepare-k8s-worker0-4mwp9                 0/1     Completed   0          20m   10.233.1.8      k8s-worker0   <none>           <none>
rook-ceph-tools-7f4d4cfb5d-xpqbg                        1/1     Running     0          35m   10.233.1.7      k8s-worker0   <none>           <none>
```

Error messages RBD.
```
MountVolume.MountDevice failed for volume "pvc-70469a1e-f9a0-4254-9231-8f37cdebf03f" : rpc error: code = Internal desc = rbd: map failed with error an error (exit status 2) occurred while running rbd args: [--id csi-rbd-node -m 10.43.206.139:3300 --keyfile=***stripped*** map ceph-block/csi-vol-d76a9432-5494-11ed-b6b4-921414c17b9f --device-type krbd --options noudev], rbd error output: 2022-10-25T18:47:19.398+0000 7fbec95b0380 1 -- 10.233.1.0:0/210330771 >> v2:10.43.206.139:3300/0 conn(0x5618cb7c0980 msgr2=0x5618cb7c0df0 secure :-1 s=STATE_CONNECTION_ESTABLISHED l=1).mark_down 2022-10-25T18:47:19.398+0000 7fbec95b0380 1 --2- 10.233.1.0:0/210330771 >> v2:10.43.206.139:3300/0 conn(0x5618cb7c0980 0x5618cb7c0df0 secure :-1 s=READY pgs=1075 cs=0 l=1 rev1=1 crypto rx=0x7fbeb800a440 tx=0x7fbeb80049c0 comp rx=0 tx=0).stop 2022-10-25T18:47:19.398+0000 7fbec95b0380 1
```

Error message CephFS
```
MountVolume.MountDevice failed for volume "pvc-cbad6e62-49be-4feb-886e-47b17f5356c7" : rpc error: code = Internal desc = an error (exit status 32) occurred while running mount args: [-t ceph 10.43.206.139:3300:/volumes/csi/csi-vol-d77241ee-5494-11ed-a5cd-7a3eb6bbec3a/570927b8-ed15-49a6-aa9d-d6081d39c0a6 /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/319bf46a5b7ced5757539cc0f021346e07f55daa46e57fc505cdbc5d051517d1/globalmount -o name=csi-cephfs-node,secretfile=/tmp/csi/keys/keyfile-1802976147,mds_namespace=ceph-filesystem,_netdev] stderr: unable to get monitor info from DNS SRV with service name: ceph-mon 2022-10-25T18:56:28.759+0000 7f05d006cf40 -1 failed for service _ceph-mon._tcp mount error: no mds server is up or the cluster is laggy
```
