### DISCUSSION TITLE
OSD Pods Failed to start (Error setting cgroup config for procHooks process)

### DISCUSSION THREAD

**Discussion by panteparak** [rook/rook#11200] [Q&A] [answered]
I have 1 control-plane and 1 storage node set up and trying to deploy RookCeph. However I'm stuck with this error when I reach OSD Deployment stage.

Other Pods including Operator are running fine without any problem. And there are no error logs within operator that is related to cgroup issue.

`Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "209715200000000": write /sys/fs/cgroup/cpu,cpuacct/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podaa0955ff_78a9_4999_b27b_9f70cde613a3.slice/cri-containerd-activate.scope/cpu.cfs_quota_us: invalid argument: unknown`

Not sure if this is related to k3s [removing](https://docs.k3s.io/storage) cephfs storage plugin or something else.

k3s: v1.25.2+k3s1
OS: Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-131-generic x86_64)
Rook: 1.10.4
Ceph: v17.2

Helm Yaml:

Operator
```
priorityClassName: storage-operator-tier

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
```

Ceph Cluster
```
operatorNamespace: rook-ceph

monitoring:
  enabled: false
  rulesNamespace: rook-ceph
configOverride: |
    [global]
    osd_pool_default_min_size = 1
    osd_pool_default_size = 1
    mon_warn_on_pool_no_redundancy = false

    [osd]
    osd osd_min_pg_log_entries = 50
    osd osd_max_pg_log_entries = 500
    osd_memory_target_autotune = true
    # osd_memory_target = 2G
    # autotune_memory_target_ratio = 0.7
    mds_cache_memory_limit = 2G
    osd_scrub_auto_repair = true

toolbox:
  enabled: true

cephClusterSpec:
  # disruptionManagement:
  #   manageMachineDisruptionBudgets: false
  #   managePodBudgets: false

  cephVersion:
    image: quay.io/ceph/ceph:v17.2
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: true
  continueUpgradeAfterChecksEvenIfNotHealthy: true
  
  priorityClassNames:
    mgr: storage-operator-tier
    mon: storage-agent-tier
    osd: storage-agent-tier
    rbdmirror: storage-agent-tier
  mon:
    count: 1
    allowMultiplePerNode: false

  mgr:
    count: 1
    modules:
    - name: pg_autoscaler
      enabled: true
  network:
    connections:
      encryption:
        enabled: false
      compression:
        enabled: true

  dashboard:
    enabled: true
    ssl: false

  resources:
    api:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    mgr:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    mon:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    osd:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "2000Mi"
        memory: "2G"

  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/storage-cluster
              operator: Exists
    mon:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
      # tolerations:
      # - effect: NoSchedule
      #   key: 
      #   operator: Exists
    mgr:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    config:
      osdsPerDevice: "2"
    nodes:
      - name: "k8s-worker0"
        devices:
          - name: "sdb"
          - name: "nvme0n1"
            config:
              osdsPerDevice: "4"
          - name: "nvme1n1"
            config:
              osdsPerDevice: "4"
cephBlockPools:
  - name: ceph-block
    spec:
      failureDomain: osd
      erasureCoded:
        dataChunks: 2
        codingChunks: 1
    storageClass:
      enabled: true
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      isDefault: true
      name: rook-ceph-block
      parameters:
        imageFormat: "2"
        imageFeatures: layering
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
        csi.storage.k8s.io/fstype: ext4

cephFileSystems:
  - name: ceph-filesystem
    spec:
      metadataPool:
        replicated:
          size: 1
          requireSafeReplicaSize: false
      dataPools:
      - name: cephfs-erasurecoded
        failureDomain: osd
        erasureCoded:
          dataChunks: 2
          codingChunks: 1
      preserveFilesystemOnDelete: true
      metadataServer:
        activeCount: 1
        activeStandby: true
    storageClass:
      name: rook-cephfs
      enabled: true
      reclaimPolicy: Delete
      parameters:
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
        csi.storage.k8s.io/fstype: ext4

cephObjectStores:
  - name: asia-southeast-1
    spec:
      metadataPool:
        replicated:
          size: 1
      dataPool:
        name: cephfs-erasurecoded
        failureDomain: osd
        erasureCoded:
          dataChunks: 2
          codingChunks: 1
          requireSafeReplicaSize: false
      gateway:
        instances: 1
        port: 80
        securePort: 443
        endpoint: 
        priorityClassName: storage-agent-tier
      healthCheck:
        bucket:
          disabled: false
          interval: 60s 
      preservePoolsOnDelete: true
    storageClass:
      enabled: true
      name: rook-ceph-bucket
      reclaimPolicy: Delete
      parameters:
        region: asia-southeast-1
        objectStoreNamespace: rook-ceph
```

**Comment by travisn** [comment, marked as answer]
To be clear, are you seeing the error in the osd prepare logs, or did the osd prepare jobs finish successfully, and this error is from the osd deployment pods? 

Does it make a difference if you remove the cpu and memory limits from the OSD pods? Though if the other pods are working with the limits, I don't see why the OSDs would be different this way. The error message just seems to indicate it's a problem with the cpu quota.

**Reply by panteparak** [reply]
hmmm why didn't I think of that. And you're right the unit of CPU quota limit is wrong. Should have been `m` not `Mi`
```
    osd:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "2000Mi"
        memory: "2G"
```
