### DISCUSSION TITLE
OSD Errors with bluefs _allocate unable to allocate 0x80000 on bdev 1

### DISCUSSION THREAD

**Discussion by erkerb4** [rook/rook#11340] [Q&A]
**Deviation from expected behavior:**
We have a three node cluster. All MONs, and MGRs are up and running, however two of the three OSDs are in CrashLoopBackOff state. One seems to be happily running, somehow.

We did NOT upgrade K8s, rook-ceph or any other component. 

For diagnosing purposes, I did disable daemonHealth,  livenessProbe and startupProbe checks for the OSDs.

**Expected behavior:**
All OSDs are happy and in Running State

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
<details>
  <summary>ClusterCR</summary>

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    allowUnsupported: false
    image: internal-repo.fabrikam.net:8080/ceph/ceph:v16.2.9
  cleanupPolicy:
    allowUninstallWithVolumes: false
    confirmation: ""
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  crashCollector:
    daysToRetain: 30
    disable: false
  dashboard:
    enabled: true
    ssl: false
    urlPrefix: /ceph-dashboard
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    manageMachineDisruptionBudgets: false
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
  external: {}
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: true
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mgr:
        disabled: false
      mon:
        disabled: false
      osd:
        disabled: true
    startupProbe:
      osd:
        disabled: true
  logCollector: {}
  mgr:
    allowMultiplePerNode: false
    count: 2
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    allowMultiplePerNode: false
    count: 3
  monitoring:
    enabled: true
  network:
    ipFamily: IPv4
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - storage-node
      tolerations:
      - key: storage-node
        operator: Exists
  priorityClassNames:
    mgr: system-cluster-critical
    mon: system-node-critical
    osd: system-node-critical
  removeOSDsIfOutAndSafeToRemove: false
  resources:
    cleanup:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 100Mi
    crashcollector:
      limits:
        cpu: 500m
        memory: 60Mi
      requests:
        cpu: 100m
        memory: 60Mi
    logcollector:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    mgr:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    mgr-sidecar:
      limits:
        cpu: 500m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 40Mi
    mon:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 1Gi
    osd:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 4Gi
    prepareosd:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 500m
        memory: 50Mi
  security:
    kms: {}
  skipUpgradeChecks: false
  storage:
    config:
      encryptedDevice: "true"
    devices:
    - name: sdc
    useAllDevices: false
    useAllNodes: true
  waitTimeoutForHealthyOSDInMinutes: 10
```
</details>

**Logs to submit**:

* OSD logs

<details>
  <summary>OSD Crash Logs Node 1</summary>

Entire Crash log - https://pastebin.com/AcxEJSPv

```

   -29> 2022-11-21T18:36:19.616+0000 7f28917c1200  4 rocksdb: [column_family.cc:555]    (skipping printing options)
   -28> 2022-11-21T18:36:19.664+0000 7f28917c1200  4 rocksdb: [version_set.cc:4568] Recovered from manifest file:db/MANIFEST-230668 succeeded,manifest_file_number is 230668, next_file_number is 279177, last_sequence is 36221432353, log_number is 279174,prev_log_number is 0,max_column_family is 11,min_log_number_to_keep is 0
   -27> 2022-11-21T18:36:19.664+0000 7f28917c1200  4 rocksdb: [version_set.cc:4577] Column family [default] (ID 0), log number is 279160
   -26> 2022-11-21T18:36:19.664+0000 7f28917c1200  4 rocksdb: [version_set.cc:4577] Column family [m-0] (ID 1), log number is 230658
   -25> 2022-11-21T18:36:19.664+0000 7f28917c1200  4 rocksdb: [version_set.cc:4577] Column family [m-1] (ID 2), log number is 230658
   -24> 2022-11-21T18:36:19.664+0000 7f28917c1200  4 rocksdb: [version_set.cc:4577] Column family [m-2] (ID 3), log number is 230658
   -23> 2022-11-21T18:36:19.664+0000 7f28917c1200  4 rocksdb: [version_set.cc:4577] Column family [p-0] (ID 4), log number is 279033
   -22> 2022-11-21T18:36:19.664+0000 7f28917c1200  4 rocksdb: [version_set.cc:4577] Column family [p-1] (ID 5), log number is 279169
   -21> 2022-11-21T18:36:19.664+0000 7f28917c1200  4 rocksdb: [version_set.cc:4577] Column family [p-2] (ID 6), log number is 279087
   -20> 2022-11-21T18:36:19.664+0000 7f28917c1200  4 rocksdb: [version_set.cc:4577] Column family [O-0] (ID 7), log number is 279151
   -19> 2022-11-21T18:36:19.664+0000 7f28917c1200  4 rocksdb: [version_set.cc:4577] Column family [O-1] (ID 8), log number is 279174
   -18> 2022-11-21T18:36:19.664+0000 7f28917c1200  4 rocksdb: [version_set.cc:4577] Column family [O-2] (ID 9), log number is 279164
   -17> 2022-11-21T18:36:19.664+0000 7f28917c1200  4 rocksdb: [version_set.cc:4577] Column family [L] (ID 10), log number is 279171
   -16> 2022-11-21T18:36:19.664+0000 7f28917c1200  4 rocksdb: [version_set.cc:4577] Column family [P] (ID 11), log number is 279158
   -15> 2022-11-21T18:36:19.666+0000 7f28917c1200  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1669055779666438, "job": 1, "event": "recovery_started", "log_files": [279151, 279156, 279158, 279160, 279164, 279169, 279171, 279174, 279176]}
   -14> 2022-11-21T18:36:19.666+0000 7f28917c1200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #279151 mode 2
   -13> 2022-11-21T18:36:19.739+0000 7f28917c1200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #279156 mode 2
   -12> 2022-11-21T18:36:19.764+0000 7f28917c1200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #279158 mode 2
   -11> 2022-11-21T18:36:19.975+0000 7f28917c1200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #279160 mode 2
   -10> 2022-11-21T18:36:20.015+0000 7f28917c1200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #279164 mode 2
    -9> 2022-11-21T18:36:20.100+0000 7f28917c1200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #279169 mode 2
    -8> 2022-11-21T18:36:21.029+0000 7f28917c1200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #279171 mode 2
    -7> 2022-11-21T18:36:21.618+0000 7f28917c1200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #279174 mode 2
    -6> 2022-11-21T18:36:22.039+0000 7f28917c1200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #279176 mode 2
    -5> 2022-11-21T18:36:22.039+0000 7f28917c1200  3 rocksdb: [le/block_based/filter_policy.cc:584] Using legacy Bloom filter with high (20) bits/key. Dramatic filter space and/or accuracy improvement is available with format_version>=5.

------> FOCUS END

    **-4> 2022-11-21T18:36:29.412+0000 7f28917c1200  1 bluefs _allocate unable to allocate 0x80000 on bdev 1, allocator name block, allocator type hybrid, capacity 0x3e7ec00000, block size 0x1000, free 0xe74879000, fragmentation 0.579653, allocated 0x0
    -3> 2022-11-21T18:36:29.412+0000 7f28917c1200 -1 bluefs _allocate allocation failed, needed 0x79be4**
    -2> 2022-11-21T18:36:29.412+0000 7f28917c1200 -1 bluefs _flush_range allocated: 0x6570000 offset: 0x65690e7 length: 0x80afd

------> FOCUS START 

    -1> 2022-11-21T18:36:29.432+0000 7f28917c1200 -1 /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.9/rpm/el8/BUILD/ceph-16.2.9/src/os/bluestore/BlueFS.cc: In function 'int BlueFS::_flush_range(BlueFS::FileWriter*, uint64_t, uint64_t)' thread 7f28917c1200 time 2022-11-21T18:36:29.413698+0000
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.9/rpm/el8/BUILD/ceph-16.2.9/src/os/bluestore/BlueFS.cc: 2768: ceph_abort_msg("bluefs enospc")

```

</details>

<details>
  <summary>OSD Crash Logs Node 2</summary>

Entire Crash log - https://pastebin.com/JtJ1f3cw

```
   -20> 2022-11-21T19:32:39.486+0000 7f7e734fe200  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1669059159487204, "job": 1, "event": "recovery_started", "log_files": [283806, 283808, 283810, 283812, 283816, 283818, 283820, 283824]}
   -19> 2022-11-21T19:32:39.486+0000 7f7e734fe200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #283806 mode 2
   -18> 2022-11-21T19:32:39.649+0000 7f7e734fe200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #283808 mode 2
   -17> 2022-11-21T19:32:39.802+0000 7f7e734fe200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #283810 mode 2
   -16> 2022-11-21T19:32:40.038+0000 7f7e734fe200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #283812 mode 2
   -15> 2022-11-21T19:32:40.227+0000 7f7e734fe200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #283816 mode 2
   -14> 2022-11-21T19:32:40.314+0000 7f7e734fe200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #283818 mode 2
   -13> 2022-11-21T19:32:41.281+0000 7f7e734fe200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #283820 mode 2
   -12> 2022-11-21T19:32:41.305+0000 7f7e734fe200  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #283824 mode 2
   -11> 2022-11-21T19:32:41.310+0000 7f7e734fe200  3 rocksdb: [le/block_based/filter_policy.cc:584] Using legacy Bloom filter with high (20) bits/key. Dramatic filter space and/or accuracy improvement is available with format_version>=5.
   -10> 2022-11-21T19:32:41.517+0000 7f7e734fe200  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1669059161517896, "cf_name": "default", "job": 1, "event": "table_file_creation", "file_number": 283825, "file_size": 1289577, "table_properties": {"data_size": 1109063, "index_size": 7941, "index_partitions": 0, "top_level_index_size": 0, "index_key_is_user_key": 0, "index_value_is_delta_encoded": 0, "filter_size": 171717, "raw_key_size": 1236061, "raw_average_key_size": 18, "raw_value_size": 197727, "raw_average_value_size": 2, "num_data_blocks": 272, "num_entries": 68670, "num_deletions": 56313, "num_merge_operands": 12279, "num_range_deletions": 0, "format_version": 0, "fixed_key_len": 0, "filter_policy": "rocksdb.BuiltinBloomFilter", "column_family_name": "default", "column_family_id": 0, "comparator": "leveldb.BytewiseComparator", "merge_operator": ".T:int64_array.b:bitwise_xor", "prefix_extractor_name": "nullptr", "property_collectors": "[]", "compression": "NoCompression", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=0; ", "creation_time": 1669059161, "oldest_key_time": 3, "file_creation_time": 0}}
    -9> 2022-11-21T19:32:41.525+0000 7f7e734fe200  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1669059161526020, "cf_name": "p-1", "job": 1, "event": "table_file_creation", "file_number": 283826, "file_size": 1480, "table_properties": {"data_size": 441, "index_size": 154, "index_partitions": 0, "top_level_index_size": 0, "index_key_is_user_key": 0, "index_value_is_delta_encoded": 0, "filter_size": 69, "raw_key_size": 249, "raw_average_key_size": 124, "raw_value_size": 194, "raw_average_value_size": 97, "num_data_blocks": 1, "num_entries": 2, "num_deletions": 0, "num_merge_operands": 0, "num_range_deletions": 0, "format_version": 0, "fixed_key_len": 0, "filter_policy": "rocksdb.BuiltinBloomFilter", "column_family_name": "p-1", "column_family_id": 5, "comparator": "leveldb.BytewiseComparator", "merge_operator": "nullptr", "prefix_extractor_name": "nullptr", "property_collectors": "[]", "compression": "NoCompression", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=0; ", "creation_time": 1669059161, "oldest_key_time": 3, "file_creation_time": 0}}
    -8> 2022-11-21T19:32:41.542+0000 7f7e734fe200  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1669059161543680, "cf_name": "O-0", "job": 1, "event": "table_file_creation", "file_number": 283827, "file_size": 99581, "table_properties": {"data_size": 95277, "index_size": 1874, "index_partitions": 0, "top_level_index_size": 0, "index_key_is_user_key": 0, "index_value_is_delta_encoded": 0, "filter_size": 1605, "raw_key_size": 53271, "raw_average_key_size": 83, "raw_value_size": 80007, "raw_average_value_size": 125, "num_data_blocks": 24, "num_entries": 637, "num_deletions": 517, "num_merge_operands": 0, "num_range_deletions": 0, "format_version": 0, "fixed_key_len": 0, "filter_policy": "rocksdb.BuiltinBloomFilter", "column_family_name": "O-0", "column_family_id": 7, "comparator": "leveldb.BytewiseComparator", "merge_operator": "nullptr", "prefix_extractor_name": "nullptr", "property_collectors": "[]", "compression": "NoCompression", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=0; ", "creation_time": 1669059161, "oldest_key_time": 3, "file_creation_time": 0}}
    -7> 2022-11-21T19:32:41.735+0000 7f7e734fe200  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1669059161736599, "cf_name": "O-1", "job": 1, "event": "table_file_creation", "file_number": 283828, "file_size": 1464227, "table_properties": {"data_size": 1375685, "index_size": 29914, "index_partitions": 0, "top_level_index_size": 0, "index_key_is_user_key": 0, "index_value_is_delta_encoded": 0, "filter_size": 57797, "raw_key_size": 1923987, "raw_average_key_size": 83, "raw_value_size": 917945, "raw_average_value_size": 39, "num_data_blocks": 338, "num_entries": 23068, "num_deletions": 21539, "num_merge_operands": 0, "num_range_deletions": 0, "format_version": 0, "fixed_key_len": 0, "filter_policy": "rocksdb.BuiltinBloomFilter", "column_family_name": "O-1", "column_family_id": 8, "comparator": "leveldb.BytewiseComparator", "merge_operator": "nullptr", "prefix_extractor_name": "nullptr", "property_collectors": "[]", "compression": "NoCompression", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=0; ", "creation_time": 1669059161, "oldest_key_time": 3, "file_creation_time": 0}}
    -6> 2022-11-21T19:32:41.862+0000 7f7e734fe200  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1669059161863237, "cf_name": "O-2", "job": 1, "event": "table_file_creation", "file_number": 283829, "file_size": 1155303, "table_properties": {"data_size": 1103999, "index_size": 24038, "index_partitions": 0, "top_level_index_size": 0, "index_key_is_user_key": 0, "index_value_is_delta_encoded": 0, "filter_size": 26437, "raw_key_size": 882627, "raw_average_key_size": 83, "raw_value_size": 875655, "raw_average_value_size": 83, "num_data_blocks": 270, "num_entries": 10529, "num_deletions": 9134, "num_merge_operands": 0, "num_range_deletions": 0, "format_version": 0, "fixed_key_len": 0, "filter_policy": "rocksdb.BuiltinBloomFilter", "column_family_name": "O-2", "column_family_id": 9, "comparator": "leveldb.BytewiseComparator", "merge_operator": "nullptr", "prefix_extractor_name": "nullptr", "property_collectors": "[]", "compression": "NoCompression", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=0; ", "creation_time": 1669059161, "oldest_key_time": 3, "file_creation_time": 0}}
    -5> 2022-11-21T19:32:41.896+0000 7f7e734fe200  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1669059161897166, "cf_name": "L", "job": 1, "event": "table_file_creation", "file_number": 283830, "file_size": 300143, "table_properties": {"data_size": 298036, "index_size": 962, "index_partitions": 0, "top_level_index_size": 0, "index_key_is_user_key": 0, "index_value_is_delta_encoded": 0, "filter_size": 325, "raw_key_size": 1312, "raw_average_key_size": 16, "raw_value_size": 296299, "raw_average_value_size": 3613, "num_data_blocks": 34, "num_entries": 82, "num_deletions": 48, "num_merge_operands": 0, "num_range_deletions": 0, "format_version": 0, "fixed_key_len": 0, "filter_policy": "rocksdb.BuiltinBloomFilter", "column_family_name": "L", "column_family_id": 10, "comparator": "leveldb.BytewiseComparator", "merge_operator": "nullptr", "prefix_extractor_name": "nullptr", "property_collectors": "[]", "compression": "NoCompression", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=0; ", "creation_time": 1669059161, "oldest_key_time": 3, "file_creation_time": 0}}
    -4> 2022-11-21T19:32:46.631+0000 7f7e734fe200  1 bluefs _allocate unable to allocate 0x80000 on bdev 1, allocator name block, allocator type hybrid, capacity 0x3e7ec00000, block size 0x1000, free 0xecef55000, fragmentation 0.58934, allocated 0x0
    -3> 2022-11-21T19:32:46.631+0000 7f7e734fe200 -1 bluefs _allocate allocation failed, needed 0x7b2d2
    -2> 2022-11-21T19:32:46.631+0000 7f7e734fe200 -1 bluefs _flush_range allocated: 0x27b0000 offset: 0x27aa4fb length: 0x80dd7
    -1> 2022-11-21T19:32:46.645+0000 7f7e734fe200 -1 /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.9/rpm/el8/BUILD/ceph-16.2.9/src/os/bluestore/BlueFS.cc: In function 'int BlueFS::_flush_range(BlueFS::FileWriter*, uint64_t, uint64_t)' thread 7f7e734fe200 time 2022-11-21T19:32:46.632559+0000
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.9/rpm/el8/BUILD/ceph-16.2.9/src/os/bluestore/BlueFS.cc: 2768: ceph_abort_msg("bluefs enospc")

```
</details>

**Cluster Status to submit**:

```
[rook@rook-ceph-tools-744cff9db7-vchhb /]$ ceph health
HEALTH_WARN 1 osds down; 1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set; 2 hosts (2 osds) down; Reduced data availability: 44 pgs inactive, 43 pgs down; Degraded data redundancy: 303/268731 objects degraded (0.113%), 21 pgs degraded, 22 pgs undersized; 42 daemons have recently crashed
```

**Environment**:
* OS (e.g. from /etc/os-release): 
CentOS Linux release 7.9.2009 (Core)

* Kernel (e.g. `uname -a`):
Linux 5.19.8-1.el7.elrepo.x86_64

* Cloud provider or hardware configuration: 
5 Worker Nodes (only 3 used for Rook-Ceph)
12 vCPU/24GB Memory 250GB OSD 

* Rook version (use `rook version` inside of a Rook Pod): 
rook: v1.9.5

* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 16.2.9 (4c3647a322c0ff5a1dd2344e039859dcbd28c830) pacific (stable)

* Kubernetes version (use `kubectl version`):
1.22.7

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Kubernetes Upstream/Vanilla

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
