### DISCUSSION TITLE
Can StorageClusters declare a deviceClass for CephBlockPools and CephFilesystems?

### DISCUSSION THREAD

**Discussion by johnsimcall** [rook/rook#11376] [Ideas]
Hi Rook! I've been having a great time using Rook to deploy Ceph (OpenShift Data Foundation) on my OpenShift cluster. But my servers have both SSDs and HDDs in them and Rook/ODF doesn't seem to deal with that combination very easily. My goal is to create two `StorageClasses`. One `StorageClass` that returns `PersistentVolumes` from an HDD-based RBD pool and another `StorageClass` that returns `PVs` from an NVMe-backed pool. I'd like to do the same kind of thing for CephFS. I want the CephFS metadata to land on NVMe disks, but the data can land on HDDs. (I don't need it to be super fast.)

I've got everything working by creating two of my own `CephBlockPools` after the `StorageCluster` gets created. But I have to set the `StorageCluster.spec.managedResources.CephBlockPool.reconcileStrategy` to `ignore` because I don't want the default `CephBlockPool` & `StorageClass` that randomly spread data across NVMe and HDD devices to be created. I also disable the default `CephFilesystem` for the same reason.

I wonder, has anybody thought about extending the `StorageCluster` resource to allow it to specify a `deviceClass` for the default `CephBlockPool`, `CephFilesystem.metadata` and `CephFilesystem.dataPools.[]` objects? Is this a good idea?

Here's an example of the resources I create to accomplish my goal in the mean time...

StorageCluster
```
---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  encryption:
    clusterWide: true   ### LUKS encrypt all the OSDs
  flexibleScaling: true ### allow scaling by node instead of by "rack" or by "zone"
  monDataDirHostPath: /var/lib/rook
  network:
    provider: multus
    selectors:
      public: openshift-storage/ocs-public
      cluster: openshift-storage/ocs-cluster
  storageDeviceSets:
  - name: nvme
    count: 6
    replica: 1
    deviceType: nvme
    dataPVCTemplate:
      spec:
        storageClassName: local-nvme
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 1
  - name: hdd
    count: 30
    replica: 1
    deviceType: hdd
    dataPVCTemplate:
      spec:
        storageClassName: local-hdd
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 1
  managedResources:
    cephBlockPools:
      reconcileStrategy: ignore  ###don't create the default CephBlockPool nor the RBD StorageClass
    cephFilesystems:
      reconcileStrategy: ignore  ###don't create the default CephFilesystem nor the CephFS StorageClass
  multiCloudGateway:
    dbStorageClassName: ocs-storagecluster-ceph-rbd-nvme
```

CephBlockPools
```
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ocs-storagecluster-cephblockpool-nvme
  namespace: openshift-storage
spec:
  deviceClass: nvme
  enableRBDStats: true
  failureDomain: rack
  replicated:
    replicasPerFailureDomain: 1
    size: 3

---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ocs-storagecluster-cephblockpool-hdd
  namespace: openshift-storage
spec:
  deviceClass: hdd
  enableRBDStats: true
  failureDomain: rack
  replicated:
    replicasPerFailureDomain: 1
    size: 3
```

CephFilesystem
```
---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: ocs-storagecluster-cephfilesystem
  namespace: openshift-storage
spec:
  dataPools:
  - deviceClass: hdd
    failureDomain: host
    replicated:
      replicasPerFailureDomain: 1
      size: 3
      targetSizeRatio: 0.49
    statusCheck:
      mirror: {}
  metadataPool:
    deviceClass: nvme
    failureDomain: host
    replicated:
      replicasPerFailureDomain: 1
      size: 3
  metadataServer:
    activeCount: 1
    activeStandby: true
    priorityClassName: openshift-user-critical
    placement: {}  # Should probably add this
    resources: {}  # Should probably also add this
```

StorageClasses
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    description: CephFS with metadata on NVMe and data on HDD
  name: ocs-storagecluster-cephfs
parameters:
  clusterID: openshift-storage
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: openshift-storage
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: openshift-storage
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: openshift-storage
  fsName: ocs-storagecluster-cephfilesystem
allowVolumeExpansion: true
provisioner: openshift-storage.cephfs.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    description: HDD - Provides RWO Filesystem volumes, and RWO and RWX Block volumes
  name: ocs-storagecluster-ceph-rbd-hdd
parameters:
  clusterID: openshift-storage
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: openshift-storage
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: openshift-storage
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: openshift-storage
  imageFeatures: layering
  imageFormat: "2"
  pool: ocs-storagecluster-cephblockpool-hdd
allowVolumeExpansion: true
provisioner: openshift-storage.rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    description: NVMe - Provides RWO Filesystem volumes, and RWO and RWX Block volumes
  name: ocs-storagecluster-ceph-rbd-nvme
parameters:
  clusterID: openshift-storage
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: openshift-storage
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: openshift-storage
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: openshift-storage
  imageFeatures: layering
  imageFormat: "2"
  pool: ocs-storagecluster-cephblockpool-nvme
allowVolumeExpansion: true
provisioner: openshift-storage.rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
