### DISCUSSION TITLE
Disaster Recovery: Reset ephemeral data on all nodes.

### DISCUSSION THREAD

**Discussion by reitermarkus** [rook/rook#11418] [Q&A]
On my Talos cluster, I accidentally did `talosctl reset --system-labels-to-wipe EPHEMERAL -e talos-cp-1` instead of `talosctl reset --system-labels-to-wipe EPHEMERAL -n talos-cp-1`, resulting in all nodes wiping their ephemeral data.

I managed to get the OSD pods to start again by manually importing the new auth keys for each one, but I am still faced with various errors:

- `ceph status` shows:
  ```
    cluster:
    id:     f10ee1a2-6ced-4938-b75e-47a0aace87a5
    health: HEALTH_WARN
            mons are allowing insecure global_id reclaim
            1 MDSs report slow metadata IOs
            1/3 mons down, quorum ag,ah
            Reduced data availability: 60 pgs inactive
            3 slow ops, oldest one blocked for 486 sec, daemons [mon.ag,mon.ah,mon.aj] have slow ops.
 
  services:
    mon: 3 daemons, quorum ag,ah (age 18s), out of quorum: aj
    mgr: a(active, since 8m), standbys: b
    mds: 1/1 daemons up, 1 standby
    osd: 3 osds: 0 up, 3 in (since 3h)
 
  data:
    volumes: 1/1 healthy
    pools:   11 pools, 60 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             60 unknown
  ```
- The operator shows:
  ```
  2022-12-11 23:53:31.550075 I | clusterdisruption-controller: all "host" failure domains: [talos-cp-1 talos-net1 talos-net2]. osd is down in failure domain: "". active node drains: false. pg health: "cluster is not fully clean. PGs: [{StateName:unknown Count:60}]"
  ```
  and
  ```
  2022-12-11 23:53:33.632056 E | ceph-block-pool-controller: failed to reconcile CephBlockPool "rook-ceph/ceph-blockpool". failed to create pool "ceph-blockpool".: failed to create pool "ceph-blockpool".: failed to initialize pool "ceph-blockpool" for RBD use. : signal: interrupt
  ```
- Dashboard shows:
  ```
  Bad Gateway
  ```
- Pods fail to mount volumes, e.g.
   ```
  Warning  FailedMount  14m (x54 over 113m)   kubelet  MountVolume.MountDevice failed for volume "pvc-1f463b30-963e-46f9-8aaa-9441498d9e45" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-203315f5-06ee-11ed-bd89-becd39ed1c71 already exists
  Warning  FailedMount  4m7s (x38 over 119m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data kube-api-access-mdpm9]: timed out waiting for the condition
   ```

Not sure how to proceed.
