### DISCUSSION TITLE
Can I add osd by use devices' UUID?

### DISCUSSION THREAD

**Discussion by mc956759** [rook/rook#11466] [Q&A]
As title described, can I create an osd by use devices' UUID. I just found path config in cluster.yaml, just like this:
# nodes:
    #   - name: "172.17.4.201"
    #     devices: # specific devices to use for storage can be specified for each node
    #       - name: "sdb"
    #       - name: "nvme01" # multiple osds can be created on high performance devices
    #         config:
    #           osdsPerDevice: "5"
And also, now ceph just support bluestore as storage engine, which ask unformatted devices. So does that mean there are no UUIDs before devices add osds?
If can't use UUID, how can I handle if devices' block_path changed after node restarted?
Thanks for any help!

**Comment by BlaineEXE** [comment]
Try using `fullPath: /dev/disk/by-uuid/...` instead of `name: ...`, and let us know if that works.

**Comment by microyahoo** [comment]
Hi @mc956759, you also can use `/dev/disk/by-path` like follows.
https://rook.io/docs/rook/v1.10/CRDs/Cluster/ceph-cluster-crd/#storage-selection-settings
```yaml
    storage:                                                                                                                                 
      nodes:                                                                                                                                 
      - devices:                                                                                                                             
        - name: /dev/disk/by-path/pci-0000:00:0b.0                    
        - name: /dev/disk/by-path/pci-0000:00:0d.0                                                                                           
        name: k3
        resources: {}                                                                                                                        
      - devices:   
        - name: /dev/disk/by-path/pci-0000:00:0d.0                                                                                           
        - name: /dev/disk/by-path/pci-0000:00:0b.0                    
        name: k2                                                      
        resources: {}                                                 
      - devices:                                                      
        - name: /dev/disk/by-path/pci-0000:00:0b.0                    
        - name: /dev/disk/by-path/pci-0000:00:0d.0                    
        name: k1       
        resources: {}                                                 
      useAllDevices: false
```
