### DISCUSSION TITLE
How to check that a node-level metadataDevice is configured?

### DISCUSSION THREAD

**Discussion by davidjsherman** [rook/rook#11489] [Q&A] [answered]
I have a cluster of Ceph nodes, each with multiple HDDs plus a single SSD that I want to use for metadata. I have successfully configured the v1.10.7 Helm charts for `rook-ceph` and `rook-ceph-cluster` using only the HDDs. I now want to tear down and rebuild the cluster to use the metadata devices. Following the [documentation](https://github.com/rook/rook/blob/f908bcdba2667ce62118a7eeb9124b7e87272f34/Documentation/CRDs/Cluster/ceph-cluster-crd.md) and https://github.com/rook/rook/issues/9430#issuecomment-994849335 I specify a node-level `metadataDevice` but I cannot find any evidence that it is being used by the OSDs.

```yaml
storage:
    config: null
    useAllDevices: false
    useAllNodes: false
    nodes:
      - name: ceph-0
        config:
          metadataDevice: /dev/disk/by-id/scsi-35000c500ec7bb927
        devices:
          - name: /dev/disk/by-id/scsi-35000c500e0eaa9a5
          - name: /dev/disk/by-id/scsi-35000c500e0e93e9f
```

The *prepare* pod identifies the metadata device as available and reports that *cephosd* skips it (correctly, because it is not on the filter list). However the device does not appear in the metadata for any OSD, nor does any `/var/lib/ceph/osd/` directory contain a `block.wal` or `block.db`. Am I looking in the right place?

Thanks in advance!
