### DISCUSSION TITLE
How to determine the number of `active MDS instances` and `mds_cache_memory_limit` ?

### DISCUSSION THREAD

**Discussion by microyahoo** [rook/rook#11590] [Q&A]
How to determine the number of `active MDS instances` and `mds_cache_memory_limit` according to the hardware environment? For example:
```
[root@node01 smd]# ceph -s
  cluster:
    id:     f7f1c8ba-f793-436b-bb73-0964108a30c1
    health: HEALTH_WARN
            Degraded data redundancy: 133291/824633738 objects degraded (0.016%), 1 pg degraded, 1 pg undersized

  services:
    mon: 3 daemons, quorum a,b,c (age 7d)
    mgr: a(active, since 6w), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 108 osds: 108 up (since 26h), 108 in (since 11w); 1 remapped pgs
    rgw: 9 daemons active (9 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   16 pools, 5553 pgs
    objects: 109.09M objects, 105 TiB
    usage:   184 TiB used, 664 TiB / 849 TiB avail
    pgs:     133291/824633738 objects degraded (0.016%)
             5551 active+clean
             1    active+clean+scrubbing+deep
             1    active+undersized+degraded+remapped+backfilling

  io:
    client:   38 MiB/s rd, 23 MiB/s wr, 12.54k op/s rd, 1.89k op/s wr
    recovery: 4.3 MiB/s, 5 objects/s

  progress:
    Global Recovery Event (6d)
      [===========================.] (remaining: 99s)
```
