### DISCUSSION TITLE
rook cluster gets deleted unintentionally

### DISCUSSION THREAD

**Discussion by gaord** [rook/rook#11821] [Q&A]
Hi,
osd disk and host data directory are kept well. Any suggestions for restoring the ceph cluster by rook?
I have recreated rook cluster but stuck in osd preparing job with the following log:

2023-03-02 03:36:44.568158 D | cephosd: {
"f0bf6de8-8702-4494-a956-af0cHi,
osd and host data dir are kept well. Any suggestions for restoring the ceph cluster by rook?
I have recreated rook cluster but stuck in osd preparing job with the following log:

2023-03-02 03:36:44.568158 D | cephosd: {
"f0bf6de8-8702-4494-a956-af0cd7900a4d": {
"ceph_fsid": "3f271841-6188-47c1-b3fd-90fd4f978c76",
"device": "/dev/sdc",
"osd_id": 0,
"osd_uuid": "f0bf6de8-8702-4494-a956-af0cd7900a4d",
"type": "bluestore"
}
}
2023-03-02 03:36:44.568245 I | cephosd: skipping osd.0: "f0bf6de8-8702-4494-a956-af0cd7900a4d" belonging to a different ceph cluster "3f271841-6188-47c1-b3fd-90fd4f978c76"
2023-03-02 03:36:44.568252 I | cephosd: 0 ceph-volume raw osd devices configured on this node

Thanks

**Comment by subhamkrai** [comment]
@gaord you can try https://rook.github.io/docs/rook/latest/Troubleshooting/disaster-recovery/#restoring-crds-after-deletion

**Reply by gaord** [reply]
Things get a bit worse, all stuff in common.yaml and crd.yaml get deleted. Any ideas on chance of restoring? Thanks for feedback.

**Reply by travisn** [reply]
- Is anything left in the rook namespace? 
   - Any pods, services, or any other resources?
   - Any secrets or configmaps? They should have had a finalizer that prevented their deletion. 
- Was the cephcluster CR restored after you followed the disaster recovery guide? 
- Try reading through the rest of the disaster recovery guide.

**Reply by gaord** [reply]
there was things protected by finalizer. Unfortunately they got wiped out as well. I managed to make the cluster running again with original osds by restoring secret rook-ceph-mon and other manual keyring manipulation. However, they are all in status down,in. Any chance to get them back?

**Reply by gaord** [reply]
osd log details is here:
https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/ZBNQIADW4XRM5Y5BJIOCKXMWFOGPMV2Y/

**Reply by gaord** [reply]
> * Is anything left in the rook namespace?
>   
>   * Any pods, services, or any other resources?
>   * Any secrets or configmaps? They should have had a finalizer that prevented their deletion.
> * Was the cephcluster CR restored after you followed the disaster recovery guide?
> * Try reading through the rest of the disaster recovery guide.

is there a way to designate the mon daemon id in cephcluster? It would be nice to let mon start as ID "k" instead of "a" by default, for sake of original mon data.
@travisn

**Reply by travisn** [reply]
The `maxMonID` controls the ID of the next mon that will be created. This is incremented whenever there is a mon failover. 
For example, in my test cluster with three mons, the maxMonID is 2.
```
% kubectl -n rook-ceph get cm rook-ceph-mon-endpoints -o yaml
apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"rook-ceph","monitors":["10.104.210.249:6789","10.100.108.105:6789","10.97.140.62:6789"],"namespace":""}]'
  data: b=10.104.210.249:6789,c=10.100.108.105:6789,a=10.97.140.62:6789
  mapping: '{"node":{"a":{"Name":"minikube","Hostname":"minikube","Address":"10.0.2.15"},"b":{"Name":"minikube","Hostname":"minikube","Address":"10.0.2.15"},"c":{"Name":"minikube","Hostname":"minikube","Address":"10.0.2.15"}}}'
  maxMonId: "2"
  outOfQuorum: ""
kind: ConfigMap
```

However, changing this to a later value is going to be difficult since the operator tries to reconcile it to be the value of the largest existing mon [here](https://github.com/rook/rook/blob/master/pkg/operator/ceph/controller/cluster_info.go#L310).
