### DISCUSSION TITLE
How to convert to helm deployment when using flux for CI/CD?

### DISCUSSION THREAD

**Discussion by 2fst4u** [rook/rook#11832] [Q&A]
I have found the relevant instructions for converting an existing cluster to a helm managed deployment [here](https://rook.io/docs/rook/latest/Helm-Charts/ceph-cluster-chart/#existing-clusters), but I use flux for CI/CD which presents some issues before I start.

The instructions state:

`Extract the spec section of your existing CephCluster CR and copy to the cephClusterSpec section in values-override.yaml.`

Which is easy enough. In flux I actually use their helm release method so my values go directly into my manifest for the relevant app. Copy these values in, that's easy enough. Then:

```
Add the following annotations and label to your existing CephCluster CR:

  annotations:
    meta.helm.sh/release-name: rook-ceph-cluster
    meta.helm.sh/release-namespace: rook-ceph
  labels:
    app.kubernetes.io/managed-by: Helm
```

Again easy enough. This makes the current deployment switch over to being managed by helm.

Then you install the helm chart as normal (which in my case just means adding it to my git repo).

But now here's the problem: my current deployment is already in my git repo. And flux is going to reconcile any changes to that existing deployment. So when I install the helm chart what is going to happen? Will flux flap between my old one and my new helm one? Will the helm chart even install if flux is also trying to reconcile the existing one I have in the repo? If I delete the existing deployment from my repo, flux will then delete that deployment from my cluster and break all my storage.

Any ideas or thoughts welcome please.
