### DISCUSSION TITLE
Ceph says "distribution is already perfect"  yet  Prometheus says "PGs are not balanced across OSDs"

### DISCUSSION THREAD

**Discussion by reefland** [rook/rook#11881] [Q&A]
I added 2 OSD's yesterday, and since then I've been getting alerts from Prometheus that OSDs are not balanced on one of the new OSDs added.  Rook-Ceph Chart: v1.11.1

Prometheus alert:
```
PGs are not balanced across OSDs 
OSD osd.7 on k3s04 deviates by more than 30% from average PG count.
```

Cluster is Healthy
```
ceph version
ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)

ceph status              
  cluster:
    id:     cb82340a-2eaf-4597-b83e-cc0e62a9d019
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum b,c,d (age 3d)
    mgr: b(active, since 3d), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 9 osds: 9 up (since 22h), 9 in (since 22h)
    rgw: 1 daemon active (1 hosts, 1 zones)
 
  data:
    volumes: 1/1 healthy
    pools:   12 pools, 193 pgs
    objects: 58.52k objects, 164 GiB
    usage:   453 GiB used, 6.2 TiB / 6.6 TiB avail
    pgs:     193 active+clean
 
  io:
    client:   1.2 KiB/s rd, 71 KiB/s wr, 2 op/s rd, 3 op/s wr
```

Status
```
OSD_STAT  USED     AVAIL    USED_RAW  TOTAL    HB_PEERS           PG_SUM  PRIMARY_PG_SUM
8          25 GiB  675 GiB    25 GiB  700 GiB  [0,1,2,3,4,5,6,7]      64              19
7          31 GiB  669 GiB    31 GiB  700 GiB  [0,1,2,3,4,5,6,8]      43              16
6          56 GiB  875 GiB    56 GiB  932 GiB  [0,1,2,3,4,5,7,8]      70              30
1          52 GiB  648 GiB    52 GiB  700 GiB  [0,2,3,4,5,6,7,8]      66              14
0          66 GiB  634 GiB    66 GiB  700 GiB  [1,2,3,4,5,6,7,8]      65              15
2          60 GiB  640 GiB    60 GiB  700 GiB  [0,1,3,4,5,6,7,8]      76              20
3          61 GiB  639 GiB    61 GiB  700 GiB  [0,1,2,4,5,6,7,8]      72              26
4          57 GiB  643 GiB    57 GiB  700 GiB  [0,1,2,3,5,6,7,8]      56              23
5          47 GiB  885 GiB    47 GiB  932 GiB  [0,1,2,3,4,6,7,8]      67              30
sum       454 GiB  6.2 TiB   454 GiB  6.6 TiB                                           
```

Balancer Status
```
ceph balancer status

{
    "active": true,
    "last_optimize_duration": "0:00:00.000761",
    "last_optimize_started": "Sun Mar 12 13:23:43 2023",
    "mode": "upmap",
    "optimize_result": "Unable to find further optimization, or pool(s) pg_num is decreasing, or distribution is already perfect",
    "plans": []
}
```

Balancer Mode
```
ceph config get mgr mgr/balancer/mode
upmap

ceph config get mgr mgr/balancer/active
true
```

Documentation for upmap states:
_In most cases, this distribution is “perfect,” which an equal number of PGs on each OSD (+/-1 PG, since they might not divide evenly)._

If these are supposed to be +/-1 PG they are not even close.  If the number of OSDs is too low to reach "perfect balance", I don't see anything in the documentation that even hints that could be a cause.

Not sure if relevant...
```
ceph config get osd osd_pool_default_pg_autoscale_mode
on
ceph config get mgr mgr/pg_autoscaler/noautoscale     
false
ceph config get mgr mgr/pg_autoscaler/threshold  
3.000000
ceph config get mgr mgr/pg_autoscaler/sleep_interval
60
```
In any event, I have Ceph saying everything is good. Yet status does not match documentation and Prometheus agrees OSDs are not balanced.   I'm not sure what I should do about it.
