### DISCUSSION TITLE
Migrating from deviceGroups with DB devices (multiple DB devices per OSD node)

### DISCUSSION THREAD

**Discussion by kyle-rf** [rook/rook#12049] [Q&A] [answered]
I have been stuck on 1.5 for a while now and I am not sure how to effectively migrate in place when using DB devices.  The `deviceGroups` configuration was incredibly simple and easy to use.

```
driveGroups:
    - name: nodes_by_hostname
      spec:
        data_devices:
          model: {{ ceph.data_devices }}
        db_devices:
          model: {{ ceph.db_devices }}
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/ceph-storage
                  operator: Exists
```

I see no way to specify devices by model name or to easily declare which disks are DB devices.  In my setup I think I would be able to set `useAllDevices: true`, since we use all available devices on specific nodes.  However, it isn't clear to me how I would be able declare which ones are DB devices.  

There is `metadataDevice`, but is that the same as `db_devices`? 
Does this parameter take regex matching? i.e. `/dev/nvme.*`

**Comment by travisn** [comment]
@kyle-rf I assume you are reviewing the [upgrade guide for migrating the drive groups](https://rook.github.io/docs/rook/v1.6/ceph-upgrade.html#migrate-the-drive-group-spec)? That said, I don't see anything specifically about OSDs that had metadata devices.
@BlaineEXE Any specific guidance around OSDs with db_devices? I believe that would just be the same as metadataDevice from Rook's perspective. And if those OSDs already exist, I would hope they could continue to exist since Rook makes every attempt possible to continue upgrading existing OSDs. Creation of new OSDs may require ensuring the metadataDevice setting is correct, but existing OSDs may not be affected during upgrade.

**Comment by kyle-rf** [comment]
Hi Travis

I read the migration guide, but it doesn't cover using DB/WAL devices.  I don't think the repo examples cover configuring a cluster with this feature either.  Based on that guide though, I removed `deviceGroups` and replaced with the following:

```
placement:
  osd:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
           - key: node-role.kubernetes.io/ceph-storage
              operator: Exists
storage:
  useAllNodes: false
  useAllDevices: true
  config:
    metadataDevice: "/dev/nvme.*"
  onlyApplyOSDPlacement: true
```
Which resulted in logs like this in the operator:

`op-osd: not updating OSD 22 on node "worker01". node no longer exists in the storage spec. if the user wishes to remove OSDs from the node, they must do so manually. Rook will not remove OSDs from nodes that are removed from the storage spec in order to prevent accidental data loss`

Once I explicitly added the storage nodes to `storage.nodes` did the rook version get updated for those pods.  Which contradicts my interpretation of that migration guide.  The guide's option `2.2` using node labels and `spec.placement.osd.nodeAffinity` could be used to tell the system which nodes to use for OSDs.  So I took that to mean that I wouldn't need to hardcode specific nodes into the CephCluster CRD, but it didn't workout that way.

**Reply by travisn** [reply]
If you're going to set the `nodeAffinity`, you'll also need to set `useAllNodes: true`. It won't actually use all nodes, but will use all nodes that match the node affinity.

The documentation isn't clear, but if you set `useAllNodes: false`, this means that the `nodes` section must be specified with the individual nodes.

**Reply by BlaineEXE** [reply]
I wonder if manually setting up some Local PVs (https://kubernetes.io/docs/concepts/storage/volumes/#local) would be a good way to migrate. 

I think the workflow would be something like:
1. create a local PV `local-pv-data-0-migrated` for a local data disk (e.g., /dev/disk/by-id/sdb)
   - call the storageClassName `migrated-data-0`
2. create a local PV `local-pv-meta-0-migrated` for the local meta partition (e.g., /dev/disk/by-id/nvme1p1) that goes with the data disk
   - call the storageClassName `migrated-meta-0`
3. Do steps 1 & 2 for all nodes you need to migrate OSDs for
4. Create storage classes `migrated-data-0` and `migrated-meta-0`
5. Configure a StorageClassDeviceSet in CephCluster that creates <number-of-nodes> OSDs across migration nodes
   - The data disk should be a PVC w/ storage class `migrated-data-0` for data and `migrated-meta-0` for metadata
6. OSD prepare jobs should hopefully discover that the disks already have valid OSDs on them and start using them
  - if not, we might consider if we can massage resources in the right way to use already-existing PVCs
  - or if it does work, then do the same for additional disks on each node, repeating steps 1-6 for a `migrated-data-1` OSD, then `migrated-data-2` OSD, etc. until all OSDs on each node are migrated

**Reply by kyle-rf** [reply]
> If you're going to set the `nodeAffinity`, you'll also need to set `useAllNodes: true`. It won't actually use all nodes, but will use all nodes that match the node affinity.
> 
> The documentation isn't clear, but if you set `useAllNodes: false`, this means that the `nodes` section must be specified with the individual nodes.

That makes a lot sense actually and I'm disappointed I didn't figure that out myself.  Thank you :)

**Comment by kyle-rf** [comment]
I was able to setup a test cluster to test a new rook-ceph deployment and `storage.config.metadataDevice` does not support specifying multiple db devices.  

Here is the error after deploying a fresh cluster without `deviceGroups`, and trying to specify multiple db devices, `metadataDevice: /dev/nvme.*`.
Error from osd-prepare pods:

```
2023-04-11 16:48:02.713658 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 /dev/sdh /dev/sdg /dev/nvme0n1 /dev/sda /dev/sdd /dev/sdf /dev/sdb /dev/sdc /dev/sde --db-devices /dev/nvme.* --report
2023-04-11 16:48:05.449247 D | exec:  stderr: lsblk: /dev/nvme.*: not a block device
2023-04-11 16:48:05.449394 D | exec:  stderr: blkid: error: /dev/nvme.*: No such file or directory
2023-04-11 16:48:05.449404 D | exec:  stderr: Unknown device, --name=, --path=, or absolute path in /dev/ or /sys expected.
2023-04-11 16:48:05.449413 D | exec: usage: ceph-volume lvm batch [-h] [--db-devices [DB_DEVICES [DB_DEVICES ...]]]
2023-04-11 16:48:05.449419 D | exec:                              [--wal-devices [WAL_DEVICES [WAL_DEVICES ...]]]
2023-04-11 16:48:05.449425 D | exec:                              [--journal-devices [JOURNAL_DEVICES [JOURNAL_DEVICES ...]]]
2023-04-11 16:48:05.449431 D | exec:                              [--auto] [--no-auto] [--bluestore] [--filestore]
2023-04-11 16:48:05.449437 D | exec:                              [--report] [--yes]
2023-04-11 16:48:05.449443 D | exec:                              [--format {json,json-pretty,pretty}] [--dmcrypt]
2023-04-11 16:48:05.449449 D | exec:                              [--crush-device-class CRUSH_DEVICE_CLASS]
2023-04-11 16:48:05.449454 D | exec:                              [--no-systemd]
2023-04-11 16:48:05.449460 D | exec:                              [--osds-per-device OSDS_PER_DEVICE]
2023-04-11 16:48:05.449467 D | exec:                              [--data-slots DATA_SLOTS]
2023-04-11 16:48:05.449472 D | exec:                              [--block-db-size BLOCK_DB_SIZE]
2023-04-11 16:48:05.449478 D | exec:                              [--block-db-slots BLOCK_DB_SLOTS]
2023-04-11 16:48:05.449484 D | exec:                              [--block-wal-size BLOCK_WAL_SIZE]
2023-04-11 16:48:05.449490 D | exec:                              [--block-wal-slots BLOCK_WAL_SLOTS]
2023-04-11 16:48:05.449496 D | exec:                              [--journal-size JOURNAL_SIZE]
2023-04-11 16:48:05.449501 D | exec:                              [--journal-slots JOURNAL_SLOTS] [--prepare]
2023-04-11 16:48:05.449507 D | exec:                              [--osd-ids [OSD_IDS [OSD_IDS ...]]]
2023-04-11 16:48:05.449513 D | exec:                              [DEVICES [DEVICES ...]]
2023-04-11 16:48:05.449518 D | exec: ceph-volume lvm batch: error: Unable to proceed with non-existing device: /dev/nvme.*
```

**Comment by kyle-rf** [comment]
Prior to the test in my previous post, I deployed the test cluster with the deviceGroups configuration migrated from deviceGroups went through a upgrade, and as @travisn mentioned it didn't appear to impact the existing OSDs.  

So I could technically move forward with upgrading, but when any of those drives fail I'm not sure I'll be able to perform any corrective/recovery actions via Rook.  Though to be honest I have not been in this situation yet so I have no idea what all would need to take place to recover drive failures even with my current configuration using `deviceGroups`.

**Comment by kyle-rf** [comment]
@BlaineEXE 
Thanks for your reply.  Sorry for the miscommunication.  I'll try to clarify my original post here. 

We're looking to upgrade our Rook Ceph v1.5 cluster in place.  Specifically, we're trying to figure out how to migrate our deprecated `CephCluster.spec.driveGroups` spec such that Rook replicates our existing configuration.  

Our existing Rook cluster separates the OSD RocksDBs onto NVMe disks via the `CephCluster.spec.driveGroups.db_devices` directive.  On each storage node, Rook provisioned an LVM VG on each NVMe disk, dividing the RocksDB LVs amongst said VGs.  

To replicate this, our first inclination was to try and use the `CephCluster.spec.storage.config.metadataDevice` directive, but this appears to only support a single block device or VG. 

We couldn't find anything in the [migration guide](https://rook.github.io/docs/rook/v1.6/ceph-upgrade.html#migrate-the-drive-group-spec) that accounts for our specific deployment scenario, so we're wondering if there is a workaround or override that will enable the latest version of Rook to maintain our existing VG layout configuration going forward.

**Reply by BlaineEXE** [reply, marked as answer]
Ah, yes, I forgot ceph-volume sets up drive groups with LVM. You will probably have to migrate your OSDs by deleting and re-creating them. 

In general, the method I suggested before is essentially what suggest I'd suggest for setting up multiple disks as database devices. IMO, it's easier to achieve a nuanced configuration using PVCs (Local PVs in your case) than with the normal storage config. Configuration is done with StorageClassDeviceSets and PVCs instead of specifying `/dev/disk/by-id/...` for each node.

The general process for the migration would be to do it one node at a time. 
1. Pick a node, down+out all OSDs there, and wait for the cluster to rebalance.
2. Purge all those OSDs afterwards.
3. On the node, zap all the disks, and create partitions on the metadata devices that are sized how you prefer. Consider leaving extra partitions for future expansion if it makes sense (something drive groups didn't do)
4. Create Local Persistent Volumes for the metadata partitions, and give those a StorageClass that makes sense (you can do separate ones for db and wal if you want, or just for one or the other)
5. Create Local Persistent Volumes for the data disks, and give those a different StorageClass
6. Re-create OSDs by creating a DriveGroup on the CephCluster storage spec for the node you just set up with the number of osds and present, and the right storage class config.

**Reply by kyle-rf** [reply]
Thanks @BlaineEXE, I'll start testing this now and report back when I've got a handle on it.

**Comment by kyle-rf** [comment]
@BlaineEXE Thank you! 
I was able to follow your steps and migrated the test cluster off of `CephCluster.spec.driveGroups`

A General summary:
I was able to teardown the OSDs one node at a time per the steps `BlaineEXE` outlined.

After `down+out` and purge of osds of a node: 
I created a VG on the NVMe and carved up the desired LVs.  Created several PersistentVolume resources per DB LV (1 per OSD device), e.g:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host01-ceph-db-1
spec:
  capacity:
    storage: 139.73Gi
  volumeMode: Block
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-db
  local:
    path: /dev/ceph-db-1/1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - host01
```

For each disk to be an OSD another PersistentVolume e.g:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host01-ceph-data-1
spec:
  capacity:
    storage: 3.64Ti
  volumeMode: Block
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-data
  local:
    path: /dev/disk/by-id/<some disk id>
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - host01
```

Storage Classes:

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-data
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
  name: ceph-db
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

For CephCluster I removed driveGroups and as I progressed through the nodes I added an additional definition to `CephCluster.spec.storage.storageClassDeviceSets`, e.g:

```
- count: 8
  name: host-1
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - host01
  portable: false
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3.64Ti
      storageClassName: ceph-data
      volumeMode: Block
  - metadata:
      name: metadata
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 139.73Gi
      storageClassName: ceph-db
      volumeMode: Block
```

**Comment by kyle-rf** [comment]
Thank you @travisn and @BlaineEXE for your time and help on this issue.

**Comment by kyle-rf** [comment]
This didn't go so well in Production.  We have next to nothing in the test cluster so it went off without a hitch.  However, we have ~300TBs in production.  Even adding the settings recommended here: [Add OSD Node](https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/2/html/administration_guide/adding_and_removing_osd_nodes#adding_a_node) and only adding a single OSD, there is cluster wide instability across the entire Kubernetes cluster.  The nodes themselves flap Ready/NotReady and of course pods subsequently are going up and down.

Currently down a ceph OSD node (the one taken down for driveGroups migration) 1/3 of the OSDs.  Lost a mon and the operator has spun up additional mons but hasn't been able to bring them in to the cluster.

We don't have any resource limits defined for any of the Rook/Ceph components, which is the only other thing at the moment I can think to mess with.

**Reply by kyle-rf** [reply]
Another thought is whether I can reduce the pool replication size to 2?  

Thinking that could enable the cluster to clear up and go to a healthy state, since there would be 2 replicas on the 2 hosts still in the cluster.  Then adding the migrated node and OSDs would be seen as expansion, rather than needing to recover to 3 replicas...?

With regard to the mons issues: I lost one to capacity issues and the others are all dangerously high.  I lost one, after I scaled it down and removed all the old mon folders from that host.  Went from 85% disk usage to 41%, but the remaining mon folder that I was expecting to come back up was still 190GB and the mon wasn't able to get back in quorum.  The others have continued to grow:

```
[WRN] MON_DISK_BIG: mons ia,m,r,t are using a lot of disk space
    mon.m is 236 GiB >= mon_data_size_warn (15 GiB)
    mon.r is 236 GiB >= mon_data_size_warn (15 GiB)
    mon.t is 235 GiB >= mon_data_size_warn (15 GiB)
    mon.ia is 235 GiB >= mon_data_size_warn (15 GiB)
[WRN] MON_DOWN: 1/5 mons down, quorum m,r,t,ia
```

I would try the `rook-ceph mons restore-quorum` command, if any of the remaining mons was not reporting this warning.

I am not an expert on Ceph, so I am hesitant to try anything new with the cluster in its current state.

**Reply by travisn** [reply]
Wow you have had a lot of mon failovers in that cluster if you're on `mon.ia`. Cleaning the hosts of the dead mons is certainly a good thing. 

What does `ceph status` show? One of the mons is out of quorum?

What version ceph do you have in production? I see there is a fix for large mon dbs [here](https://bugzilla.redhat.com/show_bug.cgi?id=1943357), which fix should be at least in pacific or newer. If you're still on rook 1.5, I'm guessing you're also stuck on an older version of ceph where this could hit. In one of the related comments, I'm seeing these details with a potential workaround to get the mon db size down:

"The mon store keeps growing in this case because the ingest rate of new cluster log messages (due to continuous slow request reporting from another [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1905339) exceeds the monitor's rate of deleting old messages. This deletion rate is currently throttled to a static value. In the short term, the customer can increase paxos_service_trim_max to avoid this problem. In past instances (see linked BZs) we increased this from the default of 500 to 5000 or 10000 to get the monitor back down to size."

**Reply by kyle-rf** [reply]
Yeah, the first attempt to bring in the node migrated off driveGroups, created cluster wide instability in Kubernetes.  We are not exactly sure how/why there was such an impact to the container runtime, but it made the K8s nodes got NotReady up and down.   This impacted mon pods and the operator kept replacing them.

We lost quorum after the mons filled up the host disks.  We were able to restore quorum with the rook-ceph plugin `kubectl rook-ceph mons restore-quorum m`.  We changed the replication size of replicated pools from 3 to 2 to improve recovery, in hopes that more pgs would get to active+clean to reduce the mons storage consumption, which it did.

### Ceph Status
```
  cluster:
    id:     cc1b6d98-5b75-4a4d-b735-5a54d0914c15
    health: HEALTH_WARN
            noout,nodeep-scrub flag(s) set
            Degraded data redundancy: 26394221/245011384 objects degraded (10.773%), 200 pgs degraded, 200 pgs undersized
            1041 pgs not deep-scrubbed in time
            485 pgs not scrubbed in time
            19 daemons have recently crashed
 
  services:
    mon: 3 daemons, quorum m,ii,ij (age 34m)
    mgr: a(active, since 2h)
    mds: cephfs:3 {0=cephfs-c=up:active,1=cephfs-b=up:active,2=cephfs-a=up:active} 3 up:standby-replay
    osd: 61 osds: 61 up (since 22m), 60 in (since 3h); 314 remapped pgs
         flags noout,nodeep-scrub
    rgw: 6 daemons active (ec.cfc.object.store.a, ec.cfc.object.store.b, ec.cfc.object.store.c, ec.cfc.object.store.d, ec.cfc.object.store.e, ec.cfc.object.store.f)
 
  task status:
 
  data:
    pools:   12 pools, 2090 pgs
    objects: 88.56M objects, 107 TiB
    usage:   215 TiB used, 362 TiB / 577 TiB avail
    pgs:     26394221/245011384 objects degraded (10.773%)
             41501792/245011384 objects misplaced (16.939%)
             1576 active+clean
             313  active+clean+remapped
             200  active+undersized+degraded
             1    active+remapped+backfilling
 
  io:
    client:   4.3 KiB/s rd, 5 op/s rd, 0 op/s wr
    recovery: 34 MiB/s, 8 objects/s
```

### Versions

Rook: 1.5
Ceph: 15.2.8 (Octopus)

We're waiting for recovery operations to complete currently.  Ultimately the primary issue is still in play.  We are unable to bring in the osds from the storage node that is migrated off of driveGroups configuration, without seemingly overloading the Ceph cluster and taking the Kubernetes cluster down with it.  The K8s nodes would flap NotReady, with logs in the kubelet about the "PLEG" not being healthy.  The host metrics seem to indicate that it is not CPU or Memory usage.

For context our cluster is 90 OSDs across three storage nodes.  So we have 30 OSDs we're trying to bring back in and even trying to just do one OSD at a time creates this situation I've described above.

**Reply by travisn** [reply]
With 30 OSDs per node, I imagine you're getting some pretty serious memory pressure which is causing the nodes to flap. How much memory per OSD do you have? Have you set [memory limits](https://rook.github.io/docs/rook/v1.5/ceph-cluster-crd.html#resource-requirementslimits) on the OSDs? 4GB memory per OSD is preferred, but depending on the memory available, how low would you need to go with 30 per node?

**Reply by kyle-rf** [reply]
We did not have any resource limits configured, but we do now.  We looked at our metrics around the outage and only the mgr pods had concerning memory usage.  They appeared to be using all available memory on the hosts (~200 - 500 GB) until the hosts went down.  The operator was re-creating them on additional hosts, which probably led to our Kubernetes outage. 

This is what we've now set our memory limits to, based on what we saw in metrics:

```
  resources:
    mgr:
      limits:
        memory: 128Gi
      requests:
        memory: 64Gi
    mon:
      limits:
        memory: 128Gi
      requests:
        memory: 64Gi
    osd:
      limits:
        memory: 12Gi
      requests:
        memory: 6Gi
    mds:
      limits:
        memory: 4Gi
      requests:
        memory: 2Gi
```

Our OSD limits may seem high, but each of our storage hosts have 754GBs of RAM and during normal operations we saw average consumption ~4 - 5 GB.

The cluster has recovered as best as it can.  Reducing our rbd and cephfs replicated pools from 2 to 3 helped quite a bit in getting storage usage from the mons under control, but we have an erasure coded pool of `2 - data, 1 - coding` that we can't shrink.  This is preventing us from getting the rest of our PGs into `active+clean`.

At this juncture we're unsure if we should try adding OSDs again with our new resource limits applied, or fallback to something like creating new pools.  Any suggestions would be greatly appreciated.  Thank you by the way for all your help so far.
