### DISCUSSION TITLE
Is journalling enabled?

### DISCUSSION THREAD

**Discussion by holmesb** [rook/rook#12126] [Q&A]
Hi,

Our cephcluster spec storage is simply:
```
spec:	  
  storage:
    useAllDevices: true
    useAllNodes: true	
```
in other words, we have not specified:
```
spec:
  storage:
    config:
      journalSizeMB: <some_mb>
```

What is the status of journalling? Enabled? All of our disks are NVMe SSDs so doubt it has any value if it is. Is there any command to check?

We have prometheus and `ceph_osd_op_w_latency_sum` is different from (much smaller than) `ceph_osd_apply_latency_ms` and `ceph_osd_commit_latency_ms` so my best guess is that it's enabled, since latter two pertain to the journaling process. I'm concerned that journalling is unecessarily enabled and causing high latency.

Cheers.
