### DISCUSSION TITLE
ReconcileFailed: failed to set size property to replicated pool "ceph-objectstore.rgw.buckets.data" to 2 (exit status 95)

### DISCUSSION THREAD

**Discussion by weeix** [rook/rook#12290] [Q&A] [answered]
**Update**: I think I must have made a mistake when I edited the `values-cluster.yaml` file and used `helm upgrade` instead of reinstalling the cluster. I will try to reinstall and report back.

Hi, I installed Rook Ceph using Helm Charts:

```bash
helm repo add rook-release https://charts.rook.io/release
helm install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph -f values-operator.yaml
helm install --create-namespace --namespace rook-ceph rook-ceph-cluster \
   --set operatorNamespace=rook-ceph rook-release/rook-ceph-cluster -f values-cluster.yaml
```

values-operator.yaml:

```yaml
enableDiscoveryDaemon: true
```

values-cluster.yaml:

```yaml
toolbox:
  enabled: true
  image: rook/ceph:v1.11.5
cephClusterSpec:
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "worker01.k8s.redacted"
        deviceFilter: "^sd."
        config:
          deviceClass: vsan
      - name: "worker02.k8s.redacted"
        deviceFilter: "^sd."
        config:
          deviceClass: vsan
      - name: "worker03.k8s.redacted"
        devicePathFilter: ^/dev/disk/by-id/dm-uuid-mpath-.*
        config:
          deviceClass: msa2040
      - name: "worker04.k8s.redacted"
        devicePathFilter: ^/dev/disk/by-id/dm-uuid-mpath-.*
        config:
          deviceClass: msa2040
      - name: "worker05.k8s.redacted"
        devicePathFilter: ^/dev/disk/by-id/dm-uuid-mpath-.*
        config:
          deviceClass: msa2040
cephBlockPools:
  - name: ceph-blockpool
    spec:
      deviceClass: msa2040
cephFileSystems:
  - name: ceph-filesystem
    spec:
      metadataPool:
        deviceClass: msa2040
      dataPools:
        - name: data0
          deviceClass: msa2040
cephObjectStores:
  - name: ceph-objectstore
    spec:
      metadataPool:
        deviceClass: vsan
        replicated:
          size: 2
      dataPool:
        erasureCoded:
          dataChunks: 0
          codingChunks: 0
        deviceClass: vsan
        replicated:
          size: 2
```

Everything seems to be fine. `ceph status` returned "health: HEALTH_OK":

```bash
$ ceph status
  cluster:
    id:     cfd*****-****-****-****-**********01
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 2w)
    mgr: a(active, since 7h), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 6 osds: 6 up (since 2w), 6 in (since 2w)
    rgw: 1 daemon active (1 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   12 pools, 185 pgs
    objects: 395 objects, 843 KiB
    usage:   4.2 GiB used, 25 TiB / 25 TiB avail
    pgs:     185 active+clean

  io:
    client:   4.8 KiB/s rd, 0 B/s wr, 5 op/s rd, 2 op/s wr
```

However, I got about 70+ ReconcileFailed warnings per day:

```
Events:
  Type     Reason           Age                     From                         Message
  ----     ------           ----                    ----                         -------
  Warning  ReconcileFailed  2m53s (x1147 over 15d)  rook-ceph-object-controller  failed to reconcile CephObjectStore "rook-ceph/ceph-objectstore". failed to create object store deployments: failed to create object pools: failed to create data pool: failed to create pool "ceph-objectstore.rgw.buckets.data": failed to set size property to replicated pool "ceph-objectstore.rgw.buckets.data" to 2: failed to set pool property "size" on pool "ceph-objectstore.rgw.buckets.data": exit status 95
```

Is there anything wrong about the Object Storage? How should I further troubleshoot this issue?

Thank you.

**Comment by travisn** [comment]
What does `ceph osd tree` show in the toolbox? Are there at least two OSDs on different nodes with the `vsan` deviceClass?

Any other details in the rook operator log besides that message? If not, see the output for this command in the toolbox: `ceph osd pool set <poolName> size 2`, where the poolName can be found by the rgw data pool with `ceph osd pool ls`

**Reply by weeix** [reply]
Thank you @travisn 

I used the `ceph osd pool set ceph-objectstore.rgw.buckets.data size 2` command in the toolbox as you suggested. However, the pool for `ceph-objectstore` is actually an erasure-coded pool, which cannot be resized. I think I must have made a mistake when I edited the `values-cluster.yaml` file and used `helm upgrade` instead of reinstalling the cluster. I will try to reinstall and report back.

**Comment by weeix** [comment, marked as answer]
I naively edited the `values-cluster.yaml` file, thinking that I could simply use `helm update` to update my release. However, I discovered that the CRDs were updated but the Ceph settings were not affected. I had to clean up and redeploy the `rook-ceph-cluster` Helm chart again. Additionally, I had to fill in all the details of the entries in the `cephBlockPools`, `cephFileSystems`, and `cephObjectStores` sections instead of partially editing the parts that I needed to change. This is my final `values-cluster.yaml`:

```yaml
toolbox:
  enabled: true
cephClusterSpec:
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "worker01.k8s.redacted"
        deviceFilter: "^sd."
        config:
          deviceClass: vsan
      - name: "worker02.k8s.redacted"
        deviceFilter: "^sd."
        config:
          deviceClass: vsan
      - name: "worker03.k8s.redacted"
        devicePathFilter: ^/dev/disk/by-id/dm-uuid-mpath-.*
        config:
          deviceClass: msa2040
      - name: "worker04.k8s.redacted"
        devicePathFilter: ^/dev/disk/by-id/dm-uuid-mpath-.*
        config:
          deviceClass: msa2040
      - name: "worker05.k8s.redacted"
        devicePathFilter: ^/dev/disk/by-id/dm-uuid-mpath-.*
        config:
          deviceClass: msa2040
cephBlockPools:
  - name: ceph-blockpool
    spec:
      failureDomain: host
      replicated:
        size: 3
      deviceClass: msa2040
    storageClass:
      enabled: true
      name: ceph-block
      isDefault: true
      parameters:
        imageFormat: "2"
        imageFeatures: layering
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/fstype: ext4
cephFileSystems:
  - name: ceph-filesystem
    spec:
      metadataPool:
        replicated:
          size: 3
        deviceClass: msa2040
      dataPools:
        - name: data0
          failureDomain: host
          replicated:
            size: 3
          deviceClass: msa2040
      metadataServer:
        activeCount: 1
        activeStandby: true
    storageClass:
      enabled: true
      isDefault: false
      name: ceph-filesystem
      pool: data0
      parameters:
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
        csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/fstype: ext4
cephObjectStores:
  - name: ceph-objectstore
    spec:
      metadataPool:
        failureDomain: host
        replicated:
          size: 2
        deviceClass: vsan
      dataPool:
        failureDomain: host
        replicated:
          size: 2
        deviceClass: vsan
      preservePoolsOnDelete: true
      gateway:
        port: 80
        instances: 1
    storageClass:
      enabled: true
      name: ceph-bucket
      parameters:
        region: us-east-1
```

I wonder if there is a way to partially override an array entry in `values.yaml` instead of completely replacing the entire entry like I did.
