### DISCUSSION TITLE
Mon pods have a hardcoded nodeselector. How do I get it to refresh?

### DISCUSSION THREAD

**Discussion by 2fst4u** [rook/rook#12292] [Q&A] [answered]
I have updated my placement settings for my mons to prefer my more powerful nodes, but schedule on my arm nodes if they absolutely must in order to maintain uptime.

My placement spec in `cluster.yaml` looks like this:

```
  placement:
    mon:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - amd64
```

I can see that the affinity applies to the pods, because they show the following while running:

```
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
        weight: 100

```

But when I delete the mon pods to force them to reschedule, they never schedule where I want them to in the affinity, they just schedule back where they were. When I drain the node one of the mons is on, the pod remains `pending` until it is uncordoned. When I describe the pod with `kubectl`, it shows the mons have a hardcoded node selector of the specific name of the respective pod they have been running on.

How do I get this node selector to go away, or get the operator to reschedule a completely new mon to get the affinity to apply?
