### DISCUSSION TITLE
No osd down, but the pg always need remapped?

### DISCUSSION THREAD

**Discussion by zhucan** [rook/rook#12332] [Q&A]
```
root@bd-node12:/# ceph -s 
  cluster:
    id:     f5cd43dc-d28c-4736-9cb2-4c230755e51e
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 27h)
    mgr: b(active, since 16h), standbys: a
    osd: 308 osds: 308 up (since 37m), 308 in (since 37m); 1 remapped pgs
    rgw: 14 daemons active (14 hosts, 1 zones)
 
  data:
    pools:   9 pools, 4449 pgs
    objects: 31.55M objects, 19 TiB
    usage:   25 TiB used, 2.0 PiB / 2.0 PiB avail
    pgs:     0.090% pgs not active
             2655/315377725 objects misplaced (0.001%)
             4442 active+clean
             4    peering
             2    active+remapped+backfilling
             1    active+clean+scrubbing+deep
 
  io:
    client:   2.0 MiB/s rd, 1.6 GiB/s wr, 2.88k op/s rd, 4.98k op/s wr
    recovery: 1.7 GiB/s, 2.79k objects/s
```

and print "0.090% pgs not active", why?
