### DISCUSSION TITLE
CephPGImbalance alert

### DISCUSSION THREAD

**Discussion by dyvol777** [rook/rook#13126] [General]
i have mixed ssd and hdd cluster, with mixed s3 store. ssd drives are 1tb and hdd are 4tb

```
cephObjectStores:
  - name: ceph-objectstore
    spec:
      metadataPool:
        failureDomain: host
        replicated:
          size: 3
        deviceClass: ssd
      dataPool:
        failureDomain: osd
        erasureCoded:
          dataChunks: 5
          codingChunks: 1
        deviceClass: hdd
```

in case of that, my osd have different number of pg (16 and 84 actually), CephPGImbalance alert is always firing. what is the best thing i can do with it? Maybe it should be some fixes on alert?
