### DISCUSSION TITLE
fail to get zone

### DISCUSSION THREAD

**Discussion by 13567436138** [rook/rook#13536] [Q&A]
```
2024-01-09 04:26:09.760101 E | ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/multisite-store". failed to create object store deployments: failed to configure multisite for object store: failed join ceph multisite in zone "zone-a": failed to get rgw zone: exit status 2
```

create by:
```
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: realm-a
  namespace: rook-ceph 
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: zonegroup-a
  namespace: rook-ceph 
spec:
  realm: realm-a
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: zone-a
  namespace: rook-ceph 
spec:
  zoneGroup: zonegroup-a
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
  dataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      compression_mode: none
  # recommended to set this value if ingress used for exposing rgw endpoints
  # customEndpoints:
  #   - "http://rgw-a.fqdn"
  #   - "http://rgw-b.fqdn"
  # if the pools need to be removed from backend enable following setting
  # preservePoolsOnDelete: false
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: multisite-store
  namespace: rook-ceph
spec:
  gateway:
    port: 80
    # securePort: 443
    instances: 1
  zone:
    name: zone-a
```
