### DISCUSSION TITLE
can not provide pv

### DISCUSSION THREAD

**Discussion by 13567436138** [rook/rook#13537] [Q&A]
sc-rook-ceph-delete-bucket.yaml

kubectl apply -f sc-rook-ceph-delete-bucket.yaml -n rook-ceph --kubeconfig ~/.kube/182config

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-delete-bucket
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: multisite-store
  objectStoreNamespace: rook-ceph 
  region: us-east-1

```

nginx-deploy-with-volume.yaml

kubectl apply -f nginx-deploy-with-volume.yaml -n default --kubeconfig ~/.kube/182config 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        persistentVolumeClaim:
          claimName: nginx-html-claim

```

pvc-html-object.yaml

kubectl apply -f pvc-html-object.yaml -n default --kubeconfig ~/.kube/182config 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-html-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-delete-bucket
```

```
root@karmada-02-a:~# kubectl describe pvc nginx-html-claim 
Name:          nginx-html-claim
Namespace:     default
StorageClass:  rook-ceph-delete-bucket
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rook-ceph.ceph.rook.io/bucket
               volume.kubernetes.io/storage-provisioner: rook-ceph.ceph.rook.io/bucket
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       nginx-deployment-68f8f7f9d9-s5s72
Events:
  Type    Reason                Age                   From                         Message
  ----    ------                ----                  ----                         -------
  Normal  ExternalProvisioning  4m39s (x42 over 14m)  persistentvolume-controller  Waiting for a volume to be created either by the external provisioner 'rook-ceph.ceph.rook.io/bucket' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
root@karmada-02-a:~# 
```
