### DISCUSSION TITLE
cephobjectstore endpoint is different from setting

### DISCUSSION THREAD

**Discussion by 13567436138** [rook/rook#13550] [Q&A]
```
status:
  endpoints:
    insecure:
    - http://rook-ceph-rgw-multisite-store.rook-ceph.svc:80
    secure: []
  info:
    endpoint: http://rook-ceph-rgw-multisite-store.rook-ceph.svc:80
  observedGeneration: 1
  phase: Ready
```

```
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: realm-a
  namespace: rook-ceph 
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: zonegroup-a
  namespace: rook-ceph 
spec:
  realm: realm-a
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: zone-a
  namespace: rook-ceph 
spec:
  zoneGroup: zonegroup-a
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
  dataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      compression_mode: none
  # recommended to set this value if ingress used for exposing rgw endpoints
  customEndpoints:
  - "http://rgw.example.com"
  #   - "http://rgw-b.fqdn"
  # if the pools need to be removed from backend enable following setting
  # preservePoolsOnDelete: false
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: multisite-store
  namespace: rook-ceph
spec:
  gateway:
    port: 80
    # securePort: 443
    instances: 1
  zone:
    name: zone-a
```
