### DISCUSSION TITLE
why delete rookctl command tool in rook-tools:master

### DISCUSSION THREAD

**Discussion by 13567436138** [rook/rook#13569] [Q&A] [answered]
```
apiVersion: v1
kind: Pod
metadata:
  name: rook-tools
  namespace: rook-ceph
spec:
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: rook-tools
    image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/toolbox:master
    imagePullPolicy: IfNotPresent
    env:
      - name: ROOK_ADMIN_SECRET
        valueFrom:
          secretKeyRef:
            name: rook-ceph-mon
            key: ceph-secret
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /dev
        name: dev
      - mountPath: /sys/bus
        name: sysbus
      - mountPath: /lib/modules
        name: libmodules
      - name: mon-endpoint-volume
        mountPath: /etc/rook
  hostNetwork: false
  volumes:
    - name: dev
      hostPath:
        path: /dev
    - name: sysbus
      hostPath:
        path: /sys/bus
    - name: libmodules
      hostPath:
        path: /lib/modules
    - name: mon-endpoint-volume
      configMap:
        name: rook-ceph-mon-endpoints
        items:
        - key: data
          path: mon-endpoints
```

root@rook-tools:/# rookctl
bash: rookctl: command not found
