### DISCUSSION TITLE
how to config pv yaml to make pv from one cluster to use in another cluster with the same data

### DISCUSSION THREAD

**Discussion by 13567436138** [rook/rook#13676] [Q&A] [answered]
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph.rbd.csi.ceph.com
    volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-rbd-provisioner
    volume.kubernetes.io/provisioner-deletion-secret-namespace: rook-ceph-external
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-d39014a2-189c-4733-9c0a-b481caa0a860
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: www-web-0
    namespace: default
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph-external
    driver: rook-ceph.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph-external
    volumeAttributes:
      clusterID: rook-ceph-external
      imageFeatures: layering
      imageFormat: "2"
      imageName: csi-vol-8338cc9e-e952-4882-8ca8-6d6716439e8d
      journalPool: replicapool
      pool: replicapool
      storage.kubernetes.io/csiProvisionerIdentity: 1706862929032-9981-rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-0012-rook-ceph-external-0000000000000002-8338cc9e-e952-4882-8ca8-6d6716439e8d
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ceph-rbd
  volumeMode: Filesystem
```

with above config,the pv create is different,no data.
I have a rook ceph cluster,and three member cluster using external mode to connect to ceph cluster
I want to use the same pv ,when sts failover to another cluster

**Comment by travisn** [comment]
Did you try the CSI topic to create a [Static PV](https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md)?

**Reply by 13567436138** [reply]
no，how

**Reply by 13567436138** [reply]
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-d39014a2-189c-4733-9c0a-b481caa0a860
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
  csi:
    driver: rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph-external
    volumeAttributes:
      clusterID: rook-ceph-external
      pool: replicapool
      staticVolume: "true"
      imageFeatures: "layering"
    # volumeHandle should be same as rbd image name
    volumeHandle: csi-vol-8338cc9e-e952-4882-8ca8-6d6716439e8d
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```

I created a static volume,but data is lost
