### DISCUSSION TITLE
how can I use pvc and volumeMode block,using minio directpv did not support.

### DISCUSSION THREAD

**Discussion by 13567436138** [rook/rook#13723] [Q&A] [answered]
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  finalizers:
  - cephcluster.ceph.rook.io
  name: rook-ceph
  namespace: rook-ceph
spec:
  annotations:
    mon:
      backup.velero.io/backup-volumes: ceph-daemon-data
    osd:
      backup.velero.io/backup-volumes: data-directpv
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.1
  cleanupPolicy:
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  crashCollector: {}
  csi:
    cephfs: {}
    readAffinity:
      enabled: false
  dashboard:
    enabled: true
    ssl: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  external: {}
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 1m0s
      status:
        interval: 1m0s
    livenessProbe:
      mgr: {}
      mon: {}
      osd: {}
    startupProbe:
      mgr: {}
      mon: {}
      osd: {}
  logCollector:
    enabled: true
    maxLogSize: 500M
    periodicity: daily
  mgr:
    count: 2
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    count: 3
    volumeClaimTemplate:
      metadata:
        name: mon-directpv
      spec:
        storageClassName: directpv-min-io
        resources:
          requests:
            storage: 10Gi
  monitoring: {}
  network:
    connections:
      compression: {}
      encryption: {}
    hostNetwork: true
    multiClusterService: {}
  priorityClassNames:
    mgr: system-cluster-critical
    mon: system-node-critical
    osd: system-node-critical
  security:
    keyRotation:
      enabled: false
    kms: {}
  storage:
    flappingRestartIntervalHours: 0
    store: {}
    useAllDevices: false
    useAllNodes: false
    nodes:
      - name: "worker-03"
        devices:
          - name: sde
        config:
          storeType: bluestore
          databaseSizeMB: "1024"
          journalSizeMB: "1024"
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 30Gi
              storageClassName: ""
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
    storageClassDeviceSets:
    - name: set1
      count: 8
      portable: false
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 20Gi
          storageClassName: directpv-min-io
          volumeMode: Filesystem
          accessModes:
            - ReadWriteOnce
      - metadata:
          name: metadata
        spec:
          resources:
            requests:
              storage: 5Gi
          storageClassName: directpv-min-io
          volumeMode: Filesystem
          accessModes:
            - ReadWriteOnce
      - metadata:
          name: wal
        spec:
          resources:
            requests:
              storage: 5Gi
          storageClassName: directpv-min-io
          volumeMode: Filesystem
          accessModes:
            - ReadWriteOnce
  waitTimeoutForHealthyOSDInMinutes: 10
```
