### DISCUSSION TITLE
Snapshotting CephFS not working

### DISCUSSION THREAD

**Discussion by LarsKumbier** [rook/rook#13964] [Q&A]
Hey everyone,
I'm currently working on backup and restore for a Rook Ceph installation. In order to have a minimal timeframe of changes within and between the 3 storage nodes, I'd like to snapshot the PVs.
I've worked through the CephFS [snapshotting documentation](https://rook.io/docs/rook/latest-release/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot/) and installed the CRDs for VolumeSnapshotClasses, VolumeSnapshotContents and VolumeSnapshots from the [Kubernetes CSI External Snapshotter Repo](https://github.com/kubernetes-csi/external-snapshotter/raw/master/client/config/crd/) and added the [Snapshotter RBAC and Controller](https://github.com/kubernetes-csi/external-snapshotter/raw/master/deploy/kubernetes/snapshot-controller/). 
Next, I've added the SnapshotClass, customized for my namespace:

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-cephfsplugin-snapclass
driver: rook-ceph-storage-standard.cephfs.csi.ceph.com # csi-provisioner-name
parameters:
  clusterID: rook-ceph-storage-standard # namespace:cluster
  csi.storage.k8s.io/snapshotter-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph-storage-standard # namespace:cluster
deletionPolicy: Delete
```

So far so good. But if I create a snapshot of some demo-PVC, it does not work. Example:

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lars-backup-claim
spec:
  storageClassName: storage-standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: lars-backup-snapshot
spec:
  volumeSnapshotClassName: csi-cephfsplugin-snapclass
  source:
    persistentVolumeClaimName: lars-backup-claim
```

The snapshot stays on NotReady, with the event store waiting for the CSI driver:

```
# kubectl get volumesnapshot lars-backup-snapshot
NAME                   READYTOUSE   SOURCEPVC           SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS                SNAPSHOTCONTENT                                    CREATIONTIME   AGE
lars-backup-snapshot   false        lars-backup-claim                                         csi-cephfsplugin-snapclass   snapcontent-b052fa6e-af84-40aa-ae9a-9126064f7b92                  17h

# kubectl describe volumesnapshot lars-backup-snapshot
Name:         lars-backup-snapshot
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2024-03-20T16:30:18Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
  Generation:        1
  Resource Version:  3536440
  UID:               b052fa6e-af84-40aa-ae9a-9126064f7b92
Spec:
  Source:
    Persistent Volume Claim Name:  lars-backup-claim
  Volume Snapshot Class Name:      csi-cephfsplugin-snapclass
Status:
  Bound Volume Snapshot Content Name:  snapcontent-b052fa6e-af84-40aa-ae9a-9126064f7b92
  Ready To Use:                        false
Events:                                <none>
```

I've attached the [cephfs-provisioner log](https://github.com/rook/rook/files/14693044/leader.log), where I can see a lot being done, but no warnings or errors.

I've double-checked that the provisioner-secret is correctly found (by putting in a typo and seeing an appropriate error message in the provisioner log). Beside that, I'm unsure how to proceed debugging this issue.

Any help appreciated.
