### DISCUSSION TITLE
Pool only using one OSD per host

### DISCUSSION THREAD

**Discussion by NullOranje** [rook/rook#14188] [Q&A]
I'm trying to setup a simple Ceph cluster using Rook .  There are three hosts, with four disks per host.  I create a `CephBlockPool` and storage class.

```yaml
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
  metadata:
    name: replicapool
    namespace: rook-ceph
  spec:
    replicated:
      size: 3
```

Everything seems to come up okay, and I'm seeing data replicated across hosts.  However, it appears that it only one OSD per host is being used; if I fill that OSD, it does not utilize any others. 

I'm new to Rook/Ceph, so I would expect to see it using all the OSDs per host to expand the storage.  Where am I going wrong?
