### DISCUSSION TITLE
Understanding Node Removal in Rook-Ceph Clusters

### DISCUSSION THREAD

**Discussion by takafumi-kataoka** [rook/rook#14351] [Q&A] [answered]
I'm lookin into how to delete a node from rook-ceph cluster.

I understood from [the document](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/#node-settings) that removing a node from a CephCluster CR will delete the OSD deployment and the OSDs, but am I misunderstanding this?

> When useAllNodes is set to false, Rook relies on the user to be explicit about when nodes are added to or removed from the Ceph cluster. Nodes are only added to the Ceph cluster if the node is added to the Ceph cluster resource. Similarly, nodes are only removed if the node is removed from the Ceph cluster resource.

When I tried this in my test environment, neither the OSD deployment nor the OSDs were deleted.
Then rook ceph operator output the following log:

```
not updating OSD 3 on node "k8s-4". node no longer exists in the storage spec. if the user wishes to remove OSDs from the node, they must do so manually. Rook will not remove OSDs from nodes that are removed from the storage spec in order to prevent accidental data loss
```

Do I need to delete it by following the instructions in [the document](https://rook.io/docs/rook/latest-release/Storage-Configuration/Advanced/ceph-osd-mgmt/#remove-an-osd), rather than just deleting it from CephCluster CR?

And if so, what exactly does the above document mean?

The storage setting in CephCluster CR I used is show below.
```
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: k8s-1
        devices:
          - name: "vdb"
      - name: k8s-2
        devices:
          - name: "vdb"
      - name: k8s-3
        devices:
          - name: "vdb"
      - name: k8s-4
        devices:
          - name: "vdb"
```
`kubectl -n rook-ceph edit cephcluster rook-ceph` and removed k8s-4.

OS: Ubuntu22.04
k8s: v1.28.10
Rook: v1.14.6
