### DISCUSSION TITLE
No osd and mgr pods are created

### DISCUSSION THREAD

**Discussion by portwatcher** [rook/rook#14364] [Q&A]
Now the cluster looks like this:
```
[root@master ~]# kubectl get pods -n rook-ceph
NAME                                            READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-8759s                          2/2     Running   0          21h
csi-cephfsplugin-cjqfv                          2/2     Running   0          21h
csi-cephfsplugin-jd6wx                          2/2     Running   0          21h
csi-cephfsplugin-provisioner-868bf46b56-kj5lk   5/5     Running   0          21h
csi-cephfsplugin-provisioner-868bf46b56-phn6t   5/5     Running   0          21h
csi-rbdplugin-l6twm                             2/2     Running   0          21h
csi-rbdplugin-mvl8x                             2/2     Running   0          21h
csi-rbdplugin-provisioner-d9b9d694c-5bdgl       5/5     Running   0          21h
csi-rbdplugin-provisioner-d9b9d694c-jvqrx       5/5     Running   0          21h
csi-rbdplugin-zj2hp                             2/2     Running   0          21h
rook-ceph-mon-a-6f8bf57b7c-xdztx                2/2     Running   0          21h
rook-ceph-mon-b-5df8c77fdf-lh767                2/2     Running   0          37m
rook-ceph-operator-589b5bb466-grhcq             1/1     Running   0          8d
```

This is my cluster.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph # namespace:cluster
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  waitTimeoutForHealthyOSDInMinutes: 10
  upgradeOSDRequiresHealthyPGs: false
  mon:
    count: 2
    allowMultiplePerNode: false
  mgr:
    count: 2
    allowMultiplePerNode: false
    modules:
      - name: rook
        enabled: true
  dashboard:
    enabled: true
    ssl: true
  monitoring:
    enabled: false
    metricsDisabled: false
  network:
    connections:
      encryption:
        enabled: false
      compression:
        enabled: false
      requireMsgr2: false
  crashCollector:
    disable: false
  logCollector:
    enabled: true
    periodicity: daily
    maxLogSize: 500M
  cleanupPolicy:
    confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
    allowUninstallWithVolumes: false
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: ceph
              operator: In
              values:
              - "true"
      tolerations:
      - key: ceph
        operator: Equal
        value: "true"
        effect: NoSchedule
  annotations: {}
  labels: {}
  resources: {}
  removeOSDsIfOutAndSafeToRemove: false
    priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
  storage:
    useAllNodes: false
    nodes:
    - name: storage0
      devices:
      - name: nvme0n1
    - name: storage1
      devices:
      - name: nvme0n1
    useAllDevices: false
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
  csi:
    readAffinity:
      enabled: false
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
    startupProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
```

I also tried the original cluster.yaml provided in `deploy/examples` with node affinity modified only, still same results.

Check prepare pods:

```
[root@master rook-ceph]# kubectl -n rook-ceph get pod -l app=rook-ceph-osd-prepare
No resources found in rook-ceph namespace.
```

Check operator logs:

```
[root@master rook-ceph]# kubectl -n rook-ceph logs -l app=rook-ceph-operator
2024-06-21 09:18:04.234080 I | op-mon: mons running: [b a c]
2024-06-21 09:18:24.375254 I | op-mon: mons running: [b a c]
2024-06-21 09:18:44.514085 I | op-mon: mons running: [b a c]
2024-06-21 09:19:04.652257 I | op-mon: mons running: [b a c]
2024-06-21 09:19:24.793402 I | op-mon: mons running: [b a c]
2024-06-21 09:19:44.934061 I | op-mon: mons running: [b a c]
2024-06-21 09:20:05.075952 I | op-mon: mons running: [b a c]
2024-06-21 09:20:25.213523 I | op-mon: mons running: [b a c]
2024-06-21 09:20:45.352963 I | op-mon: mons running: [b a c]
2024-06-21 09:21:05.502470 I | op-mon: mons running: [b a c]
```

check nodes:

```
[root@master rook-ceph]# kubectl get nodes
NAME       STATUS   ROLES           AGE   VERSION
master     Ready    control-plane   8d    v1.30.1
node0      Ready    <none>          8d    v1.30.1
node1      Ready    <none>          8d    v1.30.1
node2      Ready    <none>          8d    v1.30.1
storage0   Ready    <none>          8d    v1.30.2
storage1   Ready    <none>          8d    v1.30.2
```

check devices on nodes:

```
[root@storage0 ~]# lsblk -f
NAME        FSTYPE      LABEL UUID                                   MOUNTPOINT
sda
|-sda1      vfat              E4AC-48C6                              /boot/efi
|-sda2      xfs               ef9e9b03-a187-4546-a2ea-24819a6b8678   /boot
`-sda3      LVM2_member       zE64ux-Ryb6-yxMt-hDRv-DCf1-xNXF-fNUXlc
  |-cs-root xfs               7091ae6e-aa61-4e1a-bc0e-5f1581b92c55   /
  |-cs-swap swap              d0790e49-448e-4a93-b548-e823daf46cf1
  `-cs-home xfs               d9312ac2-1377-4ae3-a39e-6807f62b5482   /home
nvme0n1
```

👆 same on `storage1`

`lvm2` is installed on `storage0` and `storage1`

check taints

```
[root@master rook-ceph]# kubectl get nodes -o custom-columns=NAME:.metadata.name,TAINTS:.spec.taints
NAME       TAINTS
master     [map[effect:NoSchedule key:node-role.kubernetes.io/control-plane]]
node0      <none>
node1      <none>
node2      <none>
storage0   [map[effect:NoSchedule key:ceph value:true]]
storage1   [map[effect:NoSchedule key:ceph value:true]]
```

check with toolbox:

```
[root@master rook-ceph]# kubectl -n rook-ceph exec -it deploy/rook-ceph-tools -- bash
bash-4.4$ ceph status
^CCluster connection aborted
bash-4.4$ ceph osd status
^CCluster connection aborted
bash-4.4$ ceph df
^CCluster connection aborted
```

All commands just got stuck after I press Enter, I have to ctrl + c to cancel them
