### DISCUSSION TITLE
Mount single RBD Block on multiple nodes (Read-only)

### DISCUSSION THREAD

**Discussion by M-Gregoire** [rook/rook#14765] [Q&A] [answered]
Hello :wave: ,

Here is my use case: I want a pod to write some data to a Block storage, and multiple other pods, in different namespaces, to read the data from it.

The block is created with:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "rook-ceph"
      "pool": "slow-block"
      "staticVolume": "true"
      "imageFeatures": "layering"
      #mounter: rbd-nbd
    # volumeHandle should be same as rbd image name
    volumeHandle: static
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Block
```

This is then used with the following PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: write-static-pvc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # The volumeMode can be either `Filesystem` or `Block` if you are creating Filesystem PVC it should be `Filesystem`, if you are creating Block PV you need to change it to `Block`
  volumeMode: Block
  # volumeName should be same as PV name
  volumeName: static
```

This correctly creates a `static` block in which I could write some data. However, I failed to read it from other pods.
I've created a similar PV referencing to the same block:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: read-static-pv
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1Gi
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    fsType: ext4
    readOnly: true
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "rook-ceph"
      "pool": "slow-block"
      "staticVolume": "true"
      "imageFeatures": "layering"
      #mounter: rbd-nbd
    # volumeHandle should be same as rbd image name
    volumeHandle: static
  persistentVolumeReclaimPolicy: Retain
  # The volumeMode can be either `Filesystem` or `Block` if you are creating Filesystem PVC it should be `Filesystem`, if you are creating Block PV you need to change it to `Block`
  volumeMode: Block

```

And associated PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: read-static-pvc
spec:
  storageClassName: ""
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  # The volumeMode can be either `Filesystem` or `Block` if you are creating Filesystem PVC it should be `Filesystem`, if you are creating Block PV you need to change it to `Block`
  volumeMode: Block
  # volumeName should be same as PV name
  volumeName: read-static-pv
```

In my `deployment`, it's mounted with `readOnly: true` as well. The PVC correctly binds to the PV but the pod fails to start with:
```
│   Warning  FailedMount  34s (x13 over 11m)  kubelet            MountVolume.MountDevice failed for volume "read-static-pv" : rpc error: code = Internal desc = mount failed: exit status 32              │
│ Mounting command: mount                                                                                                                                                                                           │
│ Mounting arguments: -t ext4 -o _netdev,ro,defaults /dev/rbd0 /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com/<uid>/globalmount/static                                                                                                                                                                                                         
│ Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com/<uid>/globalmount/static: cannot mount /dev/rbd0 read-only.   │

```

After some investigation, I discovered my Block had `exclusive-lock`, which I disabled, but this didn't solved the issue.

I have two questions: 
1. How to make it so the Block is created without `exclusive-lock` from the start so I don't have to manually remove it
2. Why cannot my volume be mounted as expected

Thank you for any help you might provide.
