### DISCUSSION TITLE
Migrate Pool to use SSD Devices

### DISCUSSION THREAD

**Discussion by denppa** [rook/rook#14852] [Q&A] [answered]
A pool was originally created without any specification of device types, but there is a need to convert this pool to use SSDs for faster random access. Editing the yaml directly does not seem to trigger a migration after reapplying the yaml.

Original:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - name: my_data
      deviceClass: ssd
      replicated:
        size: 3
      quotas:
        maxSize: 128Gi
  preserveFilesystemOnDelete: false
  metadataServer:
    activeCount: 1
    activeStandby: true
```

Added device type:
```yaml
spec:
  metadataPool:
    deviceClass: ssd
    replicated:
```

The new yaml is then applied like so:
```bash
kubectl -n rook-ceph apply -f myfs.yml
```

But upon inspecting the pool and the pgs inside, HDD OSDs are still being used.

Do I need to run a command via `kubectl rook-ceph ceph` in order to trigger the migration of placement groups?
