### DISCUSSION TITLE
Ceph capabilities for external clusters seem excessive

### DISCUSSION THREAD

**Discussion by SkalaNetworks** [rook/rook#15277] [General]
When using the python script to generate clients for external provisioning of storage, the capabilities seem way too open for me.

My use-case is the following:
- A central Rook cluster acts as a storage cluster
- Remote K8s clusters use that Rook cluster to provision their PVCs
- Each "client" cluster may or may not be operated by the operators of the Rook cluster, which means those clusters cannot be considered trusted. They need minimum capabilities to ensure an administrator of a client cluster cannot access/destroy the data of another client. Each client cluster has its own pool on the Rook cluster (could be a rados namespace too, not doing it right now)

The capabilities generated right now are the following (I'm only taking RBD as an example, I'm not too interested in CephFS but it also has pretty wide permissions, probably due to requirements of CephFS) for a pool named "local-block":
- For the provisionner that creates the PVCs on the remote Rook cluster:
```bash
ceph auth get-or-create client.csi-rbd-provisioner-testcluster-local-block mon profile rbd, allow command 'osd blocklist' mgr allow rw osd profile rbd pool=local-block
```
That "mgr allow rw" seems wild. OSDs are limited to their pool.

- For the "node" that mounts the PVCs from the remote Rook cluster:
```bash
ceph auth get-or-create client.csi-rbd-node-testcluster-local-block mon profile rbd, allow command 'osd blocklist' osd profile rbd pool=local-block
```

There's also the healthchecker account which has wide permissions over the cluster:
```bash
ceph auth get-or-create client.test mon allow r, allow command quorum_status, allow command version mgr allow command config osd profile rbd-read-only, allow rwx pool=default.rgw.meta, allow r pool=.rgw.root, allow rw pool=default.rgw.control, allow rx pool=default.rgw.log, allow x pool=default.rgw.buckets.index mds allow *
```

I managed to get everything to work by creating more limited permissions:
```yaml
---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: csi-rbd-node-testcluster-local-block
  namespace: testcluster
spec:
  caps: # I didn't change anything here, though I'm not sure what the blocklist is for
    mon: "profile rbd, allow command 'osd blocklist'"
    osd: "profile rbd pool=local-block"

---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: csi-rbd-provisioner-testcluster-local-block
  namespace: testcluster
spec:
  caps: # The provisioner doesn't seem to need unlimited permissions on the MGR, I limited it to the pool associated with the customer cluster
    mon: "profile rbd"
    mgr: "profile rbd pool=local-block"
    osd: "profile rbd pool=local-block"

---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: csi-health-testcluster
  namespace: testcluster
spec:
  caps:
    mon: "allow r, allow command quorum_status, allow command version" # That's what the rook-ceph-operator needs to probe the cluster and see if it's connected/healthy/has a version it can deploy a CSI for
```

Those decisions were based on this documentation from the ceph-csi project:
https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md

They clearly don't give as much permissions, but there's no reference to the healthchecker considering it's a Rook thing, so I improvised on that side by looking at what the operator was trying to do using the account its given.

What do you think of my usecase and the permissions I set? I am gonna encounter problems later down the road? Seems to me like the permissions given by the script are based on a usage where the client cluster might try to provision stuff on the Rook cluster remotely through CRDs, which is not what I want to do. I cannot trust users on the client clusters.

**Comment by BlaineEXE** [comment]
@parth-gr has done a lot of the provider/consumer cluster stuff and can probably explain why the permissions are needed and allowed. @Madhu-1 might have deeper insights into CSI's permissions.

@SkalaNetworks please provide the external script command you ran including args so we can look more closely. Obviously, please redact any sensitive data, but please include all flags. If this is a usage issue, we can follow up by improving documentation. 

In general, I have no reason to believe the permissions allow client users to read/write each other's data, or to interfere with the central (provider) Rook cluster. Downstream, we've done a lot of work and testing on these aspects. Parth will be able to help clarify whether certain config options are needed to ensure that.

`blocklist` is managed by CSI (via CSI addons) to handle node failure events, fencing them off with blocklists. If you aren't using CSI addons or node fencing, this permission is probably unnecessary. I don't suspect that it is a risk to leave as-is, however.

> The provisioner doesn't seem to need unlimited permissions on the MGR, I limited it to the pool associated with the customer cluster

If this is true for all cases, this seems like a good change to make in our external script to keep permissions as minimal as possible. We have strived to make sure the permissions truly are minimal as long as the limits don't break functions/features.

> There's also the healthchecker account which has wide permissions over the cluster:
> 
> ```
> ceph auth get-or-create client.test mon allow r, allow command quorum_status, allow command version mgr allow command config osd profile rbd-read-only, allow rwx pool=default.rgw.meta, allow r pool=.rgw.root, allow rw pool=default.rgw.control, allow rx pool=default.rgw.log, allow x pool=default.rgw.buckets.index mds allow *
> ```

My understanding has been that the health checker only has read permissions and should only have permissions to read pools (and pool namespaces) associated with the specific client cluster. I share some concerns that, at minimum, double checking these with the flags used is needed.

I'm particularly concerned about the write permissions here, like `rwx pool=default.rgw.meta`, `rw pool=default.rgw.control`. I can't currently imagine any reason why write permissions to RGW pools would be needed by the Rook operator.

`mds allow *` also looks concerning on the surface. I think this might be necessary for Rook to ensure CephFS filesystems are online, but a non-glob allow list would instill more confidence.

**Comment by SkalaNetworks** [comment]
Hi @BlaineEXE, thanks for the comment.

The ceph commands were generated using dry-mode (and I verified in non-drymode that it actually applied those permissions). I mounted the latest version of the python script inside the toolbox.

I ran this command (I insist on the fact this is only for RBD, I'm not even sure it's feasible to give restricted permissions to CephFS):
```bash
python3 create-external-cluster.py --namespace spx-storage --format bash --rbd-data-pool-name local-block --k8s-cluster testcluster --dry-run --restricted-auth-permission true
Execute: 'ceph fs ls'
Execute: 'ceph fsid'
Execute: 'ceph quorum_status'
Execute: 'ceph auth get-or-create client.healthchecker mon allow r, allow command quorum_status, allow command version mgr allow command config osd profile rbd-read-only, allow rwx pool=default.rgw.meta, allow r pool=.rgw.root, allow rw pool=default.rgw.control, allow rx pool=default.rgw.log, allow x pool=default.rgw.buckets.index mds allow *'
Execute: 'ceph mgr services'
Execute: 'ceph auth get-or-create client.csi-rbd-node-testcluster-local-block mon profile rbd, allow command 'osd blocklist' osd profile rbd pool=local-block'
Execute: 'ceph auth get-or-create client.csi-rbd-provisioner-testcluster-local-block mon profile rbd, allow command 'osd blocklist' mgr allow rw osd profile rbd pool=local-block'
Execute: 'ceph status'
export ARGS="[Configurations]
k8s-cluster-name = testcluster
namespace = spx-storage
rgw-pool-prefix = default
restricted-auth-permission = true
format = bash
rbd-data-pool-name = local-block
dry-run = True
"
export NAMESPACE=spx-storage
export ROOK_EXTERNAL_USERNAME=client.healthchecker
export RESTRICTED_AUTH_PERMISSION=true
export RBD_POOL_NAME=local-block
export RGW_POOL_PREFIX=default
```

I also just did a test of introducing rados namespaces into the mix and it seems to work, though it isn't very intuitive:
```yaml
---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: csi-rbd-node-spx-virt-local-block
  namespace: spx-storage
spec:
  caps:
    mon: "profile rbd, allow command 'osd blocklist'"
    osd: "profile rbd pool=local-block namespace=namespace-3"

---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: csi-rbd-provisioner-spx-virt-local-block
  namespace: spx-storage
spec:
  caps:
    mon: "profile rbd"
    mgr: "profile rbd pool=local-block namespace=namespace-3"
    osd: "profile rbd pool=local-block namespace=namespace-3"

---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: csi-health-spx-virt
  namespace: spx-storage
spec:
  caps:
    mon: "allow r, allow command quorum_status, allow command version"
 ```
 
 The capabilities are pretty straightforward, I introduce a NS in pool local-block, called "namespace-3", to check how it handled capabilities.
 
Now because of how the Ceph-CSI implemented rados namespaces, you need a different CSI config for each namespace, with a pseudo-random ID that is passed to the storageclass. The thing is, I tried to generate the radosnamespace on the rook cluster, and obviously that ID wasn't available in my client cluster. So you need to apply a Cephblockpoolradosnamespace CR on both the client and on the source cluster.
 
The one on the source cluster actually handles creating the rados namespace on the Rook cluster, while the one on the external cluster generates the configuration so that you can pass the ID in the storageclass. I don't know if the code detects that I'm doing it on the client cluster and doesn't try to create the namespace on the rook cluster, or if I simply locked down the capabilities enough to prevent the client cluster from remotely creating namespaces. But I'm happy that it cannot remotely create namespaces.

Also, the Ceph Operator (on the client cluster) tries to run a `ceph status` on the Rook cluster, sadly it "leaks" a bunch of information about filesystems in the fsMap, but I couldn't find a way to lock that down using capabilities.

> If this is true for all cases, this seems like a good change to make in our external script to keep permissions as minimal as possible. We have strived to make sure the permissions truly are minimal as long as the limits don't break functions/features.

To my knowledge, there's 2 main use cases to having external clusters configured in Rook:
1. Provisioning storage from a remote Ceph cluster (can be built using cephadm or Rook, doesn't matter that much)
2. Provisioning storage from a remote Ceph cluster AND administrating that cluster remotely (creating FS, RBD, users and more)

The permissions might include some capabilities necessary for that second use case? Mine is very much the first one, considering I don't want my end users to meddle with the Ceph cluster in any shape or form.

I'll keep running those capabilities for now, I tested resizing, deleting, provisioning, namespaces and they all work. Probably some tests needed regarding snapshots and recovering from snapshots, but considering the capabilities, I doubt it will fail.
