### DISCUSSION TITLE
Ceph fails to create OSD

### DISCUSSION THREAD

**Discussion by GoCodingIcreated** [rook/rook#15502] [General]
Hi everyone,
I'm new to Ceph and trying to set it up.
I deployed a helm chart with rook-ceph and rook-ceph-cluster.

I configured it to run on LV, but the creating of CephPool is failing, and I suspect it because of the disk (might be wrong though).

My disk looks like that
```
sdb                                   1T                        
└─sdb1                             1024G LVM2_member            reu1gD-W1p4-0Jz3-sluQ-9iVT-s0HS-VSpuo1
  ├─vvg_ampa9423_misc-data01--400g  400G                        
  └─vvg_ampa9423_misc-data02--128g  128G xfs         /data/128g ccee1c76-b132-4178-b44b-9844f8cf298e
```

I'm trying to use this one vvg_ampa9423_misc-data01--400g

with this configuration

```
cephClusterSpec:
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "10.92.130.71" #ampa9423
        devices: 
          - name: "/dev/vvg_ampa9423_misc/data01-400g"

```

The error that I'm getting is
```

  Warning  ReconcileFailed     8s (x13 over 3m45s)  rook-ceph-block-pool-controller  failed to reconcile CephBlockPool "rook-cep

h/ceph-blockpool-no-replica". failed to create pool "ceph-blockpool-no-replica".: failed to configure pool "ceph-blockpool-no-re

plica".: failed to initialize pool "ceph-blockpool-no-replica" for RBD use. : signal: interrupt
 
```

So, anybody has any idea why that happens and how I can debug this?
