### DISCUSSION TITLE
Externally Ceph FS mount Rook Ceph Cluster with `hostNetwork:true`

### DISCUSSION THREAD

**Discussion by ToolKami** [rook/rook#15611] [Q&A]
I am trying to Cephfs mount a cluster setup with Rook Ceph from an external instance which doesn't have access to the internal Kubernetes IP.

I have a Ceph Rook setup with `hostNetwork:true`.

I have verified each of those mon ports are accessible on each node:
```bash
ubuntu@instance:~$ nc -vz {external_ip_1} 6789
Connection to {external_ip_1} 6789 port [tcp/*] succeeded!
ubuntu@instance:~$ nc -vz {external_ip_2} 6789
Connection to {external_ip_2} 6789 port [tcp/*] succeeded!
ubuntu@instance:~$ nc -vz {external_ip_3} 6789
Connection to {external_ip_3} 6789 port [tcp/*] succeeded!
```

When I try to mount however:
```bash
ubuntu@instance-1:~$ sudo mount \
    -vvv \
    -t ceph \
    -o mds_namespace=myfs,name=admin,secret={secret} \
    {external_ip_1}:6789,{external_ip_2}:6789,{external_ip_3}:6789:/ mnt

mount: /home/ubuntu/mnt: mount(2) system call failed: No route to host.
       dmesg(1) may have more information after failed mount system call.
```

Have anyone tried a similar setup? Is it even possible? Thanks for having a look at this.

**Comment by travisn** [comment]
Try checking the [Ceph network config guide](https://docs.ceph.com/en/latest/rados/configuration/network-config-ref/) and confirm that you have all the needed port ranges open for connection to the mons and OSDs.

**Reply by ToolKami** [reply]
@travisn thanks for responding! Yes I've confirmed the following ports are opened for TCP:
```js
"8443",      # Ceph dashboard
"6800-7568", # https://docs.ceph.com/en/latest/rados/configuration/network-config-ref/
"3300",      # Ceph Monitor
"6789",      # Ceph Monitor fallback
```

To be more specific, I made only the following changes in the files from latest master (7908e52a415c3eb9f95f814966ee9c7b772b830f).

`deploy/examples/operator.yaml`:
```yaml
...
ROOK_ENABLE_DISCOVERY_DAEMON: "true"
...
ROOK_ENFORCE_HOST_NETWORK: "true"
...
spec:
  spec:
    containers:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
```

`deploy/examples/cluster.yaml`:
```yaml
...
provider: host
...
network:
  annotations:
    mon:
      network.rook.io/mon-ip: {external_ip_1},{external_ip_1},{external_ip_1}
...
```

I built the cluster fresh, is there anything else I could have possibly missed out on? Thanks for the help!
