### DISCUSSION TITLE
rgw metadata pool when using metadataDevice

### DISCUSSION THREAD

**Discussion by maxpain** [rook/rook#15672] [Q&A]
Hello. I've deployed Rook on HDD disks and used NVMe disks as `metadataDevice` for WAL and metadata, but the rgw metadata pool is created on HDD, not NVMe. Is this normal behavior? Does it mean all my RGW/S3 bucket metadata will be stored on HDD instead of NVMe? If so, how to fix it?

**Comment by travisn** [comment]
@maxpain When creating OSDs with the `metadataDevice`, every OSD will be faster in its metadata operations, as related to all pools. 

To store different pools on different types of devices, you'll need to create separate OSDs for each type of device, then configure the pools to use a particular set of OSDs. This is controlled with the `deviceClass` setting when creating the OSDs. Each OSD's device class can be seen in the output of ceph commands such as `ceph osd tree`. Then, when creating the pools set the `deviceClass` to the desired type. 

For example, the simplified CephObjectStore might look like this:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-store
  namespace: rook-ceph # namespace:cluster
spec:
  metadataPool:
    deviceClass: nvme
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
  dataPool:
    deviceClass: hdd
    failureDomain: host
    replicated:
      size: 3
  gateway:
    ...
```

If you have already created OSDs on all your devices, it would require wiping and starting over with the OSDs in this configuration. It's difficult to say if your current config or the new config would be more performant, it depends on your workload. One clear disadvantage of the `metadataDevice` is that the failure of that one device normally causes the loss of multiple OSDs that were sharing the same metadataDevice.
