### DISCUSSION TITLE
Specifying nodes and storage device filters without explicitly listing all nodes?

### DISCUSSION THREAD

**Discussion by edqallen** [rook/rook#15837] [Q&A]
I have series of SaaS/IaC scripts I use to spin up k8s clusters on our vmware cluster with little to no manual intervention.  The clusters typically have three controlplane nodes and three or more workers.  The names are predictable, but not static; for example if I tell it to create cluster "3" with 5 workers, it will make nodes named e.g. `c03-ctrl0[1-3]` and `c03-work0[1-4]`.  I've added a separate unpartitioned vmdk to each worker node as `/dev/sdb`.

I'd like to create a single `values.yaml` file that can properly deploy the cluster storage to just these worker nodes, using their names (and not their IPs as in the documentation example), using just `/dev/sdb` for storage.

I haven't been able to find a way to do this with the CRDs and I'm hoping it's not simply impossible.  I can probably alter the existing tooling I have (a mix of packer, terraform, and ansible) to create the `values.yaml` file when I spin up the cluster but I'm hoping to avoid that and just use a single fixed file.

If this is possible can someone provide an example of the correct way to the `cephClusterSpec/storage` block with `useAllNodes` and `useAllDevices` both false?  Or maybe with them set to true but using some sort of wildcard/regex?  I see that this is allowed when you specify each individual node but I'm trying to avoid that since the names and node count differ from one cluster to the next, though the naming pattern is always the same.

**Comment by travisn** [comment]
@edqallen Yes, you can do this without the `nodes` section. And anything you see in the `CephCluster` examples or documentation can be specified in the values.yaml under `cephClusterSpec`.

When using the `deviceFilter`, those first two settings actually need to be true:
```yaml
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: true
    deviceFilter: sdb # no need for the /dev/ prefix
```
Then if you want to filter out some nodes, either taint them, or you can specify `nodeAffinity` under the `placement.osd`, such as:
```yaml
   placement:
     osd:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: role
               operator: In
               values:
               - storage-node
```
See more about the deviceFilter and other storage settings in the [CephCluster CR topic](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/#storage-selection-settings).

**Reply by edqallen** [reply]
Thanks @travisn I'll give that a shot.  I've added some labels to the worker nodes with `kubectl label node c04-work01 node-role.kubernetes.io/storage=rook`.  What's supposed to be in the `values` tag here to limit the OSDs to just these nodes?  The example doesn't make it clear how to specify both the tag name (e.g. `storage`) and the value (`rook`)?

**Reply by travisn** [reply]
In my example, the label would be `role=storage-node`. For your values, I believe you want:
```yaml
             - key: node-role.kubernetes.io/storage
               operator: In
               values:
               - rook
```
edit: fixed the example label

**Comment by edqallen** [comment]
Hey @travisn I replied earlier to report that this isn't working and maybe my inexperience with this role/label aspect of k8s is to blame, but I deleted that response after noticing I'd forgotten to change `useAllNodes` and `useAllDevices` back to true.  I tore down the cluster and rebuilt it and then redeployed rook, but that apparently wasn't the problem.

My k8s nodes look good, but I admit I'm not really familiar with the role assignment stuff as I've never had to use it before:

```
c04-work01   Ready    storage         63m   v1.31.6   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=c04-work01,kubernetes.io/os=linux,node-role.kubernetes.io/storage=rook
c04-work02   Ready    storage         63m   v1.31.6   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=c04-work02,kubernetes.io/os=linux,node-role.kubernetes.io/storage=rook
c04-work03   Ready    storage         63m   v1.31.6   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=c04-work03,kubernetes.io/os=linux,node-role.kubernetes.io/storage=rook
```

And the relevant config section from the `values.yaml` is just as we discussed above:

```
  placement:
       osd:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: role.kuberneties.io/storage
                 operator: In
                 values:
                 - rook

  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: true
    deviceFiltere: sdb

```

Both the rook operator and cluster are installed via helm.

```
helm install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph -f rook_operator.yaml
helm install --create-namespace --namespace rook-ceph rook-ceph-cluster --set operatorNamespace=rook-ceph rook-release/rook-ceph-cluster -f rook-ceph-cluster.values.yaml

```

But `ceph status` still shows 0 osds:

```
ceph status
  cluster:
    id:     31ea9f1a-745d-4298-a45c-d51f8ccce713
    health: HEALTH_WARN
            clock skew detected on mon.b, mon.c
 
  services:
    mon: 3 daemons, quorum a,b,c (age 92s)
    mgr: a(active, since 27s), standbys: b
    osd: 0 osds: 0 up, 0 in
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     
```

I'm guessing the tagging still isn't quite right.  I'm going to tear it down again and try with your example to see if this is the issue or not, but any suggestions or pointers in the mean time would be appreciated.
