### DISCUSSION TITLE
waiting for a volume to be created, either by external provisioner "ceph.rook.io/block"

### DISCUSSION THREAD

**Discussion by rgstephens** [rook/rook#7614] [Q&A]
I'm new to Rook & Ceph and I followed the quickstart guide. The ceph status commands look good and I have the dashboard up and it looks good.

When I define a PVC the status stays `Pending` and I get the error message `waiting for a volume to be created, either by external provisioner "ceph.rook.io/block"`.

Here's an example PVC:

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-ceph-pvc2
  namespace: monitoring
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1M
```

I've looked at the `csi-rbdplugin-provsioner...` pods and see a message `CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments`. I also tried to run the `rbd status` command but I'm not clear what container I should be testing this in.
