### DISCUSSION TITLE
Why master node is not selected as OSD candidate?

### DISCUSSION THREAD

**Discussion by ccokee** [rook/rook#7795] [Q&A] [answered]
Hi, I have a raspberry pi cluster running k8s with rook. All the raspberrys have the same elements and specs. But surprisingly, only workers/nodes are selected as OSD candidate. Does anyone know why is this happening?

**Comment by travisn** [comment, marked as answer]
@ccokee To run on the master nodes, you need to add [tolerations](https://github.com/rook/rook/blob/release-1.6/cluster/examples/kubernetes/ceph/cluster.yaml#L150) such as the following to the CephCluster CR:
```
  placement:
    all:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
```
