### DISCUSSION TITLE
ceph: block device name change causes OSDs to crash loop and not update, workaround

### DISCUSSION THREAD

**Discussion by henryzhangsta** [rook/rook#7796] [General]
I have a cluster with a single node, with the following storage block:

```yaml
storage:
  useAllNodes: false
  useAllDevices: false
  deviceFilter: ""
  nodes:
    - name: "worker-nova"
      devices:
        - name: /dev/disk/by-id/scsi-SATA_WDC_WD30EFRX-68A_WD-WMC1T2181220
        - name: /dev/disk/by-id/scsi-SATA_WDC_WD30EFRX-68A_WD-WMC1T2195578
```

I was attaching 2 more disks to the machine, so followed the instructions in https://ceph.io/planet/how-to-do-a-ceph-cluster-maintenance-shutdown/ to shutdown Ceph, except setting replicas to 0 in pods vs stopping services. I started with the operator first. After turning off the host, attaching the disks, and rebooting, the OSD disks located at `/dev/sda` and `/dev/sdb` shifted to `/dev/sdc` and `/dev/sdd`. After starting the mon, mgr, and operator, I waited for prepare-node, and started the OSDs.

The OSDs were crash looping because the despite the devices in `nodes` using the disk ID, Rook translates these into the "real" device ID and sets the `ROOK_BLOCK_PATH` env var in the OSD deployment to these values. These values were `/dev/sda` and `/dev/sdb`. I had to set one of these to a working disk (changing the second OSD `/dev/sdb` to `/dev/sdd`), which caused the OSD to come back up. Rook was then able to update the other OSD and bring it up as well.

Not sure if this is a supported scenario, but maybe it would be possible to pass the disk-id of drives instead of the raw device?
