### DISCUSSION TITLE
S3 bucket failing to provision

### DISCUSSION THREAD

**Discussion by sjholden** [rook/rook#7937] [Q&A]
I have an install of rook-ceph-v1.6.1 and when trying to set up an s3 bucket it stays in Phase: Pending. And the operator logs:

```
E0518 17:14:56.159821       6 controller.go:199] error syncing 'rook-ceph/backups-bucket': error provisioning bucket: Provision: can't create ceph user: no user name provided and unable to generate a unique name: error getting ceph user "ceph-user-UFwG8h2N": radosgw-admin command err. ERROR: invalid flag --rgw-default-data-log-backing=omap: exit status 22, requeuing
```

Which seems a little like https://github.com/rook/rook/issues/7573 but I haven't done an upgrade.

I've tried to copy from https://github.com/rook/rook/blob/master/Documentation/ceph-object-bucket-claim.md (with names/etc tweaked). The CephObjectStore and StorageClass are:

```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: s3-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    replicated:
      size: 3
  preservePoolsOnDelete: true
  gateway:
    type: s3
    port: 80
    instances: 1
  healthCheck:
    bucket:
      disabled: false
      interval: 60s

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: s3-store-bucket
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: s3-store
  objectStoreNamespace: rook-ceph
  region: data-infra
```

And then the objectbucketclaim is:
```
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: backups-bucket
  namespace: rook-ceph
spec:
  generateBucketName: backups
  storageClassName: s3-store-bucket
  additionalConfig:
    maxSize: "100G"
```
From reading the issue above my suspicion is that the rook-ceph-operator thinks ceph is a newer version than it actually is? But I'm brand new at this and just guessing.

```
[root@rook-ceph-tools-5947b67d64-w67gc /]# ceph version
ceph version 15.2.11 (e3523634d9c2227df9af89a4eac33d16738c49cb) octopus (stable)
```

We use local copies of docker images, so one thought is are the comments in the values.yaml file are not the versions I should be using? I've set them in our values overrides to point a local docker repo. The stock comments are:

```
  #cephcsi:
    #image: quay.io/cephcsi/cephcsi:v3.3.1
  #registrar:
    #image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
  #provisioner:
    #image: k8s.gcr.io/sig-storage/csi-provisioner:v2.0.4
  #snapshotter:
    #image: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.2
  #attacher:
    #image: k8s.gcr.io/sig-storage/csi-attacher:v3.0.2
  #resizer:
    #image: k8s.gcr.io/sig-storage/csi-resizer:v1.0.1
```

A CephFilesystem and StorageClass are working fine also just copied from the docs. As is a CephBlockPool and StorageClass also copied from the docs. Both with similar name changes.
