### DISCUSSION TITLE
Bare-metal <-> AWS K8s cluster mirroring

### DISCUSSION THREAD

**Discussion by nikola-vortexwe** [rook/rook#8144] [Q&A]
Hi guys,
We are trying to mirror storage between two k8s clusters, one on bare-metal, and the other one on AWS. The approach that we're currently trying is to set up an external cluster on bare metal (and user that one as the master cluster), and install a local cluster inside the AWS (read-only). Is this the optimal approach for the problem, or should we look into something else? 

On the other hand, with the current setup we are currently facing an issue that one of the OSDs is reporting the following problem:
`_collect_metadata sdc:  no unique device id for sdc: fallback method has model 'Virtual disk    ' but no serial'`

The OSD keeps restarting after reporting the issue, and getting back to the up state. The following output is reported as well prior to the log entry mentioned before:
```
log_channel(cluster) log [WRN] : Monitor daemon marked osd.1 down, but it is still running
map e791 wrongly marked me down at e791
```

All three nodes are on identical VMs. This is the output of ceph -s:
```
cluster:
    id: 
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 4h)
    mgr: a(active, since 4h)
    osd: 3 osds: 3 up (since 14s), 3 in (since 4h)
 
  data:
    pools:   1 pools, 1 pgs
    objects: 0 objects, 0 B
    usage:   3.2 GiB used, 447 GiB / 450 GiB avail
    pgs:     1 active+clean+wait
```
 
Let me know if I can provide any further information. Thanks in advance!
