### DISCUSSION TITLE
Moving drive between nodes

### DISCUSSION THREAD

**Discussion by panteparak** [rook/rook#8755] [Q&A] [answered]
I have 2 NVME SSD installed in each of my two out of three nodes. And I would like to move it to a different node. Is there a way to do this? 

**Helm Chart Version:**
Operator: v1.7.3
RookCephCluster: v1.7.3

Goal: Move two `nvme0n1` currently presented on `k8s-node1`, `k8s-node2` to `k8s-node0`

Helm Values Files for RookCephCluster
```
configOverride: |
 [global]
 osd_pool_default_min_size = 1
 osd_pool_default_size = 1
 mon_warn_on_pool_no_redundancy = false

cephClusterSpec:
  cephVersion:
    image: ceph/ceph:v15.2.7
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: true
  continueUpgradeAfterChecksEvenIfNotHealthy: true
  
  monitoring:
    enabled: false
    rulesNamespace: rook-ceph
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true

  dashboard:
    enabled: true

  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    config:
      osdsPerDevice: "3"
    nodes:
      - name: "k8s-node1"
        devices:
          - name: "sda3"
          - name: "nvme0n1"
            config:
              osdsPerDevice: "4"
      - name: "k8s-node2"
        devices:
          - name: "sda3"
          - name: "nvme0n1"
            config:
              osdsPerDevice: "4"
      - name: "k8s-node0"
        devices:
          - name: "sda1"
            config:
              osdsPerDevice: "1"
```
