### DISCUSSION TITLE
CephFS mounted in a pod, not as a volume in the CephFS

### DISCUSSION THREAD

**Discussion by karlsabo** [rook/rook#9266] [Q&A] [answered]
I've got a rook CephFS that I can mount external to the cluster and view files, but when I create a StorageClass and PVC for a pod, I'm getting a volume that is created in the CephFS instead of getting the root CephFS itself mounted. E.g., in the CephFS I have a volumes directory with a csi volume for every pod.

Can anyone clarify for me what I should be creating to get the root of the CephFS mounted as a directory in my pod?

I appreciate any insight you can give me.

**Comment by karlsabo** [comment]
I got further today by using a CephFS volume and creating a secret in my namespace:

Secret:
```yaml
apiVersion: v1
data:
  userID: admin
  userKey: the-actual-token
kind: Secret
metadata:
  name: rook-ceph-admin-token
  namespace: default
type: Opaque
```

CephFS volume on pod:
```yaml
  volumes:
  - cephfs:
      monitors:
      - 10.1.2.3:6789
      secretRef:
        name: rook-ceph-admin-token
      user: admin
    name: testvname
```

Now I need to figure out how to reference the monitors in a better way.
