### DISCUSSION TITLE
Rook on CoreOS Typhoon Kubernetes

### DISCUSSION THREAD

**Discussion by sedlund** [rook/rook#9762] [Q&A] [answered]
I have a Typhoon Kubernetes cluster with latest Fedora CoreOS (kubelet in container), 3 OSD's (partitions on root disk).  Installed Rook (latest). Tried the storageclass.yaml and storageclass-ec.yaml and the pvc.yaml along with pod.yaml, and also pod-ephemeral.yaml.  Also tried the mysql.yaml + wordpress.yaml.

In all cases the RBD volumes were mounted to the container but are mode 777 owned by root/root but gives 'Permission denied' when trying to access the volumes.

Any ideas?

**Comment by Madhu-1** [comment]
@sedlund Have you tried using setting `SecurityContext` in the pod/deployment/container spec?

**Reply by sedlund** [reply]
I have tried spec.securityContext.setUser=0 spec.securityContext.fsGroup=0 with the same result.

**Reply by Madhu-1** [reply]
can you share the error message and the pod spec?

**Reply by sedlund** [reply]
```
kaf pod-ephemeral.yaml
pod/csi-rbd-demo-ephemeral-pod created

keti -n default csi-rbd-demo-ephemeral-pod -- bash

root@csi-rbd-demo-ephemeral-pod:/# df -h /myspace
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd0       976M  2.6M  958M   1% /myspace
root@csi-rbd-demo-ephemeral-pod:/# ls -ld /myspace
drwxrwxrwx. 3 root root 4096 Feb 17 15:27 /myspace
root@csi-rbd-demo-ephemeral-pod:/# ls -l /myspace
ls: cannot open directory '/myspace': Permission denied
root@csi-rbd-demo-ephemeral-pod:/#
```

```yaml
kgp -n default csi-rbd-demo-ephemeral-pod -o jsonpath='{.spec}' | jq

{
  "containers": [
    {
      "image": "docker.io/library/nginx:latest",
      "imagePullPolicy": "Always",
      "name": "web-server",
      "resources": {},
      "terminationMessagePath": "/dev/termination-log",
      "terminationMessagePolicy": "File",
      "volumeMounts": [
        {
          "mountPath": "/myspace",
          "name": "mypvc"
        },
        {
          "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
          "name": "kube-api-access-qg5pt",
          "readOnly": true
        }
      ]
    }
  ],
  "dnsPolicy": "ClusterFirst",
  "enableServiceLinks": true,
  "nodeName": "blah.host.com",
  "preemptionPolicy": "PreemptLowerPriority",
  "priority": 0,
  "restartPolicy": "Always",
  "schedulerName": "default-scheduler",
  "securityContext": {},
  "serviceAccount": "default",
  "serviceAccountName": "default",
  "terminationGracePeriodSeconds": 30,
  "tolerations": [
    {
      "effect": "NoExecute",
      "key": "node.kubernetes.io/not-ready",
      "operator": "Exists",
      "tolerationSeconds": 300
    },
    {
      "effect": "NoExecute",
      "key": "node.kubernetes.io/unreachable",
      "operator": "Exists",
      "tolerationSeconds": 300
    }
  ],
  "volumes": [
    {
      "ephemeral": {
        "volumeClaimTemplate": {
          "metadata": {
            "creationTimestamp": null
          },
          "spec": {
            "accessModes": [
              "ReadWriteOnce"
            ],
            "resources": {
              "requests": {
                "storage": "1Gi"
              }
            },
            "storageClassName": "rook-ceph-block",
            "volumeMode": "Filesystem"
          }
        }
      },
      "name": "mypvc"
    },
    {
      "name": "kube-api-access-qg5pt",
      "projected": {
        "defaultMode": 420,
        "sources": [
          {
            "serviceAccountToken": {
              "expirationSeconds": 3607,
              "path": "token"
            }
          },
          {
            "configMap": {
              "items": [
                {
                  "key": "ca.crt",
                  "path": "ca.crt"
                }
              ],
              "name": "kube-root-ca.crt"
            }
          },
          {
            "downwardAPI": {
              "items": [
                {
                  "fieldRef": {
                    "apiVersion": "v1",
                    "fieldPath": "metadata.namespace"
                  },
                  "path": "namespace"
                }
              ]
            }
          }
        ]
      }
    }
  ]
}
```
