### DISCUSSION TITLE
rbd snapshot count is non-zero, but snap list doesn't return anything?

### DISCUSSION THREAD

**Discussion by zestysoft** [rook/rook#9810] [Q&A] [answered]
`kubectl rook-ceph rbd info replicapool/csi-vol-0260041e-3449-11ec-87f2-42a41681ffea`
returns:
```
rbd image 'csi-vol-0260041e-3449-11ec-87f2-42a41681ffea':
        size 250 MiB in 63 objects
        order 22 (4 MiB objects)
        snapshot_count: 1
        id: 20d3499d873626
        block_name_prefix: rbd_data.20d3499d873626
        format: 2
        features: layering, operations
        op_features: clone-parent, snap-trash
        flags:
        create_timestamp: Sat Oct 23 21:34:32 2021
        access_timestamp: Sat Oct 23 21:34:32 2021
        modify_timestamp: Sat Oct 23 21:34:32 2021
```
however,
`kubectl rook-ceph rbd snap list replicapool/csi-vol-0260041e-3449-11ec-87f2-42a41681ffea`
doesn't return anything.

I have a few other images that also have non-zero snapshot counts, but none return results when I attempt to list the snapshots.   What am I doing wrong?

ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)
rook: v1.8.5
go: go1.16.13

`kubectl rook-ceph rbd snap purge replicapool/csi-vol-0260041e-3449-11ec-87f2-42a41681ffea` also did not change the count to 0.
