### DISCUSSION TITLE
Custom ceph.conf Settings

### DISCUSSION THREAD

**Discussion by df-bingo** [rook/rook#9864] [Q&A] [answered]
Modify the settings below and save 

kubectl -n rook-ceph edit configmap rook-config-override
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    osd crush update on start = false
    osd pool default size = 2
```
Then how to restart all daemon pod for the configuration to take effect
