### DISCUSSION TITLE
osd crashloopbakcoff always happens on the same server

### DISCUSSION THREAD

**Discussion by df-bingo** [rook/rook#9882] [Q&A]
osd crashloopbakcoff always happens on the same server, I didn't find anything abnormal about this server, all the resources are sufficient, and there are no obvious errors in the logs. I don't know where to start to troubleshoot.

```
kubectl -n rook-ceph describe pod rook-ceph-osd-57-6656d6d77-hx972 &> /tmp/rook-ceph-osd-57-6656d6d77-hx972.txt
kubectl -n rook-ceph logs rook-ceph-osd-57-6656d6d77-hx972 &> /tmp/rook-ceph-osd-57-6656d6d77-hx972.log
```
[rook-ceph-osd-57-6656d6d77-hx972.log](https://github.com/rook/rook/files/8221761/rook-ceph-osd-57-6656d6d77-hx972.log)
[rook-ceph-osd-57-6656d6d77-hx972.txt](https://github.com/rook/rook/files/8221764/rook-ceph-osd-57-6656d6d77-hx972.txt)

**Comment by travisn** [comment]
The issue is with the startup probe:
```
Startup probe failed: no valid command found; 10 closest matches:
```

Please try adjusting the settings on the probe, or else disable the probe as described in https://github.com/rook/rook/issues/9852#issuecomment-1063459959.

**Reply by df-bingo** [reply]
I adjusted the config file as follows, what is the difference between livenessProbe and startupProbe?
```
healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mgr:
        disabled: false
      mon:
        disabled: false
      osd:
        disabled: false
        probe:
          initialDelaySeconds: 3
          periodSeconds: 3
```

**Reply by df-bingo** [reply]
I disabled livenessProbe and startupProbe, the osd still down and out. Strangely it all happens on the same server.
![Screenshot from 2022-03-11 10-32-39](https://user-images.githubusercontent.com/84017898/157791906-485194fa-7cce-4db2-9e15-5f57381227f2.png)

The log of each osd is the same, as follows
[rook-ceph-osd-52-85d7dc6968-ln5jd.log](https://github.com/rook/rook/files/8228551/rook-ceph-osd-52-85d7dc6968-ln5jd.log)
[rook-ceph-osd-52-85d7dc6968-ln5jd.txt](https://github.com/rook/rook/files/8228553/rook-ceph-osd-52-85d7dc6968-ln5jd.txt)

**Reply by df-bingo** [reply]
Are the resources I configured enough? Each server has 512G of memory and 48 logical cpus
```
resources:
    crashcollector:
      limits:
        cpu: "1"
        memory: 150Mi
      requests:
        cpu: 500m
        memory: 60Mi
    mgr:
      limits:
        cpu: "1"
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi
    mgr-sidecar:
      limits:
        cpu: "1"
        memory: 100Mi
      requests:
        cpu: 500m
        memory: 40Mi
    mon:
      limits:
        cpu: "1"
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi
    osd:
      requests:
        cpu: 500m
        memory: 2048Mi
    prepareosd:
      limits:
        cpu: "1"
        memory: 120Mi
      requests:
        cpu: 500m
        memory: 50Mi
```
