### ISSUE TITLE
OSD created by wrong deviceClass

### ISSUE THREAD

**Issue by caffeinism** [rook/rook#10107]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Device class applied incorrectly in OSD.

**Expected behavior:**
OSD should be set automatically well or be configurable manually.

**How to reproduce it (minimal and precise):**

I have 3 machines with 4 SSDs and 4 NVMEs per machine, with the following settings:
```
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: storage-01
        config:
          metadataDevice: nvme0n1
        devices:
          - name: "sdb"
          - name: "sdc"
          - name: "sdd"
          - name: "sde"
          - name: "nvme0n1"
          - name: "nvme1n1"
          - name: "nvme2n1"
          - name: "nvme3n1"
      - name: storage-02 # same as storage-01
      - name: storage-03 # same as storage-01
```
Then osd tree was like this:
```
ID   CLASS  WEIGHT    TYPE NAME            STATUS  REWEIGHT  PRI-AFF
 -1         10.91560  root default
-10          3.63853      host storage-01
  2   ssh   0.51979          osd.2            up   1.00000  1.00000
  5   ssh   0.51979          osd.5            up   1.00000  1.00000
  8   ssh   0.51979          osd.8            up   1.00000  1.00000
 11   ssh   0.51979          osd.11           up   1.00000  1.00000
 14   ssh   0.51979          osd.14           up   1.00000  1.00000
 17   ssh   0.51979          osd.17           up   1.00000  1.00000
 20   ssh   0.51979          osd.20           up   1.00000  1.00000
 -4          3.63853      host storage-02
  1   ssh   0.51979          osd.1            up   1.00000  1.00000
  4   ssh   0.51979          osd.4            up   1.00000  1.00000
  7   ssh   0.51979          osd.7            up   1.00000  1.00000
 10   ssh   0.51979          osd.10           up   1.00000  1.00000
 12   ssh   0.51979          osd.12           up   1.00000  1.00000
 15   ssh   0.51979          osd.15           up   1.00000  1.00000
 18   ssh   0.51979          osd.18           up   1.00000  1.00000
 -7          3.63853      host storage-03
  0    nvme   0.51979          osd.0            up   1.00000  1.00000
  3    nvme   0.51979          osd.3            up   1.00000  1.00000
  6    nvme   0.51979          osd.6            up   1.00000  1.00000
  9    nvme   0.51979          osd.9            up   1.00000  1.00000
 13    nvme   0.51979          osd.13           up   1.00000  1.00000
 16    nvme   0.51979          osd.16           up   1.00000  1.00000
 19    nvme   0.51979          osd.19           up   1.00000  1.00000
```

So I changed the settings like this:
```
      - name: storage-01
        config:
          metadataDevice: nvme0n1
        devices:
          - name: "sdb"
            config:
              deviceClass: "ssd"
          - name: "sdc"
            config:
              deviceClass: "ssd"
          - name: "sdd"
            config:
              deviceClass: "ssd"
          - name: "sde"
            config:
              deviceClass: "ssd"
          - name: "nvme0n1"
            config:
              deviceClass: "nvme"
          - name: "nvme1n1"
            config:
              deviceClass: "nvme"
          - name: "nvme2n1"
            config:
              deviceClass: "nvme"
          - name: "nvme3n1"
            config:
              deviceClass: "nvme"
      - name: storage-02 # same as storage-01
      - name: storage-03 # same as storage-01
```
But the osd tree was still as follows.
```
ID   CLASS  WEIGHT    TYPE NAME            STATUS  REWEIGHT  PRI-AFF
 -1         10.91560  root default
-10          3.63853      host storage-01
  2   nvme   0.51979          osd.2            up   1.00000  1.00000
  5   nvme   0.51979          osd.5            up   1.00000  1.00000
  8   nvme   0.51979          osd.8            up   1.00000  1.00000
 11   nvme   0.51979          osd.11           up   1.00000  1.00000
 14   nvme   0.51979          osd.14           up   1.00000  1.00000
 17   nvme   0.51979          osd.17           up   1.00000  1.00000
 20   nvme   0.51979          osd.20           up   1.00000  1.00000
 -4          3.63853      host storage-02
  1   nvme   0.51979          osd.1            up   1.00000  1.00000
  4   nvme   0.51979          osd.4            up   1.00000  1.00000
  7   nvme   0.51979          osd.7            up   1.00000  1.00000
 10   nvme   0.51979          osd.10           up   1.00000  1.00000
 12   nvme   0.51979          osd.12           up   1.00000  1.00000
 15   nvme   0.51979          osd.15           up   1.00000  1.00000
 18   nvme   0.51979          osd.18           up   1.00000  1.00000
 -7          3.63853      host storage-03
  0    ssd   0.51979          osd.0            up   1.00000  1.00000
  3    ssd   0.51979          osd.3            up   1.00000  1.00000
  6    ssd   0.51979          osd.6            up   1.00000  1.00000
  9    ssd   0.51979          osd.9            up   1.00000  1.00000
 13    ssd   0.51979          osd.13           up   1.00000  1.00000
 16    ssd   0.51979          osd.16           up   1.00000  1.00000
 19    ssd   0.51979          osd.19           up   1.00000  1.00000
```

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 20.04 focal
* Kernel (e.g. `uname -a`): 5.4.0-107-generic
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.9.0
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)
* Kubernetes version (use `kubectl version`): 1.22.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): baremetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): Warn but its caused by this issue
