### ISSUE TITLE
mon entries in csi configmap is not updated for subvolume group/rados namespace in external cluster mode

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#10126]
The mon IP are updated only for the default cluster ID in case of the external mode and more subvolume groups created, Below is the configmap output.

```yaml
apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"rook-ceph","monitors":["10.0.161.89:6789","10.0.162.250:6789","10.0.163.112:6789"]},{"clusterID":"301f300cac48f552a5cd6b837c49d355","monitors":["10.0.163.80:6789"],"cephFS":{"subvolumeGroup":"cephfilesystemsubvolumegroup-storageconsumer-82b1ab88-29c0-4878-b572-fb4dda0623aa"}}]'
kind: ConfigMap
``` 

For cluster-ID `rook-ceph` we have all 3 monitors Rook reconciled but for the cluster-ID `301f300cac48f552a5cd6b837c49d355` we have only one Mon. Rook should update all the clusterID belonging to one ceph cluster with required mon information

AS discussed with @travisn below could be two possible approaches

```apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"rook-ceph","monitors":["10.0.161.89:6789","10.0.162.250:6789","10.0.163.112:6789"]},{"clusterID":"301f300cac48f552a5cd6b837c49d355","monitors":["10.0.163.80:6789"],"cephFS":{"subvolumeGroup":"cephfilesystemsubvolumegroup-storageconsumer-82b1ab88-29c0-4878-b572-fb4dda0623aa"}}]'
  clusterIDMappings:'[{"clusterID":"rook-ceph","cephFS":[{"subvolumeGroupName":"cephfilesystemsubvolumegroup-123"},{"subvolumeGroupName":"cephfilesystemsubvolumegroup-567"}],"rbd":[{"radosNamespace":"radosnamespace1234"},{"radosNamespace":"radosnamespace5678"}]}]'
kind: ConfigMap
```

or 
```
apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"rook-ceph","monitors":["10.0.161.89:6789","10.0.162.250:6789","10.0.163.112:6789"]},{"clusterID":"301f300cac48f552a5cd6b837c49d355","monitors":["10.0.163.80:6789"],"cephFS":{"subvolumeGroup":"cephfilesystemsubvolumegroup-storageconsumer-82b1ab88-29c0-4878-b572-fb4dda0623aa"}}]'
  clusterIDMappings:'[{"rook-ceph":["clusterID1","clusterID2","clusterID3"]},{"rook-ceph-external":["clusterID4","clusterID5","clusterID6"]}]'
kind: ConfigMap
```

with new empty in configmap clusterIDMappings we will have a mapping between clusterID's of subvolumegroups and rados namespaces to the namespace name of ceph cluster.
