### ISSUE TITLE
Mon not reaching quorum after uninstall/reinstall in k3s cluster with operator

### ISSUE THREAD

**Issue by TimothySutton81** [rook/rook#10178]
I have uninstalled rook-ceph and then attempt to reinstall from my k3s cluster. Some of the times this appears to work just fine with out issue other times it appears that my mon doesn't reach quorum. It seems similar to the issue that is being pointed to here https://rook.github.io/docs/rook/v1.9/ceph-common-issues.html#monitors-are-the-only-pods-running, but none of the things this is pointing at to check/fix seem to get me past this state. 

Version I am using t of rook is v1.7.2. 

k get pods -n rook-ceph
NAME                                            READY   STATUS    RESTARTS   AGE
rook-ceph-operator-67547964f9-tk4fd             1/1     Running   0          14m
csi-rbdplugin-4sdwl                             3/3     Running   0          14m
csi-rbdplugin-r8942                             3/3     Running   0          14m
csi-rbdplugin-968qd                             3/3     Running   0          14m
csi-rbdplugin-bxqh4                             3/3     Running   0          14m
csi-rbdplugin-provisioner-7cbf9798c-bw6dg       6/6     Running   0          14m
csi-rbdplugin-provisioner-7cbf9798c-p5m2p       6/6     Running   0          14m
csi-cephfsplugin-bq7pf                          3/3     Running   0          14m
csi-cephfsplugin-h9rkk                          3/3     Running   0          14m
csi-cephfsplugin-xbxgv                          3/3     Running   0          14m
csi-cephfsplugin-k76gn                          3/3     Running   0          14m
csi-cephfsplugin-provisioner-6d44f94dfd-rj755   6/6     Running   0          14m
csi-cephfsplugin-provisioner-6d44f94dfd-wcrld   6/6     Running   0          14m
rook-ceph-mon-a-66c5bb6fdc-wkm5p                1/1     Running   0          14m

 kubectl -n rook-ceph logs -l app=rook-ceph-operator
2022-04-27 14:33:47.136384 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2022-04-27 14:33:47.136842 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2022-04-27 14:33:47.556201 I | op-mon: deployment for mon rook-ceph-mon-a already exists. updating if needed
2022-04-27 14:33:47.573035 I | op-k8sutil: deployment "rook-ceph-mon-a" did not change, nothing to update
2022-04-27 14:33:47.573073 I | op-mon: waiting for mon quorum with [a]
2022-04-27 14:33:47.744849 I | op-mon: mons running: [a]
2022-04-27 14:33:50.278339 E | clusterdisruption-controller: failed to check cluster health: failed to get status. . 2022-04-27T14:33:50.272+0000 7f9fd3fff700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
[errno 13] RADOS permission denied (error connecting to the cluster): exit status 13
2022-04-27 14:33:52.938155 I | op-mon: mons running: [a]
2022-04-27 14:33:58.132390 I | op-mon: mons running: [a]

[vagrant@master rook-ceph-dep]$ kubectl -n rook-ceph exec deploy/rook-ceph-operator -- curl $(kubectl -n rook-ceph get svc -l app=rook-ceph-mon -o jsonpath='{.items[0].spec.clusterIP}'):3300 2>/dev/null
ceph v2

[vagrant@master rook-ceph-dep]$ kubectl -n rook-ceph get pod -l app=rook-ceph-mon
NAME                               READY   STATUS    RESTARTS   AGE
rook-ceph-mon-a-66c5bb6fdc-wkm5p   1/1     Running   0          12m

 kubectl -n rook-ceph describe pod -l app=rook-ceph-mon

Events:
  Type     Reason       Age   From               Message
  ----     ------       ----  ----               -------
  Normal   Scheduled    13m   default-scheduler  Successfully assigned rook-ceph/rook-ceph-mon-a-66c5bb6fdc-wkm5p to node01
  Warning  FailedMount  13m   kubelet            MountVolume.SetUp failed for volume "rook-config-override" : failed to sync configmap cache: timed out waiting for the condition
  Normal   Pulled       13m   kubelet            Container image "quay.io/ceph/ceph:v16" already present on machine
  Normal   Created      13m   kubelet            Created container chown-container-data-dir
  Normal   Started      13m   kubelet            Started container chown-container-data-dir
  Normal   Pulled       13m   kubelet            Container image "quay.io/ceph/ceph:v16" already present on machine
  Normal   Created      13m   kubelet            Created container init-mon-fs
  Normal   Started      13m   kubelet            Started container init-mon-fs
  Normal   Pulled       13m   kubelet            Container image "quay.io/ceph/ceph:v16" already present on machine
  Normal   Created      13m   kubelet            Created container mon
  Normal   Started      13m   kubelet            Started container mon

Addition information:

cat /etc/os-release
NAME=Fedora
VERSION="34 (Thirty Four)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Thirty Four)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"

uname -a
Linux master 5.15.16-100.fc34.x86_64 #1 SMP Thu Jan 20 16:34:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

 k get nodes
NAME     STATUS   ROLES                  AGE   VERSION
node02   Ready    <none>                 17h   v1.22.7+k3s1
master   Ready    control-plane,master   17h   v1.22.7+k3s1
node03   Ready    <none>                 17h   v1.22.7+k3s1
node01   Ready    <none>                 17h   v1.22.7+k3s1

 kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by davesargrad** [comment]
I've seen such issues as well. 
I fear that resolving these types of sticky issues are often left to the users (guys like you and me) deploying the platform. 

Such users (even those that are technical experts in linux and platform integration) typically do not have the targeted expertise to easily resolve the underlying problems.

I think that this kind of "hardening issue" slows down adoption of Rook/Ceph: because it often takes days to isolate and resolve such technical issues. 

I hope the Rook/Ceph team can provide some insight on how to resolve this issue, and on whether or not there is a roadmap focus on such "hardening issues".

**Comment by travisn** [comment]
> [errno 13] RADOS permission denied (error connecting to the cluster): exit status 13

This error indicates Ceph is explicitly denying connection, which likely means an invalid cephx keyring. This should only happen if the dataDirHostPath was not fully cleaned up from a previous install. You're sure the [cleanup guide](https://rook.github.io/docs/rook/v1.9/ceph-teardown.html#delete-the-data-on-hosts) was fully followed, especially cleaning up the host path under `/var/lib/rook`? Could there be a timing issue with your cleanup procedure where the host isn't fully cleaned up before the new cluster is deployed?

**Comment by travisn** [comment]
> Thanks for you help on this. Appreciate your quick reply.

Is the issue resolved then, or you're still investigating?

**Comment by jsnouffer** [comment]
I am also experiencing this issue with a new rook-ceph install on a fresh k3s cluster. I have also tried tearing down the cluster using the automated cleanupPolicy, mentioned [here](https://github.com/rook/rook/blob/d3e7a17db99df9cd027584dd04a99d6d273c7b63/deploy/charts/rook-ceph-cluster/values.yaml#L160), and verified that /var/lib/rook is removed on each node, but the problem persists.

I'm not sure what else to try.



logs: https://pastebin.com/LVS0NaJU
k3s configs: https://pastebin.com/465fM7Q0

cluster spec
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  annotations:
    meta.helm.sh/release-name: rook-ceph
    meta.helm.sh/release-namespace: rook-ceph
  labels:
    app.kubernetes.io/managed-by: Helm
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: nexusrepo.avde.net:8080/ceph/ceph:v16.2.7
  cleanupPolicy:
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  crashCollector:
    daysToRetain: 30
  dashboard:
    enabled: true
    urlPrefix: /ceph-dashboard
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 1m0s
      status:
        interval: 1m0s
  mgr:
    count: 2
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    count: 3
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - storage-node
      tolerations:
      - key: storage-node
        operator: Exists
  priorityClassNames:
    mgr: system-cluster-critical
    mon: system-node-critical
    osd: system-node-critical
  resources:
    cleanup:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 100Mi
    crashcollector:
      limits:
        cpu: 500m
        memory: 60Mi
      requests:
        cpu: 100m
        memory: 60Mi
    logcollector:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    mgr:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    mgr-sidecar:
      limits:
        cpu: 500m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 40Mi
    mon:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 1Gi
    osd:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 4Gi
    prepareosd:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 500m
        memory: 50Mi
  storage:
    config:
      encryptedDevice: "true"
    devices:
    - name: sdc
    useAllDevices: false
    useAllNodes: true
  waitTimeoutForHealthyOSDInMinutes: 10
```
