### ISSUE TITLE
manage RGW Lua scripts via CRD

### ISSUE THREAD

**Issue by yuvalif** [rook/rook#10182]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
we should support [Lua script management](https://docs.ceph.com/en/quincy/radosgw/lua-scripting/) via CRDs.
we should support both script management and luarocks dependency management via CRDs (for simplicity we should try and use the same CR for both)

**What is use case behind this feature:**
list of usecases is here: https://github.com/ceph/ceph/tree/master/examples/lua
that would currently require using the toolbox to interact with `radosgw-admin`

**Environment**:
N/A

**Comment by travisn** [comment]
Looking forward to the design of the CRD(s)... I wonder if we can design such that we don't need to embed the script in the yaml. Embedding a script in a whitespace-sensitive format (yaml) is just bound to cause issues. Perhaps we just include an example of how to generate the CR with the lua script plus a template so they can test the script independently before dropping it in a CR.

**Comment by yuvalif** [comment]
i don't see an easy option if the lua code is not in the CR.
trying to point to a file would be difficult since it probably won't be accessible from inside the operator.

according to this: https://yaml.org/spec/1.2-old/spec.html#id2760844
it should be possible to embed literal string so that the yaml ignores newlines, spaces etc. in the string.
do you think this would be an option?

**Comment by yuvalif** [comment]
an initial proposal
based on the last example from [here](https://docs.ceph.com/en/quincy/radosgw/lua-scripting/):
```yaml
apiVersion: objectbucket.io/v1alpha1
kind: CephLuaScript
metadata:
  name: my-script
  namespace: my-app-space
spec:
  objectStoreName: my-store
  objectStoreNamespace: rook-ceph
  tenant: some-tenant
  context: postRequest
  script: |
    if Request.RGWOp == "get_obj" then
      local json = require("json")
      local socket = require("socket")
      local unix = require("socket.unix")
      local s = assert(unix())
      E = {}

      msg = {bucket = (Request.Bucket or (Request.CopyFrom or E).Bucket).Name,
      time = Request.Time,
      operation = Request.RGWOp,
      http_status = Request.Response.HTTPStatusCode,
      error_code = Request.Response.HTTPStatus,
      object_size = Request.Object.Size,
      trans_id = Request.TransactionId}

      assert(s:connect("/tmp/socket"))
      assert(s:send(json.encode(msg).."\n"))
      assert(s:close())
    end
  packages:
    - name: luajson
      version:
      allowCompilation: false
    - name: luasocket
      version:
      allowCompilation: true
```

**Comment by yuvalif** [comment]
another issue is the fact that we can have only one script per "context".
because the CRs are named, we can have multiple CRs for the same context, but only one of them can apply,
any idea on how we should represent this?

**Comment by yuvalif** [comment]
suggested different structure to allow for bindings other than lua (e.g. web assembly):

based on [the "storage class" example](https://github.com/ceph/ceph/blob/master/examples/lua/storage_class.md) with relatively simple script embedded in the yaml:
```yaml
apiVersion: objectbucket.io/v1alpha1
kind: CephObjectStoreLambda
metadata:
  name: storage-class-script
  namespace: my-app-space
spec:
  objectStoreName: my-store
  objectStoreNamespace: rook-ceph
  tenant: some-tenant
  context: preRequest
  runtime:
    lua:
      script: |
        local function isempty(input)
          return input == nil or input == ''
        end

        if Request.RGWOp == 'put_obj' then
          if (isempty(Request.HTTP.StorageClass)) then
            if (Request.ContentLength >= 65536) then
              Request.HTTP.StorageClass = "QLC_CLASS"
            else
              Request.HTTP.StorageClass = "STANDARD"
            end
        end
```

based on [the "elasticsearch" example](https://github.com/ceph/ceph/blob/master/examples/lua/elasticsearch_adapter.md) with complex script referenced via URL (that the operator should download):
```yaml
apiVersion: objectbucket.io/v1alpha1
kind: CephObjectStoreLambda
metadata:
  name: elasticsearch-script
  namespace: my-app-space
spec:
  objectStoreName: my-store
  objectStoreNamespace: rook-ceph
  tenant: some-tenant
  context: postRequest
  runtime:
    lua:
      scriptURL: https://raw.githubusercontent.com/ceph/ceph/master/examples/lua/elasticsearch_adapter.lua
      packages:
        - name: luajson
          allowCompilation: false
        - name: lua-cjson
          version: 2.1.0-1
          allowCompilation: true
        - name: elasticsearch
          version: 1.0.0-1
          allowCompilation: true
```
