### ISSUE TITLE
Issue configuring ingress

### ISSUE THREAD

**Issue by encausticcello** [rook/rook#10193]
Hi, I'm having issues getting a custom ingress to work (helm chart v1.9.2) Please review my values.yaml and let me know if I'm missing something. Thanks!

```
  dashboard:
    enabled: true
    urlPrefix: "/ceph-dashboard"
    port: 8443
    ssl: true

ingress:
  dashboard:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-dns"
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /ceph-dashboard/$2
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/server-snippet: |
        proxy_ssl_verify off;
    host:
      name: customdomain.com
      path: "/ceph-dashboard(/|$)(.*)"
    tls:
    - hosts:
        - customdomain.com
      secretName: rook-dashboard-tls

**Comment by encausticcello** [comment]
This is the ingress manifest helm is creating:

```
# Source: rook-ceph-cluster/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rook-ceph-dashboard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: /ceph-dashboard/$2
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
spec:
  rules:
    - host: customdomain.com
      http:
        paths:
          - path: /ceph-dashboard(/|$)(.*)
            backend:
              service:
                name: rook-ceph-mgr-dashboard
                port:
                  name: https-dashboard
            pathType: Prefix
  tls:
    - hosts:
      - customdomain.com
      secretName: rook-dashboard-tls
```

It looks like the service that is being rendered is using a different port name:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-ceph-mgr
    ceph_daemon_id: a
    rook_cluster: rook-ceph
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph
spec:
  clusterIP: 10.43.64.238
  clusterIPs:
  - 10.43.64.238
  ports:
  - name: http-dashboard
    port: 8443
  selector:
    app: rook-ceph-mgr
    ceph_daemon_id: a
    rook_cluster: rook-ceph
```
