### ISSUE TITLE
Helm chart adds createPrometheusRules property in generated CephCluster CRD 

### ISSUE THREAD

**Issue by Jean-Daniel** [rook/rook#10267]
* Bug Report

We have a Kubernetes configuration generator tool that try to validate all generated files before applying them. 
Since rook 1.9, it now fails because the generated CephCluster resources includes an extra property not defined in the CRD schema.

**Deviation from expected behavior:**

The generated CRD cannot be validated using the OpenAPI CRD schema.

**Expected behavior:**

The generated CRD matches the CRD schema.

**How to reproduce it (minimal and precise):**

Run the helm chart to generate a CephCluster. 
The monitoring block includes a `createPrometheusRules` property.

**Environment**:
* Rook version: 1.9.3

**Comment by travisn** [comment]
What exactly is your values.yaml? The `createPrometheusRules` is not part of the CephCluster schema, but is rather a top-level monitoring setting that will be used to determine how the templates are created. (This section is *not* under `cephClusterSpec`):
```
monitoring:
  enabled: true
  createPrometheusRules: true
```

**Comment by Jean-Daniel** [comment]
According to the chart template: (templates/cephcluster.yaml), the whole monitoring section is blindly copied in the generated CephCluster section.

This is why the `createPrometheusRules` property ends up in the generated resource.

```
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: {{ default .Release.Namespace .Values.clusterName }}
spec:
  monitoring:
{{ toYaml .Values.monitoring | indent 4 }}
```
