### ISSUE TITLE
Multiple OBCs owned by single user

### ISSUE THREAD

**Issue by LittleFox94** [rook/rook#10276]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

I want to create multiple CephObjectBucketClaims (OBCs) belonging to a single Ceph RGW user.

A possible way of allowing this is creating a `CephObjectStoreUser` (but now we probably want them in other namespaces #8792) and define the user in the `OBC` like this:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: user-with-multiple-buckets
  namespace: gitlab
spec:
  store: my-store
  displayName: Gitlab S3 user
  quotas:
    #maxBuckets: (defined by rook matching the number of OBCs?)
    maxSize: 80G
    maxObjects: -1
  capabilities:
    # none, not an admin user
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: bucket-1
spec:
  generateBucketName: bucket-1
  storageClassName: rook-ceph-bucket
  owner: user-with-multiple-buckets
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: bucket-2
spec:
  generateBucketName: bucket-2
  storageClassName: rook-ceph-bucket
  owner: user-with-multiple-buckets
```

**What is use case behind this feature:**

I'm in the process of moving my Gitlab installation from it's virtual machine to Kubernetes. Gitlab wants different buckets for it's different kinds of data (artifacts, docker registry, pages, terraform state, ...), but only allows configuring a single set of credentials used for all of them (well, except the docker registry - that actually has its own).

**Environment**:
