### ISSUE TITLE
Startup probes failed on new CephObjectStore

### ISSUE THREAD

**Issue by engineering-dotcms** [rook/rook#10293]
### Discussed in https://github.com/rook/rook/discussions/10292

<div type='discussions-op-text'>

<sup>Originally posted by **engineering-dotcms** May 20, 2022</sup>
Hi,
I'm trying to create my first CephObjectStore with S3 access based on documentation https://rook.io/docs/rook/v1.9/ceph-object.html. When I create it, the relative pod marked as **rook-ceph-rwg-<object-name>** failed to startup because on a startup probes failed.

This is my pod describe

  Normal   Scheduled  49m                    default-scheduler  Successfully assigned rook-ceph/rook-ceph-rgw-<object-name>-a-75cbd99d5-rjpg7 to aks-agentpool-ZZZZZZZZZ
  Normal   Pulled     49m                    kubelet            Container image "quay.io/ceph/ceph:v16.2.7" already present on machine
  Normal   Created    49m                    kubelet            Created container chown-container-data-dir
  Normal   Started    49m                    kubelet            Started container chown-container-data-dir
  Normal   Pulled     49m                    kubelet            Container image "quay.io/ceph/ceph:v16.2.7" already present on machine
  Normal   Created    49m                    kubelet            Created container rgw
  Normal   Started    49m                    kubelet            Started container rgw
  Normal   Killing    46m                    kubelet            Container rgw failed startup probe, will be restarted
  Warning  Unhealthy  9m39s (x174 over 49m)  kubelet            Startup probe failed: dial tcp 10.1.66.102:8080: connect: connection refused
  Warning  BackOff    4m38s (x42 over 20m)   kubelet            Back-off restarting failed container

And this is my yaml

```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: portale-aste-osd
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: true
  gateway:
    port: 80
    instances: 1
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
```

Can anyone help me please?</div>
