### ISSUE TITLE
Add design for enabling metrics via CephCluster CR

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#10291]
It would also be good to add a section started in #10254 on how we can allow users to enable telemetry. With a CephCluster CR setting? How will they opt into the new settings? Or is a CephCluster setting sufficient that we can just automatically opt-in to updates? That's the typical approach for rook, though the pattern doesn't feel right in this case since it would circumvent visibility into what is being collected.

_Originally posted by @travisn in https://github.com/rook/rook/pull/10254#pullrequestreview-977663188_

**Comment by BlaineEXE** [comment]
Notes:
- users don't just opt into telemetry, they also opt into a license
- similarly, telemetry and license may be changed on an update
- docs should note if Rook auto agrees, and should link to telemetry docs and license

Possible manifest spec:
```yaml
spec:
  telemetry:
    enableAndAcceptLicense: <default false>
    channelsEnabled:
      basic: <default true>
      crash: <default true>
      device: <default true>
      ident: <default false>
      perf: <default false>
```
