### ISSUE TITLE
Deploying multiple OSDs on the same node with replication=1

### ISSUE THREAD

**Issue by caffeinism** [rook/rook#10327]
Hello! I tried to deploy multiple OSDs on the same node for testing, but the PG was only deployed on one OSD.
My settings are:

my cluster.yml
```
      - name: storage-03
        devices:
          - name: "nvme0n1"
            config:
              deviceClass: "nvme"
          - name: "nvme1n1"
            config:
              deviceClass: "nvme"
          - name: "nvme2n1"
            config:
              deviceClass: "nvme"
          - name: "nvme3n1"
            config:
              deviceClass: "nvme"
```

and rbd.yaml
```
  failureDomain: osd
  replicated:
    size: 1
    requireSafeReplicaSize: false
```

In essence, this problem occurs because the crush rule of replicated_rule selects the host by default.

The following code seems to be related.
https://github.com/rook/rook/blob/1cdcb3746170fe47b635c7067fcb281f7e1e005c/pkg/operator/ceph/cluster/cluster.go#L364-L397

The crush rule of replicated_rule seems to be hard-coded as a host.

Aside from the post-deployment order, what else can I do?

The method that can be used after deployment was referenced from the following link.

https://access.redhat.com/solutions/6518681
