### ISSUE TITLE
Enhance Documentation to show `pg_num` and `pgp_num` parameters as part of CephBlockPool resource

### ISSUE THREAD

**Issue by zamnuts** [rook/rook#10361]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Enhance the documentation to show how to declare `pg_num` and `pgp_num` per pool within the `CephBlockPool` resource at path `spec.parameters`. This can be mentioned at ["Configuring Pools, Setting PG Count"](https://rook.io/docs/rook/v1.9/Storage-Configuration/Advanced/ceph-configuration/#setting-pg-count) which currently shows the un-rook-like CLI variant.

Additionally, ["Required configurations, Default PG and PGP counts"](https://rook.io/docs/rook/v1.9/Storage-Configuration/Advanced/configuration/#default-pg-and-pgp-counts) mentions the cluster-wide default PG count option, but doesn't illustrate how to declare this in the `CephCluster` CRD.

Example for a specific pool, this works today in my environment (see "Environment" below):
```yaml
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ceph-block-pool-test
  namespace: rook-ceph
spec:
  deviceClass: hdd
  replicated:
    size: 3
  parameters:
    pg_num: '4' # create the pool with a pre-configured placement group number
    pgp_num: '4' # this should match `pg_num` so that all PGs are used
```

**What is use case behind this feature:**
Reinforce keeping the configuration declarative instead of via CLI. Also, seeding an initial PG count or expected pool utilization size is advised by the Ceph documentation.

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 20.04.4 LTS`
* Kernel (e.g. `uname -a`): `Linux <redacted> 5.13.0-44-generic #49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: nocloud/self-hosted
* Rook version (use `rook version` inside of a Rook Pod): `v1.9.3`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 17.2.0 (43e2e60a7559d3f46c9d53f1ca875fd499a1e35e) quincy (stable)`
* Kubernetes version (use `kubectl version`): `v1.23.5`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): vanilla
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): `HEALTH_OK`
* Additional, ceph version in rook operator image: `ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)`
