### ISSUE TITLE
How to confirm RBD PVC encryption is operating?

### ISSUE THREAD

**Issue by jfathman** [rook/rook#10371]
Thank you for your excellent open source software.

I am using RBD PVC encryption on rook-ceph v1.9.2 on microk8s v1.23.3-2 running on Debian 10.11 buster cluster nodes.

An app file path based on an encrypted PVC works properly (write/read) for an app running in the cluster.  Good.

The SC runtime config indicates encryption is enabled:

```
jfathman@server-1:~$ kubectl get sc rook-ceph-block-encrypted -o yaml | grep -B8 -A2 -i encrypted: | grep -v csi.storage 
parameters:
  clusterID: rook-ceph
  encrypted: "true"
  encryptionKMSID: user-secret-metadata
  fsName: myfs
```

The PV runtime config similarly indicates encryption is enabled:

```
jfathman@server-1:~$ kubectl get pv pvc-dfa4dd20-c290-4ae9-9dde-34ebc88ad9e4 -o yaml | grep -B2 -A2 encrypted:
    volumeAttributes:
      clusterID: rook-ceph
      encrypted: "true"
      encryptionKMSID: user-secret-metadata
      fsName: myfs
```

How can I confirm externally that encryption is operating, and perhaps what level of encryption is being used?  Is there a command that can be run in the rook-ceph toolkit or on the outer host Linux command line?

Note that this is RBD PVC encryption, not OSD encryption.

Thanks.
