### ISSUE TITLE
1.9 Rook upgrade. Permission denied

### ISSUE THREAD

**Issue by Antiarchitect** [rook/rook#10406]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Formerly (1.8.9) my initContainer create directory on persistent volume well:

```
      initContainers:
      - name: plugins-extractor
        image: {{ .Values.global.imageDashboards }}
        command:
        - /bin/sh
        args:
        - -c
        - "mkdir -p /grafana/plugins && cp -avr /var/lib/grafana/plugins/. /grafana/plugins"
        volumeMounts:
        - name: var-lib-grafana
          mountPath: /grafana
...
  volumeClaimTemplates:
  - metadata:
      name: var-lib-grafana
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: core-rook-block
      resources:
        requests:
          storage: 1Gi
```

After upgrade to 1.9.x:

```
plugins-extractor mkdir: can't create directory '/grafana/plugins': Permission denied
```

**Expected behavior:**

Note that the image sets USER to non-root.

Directory is created without permission problems.

Directory is created sussessfully

**How to reproduce it (minimal and precise):**
Try to create directory inside mounted PV with non-root user.

**Comment by Madhu-1** [comment]
@Antiarchitect can you specify `SecurityContext` in the pod yaml and check this again?

**Comment by Antiarchitect** [comment]
What `SecurityContext` do you mean exactly? `runAsNonRoot` or it does not matter?

**Comment by Madhu-1** [comment]
Am able to create pod and use it as non root user

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: csirbd-demo-pod
spec:
  securityContext:
    runAsNonRoot: true
    fsGroup: 999
  containers:
    - name: web-server
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      image: gcr.io/google-samples/node-hello:1.0
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: rbd-pvc
        readOnly: false
```
```bash
kubectl execectl exec -it csirbd-demo-pod -- sh
$ ps -auf
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
999           12  0.0  0.0   4336   784 pts/0    Ss   13:34   0:00 sh
999           18  0.0  0.0  17496  2012 pts/0    R+   13:34   0:00  \_ ps -auf
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          28G  7.1G   20G  27% /
tmpfs            64M     0   64M   0% /dev
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/vda1        28G  7.1G   20G  27% /etc/hosts
shm              64M     0   64M   0% /dev/shm
/dev/rbd0       976M  2.6M  958M   1% /var/lib/www/html
tmpfs           3.9G   12K  3.9G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           2.0G     0  2.0G   0% /proc/acpi
tmpfs           2.0G     0  2.0G   0% /proc/scsi
tmpfs           2.0G     0  2.0G   0% /sys/firmware
$ cd /var/lib/www/html
$ touch c
$ ls
c  lost+found
$ cat c
$ ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
999            1  0.0  0.0   4336   788 ?        Ss   13:34   0:00 /bin/sh -c node server.js
999            7  0.1  0.5 772124 22648 ?        Sl   13:34   0:00 node server.js
999           12  0.0  0.0   4336   784 pts/0    Ss   13:34   0:00 sh
999           23  0.0  0.0  17500  2008 pts/0    R+   13:35   0:00 ps aux
$ 
```

**Comment by Antiarchitect** [comment]
I bet we use grafana https://github.com/grafana/grafana/blob/main/Dockerfile as the base image. So any official grafana image e.g. grafana/grafana:8.5.4

**Comment by Madhu-1** [comment]
without securityContext it fails for me with security context it works fine. can you please try and let me know

**Comment by Antiarchitect** [comment]
Will try later. Do not want to disturb my team at work time. Could you try on 1.8.9. and tell if it work in both ways or with SecurityContext only?

**Comment by Madhu-1** [comment]
You can try like below 

```yaml
securityContext:
    runAsNonRoot: true
    fsGroup: 999
  containers:
    - name: web-server
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
```

**Comment by Madhu-1** [comment]
> Will try later. Do not want to disturb my team at work time. Could you try on 1.8.9. and tell if it work in both ways or with SecurityContext only?

I think its a change in cephcsi 3.6.0 which is present in 1.9 not in 1.8 i can test it and confirm tomorrow.

**Comment by Antiarchitect** [comment]
@Madhu-1 Please do if you can. Looks like some sort of regression.

**Comment by Madhu-1** [comment]
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: csirbd-demo-pod
spec:
  containers:
    - name: web-server
      image: madhupr001/non-root-user
      command: ["/bin/sleep", "infinity"]
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: rbd-pvc
        readOnly: false
```

This pod yaml which uses the non-root user works with Rook 1.8 and 1.9

**Comment by Antiarchitect** [comment]
I don't see you create directory inside mounted pv from within the container

**Comment by Madhu-1** [comment]
```bash
[🎩︎]mrajanna@fedora rbd $]kubectl exec -it csirbd-demo-pod -- sh
~ $ ps aux
PID   USER     TIME  COMMAND
    1 1000      0:00 /bin/sleep infinity
    7 1000      0:00 sh
   13 1000      0:00 ps aux
~ $ df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  27.9G      6.9G     19.4G  26% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     1.9G         0      1.9G   0% /sys/fs/cgroup
/dev/vda1                27.9G      6.9G     19.4G  26% /dev/termination-log
/dev/vda1                27.9G      6.9G     19.4G  26% /etc/resolv.conf
/dev/vda1                27.9G      6.9G     19.4G  26% /etc/hostname
/dev/vda1                27.9G      6.9G     19.4G  26% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/rbd0               975.9M      2.5M    957.4M   0% /var/lib/www/html
tmpfs                     3.8G     12.0K      3.8G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     1.9G         0      1.9G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                     1.9G         0      1.9G   0% /proc/scsi
tmpfs                     1.9G         0      1.9G   0% /sys/firmware
~ $ cd /var/lib/www/html
/var/lib/www/html $ touch a
/var/lib/www/html $ ks
sh: ks: not found
/var/lib/www/html $ ls
a           lost+found
/var/lib/www/html $ ls -lrt
total 16
drwx------    2 root     root         16384 Jun  8 09:32 lost+found
-rw-r--r--    1 1000     1000             0 Jun  8 09:33 a
/var/lib/www/html $ cd ..
/var/lib/www $ ls
html
/var/lib/www $ ls -lrt html/
total 16
drwx------    2 root     root         16384 Jun  8 09:32 lost+found
-rw-r--r--    1 1000     1000             0 Jun  8 09:33 a
```

**Comment by onedr0p** [comment]
> > Will try later. Do not want to disturb my team at work time. Could you try on 1.8.9. and tell if it work in both ways or with SecurityContext only?
> 
> I think its a change in cephcsi 3.6.0 which is present in 1.9 not in 1.8 i can test it and confirm tomorrow.

Something definitely changed. Pre rook 1.9 I was able to create a cephblock PVC and use it as an `existingClaim` in a deployment and it appears the volume would be chowned with the user and group of the UID/GID of the running container.

Now with rook 1.9 I have to be explicit and set a pod security context like below for the application to be able to access the `existingClaim`. The UID and GID are the default user/group running the container.

```yaml
  securityContext
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
```

**Comment by travisn** [comment]
@Antiarchitect @onedr0p 
1. You are just using the csi version deployed by default with Rook, right? In v1.9.x this default is currently csi [v3.6.2](https://github.com/rook/rook/blob/release-1.9/pkg/operator/ceph/csi/spec.go#L126), and in v1.8.x this default would be csi [v3.5.1](https://github.com/rook/rook/blob/release-1.8/pkg/operator/ceph/csi/spec.go#L104).
2. These are just rbd volumes affected? Or have you seen it affect cephfs volumes?

@Madhu-1 @humblec Sounds like something in v3.6 related?

**Comment by Antiarchitect** [comment]
1. Yes, I use csi provided by rook by default
2. I've noticed on RBD volume but have not so many CephFS usecases overall

**Comment by onedr0p** [comment]
@travisn 

1. Yes, default. I am on rook-ceph 1.9.7. Manifests for the Helm releases are [here](https://github.com/onedr0p/home-ops/tree/main/cluster/core/rook-ceph/cluster) and [here](https://github.com/onedr0p/home-ops/tree/main/cluster/core/rook-ceph/operator).
2. I do not mess around much with cephfs, all of my volumes are RDB/RWO/Ceph Block.

You can try a quick test with this container which runs as `568:568` by default:

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: prowlarr
    app.kubernetes.io/name: prowlarr
  name: prowlarr
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: prowlarr
      app.kubernetes.io/name: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: prowlarr
        app.kubernetes.io/name: prowlarr
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: PROWLARR__BRANCH
          value: nightly
        - name: PROWLARR__INSTANCE_NAME
          value: Prowlarr
        - name: PROWLARR__LOG_LEVEL
          value: info
        - name: PROWLARR__PORT
          value: "80"
        envFrom:
        - secretRef:
            name: prowlarr
        image: ghcr.io/onedr0p/prowlarr-nightly:0.4.3.1905@sha256:6ab6eeda688638c62fe8a08cae069762517f8b1c83342d92beff004f90ebe0a6
        imagePullPolicy: IfNotPresent
        name: prowlarr
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
      # securityContext:
      #   fsGroup: 568
      #   fsGroupChangePolicy: OnRootMismatch
      #   runAsGroup: 568
      #   runAsUser: 568
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-config-v1
```
