### ISSUE TITLE
External RGW example should use ingress resource

### ISSUE THREAD

**Issue by jpds** [rook/rook#1042]
Hello,

The external RGW example should use an Ingress resource instead of the NodePort hack it uses.

Here's an example ingress definition I made for my test cluster:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rgw.example
  namespace: rook
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: rgw.example
    http:
      paths:
      - path: /
        backend:
          serviceName: rook-ceph-rgw-my-store
          servicePort: 80
```

**Comment by bassam** [comment]
@jpds which versions of Kubernetes support ingress? it would be great if we switch to ingress.

**Comment by jpds** [comment]
@bassam It's been available since 1.1.

**Comment by travisn** [comment]
@jpds were you running in GCE? If outside GCE, looks like we would need to deploy an ingress controller, which itself would need a node port defined. https://kubernetes.io/docs/concepts/services-networking/ingress/#prerequisites

So perhaps we add this example as GCE-specific, or else include with the example how to start the ingress controller. The latter full example would be great if you have it.

**Comment by jpds** [comment]
@travisn I run rook on bare-metal. You do indeed require an ingress controller to run ingresses, the two popular ones are nginx and traefik - these run as pods which run on "ingress nodes" so they sit on port 80/443 and they are essentially reverse HTTP proxies which match domain names to deployment endpoints.

A simple way to deploy the nginx ingress is through the helm chart:

```
$ helm install --values nginx-ingress-values.yml stable/nginx-ingress --namespace nginx-ingress
```

Where `nginx-ingress-values.yml` contains:

```
rbac:
  create: true
controller:
  replicaCount: 1
  hostNetwork: true
```

You can then create DNS which points at the IP address of the node the nginx pod is running on.
