### ISSUE TITLE
Move or copy deploy/examples/crds.yaml to deploy/crds/

### ISSUE THREAD

**Issue by onedr0p** [rook/rook#10467]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Move or create a new directory with the CRDs to `/deploy/crds` e.g.

```
deploy/
    crds/
        cephblockpools.ceph.rook.io.yaml
        cephclusters.ceph.rook.io.yaml
        ...
        kustomization.yaml # (see below)
```

```yaml
# kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cephblockpools.ceph.rook.io.yaml
  - cephclusters.ceph.rook.io.yaml
  - ...
```

**What is use case behind this feature:**

This would be very useful to install the CRDs with Kustomize, for example:

`kubectl apply -k ./path/to/folder/containing/file/below`

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/rook/rook//deploy/crds?ref=v1.9.5
```

Thanks!

**Comment by travisn** [comment]
Since this is specific for kustomize, what about this structure?
```
deploy/kustomize/kustomize.yaml
deploy/kustomize/crds.yaml (symlink to ../examples/crds.yaml)

**Comment by onedr0p** [comment]
That works perfectly!

It seemed cleaner to me if possible to break up the CRDs into different files, but thinking it over I am not sure what benefit that would bring other than not having a phat manifest.

**Comment by onedr0p** [comment]
### The kustomization in `./deploy/kustomize/kustomization.yaml` would just look like this

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds.yaml
```

### A person that wants to apply the CRDs would need to create and `kubectl apply -k` a file like this:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/rook/rook//deploy/kustomize?ref=v1.9.5
```
