### ISSUE TITLE
mon multiple storage class support

### ISSUE THREAD

**Issue by kfox1111** [rook/rook#10470]
* Feature Request

**What should the feature do:**
It would be nice to specify a list of storage classes for the mons, and have rook try and spread the mons out across those storage classes as much as possible.

**What is use case behind this feature:**
Having high availability in the mons, that are backed by low availability storage classes. A whole storage class could go unavailable then and enough mons could stay up to keep the cluster running.

**Comment by travisn** [comment]
To capture scenario from the slack discussion... the scenario is where each datacenter would have its own storage class, instead of following the pattern of cloud providers that have a single storage class and affinity of PVs to an AZ.

**Comment by travisn** [comment]
Still an interesting scenario

**Comment by ideepika** [comment]
seems interesting, can I pick this one up or is anyone working on it @travisn ?

**Comment by travisn** [comment]
> seems interesting, can I pick this one up or is anyone working on it @travisn ?

Sounds good, it would be good to first have a design doc (even if small) so we can agree on the approach.

**Comment by travisn** [comment]
The operator really needs to become aware of zones and be able to associate a storage class with each zone. This is very similar to what was implemented for the stretch clusters. In the example [here](https://github.com/rook/rook/blob/release-1.10/deploy/examples/cluster-stretched-aws.yaml#L22-L43), the operator is made aware of the zone names, which one is arbiter. Also not seen in that example is that each zone could have a separate `volumeClaimTemplate` as seen in the [StretchClusterZoneSpec type](https://github.com/rook/rook/blob/release-1.10/pkg/apis/ceph.rook.io/v1/types.go#L526-L537). 

We could potentially re-use those types for a non-stretch cluster with settings such as:
```yaml
  mon:
    count: 3
    zones:
      - name: us-east-2a
        volumeClaimTemplate:
          spec:
            storageClassName: storageclass-2a
            resources:
              requests:
                storage: 10Gi
      - name: us-east-2b
        volumeClaimTemplate:
          spec:
            storageClassName: storageclass-2b
            resources:
              requests:
                storage: 10Gi
      - name: us-east-2c
        volumeClaimTemplate:
          spec:
            storageClassName: storageclass-2c
            resources:
              requests:
                storage: 10Gi
```

Much the same as stretch clusters, the operator would need to be aware of creating a mon in each zone, and failover of a mon would need to create another mon on a node in the same zone. There will be some differences from stretch cluster since stretch clusters have two mons in two of the zones and a single mon in the third zone. But overall, there should be a lot of overlap and we could re-use of the patterns and code.
