### ISSUE TITLE
Existing RBDs fail to be mounted after enabling network compression

### ISSUE THREAD

**Issue by silvio201** [rook/rook#10487]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

After enabling network compression in the CephCluster Object, Pods which have RDB volumes fail to start and are stuck in ContainerCreating. The following event is logged multiple times: 

`MountVolume.MountDevice failed for volume "pvc-a4d3a97f-64dc-444a-922c-3bd18eb51a33" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000002-9e75fc1c-e669-11ec-ab60-0a580a82001b already exists`

After disabling network compression again, the volumes can be mounted again and everything works fine.

**Expected behavior:**

Pod starts normally.

**How to reproduce it (minimal and precise):**

Cluster was updated from ceph version 16 to ceph version 17 and network compression was enabled.

**Environment**:
* OS (e.g. from /etc/os-release): Fedora Linux CoreOS 35
* Kernel (e.g. `uname -a`): 5.17.13-200.fc35.x86_64
* Cloud provider or hardware configuration: 3 masters running as KVMs
* Rook version (use `rook version` inside of a Rook Pod): v 1.9.4
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.0 (43e2e60a7559d3f46c9d53f1ca875fd499a1e35e) quincy (stable)
* Kubernetes version (use `kubectl version`): v1.23.5-rc.0.2071+3afdacbd018325-dirty
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OKD
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by silvio201** [comment]
Unfortunately I am not able to execute this commands, because I already rolled back by deactivating network compression again.

But as I said, my Cluster was healthy. In the dashboard the health status was HEALTH_OK.

**Comment by silvio201** [comment]
@Madhu-1 After reenabeling compression and reproducing the same issue, I am now able to provide you with the outputs of the commands:

`ceph -s`:

When trying to execute `ceph -s` in my toolbox pod, I get the following error message:
`2022-06-23T05:07:01.019+0000 7ff9e9984700  0 monclient(hunting): authenticate timed out after 300`

Usually, I have no problems executing `ceph status` on the toolbox pod... Nevertheless, the dashboard shows HEALTH_OK.
As for why this would happen, I have a theory. I noticed that the toolbox pod still runs with ceph version 16.2.9 even though i have set `cephClusterSpec.cephVersion.image` to `quay.io/ceph/ceph:v17.2.0`. Other pods like the osd pods run with the correct ceph version.

`kubectl get po -n rook-ceph`:

```
NAME                                                              READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-6l9zk                                            3/3     Running   6          9d
csi-cephfsplugin-9572h                                            3/3     Running   6          9d
csi-cephfsplugin-bf9nq                                            3/3     Running   12         9d
csi-cephfsplugin-provisioner-c8586c8bd-hprwp                      6/6     Running   19         20h
csi-cephfsplugin-provisioner-c8586c8bd-zxjfp                      6/6     Running   6          9d
csi-rbdplugin-6hkjc                                               3/3     Running   12         9d
csi-rbdplugin-bv8wh                                               3/3     Running   6          9d
csi-rbdplugin-dql6s                                               3/3     Running   6          9d
csi-rbdplugin-provisioner-647fd6bb96-gq7rm                        6/6     Running   6          9d
csi-rbdplugin-provisioner-647fd6bb96-ndfwf                        6/6     Running   18         20h
rook-ceph-crashcollector-master1.okd4-test.silbergrau.org-zqjnn   1/1     Running   0          18h
rook-ceph-crashcollector-master2.okd4-test.silbergrau.org-fz445   1/1     Running   1          40h
rook-ceph-crashcollector-master3.okd4-test.silbergrau.org-chb77   1/1     Running   1          20h
rook-ceph-mds-cephfs-fs1-a-58dfd77d65-5l9mv                       1/1     Running   0          18h
rook-ceph-mds-cephfs-fs1-b-58945f74c7-5dhhf                       1/1     Running   0          18h
rook-ceph-mgr-a-6dbd8cfddf-p9tvc                                  2/2     Running   2          40h
rook-ceph-mgr-b-847bbcc66f-mbj2g                                  2/2     Running   2          20h
rook-ceph-mon-a-6f78b797b-7zlhz                                   1/1     Running   0          9m3s
rook-ceph-mon-c-6dcbd4466b-brxmq                                  1/1     Running   0          9m37s
rook-ceph-mon-d-798bc946f5-tgkpv                                  1/1     Running   0          10m
rook-ceph-operator-54b96d798-w6qfz                                1/1     Running   0          18h
rook-ceph-osd-0-647b5c47df-7kqss                                  1/1     Running   1          20h
rook-ceph-osd-1-668b9fb8db-5h8l6                                  1/1     Running   1          40h
rook-ceph-osd-2-59b7f8ff67-5mtgp                                  1/1     Running   1          40h
rook-ceph-rgw-loki-store-a-6b855957b4-f5f7g                       1/1     Running   1          40h
rook-ceph-tools-bf64cf8cb-x6jts                                   1/1     Running   1          20h
```

@travisn Ok, so as I understand it, for that to work I have to delete the existing StorageClass and PVs and recreate them with this parameter.
I first wanted to try recreating the StorageClass when network compression is turned on without the mounter parameter. When I then created the Application, which should use rook-ceph, the created pvc cannot create the PV. The following error appears in the event log:

`failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-bc708668-61a4-491d-b739-85cbbda71136 already exists`

As for the `mounter: rbd-nbd` parameter... I don't know how to add this parameter using the rook-ceph-cluster helm chart. Maybe you can enlighten me. I tried adding it by modifying the YAML of the StorageClass afterwards by adding `mounter: rbd-nbd` but after saving the StorageClass still has the same settings as before...

**Comment by travisn** [comment]
> As for the `mounter: rbd-nbd` parameter... I don't know how to add this parameter using the rook-ceph-cluster helm chart. Maybe you can enlighten me. I tried adding it by modifying the YAML of the StorageClass afterwards by adding `mounter: rbd-nbd` but after saving the StorageClass still has the same settings as before...

If you want to use the helm chart, you would just add the `mounter: rbd-nbd` in the `storageClass` settings. But since storage classes cannot be modified, you would need to delete the existing storage class first. So instead of updating the helm chart storage class, you could just create a separate storage class based on [this example](https://github.com/rook/rook/blob/master/deploy/examples/csi/rbd/storageclass.yaml) and modify the pool to be `ceph-blockpool`, the same as the pool created by the helm chart.

**Comment by Madhu-1** [comment]
>failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-bc708668-61a4-491d-b739-85cbbda71136 already exists

This happens when cephcsi does not receive any response from the ceph. to confirm you can exec in to the csi-rbdprovisioner/csi-rbdplugin  container and try to create the rbd image manually.

**Comment by silvio201** [comment]
Hello again,

@travisn 

> If you want to use the helm chart, you would just add the mounter: rbd-nbd in the storageClass settings.

I already tried adding rbd-nbd in the storageClass settings of the cephBlockPools section, but even if I add it, it does not get applied to the created storage class. And as I looked through the template file [here](https://github.com/rook/rook/blob/release-1.9/deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml) there does not seem to be integrated support for mounter: rbd-nbd in the current version of the helm chart. Maybe I am missing something.

> So instead of updating the helm chart storage class, you could just create a separate storage class based on [this example](https://github.com/rook/rook/blob/master/deploy/examples/csi/rbd/storageclass.yaml) and modify the pool to be ceph-blockpool, the same as the pool created by the helm chart.

So, I created the following YAML for an extra StorageClass which has the `mounter:rbd-nbd` option in it. The `ceph-blockpool` does not exist in my cluster, because I have overwritten it with my custom CephBlockPool `replicapool`.

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-block-test
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  # clusterID is the namespace where the rook cluster is running
  # If you change this namespace, also change the namespace below where the secret namespaces are defined
  clusterID: rook-ceph # namespace:cluster

  # If you want to use erasure coded pool with RBD, you need to create
  # two pools. one erasure coded and one replicated.
  # You need to specify the replicated pool here in the `pool` parameter, it is
  # used for the metadata of the images.
  # The erasure coded pool must be set as the `dataPool` parameter below.
  #dataPool: ec-data-pool
  pool: replicapool

  # (optional) mapOptions is a comma-separated list of map options.
  # For krbd options refer
  # https://docs.ceph.com/docs/master/man/8/rbd/#kernel-rbd-krbd-options
  # For nbd options refer
  # https://docs.ceph.com/docs/master/man/8/rbd-nbd/#options
  # mapOptions: lock_on_read,queue_depth=1024

  # (optional) unmapOptions is a comma-separated list of unmap options.
  # For krbd options refer
  # https://docs.ceph.com/docs/master/man/8/rbd/#kernel-rbd-krbd-options
  # For nbd options refer
  # https://docs.ceph.com/docs/master/man/8/rbd-nbd/#options
  # unmapOptions: force

   # (optional) Set it to true to encrypt each volume with encryption keys
   # from a key management system (KMS)
   # encrypted: "true"

   # (optional) Use external key management system (KMS) for encryption key by
   # specifying a unique ID matching a KMS ConfigMap. The ID is only used for
   # correlation to configmap entry.
   # encryptionKMSID: <kms-config-id>

  # RBD image format. Defaults to "2".
  imageFormat: "2"

  # RBD image features. Available for imageFormat: "2". CSI RBD currently supports only `layering` feature.
  imageFeatures: layering

  # The secrets contain Ceph admin credentials. These are generated automatically by the operator
  # in the same namespace as the cluster.
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph # namespace:cluster
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph # namespace:cluster
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph # namespace:cluster
  # Specify the filesystem type of the volume. If not specified, csi-provisioner
  # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
  # in hyperconverged settings where the volume is mounted on the same node as the osds.
  csi.storage.k8s.io/fstype: ext4
# uncomment the following to use rbd-nbd as mounter on supported nodes
# **IMPORTANT**: CephCSI v3.4.0 onwards a volume healer functionality is added to reattach
# the PVC to application pod if nodeplugin pod restart.
# Its still in Alpha support. Therefore, this option is not recommended for production use.
mounter: rbd-nbd
allowVolumeExpansion: true
reclaimPolicy: Delete
```

Curiously, after creating the storageClass with `oc apply -f test.yaml` and I checked the YAML of the created StorageClass, the mounter section was only to be found in lastAppliedConfig and not in the general section of the YAML, if you know what I mean.
Nevertheless, after recreating my application with the storageClass `rook-ceph-block-test`, rook-ceph successfully provisioned the volume but unfortunately it the the initial mount error appears again:

```
MountVolume.MountDevice failed for volume "pvc-a4d3a97f-64dc-444a-922c-3bd18eb51a33" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000002-9e75fc1c-e669-11ec-ab60-0a580a82001b already exists
```

@Madhu-1 

> This happens when cephcsi does not receive any response from the ceph. to confirm you can exec in to the csi-rbdprovisioner/csi-rbdplugin container and try to create the rbd image manually.

How can I create the RBD image manually?
