### ISSUE TITLE
Separate image name and tags for helm chart

### ISSUE THREAD

**Issue by willzhang** [rook/rook#10529]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

i use myself pravite registry，so every time i deploy a new version rook with helm , i must find what image tag it use , so is it possible let image name and tags Separate  for helm chart,

eg
```
image-repo: registry.k8s.io/sig-storage/csi-node-driver-registrar
image-tag:  v2.5.1
```

and where it is now:

```
  #cephcsi:
    #image: quay.io/cephcsi/cephcsi:v3.6.2
  #registrar:
    #image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1
  #provisioner:
    #image: registry.k8s.io/sig-storage/csi-provisioner:v3.1.0
  #snapshotter:
    #image: registry.k8s.io/sig-storage/csi-snapshotter:v6.0.1
  #attacher:
    #image: registry.k8s.io/sig-storage/csi-attacher:v3.4.0
  #resizer:
    #image: registry.k8s.io/sig-storage/csi-resizer:v1.4.0
  # Labels to add to the CSI CephFS Deployments and DaemonSets Pods.
  #cephfsPodLabels: "key1=value1,key2=value2"
  # Labels to add to the CSI NFS Deployments and DaemonSets Pods.
  #nfsPodLabels: "key1=value1,key2=value2"
  # Labels to add to the CSI RBD Deployments and DaemonSets Pods.
  #rbdPodLabels: "key1=value1,key2=value2"
  # Enable the volume replication controller.
  # Before enabling, ensure the Volume Replication CRDs are created.
  # See https://rook.io/docs/rook/latest/ceph-csi-drivers.html#rbd-mirroring
  volumeReplication:
    enabled: false
    #image: "quay.io/csiaddons/volumereplication-operator:v0.3.0"
  # Enable the CSIAddons sidecar.
  csiAddons:
    enabled: false
    #image: "quay.io/csiaddons/k8s-sidecar:v0.4.0"
  # Enable the nfs csi driver.
  nfs:
    enabled: false
    #image: "registry.k8s.io/sig-storage/nfsplugin:v4.0.0"
```

**What is use case behind this feature:**
easy install for helm when someone use a pravite registry

before
```
helm install rook-ceph --version v1.9.6 \
  --namespace rook-ceph --create-namespace \
  --set image.repository=registry.cn-shenzhen.aliyuncs.com/images_mirror/ceph \
  --set image.tag=v1.9.6 \
  --set csi.cephcsi.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/cephcsi:v3.6.2 \
  --set csi.registrar.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-node-driver-registrar:v2.5.1 \
  --set csi.resizer.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-resizer:v1.4.0 \
  --set csi.provisioner.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-provisioner:v3.1.0 \
  --set csi.snapshotter.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-snapshotter:v6.0.1 \
  --set csi.attacher.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-attacher:v3.4.0 \
  --set csi.volumeReplication.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/volumereplication-operator:v0.3.0 \
  --set csi.csiAddons.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/k8s-sidecar:v0.4.0 \
  rook-release/rook-ceph
```

after, i don't need care about each image version tag, rook have a default one if i not define image-tag env

```
helm install rook-ceph --version v1.9.6 \
  --namespace rook-ceph --create-namespace \
  --set image.repository=registry.cn-shenzhen.aliyuncs.com/images_mirror/ceph \
  --set csi.cephcsi.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/cephcsi \
  --set csi.registrar.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-node-driver-registrar \
  --set csi.resizer.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-resizer \
  --set csi.provisioner.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-provisioner \
  --set csi.snapshotter.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-snapshotter \
  --set csi.attacher.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-attacher \
  --set csi.volumeReplication.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/volumereplication-operator \
  --set csi.csiAddons.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/k8s-sidecar \
  rook-release/rook-ceph
```

**Environment**:
