### ISSUE TITLE
add rook ceph dashboard `service type` to helm chart values.yaml

### ISSUE THREAD

**Issue by willzhang** [rook/rook#10535]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

add rook ceph dashboard service type to helm chart values.yaml.
i want define nodeport type service for dashboard.

**What is use case behind this feature:**
easy access dashboard without ingress.

**Environment**:

rook v1.9.6

add     service-type: NodePort to values.yaml
https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml

```
  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    # port: 8443
    # Serve the dashboard using SSL (if using ingress to expose the dashboard and `ssl: true` you need to set
    # the corresponding "backend protocol" annotation(s) for your ingress controller of choice)
    ssl: true
    service-type: NodePort

```

relative：https://github.com/rook/rook/issues/6450
