### ISSUE TITLE
Ceph dashboard not showing up

### ISSUE THREAD

**Issue by vyom-soft** [rook/rook#10532]
Hello,
I followed the standard procedure and installed the rook-ceph by using Helm as describe in the official document of rook-ceph.
https://rook.io/docs/rook/v1.9/helm-operator.html
https://rook.io/docs/rook/v1.9/helm-ceph-cluster.html

Ceph dashboard not showing up
<img width="800" alt="image" src="https://user-images.githubusercontent.com/18686082/176655981-c54b1f8d-212f-4829-8a20-4702b73283b1.png">

<img width="786" alt="image" src="https://user-images.githubusercontent.com/18686082/176517653-35278bfe-7e2a-4d93-b981-d3540e3fc319.png">
<img width="787" alt="image" src="https://user-images.githubusercontent.com/18686082/176517795-56620741-8e8d-4bc9-befa-609cd0a9d5a2.png">

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/18686082/176518023-86a627aa-1fec-48bb-a995-4c37e0fa0ac8.png">
<img width="681" alt="image" src="https://user-images.githubusercontent.com/18686082/176518241-c44e1fd7-16f9-422e-b46e-ccd6631dca36.png">

#From my ceph-cluster.yaml

```
  # enable the ceph dashboard for viewing cluster status
    dashboard:
      enabled: true
      # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
      urlPrefix: /ceph-dashboard
      # serve the dashboard at the given port.
      # port: 8443
      # Serve the dashboard using SSL (if using ingress to expose the dashboard and `ssl: true` you need to set
      # the corresponding "backend protocol" annotation(s) for your ingress controller of choice)
      ssl: true
```

#ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rook-ceph-dashboard
  namespace: rook-ceph
  annotations:
    cert-manager.io/cluster-issuer: kvib-prod-ca-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kvib.rook-ceph.prodlab.tech
      secretName: kvib-prod-ca
  rules:
    - host: kvib.rook-ceph.prodlab.tech
      http:
        paths:
          - path: /ceph-dashboard
            pathType: Prefix
            backend:
              service:
                name: rook-ceph-mgr-dashboard
                port:
                  name: https-dashboard
```

**Environment**:
RHEL 8
Kubernetes version: 1.23.0
Cloud-provider/provisioner: K8, KubeSpray, MetalLB (LoadBalancer)
rook-ceph. 1.9.5
cert-manager version: 1.8.0
Nginx Ingress controller
SealedSecret
Install method: helm
/[triage/support]

**Comment by parth-gr** [comment]
Everything looks okay to me,

Can you do me a favor can you use the service node port https://www.rook.io/docs/rook/v1.9/Storage-Configuration/Monitoring/ceph-dashboard/#node-port
For a sake of testing as it the general works.

**Comment by spacex** [comment]
I ran into this same problem and was able to resolve it using 'http-dashboard' instead of 'https-dashboard' in the ingress spec. Port-forwarding and trying to access the https-dashboard directly (even when spec.dashboard.ssl was set to true) did not work.

**Comment by parth-gr** [comment]
@vyom-soft can you confirm, as I see one more similar issue here too https://github.com/rook/rook/issues/10612

That normal `http` work fine?

**Comment by parth-gr** [comment]
@spacex but in the mgr dashboard service mentioned above I can see the port is `8443`

**Comment by jmolmo** [comment]
Hi @spacex , @vyom-soft : 
The first thing to see is where is really listening the dashboard:
Use the ceph tool box, with the command "ceph mgr services":
```
bash-4.4$ ceph mgr services
{
    "dashboard": "https://10.244.1.30:8443/",
    "prometheus": "http://10.244.1.30:9283/"
}
```

The @spacex comment:
> I ran into this same problem and was able to resolve it using 'http-dashboard' instead of 'https-dashboard' in the ingress spec.

Points towards the configuration applied for the dashboard was without https.

Another important point to take into account:

The Ceph dashboard module, has two different settings for adjust the port used with/without ssl:
By default: 
- if you use "ssl: true" in your cluster crd ( or helm cluster values file), the port used will be 8443.
- if you use "ssl: false" in your cluster crd ( or helm cluster values file), the port used will be 7000.

So if you enable or disable ssl, and you want to provide a way to access the dashboard from a external location  (node port, load balancer, ingress), you will need to use the right port specification in your CRD spec/helm chart.

**Comment by Brainpitcher** [comment]
just in case if someone does not want to spend many hours like me :)

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ceph-dashboard-ingress
  namespace: rook-ceph
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-domain
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: ceph.local.domain.com
    http:
      paths:
      - path: "/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: rook-ceph-mgr-dashboard
            port:
              number: 8443
  tls:              
  - hosts:
      - ceph.local.domain.com
    secretName: le-ceph-dashboard-tls
```
