### ISSUE TITLE
rook-ceph-mgr-dashboard defaults to http port on pod recreation when ssl: true

### ISSUE THREAD

**Issue by arcreigh** [rook/rook#10612]
* Bug Report

**Deviation from expected behavior:**
When SSL=true and a pod gets recreated the service defaults ports to 7000 "http"

**Expected behavior:**
When SSL is true the service should use the port configured for HTTPS vs HTTP

**How to reproduce it (minimal and precise):**
delete the active mgr pod that is tied to the service.

**Environment**:

* Rook version (use `rook version` inside of a Rook Pod): "command not found"
* Storage backend version: 17.2.1
* Kubernetes version: 1.24.2
* Kubernetes cluster type: kubeadm
* Storage backend status: green

**Comment by parth-gr** [comment]
@arcreigh I tried deleting mgr pod there is no change in the service,

And are you trying to access the cluster externally like this https://www.rook.io/docs/rook/v1.9/Storage-Configuration/Monitoring/ceph-dashboard/#node-port?

Can you please share logs and examples?

**Comment by arcreigh** [comment]
I'll be happy to but do bear with me this week I am getting married. I am actually using an nginx ingress to access the dashboard. That is tied to the service and points to port 8443.

**Comment by arcreigh** [comment]
Was there anything else you needed from me?

**Comment by parth-gr** [comment]
> Was there anything else you needed from me?

Thanks for the details I missed your message, will  look into this on Monday and try to reproduce it.

**Comment by parth-gr** [comment]
Which pod `pod gets recreated` are you talking about,

Can you do me a favour of reapplying the settings in cluster.yaml to `ssl:true`  and removing the already existing service that is being created,

Or re-starting the mgr pod,

And see if the bug re-produce

**Comment by parth-gr** [comment]
@arcreigh can you try deleting the dashboard service and restarting the mgr pod?

**Comment by arcreigh** [comment]
Sure! Give me a few and i'll give it a shot.

**Comment by arcreigh** [comment]
deletion of the service recreates the service with the expected port of 8443, deleting the associated pods to the service causes the service to be rebuilt with port 7000.

**Comment by arcreigh** [comment]
Deleting the service after it was recreated w/ port 7000 creates the service w/ port 7000 over again.

**Comment by arcreigh** [comment]
in rook-common.yaml the HTTP ports are commented out as such.
```
    # # Ceph dashboard port HTTP (not recommended)
    # - min: 7000
    #   max: 7000
```
these are the only places in my yaml files for rook where port 7000 is found.

Of note I do see under cluster.yaml that the dashboard port is set as 8443 however commented out as if it is a default value.

```
  # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    # port: 8443
    # serve the dashboard using SSL
    ssl: true
```
Perhaps I should remove the comment on that and see if that helps.
