### ISSUE TITLE
Degraded data redundancy

### ISSUE THREAD

**Issue by kuhar2007** [rook/rook#10672]
Hello, 
I try make fresh install rook with helm. Ceph cluster installed but I always have message in checking health:
Degraded data redundancy: 246/738 objects degraded (33.333%)
I use k8s with 3 masters and 2 workers, each worker have 2 NVMe drives one for OS and second for ceph. (3.5Tb each).
My storage config in helm (v1.9.7 rook-ceph):
```
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "k8s-worker-0"
        devices: # specific devices to use for storage can be specified for each node
          - name: "nvme2n1"
            config:
              osdsPerDevice: "2" 
      - name: "k8s-worker-1"
        devices: # specific devices to use for storage can be specified for each node
          - name: "nvme1n1"
            config:
              osdsPerDevice: "2"
```
Full ceph health:
```
[rook@rook-ceph-tools-778899f66d-9xhfx /]$ ceph -s
  cluster:
    id:     3c052761-5e80-4d43-8669-00dcee30d95f
    health: HEALTH_WARN
            Degraded data redundancy: 246/738 objects degraded (33.333%), 66 pgs degraded, 169 pgs undersized
 
  services:
    mon: 3 daemons, quorum a,b,c (age 4m)
    mgr: b(active, since 3m), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 4 osds: 4 up (since 3m), 4 in (since 3m)
    rgw: 1 daemon active (1 hosts, 1 zones)
 
  data:
    volumes: 1/1 healthy
    pools:   10 pools, 169 pgs
    objects: 246 objects, 12 KiB
    usage:   26 MiB used, 7.0 TiB / 7.0 TiB avail
    pgs:     246/738 objects degraded (33.333%)
             103 active+undersized
             66  active+undersized+degraded
 
  io:
    client:   938 B/s rd, 170 B/s wr, 1 op/s rd, 0 op/s wr
 
  progress:
    Global Recovery Event (0s)
      [............................] 
```
 
```
[rook@rook-ceph-tools-778899f66d-9xhfx /]$ ceph health detail
HEALTH_WARN Degraded data redundancy: 246/738 objects degraded (33.333%), 70 pgs degraded, 169 pgs undersized
[WRN] PG_DEGRADED: Degraded data redundancy: 246/738 objects degraded (33.333%), 70 pgs degraded, 169 pgs undersized
    pg 2.0 is stuck undersized for 11m, current state active+undersized+degraded, last acting [3,0]
    pg 2.5 is stuck undersized for 11m, current state active+undersized+degraded, last acting [3,0]
    pg 2.6 is stuck undersized for 11m, current state active+undersized+degraded, last acting [2,3]
    pg 2.7 is stuck undersized for 11m, current state active+undersized+degraded, last acting [3,2]
    pg 3.1 is stuck undersized for 11m, current state active+undersized, last acting [0,1]
    pg 3.2 is stuck undersized for 11m, current state active+undersized, last acting [2,3]
    pg 3.4 is stuck undersized for 11m, current state active+undersized, last acting [2,3]
    pg 3.6 is stuck undersized for 11m, current state active+undersized+degraded, last acting [0,1]
    pg 3.7 is stuck undersized for 11m, current state active+undersized+degraded, last acting [2,1]
    pg 3.1b is stuck undersized for 11m, current state active+undersized, last acting [0,1]
    pg 3.1c is stuck undersized for 11m, current state active+undersized+degraded, last acting [1,2]
    pg 3.1d is stuck undersized for 11m, current state active+undersized+degraded, last acting [3,2]
    pg 3.1e is stuck undersized for 11m, current state active+undersized, last acting [2,3]
    pg 3.1f is stuck undersized for 11m, current state active+undersized+degraded, last acting [0,1]
    pg 4.0 is stuck undersized for 11m, current state active+undersized, last acting [0,1]
    pg 4.1 is stuck undersized for 11m, current state active+undersized, last acting [1,0]
    pg 4.3 is stuck undersized for 11m, current state active+undersized, last acting [0,3]
    pg 4.5 is stuck undersized for 11m, current state active+undersized+degraded, last acting [3,0]
    pg 4.6 is stuck undersized for 11m, current state active+undersized+degraded, last acting [0,1]
    pg 5.0 is stuck undersized for 11m, current state active+undersized, last acting [2,1]
    pg 5.1 is stuck undersized for 11m, current state active+undersized, last acting [3,0]
    pg 5.2 is stuck undersized for 11m, current state active+undersized, last acting [3,0]
    pg 5.4 is stuck undersized for 11m, current state active+undersized, last acting [1,2]
    pg 5.7 is stuck undersized for 11m, current state active+undersized, last acting [3,0]
    pg 5.18 is stuck undersized for 11m, current state active+undersized, last acting [1,2]
    pg 5.19 is stuck undersized for 11m, current state active+undersized, last acting [0,3]
    pg 5.1a is stuck undersized for 11m, current state active+undersized, last acting [1,0]
    pg 5.1b is stuck undersized for 11m, current state active+undersized, last acting [1,0]
    pg 5.1d is stuck undersized for 11m, current state active+undersized, last acting [2,1]
    pg 6.1 is stuck undersized for 11m, current state active+undersized+degraded, last acting [2,3]
    pg 6.2 is stuck undersized for 11m, current state active+undersized+degraded, last acting [3,0]
    pg 6.3 is stuck undersized for 11m, current state active+undersized+degraded, last acting [3,2]
    pg 6.4 is stuck undersized for 11m, current state active+undersized+degraded, last acting [0,1]
    pg 6.18 is stuck undersized for 11m, current state active+undersized+degraded, last acting [0,1]
    pg 6.19 is stuck undersized for 11m, current state active+undersized+degraded, last acting [2,3]
    pg 6.1a is stuck undersized for 11m, current state active+undersized+degraded, last acting [3,0]
    pg 6.1b is stuck undersized for 11m, current state active+undersized+degraded, last acting [3,2]
    pg 6.1e is stuck undersized for 11m, current state active+undersized+degraded, last acting [2,3]
    pg 7.0 is stuck undersized for 10m, current state active+undersized+degraded, last acting [1,0]
    pg 7.2 is stuck undersized for 10m, current state active+undersized+degraded, last acting [2,3]
    pg 7.3 is stuck undersized for 10m, current state active+undersized+degraded, last acting [0,3]
    pg 7.5 is stuck undersized for 10m, current state active+undersized+degraded, last acting [3,2]
    pg 10.8 is stuck undersized for 10m, current state active+undersized, last acting [0,2147483647,3]
    pg 10.d is stuck undersized for 10m, current state active+undersized, last acting [1,0,2147483647]
    pg 10.e is stuck undersized for 10m, current state active+undersized, last acting [3,2,2147483647]
    pg 10.f is stuck undersized for 10m, current state active+undersized, last acting [3,2,2147483647]
    pg 10.12 is stuck undersized for 10m, current state active+undersized, last acting [1,0,2147483647]
    pg 10.14 is stuck undersized for 10m, current state active+undersized, last acting [0,2147483647,3]
    pg 10.15 is stuck undersized for 10m, current state active+undersized, last acting [0,2147483647,1]
    pg 10.16 is stuck undersized for 10m, current state active+undersized, last acting [3,2147483647,0]
    pg 10.17 is stuck undersized for 10m, current state active+undersized, last acting [3,0,2147483647]
```
Could somebody help me, what did I do wrong?
