### ISSUE TITLE
Support for Ceph SQLite VFS

### ISSUE THREAD

**Issue by t3hmrman** [rook/rook#10689]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add support for [Ceph SQLite VFS on RADOS](https://docs.ceph.com/en/latest/rados/api/libcephsqlite/). 

It seems like a new CRD (`SQLiteVFS`?) would be the way to do this in fitting with the rest of Rook's API. 

It's not immediately clear how to use a `CephClient` to surface the relevant credentials to build the necessary SQLite address (which requires the username/password for a user), so maybe most of the value here would be expanding `CephClient` or adding a new CRD that explicitly does user creation which can be used in this usecase.

**What is use case behind this feature:**

Running SQLite off of RADOS directly.

This is somewhat redundant with CephFS and even regular RBD storage since [concurrent readers are not yet supported](https://tracker.ceph.com/issues/49958).

**Environment**:

**Comment by travisn** [comment]
I believe all the needed API is already there to support VFS in Rook, most of the configuration will be in the application pod instead of in Rook or the CSI driver. Try this:
- Create the CephClient CR with the needed privileges. The cephx key will be added to a secret (see the `status` of the CR for the secret name)
- Define your client pod spec with:
   - Mount the secret (from step 1) as a volume in the client pod
   - For the mon endpoints, mount the `rook-ceph-mon-endpoints` configmap. See the [toolbox](https://github.com/rook/rook/blob/master/deploy/examples/toolbox.yaml#L105-L110) for an example.
   - Generate the ceph.conf with that secret
   - Perform the necessary VFS configuration
   - Start the sqlite client

**Comment by t3hmrman** [comment]
Hey @travisn thank you, that's exactly what I needed to make it a bit clearer *how* to use the `CephClient`, I'll find some time to give this a try. 

Maybe it's more a documentation change than anything!

**Comment by travisn** [comment]
> Maybe it's more a documentation change than anything!

Yes, it would be great to document these steps after you confirm it's working.

**Comment by t3hmrman** [comment]
Hey @travisn thanks for the help, after a bunch of tinkering I got it working.

I'll find some time this week or next to write it up, but basically the relevant YAML looks like this:

```yaml
---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: sqlitevfs
  namespace: rook-ceph
spec:
  caps:
    mon: 'allow r' # access to read mons
    osd: 'profile rbd pool=raid1, profile rbd pool=rook-raid1-3n-host' # RBD access on all OSDs via RBD but on *specific* pools only
```

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlitevfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlitevfs
      component: app
  template:
    metadata:
      labels:
        app: sqlitevfs
        component: app
    spec:
      serviceAccountName: sqlitevfs-setup

      initContainers:
        ## Setup Ceph SQLite VFS
        - name: setup
          image: bitnami/kubectl:1.21.11
          command:
            - /bin/bash
            - -c
            - |
              # Wait until sqlitevfs cephclient is ready
              SECRET_NAME=`kubectl get cephclient ${CEPH_CLIENT_NAME} -o jsonpath='{.status.info.secretName}' -n ${CEPH_NS}`
              while [ -z "${SECRET_NAME}" ]; do
                sleep 3;
                echo -e "[info] checking for cephclient [${CEPH_CLIENT_NAME}]...";
                SECRET_NAME=`kubectl get cephclient ${CEPH_CLIENT_NAME} -o jsonpath='{.status.info.secretName}' -n ${CEPH_NS}`;
              done;

              echo -e "[info] found ceph client secret [${SECRET_NAME}] in namespace [${CEPH_NS}], extracting content...";
              SECRET_CONTENT=`kubectl get secret ${SECRET_NAME} -o jsonpath="{.data.${CEPH_CLIENT_NAME}}" -n ${CEPH_NS} | base64 -d`;

              echo -e "[info] writing ceph keyring...";
              echo -e "[client.${CEPH_CLIENT_NAME}]" > /libsqliteceph/ceph.keyring;
              echo -e "  key = ${SECRET_CONTENT}" >> /libsqliteceph/ceph.keyring;
              echo -e "  caps mon = 'allow r'" >> /libsqliteceph/ceph.keyring;
              echo -e "  caps osd = 'profile rbd pool=raid1, profile rbd pool=rook-raid-1-3n-host'" >> /libsqliteceph/ceph.keyring;

              echo -e "retrieving mon endpoints...";
              MON_ENDPOINTS=`kubectl get configmap rook-ceph-mon-endpoints -o jsonpath='{.data.data}' -n ${CEPH_NS} | sed 's/.=//g'`;

              echo -e "[info] writing out ceph.conf...";
              echo -e "[global]" > /libsqliteceph/ceph.conf;
              echo -e "mon_host=${MON_ENDPOINTS}" >> /libsqliteceph/ceph.conf;
              echo -e "#debug ms = 1/6" >> /libsqliteceph/ceph.conf;
              echo -e "#debug default = 3/5" >> /libsqliteceph/ceph.conf;
              echo -e "#debug client = 3/5" >> /libsqliteceph/ceph.conf;
              echo -e "#log file = /tmp/ceph-\$pid.log" >> /libsqliteceph/ceph.conf;

              echo -e "[info] writing ceph args...";
              echo -e "--id ${CEPH_CLIENT_NAME}" > /libsqliteceph/ceph.args

              echo -e "[info] successfully set up temporary libsqliteceph credentials!";
          env:
            - name: CEPH_CLIENT_NAME
              value: sqlitevfs
            - name: CEPH_NS
              value: rook-ceph
          volumeMounts:
            - name: libsqliteceph-config
              mountPath: /libsqliteceph

      containers:
        - name: sqlitevfs
          image: alpine:3.16.2
          command:
            - /bin/ash
            - -c
            - |
              apk add ceph vim sqlite;

              export CEPH_CONF=/libsqliteceph/ceph.conf;
              export CEPH_KEYRING=/libsqliteceph/ceph.keyring;
              export CEPH_ARGS=`cat /libsqliteceph/ceph.args`;

              # Sleep forever (kubectl exec in to test!)
              sleep infinity;
          volumeMounts:
            - name: libsqliteceph-config
              mountPath: /libsqliteceph

      volumes:
        - name: libsqliteceph-config
          emptyDir:
            medium: Memory
```

To make the `initContainer` stuff work out, you'd need the following RBAC resources:

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sqlitevfs-setup

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sqlitevfs-setup
rules:
  - apiGroups: ["ceph.rook.io"]
    resources:
      - 'cephclients'
    verbs:
      - 'get'

  - apiGroups: [""]
    resources:
      - 'secrets'
    verbs:
      - 'get'
    resourceNames:
      - rook-ceph-client-sqlitevfs

  - apiGroups: [""]
    resources:
      - 'configmaps'
    verbs:
      - 'get'
    resourceNames:
      - rook-ceph-mon-endpoints

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sqlitevfs-setup
roleRef:
  kind: ClusterRole
  name: sqlitevfs-setup
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: sqlitevfs-setup
    apiGroup: ""
```

Once I did this I was able to get it successfully working with some trial & error.

First to load and get data:

```
sqlite> .load libcephsqlite.so
sqlite> .open file:///raid1:/sqlitevfs.db?vfs=ceph
sqlite> CREATE TABLE test (id INTEGER PRIMARY KEY, text TEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
sqlite> INSERT INTO test (text) VALUES ("this is the first line!");
sqlite> INSERT INTO test (text) VALUES ("second record!");
sqlite> .timer on
sqlite> INSERT INTO test (text) VALUES ("third record!");
Run Time: real 0.077 user 0.006516 sys 0.005160
```

Then I compared with a "regular" DB on ephemeral *in-container* `overlayfs`:

```
sqlite> .open /tmp/test.db
sqlite> CREATE TABLE test (id INTEGER PRIMARY KEY, text TEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
sqlite> INSERT INTO test (text) VALUES ("this is the first line!");
sqlite> INSERT INTO test (text) VALUES ("second record!");
sqlite> .timer on
sqlite> INSERT INTO test (text) VALUES ("third record!");
Run Time: real 0.013 user 0.000505 sys 0.000000
```

~6x slower than straight `overlayfs`, but this makes sense, I haven't done any tuning, not even the recommended `PRAGMA` setting, etc.

So then I killed the container, let it come back up, and repeated the process and:

```
/ # sqlite3
SQLite version 3.38.5 2022-05-06 15:25:27
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .load libcephsqlite.so
sqlite> .open file:///raid1:/sqlitevfs.db?vfs=ceph
sqlite> .timer on
sqlite> SELECT * FROM test;
1|this is the first line!|2022-08-16 14:22:56
2|second record!|2022-08-16 14:23:17
3|third record!|2022-08-16 14:23:52
Run Time: real 0.019 user 0.001332 sys 0.000485
```

Very exciting!
