### ISSUE TITLE
No storage class exists matching configured Rook orchestrator storage class which currently is <local>. This storage class can be set in ceph config (mgr/rook/storage_class)

### ISSUE THREAD

**Issue by wjentner** [rook/rook#10703]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When clicking in the Dashboard on: Cluster -> Physical Disks a 500 error appears.
The mgr log shows the following:
```
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr debug 2022-07-29T10:20:50.428+0000 7fa70784d700  0 [rook ERROR rook.rook_cluster] No storage class exists matching configured Rook orchestrator storage class which currently is <local>. This storage class can be set in ceph config (mgr/rook/storage_class)
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr debug 2022-07-29T10:20:50.428+0000 7fa70784d700  0 [rook ERROR orchestrator._interface] No storage class exists matching name provided in ceph config at mgr/rook/storage_class
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr Traceback (most recent call last):
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr   File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 125, in wrapper
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr     return OrchResult(f(*args, **kwargs))
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr   File "/usr/share/ceph/mgr/rook/module.py", line 229, in get_inventory
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr     discovered_devs = self.rook_cluster.get_discovered_devices(host_list)
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr   File "/usr/share/ceph/mgr/rook/rook_cluster.py", line 713, in get_discovered_devices
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr     storage_class = self.get_storage_class()
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr   File "/usr/share/ceph/mgr/rook/rook_cluster.py", line 709, in get_storage_class
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr     raise Exception('No storage class exists matching name provided in ceph config at mgr/rook/storage_class')
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr Exception: No storage class exists matching name provided in ceph config at mgr/rook/storage_class
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr Internal Server Error
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr Traceback (most recent call last):
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr   File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 47, in dashboard_exception_handler
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr     return handler(*args, **kwargs)
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr   File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr     return self.callable(*self.args, **self.kwargs)
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr   File "/usr/share/ceph/mgr/dashboard/controllers/_base_controller.py", line 258, in inner
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr     ret = func(*args, **kwargs)
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr   File "/usr/share/ceph/mgr/dashboard/controllers/orchestrator.py", line 33, in _inner
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr     return method(self, *args, **kwargs)
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr   File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr     return func(*args, **kwds)
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr   File "/usr/share/ceph/mgr/dashboard/controllers/host.py", line 506, in inventory
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr     return get_inventories(None, refresh)
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr   File "/usr/share/ceph/mgr/dashboard/controllers/host.py", line 251, in get_inventories
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr     for host in orch.inventory.list(hosts=hosts, refresh=do_refresh)]
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr   File "/usr/share/ceph/mgr/dashboard/services/orchestrator.py", line 38, in inner
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr     raise_if_exception(completion)
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr   File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr     raise e
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr Exception: No storage class exists matching name provided in ceph config at mgr/rook/storage_class
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr [::ffff:134.34.xxx.xxx:43590] [GET] [500] [0.217s] [admin] [513.0B] /ui-api/host/inventory
rook-ceph-mgr-b-5dcc665dd6-nbxf9 mgr [b'{"status": "500 Internal Server Error", "detail": "The server encountered an unexpected condition which prevented it from fulfilling the request.", "request_id": "cac564a4-89f4-42d0-b4ef-3d7e5ac4f9eb"}   
```

**Expected behavior:**

No 500 error.

**How to reproduce it (minimal and precise):**

We have a working cluster (HEALTH_OK) with 6 OSDs and an Ceph Filesystem (3 pools: mgr, cephrs-metadata, cephfs-data).

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
StorageClass:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rook-cephfs
  creationTimestamp: '2021-04-26T13:32:14Z'
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  fsName: rook-cephfs
  pool: rook-cephfs-data0
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

CephFilesystem:
```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  labels:
    ceph_version: 17.2.1-0-quincy
  name: rook-cephfs
  namespace: rook-ceph
spec:
  dataPools:
  - erasureCoded:
      codingChunks: 0
      dataChunks: 0
    failureDomain: chassis
    replicated:
      size: 3
  metadataPool:
    failureDomain: chassis
    replicated:
      size: 3
    parameters:
      target_size_bytes: 100G
  metadataServer:
    activeCount: 1
    activeStandby: true
  mirroring:
    enabled: true
    # list of Kubernetes Secrets containing the peer token
    # for more details see: https://docs.ceph.com/en/latest/dev/cephfs-mirroring/#bootstrap-peers
    peers:
      secretNames:
        - backup-server-cluster-peer
    # specify the schedule(s) on which snapshots should be taken
    # see the official syntax here https://docs.ceph.com/en/latest/cephfs/snap-schedule/#add-and-remove-schedules
    snapshotSchedules:
      - path: /
        interval: 3h # snapshots every 3 hours
        # startTime: 01:00
    # manage retention policies
    # see syntax duration here https://docs.ceph.com/en/latest/cephfs/snap-schedule/#add-and-remove-retention-policies
```

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

No pods are crashlooping.

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): 
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
* Kernel (e.g. `uname -a`):
```
5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux
```
* Cloud provider or hardware configuration:
Bare-metal cluster.
* Rook version (use `rook version` inside of a Rook Pod):
```
rook: v1.9.8
go: go1.17.12
```
* Storage backend version (e.g. for ceph do `ceph -v`):
```
ceph version 16.2.10 (45fa1a083152e41a408d15505f594ec5f1b4fe17) pacific (stable)
```
This is also weird. The operator shows:
```
rook-ceph-operator-6f75bccd94-mf6n7 rook-ceph-operator 2022-08-11 09:07:51.680039 I | ceph-spec: detecting the ceph image version for image quay.io/ceph/ceph:v17.2.1...
rook-ceph-operator-6f75bccd94-mf6n7 rook-ceph-operator 2022-08-11 09:07:53.228126 I | ceph-spec: detected ceph image version: "17.2.1-0 quincy"
```

* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:59:18Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:53:39Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Bare-metal / kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
HEALTH_OK
