### ISSUE TITLE
Operator doesn't detect new storage nodes until restart

### ISSUE THREAD

**Issue by Capitrium** [rook/rook#10706]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The rook-ceph-operator doesn't detect new storage nodes after a storage node failure until the operator is restarted.

I've been simulating storage node failure/failover, and the operator consistently requires a restart before new prepare-osd jobs and osd pods will be launched on new nodes. There are no errors that I can see in the logs, including with debug logging enabled. Restarting the operator causes a full reconciliation and (prepare-)osd pods are eventually launched, at which point recovery continues and everything works as expected from that point on.

**Expected behavior:**
The operator automatically detects new storage nodes when they are launched after a storage node failure, instead of requiring manual intervention.

**How to reproduce it (minimal and precise):**

1) Configure an autoscaling group consisting of 3 storage nodes, with labels/taints/tolerations to run only the rook-ceph mon/mgr/mds/osd/etc. pods.
2) Scale the autoscaling group down by 1, simulating a node failure. This removes a mon and osd from the cluster.
3) Scale the autoscaling group back up by 1, bringing a new node into service. A new mon is launched on the new storage node and is able to join the cluster, but no osd-prepare or osd pods are ever launched on the new node.
4) Restart the rook-ceph-operator pod. The osd-prepare and osd pods are created during cluster reconciliation.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary:
[cluster.yaml.txt](https://github.com/rook/rook/files/9311262/cluster.yaml.txt)
* Operator's logs, if necessary: 
[rook-operator-debug-logs.txt](https://github.com/rook/rook/files/9311266/rook-operator-debug-logs.txt)
(logs start when I enabled debug logging shortly before simulating node failure, logs end when I restarted the operator pod)

**Environment**:
* OS (e.g. from /etc/os-release): Flatcar Container Linux by Kinvolk 3033.2.4 (Oklo)
* Kernel (e.g. `uname -a`): 5.10.107-flatcar
* Cloud provider or hardware configuration: AWS (3x i3.2xlarge nodes for all rook-ceph pods)
* Rook version (use `rook version` inside of a Rook Pod): v1.9.8
* Storage backend version (e.g. for ceph do `ceph -v`): v16.2.10
* Kubernetes version (use `kubectl version`): v1.23.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Custom (based on kubeadm/tectonic)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by travisn** [comment]
When searching the operator debug log for "node watcher", there are messages about the nodes being unschedulable or not tolerable.
```
2022-08-10 19:10:51.274646 D | ceph-cluster-controller: node watcher: skipping cluster update. added node "ip-10-0-7-112.ec2.internal" is unschedulable
2022-08-10 19:11:29.527207 D | ceph-cluster-controller: node watcher: node "ip-10-0-18-89.ec2.internal" is not tolerable for cluster "rook-ceph", skipping
```
Which nodes are you expecting to be available? And there are tolerations for the OSDs to run there?

When a node is added, rook only evaluates it once and then ignores future events about the node to reduce noisy node events. It's possible that ignoring the node events is too aggressive, will dig into the code later after knowing which node(s) to look at.

**Comment by Capitrium** [comment]
@travisn Those are unrelated nodes. Looking at our metrics, I can see that both of those nodes are labelled with `node.kubernetes.io/role: gpu`, while our rook/ceph pods are configured to run on nodes labelled with `node.kubernetes.io/role: storage`.

<img width="889" alt="Screen Shot 2022-08-12 at 11 53 22 AM" src="https://user-images.githubusercontent.com/5111534/184384427-1d429c44-2fdb-4b27-a446-3f9eae7a379f.png">

The kubelets on our storage nodes are configured to run with the following arguments:
```
--register-with-taints="node.kubernetes.io/role=storage:NoSchedule"
--node-labels="node.kubernetes.io/role=storage"
```

And our CephCluster CR (attached to the ticket) configures the following `nodeAffinity` and `tolerations` for all ceph pods:
```
  placement:
    all:
      tolerations:
        - effect: NoSchedule
          key: node.kubernetes.io/role
          operator: Equal
          value: storage
    mgr:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node.kubernetes.io/role
                  operator: In
                  values:
                    - storage
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: rook-ceph-mgr
            topologyKey: kubernetes.io/hostname
    mon:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node.kubernetes.io/role
                  operator: In
                  values:
                    - storage
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: rook-ceph-mon
            topologyKey: kubernetes.io/hostname
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node.kubernetes.io/role
                  operator: In
                  values:
                    - storage
```

I will try to query our metrics for the storage node that was launched corresponding to the times covered by the debug logs attached to the ticket.
