### ISSUE TITLE
CephObjectStore CRD - gateway.port partially ignored when hostNetwork disabled

### ISSUE THREAD

**Issue by taxilian** [rook/rook#10743]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I set `gateway.port` on my cephobjectstore to `80` but when I later set `hostNetwork: false` (see issue #10649) it ignored that and set the port for the gateway to `8080`. Worse, the health checks still tried to check on port 80, which caused them to fail and the pod never came up. I only figured out what was going on by examining the created pod and then looking at the rook source code to [find where it was overriding it and see that there is no way to tell it not to](https://github.com/rook/rook/blob/master/pkg/operator/ceph/object/config.go#L69).

**Expected behavior:**

At the very least the health checks should keep working =] My best guess is that the service likely tried to redirect port 80 to 8080 but note that this can also be problematic if you are using a LoadBalancer service with `externalTrafficPolicy: Cluster` which would cause traffic to go directly to the pod -- there should be a way to set the actual port used.

**How to reproduce it (minimal and precise):**

On a rook cluster with `hostNetwork: true` create a CephObjectStore with `spec.hostNetwork: false` and `spec.gateway.port` set to `80` (or probably any other value except 8080.

**File(s) to submit**:

This is my CephObjectStore config:

```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: backup-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
    deviceClass: nvme
  dataPool:
    failureDomain: host
    replicated:
      size: 3
    deviceClass: hdd
  preservePoolsOnDelete: true
  hostNetwork: false
  gateway:
    hostNetwork: false
    sslCertificateRef: wildcard-mydomain-com-tls
    port: 80
    securePort: 443
    instances: 2
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
```
