### ISSUE TITLE
ceph/rgw - CephObjectStore should be able to override the hostname

### ISSUE THREAD

**Issue by taxilian** [rook/rook#10748]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

For a number of reasons I wanted to allow direct access to the RGW gateway pods rather than going through a load balancer; unfortunately when I attempted the configure an sslCertificateRef in `spec.gateway` everything external worked but internally to the system the health checks began failing because the ssl certificate was not valid. I tried adding something. From the docs:

```
They are scenarios where the certificate DNS is set for a particular domain that does not include the local Kubernetes DNS, namely the object store DNS service endpoint. If adding the service DNS name to the certificate is not empty another key can be specified in the secret's data: insecureSkipVerify: true to skip the certificate verification. It is not recommended to enable this option since TLS is susceptible to machine-in-the-middle attacks unless custom verification is used.
```

I'm not totally sure what that means -- it definitely needed some proof reading -- but I tried adding insecureSkipVerify to my secret (which wouldn't have lasted since the tls secret is managed by cert-manager) and tried adding it to my gateway ref and nothing I tried helped in any way.

It seems like the correct way to fix this would be to be able to specify what the hostname of the endpoint should be so that it can access it using the provided ssl certificate -- alternatively, it may be possible to make it so that the health check doesn't care about invalid TLS certificates.

**Comment by thotz** [comment]
@taxilian I am guessing following is your scenario but I am not sure what you are referring to hostname override

s3 client <--> LB <-> RGW server, certs are generated for LB and if the client is trying to use different hostname all the requests will fail. Since Rook itself contains s3 client with RGW and always uses RGW service endpoint, all the requests from Rook will fail. Is you requirement is to provide option for Rook Operator to communicate with RGW??
Why can't we add the rgw service endpoint to TLS certs as additional DNS server?

**Comment by taxilian** [comment]
> s3 client <--> LB <-> RGW server, certs are generated for LB and if the client is trying to use different hostname all the requests will fail. Since Rook itself contains s3 client with RGW and always uses RGW service endpoint, all the requests from Rook will fail. Is you requirement is to provide option for Rook Operator to communicate with RGW?? Why can't we add the rgw service endpoint to TLS certs as additional DNS server?

Yes, that's the scenario. The certificates that I use are generated by ACME / cert-manager -- I can't add additional SANs to it or LetsEncrypt will not sign the certificate. I don't actually know of any publicly trusted certificate providers that will allow that, in fact... are you expecting that anyone using this would be using their own internal CA? I guess I'm confused why this seems strange and thinking I must be missing something =]

**Comment by thotz** [comment]
@travisn @BlaineEXE since a lot of similar issues are poping can we make Rook as trusted client for RGW and use always skip TLS cert check for the clients inside Rook?

**Comment by taxilian** [comment]
That would probably be the easiest option, if it's viable. Searching the slack channel I found 5 or 6 other people with the same issue

**Comment by BlaineEXE** [comment]
Agreed that we definitely need to resolve this issue and that the unintended and hidden assumption that users have their own CA is not a great experience. Thanks @taxilian for breaking this down so clearly. 

Before we rush into a solution, I want to make sure we are all on the same page and have an idea for what an adequate solution will look like:

1. Firstly, I want to make sure we keep security a priority. If we are too liberal with our policy(ies), we could allow any Kubernetes pod to be an untrusted client, which would be a big risk.

2. One possible good workflow: When the Rook operator starts up, it uses `radosgw-admin` to configure the RGWs to accept untrusted Admin ops API connections only from its own IP. I think Rook should be able to use `radosgw-admin` to configure RGWs regardless of its IP, but if not, this could be a sticking point.

3. Let's determine the exact RGW config we will set that will allow Rook to be a trusted client. After that, let's make sure we get the config validated by some other RGW experts to do our due diligence to ensure we aren't accidentally opening a security vulnerability.

4. As my final thought, is a multisite peer affected by this issue? I assume not since the peer should be going through the load balancer, but we should verify this.

**Comment by BlaineEXE** [comment]
Updated thought: are external mode RGWs affected?

**Comment by ikogan** [comment]
So I have an external mode RGW and I'm having trouble. I do have my own CA but it looks like external mode RGWs completely ignore any certificate related flags in the `CephObjectStore` CRD. I tried specifying `caBundle` and it still claims it cannot validate the cert even though `openssl` in another pod (with a proper ca-bundle setup) can validate the cert against the service the operator created.

I tried adding `insecureSkipVerify` and that also doesn't work. The operator is marking the `CephObjectStore` as failed because

```
ceph-object-controller: failed to check rgw health for object store "rook-ceph-external". failed to get details from ceph object user "rook-ceph-internal-s3-user-checker-{a-uuid}": Get "https://rook-ceph-rgw-rook-ceph-external.rook-ceph.svc:7443/admin/user?format=json&uid=rook-ceph-internal-s3-user-checker-{a-uuid}": x509: certificate signed by unknown authority
```

I even have bucket health checks disabled. Here's my CRD:

```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: rook-ceph-external
  namespace: rook-ceph
spec:
  gateway:
    caBundleRef: internal-ca
    externalRgwEndpoints:
    - ip: 10.10.0.1
    - ip: 10.10.0.2
    - ip: 10.10.0.3
    - ip: 10.10.0.20
    - ip: 10.10.0.32
    port: 7480
    securePort: 7443
  healthCheck:
    bucket:
      disabled: true
      interval: 1m0s
status:
  bucketStatus:
    details: 'failed to get details from ceph object user "rook-ceph-internal-s3-user-checker-f3042a95-b6fd-460c-8803-6fcb43c1d0af":
      Get "https://rook-ceph-rgw-rook-ceph-external.rook-ceph.svc:7443/admin/user?format=json&uid=rook-ceph-internal-s3-user-checker-{a-uuid}":
      x509: certificate signed by unknown authority'
    health: Failure
    lastChanged: "2022-11-04T02:21:02Z"
    lastChecked: "2022-11-04T02:56:03Z"
  info:
    endpoint: http://rook-ceph-rgw-rook-ceph-external.rook-ceph.svc:7480
    secureEndpoint: https://rook-ceph-rgw-rook-ceph-external.rook-ceph.svc:7443
  phase: Failure
```

Here's my (redacted) secret:

```yaml
apiVersion: v1
data:
  cabundle: {pem encoded cert}
kind: Secret
metadata:
  name: internal-ca
type: Opaque
```

What's interesting is that I can set the `caBundleRef` property to anything and Rook never complains. I feel like it's totally ignored.
