### ISSUE TITLE
Stretch mode not enabled when updating CephCluster settings

### ISSUE THREAD

**Issue by jmasud** [rook/rook#10773]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When setting stretch mode, the default "zone" is not recognized, and errors when attempting to restart monitors.  Sometimes monitor will restart but then will stay in a `pending` state and never fully start.   Hence unable to get cluster to enable stretch mode. 

We have 6 nodes in both LAX and DFW are tagged with the following topology labels, each node has 1TB SSD.  Old SSD disks were removed, and re-added back to ensure OSD pods have topology labels.  

All nodes have topology labels respective added: 

```
                    topology.kubernetes.io/region=tx
                    topology.kubernetes.io/zone=dfw-tx
                    topology.rook.io/datacenter=dfw-tx-01
                    topology.rook.io/rack=dfw-tx-01-r1

                    topology.kubernetes.io/region=ca
                    topology.kubernetes.io/zone=lax-ca
                    topology.rook.io/datacenter=lax-ca-01
                    topology.rook.io/rack=lax-ca-01-r1
```

One example OSD pod label for DFW: 

```
  labels:
    app: rook-ceph-osd
    ceph-osd-id: "0"
    ceph-version: 16.2.7-0
    ceph_daemon_id: "0"
    ceph_daemon_type: osd
    failure-domain: fusedfwn1.example.com
    osd: "0"
    pod-template-hash: f8d98d57b
    portable: "false"
    rook-version: v1.7.11
    rook_cluster: rook-ceph
    topology-location-datacenter: dfw-tx-01
    topology-location-host: fusedfwn1-example-com
    topology-location-rack: dfw-tx-01-r1
    topology-location-region: tx
    topology-location-root: default
    topology-location-zone: dfw-tx
  name: rook-ceph-osd-0-f8d98d57b-zzzvw
  namespace: rook-ceph
```

Show `ceph osd tree` output: 

```
ID    CLASS  WEIGHT    TYPE NAME                                     STATUS  REWEIGHT  PRI-AFF
  -1         13.63199  root default                                                           
 -30          8.17400      region ca                                                          
 -29          8.17400          datacenter lax-ca-01                                           
 -44          4.54099              rack lax-ca-01-r1                                          
 -43          0.90799                  host fuselaxn1-example-com                           
   6    hdd   0.90799                      osd.6                         up   1.00000  1.00000
 -49          1.81599                  host fuselaxn2-example-com                           
   8    hdd   0.90799                      osd.8                         up   1.00000  1.00000
  10    hdd   0.90799                      osd.10                        up   1.00000  1.00000
 -47          1.81599                  host fuselaxn3-example-com                           
   7    hdd   0.90799                      osd.7                         up   1.00000  1.00000
   9    hdd   0.90799                      osd.9                         up   1.00000  1.00000
 -28          3.63300              rack lax-ca-01-r2                                          
 -37          1.81599                  host fuselaxn4-example-com                           
   1    hdd   0.90799                      osd.1                         up   1.00000  1.00000
   2    hdd   0.90799                      osd.2                         up   1.00000  1.00000
 -41          0.90799                  host fuselaxn5-example-com                           
   5    hdd   0.90799                      osd.5                         up   1.00000  1.00000
 -39          0.90799                  host fuselaxn6-example-com                           
   3    hdd   0.90799                      osd.3                         up   1.00000  1.00000
 -79          5.45799      region tx                                                          
 -78          5.45799          datacenter dfw-tx-01                                           
 -77          5.45799              rack dfw-tx-01-r1                                          
 -76          0.90999                  host fusedfwn1-example-com                           
   0    ssd   0.90999                      osd.0                         up   1.00000  1.00000
 -91          0.90999                  host fusedfwn2-example-com                           
  12    ssd   0.90999                      osd.12                        up   1.00000  1.00000
 -88          0.90999                  host fusedfwn3-example-com                           
   4    ssd   0.90999                      osd.4                         up   1.00000  1.00000
 -97          0.90999                  host fusedfwn4-example-com                           
  11    ssd   0.90999                      osd.11                        up   1.00000  1.00000
 -94          0.90999                  host fusedfwn5-example-com                           
  14    ssd   0.90999                      osd.14                        up   1.00000  1.00000
-100          0.90999                  host fusedfwn6-example-com                           
  13    ssd   0.90999                      osd.13                        up   1.00000  1.00000
```

Note there is no zone information present in the tree like the Rook examples.  However, above, I did include `zone` in the topology labels before the OSD pods were created.  

Next, updated CephCluster `rook-ceph`  yaml

```
  mon:
    count: 3
    allowMultiplePerNode: false
```

change/addition:  

```
  mon:
    count: 5
    allowMultiplePerNode: false
    stretchCluster:
      failureDomainLabel: topology.kubernetes.io/zone
      subFailureDomain: host
      zones:
      - name: las-nv
        arbiter: true
      - name: lax-ca
      - name: dfw-tx

  placement:
    arbiter:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
              - lax-ca
              - dfw-tx
```

When the operator is attempting to restart monitors, these are the errors I get 

```
2022-08-19 01:34:37.146611 I | op-k8sutil: Reporting Event rook-ceph:rook-ceph Warning:ReconcileFailed:failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph monitors: failed to init mon config: stretch zone not available: zone not found on mon "ar"
2022-08-19 01:41:36.040614 W | op-mon: failed to check mon health. failed to init mon config: stretch zone not available: zone not found on mon "at"
```

Its failing `zone,` which I verified is present on the nodes, is present on the OSDs, but i don't see any labels on the MONs. 

One example MON pod labes: 

```
  labels:
    app: rook-ceph-mon
    ceph_daemon_id: ar
    ceph_daemon_type: mon
    mon: ar
    mon_cluster: rook-ceph
    pod-template-hash: 7d455786cf
    rook_cluster: rook-ceph
```

I then attempted to change  `failureDomainLabel` from `topology.kubernetes.io/zone` to `topology.rook.io/datacenter` my updated yaml looks like this: 

```
mon:
    allowMultiplePerNode: false
    count: 5
    stretchCluster:
      failureDomainLabel: topology.rook.io/datacenter
      subFailureDomain: host
      zones:
      - arbiter: true
        name: las-nv-01
      - name: lax-ca-01
      - name: dfw-tx-01
...
  placement:
    arbiter:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: topology.rook.io/datacenter
              operator: In
              values:
              - lax-ca-01
              - dfw-tx-01
```

At this point, the MON doesn't give the same error on missing `zone` and restarts the pod, but the pod is in a never-ending pending state because of nodeAffinity settings. 

```
affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.rook.io/datacenter
            operator: In
            values:
            - ""
```

During this process, I also updated CephBlockPool, below is the latest yaml which was working once i started using `datacenter` and instead of example `zone`.  When applied Ceph recovered correctly without any health issues.  

```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  finalizers:
  - cephblockpool.ceph.rook.io
  name: replicapool
  namespace: rook-ceph
spec:
  compressionMode: ""
  crushRoot: ""
  deviceClass: ssd
  erasureCoded:
    algorithm: ""
    codingChunks: 0
    dataChunks: 0
  failureDomain: datacenter
  mirroring:
    enabled: false
    mode: image
  parameters:
    compression_mode: none
  replicated:
    replicasPerFailureDomain: 2
    requireSafeReplicaSize: true
    size: 4
    subFailureDomain: host
    targetSizeRatio: 0
```

I'm expecting the MON to be updated properly, and then restart to distribute 2 in both LAX and DFW datacenters, then once that is done enable stretch mode.  The monitors when set to `zone` didn't restart and failed, then when set to `datacenter` to match the `ceph osd tree`, restarted but had the blank/incorrect nodeAffinity.  

**Environment**:
* OS (e.g. from /etc/os-release): 

```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

* Kernel (e.g. `uname -a`): `Linux fuselaxm1.example.com 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: `Baremetal`
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.7.11`
* Storage backend version (e.g. for ceph do `ceph -v`):  `ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)`
* Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11", GitCommit:"38d3c1f3d5306401bcf39a71bad3b5a5106033d7", GitTreeState:"clean", BuildDate:"2022-03-16T14:08:11Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `kubeadm`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

```
  cluster:
    id:     7137b765-ec87-4cfb-94b3-8811e79fbc7b
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum ar,as,at (age 5h)
    mgr: a(active, since 12h)
    mds: 1/1 daemons up, 1 hot standby
    osd: 15 osds: 15 up (since 10h), 15 in (since 5d)
 
  data:
    volumes: 1/1 healthy
    pools:   4 pools, 513 pgs
    objects: 727.93k objects, 581 GiB
    usage:   2.1 TiB used, 12 TiB / 14 TiB avail
    pgs:     513 active+clean
 
  io:
    client:   1.2 KiB/s rd, 160 KiB/s wr, 1 op/s rd, 22 op/s wr
```
