### ISSUE TITLE
insecureSkipVerify not respected in bucket provisioner

### ISSUE THREAD

**Issue by cy-ddg** [rook/rook#10910]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Creating an ObjectBucketClaim for an object store with external Let's Encrypt certificate does not result in creation of ObjectBucket even though insecureSkipVerify is set in certificate.

**Expected behavior:**
ObjectBucket should be created

**How to reproduce it:**
I took a look at the code in https://github.com/rook/rook/blob/v1.10.0/pkg/operator/ceph/object/bucket/provisioner.go#L83 and at a cursory glance it does not seem to take the `insecureSkipVerify` in the secret into account when creating the S3 client.

**Resources**:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: objstore-certificate
  namespace: rook-ceph
type: Opaque
data:
  cert: >-
    [...]
  insecureSkipVerify: dHJ1ZQ==
```
```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  labels:
    app.kubernetes.io/instance: objstore-cluster
  name: ceph-objectstore
  namespace: rook-ceph
spec:
  dataPool:
    erasureCoded:
      codingChunks: 1
      dataChunks: 2
    failureDomain: host
  gateway:
    instances: 1
    port: 80
    priorityClassName: system-cluster-critical
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    securePort: 443
    sslCertificateRef: objstore-certificate
  healthCheck:
    bucket:
      interval: 60s
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  preservePoolsOnDelete: true
```

**Logs**:
```
[...]
E0907 11:35:09.999360       1 controller.go:205] error syncing 'rook-ceph/thanos-bucket': error provisioning bucket: error creating bucket "thanos": failed to create bucket "thanos": RequestError: send request failed
caused by: Put "https://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc:443/thanos": x509: certificate is valid for [...], not rook-ceph-rgw-ceph-objectstore.rook-ceph.svc, requeuing
[...]
```

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): 1.10.0
* Kubernetes version (use `kubectl version`): 1.22
