### ISSUE TITLE
csi-cephfsplugin fails on NixOS

### ISSUE THREAD

**Issue by yajo** [rook/rook#10932]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Fails when host OS is NixOS.

Basically, this is the resurrection of https://github.com/rook/rook/pull/2190. That PR fixed the problem for old flex volumes mode, but with new CSI mode the problem is happening again. In 0a0b9c98bd809fbfd70ad629c2b6683803879d17 the fix was deleted, and thus here we have the same issue again. 😅 

**Expected behavior:**
Should work.

**How to reproduce it (minimal and precise):**

1. Install Rook 1.9 with helm charts as per [docs](https://rook.io/docs/rook/v1.9/Helm-Charts/helm-charts/). Host OS must be NixOS.
1. Deploy following file.

**File(s) to submit**:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pgtest1
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgtest2
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: postgres:alpine
        imagePullPolicy: IfNotPresent
        name: container-0
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: vol-pbhtp
      restartPolicy: Always
      volumes:
      - name: vol-pbhtp
        persistentVolumeClaim:
          claimName: pvc-pgtest1
```

**Logs to submit**:

[rook-ceph-operator-56c65d67c5-stnbn_rook-ceph-operator.log](https://github.com/rook/rook/files/9525955/rook-ceph-operator-56c65d67c5-stnbn_rook-ceph-operator.log)

[csi-cephfsplugin-p7vmf_csi-cephfsplugin.log](https://github.com/rook/rook/files/9525953/csi-cephfsplugin-p7vmf_csi-cephfsplugin.log)

**Environment**:
* OS (e.g. from /etc/os-release): NixOS 22.05 (Quokka)
* Kernel (e.g. `uname -a`): `Linux k3s-server03 5.15.58 #1-NixOS SMP Fri Jul 29 15:25:34 UTC 2022 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: VM on Hetzner Cloud.
* Rook version (use `rook version` inside of a Rook Pod): v1.9.10
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.10 (45fa1a083152e41a408d15505f594ec5f1b4fe17) pacific (stable)
* Kubernetes version (use `kubectl version`): 
  ```
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"1970-01-01T01:01:01Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
  ```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

@moduon MT-1075

**Comment by yajo** [comment]
Yes, please.

FWIW I managed to workaround it by applying this [patch](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/) after rook is deployed:

```yaml
spec:
  template:
    spec:
      containers:
        - name: csi-cephfsplugin
          volumeMounts:
            - name: host-nix-store
              mountPath: /nix/store
              readOnly: true
      volumes:
        - name: lib-modules
          hostPath:
            path: /run/current-system/kernel-modules/lib/modules/
        - name: host-nix-store
          hostPath:
            path: /nix/store
```

My guess is that NixOS will always need some specific details like this. I wouldn't be surprised if I find more similar scenarios.

Do you think it'd be helpful to add some flag to the helm chart such as `specialOS=NixOS`? Or maybe the operator can detect automatically on which OS it's running and apply the specificities automatically?
