### ISSUE TITLE
rook-ceph-osd-prepare-set1-data status Pending

### ISSUE THREAD

**Issue by gouki777** [rook/rook#10947]
**Deviation from expected behavior:**

rook-ceph-osd-prepare-set1-data status Pending

**Expected behavior:**
rook-ceph-osd-prepare-set1-data status running
I don't know, How to modify the configuration cluster-on-local-pvc.yaml  

**How to reproduce it (minimal and precise):**
I just have follow the quickstart.

```
1. git clone -b v1.9.9 https://github.com/rook/rook.git
2. kubectl create -f crds.yaml -f common.yaml -f operator.yaml
3. kubectl create -f cluster-on-local-pvc.yaml


# kubectl  get po -n rook-ceph 
NAME                                                              READY   STATUS    RESTARTS   AGE
rook-ceph-mgr-a-6c858f6b55-5sgrf                                  2/2     Running   0          8m35s
rook-ceph-mon-a-8559479b59-fbhkm                                  1/1     Running   0          10m
rook-ceph-mon-b-6889fdc5b-jdz5h                                   1/1     Running   0          9m7s
rook-ceph-mon-c-6b59d44689-p5vvh                                  1/1     Running   0          8m51s
rook-ceph-operator-54d57df748-mqgv4                               1/1     Running   0          11m
rook-ceph-osd-prepare-set1-data-04ttfq-cs8v6                      0/1     Pending   0          7m3s
rook-ceph-osd-prepare-set1-data-1vr9cn-hrc6n                      0/1     Pending   0          7m2s
rook-ceph-osd-prepare-set1-data-26966j-n5dc9                      0/1     Pending   0          7m2s


# kubectl describe po -n rook-ceph rook-ceph-osd-prepare-set1-data-2c9kdl-2lrx9 
Name:                 rook-ceph-osd-prepare-set1-data-2c9kdl-2lrx9
Namespace:            rook-ceph
.................................................
Tolerations:     op=Exists
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  3m42s  default-scheduler  0/14 nodes are available: 14 node(s) didn't find available persistent volumes to bind.
  Warning  FailedScheduling  3m42s  default-scheduler  0/14 nodes are available: 14 node(s) didn't find available persistent volumes to bind.
```

**File(s) to submit**:
* cluster-on-local-pvc.yaml
```
# cat cluster-on-local-pvc.yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /data/cephdb
  mon:
    count: 3
    allowMultiplePerNode: false
    tolerations:
    - operator: "Exists"
    volumeClaimTemplate:
      spec:
        storageClassName: ceph-storage
        resources:
          requests:
            storage: 3500Gi
  cephVersion:
    image: ceph/ceph:v16.2.10
    allowUnsupported: false
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mgr:
    count: 1
    tolerations:
    - operator: "Exists"
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    ssl: false
  crashCollector:
    disable: false
  storage:
    storageClassDeviceSets:
      - name: set1
        count: 3
        portable: true
        tuneDeviceClass: true
        tuneFastDeviceClass: false
        encrypted: false
        placement:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd
        preparePlacement:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd-prepare
                  topologyKey: kubernetes.io/hostname
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd-prepare
          tolerations:
          - operator: "Exists"
		  .............................................
```
**Logs to submit**:

* rook-ceph-osd-prepare-set1 yaml
```
#kubectl  get jobs -n rook-ceph rook-ceph-osd-prepare-set1-data-2c9kdl -oyaml
...................................................
  name: rook-ceph-osd-prepare-set1-data-26966j
  namespace: rook-ceph
      labels:
        app: rook-ceph-osd-prepare
        ceph.rook.io/DeviceSet: set1
        ceph.rook.io/pvc: set1-data-2c9kdl
        controller-uid: f5f4848f-b42a-4789-ba13-57bbc38e2fe4
        job-name: rook-ceph-osd-prepare-set1-data-2c9kdl
        rook_cluster: rook-ceph
      name: rook-ceph-osd
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
...........................................
      tolerations:
      - operator: Exists
      topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
```

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 7.9.2009 (Core)
* Kernel (e.g. uname -a): 3.10.0-1160.66.1.el7.x86_64
* Cloud provider or hardware configuration: Physical machine servers
* Rook version (use rook version inside of a Rook Pod): quay.io/ceph/ceph:v16.2.10
* Storage backend version (e.g. for ceph do ceph -v): quay.io/ceph/ceph:v16.2.10
* Kubernetes version (use kubectl version): v1.19.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE

**Comment by travisn** [comment]
What is the status of the `PersistentVolume`s created in cluster-on-local-pvc.yaml? They must not be binding to the PVCs requested by Rook for the OSDs. Did you also update the PVs for the host names and devices on your nodes? For example, this example likely doesn't match your cluster:
```yaml
  local:
    path: /dev/sdc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - host0
```
