### ISSUE TITLE
How to expose rook-ceph-rgw to an external application outside the k8s cluster

### ISSUE THREAD

**Issue by xyxjames** [rook/rook#11097]
Hi there, I have successfully deployed ceph on my k8s cluster using rook, but I encountered a problem when trying to access **rook-ceph-rgw-my-store-external** from an external application (outside the k8s cluster) according to [this](https://rook.io/docs/rook/v1.10/Storage-Configuration/Object-Storage-RGW/object-storage/#access-external-to-the-cluster) part of the official documentation, where the service did not expose its external IP. I would like to know how to correctly access the service from outside the k8s cluster.
![Screen Shot 2022-10-04 at 3 45 35 PM](https://user-images.githubusercontent.com/101579833/193763417-1a673600-9d2d-44f5-864e-25bf01cd7e9a.png)

Best regards,
James

**Comment by chaojin0310** [comment]
I've encountered the exact same problem before. I'd like to know how to make it, too.

**Comment by travisn** [comment]
At the end of that section in the document it says: "All you need is the hostname for any machine in the cluster, the external port, and the user credentials." So instead of the external-ip field on the service, use the IP of a host and combine it with the node port, for example: http://host:31277

That example uses a node port service. There are other methods such as an ingress or load balancer as shown in the examples for the [external dashboard access](https://rook.io/docs/rook/latest/Storage-Configuration/Monitoring/ceph-dashboard/#viewing-the-dashboard-external-to-the-cluster).

**Comment by abh** [comment]
We use an ingress similar to this

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: object-ingress
  namespace: rook-ceph
spec:
  rules:
  - host: objects.example.org
    http:
      paths:
      - backend:
          service:
            name: rook-ceph-rgw-my-store
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: '*.objects.example.org'
    http:
      paths:
      - backend:
          service:
            name: rook-ceph-rgw-my-store
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - objects.example.org
    - '*.objects.example.org'
    secretName: objects.example.org-tls
```
