### ISSUE TITLE
Readiness probe endpoint for RGW returns 404

### ISSUE THREAD

**Issue by mikelsid** [rook/rook#11286]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
rgw container fails to start due to readiness probe returning 404

**Expected behavior:**
container starts normally 

**How to reproduce it (minimal and precise):**

Apply attached CR on rook v1.10.5

**File(s) to submit**:

* ObjectStore CR:
``` yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: rgw-test-01
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
  dataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
  preservePoolsOnDelete: false
  gateway:
    instances: 1
    port: 80
  healthCheck:
    readinessProbe:
      disabled: false
```

**Logs to submit**:
* Crashing pod(s) logs, if necessary
``` sh
kubectl describe pod/rook-ceph-rgw-rgw-test-a-5f7dc8c557-fvgh7
...
    Readiness:  http-get http://:80/swift/healthcheck delay=10s timeout=1s period=10s #success=1 #failure=3
...
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  8m10s                   default-scheduler  Successfully assigned rook-ceph/rook-ceph-rgw-rgw-test-a-5f7dc8c557-fvgh7 to rook-01
  Normal   Pulled     8m9s                    kubelet            Container image "quay.io/ceph/ceph:v17.2.5-20221017" already present on machine
  Normal   Created    8m9s                    kubelet            Created container chown-container-data-dir
  Normal   Started    8m9s                    kubelet            Started container chown-container-data-dir
  Normal   Pulled     8m9s                    kubelet            Container image "quay.io/ceph/ceph:v17.2.5-20221017" already present on machine
  Normal   Created    8m9s                    kubelet            Created container rgw
  Normal   Started    8m9s                    kubelet            Started container rgw
  Normal   Pulled     8m9s                    kubelet            Container image "quay.io/ceph/ceph:v17.2.5-20221017" already present on machine
  Normal   Created    8m9s                    kubelet            Created container log-collector
  Normal   Started    8m8s                    kubelet            Started container log-collector
  Warning  Unhealthy  2m59s (x34 over 7m58s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 404
```

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): 1.10.5
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
* Kubernetes version (use `kubectl version`):  v1.24.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE
