### ISSUE TITLE
Cannot mount resized CephFS-PVC

### ISSUE THREAD

**Issue by ibotty** [rook/rook#11344]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I cannot start a new container with the same pvc as a running container.  Its events include the following.
```
  Warning  VolumeResizeFailed  2m2s   kubelet            NodeExpandVolume.NodeExpandVolume failed for volume "pvc-ac2174e8-8e9a-4c31-832e-a845d7cd3280" : Expander.NodeExpand found CSI plugin kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com to not support node expansion
```

The PVC had been resized before after running into quota issues.  The new quota is reflect in the running container and the `csi-cephfsplugin-provisioner`s `csi-resizer` signals success.
```
I1123 10:36:53.109592       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"mail", Name:"dovecot-mail-storage", UID:"ac2174e8-8e9a-4c31-832e-a845d7cd3280", APIVersion:"v1", ResourceVersion:"990884444", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-ac2174e8-8e9a-4c31-832e-a845d7cd3280
I1123 10:36:53.293116       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"mail", Name:"dovecot-mail-storage", UID:"ac2174e8-8e9a-4c31-832e-a845d7cd3280", APIVersion:"v1", ResourceVersion:"990884444", FieldPath:""}): type: 'Normal' reason: 'VolumeResizeSuccessful' Resize volume succeeded
```

The `csi-cephfsplugin`'s `csi-cephfsplugin` on the node does not log anything, unfortunately.

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

https://paste.centos.org/view/726281a7

**Cluster Status to submit**:

Note, that that happened also when the status was `HEALTH_OK`.  I am writing non-stop on this cephfs volume ATM and it flips from `HEALTH_OK` to `HEALTH_WARN` with `MDS_TRIM` continuously.  I guess it's unrelated.

```
ceph -s
  cluster:
    id:     08f51f08-9551-488f-9419-787a7717555e
    health: HEALTH_WARN
            2 MDSs behind on trimming

  services:
    mon: 5 daemons, quorum dt,dv,dx,dy,dz (age 5d)
    mgr: b(active, since 5d), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 10 osds: 10 up (since 5d), 10 in (since 2w); 12 remapped pgs
    rgw: 2 daemons active (2 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   15 pools, 401 pgs
    objects: 4.55M objects, 1.8 TiB
    usage:   5.4 TiB used, 21 TiB / 26 TiB avail
    pgs:     91605/13646406 objects misplaced (0.671%)
             389 active+clean
             12  active+remapped+backfilling

  io:
    client:   36 MiB/s rd, 33 MiB/s wr, 149 op/s rd, 428 op/s wr
    recovery: 23 MiB/s, 131 objects/s
```

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`): `Linux <redacted> 6.0.5-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 26 15:55:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Rook version (use `rook version` inside of a Rook Pod): `rook v1.10.6`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)`
* Kubernetes version (use `kubectl version`):
```
Server Version: 4.11.0-0.okd-2022-11-05-030711
Kubernetes Version: v1.24.0-2566+5157800f2a3bc3-dirty
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): `WARN`
