### ISSUE TITLE
One set of pools for RGWs isolated by namespaces

### ISSUE THREAD

**Issue by CalmVibes** [rook/rook#11411]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The ability to create muliple RADOS objectstores using one set of pools, isolated with the help of Rados namespaces. More detailed information in [the Issue 10805](https://github.com/rook/rook/issues/10805) beginning from [this comment](https://github.com/rook/rook/issues/10805#issuecomment-1339972999)

For example, instead of these defaults:
```
    "user_email_pool": "ceph-objectstore-name.rgw.meta:users.email",
    "user_swift_pool": "ceph-objectstore-name.rgw.meta:users.swift",
    "user_uid_pool": "ceph-objectstore-name.rgw.meta:users.uid",
    "otp_pool": "ceph-objectstore-name.rgw.otp",
    "data_pool": "ceph-objectstore-name.rgw.buckets.data" 
```
	
a collection of objectstores could use pool names of the form:
```
    "user_email_pool": "collection.rgw.meta:ceph-objectstore-name.users.email",
    "user_swift_pool": "collection.rgw.meta:ceph-objectstore-name.users.swift",
    "user_uid_pool": "collection.rgw.meta:ceph-objectstore-name.users.uid",
    "otp_pool": "collection.rgw.otp:ceph-objectstore-name",
    "data_pool": "collection.rgw.buckets.data:ceph-objectstore-name"
```

**What is use case behind this feature:**
The ability to create muliple isolated RADOS object storages.

**Comment by hohoqq** [comment]
> @hohoqq Are you interested in implementing this feature, or asking for a community member to implement?

Unfortunately, I do not have the necessary knowledge and skills to implement this feature. I would like to ask a community member to implement it. How can I do this?

**Comment by travisn** [comment]
Rook maintainers have regular discussions on who is taking up issues so we will discuss, just not sure on a timeline yet.

**Comment by travisn** [comment]
@thotz Interested in taking a look?

**Comment by thotz** [comment]
A couple of questions wrt to this feature, I am guessing we just include the option to pool names in the ObjectStore CRD.
1.) Can we assume pool already exists for this use case, so that the complexity of creating pools can be removed from the ObjectStoreController?
2.) Do need to extend this feature for multisite, not sure how technically feasible this for multisite

**Comment by hohoqq** [comment]
@thotz Thank you for taking a look!

1) In my case, it is possible to use a pre-created set of pools, adding the necessary ObjectStores to them. And isolating ObjectStores due to different namespaces. 
2) And in my case, all these ObjectStores can be located in one zone. Therefore, there is no need to implement this function for multisite. But perhaps in the multisite case, the zone name can be used as the name for the set of pools. If I'm not mistaken now it is used one set of pools for all ObjectStores in one zone too. The isolation can be added for ObjectStores in one zone by using namespaces.

**Comment by travisn** [comment]
@BlaineEXE To follow up from [this comment](https://github.com/rook/rook/issues/10805#issuecomment-1404363274), I'm reluctant to use a CephBlockPool spec to avoid confusion between the pools used by the object store. We could make similar exceptions like for the .nfs pool, but this feels different to me. 

What if we allowed one object store to define the pool specs, and other object stores would then provide the name of the object store that owns the pools? Then we can avoid the separate CephBlockPool CR. Something like this in the object store spec:
```yaml
  radosNamespaces:
    # If true, create RADOS namespaces for this object store. 
    # Default is false, preserve the current behavior for backward compatibility.
    create: true
    # If blank, this object store will create the pools.
    # If the object store name is specified, require the pools to be created by
    # the othe object store, and create new RADOS namespaces for this object store in those pools. 
    objectStoreOwningPools: <name-of-object-store>
```
