### ISSUE TITLE
shouldn't fall back to creating lvm mode if only raw mode is supported.

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/rook#11438]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Rook creates raw mode OSD as possible and falls back to lvm mode if necessary. This logic doesn't work well if only raw mode is supported.

Let assumes the case that we try to create an OSD on top of LV and `osdsPerDevice` is >= 2. In this case, Rook first tries to create raw mode OSD and changes its mind to create lvm mode OSD because `osdsPerDevice` is only valid for lvm mode. However, this OSD creation fails because OSD on LV only supports raw mode.

Although I've not tried it yet, this logic can also be applied to OSD on `crypt` device.

**Expected behavior:**

Skip to creating OSD.

**How to reproduce it (minimal and precise):**

Create an OSD with the following cluster.yaml.

```
          storage:
            useAllNodes: false
            useAllDevices: false
            nodes:
              - name: "node0"
                devices:
                  - name: "/dev/vg0/data"
                    config:
                      osdsPerDevice: "3"
```

Ref.
https://github.com/rook/rook/pull/11301#issuecomment-1325809818
