### ISSUE TITLE
RBD Mirror Daemon reporting health warning

### ISSUE THREAD

**Issue by dexma-dev** [rook/rook#11485]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Daemons are reporting "WARNING" health status.

**Expected behavior:**
RBD mirror daemons should report "OK" health status for newly created daemon.

**How to reproduce it (minimal and precise):**
- Install operator helm chart
- create cluster
- cluster blockpool with mirroring enabled
- created rbd mirror daemon

**Cluster Health:**
```
cluster:
    id:     1c4fc90d-a87b-4348-8a20-ab9a26df7e37
    health: HEALTH_OK
 
  services:
    mon:        3 daemons, quorum a,b,c (age 53m)
    mgr:        b(active, since 52m), standbys: a
    osd:        6 osds: 6 up (since 49m), 6 in (since 3h)
    rbd-mirror: 2 daemons active (2 hosts)
 
  data:
    pools:   3 pools, 3 pgs
    objects: 16 objects, 577 KiB
    usage:   72 MiB used, 32 TiB / 32 TiB avail
    pgs:     3 active+clean
```

**BlockPool CRD**:
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: pool-name
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
  deviceClass: hdd
  mirroring:
    enabled: true
    mode: image

```

**RBDMirror CRD:**
```
apiVersion: ceph.rook.io/v1
kind: CephRBDMirror
metadata:
  name: rbd-mirror
  namespace: rook-ceph
spec:
  count: 2
```

Output of `rbd mirror pool status pool-name --verbose`:
```
health: WARNING
daemon health: WARNING
image health: OK
images: 0 total

DAEMONS
service 10659974:
  instance_id: 
  client_id: a
  hostname: node-16
  version: 17.2.5
  leader: false
  health: OK

service 10660004:
  instance_id: 
  client_id: a
  hostname: node-14
  version: 17.2.5
  leader: false
  health: OK

IMAGES
```

After a freshly created cluster and blockpools I tried to setup rbd mirroring and followed the corresponding setup in the [rook documentation](https://rook.io/docs/rook/v1.9/Storage-Configuration/Block-Storage-RBD/rbd-mirroring/). 
After that the status of the mirroring daemons are `"WARNING"` and I am not able to find a reason for that.

What could be the reasons for the state and where can I find some information on this?

Thanks an BR
