### ISSUE TITLE
Error mounting a volume "rpc error: code = Internal desc = missing required field monitors"

### ISSUE THREAD

**Issue by ilclaudio** [rook/rook#11504]
When I try to create:

- a volume: **wp-dev-volume-backup** (with the storage class: **rook-cephfs**)
- a persistent volume claim: **wp-dev-pvc-backup** 
- a sidecar: **backup-sidecar** (that mounts the previously created volume)
 with this command:

```
kubectl apply -f .\test.yaml 
persistentvolume/wp-dev-volume-backup created
persistentvolumeclaim/wp-dev-pvc-backup created
deployment.apps/backup-sidecar created
```

I have this error:
```
20s         Normal    SuccessfulAttachVolume   pod/backup-sidecar-7896b7c9fd-s7f7z       AttachVolume.Attach succeeded for volume "wp-dev-volume-backup"
1s          Warning   FailedMount              pod/backup-sidecar-7896b7c9fd-s7f7z       MountVolume.MountDevice failed for volume "wp-dev-volume-backup" : rpc error: code = Internal desc = rpc error: code = Internal desc = missing required field monitors
```
It seems that the volume is attacched but it is **not mounted**.

All the items are defined in the file **test.yaml**:
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph.cephfs.csi.ceph.com
    volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-cephfs-provisioner
    volume.kubernetes.io/provisioner-deletion-secret-namespace: rook-ceph
  finalizers:
  - kubernetes.io/pv-protection
  name: wp-dev-volume-backup
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: wp-dev-pvc-backup
    namespace: wordpress-dev
  csi:
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: cephfs
      pool: cephfs-replicated
    volumeHandle: wp-dev-volume-backup
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
    volume.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
  creationTimestamp: "2023-01-05T09:34:57Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: wp-dev-pvc-backup
  namespace: wordpress-dev
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  volumeName: wp-dev-volume-backup
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-wordpress-dev-backup-sidecar  
  name: backup-sidecar
  namespace: wordpress-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-wordpress-dev-backup-sidecar
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-wordpress-dev-backup-sidecar
    spec:
      affinity: {}
      containers:
      - image: php:fpm
        imagePullPolicy: Always
        name: container-0
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /backup
          name: volume-backup
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: volume-backup
        persistentVolumeClaim:
          claimName: wp-dev-pvc-backup
---
```

If I create the volume, the pvc and the container from Rancher it works and the volume is mounted, but if I use kubectl and the yaml files I have the previous error. I have to use yaml files because I'm creating an Helm chart.

**Environment**:
I'm using Rancher/Kubernetes on the Azure cloud:

* Rancher: v2.6.9
* Kubernetes: v1.24.3
*  Rook version: v1.10.7
* Ceph: v17.2.5
* csi-node-driver-registrar: v2.5.1

**Comment by Madhu-1** [comment]
Please increase the log level to `5` and paste the new logs. if you are using static PVC please refer to https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md#cephfs-static-pvc , look like you are missing to set `"staticVolume": "true"` in PV volumeAttributes

**Comment by claudiobat** [comment]
Thank you.
It seems that to create a static pvc I should set parameters like: staticVolume and rootPath.
But I do not want to create before the PV  by hand.

In other words, if I set these volume attributes:

```
volumeAttributes:
  clusterID: rook-ceph
  fsName: cephfs
  pool: cephfs-replicated
  staticVolume: "true"
  imageFeatures: "layering"
  rootPath: ????

```
I don't know what to write in rootPath.
The reason why I need to specify the properties of the volume is that I have to force:
`persistentVolumeReclaimPolicy: Retain`
Otherwise I would have let the PV be created by the PVC.

cld
