### ISSUE TITLE
Cannot create readWriteMany PVC due to FIPS error

### ISSUE THREAD

**Issue by kevinlmadison** [rook/rook#11531]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Creating a readWriteMany PVC backed by the default `ceph-filesystem` results in k8s throwing a traceback that seems to indicate something about fips.

**Expected behavior:**
PVC should be created 

**How to reproduce it (minimal and precise):**

1. Deploy Rook-Ceph with Helm
2. Deploy Rook-Ceph-Cluster with Helm (this values.yaml is pasted below)
3. Deploy the following PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ziti-volume
  namespace: admin
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-filesystem
```
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
Deploy Cluster with Helm as well
```
      operatorNamespace: rook-ceph
      toolbox:
        enabled: true
      cephClusterSpec:
        cephVersion:
          image: quay.io/ceph/ceph:v16.2.10
          allowUnsupported: false
        dataDirHostPath: /var/lib/rook
        skipUpgradeChecks: false
        continueUpgradeAfterChecksEvenIfNotHealthy: false
        waitTimeoutForHealthyOSDInMinutes: 10
        mon:
          count: 3
          allowMultiplePerNode: false
        mgr:
          count: 2
          modules:
            - name: pg_autoscaler
              enabled: true
        dashboard:
          enabled: true
          ssl: true
        monitoring:
          enabled: false
          rulesNamespace: rook-ceph
        network:
        crashCollector:
          disable: false
        cleanupPolicy:
          confirmation: ""
          sanitizeDisks:
            method: quick
            dataSource: zero
            iteration: 1
          allowUninstallWithVolumes: false
        annotations:
        labels:
        resources:
        removeOSDsIfOutAndSafeToRemove: false
        storage: # cluster level storage configuration and selection
          useAllNodes: true
          useAllDevices: true
          deviceFilter: "^nvme.n1"
          config:
          onlyApplyOSDPlacement: false
        disruptionManagement:
          managePodBudgets: true
          osdMaintenanceTimeout: 30
          pgHealthCheckTimeout: 0
          manageMachineDisruptionBudgets: false
          machineDisruptionBudgetNamespace: openshift-machine-api
        healthCheck:
          daemonHealth:
            mon:
              disabled: false
              interval: 45s
            osd:
              disabled: false
              interval: 60s
            status:
              disabled: false
              interval: 60s
          livenessProbe:
            mon:
              disabled: false
            mgr:
              disabled: false
            osd:
              disabled: false
          startupProbe:
            mon:
              disabled: false
            mgr:
              disabled: false
            osd:
              disabled: false
```
**Logs to submit**:
```
k describe pvc -n admin ziti-volume

Events:
  Type     Reason                Age                   From                                                                                                              Message
  ----     ------                ----                  ----                                                                                                              -------
  Warning  ProvisioningFailed    21m (x14 over 40m)    rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-6c49559789-r7d2n_a461c043-49de-4abc-984d-3f57ed99ad06  failed to provision volume with StorageClass "ceph-filesystem": rpc error: code = Internal desc = rados: ret=-22, Invalid argument: "Traceback (most recent call last):\n  File \"/usr/share/ceph/mgr/mgr_module.py\", line 1446, in _handle_command\n    return self.handle_command(inbuf, cmd)\n  File \"/usr/share/ceph/mgr/volumes/module.py\", line 396, in handle_command\n    return handler(inbuf, cmd)\n  File \"/usr/share/ceph/mgr/volumes/module.py\", line 34, in wrap\n    return f(self, inbuf, cmd)\n  File \"/usr/share/ceph/mgr/volumes/module.py\", line 450, in _cmd_fs_subvolume_create\n    namespace_isolated=cmd.get('namespace_isolated', False))\n  File \"/usr/share/ceph/mgr/volumes/fs/volume.py\", line 171, in create_subvolume\n    with open_subvol(self.mgr, fs_handle, self.volspec, group, subvolname, SubvolumeOpType.CREATE) as subvolume:\n  File \"/usr/lib64/python3.6/contextlib.py\", line 81, in __enter__\n    return next(self.gen)\n  File \"/usr/share/ceph/mgr/volumes/fs/operations/subvolume.py\", line 72, in open_subvol\n    subvolume = loaded_subvolumes.get_subvolume_object(mgr, fs, vol_spec, group, subvolname)\n  File \"/usr/share/ceph/mgr/volumes/fs/operations/versions/__init__.py\", line 93, in get_subvolume_object\n    subvolume = SubvolumeBase(mgr, fs, vol_spec, group, subvolname)\n  File \"/usr/share/ceph/mgr/volumes/fs/operations/versions/subvolume_base.py\", line 38, in __init__\n    self.load_config()\n  File \"/usr/share/ceph/mgr/volumes/fs/operations/versions/subvolume_base.py\", line 129, in load_config\n    self.fs.stat(self.legacy_config_path)\n  File \"/usr/share/ceph/mgr/volumes/fs/operations/versions/subvolume_base.py\", line 78, in legacy_config_path\n    m = md5()\nValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS\n"
  Normal   Provisioning          2m39s (x19 over 40m)  rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-6c49559789-r7d2n_a461c043-49de-4abc-984d-3f57ed99ad06  External provisioner is provisioning volume for claim "admin/ziti-volume"
  Normal   ExternalProvisioning  7s (x162 over 40m)    persistentvolume-controller                                                                                       waiting for a volume to be created, either by external provisioner "rook-ceph.cephfs.csi.ceph.com" or manually created by system administrator
```
* Operator's logs, if necessary
These logs don't seem to have any relevance.
* Crashing pod(s) logs, if necessary
No crashing pods
