### ISSUE TITLE
Zapping device do not work on all nodes (only able to create 2 out of 3 osds)

### ISSUE THREAD

**Issue by whs-dot-hk** [rook/rook#11589]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
osd didn't start on k8s-2

**Expected behavior:**
3 osds started

**How to reproduce it (minimal and precise):**

Run zapping device on each of the 3 nodes https://rook.io/docs/rook/v1.10/Storage-Configuration/ceph-teardown/#zapping-devices
and delete the operator
```sh
sudo -i

apt-get update
apt-get install -y gdisk

sgdisk --zap-all /dev/sda
dd if=/dev/zero of=/dev/sda bs=1M count=100 oflag=direct,dsync
blkdiscard /dev/sda
partprobe /dev/sda
```
```sh
kubectl delete pod  -nrook-ceph -lapp=rook-ceph-operator
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
Cluster yaml: https://gist.github.com/whs-dot-hk/9227a8f71c268e48a641cd7311fbbdd5

**Logs to submit**:

* Operator's logs, if necessary
Before zapping nodes
```sh
kubectl get po -nrook-ceph
NAME                                              READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-6c47p                            2/2     Running     0          19m
csi-cephfsplugin-7zgwr                            2/2     Running     0          19m
csi-cephfsplugin-m2kzh                            2/2     Running     0          19m
csi-cephfsplugin-provisioner-75b9f74d7b-hg9qt     5/5     Running     0          19m
csi-cephfsplugin-provisioner-75b9f74d7b-hmf26     5/5     Running     0          19m
csi-rbdplugin-868f8                               2/2     Running     0          19m
csi-rbdplugin-8z2mb                               2/2     Running     0          19m
csi-rbdplugin-gzj42                               2/2     Running     0          19m
csi-rbdplugin-provisioner-66d48ddf89-cddmg        5/5     Running     0          19m
csi-rbdplugin-provisioner-66d48ddf89-hvxwr        5/5     Running     0          19m
rook-ceph-crashcollector-k8s-1-67d4c96f7-rb9xl    1/1     Running     0          13m
rook-ceph-crashcollector-k8s-2-58d86b69c6-59mrn   1/1     Running     0          13m
rook-ceph-crashcollector-k8s-3-6dbf9b96b7-8mnrq   1/1     Running     0          16m
rook-ceph-mgr-a-76597999bb-fjgpg                  3/3     Running     0          16m
rook-ceph-mgr-b-6769775f75-64974                  3/3     Running     0          13m
rook-ceph-mon-a-646b89b7b8-w275d                  2/2     Running     0          19m
rook-ceph-mon-b-9dd58fc9b-szbkj                   2/2     Running     0          19m
rook-ceph-mon-c-6c9f55b45b-xbglj                  2/2     Running     0          17m
rook-ceph-operator-677f8f4c47-wthgn               1/1     Running     0          23m
rook-ceph-osd-prepare-k8s-1-pjgjt                 0/1     Completed   0          14m
rook-ceph-osd-prepare-k8s-2-rqf7c                 0/1     Completed   1          15m
rook-ceph-osd-prepare-k8s-3-rd7zr                 0/1     Completed   0          14m
```
Operator log: https://gist.github.com/whs-dot-hk/75b69dfb4cd40328e89d85882deb24a5

After zapping device on each node and delete the operator
```sh
kubectl get po -nrook-ceph -owide
NAME                                              READY   STATUS      RESTARTS   AGE     IP             NODE    NOMINATED NODE   READINESS GATES
csi-cephfsplugin-6c47p                            2/2     Running     0          36m     172.18.8.103   k8s-3   <none>           <none>
csi-cephfsplugin-7zgwr                            2/2     Running     0          36m     172.18.8.101   k8s-1   <none>           <none>
csi-cephfsplugin-m2kzh                            2/2     Running     0          36m     172.18.8.102   k8s-2   <none>           <none>
csi-cephfsplugin-provisioner-75b9f74d7b-hg9qt     5/5     Running     0          36m     10.233.64.5    k8s-1   <none>           <none>
csi-cephfsplugin-provisioner-75b9f74d7b-hmf26     5/5     Running     0          36m     10.233.66.7    k8s-3   <none>           <none>
csi-rbdplugin-868f8                               2/2     Running     0          36m     172.18.8.101   k8s-1   <none>           <none>
csi-rbdplugin-8z2mb                               2/2     Running     0          36m     172.18.8.102   k8s-2   <none>           <none>
csi-rbdplugin-gzj42                               2/2     Running     0          36m     172.18.8.103   k8s-3   <none>           <none>
csi-rbdplugin-provisioner-66d48ddf89-cddmg        5/5     Running     0          36m     10.233.65.4    k8s-2   <none>           <none>
csi-rbdplugin-provisioner-66d48ddf89-hvxwr        5/5     Running     0          36m     10.233.66.6    k8s-3   <none>           <none>
rook-ceph-crashcollector-k8s-1-67db95bdcf-f69b2   1/1     Running     0          4m1s    10.233.64.16   k8s-1   <none>           <none>
rook-ceph-crashcollector-k8s-2-58d86b69c6-59mrn   1/1     Running     0          30m     10.233.65.9    k8s-2   <none>           <none>
rook-ceph-crashcollector-k8s-3-6f44bd7545-rxnkk   1/1     Running     0          3m53s   10.233.66.17   k8s-3   <none>           <none>
rook-ceph-mgr-a-76597999bb-fjgpg                  3/3     Running     0          32m     10.233.66.10   k8s-3   <none>           <none>
rook-ceph-mgr-b-6769775f75-64974                  3/3     Running     0          30m     10.233.64.12   k8s-1   <none>           <none>
rook-ceph-mon-a-646b89b7b8-w275d                  2/2     Running     0          36m     10.233.66.8    k8s-3   <none>           <none>
rook-ceph-mon-b-9dd58fc9b-szbkj                   2/2     Running     0          35m     10.233.65.5    k8s-2   <none>           <none>
rook-ceph-mon-c-6c9f55b45b-xbglj                  2/2     Running     0          33m     10.233.64.6    k8s-1   <none>           <none>
rook-ceph-operator-677f8f4c47-r9qpv               1/1     Running     0          4m36s   10.233.65.11   k8s-2   <none>           <none>
rook-ceph-osd-0-6bd85cb9-nbhlc                    2/2     Running     0          4m2s    10.233.64.15   k8s-1   <none>           <none>
rook-ceph-osd-1-7bf6dfc6-6459t                    2/2     Running     0          3m54s   10.233.66.16   k8s-3   <none>           <none>
rook-ceph-osd-prepare-k8s-1-cpfkk                 0/1     Completed   0          3m31s   10.233.64.17   k8s-1   <none>           <none>
rook-ceph-osd-prepare-k8s-2-98cl6                 0/1     Completed   0          3m28s   10.233.65.15   k8s-2   <none>           <none>
rook-ceph-osd-prepare-k8s-3-n2jsx                 0/1     Completed   0          3m24s   10.233.66.18   k8s-3   <none>           <none>
```
Operator log: https://gist.github.com/whs-dot-hk/633bcef1e2cb526f21cc01f5ea967d35

* Crashing pod(s) logs, if necessary
OSP prepare logs: https://gist.github.com/whs-dot-hk/9d26fedf8e371593e29c929ff28f4edf

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by whs-dot-hk** [comment]
I try futher default `cluster.yaml` with `useAllNodes` and `useAddDevices` works. Default `cluster-test.yaml` also works. And `cluster-test.yaml` works for both `name: sda` and LVM.
```yaml
#################################################################################################################
# Define the settings for the rook-ceph cluster with common settings for a small test cluster.
# All nodes with available raw devices will be used for the Ceph cluster. One node is sufficient
# in this example.

# For example, to create the cluster:
#   kubectl create -f crds.yaml -f common.yaml -f operator.yaml
#   kubectl create -f cluster-test.yaml
#################################################################################################################
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: rook-ceph # namespace:cluster
data:
  config: |
    [global]
    osd_pool_default_size = 1
    mon_warn_on_pool_no_redundancy = false
    bdev_flock_retry = 20
    bluefs_buffered_io = false
    mon_data_avail_warn = 10
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: my-cluster
  namespace: rook-ceph # namespace:cluster
spec:
  dataDirHostPath: /var/lib/rook
  cephVersion:
    image: quay.io/ceph/ceph:v17
    allowUnsupported: true
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  crashCollector:
    disable: true
  storage:
    useAllNodes: false
    useAllDevices: false
    #deviceFilter:
    nodes:
      - name: k8s-1
        devices:
          - name: /dev/vg1/lv1
      - name: k8s-2
        devices:
          - name: /dev/vg1/lv1
      - name: k8s-3
        devices:
          - name: /dev/vg1/lv1
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
        timeout: 600s
  priorityClassNames:
    all: system-node-critical
    mgr: system-cluster-critical
  disruptionManagement:
    managePodBudgets: true
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: builtin-mgr
  namespace: rook-ceph # namespace:cluster
spec:
  name: .mgr
  replicated:
    size: 1
    requireSafeReplicaSize: false
```
I am happy with the LVM option, therefore I close this issue.
