### ISSUE TITLE
Should service rook-ceph-mgr always "bind" to mgr-a?

### ISSUE THREAD

**Issue by mnlipp** [rook/rook#11638]
* Bug Report

**Deviation from expected behavior:**

The example for [ceph mgr monitoring](https://github.com/rook/rook/blob/master/deploy/examples/monitoring/service-monitor.yaml) with Prometheus explicitly selects (monitors) `ceph_daemon_id: a` (yaml abbreviated).

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
spec:
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook-ceph
      ceph_daemon_id: a
```

I have restarted some nodes and now the service `ceph-mgr-service` created by rook selects mgr-b (and has label `ceph_daemon_id: b`).

```
kind: Service
apiVersion: v1
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph
  labels:
    app: rook-ceph-mgr
    ceph_daemon_id: b
    rook_cluster: rook-ceph
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 9283
      targetPort: 9283
  selector:
    app: rook-ceph-mgr
    ceph_daemon_id: b
    rook_cluster: rook-ceph
```

Thus, the currently active ceph-mgr (b) is not monitored by Prometheus.

**Expected behavior:**

The "active" ceph-mgr should be monitored.

So, either something's wrong with the rook-ceph-mgr service defined by rook (if the intend is that it alway has label "a") or the selector of the ServiceMonitor should be less restrictive.
