### ISSUE TITLE
could not write to mounted volume when using non-root user (same when using fsGroup)

### ISSUE THREAD

**Issue by devops-lab** [rook/rook#11649]
* Bug Report
I hope I miss something, but could not find answer anywhere. I am using ROOK storage class resource to provision PV that are later attached to POD. in example adding 3 volumes (1 emptyDir, and 2 volumes from ROOK cluster) 

test.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  namespace: misc
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: keymanager-keys
    persistentVolumeClaim:
      claimName: keymanager-pvc
      readOnly: false
  - name: local-keys
    emptyDir: {}
  - name: ephemeral-storage
    ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteMany"]
          storageClassName: "ceph-filesystem"
          resources:
            requests:
              storage: 10Mi
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: keymanager-keys
      mountPath: /data/demo
    - name: local-keys
      mountPath: /data/demo2
    - name: ephemeral-storage
      mountPath: /data/demo3
```

POD information:

```
kubectl get pods -n misc

NAME                                           READY   STATUS      RESTARTS       AGE
security-context-demo                          1/1     Running     15 (30m ago)   15h

kubectl exec -it -n misc  security-context-demo -- sh

/ $ ls -la /data/
total 12
drwxr-xr-x    5 root     root          4096 Feb 10 06:08 .
drwxr-xr-x    1 root     root          4096 Feb 10 06:08 ..
drwxr-xr-x    2 root     root             0 Feb  9 11:29 demo
drwxrwsrwx    2 root     2000          4096 Feb  9 15:08 demo2
drwxr-xr-x    2 root     root             0 Feb  9 15:08 demo3
```

demo and demo3 directories are not mounted as expected to group 2000.  

**Expected behavior:**

would like to see mounted volumes to specific group  (that will be used by unprivileged users). Don't know weather doing something wrong or what is happening please let me know. Expecting to be able to write to mounted volume with app user. 

**Environment**:
* OS (e.g. from /etc/os-release): Debian GNU/Linux 11 (bullseye)
* Kernel (e.g. `uname -a`): Linux worker1 5.10.0-9-amd64 1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod):  v1.10.6
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
* Kubernetes version (use `kubectl version`): v1.24.1
*   ```
cluster:
    id:     25e0134a-515e-4f62-8eec-ae5d8cb3e650
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,c,d (age 7w)
    mgr: a(active, since 10w)
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 11w), 3 in (since 11w)
    rgw: 1 daemon active (1 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   12 pools, 185 pgs
    objects: 421 objects, 1.2 MiB
    usage:   1.5 GiB used, 249 GiB / 250 GiB avail
    pgs:     185 active+clean

```

if needed more information let me know and I will update this post.

**Comment by Madhu-1** [comment]
@devops-lab, you are missing securityContext at container spec. please set it and try

**Comment by devops-lab** [comment]
@Madhu-1 what kind of securityContext in container spec? fsGroup is only for POD spec. 
container securityContext spec (container spec are mainly for overriding POD spec):  
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#securitycontext-v1-core

**Comment by devops-lab** [comment]
does ROOK even support fsGroup override for shared filesystem? 

tested with **block storage** - All good. Storage class provisioned PV and fsGroup parameter changed permissions. However I would like to see shared file storage to work with fsGroup securityContext. I know it is possible to use init container to override directory permissions, but want to avoid that solution as it seems more like workaround and not a correct approach.

**Comment by Madhu-1** [comment]
@devops-lab, yes, it should work for cephfs also.

**Comment by devops-lab** [comment]
@Madhu-1 what kind of securityContext in container spec you were talking earlier? I could try to set it, if it helps to debug and determine why fsGroup override is not triggered.  

any other ideas which part could be wrong?

**Comment by Madhu-1** [comment]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#securitycontext-v1-core is for the containers, which helps.

**Comment by devops-lab** [comment]
it is same link I posted above. tied multiple parameter combinations.  
thanks for quick responses. would be good if you can be more specific which line/key helps from that documentation please.  

here is example what modified as you suggested but still same output: 
```

apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  namespace: misc
spec:
  securityContext:
#    runAsUser: 1000
#    runAsGroup: 3000
    fsGroup: 2000
#   runAsNonRoot: true
  volumes:
  - name: keymanager-keys
    persistentVolumeClaim:
      claimName: keymanager-pvc
      readOnly: false
  - name: keymanager-keyblock
    persistentVolumeClaim:
      claimName: keymanager-block-pvc
      readOnly: false
  - name: keymanager-key-n
    persistentVolumeClaim:
      claimName: keymanager-ext4x-pvc
      readOnly: false
  - name: local-keys
    emptyDir: {}
  - name: ephemeral-storage
    ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteMany"]
          storageClassName: "ceph-filesystem"
          resources:
            requests:
              storage: 10Mi
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
      allowPrivilegeEscalation: true
      privileged: false
      runAsNonRoot: true
    volumeMounts:
    - name: keymanager-keys
      mountPath: /data/pvc-filesystem-preconfigured
    - name: local-keys
      mountPath: /data/emptydir
    - name: ephemeral-storage
      mountPath: /data/pvc-filesystem-ephemeral-storage
    - name: keymanager-keyblock
      mountPath: /data/pvc-block-storage
    - name: keymanager-key-n
      mountPath: /data/testing-with-fstypes
```
container: 

```
kubectl exec -it security-context-demo -n misc -- sh
/ $ id
uid=1000 gid=3000 groups=2000
/ $ ls -al /data/
total 13
drwxr-xr-x    7 root     root          4096 Feb 17 07:49 .
drwxr-xr-x    1 root     root          4096 Feb 17 07:49 ..
drwxrwsrwx    2 root     2000          4096 Feb 17 07:48 emptydir
drwxrwsr-x    3 root     2000          1024 Feb 13 07:08 pvc-block-storage
drwxr-xr-x    2 root     root             0 Feb 17 07:48 pvc-filesystem-ephemeral-storage
drwxr-xr-x    2 root     root             0 Feb 17 07:47 pvc-filesystem-preconfigured
drwxr-xr-x    2 root     root             0 Feb 17 07:40 testing-with-fstypes

```
as you can see fallowing mounts are still mounted as root: 
`pvc-filesystem-ephemeral-storage,  pvc-filesystem-preconfigured, testing-with-fstypes`
