### ISSUE TITLE
4 node 4+2 erasure coding pool

### ISSUE THREAD

**Issue by echel0n-TR** [rook/rook#11650]
How would you create a 4 node erasure coding pool of 4+2 with Rook?

**Comment by travisn** [comment]
See the [documentation on erasure coding](https://rook.io/docs/rook/latest/CRDs/Block-Storage/ceph-block-pool-crd/#erasure-coding) and the example for an [erasure coded pool](https://github.com/rook/rook/blob/release-1.10/deploy/examples/pool-ec.yaml). From your description I believe you would want this:
```yaml
  failureDomain: osd
  erasureCoded:
    dataChunks: 4
    codingChunks: 2
```
This requires at least 6 OSDs.

**Comment by echel0n-TR** [comment]
would this profile allow for loss of 1 node from the 4 ?

**Comment by travisn** [comment]
You can lose 2 chunks and still recover the data. If you have exactly two OSDs per node that would work, but if you have 3 or more OSDs per node, you might end up with 3 chunks on the same node. If you want node toleration, you might consider need a schema like this, which is tolerant to lose two nodes:
```
  failureDomain: host
  erasureCoded:
    dataChunks: 2
    codingChunks: 2
```
