### ISSUE TITLE
podAntiAffinity rule too broad in examples/filesystem.yaml

### ISSUE THREAD

**Issue by mnlipp** [rook/rook#11658]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

After adding a second filesystem to a three node cluster, ceph showed a health warning that the second mds daemon of one of the filesystems was missing.

It turned out that the rook operator had created the deployment, but the daemon could not be placed due to (`examples/filesystem.yaml`):

```
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - rook-ceph-mds
```

I *do* understand that placing only one mds daemon on a node is a good approach if you have a large cluster with heavy loads. However, if you have the cluster mostly for HA and with few but powerful machines, it's no problem to have several mds on a machine, at least as long as they handle different filesystems.

**Expected behavior:**

It should be possible to have more than one filesystem without requiring twice the number of nodes.

So I came up with:

```
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - rook-ceph-mds
                - key: rook_file_system
                  operator: In
                  values:
                    - myfs
```

Of course, it is annoying to have the name of the filesystem (again) in `values`, so maybe this should not be added to the example (or with a reference from `name` to the relevant part of the `podAntiAffinity` section). But at least the (possible) problem should be mentioned somewhere to warn the users and avoid surprises with more than one filesystem.
