### ISSUE TITLE
Add Labels and Annotations to rook-ceph-mgr ServiceMonitor from values.yaml

### ISSUE THREAD

**Issue by jameshearttech** [rook/rook#11696]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
* Add labels and annotations to rook-ceph-mgr servicemonitor from values.yaml.

**What is use case behind this feature:**
* Add label to rook-ceph-mgr servicemonitor so it can be scraped by prometheus (i.e., kube-prometheus-stack).

**Environment**:

```
$ kubectl get node -o wide
NAME          STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
dev-master0   Ready    control-plane   31d   v1.26.0   10.69.2.30    <none>        Ubuntu 22.04.1 LTS   5.15.0-58-generic   containerd://1.6.15
dev-master1   Ready    control-plane   31d   v1.26.0   10.69.2.31    <none>        Ubuntu 22.04.1 LTS   5.15.0-58-generic   containerd://1.6.15
dev-master2   Ready    control-plane   31d   v1.26.0   10.69.2.32    <none>        Ubuntu 22.04.1 LTS   5.15.0-58-generic   containerd://1.6.15
dev-worker0   Ready    <none>          31d   v1.26.0   10.69.2.33    <none>        Ubuntu 22.04.1 LTS   5.15.0-58-generic   containerd://1.6.15
dev-worker1   Ready    <none>          31d   v1.26.0   10.69.2.34    <none>        Ubuntu 22.04.1 LTS   5.15.0-58-generic   containerd://1.6.15
dev-worker2   Ready    <none>          31d   v1.26.0   10.69.2.35    <none>        Ubuntu 22.04.1 LTS   5.15.0-58-generic   containerd://1.6.15
dev-worker3   Ready    <none>          31d   v1.26.0   10.69.2.36    <none>        Ubuntu 22.04.1 LTS   5.15.0-58-generic   containerd://1.6.15
```

**Comment by travisn** [comment]
Try adding the [labels.monitoring](https://github.com/rook/rook/blob/release-1.10/deploy/examples/cluster.yaml#L194) to the values.yaml for the rook-ceph-cluster chart. Any setting from the CephCluster CR can be added under the `cephClusterSpec` in the chart.

**Comment by jameshearttech** [comment]
Something like this?

```
cephClusterSpec:
  # https://github.com/rook/rook/issues/11696
  # https://rook.io/docs/rook/v1.10/CRDs/Cluster/ceph-cluster-crd/#annotations-and-labels
  # monitoring: Set annotations / labels for service monitor
  labels:
    monitoring:
      release: kube-prometheus-stack
```
