### ISSUE TITLE
1.11.0 broken with hostnetwork due to new ports on pod from #11578

### ISSUE THREAD

**Issue by taxilian** [rook/rook#11792]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
With 1.11.0 every pod defines port 6800 and possibly 6801 as of #11578 -- if you have host networking enabled then OSDs are started on the host network and only one pod can use any given port on the same network interface, thus only one OSD or MGR pod (the MGR pod already claims port 6800) can start on any given node.

**Expected behavior:**
You should be able to run many OSDs on the same node without having kubernetes refuse to start them up due to port unavailability =]

**How to reproduce it (minimal and precise):**

* Install Rook with `spec.network.provider: host` on 1.11.0 with multiple OSDs on one host

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs**:

kubectl describe pod on the OSDs stuck in "Pending" state says:

```Warning  FailedScheduling  18m (x4 over 18m)  default-scheduler  0/8 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 7 node(s) didn't match Pod's node affinity/selector. preemption: 0/8 nodes are available: 1 No preemption victims found for incoming pod, 7 Preemption is not helpful for scheduling..```

**Comment by reefland** [comment]
Using Chart `v1.11.0` with image tag override `v1.11.0-14.gd70d8ad60`.   Using host networking. All my nodes have at least one OSD.

Applied this and still have both MGRs down and nodes with more than one OSD has OSDs down (only one OSD up).  I tried to delete the respective pods having issues, new ones have same issue. 

mgr events:
```
0/6 nodes are available: 6 node(s) didn't have free ports for the requested pod ports. preemption: 0/6 nodes are available: 6 node(s) didn't have free ports for the requested pod ports.
```

osd events:
```
0/6 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 5 node(s) didn't match Pod's node affinity/selector. preemption: 0/6 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 5 Preemption is not helpful for scheduling.
```

```
# ceph -s
  cluster:
    id:     cb82340a-2eaf-4597-b83e-cc0e62a9d019
    health: HEALTH_WARN
            no active mgr
            Degraded data redundancy: 19877/91515 objects degraded (21.720%), 69 pgs degraded
 
  services:
    mon: 3 daemons, quorum b,c,d (age 4h)
    mgr: no daemons active (since 4h)
    mds: 1/1 daemons up, 1 hot standby
    osd: 7 osds: 6 up (since 67m), 6 in (since 65m)
    rgw: 1 daemon active (1 hosts, 1 zones)

# ceph -v
ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
```

**Comment by taxilian** [comment]
That's strange.

```
rook-ceph-operator   1/1     1            1           542d   rook-ceph-operator   rook/ceph:v1.11.0-14.gd70d8ad60   app=rook-ceph-operator
```

```
$ k rook-ceph ceph -v
ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
```

```
$ k rook-ceph ceph status                                                                                                                        ✹master  (arm64)
  cluster:
    id:     0e85e9cf-632e-4737-9f94-6c0429444fe2
    health: HEALTH_OK

  services:
    mon: 5 daemons, quorum ax,bc,bf,bh,bi (age 75m)
    mgr: b(active, since 71m), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 40 osds: 40 up (since 44m), 40 in (since 2d)
    rgw: 4 daemons active (3 hosts, 2 zones)

  data:
    volumes: 1/1 healthy
    pools:   29 pools, 2162 pgs
    objects: 5.84M objects, 6.1 TiB
    usage:   18 TiB used, 178 TiB / 196 TiB avail
    pgs:     2162 active+clean
```

It's all working great for me. I did have some issues with exporter deployments but I think that's because I applied the helm chart and then immediately changed the operator image and it changed things partway through. I scaled down the operator, deleted the exporter deployments, and then scaled it back up and things came up fine.

**Comment by reefland** [comment]
I just tried to scale down the Operator to zero, deleted all exporter pods, mgr and OSDs pods not starting.  Scale back to 1, Let them get recreated.  The exporter pods started up fine.  The MGR and OSDs pods having issues still have issues.

On a node with 2 OSDs (one up / one down), I killed the OSD pod to the one Up, the pending one was then able to start, but the new pod was now unable to start ... no free ports.

**Comment by taxilian** [comment]
@reefland do you have multi-cluster service / ExportService enabled?

**Comment by reefland** [comment]
Sorry, I'm not familiar with these services.  I do not see anything obvious in my values.yaml, and `ceph config ls` is not showing anything like that. The monitoring section in my cluster.yaml:
```
          monitoring:
            enabled: true
            createPrometheusRules: true
            rulesNamespaceOverride:
            prometheusRule:
              labels: {}
              annotations: {}
```

I see above you are referencing `multiClusterService.enabled: true` but I don't know where to check this.
