### ISSUE TITLE
Mangled mon bind address during IPv6-only Cluster Creation

### ISSUE THREAD

**Issue by heliochronix** [rook/rook#11858]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Creating an IPv6-only cluster results in ceph-mon being started with a mangled `--public-addr=fd07:aaaa:bbbb:cccc::12:3300` where the port number is part of the bind address, causing ceph-mon to fail. For example: `[fd07:aaaa:bbbb:cccc::12:3300]:3300`

**Expected behavior:**
Creation of IPv6-only cluster should start monitors that bind to an appropriately formatted IPv6 address and port. For example: `[fd07:aaaa:bbbb:cccc::12]:3300`

**How to reproduce it (minimal and precise):**
* IPv6-only K8s cluster
* Use v1.11.1 `deploy/examples`
* `kubectl create -f crd.yaml -f common.yaml -f operator.yaml`
* Modify default `cluster.yaml` with the following values:
  * `ipFamily: "IPv6"`
  * `dualStack: false`
  * `requireMsgr2: true`
* `kubectl create -f cluster.yaml`
* Observe creation of the first monitor crashes repeatedly with a bad bind address

**File(s) to submit**:
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph # namespace:cluster
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.5
    allowUnsupported: false
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  waitTimeoutForHealthyOSDInMinutes: 10
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
    allowMultiplePerNode: false
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    ssl: false
  monitoring:
    enabled: false
  network:
    connections:
      encryption:
        enabled: false
      compression:
        enabled: false
      requireMsgr2: true
    provider: host
    ipFamily: "IPv6"
    dualStack: false
  crashCollector:
    disable: false
  logCollector:
    enabled: true
    periodicity: daily # one of: hourly, daily, weekly, monthly
    maxLogSize: 500M # SUFFIX may be 'M' or 'G'. Must be at least 1M.
  cleanupPolicy:
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
    allowUninstallWithVolumes: false
  annotations:
  labels:
  resources:
  removeOSDsIfOutAndSafeToRemove: false
  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: false
    config:
    onlyApplyOSDPlacement: false
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0

  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
    startupProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
```
**Logs to submit**:
Relevant Operator Logs:
```
p-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":["[fd07:aaaa:bbbb:cccc::12]:3300"],"namespace":""}] data:a=[fd07:aaaa:bbbb:cccc::12]:3300 mapping:{"node":{"a":{"Name":"node02","Hostname":"node02","Address":"fd07:aaaa:bbbb:cccc::12"},"b":{"Name":"node01","Hostname":"node01","Address":"fd07:aaaa:bbbb:cccc::11"},"c":{"Name":"node00","Hostname":"node00","Address":"fd07:aaaa:bbbb:cccc::10"}}} maxMonId:0 outOfQuorum:]
op-mon: waiting for mon quorum with [a]
op-mon: mon a is not yet running
op-mon: mons running: []
op-mon: mons running: [a]
op-mon: mons running: [a]
...<repeats>...
```
Relevant mon.a log:
```
  0 mon.a does not exist in monmap, will attempt to join an existing cluster
  0 using public_addr v2:[fd07:aaaa:bbbb:cccc::12:3300]:0/0 -> [v2:[fd07:aaaa:bbbb:cccc::12:3300]:3300/0,v1:[fd07:aaaa:bbbb:cccc::12:3300]:6789/0]
  0 starting mon.a rank -1 at public addrs [v2:[fd07:aaaa:bbbb:cccc::12:3300]:3300/0,v1:[fd07:aaaa:bbbb:cccc::12:3300]:6789/0] at bind addrs [v2:[fd07:aaaa:bbbb:cccc::12:3300]:3300/0,v1:[fd07:aaaa:bbbb:cccc::12:3300]:6789/0] mon_data /var/lib/ceph/mon/ceph-a fsid 9258be19-0fdb-4a46-bee6-d1d110f594a3
  1 mon.a@-1(???) e0 preinit fsid 9258be19-0fdb-4a46-bee6-d1d110f594a3
  1 mon.a@-1(???) e0  initial_members a, filtering seed monmap
 -1  Processor -- bind unable to bind to v2:[fd07:aaaa:bbbb:cccc::12:3300]:3300/0: (99) Cannot assign requested address
 -1  Processor -- bind was unable to bind. Trying again in 5 seconds
 -1  Processor -- bind unable to bind to v2:[fd07:aaaa:bbbb:cccc::12:3300]:3300/0: (99) Cannot assign requested address
 -1  Processor -- bind was unable to bind. Trying again in 5 seconds
 -1  Processor -- bind unable to bind to v2:[fd07:aaaa:bbbb:cccc::12:3300]:3300/0: (99) Cannot assign requested address
 -1  Processor -- bind was unable to bind after 3 attempts: (99) Cannot assign requested address
 -1 unable to bind monitor to [v2:[fd07:aaaa:bbbb:cccc::12:3300]:3300/0,v1:[fd07:aaaa:bbbb:cccc::12:3300]:6789/0]
 ```

**Environment**:
* Kernel (e.g. `uname -a`): 6.1.7
* Rook version (use `rook version` inside of a Rook Pod): 1.11.1
* Kubernetes version (use `kubectl version`): 1.26.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare metal
