### ISSUE TITLE
cephfs subvolume uid, gid information not retain after mounting the subvolumegroup

### ISSUE THREAD

**Issue by zeddit** [rook/rook#11901]
I created a subvolumegroup with default settings as:
```
ceph fs subvolumegroup create myfs mysvg
```
then I add some subvolumes under the subvolumegroup with uid,gid settings, like:
```
ceph fs subvolume create myfs user1 --size 10737418240 --group_name mysvg --uid 190002 --gid 19001 --mode 640 --namespace-isolated
```
then I try to mount the subvolumegroup from host os and k8s pod like:
```
sudo mount -t ceph -o mds_namespace=myfs,name=user1,secret=AQA9CxBkqx+CAhABF2Gu+f7vybws6HkAO2KKYg== 10.0.26.1:6789:/volumes/mysvg /mnt 
```
and 
```
   - name: cephfs
        cephfs:
          monitors:
            - 10.0.26.1:6789
            - 10.0.26.2:6789
            - 10.0.26.3:6789
          user: user1
          secretRef:
            name: rook-ceph-client-user1
          path: "/volumes/mysvg"
```

However, all subvolumes have user and group as `root` and `root`, where I expect should be the `uid` and `gid` I have set.
Is there any configuration that I missed, I can find few documentations about this topic.

Great thanks.
