### ISSUE TITLE
Ability to specify pg_num and pgp_num in replicapool storage class

### ISSUE THREAD

**Issue by andrewmyhre** [rook/rook#1191]
When creating a ceph pool I want to be able to specify appropriate `pg_num` and `pgp_num` values for my cluster.

Proposal:

```
apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: replicapool
  namespace: rook
spec:
  replicated:
    size: 1
    pg_num: 1024
    pgp_num: 1024
```

`pgp_num` should always ==`pg_num` so perhaps that's redundant.

This would make it easier to author scripts to provision ceph clusters via rook without having to execute a command from the rook-tools pod, given you first have to wait for the rook-api to be deployed and then become healthy which can be complicated to implement in scripts.
