### ISSUE TITLE
OSD  memory consumption too high

### ISSUE THREAD

**Issue by dwy12321** [rook/rook#11930]
I have config the resources limits for osd, but the osd still consume more than 8G memory in every node.
here is my CephCluster.yaml.  What's the right configuration for limit osd menery consumption?
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  finalizers:
    - cephcluster.ceph.rook.io
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: 'quay.io/ceph/ceph:v16.2.9'
  cleanupPolicy:
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  crashCollector: {}
  dashboard:
    enabled: true
    ssl: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  external: {}
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 1m0s
      status:
        interval: 1m0s
    livenessProbe:
      mgr: {}
      mon: {}
      osd: {}
    startupProbe:
      mgr: {}
      mon: {}
      osd: {}
  logCollector: {}
  mgr:
    count: 2
    modules:
      - enabled: true
        name: pg_autoscaler
  mon:
    count: 3
  monitoring: {}
  network:
    connections:
      compression: {}
      encryption: {}
  priorityClassNames:
    mgr: system-cluster-critical
    mon: system-node-critical
    osd: system-node-critical
  resources:
    osd:
      limits:
        cpu: '2'
        memory: 4000Mi
      requests:
        cpu: '2'
        memory: 4000Mi
    osd-hdd:
      limits:
        cpu: '1'
        memory: 4000Mi
      requests:
        cpu: '1'
        memory: 4000Mi
  security:
    kms: {}
  storage:
    useAllDevices: true
    useAllNodes: true
  waitTimeoutForHealthyOSDInMinutes: 10
```
