### ISSUE TITLE
metadata annotations too long in cephnfses CR

### ISSUE THREAD

**Issue by yuvalif** [rook/rook#11949]
when deploying rook operator (from master). running:
```
kubectl apply -f crds.yaml
```
gives the following error message:
```
The CustomResourceDefinition "cephnfses.ceph.rook.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**Environment**:
* OS (e.g. from /etc/os-release): Red Hat Enterprise Linux 8.6 (Ootpa)
* Kernel (e.g. `uname -a`): 4.18.0-372.32.1.el8_6.x86_64
* Rook version (use `rook version` inside of a Rook Pod): master branch
* Kubernetes version (use `kubectl version`): v1.26.1

**Comment by yuvalif** [comment]
not sure why the complaint, annotation looks small
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.3
  creationTimestamp: null
  name: cephnfses.ceph.rook.io          
```
