### ISSUE TITLE
 error when creating "filesystem.yaml": CephFilesystem in version "v1" cannot be handled as a CephFilesystem: strict decoding error: unknown field "spec.dataPools[0].name"

### ISSUE THREAD

**Issue by talhakhan119** [rook/rook#11946]
I created rook cluster v1.11 successfully in my kubernetes version 1.25.6. 

I am running calico in my k8s cluster. I faced an issue while I was applying filesystem.yaml for cephfs from this rook [documentation ](https://rook.github.io/docs/rook/v1.11/Storage-Configuration/Shared-Filesystem-CephFS/filesystem-storage/#prerequisites)

the error logs are as follows: 
```
kubectl create -f filesystem.yaml
Error from server (BadRequest): error when creating "filesystem.yaml": CephFilesystem in version "v1" cannot be handled as a CephFilesystem: strict decoding error: unknown field "spec.dataPools[0].name"

```
My other block storage and object storage are working fine

**Comment by parth-gr** [comment]
Do you have created `dataPools`, show the filesystem CR you are using

**Comment by talhakhan119** [comment]
Sure, here it is

```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - name: replicated
      replicated:
        size: 3
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true

```

> Do you have created `dataPools`, show the filesystem CR you are using

**Comment by parth-gr** [comment]
Hey the above error only looks like formatting thing

```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
  namespace: rook-ceph # namespace:cluster
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - name: replicated
      failureDomain: osd
      replicated:
        size: 3
  preserveFilesystemOnDelete: false
  metadataServer:
    activeCount: 1
    activeStandby: true
```

Can you try this one?
