### ISSUE TITLE
If Default pgp

### ISSUE THREAD

**Issue by thywyn** [rook/rook#11956]
**Is this a bug report or feature request?**
* Bug Report

Deviation from expected behavior:  

In the presence of osd_pool_default_pg_num and osd_pool_default_pgp_num values greater than the defaults, (32 and 0 respectively) the RGW data pool fails to be created.  All the metadata pools seem to be created fine with a pg_num of 8.

**How to reproduce it (minimal and precise):**
set osd_pool_default_pg_num=256 and osd_pool_default_pgp_num=256 in the global context
create new objectstore with the following manifest:
 ```
     apiVersion: ceph.rook.io/v1
      kind: CephObjectStore
      metadata:
        name: rook-ceph
        namespace: rook-ceph
      spec:
        metadataPool:
          failureDomain: rack
          replicated:
            size: 3
            requireSafeReplicaSize: true
        dataPool:
          failureDomain: rack
          replicated:
            size: 3
            requireSafeReplicaSize: true
          parameters:
            compression_mode: none
        preserverPoolsOnDelete: true
        gateway:
          instances: 3
```

* Cluster CR (custom resource), typically called `cluster.yaml`:
  ```
    apiVersion: ceph.rook.io/v1
      kind: CephCluster
      metadata:
        name: rook-ceph
        namespace: rook-ceph
      spec:
        dataDirHostPath: "/var/lib/rook"
        cephVersion:
          image: "rook/ceph:v17.2.5"
        external:    apiVersion: ceph.rook.io/v1
      kind: CephCluster
      metadata:
        name: rook-ceph
        namespace: rook-ceph
      spec:
        dataDirHostPath: "/var/lib/rook"
        cephVersion:
          image: "rook/ceph:v17.2.5"
        external:
          enable: Yes
          enable: Yes
```

* Operator's logs:
"2023-03-21 17:53:26.061225 E | ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/rook-ceph". failed to create object store deployments: failed to create object pools: failed to create data pool: failed to create pool "rook-ceph.rgw.buckets.data": failed to create replicated pool rook-ceph.rgw.buckets.data. . Error ERANGE: 'pgp_num' must be greater than 0 and lower or equal than 'pg_num', which in this case is 1: exit status 34"

**Environment**:
* OS (e.g. from /etc/os-release):
         ubuntu 22.04
* Kernel (e.g. `uname -a`):
         5.19.0-35-generic
* Cloud provider or hardware configuration:
         supermicro
* Rook version (use `rook version` inside of a Rook Pod):
         rook: v1.11.1
         go: go1.19.6
* Storage backend version (e.g. for ceph do `ceph -v`):  
         ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
* Kubernetes version (use `kubectl version`):
          v1.24.11
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
          baremetal k8s cluster
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
The below is complaining about MGR be owned by Rook not cephadm:
```
sudo ceph health
HEALTH_WARN 3 stray daemon(s) not managed by cephadm; 3 stray host(s) with 3 daemon(s) not managed by cephadm
```

**Comment by zhucan** [comment]
@thywyn the ceph version is?

**Comment by thywyn** [comment]
odd, I thought I added that to the bug..  rook 1.11.1 and ceph v17.2.5

**Comment by thywyn** [comment]
> ugh, just saw this.. The log entry is this: `* Operator's logs: "2023-03-21 17:53:26.061225 E | ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/rook-ceph". failed to create object store deployments: failed to create object pools: failed to create data pool: failed to create pool "rook-ceph.rgw.buckets.data": failed to create replicated pool rook-ceph.rgw.buckets.data. . Error ERANGE: 'pgp_num' must be greater than 0 and lower or equal than 'pg_num', which in this case is 1: exit status 34"`
> 
> I'll test the parameters thing

There are 2 issues when trying the parameters:
1.  .rgw.root doesn't get created for the same reasons, you have to manually create it
2. the other pools fail with this message in the operator logs:
`2023-06-15 20:40:33.422215 E | ceph-object-zone-controller: failed to reconcile CephObjectZone "rook-ceph/us-east-1-undercloud-k8s00". failed to create ceph zone: failed to create pools for zone us-east-1-undercloud-k8s00: failed to create metadata pools: failed to create pool "us-east-1-undercloud-k8s00.rgw.control": failed to create replicated pool us-east-1-undercloud-k8s00.rgw.control. . Error ERANGE: 'pgp_num' must be greater than 0 and lower or equal than 'pg_num', which in this case is 1: exit status 34`

**Comment by thywyn** [comment]
> @thywyn What error exactly are you seeing when the data pool is created with the higher pg defaults? Does the operator log have an error?
> 
> Another possibility is to set the pg_num on the data pool. Does this work?
> 
> ```yaml
> ...
>        dataPool:
>          failureDomain: rack
>          replicated:
>            size: 3
>            requireSafeReplicaSize: true
>          parameters:
>            compression_mode: none
>            pg_num: 256
> ...
> ```
> 
> Documenting this setting is in progress with #11967.

There are 2 issues when trying the parameters:
1.  .rgw.root doesn't get created for the same reasons, you have to manually create it
2. the other pools fail with this message in the operator logs:
`2023-06-15 20:40:33.422215 E | ceph-object-zone-controller: failed to reconcile CephObjectZone "rook-ceph/us-east-1-undercloud-k8s00". failed to create ceph zone: failed to create pools for zone us-east-1-undercloud-k8s00: failed to create metadata pools: failed to create pool "us-east-1-undercloud-k8s00.rgw.control": failed to create replicated pool us-east-1-undercloud-k8s00.rgw.control. . Error ERANGE: 'pgp_num' must be greater than 0 and lower or equal than 'pg_num', which in this case is 1: exit status 34`

I did try a pgp_num in the parameters but apparently that wasn't honored.

**Comment by thywyn** [comment]
any update on this one?

**Comment by travisn** [comment]
Try setting the `pgp_num` as well to the same value as the `pg_num`.
```
         parameters:
           compression_mode: none
           pg_num: 256
           pgp_num: 256
```
