### ISSUE TITLE
Upgrade to 1.9 failed in GKE without a custom ResourceQuota

### ISSUE THREAD

**Issue by nyarly** [rook/rook#11973]
**Is this a bug report or feature request?**
* Bug Report

We upgraded from 1.8.5 to 1.9.12. Afterwards, we found that all the CSI components weren't deploying successfully.

**Deviation from expected behavior:**

**Expected behavior:**

Smooth upgrade to 1.9.12

**How to reproduce it (minimal and precise):**

We deployed using the 1.9.12 Helm chart to a GKE cluster into our `rook-ceph` namespace. Later, a statefulset failed, unable to mount its volumes after a Pod was evicted. Reviewing the DaemonSet and Deployment for the CSI components, we found that they weren't updating (and that the Deployment had 0 running Pods) with an Event: `Error creating: insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical[]}]` 

What we found in the end is that GKE appears to deploy clusters with https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default, so that the CSI components, having set those priorityClassNames, weren't allowed to deploy into the `rook-ceph` namespace. Copying the `ResourceQuota` from `kube-system` to `rook-ceph` corrected the problem, and the DaemonSets and Deployments were able to restart appropriately.

We've fixed this by added the ResourceQuota to our local installation, but we wanted to report the issue upstream since we didn't see anything about ResourceQuotas and GKE in the upgrade guide.

**Environment**:
* Cloud provider or hardware configuration: Google Cloud
* Rook version (use `rook version` inside of a Rook Pod): 1.9.12
* Kubernetes version (use `kubectl version`): 1.23
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE

**Comment by travisn** [comment]
@nyarly Perhaps it would help if we add a note on this topic to the [1.9 upgrade guide](https://rook.github.io/docs/rook/v1.9/Upgrade/rook-upgrade/)?

**Comment by nyarly** [comment]
It would have helped us, but I think it would be a problem for new installs on GKE in certain circumstances, too

**Comment by travisn** [comment]
What if we add a section on the [prereqs page](https://rook.io/docs/rook/latest/Getting-Started/Prerequisites/prerequisites/) for this topic? Do you have a suggestion on the wording?

**Comment by charlesmulder** [comment]
Deploying the following `ResourceQuota` seems to be working...
```
apiVersion: v1
kind: ResourceQuota
metadata:
  # annotations:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: rook-critical-pods
  namespace: rook-ceph
spec:
  hard:
    pods: 1G
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
      - system-cluster-critical
```
Found it on [this issue](https://github.com/openservicemesh/osm/issues/4408)
