### ISSUE TITLE
 feature request: rook-ceph helm chart as a client using external ceph cluster 

### ISSUE THREAD

**Issue by riaanp78** [rook/rook#12066]
**Is this a bug report or feature request?**

* Feature Request

**Feature Request**
Would it be possible to to use the existing rook-ceph helm chart to setup a client connection to a external ceph cluster? 
And if possible an example values.yaml be created to explain how to do this?

**Are there any similar features already existing:**
Not officially that I am aware of 

**What should the feature do:**
setup a client connection to an external ceph cluster that already exists RBD/Cepfs/Bucket

**What would be solved through this feature:**
using the existing helm chart instead of creating a new one from scratch just so it can be used as an client 

**Does this have an impact on existing features:**
should not - should expand it

**Comment by parth-gr** [comment]
@travisn 
This was something we updated, But good to have a different file for this too 
https://github.com/rook/rook/blob/master/Documentation/Helm-Charts/ceph-cluster-chart.md#ceph-cluster-spec

https://github.com/rook/rook/pull/11505/files

**Comment by travisn** [comment]
The rook-ceph-cluster chart is intended to be used for any type of cluster, and you just need to specify the needed values.yaml to override the defaults. The defaults will create the converged cluster with all the ceph daemons running in the local cluster, but in the case of the external cluster, we don't want those settings. 

@riaanp78 Can you try the following to see if it will create external cluster for you? This is the most basic values.yaml that I would expect to hopefully work, though I haven't tested it yet. The example assumes that the key provided to connect to the external cluster has sufficient permissions to create a pool to be used by this cluster along with a storage class. If creating a pool is not desired because it already exists, you would need to remove this pool from the values.yaml. But here is this example to try out:
```console
helm install --create-namespace --namespace rook-ceph rook-ceph-cluster \
   --set operatorNamespace=rook-ceph rook-release/rook-ceph-cluster -f values-external.yaml
```

The example `values-external.yaml`:
```yaml
# All values below are taken from the CephCluster CRD
# -- Cluster configuration.
# @default -- See [below](#ceph-cluster-spec)
cephClusterSpec:
  external:
    enable: true
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s

# -- A list of CephBlockPool configurations to deploy
# @default -- See [below](#ceph-block-pools)
cephBlockPools:
  - name: external-blockpool
    spec:
      failureDomain: host
      replicated:
        size: 3
      # Enables collecting RBD per-image IO statistics by enabling dynamic OSD performance counters. Defaults to false.
      # For reference: https://docs.ceph.com/docs/master/mgr/prometheus/#rbd-io-statistics
      # enableRBDStats: true
    storageClass:
      enabled: true
      name: ceph-block
      isDefault: true
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: "Immediate"
      mountOptions: []
      parameters:
        imageFormat: "2"
        imageFeatures: layering

        # These secrets contain Ceph admin credentials.
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"

        csi.storage.k8s.io/fstype: ext4

# -- A list of CephFileSystem configurations to deploy
# @default -- See [below](#ceph-file-systems)
cephFileSystems: {}

# -- A list of CephObjectStore configurations to deploy
# @default -- See [below](#ceph-object-stores)
cephObjectStores: {}
```
