### ISSUE TITLE
dashboard ssl: false yet mon gives ssl cert error

### ISSUE THREAD

**Issue by gattytto** [rook/rook#12062]
hello, I'm using the current github avaiable yaml samples (image: quay.io/ceph/ceph:v17.2.5) to spin up a pure-ipv6 cluster inside lxd containers as nodes, so far so good but I get this when trying to create the rook ceph cluster:

```yaml
  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    # port: 8443
    # serve the dashboard using SSL
    ssl: false
```

yet my logs say:

```verilog
debug 2023-04-10T23:18:31.178+0000 7f6a47dcd700  0 [dashboard INFO root] server: ssl=yes host=:: port=8443
debug 2023-04-10T23:18:31.178+0000 7f6a47dcd700  0 [dashboard INFO root] Config not ready to serve, waiting: no certificate configured
```
does this mean it's using self-signed certs and it's ok? if so please tell me and I will close the issue

thank you very much in advance, travis has already been assisting me in the slack channel
