### ISSUE TITLE
Possible bottleneck?

### ISSUE THREAD

**Issue by echel0n-TR** [rook/rook#12145]
We have 30 NVMe Gen3 U.2 drives, each drive assigned 5 OSDs, we can't seem to get NVMe speeds across the cluster and believe there is a bottleneck with the network it self, each server has a dedicated 80Gbit network card (2x 40Gb ports bonded), we have 6x Dell R740xd systems with NVMe expanders and 5x NVMe drives each.

Any help would be appreciated in tracking this bottleneck down please.

Thanks!

**Comment by parth-gr** [comment]
> we can't seem to get NVMe speeds across the cluster
Can you share the benchmark of the performance

**Comment by echel0n-TR** [comment]
@travisn we do have resource limits on the OSDs, CPU limits are never reached, and memory limit still has 1GB of room to go.

**Comment by travisn** [comment]
Could you test without the cpu or memory limits to verify if that's a factor?

**Comment by echel0n-TR** [comment]
This is a helm chart, how would I remove those limits, other then setting them higher, which I have already done.

**Comment by echel0n-TR** [comment]
The current OSD resource limits are
```
        osd:
          limits:
            cpu: "2000m"
            memory: "5Gi"
          requests:
            cpu: "1000m"
            memory: "5Gi"
```

Below is what the OSDs are actually using
![image](https://user-images.githubusercontent.com/120627298/234962091-ce2678a3-ec64-4fc6-9076-3fc8f59d7652.png)
