### ISSUE TITLE
MountVolume.MountDevice failed for ceph-block device

### ISSUE THREAD

**Issue by robertwenquan** [rook/rook#12219]
Installed thru helm chart
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: v1.11.5
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-sources
  values:
```
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.11.5
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-sources
  values:
    toolbox:
      enabled: true
```

runtime looks ok
```
✗ kubectl -n rook-ceph get pod
csi-cephfsplugin-m29fr                              2/2     Running             0          160m
csi-cephfsplugin-nm79q                              2/2     Running             0          160m
csi-cephfsplugin-provisioner-59b77fb557-xlrfm       5/5     Running             0          160m
rook-ceph-mon-b-6c7cc7cfdb-qn2tv                    2/2     Running             0          159m
rook-ceph-mon-c-584cc6dcbd-4hdjk                    2/2     Running             0          159m
rook-ceph-crashcollector-dn112-67df88856c-gpc4p     1/1     Running             0          159m
rook-ceph-mgr-a-6d99849cf4-5wwwx                    3/3     Running             0          159m
rook-ceph-crashcollector-dn113-7dfc76c688-k27s9     1/1     Running             0          158m
rook-ceph-tools-6595b6bb4-j9nr6                     1/1     Running             0          157m
rook-ceph-osd-1-67695cdb54-dfr8x                    2/2     Running             0          158m
rook-ceph-osd-0-6fb4d4db9-7gb4c                     2/2     Running             0          158m
rook-ceph-operator-fccc54647-m8b8k                  1/1     Running             0          157m
rook-ceph-mds-ceph-filesystem-a-54f47579b9-vb5kp    2/2     Running             0          153m
rook-ceph-mds-ceph-filesystem-b-656c5f7dd6-rnm82    2/2     Running             0          153m
rook-ceph-rgw-ceph-objectstore-a-5d894f746d-pppc8   2/2     Running             0          148m
rook-ceph-crashcollector-dn114-5fb4d94c59-bmggr     1/1     Running             0          150m
rook-ceph-mon-d-78c58b766b-hxc5c                    2/2     Running             0          134m
rook-ceph-osd-prepare-dn114-5tb7t                   0/1     Completed           0          106m
rook-ceph-osd-prepare-dn113-5k4ql                   0/1     Completed           0          106m
rook-ceph-osd-prepare-dn112-cdjhm                   0/1     Completed           0          106m
csi-cephfsplugin-provisioner-59b77fb557-qhng7       5/5     Running             0          86m
csi-cephfsplugin-krr6f                              2/2     Running             0          83m```

pvc and pv looks ok
```
✗ kubectl -n dev-abc get pvc | grep ceph
data-postgresql-0           Bound    pvc-dab0e0e0-0b68-4205-859f-c5a28fdd9405   2Gi        RWO            ceph-block          80m
```

```
✗ kubectl -n dev-abc get pv | grep ceph
pvc-dab0e0e0-0b68-4205-859f-c5a28fdd9405   2Gi        RWO            Delete           Bound    dev/data-postgresql-0              ceph-block                   81m
```

pod logs shows mount failure error
```
Events:
  Type     Reason       Age   From               Message
  ----     ------       ----  ----               -------
  Normal   Scheduled    67s   default-scheduler  Successfully assigned dev-robert/postgresql-0 to dn112
  Warning  FailedMount  2s    kubelet            MountVolume.MountDevice failed for volume "pvc-dab0e0e0-0b68-4205-859f-c5a28fdd9405" : rpc error: code = InvalidArgument desc = staging path /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com/071765296c2e72a48989e72745a40ab6895eb61450fd5d089e1cddcbbb866fb3/globalmount does not exist on node
```

would appreciate if someone could shed some light on how to debug this.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

Expected the pod to be able to mount the pvc

**How to reproduce it (minimal and precise):**
<!-- Please let us know any circumstances for reproduction of your bug. -->

1. create the workload to use a pvc
2. the pod is not coming up

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
bare-metal

* Rook version (use `rook version` inside of a Rook Pod)
v1.11.5

* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)

* Kubernetes version (use `kubectl version`):

```
Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.26.4
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
microk8s

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

```
# ceph health
HEALTH_WARN mon b is low on available space; Degraded data redundancy: 404/1212 objects degraded (33.333%), 55 pgs degraded, 280 pgs undersized; OSD count 2 < osd_pool_default_size 3; too many PGs per OSD (296 > max 250)
```
