### ISSUE TITLE
No OSDs are created for my block-based ceph cluster 

### ISSUE THREAD

**Issue by Gabson1** [rook/rook#12237]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:** A ceph cluster is successfully deployed with a block-based storage configuration

### Current configuration:

* block-storage.yaml
```
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ceph-pool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
    pool: ceph-pool
    imageFormat: "2"
    clusterID: rook-ceph
    imageFeatures: layering
    csi.storage.k8s.io/fstype: ext4
    csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
    csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
    csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
    csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
    csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
```

* block-cluster.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.6
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook-block-poc
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  waitTimeoutForHealthyOSDInMinutes: 10
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
    allowMultiplePerNode: false
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    ssl: true
  monitoring:
    enabled: false
    metricsDisabled: false
  network:
    connections:
      encryption:
        enabled: false
      compression:
        enabled: false
      requireMsgr2: false
  crashCollector:
    disable: false
  logCollector:
    enabled: true
    periodicity: daily
    maxLogSize: 500M
  cleanupPolicy:
    confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
    allowUninstallWithVolumes: false
  removeOSDsIfOutAndSafeToRemove: false
  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
  storage:
    useAllNodes: true
    useAllDevices: true
    onlyApplyOSDPlacement: false
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
    startupProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
```

The rook operator is deployed via their provided helm chart in the default configuration with psp enabled.

### Problem:

* a snippet from one of the osd-prepare-logs pods
```
2023-05-16 08:41:47.504917 I | cephosd: skipping device "sda1" with mountpoint "rootfs"
2023-05-16 08:41:47.504920 I | cephosd: skipping device "sdb" with mountpoint "mount"
2023-05-16 08:41:47.504923 I | cephosd: skipping device "sdc" with mountpoint "mount"
2023-05-16 08:41:47.504925 I | cephosd: skipping device "sdd" with mountpoint "mount"
2023-05-16 08:41:47.504927 I | cephosd: skipping device "sde" with mountpoint "mount"
2023-05-16 08:41:47.504930 I | cephosd: skipping device "sdf" with mountpoint "mount"
2023-05-16 08:41:47.513250 I | cephosd: configuring osd devices: {"Entries":{}}
2023-05-16 08:41:47.513264 I | cephosd: no new devices to configure. returning devices already configured with ceph-volume.
2023-05-16 08:41:47.513384 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm list  --format json
2023-05-16 08:41:47.810366 D | cephosd: {}
2023-05-16 08:41:47.810398 I | cephosd: 0 ceph-volume lvm osd devices configured on this node
2023-05-16 08:41:47.810417 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log raw list --format json
2023-05-16 08:41:48.372299 D | cephosd: {}
2023-05-16 08:41:48.372332 I | cephosd: 0 ceph-volume raw osd devices configured on this node
2023-05-16 08:41:48.372338 W | cephosd: skipping OSD configuration as no devices matched the storage settings for this node "worker-node-1"
```

Now I understand why no OSDs are being created during the preparation, but I thought that rook would dynamically provision the pv based on the given storageclass... which does not seem to be the case even if I define the storageClassDeviceSets and the linked volumeClaimTemplate

* block-cluster-v2.yaml
```
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook_block_two
  mon:
    count: 3
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 5Gi
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.6
    allowUnsupported: true
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mgr:
    count: 1
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    ssl: true
  crashCollector:
    disable: false
  logCollector:
    enabled: true
    periodicity: daily
    maxLogSize: 500M
  storage:
    storageClassDeviceSets:
      - name: set1
        count: 3
        portable: true
        tuneDeviceClass: true
        tuneFastDeviceClass: false
        encrypted: false
        placement:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd
        preparePlacement:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd-prepare
                  topologyKey: kubernetes.io/hostname
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd-prepare
        resources:
          limits:
            cpu: "500m"
            memory: "5Gi"
          requests:
            cpu: "500m"
            memory: "5Gi"
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 10Gi
              storageClassName: rook-ceph-block
              volumeMode: Block
              accessModes:
                - ReadWriteMany
        # dedicated block device to store bluestore database (block.db)
        # - metadata:
        #     name: metadata
        #   spec:
        #     resources:
        #       requests:
        #         # Find the right size https://docs.ceph.com/docs/master/rados/configuration/bluestore-config-ref/#sizing
        #         storage: 5Gi
        #     # IMPORTANT: Change the storage class depending on your environment
        #     storageClassName: io1
        #     volumeMode: Block
        #     accessModes:
        #       - ReadWriteOnce
        # dedicated block device to store bluestore wal (block.wal)
        # - metadata:
        #     name: wal
        #   spec:
        #     resources:
        #       requests:
        #         # Find the right size https://docs.ceph.com/docs/master/rados/configuration/bluestore-config-ref/#sizing
        #         storage: 5Gi
        #     # IMPORTANT: Change the storage class depending on your environment
        #     storageClassName: io1
        #     volumeMode: Block
        #     accessModes:
        #       - ReadWriteOnce
        # Scheduler name for OSD pod placement
        # schedulerName: osd-scheduler
    onlyApplyOSDPlacement: false
  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0

```

When I deploy the v2 cluster not even the mons are being created. The error I am getting now is `error getting secret rook-csi-rbd-provisioner in namespace rook-ceph: secrets "rook-csi-rbd-provisioner" not found`... so the question is why is the rbd secret not being created?

### Summary
My question is basically this. Why is rook/ceph failing to setup the cluster as I need it and what am I missing?
I want a block-based configuration where the pvs are dynamically provisioned.

I tried looking through the documentation, but could not find an answer to my question(s)... maybe I missed something.
I would greatly appreciate anyone who could point me in the correct direction

**Environment**:
* OS (e.g. from /etc/os-release): K8 cluster running on Ubuntu 20 LTS
* Cloud provider or hardware configuration: baremetal
* Rook version (use `rook version` inside of a Rook Pod): v1.11.5
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)
* Kubernetes version (use `kubectl version`): v1.24.12
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): unable to get monitor info from DNS SRV with service name: ceph-mon
2023-05-16T14:08:17.076+0000 7ff9d519f700 -1 failed for service _ceph-mon._tcp
2023-05-16T14:08:17.076+0000 7ff9d519f700 -1 monclient: get_monmap_and_config cannot identify monitors to contact
