### ISSUE TITLE
add RGW DB store support to rook

### ISSUE THREAD

**Issue by yuvalif** [rook/rook#12276]
DB store was first introduced to the RGW here: https://github.com/ceph/ceph/pull/31454
This allows deploying an RGW without a ceph cluster. Would be useful for S3 demos and lighweight deployments.

**Comment by travisn** [comment]
Since that was merged a while back, is it available since Pacific?

**Comment by yuvalif** [comment]
> Since that was merged a while back, is it available since Pacific?

from what i see in the code. it is only in quincy

**Comment by yuvalif** [comment]
information on how to setup dbstore in rgw: https://github.com/ceph/ceph/blob/main/src/rgw/driver/dbstore/README.md

**Comment by travisn** [comment]
After a quick thought on what the design might look like, what about the following?
- Since RGW is independent of Ceph in this scenario, no need to create the CephCluster CR. Since today the object controller expects the CephCluster CR to exist, the object controller would need to skip that requirement in this scenario.
- The `CephObjectStore` CR would have these updates:
    - New `dbstore` section with properties needed to start it 
        - `image` specifies which ceph image to start the rgw daemon
        - `hostPath` specifies where on the host the db should be persisted. 
        - `volumeClaimTemplate`: Could be used instead of a hostPath if they want to back it with a PV. But since the feature is experimental and not for production, this option may not be necessary.
    - `gateway.instances` must be `1`

For example:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: rgw-dbstore
  namespace: rook-ceph # namespace:cluster
spec:
  gateway:
    port: 80
    # securePort: 443
    instances: 1
    dbstore:
      image: quay.io/ceph/ceph:v17.2.6
      hostPath: /var/lib/rook/rgw
```
