### ISSUE TITLE
All OSD are on the same node

### ISSUE THREAD

**Issue by msaustral** [rook/rook#12285]
Hi we have Ceph v17.2.5 implemented ok a AKS with an exclusive node group to Ceph, we add to the cluster:

```yaml
nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
            - key: agentpool
               operator: In
                values:
                - npstorage
```

and 
```yaml
useAllNodes: true
useAllDevices: true
```

All node on the storage group are tagged with agentpool:npstorage and --node-taints storage-node=true:NoScheduleall 

All OSD are created only in one node of the storage Group node.

![image](https://github.com/rook/rook/assets/46203943/4e974d48-29ce-472d-ade6-0a6649e5bfd9)

searching we found on the documentation to kill the process pod and this should trigger the OSD prepare, it did, but it create a 4th OSD on the same node :(

How can we create news OSD on the other storage node without losing the data and then erase 3 OSD from the actual node?

**Comment by travisn** [comment]
Do you see OSD prepare pods created on all the nodes where you expect OSDs to be created? See this [troubleshooting topic](https://rook.io/docs/rook/latest/Troubleshooting/ceph-common-issues/#osd-pods-are-not-created-on-my-devices). 

Once you get all nodes to create the OSDs, then you can remove any extra OSDs with [these steps](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-osd-mgmt/#remove-an-osd).

With AKS running in a cloud environment, I would recommend considering the [cluster-on-pvc](https://rook.io/docs/rook/latest/CRDs/Cluster/pvc-cluster/) approach, which will allow your nodes to be simply replaced because the storage is portable between nodes, and the backing storage easily provisioned from a storage class.

**Comment by msaustral** [comment]
Hi thank you for yous fast response, we do see OSD prepare with status completed but on nodes that are not for storage
![image](https://github.com/rook/rook/assets/46203943/c48cd418-c988-41cf-81db-f52d54f3a128)

We are using WRX volume, can be use with cluster-on-pvc? can we migrate without losing the data and keep the same volume?

**Comment by travisn** [comment]
Did you add the node affinity under the `placement.osd`, like this?
```yaml
  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: agentpool
                  operator: In
                  values:
                    - npstorage
```

The node affinity doesn't seem to have applied since the osd prepare jobs ran on other nodes as well.

> We are using WRX volume, can be use with cluster-on-pvc? can we migrate without losing the data and keep the same volume?

What is the WRX volume?

**Comment by msaustral** [comment]
Hi, yes we did:
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph # namespace:cluster
spec:
......
......
removeOSDsIfOutAndSafeToRemove: false
  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
  storage: # cluster level storage configuration and selection
    storageClassDeviceSets:
    - name: set1
      count: 4
      portable: true
      placement:
        tolerations:
        - key: storage-node
          operator: Exists
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - npstorage
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
      resources:
        limits:
          cpu: "500m"
          memory: "4Gi"
        requests:
          cpu: "500m"
          memory: "2Gi"
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 1024Gi
          storageClassName: managed-premium
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
    useAllNodes: true
    useAllDevices: true


And sorry is RWX Read Write Many using CephFilesystem

Thank you again for your help

**Comment by travisn** [comment]
This configuration is different than you had before. It's a new cluster now? Do you see the OSDs on the correct nodes now? 

> And sorry is RWX Read Write Many using CephFilesystem

Yes, CephFS (RXW), RBD (RWO), or RGW (S3) object storage can all be used if the OSDs are setup with this cluster-on-pvc configuration.

**Comment by travisn** [comment]
To spread the OSDs across the nodes, you'll need to use the topologySpreadConstraints. In the cluster-on-pvc example, the TSCs are specific for spreading across zones, but you could change it to spread across nodes.

**Comment by msaustral** [comment]
is there a way to do it with the actual configuration?

**Comment by msaustral** [comment]
Hi sorry to bother, this is our first cluster, we did compare the cluster PVC example on the manual with our actual yaml and do not see any differences, can you help us? do we have PVC cluster already? please find attached our full cluster yaml

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph 
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.5
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  waitTimeoutForHealthyOSDInMinutes: 10
  mon:
    count: 3
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: managed-premium
        resources:
          requests:
            storage: 10Gi
  mgr:
    count: 2
    allowMultiplePerNode: false
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    ssl: true
  monitoring:
    enabled: false
  network:
    connections:
      encryption:
        enabled: false
      compression:
        enabled: false
  crashCollector:
    disable: false
  logCollector:
    enabled: true
    periodicity: daily
    maxLogSize: 500M
  cleanupPolicy:
    confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
    allowUninstallWithVolumes: false
  annotations:
  labels:
  resources:
  removeOSDsIfOutAndSafeToRemove: false
  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
  storage:
    storageClassDeviceSets:
    - name: set1
      count: 4
      portable: true
      placement:
        tolerations:
        - key: storage-node
          operator: Exists
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - npstorage
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
      resources:
        limits:
          cpu: "500m"
          memory: "4Gi"
        requests:
          cpu: "500m"
          memory: "2Gi"
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 1024Gi
          storageClassName: managed-premium
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
    useAllNodes: true
    useAllDevices: true
    config:
    onlyApplyOSDPlacement: false
  disruptionManagement:
    managePodBudgets: false
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0

  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
    startupProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
```

**Comment by travisn** [comment]
With the existing deployment? The scheduler only honors the TSCs when the pods are scheduled, so it is difficult after the fact. You might try adding [resource requests](https://github.com/rook/rook/blob/master/deploy/examples/cluster-on-pvc.yaml#L115-L122) that are extra-high to see if it the scheduler will move some of the OSDs to another node.

**Comment by msaustral** [comment]
Hi Travis, sorry but i did not understand

**Comment by travisn** [comment]
There are two suggestions:
1. When creating a new cluster, you will want to use the topologySpreadConstraints so the OSDs will be spread across nodes. For example, see [this example](https://github.com/rook/rook/blob/master/deploy/examples/cluster-on-pvc.yaml#L77-L87). Also, remove the `useAllNodes` and `useAllDevices` settings. They are not used when the `storageClassDeviceSets` are specified.
2. If you are trying to move the OSDs in the existing cluster without the topologySpreadConstraints it will be difficult. You can either destroy the cluster and try step 1. Or I am suggesting you could increase the memory resource requests on the OSDs really high so K8s might re-schedule some of the OSDs. In your yaml, their memory is at 2Gi. You could increase it a lot more to see if it works.

**Comment by msaustral** [comment]
Hi i change the resources to this:

```
resources:
        limits:
          memory: "8Gi"
        requests:
          cpu: "500m"
          memory: "4Gi"
```
can i re apply the cluster yaml to the actual cluster without down time or data lost?

We also try to scale the storage node group, no OSD on the new node, we kill operator pod and it try to create OSD on any other node less the storage.

**Comment by msaustral** [comment]
Hi, should we change this:

```
podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
```

To this:

```
podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
```

Can we reapply the same yaml?

**Comment by msaustral** [comment]
Hi, please help us

**Comment by travisn** [comment]
@msaustral Yes, you can apply the same cluster.yaml with the updated yaml and it will apply the new settings, and update/restart the OSDs with the new settings as needed.

The pod antiaffinity only works for one OSD per node. After that, the K8s scheduler will ignore the preferred anti-affinity. The TSCs will be needed to correctly balance when there is more than a single OSD per node.

Since you're trying to get two OSDs evicted to other nodes, you may need to change the memory requests even higher, depending on your node resources.

**Comment by msaustral** [comment]
Hi Travis, thank you for your help, we have combine the example with our previos yaml and increase the image version, can you help us to check if there is any error on the new yaml before apply it?

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: managed-premium
        resources:
          requests:
            storage: 10Gi
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.6
    allowUnsupported: false
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  waitTimeoutForHealthyOSDInMinutes: 10
  
  mgr:
    count: 2
    allowMultiplePerNode: false
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    ssl: true
  monitoring:
    enabled: false
  network:
    connections:
      encryption:
        enabled: false
      compression:
        enabled: false
  crashCollector:
    disable: false
  logCollector:
    enabled: true
    periodicity: daily 
    maxLogSize: 500M 
  
  cleanupPolicy:
    confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
    allowUninstallWithVolumes: false
  annotations:
  labels:
  resources:
# The requests and limits set here, allow the mgr pod to use half of one CPU core and 1 gigabyte of memory
#    mgr:
#      limits:
#        cpu: "500m"
#        memory: "1024Mi"
#      requests:
#        cpu: "500m"
#        memory: "1024Mi"
  removeOSDsIfOutAndSafeToRemove: false
  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
  storage: 
    storageClassDeviceSets:
    - name: set1
      count: 4
      portable: true
      tuneDeviceClass: true
      tuneFastDeviceClass: true
      encrypted: false
      placement:
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - rook-ceph-osd
      preparePlacement:
        tolerations:
        - key: storage-node
          operator: Exists
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - npstorage
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - rook-ceph-osd-prepare
      resources:
      #  limits:
      #    memory: "8Gi"
      #  requests:
      #    cpu: "500m"
      #    memory: "4Gi"
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 1024Gi
          storageClassName: managed-premium
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
    config:
    onlyApplyOSDPlacement: false
  disruptionManagement:
    managePodBudgets: true
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
```

**Comment by msaustral** [comment]
Hi the previos setting did not work, we use this one and problem solved, 1 OSD on each storage node:

```
storage: 
    storageClassDeviceSets:
    - name: set1
      count: 4
      portable: true
      tuneDeviceClass: true
      tuneFastDeviceClass: true
      encrypted: false
      placement:
        tolerations:
        - key: storage-node
          operator: Exists
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - rook-ceph-osd
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - npstorage
      preparePlacement:
        tolerations:
        - key: storage-node
          operator: Exists
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - npstorage
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
      resources:
      #  limits:
      #    memory: "8Gi"
      #  requests:
      #    cpu: "500m"
      #    memory: "4Gi"
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 1024Gi
          storageClassName: managed-premium
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
    config:
    onlyApplyOSDPlacement: false
  disruptionManagement:
    managePodBudgets: true
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
```
