### ISSUE TITLE
mon limit exceeded create

### ISSUE THREAD

**Issue by clcc2019** [rook/rook#12325]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The k8s node is abnormal, and three mons are automatically added to the ceph cluster, but the old mon is running normally,
I only allow 3 mons to be created

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:
<img width="1486" alt="image" src="https://github.com/rook/rook/assets/46099295/c0ef02d9-0c83-458d-a819-647446051e84">

```yaml
2023-06-05 03:24:16.110176 E | ceph-cluster-controller: failed to get ceph daemons versions. failed to run 'ceph versions'. . /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.7/rpm/el8/BUILD/ceph-16.2.7/src/mon/MonMap.h: In function 'void MonMap::add(const mon_info_t&)' thread 7fbdff7fe700 time 2023-06-05T03:24:16.105355+0000
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.7/rpm/el8/BUILD/ceph-16.2.7/src/mon/MonMap.h: 221: FAILED ceph_assert(addr_mons.count(a) == 0)
 ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x158) [0x7fbe0a112b52]
 2: /usr/lib64/ceph/libceph-common.so.2(+0x276d6c) [0x7fbe0a112d6c]
 3: (MonMap::add(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, entity_addrvec_t const&, unsigned short, unsigned short)+0x1b2) [0x7fbe0a4d1482]
 4: (MonMap::init_with_addrs(std::vector<entity_addrvec_t, std::allocator<entity_addrvec_t> > const&, bool, std::basic_string_view<char, std::char_traits<char> >)+0x9b) [0x7fbe0a4cc85b]
 5: (MonMap::init_with_ips(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::basic_string_view<char, std::char_traits<char> >)+0x94) [0x7fbe0a4ccaa4]
 6: (MonMap::build_initial(ceph::common::CephContext*, bool, std::ostream&)+0x676) [0x7fbe0a4ce1f6]
 7: (MonClient::build_initial_monmap()+0x140) [0x7fbe0a4ae3d0]
 8: (MonClient::get_monmap_and_config()+0x62) [0x7fbe0a4b84a2]
 9: /lib64/librados.so.2(+0xb9188) [0x7fbe12e37188]
 10: rados_connect()
 11: /usr/lib64/python3.6/site-packages/rados.cpython-36m-x86_64-linux-gnu.so(+0xcda7c) [0x7fbe131fda7c]
 12: /usr/lib64/python3.6/site-packages/rados.cpython-36m-x86_64-linux-gnu.so(+0x3336c) [0x7fbe1316336c]
 13: _PyObject_FastCallDict()
 14: /lib64/libpython3.6m.so.1.0(+0x10dda0) [0x7fbe1604fda0]
 15: PyObject_Call()
 16: _PyEval_EvalFrameDefault()
 17: /lib64/libpython3.6m.so.1.0(+0x179e28) [0x7fbe160bbe28]
 18: /lib64/libpython3.6m.so.1.0(+0x19d397) [0x7fbe160df397]
 19: _PyEval_EvalFrameDefault()
 20: /lib64/libpython3.6m.so.1.0(+0x179e28) [0x7fbe160bbe28]
 21: /lib64/libpython3.6m.so.1.0(+0x19d397) [0x7fbe160df397]
 22: _PyEval_EvalFrameDefault()
 23: _PyFunction_FastCallDict()
 24: _PyObject_FastCallDict()
 25: /lib64/libpython3.6m.so.1.0(+0x10dda0) [0x7fbe1604fda0]
 26: PyObject_Call()
 27: /lib64/libpython3.6m.so.1.0(+0x20df22) [0x7fbe1614ff22]
 28: /lib64/libpython3.6m.so.1.0(+0x1b4434) [0x7fbe160f6434]
 29: /lib64/libpthread.so.0(+0x817a) [0x7fbe15d2a17a]
 30: clone(): signal: aborted
2023-06-05 03:24:26.438032 W | op-mon: failed to check mon health. failed to get mon quorum status: mon quorum status failed: signal: aborted
```
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:
```yaml
  cluster:
    id:     323bed43-f369-4fee-a6d6-0e10db3f9602
    health: HEALTH_WARN
            25 daemons have recently crashed

  services:
    mon: 3 daemons, quorum a,d,e (age 7m)
    mgr: a(active, since 11d), standbys: b
    osd: 3 osds: 3 up (since 8h), 3 in (since 8w)

  data:
    pools:   2 pools, 33 pgs
    objects: 46.43k objects, 168 GiB
    usage:   494 GiB used, 2.5 TiB / 3.0 TiB avail
    pgs:     33 active+clean

  io:
    client:   341 B/s rd, 75 KiB/s wr, 0 op/s rd, 5 op/s wr
```
* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): debian11
* Kernel (e.g. `uname -a`):4.19
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):16.2.7
* Kubernetes version (use `kubectl version`):1.18.20
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):self host
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
```yaml
  cluster:
    id:     323bed43-f369-4fee-a6d6-0e10db3f9602
    health: HEALTH_WARN
            25 daemons have recently crashed
```
