### ISSUE TITLE
Add worker and storage node type options to multus validation tool

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#12347]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Rook is often given standalone storage nodes for operation while other nodes are used as general k8s worker nodes. Network hardware may also differ on storage nodes compared to worker nodes, and the number of macvlan addresses between the types could differ. Additionally, many network CIDRs dedicated to cluster networks are much smaller than CIDRs for public networks. 

The multus cluster network and public network both should should be attached to <osd> number of client pods on storage nodes. The multus public network only is attached to all other storage node clients. On worker nodes, the public network only is needed, and only one instance per CSI daemon.

In this scheme, the number of `--daemons-per-node` could be different for worker nodes versus storage nodes. 

With these options, the config for the daemon is becoming quite complex. We may wish to consider supporting a config file for these advanced options instead of CLI arguments.

Implementing this doesn't make sense until after allowing placement options on client pods: https://github.com/rook/rook/issues/12173. Because those placement options are also complex, we should consider implementing this config file based design there as well.

Perhaps a structure like so, assuming yaml:
```yaml
publicNetwork: <str>  # current `--public-network` flag
clusterNetwork: <str>  # current `--cluster-network` flag

timeoutMinutes: <int>  # current `--timeout-minutes` flag

nginxImage: <str>  # current `--nginx-image` flag

convergedStorageWorkerNodes:
  # default 3 with config
  osdsPerNode: <int>  # current `--daemons-per-node` option (default 16)
  
  # default 13 with config: 1 mon, 1 mgr, 1 mds, 1 nfs, 1 rgw, 1 rbdmirror, 1 cephfsmirror, 
  # (1 csi provisioner, 1 csi plugin) x3 for rbd, cephfs, and nfs CSI drivers
  otherDaemonsPerNode: <int> 
  placement:
    tolerations: <k8s toleration spec>
    affinity: <k8s affinity spec>
    nodeSelector: <k8s node selector spec>

dedicatedStorageNodes:
  osdsPerNode: <int> # your number of osds; default 0
  otherDaemonsPerNode: <int> # suggest 13, or 10 not running CSI plugins on storage nodes; default 0
  placement:
    tolerations: <k8s toleration spec> # default: some basic node-role=storage toleration
    affinity: <k8s affinity spec>
    nodeSelector: <k8s node selector spec>

dedicatedWorkerNodes:
  daemonsPerNode: <int>  # suggest 6 to handle CSI daemons; default 0
  placement:
      tolerations: <k8s toleration spec>
      affinity: <k8s affinity spec>
      nodeSelector: <k8s node selector spec>
```

New usage suggestions:
```
rook multus validation run --config configfile.yaml # no other args supported if config given

rook multus validation gen-config simple # generate sample config with current defaults

rook multus validation gen-config dedicated # generate sample config for env w/ dedicated stg nodes

# both the above output to std out so `>` can be used to choose the output file
```

**What is use case behind this feature:**

**Environment**:
