### ISSUE TITLE
The block devices are considered as unusable

### ISSUE THREAD

**Issue by khmarochos** [rook/rook#12393]
The rook-ceph-osd-prepare job fails to detect the device allowed for the node. 

To reproduce this behaviour we'll need a single VM with Minikube and 5 virtual drives: `vdd`, `vde`, `vdf`, `vdg`, `vdh`.

1. Initialise Minikube with the Docker driver: `minikube start --nodes 5`.
2. Deploy `rook-ceph` as the operator: `helm install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph`
3. Deploy `rook-ceph-cluster` as a cluster: `helm install --create-namespace --namespace rook-ceph --values helm_rook-ceph-cluster.yaml rook-ceph-cluster rook-release/rook-ceph-cluster`.

The values for `rook-ceph-cluster` are the following:
```yaml
operatorNamespace: rook-ceph
toolbox:
  enabled: true
cephClusterSpec:
  storage:
    useAllDevices: false
    nodes:
      - name: "minikube"
        devices:
          - name: "vdd"
      - name: "minikube-m02"
        devices:
          - name: "vde"
      - name: "minikube-m03"
        devices:
          - name: "vdf"
      - name: "minikube-m04"
        devices:
          - name: "vdg"
      - name: "minikube-m05"
        devices:
          - name: "vdh"
```

The following `cephclusters.ceph.rook.io` object is being produced: https://gist.github.com/khmarochos/41db0ed29f1634e44e25514b5e2b7545

Alas, none of the nodes are able to use the devices we assigned.

Here are the rook-ceph-osd-prepare logs:
https://gist.github.com/khmarochos/f269a0ea51bf649294890cbec2ac888e
https://gist.github.com/khmarochos/0aa835335f23d9583cc9cce409dbe664
https://gist.github.com/khmarochos/537cfc45b97a1ee1737234fdfb5c1164
https://gist.github.com/khmarochos/5a566c07d33ce58fafcbacf8fe665c2b
https://gist.github.com/khmarochos/ef5f651490efd8b3091ef63b30b0078f
To be short, we can see the following messages in logs: `cephosd: desiredDevices are []` and `cephosd: skipping device "..." until the admin specifies it can be used by an osd`.

Here is the rook-ceph-operator log:
https://gist.github.com/khmarochos/d33351123773470abb02b5f42de1ca24

Helm chart versions are `1.11.4`, Minikube version is `1.26.1`, Ubuntu version is `22.04.01`.
