### ISSUE TITLE
Unable to allocate 0x900000 on bdev 1 despite having plenty of space

### ISSUE THREAD

**Issue by CooperWolfe** [rook/rook#12433]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The OSD will not start, reporting `unable to allocate 0x90000 on bdev 1`, despite showing:
```
allocator name block, allocator type hybrid, capacity 0x500000000, block size 0x1000, free 0x2e2c1e000, fragmentation 0.203124, allocated 0x20000
```

**Expected behavior:**
I expect that my OSD will be able to start, considering its disk is only at 42.27% of its capacity, and it should be able to allocate 0x90000 because 0x2e2c1e000 is free.

**How to reproduce it (minimal and precise):**
I simply do not know. I have one OSD configured with a 20GB PVC. At 8.5-ish GB this happened out of the blue and I cannot run my application.

**cluster.yaml**
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: standard-rwo
        resources:
          requests:
            storage: 10Gi
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.7
    allowUnsupported: false
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mgr:
    count: 1
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    urlPrefix: /ceph-dashboard
    port: 8080
    ssl: false
  crashCollector:
    disable: false
  storage:
    storageClassDeviceSets:
      - name: set1
        count: 1
        portable: true
        encrypted: false
        placement:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd
          tolerations:
            - key: dedicated
              operator: Equal
              value: rook-ceph
        preparePlacement:
          tolerations:
            - key: dedicated
              operator: Equal
              value: rook-ceph
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: dedicated
                    operator: In
                    values:
                     - rook-ceph
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd-prepare
                  topologyKey: topology.kubernetes.io/zone
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd-prepare
        resources:
          limits:
            cpu: 400m
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 2Gi
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 20Gi
              storageClassName: standard-rwo
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
    onlyApplyOSDPlacement: false
  resources:
  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
```

**operator logs**
some startup info and then this over and over
```
clusterdisruption-controller: osd "rook-ceph-osd-0" is down but no node drain is detected
clusterdisruption-controller: osd is down in failure domain "set1-data-0z2xnt" and pgs are not active+clean. pg health: "cluster is not fully clean. PGs: [{StateName:stale+active+clean Count:224}]"
```

**osd logs**
some startup info, then this, then event dumps
```
debug     -9> 7f2e4f4e8080  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1687832398076939, "job": 1, "event": "recovery_started", "log_files": [2441, 2451, 2453]}
debug     -8> 7f2e4f4e8080  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #2441 mode 2
debug     -7> 7f2e4f4e8080  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #2451 mode 2
debug     -6> 4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #2453 mode 2
debug     -5> 7f2e4f4e8080  3 rocksdb: [le/block_based/filter_policy.cc:584] Using legacy Bloom filter with high (20) bits/key. Dramatic filter space and/or accuracy improvement is available with format_version>=5.


debug     -4> 1 bluefs _allocate unable to allocate 0x90000 on bdev 1, allocator name block, allocator type hybrid, capacity 0x500000000, block size 0x1000, free 0x2e2c1e000, fragmentation 0.203124, allocated 0x20000


debug     -3> -1 bluefs _allocate allocation failed, needed 0x8042e
debug     -2> -1 bluefs _flush_range allocated: 0x0 offset: 0x0 length: 0x8042e
debug     -1> -1 /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.7/rpm/el8/BUILD/ceph-16.2.7/src/os/bluestore/BlueFS.cc: In function 'int BlueFS::_flush_range(BlueFS::FileWriter*, uint64_t, uint64_t)' thread 7f2e4f4e8080 time
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.7/rpm/el8/BUILD/ceph-16.2.7/src/os/bluestore/BlueFS.cc: 2768: ceph_abort_msg("bluefs enospc")
```

**ceph status**
```
  cluster:
    id:     7c48f865-9e7b-49e0-8160-ad4c216f3033
    health: HEALTH_WARN
            3 filesystems are degraded
            3 MDSs report slow metadata IOs
            1 osds down
            1 host (1 osds) down
            1 region (1 osds) down
            1 root (1 osds) down
            1 zone (1 osds) down
            Reduced data availability: 224 pgs stale
            7 pool(s) have no replicas configured
            740 daemons have recently crashed
            OSD count 1 < osd_pool_default_size 3
 
  services:
    mon: 1 daemons, quorum a (age 41m)
    mgr: a(active, since 12d)
    mds: 3/3 daemons up, 3 standby
    osd: 1 osds: 0 up (since 2d), 1 in (since 39m)
 
  data:
    volumes: 0/3 healthy, 3 recovering
    pools:   7 pools, 224 pgs
    objects: 2.74k objects, 7.5 GiB
    usage:   8.5 GiB used, 12 GiB / 20 GiB avail
    pgs:     224 stale+active+clean
```

**Environment**:
* OS: CentOS Stream 8
* Kernel: 5.15.0-1028-gke No.33-Ubuntu SMP Mon Feb 20 01:54:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Google Cloud Platform
* Rook version: v1.9.2
* Storage backend version: 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)
* Kubernetes version: v1.24.12-gke.1000
* Kubernetes cluster type: GKE
* Storage backend status:
```
HEALTH_WARN 3 filesystems are degraded; 3 MDSs report slow metadata IOs; 1 osds down; 1 host (1 osds) down; 1 region (1 osds) down; 1 root (1 osds) down; 1 zone (1 osds) down; Reduced data availability: 224 pgs stale; 7 pool(s) have no replicas configured; 742 daemons have recently crashed; OSD count 1 < osd_pool_default_size 3
```
