### ISSUE TITLE
osd creation skipped permanently if node is not READY for a short time

### ISSUE THREAD

**Issue by axel7083** [rook/rook#12506]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When a node is not available during the creation of a cluster, the creation of OSD is skipped on this node, and will never check again.

**Expected behavior:**

The OSD should be created on the node when the node match the placement settings (could happen after the cluster has been created) .

**How to reproduce it (minimal and precise):**

- Create a cluster with a storage on one or many nodes
- Before/During the creation of the Cluster the Node is not available (My problem was DISK Pressure)
- In the `rook-ceph-operator-*` pod got `op-k8sutil: skipping creation of OSDs on nodes [node-name]: placement settings do not match`
- 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.6
  dataDirHostPath: /var/lib/rook
  mon:
    count: 2
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  # cluster level storage configuration and selection
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    config:
      metadataDevice:
    nodes:
    - name: "node-1"
      devices:            
      - name: "raw-partition"
    - name: "node-2"
      devices:            
      - name: "raw-partition"
```

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Investigation**

The problem come from the `GetValidNodes` functions in [pkg/operator/k8sutil/node.go](https://github.com/rook/rook/blob/1913413ddf1251822ff17b2a94eabdc30997d510/pkg/operator/k8sutil/node.go#L68). They are only checked once when creating the cluster (pkg/operator/ceph/cluster/cluster.go -> initializeCluster)

Maybe watching for nodes status changes, and reconcile on those changes could be a solution.

**Cluster Status to submit**:

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux 7
* Kernel (e.g. `uname -a`): `Linux <host> 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Using raw partition
* Rook version (use `rook version` inside of a Rook Pod): v1.11.9
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)
* Kubernetes version (use `kubectl version`):  1.25.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): On Premise deployed with kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): unknown
