### ISSUE TITLE
Auto discover new disk

### ISSUE THREAD

**Issue by gvrosun** [rook/rook#12567]
Hi, I'm setting up rook ceph cluster on my kubernetes cluster for storage management.

Steps I followed.
-> Created k8s cluster
-> I attached 200GB raw disk to random 4 worker nodes
-> Cloned rook git repo v1.12.0
-> Modifed 2 values ROOK_ENABLE_DISCOVERY_DAEMON: "true" and    - name: ROOK_DISCOVER_DEVICES_INTERVAL value: "5m" on operator.yaml file
-> Deployed rook ceph v1.12.0 sucessfully on k8s cluster.

I can see 800GB total storage as expected on ceph cluster
```
bash-4.4$ ceph osd status
ID  HOST      USED  AVAIL  WR OPS  WR DATA  RD OPS  RD DATA  STATE      
 0  worker1  5071M   195G     30     5468k      4      422k  exists,up  
 1  worker2  5677M   194G     40     9751k      1      112   exists,up  
 2  worker4  5842M   194G     36     9161k      0        0   exists,up  
 3  worker3  4764M   195G     29     7484k      0        0   exists,up  
bash-4.4$ 
```

Next I added another 200GB for 2 more workers (worker10, worker20).
```
root@worker10:~# lsblk
NAME                      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                         8:0    0   64G  0 disk 
├─sda1                      8:1    0    1M  0 part 
├─sda2                      8:2    0  1.4G  0 part /boot
└─sda3                      8:3    0 62.6G  0 part 
  └─ubuntu--vg-ubuntu--lv 253:0    0 62.6G  0 lvm  /
sdb                         8:16   0  200G  0 disk 
sr0                        11:0    1 1024M  0 rom  
```

I expected rook ceph should pickup automatically and add it to total disk. But nothing changed, Still it's 800GB total.

I looked on discovery service pod running on worker10. I noticed it discoved sdb disk of 200GB.
![image](https://github.com/rook/rook/assets/47551990/39ce5d75-b41a-45d2-bb93-70459bd16fcd)

I though, may be on demand ceph will expand it's storage. So I filled up 800GB with dummy data. Still nothing changed.

I need help with my configuration. 
Thanks

**Comment by gvrosun** [comment]
I attached a disk for ceph storage on all worker nodes. But 4 worker node have taint for different purposes.

If I look into operator logs those 4 worker nodes have been ignored.
```
 op-k8sutil: skipping creation of OSDs on nodes [master1 master2 master3 worker10 worker11 worker19 worker20]: placement settings do not match
```

I'm trying to find a way to add toleration. But I'm not sure where to add.

Please let me know how I can fix this.
Thanks

**Comment by subhamkrai** [comment]
@gvrosun please read this https://rook.github.io/docs/rook/latest/CRDs/Cluster/ceph-cluster-crd/?h=placem#placement-configuration-settings will help

**Comment by gvrosun** [comment]
Taint
```
➜ kubectl describe nodes worker10 | grep -A 5 Taints
Taints:             internet=enabled:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  worker10
  AcquireTime:     <unset>
  RenewTime:       Tue, 25 Jul 2023 11:30:23 +0530
 ```
 NodeSelector
 ```
 worker10   Ready                      worker          160d   v1.24.9   10.0.11.16    <none>        Ubuntu 20.04.5 LTS   5.4.0-147-generic   containerd://1.6.12   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,bitbucket=true,internet=enabled,kubernetes.io/arch=amd64,kubernetes.io/hostname=worker10,kubernetes.io/os=linux,node-role.kubernetes.io/worker=worker,nodepool-name=svc-pool,role=storage-node,whitelistedfordbconn=true
 ```
 cluster.yaml file
 ```
   # tolerate taints with a key of 'storage-node'.
    placement:
      all:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - storage-node
        podAffinity:
        podAntiAffinity:
        topologySpreadConstraints:
        tolerations:
        - effect: NoSchedule
          key: internet
          operator: Exists
  # The above placement information can also be specified for mon, osd, and mgr components
  #   mon:
  ```
  operator logs
  ```
  k-ceph-operator-77cf6f65d9-kzs9d worker3 07-25 11:29:00 2023-07-25 05:59:00.043830 I | op-osd: start running osds in namespace "rook-ceph"  
rook-ceph-operator-77cf6f65d9-kzs9d worker3 07-25 11:29:00 2023-07-25 05:59:00.043860 I | op-osd: wait timeout for healthy OSDs during upgrade or restart is "10m0s"  
rook-ceph-operator-77cf6f65d9-kzs9d worker3 07-25 11:29:00 2023-07-25 05:59:00.100602 I | op-osd: start provisioning the OSDs on PVCs, if needed  
rook-ceph-operator-77cf6f65d9-kzs9d worker3 07-25 11:29:00 2023-07-25 05:59:00.107681 I | op-osd: no storageClassDeviceSets defined to configure OSDs on PVCs  
rook-ceph-operator-77cf6f65d9-kzs9d worker3 07-25 11:29:00 2023-07-25 05:59:00.107788 I | op-osd: start provisioning the OSDs on nodes, if needed  
rook-ceph-operator-77cf6f65d9-kzs9d worker3 07-25 11:29:00 2023-07-25 05:59:00.543729 I | op-k8sutil: skipping creation of OSDs on nodes [master1 master2 master3 worker10 worker11 worker19 worker20 worker21 worker22 worker23 worker24 worker25 worker26 worker28 worker29 worker30 worker31 worker32 worker33 worker34 worker35 worker37 worker38 worker39]: placement settings do not match  
rook-ceph-operator-77cf6f65d9-kzs9d worker3 07-25 11:29:00 2023-07-25 05:59:00.545396 I | op-k8sutil: skipping creation of OSDs on nodes [worker27 worker36 worker9]: node is unschedulable  
rook-ceph-operator-77cf6f65d9-kzs9d worker3 07-25 11:29:00 2023-07-25 05:59:00.545820 I | op-osd: 15 of the 42 storage nodes are valid  
```
