### ISSUE TITLE
setting activeStandby: false on existing CephFilesystem has no effect

### ISSUE THREAD

**Issue by jhoblitt** [rook/rook#12576]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Changing an existing `CephFilesystem` from `activeStandby: true` to `activeStandby: false` has no effect.  The standby-replay mds have to be manually disabled by running `ceph fs set <fs> allow_standby_replay false` from the toolbox.

**Expected behavior:**

The expectation is that rook would disabled `standby-replay` mode.

**How to reproduce it (minimal and precise):**

Create a cephfs

```yaml
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: project
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
    quotas:
      maxSize: 10Gi
  dataPools:
    - failureDomain: host
      replicated:
        size: 3
      quotas:
        maxSize: 500Gi
  metadataServer:
    activeCount: 3
    activeStandby: true
    resources:
      limits:
        cpu: "4"
        memory: 2Gi
      requests:
        cpu: "4"
        memory: 2Gi
  preserveFilesystemOnDelete: false
```

<allow rook/ceph to settle>

Update the cephfs to have `activeStandby: false`:

```yaml
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: project
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
    quotas:
      maxSize: 10Gi
  dataPools:
    - failureDomain: host
      replicated:
        size: 3
      quotas:
        maxSize: 500Gi
  metadataServer:
    activeCount: 3
    activeStandby: false
    resources:
      limits:
        cpu: "4"
        memory: 2Gi
      requests:
        cpu: "4"
        memory: 2Gi
  preserveFilesystemOnDelete: false
```

<wait for rook to settle>

Check status of said cephfs, which shows mds still in `standby-replay` mode.

```bash
[root@rook-ceph-tools-7cf684f75c-kr2b8 /]# ceph fs status project
project - 1 clients
=======
RANK      STATE          MDS        ACTIVITY     DNS    INOS   DIRS   CAPS  
 0        active      project-a  Reqs:    0 /s  10.9k  4854     32     10   
 1        active      project-b  Reqs:    0 /s  11.1k    28     17      2   
 2        active      project-c  Reqs:    0 /s  70.4k  63.1k   524      0   
0-s   standby-replay  project-f  Evts:    0 /s  10.9k  4853     32      0   
1-s   standby-replay  project-d  Evts:    0 /s  11.1k    28     17      0   
2-s   standby-replay  project-e  Evts:    0 /s  70.4k  63.1k   514      0   
      POOL          TYPE     USED  AVAIL  
project-metadata  metadata  1428M  4861G  
 project-data0      data     583G  4861G  
STANDBY MDS  
  auxtel-e   
  auxtel-b   
  auxtel-f   
MDS version: ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)
```

**Environment**:

* Rook version (use `rook version` inside of a Rook Pod):
`1.11.2`

**Comment by sp98** [comment]
Previous issue around this got closed - https://github.com/rook/rook/issues/9857

**Comment by travisn** [comment]
@jhoblitt You only see this issue when editing the filesystem CR, right? When a new filesystem is created with the standby disabled, it should be working. So we need to fix this when editing the CR.

**Comment by jhoblitt** [comment]
@travisn That is a good question... I'm unsure if I ever tested creating a new cephfs with standby disabled.  For context, I was disabling standby-replay on some production systems due to a mds memory leak for standby-replay instances.

**Comment by BlaineEXE** [comment]
I thought when I tested it, it didn't matter whether it was after editing or on a new creation, active standby MDSes were always deployed no matter what.

**Comment by jhoblitt** [comment]
I think this is still a live concern.

**Comment by R-omk** [comment]
still relevant,    
https://github.com/rook/rook/issues/9857#issuecomment-1061845459

parasitic deployments are created even after manual removal

@travisn  please reopen issue

**Comment by travisn** [comment]
@R-omk Do you mean #9857 should be reopened? Please comment on that issue with more details. Not sure what you mean by parasitic deployments.

**Comment by R-omk** [comment]
@travisn ,   I investigated the problem, look at the logs in my screenshot, this is the scenario in which I reduced the number from three to two.

The logs show that the actual decrease occurred after waiting and receiving an error, however, from the waiting code (https://github.com/rook/rook/blob/460fcda544df8a6acf99afb8e052363c3ac86e2b/pkg/daemon/ceph/client/filesystem.go#L250) it is clear that the current value is compared with the actual one, but the current value will always be equal to three, and two is expected.

![image](https://github.com/rook/rook/assets/1633879/bb712dd3-1f3b-4473-b95b-f7111554b473)

**Comment by R-omk** [comment]
I also found out why turning off  `activeStandby: true`  - >   `activeStandby: false` does not reduce the number of deployments.   

.. there's just hardcoded  increasing twice

https://github.com/rook/rook/blob/460fcda544df8a6acf99afb8e052363c3ac86e2b/pkg/operator/ceph/file/mds/mds.go#L128

**Comment by BlaineEXE** [comment]
@R-omk Can you copy the full text of the log instead of just a screenshot. I can't see the base error to debug the issue further. 

It seems that the code is starting to wait for the num active mdses to change, but then exits immediately. Perhaps this is an issue with the context in `PollUntilContextTimeout`. 🤔

**Comment by visdmin** [comment]
Still relevant 👍🏼 

Just wasted multiple hours trying to get rid of the extra mds deployment using rook-ceph-cluster Helm chart values :
```yaml
metadataServer:
  activeCount: 1
  activeStandby: false
``` 

I am new to this project, but as fresh user I can still state that this behaviour should be at least well documented !
