### ISSUE TITLE
Rook StorageClass ignores reclaimPolicy attribute

### ISSUE THREAD

**Issue by costrouc** [rook/rook#1259]
A kubernetes StorageClass has a default relaimPolicy value of `Delete`. I would like to set the value to `Retain` however rook appears to ignore this attribute. In the [documentation](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming) the allowable values are `Delete`, `Recycle`, `Retain`.  My rook setup closely follows the [quickstart](https://rook.io/docs/rook/master/kubernetes.html).

```
apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: replicapool
  namespace: rook
spec:
  replicated:
    size: 2
  failureDomain: osd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-slow-retain
provisioner: rook.io/block
reclaimPolicy: Retain
parameters:
  pool: replicapool
```
![screenshot-2017-11-26 storage classes - kubernetes dashboard](https://user-images.githubusercontent.com/1740337/33244959-29750fb2-d2cf-11e7-8b28-a852309ccdbb.png)

![screenshot-2017-11-26 persistent volumes - kubernetes dashboard](https://user-images.githubusercontent.com/1740337/33244957-1dfd47d0-d2cf-11e7-8d3e-7e63bcbc3101.png)

**Comment by costrouc** [comment]
Are there any workarounds before this feature is implemented to prevent deletion of the pvclaim/pv? I want to prevent accedental delation of the PV data from my own stupidity.

**Comment by kokhang** [comment]
I am not sure if if the `reclaimPolicy` on the PV is editable but if it is, try to update it. That could be a workaround.
Keep in mind that if the underneath ceph volume is not deleted, you would have to use something like the rook toolbox or a ceph rbd command to delete it.

Also, if you want to make the PV available again, you would have to manually create the PV object and reference the underneath RBD image in it.

**Comment by hickey** [comment]
The rook provisioner is not honoring the reclaimPolicy from the storageclass (i.e. the PV is created with the Delete policy no matter what). If after the PV was created one edits the definition and changes the `persistentVolumeReclaimPolicy` to Retain, then the PV will not be deleted when it is unbound. 

I took a quick look at the `provisioner.go` code and that seemed pretty rational. The `persistentVolumeReclaimPolicy` is getting set by the `options` structure being passed into the routine, so I have to wonder if the caller is not passing the options correctly. I am not certain what calls the provisioner code otherwise I would try to track it back further.

**Comment by ivdelchev** [comment]
@kokhang How would one achieve that part - "Also, if you want to make the PV available again, you would have to manually create the PV object and reference the underneath RBD image in it." 

Some real-world yaml would be greatly appreciated.

**Comment by rtnpro** [comment]
I am using rook 0.8, and I still see that the persistent volume does not respect the `reclaimPolicy` set in `StorageClass`. Here's my `storageclass.yaml`:

```
kind: Pool
metadata:
  name: defaultpool
  namespace: rook-ceph
spec:
  replicated:
    size: 1
  #erasureCoded:
  #  dataChunks: 2
  #  codingChunks: 1
  #crushRoot: default
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: default
   annotations:
     storageclass.kubernetes.io/is-default-class: "true"
provisioner: ceph.rook.io/block
parameters:
  pool: defaultpool
  clusterNamespace: rook-ceph
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: default-retained
provisioner: ceph.rook.io/block
parameters:
  pool: defaultpool
  clusterNamespace: rook-ceph
allowVolumeExpansion: true
reclaimPolicy: Retain
---
apiVersion: ceph.rook.io/v1beta1
kind: Pool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  replicated:
    size: 2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: replicapool
provisioner: ceph.rook.io/block
parameters:
  pool: replicapool
  clusterNamespace: rook-ceph
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: replicapool-retained
provisioner: ceph.rook.io/block
parameters:
  pool: replicapool
  clusterNamespace: rook-ceph
allowVolumeExpansion: true
reclaimPolicy: Retain
```

**kubectl get pvc**

```
NAMESPACE         NAME                                              STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS           AGE
odoo-rtnpro-com   odoo-rtnpro-com-odoo                              Bound     pvc-42e1feda-97eb-11e8-baef-de1a281f9003   2Gi        RWO            replicapool-retained   22m
odoo-rtnpro-com   odoo-rtnpro-com-postgresql                        Bound     pvc-42de1876-97eb-11e8-baef-de1a281f9003   4Gi        RWO            replicapool-retained   22m
```

**kubectl get pv**

```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                                     STORAGECLASS           REASON    AGE
pvc-42de1876-97eb-11e8-baef-de1a281f9003   4Gi        RWO            Delete           Bound     odoo-rtnpro-com/odoo-rtnpro-com-postgresql                replicapool-retained             22m
pvc-42e1feda-97eb-11e8-baef-de1a281f9003   2Gi        RWO            Delete           Bound     odoo-rtnpro-com/odoo-rtnpro-com-odoo                      replicapool-retained             22m
```
