### ISSUE TITLE
when on Multus enable Rook/Ceph, pods with NAD still connect via default Network 

### ISSUE THREAD

**Issue by busyboy77** [rook/rook#12609]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When deployed using multus as the network provider with 2 different NADs, the validation tools is reporting all ok ( except slow response from the server, but this is okay as we are running the POC atm.)

the pod with the cluster NAD are still getting their PVs using the default network. I'm not sure if this is the default behavior and whether this is the right that offloads the storage traffic from the default network.

As per below given image.

![image](https://github.com/rook/rook/assets/19593617/3e68087d-8c42-4232-8d85-2b304f6c4b17)
from https://www.youtube.com/watch?v=zIS5qaG_HRw&t=694s
which says the workload pods should be connected to the public NAD. 

NAD for rook-public:
`# k -n rook-ceph get net-attach-def  rook-public -o yaml`
```YAML
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  creationTimestamp: "2023-07-24T08:44:03Z"
  generation: 1
  name: rook-public
  namespace: rook-ceph
  resourceVersion: "549254"
  uid: 7dc33a00-f7a8-46e1-a0b9-31f09aed397b
spec:
  config: '{ "cniVersion": "0.3.1","type": "macvlan","master": "enp5s0","mode": "bridge","name":
    "custom-network","isDefaultGateway": false,"ipam": {"type": "whereabouts","datastore":
    "kubernetes","kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig"
    },"range":"172.18.0.0/16","subnet": "172.18.0.0/16","rangeStart": "172.18.2.1","rangeEnd":
    "172.18.254.254","exclude": [ "172.18.1.0/24" ],"log_file" : "/tmp/whereabouts.log","log_level"
    : "debug"}}'


```

and rook-Cluster NAD

` k -n rook-ceph get net-attach-def  rook-cluster -o yaml`
```YAML
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  creationTimestamp: "2023-07-24T08:44:16Z"
  generation: 1
  name: rook-cluster
  namespace: rook-ceph
  resourceVersion: "549388"
  uid: 55deced4-4727-4be7-84df-a5219dd930e1
spec:
  config: '{ "cniVersion": "0.3.1","type": "macvlan","master": "enp4s0","mode": "bridge","name":
    "custom-network","isDefaultGateway": false,"ipam": {"type": "whereabouts","datastore":
    "kubernetes","kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig"
    },"range":"172.19.0.0/16","subnet": "172.19.0.0/16","rangeStart": "172.19.2.1","rangeEnd":
    "172.19.254.254","exclude": [ "172.19.1.0/24" ],"log_file" : "/tmp/whereabouts.log","log_level"
    : "debug"}}'


```
however, when I deploy a sample pod with the PUBLIC NAD annotation like below:
```YAML
---
apiVersion: v1
kind: Pod
metadata:
  name: csicephfs-demo-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: rook-ceph/rook-public
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: cephfs-pvc
        readOnly: false

```

and the pod runs with its IP addresses from both the default network and the public NAD.

```
# k describe pod csicephfs-demo-pod
Name:             csicephfs-demo-pod
Namespace:        default
Priority:         0
Service Account:  default
Node:             devops68/10.192.168.68
Start Time:       Wed, 26 Jul 2023 14:49:01 +0500
Labels:           <none>
Annotations:      cni.projectcalico.org/containerID: 7ea431655d259eea83df49dc71d96596a01ecbfb53a340264118b29de9aa6f5e
                  cni.projectcalico.org/podIP: 10.42.1.148/32
                  cni.projectcalico.org/podIPs: 10.42.1.148/32
                  k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "k8s-pod-network",
                        "ips": [
                            "10.42.1.148"
                        ],
                        "default": true,
                        "dns": {}
                    },{
                        "name": "rook-ceph/rook-cluster",
                        "interface": "net1",
                        "ips": [
                            "172.18.0.52"
                        ],
                        "mac": "52:cf:18:03:ac:a7",
                        "dns": {}
                    }]
                  k8s.v1.cni.cncf.io/networks: rook-ceph/rook-public
                  k8s.v1.cni.cncf.io/networks-status:
                    [{
                        "name": "k8s-pod-network",
                        "ips": [
                            "10.42.1.148"
                        ],
                        "default": true,
                        "dns": {}
                    },{
                        "name": "rook-ceph/rook-public",
                        "interface": "net1",
                        "ips": [
                            "172.18.0.52"
                        ],
                        "mac": "52:cf:18:03:ac:a7",
                        "dns": {}
                    }]
Status:           Running
IP:               10.42.1.148


```

and inside the POD I can see the Volume is attached using default network IP addresses rather than the rook-public IPs

```
# k exec -ti csicephfs-demo-pod  -- df -h
Filesystem                                                                                                                                                                                Size  Used Avail Use% Mounted on
overlay                                                                                                                                                                                   149G   28G  122G  19% /
tmpfs                                                                                                                                                                                      64M     0   64M   0% /dev
/dev/vda4                                                                                                                                                                                 149G   28G  122G  19% /etc/hosts
shm                                                                                                                                                                                        64M     0   64M   0% /dev/shm
10.43.141.2:6789,10.43.141.125:6789,10.43.20.122:6789,10.43.22.97:6789,10.43.148.252:6789:/volumes/csi/csi-vol-adcd66d7-ab74-47cc-9a45-c484a002d2fa/ab04678b-6f52-44f2-9b66-51c8cb1028a9  1.0G     0  1.0G   0% /var/lib/www/html
tmpfs                                                                                                                                                                                      24G   12K   24G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                                                                                                                                      12G     0   12G   0% /proc/acpi
tmpfs                                                                                                                                                                                      12G     0   12G   0% /proc/scsi
tmpfs                                                                                                                                                                                      12G     0   12G   0% /sys/firmware
```

All these volume mounts are from the default network which means the POD still communicates with the PV over the default network rather than using the rook-public NAD ( 10.43.141.2:6789,10.43.141.125:6789,10.43.20.122:6789,10.43.22.97:6789,10.43.148.252:6789  is the default network range )

the csi sample pods as all these required NICs

```
# k exec -it csicephfs-demo-pod -- ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if31: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether 0a:93:23:d5:ff:89 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.42.1.148/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::893:23ff:fed5:ff89/64 scope link
       valid_lft forever preferred_lft forever
4: net1@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 52:cf:18:03:ac:a7 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.0.52/16 brd 172.18.255.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::50cf:18ff:fe03:aca7/64 scope link
       valid_lft forever preferred_lft forever

```
As per my understanding and the experience with Longhorn based CNS, the NADs are defined with a pure purpose of defining the Storage traffic and the StorageClass assigns the PVs with separate NADs.

is this something I am not correct or am I missing something. 

If the volume attachments are still coming from the default network, even using the Multus , then we are not using the separate network and putting all the traffic including storage workload onto the same pipe.

Can someone please guide

**Expected behavior:**

When multus networks are using, the volume traffic should be routed to the separate net instead of the default NIC.

**How to reproduce it (minimal and precise):**

Just follow the default multus integration guide with Rook/Ceph

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* 
`# egrep -v "^[ ]*#|^$" cluster.yaml`
```YAML
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph # namespace:cluster
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.6
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  waitTimeoutForHealthyOSDInMinutes: 15
  mon:
    count: 5
    allowMultiplePerNode: false
  mgr:
    count: 2
    allowMultiplePerNode: false
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    ssl: false
  monitoring:
    enabled: true
    metricsDisabled: false
  network:
    connections:
      encryption:
        enabled: false
      compression:
        enabled: false
      requireMsgr2: false
    provider: multus
    selectors:
      public: rook-public
      cluster: rook-cluster
  crashCollector:
    disable: false
  logCollector:
    enabled: true
    periodicity: daily # one of: hourly, daily, weekly, monthly
    maxLogSize: 500M # SUFFIX may be 'M' or 'G'. Must be at least 1M.
  cleanupPolicy:
    confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
    allowUninstallWithVolumes: false
  annotations:
  labels:
  resources:
  removeOSDsIfOutAndSafeToRemove: false
  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: true
    config:
    onlyApplyOSDPlacement: false
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
    startupProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
```

**Logs to submit**:

* Operator's logs, if necessary
attached logs f
[k-rook-ceph-logs-operator.txt](https://github.com/rook/rook/files/12183196/k-rook-ceph-logs-operator.txt)
ile

* Crashing pod(s) logs, if necessary
none so far

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`

```
# kubectl rook-ceph health
Info: Checking if at least three mon pods are running on different nodes
rook-ceph-mon-a-6ff856cb99-mqxn9        Running rook-ceph       devops68
rook-ceph-mon-b-78fcfdb84d-76fvz        Running rook-ceph       devops64
rook-ceph-mon-c-7bc7cf9655-48jck        Running rook-ceph       devops66
rook-ceph-mon-d-84b6b5869f-k5b4b        Running rook-ceph       devops69
rook-ceph-mon-e-78b8d86866-knqjp        Running rook-ceph       devops65

Info: Checking mon quorum and ceph health details
Info: HEALTH_OK

Info: Checking if at least three osd pods are running on different nodes
rook-ceph-osd-0-54455fc47-dsz69 Running rook-ceph       devops64
rook-ceph-osd-1-8676c4f59-zq4xk Running rook-ceph       devops65
rook-ceph-osd-2-86b5966cb-k25vj Running rook-ceph       devops66
rook-ceph-osd-3-9865f466b-fdkc8 Running rook-ceph       devops68
rook-ceph-osd-4-555fbb995d-tzc2w        Running rook-ceph       devops69

Info: Pods that are in 'Running' or `Succeeded` status
csi-cephfsplugin-4wngp   Running         rook-ceph       devops65
csi-cephfsplugin-5qglj   Running         rook-ceph       devops62
csi-cephfsplugin-8rc4f   Running         rook-ceph       devops63
csi-cephfsplugin-b5m6q   Running         rook-ceph       devops66
csi-cephfsplugin-d5cqk   Running         rook-ceph       devops61
csi-cephfsplugin-fmjmk   Running         rook-ceph       devops69
csi-cephfsplugin-ghqh6   Running         rook-ceph       devops64
csi-cephfsplugin-holder-rook-ceph-4vtb4          Running         rook-ceph       devops68
csi-cephfsplugin-holder-rook-ceph-8767r          Running         rook-ceph       devops64
csi-cephfsplugin-holder-rook-ceph-fdwn4          Running         rook-ceph       devops69
csi-cephfsplugin-holder-rook-ceph-kdjh4          Running         rook-ceph       devops63
csi-cephfsplugin-holder-rook-ceph-mm82v          Running         rook-ceph       devops65
csi-cephfsplugin-holder-rook-ceph-w6rgx          Running         rook-ceph       devops62
csi-cephfsplugin-holder-rook-ceph-wsqkz          Running         rook-ceph       devops66
csi-cephfsplugin-holder-rook-ceph-xhqhd          Running         rook-ceph       devops61
csi-cephfsplugin-kkns5   Running         rook-ceph       devops68
csi-cephfsplugin-provisioner-6bbfb66484-2bdzx    Running         rook-ceph       devops66
csi-cephfsplugin-provisioner-6bbfb66484-2cwzc    Running         rook-ceph       devops65
csi-rbdplugin-5xdl4      Running         rook-ceph       devops63
csi-rbdplugin-bg4jq      Running         rook-ceph       devops64
csi-rbdplugin-czzhc      Running         rook-ceph       devops66
csi-rbdplugin-d2fm5      Running         rook-ceph       devops69
csi-rbdplugin-frlbq      Running         rook-ceph       devops61
csi-rbdplugin-gnkvr      Running         rook-ceph       devops62
csi-rbdplugin-holder-rook-ceph-7c92w     Running         rook-ceph       devops63
csi-rbdplugin-holder-rook-ceph-7pj4f     Running         rook-ceph       devops61
csi-rbdplugin-holder-rook-ceph-cnbqx     Running         rook-ceph       devops62
csi-rbdplugin-holder-rook-ceph-jx82l     Running         rook-ceph       devops66
csi-rbdplugin-holder-rook-ceph-ldgt4     Running         rook-ceph       devops65
csi-rbdplugin-holder-rook-ceph-phs8c     Running         rook-ceph       devops64
csi-rbdplugin-holder-rook-ceph-vtd9b     Running         rook-ceph       devops69
csi-rbdplugin-holder-rook-ceph-zv4b5     Running         rook-ceph       devops68
csi-rbdplugin-kxd8v      Running         rook-ceph       devops65
csi-rbdplugin-provisioner-6c85dc596b-fxsnt       Running         rook-ceph       devops64
csi-rbdplugin-provisioner-6c85dc596b-x6wg6       Running         rook-ceph       devops68
csi-rbdplugin-tl87z      Running         rook-ceph       devops68
rook-ceph-crashcollector-devops64-5dc7f9f778-tcwck       Running         rook-ceph       devops64
rook-ceph-crashcollector-devops65-64674cc57c-slbm8       Running         rook-ceph       devops65
rook-ceph-crashcollector-devops66-6466dc9bb6-nhlfg       Running         rook-ceph       devops66
rook-ceph-crashcollector-devops68-847d946766-vchf6       Running         rook-ceph       devops68
rook-ceph-crashcollector-devops69-545b595f6c-5h76c       Running         rook-ceph       devops69
rook-ceph-mds-myfs-ec-a-769775bfdb-qczsw         Running         rook-ceph       devops69
rook-ceph-mds-myfs-ec-b-89ddfbb45-w24s7          Running         rook-ceph       devops66
rook-ceph-mgr-a-d85c7975d-tkz9f          Running         rook-ceph       devops69
rook-ceph-mgr-b-5f99944b5f-dwxdf         Running         rook-ceph       devops64
rook-ceph-mon-a-6ff856cb99-mqxn9         Running         rook-ceph       devops68
rook-ceph-mon-b-78fcfdb84d-76fvz         Running         rook-ceph       devops64
rook-ceph-mon-c-7bc7cf9655-48jck         Running         rook-ceph       devops66
rook-ceph-mon-d-84b6b5869f-k5b4b         Running         rook-ceph       devops69
rook-ceph-mon-e-78b8d86866-knqjp         Running         rook-ceph       devops65
rook-ceph-operator-749567dc87-49jtl      Running         rook-ceph       devops68
rook-ceph-osd-0-54455fc47-dsz69          Running         rook-ceph       devops64
rook-ceph-osd-1-8676c4f59-zq4xk          Running         rook-ceph       devops65
rook-ceph-osd-2-86b5966cb-k25vj          Running         rook-ceph       devops66
rook-ceph-osd-3-9865f466b-fdkc8          Running         rook-ceph       devops68
rook-ceph-osd-4-555fbb995d-tzc2w         Running         rook-ceph       devops69
rook-ceph-osd-prepare-devops61-t22p2     Succeeded       rook-ceph       devops61
rook-ceph-osd-prepare-devops62-pwhwv     Succeeded       rook-ceph       devops62
rook-ceph-osd-prepare-devops63-mld8k     Succeeded       rook-ceph       devops63
rook-ceph-osd-prepare-devops64-w44nz     Succeeded       rook-ceph       devops64
rook-ceph-osd-prepare-devops65-wkkc4     Succeeded       rook-ceph       devops65
rook-ceph-osd-prepare-devops66-wlxb7     Succeeded       rook-ceph       devops66
rook-ceph-osd-prepare-devops68-2nngx     Succeeded       rook-ceph       devops68
rook-ceph-osd-prepare-devops69-5gpg6     Succeeded       rook-ceph       devops69
rook-ceph-tools-887bf79df-gx4bg          Running         rook-ceph       devops68

Warning: Pods that are 'Not' in 'Running' status

Info: Checking placement group status
Info:   PgState: active+clean, PgCount: 145

Info: Checking if at least one mgr pod is running
rook-ceph-mgr-a-d85c7975d-tkz9f Running rook-ceph       devops69
rook-ceph-mgr-b-5f99944b5f-dwxdf        Running rook-ceph       devops64

```

  To get the status of the cluster, use `kubectl rook-ceph ceph status`
```
# kubectl rook-ceph ceph status
Info: running 'ceph' command with args: [status]
  cluster:
    id:     c33ea0e7-e3c9-46f2-9653-f4061b48652b
    health: HEALTH_OK

  services:
    mon: 5 daemons, quorum a,b,c,d,e (age 14h)
    mgr: a(active, since 14h), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 5 osds: 5 up (since 14h), 5 in (since 3d)

  data:
    volumes: 1/1 healthy
    pools:   6 pools, 145 pgs
    objects: 932 objects, 2.9 GiB
    usage:   5.3 GiB used, 995 GiB / 1000 GiB avail
    pgs:     145 active+clean

  io:
    client:   1.4 KiB/s rd, 596 B/s wr, 2 op/s rd, 0 op/s wr



```
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
Ubuntu-22.04
* Kernel (e.g. `uname -a`):
`Linux devops61 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
KVM based POC cluster 
* Rook version (use `rook version` inside of a Rook Pod):
no such command inside any of the pods

* Storage backend version (e.g. for ceph do `ceph -v`):
```
# k rook-ceph ceph -v
Info: running 'ceph' command with args: [-v]
ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)
```

* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.11+rke2r1", GitCommit:"8cfcba0b15c343a8dc48567a74c29ec4844e0b9e", GitTreeState:"clean", BuildDate:"2023-06-14T21:31:34Z", GoVersion:"go1.19.10 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.11+rke2r1", GitCommit:"8cfcba0b15c343a8dc48567a74c29ec4844e0b9e", GitTreeState:"clean", BuildDate:"2023-06-14T21:31:34Z", GoVersion:"go1.19.10 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
RKE2

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

```
# k rook-ceph ceph health
Info: running 'ceph' command with args: [health]
HEALTH_OK
```

PS. The Cluster was rebooted due to disk operations on the KVM host, so you might see some issues with failure domains happening.
