### ISSUE TITLE
Module 'devicehealth' has failed: osd pool create failed: No suitable CRUSH rule exists, check 'osd pool default crush *' config options retval: -2 (MGR_MODULE_ERROR)

### ISSUE THREAD

**Issue by jsalatiel** [rook/rook#12610]
**Is this a bug report or feature request?**
* Bug Report

The message I get in this bug is the same i got on #12356, but now using the 1.12.0 release and the .mgr pool has been created just fine, but i still get the same error.

I am building a small test cluster in stretched mode.
I have 3 nodes:
stg1 -> zone dc7
stg2 -> zone dcc
stg3 -> zone dca arbiter

stg1 and stg2 has 3 extra disks, which will be used for the 4 osds required and I am using subFailureDomain: osd.

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph # namespace:cluster
spec:
  crashCollector:
    disable: true
  dataDirHostPath: /var/lib/rook
  monitoring:
    enabled: false
  mon:
    # Five mons must be created for stretch mode
    count: 5
    allowMultiplePerNode: false
    stretchCluster:
      failureDomainLabel: topology.kubernetes.io/zone
      subFailureDomain: osd
      zones:
        - name: dca
          arbiter: true
        - name: dcc
        - name: dc7
  mgr:
    count: 2
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.6
    allowUnsupported: true
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  dashboard:
    enabled: true
    ssl: false
  #network:
  #  provider: host
  storage:
    useAllNodes: true
    useAllDevices: true
    deviceFilter: ""
  # OSD placement is expected to include the non-arbiter zones
  placement:
    all:
      tolerations:
        - key: taint/node-role
          operator: Exists
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                    - dcc
                    - dc7
                - key: storage-node
                  operator: Exists
  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
  disruptionManagement:
    managePodBudgets: true

---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: builtin-mgr
  namespace: rook-ceph
spec:
  name: .mgr
  failureDomain: zone
  replicated:
    size: 4
    requireSafeReplicaSize: true
    replicasPerFailureDomain: 2
    subFailureDomain: osd


```
**Logs to submit**:

* Operator's logs, if necessary
[operator.log](https://pastebin.com/0dUH8S3A)

**Cluster Status to submit**:
```
ceph status
  cluster:
    id:     6136021e-be33-4ec5-8f44-2e7a85d270d2
    health: HEALTH_ERR
            Module 'devicehealth' has failed: osd pool create failed: No suitable CRUSH rule exists, check 'osd pool default crush *' config options retval: -2
 
  services:
    mon: 5 daemons, quorum a,b,c,d,e (age 39m)
    mgr: b(active, since 39m), standbys: a
    osd: 6 osds: 6 up (since 39m), 6 in (since 39m)
 
  data:
    pools:   1 pools, 32 pgs
    objects: 0 objects, 0 B
    usage:   120 MiB used, 120 GiB / 120 GiB avail
    pgs:     32 active+clean

```
```
# ceph  health
HEALTH_ERR Module 'devicehealth' has failed: osd pool create failed: No suitable CRUSH rule exists, check 'osd pool default crush *' config options retval: -2
```

```
# ceph osd crush rule ls
replicated_rule
default_stretch_cluster_rule
# ceph osd pool ls
.mgr
# ceph osd pool get .mgr crush_rule
crush_rule: default_stretch_cluster_rule
```
```
# ceph osd getcrushmap -o /tmp/cm.bin
# crushtool -d /tmp/cm.bin -o /tmp/cm.bin.ascii
# cat /tmp/cm.bin.ascii
# begin crush map
tunable choose_local_tries 0
tunable choose_local_fallback_tries 0
tunable choose_total_tries 50
tunable chooseleaf_descend_once 1
tunable chooseleaf_vary_r 1
tunable chooseleaf_stable 1
tunable straw_calc_version 1
tunable allowed_bucket_algs 54

# devices
device 0 osd.0 class hdd
device 1 osd.1 class hdd
device 2 osd.2 class hdd
device 3 osd.3 class hdd
device 4 osd.4 class hdd
device 5 osd.5 class hdd

# types
type 0 osd
type 1 host
type 2 chassis
type 3 rack
type 4 row
type 5 pdu
type 6 pod
type 7 room
type 8 datacenter
type 9 zone
type 10 region
type 11 root

# buckets
host stg1 {
	id -3		# do not change unnecessarily
	id -5 class hdd		# do not change unnecessarily
	# weight 0.05846
	alg straw2
	hash 0	# rjenkins1
	item osd.4 weight 0.01949
	item osd.0 weight 0.01949
	item osd.2 weight 0.01949
}
zone dcc {
	id -4		# do not change unnecessarily
	id -6 class hdd		# do not change unnecessarily
	# weight 0.05846
	alg straw2
	hash 0	# rjenkins1
	item stg1 weight 0.05846
}
host stg2 {
	id -7		# do not change unnecessarily
	id -9 class hdd		# do not change unnecessarily
	# weight 0.05846
	alg straw2
	hash 0	# rjenkins1
	item osd.5 weight 0.01949
	item osd.1 weight 0.01949
	item osd.3 weight 0.01949
}
zone dc7 {
	id -8		# do not change unnecessarily
	id -10 class hdd		# do not change unnecessarily
	# weight 0.05846
	alg straw2
	hash 0	# rjenkins1
	item stg2 weight 0.05846
}
root default {
	id -1		# do not change unnecessarily
	id -2 class hdd		# do not change unnecessarily
	# weight 0.11691
	alg straw2
	hash 0	# rjenkins1
	item dcc weight 0.05846
	item dc7 weight 0.05846
}

# rules
rule replicated_rule {
	id 0
	type replicated
	step take default
	step chooseleaf firstn 0 type host
	step emit
}
rule default_stretch_cluster_rule {
	id 1
	type replicated
	step take default
	step choose firstn 0 type zone
	step chooseleaf firstn 2 type osd
	step emit
}

# end crush map

```
```
# ceph osd tree
ID  CLASS  WEIGHT   TYPE NAME          STATUS  REWEIGHT  PRI-AFF
-1         0.11691  root default                                
-8         0.05846      zone dc7                                
-7         0.05846          host stg2                           
 1    hdd  0.01949              osd.1      up   1.00000  1.00000
 3    hdd  0.01949              osd.3      up   1.00000  1.00000
 5    hdd  0.01949              osd.5      up   1.00000  1.00000
-4         0.05846      zone dcc                                
-3         0.05846          host stg1                           
 0    hdd  0.01949              osd.0      up   1.00000  1.00000
 2    hdd  0.01949              osd.2      up   1.00000  1.00000
 4    hdd  0.01949              osd.4      up   1.00000  1.00000

```

```
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): AlmaLinux release 9.2 (Turquoise Kodkod)
* Kernel (e.g. `uname -a`): 5.14.0-284.18.1.el9_2.x86_64
* Cloud provider or hardware configuration: onprem
* Rook version (use `rook version` inside of a Rook Pod):
```
rook: v1.12.0
go: go1.20.5
```
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"890a139214b4de1f01543d15003b5bda71aae9c7", GitTreeState:"clean", BuildDate:"2023-05-17T14:14:46Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"890a139214b4de1f01543d15003b5bda71aae9c7", GitTreeState:"clean", BuildDate:"2023-05-17T14:08:49Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): onprem/kubespray

**Comment by parth-gr** [comment]
`kubect get cephblockpool -nnamespace` ?

Your pool I think is not getting created

**Comment by jsalatiel** [comment]
```
# kubectl get cephblockpool -A
NAMESPACE   NAME          PHASE
rook-ceph   builtin-mgr   Ready


```

**Comment by travisn** [comment]
Other than the health warning, do you see any other side effects? Are you able to create more pools other than the default `.mgr`? I can't see the cause of the warning since the `.mgr` pool was created successfully and has the expected CRUSH rule.

Here are a couple of issues to look at, though they don't look related:
- `mon.allowMultiplePerNode: true` should be set, so you can have two mons per node in the data zones, and give you 5 mons. Your ceph status shows you have all 5 mons running, i'm just not sure how that's possible unless you set this to true.
- No need to set all the pool properties related to the CRUSH rules, since stretch clusters will automatically use the default stretch rule. Really there is no need to create the CephBlockPool CR for `.mgr`, but it shouldn't hurt either. Although, perhaps this pool was created before the stretch mode was enabled and caused the warning. So you might try creating the cluster fresh without this CR and see if it helps.

**Comment by jsalatiel** [comment]
HI @travisn , my bad! I had a few other nodes and the mons are running there, but since they are not for OSD i had not mentioned.
```
kubectl get nodes
NAME      STATUS   ROLES           AGE     VERSION
master1   Ready    control-plane   6h12m   v1.26.5
node1     Ready    <none>          6h11m   v1.26.5
node2     Ready    <none>          6h11m   v1.26.5
stg1      Ready    <none>          6h11m   v1.26.5
stg2      Ready    <none>          6h11m   v1.26.5
stg3      Ready    <none>          6h11m   v1.26.5
```

```
kubectl get pods -o wide
NAME                                            READY   STATUS      RESTARTS   AGE     IP               NODE    NOMINATED NODE   READINESS GATES
csi-cephfsplugin-4n44z                          2/2     Running     0          4h51m   192.168.254.43   node2   <none>           <none>
csi-cephfsplugin-hdgmz                          2/2     Running     0          4h51m   192.168.254.46   stg3    <none>           <none>
csi-cephfsplugin-k4bsb                          2/2     Running     0          4h51m   192.168.254.45   stg2    <none>           <none>
csi-cephfsplugin-lgnhg                          2/2     Running     0          4h51m   192.168.254.44   stg1    <none>           <none>
csi-cephfsplugin-pr58m                          2/2     Running     0          4h51m   192.168.254.42   node1   <none>           <none>
csi-cephfsplugin-provisioner-7fbcdb4dcf-978wg   5/5     Running     0          4h51m   10.238.79.4      stg1    <none>           <none>
csi-cephfsplugin-provisioner-7fbcdb4dcf-bj7dr   5/5     Running     0          4h51m   10.238.102.195   stg2    <none>           <none>
csi-rbdplugin-2c7tr                             2/2     Running     0          4h51m   192.168.254.42   node1   <none>           <none>
csi-rbdplugin-h5vhr                             2/2     Running     0          4h51m   192.168.254.43   node2   <none>           <none>
csi-rbdplugin-m7mxh                             2/2     Running     0          4h51m   192.168.254.46   stg3    <none>           <none>
csi-rbdplugin-m8mcv                             2/2     Running     0          4h51m   192.168.254.45   stg2    <none>           <none>
csi-rbdplugin-provisioner-8c7858465-85vpr       5/5     Running     0          4h51m   10.238.102.194   stg2    <none>           <none>
csi-rbdplugin-provisioner-8c7858465-v2brc       5/5     Running     0          4h51m   10.238.79.3      stg1    <none>           <none>
csi-rbdplugin-wqrgl                             2/2     Running     0          4h51m   192.168.254.44   stg1    <none>           <none>
rook-ceph-mgr-a-6c4d49955f-p9kln                2/2     Running     0          4h43m   10.238.80.68     stg3    <none>           <none>
rook-ceph-mgr-b-f9874f479-lg7hq                 2/2     Running     0          4h43m   10.238.75.9      node2   <none>           <none>
rook-ceph-mon-a-7cb4f9888-nhrvz                 1/1     Running     0          4h49m   10.238.80.67     stg3    <none>           <none>
rook-ceph-mon-b-6cf6478888-x9prj                1/1     Running     0          4h48m   10.238.102.135   node1   <none>           <none>
rook-ceph-mon-c-787b445b78-cf7wn                1/1     Running     0          4h46m   10.238.79.6      stg1    <none>           <none>
rook-ceph-mon-d-7f77667fbc-lrczh                1/1     Running     0          4h45m   10.238.75.8      node2   <none>           <none>
rook-ceph-mon-e-7f9d65bf57-c7477                1/1     Running     0          4h44m   10.238.102.197   stg2    <none>           <none>
rook-ceph-operator-d54b4cc6f-p8dlf              1/1     Running     0          5h1m    10.238.102.133   node1   <none>           <none>
rook-ceph-osd-0-54f4bb669b-p85r9                1/1     Running     0          4h42m   10.238.79.9      stg1    <none>           <none>
rook-ceph-osd-1-575b9565fd-4qxjg                1/1     Running     0          4h42m   10.238.102.199   stg2    <none>           <none>
rook-ceph-osd-2-95cc757cb-rl2hv                 1/1     Running     0          4h42m   10.238.79.10     stg1    <none>           <none>
rook-ceph-osd-3-6fc797d68-85s6j                 1/1     Running     0          4h42m   10.238.102.201   stg2    <none>           <none>
rook-ceph-osd-4-5497b77979-qtdds                1/1     Running     0          4h42m   10.238.79.8      stg1    <none>           <none>
rook-ceph-osd-5-69d58b7d85-wtplq                1/1     Running     0          4h42m   10.238.102.200   stg2    <none>           <none>
rook-ceph-osd-prepare-stg1-wbx6c                0/1     Completed   0          4h43m   10.238.79.7      stg1    <none>           <none>
rook-ceph-osd-prepare-stg2-6h5j6                0/1     Completed   0          4h43m   10.238.102.198   stg2    <none>           <none>
rook-ceph-tools-9b7967b5d-vmw68                 1/1     Running     0          4h40m   10.238.102.136   node1   <none>           <none>
rook-discover-7vdkl                             1/1     Running     0          5h      10.238.102.193   stg2    <none>           <none>
rook-discover-wrl5n                             1/1     Running     0          5h      10.238.79.1      stg1    <none>           <none>
```


I will check  creation of other pools, althougt that health error is problematic if i go to production even if everything is working.


This cluster is brand new, created only to test version rook 1.12.0.
So i followed the quick guide:
```
cd rook/deploy/examples
kubectl create -f crds.yaml -f common.yaml 
Changed operator tolerations and kubectl create -f operator.yaml
Changed cluster-stretched.yaml to the one above and  kubectl create -f cluster-stretched.yaml

```

**Comment by travisn** [comment]
Got it, makes sense now for the mons.
I see in #12360 that the stretch cluster seems confused if we don't create that .mgr pool (and it's amazing how quickly I forget!)

Will investigate more soon...

**Comment by jsalatiel** [comment]
Other pools just get in Progressing state forever.
btw, this is the operator-config.yml I use:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
  namespace: rook-ceph # namespace:operator
data:
  ROOK_LOG_LEVEL: "INFO"
  ROOK_CEPH_ALLOW_LOOP_DEVICES: "false"
  ROOK_CSI_ENABLE_CEPHFS: "true"
  ROOK_CSI_ENABLE_RBD: "true"
  ROOK_CSI_ENABLE_NFS: "false"
  ROOK_CSI_ENABLE_GRPC_METRICS: "false"
  CSI_ENABLE_ENCRYPTION: "false"
  CSI_ENABLE_METADATA: "true"
  CSI_CLUSTER_NAME: "my-prd-cluster"
  CSI_PROVISIONER_REPLICAS: "2"
  CSI_ENABLE_CEPHFS_SNAPSHOTTER: "true"
  CSI_ENABLE_NFS_SNAPSHOTTER: "false"
  CSI_ENABLE_RBD_SNAPSHOTTER: "true"
  CSI_FORCE_CEPHFS_KERNEL_CLIENT: "true"
  CSI_RBD_FSGROUPPOLICY: "File"
  CSI_CEPHFS_FSGROUPPOLICY: "File"
  CSI_NFS_FSGROUPPOLICY: "File"
  ROOK_CSI_ALLOW_UNSUPPORTED_VERSION: "false"
  CSI_PLUGIN_ENABLE_SELINUX_HOST_MOUNT: "false"
  CSI_PLUGIN_PRIORITY_CLASSNAME: "system-node-critical"
  CSI_PROVISIONER_PRIORITY_CLASSNAME: "system-cluster-critical"
  CSI_PROVISIONER_NODE_AFFINITY: "storage-node=True"
  CSI_PROVISIONER_TOLERATIONS: |
   - key: taint/node-role
     operator: Exists
  CSI_PLUGIN_NODE_AFFINITY: "storage-node=True"
  CSI_PLUGIN_TOLERATIONS: |
   - key: taint/node-role
     operator: Exists
  CSI_RBD_PROVISIONER_TOLERATIONS: |
    - operator: Exists
      key: taint/node-role
  CSI_RBD_PLUGIN_NODE_AFFINITY: |
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: Exists
  CSI_CEPHFS_PLUGIN_NODE_AFFINITY: |
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: Exists
  CSI_CEPHFS_PLUGIN_TOLERATIONS: |
    - operator: Exists
      key: taint/node-role
  CSI_ENABLE_LIVENESS: "true"
  ROOK_OBC_WATCH_OPERATOR_NAMESPACE: "true"
  ROOK_ENABLE_DISCOVERY_DAEMON: "true"
  ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS: "15"
  CSI_ENABLE_CSIADDONS: "false"
  CSI_GRPC_TIMEOUT_SECONDS: "150"
  ROOK_DISABLE_ADMISSION_CONTROLLER: "true"
  CSI_ENABLE_TOPOLOGY: "true"
  CSI_TOPOLOGY_DOMAIN_LABELS: "kubernetes.io/hostname,topology.kubernetes.io/zone"
  CSI_ENABLE_READ_AFFINITY: "false"
  CSI_CEPHFS_ATTACH_REQUIRED: "true"
  CSI_RBD_ATTACH_REQUIRED: "true"
  CSI_NFS_ATTACH_REQUIRED: "false"
```
