### ISSUE TITLE
Failed to create bucket

### ISSUE THREAD

**Issue by tyxubaoying** [rook/rook#12654]
use object.yaml
object-bucket-claim-delete.yaml and  storageclass-bucket-delete.yaml 
echo "==============="

-sh-4.2$ cat object.yaml 
```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: test-bucket
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: true
  gateway:
    sslCertificateRef:
    port: 80
    # securePort: 443
    instances: 1
```

sh-4.2$ cat object.yaml 
```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: test-bucket
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: true
  gateway:
    sslCertificateRef:
    port: 80
    # securePort: 443
    instances: 1
```
-sh-4.2$ cat object-bucket-claim-delete.yaml 
```yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-delete-bucket
spec:
  # To create a new bucket specify either `bucketName` or
  # `generateBucketName` here. Both cannot be used. To access
  # an existing bucket the bucket name needs to be defined in
  # the StorageClass referenced here, and both `bucketName` and
  # `generateBucketName` must be omitted in the OBC.
  generateBucketName: test-obj
  storageClassName: rook-ceph-delete-bucket
  additionalConfig:
    # To set for quota for OBC
    #maxObjects: "1000"
    #maxSize: "2G"
```
-sh-4.2$ cat object-bucket-claim-delete.yaml 
```yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-delete-bucket
spec:
  bucketName: test-obj
  generateBucketName: test-obj
  storageClassName: rook-ceph-delete-bucket
  additionalConfig:
    # To set for quota for OBC
    #maxObjects: "1000"
    #maxSize: "2G"
```
-sh-4.2$ cat object-bucket-claim-delete.yaml ^C
-sh-4.2$ cat storageclass-bucket-delete.yaml 
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-delete-bucket
provisioner: rook-ceph.ceph.rook.io/bucket # driver:namespace:cluster
# set the reclaim policy to delete the bucket and all objects
# when its OBC is deleted.
reclaimPolicy: Delete
parameters:
   objectStoreName: test-obj
   objectStoreNamespace: rook-ceph # namespace:cluster
```
```
[root@rook-ceph-tools-5f846f89ff-dbx75 /]# radosgw-admin bucket list      
[
    "rook-ceph-bucket-checker-6b31dde5-0d42-49a9-ab96-1ceef0a3b447",
    "document-bucket-d34256a3-1a89-4d5b-a733-c8bbc2029138"
]
```

I only see the following log： Repeatedly changing the corresponding names and recreating multiple ones didn't work.
![image](https://github.com/rook/rook/assets/115436551/d03174e4-7cda-415a-a028-886a983ff7e6)
