### ISSUE TITLE
multus-cluster-network canary test is failing consistently

### ISSUE THREAD

**Issue by travisn** [rook/rook#12670]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The multus test is failing consistently. The OSDs are not starting properly.

The OSDs are not coming `in`, so the test is stuck on the "waiting for ceph to be ready" step.
```
  services:
    mon: 1 daemons, quorum a (age 9m)
    mgr: a(active, since 6m)
    mds: 0/0 daemons up
    osd: 2 osds: 0 up, 2 in (since 7m)
 ```

Looking at an OSD pod log from the multus test, it shows:
```
debug 2023-08-03T14:28:18.158+0000 7f236496e540 -1 unable to find any IPv4 address in networks '192.168.20.0/24' interfaces ''
debug 2023-08-03T14:28:18.158+0000 7f236496e540 -1 Failed to pick public address.
```

See attached for full log.
[logs--rook-ceph-osd-0-7ccf99675d-lq2fx.txt](https://github.com/rook/rook/files/12262267/logs--rook-ceph-osd-0-7ccf99675d-lq2fx.txt)

**Expected behavior:**
Tests should pass consistently.

**How to reproduce it (minimal and precise):**

Look at the Canary integration tests: https://github.com/rook/rook/actions/workflows/canary-integration-test.yml?query=branch%3Amaster
