### ISSUE TITLE
CephFS reconcile failure, possibly after upgrade

### ISSUE THREAD

**Issue by cehoffman** [rook/rook#12673]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

See error messages in operator with failures around adding pools to cephfs from an unchanged cephfs definition prior to operator and ceph upgrade. I only saw these because I was trying to add an object store and the system accepted an objectstore with an empty zone name. Trying to change the zone name entered a failure mode which also resulted in failure to delete. While investigating why, I saw these logs. I'm fairly sure they are unrelated to the object store changes and nothing but an object store CRD has been added or changed.

**Expected behavior:**

No error messages on failing to reconcile existing pools to preexisting cephfs instances.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```yaml
cephFileSystems:
  - name: ceph
    storageClass:
      enabled: true
      name: ceph-fs-nvme
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      parameters:
        pool: ceph-ec-nvme
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: '{{ .Release.Namespace }}'
        csi.storage.k8s.io/fstype: ext4
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
        csi.storage.k8s.io/node-stage-secret-namespace: '{{ .Release.Namespace }}'
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: '{{ .Release.Namespace }}'
    spec:
      metadataServer:
        activeCount: 1
        activeStandby: true
        priorityClassName: system-cluster-critical
        placement:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: rook_cluster
                    operator: In
                    values:
                    - rook-ceph
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - ceph-mds # match the name of this filesystem instance plus -mds
                topologyKey: kubernetes.io/hostname
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 4Gi
      metadataPool:
        failureDomain: host
        deviceClass: nvme
        replicated:
          size: 3
      dataPools:
        - name: default
          failureDomain: host
          deviceClass: nvme
          replicated:
            size: 3
        - name: ec-nvme
          failureDomain: host
          deviceClass: nvme
          erasureCoded:
            dataChunks: 2
            codingChunks: 1
        - name: ec-hdd
          failureDomain: host
          deviceClass: hdd
          erasureCoded:
            dataChunks: 2
            codingChunks: 1
```

**Logs to submit**:

```
2023-08-07 07:58:10.563896 E | ceph-file-controller: failed to reconcile failed to create filesystem "ceph": failed to create filesystem "ceph": failed to add pool "ceph-default" to file system "ceph". (exit status 22): exit status 22  
2023-08-07 07:58:10.652270 E | ceph-file-controller: failed to reconcile CephFilesystem "rook-ceph/ceph". failed to create filesystem "ceph": failed to create filesystem "ceph": failed to add pool "ceph-default" to file system "ceph".  (exit status 22): exit status 22
```

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): talos 1.4.6
* Kernel (e.g. `uname -a`): Linux nxl03 6.1.35-talos #1 SMP PREEMPT_DYNAMIC Thu Jul 20 14:13:36 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: bare metal
* Rook version (use `rook version` inside of a Rook Pod): 
  * the example command doesn't work in the toolset container, real shame seems like it should

```
rook: v1.12.1
go: go1.20.6
```

* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 18.1.3 (f594a0802c34733bb06e5993bc4bdb085c9a5f3f) reef (rc)
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:49Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Talos
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_WARN 1 pgs not deep-scrubbed in time
