### ISSUE TITLE
Failed to reconcile CephCluster

### ISSUE THREAD

**Issue by alifiroozi80** [rook/rook#12709]
Hello everyone.

When I try to Install the Rook with its official Helm Charts, It's not working correctly!

Here are the `operator values`:

```yaml
image:
  repository: 10.0.1.132:8082/rook/ceph
  tag: v1.12.1
  pullPolicy: IfNotPresent

crds:
  # **WARNING** Only set during first deployment. If later disabled the cluster may be DESTROYED.
  # If the CRDs are deleted in this case, see
  # [the disaster recovery guide](https://rook.io/docs/rook/latest/Troubleshooting/disaster-recovery/#restoring-crds-after-deletion)
  # to restore them.
  enabled: true

csi:
  serviceMonitor:
    # -- Enable ServiceMonitor for Ceph CSI drivers
    enabled: false
    # -- Service monitor scrape interval
    interval: 5s

  cephcsi:
    image: 10.0.1.132:8082/rook/cephcsi/cephcsi:v3.9.0

  registrar:
    image: 10.0.1.132:8082/rook/sig-storage/csi-node-driver-registrar:v2.8.0

  provisioner:
    image: 10.0.1.132:8082/rook/sig-storage/csi-provisioner:v3.5.0

  snapshotter:
    image: 10.0.1.132:8082/rook/sig-storage/csi-snapshotter:v6.2.2

  attacher:
    image: 10.0.1.132:8082/rook/sig-storage/csi-attacher:v4.3.0

  resizer:
    image: 10.0.1.132:8082/rook/sig-storage/csi-resizer:v1.8.0

  csiAddons:
    enabled: false
    image: "10.0.1.132:8082/rook/csiaddons/k8s-sidecar:v0.7.0"

imagePullSecrets:
  - name: nx-cluster

monitoring:
  # -- Enable monitoring. Requires Prometheus to be pre-installed.
  # Enabling will also create RBAC rules to allow Operator to create ServiceMonitors
  enabled: false
```

Here are the `Cluster values`:

```yaml
# Installs a debugging toolbox deployment
toolbox:
  enabled: true
  image: 10.0.1.132:8082/rook/ceph:v17.2.6

monitoring:
  enabled: false
  # -- Whether to create the Prometheus rules for Ceph alerts
  createPrometheusRules: false
  rulesNamespaceOverride: monitoring

imagePullSecrets:
  - name: nx-cluster

cephClusterSpec:
  cephVersion:
    # v16 is Pacific, v17 is Quincy.
    image: 10.0.1.132:8082/rook/ceph:v17.2.6
    # Future versions such as `reef` (v18) would require this to be set to `true`.
    # Do not set to true in production.
    allowUnsupported: false

  # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: False
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    # port: 8443
    # Serve the dashboard using SSL (if using ingress to expose the dashboard and `ssl: true` you need to set
    # the corresponding "backend protocol" annotation(s) for your ingress controller of choice)
    ssl: true

ingress:
  # -- Enable an ingress for the ceph-dashboard
  dashboard:
    {}
    # annotations:
    #   external-dns.alpha.kubernetes.io/hostname: dashboard.example.com
    #   nginx.ingress.kubernetes.io/rewrite-target: /ceph-dashboard/$2
    # If the dashboard has ssl: true the following will make sure the NGINX Ingress controller can expose the dashboard correctly
    #   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #   nginx.ingress.kubernetes.io/server-snippet: |
    #     proxy_ssl_verify off;
    # host:
    #   name: dashboard.example.com
    #   path: "/ceph-dashboard(/|$)(.*)"
    # tls:
    # - hosts:
    #     - dashboard.example.com
    #   secretName: testsecret-tls
    ## Note: Only one of ingress class annotation or the `ingressClassName:` can be used at a time
    ## to set the ingress class
    # ingressClassName: nginx
```

And Here are the Commands:

```shell
helm install -n rook-ceph rook-ceph rook-release/rook-ceph -f rook-operator.yaml
helm install -n rook-ceph rook-ceph-cluster rook-release/rook-ceph-cluster -f rook-cluster.yaml
```

---

Here is the result:

```shell
$ kubectl -n rook-ceph get pod
NAME                                            READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-7tpgl                          2/2     Running   0          9m27s
csi-cephfsplugin-fg64s                          2/2     Running   0          9m27s
csi-cephfsplugin-ghgmh                          2/2     Running   0          9m27s
csi-cephfsplugin-provisioner-6d9dddb5f5-8bklp   5/5     Running   0          9m27s
csi-cephfsplugin-provisioner-6d9dddb5f5-bg2lq   5/5     Running   0          9m27s
csi-cephfsplugin-spzf2                          2/2     Running   0          9m27s
csi-cephfsplugin-vhp8g                          2/2     Running   0          9m27s
csi-rbdplugin-fw2ft                             2/2     Running   0          9m27s
csi-rbdplugin-provisioner-6fc47bb97c-5v469      5/5     Running   0          9m27s
csi-rbdplugin-provisioner-6fc47bb97c-sx6cr      5/5     Running   0          9m27s
csi-rbdplugin-s9pjv                             2/2     Running   0          9m27s
csi-rbdplugin-v89jd                             2/2     Running   0          9m27s
csi-rbdplugin-wbx4h                             2/2     Running   0          9m27s
csi-rbdplugin-xjzl2                             2/2     Running   0          9m27s
rook-ceph-mon-a-d4b87f994-rhq4p                 2/2     Running   0          9m19s
rook-ceph-mon-b-6b7688c578-q8qlb                2/2     Running   0          3m39s
rook-ceph-operator-67486f8f85-jpd6s             1/1     Running   0          9m58s
rook-ceph-tools-5cc94c674f-bp7kh                1/1     Running   0          9m30s
```

But the cluster is stuck at `Progressing `:

```shell
$ kubectl --namespace rook-ceph get cephcluster
NAME        DATADIRHOSTPATH   MONCOUNT   AGE     PHASE         MESSAGE                 HEALTH   EXTERNAL   FSID
rook-ceph   /var/lib/rook     3          9m54s   Progressing   Configuring Ceph Mons                       
```

Here is the `describe`:

```shell
$ kubectl -n rook-ceph describe cephcluster rook-ceph 
Name:         rook-ceph
Namespace:    rook-ceph
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: rook-ceph-cluster
              meta.helm.sh/release-namespace: rook-ceph
API Version:  ceph.rook.io/v1
Kind:         CephCluster
Metadata:
  Creation Timestamp:  2023-08-13T09:01:46Z
  Finalizers:
    cephcluster.ceph.rook.io
  Generation:        2
  Resource Version:  3152667
  UID:               4f6206b4-a05d-4f66-8fba-ebe7662fdefe
Spec:
  Ceph Version:
    Image:  10.0.1.132:8082/rook/ceph:v17.2.6
  Cleanup Policy:
    Sanitize Disks:
      Data Source:  zero
      Iteration:    1
      Method:       quick
  Crash Collector:
  Dashboard:
    Ssl:               true
  Data Dir Host Path:  /var/lib/rook
  Disruption Management:
    Manage Pod Budgets:       true
    Osd Maintenance Timeout:  30
  External:
  Health Check:
    Daemon Health:
      Mon:
        Interval:  45s
      Osd:
        Interval:  1m0s
      Status:
        Interval:  1m0s
    Liveness Probe:
      Mgr:
      Mon:
      Osd:
  Log Collector:
    Enabled:       true
    Max Log Size:  500M
    Periodicity:   daily
  Mgr:
    Count:  2
    Modules:
      Enabled:  true
      Name:     pg_autoscaler
  Mon:
    Count:  3
  Monitoring:
  Network:
    Connections:
      Compression:
      Encryption:
    Multi Cluster Service:
  Priority Class Names:
    Mgr:  system-cluster-critical
    Mon:  system-node-critical
    Osd:  system-node-critical
  Resources:
    Cleanup:
      Limits:
        Cpu:     500m
        Memory:  1Gi
      Requests:
        Cpu:     500m
        Memory:  100Mi
    Crashcollector:
      Limits:
        Cpu:     500m
        Memory:  60Mi
      Requests:
        Cpu:     100m
        Memory:  60Mi
    Exporter:
      Limits:
        Cpu:     250m
        Memory:  128Mi
      Requests:
        Cpu:     50m
        Memory:  50Mi
    Logcollector:
      Limits:
        Cpu:     500m
        Memory:  1Gi
      Requests:
        Cpu:     100m
        Memory:  100Mi
    Mgr:
      Limits:
        Cpu:     1
        Memory:  1Gi
      Requests:
        Cpu:     500m
        Memory:  512Mi
    Mgr - Sidecar:
      Limits:
        Cpu:     500m
        Memory:  100Mi
      Requests:
        Cpu:     100m
        Memory:  40Mi
    Mon:
      Limits:
        Cpu:     2
        Memory:  2Gi
      Requests:
        Cpu:     1
        Memory:  1Gi
    Osd:
      Limits:
        Cpu:     2
        Memory:  4Gi
      Requests:
        Cpu:     1
        Memory:  4Gi
    Prepareosd:
      Requests:
        Cpu:     500m
        Memory:  50Mi
  Security:
    Key Rotation:
      Enabled:  false
    Kms:
  Storage:
    Store:
    Use All Devices:                        true
    Use All Nodes:                          true
  Wait Timeout For Healthy OSD In Minutes:  10
Status:
  Conditions:
    Last Heartbeat Time:   2023-08-13T09:07:32Z
    Last Transition Time:  2023-08-13T09:07:32Z
    Message:               Configuring Ceph Mons
    Reason:                ClusterProgressing
    Status:                True
    Type:                  Progressing
  Message:                 Configuring Ceph Mons
  Phase:                   Progressing
  State:                   Creating
  Version:
    Image:    10.0.1.132:8082/rook/ceph:v17.2.6
    Version:  17.2.6-0
Events:
  Type     Reason           Age    From                          Message
  ----     ------           ----   ----                          -------
  Warning  ReconcileFailed  7m37s  rook-ceph-cluster-controller  failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create a cluster: failed to start ceph monitors: failed to start mon pods: failed to check mon quorum a: failed to wait for mon quorum: exceeded max retry count waiting for monitors to reach quorum
```

---

Here are the `rook-ceph-operator` logs:

```shell
$ kubectl -n rook-ceph logs -l app=rook-ceph-operator
2023-08-13 09:15:46.802933 I | op-mon: mons running: [a b]
2023-08-13 09:16:02.911228 I | op-k8sutil: ROOK_WATCH_FOR_NODE_FAILURE="true" (default)
2023-08-13 09:16:04.145804 I | op-k8sutil: ROOK_WATCH_FOR_NODE_FAILURE="true" (default)
2023-08-13 09:16:07.015146 I | op-mon: mons running: [a b]
2023-08-13 09:16:18.564465 I | op-k8sutil: ROOK_WATCH_FOR_NODE_FAILURE="true" (default)
2023-08-13 09:16:27.274691 I | op-mon: mons running: [a b]
2023-08-13 09:16:45.763313 I | op-k8sutil: ROOK_WATCH_FOR_NODE_FAILURE="true" (default)
2023-08-13 09:16:47.581660 I | op-mon: mons running: [a b]
2023-08-13 09:17:07.894680 I | op-mon: mons running: [a b]
2023-08-13 09:17:20.125181 I | op-k8sutil: ROOK_WATCH_FOR_NODE_FAILURE="true" (default)
```

---

Also, in the `ToolBox Container`, every command (`ceph status`, for instance) times out!

---

Kubernetes Version: `v1.27.4`
Helm Version: `v3.12.2`
Rook Version: `v1.12.1`
