### ISSUE TITLE
Error when Mounting RBD Volume: Connection Timed Out (Exit Status 110)

### ISSUE THREAD

**Issue by eliassteiner** [rook/rook#12759]
* Bug Report
I encountered an issue while trying to mount an RBD (Ceph RADOS Block Device) volume in my Kubernetes cluster. The error message I'm receiving is as follows:

`MountVolume.MountDevice failed for volume "pvc-cafca99f-0184-40eb-aa44-7eabe0e9d4d2" : rpc error: code = Internal desc = rbd: map failed with error an error (exit status 110) occurred while running rbd args: [--id admin -m 192.168.1.1:6789,192.168.1.2:6789 --keyfile=<stripped> map okd-encrypted/csi-vol-f6428a38-0b82-4450-87c9-1a35da3ef4e1 --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed rbd: map failed: (110) Connection timed out`

Creating the Storage Class and the PVC working fine. The PVC and PV  is in the Status Bounded.

**Deviation from expected behavior:**

**Expected behavior:**
Container Connect to the PV and is Up and Running

**How to reproduce it (minimal and precise):**
* https://medium.com/techlogs/configuring-rook-with-external-ceph-6b4b49626112

StorageClass:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rook-ceph-block-ext-rook-ceph
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph-external
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  imageFormat: “2”
  clusterID: rook-ceph-external
  imageFeatures: layering
  pool: okd-encrypted
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph-external
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

PVC:
```
kind: PersistentVolumeClaim
apiVersion: v1
  name: ceph-ext-test
  namespace: elias-test
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: pvc-cafca99f-0184-40eb-aa44-7eabe0e9d4d2
  storageClassName: rook-ceph-block-ext-rook-ceph
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: **3Gi**
```

Contianer:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  namespace: test
spec:
  volumes:
    - name: mystorage
      persistentVolumeClaim:
        claimName: ceph-ext-test
  containers:
    - name: task-pv-container
      #image: nginx:latest
      image: quay.io/bitnami/nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: mystorage
```
