### ISSUE TITLE
Object Storage Gateway / CephObjectStore does not work correctly if using a custom sslCertificateRef

### ISSUE THREAD

**Issue by taxilian** [rook/rook#12763]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
It should be possible to provide a custom TLS certificate secret and have the RGW work correctly; however, even though it can get things in a technically functioning state (where you can connect externally) if you started with a working system it will remain in the "Progressing" state with an error about an invalid host certificate, such as:

```
2023-08-21 18:26:53.479864 E | ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/data-store-test". failed to get dependents of CephObjectStore "rook-ceph/data-store-test": failed to list buckets in CephObjectStore "rook-ceph/data-store-test": Get "https://rook-ceph-rgw-data-store-test.rook-ceph.svc:443/admin/bucket?": x509: certificate is valid for *.ut2.company.dev, ut2.company.dev, not rook-ceph-rgw-data-store-test.rook-ceph.svc
```

It's easy to understand why it's happening -- it expects a valid https certificate but there is no way to give it the hostname that it should use to talk to the bucket.

**Expected behavior:**

It should work -- it should either ignore invalid certificates (probably for the best, since then it's not the job of the operator to care whether or not the provided certificate is valid) or else there should be a way to provide a custom hostname which should then be used for any operations needed to "reconcile [the] CephObjectStore".

**How to reproduce it (minimal and precise):**

1. Create a CephObjectStore with a custom (valid) `spec.gateway.sslCertificateRef` which is valid only for an external hostname, not the DNS entry for the objectstore inside the cluster.
2. Watch as it never goes into a "good" state -- if you tail the operator logs you'll see errors like the one I posted above.

** Rook version(s) **

I've reproduced this on Rook 1.11.7 and 1.12.2 -- I've seen it on older versions as well but not in the last few days

**Comment by thotz** [comment]
If you are using the OBC, please refer to the required hostname in StorageClass, "endpoint" in "Parameters" map

**Comment by taxilian** [comment]
Can you define the term "OBC" for me?

Looking at https://rook.io/docs/rook/latest/CRDs/Object-Storage/ceph-object-store-crd/ the only place I see a hostname defined is for an external RgwEndpoint; but I'm not using an external endpoint, I'm just using a regular ordinary CephObjectStore.  Here is my definition:

```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: data-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
    deviceClass: nvme
  dataPool:
    failureDomain: host
    replicated:
      size: 3
    deviceClass: hdd
  preservePoolsOnDelete: false
  gateway:
    annotations:
      wave.pusher.com/update-on-config-change: "true"
    hostNetwork: false
    sslCertificateRef: star-mycompany-com-tls
    port: 80
    securePort: 443
    instances: 2
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "250m"
        memory: 512Mi
```

**Comment by taxilian** [comment]
Ahh; OBC == ObjectBucketClaim. I'm figuring it out =] So https://rook.io/docs/rook/v1.12/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim/

I don't see anything to indicate that there is a way to override the hostname; I'll dig into the source and see what I can find.

Currently I'm just using:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: data-store-bucket
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: data-store
  objectStoreNamespace: rook-ceph
  region: us-east-1
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: pbm-backup
  namespace: my-prod
spec:
  generateBucketName: pbm-backup
  storageClassName: data-store-bucket
```

If there is a way to override the hostname on the storageClass that would be really good to add to the documentation somewhere -- or make it easier to find, if it's there and I'm missing it. I won't complain if there is already a way to fix this though =]

**Comment by taxilian** [comment]
I looked through the Rook source code and it appears that if it's not an external RGW (which it isn't) then it gets the endpoint address by building a cluster DNS name, which seems to indicate that there isn't a way to override that.

It seems like the "simplest" fix would be to add an optional field and then update `rook/pkg/operator/ceph/object/rgw.go` so that `getDomainName` will use that field value if provided -- but I don't know if that's the only place it's used. if it is then I can take a stab at doing it.

**Comment by BlaineEXE** [comment]
@taxilian what Rook version is this? We need that info

**Comment by taxilian** [comment]
I thought I'd updated the cluster to 1.12.x but it looks like it's still on 1.11.7; I'll update to the latest to make sure but I don't really expect it to matter based on anything I've seen

**Comment by taxilian** [comment]
Confirmed; I updated to 1.12.2 and I'm seeing the same log message. 

```E0825 03:27:24.414843       1 controller.go:204] error syncing 'go-prod/pbm-backup': error provisioning bucket: Provision: can't create ceph user: failed to get ceph user "obc-go-prod-pbm-backup-1dd1818b-c711-427b-b0d3-1ab1d8dba8f5": Get "https://rook-ceph-rgw-data-store.rook-ceph.svc:443/admin/user?format=json&uid=obc-go-prod-pbm-backup-1dd1818b-c711-427b-b0d3-1ab1d8dba8f5": tls: failed to verify certificate: x509: certificate is valid for *.company.dev, not rook-ceph-rgw-data-store.rook-ceph.svc, requeuing```

**Comment by thotz** [comment]
Have u added endpoint in the storage class for OBC

**Comment by thotz** [comment]
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: data-store-bucket
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: data-store
  objectStoreNamespace: rook-ceph
  region: us-east-1
  endpoint: <hostname including port>
```
