### ISSUE TITLE
Allow defining multiple cephECStorageClass and set any of them as default storageclass of the cluster

### ISSUE THREAD

**Issue by folliehiyuki** [rook/rook#12772]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
/ For Helm specific Installation/

Right now, I can define an arbitrary number of `CephBlockPool` CRDs in `cephECBlockPools` configuration object (both replicated and erasure coded pool types), but can only define a single `cephECStorageClass`. Also the template doesn't allow me to set the defined StorageClass as the default StorageClass of the cluster.

**Expected behavior:**

Allow to specify `cephECStorageClass` as a list of StorageClass objects and add `isDefault` configuration field for them (to match existing `cephBlockPools` field).

**Proposal:**

Since the `cephECBlockPools` field allows any number of pool definitions without restriction, nothing will stop me from creating only replicated pools there, for example. This is a bit confusing. Maybe something similar to cephObjectStores schema would be nicer here?

An example of what it might look like:
```yaml
cephECBlockPools:
  # The name of the EC data pool
  # The replicated pool's name can be fixed as {{ name }}-metadata (in this case "ec-pool-metadata")
  - name: ec-pool
    spec:
      metadataPool:
        replicated:
          size: 2
        ... # other spec settings for the metadata replicated pool here
      dataPool:
        erasureCoded:
          dataChunks: 2
          codingChunks: 1
        ... # other spec settings for EC pool here

    # parameters for the EC data pool, with fixed values for `dataPool` and `pool`
    parameters:
      ...
    # StorageClass corresponding to the EC data pool
    storageClass:
      enabled: true
      isDefault: false
      ...
```

This way we don't need separated configurations `cephECBlockPools` and `cephECStorageClass`, and we  have stricter (more limited) options so people won't mess up. What do you think?
