### ISSUE TITLE
when mountOptions are not explicitly set, cephfs vols are mounted ro

### ISSUE THREAD

**Issue by cruwe** [rook/rook#12783]
First and foremost, thank you very much for developing rook.

When using the rook operator and the ceph-cluster helm chart,

https://github.com/rook/rook/blob/031f3c60e46ebf35cb8d82c13e30776d3b2d59b7/deploy/charts/rook-ceph-cluster/values.yaml#L452

unless `mountOptions: [rw, ...]` is explicitly set,  volumes from cephfs are mounted `rw` on the host, but passed `ro` to the pod.

If this behaviour is to be expected as the default, it requires documentation, as it runs contrary to the general expectation that filesystems are mounted `rw` unless explicitly stated otherwise. Then, I am offering to drop a line or two into the comments of the chart's `values.yaml`.

If it is not and the case I am observing is an edge case, I do not know why and therefore can only contribute to establishing the parameters making the behaviour flip from normal to abnormal.

In any case, thanks again for your awesome work on rook.

**Comment by subhamkrai** [comment]
I think at least adding a comment in vaules.yaml makes sense to me.
@Madhu-1 @Rakshith-R ^^

**Comment by Rakshith-R** [comment]
@cruwe 
Did you check your pod and pvc yamls ?

**Comment by cruwe** [comment]
I did, I c&p'ed from `deploy/examples/csi/cephfs`, changing the image and sorting the dictionary alphabetically. I took care to double check that `readOnly: false`.

**Comment by Rakshith-R** [comment]
> I did, I c&p'ed from `deploy/examples/csi/cephfs`, changing the image and sorting the dictionary alphabetically. I took care to double check that `readOnly: false`.

Its working for everyone else as expected.

> mountOptions: [] 
unless mountOptions: [rw, ...] is explicitly set, volumes from cephfs are mounted rw on the host, but passed ro to the pod.

Can you explain how you determined this ?

**Comment by cruwe** [comment]
> Its working for everyone else as expected.

I suspected so ... As I said, if this is an edge case, I am willing to provide what I can.

> > mountOptions: []
> > unless mountOptions: [rw, ...] is explicitly set, volumes from cephfs are mounted rw on the host, but passed ro to the pod.
> 
> Can you explain how you determined this ?

I did `mount -l` on the host and from inside the pod:

1: On the host, it was and is (i.e., both cases)
```
10.106.74.153:3300,10.104.135.74:3300,10.102.76.28:3300:/volumes/csi/csi-vol-689c7552-eb21-4fb7-aae4-561d0cfd9050/6ace67e7-684b-4273-9a3c-7bb12abf72d7 on /var/lib/kubelet/plugins/kubernetes.io/csi/rook.cephfs.csi.ceph.com/6283e58b661725ecca68e7b67de84eb77d71807d8ee554cea501c56519153ddd/globalmount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,ms_mode=prefer-secure,fsid=00000000-0000-0000-0000-000000000000,acl,mds_namespace=ceph-filesystem,_netdev)
10.106.74.153:3300,10.104.135.74:3300,10.102.76.28:3300:/volumes/csi/csi-vol-689c7552-eb21-4fb7-aae4-561d0cfd9050/6ace67e7-684b-4273-9a3c-7bb12abf72d7 on /var/lib/kubelet/pods/2e34f508-ffbf-4232-8898-880865a77eea/volumes/kubernetes.io~csi/pvc-be33ea82-ead0-408b-be83-56f0f76b87aa/mount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,ms_mode=prefer-secure,fsid=00000000-0000-0000-0000-000000000000,acl,mds_namespace=ceph-filesystem,_netdev)
```

2.  With mountOptions: [rw], on the pod, it is
```10.106.74.153:3300,10.104.135.74:3300,10.102.76.28:3300:/volumes/csi/csi-vol-689c7552-eb21-4fb7-aae4-561d0cfd9050/6ace67e7-684b-4273-9a3c-7bb12abf72d7 on /var/lib/www/html type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,ms_mode=prefer-secure,fsid=00000000-0000-0000-0000-000000000000,acl,mds_namespace=ceph-filesystem)
```

3. Leaving them `[]` as in the chart's values, it had `type ceph (ro,relatime ...`

**Comment by Rakshith-R** [comment]
@cruwe 
Can you provide storageclass, pvc and pod yamls in each case from the cluster using `-o yaml`?
CephCSI passes mountOptions and `ro`  is only passed it the volume is readonly.

**Comment by cruwe** [comment]
I tried to reproduce the issue in a provable untainted environment, which is k8s 1.26.2 on three machines Ubuntu 22.04 and VirtualBox. I could not. I am not at liberty to tear down and rebuild the environment where I observed the issue at first.

I used the operator with `values.yaml`

```yaml
cephFileSystems:
  - name: ceph-filesystem
    ...
    storageClass:
      allowVolumeExpansion: true
      enabled: true
      isDefault: false
#      mountOptions:
#        - debug
#        - rw
      name: ceph-filesystem
      parameters:
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/fstype: ext4
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
        csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
      pool: data0
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
```
with the comments indicating the section modified.

The current storage class is (I removed timestamps and IDs)
```yaml
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: ceph
    meta.helm.sh/release-namespace: rook
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ceph-filesystem
parameters:
  clusterID: rook
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook
  fsName: ceph-filesystem
  mountOptions:
    - rw
  pool: ceph-filesystem-data0
provisioner: rook.cephfs.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

The pvc is/was
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
  namespace: rook
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
```
and the pod is/was
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: csicephfs-demo-pod
  namespace: rook
spec:
  containers:
    - image: nginx-unprivileged:1.25.1
      name: web-server
      securityContext:
        runAsGroup: 33
        runAsUser: 33
      volumeMounts:
        - mountPath: /var/lib/www/html
          name: mypvc
  securityContext:
    fsGroup: 33
    runAsGroup: 33
    runAsUser: 33
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: cephfs-pvc
        readOnly: false
```

I have no idea how to trace cause and effect in finite time. Should you have further ideas, I am certainly willing to help.

Considering that "it works for everyone else" with "everyone else" including myself with a new, from scratch and provable untainted environment, I could very well understand if this issue should be closed, but would hope it could still be found and referenced if someone else should observe similar behaviour.
