### ISSUE TITLE
Multi-site RGW resources fail to reconciliate on Multus due to mangled return code from mgr-proxied exec call

### ISSUE THREAD

**Issue by zer0def** [rook/rook#12833]
**Is this a bug report or feature request?**: Bug Report

**Deviation from expected behavior:**
Whenever `pkg/operator/ceph/object/admin.go:RunAdminCommandNoMultisite()` is called on a Rook-Ceph cluster running on Multus, failure return codes from mgr-proxied exec calls fall through `pkg/util/exec/error.go:ExitStatus()` cases. This leads to issues during reconciliation of various RGW multi-site resources like `CephObjectRealm`, `CephObjectZoneGroup`, `CephObjectZone` and whenever `CephObjectStore` explicitly refers to a hierarchy of RGW entities.

**Expected behavior:**
`CephObject*` resources are created normally.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

```
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cilium
  namespace: default
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "cilium-cni",
    "ipam": {
      "type": "whereabouts",
      "range": "10.245.0.1/16"
    }
  }'
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: my-cluster
  namespace: rook-ceph
spec:
  skipUpgradeChecks: true
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.0
    allowUnsupported: true
  mon:
    count: 3
    allowMultiplePerNode: true
  mgr:
    count: 2
    allowMultiplePerNode: true
  network:
    provider: multus
    selectors:
      cluster: default/cilium
  storage:
    useAllNodes: true
    useAllDevices: true
    config:
      encryptedDevice: "true"
---
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: my-realm
  namespace: rook-ceph
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: my-realm-a
  namespace: rook-ceph
spec:
  realm: my-realm
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: my-realm-a-rook-ceph
  namespace: rook-ceph
spec:
  zoneGroup: my-realm-a
  preservePoolsOnDelete: true
  metadataPool:
    replicated:
      size: 3
  dataPool:
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-realm-a-rook-ceph-rgw
  namespace: rook-ceph
spec:
  zone:
    name: my-realm-a-rook-ceph
  gateway:
    port: 8080
    instances: 2
```

**Logs to submit**:

Operator log example:

```
2023-09-01 14:17:24.750021 E | ceph-object-realm-controller: failed to reconcile CephObjectRealm "rook-ceph/my-realm". failed to create ceph realm: radosgw-admin realm get failed with code 0: command terminated with exit code 2
2023-09-01 14:17:36.128658 E | ceph-object-zone-controller: failed to reconcile CephObjectZone "rook-ceph/my-realm-a-rook-ceph". radosgw-admin zonegroup get failed with code 0: command terminated with exit code 2
```

* Crashing pod(s) logs, if necessary - no crashing pods

**Environment**:
* OS (e.g. from /etc/os-release): `Arch Linux`
* Kernel (e.g. `uname -a`): `6.4.11-hardened1-1-hardened`
* Cloud provider or hardware configuration: baremetal
* Rook version (use `rook version` inside of a Rook Pod): `v1.12.3`
* Storage backend version (e.g. for ceph do `ceph -v`): 
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"archive", BuildDate:"2023-07-20T07:37:53Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4+k3s1", GitCommit:"36645e7311e9bdbbf2adb79ecd8bd68556bc86f6", GitTreeState:"clean", BuildDate:"2023-07-28T09:46:04Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `autok3s`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): `HEALTH_WARN 3 pool(s) have no replicas configured`
