### ISSUE TITLE
Specifying a cluster-wide directory name for OSDs on Cluster CRD does not work

### ISSUE THREAD

**Issue by dgonzalezruiz** [rook/rook#1293]
As specified in the title, this does not work. I used the following syntax in the CRD:

```
spec:
  versionTag: v0.6.1
  monCount: 3
  dataDirHostPath: /var/lib/rook
  storage:
    useAllNodes: true
    useAllDevices: false
    directories:
    - path: "/data"
    storeConfig:
      storeType: bluestore
      databaseSizeMB: 1024
      journalSizeMB: 1024
```
But the created OSDs ignore this property. I have seen this feature documented. I will take care of the implementation of a solution if no one else decides to do so in the following days.
