### ISSUE TITLE
Add support for csi drivers to recover corrupted fuse mounts

### ISSUE THREAD

**Issue by mkhpalm** [rook/rook#13009]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Add support for csi-cephfsplugin and csi-rbdplugin daemonsets to attempt to recover corrupted fuse mounts. This has been supported in ceph-csi since v3.6.0 but rook-ceph operator is not creating daemonsets that can take advantage of this feature.

https://github.com/ceph/ceph-csi/releases/tag/v3.6.0

Documentation on the feature: 

https://github.com/ceph/ceph-csi/blob/devel/docs/ceph-mount-corruption.md#ceph-fuse-recovery

> **ceph-fuse corruption detection**
>
> A mountpoint is deemed corrupted if stat()-ing it returns one of the following errors:
>
>    `ENOTCONN`
>    `ESTALE`
>    `EIO`
>    `EACCES`
>    `EHOSTDOWN`
>
> **ceph-fuse recovery**
>
> Once a mountpoint corruption is detected, its recovery is performed by remounting the volume associated with it.
>
> Recovery is attempted only if /csi/mountinfo directory is made available to CSI CephFS plugin (available by default in the Helm chart and Kubernetes manifests).

Example of the key pieces missing to the daemonsets that rook manages:

```yaml
kind: DaemonSet
metadata:
  name: csi-cephfsplugin
...
spec:
  template:
    spec:
      containers:
      - name: csi-cephfsplugin
        volumeMounts:
        - name: ceph-csi-mountinfo
           mountPath: /csi/mountinfo
...
      volumes:
      - name: ceph-csi-mountinfo
        hostPath:
          path: /var/lib/kubelet/plugins/storage.cephfs.csi.ceph.com/mountinfo
          type: DirectoryOrCreate
...
```

Reference: https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml

**What is use case behind this feature:**

Maybe the biggest use case is when the csi pod/container restarts it doesn't permanently break all of the fuse based mount with `EONOTCONN` / `Transport endpoint not connected` errors. The drivers could attempt to recover the mount point after the issue is detected.

**Environment**:

Rook v1.9+ is when the default csi drivers started supporting this enhancement
