### ISSUE TITLE
MGR_MODULE_ERROR: Module 'rook' has failed: No storage class exists matching name provided in ceph config at mgr/rook/storage_class

### ISSUE THREAD

**Issue by a180285** [rook/rook#13175]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Cluster status
MGR_MODULE_ERROR: Module 'rook' has failed: No storage class exists matching name provided in ceph config at mgr/rook/storage_class

**Expected behavior:**
We are not using PVC, but raw device. expect NO error.

**How to reproduce it (minimal and precise):**

base on this issue: https://github.com/rook/rook/issues/10703 
it says set ROOK_ENABLE_DISCOVERY_DAEMON to true should be ok.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

rook-ceph-operator-config
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
  namespace: rook-ceph
data:
  CSI_CEPHFS_ATTACH_REQUIRED: 'true'
  CSI_CEPHFS_FSGROUPPOLICY: File
  CSI_ENABLE_CEPHFS_SNAPSHOTTER: 'true'
  CSI_ENABLE_CSIADDONS: 'false'
  CSI_ENABLE_ENCRYPTION: 'false'
  CSI_ENABLE_LIVENESS: 'false'
  CSI_ENABLE_NFS_SNAPSHOTTER: 'true'
  CSI_ENABLE_RBD_SNAPSHOTTER: 'true'
  CSI_ENABLE_READ_AFFINITY: 'false'
  CSI_ENABLE_TOPOLOGY: 'false'
  CSI_FORCE_CEPHFS_KERNEL_CLIENT: 'true'
  CSI_GRPC_TIMEOUT_SECONDS: '150'
  CSI_NFS_ATTACH_REQUIRED: 'true'
  CSI_NFS_FSGROUPPOLICY: File
  CSI_PLUGIN_ENABLE_SELINUX_HOST_MOUNT: 'false'
  CSI_PLUGIN_PRIORITY_CLASSNAME: system-node-critical
  CSI_PROVISIONER_PRIORITY_CLASSNAME: system-cluster-critical
  CSI_PROVISIONER_REPLICAS: '2'
  CSI_RBD_ATTACH_REQUIRED: 'true'
  CSI_RBD_FSGROUPPOLICY: File
  ROOK_CEPH_ALLOW_LOOP_DEVICES: 'false'
  ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS: '15'
  ROOK_CSI_ALLOW_UNSUPPORTED_VERSION: 'false'
  ROOK_CSI_ENABLE_CEPHFS: 'true'
  ROOK_CSI_ENABLE_GRPC_METRICS: 'false'
  ROOK_CSI_ENABLE_NFS: 'false'
  ROOK_CSI_ENABLE_RBD: 'true'
  ROOK_DISABLE_ADMISSION_CONTROLLER: 'true'
  ROOK_DISABLE_DEVICE_HOTPLUG: 'false'
  ROOK_DISCOVER_DEVICES_INTERVAL: 60m
  ROOK_ENABLE_DISCOVERY_DAEMON: 'true'
  ROOK_LOG_LEVEL: INFO
  ROOK_OBC_WATCH_OPERATOR_NAMESPACE: 'true'
  ROOK_WATCH_FOR_NODE_FAILURE: 'true'
```

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

* Kernel (e.g. `uname -a`): `Linux ssdceph 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: nvme
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.12.7       go: go1.21.3`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 18.2.0 (5dd24139a1eada541a3bc16b6941c5dde975e26d) reef (stable)`
* Kubernetes version (use `kubectl version`):
```

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm inited
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
```

HEALTH_ERR insufficient standby MDS daemons available; Module 'rook' has failed: No storage class exists matching name provided in ceph config at mgr/rook/storage_class; mons aa,u,y are low on available space; 1 daemons have recently crashed; 46 mgr modules have recently crashed
```
