### ISSUE TITLE
API server crash asking for POD_NAME and POD_NAMESPACE envs

### ISSUE THREAD

**Issue by kraman** [rook/rook#1318]
**Bug Report**

What happened:

api server error:
```
2017-12-15 00:35:18.889832 I | rook: starting Rook v0.6.0-88.g88dfbc5 with arguments '/usr/local/bin/rook api --config-dir=/var/lib/rook --port=8124 --hostnetwork=false'
2017-12-15 00:35:18.890716 I | rook: flag values: --admin-secret=*****, --ceph-config-override=, --cluster-name=rook, --config-dir=/var/lib/rook, --fsid=, --help=false, --hostnetwork=false, --log-level=INFO, --mon-endpoints=rook-ceph-mon2=172.17.173.66:6790,rook-ceph-mon0=172.17.122.242:6790,rook-ceph-mon1=172.17.60.240:6790, --mon-secret=*****, --namespace=rook, --port=8124, --private-ipv4=127.0.0.1, --public-ipv4=127.0.0.1
failed to get container image. cannot detect the pod name. Please provide it using the downward API in the manifest file
```

What you expected to happen:

API server should start succesfully

How to reproduce it (minimal and precise):

installed with:
```
helm repo add rook-alpha https://charts.rook.io/alpha
helm install rook-alpha/rook --name rook --namespace rook --version 0.6.2
```

cluster def:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook
data:
  config: |
    [global]
    rbd default features = 1
---
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  versionTag: master
  dataDirHostPath: /var/lib/rook
  storage:
    useAllNodes: true
    useAllDevices: false
    storeConfig:
      storeType: bluestore
      databaseSizeMB: 1024
      journalSizeMB: 1024
```

pod status
```
rook-agent-gcz8t                 1/1       Running            0          6m
rook-agent-h4j9t                 1/1       Running            0          6m
rook-agent-x9st2                 1/1       Running            0          6m
rook-api-5f95f65577-qsdnm        0/1       CrashLoopBackOff   5          5m
rook-ceph-mgr0-cbb9df9d4-v69p5   1/1       Running            0          5m
rook-ceph-mgr1-cf647cfcd-t52rd   1/1       Running            0          5m
rook-ceph-mon0-79pkc             1/1       Running            0          5m
rook-ceph-mon1-6lpj4             1/1       Running            0          5m
rook-ceph-mon2-7snfz             1/1       Running            0          5m
rook-ceph-osd-62fft              1/1       Running            0          5m
rook-ceph-osd-bmxkd              1/1       Running            0          5m
rook-ceph-osd-fdr8p              1/1       Running            0          5m
rook-operator-696f8bd987-vtscw   1/1       Running            0          7m 
```

**Environment**:
* OS (e.g. from /etc/os-release): 
ubuntu 16.04
* Kernel (e.g. `uname -a`):
Linux node1 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
vagrant VMs
* Rook version (use `rook version` inside of a Rook Pod):
0.6.2
* Kubernetes version (use `kubectl version`):
1.8.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
custom
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
