### ISSUE TITLE
csi-cephfsplugin-holder-rook-ceph failing and back off restarting

### ISSUE THREAD

**Issue by gagareg** [rook/rook#13209]
We have about 26 k8s nodes, almost all csi-cephfsplugin-holder-rook are working but one is failing

**Is this a bug report or feature request?**
* Bug Report

**Expected behavior:**
It should be running

**How to reproduce it (minimal and precise):**
kubectl get pods | grep holder
kubectl logs csi-cephfsplugin-holder-rook-ceph-5dl84

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
*rook-ceph*
```yaml
USER-SUPPLIED VALUES:
cephCommandsTimeoutSeconds: "180"
csi:
  csiCephFSPluginResource: |
    - name : driver-registrar
      resource:
        requests:
          memory: 128Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 20m
    - name : csi-cephfsplugin
      resource:
        requests:
          memory: 128Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 20m
    - name : liveness-prometheus
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
  csiCephFSProvisionerResource: |
    - name : csi-provisioner
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-resizer
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-attacher
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-snapshotter
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-cephfsplugin
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : liveness-prometheus
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
  enableCSIHostNetwork: false
  enableCephfsDriver: true
  enableCephfsSnapshotter: false
  enableNFSSnapshotter: false
  enablePluginSelinuxHostMount: false
  enableRBDSnapshotter: false
  enableRbdDriver: false
  logLevel: 0
  pluginPriorityClassName: ""
  provisionerPriorityClassName: ""
  serviceMonitor:
    enabled: false
    interval: 5s
image:
  pullPolicy: IfNotPresent
  tag: v1.12.3
logLevel: DEBUG
monitoring:
  enabled: false
resources:
  limits:
    cpu: 100m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi
```
*ceph-rook-cluster*
```yaml
USER-SUPPLIED VALUES:
cephBlockPools: []
cephClusterSpec:
  crashCollector:
    daysToRetain: 30
    disable: true
  dashboard:
    enabled: false
    ssl: true
  logCollector:
    createPrometheusRules: false
    enabled: false
  mgr:
    allowMultiplePerNode: false
    count: 2
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    allowMultiplePerNode: false
    count: 3
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi
        storageClassName: standard-rwo
  placement:
    arbiter:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
  priorityClassNames:
    mgr: ""
    mon: ""
    osd: ""
  resources:
    cleanup:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 200Mi
    crashcollector:
      limits:
        cpu: 100m
        memory: 60Mi
      requests:
        cpu: 100m
        memory: 60Mi
    logcollector:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 100Mi
    mgr:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    mgr-sidecar:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 40Mi
    mon:
      limits:
        cpu: 400m
        memory: 2048Mi
      requests:
        cpu: 300m
        memory: 512Mi
    osd:
      limits:
        cpu: 400m
        memory: 2048Mi
      requests:
        cpu: 200m
        memory: 1024Mi
  storage:
    storageClassDeviceSets:
    - count: 4
      name: set1
      portable: true
      volumeClaimTemplates:
      - metadata:
          name: set1
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: standard-rwo
          volumeMode: Block
    useAllDevices: false
    useAllNodes: false
cephFileSystems:
- name: ceph-filesystem
  spec:
    dataPools:
    - failureDomain: host
      name: data0
      replicated:
        size: 3
    metadataPool:
      replicated:
        requireSafeReplicaSize: true
        size: 3
        targetSizeRatio: 80
    metadataServer:
      activeCount: 1
      activeStandby: true
      priorityClassName: ""
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 2Gi
    preserveFilesystemOnDelete: true
  storageClass:
    allowVolumeExpansion: true
    enabled: true
    isDefault: false
    mountOptions: []
    name: ceph-filesystem
    parameters:
      csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
      csi.storage.k8s.io/controller-expand-secret-namespace: '{{ .Release.Namespace
        }}'
      csi.storage.k8s.io/fstype: ext4
      csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
      csi.storage.k8s.io/node-stage-secret-namespace: '{{ .Release.Namespace }}'
      csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
      csi.storage.k8s.io/provisioner-secret-namespace: '{{ .Release.Namespace }}'
    pool: data0
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
cephObjectStores: []
clusterName: rook-ceph
ingress:
  dashboard: {}
monitoring:
  createPrometheusRules: false
  enabled: false
toolbox:
  enabled: true
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
```

**Logs to submit**:

* Operator's logs, if necessary
```bash
kubectl logs rook-ceph-operator-7d65589c67-42sd6 | grep err                                                                                                                                                                   
Trace[1298889818]: ---"Objects listed" error:<nil> 31598ms (05:25:34.134)
2023-11-15 05:25:49.439385 D | cephclient: No ceph configuration override to merge as "rook-config-override" configmap is empty
2023-11-15 05:26:16.432455 D | ceph-spec: do not reconcile on configmap that is not "rook-config-override"
2023-11-15 05:26:16.631259 D | cephclient: No ceph configuration override to merge as "rook-config-override" configmap is empty
2023-11-15 05:27:26.229266 D | ceph-spec: do not reconcile on configmap that is not "rook-config-override"
2023-11-15 05:27:26.531007 D | cephclient: No ceph configuration override to merge as "rook-config-override" configmap is empty
```

* Crashing pod(s) logs, if necessary
```bash
kubectl logs csi-cephfsplugin-holder-rook-ceph-5dl84                                                                                                                                                                          

ln: failed to create symbolic link '/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/rook-ceph.net.ns': No such file or directory
```

* Output of kubectl commands, if necessary
```
[root@rook-ceph-tools-6595b6bb4-tps5m /]# ceph status
  cluster:
    id:     e021429b-e9c8-4dd6-a0c7-8ec1e0238444
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 25h)
    mgr: b(active, since 89m), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 4 osds: 4 up (since 23h), 4 in (since 9w)
 
  data:
    volumes: 1/1 healthy
    pools:   3 pools, 161 pgs
    objects: 135.19k objects, 75 GiB
    usage:   228 GiB used, 172 GiB / 400 GiB avail
    pgs:     161 active+clean
 
  io:
    client:   28 KiB/s rd, 29 KiB/s wr, 2 op/s rd, 4 op/s wr
```

**Environment**:
* OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
* Kernel (e.g. `uname -a`):
```
Linux gke-ids-infra-gcp-n2d-default-spot-po-dcb7fa61-rtek 5.15.0-1044-gke #49-Ubuntu SMP Wed Sep 20 16:15:35 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

* Cloud provider or hardware configuration: gcp managed k8s
* Rook version (use `rook version` inside of a Rook Pod):
```
rook: v1.12.3
go: go1.21.0
```

* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)
* Kubernetes version (use `kubectl version`):
```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.6-gke.1506000
```
