### ISSUE TITLE
Monitor repeatedly causes false low-space alerts

### ISSUE THREAD

**Issue by husseinsamander** [rook/rook#13212]
Monitor repeatedly causes low-space alerts to fire right before it auto-cleans.

Is this a bug report or feature request?

    Bug Report

Expected behavior:
Monitor should either be cleaning earlier or have some grace period before the metric is emitted.

How to reproduce it (minimal and precise):
Can be simulated by having a monitor that is close to the %70 threshold that triggers the `MON_DISK_LOW` check/alert.
The monitor is not auto-cleaning on time, so the [alert](
https://github.com/rook/rook/blob/d01029a4b0aa32206a7db502b6c55310d7e8ade6/deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml#L65) fires whenever the slightest increase above `%70` happens, even when it goes right back down to below the threshold.

- Cluster CR (custom resource), typically called cluster.yaml, if necessary
    rook-ceph
    ```
      monitoring:
    enabled: true
  resources:
    limits:
      cpu: 2000m
      memory: 400Mi
    requests:
      cpu: 500m
      memory: 200Mi
    ```
rook-ceph-cluster
```

  resources:
    mgr:
      limits:
        cpu: "1000m"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "512Mi"
    mon:
      limits:
        cpu: "2000m"
        memory: "2Gi"
      requests:
        cpu: "1000m"
        memory: "1Gi"
    osd:
      limits:
        cpu: "2000m"
        memory: "4Gi"
      requests:
        cpu: "1000m"
        memory: "4Gi"
    prepareosd:
      # limits: It is not recommended to set limits on the OSD prepare job since it's a one-time burst for memory
      # that must be allowed to complete without an OOM kill
      requests:
        cpu: "500m"
        memory: "50Mi"
    mgr-sidecar:
      limits:
        cpu: "500m"
        memory: "100Mi"
      requests:
        cpu: "100m"
        memory: "40Mi"
    crashcollector:
      limits:
        cpu: "500m"
        memory: "60Mi"
      requests:
        cpu: "100m"
        memory: "60Mi"
    logcollector:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "100Mi"
    cleanup:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "100Mi"
```

- Output of kubectl commands, if necessary
```sh
[rook@rook-ceph-tools-6cbbb4495d-rzgv9 /]$ ceph status
```
```
  cluster:
    id:     2e2f8ec0-cd54-44c9-8a4d-350151938a6d
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum l,m,n (age 2h)
    mgr: a(active, since 12d), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 6 osds: 6 up (since 3w), 6 in (since 3w)
    rgw: 1 daemon active (1 hosts, 1 zones)
 
  data:
    volumes: 1/1 healthy
    pools:   12 pools, 449 pgs
    objects: 297.86k objects, 968 GiB
    usage:   2.9 TiB used, 1.9 TiB / 4.8 TiB avail
    pgs:     449 active+clean
 
  io:
    client:   147 KiB/s rd, 96 KiB/s wr, 180 op/s rd, 10 op/s wr
```
```sh
df -h mon-l/data/store.db
```
```
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg0-root  9.8G  6.0G  3.3G  65% /
```

**Environment**:

 - OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

- Kernel (e.g. uname -a):
```
Linux htzhel1-ax41c 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

- Cloud provider or hardware configuration:

- Rook version (use rook version inside of a Rook Pod):
```
rook: v1.10.4
go: go1.18.7
```

-Storage backend version (e.g. for ceph do ceph -v): 
```
ceph version 17.2.3 (dff484dfc9e19a9819f375586300b3b79d80034d) quincy (stable)
```
    
- Kubernetes version (use kubectl version):
```
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.4
```
