### ISSUE TITLE
Subvolume Group CR should add a separate name spec

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13220]
**Is this a bug report or feature request?**
* Bug Report

Currently, we create the default "csi" named svg for filesystem, 
But if we need to add more than one filesystem we cannot create the same "csi" named svg

**Deviation from expected behavior:**

Originally we create it using this cmd ``` ceph fs subvolume create <vol_name> <subvol_name>  ```
So we can have 2 variables filesystem and subvolume name,
Currently the CR doesn't allow us to make subvolume-name as constant as needed to "csi" because of k8s limitations 

**Expected behavior:**

Multiple filesystems should create "csi" named svgs
So the CR would add Svg official name, so for the default case it would always be "csi"
```
---
apiVersion: ceph.rook.io/v1
kind: CephFilesystemSubVolumeGroup
metadata:
  name: group-a
  namespace: rook-ceph # namespace:cluster
spec:
  # filesystemName is the metadata name of the CephFilesystem CR where the subvolume group will be created
  filesystemName: myfs
  svgName: csi
```
Addition `svgName: csi`, rook reconcile should handle it

**Comment by Madhu-1** [comment]
The same problem exists for RadosBlockPool as well, instead of use metadata name as the backend resource name we need to add a new file in the spec which can be the actual backend name

```yaml
...
spec:
  name: xyz
```

With above we can create 2 radosblockpool with same name but for different blockpool and same goes for SVG and filesystem
