### ISSUE TITLE
helm: missing namespace in operator deployment and operator configmap templates

### ISSUE THREAD

**Issue by foyerunix** [rook/rook#13268]
Hello,

The namespace is missing in operator deployment and operator configmap when generating manifests using "helm template".

How to reproduce it (minimal and precise):

`helm template --namespace test-namespace deploy/charts/rook-ceph | grep -E '^  name: (rook-ceph-operator-config|rook-ceph-operator)' -A 8 -B 3`

Deviation from expected behavior:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
data:
  ROOK_LOG_LEVEL: "INFO"
  ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS: "15"
  ROOK_OBC_WATCH_OPERATOR_NAMESPACE: "true"
  ROOK_CEPH_ALLOW_LOOP_DEVICES: "false"
  ROOK_DISABLE_ADMISSION_CONTROLLER: "true"
  ROOK_ENABLE_DISCOVERY_DAEMON: "false"
  ROOK_CSI_ENABLE_RBD: "true"
--
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/created-by: helm
    helm.sh/chart: "rook-ceph-0.0.1"
spec:
```

Expected behavior:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
  namespace: test-namespace
--
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-operator
  namespace: test-namespace

```
