### ISSUE TITLE
OSD daemon running count double of total on "Services" tab

### ISSUE THREAD

**Issue by Omar007** [rook/rook#13278]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Running with `quay.io/ceph/daemon-base@sha256:cb226bc79ccb47df9993ecd9da840db5b20eb27f8e4c383f029b5621ba316156`, the OSD daemons on the "Services" tab are shown have double the amount of running daemons of the total of actual daemons:

![screenshot_2023-11-27T18:14:34](https://github.com/rook/rook/assets/5380079/1acae843-de89-4768-bb4e-a0f0ab522ddb)

When expanding it, there's only 30 total (the expected amount):

![screenshot_2023-11-27T12:02:30](https://github.com/rook/rook/assets/5380079/31f3b599-cb4a-40d2-9f63-6d879bec7066)

**Expected behavior:**

The amount (and states) shown on the "Services" tab reflects the actual amount (and states) of the OSD daemons.

**How to reproduce it (minimal and precise):**

I've not done anything other than running/updating the cluster to `quay.io/ceph/daemon-base@sha256:cb226bc79ccb47df9993ecd9da840db5b20eb27f8e4c383f029b5621ba316156`

**File(s) to submit**:

```
cephClusterSpec:
  cephVersion:
    image: quay.io/ceph/daemon-base@sha256:cb226bc79ccb47df9993ecd9da840db5b20eb27f8e4c383f029b5621ba316156
  mgr:
    count: 1
  dashboard:
    ssl: false
  network:
    connections:
      requireMsgr2: true
  storage:
    useAllNodes: false
    useAllDevices: false
    storageClassDeviceSets:
      - name: nvme-ssd
        count: 2
        portable: false
        encrypted: true
        volumeClaimTemplates:
          - spec:
              storageClassName: nvme-ssd
              resources:
                requests:
                  storage: 93Gi
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
      - name: sata-ssd
        count: 4
        portable: false
        encrypted: true
        volumeClaimTemplates:
          - spec:
              storageClassName: sata-ssd
              resources:
                requests:
                  storage: 931Gi
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
      - name: scsi-hdd
        count: 24
        portable: false
        encrypted: true
        volumeClaimTemplates:
          - spec:
              storageClassName: scsi-hdd
              resources:
                requests:
                  storage: 3726Gi
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
```

**Logs to submit**:

N/A.

**Cluster Status to submit**:

```
# ceph health
HEALTH_OK
```

```
# ceph status
  cluster:
    id:     ac447077-0c75-4803-b14b-1f46a7e2e9ab
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum t,bz,ca (age 10h)
    mgr: a(active, since 12h)
    mds: 3/3 daemons up, 3 hot standby
    osd: 30 osds: 30 up (since 10h), 30 in (since 8M)
    rgw: 1 daemon active (1 hosts, 1 zones)

  data:
    volumes: 3/3 healthy
    pools:   20 pools, 441 pgs
    objects: 7.88M objects, 20 TiB
    usage:   27 TiB used, 64 TiB / 91 TiB avail
    pgs:     441 active+clean

  io:
    client:   447 KiB/s rd, 591 KiB/s wr, 10 op/s rd, 20 op/s wr

  progress:

```

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```
* Kernel (e.g. `uname -a`):
```
Linux control 6.6.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 20 Nov 2023 23:18:21 +0000 x86_64 GNU/Linux
```
* Rook version (use `rook version` inside of a Rook Pod):
```
rook: v1.12.8
go: go1.21.3
```
* Storage backend version (e.g. for ceph do `ceph -v`):
```
ceph version 18.2.0-1268-gfebc580e (febc580e0fcb7862aac2078379090554e3113e07) reef (stable)
```
* Kubernetes version (use `kubectl version`):
```
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Bare-metal kubeadm
