### ISSUE TITLE
support create osd with different metadata devices

### ISSUE THREAD

**Issue by zhucan** [rook/rook#13280]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
1. Partition the nvme device firstly
2. In yaml, specify partitions for each data disk
3. Use the partition of the nvme devices as metadata devices to create osd

**What is use case behind this feature:**
releated discussion:  https://github.com/rook/rook/discussions/13191  https://github.com/rook/rook/issues/13240
**Environment**:

**Comment by travisn** [comment]
@satoru-takeuchi Actually is it already possible to use multiple `metadataDevice`s for different devices on a node? Something like this is possible in the schema today, but I don't recall if it's supported in this scenario.
```yaml
  storage:
    nodes:
    - name: "node-a"
      devices: 
      - name: "sda"
        config:
          metadataDevice: "nvme01"
      - name: "sdb"
        config:
          metadataDevice: "nvme01"
      - name: "sdc"
        config:
          metadataDevice: "nvme02"
```

**Comment by satoru-takeuchi** [comment]
@travisn 

> Actually is it already possible to use multiple metadataDevices for different devices on a node? Something like this is possible in the schema today, 

Yes, it's possible. 

> but I don't recall if it's supported in this scenario.

However, it doesn't work in his case because `ceph-volume lvm batch` only supports disk and lvm.

https://github.com/ceph/ceph/blob/main/src/ceph-volume/ceph_volume/util/arg_validators.py#L99-L111

**Comment by Underknowledge** [comment]
@satoru-takeuchi 
> only supports disk and lvm. 

that means this should work? 
```yaml
- name: "/dev/disk/by-id/scsi-SLENOVO_MG08SCA16TE_Z0C0A005FWUA"
        # sda
        config:
          metadataDevice: /dev/vg_md0/lv_bluestore
 # ... 
- name: "/dev/disk/by-id/scsi-SLENOVO_MG08SCA16TE_Z0C0A005FWUG"
        # sdg
        config:
          metadataDevice: /dev/vg_md0/lv_bluestore
```
