### ISSUE TITLE
EC pool constantly backfilling misplaced objects since v1.12.8 upgrade

### ISSUE THREAD

**Issue by dhess** [rook/rook#13340]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

We set up a Rook cluster (initialized at `v1.12.7`, I believe) on bare metal about a month ago, and after some testing, successfully moved about 40TiB of data from ZFS to Ceph. The cluster consists of 4 worker nodes, each with 2 HDDs and 2 NVMe drives. The HDDs are provisioned as whole-drive PVCs (PVC cluster-style), as we wanted to use Rook's support for encrypted devices.

After a few weeks of flawless operation, we upgraded the rook-ceph Helm chart to `v1.12.8`, and just a few minutes later, Ceph reported that nearly half the objects in the cluster were misplaced, and started rebalancing:

```
debug 2023-11-16T22:19:52.352+0000 7f0c03ae0700  0 log_channel(cluster) log [DBG] : pgmap v69: 273 pgs: 1 active+clean+scrubbing+deep, 24 remapped+peering, 27 active+remapped+backfilling, 45 active+remapped+backfill_wait, 176 active+clean; 36 TiB data, 71 TiB used, 78 TiB / 149 TiB avail; 6.1 MiB/s rd, 276 MiB/s wr, 26.93k op/s; 37351011/74716231 objects misplaced (49.990%); 14 MiB/s, 40 keys/s, 14 objects/s recovering
```

Since then, it's been working its way down to 5% misplaced, and then the process starts over again. This has been going on since 16 November when I did the upgrade; i.e., the cluster has been continuously rebalancing since the upgrade to `v1.12.8` on November 16. 

The pool that's causing all the rebalancing, `cephfs-0-erasurecoded`, is EC:4+4 , across 4 nodes each with 2 HDDs. All of the other pools are stable. The vast majority of the 40TiB we migrated to Ceph is stored on the pool in question.

The operator is also spamming this log entry, though I'm not sure it's related:

```
2023-12-04 18:18:18.922585 I | clusterdisruption-controller: all "host" failure domains: [worker-a worker-b worker-c worker-d]. osd is down in failure domain: "". active node drains: false. pg health: "cluster is not fully clean. PGs: [{StateName:active+clean Count:263} {StateName:active+remapped+backfilling Count:10}]"
```

(Yes, the failure domain is given as "" . But no OSDs are actually down, according to ceph status.)

Cluster health is good except for the warning that deep scrubs aren't running, presumably because they can't during the constant rebalancing.

I'm fairly certain that no changes were made to the pool in question after initially creating it. For certain, no configuration changes were introduced with the upgrade to `v1.12.8` &mdash; it was just a Helm chart version bump.

**Expected behavior:**

Minor point upgrade should not have caused a massive rebalancing, and in any case, once the rebalancing is complete, it shouldn't rebalance again, over and over.

**How to reproduce it (minimal and precise):**

Unknown.

**File(s) to submit**:

Here's a link to our `values.yaml` for the Helm chart:

https://gist.github.com/dhess/c25058c40d149391cfef426a5aa44aa9

The problematic pool is defined on line 580:

https://gist.github.com/dhess/c25058c40d149391cfef426a5aa44aa9#file-valyes-yaml-L580

Also potentially relevant: we have divided our 4 nodes into 2 PDU failure domains with appropriate labels, `topology.rook.io/pdu=lhr1-pdu-a` and `topology.rook.io/pdu=lhr1-pdu-b`.

**Logs to submit**:

As requested on Slack, here is the output of `ceph osd crush dump`: https://gist.github.com/dhess/54a28b83d3c96fb85e7be2d4ccde5a78

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

```
# ceph health
HEALTH_WARN 110 pgs not deep-scrubbed in time; 112 pgs not scrubbed in time
```

```
# ceph status
  cluster:
    id:     30cf513d-aeb2-4d9f-9ab2-22801a31dab4
    health: HEALTH_WARN
            110 pgs not deep-scrubbed in time
            112 pgs not scrubbed in time
 
  services:
    mon: 3 daemons, quorum e,f,g (age 4h)
    mgr: b(active, since 5d), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 16 osds: 16 up (since 5d), 16 in (since 11d); 22 remapped pgs
 
  data:
    volumes: 1/1 healthy
    pools:   9 pools, 273 pgs
    objects: 9.37M objects, 36 TiB
    usage:   78 TiB used, 72 TiB / 149 TiB avail
    pgs:     10245934/74885825 objects misplaced (13.682%)
             251 active+clean
             12  active+remapped+backfill_wait
             10  active+remapped+backfilling
 
  io:
    client:   852 B/s rd, 1 op/s rd, 0 op/s wr
    recovery: 48 MiB/s, 11 objects/s
```

**Environment**:
* OS (e.g. from /etc/os-release): Talos v1.5.5
* Kernel (e.g. `uname -a`): `6.1.61-talos #1 SMP PREEMPT_DYNAMIC Wed Nov  8 10:39:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: bare metal
* Rook version (use `rook version` inside of a Rook Pod): `v1.12.9`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)`
* Kubernetes version (use `kubectl version`): ` v1.28.1`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Talos
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): See above
