### ISSUE TITLE
COSI - BucketClass/BucketAccessClass objectStoreUserSecretName

### ISSUE THREAD

**Issue by cfis** [rook/rook#13384]
When using COSI, the documentation states that the `objectStoreUserSecretName` will be autogenerated  like this:

```
rook-ceph-object-user-<store-name>-cosi
```
So in my case:

```
rook-ceph-object-user-ceph-objectstore-cosi
```

Except that is only sort of true. What really happens is the secret starts out like this:

```
rook-ceph-object-user-<store-name>-<user-name>
```
So in my case:

```
rook-ceph-object-user-ceph-objectstore-terrabox
```
And that is the  `objectStoreUserSecretName` I need to specify in BucketClass and BucketAccessClass.

After a few minutes though, the `rook-ceph-object-user-ceph-objectstore-terrabox` becomes `rook-ceph-object-user-ceph-objectstore-cosi`. Not sure if just the name is updated or if the secret is recreated.

**Expected behavior:**

That the generated secret name matches the documentation

**How to reproduce it (minimal and precise):**
Create a new BucketClass and BucketAccessClass

This is Kubernetes 1.28.4 via Microk8s on Ubuntu on a 10 node cluster.

**Comment by BlaineEXE** [comment]
I have some questions to help us debug.

Which Rook version are you using?

In the manifests you are using, is one of the secrets you mentioned present?

There was an update at some point to change behavior, and you may be using the Rook version that requires manually creating the secret.

**Comment by cfis** [comment]
Latest rook. Helm chart version v1.12.9.

So yes and no on the secrets. At first I had:

```
kind: BucketClass
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: ceph-bucket-class
driverName: ceph.objectstorage.k8s.io
deletionPolicy: Delete
parameters:
  objectStoreUserSecretName: rook-ceph-object-user-ceph-objectstore-terrabox
  objectStoreUserSecretNamespace: rook-ceph
```
So I thought that might have caused the secret to be created. Then I tried it with:

```
 objectStoreUserSecretName: rook-ceph-object-user-ceph-objectstore-cosi
```

I set that based on the documentation. But then I noticed `rook-ceph-object-user-ceph-objectstore-terrabox` was being created, but eventually disappears and `rook-ceph-object-user-ceph-objectstore-cosi` appears.

Hope that helps - happy to answer anymore questions and thanks for the help.

**Comment by thotz** [comment]
Can you please check cephobjectstoreuser CRD whether it exists or check from toolbox whether both users exists? RookOp creates the user `rook-ceph-object-user-ceph-objectstore-cosi` for the cosi usecase . But end-user has full control to use which user the cephcosi driver to pick. This is defined in BucketClass

**Comment by cfis** [comment]
Yes, the user terrabox exists in the CephObjectStoreUser CRD.

And for the bucket class:

```
kind: BucketClass
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: ceph-bucket-class
driverName: ceph.objectstorage.k8s.io
deletionPolicy: Delete
parameters:
  objectStoreUserSecretName: rook-ceph-object-user-ceph-objectstore-terrabox
  objectStoreUserSecretNamespace: rook-ceph
```
Note created buckets (via BucketClaim) are successfully created and are owned by the Terrabox user. So the process is working. What is confusing is what should `objectStoreUserSecretName` be and why are two different secrets created (or one that changes names, not sure)
