### ISSUE TITLE
COSI - Buckets Names

### ISSUE THREAD

**Issue by cfis** [rook/rook#13396]
When creating buckets with a bucket claim like this:

```
apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClaim
metadata:
  name: my-bucket
spec:
  bucketClassName: ceph-bucket-class
  protocols:
    - s3
```

The bucket created is ceph is not `my-bucket` but instead a random auto generated name. In our use case we need to be able to create buckets with specified names. Is that possible somehow?
