### ISSUE TITLE
Opertator is trying to create gRPC metrics port, but the value is not defined

### ISSUE THREAD

**Issue by A1994SC** [rook/rook#13419]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

It seems that in this commit [here](https://github.com/rook/rook/commit/5658e026cba0950b576b0d01a1f0f3e92fbd8ac2) the svc the operator creates, [pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-svc.yaml](https://github.com/rook/rook/blob/v1.13.0/pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-svc.yaml), the `gRPC` part was not removed causing the operator to not be able to set the port.

**Expected behavior:**

Metric service is created and configured by operator

**How to reproduce it (minimal and precise):**

`values.yaml` file below

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
csi:
  csiCephFSPluginResource: ""
  csiCephFSProvisionerResource: ""
  csiRBDPluginResource: ""
  csiRBDProvisionerResource: ""
  enableGrpcMetrics: false
  enableLiveness: true
  pluginTolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
  serviceMonitor:
    enabled: true
    namespace: rook-ceph
image:
  repository: docker.io/rook/ceph
monitoring:
  enabled: true
resources:
  limits: null
  requests: null

```

**File(s) to submit**:

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.6
  cleanupPolicy:
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  crashCollector: {}
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  external: {}
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 1m0s
      status:
        interval: 1m0s
    livenessProbe:
      mgr: {}
      mon: {}
      osd: {}
  logCollector:
    enabled: true
    maxLogSize: 500M
    periodicity: daily
  mgr:
    count: 2
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    count: 3
  monitoring:
    enabled: true
  network:
    connections:
      compression: {}
      encryption: {}
    multiClusterService: {}
  priorityClassNames:
    mgr: system-cluster-critical
    mon: system-node-critical
    osd: system-node-critical
  resources:
    cleanup: {}
    crashcollector:
      limits:
        cpu: 500m
        memory: 60Mi
      requests:
        cpu: 100m
        memory: 60Mi
    exporter: {}
    logcollector: {}
    mgr: {}
    mgr-sidecar: {}
    mon: {}
    osd: {}
    prepareosd:
      requests:
        cpu: 500m
        memory: 50Mi
  security:
    keyRotation:
      enabled: false
    kms: {}
  storage:
    flappingRestartIntervalHours: 0
    store: {}
    useAllDevices: true
    useAllNodes: true
  waitTimeoutForHealthyOSDInMinutes: 10

```

**Logs to submit**:

```text
kubectl -n rook-ceph logs deployments/rook-ceph-operator | grep -i "e |"
...
2023-12-18 02:35:42.512532 E | ceph-csi: failed to reconcile failed to configure ceph csi: failed to start ceph csi drivers: failed to load rbd plugin service template: failed to load service template: template: rbd-service:18:21: executing "rbd-service" at <.RBDGRPCMetricsPort>: can't evaluate field RBDGRPCMetricsPort in type csi.templateParam
2023-12-18 02:41:11.854610 E | ceph-csi: failed to reconcile failed to configure ceph csi: failed to start ceph csi drivers: failed to load rbd plugin service template: failed to load service template: template: rbd-service:18:21: executing "rbd-service" at <.RBDGRPCMetricsPort>: can't evaluate field RBDGRPCMetricsPort in type csi.templateParam
...
```

**Environment**:
* OS (e.g. from /etc/os-release):
```text
Talos Linux, 1.5.5
```
* Kernel (e.g. `uname -a`):
```text
Linux: 6.1.61
```
* Cloud provider or hardware configuration:
```text
Intel NUC
```
* Rook version (use `rook version` inside of a Rook Pod):
```text
kubectl -n rook-ceph exec -it deployments/rook-ceph-operator -- rook version
rook: v1.13.0
go: go1.21.4
```
* Storage backend version (e.g. for ceph do `ceph -v`):
```text
kubectl -n rook-ceph exec -it deployments/rook-ceph-tools -- ceph -v
ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)
```
* Kubernetes version (use `kubectl version`):
```text
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.7", GitCommit:"07a61d861519c45ef5c89bc22dda289328f29343", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.4", GitCommit:"bae2c62678db2b5053817bc97181fcc2e8388103", GitTreeState:"clean", BuildDate:"2023-11-15T16:48:54Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
```text
Core, vanilla
```
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
```text
  kubectl -n rook-ceph exec -it deployments/rook-ceph-tools -- ceph status
  cluster:
    id:     62ce7b8d-b5b6-4305-ae9d-31b55bd683d5
    health: HEALTH_WARN
            1 mgr modules have recently crashed
 
  services:
    mon: 3 daemons, quorum a,b,c (age 4d)
    mgr: a(active, since 51m), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 4d), 3 in (since 2w)
    rgw: 2 daemons active (2 hosts, 1 zones)
 
  data:
    volumes: 1/1 healthy
    pools:   12 pools, 169 pgs
    objects: 5.42k objects, 13 GiB
    usage:   26 GiB used, 5.6 TiB / 5.6 TiB avail
    pgs:     169 active+clean
 
  io:
    client:   1.2 KiB/s rd, 58 KiB/s wr, 2 op/s rd, 9 op/s wr
 ```
