### ISSUE TITLE
Dashboard Ingress SSL error:0A00042E

### ISSUE THREAD

**Issue by cfis** [rook/rook#13449]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Enable the ceph dashboard. Using the rook-ceph-cluster helm chart:

```

cephClusterSpec:
  dashboard:
    enabled: true
    urlPrefix: /
    ssl: true

ingress:
  dashboard:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: ceph.xxx.internal
      nginx.ingress.kubernetes.io/rewrite-target: /ceph-dashboard/$2
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/server-snippet: |
        proxy_ssl_verify off;
    host:
      name: ceph.xxx.internal
      path: /
    ingressClassName: nginx
```

This is using the nginx ingress on Kubernetes 1.28.4 with a certificate generated by cert-manager.

Go to https://ceph.xxx.internal in a browser. Get a 502 Bad Gateway Error.

Looking at the nginx controller logs:

```
127.0.0.1 - - [20/Dec/2023:05:43:35 +0000] "GET / HTTP/2.0" 502 150 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0" 332 0.003 [rook-ceph-rook-ceph-mgr-dashboard-https-dashboard] [] 10.1.222.3:8443, 10.1.222.3:8443, 10.1.222.3:8443 0, 0, 0 0.002, 0.000, 0.001 502, 502, 502 7c121fc6b5b9de9ab76348147371d42d

2023/12/20 05:44:01 [error] 57361#57361: *30727277 SSL_do_handshake() failed (SSL: error:0A00042E:SSL routines::tlsv1 alert protocol version:SSL alert number 70) while SSL handshaking to upstream, client: 127.0.0.1, server: ceph.orbitalinsight.internal, request: "GET / HTTP/2.0", upstream: "https://10.1.222.3:8443/", host: "ceph.xxxxx.internal"
```

Googling a bit, I tried setting `proxy-ssl-protocols` to various values. For example:

    nginx.ingress.kubernetes.io/proxy-ssl-protocols: TLSv1.2

I cycled through all protocol versions but none worked.

**Expected behavior:**
That the ingress works.

**Environment**:
* Unbuntu 20.4
* Bare metal server
* Rook version 1.13.0
* Storage backend version: 18.2.1
* Kubernetes version (use `kubectl version`): 1.28.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Microk8s

**Comment by dcplaya** [comment]
I seem to have the same issue. I was able to connect to the dashboard via the host IP the `mgr` is on with port 8443. But I am unable to connect to it via the nginx ingress with the same error as OP.

**Comment by CrimsonFez** [comment]
I'm having this issue aswell. I believe it's caused by ingress-nginx not supporting or allowing tlsv1 out of the box. The auto generated cert is tlsv1 from what I can tell.

I've tried enabling support for TLSv1 in my ingress controller config and my ingress config but I'm still getting the error.
We need to be able to set our own certificate, or just have the cert use a newer version of TLS.

Setting the cert with a secret would also enable us to validate the connection with that same secret in the ingress config.

**Comment by rkachach** [comment]
@CrimsonFez @cfis this seems an issue on the nginx side! is there anything we can do on the dashboard side to improve the user experience in this case?

**Comment by rkachach** [comment]
@CrimsonFez thank you for the feedback. Capturing the traffic on the failed session will definitely help to understand why a higher TLS version is not used :+1:

**Comment by CrimsonFez** [comment]
@rkachach Here is the packet capture
[nginx.zip](https://github.com/rook/rook/files/13932607/nginx.zip)

**Comment by rkachach** [comment]
@CrimsonFez thank you very much for providing the traffic capture. I was able to reproduce the issue on my cluster and after some more investigation I found that the support of TLSv1.2 was dropped from the dashboard intentionally by the PR https://github.com/ceph/ceph/pull/50494 because of security concerns. 

However, in reef branch you can still enable the support by the configuration parameter `UNSAFE_TLS_1_2` on the dashboard. For this you have to:

1. From the dashboard open `Cluster > Manager Modules > dashboard` select dashboard and click on `Edit` button. Enable the option `UNSAFE_TLS_v1_2` and click on `Update`
2. Restart the dashboard, for this you have to open a toolbox and run the following:

`> ceph mgr module disable dashboard; ceph mgr module enable dashboard --force
`
Once the dashboard is up&running you should be able to use TLSv1.2

**Note:**
Please, keep in mind that moving to TLSv1.3 is highly recommendable and the support for TLSv1.2 could be completely removed  from the Ceph dashboard in future releases.

**Comment by CrimsonFez** [comment]
@rkachach Thanks for your work digging this up. However, ingress nginx does support TLSv1.3. So why it isn't using that I'm not sure. I've even specified it to use it for this ingress via annotation.

**Comment by rkachach** [comment]
@CrimsonFez I see, from the capture you provided it seems that nginx keeps trying to use TLSv1.2 all the time:

![image](https://github.com/rook/rook/assets/15921511/196e3762-9ae9-4cac-817b-1649c0534c2a)

I don't either understand why it doesn't switch to a higher protocol version once the handshake fails nor why it doesn't use `TLSv1.3` even when you specified it in the configuration. Maybe there's something wrong with configuration or some other issue. Unfortunately I can't help with that part as I'm not familiar with nginx internals.

**Comment by jsmouret** [comment]
fyi https://github.com/kubernetes/ingress-nginx/issues/8257

**Comment by rkachach** [comment]
Closing this issue as there's no BUG to be fixed in Rook or Ceph.

**Comment by am-i-helpful** [comment]
The current "ingress-nginx" HelmRelease values block setting up of `controller.allowSnippetAnnotations`
(reference - https://github.com/kubernetes/ingress-nginx/issues/12648#issuecomment-2796248026).

> (BadRequest): admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: annotation group ConfigurationSnippet contains risky annotation based on ingress configuration

So, one might want to explore resetting the controller.config.annotations-risk-level to 'Critical'.
```
controller:
    publishService:
        enabled: true
    allowSnippetAnnotations: true
    config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        enable-real-ip: "true"
        use-proxy-protocol: "true"
        annotations-risk-level: "Critical" # https://github.com/kubernetes/ingress-nginx/issues/12648#issuecomment-2796248026
```
