### ISSUE TITLE
AMQP URI With Password

### ISSUE THREAD

**Issue by cfis** [rook/rook#13450]
**Is this a bug report or feature request?**
* Bug Report

Try to create a Topic:

```
apiVersion: ceph.rook.io/v1
kind: CephBucketTopic
metadata:
  name: MyTopic
spec:
  objectStoreName: ceph-objectstore
  objectStoreNamespace: rook-ceph
  persistent: true
  endpoint:
    amqp:
      exchange: MyExchange
      uri:  amqp://user:password@rabbitmq.ops/eda
      ackLevel: broker
```
This will fail because Ceph rejects the request due to the user:password in the uri (not using amqps doesn't make a difference).

According to the Ceph documentation (https://docs.ceph.com/en/quincy/radosgw/notifications/#create-a-topic):

> user/password: This defaults to “guest/guest”.
   user/password: This must be provided only over HTTPS. Topic creation requests will otherwise be rejected.

Thus it seems that Rook is communication with Ceph via HTTP and not HTTPS? Note ssl is enabled on the ceph dashboard.

**Environment**:
* Unbuntu 20.4
* Bare metal server
* Rook version 1.13.0
* Storage backend version: 18.2.1
* Kubernetes version (use `kubectl version`): 1.28.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Microk8s
