### ISSUE TITLE
Ceph: config: revisit cluster CRD defaults (paths, namespaces, ...)

### ISSUE THREAD

**Issue by liewegas** [rook/rook#1347]
Several things stood out when looking at the cluster CRD:

- the default path, if not specified, makes rook use emptyDir.  defaulting to an emphemeral clsuter seems like a very dangerous/bad default!
- /var/lib/ceph/$namespace for the default instead of /var/lib/rook?  makes it very confusing (esp inside containers) when things are in default locations.
- drop cluster name inside ceph container?

**Comment by kokhang** [comment]
@liewegas one thing Rook is doing with the cluster CRD is to avoid exposing information about the underlying storage backend. Even though ceph is currently the only storage backend, I would like to make the Rook API (CRD) generic enough so that more storage backends can be added in the future.

You are right about the need to revisit the CRD. How about having a `ceph` element under `spec` for all the ceph specific params. We can even set the dataDir here to be `/var/lib/ceph`. For example:

```
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  dataDirHostPath: /var/lib/rook
  # toggle to use hostNetwork
  hostNetwork: false
  ceph:
    dataDir: /var/lib/ceph
    # set the amount of mons to be started
    monCount: 3
    storage: # cluster level storage configuration and selection
      useAllNodes: true
      useAllDevices: false
      deviceFilter:
      metadataDevice:
      location:
      storeConfig:
        storeType: bluestore
        databaseSizeMB: 1024 # this value can be removed for environments with normal sized disks (100 GB or larger)
        journalSizeMB: 1024  # this value can be removed for environments with normal sized disks (20 GB or larger)
```
