### ISSUE TITLE
can rook make more easy to use，delete things makes me annoyed

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#13548]
···
2024-01-10 07:08:47.005666 E | ceph-object-zone-controller: failed to reconcile CephObjectZone "rook-ceph/zone-b". CephObjectZoneGroup.ceph.rook.io "zonegroup-a" not found
2024-01-10 07:08:57.107848 I | ceph-spec: parsing mon endpoints: a=192.168.229.189:6789,b=192.168.229.185:6789,c=192.168.229.188:6789
2024-01-10 07:09:12.007813 E | ceph-object-zone-controller: failed to reconcile CephObjectZone "rook-ceph/zone-b". CephObjectZoneGroup.ceph.rook.io "zonegroup-a" not found
2024-01-10 07:09:22.023693 I | ceph-spec: parsing mon endpoints: a=192.168.229.189:6789,b=192.168.229.185:6789,c=192.168.229.188:6789
2024-01-10 07:09:37.904655 E | ceph-object-zone-controller: failed to reconcile CephObjectZone "rook-ceph/zone-b". CephObjectZoneGroup.ceph.rook.io "zonegroup-a" not found
2024-01-10 07:09:48.004811 I | ceph-spec: parsing mon endpoints: a=192.168.229.189:6789,b=192.168.229.185:6789,c=192.168.229.188:6789
···
apply this:
```

apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: realm-a
  namespace: rook-ceph
spec:
  pull:
    endpoint: http://rook-ceph-rgw-multisite-store.rook-ceph.svc:80
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: zonegroup-a
  namespace: rook-ceph
spec:
  realm: realm-a
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: zone-b
  namespace: rook-ceph
spec:
  zoneGroup: zonegroup-a
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
  dataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: zone-b-multisite-store
  namespace: rook-ceph
spec:
  gateway:
    port: 80
    # securePort: 443
    instances: 1
  zone:
    name: zone-b
```

then delete it

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:
