### ISSUE TITLE
when update zone's endpoint objectstore's endpoint wan't updated

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#13549]
```
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: zone-a
  namespace: rook-ceph 
spec:
  zoneGroup: zonegroup-a
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
  dataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      compression_mode: none
  # recommended to set this value if ingress used for exposing rgw endpoints
  customEndpoints:
  - "http://rgw.example.com"
```
```

status:
  endpoints:
    insecure:
    - http://rook-ceph-rgw-multisite-store.rook-ceph.svc:80
    secure: []
  info:
    endpoint: http://rook-ceph-rgw-multisite-store.rook-ceph.svc:80
```
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:
