### ISSUE TITLE
Dashboard Password Invalid Even Though Logs Show Successfully Set

### ISSUE THREAD

**Issue by tman5** [rook/rook#13594]
**Is this a bug report or feature request?* 
* Bug Report

**Deviation from expected behavior:** admin account cannot login to the dashboard. This is from a restored cluster using these steps: https://rook.io/docs/rook/latest/Troubleshooting/disaster-recovery/#restoring-crds-after-deletion

**Expected behavior:** admin account can login to the dashboard

**How to reproduce it (minimal and precise):**
Even after deleting and re-creating the password we still get failed logins. We're seeing 400s in the logs when the mons try to run the login. The logs show the password is set, so that's why it's baffling

**Logs to submit**:

[logs.zip](https://github.com/rook/rook/files/13990842/logs.zip)

```
bash-4.4$ ceph health
HEALTH_OK

bash-4.4$ ceph status
  cluster:
    id:     5de11a19-6bef-4fe7-bb1e-ed4471446790
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum q,t,w (age 2h)
    mgr: b(active, since 2h), standbys: a
    mds: 2/2 daemons up, 2 hot standby
    osd: 5 osds: 5 up (since 2h), 5 in (since 10d)
    rgw: 1 daemon active (1 hosts, 1 zones)
 
  data:
    volumes: 2/2 healthy
    pools:   14 pools, 313 pgs
    objects: 109.37k objects, 414 GiB
    usage:   1.2 TiB used, 1.2 TiB / 2.4 TiB avail
    pgs:     313 active+clean
 
  io:
    client:   2.6 KiB/s rd, 9.0 MiB/s wr, 5 op/s rd, 136 op/s wr
```

**Environment**:
* OS (e.g. from /etc/os-release): Rocky 8
* Kernel (e.g. `uname -a`): 4.18.0-513.9.1.el8_9.x86_64
* Cloud provider or hardware configuration: on-prem
* Rook version (use `rook version` inside of a Rook Pod): 1.13
* Storage backend version (e.g. for ceph do `ceph -v`): 17.2.5
* Kubernetes version (use `kubectl version`): 1.25.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubespray
