### ISSUE TITLE
Consider supporting EC pools for block storage class

### ISSUE THREAD

**Issue by AceHack** [rook/rook#1360]
See https://github.com/rook/rook/issues/1327 for known issues with this scenario.

Looks like a few things would need to happen for this to work

Allow optional creation of EC pools that have "ceph osd pool set POOL_NAME allow_ec_overwrites true" enabled

This alone is not enough to support EC pools for block storage class, looks like there are two options to fully enabled it and it would be great to support both.

http://docs.ceph.com/docs/master/rados/operations/erasure-code/#erasure-coding-with-overwrites
This talks about either storing metadata in a replicated pool or using a caching tier for writeback, both of these options are appealing.

**Comment by travisn** [comment]
Here are some thoughts on the Rook design to support the erasure coded pools for rbd:
1. Set all erasure coded pools to `allow_ec_overwrites true`. According to ceph docs, this should only be set on `bluestore` osds. Setting this on filestore is unsafe for writes. 
1. Add `metadataPool` and `cacheTierPool `properties to the rook storage class, in addition to the `pool` property. 
    - If only `pool` is set, it will be used for both metadata and data
    - If `pool` and `metadataPool` are set, `pool` is used for data and `metadataPool` is used for metadata, in which case `pool` should be an erasure coded pool. When the rbd image is created by the rook provisioner, the `--data-pool` argument is passed to the `rbd create` [command](https://github.com/rook/rook/blob/master/pkg/daemon/ceph/client/image.go#L75).
    - If `pool` and `cacheTierPool` are set, the `cacheTierPool` is configured in front of the erasure coded `pool`.

The storage class parameters for a basic replica pool:
``` 
pool: replicapool
```
The storage class parameters for an erasure coded pool with a replicated pool for metadata:
```
pool: ecpool
metadataPool: replicapool
```
The storage class parameters for an erasure coded pool with a fast tier in front of it
```
pool: ecpool
cacheTierPool: fastpool
```
Where the pools are defined by the pool CRD such as the following.
```
apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: replicapool
  namespace: rook
spec:
  replicated:
    size: 3
---
apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: ecpool
  namespace: rook
spec:
  erasureCoded:
    dataChunks: 2
    codingChunks: 1
---
apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: fastpool
  namespace: rook
spec:
  crushRoot: ssd
  replicated:
    size: 1
```
Note that setting the `crushRoot` requires the change from #1204.
