### ISSUE TITLE
Cannot make use of RADOS namespace for external cluster with EC block pool

### ISSUE THREAD

**Issue by bauerjs1** [rook/rook#13633]
When using an erasure-coded data pool for RBDs, there must exist an additional replicated metadata pool. Since Ceph does not support RADOS namespaces in EC pools, I only created it in the metadata pool. When I pass the flags
```sh
--rbd-data-pool-name ceph-block
--rbd-metadata-ec-pool-name ceph-block-metadata # afaik metadata pool can't be EC so the name is a bit misleading
--rados-namespace staging
```
to `create-external-cluster-resources.py`, the script looks for namespace `staging` in the EC data pool `ceph-block` (where it cannot exist) instead of the metadata pool.

How can I use tenant isolation with RADOS namespaces for external clusters when the data pool for RBDs is erasure-coded?

Thanks in advance!

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
`create-external-cluster-resources.py` script fails with
> The provided rados Namespace, 'staging', is not found in the pool 'ceph-block'

**Expected behavior:**
To my understanding, the script should look for the provided namespace in the *metadata* block pool if the data pool is erasure-coded **(please correct me if I am wrong here)**

**How to reproduce it:**
Apply below resources in source cluster and try to extract information for a Rook external consumer cluster with
```sh
python3 create-external-cluster-resources.py --rbd-data-pool-name ceph-block --rbd-metadata-ec-pool-name ceph-block-metadata --rados-namespace staging
```

**File(s) to submit**:
Resources created in the source cluster:
```yaml
# metadata pool (for use in consumer StorageClass.parameters.pool)
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ceph-block-metadata
spec:
  replicated:
    size: 3
---
# data pool (for use in consumer StorageClass.parameters.dataPool)
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ceph-block
spec:
  erasureCoded:
    codingChunks: 1
    dataChunks: 2
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPoolRadosNamespace
metadata:
  name: staging
spec:
  blockPoolName: ceph-block-metadata
  name: staging
```

**Environment**:
Source cluster:
* OS: Ubuntu 20.04
* Kernel: `5.15.0`
* Rook version: `1.13.3`
* Storage backend version: `18.2.1`
* Kubernetes version: `1.25`
* Kubernetes cluster type: bare metal

**Comment by bauerjs1** [comment]
Any ideas? I would probably go with a replicated pool for block storage, otherwise.

**Comment by subhamkrai** [comment]
@bauerjs1 Something seems to be wrong, please wait for @parth-gr to response he will back in next week. Thanks

**Comment by parth-gr** [comment]
We currently do not support rados namesapce with ec block pool, I think even not ceph, 

>To my understanding, the script should look for the provided namespace in the metadata block pool if the data pool is erasure-coded (please correct me if I am wrong here)
That can be done, but its just the python script check, we need that support from the ceph backend.

I you have any recommendations on how to use it please let us know.


cc @travisn

**Comment by bauerjs1** [comment]
Yes, afaik Ceph does not support namespaced EC block pool.

> > To my understanding, the script should look for the provided namespace in the metadata block pool if the data pool is erasure-coded (please correct me if I am wrong here)
> 
> That can be done, but its just the python script check, we need that support from the ceph backend.
> 
> I you have any recommendations on how to use it please let us know.

I am not sure what you mean here.
Shouldn't it be sufficient that if `--rbd-metadata-ec-pool-name` is provided, the script should look for the `--rados-namespace` there (instead of the data pool). This should be supported by Ceph, I was able to do that from the CLI.

However, I am unsure if that construct of having a namespaced metadata pool but a non-namespaced data pool would make sense at all. I am far from being a Ceph expert and that just felt most intuitive to me, tbh.

**Comment by parth-gr** [comment]
I tried creating radosnamesapce in ec pool and it was successful, then I created a ec Storageclass(updating the cluster-id throuh radosnamesapce status) and created the pvc,

But I got this warning in pvc and still in pending state, not sure how it worked for you @bauerjs1 
```
Type     Reason                Age                  From                                                                                                                Message
  ----     ------                ----                 ----                                                                                                                -------
  Normal   Provisioning          8s (x9 over 2m16s)   [openshift-storage.rbd.csi.ceph.com](http://openshift-storage.rbd.csi.ceph.com/)_csi-rbdplugin-provisioner-57488675f8-mvhh6_e21e5f28-22bf-46eb-9469-3fe1119588ee  External provisioner is provisioning volume for claim "openshift-storage/rbd-pvc-test"
  Warning  ProvisioningFailed    8s (x9 over 2m16s)   openshift-storage.rbd.csi.ceph.com_csi-rbdplugin-provisioner-57488675f8-mvhh6_e21e5f28-22bf-46eb-9469-3fe1119588ee  failed to provision volume with StorageClass "rook-ceph-block-ec": rpc error: code = InvalidArgument desc = failed to fetch monitor list using clusterID (cb04b59bcd4b2535c5cb1b1ebec4c59b): missing configuration for cluster ID "cb04b59bcd4b2535c5cb1b1ebec4c59b"
  Normal   ExternalProvisioning  1s (x11 over 2m16s)  persistentvolume-controller                                                                                         Waiting for a volume to be created either by the external provisioner 'openshift-storage.rbd.csi.ceph.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
[rider@localhost rbd]$
```

cc @Madhu-1 should this need fix in csi

**Comment by bauerjs1** [comment]
> Yes, afaik Ceph does not support namespaced EC block pool.

Yes, unfortunately Ceph doesn't support this. So the idea was to create the namespaces only in the metadata pool (which is always replicated and not erasure-coded). I can confirm that Rook's RADOS namespace objects are successfully created on the metadata pool:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephBlockPoolRadosNamespace
metadata:
  name: staging
  namespace: storage
spec:
  blockPoolName: ceph-block-metadata
  name: staging
status:
  info:
    clusterID: 429b...
  phase: Ready
```
However, there is currently no possibility to pass this to the `create-external-cluster-resources.py` script.

**Comment by parth-gr** [comment]
@bauerjs1 is this what you are looking for https://github.com/rook/rook/pull/13769

**Comment by parth-gr** [comment]
@bauerjs1 so can you try and test the new script changes https://github.com/rook/rook/pull/13769 and lemme know is that fix you wanted, as the requirements were quite confusing.

**Comment by bauerjs1** [comment]
Sorry for the delay @parth-gr, I'm quite busy with different stuff in the past few weeks but I'm currently on it again. I will let you know as soon as I have tested it.

**Comment by bauerjs1** [comment]
I suppose it's a different problem, but I am now getting the error
```
Execution Failed: Only 'v2' address type is enabled, user should also enable 'v1' type as well
```
so I am not yet able to test if this works.

PR https://github.com/rook/rook/pull/8083 seems to be the origin of the error message but I have no clue, why this fails and how to resolve that. Since I enabled encryption, I specified `--v2-port-enable` as explained [in the docs](https://rook.io/docs/rook/latest-release/CRDs/Cluster/external-cluster/#connect-to-v2-mon-port).

Networking config:
```yaml
  network:
    connections:
      compression:
        enabled: false
      encryption:
        enabled: true
      requireMsgr2: false
```
