### ISSUE TITLE
Leverage node labels for OSD CRUSH locations

### ISSUE THREAD

**Issue by jpds** [rook/rook#1366]
Is this a bug report or feature request?
**Feature Request**

Are there any similar features already existing: N/A

What should the feature do: 

It would be good to have a way of setting node labels on Kubernetes nodes which the operator can then use to set OSD CRUSH locations: http://docs.ceph.com/docs/master/rados/operations/crush-map/#crush-location

This could also use `failure-domain.beta.kubernetes.io/region` and `zone`: https://kubernetes.io/docs/reference/labels-annotations-taints/#failure-domainbetakubernetesiozone

However, we'll more likely need a `rook.io/crushmap/*` for labels, for example:

 * `rook.io/crushmap/row=B`
 * `rook.io/crushmap/rack=B11`

What would be solved through this feature:

This would then allow the user to set the `crush-failure-domain` on their pools to rows of racks/racks rather than at a host level.

**Comment by galexrt** [comment]
Note: We need to keep in mind when adding a label for this to rook that this is a Ceph specific setting.

**Comment by galexrt** [comment]
Having talked about this with @mmack a bit, I have come to the conclusion that something like this may possibly as a solution:
```
locations:
  bySelector:
    node: # []map[string]string
      - this-is-a-custom-crush-key-thing: my-value-here
      - host: .Metadata.Name
      - datacenter: .Metadata.Labels["failure-domain.beta.kubernetes.io/datacenter"]
      - rack: .Metadata.Labels["failure-domain.beta.kubernetes.io/rack"]
```
