### ISSUE TITLE
Rook Dashboard hangs/times out

### ISSUE THREAD

**Issue by Nickmman** [rook/rook#13662]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When accessing the Rook Dashboard from the Ingress (or even directly to the active mgr pod), the HTTP request times out. Sometimes it serves the content once but then it continuously times out with the ingress reporting 504.

**Expected behavior:**
Rook Dashboard is properly served

**How to reproduce it (minimal and precise):**

Deploy an operator that then deploys the CephCluster

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```
  values:
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
          enableRBDStats: true
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: false
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: "Immediate"
          mountOptions: []
          allowedTopologies: []
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/fstype: ext4
    cephClusterSpec:
      dataDirHostPath: /var/lib/rook
      dashboard:
        enabled: true
        ssl: false
      monitoring:
        enabled: true
      disruptionManagement:
        managePodBudgets: true
      mon:
        count: 3
        allowMultiplePerNode: false
        volumeClaimTemplate:
          spec:
            storageClassName: standard-rwo
            resources:
              requests:
                storage: 10Gi
      mgr:
        count: 3
      storage:
        useAllNodes: true
        useAllDevices: false
        storageClassDeviceSets:
          - name: rook
            count: 3
            placement:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - rook-ceph-osd
                            - rook-ceph-osd-prepare
                    topologyKey: topology.kubernetes.io/zone
            portable: true
            tuneDeviceClass: false
            volumeClaimTemplates:
              - metadata:
                  name: data
                spec:
                  resources:
                    requests:
                      storage: 200Gi
                  storageClassName: standard-rwo
                  volumeMode: Block
                  accessModes:
                    - ReadWriteOnce
      placement:
        mon:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - rook-ceph-mon
                topologyKey: topology.kubernetes.io/zone
        storage:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - rook-ceph-osd
                        - rook-ceph-osd-prepare
                topologyKey: topology.kubernetes.io/zone
      resources:
        crashcollector:
          limits:
            cpu: 500m
            memory: 60Mi
          requests:
            cpu: 10m
            memory: 60Mi
        mgr:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 512Mi
        mon:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
        osd:
          limits:
            cpu: 500m
            memory: 6Gi
          requests:
            cpu: 100m
            memory: 2Gi
    cephFileSystems: {}
    cephObjectStores: {}
    ingress:
      dashboard:
        annotations:
          cert-manager.io/cluster-issuer: dns-issuer
          kubernetes.io/tls-acme: "true"
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        ingressClassName: nginx-internal
    monitoring:
      enabled: true
      createPrometheusRules: true
      rulesNamespaceOverride: logging-monitoring
    toolbox:
      enabled: true
      containerSecurityContext:
        runAsNonRoot: true
        runAsUser: 2016
        runAsGroup: 2016
        capabilities:
          drop: ["ALL"]
```

**Logs to submit**:
No logs related to accessing the dashboard from the mgr pods 

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
No crashing pods

**Cluster Status to submit**:
```
[root@rook-ceph-tools-6595b6bb4-gw68d /]# ceph status
  cluster:
    id:     113e9a1d-f5bd-4c95-b3b6-ce79136c679b
    health: HEALTH_WARN
            2 nearfull osd(s)
            2 pool(s) nearfull
            4 daemons have recently crashed

  services:
    mon: 3 daemons, quorum g,j,k (age 3h)
    mgr: a(active, since 3h), standbys: c, b
    osd: 3 osds: 3 up (since 26h), 3 in (since 3M)

  data:
    pools:   2 pools, 33 pgs
    objects: 20.13k objects, 78 GiB
    usage:   436 GiB used, 164 GiB / 600 GiB avail
    pgs:     33 active+clean

  io:
    client:   2.0 MiB/s wr, 0 op/s rd, 164 op/s wr
```
* Output of kubectl commands, if necessary

**Environment**:
* OS (e.g. from /etc/os-release):  Ubuntu 22.04.3 LTS
* Kernel (e.g. `uname -a`):  5.15.0-1039-gke
* Cloud provider or hardware configuration: GCP
* Rook version (use `rook version` inside of a Rook Pod): 
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)
* Kubernetes version (use `kubectl version`): v1.26.10-gke.1101000
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): `HEALTH_WARN 2 nearfull osd(s); 2 pool(s) nearfull; 4 daemons have recently crashed` (crashed pods probably correspond with spot instances terminating)

**Comment by rkachach** [comment]
@Nickmman please, can you have a look to this issue https://github.com/rook/rook/issues/12877. The symptoms seem really similar and it may be related with some issues that arise when SSL is enabled.

**Comment by Nickmman** [comment]
> @Nickmman please, can you have a look to this issue #12877. The symptoms seem really similar and it may be related with some issues that arise when SSL is enabled but from your spec I can see that it's not the case!

Hi @rkachach, I can confirm that I am not using rook with SSL enabled, rather that is taken care of by nginx-ingress. This would also not correlate with trying to hit the pod directly on what should be a regular http reply. I can confirm, however, that I did notice a spike in CPU usage by the active mgr pod, see below:
![image](https://github.com/rook/rook/assets/6664031/bf3c58c3-cda1-44bf-9c22-2b9cba5ba6c1)
Though this may have to be due to cleanup by deleting a block image (since I'm using RBD).
I look forward to see what else could be causing this issue.

**Comment by Nickmman** [comment]
I have confirmed that the increased CPU usage only corresponds when accessing the dashboards, as it is high again and I have opened up the dashboards. It initially worked for a couple of pages but has started timing out again and is unusable.

**Comment by rkachach** [comment]
@Nickmman I'm curious about the ingress configuration:

`          nginx.ingress.kubernetes.io/ssl-redirect: "true"`

Would this convert http traffic to https when directing it to the dashboard?

**Comment by Nickmman** [comment]
@rkachach This is just to redirect end users when using HTTP to the HTTPS version of the endpoint, via a 308. It is not related to the backend endpoint, which is the mgr service. Backend traffic to the mgr service is maintained as HTTP, as per `nginx.ingress.kubernetes.io/backend-protocol: HTTP`

**Comment by rkachach** [comment]
I see, thanks for the clarification @Nickmman. BTW: your cluster has two important warnings: 

```
            2 nearfull osd(s)
            2 pool(s) nearfull
```

It would be good to see if after fixing them you continue experimenting the slowness issue or not. Meanwhile, can you please attach the mgr logs (specially when the dashboard starts going slow)?

**Comment by Nickmman** [comment]
@rkachach I have fixed the osd/pool usage last night by recreating each of the osds, since it was not freeing up space from deleted block images. I hope that I don't have to do this frequently but I haven't been able to come across any documentation about cleaning up the osds, aside from recreating them.

Regarding the original issue, I have also increased the CPU limit to double (or more than double) what was assigned to the mgr pods. This seems to have resolved the issue, though it is still unclear why it needs so much processing power to present a dashboard. It is already reaching the CPU limit I have assigned.

Should this happen again, I will try to obtain the mgr logs (nothing jumps out aside from constant DBG messages about the PGs). I did run top however, and the process that is consuming near 100% (and sometimes 100%) is `dashboard`
![image](https://github.com/rook/rook/assets/6664031/069ca8f2-605a-4f07-aa02-e46b1a16c8f9)

**Comment by rkachach** [comment]
can you plz run the following from inside the mgr pod and report the output?

`ss -tulpn`
`ss -anp`

**Comment by Nickmman** [comment]
@rkachach Output is attached. The dashboard is timing out again, I've attached the logs from the active mgr as well. I've created a zipfile containing both files since one of them is pretty large in size.
[rookmgr-output-and-logs.zip](https://github.com/rook/rook/files/14127586/rookmgr-output-and-logs.zip)

**Comment by rkachach** [comment]
hi @Nickmman thank you for providing the logs. As I can see there're a lot of connections open but left in `TIME_WAIT` probably causing high CPU consumption at server side level. Some exceptions are being raised such as:

```
Internal Server Error
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 47, in dashboard_exception_handler
    return handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/_base_controller.py", line 258, in inner
    ret = func(*args, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/health.py", line 293, in minimal
    return self.health_minimal.all_health()
  File "/usr/share/ceph/mgr/dashboard/controllers/health.py", line 150, in all_health
    result['hosts'] = self.host_count()
  File "/usr/share/ceph/mgr/dashboard/controllers/health.py", line 213, in host_count
    return len(get_hosts())
  File "/usr/share/ceph/mgr/dashboard/controllers/host.py", line 204, in get_hosts
    return merge_hosts_by_hostname(ceph_hosts, orch.hosts.list())
  File "/usr/share/ceph/mgr/dashboard/controllers/host.py", line 161, in merge_hosts_by_hostname
    host['hostname'], host['services'])
  File "/usr/share/ceph/mgr/dashboard/controllers/host.py", line 170, in populate_service_instances
    for d in orch.services.list_daemons(hostname=hostname)))
  File "/usr/share/ceph/mgr/dashboard/services/orchestrator.py", line 39, in inner
    raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception
    raise e
```
I can see that you are running ceph `v17.2.6` which is the previous version. Latest version `v18.2.1` has several fixes so it could potentially fix the issue you are experimenting but it has [this BUG](https://github.com/rook/rook/issues/13527) with metrics and at this moment users are relying on the image `docker.io/rkachach/ceph:v18.2.1_patched_v1` until a stable ceph release with the fix is made available.

I'd recommend upgrade to the latest Rook release and use the above patch version to see if that fixes your issue.

**Comment by Nickmman** [comment]
@rkachach Thank you for your findings and comment. I have gone ahead and updated the deployment, I will be watching and testing to see if this resolves the issue. As far as the connections go, the only thing I can think of is the prometheus scraper, which shows up in the mgr logs frequently. Other than that, the dashboard isn't frequently accessed.

**Comment by rkachach** [comment]
@Nickmman please let me now if the upgrade has solved your issues or not.

**Comment by Nickmman** [comment]
@rkachach The issue seems to be resolved. I am now questioning the resources used up by the dashboard component, mainly CPU. Currently, [default values](https://github.com/rook/rook/blob/577c7cc6360fc64f4aacd9075fec8527d5d9001a/deploy/charts/rook-ceph-cluster/values.yaml#L281-L288) are:
```
  resources:
    mgr:
      limits:
        cpu: "1000m"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "512Mi"
```
But watching over this issue and subsequent increase of resources, it seems that it is constantly maxing out during usage. Is this normal or is dashboard/mgr just using up more resources than it should be?
