### ISSUE TITLE
Ceph External docs create buggy storage classes and toolbox ot working

### ISSUE THREAD

**Issue by urbaman** [rook/rook#13681]
* Bug Report

**Deviation from expected behavior:**

The Storage classes auto-created point to the wrong namespace when creating an external cluster as per the documentation.
The Tollbox, if running in the same namespace as the cluster, has RADOS permission errors.

The sample mysql/wordpress site works flawlessly with the corrected storage class (the app works and I can see the rbd volumes created), so the cluster works.

**Expected behavior:**

The Storage classes shoud point to the right namespace, the toolbox connects.

**How to reproduce it (minimal and precise):**

Create an external cluster as per the documentation (manifests, as the helm values files mentioned are not present in the examples)

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

Wrong SC

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-rbd
parameters:
  clusterID: external-rook
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: external-rook
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: external-rook
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: external-rook
  imageFeatures: layering
  imageFormat: "2"
  pool: Ceph-NVMe2TB
provisioner: rook-ceph.rbd.csi.ceph.com
reclaimPolicy: Delete
```
Right SC

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-external-rbd
parameters:
  clusterID: rook-ceph-external
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph-external
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph-external
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph-external
  imageFeatures: layering
  imageFormat: "2"
  pool: Ceph-NVMe2TB
provisioner: rook-ceph.rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 22.04
* Kernel (e.g. `uname -a`): 5.15.0-92-generic
* Cloud provider or hardware configuration: Kubeadm, 3xCP 9xW
* Rook version (use `rook version` inside of a Rook Pod): v1.13.0-alpha.0.218.g21a99f33b
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.1
* Kubernetes version (use `kubectl version`): 1.28.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): Tollbox not working, see above, I can assure Ceph works flawlessly.
