### ISSUE TITLE
Upgrade Rook Version to 1.12.11 Ceph Exporter Nodes not upgraded

### ISSUE THREAD

**Issue by grassdionera** [rook/rook#13700]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
On Upgrading the Rook Version from one Patch 1.12.6 to 1.12.11 with the official guide, then all of the rook-ceph-exporter-node{n} deployments are not getting upgraded, or at least the version label is not set correctly. Watching the rook version with watch kubectl it shows the old rook version, 

<details>
  <summary>Watch output</summary>

```bash
Alle 1,0s: kubectl --context int -n rook-ceph get deployments -l rook_cluster=rook-ceph -o jsonpath={range .items[*]}{.metadata.name}{"  \treq/upd/avl: "}...  

rook-ceph-crashcollector-node1          req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-crashcollector-node2          req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-crashcollector-node3          req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-crashcollector-node4          req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-exporter-node1        req/upd/avl: 1/1/1      rook-version=v1.12.6
rook-ceph-exporter-node2        req/upd/avl: 1/1/1      rook-version=v1.12.6
rook-ceph-exporter-node3        req/upd/avl: 1/1/1      rook-version=v1.12.6
rook-ceph-exporter-node4        req/upd/avl: 1/1/1      rook-version=v1.12.6
rook-ceph-mds-myfs-a    req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-mds-myfs-b    req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-mgr-a         req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-mgr-b         req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-mon-d         req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-mon-k         req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-mon-l         req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-osd-0         req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-osd-1         req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-osd-2         req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-osd-3         req/upd/avl: 1/1/1      rook-version=v1.12.11
rook-ceph-rgw-dio-object-store-a        req/upd/avl: 1/1/1      rook-version=v1.12.11
```
</details>

but the operator says `done reconciling ceph cluster in namespace "rook-ceph"`

I tried the Patch upgrade on another cluster from 1.12.4 to 1.12.7 and this worked as expected. But then upgrading this from 1.12.7 to 1.12.11 the same problem happend. 

as the cluster seems to be working correctly, it is not a major problem, but i don't know if i can go forward with upgrades to 1.13 or if the patch versions should anywhere be the same for the minor upgarde

**Expected behavior:**
The Upgrade of a rook Version should upgrade all required Components and set correct Version Labels, or remove components if they are not required anymore. 

**How to reproduce it (minimal and precise):**

Set up a cluster with rook version 1.12.6 or 1.12.7 and update rook with the official guide to version 1.12.11

**File(s) to submit**:

<details>
  <summary>Cluster CR</summary>

```yaml
#################################################################################################################
# Define the settings for the rook-ceph cluster with common settings for a production cluster.
# All nodes with available raw devices will be used for the Ceph cluster. At least three nodes are required
# in this example. See the documentation for more details on storage settings available.

# For example, to create the cluster:
#   kubectl create -f crds.yaml -f common.yaml -f operator.yaml
#   kubectl create -f cluster.yaml
#################################################################################################################

apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph # namespace:cluster
spec:
  cephVersion:
    # The container image used to launch the Ceph daemon pods (mon, mgr, osd, mds, rgw).
    # v16 is Pacific, and v17 is Quincy.
    # RECOMMENDATION: In production, use a specific version tag instead of the general v17 flag, which pulls the latest release and could result in different
    # versions running within the cluster. See tags available at https://hub.docker.com/r/ceph/ceph/tags/.
    # If you want to be more precise, you can always use a timestamp tag such quay.io/ceph/ceph:v17.2.3-20220805
    # This tag might not contain a new Ceph version, just security fixes from the underlying operating system, which will reduce vulnerabilities
    image: quay.io/ceph/ceph:v18.2
    # Whether to allow unsupported versions of Ceph. Currently `pacific` and `quincy` are supported.
    # Future versions such as `reef` (v18) would require this to be set to `true`.
    # Do not set to true in production.
    allowUnsupported: false
  # The path on the host where configuration files will be persisted. Must be specified.
  # Important: if you reinstall the cluster, make sure you delete this directory from each host or else the mons will fail to start on the new cluster.
  # In Minikube, the '/data' directory is configured to persist across reboots. Use "/data/rook" in Minikube environment.
  dataDirHostPath: /var/lib/rook
  # Whether or not upgrade should continue even if a check fails
  # This means Ceph's status could be degraded and we don't recommend upgrading but you might decide otherwise
  # Use at your OWN risk
  # To understand Rook's upgrade process of Ceph, read https://rook.io/docs/rook/latest/ceph-upgrade.html#ceph-version-upgrades
  skipUpgradeChecks: false
  # Whether or not continue if PGs are not clean during an upgrade
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  # WaitTimeoutForHealthyOSDInMinutes defines the time (in minutes) the operator would wait before an OSD can be stopped for upgrade or restart.
  # If the timeout exceeds and OSD is not ok to stop, then the operator would skip upgrade for the current OSD and proceed with the next one
  # if `continueUpgradeAfterChecksEvenIfNotHealthy` is `false`. If `continueUpgradeAfterChecksEvenIfNotHealthy` is `true`, then operator would
  # continue with the upgrade of an OSD even if its not ok to stop after the timeout. This timeout won't be applied if `skipUpgradeChecks` is `true`.
  # The default wait timeout is 10 minutes.
  waitTimeoutForHealthyOSDInMinutes: 10
  mon:
    # Set the number of mons to be started. Generally recommended to be 3.
    # For highest availability, an odd number of mons should be specified.
    count: 3
    # The mons should be on unique nodes. For production, at least 3 nodes are recommended for this reason.
    # Mons should only be allowed on the same node for test environments where data loss is acceptable.
    allowMultiplePerNode: false
  mgr:
    # When higher availability of the mgr is needed, increase the count to 2.
    # In that case, one mgr will be active and one in standby. When Ceph updates which
    # mgr is active, Rook will update the mgr services to match the active mgr.
    count: 2
    allowMultiplePerNode: false
    modules:
      # Several modules should not need to be included in this list. The "dashboard" and "monitoring" modules
      # are already enabled by other settings in the cluster CR.
      - name: pg_autoscaler
        enabled: true
  # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    # port: 8443
    # serve the dashboard using SSL
    ssl: true
  # enable prometheus alerting for cluster
  monitoring:
    # requires Prometheus to be pre-installed
    enabled: true
  network:
    connections:
      # Whether to encrypt the data in transit across the wire to prevent eavesdropping the data on the network.
      # The default is false. When encryption is enabled, all communication between clients and Ceph daemons, or between Ceph daemons will be encrypted.
      # When encryption is not enabled, clients still establish a strong initial authentication and data integrity is still validated with a crc check.
      # IMPORTANT: Encryption requires the 5.11 kernel for the latest nbd and cephfs drivers. Alternatively for testing only,
      # you can set the "mounter: rbd-nbd" in the rbd storage class, or "mounter: fuse" in the cephfs storage class.
      # The nbd and fuse drivers are *not* recommended in production since restarting the csi driver pod will disconnect the volumes.
      encryption:
        enabled: false
      # Whether to compress the data in transit across the wire. The default is false.
      # Requires Ceph Quincy (v17) or newer. Also see the kernel requirements above for encryption.
      compression:
        enabled: false
      # Whether to require communication over msgr2. If true, the msgr v1 port (6789) will be disabled
      # and clients will be required to connect to the Ceph cluster with the v2 port (3300).
      # Requires a kernel that supports msgr v2 (kernel 5.11 or CentOS 8.4 or newer).
      requireMsgr2: false
    # enable host networking
    #provider: host
    # enable the Multus network provider
    #provider: multus
    #selectors:
      # The selector keys are required to be `public` and `cluster`.
      # Based on the configuration, the operator will do the following:
      #   1. if only the `public` selector key is specified both public_network and cluster_network Ceph settings will listen on that interface
      #   2. if both `public` and `cluster` selector keys are specified the first one will point to 'public_network' flag and the second one to 'cluster_network'
      #
      # In order to work, each selector value must match a NetworkAttachmentDefinition object in Multus
      #
      #public: public-conf --> NetworkAttachmentDefinition object name in Multus
      #cluster: cluster-conf --> NetworkAttachmentDefinition object name in Multus
    # Provide internet protocol version. IPv6, IPv4 or empty string are valid options. Empty string would mean IPv4
    #ipFamily: "IPv6"
    # Ceph daemons to listen on both IPv4 and Ipv6 networks
    #dualStack: false
    # Enable multiClusterService to export the mon and OSD services to peer cluster.
    # This is useful to support RBD mirroring between two clusters having overlapping CIDRs.
    # Ensure that peer clusters are connected using an MCS API compatible application, like Globalnet Submariner.
    #multiClusterService:
    #  enabled: false

  # enable the crash collector for ceph daemon crash collection
  crashCollector:
    disable: false
    # Uncomment daysToRetain to prune ceph crash entries older than the
    # specified number of days.
    daysToRetain: 30
  # enable log collector, daemons will log on files and rotate
  logCollector:
    enabled: false
    periodicity: daily # one of: hourly, daily, weekly, monthly
    maxLogSize: 500M # SUFFIX may be 'M' or 'G'. Must be at least 1M.
  # automate [data cleanup process](https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/ceph-teardown.md#delete-the-data-on-hosts) in cluster destruction.
  cleanupPolicy:
    # Since cluster cleanup is destructive to data, confirmation is required.
    # To destroy all Rook data on hosts during uninstall, confirmation must be set to "yes-really-destroy-data".
    # This value should only be set when the cluster is about to be deleted. After the confirmation is set,
    # Rook will immediately stop configuring the cluster and only wait for the delete command.
    # If the empty string is set, Rook will not destroy any data on hosts during uninstall.
    confirmation: ""
    # sanitizeDisks represents settings for sanitizing OSD disks on cluster deletion
    sanitizeDisks:
      # method indicates if the entire disk should be sanitized or simply ceph's metadata
      # in both case, re-install is possible
      # possible choices are 'complete' or 'quick' (default)
      method: quick
      # dataSource indicate where to get random bytes from to write on the disk
      # possible choices are 'zero' (default) or 'random'
      # using random sources will consume entropy from the system and will take much more time then the zero source
      dataSource: zero
      # iteration overwrite N times instead of the default (1)
      # takes an integer value
      iteration: 1
    # allowUninstallWithVolumes defines how the uninstall should be performed
    # If set to true, cephCluster deletion does not wait for the PVs to be deleted.
    allowUninstallWithVolumes: false
  # To control where various services will be scheduled by kubernetes, use the placement configuration sections below.
  # The example under 'all' would have all services scheduled on kubernetes nodes labeled with 'role=storage-node' and
  # tolerate taints with a key of 'storage-node'.
  # placement:
  #   all:
  #     nodeAffinity:
  #       requiredDuringSchedulingIgnoredDuringExecution:
  #         nodeSelectorTerms:
  #         - matchExpressions:
  #           - key: role
  #             operator: In
  #             values:
  #             - storage-node
  #     podAffinity:
  #     podAntiAffinity:
  #     topologySpreadConstraints:
  #     tolerations:
  #     - key: storage-node
  #       operator: Exists
  # The above placement information can also be specified for mon, osd, and mgr components
  #   mon:
  # Monitor deployments may contain an anti-affinity rule for avoiding monitor
  # collocation on the same node. This is a required rule when host network is used
  # or when AllowMultiplePerNode is false. Otherwise this anti-affinity rule is a
  # preferred rule with weight: 50.
  #   osd:
  #    prepareosd:
  #    mgr:
  #    cleanup:
  annotations:
  #   all:
  #   mon:
  #   osd:
  #   cleanup:
  #   prepareosd:
  # clusterMetadata annotations will be applied to only `rook-ceph-mon-endpoints` configmap and the `rook-ceph-mon` and `rook-ceph-admin-keyring` secrets.
  # And clusterMetadata annotations will not be merged with `all` annotations.
  #    clusterMetadata:
  #       kubed.appscode.com/sync: "true"
  # If no mgr annotations are set, prometheus scrape annotations will be set by default.
  #   mgr:
  labels:
  #   all:
  #   mon:
  #   osd:
  #   cleanup:
  #   mgr:
  #   prepareosd:
  # monitoring is a list of key-value pairs. It is injected into all the monitoring resources created by operator.
  # These labels can be passed as LabelSelector to Prometheus
  #   monitoring:
  #   crashcollector:
  resources:
  #The requests and limits set here, allow the mgr pod to use half of one CPU core and 1 gigabyte of memory
    mgr:
      limits:
        cpu: "300m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"
    mon:
      limits:
        cpu: "300m"
        memory: "2Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"
    osd:
      limits:
        cpu: "1000m"
        memory: "12Gi"
      requests:
        cpu: "200m"
        memory: "10Gi"
    crashcollector:
      limits:
        cpu: "100m"
        memory: "100Mi"
      requests:
        cpu: "10m"
        memory: "10Mi"
    prepareosd:
      limits:
        cpu: "100m"
        memory: "100Mi"
      requests:
        cpu: "10m"
        memory: "10Mi"
  # The above example requests/limits can also be added to the other components
  #   mon:
  #   osd:
  # For OSD it also is a possible to specify requests/limits based on device class
  #   osd-hdd:
  #   osd-ssd:
  #   osd-nvme:
  #   prepareosd:
  #   mgr-sidecar:
  #   crashcollector:
  #   logcollector:
  #   cleanup:
  # The option to automatically remove OSDs that are out and are safe to destroy.
  removeOSDsIfOutAndSafeToRemove: true
  priorityClassNames:
    #all: rook-ceph-default-priority-class
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
    #crashcollector: rook-ceph-crashcollector-priority-class
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    #deviceFilter:
    config:
      # crushRoot: "custom-root" # specify a non-default root label for the CRUSH map
      # metadataDevice: "md0" # specify a non-rotational storage so ceph-volume will use it as block db device of bluestore.
      # databaseSizeMB: "1024" # uncomment if the disks are smaller than 100 GB
      # journalSizeMB: "1024"  # uncomment if the disks are 20 GB or smaller
      # osdsPerDevice: "1" # this value can be overridden at the node or device level
      encryptedDevice: "true" # the default value for this option is "false"
      deviceClass: ssd
# Individual nodes and their config can be specified as well, but 'useAllNodes' above must be set to false. Then, only the named
# nodes below will be used as storage resources.  Each node's 'name' field should match their 'kubernetes.io/hostname' label.
    nodes:
    - devices:
      - name: sdb
        deviceClass: ssd
      name: node1
      resources: {}
    - devices:
      - name: sdb
        deviceClass: ssd
      name: node2
      resources: {}
    - devices:
      - name: sdb  # sdc is special elasticsearch mount
        deviceClass: ssd
      name: node3
      resources: {}
    - devices:
      - name: sdb
        deviceClass: ssd
      name: node4
      resources: {}
    #   - name: "172.17.4.201"
    #     devices: # specific devices to use for storage can be specified for each node
    #       - name: "sdb"
    #       - name: "nvme01" # multiple osds can be created on high performance devices
    #         config:
    #           osdsPerDevice: "5"
    #       - name: "/dev/disk/by-id/ata-ST4000DM004-XXXX" # devices can be specified using full udev paths
    #     config: # configuration can be specified at the node level which overrides the cluster level config
    #   - name: "172.17.4.301"
    #     deviceFilter: "^sd."
    # when onlyApplyOSDPlacement is false, will merge both placement.All() and placement.osd
    onlyApplyOSDPlacement: false
  # The section for configuring management of daemon disruptions during upgrade or fencing.
  disruptionManagement:
    # If true, the operator will create and manage PodDisruptionBudgets for OSD, Mon, RGW, and MDS daemons. OSD PDBs are managed dynamically
    # via the strategy outlined in the [design](https://github.com/rook/rook/blob/master/design/ceph/ceph-managed-disruptionbudgets.md). The operator will
    # block eviction of OSDs by default and unblock them safely when drains are detected.
    managePodBudgets: true
    # A duration in minutes that determines how long an entire failureDomain like `region/zone/host` will be held in `noout` (in addition to the
    # default DOWN/OUT interval) when it is draining. This is only relevant when  `managePodBudgets` is `true`. The default value is `30` minutes.
    osdMaintenanceTimeout: 30
    # A duration in minutes that the operator will wait for the placement groups to become healthy (active+clean) after a drain was completed and OSDs came back up.
    # Operator will continue with the next drain if the timeout exceeds. It only works if `managePodBudgets` is `true`.
    # No values or 0 means that the operator will wait until the placement groups are healthy before unblocking the next drain.
    pgHealthCheckTimeout: 0

  # healthChecks
  # Valid values for daemons are 'mon', 'osd', 'status'
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    # Change pod liveness probe timing or threshold values. Works for all mon,mgr,osd daemons.
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
    # Change pod startup probe timing or threshold values. Works for all mon,mgr,osd daemons.
    startupProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false

```
</details>

**Logs to submit**:

[Operator-Logs.txt](https://github.com/rook/rook/files/14176247/Operator-Logs.txt)
The Only Logs i could found for the rook-ceph-exporter-node{n} deployments are the following
<details>
  <summary>rook-ceph-exporter-nodes</summary>

```bash
system:0
ownership of '/var/lib/ceph/crash/posted/2023-11-14T09:01:59.190231Z_e4f23ff8-99a2-4c45-8b38-15a1b98e61b4/done' retained as ceph:ceph
ownership of '/var/lib/ceph/crash/posted/2023-11-14T09:01:59.190231Z_e4f23ff8-99a2-4c45-8b38-15a1b98e61b4' retained as ceph:ceph
ownership of '/var/lib/ceph/crash/posted/2023-11-13T09:51:00.308887Z_1483aa47-e996-447b-8978-d32b2d778863/done' retained as ceph:ceph
ownership of '/var/lib/ceph/crash/posted/2024-02-01T11:01:58.637317Z_c9fb05a4-7f33-408c-9e9d-b8b1519affba/done' retained as ceph:ceph
ownership of '/var/lib/ceph/crash/posted/2023-11-14T09:01:59.190231Z_e4f23ff8-99a2-4c45-8b38-15a1b98e61b4/meta' retained as ceph:ceph
ownership of '/run/ceph/ceph-mgr.a.asok' retained as ceph:ceph
ownership of '/run/ceph/ceph-osd.0.asok' retained as ceph:ceph
ownership of '/run/ceph' retained as ceph:ceph
ownership of '/var/lib/ceph/crash/posted/2024-02-01T11:01:58.637317Z_c9fb05a4-7f33-408c-9e9d-b8b1519affba/meta' retained as ceph:ceph
ownership of '/var/log/ceph' retained as ceph:ceph
ownership of '/var/lib/ceph/crash/posted/2024-02-01T11:01:58.637317Z_c9fb05a4-7f33-408c-9e9d-b8b1519affba' retained as ceph:ceph
ownership of '/var/lib/ceph/crash/posted/2023-11-13T09:51:00.308887Z_1483aa47-e996-447b-8978-d32b2d778863/meta' retained as ceph:ceph
ownership of '/var/lib/ceph/crash' retained as ceph:ceph
ownership of '/var/lib/ceph/crash/posted' retained as ceph:ceph
ownership of '/var/lib/ceph/crash/posted/2023-11-13T09:51:00.308887Z_1483aa47-e996-447b-8978-d32b2d778863' retained as ceph:ceph
ownership of '/run/ceph/ceph-mgr.b.asok' retained as ceph:ceph
ownership of '/run/ceph/ceph-client.admin.asok' retained as ceph:ceph
ownership of '/var/log/ceph/core.1' retained as ceph:ceph
ownership of '/var/log/ceph/ceph-volume.log' retained as ceph:ceph
system:0
system:0
2024-02-05T12:14:06.392+0000 7f5b9cb36100 -1 asok(0x560a007f3460) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: failed to bind the UNIX domain socket to '/var/run/ceph/ceph-client.admin.asok': (17) File exists
system:0
```
</details>

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

<details>
  <summary>kubectl rook-ceph health</summary>

```bash
Info: Checking if at least three mon pods are running on different nodes
rook-ceph-mon-d-68f858d8c5-bl5w4	Running	rook-ceph	node2
rook-ceph-mon-k-5d494d9fbc-r9lb2	Running	rook-ceph	node4
rook-ceph-mon-l-7cb7d7d846-2jcrb	Running	rook-ceph	node1

Info: Checking mon quorum and ceph health details
Info: HEALTH_OK

Info: Checking if at least three osd pods are running on different nodes
rook-ceph-osd-0-ff647d459-tzpph	Running	rook-ceph	node3
rook-ceph-osd-1-6f457f98fd-bp8c8	Running	rook-ceph	node1
rook-ceph-osd-2-b98ff4c86-qhcw7	Running	rook-ceph	node2
rook-ceph-osd-3-579b57c457-tpmhq	Running	rook-ceph	node4

Info: Pods that are in 'Running' or `Succeeded` status
csi-cephfsplugin-26nll 	 Running 	 rook-ceph	 node3
csi-cephfsplugin-bff8q 	 Running 	 rook-ceph	 node1
csi-cephfsplugin-mqfql 	 Running 	 rook-ceph	 node2
csi-cephfsplugin-mv99d 	 Running 	 rook-ceph	 node4
csi-cephfsplugin-provisioner-86788ff996-22ffb 	 Running 	 rook-ceph	 node1
csi-cephfsplugin-provisioner-86788ff996-btcvs 	 Running 	 rook-ceph	 node2
csi-rbdplugin-bhgs6 	 Running 	 rook-ceph	 node3
csi-rbdplugin-fb7ct 	 Running 	 rook-ceph	 node2
csi-rbdplugin-lh6s5 	 Running 	 rook-ceph	 node1
csi-rbdplugin-m95xs 	 Running 	 rook-ceph	 node4
csi-rbdplugin-provisioner-7b5494c7fd-jsn58 	 Running 	 rook-ceph	 node4
csi-rbdplugin-provisioner-7b5494c7fd-xfrgh 	 Running 	 rook-ceph	 node2
rook-ceph-crashcollector-node1-b99dd658b-r8qbl 	 Running 	 rook-ceph	 node1
rook-ceph-crashcollector-node2-78976c5985-7vst9 	 Running 	 rook-ceph	 node2
rook-ceph-crashcollector-node3-7b9dcb94c8-7wgwf 	 Running 	 rook-ceph	 node3
rook-ceph-crashcollector-node4-857c7c99c7-zlp6j 	 Running 	 rook-ceph	 node4
rook-ceph-crashcollector-pruner-28452960-fbz26 	 Succeeded 	 rook-ceph	 node3
rook-ceph-exporter-node1-d9fd4c559-npv9n 	 Running 	 rook-ceph	 node1
rook-ceph-exporter-node2-6bd74bdb4d-pqnmk 	 Running 	 rook-ceph	 node2
rook-ceph-exporter-node3-65bfd6bf8f-nlmbw 	 Running 	 rook-ceph	 node3
rook-ceph-exporter-node4-64d7d7fffb-ncz2j 	 Running 	 rook-ceph	 node4
rook-ceph-mds-myfs-a-f89c7fcb6-tkwhb 	 Running 	 rook-ceph	 node2
rook-ceph-mds-myfs-b-6d594fb5c-hjcf5 	 Running 	 rook-ceph	 node1
rook-ceph-mgr-a-6b4b8dd67-94pxl 	 Running 	 rook-ceph	 node3
rook-ceph-mgr-b-6d8d7f48d5-kdm6s 	 Running 	 rook-ceph	 node2
rook-ceph-mon-d-68f858d8c5-bl5w4 	 Running 	 rook-ceph	 node2
rook-ceph-mon-k-5d494d9fbc-r9lb2 	 Running 	 rook-ceph	 node4
rook-ceph-mon-l-7cb7d7d846-2jcrb 	 Running 	 rook-ceph	 node1
rook-ceph-operator-6498c69479-gwm59 	 Running 	 rook-ceph	 node4
rook-ceph-osd-0-ff647d459-tzpph 	 Running 	 rook-ceph	 node3
rook-ceph-osd-1-6f457f98fd-bp8c8 	 Running 	 rook-ceph	 node1
rook-ceph-osd-2-b98ff4c86-qhcw7 	 Running 	 rook-ceph	 node2
rook-ceph-osd-3-579b57c457-tpmhq 	 Running 	 rook-ceph	 node4
rook-ceph-osd-prepare-node1-kw4dz 	 Succeeded 	 rook-ceph	 node1
rook-ceph-osd-prepare-node2-dhfmj 	 Succeeded 	 rook-ceph	 node2
rook-ceph-osd-prepare-node3-x2r5w 	 Succeeded 	 rook-ceph	 node3
rook-ceph-osd-prepare-node4-wwgnv 	 Succeeded 	 rook-ceph	 node4
rook-ceph-rgw-dio-object-store-a-858f64bd9b-tbkfp 	 Running 	 rook-ceph	 node2
rook-ceph-tools-68975479f9-6xw2m 	 Running 	 rook-ceph	 node1
rook-ceph-tools-operator-image-66c687fddc-p855d 	 Running 	 rook-ceph	 node1

Warning: Pods that are 'Not' in 'Running' status

Info: Checking placement group status
Info: 	PgState: active+clean, PgCount: 185

Info: Checking if at least one mgr pod is running
rook-ceph-mgr-a-6b4b8dd67-94pxl	Running	rook-ceph	node3
rook-ceph-mgr-b-6d8d7f48d5-kdm6s	Running	rook-ceph	node2
```
</details>

<details>
  <summary>kubectl rook-ceph ceph status</summary>

```bash
Info: running 'ceph' command with args: [status]
  cluster:
    id:     4aa035b9-ef3e-4f74-bca7-e296981022cb
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum d,k,l (age 4d)
    mgr: b(active, since 17h), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 4 osds: 4 up (since 4d), 4 in (since 4d)
    rgw: 1 daemon active (1 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   12 pools, 185 pgs
    objects: 3.05M objects, 50 GiB
    usage:   154 GiB used, 446 GiB / 600 GiB avail
    pgs:     185 active+clean

  io:
    client:   56 KiB/s rd, 464 KiB/s wr, 2 op/s rd, 33 op/s wr
```
</details>

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 22.04
* Kernel (e.g. `uname -a`): 5.15.0-91-generic 
* Cloud provider or hardware configuration: bare-metal
* Rook version (use `rook version` inside of a Rook Pod): 1.12.6
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.1
* Kubernetes version (use `kubectl version`): 1.28.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): 

```bash
Info: running 'ceph' command with args: [health]
HEALTH_OK
```
