### ISSUE TITLE
OSD not getting created when the node has taints.

### ISSUE THREAD

**Issue by zerowebcorp** [rook/rook#13781]
How do I specify toleration correctly so that the node which has a taint can be used to schedule the OSD pods

This is what I tried.  This is under `.spec.`

```
  placement:
    osd:
      tolerations:
        - key: "node-role.kubernetes.io/ceph"
          operator: "Exists"
          effect: "NoSchedule"
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                    - "1"
                    - "2"
```

I noticed the "Note" on this page https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/#placement-configuration-settings which says `Placement of OSD pods is controlled using the [Storage Class Device Set], not the general placement configuration.`

However, Storage Class Device Set has a VolumeClaimTemplate which is a mandatory field. I am not quite sure how to make use of this. The node has a volume attached to /dev/sdc already. Bit confused on how to set tolerations on OSDs. Help?
