### ISSUE TITLE
Confusing ceph cluster version message

### ISSUE THREAD

**Issue by roadSurfer** [rook/rook#13782]
* Bug Report

**Deviation from expected behavior:**
When attempting to using the `rook-ceph` module from MicroK8s with an external MicroCeph cluster, I started receiving the following error message:
`ceph-file-controller: failed to reconcile refusing to run new crd: local cluster ceph version is higher "17.2.6-0 quincy" than the external cluster "18.2.1-0 reef", this must never happen`
The error message is confusing, 17 is not higher than 18.

I am logging this here as I found the [code in question](https://github.com/rook/rook/blob/04a5fd6ab5fae673f821deea49a2e6ba3b0eef21/pkg/operator/ceph/version/version.go#L313) within this project.

I am not raising an issue about my problem using `CephFS`, it's just about the error message received when attempting to do so.

**Expected behavior:**
The error messages need to be understandable. The parameters passed to the `errors.Errorf` method do not appear match the order of the text.

It may also be that the preceeding `IsSuperior` check is invalid, all depending on if the order of the text or paramaters is correct (I am not expert enough to make that call).

**How to reproduce it (minimal and precise):**
There may be quicker way to do this, but this is how I enouctered the message:
* Install MicroCeph 18.2.0 or 17.2.6 (single node is OK): `snap install microceph`
  * Perform [basic configuration](https://canonical-microceph.readthedocs-hosted.com/en/latest/tutorial/single-node/)
* Install MicroK8s 1.29 (single node is OK): `snap install microk8s --revision=6364 --classic`
* Enable Rook-Ceph: `microk8s enable rook-ceph`
  * [Connect to MicroCeph](https://microk8s.io/docs/how-to-ceph#connect-microceph-to-microk8s-3)
* Attempt to configure CephFS my using a [modified Rook example](https://rook.io/docs/rook/latest-release/Storage-Configuration/Shared-Filesystem-CephFS/filesystem-storage/):
```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
  #Updated for rook-ceph
  namespace: rook-ceph-external 
spec:
  metadataPool:
    replicated:
      # Reduced purely for testing
      size: 1 
  dataPools:
    - replicated:
        size: 1
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
```
* `microk8s.kubectl apply -f the.yaml`
* In time the message will start to appear
 
**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 22.02
* Kernel (e.g. `uname -a`): .5.0-17-generic
* Cloud provider or hardware configuration: N/A
* Rook version (use `rook version` inside of a Rook Pod): v1.11.9
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.0 Reef and 17.2.6 Quincy
* Kubernetes version (use `kubectl version`): v1.29.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): MicroK8s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK
