### ISSUE TITLE
RDMA network support (RoCEv2)

### ISSUE THREAD

**Issue by halohsu** [rook/rook#13911]
I enter the pod of OSD and execute the following command:
```shell
strings /usr/bin/ceph-osd |grep -i rdma
```

I found that Ceph supports RDMA networks.

Then I created the following ConfigMap `rook-ceph-config-override.yaml`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    ms_type = async+rdma
    ms_cluster_type = async+rdma
    ms_async_rdma_device_name = bond0
    ms_async_rdma_polling_us = 0
    ms_async_rdma_local_gid=0000:0000:0000:0000:0000:ffff:6ea8:0138
```

and  restart all osd pod.

Then all osd pod error, because the  role of `ms_async_rdma_local_gid` :

```
//Set local GID for ROCEv2 interface used for CEPH
//The GID corresponding to IPv4 or IPv6 networks
//should be taken from show_gids command output
//This parameter should be uniquely set per OSD server/client
//Not defining this parameter limits the network to RoCEv1
//That means no routing and no congestion control (ECN)
```

I hope to support the RoCEv2 network!
