### ISSUE TITLE
cluster create only one disk per node

### ISSUE THREAD

**Issue by hoanhdo** [rook/rook#1394]
**Bug Report**
What happened:
rook cluster config has 3 disk per node

```
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  versionTag: v0.6.0
  dataDirHostPath: /var/lib/rook
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    storeConfig:
      storeType: bluestore
    nodes:
    - name: "k8s-ceph-2.novalocal"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "vdb"
      - name: "vdc"
      - name: "vdd"
    - name: "k8s-ceph-3.novalocal"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "vdb"
      - name: "vdc"
      - name: "vdd"
    - name: "k8s-ceph-4.novalocal"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "vdb"
      - name: "vdc"
      - name: "vdd"

```

What you expected to happen:
cluster create 9 osd 

**Environment**:
* OS (e.g. from /etc/os-release): centos 7.4
* Kernel (e.g. `uname -a`):   3.10.0-693.5.2.el7.x86_64
* Cloud provider or hardware configuration: 
* Rook version (use `rook version` inside of a Rook Pod): v0.6.0-98.gc1a87fa
* Kubernetes version (use `kubectl version`): 1.8.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
```
root@rook-tools:/# ceph health                                                                                                                                                                                    
HEALTH_OK
root@rook-tools:/# ceph -s    
  cluster:
    id:     180d548e-a0ac-41bf-bf56-94babf9d6a93
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum rook-ceph-mon1,rook-ceph-mon2,rook-ceph-mon0
    mgr: rook-ceph-mgr0(active), standbys: rook-ceph-mgr1
    osd: 3 osds: 3 up, 3 in
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 bytes
    usage:   64515 MB used, 247 GB / 310 GB avail
    pgs:     
 

```

Thanks.
