### ISSUE TITLE
The PV created by rookceph cannot be written to the mounted pod, but the write permission is given

### ISSUE THREAD

**Issue by ywd1988** [rook/rook#13998]
The PV created by rookceph cannot be written to the mounted pod, but the write permission is given
![image](https://github.com/rook/rook/assets/92080991/90442dbf-6051-4dce-bd86-cf25918c5998)
![image](https://github.com/rook/rook/assets/92080991/58559b04-0bc6-41e0-ad14-6a563154d54c)
![image](https://github.com/rook/rook/assets/92080991/c09bc340-20dc-4237-95ae-70c9600bd543)

**Comment by subhamkrai** [comment]
@ywd1988 which pv you are pointing to?

**Comment by ywd1988** [comment]
> @ywd1988你指的是哪个PV？

The PV pod created by rookceph has root privileges but no write privileges

**Comment by Madhu-1** [comment]
@ywd1988 you need to add securityContext to the pod as i mentioned here https://github.com/ceph/ceph-csi/issues/3342#issuecomment-1225854433

**Comment by ywd1988** [comment]
> @ywd1988你需要将 securityContext 添加到 pod 中，正如我在上面提到的[ceph/ceph-csi#3342（评论）](https://github.com/ceph/ceph-csi/issues/3342#issuecomment-1225854433)
Adding a securityContext still doesn't work, it's normal to not mount the PV pod

**Comment by Madhu-1** [comment]
> > @ywd1988你需要将 securityContext 添加到 pod 中，正如我在上面提到的[ceph/ceph-csi#3342（评论）](https://github.com/ceph/ceph-csi/issues/3342#issuecomment-1225854433)
> > Adding a securityContext still doesn't work, it's normal to not mount the PV pod

Please provide the PVC and Pod yaml you are using , what version of Rook/kubernetes you are using?

**Comment by Madhu-1** [comment]
i dont see anything like below or similar to it in above pod yaml, the securityContext is empty above

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: csicephfs-demo-pod
spec:
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  containers:
    - name: web-server
      image: busybox
      command: ["sleep", "60000"]
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
```

**Comment by ywd1988** [comment]
> ```yaml
> fsGroup: 1000
>     runAsUser: 1000
>     runAsGroup: 1000
>     runAsNonRoot: true
> ```

kind: Pod
apiVersion: v1
metadata:
  name: elk-869f4748fb-xzkqq
  generateName: elk-869f4748fb-
  namespace: elk
  labels:
    app: elk
    pod-template-hash: 869f4748fb
  annotations:
    cni.projectcalico.org/containerID: ca5418d4816b8419794caf4d8efb5c027eb45d552828014b3aa2104c788730c1
    cni.projectcalico.org/podIP: 100.84.100.55/32
    cni.projectcalico.org/podIPs: 100.84.100.55/32
    kubesphere.io/creator: admin
    kubesphere.io/imagepullsecrets: '{}'
    kubesphere.io/restartedAt: '2024-04-05T08:13:47.483Z'
    logging.kubesphere.io/logsidecar-config: '{}'
spec:
  volumes:
    - name: volume-cjzk3s
      persistentVolumeClaim:
        claimName: '8'
    - name: kube-api-access-jkv29
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: container-x4es2a
      image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2'
      ports:
        - name: tcp-9200
          containerPort: 9200
          protocol: TCP
        - name: tcp-9300
          containerPort: 9300
          protocol: TCP
      resources: {}
      volumeMounts:
        - name: volume-cjzk3s
          mountPath: /usr/share/elasticsearch/data
        - name: kube-api-access-jkv29
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: ks-master
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority            
This still doesn't work

**Comment by Madhu-1** [comment]
```yaml
spec:
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
```

Can you add fsGroup at the pod level as well?
