### ISSUE TITLE
Allow updating of the OSD device classes

### ISSUE THREAD

**Issue by travisn** [rook/rook#14056]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
OSDs can configure their deviceClass with settings. If this deviceClass is updated, the deviceClass is not updated on the OSDs. An update to the device classes is intentionally not completed to avoid unintentional updates. However, the user may want to assign the device classes after deployment, in which case Rook can support updating the device class. 

To avoid accidental updates, we could consider an additional setting for updating the device class:
```yaml
  storage:
    allowDeviceClassUpdate: true
```

Note the deviceClass is set in the cluster.yaml such as:
```yaml
  storage:
    useAllNodes: true
    useAllDevices: true
    config:
      deviceClass: foo
```

Or if using the `storageClassDeviceSets` (cluster-on-pvc example), it's with this annotation:
```yaml
        volumeClaimTemplates:
          - metadata:
              name: data
              annotations:
                crushDeviceClass: foo
```

For example, see the `ceph osd tree` output with the device class set to "foo":
```
bash-4.4$ ceph osd tree
ID  CLASS  WEIGHT   TYPE NAME          STATUS  REWEIGHT  PRI-AFF
-1         0.11728  root default                                
-3         0.11728      host minikube                           
 0    foo  0.03909          osd.0          up   1.00000  1.00000
 1    foo  0.03909          osd.1          up   1.00000  1.00000
 2    foo  0.03909          osd.2          up   1.00000  1.00000
```

Ceph allows the device class to be updated only if removing the existing device class. If the device class is changed, it would require two commands for each OSD:
```
$ ceph osd crush rm-device-class osd.<id>
$ ceph osd crush set-device-class <deviceClass> osd.<id>
```

**What is use case behind this feature:**
The user may want to assign the device classes after deployment, in which case Rook can support updating the device class.
