### ISSUE TITLE
Object Gateway panel does not work in Ceph Dashboard (KeyError: 'id')

### ISSUE THREAD

**Issue by hemantsonawane95** [rook/rook#14058]
**Is this a bug report or feature request?**
* Bug Report 

**Deviation from expected behavior:**

In ceph dashboard the Object Gateway panel having 500 "Internal Server Error". None of the pages of this panel works. After digging in I managed to gather some logs:
```
rook-ceph-mgr-a-6664b67588-9nbqt mgr debug 2024-04-11T09:09:54.481+0000 7f5181386700  0 [dashboard INFO rgw_client] Found RGW daemon with configuration: host=192.168.101.57, port=8080, ssl=False
rook-ceph-mgr-a-6664b67588-9nbqt mgr debug 2024-04-11T09:09:54.485+0000 7f5181386700  0 [dashboard INFO rgw_client] Found RGW daemon with configuration: host=192.168.101.49, port=8080, ssl=False
rook-ceph-mgr-a-6664b67588-9nbqt mgr debug 2024-04-11T09:09:54.485+0000 7f5181386700  0 [dashboard ERROR exception] Internal Server Error
rook-ceph-mgr-a-6664b67588-9nbqt mgr Traceback (most recent call last):
rook-ceph-mgr-a-6664b67588-9nbqt mgr   File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 47, in dashboard_exception_handler
rook-ceph-mgr-a-6664b67588-9nbqt mgr     return handler(*args, **kwargs)
rook-ceph-mgr-a-6664b67588-9nbqt mgr   File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
rook-ceph-mgr-a-6664b67588-9nbqt mgr     return self.callable(*self.args, **self.kwargs)
rook-ceph-mgr-a-6664b67588-9nbqt mgr   File "/usr/share/ceph/mgr/dashboard/controllers/_base_controller.py", line 263, in inner
rook-ceph-mgr-a-6664b67588-9nbqt mgr     ret = func(*args, **kwargs)
rook-ceph-mgr-a-6664b67588-9nbqt mgr   File "/usr/share/ceph/mgr/dashboard/controllers/rgw.py", line 56, in status
rook-ceph-mgr-a-6664b67588-9nbqt mgr     instance = RgwClient.admin_instance()
rook-ceph-mgr-a-6664b67588-9nbqt mgr   File "/usr/share/ceph/mgr/dashboard/services/rgw_client.py", line 382, in admin_instance
rook-ceph-mgr-a-6664b67588-9nbqt mgr     return RgwClient.instance(daemon_name=daemon_name)
rook-ceph-mgr-a-6664b67588-9nbqt mgr   File "/usr/share/ceph/mgr/dashboard/services/rgw_client.py", line 340, in instance
rook-ceph-mgr-a-6664b67588-9nbqt mgr     RgwClient._daemons = _get_daemons()
rook-ceph-mgr-a-6664b67588-9nbqt mgr   File "/usr/share/ceph/mgr/dashboard/services/rgw_client.py", line 72, in _get_daemons
rook-ceph-mgr-a-6664b67588-9nbqt mgr     daemon = _determine_rgw_addr(daemon_map[key])
rook-ceph-mgr-a-6664b67588-9nbqt mgr   File "/usr/share/ceph/mgr/dashboard/services/rgw_client.py", line 92, in _determine_rgw_addr
rook-ceph-mgr-a-6664b67588-9nbqt mgr     who=name_to_config_section('rgw.' + daemon_info['metadata']['id']),  # noqa E501 #pylint: disable=line-too-long
rook-ceph-mgr-a-6664b67588-9nbqt mgr KeyError: 'id'
rook-ceph-mgr-a-6664b67588-9nbqt mgr debug 2024-04-11T09:09:54.485+0000 7f5181386700  0 [dashboard ERROR request] [::ffff:85.163.56.57:51329] [GET] [500] [0.005s] [admin] [513.0B] /ui-api/rgw/status
rook-ceph-mgr-a-6664b67588-9nbqt mgr debug 2024-04-11T09:09:54.485+0000 7f5181386700  0 [dashboard ERROR request] [b'{"status": "500 Internal Server Error", "detail": "The server encountered an unexpected condition which prevented it from fulfilling the request.", "request_id": "3a084733-be95-4543-839d-4907baa936da"}
``` 
Ther error refers to `KeyError: 'id'`. 

This is happening whenever I click on any tab in Object Gateway panel in Ceph Dashboard. 

<img width="957" alt="Screenshot 2024-04-11 at 11 15 13" src="https://github.com/rook/rook/assets/22501121/7366a640-e2fd-4a13-a5c6-a7a23261649f">

I have also referred issue [#9660](https://github.com/rook/rook/issues/9660) which was already reported earlier and it was looking like similar to mine. But referring it and trying steps explained there did not helped me. Any idea about this issue and possible solution for it ?

**Expected behavior:**

Object Gateway panel should be enabled by default as radosgw is working fine and running. 

**How to reproduce it (minimal and precise):**

* Once ceph cluster is deployed expose ceph dashboard to access it in browser.
* Click on the "Object Gateway" panel and then click on the any options underneath of it for e.g Overview, Gateways, Users, Buckets, Multi-Site
* You will see "Page Not Found" error exactly same as above attached image.

**Comment by travisn** [comment]
@hemantsonawane95 What version of Rook and Ceph are you using?

**Comment by hemantsonawane95** [comment]
@travisn 
`ceph version 18.2.2 (531c0d11a1c5d39fbfe6aa8a521f023abf3bf3e2) reef (stable)`
`rook-version: v1.13.7`

**Comment by rkachach** [comment]
@hemantsonawane95 please, can you share the specs you used to create our object store?

**Comment by hemantsonawane95** [comment]
@travisn I used default 

object store created in rook-ceph namespace
```
apiVersion: v1
items:
- apiVersion: ceph.rook.io/v1
  kind: CephObjectStore
  metadata:
    annotations:
      meta.helm.sh/release-name: rook-ceph-rook-ceph-cluster
      meta.helm.sh/release-namespace: rook-ceph
    creationTimestamp: "2024-04-03T09:52:02Z"
    finalizers:
    - cephobjectstore.ceph.rook.io
    generation: 2
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.toolkit.fluxcd.io/name: rook-ceph-cluster
      helm.toolkit.fluxcd.io/namespace: rook-ceph
    name: ceph-objectstore
    namespace: rook-ceph
    resourceVersion: "1427260"
    uid: 9827a2d3-b851-41c7-a7e6-2814a25572f0
  spec:
    dataPool:
      erasureCoded:
        codingChunks: 0
        dataChunks: 0
      failureDomain: host
      mirroring: {}
      quotas: {}
      replicated:
        size: 3
      statusCheck:
        mirror: {}
    gateway:
      instances: 2
      placement: {}
      port: 8080
      priorityClassName: system-cluster-critical
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 1Gi
    healthCheck: {}
    metadataPool:
      erasureCoded:
        codingChunks: 0
        dataChunks: 0
      failureDomain: host
      mirroring: {}
      quotas: {}
      replicated:
        size: 3
      statusCheck:
        mirror: {}
    preservePoolsOnDelete: true
    zone:
      name: ""
  status:
    endpoints:
      insecure:
      - http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc:8080
      secure: []
    info:
      endpoint: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc:8080
    observedGeneration: 2
    phase: Ready
kind: List
metadata:
  resourceVersion: ""
  ```

config:

```
    # ceph object storage configuration
    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPool:
            failureDomain: host
            replicated:
              size: 3
          preservePoolsOnDelete: true
          gateway:
            port: 8080
            resources:
              limits:
                cpu: "2000m"
                memory: "2Gi"
              requests:
                cpu: "1000m"
                memory: "1Gi"
            # securePort: 443
            # sslCertificateRef:
            instances: 2
            priorityClassName: system-cluster-critical
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Delete
```
