### ISSUE TITLE
Ceph Cluster Creation Failed on GKE

### ISSUE THREAD

**Issue by Dev-Destructor** [rook/rook#14071]
I have been trying to deploy rook-ceph for the past 2 days but every time I am getting the same issue. I have tried with both the official rook-ceph helm chart and also the official example files. This is the first time I am trying to deploy  rook-ceph cluster, what is going wrong?

**Is this a bug report or feature request?**
* Bug Report

**How to reproduce it (minimal and precise):**

1. Create a GKE Cluster (My Specs:- e2-standard-4, pd-standard 100GB, 3 nodes, k8s version 1.29)
2. Use this [repo](https://github.com/rook/rook/blob/release-1.14/deploy/examples)
3. deploy crds.yaml, common.yaml
5. Add FlexVolume Directory path as env in the operator.yaml. more info [here](https://rook.io/docs/rook/v1.0/flexvolume.html#google-kubernetes-engine-gke)
6. deploy operator.yaml
7. deploy cluster.yaml

**Logs to submit**:
```log
2024-04-15 06:45:52.677022 E | op-mon: failed to schedule mon "a". failed to schedule canary pod(s)
2024-04-15 06:45:53.241544 I | op-mon: waiting for canary pod creation rook-ceph-mon-b-canary
2024-04-15 06:45:53.241575 E | op-mon: failed to schedule mon "b". failed to schedule canary pod(s)
2024-04-15 06:45:53.244743 I | op-mon: waiting for canary pod creation rook-ceph-mon-c-canary
2024-04-15 06:45:53.244765 E | op-mon: failed to schedule mon "c". failed to schedule canary pod(s)
2024-04-15 06:45:53.250055 I | op-mon: cleaning up canary monitor deployment "rook-ceph-mon-a-canary"
2024-04-15 06:45:53.256693 I | op-mon: cleaning up canary monitor deployment "rook-ceph-mon-b-canary"
2024-04-15 06:45:53.285692 I | op-mon: cleaning up canary monitor deployment "rook-ceph-mon-c-canary"
2024-04-15 06:45:53.418963 E | ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph monitors: failed to assign pods to mons: failed to schedule mons
2024-04-15 06:45:53.424397 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2024-04-15 06:45:53.455441 I | ceph-spec: parsing mon endpoints: 
2024-04-15 06:45:53.455503 W | ceph-spec: ignoring invalid monitor 
2024-04-15 06:45:53.577042 I | ceph-spec: detecting the ceph image version for image quay.io/ceph/ceph:v18.2.2...
2024-04-15 06:46:36.985671 I | ceph-spec: detected ceph image version: "18.2.2-0 reef"
2024-04-15 06:46:36.985715 I | ceph-cluster-controller: validating ceph version from provided image
2024-04-15 06:46:37.002087 I | ceph-spec: parsing mon endpoints: 
2024-04-15 06:46:37.002109 W | ceph-spec: ignoring invalid monitor 
2024-04-15 06:46:37.006846 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2024-04-15 06:46:37.007023 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2024-04-15 06:46:37.132615 E | ceph-cluster-controller: failed to get ceph daemons versions, this typically happens during the first cluster initialization. failed to run 'ceph versions'. . unable to get monitor info from DNS SRV with service name: ceph-mon
2024-04-15T06:46:37.129+0000 7813faf02700 -1 failed for service _ceph-mon._tcp
2024-04-15T06:46:37.129+0000 7813faf02700 -1 monclient: get_monmap_and_config cannon
```
```cli
$ kubectl rook-ceph ceph status
Info: running 'ceph' command with args: [status]
unable to get monitor info from DNS SRV with service name: ceph-mon
2024-04-15T07:03:36.281+0000 7f5496385700 -1 failed for service _ceph-mon._tcp
2024-04-15T07:03:36.281+0000 7f5496385700 -1 monclient: get_monmap_and_config cannot identify monitors to contact
[errno 2] RADOS object not found (error connecting to the cluster)
Error: . failed to run command. command terminated with exit code 1
```

```cli
$kubectl get cephcluster -A
NAMESPACE   NAME        DATADIRHOSTPATH   MONCOUNT   AGE   PHASE         MESSAGE                                                                                                           HEALTH   EXTERNAL   FSID
rook-ceph   rook-ceph   /var/lib/rook     3          21m   Progressing   failed to create cluster: failed to start ceph monitors: failed to assign pods to mons: failed to schedule mons 
```

**Environment**:
* OS (e.g. from /etc/os-release): cos-containerd
* Cloud provider or hardware configuration: e2-standard-4 with pd-standard 100GB
* Rook version (use `rook version` inside of a Rook Pod): 1.14.0
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.2
* Kubernetes version (use `kubectl version`): 1.28.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE

**Comment by travisn** [comment]
```
2024-04-15 06:45:53.418963 E | ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": 
failed to configure local ceph cluster: failed to create cluster: 
failed to start ceph monitors: failed to assign pods to mons: failed to schedule mons
```
Do you have at least three nodes in the cluster? The mons could not be scheduled as needed on separate nodes. Does `kubectl describe` for the mon-canary deployments/replicasets show for the reason it was not schedulable?

Note that for GKE you'll want to follow the [cluster-on-pvc example](https://rook.io/docs/rook/latest/CRDs/Cluster/pvc-cluster/). The default example is for AWS, you just need to modify the storage classes for GKE.

**Comment by Dev-Destructor** [comment]
Using cluster-on-pvc seems to resolve the previous issue but still the pgs are inactive

cluster.yaml
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
  storage:
    storageClassDeviceSets:
      - name: px-set1
        count: 3
        portable: false
        encrypted: false
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 100Gi
              storageClassName: standard
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
    onlyApplyOSDPlacement: false
  ```

fs.yaml
```yaml
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: px-ceph-fs
  namespace: rook-ceph # namespace:cluster
spec:
  metadataPool:
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      compression_mode: none
  dataPools:
    - name: replicated
      failureDomain: host
      replicated:
        size: 3
        requireSafeReplicaSize: true
      parameters:
        compression_mode: none
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 2
    activeStandby: true
---
# create default csi subvolume group
apiVersion: ceph.rook.io/v1
kind: CephFilesystemSubVolumeGroup
metadata:
  name: px-ceph-fs-csi
  namespace: rook-ceph
spec:
  name: csi
  filesystemName: px-ceph-fs
  pinning:
    distributed: 1
```

these are the configuration I have used.

*** Output:-
```cli
bash-4.4$ ceph status
  cluster:
    id:     43898019-dc9e-42b5-8298-989521715781
    health: HEALTH_WARN
            1 MDSs report slow metadata IOs
            1 filesystem is online with fewer MDS than max_mds
            Reduced data availability: 49 pgs inactive
            Degraded data redundancy: 49 pgs undersized
 
  services:
    mon: 3 daemons, quorum a,b,c (age 3h)
    mgr: a(active, since 3h)
    mds: 1/1 daemons up, 3 standby
    osd: 3 osds: 3 up (since 3h), 3 in (since 3h)
 
  data:
    volumes: 1/1 healthy
    pools:   3 pools, 49 pgs
    objects: 0 objects, 0 B
    usage:   79 MiB used, 300 GiB / 300 GiB avail
    pgs:     100.000% pgs not active
             49 undersized+peered
 
bash-4.4$ ceph osd tree 
ID  CLASS  WEIGHT   TYPE NAME                                                      STATUS  REWEIGHT  PRI-AFF
-1         0.29306  root default                                                                            
-5         0.29306      region asia-south2                                                                  
-4         0.29306          zone asia-south2-a                                                              
-3         0.29306              host gke-px-ceph-test1-default-pool-616e1dd7-m6qs                           
 0    hdd  0.09769                  osd.0                                              up   1.00000  1.00000
 1    hdd  0.09769                  osd.1                                              up   1.00000  1.00000
 2    hdd  0.09769                  osd.2                                              up   1.00000  1.00000
bash-4.4$ ceph osd lspools
1 .mgr
2 px-ceph-fs-metadata
3 px-ceph-fs-replicated
```

**Comment by travisn** [comment]
The issue is that the OSDs all ended up on the same node, which means that replica 3 cannot be satisfied with `failureDomain: host` on all the pools. There are two possible solutions:
1. Change the storageClassDeviceSets in your CephCluster CR for the OSDs to have antiaffinity or use Topology spread constraints to spread the OSDs across all three nodes, or:
2. Wherever a pool is defined (CephBlockPool, CephFilesystem metadata and data pools, or CephObjectStore metadata and data pools), set `failureDomain: osd`. This allows replicas to be placed on different OSDs on the same host.

With GKE it's also recommended to set `portable: true` for the device sets, so OSDs can migrate between nodes during maintenance.

For GKE is probably preferred for the latter option `failureDomain: osd` since OSDs are portable.

**Comment by Dev-Destructor** [comment]
Hey, this process also worked, thank you very much not sure if I could have solved it on my own. Now the cluster is in OK status and the FS and StorageClass have also been created. But when I tried to attach a PVC with a pod the PVC is on a pending state 

```cli
$ kubectl describe pvc 
Name:          cephfs-test-pvc
Namespace:     default
StorageClass:  rook-cephfs
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
               volume.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       cephfs-test-pod
Events:
  Type    Reason                Age                   From                         Message
  ----    ------                ----                  ----                         -------
  Normal  ExternalProvisioning  103s (x102 over 26m)  persistentvolume-controller  Waiting for a volume to be created either by the external provisioner 'rook-ceph.cephfs.csi.ceph.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
```

I tried to find the issue around searching for leads and then I found out no `csi-cephfsplugin-xxxx` pod is running in the cluster.

```cli
$ kubectl get pods -n rook-ceph
NAME                                                              READY   STATUS      RESTARTS   AGE
rook-ceph-crashcollector-4f666562ea6e648d39246688a8255fba-v948p   1/1     Running     0          45m
rook-ceph-crashcollector-76cd90487a5b9b67adaf9b96b0efae3d-rz249   1/1     Running     0          45m
rook-ceph-crashcollector-f65d8a9e880a37b2615adc710700f62e-fx2s6   1/1     Running     0          45m
rook-ceph-exporter-gke-px-ceph-test1-default-pool-3edc63f8kmrks   1/1     Running     0          45m
rook-ceph-exporter-gke-px-ceph-test1-default-pool-3edc63f8ltrjn   1/1     Running     0          45m
rook-ceph-exporter-gke-px-ceph-test1-default-pool-3edc63f8sh8bd   1/1     Running     0          45m
rook-ceph-mds-px-ceph-fs-a-679dc78dfb-xj2r6                       1/1     Running     0          43m
rook-ceph-mds-px-ceph-fs-b-7d45474549-zzndv                       1/1     Running     0          43m
rook-ceph-mds-px-ceph-fs-c-67dcd9958b-5cdb9                       1/1     Running     0          43m
rook-ceph-mds-px-ceph-fs-d-78c75876f5-m8r2v                       1/1     Running     0          43m
rook-ceph-mgr-a-6c68b464b4-hs7g6                                  1/1     Running     0          45m
rook-ceph-mon-a-54544cfb8f-7bwks                                  1/1     Running     0          47m
rook-ceph-mon-b-5595548848-tkddf                                  1/1     Running     0          47m
rook-ceph-mon-c-86b7457c5c-qwqsd                                  1/1     Running     0          46m
rook-ceph-operator-58dfb477c8-6bbrr                               1/1     Running     0          52m
rook-ceph-osd-0-5c4f56975-k8mtz                                   1/1     Running     0          45m
rook-ceph-osd-1-84f78b867-d8jqk                                   1/1     Running     0          45m
rook-ceph-osd-2-5689b8c5c5-8wld8                                  1/1     Running     0          44m
rook-ceph-osd-prepare-px-set1-data-0xhcdt-lwz7h                   0/1     Completed   0          45m
rook-ceph-osd-prepare-px-set1-data-18rxjx-jtx5s                   0/1     Completed   0          45m
rook-ceph-osd-prepare-px-set1-data-29jmqn-hsnsk                   0/1     Completed   0          45m
rook-ceph-tools-58c6857df4-4gzn5                                  1/1     Running     0          44m
```

I am not sure why and is the reason causing my PVC not to provision PV or not

These are the resource running 
```cli
$ kubectl get cephcluster -A
NAMESPACE   NAME        DATADIRHOSTPATH   MONCOUNT   AGE   PHASE   MESSAGE                        HEALTH      EXTERNAL   FSID
rook-ceph   rook-ceph   /var/lib/rook     3          47m   Ready   Cluster created successfully   HEALTH_OK              4799fc8b-4324-477d-90d3-e9064269924f
$ kubectl get cephfilesystem -A
NAMESPACE   NAME         ACTIVEMDS   AGE   PHASE
rook-ceph   px-ceph-fs   2           43m   Ready
$ kubectl get cephfilesystemsubvolumegroup -A
NAMESPACE   NAME             PHASE   AGE
rook-ceph   px-ceph-fs-csi   Ready   43m
$ kubectl get csidrivers
NAME                            ATTACHREQUIRED   PODINFOONMOUNT   STORAGECAPACITY   TOKENREQUESTS   REQUIRESREPUBLISH   MODES        AGE
pd.csi.storage.gke.io           true             false            false             <unset>         false               Persistent   146m
rook-ceph.cephfs.csi.ceph.com   true             false            false             <unset>         false               Persistent   47m
rook-ceph.rbd.csi.ceph.com      true             false            false             <unset>         false               Persistent   47m
$ kubectl get storageclass 
NAME                     PROVISIONER                     RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
premium-rwo              pd.csi.storage.gke.io           Delete          WaitForFirstConsumer   true                   146m
rook-cephfs              rook-ceph.cephfs.csi.ceph.com   Delete          Immediate              true                   27m
standard                 kubernetes.io/gce-pd            Delete          Immediate              true                   146m
standard-rwo (default)   pd.csi.storage.gke.io           Delete          WaitForFirstConsumer   true  
```

These are the ceph resources

```cli
bash-4.4$ ceph status
  cluster:
    id:     4799fc8b-4324-477d-90d3-e9064269924f
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 39m)
    mgr: a(active, since 39m)
    mds: 2/2 daemons up, 2 hot standby
    osd: 3 osds: 3 up (since 38m), 3 in (since 38m)
 
  data:
    volumes: 1/1 healthy
    pools:   3 pools, 49 pgs
    objects: 48 objects, 621 KiB
    usage:   135 MiB used, 300 GiB / 300 GiB avail
    pgs:     49 active+clean
 
  io:
    client:   2.5 KiB/s rd, 4 op/s rd, 0 op/s wr
 
bash-4.4$ ceph fs ls
name: px-ceph-fs, metadata pool: px-ceph-fs-metadata, data pools: [px-ceph-fs-replicated ]
bash-4.4$ ceph osd lspools
1 .mgr
2 px-ceph-fs-metadata
3 px-ceph-fs-replicated
bash-4.4$ ceph fs subvolumegroup ls px-ceph-fs    
[
    {
        "name": "csi"
    }
]
```

This is the example pod and PVC I am trying to create
```cli
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-test-pod
spec:
  containers:
    - name: cephfs-test-container
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: cephfs-test-volume
          mountPath: /mnt/cephfs
  volumes:
    - name: cephfs-test-volume
      persistentVolumeClaim:
        claimName: cephfs-test-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-test-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
```

**Comment by travisn** [comment]
It seems you have disabled the settings in operator.yaml to deploy the CSI driver. The drivers are enabled by default with [these settings](https://github.com/rook/rook/blob/release-1.14/deploy/examples/operator.yaml#L32-L35). Do you see those settings in your cluster?

That article you linked for setting the flex volume is outdated and does not apply to the CSI driver.

**Comment by Dev-Destructor** [comment]
I am using the official helm, I checked the default values there and I checked both the CephFS and CephRbd CSI Drivers are enabled by default. 

Now after digging into the issue a little more, I found out the csi driver pods are not scheduling due to `Warning  FailedCreate  86s (x17 over 6m54s)  replicaset-controller  Error creating: insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]`

I used the example cluster-on-pvc.yaml from [here](https://github.com/rook/rook/blob/HEAD/deploy/examples/cluster-on-pvc.yaml), and what I found out is setting the following 
```yaml
  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
```

is causing `rook-ceph-csi-detect-version-xxxx` pods initialization and termination repeatedly and commenting this out is causing the csi driver pods not to schedule. 

some more logs:-

```cli
$ kubectl describe replicaset csi-cephfsplugin-provisioner-6d5876cc9d -n rook-ceph
Name:           csi-cephfsplugin-provisioner-6d5876cc9d
Namespace:      rook-ceph
Selector:       app=csi-cephfsplugin-provisioner,pod-template-hash=6d5876cc9d
Labels:         app=csi-cephfsplugin-provisioner
                contains=csi-cephfsplugin-metrics
                pod-template-hash=6d5876cc9d
Annotations:    banzaicloud.com/last-applied:
                  UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWzsmFFv2zYXhv8L0Yt+gKhYbtKkAnQR1O43Y4tjJENviqBgqGObM0Wyh5QaL9B/H0jKsZw4bbIVWzDsIohFHR4evu...
                deployment.kubernetes.io/desired-replicas: 2
                deployment.kubernetes.io/max-replicas: 2
                deployment.kubernetes.io/revision: 1
Controlled By:  Deployment/csi-cephfsplugin-provisioner
Replicas:       0 current / 2 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=csi-cephfsplugin-provisioner
                    contains=csi-cephfsplugin-metrics
                    pod-template-hash=6d5876cc9d
  Service Account:  rook-csi-cephfs-provisioner-sa
  Containers:
   csi-attacher:
    Image:      registry.k8s.io/sig-storage/csi-attacher:v4.5.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --v=0
      --csi-address=$(ADDRESS)
      --leader-election=true
      --timeout=2m30s
      --leader-election-namespace=rook-ceph
      --leader-election-lease-duration=2m17s
      --leader-election-renew-deadline=1m47s
      --leader-election-retry-period=26s
    Limits:
      memory:  256Mi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      ADDRESS:  /csi/csi-provisioner.sock
    Mounts:
      /csi from socket-dir (rw)
   csi-snapshotter:
    Image:      registry.k8s.io/sig-storage/csi-snapshotter:v7.0.1
    Port:       <none>
    Host Port:  <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=0
      --timeout=2m30s
      --leader-election=true
      --leader-election-namespace=rook-ceph
      --leader-election-lease-duration=2m17s
      --leader-election-renew-deadline=1m47s
      --leader-election-retry-period=26s
      --extra-create-metadata=true
    Limits:
      memory:  256Mi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      ADDRESS:  unix:///csi/csi-provisioner.sock
    Mounts:
      /csi from socket-dir (rw)
   csi-resizer:
    Image:      registry.k8s.io/sig-storage/csi-resizer:v1.10.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=0
      --timeout=2m30s
      --leader-election=true
      --leader-election-namespace=rook-ceph
      --leader-election-lease-duration=2m17s
      --leader-election-renew-deadline=1m47s
      --leader-election-retry-period=26s
      --handle-volume-inuse-error=false
      --feature-gates=RecoverVolumeExpansionFailure=true
    Limits:
      memory:  256Mi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      ADDRESS:  unix:///csi/csi-provisioner.sock
    Mounts:
      /csi from socket-dir (rw)
   csi-provisioner:
    Image:      registry.k8s.io/sig-storage/csi-provisioner:v4.0.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=0
      --timeout=2m30s
      --retry-interval-start=500ms
      --leader-election=true
      --leader-election-namespace=rook-ceph
      --feature-gates=HonorPVReclaimPolicy=true
      --prevent-volume-mode-conversion=true
      --leader-election-lease-duration=2m17s
      --leader-election-renew-deadline=1m47s
      --leader-election-retry-period=26s
      --extra-create-metadata=true
    Limits:
      memory:  256Mi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      ADDRESS:  unix:///csi/csi-provisioner.sock
    Mounts:
      /csi from socket-dir (rw)
   csi-cephfsplugin:
    Image:      quay.io/cephcsi/cephcsi:v3.11.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --nodeid=$(NODE_ID)
      --type=cephfs
      --endpoint=$(CSI_ENDPOINT)
      --v=0
      --controllerserver=true
      --drivername=rook-ceph.cephfs.csi.ceph.com
      --pidlimit=-1
      --forcecephkernelclient=true
    Limits:
      memory:  1Gi
    Requests:
      cpu:     250m
      memory:  512Mi
    Environment:
      POD_IP:          (v1:status.podIP)
      NODE_ID:         (v1:spec.nodeName)
      POD_NAMESPACE:   (v1:metadata.namespace)
      CSI_ENDPOINT:   unix:///csi/csi-provisioner.sock
    Mounts:
      /csi from socket-dir (rw)
      /dev from host-dev (rw)
      /etc/ceph-csi-config/ from ceph-csi-config (rw)
      /lib/modules from lib-modules (ro)
      /sys from host-sys (rw)
      /tmp/csi/keys from keys-tmp-dir (rw)
  Volumes:
   socket-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
   host-sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  
   lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
   host-dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  
   ceph-csi-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rook-ceph-csi-config
    Optional:  false
   keys-tmp-dir:
    Type:               EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:             Memory
    SizeLimit:          <unset>
  Priority Class Name:  system-cluster-critical
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                   From                   Message
  ----     ------        ----                  ----                   -------
  Warning  FailedCreate  86s (x17 over 6m54s)  replicaset-controller  Error creating: insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]
```

after commenting out priorityclassnames 

```cli
$ kubectl get pods -n rook-ceph -w
NAME                                  READY   STATUS     RESTARTS   AGE
rook-ceph-csi-detect-version-h2m5p    0/1     Init:0/1   0          0s
rook-ceph-operator-58dfb477c8-rrxtm   1/1     Running    0          3h13m
rook-ceph-tools-58c6857df4-hbfll      1/1     Running    0          3h7m
rook-ceph-csi-detect-version-h2m5p    0/1     Init:0/1   0          1s
rook-ceph-csi-detect-version-h2m5p    0/1     PodInitializing   0          2s
rook-ceph-csi-detect-version-h2m5p    0/1     PodInitializing   0          2s
rook-ceph-csi-detect-version-h2m5p    0/1     Terminating       0          2s
rook-ceph-csi-detect-version-h2m5p    0/1     Terminating       0          3s
rook-ceph-csi-detect-version-h2m5p    0/1     Terminating       0          3s
rook-ceph-csi-detect-version-h2m5p    0/1     Terminating       0          4s
rook-ceph-csi-detect-version-h2m5p    0/1     Terminating       0          4s
rook-ceph-csi-detect-version-h2m5p    0/1     Terminating       0          4s
rook-ceph-detect-version-687q5        0/1     Pending           0          0s
rook-ceph-detect-version-687q5        0/1     Pending           0          0s
rook-ceph-detect-version-687q5        0/1     Init:0/1          0          0s
rook-ceph-detect-version-687q5        0/1     PodInitializing   0          1s
rook-ceph-detect-version-687q5        0/1     PodInitializing   0          1s
rook-ceph-detect-version-687q5        0/1     Terminating       0          1s
rook-ceph-detect-version-687q5        0/1     Terminating       0          2s
rook-ceph-detect-version-687q5        0/1     Terminating       0          2s
rook-ceph-detect-version-687q5        0/1     Terminating       0          3s
rook-ceph-detect-version-687q5        0/1     Terminating       0          3s
rook-ceph-detect-version-687q5        0/1     Terminating       0          3s
rook-ceph-detect-version-t4xml        0/1     Pending           0          0s
rook-ceph-detect-version-t4xml        0/1     Pending           0          0s
rook-ceph-detect-version-t4xml        0/1     Init:0/1          0          0s
rook-ceph-detect-version-t4xml        0/1     Init:0/1          0          0s
rook-ceph-detect-version-t4xml        0/1     PodInitializing   0          1s
rook-ceph-detect-version-t4xml        0/1     PodInitializing   0          1s
rook-ceph-detect-version-t4xml        0/1     Terminating       0          2s
rook-ceph-detect-version-t4xml        0/1     Terminating       0          2s
rook-ceph-detect-version-t4xml        0/1     Terminating       0          2s
rook-ceph-detect-version-t4xml        0/1     Terminating       0          3s
rook-ceph-detect-version-t4xml        0/1     Terminating       0          3s
rook-ceph-detect-version-t4xml        0/1     Terminating       0          3s
```

my cluster.yaml configuration 

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi

  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mgr:
    count: 2
    allowMultiplePerNode: false
    modules:
      - name: rook
        enabled: true
  dashboard:
    enabled: true
  crashCollector:
    disable: false
  logCollector:
    enabled: true
    periodicity: daily
    maxLogSize: 500M
  storage:
    storageClassDeviceSets:
      - name: px-storage-class-device-set-1
        count: 3
        portable: true
        tuneDeviceClass: true
        tuneFastDeviceClass: false
        encrypted: false
        placement:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd
        preparePlacement:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd-prepare
                  topologyKey: kubernetes.io/hostname
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd-prepare
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 100Gi
              storageClassName: standard
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
    onlyApplyOSDPlacement: false
  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
```
