### ISSUE TITLE
Support block.wal in not-PVC deployment

### ISSUE THREAD

**Issue by chenyuanrun** [rook/rook#14142]
Rook seems support block.wal only if the osd is running under PVC, It would be better if we can use block.wal for high speed devices in host.

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
Have you tried with the `metadataDevice` setting? This 
```yaml
  storage:
    config:
      metadataDevice: nvme01
```
The `config` section can also be under the nodes, like this:
```yaml
  storage:
    nodes:
    - name: node1
      config:
        metadataDevice: nvme01
```
This will pass the device to the `ceph-volume` arg `--db-devices`. IIRC ceph will also put the wal on this metadata device as well. But if you really want the wal on a separate device, you're correct I don't see that option. 
@satoru-takeuchi Is that correct?
