### ISSUE TITLE
Streamlining Consuming the Shared Filesystem across namespaces

### ISSUE THREAD

**Issue by zalsader** [rook/rook#14254]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The [current instructions for sharing a filesystem across namespaces](https://rook.io/docs/rook/latest-release/Storage-Configuration/Shared-Filesystem-CephFS/filesystem-storage/#consume-the-shared-filesystem-across-namespaces) are complicated. Sure, it works, but it would be nice if there was some way to streamline the process. Similar to how we create [pvcs from snapshot data sources](https://github.com/rook/rook/blob/release-1.14/deploy/examples/csi/cephfs/pvc-restore.yaml) or [clone volumes](https://github.com/rook/rook/blob/release-1.14/deploy/examples/csi/cephfs/pvc-clone.yaml), we could have a data source for sharing the pvc:

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc-shared
spec:
  storageClassName: rook-cephfs
  dataSource:
    name: cephfs-pvc-shared
    kind: SharedPersistentVolumeClaim
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```

We could brainstorm the details if you'd like. I'm happy to join a call and work on defining this based on what k8s allows.

**What is a use case behind this feature:**
sharing a cephfs-based ccache across teams using different namespaces.
