### ISSUE TITLE
Compression causes csi-cephfs-plugin to stop functioning.

### ISSUE THREAD

**Issue by DeprecatedLuke** [rook/rook#14316]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Enabling compression causes csi-ceph-fs plugin to break and error with:
```
rpc error: code = Internal desc = an error (exit status 32) occurred while running mount args: [-t ceph 10.223.33.110:3300,10.223.112.36:3300,10.223.158.198:3300:/volumes/csi/csi-vol-e4fa3d47-0e75-4243-b0ca-232c95fe7253/6e5db3a9-0e99-4bd9-bd82-a097c511b4f6 /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/9a5292d045c5bc10d730fefa518ca5cabb3ab07b4825d9ee71def9783b3a3636/globalmount -o name=csi-cephfs-node,secretfile=/tmp/csi/keys/keyfile-923333010,mds_namespace=ceph-filesystem,_netdev] stderr: unable to get monitor info from DNS SRV with service name: ceph-mon
2024-06-09T06:27:56.563+0000 7f8afb7b9140 -1 failed for service _ceph-mon._tcp
```

**Expected behavior:**

**How to reproduce it (minimal and precise):**
Not really sure. I don't have another cluster like this where I can freely test this configuration.

3 nodes 6 osds
initialize the cluster with `compression: disabled`, helm upgrade to `compression: enabled`
csi-cephfs-plugin will no longer be able to mount volumes.

**File(s) to submit**:
```
rook-ceph-cluster:
  toolbox:
    enabled: false
  cephClusterSpec:
    network:
      connections:
        compression:
          enabled: false # culprit
    dashboard:
      enabled: false
    crashCollector:
      disable: false
    storage:
      useAllDevices: false
      useAllNodes: false
      nodes:
        - name: "w01"
          devices:
            - name: "sda"
            - name: "sdb"
        - name: "w02"
          devices:
            - name: "sda"
            - name: "sdb"
        - name: "w03"
          devices:
            - name: "sda"
            - name: "sdb"
  cephFileSystems:
    - name: ceph-filesystem
      spec:
        metadataPool:
          replicated:
            size: 2
        dataPools:
          - failureDomain: host
            replicated:
              size: 2
            name: data0
        metadataServer:
          activeCount: 1
          activeStandby: true
          resources:
            limits:
              memory: "4Gi"
            requests:
              cpu: "1000m"
              memory: "4Gi"
          priorityClassName: system-cluster-critical
      storageClass:
        enabled: true
        isDefault: false
        name: ceph-filesystem
        pool: data0
        reclaimPolicy: Delete
        allowVolumeExpansion: true
        volumeBindingMode: "Immediate"
        mountOptions: [ ]
        parameters:
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
          csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/fstype: ext4
```

**Logs to submit**:

- There are zero logs about mds or csi errors. (Took forever to figure out the issue!)

**Cluster Status to submit**:

Everything is healthy.
ceph -s
```
  cluster:
    id:     096ad7e8-924d-4975-a00f-08ea471b5198
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 11m)
    mgr: a(active, since 8m), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 6 osds: 6 up (since 8m), 6 in (since 7d)
    rgw: 2 daemons active (2 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   14 pools, 140 pgs
    objects: 23.85k objects, 84 GiB
    usage:   162 GiB used, 5.1 TiB / 5.2 TiB avail
    pgs:     140 active+clean

  io:
    client:   21 KiB/s rd, 473 KiB/s wr, 3 op/s rd, 73 op/s wr
```

**Environment**:
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
Linux w01 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux

rook-ceph version: latest helm chart release
ceph version 18.2.2 (531c0d11a1c5d39fbfe6aa8a521f023abf3bf3e2) reef (stable)
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1+k3s1

CNI: Calico latest helm chart release.

**Things I've tried to resolve issues:**
- Rebooting all nodes.
- Clearing leases (was actually another issue caused by abrupt node dropout, but this is honestly expected behavior).
- csi.enableCephfsDriver = false, csi.enableCephfsDriver = true helm chart upgrades.
- Disabling and enabling calico wireguard encryption.

**Additional notes:**
Network connectivity was not an issue, mons were reachable from pods.

EDIT:
RBD and Object Storage continued to work as expected.
