### ISSUE TITLE
Deleting ZoneGroup etc created using CRD does not actually delete ZoneGroup

### ISSUE THREAD

**Issue by panteparak** [rook/rook#14343]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When deleting some ceph objects via CRD the underlying object is still preset as seen in this shell output

```
bash-4.4$ radosgw-admin zonegroup list
{
    "default_info": "ca1b273f-04d3-48a0-8de2-262a840e8a3a",
    "zonegroups": [
        "asia-southeast1"
    ]
}
```

This seems to be happening with `CephObjectZoneGroup`, `CephObjectRealm` 
**Expected behavior:**
Rook Ceph should attempt to clean up these objects with finalizer and does not leave any dangling metadata behind

**How to reproduce it (minimal and precise):**
```
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: my-realm
  namespace: rook-ceph # namespace:cluster
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: asia-southeast1
  namespace: rook-ceph # namespace:cluster
spec:
  realm: my-realm
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: asia-southeast1-a
  namespace: rook-ceph # namespace:cluster
spec:
  zoneGroup: asia-southeast1
  preservePoolsOnDelete: false
  metadataPool:
    failureDomain: host
    replicated:
      size: 1
      requireSafeReplicaSize: false
  dataPool:
    failureDomain: host
    replicated:
      size: 1
      requireSafeReplicaSize: false
    parameters:
      compression_mode: none
```

**Workaround**
Manually Delete `CephObjectZoneGroup` and other problematic resources manually via `Toolbox` using `radosgw-admin zonegroup delete --rgw-zonegroup=<ZONEGROUP_NAME>`

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 22.04.4 LTS`
* Kernel (e.g. `uname -a`): `5.15.0-107-generi`
* Cloud provider or hardware configuration: `bare metal`
* Rook version (use `rook version` inside of a Rook Pod): `v1.14.3`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 18.2.2 (531c0d11a1c5d39fbfe6aa8a521f023abf3bf3e2) reef (stable)`
* Kubernetes version (use `kubectl version`): `v1.29.5+k3s1`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `k3s`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): `HEALTHY`

**`ceph status`**
```
cluster:
    id:     7c4d8a01-cf7b-44f3-ad78-d00ca49512d1
    health: HEALTH_OK

  services:
    mon: 1 daemons, quorum a (age 37h)
    mgr: a(active, since 33h)
    mds: 1/1 daemons up, 1 hot standby
    osd: 9 osds: 9 up (since 37h), 9 in (since 3w)
    rgw: 3 daemons active (3 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   12 pools, 833 pgs
    objects: 1.15M objects, 3.4 TiB
    usage:   3.4 TiB used, 2.0 TiB / 5.5 TiB avail
    pgs:     833 active+clean

  io:
    client:   1.3 MiB/s rd, 292 KiB/s wr, 3 op/s rd, 5 op/s wr
```
