### ISSUE TITLE
The rook-ceph-default SA does not have associated Cluster Role Binding

### ISSUE THREAD

**Issue by KKonak** [rook/rook#14379]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The new rook-ceph-default service account (added in 1.14.0) does not have an associated cluster role binding. Causing the rook-ceph-mon canaries to not start due to "hostPath volumes are not allowed to be used" the replica set for canary deployment cannot be started.

**Expected behavior:**
Cluster deploys using Helm install when pspEnable: true

**Logs to submit**:
* Crashing pod(s) logs, if necessary

Error from replica set, using the rook-ceph-default SA
`
kubectl describe replicaset rook-ceph-mon-a-canary:
Warning  FailedCreate  19s (x15 over 101s)  replicaset-controller  Error creating: pods "rook-ceph-mon-a-canary-5f787c4864-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[5]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
`
List of existing cluster role bindings:
kubectl get clusterrolebindings.rbac.authorization.k8s.io | grep rook-ceph
rook-ceph-global ClusterRole/rook-ceph-global
rook-ceph-mgr-cluster ClusterRole/rook-ceph-mgr-cluster
rook-ceph-mgr-cluster-namespace ClusterRole/rook-ceph-mgr-cluster
rook-ceph-object-bucket  ClusterRole/rook-ceph-object-bucket
rook-ceph-osd ClusterRole/rook-ceph-osd
rook-ceph-osd-namespace ClusterRole/rook-ceph-osd
rook-ceph-system ClusterRole/rook-ceph-system
rook-ceph-system-psp  ClusterRole/psp:rook

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): 1.14.3
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.2
* Kubernetes version (use `kubectl version`): 1.24

**Comment by KKonak** [comment]
To add, I dont see Cluster Roles, or a Role for the rook-ceph-default SA to use either in the cluster helm chart.

**Comment by KKonak** [comment]
Documenting for others: Resolved by creating a cluster role binding using the existing psp:rook cluster role for the rook-ceph-default SA. 
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:rook
subjects:
  - kind: ServiceAccount
    name: rook-ceph-default
    namespace: {namespace} # namespace:cluster
```
