### ISSUE TITLE
Ceph MDS daemons are killed by liveliness probe after upgrade from 1.13 to 1.14

### ISSUE THREAD

**Issue by mnlipp** [rook/rook#14399]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Ceph managers are terminted unexpectedly. The logs show no problem until suddenly...

```
debug 2024-06-29T15:42:13.259+0000 7f1188aba700 -1 received  signal: Terminated from Kernel ( Could be generated by pthread_kill(), raise(), abort(), alarm() ) UID: 0
debug 2024-06-29T15:42:13.259+0000 7f1188aba700 -1 mds.podstorage-a *** got signal Terminated ***
```

As a workaround, I can prevent the managers from being killed by turning off the liveliness probe in the file system CRD:
```
spec:
  metadataServer:
    livenessProbe:
      disabled: true
```

So the cause shouldn't be some lack of resources.

**Expected behavior:**

They should not be killed.

**Files**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/rook/rook/raw/release-1.14/deploy/examples/crds.yaml
- https://github.com/rook/rook/raw/release-1.14/deploy/examples/common.yaml
- https://github.com/rook/rook/raw/release-1.14/deploy/examples/operator.yaml
- https://github.com/rook/rook/raw/release-1.14/deploy/examples/cluster.yaml
- https://github.com/rook/rook/raw/release-1.14/deploy/examples/monitoring/rbac.yaml

patches:
- patch: |-
    kind: ConfigMap
    apiVersion: v1
    metadata:
      namespace: rook-ceph
      name: rook-ceph-operator-config
    data:
      CSI_PLUGIN_ENABLE_SELINUX_HOST_MOUNT: "true"
      ROOK_ENABLE_DISCOVERY_DAEMON: "true"
  
- patch: |-
    apiVersion: ceph.rook.io/v1
    kind: CephCluster
    metadata:
      name: rook-ceph
      namespace: rook-ceph # namespace:cluster
    spec:
      cephVersion:
        image: quay.io/ceph/ceph:v18.2.2
      mgr:
        modules:
        - name: rook
          enabled: true
      dashboard:
        enabled: true
        port: 8080
        ssl: false
        prometheusEndpoint: http://prometheus.monitoring:9090
        prometheusEndpointSSLVerify: false
      monitoring:
        enabled: true
      network:
        # Because we want to support client access
        provider: host
      storage:
        useAllNodes: false
        useAllDevices: false
        nodes: { ... }
      resources:
        osd:
          requests:
            # As we have plenty, we follow the recommendation
            # https://docs.ceph.com/en/quincy/start/hardware-recommendations/
            memory: "8Gi"
```

```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: podstorage
  namespace: rook-ceph # namespace:cluster
spec:
  metadataPool:
    replicated:
      size: 3
      requireSafeReplicaSize: true
    deviceClass: hdd
    parameters:
      compression_mode:
        none
  dataPools:
    - name: replicated
      failureDomain: host
      replicated:
        size: 3
        requireSafeReplicaSize: true
      deviceClass: hdd
      parameters:
        compression_mode:
          none
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
    placement:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - rook-ceph-mds
                - key: rook_file_system
                  operator: In
                  values:
                    - podstorage
            topologyKey: kubernetes.io/hostname
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-mds
              topologyKey: topology.kubernetes.io/zone
    priorityClassName: system-cluster-critical
    livenessProbe:
      disabled: false
    startupProbe:
      disabled: false
```

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="AlmaLinux"
VERSION="9.4 (Seafoam Ocelot)"
```
* Kernel (e.g. `uname -a`):
5.14.0-362.18.1.el9_3.x86_64
* Storage backend version (e.g. for ceph do `ceph -v`):
18.2.2
