### ISSUE TITLE
Rook discards Mgr SeviceMonitor monitoring labels when active manager reelected

### ISSUE THREAD

**Issue by arttor** [rook/rook#14477]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After active manager reelected, rook removes monitoring labels from mgr ServiceMonitor.

**Expected behavior:**
After active manager reelected, mgr ServiceMonitor should keep all labels.

**How to reproduce it (minimal and precise):**

1. Create Ceph Cluster with enabled monitoring and at least 2 managers:
  ```yaml
  spec:
    labels:
      monitoring:
        my-label: abc
    mgr:
      allowMultiplePerNode: true
      count: 2
      modules:
        - enabled: true
          name: rook
    monitoring:
      enabled: true
  ```
2. Check that monitoring labels were propagated to mgr `ServiceMonitor`:
  ```shell
  % kubectl -n rook-ceph get servicemonitor rook-ceph-mgr -o yaml | yq .metadata.labels
  team: rook
  my-label: abc
  ```
4. Downscale active mgr (find one with `metadata.label.mgr_role == active`) and wait until remaining mgr will be labeled as active:
  ```shell
  % kubectl -n rook-ceph scale deployment/rook-ceph-mgr-a --replicas=0
  ```
6. Check that now mgr `ServiceMonitor` is missing monitoring labels:
  ```shell
  % kubectl -n rook-ceph get servicemonitor rook-ceph-mgr -o yaml | yq .metadata.labels
  team: rook
  ```
