### ISSUE TITLE
Still connecting to unix:///csi/csi.sock

### ISSUE THREAD

**Issue by mvtab** [rook/rook#14507]
## Is this a bug report or feature request?**
Bug Report

### Expected behavior
Having a functional Rook-Ceph cluster after following the official documentation.

### Actual behavior
Non functional system.

### How to reproduce it
Install Rook with these configurations on a vanilla K8s:
``` yaml
# rook-operator.values.yaml
---
resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 128Mi

csi:
  enableRbdDriver: True
  enableCephfsDriver: True
  disableCsiDriver: False

  enableMetadata: True
  clusterName: <censored>
  
...
```
``` yaml
# rook-cluster.values.yaml
---
operatorNamespace: rook-ceph
clusterName: <censored>
cephClusterSpec:
  dataDirHostPath: /var/lib/rook
  storage:
    useAllNodes: False
    useAllDevices: False
    nodes:
    - name: <censored>
      devices:
      - name: sdb
    - name: <censored>
      devices:
      - name: sdb
    - name: <censored>
      devices:
      - name: sdb
cephBlockPools:
- name: ceph-blockpool
  spec:
    failureDomain: host
    replicated:
      size: 3
  storageClass:
    enabled: True
    name: ceph-block
    isDefault: True
    reclaimPolicy: Retain
cephFileSystems:
- name: ceph-filesystem
  spec:
    metadataPool:
      replicated:
        size: 3
    dataPools:
    - failureDomain: host
      replicated:
        size: 3
      name: data0
    metadataServer:
      activeCount: 1
      activeStandby: True
      resources:
        limits:
          memory: "8Gi"
        requests:
          cpu: "1000m"
          memory: "4Gi"
      priorityClassName: system-cluster-critical
  storageClass:
    enabled: True
    name: ceph-filesystem
    isDefault: False
    reclaimPolicy: Retain
cephObjectStores:
- name: ceph-objectstore
  spec:
    metadataPool:
      failureDomain: host
      replicated:
        size: 3
    dataPool:
      failureDomain: host
      erasureCoded:
        dataChunks: 2
        codingChunks: 1
    preservePoolsOnDelete: True
    gateway:
      port: 80
      resources:
        limits:
          memory: "4Gi"
        requests:
          cpu: "1000m"
          memory: "2Gi"
      instances: 1
      priorityClassName: system-cluster-critical
  storageClass:
    enabled: True
    name: ceph-bucket
    reclaimPolicy: Retain

...

```

### Operator's logs, if necessary
No warnings/errors related to rbd plugins in the operator logs.

### Crashing pod(s) logs, if necessary
``` bash
# csi-rbdplugin-5cwhg, csi-rbdplugin-8pjdr, csi-rbdplugin-gbg25 - same output
Defaulted container "driver-registrar" out of: driver-registrar, csi-rbdplugin
I0729 09:26:55.096500   23554 main.go:135] Version: v2.10.1
I0729 09:26:55.096564   23554 main.go:136] Running node-driver-registrar in mode=
W0729 09:27:05.097389   23554 connection.go:234] Still connecting to unix:///csi/csi.sock
W0729 09:27:15.096924   23554 connection.go:234] Still connecting to unix:///csi/csi.sock
W0729 09:27:25.097316   23554 connection.go:234] Still connecting to unix:///csi/csi.sock
E0729 09:27:25.097384   23554 main.go:160] error connecting to CSI driver: context deadline exceeded
```

### Cluster Status to submit
![image](https://github.com/user-attachments/assets/171e1f97-631a-4459-81d1-55c1fa88b4b8)

### Output of kubectl commands, if necessary
No kubectl plugins allowed.

### Environment

- OS (e.g. from /etc/os-release): opensuse-leap-15.6
- Kernel: `Linux <hostname> 6.4.0-150600.23.7-default #1 SMP PREEMPT_DYNAMIC Fri Jun 14 14:33:11 UTC 2024 (33f31da) x86_64 x86_64 x86_64 GNU/Linux`
- Cloud provider or hardware configuration: Proxmox Cluster
- Rook version: rook 1.14.9, go 1.21.12
- Storage backend version: 18.2.4
- Kubernetes version: 1.30.3
- Kubernetes cluster type: Vanilla kubeadm
- Storage backend status: `HEALTH_OK`
