### ISSUE TITLE
RGW pods unable to start when 'provider=host'

### ISSUE THREAD

**Issue by aplufr** [rook/rook#14513]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
RGW pods should be able to became healthy, instead the pod health check failed

**Expected behavior:**
RGW pods became healthy. 

**How to reproduce it (minimal and precise):**

We've a cluster with rgw services running on cni network.
Set the provided: host in network section of the cluster crds, as explained here: https://rook.io/docs/rook/latest-release/CRDs/Cluster/network-providers/#host-networking
Let the operator reconfigure the whole cluster. 
Cluster end healthy (ceph -s => health ok), mon, osd and mgr did switch the host networking but rgw deployment failed to start due to health check failling. 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```
spec:
  cephVersion:
    allowUnsupported: false
    image: docker-registry.internal/ceph/ceph:v18.2.2
  cleanupPolicy:
    allowUninstallWithVolumes: false
    confirmation: ""
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  crashCollector:
    daysToRetain: 30
    disable: false
  dashboard:
    enabled: true
    ssl: false
    urlPrefix: /
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
  external: {}
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mgr:
        disabled: false
      mon:
        disabled: false
      osd:
        disabled: false
  labels:
    monitoring:
      release: prometheus-val-ng
  logCollector:
    enabled: true
    maxLogSize: 500M
    periodicity: daily
  mgr:
    allowMultiplePerNode: false
    count: 2
    modules:
    - enabled: true
      name: pg_autoscaler
    - enabled: true
      name: stats
    - enabled: true
      name: diskprediction_local
  mon:
    allowMultiplePerNode: false
    count: 3
  monitoring:
    enabled: true
  network:
    provider: host
    connections:
      compression:
        enabled: false
      encryption:
        enabled: false
      requireMsgr2: false
    multiClusterService: {}
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node/storage-defined-software
              operator: In
              values:
              - ceph
      tolerations:
      - effect: NoSchedule
        key: gpu
        operator: Exists
  priorityClassNames:
    mgr: system-cluster-critical
    mon: system-node-critical
    osd: system-node-critical
  removeOSDsIfOutAndSafeToRemove: false
  resources:
    cleanup:
      limits:
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 100Mi
    crashcollector:
      limits:
        memory: 60Mi
      requests:
        cpu: 100m
        memory: 60Mi
    exporter:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 50Mi
    logcollector:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    mgr:
      limits:
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    mgr-sidecar:
      limits:
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 40Mi
    mon:
      limits:
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 1Gi
    osd:
      limits:
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 4Gi
    prepareosd:
      requests:
        cpu: 500m
        memory: 50Mi
  security:
    keyRotation:
      enabled: false
    kms: {}
  skipUpgradeChecks: false
  storage:
    config:
      encryptedDevice: "true"
    flappingRestartIntervalHours: 0
    store: {}
    useAllDevices: true
    useAllNodes: true
  upgradeOSDRequiresHealthyPGs: false
  waitTimeoutForHealthyOSDInMinutes: 10

````

**Logs to submit**:

Describe pods of ceph-rgw 
```
 Warning  Unhealthy  1s (x2 over 98s)  kubelet            Startup probe failed: command "bash -c #!/usr/bin/env bash\n\nPROBE_TYPE=\"startup\"\nPROBE_PORT=\"80\"\nPROBE_PROTOCOL=\"HTTP\"\n\n# standard bash codes start at 126 and progress upward. pick error codes from 125 downward for\n# script as to allow curl to output new error codes and still return a distinctive number.\nUSAGE_ERR_CODE=125\nPROBE_ERR_CODE=124\n# curl error codes: 1-123\n\nSTARTUP_TYPE='startup'\nREADINESS_TYPE='readiness'\n\nRGW_URL=\"$PROBE_PROTOCOL://0.0.0.0:$PROBE_PORT\"\n\nfunction check() {\n  local URL=\"$1\"\n  # --insecure - don't validate ssl if using secure port only\n  # --silent - don't output progress info\n  # --output /dev/stderr - output HTML header to stdout (good for debugging)\n  # --write-out '%{response_code}' - print the HTTP response code to stdout\n  curl --insecure --silent --output /dev/stderr --write-out '%{response_code}' \"$URL\"\n}\n\nhttp_response=\"$(check \"$RGW_URL\")\"\nretcode=$?\n\nif [[ $retcode -ne 0 ]]; then\n  # if this is the startup probe, always returning failure. if startup probe passes, all subsequent\n  # probes can rely on the assumption that the health check was once succeeding without errors.\n  # if this is the readiness probe, we know that curl was previously working correctly in the\n  # startup probe, so curl error most likely means some new error with the RGW.\n  echo \"RGW health check failed with error code: $retcode. the RGW likely cannot be reached by clients\" >/dev/stderr\n  exit $retcode\nfi\n\nRGW_RATE_LIMITING_RESPONSE=503\nRGW_MISCONFIGURATION_RESPONSE=500\n\nif [[ $http_response -ge 200 ]] && [[ $http_response -lt 400 ]]; then\n  # 200-399 are successful responses. same behavior as Kubernetes' HTTP probe\n  exit 0\n\nelif [[ $http_response -eq $RGW_RATE_LIMITING_RESPONSE ]]; then\n  # S3's '503: slow down' code is not an error but an indication that RGW is throttling client\n  # traffic. failing the readiness check here would only cause an increase in client connections on\n  # other RGWs and likely cause those to fail also in a cascade. i.e., a special healthy response.\n  echo \"INFO: RGW is rate limiting\" 2>/dev/stderr\n  exit 0\n\nelif [[ $http_response -eq $RGW_MISCONFIGURATION_RESPONSE ]]; then\n  # can't specifically determine if the RGW is running or not. most likely a misconfiguration.\n  case \"$PROBE_TYPE\" in\n  \"$STARTUP_TYPE\")\n    # fail until we can accurately get a valid healthy response when runtime starts.\n    echo 'FAIL: HTTP code 500 suggests an RGW misconfiguration.' >/dev/stderr\n    exit $PROBE_ERR_CODE\n    ;;\n  \"$READINESS_TYPE\")\n    # config likely modified at runtime which could result in all RGWs failing this check.\n    # occasional client failures are still better than total failure, so ignore this\n    echo 'WARN: HTTP code 500 suggests an RGW misconfiguration' >/dev/stderr\n    exit 0\n    ;;\n  *)\n    # prior arg validation means this path should never be activated, but keep to be safe\n    echo \"ERROR: probe type is unknown: $PROBE_TYPE\" >/dev/stderr\n    exit $USAGE_ERR_CODE\n    ;;\n  esac\n\nelse\n  # anything else is a failing response. same behavior as Kubernetes' HTTP probe\n  echo \"FAIL: received an HTTP error code: $http_response\"\n  exit $PROBE_ERR_CODE\n\nfi\n" timed out
```
Pod logs
```
 kubectl logs -n rook-ceph-val rook-ceph-rgw-ceph-objectstore-a-7fc5dcd748-dhn5h -c rgw -f
debug 2024-07-30T08:37:52.061+0000 7f77191e9a80  0 deferred set uid:gid to 167:167 (ceph:ceph)
debug 2024-07-30T08:37:52.061+0000 7f77191e9a80  0 ceph version 18.2.2 (531c0d11a1c5d39fbfe6aa8a521f023abf3bf3e2) reef (stable), process radosgw, pid 13
debug 2024-07-30T08:37:52.061+0000 7f77191e9a80  0 framework: beast
debug 2024-07-30T08:37:52.061+0000 7f77191e9a80  0 framework conf key: port, val: 80
debug 2024-07-30T08:37:52.061+0000 7f77191e9a80  0 framework conf key: ssl_port, val: 443
debug 2024-07-30T08:37:52.061+0000 7f77191e9a80  0 framework conf key: ssl_certificate, val: /etc/ceph/private/rgw-cert.pem
debug 2024-07-30T08:37:52.061+0000 7f77191e9a80  0 framework conf key: ssl_private_key, val: /etc/ceph/private/rgw-key.pem
debug 2024-07-30T08:37:52.061+0000 7f77191e9a80  1 init_numa not setting numa affinity
debug 2024-07-30T08:37:52.297+0000 7f77191e9a80  0 framework: beast
debug 2024-07-30T08:37:52.297+0000 7f77191e9a80  0 framework conf key: ssl_certificate, val: config://rgw/cert/$realm/$zone.crt
debug 2024-07-30T08:37:52.297+0000 7f77191e9a80  0 framework conf key: ssl_private_key, val: config://rgw/cert/$realm/$zone.key
debug 2024-07-30T08:37:52.334+0000 7f77191e9a80  0 starting handler: beast
debug 2024-07-30T08:37:52.336+0000 7f77191e9a80  0 set uid:gid to 167:167 (ceph:ceph)
debug 2024-07-30T08:37:52.378+0000 7f77191e9a80  1 mgrc service_daemon_register rgw.28237762 metadata {arch=x86_64,ceph_release=reef,ceph_version=ceph version 18.2.2 (531c0d11a1c5d39fbfe6aa8a521f023abf3bf3e2) reef (stable),ceph_version_short=18.2.2,container_hostname=fr0-dlabgpu-p02.eu.airbus.corp,container_image=docker-airbus-virtual.artifactory.2b82.aws.cloud.airbus.corp/ceph/ceph:v18.2.2,cpu=Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz,distro=centos,distro_description=CentOS Stream 8,distro_version=8,frontend_config#0=beast port=80 ssl_port=443 ssl_certificate=/etc/ceph/private/rgw-cert.pem ssl_private_key=/etc/ceph/private/rgw-key.pem,frontend_type#0=beast,hostname=fr0-dlabgpu-p02.eu.airbus.corp,id=ceph.objectstore.a,kernel_description=#1 SMP Fri Jun 14 03:19:37 EDT 2024,kernel_version=4.18.0-553.8.1.el8_10.x86_64,mem_cgroup_limit=2147483648,mem_swap_kb=4194300,mem_total_kb=263233832,num_handles=1,os=Linux,pid=13,pod_name=rook-ceph-rgw-ceph-objectstore-a-7fc5dcd748-dhn5h,pod_namespace=rook-ceph-val,realm_id=7c19a349-8d76-4253-ace3-4960e5e9e4df,realm_name=ceph-objectstore,zone_id=83a0d388-3e4f-463c-8c88-39058aa667ea,zone_name=ceph-objectstore,zonegroup_id=761dbe40-f3db-4675-97c4-3de391946d5c,zonegroup_name=ceph-objectstore}
```

**Environment**:
* OS (e.g. from /etc/os-release): RHEL8.9
* Kernel (e.g. `uname -a`): 4.18.0-553.8.1.el8_10.x86_64
* Cloud provider or hardware configuration: on prem & airgap nodes
* Rook version (use `rook version` inside of a Rook Pod): 1.14.6
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.2
* Kubernetes version (use `kubectl version`): 1.26.x
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher RKE2 on prem
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK
