### ISSUE TITLE
Host networking for provisioners

### ISSUE THREAD

**Issue by RomLecat** [rook/rook#14510]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Set `hostNetworking: True` in the spec of
https://github.com/rook/rook/blob/7dafd45accaa0e03f77c3bf10a8e338d2992ca36/pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml#L4
and
https://github.com/rook/rook/blob/7dafd45accaa0e03f77c3bf10a8e338d2992ca36/pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml

**What is use case behind this feature:**
Some Ceph clusters, especially external, are sometime not reachable over the CSI network, but requires hostNetwork.
Rook mostly handles it with those values for the operator:
```
rook-ceph:
  useOperatorHostNetwork: true
  csi:
    enableCSIHostNetwork: true
```
And those for the cluster:
```
rook-ceph-cluster:
  cephClusterSpec:
    network:
      provider: host
```

But the provisioner still has no way to be in the host network.
Manually patching the deployment of provisioner (eg. with k edit/patch) works, but it is not persistent. I'd like a way to set it in the operator.

**Environment**:
Kubernetes v1.28.12
Rook-Ceph 1.14.9 w/ external cluster

Thanks!
