### ISSUE TITLE
Single OSDs fail to start after upgrading from Ceph 18.2.2 to 18.2.4 when encrypted.

### ISSUE THREAD

**Issue by sfackler** [rook/rook#14563]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When upgrading Ceph from 18.2.2 to 18.2.4 on an environment with only a single OSD *and* disk encryption enabled, the OSD pod will get stuck at `Init:0/3` until the host is rebooted.

Either using a single unencrypted OSD or multiple encrypted OSDs with replication makes the upgrade work just fine. This appears to be 100% deterministic.

A single OSD environment is obviously not a recommended way to deploy Ceph - I would love to give it more disks in this setup if I had some :(

**Expected behavior:**

The OSD pod should reinitialize as normal after the upgrade.

**How to reproduce it (minimal and precise):**

1. Set up an environment with a single disk for Ceph to adopt.
2. Install rook-ceph and rook-ceph-cluster v1.14.9 via Helm. rook-ceph-cluster should be overridden to use Ceph 18.2.2, and have the `encryptedDevice` storage config set to `true`.
3. Once Ceph comes online, boot up a pod that uses a persistent volume. I just ran a simple container that writes to a file in the PV every few seconds.
4. Update rook-ceph-cluster via Helm to use Ceph 18.2.4.
5. Observe that the OSD pod never initializes.
7. Reboot the host, and observe that the OSD pod successfully boots after the system comes back online.

**File(s) to submit**:

rook-ceph-cluster values.yaml (after upgrading Ceph to 18.2.4)

```yaml
cephClusterSpec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.4
  mgr:
    count: 1
  mon:
    count: 1
  storage:
    config:
      encryptedDevice: "true"
  cephConfig:
    global:
      osd_pool_default_size: "1"
    mon:
      mon_warn_on_pool_no_redundancy: "false"
cephFileSystems: []
cephObjectStores: []
cephBlockPools:
- name: builtin-mgr
  spec:
    name: .mgr
    failureDomain: osd
    replicated:
      size: 1
  storageClass:
    enabled: false
- name: ceph-blockpool
  spec:
    failureDomain: osd
    replicated:
      size: 1
  storageClass:
    enabled: true
    name: ceph-block
    isDefault: true
    reclaimPolicy: Delete
    allowVolumeExpansion: true
    volumeBindingMode: "Immediate"
    mountOptions: []
    allowedTopologies: []
    parameters:
      imageFormat: "2"
      imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
      csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
      csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
      csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
      csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
      csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
      csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
      csi.storage.k8s.io/fstype: ext4
```

**Logs to submit**:

```
$ kubectl get pods -n rook-ceph
NAME                                                              READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-provisioner-78cc8b775b-zdsg9                     5/5     Running     0          33m
csi-cephfsplugin-xxqfl                                            2/2     Running     0          33m
csi-rbdplugin-8cbcr                                               2/2     Running     0          33m
csi-rbdplugin-provisioner-99c4c678f-f25s2                         5/5     Running     0          33m
rook-ceph-crashcollector-e59be2689e6d87c3904e09592ca6d452-ftfqz   1/1     Running     0          29m
rook-ceph-exporter-il-pg-alpha-5238760.use1.palantir.globarr27p   1/1     Running     0          28m
rook-ceph-mgr-a-78b9555755-cv9tk                                  2/2     Running     0          28m
rook-ceph-mon-a-79584df6f8-4cm2s                                  2/2     Running     0          29m
rook-ceph-operator-c4cdbfd5d-m4dqh                                1/1     Running     0          34m
rook-ceph-osd-0-7b6c9c8d55-2wzp7                                  0/2     Init:0/3    0          28m
rook-ceph-osd-prepare-e59be2689e6d87c3904e09592ca6d452-mppx5      0/1     Completed   0          18m
rook-discover-plwz8                                               1/1     Running     0          34m
```

(The key appearing in these logs seems nonideal but this is just a one-off test environment)
```
$ kubectl logs -n rook-ceph rook-ceph-osd-0-7b6c9c8d55-2wzp7 activate
+ OSD_ID=0
+ CEPH_FSID=8c0336a1-f999-4a8f-811d-8b163f184db1
+ OSD_UUID=2366d96c-c453-47d6-b24a-b6d0b6da6d50
+ OSD_STORE_FLAG=--bluestore
+ OSD_DATA_DIR=/var/lib/ceph/osd/ceph-0
+ CV_MODE=lvm
+ DEVICE=/dev/ceph-3df222bd-de19-4254-90bc-761dcbc7b3ed/osd-block-2366d96c-c453-47d6-b24a-b6d0b6da6d50
+ cp --no-preserve=mode /etc/temp-ceph/ceph.conf /etc/ceph/ceph.conf
+ python3 -c '
import configparser

config = configparser.ConfigParser()
config.read('\''/etc/ceph/ceph.conf'\'')

if not config.has_section('\''global'\''):
    config['\''global'\''] = {}

if not config.has_option('\''global'\'','\''fsid'\''):
    config['\''global'\'']['\''fsid'\''] = '\''8c0336a1-f999-4a8f-811d-8b163f184db1'\''

with open('\''/etc/ceph/ceph.conf'\'', '\''w'\'') as configfile:
    config.write(configfile)
'
+ ceph -n client.admin auth get-or-create osd.0 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
[osd.0]
        key = AQBXcbtmwK8BEhAAoD+K7bx8KCtAvNDSuJ6Eyg==
+ [[ lvm == \l\v\m ]]
++ mktemp -d
+ TMP_DIR=/tmp/tmp.YScChDcoBL
+ ceph-volume lvm activate --no-systemd --bluestore 0 2366d96c-c453-47d6-b24a-b6d0b6da6d50
```

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

```
$ kubectl rook-ceph rook status
Info: cephclusters rook-ceph
ceph:
    capacity:
        bytesAvailable: 107323637760
        bytesTotal: 107353210880
        bytesUsed: 29573120
        lastUpdated: "2024-08-13T15:03:22Z"
    details:
        OSD_DOWN:
            message: 1 osds down
            severity: HEALTH_WARN
        OSD_FLAGS:
            message: 1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set
            severity: HEALTH_WARN
        OSD_HOST_DOWN:
            message: 1 host (1 osds) down
            severity: HEALTH_WARN
        OSD_ROOT_DOWN:
            message: 1 root (1 osds) down
            severity: HEALTH_WARN
        PG_AVAILABILITY:
            message: 'Reduced data availability: 64 pgs stale'
            severity: HEALTH_WARN
    fsid: 8c0336a1-f999-4a8f-811d-8b163f184db1
    health: HEALTH_WARN
    lastChanged: "2024-08-13T14:49:13Z"
    lastChecked: "2024-08-13T15:03:22Z"
    previousHealth: HEALTH_OK
    versions:
        mgr:
            ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable): 1
        mon:
            ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable): 1
        overall:
            ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable): 2
conditions:
    - lastHeartbeatTime: "2024-08-13T15:03:23Z"
      lastTransitionTime: "2024-08-13T14:44:55Z"
      message: Cluster created successfully
      reason: ClusterCreated
      status: "True"
      type: Ready
message: Cluster created successfully
observedGeneration: 3
phase: Ready
state: Created
storage:
    deviceClasses:
        - name: ssd
    osd:
        storeType:
            bluestore: 1
version:
    image: quay.io/ceph/ceph:v18.2.4
    version: 18.2.4-0
```

**Environment**:
* OS (e.g. from /etc/os-release): `Rocky Linux 8.10 (Green Obsidian)`
* Kernel (e.g. `uname -a`): `4.18.0-553.8.1.el8_10.x86_64 #1 SMP Tue Jul 2 17:10:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: AWS EC2 (also reproduced on bare metal and VMWare environments)
* Rook version (use `rook version` inside of a Rook Pod): `v1.14.9`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable)`
* Kubernetes version (use `kubectl version`): `v1.28.12+rke2r1`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): `HEALTH_WARN 1 osds down; 1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set; 1 host (1 osds) down; 1 root (1 osds) down; Reduced data availability: 64 pgs stale`
