### ISSUE TITLE
Data distribution on OSDs is not effective

### ISSUE THREAD

**Issue by vincedihub** [rook/rook#14666]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I've created an 8TB PVC
There is absolutely nothing else on the SSDs, apart from the single 8TB PVC. 
After copying about 3.4TB of data onto the PVC, I get the following error message :

![image](https://github.com/user-attachments/assets/da3b7067-5ea2-4c79-b630-839261efcb8c)

But I see that only the 4TB SSDs have been used, not the 2TB SSDs.
![image](https://github.com/user-attachments/assets/26820357-6986-420e-9579-965b8fb3f127)

**Expected behavior:**

I was expecting the PVC to be spread over all the disks, not just two. 

**How to reproduce it (minimal and precise):**

**File(s) to submit**:
CephCluster

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: cluster-global
  namespace: rook-cluster-global # namespace:cluster
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.4
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook/global
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  waitTimeoutForHealthyOSDInMinutes: 10
  upgradeOSDRequiresHealthyPGs: false
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
    allowMultiplePerNode: false
    modules:
      - name: rook
        enabled: true
  dashboard:
    enabled: true
    ssl: false
  monitoring:
    enabled: false
    metricsDisabled: false
  network:
    connections:
volumes.
      encryption:
        enabled: false
      compression:
        enabled: false
      requireMsgr2: false
  crashCollector:
    disable: false
  logCollector:
    enabled: true
    periodicity: daily # one of: hourly, daily, weekly, monthly
    maxLogSize: 500M # SUFFIX may be 'M' or 'G'. Must be at least 1M.
  cleanupPolicy:
    confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
    allowUninstallWithVolumes: false
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: rook-cluster-global-storage-node
              operator: In
              values:
              - "true"
      podAffinity:
      podAntiAffinity:
      topologySpreadConstraints:
      tolerations:
      - key: rook-cluster-global-storage-node
        operator: Exists
  labels:
  resources:
  removeOSDsIfOutAndSafeToRemove: false
  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
  storage:
    useAllNodes: false
    useAllDevices: false
    devices:
    nodes:
      - name: "kube-worker-1"
        devices:
          - name: /dev/disk/by-id/..........
          - name: /dev/disk/by-id/..........
          - .......
      - name: "kube-worker-2"
        devices:
          - name: /dev/disk/by-id/..........
          - name: /dev/disk/by-id/..........
          - .......
      - name: "kube-worker-3"
          - name: /dev/disk/by-id/..........
          - name: /dev/disk/by-id/..........
          - .......
    config:
    allowDeviceClassUpdate: false
    allowOsdCrushWeightUpdate: false
    onlyApplyOSDPlacement: false
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
  csi:
    readAffinity:
      enabled: true
    cephfs:
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
    startupProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
```

CephBlockPool 
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: standard-ssd
  namespace: rook-cluster-global
spec:
  failureDomain: host
  enableRBDStats: true
  replicated:
    size: 2
  deviceClass: ssd
```

StorageClass
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-r2-rbd
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  clusterID: rook-cluster-global
  pool: standard-ssd
  imageFormat: "2"
  imageFeatures: "layering,exclusive-lock,object-map,fast-diff,deep-flatten"
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-cluster-global
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-cluster-global
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-cluster-global
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - discard
```

**Logs to submit**:

* Operator's logs, if necessary
![image](https://github.com/user-attachments/assets/ffabd01b-57f7-4d20-8f57-b9ef3d3cd618)
  1. [rook-ceph-operator.log](https://github.com/user-attachments/files/16850546/rook-ceph-operator.log)

* Crashing pod(s) logs, if necessary
![image](https://github.com/user-attachments/assets/555c9594-a72a-41b1-b7ed-5b4209fbdb6f)
  1. [rook-ceph-crashcollector-kube-worker-1.log](https://github.com/user-attachments/files/16850668/rook-ceph-crashcollector-kube-worker-1.log)
  2. [rook-ceph-crashcollector-kube-worker-2.log](https://github.com/user-attachments/files/16850669/rook-ceph-crashcollector-kube-worker-2.log)
  3. [rook-ceph-crashcollector-kube-worker-3.log](https://github.com/user-attachments/files/16850670/rook-ceph-crashcollector-kube-worker-3.log)

* Manager pod(s) logs
![image](https://github.com/user-attachments/assets/3ddbbdde-3e32-478a-aecf-52d1dffe24d7)
  1. [rook-ceph-mgr-a.log](https://github.com/user-attachments/files/16850822/rook-ceph-mgr-a.log)
  2. [rook-ceph-mgr-b.log](https://github.com/user-attachments/files/16850910/rook-ceph-mgr-b.log)

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
![image](https://github.com/user-attachments/assets/f6aa31a0-8f7e-4c76-abe0-f152a70072dd)

  To get the status of the cluster, use `kubectl rook-ceph ceph status`
![image](https://github.com/user-attachments/assets/42488ce8-6dc7-4e3b-89de-cdf53b15b886)

  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): 
![image](https://github.com/user-attachments/assets/87b965ec-cebe-4e59-8833-8558579ed375)

* Kernel (e.g. `uname -a`):
![image](https://github.com/user-attachments/assets/0346c40f-39f1-468b-bb0f-ec82202b0967)

* Cloud provider or hardware configuration:

  - I have an Bare Metal K8S cluster with 3 masters and 3 workers.
  - All nodes (masters and workers) have Talos as OS 
  - Each worker has the following configuration: 
    - 3 x 2 TB NVME
    - 1 x 2 TB SDD
    - 1 x 4 TB SDD 
    - 1 x 12TB HDD 

* Rook version (use `rook version` inside of a Rook Pod):
![image](https://github.com/user-attachments/assets/e7b8bb29-04ee-4875-9b0c-49ec5f6a2739)

* Storage backend version (e.g. for ceph do `ceph -v`):
![image](https://github.com/user-attachments/assets/40acb159-9840-42fe-9eed-8d5219bcd7a2)

* Kubernetes version (use `kubectl version`):
![image](https://github.com/user-attachments/assets/b9e41279-3c47-407b-a8e6-61cc00e56522)

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): 
`Bare metal`

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
![image](https://github.com/user-attachments/assets/f6aa31a0-8f7e-4c76-abe0-f152a70072dd)

**Comment by vincedihub** [comment]
I tried setting a replication to 2 to see if it changed anything, but in fact it changes absolutely nothing, the problem remains. 

I've created an 8TB PVC, There is absolutely nothing else on the SSDs, apart from the single 8TB PVC. 
After copying about 3.4TB of data onto the PVC, I get the following error message :

![image](https://github.com/user-attachments/assets/da3b7067-5ea2-4c79-b630-839261efcb8c)

But I see that only the 4TB SSDs have been used, not the 2TB SSDs.
![image](https://github.com/user-attachments/assets/26820357-6986-420e-9579-965b8fb3f127)

**Comment by microyahoo** [comment]
what's the output of `ceph df`? Seems pg num is too low

**Comment by vincedihub** [comment]
I think I've found the problem. 

In the manager's logs
[rook-ceph-mgr-a.log](https://github.com/user-attachments/files/16850822/rook-ceph-mgr-a.log)

I saw the following lines : 

```
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler INFO root] _maybe_adjust
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool performance-ec-rbd-replicated-metadata-pool won't scale due to overlapping roots: {-1, -2}
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] Please See: https://docs.ceph.com/en/latest/rados/operations/placement-groups/#automated-scaling
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool performance-ec-rbd-data-pool won't scale due to overlapping roots: {-1, -2}
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] Please See: https://docs.ceph.com/en/latest/rados/operations/placement-groups/#automated-scaling
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool performance-rbd-replicapool won't scale due to overlapping roots: {-1, -2}
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] Please See: https://docs.ceph.com/en/latest/rados/operations/placement-groups/#automated-scaling
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool standard-ssd won't scale due to overlapping roots: {-3, -1, -2}
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] Please See: https://docs.ceph.com/en/latest/rados/operations/placement-groups/#automated-scaling
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool 1 contains an overlapping root -1... skipping scaling
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool 6 contains an overlapping root -2... skipping scaling
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool 7 contains an overlapping root -2... skipping scaling
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool 8 contains an overlapping root -2... skipping scaling
debug 2024-09-03T14:58:01.553+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool 57 contains an overlapping root -3... skipping scaling
```

**Comment by microyahoo** [comment]
First, you'd better not overlap the crush tree.
then, you can disable the autoscaling mode for an existing pool, run a command of the following form:
```
ceph osd pool set <pool-name> pg_autoscale_mode off
```
then set pg_num for pool
```
ceph osd pool set <pool-name> pg_num <pg_num>
```

**Comment by vincedihub** [comment]
Pools list : 
![image](https://github.com/user-attachments/assets/31059ae4-a2a2-4377-9aed-af004a6be1b1)

List of pools with autoscaling enabled : 
![image](https://github.com/user-attachments/assets/86db5ad4-cbf9-4a29-b2b6-1630eac2715a)

**Comment by vincedihub** [comment]
> I have no idea why so many crush root tree, it seems to be related to device class. cc @travisn you'd better to custom crush roots according to device class, then create pool with specific crush root, make sure not overlap. https://docs.ceph.com/en/quincy/rados/operations/crush-map/#modifying-the-crush-map
> 
> https://github.com/rook/rook/blob/afe72ffd8c80eabe13118173d486d8e7b8999529/deploy/examples/pool.yaml#L30

I'll add 'crushRoot' to the CephBlockPool. 
From what I understand, I need to modify all CephBlockPools to add the 'crushRoot'.  Can I do this on the fly on all CephBlockPools or is there a procedure to follow?

**Comment by vincedihub** [comment]
I'm in the process of modifying the CephBlockPool, I was wondering if I could reuse the crushRoot automatically generated by Ceph? 

Is the best practice to create a different crushRoot for each CephBlockPool?   

When is it better to use Ceph's automatically generated crushRoot?

**Comment by vincedihub** [comment]
I updated my **CephBlockPool** with `crushRoot: standard-ssd `

```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: standard-ssd
  namespace: rook-cluster-global # namespace:cluster
spec:
  failureDomain: host
  enableRBDStats: true
  replicated:
    size: 2
  crushRoot: standard-ssd
  deviceClass: ssd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-r2-rbd
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  clusterID: rook-cluster-global
  pool: standard-ssd
  imageFormat: "2"
  imageFeatures: "layering,exclusive-lock,object-map,fast-diff,deep-flatten"


  csi.storage.k8s.io/fstype: ext4  # ou xfs
  # The secrets contain Ceph admin credentials. These are generated automatically by the operator
  # in the same namespace as the cluster.
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-cluster-global # namespace:cluster
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-cluster-global # namespace:cluster
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-cluster-global # namespace:cluster
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - discard
```
But I get the following error: 

```
failed to reconcile CephBlockPool "rook-cluster-global/standard-ssd". invalid pool CR "standard-ssd" spec: unrecognized crush root standard-ssd
```

Rook doesn't create the crush automatically?  Do you have to do it manually?

Can an OSD be in several crushes ?

**Comment by travisn** [comment]
You don't need to set a different crush root. Ceph automatically generates those for the purposes of using device classes for the pools. If you specify a device class for a pool, ceph will automatically use the correct crush root, and no need to define the crushRoot property separately on the pool. 

That error about overlapping roots is caused when device classes are set on some pools, but not all pools. You'll need to ensure that the deviceClass property is set on all pools, including the [.mgr pool](https://github.com/rook/rook/blob/master/deploy/examples/pool-builtin-mgr.yaml). After all pools have the deviceClass set, and rook reconciles/updates them, it should resolve the errors of overlapping roots, and then the PG autoscaler can work properly.

**Comment by vincedihub** [comment]
Awesome!! Thank you very much for your help @travisn . Too bad I didn't see your answer sooner.


After analyzing these error logs again and again
```
debug 2024-09-03T18:58:02.748+0000 7f9a387dd640  0 [pg_autoscaler INFO root] _maybe_adjust
debug 2024-09-03T18:58:02.748+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool performance-ec-rbd-replicated-metadata-pool won't scale due to overlapping roots: {-1, -2}
debug 2024-09-03T18:58:02.748+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] Please See: https://docs.ceph.com/en/latest/rados/operations/placement-groups/#automated-scaling
debug 2024-09-03T18:58:02.748+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool performance-ec-rbd-data-pool won't scale due to overlapping roots: {-1, -2}
debug 2024-09-03T18:58:02.748+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] Please See: https://docs.ceph.com/en/latest/rados/operations/placement-groups/#automated-scaling
debug 2024-09-03T18:58:02.748+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool 1 contains an overlapping root -1... skipping scaling
debug 2024-09-03T18:58:02.748+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool 6 contains an overlapping root -2... skipping scaling
debug 2024-09-03T18:58:02.748+0000 7f9a387dd640  0 [pg_autoscaler WARNING root] pool 7 contains an overlapping root -2... skipping scaling
```

and reread this section several times

```
deviceClass: Sets up the CRUSH rule for the pool to distribute data only on the specified device class. If left empty or unspecified, the pool will use the cluster's default CRUSH root, which usually distributes data over all OSDs, regardless of their class. If deviceClass is specified on any pool, ensure that it is added to every pool in the cluster, otherwise Ceph will warn about pools with overlapping roots.
```
https://rook.io/docs/rook/latest-release/CRDs/Block-Storage/ceph-block-pool-crd/#spec


I ended up running the following commands: 

```
ceph osd crush rule create-replicated mgr_nvme default host nvme
ceph osd pool set .mgr crush_rule mgr_nvme
```

**Comment by travisn** [comment]
Glad to hear you got it working. Alternatively, sounds like you could have set the following property on the [.mgr poo](https://github.com/rook/rook/blob/master/deploy/examples/pool-builtin-mgr.yaml) and rook would have fixed the crush rule for you:
```yaml
deviceClass: nvme
```

**Comment by vincedihub** [comment]
@travisn I need to deploy a new Rook cluster, a brand new install, when should I deploy this configuration [.mgr poo](https://github.com/rook/rook/blob/master/deploy/examples/pool-builtin-mgr.yaml) ?

**Comment by travisn** [comment]
You can create the `.mgr` CephBlockPool at any point, and the device class or other settings (e.g. `replicated.size`) would be then configured by Rook. With a new cluster, you can go ahead and create it at cluster creation.

**Comment by vincedihub** [comment]
Thx @travisn and @microyahoo  for all your help

**Comment by vincedihub** [comment]
Hi @travisn,

After applying the following configuration
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  # If the built-in Ceph pool used by the Ceph mgr needs to be configured with alternate
  # settings, create this pool with any of the pool properties. Create this pool immediately
  # with the cluster CR, or else some properties may not be applied when Ceph creates the
  # pool by default.
  name: builtin-mgr
  namespace: rook-cluster-global # namespace:cluster
spec:
  # The required pool name with underscores cannot be specified as a K8s resource name, thus we override
  # the pool name created in Ceph with this name property.
  name: .mgr
  failureDomain: host
  deviceClass: nvme
  replicated:
    size: 3
    requireSafeReplicaSize: true
  parameters:
    compression_mode: none
  mirroring:
    enabled: false
```

I checked the status of the .**mgr crush_rule** and it was still on the one I had previously created `mgr_nvme`. 

I had to execute the following command:

```
ceph osd pool set .mgr crush_rule .mgr
```

I was expecting Rook to affect it automatically, but that wasn't the case. Is this normal or not?
