### ISSUE TITLE
Mechanism for applying config parameters to an CephObjectStore instance

### ISSUE THREAD

**Issue by jhoblitt** [rook/rook#14753]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Apply `ceph config set...` parameters to a rgw instance created by a `CephObjectStore` resource.

The addition of a `CephObjectStore.spec.parameters` field to accomplish this would be consistent with the existing `CephObjectStore.spec.metadataPool.parameters` and `CephObjectStore.spec.dataPool.parameters` fields.

**What is use case behind this feature:**

I would like to set `rgw_enable_usage_log` to `false` for new and pre-existing `CephObjectStore` CRs. Currently, this can be done by using `CephCluster.spec.cephConfig` but has several limitations.

1) It requires knowledge of how the operator names rgw instances.  E.g.

```yaml
cephClusterSpec:
  cephConfig:
    client.rgw.<CephObectStore name>.a:
      rgw_enable_usage_log: "false"
```

2) The operator will encounter an error when trying to apply `ceph config set <CephObjectStore name>.a` before the rgw instance has been registered as a valid `<who>` for `ceph config`.
