### ISSUE TITLE
Cannot successfully create CephObjectStore after the store has been deleted.

### ISSUE THREAD

**Issue by denppa** [rook/rook#14763]
* Bug Report

**Deviation from expected behavior:**

The rgw pod does not get created after the CephObjectStore CRDs has been deleted.

**Expected behavior:**

Spin up CephObjectStore with rgw pod even though the object store has been created before.

**How to reproduce it (minimal and precise):**

Create the following CRD:

```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: nextcloud-obj-store
  namespace: rook-ceph
spec:
  metadataPool:
    #failureDomain: host
    replicated:
      size: 3
  dataPool:
    #failureDomain: host
    replicated:
      size: 3
    quotas:
      maxSize: 5Ti
  preservePoolsOnDelete: true
  gateway:
    #sslCertificateRef:
    port: 80
    # securePort: 443
    instances: 1
```

```bash
kubectl create -f crd.yml
```

Then delete it:
```bash
kubectl delete -f crd.yml
# In a second shell
kubectl -n rook-ceph edit cephobjectstores.ceph.rook.io nextcloud-obj-store
# comment out the finalizer
```

Then create the obj store again, and it will fail. The `Progress` column of the below command will be `Failure`, and the `Progressing` and then loop. `rgw` pod will also fail to be created.

Monitor commands:
```bash
kubectl -n rook-ceph get pods --watch
kubectl -n rook-ceph get cephobjectstores.ceph.rook.io --watch
```

**Logs to submit**:
```
ceph-object-controller-detect-version-w995k         0/1     Pending           0             0s
ceph-object-controller-detect-version-w995k         0/1     Pending           0             0s
ceph-object-controller-detect-version-w995k         0/1     Init:0/1          0             0s
ceph-object-controller-detect-version-w995k         0/1     Init:0/1          0             0s
ceph-object-controller-detect-version-w995k         0/1     Init:0/1          0             1s
ceph-object-controller-detect-version-w995k         0/1     PodInitializing   0             3s
ceph-object-controller-detect-version-w995k         0/1     PodInitializing   0             3s
ceph-object-controller-detect-version-w995k         0/1     Terminating       0             3s
ceph-object-controller-detect-version-w995k         0/1     Terminating       0             4s
ceph-object-controller-detect-version-w995k         0/1     Terminating       0             4s
ceph-object-controller-detect-version-w995k         0/1     Completed         0             4s
ceph-object-controller-detect-version-w995k         0/1     Completed         0             5s
ceph-object-controller-detect-version-w995k         0/1     Completed         0
```

```
NAME                  PHASE         ENDPOINT                                                    SECUREENDPOINT   AGE
nextcloud-obj-store   Progressing   http://rook-ceph-rgw-nextcloud-obj-store.rook-ceph.svc:80                    43s
nextcloud-obj-store   Failure                                                                                    53s
nextcloud-obj-store   Progressing   http://rook-ceph-rgw-nextcloud-obj-store.rook-ceph.svc:80                    53s
nextcloud-obj-store   Failure
```

* Operator's logs, if necessary
```
Sorry, operator restarted and logs cleared.
```

**Cluster Status to submit**:
All healthy.

**Environment**:
* OS (e.g. from /etc/os-release): debian bookworm
* Kernel (e.g. `uname -a`): Debian 6.1.106-3
* Cloud provider or hardware configuration: baremetal
* Rook version (use `rook version` inside of a Rook Pod): 
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
```
sh-5.1$ rook version
2024/09/24 18:47:01 maxprocs: Leaving GOMAXPROCS=96: CPU quota undefined
rook: v1.15.2
go: go1.22.7
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): baremetal k8s
* Storage backend status:
```
ceph version 18.2.4 ... reef (stable)
```

**Temporary Solution**

It will succeed if I delete every rgw service typed pool, including the `.rgw.root` pool.
