### ISSUE TITLE
Allow setting options for CephObjectStore index pools

### ISSUE THREAD

**Issue by dvanders** [rook/rook#14769]
Assuming the recommended 100PGs/OSD rule of thumb in Ceph, a well configured RGW service needs around 90 PGs per OSD dedicated to data pools, around 5-10 PGs per OSD for index pools, and very few PGs for all the other meta pools.

CephObjectStore allows setting spec on metadataPool and dataPool, meaning we can set pg_num for data pools 👍 but not for the index pools individually.
OOTB today, without setting specific PG numbers, Rook relies on the Ceph internal pg autoscaler to set appropriate PG numbers. This works well for small clusters, but is not ideal for large clusters where high performance is expected from day 1.
(For RGW, the PG autoscaler starts with a low number of PGs per pool, then creates more PGs as data is added).

We will work with Ceph upstream to improve the PG autoscaling algorithm for RGW, but in any case sometimes operators will want to set pg_nums manually.

Proposal: create a new CephObjectStore spec "indexPool" with the same options as dataPool and metadataPool but operates on the index pools.

**Comment by travisn** [comment]
Any pool properties that can be set under the object [data pool](https://github.com/rook/rook/blob/release-1.15/deploy/examples/object.yaml#L29-L42) can also be set on the object [metadata pools](https://github.com/rook/rook/blob/release-1.15/deploy/examples/object.yaml#L14-L27). So if you set the following on the metadataPool, I believe you'll get the expected:
```yaml
spec:
  metadataPool:
    parameters:
      pg_num: "8"
```
The only limitation is really that the same parameters are applied to all the rgw metadata pools. For simplicity, Rook groups all the non-data pools together as the "metadata" pools.

**Comment by travisn** [comment]
After slack discussion with @jhoblitt I see now there is a specific need for the index pool parameters to be configured differently. Perhaps we could add the ability to override the parameters for a specific metadata pool, something like this:
```yaml
spec:
  metadataPool:
    parameterOverrides:
      - poolName: rgw.buckets.index
        parameters:
          pg_num: 1024
      - poolName: rgw.otp
        parameters:
          pg_num: 1
```
- If `parameterOverrides` specified for a particular pool, the main `parameters` would be ignored for that pool.
- Pool names would be `.rgw.root, rgw.control, rgw.meta, rgw.log, rgw.buckets.index, rgw.buckets.non-ec, rgw.otp` (no need for the object store prefix name, it would be added automatically internally by rook). 

@BlaineEXE @sp98 thoughts?
