### ISSUE TITLE
rgw: rook 1.15.3 ignores affinity settings in cephobjectstore

### ISSUE THREAD

**Issue by adippl** [rook/rook#14817]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I have 3 worker nodes, 2 cephobjectstore objects which create 3 RGW daemons on my k8s nodes.
1st cephobjectstore with 1 rgw is dedicated to replication
2nd cephobjectstore is for general use and has 2 replicas
Default affinity cannot reliabliy schedule all 3 rgw pod on separate nodes.
Scheduling 2 RGW on the same node causes crashes since first rgw to start binds to port :8000

I've tried to us affinity settings in cephobjectstore just like in this example https://github.com/rook/rook/blob/master/deploy/examples/object-b.yaml
They have no effects and rgw deployments seem to have default affinity settings.

Example of my cephobjectstore definition:
```
kind: CephObjectStore
metadata:
  name: s3-ssd-storage
  namespace: rook-ceph
spec:
  preservePoolsOnDelete: false
  gateway:
    port: 80
    instances: 2
    placement:
      podantiaffinity:
        preferredduringschedulingignoredduringexecution:
          - weight: 100
            podaffinityterm:
              labelselector:
                matchexpressions:
                  - key: app
                    operator: in
                    values:
                      - rook-ceph-rgw
              topologyKey: kubernetes.io/hostname
    resources:
      limits:
        memory: "1024Mi"
        cpu: "1000m"
      requests:
        cpu: "50m"
        memory: "1024Mi"
  zone:
    name: k8s2-zone
  hosting:
    advertiseEndpoint:
      dnsName: "s3.k8s2.<<removed>>"
      port: 443
      useTls: true
    dnsNames:
      - "s3.k8s2.<<removed>>"
```

Affinity in rgw deployment created by rook
```
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: rook-ceph-rgw
                `: s3-ssd-storage
                rgw: s3-ssd-storage
                rook_cluster: rook-ceph
                rook_object_store: s3-ssd-storage
            topologyKey: kubernetes.io/hostname
```

**Expected behavior:**

Rook should apply affinity from cephobjectstorage to created rgw deployments.

Or it shouldn't use `rook_object_store`, `rgw` and `ceph_daemon_id` in default affinity rules since all rgw pods run with host network and different cephobjectstore deployment can easily claim default port :8000 on the node.

**How to reproduce it (minimal and precise):**
Create 2 cephobjectstorage definitions on cluster with limited ammount of nodes.
When 2 RGW pods are scheduled on the same node, 2nd one cannot bind to :8000 because it's already taken.

**Environment**:
* OS: Gentoo
* Kernel: 6.6.51-gentoo-dist
* Cloud provider or hardware configuration: baremetal cluster
* Rook version (use `rook version` inside of a Rook Pod): 1.15.3
* Storage backend version : 18.2.4
* Kubernetes version : 1.29.1
* Kubernetes cluster type : vanilla kubernetes
* Storage backend status : HEALTH_WARN            2 daemons have recently crashed

**Comment by BlaineEXE** [comment]
It sounds like you are using host networking on the CephCluster. Host networking can be disabled on the CephObjectStore to prevent RGWs from competing for the same port locally.

I would encourage you to either disable host networking on the CephObjectStore or change the port used on each separate CephObjectStore.

I don't believe the Rook project can consider this a bug. Port management is a user config, and automatic port adjustment is outside of Rook's current intent.

**Comment by BlaineEXE** [comment]
Actually, as @sp98 and I talked about this, we realized that the issue is likely a matter of typos in the config.

Most headers in this snippet are not `camelCased`, which are case sensitive. 
```
      podantiaffinity:
        preferredduringschedulingignoredduringexecution:
          - weight: 100
            podaffinityterm:
              labelselector:
                matchexpressions:
                  - key: app
                    operator: in
                    values:
                      - rook-ceph-rgw
              topologyKey: kubernetes.io/hostname
```
