### ISSUE TITLE
RGW: custom name for default pool placement

### ISSUE THREAD

**Issue by arttor** [rook/rook#14864]
Currently, Rook will set pool placement as a default only if its name is equal to "default". 

```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
spec:
  sharedPools:
    poolPlacements:
    - name: default      # default placement
      metadataPoolName: "meta-pool"
      dataPoolName: "data-pool"
    - name: fast
      metadataPoolName: "fast-meta-pool"
      dataPoolName: "fast-data-pool"
```
With this approach is not possible to set custom name to default pool placement. 

Suggestion: intorduce a separate field `isDefault`:

```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
spec:
  sharedPools:
    poolPlacements:
    - name: slow 
      isDefault: true      # default placement
      metadataPoolName: "meta-pool"
      dataPoolName: "data-pool"
    - name: fast
      metadataPoolName: "fast-meta-pool"
      dataPoolName: "fast-data-pool"
```

**Motivation:**  Placement name is [used in s3 api](https://docs.ceph.com/en/reef/radosgw/placement/#s3-bucket-placement) as bucket region `s5cmd mb s3://<bucket-name> --region=<rgw-zonegroup-name>:<placement-name>`. Normally,  for default region user just leaves it empty but it should be possible to specify  default placement explicitly.
