### ISSUE TITLE
Feature Request: manage Endpoints resource containg the set of Mon IPs

### ISSUE THREAD

**Issue by haslersn** [rook/rook#14986]
## Feature Request

**What is use case behind this feature:**

I'm mounting a CephFS volume from inside a KubeVirt VM. I'd like to use a DNS name to access the mons.

**What should the feature do:**

The set of mon IPs can change, e.g., when Rook replaces a mon (aka. mon failover). There's a `rook-ceph-mon-endpoints` ConfigMap that contains the current set of mon IPs. However, using that requires attaching the ConfigMap to the KubeVirt VM. While that's possible, it's additional effort and has downsides: Either live migration is no longer possible (when mounting the ConfigMap via virtio-fs) or updates of the ConfigMap are not reflected inside the VM (when attaching the ConfigMap as a block device).

Therefore, it would be better to use a DNS name to resolve mon IPs. This can be achieved using an Endpoints resource, i.e., Rook should manage an Endpoints resource that contains the current set of mon IPs.

Currently I have the following manually created Service and Endpoints objects:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-active-mons
spec:
  clusterIP: None # headless service

---
apiVersion: v1
kind: Endpoints
metadata:
  name: rook-ceph-active-mons
subsets:
  - addresses:
      # These are Service IPs from the mon Services rook-ceph-mon-a, etc.
      - ip: 10.96.75.163
      - ip: 10.96.198.81
      - ip: 10.96.53.34
```

However, the Endpoints resource needs to be manually updated whenever the set of mon IPs changes. Thus it would be nice if Rook could manage such an Endpoints resource.
