### ISSUE TITLE
OSDs failing to start after node restart

### ISSUE THREAD

**Issue by 11qu1d** [rook/rook#15013]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

After a node restart (either due to a crash or intentional reboot), OSDs on the node fail to start with the below errors in the logs:

```
2024-11-15T04:30:33.895604307Z stderr F debug 2024-11-15T04:30:33.887+0000 7f419ea92640 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
2024-11-15T04:30:33.895835413Z stderr F debug 2024-11-15T04:30:33.891+0000 7f419f293640 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
2024-11-15T04:30:33.896003011Z stderr F failed to fetch mon config (--no-mon-config to skip)
```

The only way to fix this is to manually purge the OSD and reformat the disks before adding them back to the cluster. This causes issues as the OSDs needs to recover a lot of data before the cluster is in a healthy state again.

Please note that this can happen randomly on any of the nodes and in any cluster (currently hosting 2 distinct Ceph clusters in the same Kubernetes cluster).

Sounds similar to https://github.com/rook/rook/issues/14825, but i am not using LVM etc.

**Expected behavior:**

OSDs should normally start after a failure.

**How to reproduce it (minimal and precise):**

This happens intermittently after a node is restarted either manually rebooting it or due to a crash. I haven't found a consistent way to replicate it.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  annotations:
    meta.helm.sh/release-name: rook-ceph-cluster-ssd
    meta.helm.sh/release-namespace: rook-ceph
  finalizers:
    - cephcluster.ceph.rook.io
  generation: 9
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ssd
  namespace: rook-ceph
status:
  ceph:
    capacity:
      bytesAvailable: 2473628868608
      bytesTotal: 7681533640704
      bytesUsed: 5207904772096
      lastUpdated: '2024-11-15T04:38:28Z'
    details:
      OSD_DOWN:
        message: 1 osds down
        severity: HEALTH_WARN
      OSD_FLAGS:
        message: >-
          1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT}
          flags set
        severity: HEALTH_WARN
      OSD_HOST_DOWN:
        message: 1 host (1 osds) down
        severity: HEALTH_WARN
      PG_DEGRADED:
        message: >-
          Degraded data redundancy: 339814/1254627 objects degraded (27.085%),
          50 pgs degraded, 119 pgs undersized
        severity: HEALTH_WARN
    fsid: 7314f74a-45c3-481c-88b5-61edfaa82371
    health: HEALTH_WARN
    lastChanged: '2024-11-15T04:10:08Z'
    lastChecked: '2024-11-15T04:38:28Z'
    previousHealth: HEALTH_OK
    versions:
      mds:
        ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable): 2
      mgr:
        ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable): 2
      mon:
        ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable): 3
      osd:
        ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable): 3
      overall:
        ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable): 12
      rgw:
        ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable): 2
  conditions:
    - lastHeartbeatTime: '2024-11-15T04:22:01Z'
      lastTransitionTime: '2024-11-15T04:22:01Z'
      message: Configuring Ceph OSDs
      reason: ClusterProgressing
      status: 'True'
      type: Progressing
    - lastHeartbeatTime: '2024-11-15T04:38:28Z'
      lastTransitionTime: '2024-06-02T20:40:04Z'
      message: Cluster created successfully
      reason: ClusterCreated
      status: 'True'
      type: Ready
  message: Cluster created successfully
  observedGeneration: 9
  phase: Ready
  state: Created
  storage:
    deviceClasses:
      - name: ssd
    osd:
      storeType:
        bluestore: 4
  version:
    image: quay.io/ceph/ceph:v18.2.4
    version: 18.2.4-0
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.4
  cleanupPolicy:
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  crashCollector: {}
  csi:
    cephfs: {}
    readAffinity:
      enabled: false
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  external: {}
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 1m0s
      status:
        interval: 1m0s
    livenessProbe:
      mgr: {}
      mon: {}
      osd: {}
  labels:
    monitoring:
      release: kube-prometheus-stack
  logCollector:
    enabled: true
    maxLogSize: 500M
    periodicity: daily
  mgr:
    count: 2
    modules:
      - enabled: true
        name: rook
  mon:
    count: 3
  monitoring:
    enabled: true
  network:
    connections:
      compression: {}
      encryption: {}
    multiClusterService: {}
    provider: host
  priorityClassNames:
    mgr: system-cluster-critical
    mon: system-node-critical
    osd: system-node-critical
  resources:
    cleanup:
      limits:
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 100Mi
    crashcollector:
      limits:
        memory: 60Mi
      requests:
        cpu: 100m
        memory: 60Mi
    exporter:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 50Mi
    logcollector:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    mgr:
      limits:
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    mgr-sidecar:
      limits:
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 40Mi
    mon:
      limits:
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    osd:
      limits:
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 4Gi
    prepareosd:
      requests:
        cpu: 500m
        memory: 50Mi
  security:
    keyRotation:
      enabled: false
    kms: {}
  storage:
    flappingRestartIntervalHours: 0
    nodes:
      - devices:
          - name: /dev/disk/by-id/ata-SAMSUNG...
        name: node1
      - devices:
          - name: /dev/disk/by-id/ata-SAMSUNG...
        name: node2
      - devices:
          - name: /dev/disk/by-id/ata-SAMSUNG...
        name: node3
      - devices:
          - name: /dev/disk/by-id/ata-SAMSUNG...
        name: node4
    store: {}
    useAllDevices: false
  waitTimeoutForHealthyOSDInMinutes: 10
```

**Environment**:
* OS (e.g. from /etc/os-release): Debian GNU/Linux 12 (bookworm)
* Kernel (e.g. `uname -a`): Linux node2 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod): v1.15.4
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable)
* Kubernetes version (use `kubectl version`): v1.30.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubespray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_WARN 1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set
