### ISSUE TITLE
 CephObjectZone shared pools never configured if pools are not created before CephObjectZone

### ISSUE THREAD

**Issue by arttor** [rook/rook#15034]
How to reproduce:
1. Create pools together with zone or after creating zone `kubectl apply -f zone.yaml`:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: realm-b
  namespace: rook-ceph # namespace:cluster
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: zonegroup-b
  namespace: rook-ceph # namespace:cluster
spec:
  realm: realm-b
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: zone-b
  namespace: rook-ceph # namespace:cluster
spec:
  zoneGroup: zonegroup-b
  sharedPools:
    metadataPoolName: rgw-meta-pool
    dataPoolName: rgw-data-pool
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rgw-meta-pool
  namespace: rook-ceph # namespace:cluster
spec:
  failureDomain: osd
  replicated:
    size: 1
    requireSafeReplicaSize: false
  application: rgw
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rgw-data-pool
  namespace: rook-ceph # namespace:cluster
spec:
  failureDomain: osd
  replicated:
    size: 1
    requireSafeReplicaSize: false
  application: rgw
```
2. wait until zone and pools will be created
3. get zone json with toolbox:
```shell
kubectl -n rook-ceph exec -it deploy/rook-ceph-tools -- radosgw-admin zone get --rgw-zone=zone-b
```
4. see that zone pools and pool_placement were not modified with shared pools.

Reason:
CephObjectStoreZone controller:
1. creates zone
2. checks if pools exists - retuns error
3. on next reconcile [controller sees that zone already exists and exists without configuring zone shared pools](https://github.com/rook/rook/blob/fc456553b3cc56725cb1eb8f68717529ea34922e/pkg/operator/ceph/object/zone/controller.go#L252-L269)
