### ISSUE TITLE
skipping device "<device-name>" until the admin specifies it can be used by an osd

### ISSUE THREAD

**Issue by jdavidson-arturo** [rook/rook#15062]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When adding a device to the devices list of a node in the ceph-cluster CRD the device does not get added as an osd

**Expected behavior:**
When adding a device in the devices list for a given node the device is not added as an osd.

in the prepare-<node> pod I get the following log output

```
cephosd: skipping device "<device-name>" until the admin specifies it can be used by an osd
```

presumably from this line in the daemon
https://github.com/rook/rook/blob/master/pkg/daemon/ceph/osd/daemon.go#L548

It would seem then the list of desired devices is 0 for some reason?

**How to reproduce it (minimal and precise):**

my ceph-cluster has the following configuration subset

```yaml
spec:
  storage:
    nodes:
    - devices:
      - name: /dev/disk/by-id/wwn-<id1> # working osd
      - name: /dev/disk/by-id/wwn-<id2> # working osd
      - name: /dev/disk/by-id/wwn-<id3> # working osd
      - name: /dev/disk/by-id/wwn-<id4> # working osd
      - name: /dev/disk/by-id/wwn-<id5> # the one that is being skipped
      name: <server-name>
```

I have tried switching the name of the new disk to another id under `/dev/disk/by-id` that points to the same volume as well as `/dev/sdX` and simply `sdX`

**File(s) to submit**:
Can submit if needed

**Logs to submit**:

Log snippet that seems to be relevant is above but I can submit more logs if needed

**Cluster Status to submit**:

**Environment**:
* OS (e.g. from /etc/os-release): nixos
* Kernel (e.g. `uname -a`): Linux suezo 5.15.83 #1-NixOS SMP Wed Dec 14 10:37:31 UTC 2022 x86_64 GNU/Linux
* Cloud provider or hardware configuration: bare metal dell r720XD
* Rook version (use `rook version` inside of a Rook Pod): v1.10.0-alpha.0.478.ge1c6b1876 (not sure what that means, my helm chart is set to v1.11.11)
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
* Kubernetes version (use `kubectl version`): v1.31.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): nixos k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK
