### ISSUE TITLE
s3 website doesn't redirect to the index.html (RGW)

### ISSUE THREAD

**Issue by cybercoder** [rook/rook#15077]
The config override:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    rgw_enable_static_website = true
    rgw_enable_apis = s3, s3website
    
    [client.rgw]
    rgw_enable_static_website = true
    rgw_enable_apis = s3, s3website
```

The object store:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: hi53
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 1
  dataPool:
    failureDomain: host
    replicated:
      size: 1
  gateway:
    port: 80
    instances: 1
  hosting:
    dnsNames:
      - s3.hi53.ir
```
And configure the bucket to be public readable and website enabled.
```bash
aws --endpoint http://s3.hi53.ir s3 website s3://highscale-www/ --index-document index.html --error-document error.html
```

the url ```http://highscale-www.hi53.ir/index.html``` renders the html but the root uri (```http://highscale-www.hi53.ir```) tries to show object lists in the bucket instead of rendering index.html
I have checked the ingress, and direct curl to the service has same behavior.

You can check both links:

https://highscale-www.s3.hi53.ir/
https://highscale-www.s3.hi53.ir/index.html
