### ISSUE TITLE
Chart discover resources field not work

### ISSUE THREAD

**Issue by kingbj940429** [rook/rook#15079]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When using the `rook-ceph` helm chart version `1.15.6`, `.dicover.resources` does not work well.
```yaml
discover:
  ...
  # -- Add resources to discover daemon pods
  resources:
    - limits:
        memory: 512Mi
    - requests:
        cpu: 100m
        memory: 128Mi
```

occur a error below
```text
Error: YAML parse error on rook-ceph/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: did not find expected ',' or ']'
helm.go:84: [debug] error converting YAML to JSON: yaml: line 59: did not find expected ',' or ']'
YAML parse error on rook-ceph/templates/deployment.yaml
```

and if set below, errors disappear
```yaml
discover:
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
```

but not setting at resources actually
discover pod doesn't have resoruces

**Expected behavior:**
`.dicover.resources` works well

**How to reproduce it (minimal and precise):**
You can render the chart locally to observe this behavior:

```bash
helm template --namespace rook-ceph rook-ceph rook-release/rook-ceph -f values.yaml
```

The issue can be workarounded by configuring the value as a String:

```yaml
discover:
  resources:
    - limits:
        memory: 512Mi
    - requests:
        cpu: 100m
        memory: 128Mi
```

The issue can be workarounded by configuring the value as a String:
```yaml
{{- if .Values.discover.resources }}
        - name: DISCOVER_DAEMON_RESOURCES
          value: {{ .Values.discover.resources }}
{{- end }}
```

**Environment**:
* Rook version: 1.15.6

**Comment by sp98** [comment]
@kingbj940429 can you share the complete `values.yaml` file and `cephCluster` CR yaml files. Thanks.

**Comment by kingbj940429** [comment]
@sp98 

cephCluster.yaml
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: exam-rook-ceph
  namespace: storage-system
spec:
  monitoring:
    enabled: true
    metricsDisabled: false
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.4
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: efs-sc
        resources:
          requests:
            storage: 50Gi
  dashboard:
    enabled: true
    prometheusEndpoint: http://kube-prom-stack-prometheus.monitoring-system.svc:9090
    prometheusEndpointSSLVerify: false
  storage:
    storageClassDeviceSets:
      - name: set1-test
        count: 3
        portable: false
        encrypted: false
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 33Gi
              # IMPORTANT: Change the storage class depending on your environment (e.g. local-storage, gp2-csi)
              storageClassName: ebs-sc
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
    onlyApplyOSDPlacement: false
  resources:
    #The requests and limits set here, allow the mgr pod to use half of one CPU core and 1 gigabyte of memory
    mgr:
      limits:
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi
    # The above example requests/limits can also be added to the other components
    mon:
      limits:
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi
    osd:
      limits:
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi
```

override-values.yaml
```yaml
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 128Mi

logLevel: INFO

monitoring:
  enabled: true

enableDiscoveryDaemon: true
discoveryDaemonInterval: 60m

################################################################################
# CSI
################################################################################
csi:
  enableCephfsDriver: true
  enableRbdDriver: false
  disableCsiDriver: "false"

  # -- Enable host networking for CSI CephFS and RBD nodeplugins. This may be necessary
  # in some network configurations where the SDN does not provide access to an external cluster or
  # there is significant drop in read/write performance
  enableCSIHostNetwork: true

  enableCephfsSnapshotter: true
  enableNFSSnapshotter: false
  enableRBDSnapshotter: false
  enableCSIEncryption: false

  enableVolumeGroupSnapshot: true

  #-- for RBD Mirroring
  enableOMAPGenerator: true
  enableMetadata: true

  provisionerReplicas: 2

  logLevel: 0
  sidecarLogLevel: 0

  csiDriverNamePrefix: prefix-test

  enableLiveness: true

  nfs:
    enabled: false

  topology:
    enabled: true
    domainLabels:
      - topology.kubernetes.io/zone

  cephFSAttachRequired: true
  rbdAttachRequired: false
  nfsAttachRequired: false

################################################################################
# Discover
################################################################################
discover:
  #-- TODO: resources does not work well
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
```

**Comment by sp98** [comment]
Thanks @kingbj940429 Also the `rook-ceph-operator` deployment yaml.

**Comment by kingbj940429** [comment]
@sp98 

> Do you mean providing memory and cpu as string values like below works for you?

I tried like below
```yaml
discover:
  resources:
    - limits:
        memory: "512Mi"
    - requests:
        cpu: "100m"
        memory: "128Mi"
```

but same error
```text
Error: YAML parse error on rook-ceph/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: did not find expected ',' or ']'
helm.go:84: [debug] error converting YAML to JSON: yaml: line 59: did not find expected ',' or ']'
YAML parse error on rook-ceph/templates/deployment.yaml
```

**Comment by sp98** [comment]
@kingbj940429 Can you share the `rook-ceph-operator` output in yaml format?  Rook parses the `DISCOVER_DAEMON_RESOURCES` env present in the operator yaml.   
If the `DISCOVER_DAEMON_RESOURCES` env is present in the operator yaml and you still don't see the resources set correctly, can you check if there are any errors or warnings in your operator pod logs?  [This](https://github.com/rook/rook/blob/ea3947351fe2e5d5c21b9179c5612da29c1c6c17/pkg/operator/discover/discover.go#L93-L97) is where the resources are parsed by rook operator.

**Comment by kingbj940429** [comment]
@sp98 

First thank you for helping :)

rook operator shows log parse error
```text
2024-12-02 11:58:34.919427 W | op-discover: failed to parse.map[limits:map[memory:512Mi] requests:map[cpu:100m memory:256Mi]] json: cannot unmarshal string into Go value of type k8sutil.resourcesRequirements
```

when uses `.resources`
```yaml
discover:
  resources:
    - limits:
        memory: "512Mi"
    - requests:
        cpu: "100m"
        memory: "128Mi"
```

below is a result when use above `.resources`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-operator
spec:
     ....
    spec:
      containers:
      - name: rook-ceph-operator
        image: "docker.io/rook/ceph:v1.15.6"
        imagePullPolicy: IfNotPresent
        args: ["ceph", "operator"]
        env:
        - name: ROOK_CURRENT_NAMESPACE_ONLY
          value: "false"
        - name: DISCOVER_TOLERATIONS
          value: "- effect: NoExecute\n  key: karpenter.lunit.in/node-pool-name\n  operator: Equal\n  value: storage-system"
        - name: DISCOVER_AGENT_NODE_AFFINITY
          value: "karpenter.lunit.in/node-pool-name=storage-system"
        - name: DISCOVER_DAEMON_RESOURCES
          value: [map[limits:map[memory:512Mi]] map[requests:map[cpu:100m memory:128Mi]]]
```

and occurs helm error
```text
Error: YAML parse error on rook-ceph/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: did not find expected ',' or ']'
helm.go:84: [debug] error converting YAML to JSON: yaml: line 59: did not find expected ',' or ']'
YAML parse error on rook-ceph/templates/deployment.yaml
```


If use `.resources` like below
```yaml
discover:
  resources:
    limits:
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
```

show deployment yaml like below
```yaml
        env:
        - name: ROOK_CURRENT_NAMESPACE_ONLY
          value: "false"
        - name: DISCOVER_TOLERATIONS
          value: "- effect: NoExecute\n  key: karpenter.lunit.in/node-pool-name\n  operator: Equal\n  value: storage-system"
        - name: DISCOVER_AGENT_NODE_AFFINITY
          value: "karpenter.lunit.in/node-pool-name=storage-system"
        - name: DISCOVER_DAEMON_RESOURCES
          value: map[limits:map[memory:512Mi] requests:map[cpu:100m memory:128Mi]]
```

and no helm error, but it works actually.
