### ISSUE TITLE
Support custom node names

### ISSUE THREAD

**Issue by arttor** [rook/rook#15183]
**Feature Request**

**What should the feature do:**
Define host with custom node label:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
spec:
  placement:
    # if empty, then "kubernetes.io/hostname" will be used
    customNodeHostLabel: "example.com/node-name"
...
```

**What is use case behind this feature:**
Currently, Rook is using well-known `"kubernetes.io/hostname"` label to define node name. This node name is then used as: 
- node name in [device filters](https://rook.io/docs/rook/v1.9/CRDs/Cluster/host-cluster/#specific-nodes-and-devices) and other node settings in `CephCluster` CRD.
- as `host` in [CRUSH rules](https://rook.io/docs/rook/v1.9/CRDs/Cluster/ceph-cluster-crd/#osd-topology)
- probably, in other places

The problem is that in some environments it is not possible to have fixed hostname for logical node. E.g. there might be a pool of compute VMs with mounted devices. In such cases it is hard to rely on `"kubernetes.io/hostname"` or on node name and it would be useful to have a custom label for logical node name which can be managed by user like it is done for other [topology labels](https://rook.io/docs/rook/v1.9/CRDs/Cluster/ceph-cluster-crd/#osd-topology) (`topology.rook.io/room`, `topology.rook.io/rack`, etc...).

**Environment**:
Host-based Rook cluster.

**Questions**
1. What are the chances that this feature will be merged if we will implement it?
2. What are potentials problems or difficulties with moving away from `"kubernetes.io/hostname"` label?

**Comment by travisn** [comment]
Sounds like this feature will essentially allow portable mons and OSDs for the host-based clusters, similar to the portable mons and OSDs for the cluster-on-pvc. This just puts the burden of host name management on some higher level management tool that has to ensure the volumes are mounted on the correct host. If there is any way to reconsider using cluster-on-pvc, the feature is already available for portable daemons. You would just need to create local PVs that are bound to a particular host name label that you choose. 

If you want to pursue this feature for host-based clusters, I imagine there are several places to track down where we have assumed the `kubernetes.io/hostname` as you already mentioned. Probably it won't require much code change, but at the same time it could be a challenge. 

For a label name, perhaps consider using the label `topology.rook.io/hostname` to be consistent with other rook topology labels, then we wouldn't even need to define a new property in the cephcluster CR. For example, rook would just detect that label on the nodes and use it instead of the other hostname label.

**Comment by arttor** [comment]
> For a label name, perhaps consider using the label `topology.rook.io/hostname` to be consistent with other rook topology labels, then we wouldn't even need to define a new property in the cephcluster CR

Sounds great.

**Comment by arttor** [comment]
@travisn @BlaineEXE I've started with implementation and there is one place where i see potential problem. 

My current idea is to use `topology.rook.io/hostname` label and fallback to `kubernetes.io/hostname`. It was quite easy to support it in CRUSH rules but i am not sure how to implement fallback logic in K8s Node/Pod Affinity expressions, which are heavily used in Rook:
```yaml
       # according to K8s docs, multiple matchExpressions are AND-ed.
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
```

So affinity logic could be implementied in the following way:
1. reconcile Nodes and copy `kubernetes.io/hostname` value into `topology.rook.io/hostname` label if `topology.rook.io/hostname` was not presented. 
2. Always use `topology.rook.io/hostname`  in all affinity expressions

But in this case all exising installations will be updated and all pods will be restarted on version upgrade.

Because of this now i am in favor of using `customNodeHostLabel` in `CephCluster` CRD.

What do you think?
