### ISSUE TITLE
Caps Not Being Added to RGW Users via radosgw-admin in Rook-Ceph

### ISSUE THREAD

**Issue by Rmaabari** [rook/rook#15201]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When attempting to add or modify capabilities (caps) for an RGW user using radosgw-admin in a Rook-Ceph-managed cluster, the capabilities are not applied. Additionally, no error or warning is displayed, leaving the issue untraceable.

**Expected behavior:**
The radosgw-admin user modify command should successfully add the specified capabilities (caps) to the RGW user, and the caps field should reflect the changes in the output of radosgw-admin user info.

**How to reproduce it (minimal and precise):**
Deploy a CephCluster managed by Rook in Kubernetes.
Create an RGW user using:

`radosgw-admin user create --uid=test-user --display-name="Test User"`
Attempt to add capabilities (caps) to the user:

`radosgw-admin user modify --uid=test-user --caps="buckets=*;objects=*"`

Verify the user's information:

`radosgw-admin user info --uid=test-user`

Observe that the caps field remains empty in the output, and no error or warning is shown during the operation.
**File(s) to submit**:

CephCluster Custom Resource (CR):
```
spec:
  cephConfig:
    global:
      osd_pool_default_size: "1"
    client.rgw:
      rgw_enable_ops: "true"
      rgw_op_mask: "read, write, delete, list, setattrs, getattrs"
      rgw_default_user_policy: "full-access"
  cephVersion:
    image: quay.io/ceph/ceph:v18
  storage:
    useAllDevices: false
    devices:
    - name: vdb

```
* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:
No logs show any errors during the radosgw-admin operation.

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): 22.04
* Kernel (e.g. `uname -a`): 5.15.0-124-generic
* Cloud provider or hardware configuration: hardware
* Rook version (use `rook version` inside of a Rook Pod): 1.3.15
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.2
* Kubernetes version (use `kubectl version`): v1.26.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
