### ISSUE TITLE
Set of small problems with multi-node build env

### ISSUE THREAD

**Issue by dmick** [rook/rook#1520]
**Bug Report**

What happened:

Trying to build with the recommended procedure in https://github.com/rook/rook/blob/master/Documentation/development-environment.md, I encounter several issues:

1) build-rook.sh tries to preserve existing .kube/config's, but doesn't check to see if the existing config is already the rook version, so generates multiple backup files containing the same info (easily fixed)

2) the system sets up an insecure docker registry on the host at 172.17.8.1:5000, but doesn't appear to configure insecure access to it (unlike the original design when building on the VMs, which adds flags to the invocation of docker).  The only workaround I'm aware of is to edit /etc/docker/daemon.json and add  ```"insecure-registries":  ["172.17.8.1:5000"]``` but perhaps there's something less ... global and permanent?..

3) the script still recommends "Now run purge-ceph.sh from your host.", but I believe that's done on the VMs by purge_ceph_vms?  in any event there's no purge-ceph.sh available to run... ?

4) the final step, restarting the operator and cluster, fail with an error I don't understand yet:  

```
+ run_rook
+ cd /home/dmick/go/src/github.com/rook/rook/cluster/examples/kubernetes/
+ kubectl create -f rook-operator.yaml
namespace "rook-system" created
clusterrole "rook-operator" created
serviceaccount "rook-operator" created
clusterrolebinding "rook-operator" created
deployment "rook-operator" created
+ kubectl create -f rook-cluster.yaml
namespace "rook" created
error: unable to recognize "rook-cluster.yaml": no matches for rook.io/, Kind=Cluster
```

I could use some help deciphering that.  The rook operator pod seems healthy:

```po/rook-operator-6b7cdbdbb4-n9s62   1/1       Running   0          33m```

here are the noncommented lines in rook-cluster.yaml:

```
apiVersion: v1
kind: Namespace
metadata:
  name: rook
---
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  backend: ceph
  hostNetwork: false
  monCount: 3
  resources:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: ^sd.
    metadataDevice:
    location:
    storeConfig:
      storeType: bluestore
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu Artful
* Kernel (e.g. `uname -a`): 4.13.0-32-generic #35-Ubuntu SMP
* Cloud provider or hardware configuration: 9 vagrant VMs

* Rook version (use `rook version` inside of a Rook Pod): fcb01efe048d6bdc7ebdecfe4cbfbba7cb6dcb6b

* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Vagrant VMs
