### ISSUE TITLE
Mon does not start with RunContainerError

### ISSUE THREAD

**Issue by maitredede** [rook/rook#15231]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Cluster is not created, mon pods fails to start `RunContainerError` :

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: failed to fulfil mount request: open /run/containerd/io.containerd.runtime.v2.task/k8s.io/mon/rook-ceph/log: no such file or directory
```

**Expected behavior:**

mon pods starting, and cluster created.

**How to reproduce it (minimal and precise):**

It is an initial installation : created a bare metal kubernetes cluster :
- created nodes on virtual machines (proxmox)
- debian 12 (bookworm)
- containerd 2.0.1
- kubeadm 1.30
- rook installed with helm chart rook-ceph-v1.16.0
- cluster created with kubectl apply

**File(s) to submit**:

chart values :

```yaml
csi:
  clusterName: mycluster
  enableLiveness: true
  enableMetadata: true
  pluginNodeAffinity: null
  pluginTolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  provisionerNodeAffinity: null
  provisionerTolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
nodeSelector:
  node-role.kubernetes.io/control-plane: null
tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/control-plane
  operator: Exists
```

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph # namespace:cluster
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.0
    allowUnsupported: false
  network:
    connections:
      requireMsgr2: true
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/storage
                  operator: Exists
      podAffinity:
      podAntiAffinity:
      topologySpreadConstraints:
      tolerations:
        - key: node-role.kubernetes.io/storage
          operator: Exists
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: vstore-1
        devices:
          - name: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"
          - name: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi2"
  csi:
    readAffinity:
      enabled: true
```

**Logs to submit**:

* Operator's logs, if necessary

```
2025-01-02 20:28:59.066408 E | ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph monitors: failed to assign pods to mons: failed to schedule mons
2025-01-02 20:28:59.092298 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2025-01-02 20:28:59.173808 I | ceph-spec: parsing mon endpoints: 
2025-01-02 20:28:59.173968 W | ceph-spec: ignoring invalid monitor 
2025-01-02 20:28:59.209788 W | ceph-cluster-controller: mon count should be at least 1, will use default value of 3
2025-01-02 20:28:59.330399 I | ceph-spec: detecting the ceph image version for image quay.io/ceph/ceph:v19.2.0...
2025-01-02 20:29:02.625250 I | ceph-spec: detected ceph image version: "19.2.0-0 squid"
2025-01-02 20:29:02.625355 I | ceph-cluster-controller: validating ceph version from provided image
2025-01-02 20:29:02.650390 I | ceph-spec: parsing mon endpoints: 
2025-01-02 20:29:02.650447 W | ceph-spec: ignoring invalid monitor 
2025-01-02 20:29:02.669620 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2025-01-02 20:29:02.671690 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2025-01-02 20:29:02.871250 E | ceph-cluster-controller: failed to get ceph daemons versions, this typically happens during the first cluster initialization. failed to run 'ceph versions'. . unable to get monitor info from DNS SRV with service name: ceph-mon
[errno 2] RADOS object not found (error connecting to the cluster): exit status 1
2025-01-02 20:29:02.871294 I | ceph-cluster-controller: cluster "rook-ceph": version "19.2.0-0 squid" detected for image "quay.io/ceph/ceph:v19.2.0"
2025-01-02 20:29:02.942139 I | op-mon: start running mons
2025-01-02 20:29:02.950690 I | ceph-spec: parsing mon endpoints: 
2025-01-02 20:29:02.951045 W | ceph-spec: ignoring invalid monitor 
2025-01-02 20:29:03.136428 I | op-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":[],"cephFS":{"netNamespaceFilePath":"","subvolumeGroup":"","radosNamespace":"","kernelMountOptions":"","fuseMountOptions":""},"rbd":{"netNamespaceFilePath":"","radosNamespace":"","mirrorDaemonCount":0},"nfs":{"netNamespaceFilePath":""},"readAffinity":{"enabled":false,"crushLocationLabels":null},"namespace":""}] data: mapping:{"node":{}} maxMonId:-1 outOfQuorum:]
2025-01-02 20:29:03.737689 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2025-01-02 20:29:03.739044 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2025-01-02 20:29:05.337898 I | op-mon: targeting the mon count 3
2025-01-02 20:29:05.369104 I | op-mon: created canary deployment rook-ceph-mon-a-canary
2025-01-02 20:29:05.393394 I | op-mon: created canary deployment rook-ceph-mon-b-canary
2025-01-02 20:29:05.437566 I | op-mon: created canary deployment rook-ceph-mon-c-canary
2025-01-02 20:29:06.138540 I | op-mon: canary monitor deployment rook-ceph-mon-a-canary scheduled to vstore-1
2025-01-02 20:29:06.138576 I | op-mon: mon a assigned to node vstore-1
2025-01-02 20:29:06.335116 I | op-mon: canary monitor deployment rook-ceph-mon-b-canary scheduled to vmaster-3
2025-01-02 20:29:06.335325 I | op-mon: mon b assigned to node vmaster-3
```

Due to node taints, only 2 on 3 mons can be created, but none are starting.

* Crashing pod(s) logs, if necessary

`kubectl describe pod rook-ceph-mon-b-canary-7c66c7bb48-pfjdx`

```
Name:             rook-ceph-mon-b-canary-7c66c7bb48-pfjdx
Namespace:        rook-ceph
Priority:         0
Service Account:  rook-ceph-default
Node:             vmaster-3/10.115.5.3
Start Time:       Fri, 03 Jan 2025 07:31:38 +1100
Labels:           app=rook-ceph-mon
                  app.kubernetes.io/component=cephclusters.ceph.rook.io
                  app.kubernetes.io/created-by=rook-ceph-operator
                  app.kubernetes.io/instance=b
                  app.kubernetes.io/managed-by=rook-ceph-operator
                  app.kubernetes.io/name=ceph-mon
                  app.kubernetes.io/part-of=rook-ceph
                  ceph_daemon_id=b
                  ceph_daemon_type=mon
                  mon=b
                  mon_canary=true
                  mon_cluster=rook-ceph
                  pod-template-hash=7c66c7bb48
                  rook.io/operator-namespace=rook-ceph
                  rook_cluster=rook-ceph
Annotations:      cni.projectcalico.org/containerID: 41092bcfcfe3b905f241b26a55c47e02b08d5a5e4e7000fa1a07e5277bdae66c
                  cni.projectcalico.org/podIP: 10.117.4.51/32
                  cni.projectcalico.org/podIPs: 10.117.4.51/32
Status:           Running
IP:               10.117.4.51
IPs:
  IP:           10.117.4.51
Controlled By:  ReplicaSet/rook-ceph-mon-b-canary-7c66c7bb48
Containers:
  mon:
    Container ID:  containerd://1d586a1699ef11ede09deb1ee9b450877e0dfbf17905723af8e19fc195b82018
    Image:         docker.io/rook/ceph:v1.16.0
    Image ID:      docker.io/rook/ceph@sha256:00293ae7c38db238c773d76fc9655e99cf0dba4dba4b74918773248831531dae
    Port:          3300/TCP
    Host Port:     0/TCP
    Command:
      sleep
    Args:
      3600
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: failed to fulfil mount request: open /run/containerd/io.containerd.runtime.v2.task/k8s.io/1d586a1699ef11ede09deb1ee9b450877e0dfbf17905723af8e19fc195b82018/rook-ceph/log: no such file or directory
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 11:00:00 +1100
      Finished:     Fri, 03 Jan 2025 07:32:17 +1100
    Ready:          False
    Restart Count:  3
    Environment:
      CONTAINER_IMAGE:                quay.io/ceph/ceph:v19.2.0
      POD_NAME:                       rook-ceph-mon-b-canary-7c66c7bb48-pfjdx (v1:metadata.name)
      POD_NAMESPACE:                  rook-ceph (v1:metadata.namespace)
      NODE_NAME:                       (v1:spec.nodeName)
      POD_MEMORY_LIMIT:               node allocatable (limits.memory)
      POD_MEMORY_REQUEST:             0 (requests.memory)
      POD_CPU_LIMIT:                  node allocatable (limits.cpu)
      POD_CPU_REQUEST:                0 (requests.cpu)
      CEPH_USE_RANDOM_NONCE:          true
      ROOK_MSGR2:                     msgr2_true_encryption_false_compression_false
      ROOK_CEPH_MON_HOST:             <set to the key 'mon_host' in secret 'rook-ceph-config'>             Optional: false
      ROOK_CEPH_MON_INITIAL_MEMBERS:  <set to the key 'mon_initial_members' in secret 'rook-ceph-config'>  Optional: false
      ROOK_POD_IP:                     (v1:status.podIP)
    Mounts:
      /etc/ceph from rook-config-override (ro)
      /etc/ceph/keyring-store/ from rook-ceph-mons-keyring (ro)
      /var/lib/ceph/crash from rook-ceph-crash (rw)
      /var/lib/ceph/mon/ceph-b from ceph-daemon-data (rw)
      /var/log/ceph from rook-ceph-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bbdd8 (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  rook-config-override:
    Type:               Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:      rook-config-override
    ConfigMapOptional:  <nil>
  rook-ceph-mons-keyring:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-mons-keyring
    Optional:    false
  rook-ceph-log:
    Type:          HostPath (bare host directory volume)
    Path:          rook-ceph/log
    HostPathType:  
  rook-ceph-crash:
    Type:          HostPath (bare host directory volume)
    Path:          rook-ceph/crash
    HostPathType:  
  ceph-daemon-data:
    Type:          HostPath (bare host directory volume)
    Path:          mon-b/data
    HostPathType:  
  kube-api-access-bbdd8:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node-role.kubernetes.io/control-plane op=Exists
                             node-role.kubernetes.io/storage op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  68s                default-scheduler  Successfully assigned rook-ceph/rook-ceph-mon-b-canary-7c66c7bb48-pfjdx to vmaster-3
  Normal   Pulled     29s (x4 over 67s)  kubelet            Container image "docker.io/rook/ceph:v1.16.0" already present on machine
  Normal   Created    29s (x4 over 67s)  kubelet            Created container mon
  Warning  Failed     29s (x4 over 67s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: failed to fulfil mount request: open /run/containerd/io.containerd.runtime.v2.task/k8s.io/mon/rook-ceph/log: no such file or directory
  Warning  BackOff    1s (x7 over 66s)   kubelet            Back-off restarting failed container mon in pod rook-ceph-mon-b-canary-7c66c7bb48-pfjdx_rook-ceph(1e7a363f-7d7d-4dbf-8334-e42abad4349b)
```

**Environment**:
* OS (e.g. from /etc/os-release): `Debian GNU/Linux 12 (bookworm)`
* Kernel (e.g. `uname -a`): `Linux vstore-1 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux`
* Cloud provider or hardware configuration: virtual machine on proxmox, manual installation 
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.16.0 go: go1.23.4`
* Storage backend version (e.g. for ceph do `ceph -v`): `N/A` (does not  start)
* Kubernetes version (use `kubectl version`): `Server Version: v1.30.8`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare metal, containerd 2.0.1, installed with kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): `N/A` (does not  start)

**Comment by travisn** [comment]
Does your env allow creating containers with host path volumes? It appears to be failing on the log folder, which is the first host path volume in the pod spec. For example, Rook's [SCC](https://github.com/rook/rook/blob/master/deploy/examples/operator-openshift.yaml#L39) grants permissions for the host path volume.

**Comment by maitredede** [comment]
Hi @travisn, my installation has no special configuration. It is virtualized debian machines, configured with kubeadm, and no special configuration. I don't know if and how hostpath usage could be denied.

The only thing that looks suspicious to me would be that the hostPath in the pod spec is not rooted : 
```yaml
  volumes:
  - hostPath:
      path: rook-ceph/log
      type: ""
    name: rook-ceph-log
 ```
 And it looks like that on the host a path `/rook-ceph/log` is created.

**Comment by maitredede** [comment]
Found the problem :

I did not set the `dataDirHostPath` in my cluster spec :

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
spec:
  # The path on the host where configuration files will be persisted. Must be specified. If there are multiple clusters, the directory must be unique for each cluster.
  # Important: if you reinstall the cluster, make sure you delete this directory from each host or else the mons will fail to start on the new cluster.
  # In Minikube, the '/data' directory is configured to persist across reboots. Use "/data/rook" in Minikube environment.
  dataDirHostPath: /var/lib/rook
  ```
  
  Maybe setting a default common value, or raising a validation error should be more helpfull :)
