### ISSUE TITLE
OBCs with bucketPolicy set causes operator to fail to watch them, does not seem to apply policy

### ISSUE THREAD

**Issue by ibotty** [rook/rook#15241]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When I have OBCs like the following, I get errors in the operator and it looks like the policy is not applied.

```yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: my-obc
spec:
  additionalConfig:
    bucketPolicy:
      Statement:
      - Action:
        - s3:GetObject
        Effect: Allow
        Principal:
          AWS:
          - arn:aws:iam:::user/my-user
        Resource:
        - arn:aws:s3:::my-bucket/*
        Sid: my-sid
      Version: "2012-10-17"
  bucketName: my-bucket
  storageClassName: rook-ceph-bucket
```

I get the following error.

```
rook-ceph-operator-57c5b644bb-2vbd7 rook-ceph-operator W0107 12:16:22.844122       1 reflector.go:569] pkg/mod/k8s.io/client-go@v0.32.0/tools/cache/reflector.go:251: failed to list *v1alpha1.ObjectBucketClaim: json: cannot unmarshal object into Go struct field ObjectBucketClaimSpec.items.spec.additionalConfig of type string
rook-ceph-operator-57c5b644bb-2vbd7 rook-ceph-operator E0107 12:16:22.844150       1 reflector.go:166] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.32.0/tools/cache/reflector.go:251: Failed to watch *v1alpha1.ObjectBucketClaim: failed to list *v1alpha1.ObjectBucketClaim: json: cannot unmarshal object into Go struct field ObjectBucketClaimSpec.items.spec.additionalConfig of type string" logger="UnhandledError"
```

There is no debug output.  But it might be, that I did not enable it correctly in the helm chart (I set `logLevel: DEBUG`, but that did not have any effect).

**Expected behavior:**

It works.

**How to reproduce it (minimal and precise):**
s.a.

Ceph status:
```
  cluster:
    id:     d03bf2ad-0d00-4936-be6c-196160f1c4d7
    health: HEALTH_OK

  services:
    mon: 5 daemons, quorum c,g,n,o,p (age 8d)
    mgr: b(active, since 8d), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 29 osds: 29 up (since 8d), 29 in (since 8w)
    rgw: 2 daemons active (2 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   16 pools, 489 pgs
    objects: 18.55M objects, 45 TiB
    usage:   77 TiB used, 340 TiB / 417 TiB avail
    pgs:     456 active+clean
             18  active+clean+scrubbing
             15  active+clean+scrubbing+deep

  io:
```

**Environment**:
* OS (e.g. from /etc/os-release): -
* Kernel (e.g. `uname -a`): -
* Cloud provider or hardware configuration: -
* Rook version (use `rook version` inside of a Rook Pod): 1.16.1
* Storage backend version (e.g. for ceph do `ceph -v`): 19.2.0
* Kubernetes version (use `kubectl version`):
Kubernetes Version: v1.30.6-dirty
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OKD-SCOS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): `HEALTH_OK`

**Comment by BlaineEXE** [comment]
@jhoblitt are you able to take a look at this?

**Comment by ibotty** [comment]
Ah, of course it is 1.16.1.  Sorry.

It happened with 1.16.0 as well, so it's not a regression.

**Comment by jhoblitt** [comment]
@ibotty Here's an example from the acceptance tests:
https://github.com/rook/rook/blob/master/tests/integration/ceph_object_test.go#L431-L451
https://github.com/rook/rook/blob/master/tests/integration/ceph_object_test.go#L485-L487

**Comment by ibotty** [comment]
Thank you for your answer.

That's interesting.  I was pretty sure I tried that but kubernetes was not accepting it like that.

I'll check tomorrow.

**Comment by ibotty** [comment]
I could not let it rest.  It works like you said it would.  I did not check whether the policies get applied, but I assume so.

Can it be changed that passing an object is not accepted by kubernetes?

**Comment by BlaineEXE** [comment]
Each the opaque parameters are a `map[string]string` type, so the behavior can't really be changed.

**Comment by BlaineEXE** [comment]
I see the question now. To be honest, I'm not sure. Now that you mention it, I would think that it should have rejected the YAML object already, since its type is string. We would first have to understand what mechanism allowed that to be accepted to know whether it can be resolved. Is that something you want to investigate?

**Comment by ibotty** [comment]
Yes, I want.

First thing, the schema is allowing anything in `additionalConfig`
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
  name: objectbucketclaims.objectbucket.io
spec:
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              additionalConfig:
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
```

so the type `map[string]string` is mapped to a `map[string]"anything"`.  I don't know how that can be changed without enumerating every possible key in `additionalConfig`.
