### ISSUE TITLE
Is it possible to change object size on pool level or storage class level?

### ISSUE THREAD

**Issue by networkingana** [rook/rook#15339]
I want to change the object size from 4MiB to 1MiB, but I couldn't find any configuration options in the documentation, am I missing something?
To be precise this is the size I'm talking about

```
kubectl exec -it pod/rook-ceph-tools-68bf47bc65-pvfff -n rook-ceph -- rbd info ceph-osd-replica-1/csi-vol-12291e2c-66f5-47c2-a363-0dce15547fb6
rbd image 'csi-vol-12291e2c-66f5-47c2-a363-0dce15547fb6':
        size 90 GiB in 23040 objects
        order 22 (4 MiB objects)
        snapshot_count: 0
        id: 8653b7cf8b9376
        block_name_prefix: rbd_data.8653b7cf8b9376
        format: 2
        features: layering, exclusive-lock, object-map, fast-diff, deep-flatten
        op_features:
        flags:
        create_timestamp: Thu Jan 23 19:41:46 2025
        access_timestamp: Thu Jan 23 19:41:46 2025
        modify_timestamp: Thu Jan 23 19:41:46 2025
```

Thank you
