### ISSUE TITLE
`kubernetes` catch-all finalizer on ObjectBucketClaim is not honored correctly

### ISSUE THREAD

**Issue by jehutyy** [rook/rook#15340]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

`kubernetes` finalizer set on ObjectBucket and ObjectBucketClaim should prevent accidental deletion of said resources but doesn't.

**Expected behavior:**

It should behave in the same manner as `kubernetes` finalizer on pvc / pv (and any other k8s resource) which is : prevent from deletion while finalizer is yet to be removed.

**How to reproduce it (minimal and precise):**
1. Apply following obc descriptor : 
```
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: test-with-finalizer
  namespace: test
spec:
  generateBucketName: foo
  storageClassName: an-encrypted-ceph-bucket-sc
```

2. Set `finalizer: ["kubernetes"]` with tool of your choice.

e.g : 
`kubectl patch obc test-with-finalizer -p '{"metadata": {"finalizers": ["kubernetes"]}}'`

3. Delete obc test-with-finalizer
`kubectl delete obc test-with-finalizer`

4. Observe that obc is stuck terminating as expected but ob is instantly removed as well as backing bucket

From there, a `kubernetes` finalizer on : 
* obc : should not remove ob until obc is effectively removed
* ob : should not remove bucket until ob is effectively removed

**Environment**:
* OS (e.g. from /etc/os-release): RockyLinux 8.10
* Kernel (e.g. `uname -a`): 4.18.0-553.8.1.el8_10.x86_6
* Cloud provider or hardware configuration: On Prem, rke 1.6.3 
* Rook version (use `rook version` inside of a Rook Pod): v1.14.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 18.2.2 (531c0d11a1c5d39fbfe6aa8a521f023abf3bf3e2) reef (stable)
* Kubernetes version (use `kubectl version`): v1.30.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): rke 1.6.3
