### ISSUE TITLE
Filesystem Mirroring doesn't add snapshot mirror directory

### ISSUE THREAD

**Issue by Macwin00X** [rook/rook#15363]
Hello, 

I have enabled Ceph filesystem mirroring with this documentation https://rook.io/docs/rook/latest/Storage-Configuration/Shared-Filesystem-CephFS/filesystem-mirroring/, the snapshots are schedule on my source cluster but never sent to my backup cluster.
I noticed that directory_count is set to zero:

```
bash-5.1$ ceph fs snapshot mirror daemon status | jq
[
  {
    “daemon_id: 277923,
    “filesystems": [
      {
        “filesystem_id": 1,
        “name": ‘test-fs’,
        “directory_count": 0,
        “peers": [
          {
            “uuid": ‘1fcdcc5f-c913-48aa-86f6-3eab5a2ff1b9’,
            “remote": {
              “client_name": ‘client.mirror’,
              “cluster_name": ‘582b7cdb-0605-4554-94c3-a80ed0581bd4’,
              “fs_name": ”test-fs”
            },
            “stats": {
              “failure_count": 0,
              “recovery_count": 0
            }
          }
        ]
      }
    ]
  }
]
```

If I manually add a directory from the toolbox, the snapshots are synchronized with my backup cluster. 

```
bash-5.1$ ceph fs snapshot mirror add test-fs /
```

is it normal to have to add the directory manually? 

Here is my cephfilesystem configuration:

```
    mirroring:
      enabled: true
      peers:
        secretNames:
        - backup-01-peer-secret
      snapshotRetention:
      - duration: 6h
        path: /
      snapshotSchedules:
      - interval: 1h
        path: /

```
