### ISSUE TITLE
Operator pod crash loop during bucket provisioning

### ISSUE THREAD

**Issue by logan2211** [rook/rook#15374]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The operator pod crashes approximately 1 minute after startup in an endless loop. The crash seems to occur during OBC provisioning. It does not happen on the same bucket each time.

**How to reproduce it (minimal and precise):**

I'm not sure what is causing it or how to reproduce it.

**Logs to submit**:

Operator log with debug mode enabled is attached. [operator-log.txt](https://github.com/user-attachments/files/18699562/operator-log.txt)

The crash generally happens in the same way each time:

```
1 controller.go:341] "msg"="provisioning" "bucket"="mimir-cf4a08ed-3965-4bf9-af04-4534af54e179" "key"="monitoring/mimir-bucket"
op-bucket-prov: initializing and setting CreateOrGrant services
op-bucket-prov: getting storage class "ceph"
operator: shutdown signal received, exiting... context canceled
```

Sometimes during the failure it throws an error like this:
```
1 manager.go:148] "msg"="stopping provisioner" "key"="gitlab/gitlab-lfs" "name"="rook-ceph.ceph.rook.io/bucket" "reason"="context canceled"
1 controller.go:204] "Unhandled Error" err="error syncing 'gitlab/gitlab-lfs': error provisioning bucket: Provision: can't create ceph user: failed to get ceph user \"obc-gitlab-gitlab-lfs-d85a2a0f-c109-4b1c-822d-677a578140e9\": Get \"[https://rook-ceph-rgw-ceph-rgw.rook-ceph.svc:443/admin/user?format=json&uid=obc-gitlab-gitlab-lfs-d85a2a0f-c109-4b1c-822d-677a578140e9](https://rook-ceph-rgw-ceph-rgw.rook-ceph.svc/admin/user?format=json&uid=obc-gitlab-gitlab-lfs-d85a2a0f-c109-4b1c-822d-677a578140e9)\": context canceled, requeuing" logger="UnhandledError"
```

Since this is occurring during a full resync at startup, I wonder if the operator is stomping on itself by provisioning dashboard/mgr stuff, causing API calls to fail, which crashes bucket provisioning and therefore apparently the entire operator itself?

One thing to note: the crash occurs at almo

st exactly the 1 minute mark of the operator pod startup every time, so I was wondering if there was some sort of timeout that was causing the startup to fail, but after looking at the bucket provisioning code it doesn't seem like it.

Since the crash always occurs somewhere after `op-bucket-prov: getting storage class "ceph"` but before `op-bucket-prov: Provision: creating bucket "*" for OBC "*"`, I have to guess the crash occurs somewhere in [here](https://github.com/rook/rook/blob/8ca918603888ab6e4dbf672a4205f3c56acf2d07/pkg/operator/ceph/object/bucket/provisioner.go#L351). Is there a way to get more granular debug/trace output from the app to track down exactly where it is breaking?

**Comment by travisn** [comment]
The log doesn't show any crash. Does `kubectl describe` show any more details or failures? And you're seeing the operator pod restart, and in CLBO?

Strangely, the log shows that the mons are quorum:
```
2025-02-06 19:36:03.649427 I | op-mon: Monitors in quorum: [j o p]
```

But also shows errors about the mons not responding, which seems they are not in quorum:
```
2025-02-06 19:36:13.186324 I | ceph-spec: ceph-bucket-notification-controller: CephCluster "rook-ceph" found but skipping reconcile since ceph health is 
&{Health:HEALTH_ERR Details:map[error:{Severity:Urgent Message:failed to get status. . timed out: exit status 1}] LastChecked:2024-11-27T02:54:52Z LastChanged: PreviousHealth: Capacity:{TotalBytes:0 UsedBytes:0 AvailableBytes:0 LastUpdated:} Versions:<nil> FSID:}
```

What do `ceph status` and `ceph osd tree` show in the toolbox? Is everything looking healthy otherwise? Or are there ceph health errors?

**Comment by logan2211** [comment]
```
bash-5.1$ ceph status
  cluster:
    id:     784fa53c-f8b9-4381-8dee-6a1b20d5ded1
    health: HEALTH_WARN
            1 pgs not scrubbed in time
 
  services:
    mon: 3 daemons, quorum j,o,p (age 6d)
    mgr: a(active, since 6d), standbys: b
    mds: 2/2 daemons up, 2 hot standby
    osd: 18 osds: 17 up (since 8h), 16 in (since 8h); 1 remapped pgs
    rgw: 3 daemons active (3 hosts, 1 zones)
 
  data:
    volumes: 2/2 healthy
    pools:   17 pools, 569 pgs
    objects: 24.48M objects, 27 TiB
    usage:   43 TiB used, 16 TiB / 58 TiB avail
    pgs:     15384/131113864 objects misplaced (0.012%)
             541 active+clean
             21  active+clean+scrubbing
             6   active+clean+scrubbing+deep
             1   active+remapped+backfilling
 
  io:
    client:   38 MiB/s rd, 86 MiB/s wr, 89 op/s rd, 52 op/s wr
    recovery: 8.1 MiB/s, 3 objects/s
```

```
bash-5.1$ ceph osd tree
ID   CLASS  WEIGHT    TYPE NAME           STATUS  REWEIGHT  PRI-AFF
 -1         65.49637  root default                                 
 -3          7.27737      host lsn-d6438                           
  0    hdd   3.63869          osd.0           up   1.00000  1.00000
  6    hdd   3.63869          osd.6           up   1.00000  1.00000
 -7          7.27737      host lsn-d6576                           
  1    hdd   3.63869          osd.1           up   1.00000  1.00000
  7    hdd   3.63869          osd.7           up   1.00000  1.00000
-17          7.27737      host lsn-d6614                           
 14    hdd   3.63869          osd.14          up   1.00000  1.00000
 15    hdd   3.63869          osd.15          up   1.00000  1.00000
 -5          7.27737      host lsn-d6644                           
  2    hdd   3.63869          osd.2           up   1.00000  1.00000
  8    hdd   3.63869          osd.8           up   1.00000  1.00000
-15          7.27737      host lsn-d6656                           
 12    hdd   3.63869          osd.12          up         0  1.00000
 13    hdd   3.63869          osd.13        down         0  1.00000
-11          7.27737      host lsn-d6970                           
  3    hdd   3.63869          osd.3           up   1.00000  1.00000
 10    hdd   3.63869          osd.10          up   1.00000  1.00000
 -9          7.27737      host lsn-d6983                           
  5    hdd   3.63869          osd.5           up   1.00000  1.00000
  9    hdd   3.63869          osd.9           up   1.00000  1.00000
-13          7.27737      host lsn-d7050                           
  4    hdd   3.63869          osd.4           up   1.00000  1.00000
 11    hdd   3.63869          osd.11          up   1.00000  1.00000
-19          7.27737      host lsn-d7232                           
 16    hdd   3.63869          osd.16          up   1.00000  1.00000
 17    hdd   3.63869          osd.17          up   1.00000  1.00000
```

OSD 13 died recently, so we drained the node and replaced it. The new disk has not been commissioned yet because the operator isn't working, but otherwise the cluster is running normally.
