### ISSUE TITLE
Operator fails to create CephObjectStore due to missing VolumeMount "vaultsses3"

### ISSUE THREAD

**Issue by n0cliche** [rook/rook#15386]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Operator does not create a CephObjectStore and outputs an error. 
```
failed to reconcile CephObjectStore "rook-ceph/ceph-objectstore". failed to create object store deployments: failed to create object store "ceph-objectstore": failed to start rgw pods: failed to create rgw deployment: Deployment.extensions "rook-ceph-rgw-ceph-objectstore-a" is invalid: spec.template.spec.initContainers[1].volumeMounts[7].name: Not found: "vaultsses3"
```

**Expected behavior:**
Operator creates a CephObjectStore with the specified encryption configuration, RGW pods will launch successfully

**How to reproduce it (minimal and precise):**

I am deploying a cluster using the chart rook-ceph-cluster with the following configuration 

```
security:
  s3:
    connectionDetails:
      KMS_PROVIDER: "vault"
      VAULT_ADDR: "http://vault.vault.svc.cluster.local:8200/"
      VAULT_BACKEND_PATH: "rook"
      VAULT_SECRET_ENGINE: "transit"
      VAULT_AUTH_METHOD: "kubernetes"
      VAULT_AUTH_KUBERNETES_ROLE: "rook"
```
**Environment**:
* Rook version: 1.16.3

**P.S** I'm not completely sure, but it seems to me that the problem is in this code snippets.
When creating volumes, we check whether TokenAuth is enabled, but when creating volumeMounts, we do not do such a check.

https://github.com/rook/rook/blob/e4c6acab54493cee3a398e10b85cb8af2d993777/pkg/operator/ceph/object/spec.go#L228-L250

https://github.com/rook/rook/blob/e4c6acab54493cee3a398e10b85cb8af2d993777/pkg/operator/ceph/object/spec.go#L310-L338
**P.P.S** Please tell me if any additional information is required.
