### ISSUE TITLE
D3N datacache support for Ceph object

### ISSUE THREAD

**Issue by mmgaggle** [rook/rook#15430]
* Feature Request

**Cache volumes for D3N/D4N**

**What is use case behind this feature:**

[The Ceph object gateway has support for caching to local NVMe](https://docs.ceph.com/en/latest/radosgw/d3n_datacache/#running), configured through Ceph parameters

```
[client.rgw.8000]
  rgw_d3n_l1_local_datacache_enabled = true
  rgw_d3n_l1_datacache_persistent_path = "/mnt/nvme0/rgw_datacache/client.rgw.8000/"
  rgw_d3n_l1_datacache_size = 10737418240
```

Some new parameters could be added to CephObjectStore, in this case local-ssd would be a storage class that corresponds with  one created by local storage operator (or similar).

```
 gateway:
   d3n_datacache: true
   d3n_datacache_storage_class: local-ssd
   d3n_datacache_size: 100G
```

As a result:

1. The RGW deployment being created with an additional PersistentVolumeClaim / volumeMount (rgw container)

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-ceph-rgw-datacache
spec:
  storageClassName: local-ssd
  accessModes:
    - ReadWriteOnce
  volumeMode: filesystem
  resources:
    requests:
      storage: 100Gi
```
```
volumeMounts:
      - mountPath: "/mnt/rgw-datacache"
        name: rook-ceph-rgw-datacache
```

2. The following parameters would be set as well, the datacache size would be based off the size of the PV (not the PVC), perhaps minus some headroom.

```
[client]
  rgw_d3n_l1_local_datacache_enabled = true
  rgw_d3n_l1_datacache_persistent_path = "/mnt/rgw-datacache/"
  rgw_d3n_l1_datacache_size = 10737418240
```

**Environment**:

This would permit the use of D3N data caches for Rook-Ceph deployed clusters in k8s.

**Comment by BlaineEXE** [comment]
`rgwConfig` can already easily handle passing through basic config values to RGWs. I don't see any reason to require dedicated values at this point. We can also rely on the `additionalVolumeMounts` feature to allow users to choose what PVC they want for the cache.

Currently, it looks like this might actually be achievable today.

The additional volume mount will allow mounting a PVC, though I haven't tested this. I think that  a user could create the PVC they want, and then reference that PVC in the `additionalVolumeMounts` for the RGW to mount it.

https://github.com/rook/rook/blob/c5d27467d6f09360602346c4d97637bf66b6d3a2/pkg/apis/ceph.rook.io/v1/types.go#L3469-L3500

Putting it together would I think look something like this:

```yaml
kind: CephObjectStore
spec:
  gateway:
    additionalVolumeMounts:
      - subPath: "cache" # last dir component of datacache path below
        volumeSource:
          persistentVolumeClaim: # hostPath is another option users might want here
            claimName: "<pvc-name-here>"
            readOnly: false
    rgwConfig:
      rgw_d3n_l1_local_datacache_enabled = true
      rgw_d3n_l1_datacache_persistent_path = "/var/rgw/cache/"
      rgw_d3n_l1_datacache_size = 10737418240
# ...
---
# PVC is fully specified by the user next to the object store, allowing flexibility to use whatever service the user wants and has available
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-ceph-rgw-datacache
spec:
  storageClassName: local-ssd
  accessModes:
    - ReadWriteOnce
  volumeMode: filesystem
  resources:
    requests:
      storage: 100Gi
```

If you're able to prove this out, this is something we can add to Rook docs as an example of how these 2 features can be used to accommodate more advanced RGW setups.
