### ISSUE TITLE
rook CRDs should support a general status condition ready pattern for helm --wait support

### ISSUE THREAD

**Issue by kayrus** [rook/rook#15461]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

rook CRDs should support status conditions ready pattern to indicate helm that the deployment is finished, e.g. 

```yaml
status:
  conditions:
  - lastTransitionTime: %date%
    message: %message%
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
```

see helm source code: https://github.com/helm/helm/blob/841f4b1256f01826d3a5dbf0b7023389ed7319e8/pkg/kube/ready.go#L365-L383

**What is use case behind this feature:**

Currently helm deployments don't wait for cephobjectstore to be reconciled and updated, and once the helm upgrade is finished we still need to wait for a k8s deployment to be rolled out watching manually for the rolling upgrade.

For example cephobjectstore CRD doesn't have ready conditions, only a phase:

```yaml
status:
  endpoints:
    insecure: []
    secure:
    - https://storage.rook-ceph.svc:443
  info:
    endpoint: https://storage.rook-ceph.svc:443
  phase: Ready
```

**Environment**:

rook v1.16.2

see also https://github.com/helm/helm/issues/11717
