### ISSUE TITLE
Operator memory leak

### ISSUE THREAD

**Issue by njibhu** [rook/rook#15499]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

![Image](https://github.com/user-attachments/assets/39b79c3a-5b8e-4970-b654-71c7c9763ca1)

![Image](https://github.com/user-attachments/assets/07f76577-6546-49be-84e2-eacbd401bf98)

**Expected behavior:**

The operator is handling a single cephcluster, I would expect the memory usage to be constant.

**How to reproduce it (minimal and precise):**

The CephCluster is having quite a lot of activity, it's tracking 3000+ namespaces, with about 200/300 being created/deleted every day. Each of these namespaces has a PVC backed by the ceph cluster.
But the operator is configured to only look at his own namespace, so it shouldn't have any impact on it:
```
kubectl -n rook-ceph get deployment rook-ceph-operator -o jsonpath="{.spec.template.spec.containers[*].env[?(@.name=='ROOK_CURRENT_NAMESPACE_ONLY')].value}"
true%  
```

**File(s) to submit**:

```
spec:
  cephVersion:
    allowUnsupported: false
    image: quay.io/ceph/ceph:v18.2.4
  cleanupPolicy:
    sanitizeDisks: {}
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  crashCollector:
    daysToRetain: 30
    disable: false
  csi:
    cephfs: {}
    readAffinity:
      enabled: false
  dashboard:
    enabled: true
    ssl: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
  external: {}
  healthCheck:
    daemonHealth:
      mon: {}
      osd: {}
      status: {}
  logCollector:
    enabled: true
    maxLogSize: 500M
    periodicity: daily
  mgr:
    allowMultiplePerNode: false
    count: 2
    modules:
    - enabled: true
      name: rook
  mon:
    allowMultiplePerNode: false
    count: 3
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources:
          requests:
            storage: 16Gi
        storageClassName: default-retain
  monitoring:
    enabled: true
  network:
    multiClusterService: {}
  placement:
    mon:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rook-ceph-mon
            topologyKey: kubernetes.io/hostname
          weight: 100
      topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - rook-ceph-mon
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
  priorityClassNames:
    mgr: system-cluster-critical
    mon: system-node-critical
    osd: system-node-critical
  security:
    keyRotation:
      enabled: false
    kms: {}
  skipUpgradeChecks: false
  storage:
    flappingRestartIntervalHours: 0
    onlyApplyOSDPlacement: true
    storageClassDeviceSets:
    - count: 3
      encrypted: false
      name: set1
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodetype
                operator: In
                values:
                - osd_pool
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rook-ceph-osd
            topologyKey: kubernetes.io/hostname
        tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: osd_pool
        topologySpreadConstraints:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-osd
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      portable: true
      preparePlacement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodetype
                operator: In
                values:
                - osd_pool
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
            weight: 100
        tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: osd_pool
        topologySpreadConstraints:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-osd-prepare
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
      resources:
        limits:
          memory: 11Gi
        requests:
          cpu: "1"
          memory: 9Gi
      tuneDeviceClass: false
      tuneFastDeviceClass: true
      volumeClaimTemplates:
      - metadata:
          annotations:
            crushDeviceClass: ssd
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1024Gi
          storageClassName: managed-premium-retain
          volumeMode: Block
    store: {}
```

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

Operator logs are pretty much empty.

**Cluster Status to submit**:

- rook-ceph health: `HEALTH_OK`

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 22.04.5
* Kernel (e.g. `uname -a`): 5.15.0
* Cloud provider or hardware configuration: Azure Managed AKS
* Rook version (use `rook version` inside of a Rook Pod): v1.14.9
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.4
* Kubernetes version (use `kubectl version`): 1.30.7
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): AKS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK
