### ISSUE TITLE
unable to get monitor info from DNS SRV with service name: ceph-mon Error in pod when mounting PVC with static PV

### ISSUE THREAD

**Issue by yumin-l** [rook/rook#15544]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

I have a created volume in my cephfs, and the path is: /volumes/_nogroup/test-sv1/fcb5ddc5-c1b8-43ed-b7d2-48023052e051,
I followed the guide  https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md#cephfs-static-pvc here to create pvc and pv.
```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-static-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: csi-cephfs-secret
      namespace: rook-ceph
    volumeAttributes:
      clusterID: "rook-ceph"
      fsName: "flexran-devcloud-fs"
      staticVolume: "true"
      rootPath: "/volumes/_nogroup/test-sv1/fcb5ddc5-c1b8-43ed-b7d2-48023052e051"
    volumeHandle: cephfs-static-pv
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-static-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  #storageClassName: rook-cephfs-sc-agp
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: cephfs-static-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-static-pvc-test
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox:latest
      volumeMounts:
        - name: static-pvc
          mountPath: /data/pvc
      command: ["sleep", "3600"]
  volumes:
    - name: static-pvc
      persistentVolumeClaim:
        claimName: cephfs-static-pvc
        readOnly: false
```
But the status of the pod is always containercreating, and here are the logs:

kubelet (combined from similar events): MountVolume.MountDevice failed for volume "cephfs-static-pv" : rpc error: code = Internal desc = an error (exit status 32) occurred while running mount args: [-t ceph 192.168.122.177:6789,192.168.122.200:6789,192.168.122.101:6789:/volumes/group1/subv1/e7f8ff25-0910-4d88-bab9-5a102763a91a /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/8d9158f5e461066ad0b7f7b9a82af1beae35f4123c00c513663e7c9dace6d526/globalmount -o name=client.admin,secretfile=/tmp/csi/keys/keyfile-757277486,mds_namespace=test-fs1,_netdev] stderr: unable to get monitor info from DNS SRV with service name: ceph-mon

Has any one met this issue? 
I have enabled host networking for the ceph cluster.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
