### ISSUE TITLE
Rook Operator Does Not Update Mons Correctly When Distributing Across Zones

### ISSUE THREAD

**Issue by Termibg22** [rook/rook#15556]
**Is this a bug report or feature request?**
* Bug Report

**Description:**

I initially installed Rook with the following configuration:

```
mon:
    count: 3
    volumeClaimTemplate:
      spec:
        storageClassName: oci-bv-para
        resources:
          requests:
            storage: 50Gi
```

Later, I wanted to distribute the mons across different zones, so I updated the configuration to this:

```
mon:
    count: 3
    failureDomainLabel: topology.kubernetes.io/zone
    zones:
      - name: EU-FRANKFURT-1-AD-1
        volumeClaimTemplate:
          spec:
            storageClassName: oci-bv-para
            resources:
              requests:
                storage: 50Gi
      - name: EU-FRANKFURT-1-AD-2
        volumeClaimTemplate:
          spec:
            storageClassName: oci-bv-para
            resources:
              requests:
                storage: 50Gi
      - name: EU-FRANKFURT-1-AD-3
        volumeClaimTemplate:
          spec:
            storageClassName: oci-bv-para
            resources:
              requests:
                storage: 50Gi
```

However, the operator does not automatically apply any changes to the mons after this update. If I manually delete the deployment of one mon and then remove the operator, it recreates the deployment, but the configuration is applied incorrectly. Specifically, the anti-affinity label is left empty, resulting in the following:

```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - ""
```

**Steps to Reproduce:**

1. Install Rook with the initial mon configuration (3 mons, no zones specified).
2. Update the configuration to distribute the mons across zones as shown above.
3. Observe that no changes are applied automatically to the mons.
4. Manually delete one mon deployment and remove the operator.
5. Allow the operator to recreate the deployment and check the resulting affinity configuration.

**Deviation from expected behavior:**

After updating the configuration to include zone distribution, the Rook operator does not apply any changes to the existing mon deployments, leaving them unaffected and not distributed across the specified zones.

When manually deleting a mon deployment and allowing the operator to recreate it, the operator generates an incorrect nodeAffinity configuration with an empty value ("") in the values field of the topology.kubernetes.io/zone match expression. This results in the mons not being properly constrained to the intended zones, undermining the high-availability setup.

**Expected behavior:**

The Rook operator should automatically detect the updated configuration and redistribute the three mons across the specified zones (EU-FRANKFURT-1-AD-1, EU-FRANKFURT-1-AD-2, EU-FRANKFURT-1-AD-3) as defined in the zones field.

The nodeAffinity rules in the mon deployments should be updated to enforce scheduling on nodes within the corresponding zones, with the topology.kubernetes.io/zone key correctly mapping to the specified zone names (e.g., EU-FRANKFURT-1-AD-1, EU-FRANKFURT-1-AD-2, EU-FRANKFURT-1-AD-3).

If a mon deployment is manually deleted and recreated by the operator, the resulting configuration should maintain the proper zone affinity settings without requiring additional manual intervention.

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release): Oracle Linux 8
* Cloud provider or hardware configuration: Oracle Cloud
* Rook version (use `rook version` inside of a Rook Pod): v1.16.5
* Kubernetes version (use `kubectl version`): v1.31.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OKE

**Comment by travisn** [comment]
If the goal is just to have zone antiaffinity, I would expect you could use the pod anti-affinity under the `placement`, such as:
```yaml
 placement:
   mon:
     podAntiAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
...
```

Since this is only used at scheduling time, then you could [failover the mons](https://rook.io/docs/rook/latest-release/Storage-Configuration/Advanced/ceph-mon-health/#failing-over-a-monitor) one at a time, if they are not in separate zones already. 

But if you want to specific the exact zone names like that, perhaps @ideepika has another suggestion.

**Comment by Termibg22** [comment]
Hi,

Thanks for your response! 

I’ve been running some tests, and as noted in the documentation here: [](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/?h=placement#placement-configuration-settings), as well as in your message, it’s clear that the placement section allows for affinity assignments to various cluster components (mgr, mon, arbiter, osd, prepareosd and cleanup).

However, this raises a question for me. The documentation on mon settings [](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/?h=placement#mon-settings) seems to suggest a specific way to handle mon placement, yet it’s unclear why these options exist separately when placement can already address this task.

Additionally, the documentation states that "Placement of OSD pods is controlled using the Storage Class Device Set, not the general placement configuration." This makes me wonder why an osd option is even provided in the general placement section if it’s not the primary mechanism for controlling OSD placement.

It seems like there might be some overlap between these configuration options, which could make things a bit confusing at times. Centralizing all placement-related settings into a single and unified structure might help streamline things and make them easier to follow.

Thanks so much for your time!

**Comment by travisn** [comment]
> I’ve been running some tests, and as noted in the documentation [here](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/?h=placement#placement-configuration-settings), as well as in your message, it’s clear that the placement section allows for affinity assignments to various cluster components (mgr, mon, arbiter, osd, prepareosd and cleanup).
> 
> However, this raises a question for me. The documentation on mon settings [here](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/?h=placement#mon-settings) seems to suggest a specific way to handle mon placement, yet it’s unclear why these options exist separately when placement can already address this task.

What specifically do you see that discusses the mon placement in that section? Perhaps one point to clarify is that if you specify a `volumeClaimTemplate` for each zone, if you reference different storage classes, and their PVs enforce PV affinity to the zone, then you don't need to specify the separate placement. Specifying more explicit affinity/anti-affinity would only be in the `placement` section.

> Additionally, the documentation states that "Placement of OSD pods is controlled using the Storage Class Device Set, not the general placement configuration." This makes me wonder why an osd option is even provided in the general placement section if it’s not the primary mechanism for controlling OSD placement.

Agreed, this is confusing. The short answer if OSDs are created with `storageClassDeviceSets`, then you need to use the `placement` settings within each of those device sets. If OSDs are created via other settings (e.g. `useAllDevices`, or `storage.nodes`), then you need to use the higher level `placement`.

> It seems like there might be some overlap between these configuration options, which could make things a bit confusing at times. Centralizing all placement-related settings into a single and unified structure might help streamline things and make them easier to follow.

For backwards compatibility it will be difficult to change at this point, but certainly open to changes on the docs to help clarify!

**Comment by Termibg22** [comment]
Hi @travisn,

Thank you again for your feedback.

Personally, I believe the best approach would be to consolidate all placement-related logic within the `placement` section of the CephCluster CRD. This would enable users to define various placement rules—such as affinity, anti-affinity, tolerations, or even the use of different storage classes per zone—in a consistent and centralized way. It would offer a more intuitive and streamlined method for managing the scheduling of all cluster components (mon, mgr, osd, etc.), without having to deal with overlapping or redundant configurations spread across multiple sections.

However, I fully understand that such a significant change would likely break backward compatibility with earlier versions of Rook, as you pointed out. Instead, I would like to propose some modifications to the documentation to better explain the current behavior.

**Proposed Documentation Updates**

```
Mon Settings:

- volumeClaimTemplate:  [...] Note: This field should not be used if you are defining a specific volumeClaimTemplate for each zone in the zones section, as it will be overridden by the zone-specific configurations.
- zones: [...] Note: Configuring this section applies specific affinity rules to assign each mon to one of the specified zones. When this section is used, there is no need to define mon placement under the Placement Configuration Settings, as the zone settings will take precedence.

Placement Configuration Settings:

- Notes:
  - If OSDs are defined using storageClassDeviceSets, placement settings must be specified within each device set and the osd key here will be ignored.
  - If OSDs are created via other settings (e.g., useAllDevices or storage.nodes), the osd key in this section applies.
  - When zones are configured in the mon settings, specific affinity rules are automatically generated to assign each mon to one of the defined zones, without needing to configure this section.
  - Other components from separate CRDs, such as metadata servers in the CephFilesystem CRD, have their own placement configurations and are not affected by this section, even if the all key is used.

```

These updates aim to make the documentation more explicit about how mon settings and placement interact. While centralizing everything in placement would be my dream solution, I think these clarifications are a practical step forward given the backward compatibility constraints.

What do you think about these proposed changes? Do they address the confusion points effectively? I’d love to hear your feedback or any additional suggestions you might have.

Thanks again for your time and support!

**Comment by travisn** [comment]
Those doc updates make sense to me. I don't know how much they will actually help with the confusion since it is so complicated though. :) 

Do you want to open a PR to update those docs?

**Comment by Termibg22** [comment]
Sure!

After opening a PR, I wanted to ask about the failureDomainLabel setting in the mon section. From what I understand, its function is essentially equivalent to specifying the following in the placement section:

```
  placement:
    mon:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
```

If that's correct, I think the documentation could be updated to make this more explicit, for example:

```
Mon Settings:

- failureDomainLabel: [...] Note: This setting is an alternative to specifying a topologySpreadConstraint rule with the chosen label for the mons under the placement section, as described in the Placement Configuration Settings.
```

What do you think about this change?

Also, I think it's worth keeping this issue open because the original concern was about Rook not correctly applying labels to mons after upgrading from a general mon configuration to a specific zone-based configuration.

Thanks so much for your time!
