### ISSUE TITLE
Bucket creation failed when ceph cluster setup in different namespace

### ISSUE THREAD

**Issue by VirajJadhav** [rook/rook#15577]
I have setup rook operator in "namespace-1" and ceph cluster in "namespace-2" via helm charts. In ceph cluster helm chart, with values files I am providing storage class parameters like name (rook-ceph-bucket-sc), reclaimPolicy as Delete, volumeBindingMode as Immediate.
Storage class manifest is reflected rightly, but when I try to apply ObjectBucketClaim manifest, the resource gets created, but the operator fails to create a bucket stating, unsupported provisioner. The provisioner for my storage class is "namespace-2.ceph.rook.io/bucket".

Can you please guide ?

**Comment by VirajJadhav** [comment]
Hi @travisn can you please suggest, what should be done ?

**Comment by travisn** [comment]
@VirajJadhav Did you find the resolution? Was the prefix in the name of the provisioner for the object storage class? Did you see any errors in the rook operator log? And did you set these parameters in the storage class?
```yaml
parameters:
  objectStoreName: my-store
  objectStoreNamespace: namespace-2 # namespace:cluster
```

**Comment by bumarcell** [comment]
Hi @travisn 
I'm having the same problem (v1.18.9) Operator namespace is `rook-ceph` and cluster/objectStore namespace is `namespace2`. The error in the operator logs is:
```
error provisioning bucket: failed to get cephObjectStore: cephObjectStore not found: cephobjectstores.ceph.rook.io \"ssd-multisite-s3\" not found, requeuing" logger="UnhandledError"
```
Although it is in namespace2 and ready indeed:
```
NAME                        PHASE   ENDPOINT                                                                SECUREENDPOINT   AGE
ssd-multisite-s3       Ready     http://rook-ceph-rgw-ssd-multisite-s3.namespace2.svc:2809               3h35m
```
My storageClass:
```
parameters:
  objectStoreName: ssd-multisite-s3
  objectStoreNamespace: namespace2
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
It seems as if `objectStoreNamespace` is ignored.
