### ISSUE TITLE
Unable to mount shared filesystem in a pod,  same filesystem works  in rook tools, tmpfs mounted instead.

### ISSUE THREAD

**Issue by mikeatm** [rook/rook#1565]
Yes, looked around, nothing similar exists, not in chat either.
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:
Created a rook  setup
```
kubectl create -f rook-operator.yaml 
kubectl create -f rook-cluster.yaml
kubectl create -f rook-storageclass.yaml
kubectl  create -f statefulset-swift/swift-fs.yaml
```
This is the contents of swift-fs.yaml

```
apiVersion: rook.io/v1alpha1
kind: Filesystem
metadata:
  name: sft-etc-fs
  namespace: rook
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - erasureCoded:
       dataChunks: 2
       codingChunks: 1
  metadataServer:
    activeCount: 1
    activeStandby: true
```
Attempted to mount it in a pod.

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: swift-obj
  namespace: blobs
spec:
  serviceName: "swift-clus"
  replicas: 2
  template:
    metadata:
      labels:
        app: swift-obj
        appCluster: swift-clu
    spec:
      terminationGracePeriodSeconds: 20
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - swift-obj
                topologyKey: kubernetes.io/hostname
      containers:
        - name: sw-proxy
          image: "localhost:5000/swift-store"
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - name: proxy-port
              containerPort: 8080
              protocol: "TCP"
          volumeMounts:
            - name: "swift-etc"
              mountPath: "/etc/swift/"
            - name: "swift-node-m"
              mountPath: "/srv/node"
      volumes:
        - name: swift-etc
          flexVolume:
            driver: rook.io/rook
            fsType: ceph
            options:
              fsName: "sft-etc-fs" #
              clusterName: rook
              path: /
  volumeClaimTemplates:
    - metadata:
        name: "swift-node-m"
      spec:
        storageClassName: rook-block
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 400M
```
The shared filesystem does not  get mounted properly, instead i get this in the mountPath
```
[root@swift-obj-0 /]# ls /etc/swift/
1fe1d8739063a93c5aac788dadfda84135aa59c25cf145072f643e219ee6aa71-stdin   config.json  init-stdin
1fe1d8739063a93c5aac788dadfda84135aa59c25cf145072f643e219ee6aa71-stdout  init-stderr  init-stdout
```

Apparently in the pod its mounting some tmpfs there:

```
[root@swift-obj-0 /]# mount  | grep swift  
tmpfs on /etc/swift type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
```
Block volumes work on this same cluster, and indeed on this same pod. 

What you expected to happen:
Shared filesystem is mounted properly, and accessible from any pod that mounts it.

How to reproduce it (minimal and precise):

The default  shared filesystem example  reproduces my  problem exactly. 
But it the same example works on katacoda for me (first installing  ceph packages before creating  2 node cluster), but not locally with fedora, all ceph packages installed:
```
# rpm -qa | grep ceph 
ceph-fuse-12.2.3-1.fc27.x86_64
ceph-mds-12.2.3-1.fc27.x86_64
ceph-selinux-12.2.3-1.fc27.x86_64
ceph-osd-12.2.3-1.fc27.x86_64
python-cephfs-12.2.3-1.fc27.x86_64
ceph-base-12.2.3-1.fc27.x86_64
ceph-12.2.3-1.fc27.x86_64
libcephfs2-12.2.3-1.fc27.x86_64
ceph-mgr-12.2.3-1.fc27.x86_64
ceph-mon-12.2.3-1.fc27.x86_64
ceph-common-12.2.3-1.fc27.x86_64
```

**Feature Request**

Are there any similar features already existing:

What should the feature do:

What would be solved through this feature:

Does this have an impact on existing features:

**Environment**:
* OS (e.g. from /etc/os-release): ``` Fedora 27```
* Kernel (e.g. `uname -a`):    ``` 4.15.6-300.fc27.x86_64```
* Cloud provider or hardware configuration:  
* Rook version (use `rook version` inside of a Rook Pod): ```rook: v0.7.0-10.g3bcee98```
* Kubernetes version (use `kubectl version`): ```v1.9.1 
 , GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812"```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):   `local install from distro repository`
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)): ```# ceph health
HEALTH_WARN Reduced data availability: 100 pgs inactive, 100 pgs incomplete; Degraded data redundancy: 21/133 objects degraded (15.789%), 17 pgs degraded, 100 pgs undersized```

Other info:
```
]$ kubectl   describe filesystem  -n  rook 
Name:         sft-etc-fs
Namespace:    rook
Labels:       <none>
Annotations:  <none>
API Version:  rook.io/v1alpha1
Kind:         Filesystem
Metadata:
  Cluster Name:        
  Creation Timestamp:  2018-03-10T15:11:51Z
  Resource Version:    1066
  Self Link:           /apis/rook.io/v1alpha1/namespaces/rook/filesystems/sft-etc-fs
  UID:                 5c428d17-2475-11e8-9980-a0b3cc522051
Spec:
  Data Pools:
    Erasure Coded:
      Coding Chunks:  1
      Data Chunks:    2
  Metadata Pool:
    Replicated:
      Size:  3
  Metadata Server:
    Active Count:    1
    Active Standby:  true
Events:              <none>
```
Agent log on relevant node:
[fpaste](https://paste.fedoraproject.org/paste/WZxvtuHziuBbV6hxhaWnXA)
