### ISSUE TITLE
Support specifying Ceph config options via Kubernetes Secrets

### ISSUE THREAD

**Issue by stygian-coffee** [rook/rook#15678]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Currently Rook supports setting Ceph config options via the CephCluster CRD at [`.spec.cephConfig`](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/#ceph-config). I am requesting that Rook also support setting Ceph config options via Kubernetes secrets.

**What is use case behind this feature:**

Certain Ceph config options are meant to include credentials. This was brought up in https://github.com/rook/rook/issues/15342 where the user wanted to specify `mgr/dashboard/GRAFANA_API_PASSWORD` in the Ceph config.

**Comment by patrostkowski** [comment]
Hey @travisn, I have an idea for how we could support setting Ceph config options from a Kubernetes Secret.

We could add a new optional field to the CephCluster spec:

```
type CephClusterSpec struct {
    ...
    // A Kubernetes Secret with Ceph config values
    // +optional
    CephConfigSecretRef corev1.SecretReference `json:"cephConfigSecretRef,omitempty"`
}
```
Very early in the reconciliation loop, we would load the Secret and combine its values with the ones from `.spec.cephConfig`. If a config value is defined in both places, the value from `.spec.cephConfig` would take priority (so it overrides the Secret).

This would make it possible to pass sensitive Ceph config values through a Secret, instead of putting them directly in the CRD.

Example:

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephConfig:
    mgr:
      mgr/devicehealth/enable_monitoring: "true"
  cephConfigSecretRef:
    name: ceph-custom-secret-config
    namespace: rook-ceph
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-custom-secret-config
  namespace: rook-ceph
type: Opaque
stringData:
  cephConfig: |
    mgr:
      mgr/dashboard/GRAFANA_API_PASSWORD: "secret"
```

Let me know if this sounds like a good direction. I would be happy to work on implementing this.

**Comment by patrostkowski** [comment]
@rouke-broersma I am afraid that I could break too many things by following the reasoning above, which is why I opted for parsing (in your case, multiple) Secrets and merging them with the existing `spec.cephConfig`

**Comment by rouke-broersma** [comment]
@patrostkowski I don't think my proposal changes anything from your suggestion except the format in which you provide the config.

`MGR_MGR_DASHBOARD_GRAFANA_API_PASSWORD` would simply map to:

```
mgr:
  mgr/dashboard/grafana_api_password
```

And then you do the merge with the `spec.cephConfig`.

**Comment by patrostkowski** [comment]
@rouke-broersma thanks for the suggestion! So I explored this idea, but since `.spec.cephConfig` is just a `map[string]map[string]string`, there’s no real schema to validate or cleanly structure those flat keys. It could get messy quickly, and the config validation logic might turn into spaghetti. 

If Rook would ever move to a more structured format (with an actual schema), this approach would make a lot more sense. But for now, the simplest and most reliable method I found is to read the config from a secret using the same map structure and merge it with the values from `.spec.cephConfig`.

**Comment by rouke-broersma** [comment]
Maybe I'm missing something but merging the map also doesn't support any validation does it? I'm not proposing to add any validation at all.

**Comment by patrostkowski** [comment]
Yeah, that is exactly what I meant - my hesitation is not about validation, but about introducing a transformation convention (like `_` → `/`) that is not robust or predictable across all other Ceph config patterns.

More specifically, I am struggling to see how something like this:

```
spec:
  cephConfigFrom:
  - name: MGR_MGR_DASHBOARD_GRAFANA_API_PASSWORD
    valueFrom:
      secretKeyRef:
        name: grafana-api-credential
        key: password
```

would cleanly and consistently map into the current `map[string]map[string]string` structure.

One idea could be to allow a format like:

```
- name: "mgr/mgr/dashboard/GRAFANA_API_PASSWORD"
```

Then we could split on the first /, resulting in:

```
map[string]map[string]string{
  "mgr": {
    "mgr/dashboard/GRAFANA_API_PASSWORD": "<value>",
  },
}
```

That would be more predictable than trying to infer structure from `_` separators - but even this is not viable due to [Kubernetes naming constraints](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names)
The name field must follow RFC-compliant rules, so slashes are not allowed in fields like `SecretKeySelector.name`.

On top of that, even with SecretKeySelector, the referenced Secret must exist in the same namespace as the pod, meaning cross-namespace sourcing (e.g., a Terraform-managed Secret in a different namespace) [is not supported either.](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#secretkeyselector-v1-core)

Let’s wait until Monday - in the meantime, I will work on cleaning up my draft PR so we have a minimal, working version of the change.

**Comment by rouke-broersma** [comment]
I had assumed that with a format like `MGR_MGR_DASHBOARD_GRAFANA_API_PASSWORD` we could simply always map the first part to the daemon and the rest as whatever `key/is/used/by/ceph` but if ceph config keys are not always in the format `key/is/used/by/ceph` then yea obviously that's a no-go.

The difference between my suggestion and your suggestion is not that big, I agree that your suggestion makes more sense. I don't see how this is related to SecretKeySelector.name though because name is not a SecretKeySelector, it's a reference to the ceph config. If I take your example it becomes this:

```
spec:
  cephConfigFrom:
  - name: 'mgr/mgr/dashboard/GRAFANA_API_PASSWORD'
    valueFrom:
      secretKeyRef:
        name: grafana-api-credential
        key: password
```

SecretKeySelector remains secretKeyRef? As for referenced secret must exist in the same namespace as Rook, that is not an issue, there are many mechanisms to sync the secret to the rook namespace and is not the responsibility of Rook. That is up to the user to provide in the correct location.

**Comment by patrostkowski** [comment]
@rouke-broersma oh I see - you might be right, I completely mixed up the APIs! We could definitely do something like this:

```
spec:
  cephConfigFrom:
    - module: mgr
      key: mgr/dashboard/GRAFANA_API_PASSWORD
      value:
        secretKeyRef:
          name: grafana-api-credential
          key: password
```

It would require introducing a new custom type like:

```
type ClusterSpec struct {
  ...
	CephConfig     map[string]map[string]string 
	CephConfigFrom []ConfigFrom                
}

type ConfigFrom struct {
	Module string 
	Key    string
	Value  v1.SecretKeySelector
}
```

This would (in some way) map to:

```
map[string]map[string]string{
  "mgr": {
    "mgr/dashboard/GRAFANA_API_PASSWORD": "secret",
  },
}
```

Totally doable :) just keep in mind that the secret still needs to exist in the same namespace as Rook.

Let’s wait until Monday so the maintainers can take a look at what we found here.

**Comment by rouke-broersma** [comment]
That sounds really good, thanks for bearing with me :)

**Comment by travisn** [comment]
@patrostkowski That approach with the `ConfigFrom` struct could work, but it does seem a bit heavyweight if a separate secret needs to be referenced for each value. 

Here's another idea that would require no schema change... Just use a keyword inside the existing `cephConfig` values to indicate that the value should be read from a secret. There is also no need to merge the different config. For example:
```yaml
  cephConfig:
    mgr:
      "mgr/dashboard/GRAFANA_API_PASSWORD": "<secret>:secretName:secretKey"
    global:
      osd_pool_default_size: "2"
      ...
```
If the `<secret>` prefix is found and there are exactly two colons, then load the secret named `secretName`, and the key `secretKey`. While some may question it since it's basically a custom way to specify a secret ref, it also keeps things very simple.

**Comment by patrostkowski** [comment]
@travisn sure, that indeed is definitely a very simple idea! My only concern would be how easy it will be to maintain this in the long run. I was originally thinking about a more typed approach and merging two maps might be a bit confusing. Your idea could be a good middle ground. Would this work for you @rouke-broersma @stygian-coffee? If yes, let me come back with a PR.

**Comment by rouke-broersma** [comment]
That can work for me and it's used in many projects like argocd and grafana. You just need to be wary of how you parse the values during replacing and that you don't introduce some kind of injection attack with it.

**Comment by stygian-coffee** [comment]
@patrostkowski Thank you for your help! The middle-ground solution should work fine, yes. That said I'm not sure that you need to be concerned about merging two maps being confusing, since this is very similar to [what the Kubernetes API already does](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#container-v1-core) with `env` and `envFrom` in `core/v1/container`, and that works fine:
> When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence.

**Comment by patrostkowski** [comment]
@stygian-coffee yep, I think that logging that information and continuing without that config piece would be the best.

Also, one last try for the typed approach - I saw that Rook actualy uses this mechanism of reading from secret using its own Type for [RGW config](https://github.com/rook/rook/pull/15426/files#diff-46a2e53ea9b825b7c3b65113b63a133da71eb0cd2a2c0e33012c224d02a8eaa1R1757). I actually have working version of this for `CephConfigFromSecret`, so maybe we could also reuse this approach here @travisn?

**Comment by BlaineEXE** [comment]
We did this in CephObjectStore recently for RGW. I think we can re-use the same idea here: https://github.com/rook/rook/pull/15426

```
	// RgwConfigFromSecret works exactly like RgwConfig but takes config value from Secret Key reference.
	// Values are modified at runtime without RGW restart.
	// This feature is intended for advanced users. It allows breaking configurations to be easily
	// applied. Use with caution.
	// +nullable
	// +optional
	RgwConfigFromSecret map[string]v1.SecretKeySelector `json:"rgwConfigFromSecret,omitempty"`
```

Allows usage like this

```
    rgwConfigFromSecret:
      rgw_keystone_barbican_password:
        name: "barbican-secret"
        key: "password"
```

Instead of `rgwConfigFromSecret`, we could drop `rgw` from the prefix to just have `configFromSecret`.

**Comment by travisn** [comment]
Good point, since we have the precedent with the rgw secrets, sounds good to use the similar pattern for the cephcluster CR. So for example, it might look like this?
```yaml
cephConfigFromSecret:
    mgr:
    - name: 'mgr/mgr/dashboard/GRAFANA_API_PASSWORD'
      valueFrom:
        secretKeyRef:
          name: grafana-api-credential
          key: password
cephConfig:
    global:
      osd_pool_default_size: "2"
```

And how about if we avoid merging the values? There is some complexity with the merge that doesn't seem necessary. The operator can just set the `cephconfig` first, then apply the `cephConfigFromSecret`. If there are conflicting values, the last one will win. That seems like a corner case not worth worrying about, if it means we can simplify the implementation.

**Comment by patrostkowski** [comment]
@travisn it would work like this:

```
cephConfigFromSecret:
    mgr:
        mgr/mgr/dashboard/GRAFANA_API_PASSWORD:
            name: grafana-api-credential
            key: password
cephConfig:
    global:
        osd_pool_default_size: "2"
    mgr:
        mgr/devicehealth/enable_monitoring: "true"
```

where `cephConfigFromSecret` is:

```
// CephConfigFromSecret works exactly like CephConfig but takes config value from Secret Key reference.
// +optional
// +nullable
CephConfigFromSecret map[string]map[string]v1.SecretKeySelector `json:"cephConfigSecretRef,omitempty"`
```

Both `cephConfig` and `cephConfigFromSecret` are merged, with values from `cephConfig` taking precedence. If a secret value can't be read, we just log the error and continue without setting that value and disrupting the reconciliation.

The implementation is more or less ready https://github.com/rook/rook/pull/15696 - but for some reason I can't run `make codegen`. Would you be able to help me troubleshoot that? I'd be also happy to add docs once I get unblocked on generating the code.
