### ISSUE TITLE
Typo in example of CephObjectStoreUser CR in docs

### ISSUE THREAD

**Issue by vsed** [rook/rook#15694]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The following is a non-working example from the docs (Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md) on how to use the new (really awesome 🤩) feature to load S3 credentials from an existing secret:
```
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: foo
  namespace: rook-ceph
spec:
  store: my-store
  clusterNamespace: rook-ceph
  keys:
    - acccessKeyRef
        name: foo-s3
        key: AWS_ACCESS_KEY_ID
      secretKeyRef
        name: foo-s3
        key: AWS_SECRET_ACCESS_KEY
    - acccessKeyRef
        name: bar-s3
        key: AWS_ACCESS_KEY_ID
      secretKeyRef
        name: bar-s3
        key: AWS_SECRET_ACCESS_KEY
```
The accessKeyRef contains an extra c and is missing a ":" at the end. It's really easy to miss the extra c which leads to the operator only reading the secret key, but not the access key. Took me a while to find out. 😅 

**Expected behavior:**
Here is an example that works for me with the typos fixed:
```
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: ceph-s3-user
  namespace: rook-ceph
spec:
  store: ceph-objectstore
  keys:
    - accessKeyRef:
        name: s3-creds
        key: AccessKey
      secretKeyRef:
        name: s3-creds
        key: SecretKey
```

**Environment**:
I used helm charts to deploy rook-ceph from:
master, commit f114fe1694d5da73ccf2cab3537bce8045d2174e (Merge pull request #15690 from BlaineEXE/cephclient-fsmap-uint64)
