### ISSUE TITLE
Fix indentation and add enabled: true in dashboard block example

### ISSUE THREAD

**Issue by OdedViner** [rook/rook#15768]
The current example in the documentation shows `prometheusEndpoint` and `prometheusEndpointSSLVerify` at the wrong indentation level under spec, instead of being nested under the dashboard block.
Additionally, the `enabled: true` field is missing.

[https://github.com/rook/rook/blob/279b6c30fbab5da8af8a2e2b8d414c67a5ef1477/pkg/apis/ceph.rook.io/v1/types.go#L373](https://www.google.com/url?q=https://github.com/rook/rook/blob/279b6c30fbab5da8af8a2e2b8d414c67a5ef1477/pkg/apis/ceph.rook.io/v1/types.go%23L373&sa=D&source=docs&ust=1745427417751171&usg=AOvVaw2Mr84ndBALQQBmchQJ9lF2)

Current:
```
spec:
  dashboard:
  prometheusEndpoint: http://192.168.61.204:30900
  prometheusEndpointSSLVerify: true
```

Expected:
```
spec:
  dashboard:
    enabled: true
    prometheusEndpoint: http://192.168.39.248:30900
    prometheusEndpointSSLVerify: true
```
