### ISSUE TITLE
Add support for creating a HTTPRoute in the cluster Helm chart

### ISSUE THREAD

**Issue by onedr0p** [rook/rook#15870]
**Is this a bug report or feature request?**
* Feature Request

Add support for defining an HTTPRoute (from [Gateway API](https://gateway-api.sigs.k8s.io/)) in the cluster helm chart. Gateway API could be the future replacement to the Ingress API.

**What should the feature do:**

Create a HTTPRoute for accessing the Rook Ceph Dashboard

**What is use case behind this feature:**

[Gateway API](https://gateway-api.sigs.k8s.io/) is GA now and it would be nice to have support for it within the Cluster chart.

For now I have defined the HTTPRoute out of the Helm chart like so:

```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rook-ceph-dashboard
spec:
  hostnames: ["rook.domain.tld"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: rook-ceph-mgr-dashboard
          namespace: rook-ceph
          port: 7000
```

We can see that some charts are already adding support for Gateway API, e.g.
https://github.com/prometheus-community/helm-charts/blob/4d14748f9ddbb7c6d02323931de104bc196e06ec/charts/kube-prometheus-stack/values.yaml#L634-L673

**Comment by onedr0p** [comment]
Yeah that seems good, I'll try to get to it!

**Comment by ayashjorden** [comment]
Hello,
And thank you for making Rook! made it easy for me to deploy in my homelab!

I've updated my CephCluster helm chart with the new `route.dashboard` configuration, helm-install, but I don't see the changes.
From other components in my setup, it is usually required to restart some pods/Deployments/DaemonSets, but that is not mentioned in rook's Helm guide.
Can you advise if any Deployment/DS needs a restart?

**Comment by onedr0p** [comment]
The changes were not released yet. Wait for the next release.

**Comment by ayashjorden** [comment]
> The changes were not released yet. Wait for the next release.

Hi @onedr0p ,
I understand route.dashboard is not released yet, can you then explain how to handle Helm changes?

For example:
1. Update CephCluster Helm values.yaml like
   ```yaml
   dashabord:
     ssl: false
     urlPrefix: /ceph-dashabord
   ```
2. `helm upgrade --install --reuse-values -f values.yaml -n rook-ceph rook-ceph-cluster rook-release/rook-ceph-cluster`
3. **Here** => should I restart the mgr-s? ``kubectl -n rook-ceph rollout restart deployment/rook-ceph-mgr-a deployment/rook-ceph-mgr-b`` or something else to pickup the changes?

Lastly, if I missed something in the docs, appreciate pointing me to the right place...

Thank you
