### ISSUE TITLE
ShortNamesConflict: "cephnfs" is already in use

### ISSUE THREAD

**Issue by adborden** [rook/rook#15925]
I believe this was introduced in https://github.com/rook/rook/pull/15900

The singular name of the CRD is already `cephnfs`, so I'm not sure if a short name makes sense here and could be the cause of the conflict.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Since rook-ceph 1.17.3, cephnfses.ceph.rook.io is reporting an unhealthy condition:

```
  Conditions:
    Last Transition Time:  2025-05-31T01:57:41Z
    Message:               "cephnfs" is already in use
    Reason:                ShortNamesConflict
    Status:                False
    Type:                  NamesAccepted
```

**Expected behavior:**
cephnfs should report healthy conditions:

```yaml
status:
  conditions:
    - status: "True"
      type: NamesAccepted
      reason: NoConflicts
```

**How to reproduce it (minimal and precise):**
Upgrade or apply CRDs from rook-ceph 1.17.3

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by daurnimator** [comment]
I also ran into this. https://github.com/rook/rook/pull/15888#issuecomment-2929187588
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata: ...
spec: ...
status:
  acceptedNames:
    kind: CephNFS
    listKind: CephNFSList
    plural: cephnfses
    shortNames:
      - nfs
    singular: cephnfs
  conditions:
    - lastTransitionTime: '2025-06-02T06:50:32Z'
      message: '"cephnfs" is already in use'
      reason: ShortNamesConflict
      status: 'False'
      type: NamesAccepted
    - lastTransitionTime: '2025-05-05T10:38:56Z'
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: 'True'
      type: Established
  storedVersions:
    - v1
```
