### ISSUE TITLE
radosgw-admin bucket stats creates unwanted "default" ZoneGroup and Zone in Rook v1.17

### ISSUE THREAD

**Issue by cupnes** [rook/rook#15984]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In Rook v17, when I run the radosgw-admin bucket stats command, it creates a new ZoneGroup and Zone both named "default". This happens even if a ZoneGroup and Zone (with different names) already exist.

Here's an example for the Zone (the ZoneGroup is similar):

```json
{
    "default_info": "8b64d619-eaee-40e4-8346-263937e3cff8",
    "zones": [
        "my-store",
        "default"
    ]
}
```

**Expected behavior:**
If a ZoneGroup and Zone already exist, running the `radosgw-admin bucket stats` command should not create a new ZoneGroup and Zone named "default". (In Rook v16, this behavior did not occur.)

**How to reproduce it (minimal and precise):**
1. Create a CephObjectStore CR:
   ```yaml
   apiVersion: ceph.rook.io/v1
   kind: CephObjectStore
   metadata:
     name: my-store
     namespace: rook-ceph
   spec:
     metadataPool:
       replicated:
         size: 1
     dataPool:
       replicated:
         size: 1
     gateway:
       port: 80
       instances: 1
       placement: {}
   ```
   - At this point, only the ZoneGroup and Zone named "my-store" exist.
2. Run the `radosgw-admin bucket stats` command.
   - As a result, a ZoneGroup and Zone named "default" are created.

**Environment**:
* OS (e.g. from /etc/os-release):
  ```
  PRETTY_NAME="Ubuntu 22.04.5 LTS"
  NAME="Ubuntu"
  VERSION_ID="22.04"
  VERSION="22.04.5 LTS (Jammy Jellyfish)"
  VERSION_CODENAME=jammy
  ID=ubuntu
  ID_LIKE=debian
  HOME_URL="https://www.ubuntu.com/"
  SUPPORT_URL="https://help.ubuntu.com/"
  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  UBUNTU_CODENAME=jammy
  ```
* Kernel (e.g. `uname -a`):
  ```
  Linux neco-r740 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
  ```
* Rook version (use `rook version` inside of a Rook Pod): v1.17.1
  * This issue does not occur in v1.16.4.
* Storage backend version (e.g. for ceph do `ceph -v`): Ceph v19.2.1

**Additional Notes**
I'm not sure if this is related, but I noticed a difference between Rook v16 and v17:

In Rook v16, after creating the CephObjectStore CR, if I checked the ZoneGroup and Zone, the `default_info` field had some text in it. In Rook v17, the `default_info` field is empty.

Here's an example for the Zone (the ZoneGroup is similar):

In Rook v16:
```json
{
    "default_info": "6b443354-07fd-49f7-a7a6-d7d1504c36fe",
    "zones": [
        "my-store"
    ]
}
```

In Rook v17:
```json
{
    "default_info": "",
    "zones": [
        "my-store"
    ]
}
```
