### ISSUE TITLE
CephObjectStoreUser cannot be deleted if secret references by keys do not exist because it cannot reconcile

### ISSUE THREAD

**Issue by mdusher** [rook/rook#16007]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The CephObjectStoreUser does not delete as the operator attempts to reconcile using secrets that no longer exist. Re-creating the secret will allow the user to be reconciled and then deleted.

**Expected behavior:**
The CephObjectStoreUser is deleted, even if the secret does not exist.

**How to reproduce it (minimal and precise):**
1. Create a CephObjectStoreUser that uses access and secret keys provided by a secret.
   ```yaml
      ---
      apiVersion: v1
      kind: Secret
      metadata:
        name: test-user-keys
        namespace: rook-ceph
        labels:
          testuser: "true"
      data:
        accessKey: dGVzdGtleQ==
        secretKey: dGVzdHNlY3JldA==
      ---
      apiVersion: ceph.rook.io/v1
      kind: CephObjectStoreUser
      metadata:
        name: test-user
        namespace: rook-ceph
        labels:
          testuser: "true"
      spec:
        clusterNamespace: rook-ceph
        store: ceph-objectstore
        keys:
        - accessKeyRef:
            key: accessKey
            name: test-user-keys
          secretKeyRef:
            key: secretKey
            name: test-user-keys
   ```
2. Delete the secret
   ```shell
      $ kubectl -n rook-ceph delete secret test-user-keys
   ```
3. Delete the CephObjectStoreUser and it will hang
   ```shell
      $ kubectl -n rook-ceph delete cephobjectstoreuser test-user
   ```

**Logs to submit**:

* Operator's logs, if necessary
```
2025-06-13 01:57:31.258520 E | ceph-object-store-user-controller: failed to reconcile failed to generate UserKeySpec for "test-user": failed to get secret value: failed to get secret "rook-ceph/test-user-keys": Secret "test-user-keys" not found
2025-06-13 01:57:31.258547 E | ceph-object-store-user-controller: failed to reconcile CephObjectStoreUser "rook-ceph/test-user". failed to generate UserKeySpec for "test-user": failed to get secret value: failed to get secret "rook-ceph/test-user-keys": Secret "test-user-keys" not found
```
