### ISSUE TITLE
Very slow overwriting speed in block storage.

### ISSUE THREAD

**Issue by rgembalik** [rook/rook#1657]
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:
1. I installed rook using default yml files and block storageclass.
1. I created busybox with PVC based on `rook-block` storage class.
1. I entered busybox, and executed `dd if=/dev/zero of=/volume/file bs=1M count=1k`
1. It shown writing speed of 729.1MB/s
1. I executed `dd if=/dev/zero of=/volume/file bs=1M count=1k` again, overwriting the file
1. It shown writing speed of 51.1MB/s

What you expected to happen:
1. Both commands should have similar write speeds 

How to reproduce it (minimal and precise):
Try to override any file in mounted PVC. Deleting file and testing write speed again shows write speed over 300MB/s each time, while overwriting will show writing speed below 100MB/s each time.

Writes outside of pvc volume are alaways around 500MB/s, no matter if it's new file, or if I am overwriting it.

**Environment**:
* Ubuntu 16.04
* Kernel 4.4.0-119-generic:
* KVM virtual machines set as 3 nodes and master. 
* Rook version v0.7.0-83.gd59e89e
* Kubernetes version v0.7.0-83.gd59e89e
* Kubernetes cluster type: Don't know
* Ceph status 
```
  cluster:
    id:     35be3470-bda4-4ffa-9730-cf29e00e3fcd
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum rook-ceph-mon9,rook-ceph-mon7,rook-ceph-mon0
    mgr: rook-ceph-mgr0(active)
    osd: 3 osds: 3 up, 3 in
 
  data:
    pools:   1 pools, 100 pgs
    objects: 2402 objects, 9544 MB
    usage:   426 GB used, 4002 GB / 4429 GB avail
    pgs:     100 active+clean
```

**Comment by galexrt** [comment]
@rgembalik Did you use the default yaml files from the docs (https://rook.io/docs/rook/v0.7/block.html) or from https://github.com/rook/rook/tree/master/cluster/examples/kubernetes ?

**Comment by rgembalik** [comment]
I think they were from a cloned git repository (https://github.com/rook/rook/tree/master/cluster/examples/kubernetes).

**Comment by rgembalik** [comment]
@galexrt Please let me know if there is any other useful info I could provide.

**Comment by tibkiss** [comment]
This issue is still present in rook 0.9. 

Initial write: 
```
dd if=/dev/urandom of=file2 bs=1M count=1k
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 4.59462 s, 234 MB/s
```

Overwrite:
```
dd if=/dev/urandom of=file2 bs=1M count=1k
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 100.902 s, 10.6 MB/s
```

The only modification made to the config on my end was to explicitly set `bluestore` in `storage.config.storeType`. 

I tried to enable `allow_ec_overwrites` but it did not have any performance benefit.

Some pointer would be appreciated to resolve this performance issue. Thanks!

**Comment by mykaul** [comment]
For various reason, this is not the right way to test performance.
1. you might be running out of entropy (especially if you are running in a VM!) - can you make sure this is not the case?
2. You are using buffered writes (try adding oflag=direct to the 'dd' command line).
3. dd is slow, synchronous. It doesn't really exercise the storage. It does have multiple threads and queues. Better look at fio. However, I suspect issue 1 and 2 above are what causing the real slowdown - can you check?

**Comment by tibkiss** [comment]
@mykaul : thanks for the suggestions. 

1. I'm running on a three node bare metal cluster, the entropy on all nodes are above 3500 (via `/proc/sys/kernel/random/entropy_avail`). As far as I know /dev/urandom should not be affected by lack of entropy, only /dev/random has such behavior. 

2. Bypassing the page cache slows things further down:
```
# dd if=/dev/urandom of=file2 bs=1M count=1k oflag=direct
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 157.049 s, 6.8 MB/s
```
3. If dd would be generally slow, it would be true for the first iteration as well, which is not the case.
The write operations are slow in case of the file is re-written. To prove this I ran dd with append mode, which shows the same performance as the initial write:
```
# dd if=/dev/urandom of=file2 bs=1M count=1k oflag=append conv=notrunc
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 4.67556 s, 230 MB/s
```

Any other idea?

**Comment by galexrt** [comment]
@tibkiss Post the Pool object yaml you are using for the tests.

**Comment by tibkiss** [comment]
@galexrt : Here it comes!

```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicated-metadata-pool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ec-data-pool
  namespace: rook-ceph
spec:
  failureDomain: host
  # Make sure you have enough nodes and OSDs running bluestore to support the replica size or erasure code chunks.
  # For the below settings, you need at least 3 OSDs on different nodes (because the `failureDomain` is `host` by default).
  erasureCoded:
    dataChunks: 2
    codingChunks: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
   annotations:
     storageclass.kubernetes.io/is-default-class: true
provisioner: ceph.rook.io/block
parameters:
  blockPool: replicated-metadata-pool
  dataBlockPool: ec-data-pool
  # Specify the namespace of the rook cluster from which to create volumes.
  # If not specified, it will use `rook` as the default namespace of the cluster.
  # This is also the namespace where the cluster will be
  clusterNamespace: rook-ceph
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  fstype: xfs
reclaimPolicy: Retain
```
