### ISSUE TITLE
Enable NFS on RGW

### ISSUE THREAD

**Issue by chr55** [rook/rook#1673]
I have created Rook ObjectStorage (instead of Block Storage) so that I can upload file remotely. I am able to connect to this storage from my macOS.  I followed https://rook.io/docs/rook/master/object.html
I have this:
```
apiVersion: rook.io/v1alpha1
kind: ObjectStore
metadata:
  name: my-store
  namespace: rook
....
```

I now want to consume this storage. I see Wordpress examples for the Block Storage but not for ObjectStorage.  

The example for block is
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```

What would this be for ObjectStorage?

thanks!!
