### ISSUE TITLE
Unable to create PVCs

### ISSUE THREAD

**Issue by arthur0** [rook/rook#1685]
# Bug Report

What happened: 
---
1. Bootstrap the rook operator (`image: rook/rook:master`), the needed RBAC and CRDs (Pool and Cluster)
2. Create the Cluster custom resource 
3. Create the Pool custom resource and the Storage Class 
4. Try to create the PVC pointing to Storage Class (tree scenarios):
4.1 SC with the parameter **clusterNamespace**: `invalid option "clusterNamespace" for volume plugin rookVolumeProvisioner`  
4.2 SC with the parameter **clusterName**: `unable to open config file from search list /var/lib/rook/rook-cluster/rook-cluster.config`
4.3 SC with Both: **clusterNamespace**: `invalid option "clusterNamespace" for volume plugin rookVolumeProvisioner`

What you expected to happen:
---
Create a PVC 
Some documentation about the allowed parameters on the Storage Classes in the [docs](
https://rook.io/docs/rook/master/)

How to reproduce it (minimal and precise):
---
My resources are strongly based on the [kubernetes examples](https://github.com/rook/rook/tree/master/cluster/examples/kubernetes) in the master repo.

Assumption: The PR  #1614 can be associated with the issue  

More detailed setup (see the scenarios above):
---
Scenario 4.1: Only **clusterNamespace**
```
apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: replicapool
  namespace: rook
spec:
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-block
provisioner: rook.io/block
parameters:
  pool: replicapool
  clusterNamespace: rook
```

When I try to create the claim
```
Events:
  Type     Reason                Age               From                                                                               Message
  ----     ------                ----              ----                                                                               -------
  Normal   ExternalProvisioning  1m (x25 over 2m)  persistentvolume-controller                                                        waiting for a volume to be created, either by external provisioner "rook.io/block" or manually created by system administrator
  Normal   Provisioning          23s (x8 over 2m)  rook.io/block rook-operator-68cfd8ff8f-smlmx ae4e568f-4a60-11e8-b952-ee602114e76d  External provisioner is provisioning volume for claim "default/mysql-pv-claim"
  Warning  ProvisioningFailed    23s (x8 over 2m)  rook.io/block rook-operator-68cfd8ff8f-smlmx ae4e568f-4a60-11e8-b952-ee602114e76d  Failed to provision volume with StorageClass "rook-block": invalid option "clusterNamespace" for volume plugin rookVolumeProvisioner
```

Scenario 4.2: **Only ClusterName**
```
apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: replicapool2
  namespace: rook
spec:
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-block2
provisioner: rook.io/block
parameters:
  pool: replicapool2
  clusterName: rook-cluster
```

When I try to create the claim
```
  Type     Reason                Age               From                                                                               Message
  ----     ------                ----              ----                                                                               -------
  Normal   ExternalProvisioning  1m (x25 over 3m)  persistentvolume-controller                                                        waiting for a volume to be created, either by external provisioner "rook.io/block" or manually created by system administrator
  Normal   Provisioning          11s (x9 over 3m)  rook.io/block rook-operator-68cfd8ff8f-smlmx ae4e568f-4a60-11e8-b952-ee602114e76d  External provisioner is provisioning volume for claim "default/mysql-pv-claim2"
  Warning  ProvisioningFailed    11s (x9 over 3m)  rook.io/block rook-operator-68cfd8ff8f-smlmx ae4e568f-4a60-11e8-b952-ee602114e76d  Failed to provision volume with StorageClass "rook-block2": Failed to create rook block image replicapool2/pvc-722e2d31-4a64-11e8-ba56-fa163ee89d19: failed to create image pvc-722e2d31-4a64-11e8-ba56-fa163ee89d19 in pool replicapool2 of size 8589934592: Failed to complete '': exit status 1. global_init: unable to open config file from search list /var/lib/rook/rook-cluster/rook-cluster.config
. output:
```

Scenario 4.3:  **With both**:
```
apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: replicapool3
  namespace: rook
spec:
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-block3
provisioner: rook.io/block
parameters:
  pool: replicapool3
  clusterNamespace: rook
  clusterName: rook-cluster
```

When I try to create the claim:
```
  Type     Reason                Age               From                                                                               Message
  ----     ------                ----              ----                                                                               -------
  Normal   ExternalProvisioning  1m (x79 over 6m)  persistentvolume-controller                                                        waiting for a volume to be created, either by external provisioner "rook.io/block" or manually created by system administrator
  Normal   Provisioning          3s (x10 over 6m)  rook.io/block rook-operator-68cfd8ff8f-smlmx ae4e568f-4a60-11e8-b952-ee602114e76d  External provisioner is provisioning volume for claim "default/mysql-pv-claim3"
  Warning  ProvisioningFailed    3s (x10 over 6m)  rook.io/block rook-operator-68cfd8ff8f-smlmx ae4e568f-4a60-11e8-b952-ee602114e76d  Failed to provision volume with StorageClass "rook-block3": invalid option "clusterNamespace" for volume plugin rookVolumeProvisioner
```

**Environment**:
* OS: Cluster with Ubuntu Xenial machines
* Rook version: `v0.7.0-81.g141e719`
* Kubernetes version: `1.10`
* Kubernetes cluster type: on-premise
* Ceph status: HEALTH_OK

Associated Issue: #1554

**Comment by galexrt** [comment]
@arthur0 Can you also post your Cluster CRD YAML

**Comment by travisn** [comment]
this looks related to #1614 which was merged yesterday. Is there any chance you have an older master build than yesterday?

**Comment by arthur0** [comment]
@galexrt Of course I do:
```
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-cluster
  namespace: rook
spec:
  backend: ceph
  dataDirHostPath: /var/lib/rook
  hostNetwork: false
  monCount: 3
  resources:
  storage: 
    useAllNodes: true
    useAllDevices: false
    deviceFilter:
    metadataDevice:
    location:
    storeConfig:
      databaseSizeMB: 1024 
      journalSizeMB: 10240
```

**Comment by arthur0** [comment]
@travisn I'm not sure. I used the `rook/rook:master` image (v0.7.0-81.g141e719)
So, I tried to change to `v0.7.1` version, but I got a new error on rook-operator (not related, I think):
```
# I have the CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumeattachments.rook.io
spec:
  group: rook.io
  names:
    kind: VolumeAttachment
    listKind: VolumeAttachmentList
    plural: volumeattachments
    singular: volumeattachment
  scope: Namespaced
  version: v1alpha1
```
```
# I have the in ClusterRole manifest
- apiGroups:
  - rook.io
  resources:
  - "*"
  verbs:
  - "*"
```
Logs of operator:
`operator: failed to init resources. failed to create custom resource. customresourcedefinitions.apiextensions.k8s.io "volumeattachments.rook.io" is forbidden: User "system:serviceaccount:rook-system:rook-operator" cannot get customresourcedefinitions.apiextensions.k8s.io at the cluster scope.`
