### ISSUE TITLE
3x performance degradation with cephfs vs rbd

### ISSUE THREAD

**Issue by aocheretnoy** [rook/rook#1706]
We did performance tests with rook on AWS.
We use 6 i3.4xlarge instances for ceph storage (each has 2 x 1900 NVMe SSD ) and cluster config
```
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
spec:
  backend: ceph
  dataDirHostPath: /var/lib/rook
  hostNetwork: false
  monCount: 3
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: false
    deviceFilter: "nvme[0-9]n1"
    metadataDevide: 
    location:
    storeConfig:
      storeType: bluestore
```
We used next command:
```
while true ; do echo -n `date +%d-%m-%Y-%H:%M:%S`; echo ; fio  --direct=1 --rw=randrw --refill_buffers --norandommap --randrepeat=0 --ioengine=libaio --bs=4k --rwmixread=50 --iodepth=16 --numjobs=16 --runtime=5 --group_reporting --name=4ktest --size=128M  | egrep "(read[ ]*:|write[ ]*:)"; echo  ; sleep 1 ; done
```

When we use pool:
```
apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: replicapool
spec:
  failureDomain: osd
  crushRoot: default
  replicated:
    size: 2
```
and mount rbd device to pod we have good performance
```
read: IOPS=19.6k, BW=76.4MiB/s (80.1MB/s)(382MiB/5004msec)
[...]
write: IOPS=19.5k, BW=76.1MiB/s (79.8MB/s)(381MiB/5004msec)
```
When we use filesystem:
```
apiVersion: rook.io/v1alpha1
kind: Filesystem
metadata:
  name: file-fs
spec:
  metadataPool:
    replicated:
      size: 2    
  dataPools:
    - replicated:
        size: 2    
  metadataServer:
    activeCount: 3
    activeStandby: true
```
we had a big drop in performance:
```
read: IOPS=6374, BW=24.9MiB/s (26.1MB/s)(125MiB/5002msec)
[...]
write: IOPS=6430, BW=25.1MiB/s (26.3MB/s)(126MiB/5002msec)
```
Is this performance fall inevitable for shared filesystem or we can somehow avoid it? How can we boost cephfs?

[ods.log](https://github.com/rook/rook/files/1985477/ods.log)
