### ISSUE TITLE
JournalPartitionType exists in code but not used

### ISSUE THREAD

**Issue by ganeshmaharaj** [rook/rook#1775]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
JournalPartitionType exists in the code today but will never be used to create a journal partition either collocated or on a stand-alone drive. Given it is not used, a small code clean-up would be good to avoid future confusions.

What you expected to happen:
Code Cleanup

How to reproduce it (minimal and precise):

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 16.04.03 LTS`
* Kernel (e.g. `uname -a`): `Linux rook-dev 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: `Baremetal`
* Rook version (use `rook version` inside of a Rook Pod):  `rook: v0.7.0`
* Kubernetes version (use `kubectl version`): `v1.10.3`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `Baremetal`
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
```
  cluster:
    id:     0e273eb2-d6b2-4aeb-9103-cad500f14d71
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum rook-ceph-mon1,rook-ceph-mon0,rook-ceph-mon2
    mgr: rook-ceph-mgr0(active)
    osd: 2 osds: 2 up, 2 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 bytes
    usage:   3325 MB used, 16575 MB / 19900 MB avail
    pgs:
```
