### ISSUE TITLE
BlueStore not using device specified in CRD

### ISSUE THREAD

**Issue by fritchie** [rook/rook#1818]
Bug Report

What Happened:

BlueStore is using files in /var/lib/rook (/dev/sda) for block storage rather than using the specified raw device (/dev/sdb).

What did I expect to happen:

BlueStore using raw devices (/dev/sdb).

OS: CentOS Linux release 7.4.1708 (Core)
Kernel: 3.10.0-693.21.1.el7.x86_64
Provider: On premise Nutanix VM
Rook Version: rook: v0.7.0-211.gf8866e6
Kube Version: 1.9.5
Kube Cluster: Kubespray
Ceph status:

```
# kubectl -n rook-ceph exec -it rook-ceph-mon0-jwt82 -- ceph -s
  cluster:
    id:     3857c93f-be68-4944-89b9-c7c6d00a730d
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum rook-ceph-mon0,rook-ceph-mon1,rook-ceph-mon2
    mgr: a(active)
    osd: 3 osds: 3 up, 3 in
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 bytes
    usage:   3079 MB used, 296 GB / 299 GB avail
    pgs:     

```

I am attempting to use 3 identical block devices (sdb, 500G) as OSDs:

```
  # lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0  100G  0 disk 
└─sda1   8:1    0  100G  0 part /
sdb      8:16   0  500G  0 disk 
sr0     11:0    1 1024M  0 rom  
sr1     11:1    1  374K  0 rom  

```

In /var/lib/rook/osdX I see block, block.db and block.wal pointing to files on the local filesystem (/dev/sda):

```
 # ll
total 452
lrwxrwxrwx. 1 root root           34 Jun 22 10:03 block -> /var/lib/rook/osd2/bluestore-block
lrwxrwxrwx. 1 root root           31 Jun 22 10:03 block.db -> /var/lib/rook/osd2/bluestore-db
lrwxrwxrwx. 1 root root           32 Jun 22 10:03 block.wal -> /var/lib/rook/osd2/bluestore-wal
```

In previous Rook versions BlueStore used raw devices with the same CRD.
 
Sample:

```
# ll
total 52
lrwxrwxrwx. 1 root root   58 Apr 16 16:20 block -> /dev/disk/by-partuuid/33116a82-cd0c-43d2-a43c-1d52923e4f95
lrwxrwxrwx. 1 root root   58 Apr 16 16:20 block.db -> /dev/disk/by-partuuid/2d60a24f-9142-46e3-8601-0e02cd4936e6
lrwxrwxrwx. 1 root root   58 Apr 16 16:20 block.wal -> /dev/disk/by-partuuid/273a0a74-08cd-4c10-9ab4-6b980e2cf478
```

I zapped the disks with "sgdisk -z /dev/sdb" before deploying.

**Comment by fritchie** [comment]
CRD:

```
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: ceph.rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  network:
    hostNetwork: true
  resources:
    mgr:
      limits:
        cpu: "500m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "1024Mi"
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    location:
    config:
      storeType: bluestore
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
    nodes:
    - name: "host1"
      devices:
      - name: "sdb"
    - name: "host2"
      devices:
      - name: "sdb"
    - name: "host3"
      devices:
      - name: "sdb"
```
