### ISSUE TITLE
ClusterRole rook-ceph-system-psp-user is missing in the Helm chart

### ISSUE THREAD

**Issue by sebastien-prudhomme** [rook/rook#1833]
Seems the serviceaccount rook-ceph-system is missing the rook-ceph-cluster-mgmt role.

Logs in the rook-ceph-operator:

```
2018-06-28 09:03:21.568409 I | op-mon: start running mons
2018-06-28 09:03:21.599774 E | op-cluster: failed to create cluster in namespace rook-ceph-system. failed to start the mons. failed to initialize ceph cluster info. failed to get cluster info. failed to get mon secrets. secrets "rook-ceph-mon" is forbidden: User "system:serviceaccount:rook-ceph-system:rook-ceph-system" cannot get secrets in the namespace "rook-ceph-system": clusterrole.rbac.authorization.k8s.io "rook-ceph-system-psp-user" not found 
```

**Comment by galexrt** [comment]
@sebastien-prudhomme Can you please post some more info.
Which version of the Helm chart was used?

**Comment by sebastien-prudhomme** [comment]
I'm using the one in the master branch.

If i look at tests/framework/installer/install_data.go, the missing code should be like this:

```yaml
# Allow the operator to create resources in this cluster's namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-cluster-mgmt
  namespace: ` + namespace + `
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-cluster-mgmt
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: ` + systemNamespace + `
```

**Comment by sebastien-prudhomme** [comment]
I add this YAML code to the chart and all seems ok now: 

```yaml
# Allow the operator to create resources in this cluster's namespace
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-cluster-mgmt
  labels:
    operator: rook
    storage-backend: ceph
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-cluster-mgmt
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: {{ .Release.Namespace }}
```
