### ISSUE TITLE
Tolerations in osd pods not being set

### ISSUE THREAD

**Issue by Segflow** [rook/rook#1895]
My Storage nodes have the label `role=storage-node` and tainted with `storage=true:NoSchedule`.

In my cluster config, I have this under placement field:
```
placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - storage-node
      tolerations:
      - key: "storage"
        operator: "Exists"
        effect: "NoSchedule"
  storage: 
    useAllNodes: false
    useAllDevices: false
    devices:
    - name: "vda2"

    nodes:
    - name: "storage-node-1"
    - name: "storage-node-2"
    - name: "storage-node-3"
```
Every thing works fines, mon pods are being scheduled in the storage nodes, agent in all nodes.

But no osd pod get scheduled. They stay in pending state because no Node is available for them. Using the dashboard I check their manifest file and didn't found the `toleration` field. So by adding this to the osd pods:
```
"tolerations": [
      {
        "key": "storage",
        "operator": "Exists",
        "effect": "NoSchedule"
      }
 ]
```

The pods got scheduled and I have my first PVC in bound state.

**Deviation from expected behavior:**
Toleration being set in osd pods, but it's not.

**Expected behavior:**
Toleration being set in osd pods

**How to reproduce it (minimal and precise):**
Taint storage nodes.

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
* Kernel (e.g. `uname -a`):
```
Linux k8s-master-1 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
* Cloud provider or hardware configuration:
Exoscale. 
* Rook version (use `rook version` inside of a Rook Pod):
rook: v0.7.0-284.g863c10f
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Installed using kubespray.
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
HEALTH_OK

**Comment by rcgoodfellow** [comment]
First off, thanks for Rook. It's pretty awesome.

I seem to be hitting this issue, but manifesting in a slightly different way. I'm seeing the following in the rook operator logs when my Ceph nodes are tainted.

```
op-osd: no valid node available to run an osd in namespace rook-ceph
```
seemingly from #1990. I'm using a combination of affinities and taints.

```yaml
placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - storage-node
      podAffinity:
      podAntiAffinity:
      tolerations:
      - key: storage-node
        operator: Exists
```

The Ceph nodes are tainted with the following, where `$x` is the node name.

```shell
kubectl taint nodes $x storage-node=$x:NoSchedule
```

According to my reading of the [k8s docs on tolerations](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration), the above toleration should allow the tainted nodes to be scheduled.

If I remove the taint from the nodes, and restart the operator (not sure if the restart is strictly required), the OSDs fire up. Note that other Rook pods seem to target the tainted nodes just fine, such as monitors and the manager.

I'm running Kubernetes version 1.13.0.
