### ISSUE TITLE
failed to create cluster in namespace... failed to start the mons

### ISSUE THREAD

**Issue by pcm32** [rook/rook#1903]
**Is this a bug report or feature request?**
Bug Report

**Deviation from expected behavior:**

After starting operator through helm, and create cluster through kubectl, cluster doesn't seem to be created, operator log repeatedly shows (until giving up):
```
op-mon: start running mons
op-cluster: failed to create cluster in namespace rook. failed to start the mons. failed to initialize ceph cluster info. failed to get cluster info. failed to get mon secrets. secrets "rook-ceph-mon" is forbidden: User "system:serviceaccount:rook:rook-ceph-system" cannot get secrets in the namespace "rook"
```

**Expected behavior:**

Cluster gets created.

**How to reproduce it (minimal and precise):**
```
# Create a rook namespace
# Create operator with helm:
helm install --name rook --namespace rook rook-master/rook-ceph -f rook-config.yaml --version v0.7.0-284.g863c10f
# Create cluster:
kubectl create -f rook-cluster.yaml
```

rook-config.yaml:
```
agent:
  flexVolumeDirPath: "/var/lib/kubelet/volume-plugins"
```

rook-cluster.yaml:
```
---
apiVersion: ceph.rook.io/v1beta1
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook
spec:
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  serviceAccount: rook-ceph-cluster
  resources:
    limits:
      cpu: "4"
      memory: "8Gi"
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "solr-scale-k8s-node-nf-1"
    - name: "solr-scale-k8s-node-nf-2"
    - name: "solr-scale-k8s-node-nf-3"
    storeConfig:
      storeType: filestore
      databaseSizeMB: 1024
      journalSizeMB: 1024
```

**Environment**:
* OS (e.g. from /etc/os-release):
Ubuntu 16.04.4 LTS
* Kernel (e.g. `uname -a`):
Linux k8s-master-1 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
OpenStack
* Rook version (use `rook version` inside of a Rook Pod):
v0.7.0-284.g863c10f (from helm)
* Kubernetes version (use `kubectl version`):
1.9.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Kubespray v2.4.0
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
Not sure I get this far.

* Additionals:
PodSecurityPolicy Admission Controller is not activated as far as I can see.

Thanks!
