### ISSUE TITLE
failed to create cluster in namespace ... . failed to start the osds

### ISSUE THREAD

**Issue by pcm32** [rook/rook#1904]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

osd orchestration status never comes up, logs in the operator show, in the last trial:
```
2018-07-18 10:55:12.363684 I | op-osd: osd orchestration status for node solr-scale-k8s-node-nf-1 is starting
2018-07-18 10:55:12.363706 I | op-osd: osd orchestration status for node solr-scale-k8s-node-nf-2 is starting
2018-07-18 10:55:12.363713 I | op-osd: osd orchestration status for node solr-scale-k8s-node-nf-3 is starting
2018-07-18 10:55:12.363722 I | op-osd: 0/3 node(s) completed osd provisioning
2018-07-18 10:56:12.365199 I | op-osd: waiting on orchestration status update from 3 remaining nodes
2018-07-18 10:57:12.365535 I | op-osd: waiting on orchestration status update from 3 remaining nodes
2018-07-18 10:58:12.365802 I | op-osd: waiting on orchestration status update from 3 remaining nodes
2018-07-18 10:59:12.366154 I | op-osd: waiting on orchestration status update from 3 remaining nodes
2018-07-18 11:00:12.366455 I | op-osd: waiting on orchestration status update from 3 remaining nodes
2018-07-18 11:01:12.366735 I | op-osd: waiting on orchestration status update from 3 remaining nodes
2018-07-18 11:02:12.367025 I | op-osd: waiting on orchestration status update from 3 remaining nodes
2018-07-18 11:03:12.367305 I | op-osd: waiting on orchestration status update from 3 remaining nodes
2018-07-18 11:04:12.367653 I | op-osd: waiting on orchestration status update from 3 remaining nodes
2018-07-18 11:05:12.463575 E | op-osd: timed out waiting for 3 nodes: &{values:map[solr-scale-k8s-node-nf-1:{} solr-scale-k8s-node-nf-2:{} solr-scale-k8s-node-nf-3:{}]}
2018-07-18 11:05:12.463729 I | op-osd: checking if any nodes were removed
2018-07-18 11:05:12.470229 I | op-osd: processing 0 removed nodes
2018-07-18 11:05:12.470267 I | op-osd: done processing removed nodes
2018-07-18 11:05:12.470594 I | exec: Running command: ceph osd unset noscrub --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/177863255
2018-07-18 11:05:15.966979 I | exec: noscrub is unset
2018-07-18 11:05:15.967250 I | exec: Running command: ceph osd unset nodeep-scrub --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/457752522
2018-07-18 11:05:18.863539 I | exec: nodeep-scrub is unset
2018-07-18 11:05:18.863667 E | op-cluster: failed to create cluster in namespace rook. failed to start the osds. 2 failures encountered while running osds in namespace rook: timed out waiting for 3 nodes: &{values:map[solr-scale-k8s-node-nf-1:{} solr-scale-k8s-node-nf-2:{} solr-scale-k8s-node-nf-3:{}]}
timed out waiting for 3 nodes: &{values:map[solr-scale-k8s-node-nf-2:{} solr-scale-k8s-node-nf-3:{} solr-scale-k8s-node-nf-1:{}]}
2018-07-18 11:05:18.863685 E | op-cluster: giving up creating cluster in namespace rook after 5m0s
```

I tried with host network set both to true and false (as I thought it could be a node name resolution problem), with the same result. Shown logs are with hostNetwork: true.

**Expected behavior:**

osds to start in the expected nodes.

**How to reproduce it (minimal and precise):**
```
# Create a rook namespace
# Create operator with helm:
helm install --name rook --namespace rook rook-master/rook-ceph -f rook-config.yaml --version v0.7.0-284.g863c10f
# Create RBAC API Objects as suggested on Issue #1903
kubectl create -f rook-roles.yaml -n rook
# Create cluster:
kubectl create -f rook-cluster.yaml
```

rook-config.yaml:
```
agent:
  flexVolumeDirPath: "/var/lib/kubelet/volume-plugins"
```

rook-roles.yaml:
```
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-cluster
  namespace: rook
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: [ "get", "list", "watch", "create", "update", "delete" ]
---
# Allow the operator to create resources in this cluster's namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-cluster-mgmt
  namespace: rook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-cluster-mgmt
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook
---
# Allow the pods in this namespace to work with configmaps
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-cluster
  namespace: rook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-cluster
subjects:
- kind: ServiceAccount
  name: rook-ceph-cluster
  namespace: rook
```

rook-cluster.yaml:
```
---
apiVersion: ceph.rook.io/v1beta1
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook
spec:
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  serviceAccount: rook-ceph-cluster
  resources:
    limits:
      cpu: "4"
      memory: "8Gi"
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "solr-scale-k8s-node-nf-1"
    - name: "solr-scale-k8s-node-nf-2"
    - name: "solr-scale-k8s-node-nf-3"
    storeConfig:
      storeType: filestore
      databaseSizeMB: 1024
      journalSizeMB: 1024
```

**Environment**:
* OS (e.g. from /etc/os-release):
Ubuntu 16.04.4 LTS
* Kernel (e.g. `uname -a`):
Linux k8s-master-1 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
OpenStack
* Rook version (use `rook version` inside of a Rook Pod):
v0.7.0-284.g863c10f (from helm)
* Kubernetes version (use `kubectl version`):
1.9.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Kubespray v2.4.0
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
Not sure I get this far.

* Additionals:
PodSecurityPolicy Admission Controller is not activated as far as I can see.

Thanks!

**Comment by travisn** [comment]
@pcm32 The "osd prepare" pod logs likely show an issue here. I suspect there is a misconfiguration with the rook-ceph-cluster service account that is preventing the osds from updating the configmaps.

**Comment by pcm32** [comment]
Thanks! I couldn't find any such osd pods running when doing it, only some jobs with osd in their nameas, but I couldn't find any pods associated to them. I will re-create the cluster and post the available pods. The only pods I had in addition to agents, discover and operator where some mon pods.

**Comment by travisn** [comment]
@pcm32 was the job named such as this? `rook-ceph-osd-prepare-<node>`. If a pod wasn't created for that job, does `kubectl describe job` for the osd job show anything helpful?

**Comment by pcm32** [comment]
Pods available after creating the cluster:

```
$ kubectl get pods -n rook
NAME                                  READY     STATUS    RESTARTS   AGE
rook-ceph-agent-4slzs                 1/1       Running   0          6h
rook-ceph-agent-bl578                 1/1       Running   0          6h
rook-ceph-agent-gxwzr                 1/1       Running   0          6h
rook-ceph-agent-hf2cs                 1/1       Running   0          6h
rook-ceph-agent-sh4hd                 1/1       Running   0          6h
rook-ceph-agent-shljb                 1/1       Running   0          6h
rook-ceph-mgr-a-549f69684c-q4kkp      1/1       Running   0          13s
rook-ceph-mon0-cxxks                  1/1       Running   5          3m
rook-ceph-mon1-48sws                  1/1       Running   0          40s
rook-ceph-mon2-65fgf                  1/1       Running   0          29s
rook-ceph-operator-6f7dd4c559-2qwzq   1/1       Running   0          5h
rook-discover-dhp6n                   1/1       Running   0          6h
rook-discover-gh7x2                   1/1       Running   0          6h
rook-discover-lhhnl                   1/1       Running   0          6h
rook-discover-qdpdc                   1/1       Running   0          6h
rook-discover-sc8l9                   1/1       Running   0          6h
rook-discover-z7c9l                   1/1       Running   0          6h
```

Jobs:
```
$ kubectl get jobs -n rook
NAME                                             DESIRED   SUCCESSFUL   AGE
rook-ceph-osd-prepare-solr-scale-k8s-node-nf-1   1         0            1m
rook-ceph-osd-prepare-solr-scale-k8s-node-nf-2   1         0            1m
rook-ceph-osd-prepare-solr-scale-k8s-node-nf-3   1         0            1m
```

Ok, now the Jobs show something in the events (maybe last time I tried it took me too long to get there to see any events):


```
kubectl describe jobs/rook-ceph-osd-prepare-solr-scale-k8s-node-nf-1 -n rook
Name:           rook-ceph-osd-prepare-solr-scale-k8s-node-nf-1
Namespace:      rook
Selector:       controller-uid=31b1eac1-8aa1-11e8-96b2-fa163e80acad
Labels:         app=rook-ceph-osd-prepare
                rook_cluster=rook
Annotations:    <none>
Parallelism:    1
Completions:    1
Pods Statuses:  0 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=rook-ceph-osd-prepare
                    controller-uid=31b1eac1-8aa1-11e8-96b2-fa163e80acad
                    job-name=rook-ceph-osd-prepare-solr-scale-k8s-node-nf-1
                    rook_cluster=rook
  Service Account:  rook-ceph-cluster
....
Events:
  Type     Reason        Age               From            Message
  ----     ------        ----              ----            -------
  Warning  FailedCreate  24s (x4 over 1m)  job-controller  Error creating: pods "rook-ceph-osd-prepare-solr-scale-k8s-node-nf-1-" is forbidden: error looking up service account rook/rook-ceph-cluster: serviceaccount "rook-ceph-cluster" not found
```

Available service accounts:
```
$ kubectl get serviceaccount -n rook
NAME               SECRETS   AGE
default            1         7h
rook-ceph-system   1         5h
```

So, is `rook-ceph-cluster` meant to be a separate service account to `rook-ceph-system` (in which case I need to figure out why or where it wasn't created), or do I just need to make sure that the same service account is being used with the same name at all places?

Thanks!

**Comment by travisn** [comment]
the intention is for `rook-ceph-system` to be for the operator, agent, and discover, and the `rook-ceph-cluster` will be for the cluster-specific resources. (You can have multiple clusters although that is not the common scenario). The `rook-ceph-cluster` SA in the examples can be found in cluster.yaml.

**Comment by pcm32** [comment]
Great, will use that! Does it need to live in a particular namespace, or putting everything on the same namespace is fine?

**Comment by pcm32** [comment]
So shouldn't `rook-ceph-system` be created by the helm repo when creating the operator and agents?

**Comment by travisn** [comment]
Yes, the `rook-ceph-system` SA should have been created by the helm chart as seen [here](https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/templates/serviceaccount.yaml). 

It is fine to put everything in the same namespace, or different namespaces than the example. The only restriction currently is that you can only have a single Rook Ceph cluster CRD defined in a namespace.

**Comment by pcm32** [comment]
Should I be using a different version of the helm chart? Currently doing:

```
helm install --name rook --namespace rook rook-master/rook-ceph -f rook-config.yaml --version v0.7.0-284.g863c10f
```

Thanks!

**Comment by pcm32** [comment]
Ahh, you are right, I meant rook-ceph-cluster, ok that makes sense. Will try adding the additional service account.

**Comment by pcm32** [comment]
Adding the `rook-ceph-cluster` service account as
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-cluster
  namespace: rook
```
sorted my issue, as suggested by @travisn. Thanks!
