### ISSUE TITLE
"OSD Prepare running on nodes that are 'invalid'" (e.g. placement not matching)

### ISSUE THREAD

**Issue by arkanmgerges** [rook/rook#1925]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**
Add taints to the storage nodes and modify cluster.yaml and operator.yaml to use these node storage

**Environment**:
* OS (e.g. from /etc/os-release):
```sh
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

* Kernel (e.g. `uname -a`):
Linux node1 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
VirtualBox on a laptop

* Rook version (use `rook version` inside of a Rook Pod):
rook: v0.8.0

* Kubernetes version (use `kubectl version`):
```yaml
clientVersion:
  buildDate: 2018-07-17T18:53:20Z
  compiler: gc
  gitCommit: b1b29978270dc22fecc592ac55d903350454310a
  gitTreeState: clean
  gitVersion: v1.11.1
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-06-27T20:08:34Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.2
  major: "1"
  minor: "11"
  platform: linux/amd64

```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
On-premise (on a laptop with 6 VirtualBox machines), 1 master node, 2 workers, 3 storage nodes

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

```sh
[root@rook-ceph-tools /]# ceph health
HEALTH_WARN noscrub,nodeep-scrub flag(s) set
```
```sh
[root@rook-ceph-tools /]# ceph status
  cluster:
    id:     9f50ccc7-b276-4594-bfbe-06cecd4e9e36
    health: HEALTH_WARN
            noscrub,nodeep-scrub flag(s) set
 
  services:
    mon: 3 daemons, quorum rook-ceph-mon0,rook-ceph-mon2,rook-ceph-mon1
    mgr: a(active)
    osd: 3 osds: 3 up, 3 in
         flags noscrub,nodeep-scrub
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 bytes
    usage:   26198 MB used, 117 GB / 143 GB avail
    pgs:     
```
```sh
[root@rook-ceph-tools /]# ceph quorum_status
{"election_epoch":12,"quorum":[0,1,2],"quorum_names":["rook-ceph-mon0","rook-ceph-mon2","rook-ceph-mon1"],"quorum_leader_name":"rook-ceph-mon0","monmap":{"epoch":3,"fsid":"9f50ccc7-b276-4594-bfbe-06cecd4e9e36","modified":"2018-07-21 09:30:06.043301","created":"2018-07-21 09:29:47.733522","features":{"persistent":["kraken","luminous"],"optional":[]},"mons":[{"rank":0,"name":"rook-ceph-mon0","addr":"10.102.3.68:6790/0","public_addr":"10.102.3.68:6790/0"},{"rank":1,"name":"rook-ceph-mon2","addr":"10.108.199.152:6790/0","public_addr":"10.108.199.152:6790/0"},{"rank":2,"name":"rook-ceph-mon1","addr":"10.110.190.32:6790/0","public_addr":"10.110.190.32:6790/0"}]}}
```
```sh
[root@rook-ceph-tools /]# ceph mon_status
{"name":"rook-ceph-mon1","rank":2,"state":"peon","election_epoch":12,"quorum":[0,1,2],"features":{"required_con":"153140804152475648","required_mon":["kraken","luminous"],"quorum_con":"2305244844532236283","quorum_mon":["kraken","luminous"]},"outside_quorum":[],"extra_probe_peers":["10.108.199.152:6790/0"],"sync_provider":[],"monmap":{"epoch":3,"fsid":"9f50ccc7-b276-4594-bfbe-06cecd4e9e36","modified":"2018-07-21 09:30:06.043301","created":"2018-07-21 09:29:47.733522","features":{"persistent":["kraken","luminous"],"optional":[]},"mons":[{"rank":0,"name":"rook-ceph-mon0","addr":"10.102.3.68:6790/0","public_addr":"10.102.3.68:6790/0"},{"rank":1,"name":"rook-ceph-mon2","addr":"10.108.199.152:6790/0","public_addr":"10.108.199.152:6790/0"},{"rank":2,"name":"rook-ceph-mon1","addr":"10.110.190.32:6790/0","public_addr":"10.110.190.32:6790/0"}]},"feature_map":{"mon":{"group":{"features":"0x1ffddff8eea4fffb","release":"luminous","num":1}},"client":{"group":{"features":"0x1ffddff8eea4fffb","release":"luminous","num":1}}}}
```

The not all the osds pod are scheduled on the storage nodes.

```sh
root@node1:/home/arkan# kubectl -n rook-ceph get all
NAME                                       READY     STATUS      RESTARTS   AGE
pod/rook-ceph-mgr-a-54458c6f9-4dx7r        1/1       Running     0          21m
pod/rook-ceph-mon0-vzm79                   1/1       Running     0          22m
pod/rook-ceph-mon1-9scx9                   1/1       Running     0          22m
pod/rook-ceph-mon2-7zkv7                   1/1       Running     0          21m
pod/rook-ceph-osd-id-0-557c7fc59f-8dfdg    1/1       Running     0          21m
pod/rook-ceph-osd-id-1-58cc99d9bd-qvhpn    1/1       Running     0          21m
pod/rook-ceph-osd-id-2-7cc96bd666-gtpbq    1/1       Running     0          21m
pod/rook-ceph-osd-prepare-node2-kq5g4      0/1       Pending     0          21m
pod/rook-ceph-osd-prepare-node3-ms5xp      0/1       Pending     0          21m
pod/rook-ceph-osd-prepare-storage1-jx54w   0/1       Completed   0          9m
pod/rook-ceph-osd-prepare-storage2-j462s   0/1       Completed   0          9m
pod/rook-ceph-osd-prepare-storage3-5xjh2   0/1       Completed   0          9m
pod/rook-ceph-tools                        1/1       Running     0          22m

NAME                                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/rook-ceph-mgr                      ClusterIP   10.101.24.98     <none>        9283/TCP   21m
service/rook-ceph-mgr-dashboard            ClusterIP   10.98.15.70      <none>        7000/TCP   21m
service/rook-ceph-mgr-dashboard-external   ClusterIP   10.108.39.235    <none>        7000/TCP   22m
service/rook-ceph-mon0                     ClusterIP   10.102.3.68      <none>        6790/TCP   22m
service/rook-ceph-mon1                     ClusterIP   10.110.190.32    <none>        6790/TCP   22m
service/rook-ceph-mon2                     ClusterIP   10.108.199.152   <none>        6790/TCP   21m

NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rook-ceph-mgr-a      1         1         1            1           21m
deployment.apps/rook-ceph-osd-id-0   1         1         1            1           21m
deployment.apps/rook-ceph-osd-id-1   1         1         1            1           21m
deployment.apps/rook-ceph-osd-id-2   1         1         1            1           21m

NAME                                            DESIRED   CURRENT   READY     AGE
replicaset.apps/rook-ceph-mgr-a-54458c6f9       1         1         1         21m
replicaset.apps/rook-ceph-mon0                  1         1         1         22m
replicaset.apps/rook-ceph-mon1                  1         1         1         22m
replicaset.apps/rook-ceph-mon2                  1         1         1         21m
replicaset.apps/rook-ceph-osd-id-0-557c7fc59f   1         1         1         21m
replicaset.apps/rook-ceph-osd-id-1-58cc99d9bd   1         1         1         21m
replicaset.apps/rook-ceph-osd-id-2-7cc96bd666   1         1         1         21m

NAME                                       DESIRED   SUCCESSFUL   AGE
job.batch/rook-ceph-osd-prepare-node2      1         0            21m
job.batch/rook-ceph-osd-prepare-node3      1         0            21m
job.batch/rook-ceph-osd-prepare-storage1   1         1            9m
job.batch/rook-ceph-osd-prepare-storage2   1         1            9m
job.batch/rook-ceph-osd-prepare-storage3   1         1            9m
```

```sh
root@node1:/home/arkan# kubectl -n rook-ceph-system get all
NAME                                      READY     STATUS    RESTARTS   AGE
pod/rook-ceph-agent-8hmmt                 1/1       Running   0          23m
pod/rook-ceph-agent-8njp5                 1/1       Running   0          23m
pod/rook-ceph-agent-jdclt                 1/1       Running   0          23m
pod/rook-ceph-agent-l7xj7                 1/1       Running   0          23m
pod/rook-ceph-agent-mjw5t                 1/1       Running   0          23m
pod/rook-ceph-operator-56565dfdcf-sjwjp   1/1       Running   0          23m
pod/rook-discover-52tjd                   1/1       Running   0          23m
pod/rook-discover-gktzq                   1/1       Running   0          23m
pod/rook-discover-s62fd                   1/1       Running   0          23m
pod/rook-discover-w54r8                   1/1       Running   0          23m
pod/rook-discover-w8mfh                   1/1       Running   0          23m

NAME                             DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/rook-ceph-agent   5         5         5         5            5           <none>          23m
daemonset.apps/rook-discover     5         5         5         5            5           <none>          23m

NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rook-ceph-operator   1         1         1            1           23m

NAME                                            DESIRED   CURRENT   READY     AGE
replicaset.apps/rook-ceph-operator-56565dfdcf   1         1         1         23m
```

cluster.yaml manifest
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: [ "get", "list", "watch", "create", "update", "delete" ]
---
# Allow the operator to create resources in this cluster's namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-cluster-mgmt
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-cluster-mgmt
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph-system
---
# Allow the pods in this namespace to work with configmaps
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-cluster
subjects:
- kind: ServiceAccount
  name: rook-ceph-cluster
  namespace: rook-ceph
---
apiVersion: ceph.rook.io/v1beta1
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  # The path on the host where configuration files will be persisted. If not specified, a kubernetes emptyDir will be created (not recommended).
  # Important: if you reinstall the cluster, make sure you delete this directory from each host or else the mons will fail to start on the new cluster.
  # In Minikube, the '/data' directory is configured to persist across reboots. Use "/data/rook" in Minikube environment.
  dataDirHostPath: "/var/lib/rook"
  # The service account under which to run the daemon pods in this cluster if the default account is not sufficient (OSDs)
  serviceAccount: rook-ceph-cluster
  # set the amount of mons to be started
  mon:
    count: 3
    allowMultiplePerNode: true
  # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: true
  network:
    # toggle to use hostNetwork
    hostNetwork: false
  # To control where various services will be scheduled by kubernetes, use the placement configuration sections below.
  # The example under 'all' would have all services scheduled on kubernetes nodes labeled with 'role=storage-node' and
  # tolerate taints with a key of 'storage-node'.
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - storage-node
#      podAffinity:
#      podAntiAffinity:
      tolerations:
      - key: storage-node
        operator: Exists
        effect: NoSchedule
# The above placement information can also be specified for mon, osd, and mgr components
#    mon:
#    osd:
#    mgr:
  resources:
# The requests and limits set here, allow the mgr pod to use half of one CPU core and 1 gigabyte of memory
#    mgr:
#      limits:
#        cpu: "500m"
#        memory: "1024Mi"
#      requests:
#        cpu: "500m"
#        memory: "1024Mi"
# The above example requests/limits can also be added to the mon and osd components
#    mon:
#    osd:
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: false
    deviceFilter:
    location:
    config:
      # The default and recommended storeType is dynamically set to bluestore for devices and filestore for directories.
      # Set the storeType explicitly only if it is required not to use the default.
      # storeType: bluestore
      databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
# Cluster level list of directories to use for storage. These values will be set for all nodes that have no `directories` set.
#    directories:
#    - path: /rook/storage-dir
# Individual nodes and their config can be specified as well, but 'useAllNodes' above must be set to false. Then, only the named
# nodes below will be used as storage resources.  Each node's 'name' field should match their 'kubernetes.io/hostname' label.
#    nodes:
#    - name: "172.17.4.101"
#      directories: # specific directories to use for storage can be specified for each node
#      - path: "/rook/storage-dir"
#      resources:
#        limits:
#          cpu: "500m"
#          memory: "1024Mi"
#        requests:
#          cpu: "500m"
#          memory: "1024Mi"
#    - name: "172.17.4.201"
#      devices: # specific devices to use for storage can be specified for each node
#      - name: "sdb"
#      - name: "sdc"
#      config: # configuration can be specified at the node level which overrides the cluster level config
#        storeType: filestore
#    - name: "172.17.4.301"
#      deviceFilter: "^sd."
```

operator.yaml manifest
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusters.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
    shortNames:
    - rcc
  scope: Namespaced
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: filesystems.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: Filesystem
    listKind: FilesystemList
    plural: filesystems
    singular: filesystem
    shortNames:
    - rcfs
  scope: Namespaced
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: objectstores.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: ObjectStore
    listKind: ObjectStoreList
    plural: objectstores
    singular: objectstore
    shortNames:
    - rco
  scope: Namespaced
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pools.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: Pool
    listKind: PoolList
    plural: pools
    singular: pool
    shortNames:
    - rcp
  scope: Namespaced
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumes.rook.io
spec:
  group: rook.io
  names:
    kind: Volume
    listKind: VolumeList
    plural: volumes
    singular: volume
    shortNames:
    - rv
  scope: Namespaced
  version: v1alpha2
---
# The cluster role for managing all the cluster-specific resources in a namespace
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rook-ceph-cluster-mgmt
  labels:
    operator: rook
    storage-backend: ceph
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - services
  - configmaps
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - update
  - delete
- apiGroups:
  - extensions
  resources:
  - deployments
  - daemonsets
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
# The role for the operator to manage resources in the system namespace
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: rook-ceph-system
  namespace: rook-ceph-system
  labels:
    operator: rook
    storage-backend: ceph
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - update
  - delete
- apiGroups:
  - extensions
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
# The cluster role for managing the Rook CRDs
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rook-ceph-global
  labels:
    operator: rook
    storage-backend: ceph
rules:
- apiGroups:
  - ""
  resources:
  # Pod access is needed for fencing
  - pods
  # Node access is needed for determining nodes where mons should run
  - nodes
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
    # PVs and PVCs are managed by the Rook provisioner
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - update
  - delete
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete   
- apiGroups:
  - ceph.rook.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - rook.io
  resources:
  - "*"
  verbs:
  - "*"
---
# The rook system service account used by the operator, agent, and discovery pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-system
  namespace: rook-ceph-system
  labels:
    operator: rook
    storage-backend: ceph
---
# Grant the operator, agent, and discovery agents access to resources in the rook-ceph-system namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-system
  namespace: rook-ceph-system
  labels:
    operator: rook
    storage-backend: ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-system
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph-system
---
# Grant the rook system daemons cluster-wide access to manage the Rook CRDs, PVCs, and storage classes
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-global
  namespace: rook-ceph-system
  labels:
    operator: rook
    storage-backend: ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-global
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph-system
---
# The deployment for the rook operator
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph-system
  labels:
    operator: rook
    storage-backend: ceph
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rook-ceph-operator
    spec:
      serviceAccountName: rook-ceph-system
      containers:
      - name: rook-ceph-operator
        image: rook/ceph:v0.8.0
        args: ["ceph", "operator"]
        volumeMounts:
        - mountPath: /var/lib/rook
          name: rook-config
        - mountPath: /etc/ceph
          name: default-config-dir
        env:
        # To disable RBAC, uncomment the following:
        # - name: RBAC_ENABLED
        #  value: "false"
        # Rook Agent toleration. Will tolerate all taints with all keys.
        # Choose between NoSchedule, PreferNoSchedule and NoExecute:
        - name: AGENT_TOLERATION
          value: "NoSchedule"
        # (Optional) Rook Agent toleration key. Set this to the key of the taint you want to tolerate
        - name: AGENT_TOLERATION_KEY
          value: "storage-node"
        # Set the path where the Rook agent can find the flex volumes
        # - name: FLEXVOLUME_DIR_PATH
        #  value: "<PathToFlexVolumes>"
        # Rook Discover toleration. Will tolerate all taints with all keys.
        # Choose between NoSchedule, PreferNoSchedule and NoExecute:
        - name: DISCOVER_TOLERATION
          value: "NoSchedule"
        # (Optional) Rook Discover toleration key. Set this to the key of the taint you want to tolerate
        - name: DISCOVER_TOLERATION_KEY
          value: "storage-node"
        # Allow rook to create multiple file systems. Note: This is considered
        # an experimental feature in Ceph as described at
        # http://docs.ceph.com/docs/master/cephfs/experimental-features/#multiple-filesystems-within-a-ceph-cluster
        # which might cause mons to crash as seen in https://github.com/rook/rook/issues/1027
        - name: ROOK_ALLOW_MULTIPLE_FILESYSTEMS
          value: "false"
        # The logging level for the operator: INFO | DEBUG 
        - name: ROOK_LOG_LEVEL
          value: "INFO"
        # The interval to check if every mon is in the quorum.
        - name: ROOK_MON_HEALTHCHECK_INTERVAL
          value: "45s"
        # The duration to wait before trying to failover or remove/replace the
        # current mon with a new mon (useful for compensating flapping network).
        - name: ROOK_MON_OUT_TIMEOUT
          value: "300s"
        # Whether to start pods as privileged that mount a host path, which includes the Ceph mon and osd pods.
        # This is necessary to workaround the anyuid issues when running on OpenShift.
        # For more details see https://github.com/rook/rook/issues/1314#issuecomment-355799641
        - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
          value: "false"
        # The name of the node to pass with the downward API
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # The pod name to pass with the downward API
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # The pod namespace to pass with the downward API
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: rook-config
        emptyDir: {}
      - name: default-config-dir
        emptyDir: {}
```
