### ISSUE TITLE
OSD Pods fail with unable to open config file

### ISSUE THREAD

**Issue by FaKod** [rook/rook#1939]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
is not able to start OSD Pods. They are failing with:
```
# k -n rook-ceph logs rook-ceph-osd-id-0-56dbf744f9-wmxpn
global_init: unable to open config file from search list /var/lib/rookdata/osd0/rook-ceph.config
```

**How to reproduce it (minimal and precise):**
I configured my cluster with separate node entries like this:
```
dataDirHostPath: /var/lib/rookdata
...
nodes:
    - name: "k8s-bc-worker-abc7b1b"
      directories: 
      - path: "/var/lib/rookdata"
```

**remarks**
- provision jobs complete successfully and the config file is at the desired location on node local SSD
- IMHO the mount point of the OSD Pod is wrong (it is `/var/lib/rook`), it should be `/var/lib/rookdata` as well. Or the container commands are wrong, they shouldn't point to `/var/lib/rookdata/`
- I tried to work around but, if I change the Cluster (CRD) directory attribute to  `/var/lib/rook` the provision jobs fail with `spec.template.spec.containers[0].volumeMounts[2].mountPath: Invalid value: "/var/lib/rook": must be unique`

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): v0.8.0
* Kubernetes version (use `kubectl version`): v1.9.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): own

**Comment by FaKod** [comment]
The operator creates this:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  generation: 2
  labels:
    app: rook-ceph-osd
    ceph-osd-id: "0"
    rook_cluster: rook-ceph
  name: rook-ceph-osd-id-0
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: v1beta1
    blockOwnerDeletion: true
    kind: Cluster
    name: rook-ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-osd
      ceph-osd-id: "0"
      rook_cluster: rook-ceph
  template:
      name: rook-ceph-osd
    spec:
      containers:
      - command:
        - /tini
        - --
        - ceph-osd
        - --public-addr=$(ROOK_PUBLIC_IP)
        - --cluster-addr=$(ROOK_PRIVATE_IP)
        - --foreground
        - --id
        - "0"
        - --conf
        - /var/lib/rookdata/osd0/rook-ceph.config
        - --osd-data
        - /var/lib/rookdata/osd0
        - --keyring
        - /var/lib/rookdata/osd0/keyring
        - --cluster
        - rook-ceph
        - --osd-uuid
        - 8c160503-a814-4915-a610-622b09e5ee6a
        - --osd-journal=/var/lib/rookdata/osd0/journal
...
        image: rook/ceph:v0.8.0
        name: rook-ceph-osd
...
        volumeMounts:
        - mountPath: /var/lib/rook
          name: rook-data
...
      volumes:
      ...
      - hostPath:
          path: /var/lib/rookdata
          type: ""
        name: rook-data
```

Manually changing volumeMounts to ` /var/lib/rookdata`solves it.

**Comment by jbw976** [comment]
I think the original issue here is that you can't add the `dataDirHostPath` as a specific directory to use for storage (ownership) by an OSD also.  That would result in 2 different mounts for the OSD pod coming from the same underlying directory.

I believe the goal here is to have everything Rook needs, both a config/data dir and a storage dir, to be coming from the same single location on the host.  To fulfill that, would it be possible to instead do something like this where the directory for storage is a sub-directory of the `dataDirHostPath`?
```
dataDirHostPath: /var/lib/rookdata
...
nodes:
    - name: "k8s-bc-worker-abc7b1b"
      directories: 
      - path: "/var/lib/rookdata/storage"
```
Be careful when trying this to either make sure your environment fully cleaned up or recreated from scratch, there could easily be some lingering state that could impact this test.
