### ISSUE TITLE
Creating a second ObjectStore doesn't create a second RGW Deamonset/Deployment

### ISSUE THREAD

**Issue by bitfisher** [rook/rook#1948]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Creating a second ObjectStore doesn't create a second RGW Deamonset/Deployment.

Also the amount of created pools are different.

**Expected behavior:**
For each created ObjectStore a RGW Daemonset/Deployment should be created and the same amount of pools should be created too.

**How to reproduce it (minimal and precise):**
---
**Create a Cluster**
```sh
cat <<EOF | kubectl create -f -
apiVersion: ceph.rook.io/v1beta1
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook-ceph
  serviceAccount: rook-ceph-cluster
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  network:
    hostNetwork: false
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: rook.io/ceph
              operator: In
              values:
              - "true"
      podAffinity:
      podAntiAffinity:
      tolerations:
      - key: rook.io/ceph
        operator: Exists
  resources:
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    metadataDevice:
    nodes:
    - name: host-01
      devices:
      - name: sdb
      config:
        storeType: bluestore
    - name: host-02
      devices:
      - name: sdb
      config:
        storeType: bluestore
    - name: host-03
      devices:
      - name: sdb
      config:
        storeType: bluestore
EOF
```
---
**Create first ObjectStore**
```sh
cat <<EOF | kubectl create -f -
apiVersion: ceph.rook.io/v1beta1
kind: ObjectStore
metadata:
  name: first
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPool:
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  gateway:
    type: s3
    port: 80
    instances: 1
    allNodes: true
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: rook.io/ceph
            operator: In
            values:
            - "true"
    podAffinity:
    podAntiAffinity:
    tolerations:
    - key: rook.io/ceph
      operator: Exists
EOF
```
---
**List Resources**
```sh
kubectl -n rook-ceph get all | grep rgw
```
```
pod/rook-ceph-rgw-first-h8gj2                    1/1       Running     0          15h
pod/rook-ceph-rgw-first-vhgxw                    1/1       Running     0          15h
pod/rook-ceph-rgw-first-xtnz6                    1/1       Running     0          15h
service/rook-ceph-rgw-first     ClusterIP   10.43.199.202   <none>        80/TCP     15h
daemonset.apps/rook-ceph-rgw-default   3         3         3         3            3           <none>          15h
```
---
**Create second ObjectStore**
```sh
cat <<EOF | kubectl create -f -
apiVersion: ceph.rook.io/v1beta1
kind: ObjectStore
metadata:
  name: second
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPool:
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  gateway:
    type: s3
    port: 80
    instances: 1
    allNodes: true
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: rook.io/ceph
            operator: In
            values:
            - "true"
    podAffinity:
    podAntiAffinity:
    tolerations:
    - key: rook.io/ceph
      operator: Exists
```
---
**List Resources**
```sh
kubectl -n rook-ceph get all | grep rgw
```
```
pod/rook-ceph-rgw-first-h8gj2                    1/1       Running     0          15h
pod/rook-ceph-rgw-first-vhgxw                    1/1       Running     0          15h
pod/rook-ceph-rgw-first-xtnz6                    1/1       Running     0          15h
service/rook-ceph-rgw-first       ClusterIP   10.43.199.202   <none>        80/TCP     15h
service/rook-ceph-rgw-second      ClusterIP   10.43.35.68     <none>        80/TCP     14h
daemonset.apps/rook-ceph-rgw-first   3         3         3         3            3           <none>          15h
```

As you can see a second Service is created but not a second Daemonset.

---
Also the created pools confuses me a bit ...

**List of created pools**
```sh
[root@rook-ceph-tools /]# ceph osd lspools
1 first.rgw.control,2 first.rgw.meta,3 first.rgw.log,4 first.rgw.buckets.index,5 .rgw.root,6 first.rgw.buckets.data,10 second.rgw.control,11 second.rgw.meta,12 second.rgw.log,
```

There are **5** pools created for **first** ObjectStore but only **3** pools are created for **second** ObjectStore.

It seems like **second.rgw.buckets.index** and **second.rgw.buckets.data** are not created.

---
I already tried the same with following cluster spec with same results.
```yaml
apiVersion: ceph.rook.io/v1beta1
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook-ceph
  serviceAccount: rook-ceph-cluster
  mon:
    count: 3
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  network:
    hostNetwork: false
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: rook.io/ceph
              operator: In
              values:
              - "true"
      podAffinity:
      podAntiAffinity:
      tolerations:
      - key: rook.io/ceph
        operator: Exists
  resources:
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    metadataDevice:
    nodes:
    - name: host-01
      devices:
      - name: sdb
      config:
        storeType: bluestore
    - name: host-02
      devices:
      - name: sdb
      config:
        storeType: bluestore
    - name: host-03
      devices:
      - name: sdb
      config:
        storeType: bluestore
```

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.7.0
VERSION_ID=1745.7.0
BUILD_ID=2018-06-14-0909
PRETTY_NAME="Container Linux by CoreOS 1745.7.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

* Kernel (e.g. `uname -a`):
Linux onl-cloud-dev-01 4.14.48-coreos-r2 #1 SMP Thu Jun 14 08:23:03 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz GenuineIntel GNU/Linux

* Cloud provider or hardware configuration:
Bare Metal

* Rook version (use `rook version` inside of a Rook Pod):
rook: v0.8.0

* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
RKE (Rancher Kubernetes Engine)

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
HEALTH_OK
