### ISSUE TITLE
FIlestore does not reclaim space after data deletion.

### ISSUE THREAD

**Issue by ivanovaleksandar** [rook/rook#1955]
**Is this a bug report or feature request?**
* Bug Report

**Expected behavior:**
The OSDs should reclaim the space after data deleted.

**How to reproduce it (minimal and precise):**
Applying cluster configuration creates all mon/mgr/osd pods without an issue (as I am aware of) and the cluster look fine, but when I try to delete data from the pvc, the space is not reclaimed. 

I tried to avoid using bluestore due to this issue #1397 , but I am encountering the same issue.
```
apiVersion: ceph.rook.io/v1beta1
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  serviceAccount: rook-ceph-cluster
  mon:
    count: 3
  dashboard:
    enabled: true
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      storeType: filestore
      databaseSizeMB: "1024"
      journalSizeMB: "1024"  
    nodes:
    - name: "node1"
      directories:
      - path: "/mnt/rook"
    - name: "node2"
      directories:
      - path: "/mnt/rook"
```

```
apiVersion: ceph.rook.io/v1beta1
kind: Pool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  replicated:
    size: 2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
provisioner: ceph.rook.io/block
parameters:
  pool: replicapool
```

```
# ceph status
  cluster:
    id:     eb7a515e-8be8-496c-9e70-d63f0f78d230
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum rook-ceph-mon0,rook-ceph-mon1,rook-ceph-mon2
    mgr: a(active)
    osd: 2 osds: 2 up, 2 in

  data:
    pools:   1 pools, 100 pgs
    objects: 1369 objects, 5189 MB
    usage:   13824 MB used, 6206 MB / 20030 MB avail
    pgs:     100 active+clean

  io:
    client:   477 kB/s wr, 0 op/s rd, 70 op/s wr
```

This is the actual data size that resides in the PVC:
```
# du -sh *
53.3M	data
4.0K	log
16.0K	lost+found
```

**Environment**:
* OS: Ubuntu 18.04
* Kernel: Linux node1 4.15.0-24-generic #26-Ubuntu SMP Wed Jun UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Digital Ocean
* Rook version: v0.8.0
* Kubernetes version: v1.11.1
* Kubernetes cluster type : kubeadm
* Storage backend status ): HEALTH_OK

**Comment by travisn** [comment]
Rook is not on the data path for the data maintenance and garbage collection, so we would need to follow up with [upstream ceph](http://docs.ceph.com/docs/mimic/start/get-involved/) on this issue. Others have reported the cleanup working on filestore in Rook, not clear why you're not seeing it.

**Comment by ivanovaleksandar** [comment]
On the other hand, how to figure out that for sure filestore was deployed/setup on that osd (just for sanity check)? 

As I can see, according to the docs, that `storage.config.storeType: filestore` is forwarded downstream if no explicit modifications are made, but the `null` value is throwing me off. I am not sure at what am I looking at, so maybe the value defaulted to `bluestore`?!?!?
```
    storage:
      config:
        storeType: filestore
      nodes:
      - config: null
        directories:
        - config: null
          path: /mnt/rook
        name: node1
        resources: {}
```
