### ISSUE TITLE
Ths osd should not be created if the device name is wrong.

### ISSUE THREAD

**Issue by sdkfzv** [rook/rook#1972]
* Bug Report
What happened

If I create a ceph cluster with a wrong device name, the osd still can be created in the path "/var/lib/rook/osd.*"
This path is in the "/", so it will consume the system space.
My understanding is the osd should not be created if the device is not exist.
Is that correct ?

cluster.yaml
```
nodes:
    - name: "172.16.0.12"
      devices:
      - name: "sdcsds"    <---------- this is wrong
    - name: "172.16.0.13"
      devices:
      - name: "sdc"
    - name: "172.16.0.14"
      devices:
      - name: "sdc"
```
the osd:
```
[root@ceph-02 ceph]# ll /var/lib/rook/osd2/
total 420
lrwxrwxrwx 1 root root           34 8月   1 16:34 block -> /var/lib/rook/osd2/bluestore-block
lrwxrwxrwx 1 root root           31 8月   1 16:34 block.db -> /var/lib/rook/osd2/bluestore-db
lrwxrwxrwx 1 root root           32 8月   1 16:34 block.wal -> /var/lib/rook/osd2/bluestore-wal
```

**Environment**:
* OS (e.g. from /etc/os-release): centos 7.4.1708
* Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v0.8.0-4.gfb2c208
* Kubernetes version (use `kubectl version`): v1.9.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
