### ISSUE TITLE
Error on recreating Erasure Coded Pool with different Settings

### ISSUE THREAD

**Issue by discostur** [rook/rook#2016]
* Bug Report
When you create an erasure coded pool, delete it, adjust your settings and recreate it rook fails, because rook didn't delete the erasure code profile:

```
2018-08-10 13:13:01.708698 I | exec: Error EPERM: will not override erasure code profile erasurepool_ecprofile because the existing profile {crush-device-class=,crush-failure-domain=host,crush-root=default,jerasure-per-chunk-alignment=false,k=4,m=2,plugin=jerasure,technique=reed_sol_van,w=8} is different from the proposed profile {crush-device-class=,crush-failure-domain=host,crush-root=default,jerasure-per-chunk-alignment=false,k=8,m=2,plugin=jerasure,technique=reed_sol_van,w=8}
2018-08-10 13:13:01.708826 E | op-pool: failed to create pool erasurepool. failed to create pool erasurepool. failed to create erasure code profile for pool 'erasurepool': failed to set ec-profile. exit status 1
```

**Deviation from expected behavior:**

Rook should delete the erasure code profile or use unique names.

**How to reproduce it (minimal and precise):**

- Create erasure coded pool:

```
apiVersion: ceph.rook.io/v1beta1
kind: Pool
metadata:
  name: erasurepool 
  namespace: rook-ceph
spec:
  failureDomain: osd
  crushRoot: default
  erasureCoded:
    dataChunks: 4
    codingChunks: 2
``` 

- Delete erasure coded pool
- Adjust settings and recreate erasure coded pool:

```
apiVersion: ceph.rook.io/v1beta1
kind: Pool
metadata:
  name: erasurepool 
  namespace: rook-ceph
spec:
  failureDomain: osd
  crushRoot: default
  erasureCoded:
    dataChunks: 8
    codingChunks: 4
```

**Environment**:
* OS (e.g. from /etc/os-release): CentOS-7
* Kernel (e.g. `uname -a`): Linux deploy 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod):  v0.8.0-67.gd331a3e
* Kubernetes version (use `kubectl version`): 1.11.2
