### ISSUE TITLE
Failed to create ceph cluster using rook operator which is deployed by helm.

### ISSUE THREAD

**Issue by MartinForReal** [rook/rook#2020]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
the service account which is associated with operator pod don't have access to creating configmap in target namespace

**Expected behavior:**
create a ceph cluster after cluster resource is created 

```
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  storage:
    useAllNodes: true
    useAllDevices: true
    deviceFilter: vd[b-c]
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
```
**How to reproduce it (minimal and precise):**

```shell
helm install ceph-rook-cluster-0.1.0.tgz --set rbacEnable=true
cat >abc.yml <<EOF
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  storage:
    useAllNodes: true
    useAllDevices: true
    deviceFilter: vd[b-c]
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
EOF
kubectl apply -f abc.yml
```

**Environment**:
* OS (e.g. from /etc/os-release): centos
* Kernel (e.g. `uname -a`): Linux testhost1 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: none
* Rook version (use `rook version` inside of a Rook Pod): v0.8.1
* Kubernetes version (use `kubectl version`): 1.9.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): baremetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): not available
