### ISSUE TITLE
ceph: expose hostname of hosts (not container names) for benefit of dashboard, crush hierarchy, etc.

### ISSUE THREAD

**Issue by liewegas** [rook/rook#2078]
If you look at the host/daemons view on the dashboard, every daemon is on its own "host" (with the hostname matching the pod name).  This isn't the reality of the cluster; the user (as least this user!) expects to see what physical hosts the daemons are on.

Similarly, this is what is used to populate the crush hierarchy, which *does* need to map to the physical hardware in order to be useful.

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by liewegas** [comment]
This might be a pure ceph issue: perhasp teh collect_metadata method the daemons use should be extracting the (physical) host name from the environment and passing the container/pod name via a different metadata field?

**Comment by liewegas** [comment]
Can we pass these values into the pod environment?
```
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```
The ceph daemons can then pick that up to fully understand their environment and include that in the daemon metadata...
