### ISSUE TITLE
Nodes defined in cluster are not getting init by operator

### ISSUE THREAD

**Issue by dimm0** [rook/rook#2112]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I have 14 nodes defined in rook cluster:
```
(⎈ |nautilus:rook)Dmitrys-MacBook-Pro-2:jupyterhub dimm$ kubectl get cluster rook -o yaml | grep "^      name:"
      name: k8s-gpu-03.sdsc.optiputer.net
      name: fiona.nwsc.ucar.edu
      name: k8s-epyc-01.sdsc.optiputer.net
      name: k8s-nvme-01.sdsc.optiputer.net
      name: fiona.tools.ucla.net
      name: fiona-dtn-1.ucsc.edu
      name: fiona-dtn.usc.edu
      name: k8s-nvme-01.ultralight.org
      name: netw-fiona.stanford.edu
      name: fiona.its.hawaii.edu
      name: dtn-main.ucr.edu
      name: ps-100g.sdsu.edu
      name: siderea.ucsc.edu
      name: knuron.calit2.optiputer.net
```
Note knuron.calit2.optiputer.net and k8s-gpu-03.sdsc.optiputer.net in the list.
Now listing the crush map:
```
[root@osg /]# ceph osd tree | grep host
-53       150.79706     host dtn-main-ucr-edu
-25         2.77475     host fiona-dtn-1-ucsc-edu
-37         2.77475     host fiona-dtn-usc-edu
-49         2.77475     host fiona-its-hawaii-edu
 -7         2.77475     host fiona-nwsc-ucar-edu
-21       174.30396     host fiona-tools-ucla-net
-10        75.06427     host k8s-epyc-01-sdsc-optiputer-net
-17       131.46848     host k8s-nvme-01-sdsc-optiputer-net
-41         6.92201     host k8s-nvme-01-ultralight-org
-45       169.26126     host netw-fiona-stanford-edu
-29         5.66150     host ps-100g-sdsu-edu
-33         5.66150     host siderea-ucsc-edu
```
These 2 hosts are not defined.

No configmap for those 2 hosts in rook, some devices configmaps for these in rook-system. Nothing about those 2 hosts in rook-operator.

**Expected behavior:**
On operator start it checks that all nodes in cluster CRD are created and have OSDs initialized

**How to reproduce it (minimal and precise):**
Can't reproduce. The operator purposely deleted these 2 nodes when it was broken after the upgrade.

**Environment**:
* Cloud provider or hardware configuration:
baremetal
* Rook version (use `rook version` inside of a Rook Pod):
0.8.1
* Kubernetes version (use `kubectl version`):
1.11.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
healthy

**Comment by travisn** [comment]
@dimm0 any chance you still have the operator log from the upgrade? Definitely would like to understand why the operator thought it should remove two nodes. Can you also share your cluster CRD to see what the settings are for configuring the osds?

**Comment by rootfs** [comment]
I was under the impression those 3 nodes were the same ones that operator failed to watch (fixed in #2111)

**Comment by dimm0** [comment]
@travisn Nope.. No logs
[cluster.zip](https://github.com/rook/rook/files/2381918/cluster.zip)
@rootfs those are different nodes

**Comment by dimm0** [comment]
I guess I'll go ahead and try to delete-add one of the nodes... Wish me luck :-D

**Comment by travisn** [comment]
@dimm0 the operator does not currently watch the nodes to see when they are added. Can you restart the operator? Then I would expect the operator to configure the new nodes. There is an issue tracking this somewhere...

**Comment by dimm0** [comment]
I did restart multiple times, no effect

**Comment by jjgraham** [comment]
Hi All. Classes are starting again here on campus and we have several hundred users looking forward to a stable rook release and working shared filesystems.

What resources do you need to improve your release testing on large distributed clusters ?

**Comment by dimm0** [comment]
Any way for us to add some storage?

**Comment by dimm0** [comment]
Node is schedulable

```
knuron.calit2.optiputer.net            Ready                      <none>    114d      v1.11.3
```

Not in cluster

```
(⎈ |nautilus:tpu)Dmitrys-MBP-2:~ dimm$ kubectl get cluster -n rook -o yaml rook | grep knuron
(⎈ |nautilus:tpu)Dmitrys-MBP-2:~ dimm$
```
Adding node definition

```
(⎈ |nautilus:tpu)Dmitrys-MBP-2:~ dimm$ kubectl edit cluster rook -n rook
cluster.ceph.rook.io/rook edited
(⎈ |nautilus:tpu)Dmitrys-MBP-2:~ dimm$ kubectl get cluster -n rook rook -o yaml | grep knuron
      name: knuron.calit2.optiputer.net
```

Remains in CRD:

```
    nodes:
    - config: null
      devices:
      - FullPath: ""
        config: null
        name: sdb
      - FullPath: ""
        config: null
        name: sdc
      - FullPath: ""
        config: null
        name: sdd
      - FullPath: ""
        config: null
        name: sde
      - FullPath: ""
        config: null
        name: sdf
      - FullPath: ""
        config: null
        name: sdg
      - FullPath: ""
        config: null
        name: sdh
      - FullPath: ""
        config: null
        name: sdi
      - FullPath: ""
        config: null
        name: nvme0n1
      - FullPath: ""
        config: null
        name: nvme1n1
      - FullPath: ""
        config: null
        name: nvme2n1
      - FullPath: ""
        config: null
        name: nvme3n1
      name: knuron.calit2.optiputer.net
      resources: {}
```

Restarting operator

```
(⎈ |nautilus:tpu)Dmitrys-MBP-2:~ dimm$ kubectl delete pod -n rook-system rook-ceph-operator-6f7768985b-szmq8
pod "rook-ceph-operator-6f7768985b-szmq8" deleted
```

Prepare is not done

```
(⎈ |nautilus:tpu)Dmitrys-MBP-2:~ dimm$ kubectl get pods -n rook | grep prepare
rook-ceph-osd-prepare-dtn-main.ucr.edu-x5n86                 0/1       Completed   0          1m
rook-ceph-osd-prepare-fiona-dtn-1.ucsc.edu-7lvlk             0/1       Completed   0          1m
rook-ceph-osd-prepare-fiona-dtn.usc.edu-krxxv                0/1       Completed   0          57s
rook-ceph-osd-prepare-fiona.its.hawaii.edu-z7mf9             0/1       Completed   0          53s
rook-ceph-osd-prepare-fiona.nwsc.ucar.edu-wrv4h              0/1       Completed   0          51s
rook-ceph-osd-prepare-fiona.tools.ucla.net-rwhv4             0/1       Completed   0          49s
rook-ceph-osd-prepare-k8s-epyc-01.sdsc.optiputer.net-tntzd   0/1       Completed   0          43s
rook-ceph-osd-prepare-k8s-nvme-01.sdsc.optiputer.net-xzznb   0/1       Completed   0          39s
rook-ceph-osd-prepare-netw-fiona.stanford.edu-5zld5          0/1       Completed   0          37s
rook-ceph-osd-prepare-ps-100g.sdsu.edu-8n8hv                 0/1       Completed   0          34s
rook-ceph-osd-prepare-siderea.ucsc.edu-p2mlx                 0/1       Completed   0          32s
```

Operator logs, zero mentions of knuron:
[op.logs.zip](https://github.com/rook/rook/files/2436811/op.logs.zip)
