### ISSUE TITLE
Rook ignores placement options with existing cluster

### ISSUE THREAD

**Issue by steebchen** [rook/rook#2231]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rook ignores/resets the `placement.all.nodeAffinity` in the kubernetes cluster resource after editing it and restarting the rook operator:
```
  placement:
    all:
      nodeAffinity: {}
```

**Expected behavior:**
Setting:
```
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingRequiredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: type
              operator: In
              values:
              - storage
```
and restarting the rook operator, seeing the same settings in the cluster resource.

**How to reproduce it (minimal and precise):**
Edit the placement settings after initializing a cluster and restart the operator.

**Environment**:
* OS: Ubuntu 16.04
* Kernel: Linux master 4.4.0-130-generic
* Cloud provider or hardware configuration: Hetzner
* Rook version: rook: v0.8.1
* Kubernetes version: `Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster type: kubeadm
* Storage backend status: `HEALTH_WARN noscrub,nodeep-scrub flag(s) set; Degraded data redundancy: 22/70 objects degraded (31.429%), 18 pgs degraded, 100 pgs undersized`
