### ISSUE TITLE
Documentation update request for Flexvolume and rancher support

### ISSUE THREAD

**Issue by gerritjvv** [rook/rook#2302]
I'm not sure where to make documentation update requests, but if I had this in the docs it would've saved me hours or struggling
 
when using rancher's RKE the kubetlet runs as a docker instance
which mean the host's volume-plugin-dir needs to be mounted as a docker volume.

This can be done via the cluster.yml as

```
kubelet:
    image: ""
    extra_args:
      volume-plugin-dir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
    extra_binds:
    - /usr/libexec/kubernetes/kubelet-plugins/volume/exec:/usr/libexec/kubernetes/kubelet-plugins/volume/exec
```

and the rook operator.yml
```
env:
- name: FLEXVOLUME_DIR_PATH
   value: "/usr/libexec/kubernetes/kubelet-plugins/volume/exec"
```
