### ISSUE TITLE
Taints prevent OSDs from running when sufficient tolerations in place.

### ISSUE THREAD

**Issue by rcgoodfellow** [rook/rook#2384]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Tolerations declared in cluster.yml do not allow OSD pods to run on tainted nodes.

**Expected behavior:**
Declaring a toleration in cluster.yml allows OSDs to be scheduled on nodes that have matching taints.

**How to reproduce it (minimal and precise):**
Use the following taint declaration in cluster.yml
```yaml
placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - storage-node
      podAffinity:
      podAntiAffinity:
      tolerations:
      - key: storage-node
        operator: Exists
```

Taint nodes as follows where `$x` is the node name.

```shell
kubectl taint nodes $x storage-node=$x:NoSchedule
```

**Environment**:
* OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

* Kernel (e.g. `uname -a`):
```
Linux ks0 4.16.0-2-amd64 #1 SMP Debian 4.16.12-1 (2018-05-27) x86_64 GNU/Linux
```

* Cloud provider or hardware configuration:

Running in virtual environment inside libvirt/qemu/kvm. Custom deployed k8s.

* Rook version (use `rook version` inside of a Rook Pod):

Currently we're just pulling the master containers.

```
rook: v0.9.0-4.g8a49531
```

* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

Custom home grown packaging, self hosted.

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

```
HEALTH_WARN Degraded data redundancy: 120/180 objects degraded (66.667%), 30 pgs degraded, 100 pgs undersized 
```

**Comment by galexrt** [comment]
@rcgoodfellow I was unable to reproduce locally. Can you post the `kubectl describe` output for an OSD Pod and if you have OSD prepare Pods post the `kubectl describe` of them too.

**Comment by tux-00** [comment]
Same here. Cluster definition : 
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v13.2.4-20190109
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  mon:
    count: 3
    allowMultiplePerNode: false
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - storage-node
      podAffinity:
      podAntiAffinity:
      tolerations:
      - key: storage-node
        operator: Exists
  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: "^vd[b-z]"
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
      osdsPerDevice: "1"
```
Labels/taints : 
```
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=scw-master1
                    node-role.kubernetes.io/master=
                    role=storage-node
Taints:             node-role.kubernetes.io/master:NoSchedule
```

I tried with this but pods don't schedule on master : 
```
placement:
    all:
      tolerations:
      - key: NoSchedule
        operator: Exists
```

**Comment by tux-00** [comment]
My bad, I'm able to schedule on master with this definition of tolerations : 
```
  placement:
    all:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
```
