### ISSUE TITLE
Rook Ceph Operator does not honor metadataDevice

### ISSUE THREAD

**Issue by stephan2012** [rook/rook#2425]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Although specified, Ceph Operator does not honor `metadataDevice`.

**Expected behavior:**
osd should be configured to use the specified `metadataDevice`.

**How to reproduce it (minimal and precise):**

1. Setup according to the docs
2. Take the example `cluster/examples/kubernetes/ceph/cluster.yaml` and configure `spec.storage` like this:

```yaml
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    metadataDevice: "zd16"
    location:
    config:
      storeType: bluestore
      osdsPerDevice: "1" # this value can be overridden at the node or device level
    nodes:
    - name: "node1"
      devices:
      - name: "zd0"
    - name: "node2"
      devices:
      - name: "zd0"
    - name: "node3"
      devices:
      - name: "zd0"
```

3. Creates the log device on the data device:

```
# ll /var/lib/rook/osd0/block*
lrwxrwxrwx 1 root root 58 Dec 23 18:24 /var/lib/rook/osd0/block -> /dev/disk/by-partuuid/67d53a6a-cb45-4bd6-a522-64a87972d0de
lrwxrwxrwx 1 root root 58 Dec 23 18:24 /var/lib/rook/osd0/block.db -> /dev/disk/by-partuuid/da7052f3-8978-40e8-899c-8814b3d322a8
lrwxrwxrwx 1 root root 58 Dec 23 18:24 /var/lib/rook/osd0/block.wal -> /dev/disk/by-partuuid/6f8936d0-2ffe-43e8-9357-672efc286400

# ll /dev/disk/by-partuuid/{67d53a6a-cb45-4bd6-a522-64a87972d0de,da7052f3-8978-40e8-899c-8814b3d322a8,6f8936d0-2ffe-43e8-9357-672efc286400}
lrwxrwxrwx 1 root root 11 Dec 23 18:24 /dev/disk/by-partuuid/67d53a6a-cb45-4bd6-a522-64a87972d0de -> ../../zd0p3
lrwxrwxrwx 1 root root 11 Dec 23 18:24 /dev/disk/by-partuuid/6f8936d0-2ffe-43e8-9357-672efc286400 -> ../../zd0p1
lrwxrwxrwx 1 root root 11 Dec 23 18:24 /dev/disk/by-partuuid/da7052f3-8978-40e8-899c-8814b3d322a8 -> ../../zd0p2

# ll /dev/zvol/rpool/ceph /dev/zvol/bulkpool/ceph
/dev/zvol/bulkpool/ceph:
total 0
lrwxrwxrwx 1 root root 12 Dec 23 18:24 osd1 -> ../../../zd0
lrwxrwxrwx 1 root root 14 Dec 23 18:24 osd1-part1 -> ../../../zd0p1
lrwxrwxrwx 1 root root 14 Dec 23 18:24 osd1-part2 -> ../../../zd0p2
lrwxrwxrwx 1 root root 14 Dec 23 18:24 osd1-part3 -> ../../../zd0p3

/dev/zvol/rpool/ceph:
total 0
lrwxrwxrwx 1 root root 13 Dec 23 18:20 osdmeta1 -> ../../../zd16
```

The block devices are on ZFS and have been created with

```
zfs create -b 4k -V 8t bulkpool/ceph/osd1
zfs create -b 4k -V 20g rpool/ceph/osdmeta1
```

**Environment**:
* OS (e.g. from /etc/os-release): Debian GNU/Linux 9.6
* Kernel (e.g. `uname -a`): `Linux node1 4.18.0-0.bpo.3-amd64 #1 SMP Debian 4.18.20-2~bpo9+1 (2018-12-08) x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Bare metal plus ZFS in two zpools
* Rook version (use `rook version` inside of a Rook Pod): 0.9.0
* Kubernetes version (use `kubectl version`): 1.13.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): N/A
