### ISSUE TITLE
Create Persistent Volumes from Existing RBD images

### ISSUE THREAD

**Issue by will7200** [rook/rook#2427]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Imported a RBD images using the direct tooling and created a persistent volume pointing to the rbd image. 
1. Create a PVC and Refer to a pv by using the volumeName
This made the scheduled pod for creation to wait for the existing storage to be mounted. Never got past the mounting stage. 
2. Create a PVC and Refer to the pv by using the claimRef specifying the namespace and name of the pv.
This made a new pv claim in the ceph storage and was able to to successfully start the pod, but using a new rbd image.
3. Create a PV to existing rbd image and then delete said PV. 
Kubernetes was able to successfully delete the pv, but there were no incidations of any commands run in the operator logs nor was the image delete from the ceph storage pool.
**Expected behavior:**
In both instances for 1 and 2, the pvc should use the referenced pv and mount successfully.
For 3, rook should've deleted the underlying rbd image.
**How to reproduce it (minimal and precise):**

1. Import a rbd image
2. Create a pv using the following template:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: ceph.rook.io/block
  finalizers:
  - kubernetes.io/pv-protection
  name: {rbd name}
  selfLink: /api/v1/persistentvolumes/{rbd name}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: {claim name}
    namespace: default
  flexVolume:
    driver: ceph.rook.io/rook-ceph-system
    fsType: xfs
    options:
      clusterNamespace: rook-ceph
      dataPool: ""
      image: {rbd name}
      pool: replicapool
      storageClass: rook-ceph-block
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
provisioner: ceph.rook.io/block
parameters:
  blockPool: replicapool
  # The value of "clusterNamespace" MUST be the same as the one in which your rook cluster exist
  clusterNamespace: rook-ceph
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  fstype: xfs
# Optional, default reclaimPolicy is "Delete". Other options are: "Retain", "Recycle" as documented in https://kubernetes.io/docs/concepts/storage/storage-classes/
reclaimPolicy: Retain
```
3. Try to reference the PV from a PVC or delete PV and query rbd pool.
**Environment**:
* OS (e.g. from /etc/os-release):
NAME=Fedora
VERSION="28 (Cloud Edition)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Cloud Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Cloud Edition"
VARIANT_ID=cloud
* Kernel (e.g. `uname -a`):
Linux fedoraKub1 4.19.5-200.fc28.x86_64 #1 SMP Tue Nov 27 20:19:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
Baremetal
* Rook version (use `rook version` inside of a Rook Pod):
rook: v0.9.0-4.g8a49531
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Rancher rke version v0.1.12
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
HEALTH_OK
