### ISSUE TITLE
Allow to disable dashboard SSL 

### ISSUE THREAD

**Issue by christianhuening** [rook/rook#2433]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Allow to configure `ssl: false` in dashboard config section of `CephCluster` resource. Just like `ceph config set mgr mgr/dashboard/ssl false` as described here http://docs.ceph.com/docs/mimic/mgr/dashboard/#ssl-tls-support
**What is use case behind this feature:**
I am running Nginx Ingress with Cert Manager and want the dashboard to be exposed via that cert instead of it's own self-signed

**Comment by whereisaaron** [comment]
Thanks @christianhuening I had the same problem. The `rook-ceph` dashboard is now HTTPS which is fine. But currently it appears it deploys only with a self-signed certificate. Which ironically makes it harder to expose the dashboard with a valid certificate.

There are a couple ways to fix this:
1. An `ssl: false` setting as @christianhuening suggests to run that dashboard over HTTP on port 7000 like the old version, so that we can use a reverse proxy to terminate the SSL.
2. Add a setting to specify the name of a k8s TLS Secret, to mount on the mgr Pod with the user generated certificate. That the user can supply a valid certificate from `cert-manager`. Then the mgr bootstrap would just not generate a key if the cert/key files already exist (from being mount at Pod launch).

**Comment by whereisaaron** [comment]
@christianhuening in the meantime, if you are using `nginx-ingress` in your clusters then this Ingress a with `server-snippet` annotation will work around the problem of the self-signed certificate. It just tells ngnix not to try to verify the certificate, since we know it will fail.

Being able to get the dashboard to mount a valid certificate via a Secret would be ideal, but in the meantime we can at least reverse proxy it with a valid certificate.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
spec:
  tls:
   - hosts:
     - rook-ceph.example.com
     secretName: rook-ceph.example.com
  rules:
  - host: rook-ceph.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rook-ceph-mgr-dashboard
          servicePort: https-dashboard
```

**Comment by christianhuening** [comment]
thanks @whereisaaron very helpful!

**Comment by slassh** [comment]
I get "400 Bad Request
The plain HTTP request was sent to HTTPS port" when I try to access the dashboard via an ingress , but it works fine the node port svc !

**Comment by whereisaaron** [comment]
@slassh vanilla k8s Ingress's expect the upstream service to be HTTP. You need an Ingress with support for HTTPS upstream, and a way to disable certificate validation. If you are using a current `nginx-ingress` these annotations will do that:
```
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
```
Other Ingress Controller may be have similar options.

**Comment by omidraha** [comment]
I got 404 error.

This is my `ingress.yaml` file:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
spec:
  tls:
   - hosts:
     - rook-ceph.example.com
     secretName: rook-ceph.example.com
  rules:
  - host: rook-ceph.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rook-ceph-mgr-dashboard
          servicePort: 8443

```

When I browse to https://rook-ceph.example.com/

And click on the browser warning button:

```Proceed to rook-ceph.example.com (unsafe)```

I get this error on browser:

```default backend - 404```


**Info:**
```bash
$ kubectl -n rook-ceph get pod
NAME                                     READY   STATUS      RESTARTS   AGE
rook-ceph-mgr-a-ffc44857d-xgh4d          1/1     Running     0          50m
rook-ceph-mon-a-86f5fc4bc-clmfb          1/1     Running     0          51m
rook-ceph-mon-b-7955f84c5c-sqhvj         1/1     Running     0          51m
rook-ceph-mon-c-684556d465-sfmvv         1/1     Running     0          51m
rook-ceph-osd-0-65968b6d86-wkdxt         1/1     Running     0          50m
rook-ceph-osd-prepare-ubuntu-191-h6g2x   0/2     Completed   0          50m

$ kubectl -n rook-ceph get service
NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
rook-ceph-mgr             ClusterIP   10.43.148.58    <none>        9283/TCP   50m
rook-ceph-mgr-dashboard   ClusterIP   10.43.89.64     <none>        8443/TCP   50m
rook-ceph-mon-a           ClusterIP   10.43.117.36    <none>        6789/TCP   51m
rook-ceph-mon-b           ClusterIP   10.43.164.245   <none>        6789/TCP   51m
rook-ceph-mon-c           ClusterIP   10.43.205.134   <none>        6789/TCP   51m

$ kubectl -n rook-ceph-system get pod
NAME                                  READY   STATUS    RESTARTS   AGE
rook-ceph-agent-w6lsz                 1/1     Running   0          1h
rook-ceph-operator-5496d44d7c-wnm7h   1/1     Running   0          1h
rook-discover-b4v7g    

$ kubectl -n rook-ceph get ingress
NAME                      HOSTS                   ADDRESS         PORTS     AGE
rook-ceph-mgr-dashboard   rook-ceph.example.com   192.168.0.191   80, 443   13m

```

**Comment by omidraha** [comment]
When I change dashboard settings in ``cluster.yaml`` and set `ssl: false`, to disable ssl for dashboard :
```
  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    port: 8443
    # serve the dashboard using SSL
    ssl: false
```
Now there is no `rook-ceph-mgr-dashboard` on the services:

$ kubectl -n rook-ceph get service
```
NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
rook-ceph-mgr     ClusterIP   10.43.60.120    <none>        9283/TCP   6m
rook-ceph-mon-a   ClusterIP   10.43.121.243   <none>        6789/TCP   6m
rook-ceph-mon-b   ClusterIP   10.43.24.138    <none>        6789/TCP   6m
rook-ceph-mon-c   ClusterIP   10.43.210.58    <none>        6789/TCP   6m
```
Any idea?
