### ISSUE TITLE
RGW instances are all created with the same name

### ISSUE THREAD

**Issue by travisn** [rook/rook#2474]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When rook creates the object store and starts the rgw instances, a deployment is created and the number of desired instances are set on the spec according to the `gateway.instances` setting in the object crd. All instances are started with the same arg, including the same name:
```
radosgw --name=client.radosgw.gateway ...
```

Since all rgw instances have the same name, `ceph status` always shows that there is only a single rgw instance:
```
[root@minikube /]# ceph -s
... 
  services:
    rgw: 1 daemon active
...
```

@yehudasa is it expected that each instance of rgw is started with its own keyring and name? Are there any known side effects of using the same name other than the incorrect status?

**Expected behavior:**
The number of rgw daemons should be accurate in the ceph status.

**How to reproduce it (minimal and precise):**

```
kubectl create -f operator.yaml
kubectl create -f cluster.yaml
# Modify the `gateway.instances` in object.yaml to 2
kubectl create -f object.yaml
```

**Comment by ramkiperiy** [comment]
Some more observations when creating 2 rgw pods. Please note in the replicaset(i.e. replicaset.apps/rook-ceph-rgw-my-store-68b65d5854) for one of rgw, the value for desired and current state is "0" as highlighted below.

Rook image: travisn/ceph:openshift-test

```
[ec2-user@ip-172-31-11-48 ceph]$ oc get all 
NAME                                                               READY     STATUS      RESTARTS   AGE
pod/rook-ceph-mgr-a-754dbd6565-4c87r                               1/1       Running     3          3d
pod/rook-ceph-mon-a-7cbb575d48-9x6pf                               1/1       Running     3          2d
pod/rook-ceph-mon-b-74594f9b55-pcmtn                               1/1       Running     3          3d
pod/rook-ceph-mon-c-5bffcb6c64-ht42b                               1/1       Running     3          3d
pod/rook-ceph-osd-0-579b56bb47-jrg8b                               1/1       Running     3          2d
pod/rook-ceph-osd-1-84977d7445-tl5gf                               1/1       Running     3          3d
pod/rook-ceph-osd-2-7596794f45-9xgsx                               1/1       Running     3          3d
pod/rook-ceph-rgw-my-store-5f5f995fcc-45d8x                        1/1       Running     0          1h
pod/rook-ceph-rgw-my-store-5f5f995fcc-758rn                        1/1       Running     0          1h
pod/rook-ceph-tools-78db69f57c-nkdwx                               1/1       Running     1          3d

NAME                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/rook-ceph-mgr             ClusterIP   172.30.247.108   <none>        9283/TCP   3d
service/rook-ceph-mgr-dashboard   ClusterIP   172.30.0.80      <none>        8445/TCP   3d
service/rook-ceph-mon-d           ClusterIP   None             <none>        6789/TCP   7h
service/rook-ceph-rgw-my-store    ClusterIP   None             <none>        8080/TCP   1h

NAME                                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rook-ceph-mgr-a          1         1         1            1           3d
deployment.apps/rook-ceph-mon-a          1         1         1            1           3d
deployment.apps/rook-ceph-mon-b          1         1         1            1           3d
deployment.apps/rook-ceph-mon-c          1         1         1            1           3d
deployment.apps/rook-ceph-osd-0          1         1         1            1           3d
deployment.apps/rook-ceph-osd-1          1         1         1            1           3d
deployment.apps/rook-ceph-osd-2          1         1         1            1           3d
deployment.apps/rook-ceph-rgw-my-store   2         2         2            2           1h
deployment.apps/rook-ceph-tools          1         1         1            1           3d

NAME                                                DESIRED   CURRENT   READY     AGE
replicaset.apps/rook-ceph-mgr-a-754dbd6565          1         1         1         3d
replicaset.apps/rook-ceph-mon-a-7cbb575d48          1         1         1         3d
replicaset.apps/rook-ceph-mon-b-74594f9b55          1         1         1         3d
replicaset.apps/rook-ceph-mon-c-5bffcb6c64          1         1         1         3d
replicaset.apps/rook-ceph-osd-0-579b56bb47          1         1         1         3d
replicaset.apps/rook-ceph-osd-1-84977d7445          1         1         1         3d
replicaset.apps/rook-ceph-osd-2-7596794f45          1         1         1         3d
**replicaset.apps/rook-ceph-rgw-my-store-5f5f995fcc   2         2         2         1h**
**replicaset.apps/rook-ceph-rgw-my-store-68b65d5854   0         0         0         1h**
replicaset.apps/rook-ceph-tools-78db69f57c          1         1         1         3d
```
yaml file used to create 2 rgw services.

```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-store
  namespace: rook-ceph
spec:
  # The pool spec used to create the metadata pools
  metadataPool:
    failureDomain: host
    replicated:
      # Increase the replication size if you have more than one osd
      size: 2
  # The pool spec used to create the data pool
  dataPool:
    failureDomain: host
    replicated:
      size: 2
    # If you have at least three osds, erasure coding can be specified
    # erasureCoded:
    #   dataChunks: 2
    #   codingChunks: 1
  # The gaeteway service configuration
  gateway:
    # type of the gateway (s3)
    type: s3
    # A reference to the secret in the rook namespace where the ssl certificate is stored
    sslCertificateRef:
    # The port that RGW pods will listen on (http)
    port: 8080
    # The port that RGW pods will listen on (https). An ssl certificate is required.
    securePort:
    # The number of pods in the rgw deployment (ignored if allNodes=true)
    instances: 2
    # Whether the rgw pods should be deployed on all nodes as a daemonset
    allNodes: false
    # The affinity rules to apply to the rgw deployment or daemonset.
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role-rgw
              operator: In
              values:
              - rgw-node
    #  tolerations:
    #  - key: rgw-node
    #    operator: Exists
    #  podAffinity:
    #  podAntiAffinity:
    resources:
    # The requests and limits set here, allow the object store gateway Pod(s) to use half of one CPU core and 1 gigabyte of memory
    #  limits:
    #    cpu: "500m"
    #    memory: "1024Mi"
    #  requests:
    #    cpu: "500m"
    #    memory: "1024Mi"
```
