### ISSUE TITLE
500 internal error to access dashboard in v0.9.1

### ISSUE THREAD

**Issue by aisensiy** [rook/rook#2492]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The dashboard failed after create a 3 mon 3 osd cluster with the cluster configuration: 

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v13.2.2-20181023
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  # set the amount of mons to be started
  mon:
    count: 3
    allowMultiplePerNode: true
  # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: true
    hostNetwork: false
  rbdMirroring:
    workers: 0
  resources:
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    location:
    config:
      databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      osdsPerDevice: "1" # this value can be overridden at the node or device level
    nodes:
    - name: xxx.compute.internal
      devices:
      - name: "xvdg"
    - name: xxxx.compute.internal
      devices:
      - name: "xvdg"
    - name: xxxxx.compute.internal
      devices:
      - name: "xvdg"
```

**Expected behavior:**

**How to reproduce it (minimal and precise):**

Create a cluster with the docs. And

    kubectl port-forward svc/rook-ceph-mgr-dashboard 8443:8443 -n rook-ceph

Then open https://localhost:8443 got error, I got logs from mgr:

```
[15/Jan/2019:10:13:03] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib64/python2.7/ssl.py", line 934, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 609, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 831, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:579)
```

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 16.04
* Kernel (e.g. `uname -a`): Linux xxxx 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: aws
* Rook version (use `rook version` inside of a Rook Pod): v0.9.0
* Kubernetes version (use `kubectl version`): v1.13.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): HEALTH_WARN mon c is low on available space

**Comment by aisensiy** [comment]
By the way, is there some way to put the dashboard up again? I don't want to reinstall the cluster just because the dashboard failed...

Thanks in advance.

**Comment by laurybueno** [comment]
I can confirm this problem in a very similar setup. However, I've configured an ingress with a valid certificate so that the dashboard could be publicly available. (and my Ceph cluster is HEALTH_OK)

When I try to access it, the page loads indefinitely and the manager pod prints the same error message on its log.

**Comment by aisensiy** [comment]
I also try to use ingress, and failed...

**Comment by aisensiy** [comment]
I am using traefik ingress which seems that it do not support ssl passthrough. And then I upgrade ceph to v13.2.4 and set `ssl: false` for the dashboard but the error message shows below:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib64/python2.7/ssl.py", line 934, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 609, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 831, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:618)
```

**Comment by chh315** [comment]
I got this error too! installed by helm and using traefik ingress.

  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    port: 8080
    # serve the dashboard using SSL
    ssl: false

like port and ssl is not effected.

**Comment by travisn** [comment]
I believe this is the same root cause as #2404. The fix is in master and I'd like to have it in a v0.9.2 release by tomorrow.

**Comment by ruzickap** [comment]
Hello. 

I tried to install rook v0.9.2 to freshly installed k8s cluster:

```bash
$ helm repo add rook-stable https://charts.rook.io/stable
$ helm install --namespace rook-ceph-system rook-stable/rook-ceph

$ helm ls
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
wobbly-parrot   1               Sat Jan 26 10:46:18 2019        DEPLOYED        rook-ceph-v0.9.2                        rook-ceph-system

$ kubectl create -f https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/cluster.yaml
```

Then I tried the port redirection to `rook-ceph-mgr`:

```bash
$ kubectl -n rook-ceph port-forward $(kubectl -n rook-ceph get pod -l app=rook-ceph-mgr -o jsonpath='{.items[0].metadata.name}') 8443:8443
```

but I'm still getting errors when trying to access dashboard on `https://localhost:8443`:

```
E0126 11:14:37.732730    7221 portforward.go:331] an error occurred forwarding 8443 -> 8443: error forwarding port 8443 to pod 751f952e3c9fd53c574c322fb3bdf55a41c8e56212e15a9e5ae40ec5dfe746b1, uid : exit status 1: 2019/01/26 10:14:37 socat[19752] E connect(5, AF=2 127.0.0.1:8443, 16): Connection refused
```

Was this issue really fixed in v0.9.2 ? Is it working for anybody who is using v0.9.2 ?

**Comment by travisn** [comment]
@aisensiy @ruzickap Is the scenario that you're trying to turn off ssl termination inside ceph and have the ssl termination handled by the ingress controller? Or connecting to the controller in any way is not working for you? By disabling ssl in the cluster crd, i would expect you'd be able to accomplish that. 

@noahdesu If ssl is disabled, is the dashboard going to be listening on a different port such as 7000?

**Comment by ruzickap** [comment]
Actually it is not the case... 
I do not want to use ingress at all. I just want to start the dashboard and be able to connect there using "kubectl port forwarding" (like it is here: https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/)

If I use port 7000 I got the same issue/errors `... an error occurred forwarding 7000 -> 7000: error forwarding port 7000 to pod ...`

**Comment by noahdesu** [comment]
the ssl setting doesn't affect the port that is used, and if no port is explicitly requested, the port selection is based on ceph version (7000 for luminous, 8443 >= mimic).

**Comment by zedtux** [comment]
I'm facing this issue too with a fresh Kubernetes cluster (v 1.13) and followed the same procedure than @ruzickap in order to install rook, and I'm using the `Kubectl proxy` command in order to access the dashboard but it wait forever and I have the error in the pod's log.

Is there anyway to access that dashboard without SSL/TLS?

**Comment by travisn** [comment]
I suspect the ingress controller will work at least when the rook cluster is configured with `hostNetwork: true`. @galexrt any ideas on this one?

**Comment by MiticoBerna** [comment]
I've tried to configure ingress with traefik and, me too, I still get Internal Server Error.
With nodeport works.

As @travisn suggest, I've put `hostNetwork:true` but still doesn't work with ingress.

rook: `v0.9.2`
ceph: `v13.2 (latest)`
EKS 10.11.5

**Comment by noahdesu** [comment]
@MiticoBerna i can try to reproduce this today. can you share your yaml configs?

**Comment by ruzickap** [comment]
If you want to reproduce this issue please follow the steps mentioned here: https://github.com/rook/rook/issues/2492#issuecomment-457820437
(It's just few commands)

If you need something more - please let me know.

In my case I'm not using ingress, but only `kubectl port-forward`.

**Comment by noahdesu** [comment]
thanks @ruzickap

**Comment by MiticoBerna** [comment]
@ruzickap in this comment https://github.com/rook/rook/issues/2526#issuecomment-458289145 @galexrt says that port-forward could not working anymore due "to the fact that the dashboard is only listening on the Pod IP and not localhost".

With the ingress could be the same problem? I don't believe...

@noahdesu following my ingress.yml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: https-rook-ceph-dashboard
  annotations:
    kubernetes.io/ingress.class: traefik-internal
    ingress.kubernetes.io/protocol: https
spec:
  rules:
  - host: "rook-dashboard.fabulous.hostname"
    http:
      paths:
      - backend:
          serviceName: rook-ceph-mgr-dashboard
          servicePort: 8443
```
