### ISSUE TITLE
Unable to mount volumes for pod, Couldn't get secret

### ISSUE THREAD

**Issue by anarcat** [rook/rook#2521]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

A prometheus operator cannot create volumes provided by ceph deployed from Rook.

**Expected behavior:**

Everything should work fine! And it did, at some point, in one of the twenty times we've cycled through this process. It seems we did something wrong at some point in the cluster either when we tore down or re-setup ceph. I suspect it might have to do with the fact we switched from dirHostPath to devices for ceph storage.

**How to reproduce it (minimal and precise):**

Install Rook:

```
helm repo add rook-stable https://charts.rook.io/stable
helm install --namespace rook-ceph-system --name rook -f hexacab-rook-values.yaml rook-stable/rook-ceph
```

* Create a Ceph cluster, a block pool, and the associated storage class:

```
kubectl create -f hexacab-rook-ceph-cluster.yaml
```

* Install Prometheus:

```
helm install --name prometheus --namespace monitoring -f hexacab-prometheus-values.yaml stable/prometheus-operator
```

See below for the ceph cluster config file.

The prometheus deployment fails to create certain pods which require permanent storage from Ceph. Here's a list of pods from the monitoring namespace:

```
$ kubectl -n monitoring get pods
NAME                                                     READY     STATUS              RESTARTS   AGE
alertmanager-prometheus-prometheus-oper-alertmanager-0   0/2       ContainerCreating   0          3h
prometheus-grafana-55fdb85f7c-zl969                      0/3       ContainerCreating   0          3h
prometheus-kube-state-metrics-6b57d88bbb-jqdsb           1/1       Running             0          3h
prometheus-prometheus-node-exporter-d8v59                1/1       Running             0          3h
prometheus-prometheus-node-exporter-rqnt6                1/1       Running             0          3h
prometheus-prometheus-node-exporter-rt9sm                1/1       Running             0          3h
prometheus-prometheus-oper-operator-86986b9d88-9qgxb     1/1       Running             0          3h
prometheus-prometheus-prometheus-oper-prometheus-0       0/3       ContainerCreating   0          3h
```

Here's what the grafana pod says:

```
$ kubectl describe pod prometheus-grafana-55fdb85f7c-zl969
[...]

Events:
  Type     Reason       Age                From                Message
  ----     ------       ----               ----                -------
  Warning  FailedMount  12m (x87 over 3h)  kubelet, kubeadmin  Unable to mount volumes for pod "prometheus-grafana-55fdb85f7c-zl969_monitoring(90e80190-1b28-11e9-b6d3-aa00005d98b8)": timeout expired waiting for volumes to attach or mount for pod "monitoring"/"prometheus-grafana-55fdb85f7c-zl969". list of unmounted volumes=[storage]. list of unattached volumes=[config ldap storage sc-dashboard-volume sc-dashboard-provider sc-datasources-volume prometheus-grafana-token-zwg6l]
  Warning  FailedMount  2m (x109 over 3h)  kubelet, kubeadmin  MountVolume.SetUp failed for volume "pvc-9059ff08-1b28-11e9-b6d3-aa00005d98b8" : mount command failed, status: Failure, reason: Rook: Mount volume failed: failed to get persistent volume pvc-9059ff08-1b28-11e9-b6d3-aa00005d98b8: Unauthorized
```

Similar errors can be seen in the `describe` of the other two pods stuck in `ContainerCreating`. The kubelet logs have this to say for themselves:

```
master# journalctl -u kubelet | tail -2
Jan 18 17:26:11 kubeadmin kubelet[473]: E0118 17:26:11.371330     473 secret.go:198] Couldn't get secret rook-ceph-system/rook-ceph-system-token-s7l9z: secrets "rook-ceph-system-token-s7l9z" not found
Jan 18 17:26:11 kubeadmin kubelet[473]: E0118 17:26:11.371533     473 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/secret/6dc7f051-1a69-11e9-b6d3-aa00005d98b8-rook-ceph-system-token-s7l9z\" (\"6dc7f051-1a69-11e9-b6d3-aa00005d98b8\")" failed. No retries permitted until 2019-01-18 17:28:13.371457637 +0000 UTC m=+136911.165786083 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"rook-ceph-system-token-s7l9z\" (UniqueName: \"kubernetes.io/secret/6dc7f051-1a69-11e9-b6d3-aa00005d98b8-rook-ceph-system-token-s7l9z\") pod \"rook-discover-xjt2x\" (UID: \"6dc7f051-1a69-11e9-b6d3-aa00005d98b8\") : secrets \"rook-ceph-system-token-s7l9z\" not found"
```

This looks similar to https://github.com/rook/rook/issues/1904, but is peculiar in that we *do* have the serviceaccount properly created in the rook-ceph namespace, as seen below. It is also similar to https://github.com/ceph/ceph-helm/issues/55 except it's not the same role that is failing. I suspect the problem might be related to our teardown procedures, which we've had trouble with in the past. So far we're using this:

**Prometheus**

To remove the services completely:

```
helm delete --purge prometheus
kubectl delete crd prometheuses.monitoring.coreos.com
kubectl delete crd prometheusrules.monitoring.coreos.com
kubectl delete crd servicemonitors.monitoring.coreos.com
kubectl delete crd alertmanagers.monitoring.coreos.com
```

Manually delete all the remaining PV and PVC objects in the *monitoring* namespace.

**Rook**

Turning down Rook properly requires some attention: the ceph objects need to be removed before deleting the pods, or the resources won't be deleted correctly. For reference, see the [Rook Ceph Teardown](https://github.com/rook/rook/blob/master/Documentation/ceph-teardown.md) documentation.

```
kubectl delete -f hexacab-rook-ceph-cluster.yaml
helm delete --purge rook
```

It is then finally necessary to remove the contents of the */var/lib/rook* directory on all the nodes.

**Environment**:
* OS (e.g. from /etc/os-release): Debian 9 stretch
* Kernel (e.g. `uname -a`): Linux hostname 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
* Cloud provider or hardware configuration: KVM
* Rook version (use `rook version` inside of a Rook Pod):  rook: v0.9.1
* Kubernetes version (use `kubectl version`): v1.11.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubespray 2.7.0
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): `HEALTH_OK`, and all rook pods are healthy

(BTW: the above "Rook Ceph toolbox" link is a 404.) The link now seems to be https://rook.io/docs/rook/v0.9/ceph-toolbox.html

Here's the content of that `hexacab-rook-ceph-cluster.yaml` file:

```yaml
# Create a Ceph cluster, a replica pool and an associated storageclass.
# But first, some necessary namespace/role/rbac objects.
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-osd
  namespace: rook-ceph
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-osd
  namespace: rook-ceph
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: [ "get", "list", "watch", "create", "update", "delete" ]
---
# Aspects of ceph-mgr that require access to the system namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr-system
  namespace: rook-ceph
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
# Aspects of ceph-mgr that operate within the cluster's namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ceph.rook.io
  resources:
  - "*"
  verbs:
  - "*"
---
# Allow the operator to create resources in this cluster's namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-cluster-mgmt
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-cluster-mgmt
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph-system
---
# Allow the osd pods in this namespace to work with configmaps
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-osd
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-osd
subjects:
- kind: ServiceAccount
  name: rook-ceph-osd
  namespace: rook-ceph
---
# Allow the ceph mgr to access the cluster-specific resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-mgr
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-ceph
---
# Allow the ceph mgr to access the rook system resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr-system
  namespace: rook-ceph-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-mgr-system
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-ceph
---
# Allow the ceph mgr to access cluster-wide resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr-cluster
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-mgr-cluster
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-ceph
---
# The ceph cluster.
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # For the latest ceph images, see https://hub.docker.com/r/ceph/ceph/tags
    image: ceph/ceph:v13.2.2-20181023
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: "vdb"
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
provisioner: ceph.rook.io/block
parameters:
  blockPool: replicapool
  # The value of "clusterNamespace" MUST be the same as the one in which your rook cluster exist
  clusterNamespace: rook-ceph
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  #fstype: xfs
# Optional, default reclaimPolicy is "Delete". Other options are: "Retain", "Recycle" as documented in https://kubernetes.io/docs/concepts/storage/storage-classes/
#reclaimPolicy: Retain
```

The above may be a flawed attempt at fixing [RBAC](https://github.com/rook/rook/blob/master/Documentation/rbac.md), even though those instructions explicitely say the above shouldn't be necessary since we don't have PodSecurityPolicy enabled, as far as I can tell.

Sorry for the long bug report but I figured that about covers it all. It would be great to have this case documented in the [common issues](https://github.com/rook/rook/blob/master/Documentation/common-issues.md) reference, because it seems it's happening to others. It's not exactly clear to me how authentication works across the cluster, that part of the design could use a little more clarity.

Thanks for the hard work!
