### ISSUE TITLE
PVC cannot be mounted anymore after series of pod deletes

### ISSUE THREAD

**Issue by zerkms** [rook/rook#2535]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
To elaborate what I'm doing: I'm researching how reliable rook/ceph is to act as a PVC provisioner for the bare metal cluster. To do that I created a tiny php application that just increments a counter in the database (postgresql), and postgresql is backed up by a PVC.

The relevant yamls for postgresql pod look like:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dummy-stateful-php-pgsql-db-pv-claim
  labels:
    app: dummy-stateful-php-pgsql-db
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-stateful-php-pgsql-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dummy-stateful-php-pgsql-db
  template:
    metadata:
      labels:
        app: dummy-stateful-php-pgsql-db
    spec:
      containers:
      - name: db
        image: postgres:11
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: password
        volumeMounts:
        - name: persistent-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: persistent-data
        persistentVolumeClaim:
          claimName: dummy-stateful-php-pgsql-db-pv-claim
```
Then I have run a loop that deletes a pod as soon as it's created:

```
while true; do kubectl delete "pod/$(kubectl get pods |grep db | cut -d' ' -f1)"; done
```

This leads to ~1-10seconds of container runtime, after which it's deleted and re-scheduled. So far so good.

After some time it stuck in an interesting state:

Here are the current database pods:

```
dummy-stateful-php-pgsql-db-5b86f9dd5d-d54l5   0/1     Terminating   0          16m
dummy-stateful-php-pgsql-db-5b86f9dd5d-f74ln   1/1     Running       0          16m
```
So you see that one is terminating for 16 minutes, the other is running for the same time.

Describe for the pvc says:

```
Mounted By:    dummy-stateful-php-pgsql-db-5b86f9dd5d-d54l5
               dummy-stateful-php-pgsql-db-5b86f9dd5d-f74ln
```

Then, describe for `pod/dummy-stateful-php-pgsql-db-5b86f9dd5d-f74ln` says

```
Events:
  Type     Reason       Age   From                       Message
  ----     ------       ----  ----                       -------
  Normal   Scheduled    17m   default-scheduler          Successfully assigned default/dummy-stateful-php-pgsql-db-5b86f9dd5d-f74ln to ip-10-250-47-127
  Warning  FailedMount  17m   kubelet, ip-10-250-47-127  MountVolume.SetUp failed for volume "pvc-9e06dbb2-1de6-11e9-b2da-0afb69308c7a" : mount command failed, status: Failure, reason: Rook: Mount volume failed: failed to attach volume pvc-9e06dbb2-1de6-11e9-b2da-0afb69308c7a for pod default/dummy-stateful-php-pgsql-db-5b86f9dd5d-f74ln. Volume is already attached by pod default/dummy-stateful-php-pgsql-db-5b86f9dd5d-d54l5. Status Pending
  Normal   Pulled       17m   kubelet, ip-10-250-47-127  Container image "postgres:11" already present on machine
  Normal   Created      17m   kubelet, ip-10-250-47-127  Created container
  Normal   Started      17m   kubelet, ip-10-250-47-127  Started container
```

BUT !!!! describe for `pod/dummy-stateful-php-pgsql-db-5b86f9dd5d-d54l5` says:

```
Events:
  Type     Reason       Age                From                       Message
  ----     ------       ----               ----                       -------
  Normal   Scheduled    18m                default-scheduler          Successfully assigned default/dummy-stateful-php-pgsql-db-5b86f9dd5d-d54l5 to ip-10-250-47-127
  Warning  FailedMount  18m (x2 over 18m)  kubelet, ip-10-250-47-127  MountVolume.SetUp failed for volume "pvc-9e06dbb2-1de6-11e9-b2da-0afb69308c7a" : mount command failed, status: Failure, reason: Rook: Mount volume failed: failed to attach volume pvc-9e06dbb2-1de6-11e9-b2da-0afb69308c7a for pod default/dummy-stateful-php-pgsql-db-5b86f9dd5d-d54l5. Volume is already attached by pod default/dummy-stateful-php-pgsql-db-5b86f9dd5d-pbvm7. Status Pending
  Normal   Pulled       18m                kubelet, ip-10-250-47-127  Container image "postgres:11" already present on machine
  Normal   Created      18m                kubelet, ip-10-250-47-127  Created container
  Normal   Started      18m                kubelet, ip-10-250-47-127  Started container
```
And as you see it thinks that the volume is attached to a pod that does not even exist!

This is one of the worst observed.

The other, which is still pretty bad is when the volume mounts to 2 containers while one has not quit entirely and postgresql goes crazy, because it does not expect to share filesystem with another process and this leads to data corruption and partial data loss (up to the last successful run).

**Expected behavior:**
This should never happen, a `ReadWriteOnce` mount should only be mounted to a single pod.

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 18.04
* Kernel (e.g. `uname -a`): `4.15.0-1031-aws #33-Ubuntu SMP Fri Dec 7 09:32:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: irrelevant, but aws
* Rook version (use `rook version` inside of a Rook Pod): `v0.9.0-79.g1a1ffdd`
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
```
# ceph health
HEALTH_WARN clock skew detected on mon.a, mon.f, mon.e; mons a,d,f are low on available space
```
