### ISSUE TITLE
pvc deleted but PV still exists.

### ISSUE THREAD

**Issue by fanux** [rook/rook#2571]
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
when delete PVC, PV delete automatic

**How to reproduce it (minimal and precise):**
```
kubectl delete -f mysql.yaml
kubectl delete -f wordpress.yaml
kubectl get pv
```
as you can see pv already exists:
```
[root@dev-86-201 kubernetes]# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                 STORAGECLASS      REASON   AGE
pvc-af2dfbd4-1ee9-11e9-84fc-becbfc415cde   20Gi       RWO            Retain           Released   default/wp-pv-claim   rook-ceph-block            3d21h
```

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod):
 rook: v0.9.0-79.g1a1ffdd
* Kubernetes version (use `kubectl version`):
1.13.2

**Comment by immesys** [comment]
What does your storage class yaml look like?

**Comment by fanux** [comment]
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool   # operator会监听并创建一个pool，执行完后界面上也能看到对应的pool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block    # 这里创建一个storage class, 在pvc中指定这个storage class即可实现动态创建PV
provisioner: ceph.rook.io/block
parameters:
  blockPool: replicapool
  # The value of "clusterNamespace" MUST be the same as the one in which your rook cluster exist
  clusterNamespace: rook-ceph
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  fstype: xfs
# Optional, default reclaimPolicy is "Delete". Other options are: "Retain", "Recycle" as documented in https://kubernetes.io/docs/concepts/storage/storage-classes/
reclaimPolicy: Retain
```
