### ISSUE TITLE
Monitors are not rebalanced

### ISSUE THREAD

**Issue by zerkms** [rook/rook#2581]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
This is relevant to https://github.com/rook/rook/pull/1212 and may have some relations to https://github.com/rook/rook/issues/2570

I have found that the operator does not re-balances monitors.

Test scenario:

1. I created a cluster of 3 storage nodes. All nodes run monitors
2. I shut down the node 1 (the one that runs `mon-a`)
3. Operator detected it - it created `mon-d` on node 2
4. I gave it 10 minutes to run like that
5. Then I started the node 1 again
6. Operator is calm - it reports nothing, and does not perform rebalancing

**Expected behavior:**
It should remove `mon-d` and recover `mon-a` on the node 1, so that every node was running a monitor

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS
* Kernel (e.g. `uname -a`): 4.15.0-1031-aws #33-Ubuntu SMP Fri Dec 7 09:32:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v0.9.0-97.g0e55102
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm on aws
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
```
  cluster:
    id:     713b7aaf-4ae0-46f4-9ab3-3e5688857bd3
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum c,d,b
    mgr: a(active)
    osd: 3 osds: 3 up, 3 in
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0  objects, 0 B
    usage:   3.0 GiB used, 1.2 TiB / 1.2 TiB avail
    pgs: 
```
That's how debug logs look

```
2019-01-28 20:42:00.070312 D | op-mon: mon c found in quorum
2019-01-28 20:42:00.070317 D | op-mon: mon d found in quorum
2019-01-28 20:42:00.070343 D | op-mon: mon b found in quorum
2019-01-28 20:42:00.080658 D | op-mon: node rook-2 with mon b is still valid
2019-01-28 20:42:00.082351 D | op-mon: node rook-3 with mon c is still valid
2019-01-28 20:42:00.084451 D | op-mon: node rook-2 with mon d is still valid
```
