### ISSUE TITLE
nodeAffinity: op-osd: no valid node available to run an osd in namespace rook-ceph

### ISSUE THREAD

**Issue by r0bj** [rook/rook#2582]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OSDs are not running. Operator generates warning:
```
2019-01-28 20:41:48.074213 W | op-osd: no valid node available to run an osd in namespace rook-ceph
```

**Expected behavior:**
OSDs are running using nodeAffinity definition.

**How to reproduce it (minimal and precise):**

I used operator.yaml (https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml) and cluster.yaml (https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml) from examples.

I edited cluster.yaml to add nodeAffinity definition:
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v13.2.4-20190109
    allowUnsupported: false
  dataDirHostPath: /data/rook
  mon:
    count: 3
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: k8s-role
              operator: In
              values:
              - k8s-storage
      tolerations:
      - key: node-role.kubernetes.io/storage
        operator: Exists
  resources:
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: false
    deviceFilter:
    location:
    config:
      databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      osdsPerDevice: "1" # this value can be overridden at the node or device level
```

My k8s nodes:
```
k8s-storage-p1      Ready    storage   165m   v1.12.3   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,k8s-role=k8s-storage,kubernetes.io/hostname=k8s-storage-p1,node-role.kubernetes.io/storage=
k8s-storage-p2      Ready    storage   160m   v1.12.3   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,k8s-role=k8s-storage,kubernetes.io/hostname=k8s-storage-p2,node-role.kubernetes.io/storage=
k8s-storage-p3      Ready    storage   160m   v1.12.3   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,k8s-role=k8s-storage,kubernetes.io/hostname=k8s-storage-p3,node-role.kubernetes.io/storage=
k8s-worker-p1       Ready    <none>    18d    v1.12.3   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,k8s-role=k8s-worker,kubernetes.io/hostname=k8s-worker-p1
k8s-worker-p2       Ready    <none>    17d    v1.12.3   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,k8s-role=k8s-worker,kubernetes.io/hostname=k8s-worker-p2
k8s-worker-p3       Ready    <none>    17d    v1.12.3   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,k8s-role=k8s-worker,kubernetes.io/hostname=k8s-worker-p3
```

Nodes `k8s-storage-s*` has taints:
```
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/storage
```

After apply cluster.yaml:
```
# kubectl -n rook-ceph get pods -o wide
NAME                               READY   STATUS    RESTARTS   AGE     IP               NODE             NOMINATED NODE
rook-ceph-mgr-a-66965c8697-vvl82   1/1     Running   0          101s    10.204.125.206   k8s-storage-p2   <none>
rook-ceph-mon-a-56b76dd76d-4xmjw   1/1     Running   0          2m17s   10.204.12.16     k8s-storage-p1   <none>
rook-ceph-mon-b-669cd58958-twnnp   1/1     Running   0          2m6s    10.204.125.205   k8s-storage-p2   <none>
rook-ceph-mon-c-685d45474c-4wgfh   1/1     Running   0          116s    10.204.58.143    k8s-storage-p3   <none>
```

OSDs are not running, operator generates warning:
```
2019-01-28 20:58:17.080370 W | op-osd: no valid node available to run an osd in namespace rook-ceph
```
Full log:
https://gist.github.com/r0bj/8ec9a02e342853059880ed15f0841dfb

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
* Kernel (e.g. `uname -a`):
```
Linux k8s-deployer-p1 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): `rook: v0.9.2`
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by r0bj** [comment]
@immesys yes

Example deployment with affinity:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: rook-ceph
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k8s-role
                operator: In
                values:
                - k8s-storage
      tolerations:
      - key: node-role.kubernetes.io/storage
        operator: Exists
      containers:
      - name: nginx
        image: nginx:1.15.4-alpine
```

Pods running on storage node:
```
# kubectl -n rook-ceph get pods -o wide
test-5fdd7f6869-s7v4p                        1/1     Running     0          65s     10.204.12.42     k8s-storage-p1   <none>
```

**Comment by r0bj** [comment]
It's still a valid issue.

**Comment by carpenike** [comment]
@r0bj  -- I'm running into the same problem, though I'm trying to only have it apply for osd placement.

Did you ever get it resolved?

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # The container image used to launch the Ceph daemon pods (mon, mgr, osd, mds, rgw).
    # v12 is luminous, v13 is mimic, and v14 is nautilus.
    # RECOMMENDATION: In production, use a specific version tag instead of the general v14 flag, which pulls the latest release and could result in different
    # versions running within the cluster. See tags available at https://hub.docker.com/r/ceph/ceph/tags/.
    image: ceph/ceph:v14.2.1-20190430
    # Whether to allow unsupported versions of Ceph. Currently luminous, mimic and nautilus are supported, with the recommendation to upgrade to nautilus.
    # Do not set to true in production.
    allowUnsupported: false
  # The path on the host where configuration files will be persisted. Must be specified.
  # Important: if you reinstall the cluster, make sure you delete this directory from each host or else the mons will fail to start on the new cluster.
  # In Minikube, the '/data' directory is configured to persist across reboots. Use "/data/rook" in Minikube environment.
  dataDirHostPath: /var/lib/rook
  # set the amount of mons to be started
  mon:
    count: 3
    allowMultiplePerNode: false
  # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    # port: 8443
    # serve the dashboard using SSL
    # ssl: true
  network:
    # toggle to use hostNetwork
    hostNetwork: false
  rbdMirroring:
    # The number of daemons that will perform the rbd mirroring.
    # rbd mirroring must be configured with "rbd mirror" from the rook toolbox.
    workers: 0
  # To control where various services will be scheduled by kubernetes, use the placement configuration sections below.
  # The example under 'all' would have all services scheduled on kubernetes nodes labeled with 'role=storage-node' and
  # tolerate taints with a key of 'storage-node'.
  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/controlplane
              operator: In
              values:
              - "true"
#      podAffinity:
#      podAntiAffinity:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
        operator: Equal
        value: "true"
# The above placement information can also be specified for mon, osd, and mgr components
#    mon:
#    osd:
#    mgr:
  annotations:
#    all:
#    mon:
#    osd:
# If no mgr annotations are set, prometheus scrape annotations will be set by default.
#   mgr:
  resources:
# The requests and limits set here, allow the mgr pod to use half of one CPU core and 1 gigabyte of memory
#    mgr:
#      limits:
#        cpu: "500m"
#        memory: "1024Mi"
#      requests:
#        cpu: "500m"
#        memory: "1024Mi"
# The above example requests/limits can also be added to the mon and osd components
#    mon:
#    osd:
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: true
    deviceFilter:
    location:
    config:
```
