### ISSUE TITLE
Wordpress/MySQL example yamls should use apps/v1 deployment with a required selector

### ISSUE THREAD

**Issue by l10xbin** [rook/rook#2731]
Failed with error information

error: error validating "wordpress.yaml": error validating data: [ValidationError(Deployment.spec.selector): unknown field "app" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector, ValidationError(Deployment.spec.selector): unknown field "tier" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector]; if you choose to ignore these errors, turn validation off with --validate=false

Solution:
Change the deployment api version 

From **apiVersion: apps/v1** to **apiVersion: extensions/v1beta1**

Or add selector for the deployment

EDIT (jbw976): This is the error I saw:
```
error: error validating "wordpress.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by galexrt** [comment]
@l10xbin What Kubernetes/OpenShift and Rook version are you running?

**Comment by l10xbin** [comment]
Here is my environment information:

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by l10xbin** [comment]
Rook is the latest one

**Comment by galexrt** [comment]
@l10xbin What do you understand as "Rook is the latest one"? A Rook image that uses `master` as the tag? The latest release `v0.9.2`?

**Comment by l10xbin** [comment]
@galexrt I mean I used master branch(the latest code).  I did not hit a problem when loading image. Just the yaml(wordpress.yaml) file can't be apply in my k8s environment.  

Anyway, I checked the rook-ceph-operator docker image which used  `Image: rook/ceph:master`

**Comment by galexrt** [comment]
@l10xbin I was unable to reproduce the issue in Minikube 1.12.3.
Could you please check if your Kubernetes cluster is not having issues? The `apps/v1` APIs are already in K8S since around 1.9 - 1.10 or so (if not longer).

Also be sure to verify that it is not a "cache" problem, by deleting the `$HOME/.kube/cache/` and `$HOME/.kube/http-cache/` directories.

**Comment by l10xbin** [comment]
@galexrt  I not sure if the behavior will be same in minikube and the real kube. But after I clean the cache and http-cache. The problem still exist.  Maybe we did not based on the same gitcommit.

![image](https://user-images.githubusercontent.com/40697655/53861329-e2d02880-401e-11e9-9b1f-e22755411703.png)


Anyway, this issue does not block me, just in case some guy like me have the same issue can work around it.

**Comment by HaveFun83** [comment]
I had the similar issue on k8s 1.13.4:
Adding a selector in the deployment.specs fixed this issue:
```
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
  loadBalancerIP: 10.6.240.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.6.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          value: changeme
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
```
