### ISSUE TITLE
osdsperdevice does not work as intended

### ISSUE THREAD

**Issue by sharkymcdongles** [rook/rook#2751]
When I set the osdsperdevice setting to 5 for my nvmes per documentation, I see the rookcmd passes the setting at cluster creation:

> rookcmd: flag values: --cluster-id=62aa7e04-3d03-11e9-8c34-000d3a45ec81, --data-device-filter=, --data-devices=nvme0n1,nvme1n1, --data-directories=, --encrypted-device=false, --force-format=false, --help=false, --location=, --log-level=INFO, --metadata-device=, --node-name=minion-10, --osd-database-size=20480, --osd-journal-size=5120, --osd-store=bluestore, --osd-wal-size=576, --osds-per-device=5

However only 1 osd is created per device.

Below are my settings. 

```
    storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: false
    deviceFilter: ^nvme
    location:
    config:
      # The default and recommended storeType is dynamically set to bluestore for devices and filestore for directories.
      # Set the storeType explicitly only if it is required not to use the default.
      storeType: bluestore
      #databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      #journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      osdsPerDevice: "5" # this value can be overridden at the node or device level
```

I tried this on 0.9.2 rook and v13.2.4-20190109 and v12.2.11-20190201.

Documentation says this should work on either version:
 
> osdsPerDevice**: The number of OSDs to create on each device. High performance devices such as NVMe can handle running multiple OSDs. If desired, this can be overridden for each node and each device.
> ** NOTE: Depending on the Ceph image running in your cluster, OSDs will be configured differently. Newer images will configure OSDs with ceph-volume, which provides support for osdsPerDevice as well as other features that will be exposed in future Rook releases. OSDs created prior to Rook v0.9 or with older images of Luminous and Mimic are not created with ceph-volume and thus would not support the same features. For ceph-volume, the following images are supported:
> 
> Luminous 12.2.10 or newer
> Mimic 13.2.3 or newer
> Nautilus

**Comment by sharkymcdongles** [comment]
I have pulled the image and run the container locally. The ceph-volume inside does have the --osds-per-device setting. I also tried with different journal and database sizes with no success.

**Comment by travisn** [comment]
@sharkymcdongles i believe you're running into a bug in the `deviceFilter`. The v0.9.3 release coming out in the next hour or two will fix that issue. In the meantime, you could either try `useAllDevices: true` or list the individual devices under nodes in the `nodes` section.

**Comment by travisn** [comment]
My bad, i take that back. I was thinking of #2703, which is not merged yet and won't be in 0.9.3

**Comment by ganeshmaharaj** [comment]
@sharkymcdongles not sure if this will help, but i just tested this with `v0.9.3` and it works. One caveat being i had to set multiple `osdsPerDevice` at a different location. 
This is my sample cluster.yaml
```
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    location:
    config:
      # The default and recommended storeType is dynamically set to bluestore for devices and filestore for directories.
      # Set the storeType explicitly only if it is required not to use the default.
      # storeType: bluestore
      databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      osdsPerDevice: "1" # this value can be overridden at the node or device level
    nodes:
    - name: "clr-01"
      devices: # specific devices to use for storage can be specified for each node
      - name: "vdb"
      - name: "vdc" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "2"
    - name: "clr-02"
      devices: # specific devices to use for storage can be specified for each node
      - name: "vdb"
      - name: "vdc" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "2"
    - name: "clr-03"
      devices: # specific devices to use for storage can be specified for each node
      - name: "vdb"
      - name: "vdc" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "2"
```
With that i have 9 osds running in my cluster.
```
rook-ceph          rook-ceph-osd-0-b89cd88f9-8krtt       1/1     Running     0          3m24s   10.244.2.7        clr-03   <none>           <none>
rook-ceph          rook-ceph-osd-1-57ddd66f95-fnnjv      1/1     Running     0          3m9s    10.244.1.10       clr-02   <none>           <none>
rook-ceph          rook-ceph-osd-2-56f4946f6c-p4wdw      1/1     Running     0          2m38s   10.244.0.9        clr-01   <none>           <none>
rook-ceph          rook-ceph-osd-3-75fd8bd66b-ttnc5      1/1     Running     0          3m24s   10.244.2.8        clr-03   <none>           <none>
rook-ceph          rook-ceph-osd-4-686675f874-grpd6      1/1     Running     0          3m9s    10.244.1.9        clr-02   <none>           <none>
rook-ceph          rook-ceph-osd-5-dfb8949f6-ld97p       1/1     Running     0          3m24s   10.244.2.9        clr-03   <none>           <none>
rook-ceph          rook-ceph-osd-6-797b84599f-569xw      1/1     Running     0          2m38s   10.244.0.10       clr-01   <none>           <none>
rook-ceph          rook-ceph-osd-7-64c4884fcf-qz7g6      1/1     Running     0          3m8s    10.244.1.8        clr-02   <none>           <none>
rook-ceph          rook-ceph-osd-8-74db59f949-lbpmj      1/1     Running     0          2m37s   10.244.0.11       clr-01   <none>           <none>                                                                                                                                                                  
```
