### ISSUE TITLE
ceph ssl disabled but dashboard service port name is still https-dashboard

### ISSUE THREAD

**Issue by cuisongliu** [rook/rook#2754]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
when i use http dashboard. the svc.spec.ports[0].name is https-dashboard.

**How to reproduce it (minimal and precise):** 
```
 dashboard:
    enabled: true
    urlPrefix: /
    port: 7000
    ssl: false
```
**Environment**:
* OS (e.g. from /etc/os-release): centos7
* Kernel (e.g. `uname -a`): 4.10
* Rook version (use `rook version` inside of a Rook Pod): v0.9.3
* Kubernetes version (use `kubectl version`): 1.13.0
(https://rook.io/docs/Rook/master/toolbox.html)):
