### ISSUE TITLE
document Ceph dashboard credentials in k8s secret

### ISSUE THREAD

**Issue by zlbabe** [rook/rook#2796]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Allow dashboard credentials to be defined in k8s secret.
maybe add a field `auth-secret` in the Ceph Cluster CRD config fie as follows:
```
dashboard:
  enabled: true
  auth-secret: <k8s secret name>
  ...
```

**What is use case behind this feature:**
Customization of dashboard credentials.

**Environment**:
Ceph
