### ISSUE TITLE
EdgeFS target CrashLoop

### ISSUE THREAD

**Issue by dimm0** [rook/rook#2797]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Target pod's corosync container is in crashloop

```
(⎈ |nautilus:rook-edgefs)➜  ~ k logs -f rook-edgefs-target-0 corosync
Running in container

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x620988]

goroutine 1 [running]:
_/opt/edgefs/src/efscli/config.ConfigNode()
	/opt/edgefs/src/efscli/config/config.go:125 +0x98
_/opt/edgefs/src/efscli/config.ConfigFileFnc(0xaad8c0, 0xc420064990, 0x1, 0x1)
	/opt/edgefs/src/efscli/config/file.go:80 +0x1b6
github.com/spf13/cobra.(*Command).execute(0xaad8c0, 0xc420064950, 0x1, 0x1, 0xaad8c0, 0xc420064950)
	/opt/edgefs/src/efscli/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xab5b60, 0x0, 0xaaee20, 0xab5cb0)
	/opt/edgefs/src/efscli/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xab5b60, 0xc420073f20, 0x1)
	/opt/edgefs/src/efscli/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/opt/edgefs/src/efscli/main.go:60 +0x288
```

Can't even find this class in rook sources...

**Expected behavior:**
Target pods starts

**How to reproduce it (minimal and precise):**
Here's my config:

```
apiVersion: edgefs.rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-edgefs
  namespace: rook-edgefs
spec:
  edgefsImageName: edgefs/edgefs:latest   # specify version here, i.e. edgefs/edgefs:1.0.0 etc
  serviceAccount: rook-edgefs-cluster
  dataDirHostPath: /var/lib/edgefs
  storage: # cluster level storage configuration and selection
    config:
      useAllSSD: "true"           # use only SSDs during deployment
      useAllNodes: "false"
    nodes:
    - name: k8s-ravi-01.calit2.optiputer.net # node level storage configuration
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme1n1" # 2TB NVMe
      - name: "sda" # SSD
      - name: "sdb" # SSD
      - name: "sdc" # SSD
      - name: "sde" # SSD
      - name: "sdf" # SSD
      - name: "sdg" # SSD
      - name: "sdh" # SSD
      - name: "sdi" # SSD
```
