### ISSUE TITLE
Only reboot can add extra osd disk to ceph cluster

### ISSUE THREAD

**Issue by caisan** [rook/rook#2830]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Nothing changes in the rook and ceph cluster.
Only i reboot the k8s host, rook will prepare new osd, and add new osd to ceph cluster.
**Expected behavior:**
creating a new osd, and run a new osd.

**How to reproduce it (minimal and precise):**
edit cluster.yml,
Before:
```
......
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    location:
    config:
      # The default and recommended storeType is dynamically set to bluestore for devices and filestore for directories.
      # Set the storeType explicitly only if it is required not to use the default.
      storeType: bluestore
      # databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      # journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      osdsPerDevice: "1" # this value can be overridden at the node or device level
    nodes:
    - name: "node1"
      devices:
      - name: "vdb"
.....
```
After:
```
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    location:
    config:
      # The default and recommended storeType is dynamically set to bluestore for devices and filestore for directories.
      # Set the storeType explicitly only if it is required not to use the default.
      storeType: bluestore
      # databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      # journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      osdsPerDevice: "1" # this value can be overridden at the node or device level
    nodes:
    - name: "node1"
      devices:
      - name: "vdb"
      - name: "vdc"
```
 after new disk `vdc`, i just run command `kubectl apply -f cluster.yml`

**Environment**:
* OS (CentOS Linux release 7.5.1804 ():
* Kernel (Linux node1 3.10.0-862.el7.x86_64 #1):
* Cloud provider or hardware configuration:
* Rook version (rook: v0.9.2):
* Kubernetes version (v1.12.3):
* Storage backend status (health ok):
