### ISSUE TITLE
rbd: pool rbd does not exist - Unable to mount volumes

### ISSUE THREAD

**Issue by 0xADD1E** [rook/rook#2844]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When attempting to attach an RBD volume to a pod, it fails with `Rook: Mount volume failed: failed to attach volume replicapool-durable/: failed to map image replicapool-durable/ cluster rook-ceph. failed to map image replicapool-durable/: Failed to complete rbd: exit status 2. . output: rbd: sysfs write failed In some cases useful info is found in syslog - try "dmesg | tail". rbd: map failed: (2) No such file or directory"`

Upon consulting dmesg: 
```
[421665.446092] libceph: mon2 10.43.86.97:6790 session established
[421665.446357] libceph: client34112 fsid 4182dcf0-e266-4190-a8fa-fe64ad5f7bfa
[421665.446579] rbd: pool rbd does not exist
[421697.601885] libceph: mon0 10.43.27.69:6790 session established
[421697.602432] libceph: client34113 fsid 4182dcf0-e266-4190-a8fa-fe64ad5f7bfa
[421697.602778] rbd: pool rbd does not exist
```

Other interesting bits: If you create a replicapool named `rbd`, the dmesg log switches to 
```
[248242.538514] libceph: mon1 10.43.32.10:6790 session established
[248242.539053] libceph: client34264 fsid 4182dcf0-e266-4190-a8fa-fe64ad5f7bfa
[248244.029185] rbd: image rbd/replicapool-durable/ does not exist
```

**Expected behavior:**
Volume mounts successfully

**How to reproduce it (minimal and precise):**

Unclear at the moment: Cluster is airgapped, but has access to images from docker hub on a different host. Everything appears up to date. Have also reproduced exactly on CentOS7 in the same environment. Rancher-specific kubelet args and binds for volume plugin dir /usr/libexec/kubernetes/kubelet-plugins/volume/exec, as well as /lib/modules are in place. Please ask about any additional information

**Environment**:
* OS (e.g. from /etc/os-release): Debian 9 (Stretch)
* Kernel (e.g. `uname -a`): Debian 4.9.144-3
* Cloud provider or hardware configuration: Rancher on manually provisioned VMs
* Rook version (use `rook version` inside of a Rook Pod): 0.9.2
* Kubernetes version (use `kubectl version`): 1.13.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher RKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by galexrt** [comment]
@0xADD1E Have you created a CephBlockPool object named `rbd` as described (with another name in the examples) in the Rook Ceph Block Quickstart documentation https://rook.io/docs/rook/v0.9/ceph-block.html ?

**Comment by 0xADD1E** [comment]
I've done it both ways - The first attempt was with a CephBlockPool named `replicapool-durable`, the second was with the same configuration, this time labeled `rbd`

**Comment by 0xADD1E** [comment]
It appears to be worth noting that this issue seems to only present itself when PersistentVolumes are being manually provisioned, and possibly only with a malformed StorageClass (namely, trying to override the reclaimPolicy). 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-persist
  labels:
    app: jenkins
spec: 
  accessModes:
    - ReadWriteOnce
  capacity: 
    storage: 2Gi
  flexVolume:
    driver: ceph.rook.io/rook-ceph-system
    fsType: xfs
    options:
      clusterNamespace: rook-ceph
      pool: replicapool-durable
      storageClass: rook-ceph-durable
  storageClassName: rook-ceph-durable
```

I'm uncertain whether this should be categorized as a bug, but in any case the logs are rather misleading
