### ISSUE TITLE
Simplify required PSPs and add hostPorts required to operator Chart

### ISSUE THREAD

**Issue by lewismarshall** [rook/rook#2852]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The Chart defined PSP which seems intended for Ceph clusters, specifies hostNetworking but doesn't specify the required hostPorts.

The [rook docs for Cluster CRD PSP](https://github.com/rook/rook/blob/master/Documentation/rbac.md#rbac-for-podsecuritypolicies) is almost identical to the the PSP in the chart and includes the hostPorts - although easily missed in documentation. The documentation also suggests naming the PSP `privileged` which clashes with another PSP in our clusters and was part of the motivation to re-use the PSP created by the operator Chart.

**Expected behavior:**
The hostPorts should be specified in the charts:
```
hostPorts:
    # Ceph ports
    - min: 6789
      max: 7300
    # Ceph MGR Prometheus Metrics
    - min: 9283
      max: 9283
```

Maybe there should also be a Chart value to enable hostNetwork in a block (given as you can only have a single rook-ceph cluster operating when it's enabled anyway)?

The hostPort requirement is probably also relevant to #2700 and the implementation #2820 but also #2109.

**How to reproduce it (minimal and precise):**

1. Created an operator using the [helm chart YAML](https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/) and the [specific PSP](https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/templates/psp.yaml).
1. Updated the examples to refer to the `rook-ceph-system-psp-user` for the cluster namespace (required for the Mon pods specifically):
    ```
    # Allow the default serviceAccount to use the privileged PSP
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: rook-default-psp
      namespace: rook-ceph
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: rook-ceph-system-psp-user
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: rook-ceph
    ```
After the Mons failed to schedule, manually updated [PSP](https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/templates/psp.yaml) to include the hostPorts (specified above).

**Environment**:
* OS (e.g. from /etc/os-release): `Container Linux by CoreOS`
* Kernel (e.g. `uname -a`): `Linux dsp-ops3 4.14.96-coreos-r1 #1 SMP Tue Feb 12 21:16:22 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz GenuineIntel GNU/Linux`
* Cloud provider or hardware configuration: Metal (Cisco UCS)
* Rook version (use `rook version` inside of a Rook Pod): v0.9.3
* Kubernetes version (use `kubectl version`): v.1.12.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Custom PXE boot
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): - Wasn't healthy (`ceph status` did not return until after the PSP updated).
