### ISSUE TITLE
mons bind to default port after upgrade from legacy, causing upgrade failure

### ISSUE THREAD

**Issue by travisn** [rook/rook#2854]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In 0.9 and previous we were using port 6790 as a non-default port for the mons.  In master we are now using the default port of 6789. The upgrade from 0.9 to master is failing due to the following sequence:
- 0.9 starts mons on port 6790
- The cluster is upgraded to master
- The new mon pod spec correctly configures port 6790 for the upgraded mon
- The mon is actually listening on port 6789 inside the pod because there is no ceph.conf configuration that indicates it should listen on a non-default port.
- The mons cannot form quorum and the operator times out connecting to the mons after upgrade.

**Expected behavior:**
Mons should be listening on port 6790 after the upgrade.

@BlaineEXE can we generate the config for mons to listen on the non-default port? In 0.9 the config generated the following, but we can hopefully do this with a command line option now.
```
[mon.a]
public bind addr = 172.17.0.6:6790
```

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by leseb** [comment]
Yes, we stopped enforcing any ports for `public_bind_ addr` because it does not behave well with msgr2. If we force a particular port then we can only have one so no port for msgr2...
This is tricky, we might need to disable msgr2 for "old" cluster that was running on a non-standard port. However, msgr1 might disappear in Octopus so we won't be helping them by doing this...

**Comment by leseb** [comment]
Another option I guess will be to migrate the monitors to new ones so they can pickup the 6789 port then do the upgrade. So basically, the procedure will be:

* Destroy monitor one by one
* New monitors will listen on msgr1
* Upgrade to master or 1.0

**Comment by BlaineEXE** [comment]
Okay. I was having some environment issues while trying to get set up to run the `TestUpgradeSuite` integration test. Everything is good now, and I'm starting to look into this. I think I would rather do something along the lines of Seb's second option, to automatically move from port 6790 to 6789.

If a user is using a direct connection to Ceph's mons via host networking, this would require them to change any configs to use port 6789, which would be a breaking update. It's not ideal, but I think this sounds like an okay move forward since msgr2 brings a lot of great improvements

**Comment by BlaineEXE** [comment]
@travis and @leseb I am observing that in the `TestUpgradeSuite` test, the monitors (according to their logs) still listen on port 6790 with only the IP set on the commandline. Joao confirmed that this behavior is expected, as the mons have their monmap stored on disk in their database. 

The buggy behavior I am seeing is defined below.

#### The operator still uses the 6790 ports for connection
```
[root@rook-ceph-operator-6bbc9bbd84-qphn2 /]# cat /var/lib/rook/upgrade-ns/upgrade-ns.config 
[global]
fsid                      = 25973937-9728-48d8-adfe-86719494dd2c
run dir                   = /var/lib/rook/upgrade-ns
mon initial members       = b c a
mon host                  = 10.111.168.200:6790,10.105.27.175:6790,10.111.170.109:6790
```

#### Despite not seeing a move to port 6789, the operator is unable to query the cluster's status with the log below repeating.
```
rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/963356104
2019-04-01 20:34:22.014737 I | exec: timed out
2019-04-01 20:34:27.057819 I | op-mon: mons running: [c a b]
2019-04-01 20:34:27.057991 I | exec: Running command: ceph mon_status --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/372019847
```

#### Mon logs don't appear to be in error state

What is interesting is that I don't see any log entries in the mon log that suggests that it is unable to connect with the other mons. I'm not sure what that message would look like if it appeared, however.


#### The daemon container still exposes port 6790, and the service still looks for 6790 and exposes it to 6790.
```yaml
  containers:
  - args:
    - --fsid=25973937-9728-48d8-adfe-86719494dd2c
    - --keyring=/etc/ceph/keyring-store/keyring
    - --log-to-stderr=true
    - --err-to-stderr=true
    - --mon-cluster-log-to-stderr=true
    - '--log-stderr-prefix=debug '
    - --mon-host=$(ROOK_CEPH_MON_HOST)
    - --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
    - --id=b
    - --foreground
    - --public-addr=10.111.168.200
    - --public-bind-addr=$(ROOK_POD_IP)
    command:
    - ceph-mon
    env:
    - name: CONTAINER_IMAGE
      value: ceph/ceph:v13
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: POD_MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.memory
    - name: POD_MEMORY_REQUEST
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: requests.memory
    - name: POD_CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "1"
          resource: limits.cpu
    - name: POD_CPU_REQUEST
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: requests.cpu
    - name: ROOK_CEPH_MON_HOST
      valueFrom:
        secretKeyRef:
          key: mon_host
          name: rook-ceph-config
    - name: ROOK_CEPH_MON_INITIAL_MEMBERS
      valueFrom:
        secretKeyRef:
          key: mon_initial_members
          name: rook-ceph-config
    - name: ROOK_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: ceph/ceph:v13
    imagePullPolicy: IfNotPresent
    name: mon
    ports:
    - containerPort: 6790
      name: client
      protocol: TCP
```
```yaml
blaine-dev-k8s-master-0:~ # kubectl -n upgrade-ns get -o yaml service rook-ceph-mon-b 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-04-01T20:24:35Z"
  labels:
    app: rook-ceph-mon
    ceph_daemon_id: b
    mon: b
    mon_cluster: upgrade-ns
    rook_cluster: upgrade-ns
  name: rook-ceph-mon-b
  namespace: upgrade-ns
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    kind: CephCluster
    name: upgrade-ns
    uid: 03368bfd-54bc-11e9-84fd-fa163eec75de
  resourceVersion: "11822"
  selfLink: /api/v1/namespaces/upgrade-ns/services/rook-ceph-mon-b
  uid: 2ac79e30-54bc-11e9-84fd-fa163eec75de
spec:
  clusterIP: 10.111.168.200
  ports:
  - name: rook-ceph-mon-b
    port: 6790
    protocol: TCP
    targetPort: 6790
  selector:
    app: rook-ceph-mon
    ceph_daemon_id: b
    mon: b
    mon_cluster: upgrade-ns
    rook_cluster: upgrade-ns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by BlaineEXE** [comment]
@travisn what is the process for addressing this:
```
=== checking if vendor deps changed

# Gopkg.lock is out of sync:

k8s.io/apimachinery/pkg/api/equality: imported or required, but missing from Gopkg.lock's input-imports

make: *** [go.vendor.check] Error 1

build/makelib/golang.mk:181: recipe for target 'go.vendor.check' failed

script returned exit code 1
```

**Comment by erictcgs** [comment]
Hi @BlaineEXE - I'm testing with an image after these changes but still getting the errors you got, what did you have to do in the end to get the operator to not time out?

Test description: Upgraded a test cluster from rook 0.8 to rook v0.9.0-374.g2ca611a (should include all recent changes, just a few days old?), then luminous to mimic, mimic to nautilus.

Luminous to mimic was fine, but mimic to nautilus I observed:
- mon's upgraded successfully, mon logs look good (mons find eachother and report quorum)
- mgr never updates
- upgraded toolbox, ceph status works and shows mon quorum
- operator seems to have hung on `ceph mon_status` command - logs show:
```
2019-04-11 15:36:38.417846 I | op-mon: mons running: [rook-ceph-mon0 rook-ceph-mon1 rook-ceph-mon2]
2019-04-11 15:36:38.417987 I | exec: Running command: ceph mon_status --connect-timeout=15 --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/734785396
2019-04-11 15:36:53.541356 I | exec: 2019-04-11 15:36:38.560 7fa92bfff700 -1 --2-  >> [v2:10.97.133.244:3300/0,v1:10.97.133.244:6790/0] conn(0x7fa92c14b2f0 0x7fa92c150440 unknown :-1 s=BANNER_CONNECTING pgs=0 cs=0 l=0 rx=0 tx=0)._handle_peer_banner peer [v2:10.97.133.244:3300/0,v1:10.97.133.244:6790/0] is using msgr V1 protocol
<similar lines repeated ~100 times>
...
timed out
2019-04-11 15:36:53.541531 E | op-cluster: failed to create cluster in namespace rook. failed to start the mons. failed to start mon pods. failed to wait for mon quorum. exceeded max retry count waiting for monitors to reach quorum
2019-04-11 15:36:53.541554 E | op-cluster: giving up creating cluster in namespace rook after 1h0m0s
2019-04-11 15:36:53.551905 I | op-cluster: update event for cluster rook
2019-04-11 15:36:53.551971 I | op-cluster: update event for cluster rook is not supported
```

Operator ceph.conf seems to have the v1 and v2 settings reflecting recent commits:
```
# cat /etc/ceph/ceph.conf 
[global]
fsid                      = 9bb8c803-3567-4e9f-98b8-4ccd94b3cdd6
run dir                   = /var/lib/rook/rook
mon initial members       = rook-ceph-mon1 rook-ceph-mon2 rook-ceph-mon0
mon host                  = [v2:10.97.133.244:3300,v1:10.97.133.244:6790],[v2:10.111.93.172:3300,v1:10.111.93.172:6790],[v2:10.111.199.224:3300,v1:10.111.199.224:6790]
...
```

Here's from a mon log:
```
debug 2019-04-11 14:18:44.957 7f32a8a2eec0  0 starting mon.rook-ceph-mon0 rank 2 at public addrs v1:10.111.199.224:6790/0 at bind addrs [v2:10.244.3.232:3300/0,v1:10.244.3.232:6789/0] mon_data /var/lib/ceph/mon/ceph-rook-ceph-mon0 fsid 9bb8c803-3567-4e9f-98b8-4ccd94b3cdd6
cluster 2019-04-10 22:35:25.debug 2019-04-11 14:18:44.957 7f32a8a2eec0  1 mon.rook-ceph-mon0@-1(???) e5 preinit fsid 9bb8c803-3567-4e9f-98b8-4ccd94b3cdd6
debug 2019-04-11 14:18:44.957 7f32a8a2eec0  0 mon.rook-ceph-mon0@-1(???).mds e816 new map
debug 2019-04-11 14:18:44.957 7f32a8a2eec0  0 mon.rook-ceph-mon0@-1(???).mds e816 print_map
...
cluster 2019-04-11 14:20:19.627972 mon.rook-ceph-mon0 (mon.2) 1 : cluster [INF] mon.rook-ceph-mon0 calling monitor election
cluster 2019-04-11 14:20:30.741580 osd.1 (osd.1) 229 : cluster [DBG] 2.31 deep-scrub starts
cluster 2019-04-11 14:20:36.682628 osd.1 (osd.1) 230 : cluster [DBG] 2.31 deep-scrub ok
cluster 2019-04-11 14:20:37.665416 mon.rook-ceph-mon2 (mon.1) 5 : cluster [INF] mon.rook-ceph-mon2 calling monitor election
cluster 2019-04-11 14:20:37.667886 mon.rook-ceph-mon1 (mon.0) 43 : cluster [INF] mon.rook-ceph-mon1 calling monitor election
cluster 2019-04-11 14:20:37.784758 osd.1 (osd.1) 231 : cluster [DBG] 3.44 deep-scrub starts
cluster 2019-04-11 14:20:41.974446 mon.rook-ceph-mon1 (mon.0) 44 : cluster [INF] mon.rook-ceph-mon1 is new leader, mons rook-ceph-mon1,rook-ceph-mon2,rook-ceph-mon0 in quorum (ranks 0,1,2)
cluster 2019-04-11 14:20:41.987050 mon.rook-ceph-mon1 (mon.0) 45 : cluster [DBG] monmap e5: 3 mons at {rook-ceph-mon0=v1:10.111.199.224:6790/0,rook-ceph-mon1=v1:10.97.133.244:6790/0,rook-ceph-mon2=v1:10.111.93.172:6790/0}
```

Here's a service spec, seems to show 6790 connecting to 6789:
```yaml
  metadata:
    name: rook-ceph-mon0
    namespace: rook
  spec:
    clusterIP: 10.111.199.224
    ports:
    - name: msgr1
      port: 6790
      protocol: TCP
      targetPort: 6789
    - name: msgr2
      port: 3300
      protocol: TCP
      targetPort: 3300
    selector:
      app: rook-ceph-mon
      ceph_daemon_id: rook-ceph-mon0
      mon: rook-ceph-mon0
      mon_cluster: rook
      rook_cluster: rook
```
