### ISSUE TITLE
master - Wrong ssl and port config on mgr

### ISSUE THREAD

**Issue by mmack** [rook/rook#2875]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
MGR starts on host port 8443 with ssl enabled

**Expected behavior:**
MGR starts on host port 8080 with ssl disabled

**How to reproduce it (minimal and precise):**

```
  mon:
    count: 5
    allowMultiplePerNode: false
  network:
    hostNetwork: true
  rbdMirroring:
    workers: 3
  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    port: 8080
    # # serve the dashboard using SSL
    ssl: false
```

The Pod is configured correct:
```
Containers:
  mgr:
    Container ID:  docker://966b435ba899337cb641a6e47b916831e3b18bbfdae38f8b5c522dfc9216b32f
    Image:         ceph/ceph:v14.2
    Image ID:      docker-pullable://ceph/ceph@sha256:550d45fbdd3625bec5681389ab68e267a1da0318e19aa0045684d511b872ae5b
    Ports:         6800/TCP, 9283/TCP, 8080/TCP
    Host Ports:    6800/TCP, 9283/TCP, 8080/TCP
    Command:
      ceph-mgr
    Args:
      --fsid=6b9e803d-0aa2-4528-a406-3392785e7dbf
      --keyring=/etc/ceph/keyring-store/keyring
      --log-to-stderr=true
      --err-to-stderr=true
      --mon-cluster-log-to-stderr=true
      --log-stderr-prefix=debug 
      --mon-host=$(ROOK_CEPH_MON_HOST)
      --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
      --id=a
      --foreground
```

However the mgr listens on port 8443:
```
[22/Mar/2019:08:25:03] ENGINE Serving on 172.22.253.88:9283
[22/Mar/2019:08:25:03] ENGINE Bus STARTED
[22/Mar/2019:08:25:03] ENGINE Bus STARTING
[22/Mar/2019:08:25:03] ENGINE Started monitor thread '_TimeoutMonitor'.
[22/Mar/2019:08:25:03] ENGINE Serving on 172.22.253.88:8443
[22/Mar/2019:08:25:03] ENGINE Bus STARTED
```

See curl:
```
curl -X HEAD -v --insecure https://172.22.253.88:8443
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the 
Warning: way you want. Consider using -I/--head instead.
* Rebuilt URL to: https://172.22.253.88:8443/
*   Trying 172.22.253.88...
* TCP_NODELAY set
* Connected to 172.22.253.88 (172.22.253.88) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=IT; CN=ceph-dashboard
*  start date: Mar 22 08:05:05 2019 GMT
*  expire date: Mar 19 08:05:05 2029 GMT
*  issuer: O=IT; CN=ceph-dashboard
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> HEAD / HTTP/1.1
> Host: 172.22.253.88:8443
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
```

```
curl -X HEAD -v --insecure https://172.22.253.88:8080
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the 
Warning: way you want. Consider using -I/--head instead.
* Rebuilt URL to: https://172.22.253.88:8080/
*   Trying 172.22.253.88...
* TCP_NODELAY set
* connect to 172.22.253.88 port 8080 failed: Connection refused
* Failed to connect to 172.22.253.88 port 8080: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 172.22.253.88 port 8080: Connection refused

```

**Environment:**
OS (e.g. from /etc/os-release):
hostNetwork: true
Kernel (e.g. uname -a):
4.14.96-coreos
Cloud provider or hardware configuration:
bare-metal / vmware
Rook version (use rook version inside of a Rook Pod):
 v0.9.0-323.g2447520
Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mmack** [comment]
Another fact, if i use hostNetwork: false and redeploy the cluster no dashboard comes up at all:
``




```
[root@k8s-worker-20 /]# ceph -s
  cluster:
    id:     4ad6281a-6ca7-4ade-af23-66d41db90b2c
    health: HEALTH_WARN
            noscrub,nodeep-scrub flag(s) set
 
  services:
    mon: 5 daemons, quorum a,b,c,d,e (age 16m)
    mgr: a(active, since 9m)
    osd: 32 osds: 32 up (since 4m), 32 in (since 4m)
         flags noscrub,nodeep-scrub
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   32 GiB used, 736 GiB / 768 GiB avail
    pgs:     

```
