### ISSUE TITLE
No osd prepare pods created 

### ISSUE THREAD

**Issue by feresberbeche** [rook/rook#2909]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
No osd prepare pod created, to provison storage and create osd pods

**Expected behavior:**

**How to reproduce it (minimal and precise):**
oc create -f scc.yaml
oc create -f operator.yaml
oc create -f cluster.yaml

changed inthe operator.yaml
>        - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
>          value: "true"

Storage config in the cluster.yaml changed to:

```
  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: loop0
    location:
    config:
      databaseSizeMB: "1024" 
      journalSizeMB: "1024"
      osdsPerDevice: "1"
```
I tried using directories too with no luck.

```
  storage: 
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    location:
    nodes:
    - name: "HOSTNAME OF THE NODE"
      directories:     
      - path: "/rook/storage-dir"
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024" 
      osdsPerDevice: "1" 
```

**Environment**:
features: Basic-Auth GSSAPI Kerberos SPNEGO
* OS CentOS Linux release 7.6.1810 (Core)
* Kernel 3.10.0-957.5.1.el7.x86_64
* Cloud provider or hardware configuration: VMware VM
* Rook version: v0.9.3
* Kubernetes version v1.11.0+d4cacc0
* Kubernetes cluster type openshift v3.11.0+92b7c41-132
* features: Basic-Auth GSSAPI Kerberos SPNEGO

oc get nodes:

```
 NAME                                   STATUS    ROLES          AGE       VERSION
 *******-1-devops.net   Ready     infra,master,compute   14d       v1.11.0+d4cacc0
*******-2-devops.net   Ready     compute        14d       v1.11.0+d4cacc0
```

lsblk on both nodes:

```
NAME            MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda               8:0    0   50G  0 disk
├─sda1            8:1    0    1G  0 part /boot
└─sda2            8:2    0   49G  0 part
  ├─centos-root 253:0    0 45.1G  0 lvm  /
  └─centos-swap 253:1    0  3.9G  0 lvm
sr0              11:0    1  4.2G  0 rom
loop0             7:0    0  9.8G  0 loop
```

```
sh-4.2# ceph -s
    cluster:
    id:     9d53f5e8-bbf8-4d7b-8f36-89267d296e7a
    health: HEALTH_OK

  services:
    mon: 1 daemons, quorum a
    mgr: no daemons active
    osd: 0 osds: 0 up, 0 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0  objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:
```
