### ISSUE TITLE
Helm install rook operator, tolerationKey not used ?

### ISSUE THREAD

**Issue by PaulSka** [rook/rook#2955]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
TolerationKey is not used ?

**Expected behavior:**

Agent and Discord on specific node with toleration

**How to reproduce it (minimal and precise):**
3 Nodes
Taint a node : kubectl taint nodes NODE1 is_storage=true:NoSchedule
Use a values.yaml :
```
agent:
  toleration: NoSchedule
  tolerationKey: is_storage
discover:
  toleration: NoSchedule
  tolerationKey: is_storage
```
Install rook chart : helm install ... rook-stable/rook-ceph -f values.yaml
Discover and Agent is on ALL nodes

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
