### ISSUE TITLE
Multiple Clusters conflict with their host paths

### ISSUE THREAD

**Issue by rjemanuele** [rook/rook#2968]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Multiple Ceph Clusters conflict with their host paths when brought up by the operator.

I have two Ceph Clusters CRDs, each in their own namespace.  Cluster 1, named `rook-ceph` is a filestore cluster based in `/var/lib/rook` on the nodes.  Cluster 2, named `rook-ceph-ssd` is a bluestore cluster based in `/var/lib/rook-ssd` on the nodes and using `sdb`, an SSD, for its storage.  Each cluster has 3 mons.

When I attempt to create the second cluster, the operator creates mons for that cluster.  The newly created mons have conflicting names with the existing cluster.

Cluster 1:
```
mon-b: node05
mon-c: node06
mon-d: node09
```

Cluster 2:
```
mon-a: node04
mon-b: node05
mon-d: node06
```

Note that Cluster 2's `mon-b` tries to start on node05 which already has a `mon-b` for Cluster 1.  *It naturally fails as they both are trying to use a host path directory at `/var/lib/rook/mon-b`* on node05.

Clusters:
```
$ kubectl get CephCluster --all-namespaces
NAMESPACE       NAME            DATADIRHOSTPATH     MONCOUNT   AGE       STATE
rook-ceph-ssd   rook-ceph-ssd   /var/lib/rook-ssd   3          12m       Creating
rook-ceph       rook-ceph       /var/lib/rook       3          44d       Created
```

**Expected behavior:**

Multiple, properly namespaced, clusters should be able to co-exist within the same rook instance.

**How to reproduce it (minimal and precise):**

My two clusters are created like so:

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph-ssd
  namespace: rook-ceph-ssd
spec:
  cephVersion:
    image: ceph/ceph:v13.2.4-20190109
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook-ssd
  mon:
    allowMultiplePerNode: false
    count: 3
  storage:
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
    devices:
    - name: sdb
    useAllDevices: false
    useAllNodes: true
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v13.2.4-20190109
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mon:
    allowMultiplePerNode: true
    count: 3
  storage:
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
    useAllDevices: false
    useAllNodes: true
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 10.04.2
* Kernel (e.g. `uname -a`): `Linux node04 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Self hosted kubernetes
* Rook version (use `rook version` inside of a Rook Pod): `v0.9.1`
* Kubernetes version (use `kubectl version`): `v1.13.3`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): n/a
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): HEALTH_OK (Only available for the functional cluster)
