### ISSUE TITLE
Cannot mount Ceph block volume in DigitalOcean managed cluster

### ISSUE THREAD

**Issue by lucj** [rook/rook#2982]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Mongo deployment cannot mount volume created against 
`ceph.rook.io/block` storageclass.

```
Events:
  Type     Reason       Age                  From                       Message
  ----     ------       ----                 ----                       -------
  Warning  FailedMount  36s (x70 over 156m)  kubelet, worker-pool-mmit  Unable to mount volumes for p
od "mongo-7bff449f98-tj5hd_default(2383bad9-5e11-11e9-a822-7edb72d50a2c)": timeout expired waiting fo
r volumes to attach or mount for pod "default"/"mongo-7bff449f98-tj5hd". list of unmounted volumes=[m
ongo-persistent-storage]. list of unattached volumes=[mongo-persistent-storage default-token-ndw2k]
```

**Expected behavior:**

Workload can mount volume

**How to reproduce it (minimal and precise):**

**Environment**:

* Cloud provider or hardware configuration:
DigitalOcean

* Rook version (use `rook version` inside of a Rook Pod):
v0.9.3

* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a0876
98aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:
"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a7770
6f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:
"linux/amd64"}
```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
DigitalOcean managed cluster

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

```
$ kubectl exec -ti rook-ceph-mgr-a-66db78887f-zmcpk -n rook-ceph -- sh
sh-4.2# ceph status
2019-04-13 20:14:08.128 7f6fd2ad9700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/
ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-04-13 20:14:08.128 7f6fd2ad9700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/
ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-04-13 20:14:08.132 7f6fd2ad9700 -1 monclient: authenticate NOTE: no keyring found; disabled cephx authenticati
on
2019-04-13 20:14:08.132 7f6fd2ad9700 -1 monclient: authenticate NOTE: no keyring found; disabled cephx authenticati
on
[errno 95] error connecting to the cluster
```

**Additional information**

* Status of the rook pods:

```
kubectl get all -n rook-ceph-system
NAME                                      READY   STATUS    RESTARTS   AGE
pod/rook-ceph-agent-8p75x                 1/1     Running   0          3h

pod/rook-ceph-agent-djllc                 1/1     Running   0          3h
pod/rook-ceph-agent-rjhss                 1/1     Running   0          3h
pod/rook-ceph-operator-5f4ff4d57d-7gkhf   1/1     Running   0          3h1m
pod/rook-discover-8jsz9                   1/1     Running   0          3h
pod/rook-discover-9slj5                   1/1     Running   0          3h
pod/rook-discover-sb7cj                   1/1     Running   0          3h

NAME                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/rook-ceph-agent   3         3         3       3            3           <none>          3h
daemonset.apps/rook-discover     3         3         3       3            3           <none>          3h

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rook-ceph-operator   1/1     1            1           3h1m

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/rook-ceph-operator-5f4ff4d57d   1         1         1       3h1m
```

* Storage configuration in *cluster.yaml*

```
storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter:
    location:
    config:
      storeType: filestore
   ...
```

* Mongo deployment

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo:4.0
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
```

* PVC created

```
$ kubectl get pvc
NAME        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
mongo-pvc   Bound    pvc-98576422-5e10-11e9-a822-7edb72d50a2c   1Gi        RWO            rook-ceph-block   177m
```

* PV 

```
$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM
STORAGECLASS      REASON   AGE
pvc-98576422-5e10-11e9-a822-7edb72d50a2c   1Gi        RWO            Delete           Bound    default/mongo-pvc
rook-ceph-block            176m
```

Mongo Pod remains in ContainerCreating status

```
$ kubectl get po
NAME                     READY   STATUS              RESTARTS   AGE
mongo-7bff449f98-tj5hd   0/1     ContainerCreating   0          176m
```

```
$ kubectl describe po
...
Events:
  Type     Reason       Age                    From                       Message
  ----     ------       ----                   ----                       -------
  Warning  FailedMount  2m42s (x77 over 174m)  kubelet, worker-pool-mmit  Unable to mount volumes for pod "mongo-7b
ff449f98-tj5hd_default(2383bad9-5e11-11e9-a822-7edb72d50a2c)": timeout expired waiting for volumes to attach or mou
nt for pod "default"/"mongo-7bff449f98-tj5hd". list of unmounted volumes=[mongo-persistent-storage]. list of unatta
ched volumes=[mongo-persistent-storage default-token-ndw2k]
```

Cannot find out what I missed here, any hints ?
