### ISSUE TITLE
ROOK_OSD_DATABASE_SIZE is not correctly configured in the ceph

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#2992]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
For cephcluster cluster, the configured "Database Size MB:  2048" is not reflected in the OSD devices. Instead, the default 1G is used.

```
kubectl -n rook-ceph exec ceph-oam-6888b674bd-jdldl -c ceph-oam -- ceph osd status
+----+-----------------+-------+-------+--------+---------+--------+---------+-----------+
| id |       host      |  used | avail | wr ops | wr data | rd ops | rd data |   state   |
+----+-----------------+-------+-------+--------+---------+--------+---------+-----------+
| 0  | ceph-control-01 | 1031M | 18.9G |    0   |     0   |    0   |     0   | exists,up |
| 1  | ceph-control-02 | 1031M | 18.9G |    0   |     0   |    0   |     0   | exists,up |
| 2  | ceph-control-03 | 1031M | 18.9G |    0   |     0   |    0   |     0   | exists,up |
+----+-----------------+-------+-------+--------+---------+--------+---------+-----------+
```

**Expected behavior:**
Expect 2G is used for block.db. 

**How to reproduce it (minimal and precise):**
No special setup is needed. 

1). Here's the cluster.yaml configuration for storage:
```yaml
 storage: 
    useAllNodes: true
    useAllDevices: False
    deviceFilter: 
    devices:
      - name: "vdd"
    location:
    config:
      storeType: 
      metadataDevice: 
      databaseSizeMB: "2048" 
      journalSizeMB: "1024"  
      osdsPerDevice: "1" 
```

2). The OSD pod shows correct database size.

```
kubectl -n rook-ceph describe pod rook-ceph-osd-0-f5bf6b667-45lsz | grep DATABASE_SIZE
      ROOK_OSD_DATABASE_SIZE:     2048
```

**Environment**:
* OS (e.g. from /etc/os-release): RedHat 7.6
* Kernel (e.g. `uname -a`):  Linux ceph-control-01 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration: openstack
* Rook version (use `rook version` inside of a Rook Pod): v0.9.3
* Kubernetes version (use `kubectl version`): v1.13.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Tectonic
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
