### ISSUE TITLE
Document running Rook on OpenShift on nodes other than worker nodes

### ISSUE THREAD

**Issue by travisn** [rook/rook#3004]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
In OpenShift when a new namespace is created, by default it will have an annotation that indicates to run all the pods in that namespace only on the `worker` nodes. However, the admin commonly wants to run the rook pods on the master or infra nodes as well. 

The recommendation to work well on nodes other than the worker nodes is the following:
1. Add a label to all the nodes where you want to start rook pods
1. Add an annotation to the rook-ceph namespace to start pods on nodes with that label. For example:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: node-role.kubernetes.io/rook=true
```

Now all pods in the rook-ceph namespace will be started on all the nodes with the `rook` label and will not be limited to `worker` nodes. Further restrictions for mons, osds, and other daemons can be accomplished with the `placement` or other settings in the cluster.yaml
