### ISSUE TITLE
use nvme2n1 on all nodes with label rook=true

### ISSUE THREAD

**Issue by stephen-dahl** [rook/rook#3042]
Hello, I tried to join the slack to ask this but it is locked down to emails @rook.io
I have the following configuration working however my nodes are in autoscale groups so I want to select nodes based on labels. How should I change my config to do this?

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # For the latest ceph images, see https://hub.docker.com/r/ceph/ceph/tags
    image: ceph/ceph:v13.2.4-20190109
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
    ssl: false
  mon:
    count: 3
    allowMultiplePerNode: false
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes: 
      - name: ip-10-0-0-1
        devices:
        - name: nvme2n1
      - name: ip-10-0-0-2
        devices:
        - name: nvme2n1
      - name: ip-10-0-0-3
        devices:
        - name: nvme2n1

  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/rook
              operator: Exists
      tolerations:
      - key: rook
        operator: Exists
```

I tried these settings and more
```
  storage:
    useAllNodes: true
    useAllDevices: false
    devices:
    - name: nvme2n1
```
```
  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: nvme2n1
```
