### ISSUE TITLE
Operator doesn't honor cluster placement tolerations

### ISSUE THREAD

**Issue by lbogdan** [rook/rook#3050]
**Is this a bug report or feature request?**
* Bug Report

My (development) setup is a single storage node `storage-0`, labeled `node-role.kubernetes.io/storage=""` and tainted `role.kubernetes.io/storage:NoSchedule`.

When adding a cluster with the following definition:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  ...
  mon:
    allowMultiplePerNode: false
    count: 1
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/storage
              operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/storage
        operator: Exists
  ...
```
the operator will just sit in a loop saying `2019-04-24 06:47:02.137648 E | op-cluster: failed to create cluster in namespace rook-ceph. failed to start the mons. failed to assign pods to mons. no nodes available for mon placement` . If I remove the taint, everything initializes OK and the cluster is successfully created.

Using `rook` version **`v0.9.0-480.gfe2a291`**.

This seems to be a regression, as with `v0.9.0-284.g6d3f7ab` everything is working fine.

**Comment by travisn** [comment]
Per conversation in slack, the [GetNodeSchedulable()](https://github.com/rook/rook/blob/master/pkg/operator/k8sutil/node.go#L117-L122) method is not looking at tolerations for the `NoSchedule` taint before returning that the node is not schedulable.

The call to GetNodeSchedulable on [line 34](https://github.com/rook/rook/blob/master/pkg/operator/k8sutil/node.go#L34) is returning before the placement tolerations can be evaluated on [line 38](https://github.com/rook/rook/blob/master/pkg/operator/k8sutil/node.go#L38).

So I would expect that this only affects using a toleration for NoSchedule.
```yaml
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
```

@lbogdan Have you seen if other taints/tolerations are also affected?

**Comment by lbogdan** [comment]
@travisn No, because `NoSchedule` is the taint I need. 🙂 But reading the code, I'd expect for other taints to work, indeed.

**Comment by lbogdan** [comment]
I think replacing `if !GetNodeSchedulable(node)` with `if node.Spec.Unschedulable` in `ValidNode()` would fix this, because the following `NodeMeetsPlacementTerms(...)` already checks for taints.

**Comment by mabushey** [comment]
Affinity/tolerations are not working in 1.1. I can make the operator itself run on the correct nodes:
```
    spec:
      serviceAccountName: rook-ceph-system
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/instance-type
                operator: In
                values:
                - i3.large
      tolerations:
      - key: "storage"
        operator: Equal
        value: "i3"
```

It probably doesn;t matter where the operator runs, however none of the pods it launches in the cluster.yaml script make it to the correct servers. The docs say to use 
```
      placement:
        all:
```
I think this is wrong, K8s syntax is (as in the operator example):
```
      affinity:
        nodeAffinity:
```

I'm also not sure what to make of the
```
# The above placement information can also be specified for mon, osd, and mgr components
#    mon:
# Monitor deployments may contain an anti-affinity rule for avoiding monitor
# collocation on the same node. This is a required rule when host network is used
# or when AllowMultiplePerNode is false. Otherwise this anti-affinity rule is a
# preferred rule with weight: 50.
#    osd:
#    mgr:
```

Can someone decipher this for me? If I want them all to run on my i3 nodes, I do not need to re-specify them, correct? I would think that's what the `all` is for. The English here is very confusing.
