### ISSUE TITLE
NFS-ganesha crashing OSDs

### ISSUE THREAD

**Issue by SeanChristopherConway** [rook/rook#3125]
Operator version: v0.9.0-467.gb999605
Cluster ceph version: v14.2.0-20190410

Cluster running on two nodes with bluestore and ceph filesystem with following configs:
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.0-20190410
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  # cluster level storage configuration and selection
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "kworker1"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "sdb"
      config:         # configuration can be specified at the node level which overrides the cluster level config
        storeType: bluestore
    - name: "kworker2"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "sdb"
      config:         # configuration can be specified at the node level which overrides the cluster level config
```
```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 2
  dataPools:
    - erasureCoded:
       dataChunks: 2
       codingChunks: 1
  metadataServer:
    activeCount: 1
    activeStandby: true

```
This all works fine. However, once I try to install nfs-ganesha two things happen, (1) the nfs-ganesha pods crash, however, (2) later on the OSD pods crash.  Here is my ganesha config:

```
apiVersion: ceph.rook.io/v1
kind: CephNFS
metadata:
  # The name of Ganesha server cluster to create. It will be reflected in
  # the name(s) of the ganesha server pod(s)
  name: mynfs
  # The namespace of the Rook cluster where the Ganesha server cluster is
  # created.
  namespace: rook-ceph
spec:
  # NFS client recovery storage settings
  rados:
    # RADOS pool where NFS client recovery data and per-daemon configs are
    # stored. In this example the data pool for the "myfs" filesystem is used.
    # If using the object store example, the data pool would be
    # "my-store.rgw.buckets.data". Note that this has nothing to do with where
    # exported CephFS' or objectstores live.
    pool: myfs-data0
    # RADOS namespace where NFS client recovery data and per-daemon configs are
    # stored.
    namespace: ganesha-ns

  # Settings for the ganesha server
  server:
    # the number of active ganesha servers
    active: 2
```

**Comment by travisn** [comment]
@SeanChristopherConway How many OSDs do you have? With your erasure coding setting in the filesystem, you need at least 3 osds. From your settings in the cluster.yaml you may only have 2 osds. The `ceph status` from the rook toolbox would show for sure. Even so, I wouldn't think it would be related to the ganesha pods dying. Are there any logs for the failed ganesha pods? If so, @jtlayton could you take a look?

**Comment by SeanChristopherConway** [comment]
Okay, so after reading the docs again and realizing you are right about needing 3 osds I rebuilt the filesystem using 2 osds and things are working now with nfs-ganesha, I used:

 ```
dataPools:
    - failureDomain: host
      replicated:
        size: 2
```

Yet, despite running the erasure coding  setting with only 2 osds it didn't seem to crash the OSDs until the NFS ganesha servers came online. Anyhow, thanks!
