### ISSUE TITLE
OSD fails in minikube

### ISSUE THREAD

**Issue by itmuckel** [rook/rook#3127]
**Is this a bug report or feature request?**
* Bug Report

I have two servers, a master and a slave and want to have replicated storage for kubernetes. To test rook-ceph I use minikube.

More specific I want ceph to use a specific directory on each server to store the data.

**Deviation from expected behavior:**
The osd logs:
```
$ kubectl -n rook-ceph logs rook-ceph-osd-0-754b6797fc-tnz9g
2019-05-07 12:20:57.668 7fe24fa50d80 -1 Falling back to public interface
2019-05-07 12:20:57.961 7fe24fa50d80 -1 journal FileJournal::_open: disabling aio for non-block journal.  Use journal_force_aio to force use of aio anyway
2019-05-07 12:20:57.961 7fe24fa50d80 -1 journal do_read_entry(2105344): bad header magic
2019-05-07 12:20:57.961 7fe24fa50d80 -1 journal do_read_entry(2105344): bad header magic
2019-05-07 12:20:58.157 7fe24fa50d80 -1 osd.0 10 log_to_monitors {default=true}
2019-05-07 12:20:59.215 7fe2422e6700 -1 osd.0 10 set_numa_affinity unable to identify public interface 'eth0' numa node: (2) No such file or directory
```
Also the operator is in status "CrashLoopBackOff".

Using ceph tools I get:

```
[root@minikube /]# ceph status
  cluster:
    id:     e831d351-7af1-4a7d-b260-d62e3d91a8b9
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 6m)
    mgr: a(active, since 36m)
    osd: 1 osds: 1 up (since 35m), 1 in (since 37m)
 
  data:
    pools:   1 pools, 100 pgs
    objects: 0 objects, 0 B
    usage:   9.4 GiB used, 7.5 GiB / 17 GiB avail
    pgs:     100 active+clean
```

**Expected behavior:**

The OSD starts and I can set up a StorageClass in order to use PVCs. I expect that the data I save in my containers ends up in `/data/rook-dir/`.

**How to reproduce it (minimal and precise):**
I followed the steps in https://rook.io/docs/rook/v1.0/ceph-examples.html and used the following cluster.yml:
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.1-20190430
    allowUnsupported: false
  dataDirHostPath: /data/rook
  mon:
    count: 3
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  network:
    hostNetwork: false
  storage:
    useAllNodes: true
    useAllDevices: false
    config:
      osdsPerDevice: "1"
    directories:
    - path: /var/lib/rook
    nodes:
    - name: "minikube"
      directories:
      - path: "/data/rook-dir"
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS
* Kernel (e.g. `uname -a`): 4.15.0-48-generic
* Cloud provider or hardware configuration: 
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.0.0-13.g05b0166
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): minikube 1.0.0
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): Like above
