### ISSUE TITLE
Edits to CephFilesystem pools replicated size are ignored

### ISSUE THREAD

**Issue by areed** [rook/rook#3144]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Changing the metadataPool and dataPools replicated size from 1 to 2 has no effect.

**Expected behavior:**
After editing the CephFilesystem config the dashboard should show the new replica size for the pools, like it does when editing the replicated size of a CephBlockPool.

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release): 18.04.2 LTS
* Kernel (e.g. `uname -a`): Linux areed-aka-8tw9 4.15.0-1030-gcp #32-Ubuntu SMP Wed Apr 10 10:27:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: GCP
* Rook version (use `rook version` inside of a Rook Pod): v1.0.0
* Kubernetes version (use `kubectl version`): v1.13.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): Health OK

**Comment by rajatsingh25aug** [comment]
@areed can you please tell where exactly in the YAML you tried to change the replicated count?.
Or if you were trying to make changes via UI, please provide the steps.
Thanks!.

**Comment by areed** [comment]
I changed both `dataPools[0].replicated.size` and `metadataPool.replicated.size` from 1 to 2 in this config:
```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: rook-shared-fs
  namespace: rook-ceph
spec:
  dataPools:
  - crushRoot: ""
    erasureCoded:
      algorithm: ""
      codingChunks: 0
      dataChunks: 0
    failureDomain: ""
    replicated:
      size: 1
  metadataPool:
    crushRoot: ""
    erasureCoded:
      algorithm: ""
      codingChunks: 0
      dataChunks: 0
    failureDomain: ""
    replicated:
      size: 1
  metadataServer:
    activeCount: 1
    activeStandby: true
    placement: {}
    resources: {}
```
