### ISSUE TITLE
Create Client CRD

### ISSUE THREAD

**Issue by invidian** [rook/rook#3175]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

It should be possible to create new `CephClient` resource, which will [create ceph cluster user](http://docs.ceph.com/docs/mimic/rados/operations/user-management/#add-a-user) with capabilities (`caps`) specified in specification (`spec`) section of the resource. Once operator detects such resource, it should create user in ceph cluster and store it's key/keyring as a secret, which then can be mounted by the client.

When resource is removed, secret should be removed as well.

Example resource:
```
apiVersion: ceph.rook.io/v1beta1
kind: CephClient
metadata:
  name: example
  namespace: rook-ceph
spec:
  caps:
    mon: 'allow r'
    osd: 'allow rw pool=liverpool'
    mds: 'allow r'
```

It might be, that multiple secret types will be needed to make using it for client easier. Then additional parameter needs to be added to `spec`.

**What is use case behind this feature:**

Currently deploying CSI requires [manual step](https://github.com/rook/rook/blob/master/Documentation/ceph-csi-drivers.md#create-rbd-secret) of creating secrets which will be used by RBD storage class. We should automate that to provide fully automated deployment process for users. This will also simplify e2e testing.

Additionally, there are use cases, where Ceph Rados pools are used directly with librados, rather than with RadosGW/S3 protocol. Currently there is no way to manage credentials for such users (which might be a blocker from migrating to Ceph deployments to Kubernetes).

**Comment by travisn** [comment]
@invidian There is a work item in progress for automating the [mon endpoints for the csi driver](https://github.com/rook/rook/issues/2649), including dealing with the ceph clients and secrets. It is expected that the admin should not need to deal with the cephx users. All of this should be handled by the CSI driver. And if we need a migration tool, we should be able to integrate it with the CSI driver as well so it hides these details from the admin. If the CSI driver is automated, do you still see a need for this CRD?

**Comment by invidian** [comment]
> If the CSI driver is automated, do you still see a need for this CRD?

For my particular use case, I will not need it when CSI is automated.

However, I know people who may need it and if any project which uses librados (like https://github.com/ceph-dovecot/dovecot-ceph-plugin) wants to run on Kubernetes with Rook, then they would also need it, or at least benefit from it (secrets can be created by hand, but this is not the optimal way). Please let me know what you think about this idea.

@travisn do you have any rough ETA for CSI automation?

I'm considering implementing it anyway, even if it not make it into upstream, since then my implementation don't need to be "production grade", I learn a bit how Kubernetes Operators works internally and I can continue my work.

**Comment by travisn** [comment]
@invidian The CSI automation is planned in the 1.1 release, so the work is currently starting since 1.0 was released. Also related is the [external cluster](https://github.com/rook/rook/blob/master/design/ceph-external-cluster.md) feature, which will improve the experience around CSI connecting to a Ceph cluster that is running outside the local K8s cluster.

**Comment by invidian** [comment]
Ah, I forgot about this issue. I have implemented a POC which I use for my deployment and it's working as expected if anyone is interested. You can find it here: https://github.com/rook/rook/compare/release-1.0...invidian:client-crd?expand=1

Then you deploy it with:
```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephclients.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephClient
    listKind: CephClientList
    plural: cephclients
    singular: cephclient
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            caps:
              properties:
                mon:
                  type: string
                osd:
                  type: string
                mds:
                  type: string
---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: kubernetes-{{ .Values.poolName }}
spec:
  caps:
    mon: 'allow profile rbd'
    osd: 'profile rbd pool=rbd-{{ .Values.poolName }}'
    mds: 'allow rw'
---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: admin-{{ .Values.poolName }}
spec:
  caps:
    mon: 'allow *'
    osd: 'allow *'
    mds: 'allow *
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rbd-{{ .Values.poolName }}
spec:
  failureDomain: host
  replicated:
    size: {{ .Values.replicationFactor }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-rbd-{{ .Values.poolName }}
provisioner: rbd.csi.ceph.com
parameters:
    # Comma separated list of Ceph monitors
    # if using FQDN, make sure csi plugin's dns policy is appropriate.
    # TODO make it configurable and automated
    monitors: rook-ceph-mon-a:6789,rook-ceph-mon-b:6789,rook-ceph-mon-a:6789

    # if "monitors" parameter is not set, driver to get monitors from same
    # secret as admin/user credentials. "monValueFromSecret" provides the
    # key in the secret whose value is the mons
    #monValueFromSecret: "monitors"

    # Ceph pool into which the RBD image shall be created
    pool: rbd-{{ .Values.poolName }}

    # RBD image format. Defaults to "2".
    imageFormat: "2"

    # RBD image features. Available for imageFormat: "2". CSI RBD currently supports only `layering` feature.
    imageFeatures: layering

    # The secrets have to contain Ceph admin credentials.
    csi.storage.k8s.io/provisioner-secret-name: admin-{{ .Values.poolName }}-client-key
    csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
    csi.storage.k8s.io/node-publish-secret-name: kubernetes-{{ .Values.poolName }}-client-key
    csi.storage.k8s.io/node-publish-secret-namespace: {{ .Release.Namespace }}

    # Ceph users for operating RBD
    adminid: admin-{{ .Values.poolName }}
    userid: kubernetes-{{ .Values.poolName }}
    # uncomment the following to use rbd-nbd as mounter on supported nodes
    #mounter: rbd-nbd
reclaimPolicy: Delete
```
