### ISSUE TITLE
CephCluster: storage.nodes.devices.name: Make the `/` optional

### ISSUE THREAD

**Issue by jjasghar** [rook/rook#3183]
It seems that the `/` is not required. Unfortunately, this requires the use like:

```yml
storage:
    useAllNodes: false
    useAllDevices: true
    nodes:
      - name: kub1
        devices:
        - name: "dev/loop6"
      - name: kub2
        devices:
        - name: "dev/loop6"
```

People will put `/dev/loop6` instead of `dev/loop6`. We need to either add a note in the Documentation or make it optional for the UX in attempting to locate the Ceph mount points.
