### ISSUE TITLE
 skipping device loop0: Failed to complete 'lsblk /dev/loop0': exit status 1.

### ISSUE THREAD

**Issue by solohin** [rook/rook#3190]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
PVC is not provisioning

**Expected behavior:**
PVC provisioning

**How to reproduce it (minimal and precise):**

create a new rke cluster o clean ubuntu 18.04
```yml
nodes:
-- 3 nodes here
services:
  kubelet:
    extra_args:
      volume-plugin-dir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
    extra_binds:
      - /usr/libexec/kubernetes/kubelet-plugins/volume/exec:/usr/libexec/kubernetes/kubelet-plugins/volume/exec
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
```

Apply demo configs
```
cd cluster/examples/kubernetes/ceph
kubectl create -f common.yaml
kubectl create -f operator.yaml
kubectl create -f cluster.yaml
cd ../
kubectl create -f storageclass.yaml
kubectl create -f mysql.yaml
```

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
* Kernel (e.g. `uname -a`):
Linux rook-1 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
Bare metal (hetzner vms)
* Rook version (use `rook version` inside of a Rook Pod):
 rook: v1.0.1
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
rke
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
[root@rook-2 /]# ceph status
  cluster:
    id:     cbef2087-a161-43d5-933b-b0161f69b62d
    health: HEALTH_WARN
            Reduced data availability: 100 pgs inactive
 
  services:
    mon: 3 daemons, quorum a,b,c (age 21h)
    mgr: a(active, since 12h)
    osd: 0 osds: 0 up, 0 in
 
  data:
    pools:   1 pools, 100 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             100 unknown
```
