### ISSUE TITLE
rook-ceph-mgr: Prometheus-Annotations in wrong place

### ISSUE THREAD

**Issue by strowi** [rook/rook#3204]
* Bug Report

**Deviation from expected behavior:**
Default Configuration puts prometheus annotations at the deployment-leve of the rook-ceph-mgr pod, which won't get picked up by "default" prometheus-config.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    ...
    prometheus.io/port: "9283"
    prometheus.io/scrape: "true"
...
```

**Expected behavior:**
Annotation should be either in the pod-template or at the service-level for prometheus to scrape all the pods or only the service.

**How to reproduce it (minimal and precise):**
- deploy prometheus with example-config from https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus- kubernetes.yml
- deploy default rook-v1.0.1
- prometheus wont scrape rook-ceph-mgr

**Environment**:
* Cloud provider or hardware configuration: bare-metal
* Rook version (use `rook version` inside of a Rook Pod): v1.0.1
* Kubernetes version (use `kubectl version`): 1.13.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

regards,
Roman
