### ISSUE TITLE
rook ceph  Wal device cannot be created

### ISSUE THREAD

**Issue by menkeyi** [rook/rook#3215]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

My cluster configuration file:
```yaml
[root@k8s-master ceph]# egrep -v "^#|^$|*#" cluster.yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.1-20190430
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  annotations:
  resources:
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    location:
    config:
      storeType: bluestore
    nodes:
    - name: "k8s-master"
      devices:
      - name: "sdc"
      - name: "sdb"
      config:
        metadataDevice: "sdd"
        databaseSizeMB: "10240"
        WalSizeMB: "10240"
    - name: "k8s-node1"
      devices:
      - name: "sdd"
      - name: "sdc"
      config:
        metadataDevice: "sdd"
        databaseSizeMB: "10240"
        WalSizeMB: "10240"
    - name: "k8s-node2"
      devices:
      - name: "sdb"
      - name: "sdc"
      config:
        metadataDevice: "sdd"
        databaseSizeMB: "10240"
        WalSizeMB: "10240"
```
```
[root@k8s-master ceph]# kubectl logs rook-ceph-osd-prepare-k8s-master-tdj5g  -n rook-ceph provision
........................
2019-05-22 13:53:21.726226 I | rookcmd: flag values: --cluster-id=852b9288-7c98-11e9-8ed6-0050569ce87d, --data-device-filter=, --data-devies=sdc, --data-directories=, --encrypted-device=false, --force-format=false, --help=false, --location=, --log-flush-frequency=5s, --log-leel=INFO, --metadata-device=sdd, --node-name=k8s-master, --osd-database-size=20480, --osd-journal-size=5120, --osd-store=bluestore, --osd-wl-size=576, --osds-per-device=1
............................
```

Enter the OSD container to view,  Wal device is not on SSD  Why?
```
[root@k8s-master ceph]# kubectl exec -it rook-ceph-osd-0-759d69bd5-wdxhr bash  -n rook-ceph
[root@rook-ceph-osd-0-759d69bd5-wdxhr /]# ll  /var/lib/ceph/osd/ceph-0/
total 28
lrwxrwxrwx 1 ceph ceph  99 May 22 13:53 block -> /dev/ceph-block-5c7224e0-37a0-4a14-b454-f1df9f83b2fc/osd-block-d15ae7a0-e46b-4d88-9003-e3efd442b7a2
lrwxrwxrwx 1 ceph ceph 106 May 22 13:53 block.db -> /dev/ceph-block-dbs-05c8ea06-e83a-4c28-a871-502a4b7e0f95/osd-block-db-3035f1c1-e982-479b-9c92-66c78fbd5769
-rw------- 1 ceph ceph  37 May 22 13:53 ceph_fsid
-rw------- 1 ceph ceph  37 May 22 13:53 fsid
-rw------- 1 ceph ceph  55 May 22 13:53 keyring
-rw------- 1 ceph ceph   6 May 22 13:53 ready
-rw-r--r-- 1 root root   3 May 22 13:53 require_osd_release
-rw------- 1 ceph ceph  10 May 22 13:53 type
-rw------- 1 ceph ceph   2 May 22 13:53 whoami
```
