### ISSUE TITLE
ceph: add client users via CRD

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#3260]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
It is possible to create users for object stores. We should be able to do the same for arbitrary Ceph clients. Users should be configured at least with name and permissions.

e.g., 
```yaml
clientName: client.cinder # or just 'cinder'
permissions:  mon 'profile rbd' osd 'profile rbd pool=volumes, profile rbd pool=vms, profile rbd pool=images'
```

I'm not sure what critical client configs I might be missing. @leseb may have thoughts here. We could also specify the permissions by map as below. I'm not sure if that would be better or not. We also have the option to enforce only `mon`, `osd`, `mgr`, etc. as keys, or we could accept arbitrary keys.
```yaml
mon: 'profile rbd'
osd: 'profile rbd pool=volumes, profile rbd pool=vms, profile rbd pool=images'
arbitraryKey: '???'
```

We could also discuss not specifying permissions directly but allowing osd access by giving profile and pool to allow. I'm certainly not the best person to decide the best way forward here.
e.g.,
```yaml
name: client.cinder
pools:
  - name: volumes
    profile: rbd
  - name: vms
    profile rbd
  - name: images
    profile: rbd
```
(I do realize that specifying profile is unnecessary for common pool names like these for openstack, but we would need to allow it as an option)

We may also want to store the key into a secret and provide a CRD parameter reporting the secret name and key where the key can be found.

**What is use case behind this feature:**
The primary use case I have in mind for this feature is for users who intend to use Rook's Ceph cluster for OpenStack. OpenStack users need to create clients for nova, glance, and/or cinder (and maybe others), and giving them a way to do so declaratively by CRD would be a huge boon to them.
