### ISSUE TITLE
Deploy ceph alerting rules post ceph cluster creation

### ISSUE THREAD

**Issue by shtripat** [rook/rook#3294]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Post creation of ceph cluster, Rook should deploy the ceph alerting rules. The steps required for the same would be as below
* Enable monitoring for namespace in which Ceph is deployed (e.g. openshift-storage)
  oc label namespace openshift-storage openshift.io/cluster-monitoring=true
  oc policy add-role-to-user view system:serviceaccount:openshift-monitoring:prometheus-k8s -n openshift-storage
* Create service monitor with ceph's namespace
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: rook
  name: rook-ceph-mgr
  namespace: openshift-storage
spec:
  endpoints:
  - interval: 5s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - openshift-storage
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: openshift-storage
```
* Deploy the ceph alerting rule file

**What is use case behind this feature:**
Alerting for ceph cluster

**Environment**:

**Comment by travisn** [comment]
Here are a few thoughts on how this might be done. Since the metrics are part of the ceph-mgr, I would recommend doing this as part of the mgr orchestrator. The rules would only be created if a new setting in the CR indicates they should be installed. This setting also sets the expectation that prometheus is already installed and there is **no need** for the operator to attempt to retry until the prometheus types exist. 
1. Add new code at the end of the [`Start()`](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/mgr/mgr.go#L102) method for the mgr that will perform the following steps. If any of the steps fail, let's log an error, but not return an error (which would fail the orchestration and cause more significant issues).
1. Create the `ServiceMonitor` resource in the same namespace as the ceph cluster
1. Create the [alerts](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-rules.yaml). By default, the alerts would be created in the same namespace. If the alerts need to be created in another namespace, we will have a setting in the CR that defines in which namespace to install them.

### cluster.yaml
 Add the settings to the cluster.yaml. The default would be `false` since prometheus isn't installed for all users.
```yaml
spec:
  monitoring:
    # whether to create the prometheus rules, which requires the prometheus operator to be configured
    createRules: true
    # an empty namespace indicates to install in the same namespace
    rulesNamespace:
```

### ClusterSpec
- Add the type to the [ClusterSpec](https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1/types.go#L50)
```
type ClusterSpec struct {
...
	// A spec for monitoring related options
	Monitoring MonitoringSpec `json:"monitoring"`
}
type MonitoringSpec struct {
	// Whether to create the prometheus rules for the ceph cluster. If true, the prometheus
	// types must exist or the creation will fail.
	CreateRules bool `json:"createRules,omitempty"`

	// The namespace where the prometheus rules and alerts should be created.
	// If empty, the same namespace as the cluster will be used.
	RulesNamespace string `json:"rulesNamespace,omitempty"`
}
```

### RBAC
We will need to give the operator permissions to create the prometheus rules and service monitor, including in other namespaces. Let's update the existing RBAC rules in [common.yaml](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/common.yaml) with the needed privileges.
