### ISSUE TITLE
After few reinstalls OSD does not appear anymore, and nothing in the logs

### ISSUE THREAD

**Issue by michaelcourcy** [rook/rook#3308]
**Is this a bug report or feature request?**
Bug Report

**Deviation from expected behavior:**
If OSD does not appear anymore I should have at least a log message from the operator explaining why it can't start the osd 

**Expected behavior:**
Having a log message from the operator, at least an error message explaining why he was unable to start the osds 

**How to reproduce it (minimal and precise):**

I install a cluster with rook 1.0.8 but dues to anomalies I reinstall with 1.0.0 and I fisrt got all the OSDs defined in cluster.yml file up and running. But other bugs arised (unable to mount a pv) and I delete it again. Every times I followed the [tear down guide](https://github.com/rook/rook/blob/master/Documentation/ceph-teardown.md). 

But now mon and mgr will start but never the OSDs and I got no error message in any logs (neither from the monitor or the agent, or from the event). The cephcluster stay in creating state indefinitely.

```
[root@bastion-1-prod ~]# oc get cephcluster
NAME        DATADIRHOSTPATH   MONCOUNT   AGE       STATE      HEALTH
rook-ceph   /var/lib/rook     3          19m       Creating   
```

**Environment**:
* OS (e.g. from /etc/os-release): centos 7
* Kernel (e.g. `uname -a`): 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: vmware
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.0.0
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-04-22T23:30:51Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
  cluster:
    id:     e7eef4bc-9e6b-47cd-b237-5048df0dcb01
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,c,b
    mgr: a(active)
    osd: 0 osds: 0 up, 0 in
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0  objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:    
```
