### ISSUE TITLE
Cephfs: file will be cleared

### ISSUE THREAD

**Issue by ajax-2** [rook/rook#3535]
**Environment**:
* Rook version : 1.0.3
* Storage backend version : ceph
* Kubernetes version : v1.14.1
* Kubernetes cluster type : kubeadm
* Storage backend status : HEALTH OK
* Container : tomcat
* Install : common.yaml operator.yaml ,cluster.yaml, filesystem.yaml
* Mount method : 
```
      - name: image-store
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: myfs # name of the filesystem specified in the filesystem CRD.
            clusterNamespace: rook-ceph # namespace where the Rook cluster is deployed
```
** Details **
```
1, I run two containers(tomcat) of the same volume(cephfs)
2, I use "kubectl exec" to enter the container, then I copy a directory to the container (a), but another container(b) all files' size are 0, and all files' name is normal !
3, I restart all containers, then all files' size is 0 in all containers!
```

** Log & Picture **
1, I cannot get any log of the problem, and my pvc(kubernetes)'s mode is RWX
2, 
![image](https://user-images.githubusercontent.com/29370146/61944198-b453e980-afcf-11e9-8133-bff9593a74a8.png)

** Compared **
```
1, I run two containers again with nfs and everything is fine
```
