### ISSUE TITLE
Label selector for rook-ceph namespace

### ISSUE THREAD

**Issue by jansmets** [rook/rook#3542]
Hi
Could you please add a label selector for the rook-ceph namespace (common.yaml)

```
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    app: rook-ceph
```

Thanks
