### ISSUE TITLE
index.yaml needs updating in https://charts.rook.io/release/index.yaml

### ISSUE THREAD

**Issue by mjschmidt** [rook/rook#3544]
Please update the image link to a working link
```
apiVersion: v1
entries:
  rook-ceph:
  - apiVersion: v1
    created: 2019-07-12T21:10:37.232645608Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: 1337d2b0f47b7044c749ac4435a689ca61045e429d41fc6c92e24011338d906b
    icon: https://rook.io/images/logos/rook/rook-logo-color-on-transparent.png
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.0.4.tgz
    version: v1.0.4
  - apiVersion: v1
    created: 2019-07-12T21:10:37.231846652Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: 979991482ecb15638633cb1419c44e05c780fff36f7b33f4f537d4b1f3a3bc13
    icon: https://rook.io/images/logos/rook/rook-logo-color-on-transparent.png
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.0.3.tgz
    version: v1.0.3
  - apiVersion: v1
    created: 2019-07-12T21:10:37.231305248Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: d13ee2111d106f7770e9392d6a59416a0bf20ad4d3f7b699d3ed084157fdf7e1
    icon: https://rook.io/images/logos/rook/rook-logo-color-on-transparent.png
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.0.2.tgz
    version: v1.0.2
  - apiVersion: v1
    created: 2019-07-12T21:10:37.230266443Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: 174f4a609167535d952fb5f7fa4f75a4dc92ed923e1f905351f4d25aa3e94890
    icon: https://rook.io/images/logos/rook/rook-logo-color-on-transparent.png
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.0.1.tgz
    version: v1.0.1
  - apiVersion: v1
    created: 2019-07-12T21:10:37.227781852Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: 6f1c280b177e42c970e9593e20b2bdc7c2f191fdb532cb1b3e16db84c0100a6e
    icon: https://rook.io/images/logos/rook/rook-logo-color-on-transparent.png
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.0.0.tgz
    version: v1.0.0
generated: 2019-07-12T21:10:37.226332569Z
```
