### ISSUE TITLE
Wrong owner references cause problems with clean up of resources

### ISSUE THREAD

**Issue by surajssd** [rook/rook#3549]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When I create a certain CRD (`x`) which in return creates other objects (`y`) the `ownerReferences` of `y` should point to `x`. But rather it points to some other object.

So I created `CephObjectStoreUser` which creates a corresponding secret. So the secret's `ownerReferences` should pont to the `CephObjectStoreUser` user I created earlier it rather points to the object of type `CephCluster`.

So this causes problems when the CR of type `CephObjectStoreUser` is deleted this secrets stays there. Now when the object with same name is recreated the operator complains saying that the secret already exists.

**Expected behavior:**

The expected behavior is that the `secret` object should point to the `CephObjectStoreUser` in it's `ownerReferences`.

**How to reproduce it (minimal and precise):**

- Deploy rook-ceph
- Create a `CephObjectStoreUser` type object following steps in https://rook.io/docs/rook/v1.0/ceph-object.html

```console
$ kubectl get CephObjectStoreUser
NAME          AGE
object-user   2m48s
```

- Now check the corresponding secret created:

```yaml
$ kubectl get secret rook-ceph-object-user-object-store-object-user -o yaml
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2019-07-31T10:06:09Z"
  labels:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: object-store
    user: object-user
  name: rook-ceph-object-user-object-store-object-user
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    blockOwnerDeletion: true
    kind: CephCluster
    name: rook-ceph
    uid: d2975bfe-b363-11e9-875b-0cc47a5407e4
```

You can see that the `ownerReferences` in above is set to another object of type `CephCluster`.

The object looks like following:

```console
$ kubectl get cephcluster
NAME        DATADIRHOSTPATH   MONCOUNT   AGE    STATE     HEALTH
rook-ceph   /var/lib/rook     3          168m   Created   HEALTH_OK
```

**Environment**:

* Rook version (use `rook version` inside of a Rook Pod):

`rook: v1.0.4`

* Storage backend version (e.g. for ceph do `ceph -v`):

```console
# ceph -v
ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)
```

* Kubernetes version (use `kubectl version`):

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

Lokomotive

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

```console
# ceph health
HEALTH_OK
```
