### ISSUE TITLE
All Rook deployments/pods should use DNS to connect to mons

### ISSUE THREAD

**Issue by travisn** [rook/rook#355]
OSDs, MDS, and RGW should all use the internal k8s DNS to find the mons. This way we can failover the mons without the need to update the consumers. Note that the mons themselves cannot use dns as their identity relies on the ip address.

**Comment by kokhang** [comment]
The issue why addressing monitors via their domain name is not working is because there is a bug that prevents pods with `hostNetwork: true` to use the skydns on the resolv.conf. The kubernetes controller manager runs as a pod with hostNetwork and therefore the storage class volume plugin is not able to query the kube-dns server to resolve the monitor dns.

The workaround is either to supply a `cluster-dns` arg to kubelet so that it uses that as the nameserver.

There is a fix in docker and there is currently a PR on kubernetes to address this issue.
https://github.com/kubernetes/kubernetes/pull/29378

**Comment by bzub** [comment]
Some IPs can be replaced with DNS, for the MON daemons at least, using SRV records and a headless service.

I made this service:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-mons
  name: rook-mons
spec:
  ports:
  - name: ceph-mon
    port: 6790
    protocol: TCP
    targetPort: 6790
  selector:
    app: mon
    mon_cluster: rookcluster
  sessionAffinity: ClientIP
  clusterIP: None
  type: ClusterIP
```

And added `rook-mons.rook.svc.k8s.zbrbdl` this to the mon pod's `/etc/resolv.conf` (my cluster domain is k8s.zbrbdl where usually people use cluster.local I think):
```
$ kubectl -n rook exec mon0 -it sh                                                           ✓  2707  09:31:44 
/ # cat /etc/resolv.conf
search rook.svc.k8s.zbrbdl svc.k8s.zbrbdl k8s.zbrbdl default.svc.k8s.zbrbdl svc.k8s.zbrbdl default.cluster.local rook-mons.rook.svc.k8s.zbrbdl
nameserver 10.3.0.10
options ndots:5
```

And I get SRV records that are expected by mon daemons by default, possibly other ceph daemons/clients. (I confirmed you get SRV records in another container with `dig`)
```
$ kubectl -n rook exec mon0 -- nslookup _ceph-mon._tcp 

nslookup: can't resolve '(null)': Name does not resolve
Name:      _ceph-mon._tcp
Address 1: 10.2.247.20 mon0
Address 2: 10.2.136.146
Address 3: 10.2.6.18
```

So with that we'd just need an automated way to make sure the cluster domain is correct when that's added to resolv.conf.  I'll probably figure it out soon when I get a chance to look more.

Reference: http://docs.ceph.com/docs/master/rados/configuration/mon-lookup-dns/
