### ISSUE TITLE
Configure Default Memory Requests and Limits for rook-ceph namespace

### ISSUE THREAD

**Issue by jmolmo** [rook/rook#3590]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Set by default the values used for limiting/requesting memory/cpu use. In this way we set a safe default environment with the minimum requirements.

Using the LimitRange object in the common.yaml file this defaults can be easily set:

```
---
apiVersion: v1
kind: LimitRange
metadata:
 name: mem-limit-range
 namespace: rook-ceph
spec:
 limits:
 - default:
     memory: 4096M
   defaultRequest:
     memory: 1024M
   type: Container
---
```

The _spec. CheckMemoryPod_ function probably should be removed because the validation of the memory is solved by K8's using this approach.

Disadvantage: We cannot set specific default values for memory/cpu limits/request depending of the Pod functionality ( a mgr pod is "cheaper" in resources utlization  than a osd pod). This modification will force to use a common default value for all the containers,...and therefore for all the pods.

**Documentation**:
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/

**What is use case behind this feature:**
Avoid to specify/use limit/requested values for pods cpu/memory hardcoded. Let k8's API to do the validation of this values and check if it is possible to create pods using the specified values.
Avoid to implement specific functions to check pod resources ( sepc.CheckPodMemory).

**Environment**:
k8's cluster with mon,mgr,osds,rgw and mds pods. 
Once modified common.yaml to introduce the default values, use different cluster.crd definitions to test the creation of mon,mgr,osd,rgw and mds pods with/without setting for limiting/requesting memory iusage.

**Related to:**
Bug #3564  
PR #3581
