### ISSUE TITLE
NodeSelector in operator helm chart only sets nodeSelector for deployment

### ISSUE THREAD

**Issue by frelon** [rook/rook#3608]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:** 
When installing rook-operator using helm and setting nodeSelector in the values.yaml file in the following way

`helm install --name rook-ceph rook-release/rook-ceph --namespace storage -f values.yaml`

and the values.yaml as follows:

```yaml
image:
  prefix: rook
  repository: rook/ceph
  tag: master
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

rbacEnable: true
pspEnable: true

nodeSelector:
  kubernetes.io/os: linux
```

The nodeSelector is only set on rook-ceph-operator, not on daemonsets rook-ceph-agent, rook-discover, csi-rbdplugin and csi-cephfsplugin

**Expected behavior:**
The nodeSelector should be set on all applicable resources.

**How to reproduce it (minimal and precise):**

Install using helm and a nodeSelector that only selects one node.

The Node Selector tab when running `kubectl get daemonsets` will be empty.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: 
* Rook version (use `rook version` inside of a Rook Pod): v1.0.0-361.ge6da8ab
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)
* Kubernetes version (use `kubectl version`):  1.14.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
