### ISSUE TITLE
minio support nas gateway

### ISSUE THREAD

**Issue by phantooom** [rook/rook#3629]
i want support minio nas gateway.

there are 2 way define crd.
1. user define pvc we only mount pvc to data path.
```
apiVersion: minio.rook.io/v1alpha1
kind: ObjectStore
metadata:
  name: my-store
  namespace: rook-minio
spec:
  mode: nasGateWay
  scope:
    nodeCount: 4
  persistentVolumeClaim:
    claimName:  minio-data
```
2. user only provide nfs info

```
apiVersion: minio.rook.io/v1alpha1
kind: ObjectStore
metadata:
  name: my-store
  namespace: rook-minio
spec:
  mode: nasGateWay
  scope:
    nodeCount: 4
  nfs:
    path: /data/minio
    server:  1.1.1.1
```

 Which do you prefer?
