### ISSUE TITLE
OSD on PV breaks topologyAware

### ISSUE THREAD

**Issue by mmgaggle** [rook/rook#3632]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

If toplogyAware is set to true in the cluster-on-pvc.yaml example, kubernetes topology information is not reflected in the crush map.

**Expected behavior:**

If toplogyAware is set to true in the cluster-on-pvc.yaml example, kubernetes topology information should be reflected in the crush map.

Presumably we are attempting to move the named host bucket to the right zone bucket, but it doesn't exist because the name of the host bucket when using OSD backed by PVC is the PVC id. This is to ensure a stable crush  map if the pod+PVC moves to another instance. If we're using OSD on PV we need to pass ROOK_NODE_NAME here (I think):

https://github.com/rook/rook/blob/1bb8a5dcd90a2246ce6a3f37e8d60466e88ec2d6/pkg/operator/k8sutil/node.go#L255

**How to reproduce it (minimal and precise):**

Set topologyAware to true in cluster-on-pvc.yaml, then from toolbox pod run

```
ceph osd tree
```

**File(s) to submit**:

* Cluster CR
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.2-20190722
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  monitoring:
    enabled: false
    rulesNamespace: rook-ceph
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  annotations:
  resources:
  storage:
    topologyAware: true
    storageClassDeviceSets:
    - name: set1
      count: 3
      resources:
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 1000Gi
          storageClassName: gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce            
```

Example output from toolbox pod:
```
sh-4.2# ceph osd tree
ID CLASS WEIGHT  TYPE NAME                  STATUS REWEIGHT PRI-AFF
-1       2.92676 root default
-7       0.97559     host set1-0-data-5hnlz
 1   hdd 0.97559         osd.1                  up  1.00000 1.00000
-5       0.97559     host set1-1-data-cb8jn
 2   hdd 0.97559         osd.2                  up  1.00000 1.00000
-3       0.97559     host set1-2-data-qrhhj
 0   hdd 0.97559         osd.0                  up  1.00000 1.00000
```

Expected output
```
sh-4.2# ceph osd tree
ID  CLASS WEIGHT  TYPE NAME                  STATUS REWEIGHT PRI-AFF
-12       0.97559 zone us-west-2a
 -5       0.97559     host set1-1-data-cb8jn
  2   hdd 0.97559         osd.2                  up  1.00000 1.00000
-11       0.97559 zone us-west-2b
 -3       0.97559     host set1-2-data-qrhhj
  0   hdd 0.97559         osd.0                  up  1.00000 1.00000
-10       0.97559 zone us-west-2c
 -7       0.97559     host set1-0-data-5hnlz
  1   hdd 0.97559         osd.1                  up  1.00000 1.00000
 -1             0 root default
```

**Environment**:
* Cloud provider or hardware configuration:
AWS
* Rook version:
6a61286e4a353548525bf126bfd4152d7eebf3f1
* Storage backend version:
```ceph version 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)```
* Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+c62ce01", GitCommit:"c62ce01", GitTreeState:"clean", BuildDate:"2019-06-27T18:14:14Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
`OpenShift 4.1 (IPI)`
* Storage backend status
`HEALTH_OK`
