### ISSUE TITLE
[rook/nfs example]In pvc.yaml resources.resources.resources=1Mi，but in fact use all nfs server storage

### ISSUE THREAD

**Issue by tarjintor** [rook/rook#3636]
I use the nfs example 
It works but with a bug
when I enter busybox pod run 'df -h'
find
`10.110.169.40:/nfs-ceph-claim      1.9G      6.0M      1.9G   0% /mnt`
but in pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-nfs-pv-claim
spec:
  storageClassName: "rook-nfs-share1"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
```

it only request 1Mi storage
===================================
My guess is nfs not support request.storage,but I'm not sure

I also have some doubt

As my understanding,kubernetes design storage class and pvc to diffrent role to use, pvc is for developer and storage class is for operation Engineer
So I wish that I can only set up one nfs server,define one storage class
any developer want a pv can write a pvc yaml that request some storage

If two pod want share the pv, they use a same metadata.name of pvc.yaml，if not, they use diffrent names, and they can't see others's pv content.
===================================

But it seems nfs server can't do this
So if I wish make this happened, I can only create many nfs server that seprate from each other?

This is not elegant

================
Am I right?
