### ISSUE TITLE
[BUG]: All OSDs (in special node) failed after restart a node!

### ISSUE THREAD

**Issue by AliMD** [rook/rook#3640]
We are using Rook Ceph in production and need urgent support, Thanks in advance.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After restarting a node, all OSDs are failed (CrashLoopBackOff) and marked as down in Ceph. In other words, after restarting the nodes we lose the Ceph cluster!

**Expected behavior:**
OSDs should have a normal state after a restart.

**How to reproduce it (minimal and precise):**
* We Have [RancherOS](https://github.com/rancher/os) (A container-based OS) installed on 10 Bare-metal servers.
* We Installed Kubernetes with [RKE](https://github.com/rancher/rke)
* `kubectl apply -f 0-common.yaml` (With custom namespace)
* `kubectl apply -f 1-operator.yaml`
* `kubectl apply -f 2-rook-ceph-cluster.yaml`
* Wait for all OSDs created and check Ceph state and etc.
* `kubectl drain NODE_NAME --ignore-daemonsets --delete-local-data`
* After a while reboot the node.
* Wait for the node to get ready again
* `kubectl uncordon NODE_NAME`
* Check ODSs, all OSDs in this node are down!

Repeat this steps more than 5 times with different methods of restart and drain and etc. always the same issue

**File(s) to submit**:

* Cluster CR (custom resource)  
```YAML
apiVersion: ceph.rook.io/v1
kind: CephCluster

metadata:
  name: xxx-storage-cluster
  namespace: xxx-storage

spec:
  cephVersion:
    image: ceph/ceph:v14.2.2-20190722
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  monitoring:
    enabled: false
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: true
    deviceFilter: "^sd."
    config:
      storeType: bluestore
    location: region=xxx datacenter=xxx-xxx rack=01
    nodes:
      - name: node-name-1
        location: chassis=n01
      - name: node-name-2
        location: chassis=n02
      - name: node-name-3
        location: chassis=n03
      - name: node-name-4
        location: chassis=n04
```

* `1-operator.yaml` if needed

```YAML
apiVersion: apps/v1
kind: Deployment

metadata:
  name: rook-ceph-operator
  namespace: xxx-storage
  labels:
    operator: rook
    storage-backend: ceph

spec:
  selector:
    matchLabels:
      app: rook-ceph-operator

  replicas: 1

  template:
    metadata:
      labels:
        app: rook-ceph-operator

    spec:
      serviceAccountName: rook-ceph-system

      containers:
        - name: rook-ceph-operator
          image: rook/ceph:v1.0.5
          args: ["ceph", "operator"]
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /var/lib/rook
              name: rook-config
            - mountPath: /etc/ceph
              name: default-config-dir
          env:
            - name: ROOK_CURRENT_NAMESPACE_ONLY
              value: "true"
            - name: FLEXVOLUME_DIR_PATH
              value: "/usr/libexec/kubernetes/kubelet-plugins/volume/exec"
            - name: ROOK_ALLOW_MULTIPLE_FILESYSTEMS
              value: "false"
            - name: ROOK_LOG_LEVEL
              value: "INFO"
            - name: ROOK_CEPH_STATUS_CHECK_INTERVAL
              value: "60s"
            - name: ROOK_MON_HEALTHCHECK_INTERVAL
              value: "45s"
            - name: ROOK_MON_OUT_TIMEOUT
              value: "600s"
            - name: ROOK_DISCOVER_DEVICES_INTERVAL
              value: "60m"
            - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
              value: "false"
            - name: ROOK_ENABLE_SELINUX_RELABELING
              value: "true"
            - name: ROOK_ENABLE_FSGROUP
              value: "true"
            - name: ROOK_DISABLE_DEVICE_HOTPLUG
              value: "false"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: rook-config
          emptyDir: {}
        - name: default-config-dir
          emptyDir: {}

```

* Crashing pod(s) logs, if necessary
```
rookcmd: starting Rook v1.0.5 with arguments '/rook/rook ceph osd start -- --foreground --id 8 --osd-uuid fae8f98e-7403-4a1e-9cdf-7342b26efa18 --conf /var/lib/rook/osd8/xxx-storage.config --cluster ceph --default-log-to-file false --ms-learn-addr-from-peer=false'
rookcmd: flag values: --help=false, --log-flush-frequency=5s, --log-level=INFO, --osd-id=8, --osd-store-type=bluestore, --osd-uuid=fae8f98e-7403-4a1e-9cdf-7342b26efa18
op-mon: parsing mon endpoints: 
op-mon: ignoring invalid monitor 
exec: Running command: stdbuf -oL ceph-volume lvm activate --no-systemd --bluestore 8 fae8f98e-7403-4a1e-9cdf-7342b26efa18
Running command: /bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-8
Running command: /usr/sbin/restorecon /var/lib/ceph/osd/ceph-8
Running command: /bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-8
Running command: /bin/ceph-bluestore-tool --cluster=ceph prime-osd-dir --dev /dev/ceph-02524f21-2fa7-4e09-97dc-97adafd5591b/osd-data-9995e644-0b30-4187-b41d-64526dd56e02 --path /var/lib/ceph/osd/ceph-8 --no-mon-config
 stderr: failed to read label for /dev/ceph-02524f21-2fa7-4e09-97dc-97adafd5591b/osd-data-9995e644-0b30-4187-b41d-64526dd56e02: (2) No such file or directory
 stderr: 2019-08-17 10:21:32.418 7f8ddae0ff00 -1 bluestore(/dev/ceph-02524f21-2fa7-4e09-97dc-97adafd5591b/osd-data-9995e644-0b30-4187-b41d-64526dd56e02) _read_bdev_label failed to open /dev/ceph-02524f21-2fa7-4e09-97dc-97adafd5591b/osd-data-9995e644-0b30-4187-b41d-64526dd56e02: (2) No such file or directory
-->  RuntimeError: command returned non-zero exit status: 1
failed to activate osd. Failed to complete '': exit status 1. 
```

**Environment**:
* OS: RancherOS v1.5.2
* Kernel: 4.14.122-rancher
* Cloud provider or hardware configuration: Bare-metal RancherOS Cloud-Config (not important)
* Rook version: v1.0.5
* Storage backend version: ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)
* Kubernetes version: v1.15.0
* Kubernetes cluster type: Bare-metal
* Storage backend status: OSD_CHASSIS_DOWN: 1 chassis (11 osds) down

**Comment by AliMD** [comment]
This is not a duplicate issue, I double-check all related issue and it's different because all OSDs down every time I restart a node!
And we use container base os!

**Comment by AliMD** [comment]
My `1-operator.yaml` if needed

```YAML
apiVersion: apps/v1
kind: Deployment

metadata:
  name: rook-ceph-operator
  namespace: xxx-storage
  labels:
    operator: rook
    storage-backend: ceph

spec:
  selector:
    matchLabels:
      app: rook-ceph-operator

  replicas: 1

  template:
    metadata:
      labels:
        app: rook-ceph-operator

    spec:
      serviceAccountName: rook-ceph-system

      containers:
        - name: rook-ceph-operator
          image: rook/ceph:v1.0.5
          args: ["ceph", "operator"]
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /var/lib/rook
              name: rook-config
            - mountPath: /etc/ceph
              name: default-config-dir
          env:
            - name: ROOK_CURRENT_NAMESPACE_ONLY
              value: "true"
            - name: FLEXVOLUME_DIR_PATH
              value: "/usr/libexec/kubernetes/kubelet-plugins/volume/exec"
            - name: ROOK_ALLOW_MULTIPLE_FILESYSTEMS
              value: "false"
            - name: ROOK_LOG_LEVEL
              value: "INFO"
            - name: ROOK_CEPH_STATUS_CHECK_INTERVAL
              value: "60s"
            - name: ROOK_MON_HEALTHCHECK_INTERVAL
              value: "45s"
            - name: ROOK_MON_OUT_TIMEOUT
              value: "600s"
            - name: ROOK_DISCOVER_DEVICES_INTERVAL
              value: "60m"
            - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
              value: "false"
            - name: ROOK_ENABLE_SELINUX_RELABELING
              value: "true"
            - name: ROOK_ENABLE_FSGROUP
              value: "true"
            - name: ROOK_DISABLE_DEVICE_HOTPLUG
              value: "false"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: rook-config
          emptyDir: {}
        - name: default-config-dir
          emptyDir: {}

```
