### ISSUE TITLE
Further CRD Validation with Kubernetes 1.14

### ISSUE THREAD

**Issue by sebastian-philipp** [rook/rook#3660]
Yaml has an unfortunate property that different empty values have different meanings:

1. ```yaml
    spec:
      storage:
    ```
2. ```yaml
    spec:
      storage: null
    ```
3. ```yaml
    spec:
      storage: {}
    ```
4. ```yaml
    spec: {}
    ```

* 1 and 2 are identical.
* 3 will set `spec.storage` to the empty object
* 4 will omit the `storage` key altogether.

Before 1.14, there is no way to properly validate case 1 and 2. 1.14 adds a way to mark those keys as `nullable`. I'd recommend to not use case 1 and 2 in any examples or tests in the future and instead just make use of 3 or 4 as an alternative.

As we have existing yamls that make use of `null`, I cannot properly validate those in the CRDs, until Rook requires K8s 1.14. In the meantime, I removed validations where we're running into this problem:

---

```
CephCluster.spec.storage.nodes[].deviceFilter 
CephCluster.spec.storage.deviceFilter
```
can be validated as:
```
type: string
nullable: true
```

---

```
CephCluster.spec.storage.nodes[].devices[].config
CephCluster.spec.storage.config
```
can be validated as:
```
nullable: true
properties:
  metadataDevice:
    type: string
  storeType:
    type: string
    pattern: ^(filestore|bluestore)$
  databaseSizeMB:
    type: string
  walSizeMB:
    type: string
  journalSizeMB:
    type: string
  osdsPerDevice:
    type: string
  encryptedDevice:
    type: string
    pattern: ^(true|false)$
```

---

```
CephCluster.spec.storage.nodes[].location
```
can be validated as:
```
type: string
nullable: true
```

---

```
CephObjectStore.spec.gateway.sslCertificateRef
```
can be validated as:
```
nullable: true
type: string
```

---

```
CephObjectStore.spec.gateway.securePort
```
can be validated as:
```
nullable: true
type: integer
```

---

See also #3534
