### ISSUE TITLE
edgefs-system/rook-edgefs-cluster: serviceaccount "rook-edgefs-cluster" not found

### ISSUE THREAD

**Issue by cameronbraid** [rook/rook#3676]
* Bug Report

Cluster is unable to start due to the following error starting the host prepare job pod

```
Error creating: pods "host-prepare-node03-" is forbidden: error looking up service account rook-edgefs-system/rook-edgefs-cluster: serviceaccount "rook-edgefs-cluster" not found
```

Workaround that seems to work is

```kubectl -n rook-edgefs-system create serviceaccount rook-edgefs-cluster```

However does this service account also need to be bound to rook-edgefs-global ClusterRole ?

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```
apiVersion: edgefs.rook.io/v1beta1
kind: Cluster
metadata:
  name: rook-edgefs
  namespace: rook-edgefs-system
spec:
  serviceAccount: rook-edgefs-cluster
  dataDirHostPath: /media/data/edgefs/data-dir
  network: # cluster level networking configuration aka "host network"
   serverIfName: "enp0s8"
   brokerIfName: "enp0s8"
  storage:
    directories:
    - path: /media/data/edgefs/storage/1
    - path: /media/data/edgefs/storage/2
    - path: /media/data/edgefs/storage/3
    - path: /media/data/edgefs/storage/4
    useAllNodes: false
    useAllDevices: false
    config:
      useMetadataOffload: "true"
      useMetadataMask: "0xff"
      maxSizeGB: "50"
    nodes:
    - name: "node01"
    - name: "node02"
    - name: "node03"
```

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod):

```v1.0.5```

* Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

```rke```
