### ISSUE TITLE
Rook should look for node labels to customize which devices should be used for OSDs

### ISSUE THREAD

**Issue by zanhsieh** [rook/rook#3681]
Hi,

I tried to combine nodeAffinity and nodes.[*].devices together but without success:

https://github.com/rook/rook/blob/master/Documentation/ceph-cluster-crd.md#node-affinity
https://github.com/rook/rook/blob/master/Documentation/ceph-cluster-crd.md#storage-configuration-specific-devices

My scenario is, I built my k8s cluster with KOPS on AWS. I decided to create an instancegroup (ig) dedicated as storage purpose (e.g. ig name = storage-nodes) and use d2.xlarge in that group. Each d2.xlarge has 3 raw ephemeral SSD disks. I hope that rook-ceph will automatically provision all raw ephemeral drives for me once I add a new node to that ig.

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.2-20190722
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: true
  # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: true
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kops.k8s.io/instancegroup
              operator: In
              values:
              - storage-nodes
      tolerations:
      - key: storage-node
        operator: Exists
    mgr:
      nodeAffinity:
      tolerations:
    mon:
      nodeAffinity:
      tolerations:
    osd:
      nodeAffinity:
      tolerations:
  storage:
    useAllNodes: false
    useAllDevices: true
    nodes:
    - ???
```

Could somebody provide a working example please? Or please let me know that is not possible.

**Comment by mabushey** [comment]
I'm trying to do the same thing as you. Affinity/Tollerations are totally broke in Rook 1.1. 

```
  placement:
    all:
```

seems wrong. The K8s way is:
```
      affinity:
        nodeAffinity:
```

I can't tell what the comments are getting at with mgr, mon, and osd. I think you only want to set those if you want to override the values of `all`. I assume this is why it's called `all`.

**Comment by zanhsieh** [comment]
@mabushey 
Thank you. I will give a try today.

**Comment by mabushey** [comment]
@zanhsieh I was able to make some progress on this. Take a look at #4147. The 1.1.0 config is missing a bunch of extra affinity / toleration settings. 1.1.2 added this.

**Comment by umangachapagain** [comment]
```
    mgr:
      nodeAffinity:
      tolerations:
    mon:
      nodeAffinity:
      tolerations:
    osd:
      nodeAffinity:
      tolerations:
```
You should not have these empty specs when you are using `all`.
This should be used only when you need custom placement for each of the resources.

For using all devices on specific nodes, set 
```
 useAllNodes: false
 useAllDevices: true
```
and then use, https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L158-L159 to select specific nodes based on Node name and device filter.

@travisn Do we have a way to select a specific group of nodes?
