### ISSUE TITLE
CSI RBD Plugin can't connect to the monitors

### ISSUE THREAD

**Issue by melnik13** [rook/rook#3718]
**Bug Report**
Either I'm doing something wrong, or v1.0 has certain difficulties with the CSI drivers... :-(

**Expected behavior:**
CSI RBD Provisioner should provision an RBD

**Deviation from expected behavior:**
CSI RBD Provisioner doesn't provision an RBD

**How to reproduce it (minimal and precise):**
It seems that it's enough to follow the documentation when trying to set up the CSI RBD Provisioner. :-)

**Environment**:
* OS (e.g. from /etc/os-release):
`CentOS Linux release 7.6.1810 (Core)` on all the nodes
* Kernel (e.g. `uname -a`):
`Linux control.c13.tuchakube.tucha13.net 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` on all the nodes
* Cloud provider or hardware configuration:
Bare metal
* Rook version (use `rook version` inside of a Rook Pod):
`rook: v1.0.5`
* Storage backend version (e.g. for ceph do `ceph -v`):
`ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)`
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
  cluster:
    id:     fa08147f-bb7a-45e5-ac35-bb8aed98eecf
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 59m)
    mgr: a(active, since 59m)
    mds: cephfs:1 {0=cephfs-a=up:active} 1 up:standby-replay
    osd: 4 osds: 4 up (since 53m), 4 in (since 53m)

  data:
    pools:   3 pools, 300 pgs
    objects: 22 objects, 2.2 KiB
    usage:   4.0 GiB used, 392 GiB / 396 GiB avail
    pgs:     300 active+clean

  io:
    client:   852 B/s rd, 1 op/s rd, 0 op/s wr
```

**Detailed explaination**
Here's what I do.

First of all, I fetch the source:
```
git clone https://github.com/rook/rook.git ${HOME}/src/rook
git --git-dir=${HOME}/src/rook/.git --work-tree=${HOME}/src/rook checkout v1.0.5
```

Then I create the CRDs, roles and rolebindings:
```
kubectl apply -f ~/src/rook/cluster/examples/kubernetes/ceph/common.yaml
```

Then I add some RBAC rules for the CSI plugins:
```
kubectl apply -f ~/src/rook/cluster/examples/kubernetes/ceph/csi/rbac/rbd/
kubectl apply -f ~/src/rook/cluster/examples/kubernetes/ceph/csi/rbac/cephfs/
```

Then I deploy the operator:
```
kubectl apply -f ~/src/rook/cluster/examples/kubernetes/ceph/operator-with-csi.yaml
```

Then I create the `rook-ceph` cluster:
```
cat ~/src/rook/cluster/examples/kubernetes/ceph/cluster.yaml \
    | sed -r 's/^(    deviceFilter:)/\1 ^vdc/' \
    > ~/k8s-manifests/rook-ceph/cephcluster_rook-ceph.yaml
kubectl apply -f ~/k8s-manifests/rook-ceph/cephcluster_rook-ceph.yaml
```

Then I create the `rbd` pool:
```
kubectl apply -f ~/tuchakube/k8s-manifests/rook-ceph/cephblockpool-rbd.yaml
```

This manifest looks like that:
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rbd
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
```

Then I create a couple of storageclasses:
```
kubectl apply -f ~/k8s-manifests/rook-ceph/storageclass-csi-rbd.yaml
kubectl apply -f ~/k8s-manifests/rook-ceph/storageclass-csi-rbd-rpd.yaml
```

These manifest look like that:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-rbd
provisioner: rbd.csi.ceph.com
parameters:
    clusterID: rook-ceph
    pool: rbd
    imageFormat: "2"
    imageFeatures: layering
    csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
    csi.storage.k8s.io/provisioner-secret-namespace: default
    csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
    csi.storage.k8s.io/node-stage-secret-namespace: default
    adminid: admin
    userid: kubernetes
reclaimPolicy: Retain
```
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-rbd
provisioner: rbd.csi.ceph.com
parameters:
    clusterID: rook-ceph
    pool: rbd
    imageFormat: "2"
    imageFeatures: layering
    csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
    csi.storage.k8s.io/provisioner-secret-namespace: default
    csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
    csi.storage.k8s.io/node-stage-secret-namespace: default
    adminid: admin
    userid: kubernetes
reclaimPolicy: Delete
```

Then I create the secret for the CSI plugin:
```
AUTHKEY_ADMIN=$( \
    kubectl \
        exec $(kubectl -n rook-ceph get pod -l 'app=rook-ceph-operator' -o jsonpath='{.items[0].metadata.name}') \
        --namespace rook-ceph \
        --tty=false \
        --stdin=false \
        -- ceph auth get-key client.admin \
   | base64
)
kubectl \
    create secret generic csi-rbd-secret \
    --from-literal=admin=${AUTHKEY_ADMIN} \
```

And here I have certain doubts. In the `cluster/examples/kubernetes/ceph/csi/example/rbd/secret.yaml` example I see the following:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
data:
  # Key value corresponds to a user name defined in Ceph cluster
  admin: BASE64-ENCODED-PASSWORD
  # Key value corresponds to a user name defined in Ceph cluster
  kubernetes: BASE64-ENCODED-PASSWORD
  # if monValueFromSecret is set to "monitors", uncomment the
  # following and set the mon there
  #monitors: BASE64-ENCODED-Comma-Delimited-Mons
```

But I don't have the `kubernetes` user in my Ceph cluster, there are only these ones:
```
installed auth entries:

mds.cephfs-a
        key: ***REMOVED***
        caps: [mds] allow
        caps: [mon] allow profile mds
        caps: [osd] allow *
mds.cephfs-b
        key: ***REMOVED***
        caps: [mds] allow
        caps: [mon] allow profile mds
        caps: [osd] allow *
osd.0
        key: ***REMOVED***
        caps: [mgr] allow profile osd
        caps: [mon] allow profile osd
        caps: [osd] allow *
osd.1
        key: ***REMOVED***
        caps: [mgr] allow profile osd
        caps: [mon] allow profile osd
        caps: [osd] allow *
osd.2
        key: ***REMOVED***
        caps: [mgr] allow profile osd
        caps: [mon] allow profile osd
        caps: [osd] allow *
osd.3
        key: ***REMOVED***
        caps: [mgr] allow profile osd
        caps: [mon] allow profile osd
        caps: [osd] allow *
client.admin
        key: ***REMOVED***
        caps: [mds] allow *
        caps: [mgr] allow *
        caps: [mon] allow *
        caps: [osd] allow *
client.bootstrap-mds
        key: ***REMOVED***
        caps: [mon] allow profile bootstrap-mds
client.bootstrap-mgr
        key: ***REMOVED***
        caps: [mon] allow profile bootstrap-mgr
client.bootstrap-osd
        key: ***REMOVED***
        caps: [mon] allow profile bootstrap-osd
client.bootstrap-rbd
        key: ***REMOVED***
        caps: [mon] allow profile bootstrap-rbd
client.bootstrap-rbd-mirror
        key: ***REMOVED***
        caps: [mon] allow profile bootstrap-rbd-mirror
client.bootstrap-rgw
        key: ***REMOVED***
        caps: [mon] allow profile bootstrap-rgw
mgr.a
        key: ***REMOVED***
        caps: [mds] allow *
        caps: [mon] allow *
        caps: [osd] allow *
```

***SUB-ISSUE №1***
Should the operator have been created the `kubernetes` user? Or should I have done it by myself? I haven't found the answer to this question in the documentation.

But let's see what happens next when I create a PVC of the `csi-rbd` storageclass. It stays in the `Pending` state and Here's the part of the log-file of the `csi-rbdplugin` container in the `csi-rbdplugin-provisioner-0` pod:
```
I0828 11:43:38.970908       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0828 11:43:38.970923       1 utils.go:106] GRPC request: {"capacity_range":{"required_bytes":2147483648},"name":"pvc-2dbb5790-4268-4ea9-b37f-9dba0fa5f1aa","parameters":{"adminid":"admin","clusterID":"rook-ceph","imageFeatures":"layering","imageFormat":"2","pool":"rbd","userid":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}]}
I0828 11:43:38.975152       1 hashed.go:47] hashedKeyMutex.LockKey(...) called for id "pvc-2dbb5790-4268-4ea9-b37f-9dba0fa5f1aa"
I0828 11:43:38.975166       1 hashed.go:49] hashedKeyMutex.LockKey(...) for id "pvc-2dbb5790-4268-4ea9-b37f-9dba0fa5f1aa" completed.
E0828 11:43:38.975193       1 rbd_util.go:259] failed getting mons (error fetching configuration for cluster ID (rook-ceph). (open /etc/csi-config/ceph-cluster-rook-ceph/monitors: no such file or directory))
I0828 11:43:38.975200       1 hashed.go:54] hashedKeyMutex.UnlockKey(...) called for id "pvc-2dbb5790-4268-4ea9-b37f-9dba0fa5f1aa"
I0828 11:43:38.975205       1 hashed.go:56] hashedKeyMutex.UnlockKey(...) for id "pvc-2dbb5790-4268-4ea9-b37f-9dba0fa5f1aa" completed.
E0828 11:43:38.975210       1 utils.go:109] GRPC error: rpc error: code = InvalidArgument desc = failed to fetch monitor list using clusterID (rook-ceph)
```

***SUB-ISSUE №2***
Shouldn't the operator provide the list of monitors to the plugin? Or should the user provide the list of mons to the CSI plugin manually?

I have a feeling that I missed something important, but it seems that I'm performing all the steps I needed. Please, correct me if I'm wrong and it's not a bug.

Thanks!
