### ISSUE TITLE
Ceph status showing node name instead of PVC name in `ceph osd status` command

### ISSUE THREAD

**Issue by rohan47** [rook/rook#3728]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Not sure if this the expected behaviour or not.
When OSDs are based on PVCs and are portable, the exepected behaviour is to have host name as the name of the PVC.
when running `ceph osd status` command in the Rook ceph toolbox we get the following output
```
[root@worker0 /]# ceph osd status
+----+---------+-------+-------+--------+---------+--------+---------+-----------+
| id |   host  |  used | avail | wr ops | wr data | rd ops | rd data |   state   |
+----+---------+-------+-------+--------+---------+--------+---------+-----------+
| 0  | worker2 | 1028M | 8187M |    0   |     0   |    0   |     0   | exists,up |
| 1  | worker0 | 1028M | 8187M |    0   |     0   |    0   |     0   | exists,up |
| 2  | worker1 | 1028M | 8187M |    0   |     0   |    0   |     0   | exists,up |
| 3  | worker1 | 1028M | 8187M |    0   |     0   |    0   |     0   | exists,up |
| 4  | worker2 | 1028M | 8187M |    0   |     0   |    0   |     0   | exists,up |
| 5  | worker0 | 1028M | 8187M |    0   |     0   |    0   |     0   | exists,up |
| 6  | worker2 | 1028M | 8187M |    0   |     0   |    0   |     0   | exists,up |
| 8  | worker1 | 1028M | 8187M |    0   |     0   |    0   |     0   | exists,up |
+----+---------+-------+-------+--------+---------+--------+---------+-----------+
```
While running `ceph osd tree` command we have the name of the PVC as the host name in the following output
```
[root@worker0 /]# ceph osd tree
ID  CLASS WEIGHT  TYPE NAME                  STATUS REWEIGHT PRI-AFF
 -1       0.07031 root default
-11       0.00879     host set1-0-data-tcpm8
  0   hdd 0.00879         osd.0                  up  1.00000 1.00000
 -5       0.00879     host set1-1-data-s94mx
  4   hdd 0.00879         osd.4                  up  1.00000 1.00000
 -7       0.00879     host set1-2-data-cvrcc
  3   hdd 0.00879         osd.3                  up  1.00000 1.00000
 -9       0.00879     host set1-3-data-kddzq
  5   hdd 0.00879         osd.5                  up  1.00000 1.00000
-17       0.00879     host set1-4-data-hbvfv
  6   hdd 0.00879         osd.6                  up  1.00000 1.00000
 -3       0.00879     host set1-5-data-47jm9
  1   hdd 0.00879         osd.1                  up  1.00000 1.00000
-15       0.00879     host set1-6-data-7lpnn
  8   hdd 0.00879         osd.8                  up  1.00000 1.00000
-13       0.00879     host set1-8-data-2fcg6
  2   hdd 0.00879         osd.2                  up  1.00000 1.00000
```
Also in the ceph.conf we have pvc name as the host location
```
[root@rook-ceph-osd-0-7996fb8465-rpsnr /]# cat /etc/ceph/ceph.conf
[global]
fsid                      = 343ef4d7-3d95-485e-97b1-a56676e3a291
run dir                   = /var/lib/rook/osd0
mon initial members       = d e a
mon host                  = v1:10.97.155.105:6789,v1:10.106.80.49:6789,v1:10.108.166.0:6789
public addr               = 10.244.3.14
cluster addr              = 10.244.3.14
mon keyvaluedb            = rocksdb
mon_allow_pool_delete     = true
mon_max_pg_per_osd        = 1000
debug default             = 0
debug rados               = 0
debug mon                 = 0
debug osd                 = 0
debug bluestore           = 0
debug filestore           = 0
debug journal             = 0
debug leveldb             = 0
filestore_omap_backend    = rocksdb
osd pg bits               = 11
osd pgp bits              = 11
osd pool default size     = 1
osd pool default min size = 1
osd pool default pg num   = 100
osd pool default pgp num  = 100
osd objectstore           = filestore
crush location            = root=default host=set1-0-data-tcpm8
rbd_default_features      = 3
fatal signal handlers     = false

[osd.0]
keyring              = /var/lib/ceph/osd/ceph-0/keyring
bluestore block path = /var/lib/ceph/osd/ceph-0/block
```
**Expected behavior:**
In the output of `ceph osd status` command we should see pvc name as the host name

**How to reproduce it (minimal and precise):**

deploy cluster-on-pvc.yaml with `portable` property set as `true`
1. `kubectl create -f common.yaml`
2. `kubectl create -f operator.yaml`
3. `kubectl create -f cluster-on-pvc.yaml`

cluster-on-pvc.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    volumeClaimTemplate:
      spec:
        storageClassName: local-storage
        resources:
          requests:
            storage: 10Gi
  storage:
   storageClassDeviceSets:
    - name: set1
      count: 3
      portable: true
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 10Gi
          # IMPORTANT: Change the storage class depending on your environment (e.g. local-storage, gp2)
          storageClassName: local-storage
          volumeMode: Block
          accessModes:
            - ReadWriteOnce

```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): 
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): master
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubernetes
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTHY
