### ISSUE TITLE
ceph: mgr pod fails scheduling

### ISSUE THREAD

**Issue by kshlm** [rook/rook#3740]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavio

r:**

When a CephCluster is created with following placement config for the mgr pods (full cluster manifest is attached below), the ceph-mgr fails to get scheduled.

```yaml
    mgr:    
      podAntiAffinity:    
        requiredDuringSchedulingIgnoredDuringExecution:    
        - labelSelector:    
            matchExpressions:    
            - key: app    
              operator: In    
              values:    
              - rook-ceph-mgr    
          topologyKey: "" 
```

The operator logs the failure as,
```
2019-08-30 15:55:18.142454 E | op-cluster: failed to create cluster in namespace openshift-storage. failed to start the ceph mgr. failed to create mgr deployment rook-ceph-mgr-a. Deployment.apps "rook-ceph-mgr-a" is invalid: [spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Required value: can not be empty, spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Invalid value: "": name part must be non-empty, spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Invalid value: "": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')]
```

**Expected behavior:**

The mgr pod should be scheduled.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

[cluster.yaml.txt](https://github.com/rook/rook/files/3560670/cluster.yaml.txt)

* Operator's logs, if necessary

[operator-logs.log](https://github.com/rook/rook/files/3560672/operator-logs.log)

* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
