### ISSUE TITLE
Unable to deploy CephFilesystem

### ISSUE THREAD

**Issue by Ludea** [rook/rook#3845]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
CephFilesystem is not created.
There are no pod with `kubectl -n rook-ceph get pod -l app=rook-ceph-mds`
**Expected behavior:**
pods like : rook-ceph-mds-myfs-...

**How to reproduce it (minimal and precise):**

deploy Rook by helm chart 
Create ceph cluster as
```apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # For the latest ceph images, see https://hub.docker.com/r/ceph/ceph/tags
    image: ceph/ceph:v14.2.3-20190904
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
  dashboard:
    enabled: true
  storage:
    useAllNodes: true
    useAllDevices: false
    # Important: Directories should only be used in pre-production environments
    directories:
    - path: /var/lib/rook
```

Create CephFileSytem as 
```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - replicated:
        size: 3
  metadataServer:
    activeCount: 1
    activeStandby: true
```
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
 ```
6 reflector.go:126] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot list resource "deployments" in API group "apps" at the cluster scope
```
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04
* Kernel (e.g. `uname -a`): Linux 4.15.0-62-generic
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.1.0
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 1.15.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): on prem
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
