### ISSUE TITLE
Failed to update mds deployment after cephfilesystem delete/add

### ISSUE THREAD

**Issue by stephan2012** [rook/rook#3854]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rook does not recreate CephFS when it has been deleted and added again

**Expected behavior:**
Rook creates CephFS 

**How to reproduce it (minimal and precise):**

1. Setup Rook Operator
2. Setup Ceph cluster via Rook
3. Request `cephfilesystem`:

```yaml
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: cephfs
  namespace: rook-ceph
spec:
  dataPools:
  - failureDomain: host
    replicated:
      size: 2
  metadataPool:
    crushDeviceClass: ssd
    deviceClass: ssd
    failureDomain: host
    replicated:
      size: 2
  metadataServer:
    activeCount: 1
    activeStandby: true
    placement:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-mds
          topologyKey: kubernetes.io/hostname
```

4. Delete `cephfs` object and wait for the Rook Operator to finish decommissioning the CephFS
5. Recreate the `cephfs` CRD
6. The operator fails with
```
2019-09-15 14:24:57.682881 E | op-file: failed to create filesystem cephfs: failed to update mds deployment rook-ceph-mds-cephfs-a. failed to get deployment rook-ceph-mds-cephfs-a. deployments.apps "rook-ceph-mds-cephfs-a" not found
```

7. No further activity. Kill the operator Pod and wait for it to resume its work.
8. Now the operator adds the Deployment for MDS A but fails for MDS B:
```
2019-09-15 14:27:30.431316 E | op-file: failed to create filesystem cephfs: failed to update mds deployment rook-ceph-mds-cephfs-b. failed to get deployment rook-ceph-mds-cephfs-b. deployments.apps "rook-ceph-mds-cephfs-b" not found
```

After another restart, booth MDS instances are finally up.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): 18.04.3 LTS (Bionic Beaver)
* Kernel (e.g. `uname -a`): `Linux master1.lab.dallmeier.de 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Virtual Machines, K8s setup via kubeadm
* Rook version (use `rook version` inside of a Rook Pod): v1.1.0
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.3 (0f776cf838a1ae3130b2b73dc26be9c95c6ccc39) nautilus (stable)`
* Kubernetes version (use `kubectl version`): 1.15.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
# ceph health
HEALTH_WARN too few PGs per OSD (10 < min 30)
```
