### ISSUE TITLE
Cannot remove disk by editing cephcluster rook-ceph in Rook v1.1.0

### ISSUE THREAD

**Issue by junhuihuang** [rook/rook#3953]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
My cephcluster rook-ceph file as beflow

```
  storage:
    config:
      storeType: bluestore
    nodes:
    - config: null
      devices:
      - config: null
        name: sda
      - config: null
        name: sdb
      - config: null
        name: sdc
      - config: null
        name: sdd
      - config: null
        name: sde
      - config: null
        name: sdf
      - config: null
        name: sdg
      - config: null
        name: sdh
      - config: null
        name: sdi
      - config: null
        name: sdk
      - config: null
        name: sdl
      name: s01
      resources: {}
```

Rook will start the osd for sda device, although i remove the sda device from YAML file.

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
