### ISSUE TITLE
Support specifying storage devices/directories to the OSD container

### ISSUE THREAD

**Issue by travisn** [rook/rook#397]
Currently in the kubernetes deployment, OSDs will automatically format all devices that it are found locally, unless they have an existing partition or file system. This comes is way too aggressive as it could cause data loss for devices that the admin may have provisioned for something else. We really need to give the admin full flexibility to specify the devices that are for Rook usage. 

The configuration of the devices will happen on a machine and should be easily specified for that machine. The most simple approach may be:
- The operator takes a flag such as `--node-config-dir` which is the directory where the OSDs should look for device configuration. The default dir will be /var/lib/rook
- The daemonset will configure the osd containers to launch with that hostPath mounted.
- The OSD container will look in that dir for the devices that should be used.

The config might include:
- a text file with the names of the devices to use, or with a keyword "all" to use all storage, or some other policy for which devices to choose
- symlinks under `<path>/devices/` that point to them

**Comment by bassam** [comment]
There are other node-specific information that we should consider like geo location (impact CRUSH map), network settings (single, multiple) etc.

**Comment by bzub** [comment]
This config file could support per-storage-device settings like force destroy partitions/filesystems. I'm sure there's other options I'm not thinking of right now.

**Comment by hunter** [comment]
I was planning on filing a ticket for device and crushmap configuration but noticed #454 and this ticket.

It's definitely important to have control over the drives and their placement. Just to add how we're currently managing our containerised ceph environments, our nodes will typically have a dozen drives of either spinners or SSDs. We run a daemonset for each device across the cluster (e.g. `/dev/sdb` for all nodes labeled 'storage', another DS for `/dev/sdc`, etc), along with an ENV var specifying the type (hdd/ssd) which we use for setting the crush location. The daemonset approach is mostly a hack that gives us some flexibility for doing rolling updates of ceph versions without taking a whole container down with 12 OSDs.

I'd imagine it is something better handled in an operator with more control over the pods but that sort of granularity is needed in order to provide tiering or redundancy. With storage being tied to a node, would a configuration in the operator suffice - specifying each node, the devices and type?

```
nodes:
   - node: storage1
      osds:
         - device: /dev/sdb
            type: ssd
   - node: storage2
      osds:
         - device: /dev/sdb
            type: hdd
```

That may require the operator to create the crushmap and any pools to match the types unless further configuration is added. With more configuration though, the node spec could be also be expanded for advanced configurations:

```
nodes:
   - node: storage1
      osds:
         - device: /dev/sdb
            type: ssd
            backend: bluestore
            weight: 10
   - node: storage2
      osds:
         - device: /dev/sdb
            journal: /dev/sdd1
            location: "root=default row=a rack=b chassis=c host=d"
         - device: /dev/sdc
            journal: /dev/sdd2
            location: "root=default row=a rack=b chassis=c host=e"
            dmcrypt: true
```

Hopefully the ideas are of some use :)
