### ISSUE TITLE
Ceph osd prepare pod error when "topologyAware: true" due to insufficient ServiceAccount permissions

### ISSUE THREAD

**Issue by splushii** [rook/rook#3993]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

`rook-ceph-osd-prepare-...` pods error with:
```
topologyAware is set, but could not get the node: could not find node '<node name>' by name: nodes "<node name>" is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-osd" cannot get resource "nodes" in API group "" at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io "rook-ceph-osd" not found
```

**Expected behavior:**

`rook-ceph-osd-prepare-...` successfully prepare osd on host

**How to reproduce it (minimal and precise):**

- Install helm chart `rook-ceph` version `v1.1.1` from `https://charts.rook.io/release`
- Configure a `CephCluster` as below:
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.4-20190917
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  storage:
    useAllNodes: true
    useAllDevices: true
    topologyAware: true
    location:
    config:
      metadataDevice:
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.3 LTS
* Kernel (e.g. `uname -a`): 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: on-prem bare metal
* Rook version (use `rook version` inside of a Rook Pod): 1.1.1
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
* Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm on-prem
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK
