### ISSUE TITLE
Cannot run cephcsi in mix architecture kubernetes cluster

### ISSUE THREAD

**Issue by Glorf** [rook/rook#4051]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When deploying new CephCluster with latest Rook operator installed by helm chart on ARM64 (Raspberry PI 4, Ubuntu 18.04), the CSI plugins fail to run with `standard_init_linux.go:211: exec user process caused "exec format error"`. Apparently, there are no arm64 images for these plugins in the quay.io repository. Therefore, csi plugins have to be disabled, or rook downgraded, to make the persistence work properly

**Expected behavior:**
The ceph cluster should spawn properly, the arm64 images should be downloaded for all components

**How to reproduce it (minimal and precise):**
Have Rook operator deployed properly in ARM64 kubernetes cluster
Do `kubectl apply -f cluster.yaml` on your `cluster.yaml`.
Watch the plugin pods spawning and crashing into crashloopbackoff

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`:
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    allowUnsupported: false
  dataDirHostPath: /storage
  skipUpgradeChecks: false
  mon:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
    ssl: true
  monitoring:
    enabled: false
    rulesNamespace: rook-ceph
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "node1"
      directories:
      - path: /storage
```

**Environment**:
* OS: `Ubuntu 18.04 aarch64`
* Kernel: custom `4.19.76` kernel compiled with rbd module
* Cloud provider or hardware configuration: Raspberry Pi 4
* Rook version: v1.1.2
* Storage backend version: ceph/ceph:v14.2.4-20190917
* Kubernetes version: v1.16.0
* Kubernetes cluster type: Kubespray
