### ISSUE TITLE
Multipart uploads failing: RGW 'non-ec' pool should be configured as metadata pool

### ISSUE THREAD

**Issue by OwenTuz** [rook/rook#4073]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When creating an RGW object store via the `CephObjectStore` CRD, the pool `<store_name>.rgw.buckets.non-ec` is created by Ceph but not configured by Rook.

We noticed this on a non-production device with only one OSD: since the default replication factor is > 1, the pool was under-replicated and would not serve write requests.

Since the pool appears to only be used during multipart uploads, this meant that S3 PUT requests below a certain size worked, but multipart uploads always hung waiting for a response to the first POST request.

**Expected behavior:**
After creating an object store using the `CephObjectStore` CRD, all necessary pools should be configured with my stated replication (and other) settings.

**How to reproduce it (minimal and precise):**

Create an object store with `metadata.replicated.size` set to `1`:
```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-object-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 1
  dataPool:
    replicated:
      size: 1
  gateway:
    type: s3
    sslCertificateRef: 
    port: 80
    securePort: 
    instances: 1
```
Using the Ceph toolbox, list pools:
```
# ceph osd pool ls
replicapool
my-object-store.rgw.control
my-object-store.rgw.meta
my-object-store.rgw.log
my-object-store.rgw.buckets.index
.rgw.root
my-object-store.rgw.buckets.data
my-object-store.rgw.buckets.non-ec
```
Verify with `osd pool get` that the size has been set for all buckets except `my-object-store-rgw.buckets.non-ec`:

```
# ceph osd pool get my-object-store.rgw.meta size
size: 1
[...]
# ceph osd pool get my-object-store.rgw.buckets.non-ec size
size: 3
```

**Workaround:**
`ceph osd pool set my-object-store.rgw.buckets.non-ec size 1`
Where '1' is your desired replication factor.

**Suggested fix:**

Documentation on this pool was a little hard to come by but [this mailing list message](http://lists.ceph.com/pipermail/ceph-users-ceph.com/2018-September/029538.html) clarifies that it's only used for storing metadata during multipart uploads:

> This extra non-ec pool is only used for the 'multipart metadata' object that tracks which parts have been written, though - the object data for each part is still written to the normal data pool, so it can take advantage of erasure coding.

I suggest we add it to the list of metadata pools mentioned in the [design document](https://github.com/rook/rook/blob/5db55e1cfdc5013366e8c4a65c05c3e22c7bf6a8/design/object-bucket.md) and ensure it is configured with the same settings that they are.
