### ISSUE TITLE
Slow edgefs+nfs writes when compared to plain NFS pod

### ISSUE THREAD

**Issue by matti** [rook/rook#4111]
* Bug Report (performance issue)

**Deviation from expected behavior:**

untarring time for `tar -xof linux-1.0.tar.gz`
AWS EFS: 28s (100mb/s provisioned)
rook+edgefs: 18s
nfs server pod + EBS: 5s
not directly related, but the same test in GKE with elastifile ($6500/mo)
elastifile (performance mode): 22s

**Expected behavior:**

rook+edgefs to be closer to NFS server pod + EBS - I understand that they can not be compared, but +13s is a big difference.

**How to reproduce it (minimal and precise):**

1. setup rook+edgefs
2. have two mounts
 a) "normal" nfs from aws ebs volume
 b) rook+edgefs
3.
```
cd /nfs-ebs
curl -LO https://mirrors.edge.kernel.org/pub/linux/kernel/v1.0/linux-1.0.tar.gz
time time tar -xof linux-1.0.tar.gz
# 5s

cd /nfs-rook-edge
curl -LO https://mirrors.edge.kernel.org/pub/linux/kernel/v1.0/linux-1.0.tar.gz
time time tar -xof linux-1.0.tar.gz
# 18s

# (bonus:)
cd /nfs-efs
curl -LO https://mirrors.edge.kernel.org/pub/linux/kernel/v1.0/linux-1.0.tar.gz
time time tar -xof linux-1.0.tar.gz
# 28s
```

**File(s) to submit**:

```
apiVersion: edgefs.rook.io/v1
kind: Cluster
metadata:
  name: rook-edgefs
  namespace: rook-edgefs
spec:
  edgefsImageName: edgefs/edgefs:1.2.64  # specify version here, i.e. edgefs/edgefs:1.1.0 etc
  serviceAccount: rook-edgefs-cluster
  dataDirHostPath: /var/lib/edgefs
  #dataVolumeSize: 100Gi
  #devicesResurrectMode: "restoreZapWait"
  #skipHostPrepare: true
  #maxContainerCapacity: 132Ti
  trlogProcessingInterval: 2      # set transaction log processing interval to 2s to speed up ISGW Link delivery
  trlogKeepDays: 2                # keep up to 2 days of transaction log interval batches to reduce local storage overhead
  #useHostLocalTime: true
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: true
    config:
      walMode: "off"
  #    mdReserved: "30"            # allocate only 30% of offloaded SSD/NVMe slice for Metadata, the rest keep for BCache
  #    hddReadAhead: "2048"        # speed up reads of 2MB+ chunks of HDD (offload use case)
      rtVerifyChid: "0"           # may improve CPU utilization
  #    lmdbPageSize: "32768"       # larger value can improve stream operations
  #    lmdbMdPageSize: "4096"      # smaller value can improve metadata offload device utilization
  #    useMetadataOffload: "true"  # enable use of SSD device as metadata offload
  #    useBCache: "true"           # enable SSD cache device and read-cache
  #    useBCacheWB: "true"         # enable SSD write-cache
  #    useMetadataMask: "0x7d"     # all metadata on SSD except second level manifests
  #    rtPLevelOverride: "4"       # enable large device partitioning, only needed if automatic not working
      sync: "0"                   # highest performance, consistent on pod/software failures, not-consistent on power failures
      useAllSSD: "true"           # use only SSDs during deployment
  #    zone: "1"                   # defines failure domain's zone number for all edgefs nodes
```

```
apiVersion: edgefs.rook.io/v1
kind: NFS
metadata:
  name: nfs-kontena
  namespace: rook-edgefs
spec:
  instances: 1
  relaxedDirUpdates: true
```

```
mountOptions: "noatime,nodiratime,noacl,nocto,rsize=32768,wsize=32768"
```

running on `m5d.2xlarge`
```
# hdparm -t /dev/nvme0n1 /dev/nvme1n1

/dev/nvme0n1:
 Timing buffered disk reads: 514 MB in  3.01 seconds = 170.84 MB/sec

/dev/nvme1n1:
 Timing buffered disk reads: 2452 MB in  3.00 seconds = 816.47 MB/sec
```

**Environment**:
* OS (e.g. from /etc/os-release):
ubuntu 16.04
* Cloud provider or hardware configuration:
aws ec2 nvme (m5d.2xlarge)
