### ISSUE TITLE
Tolerations do not get applied in Rook 1.1

### ISSUE THREAD

**Issue by mabushey** [rook/rook#4147]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Pods do not run on the specified nodes

**Expected behavior:**
Specified toleration in `cluster.yaml` is applied to the pods.

**How to reproduce it (minimal and precise):**
I have a cluster on AWS provisioned via Kops, with an instance group of three i3 nodes in the cluster that I want to run rook on:

```
✗  kubectl get nodes -l "beta.kubernetes.io/instance-type=i3.large"
NAME                                         STATUS   ROLES     AGE     VERSION
ip-10-132-10-25.us-west-2.compute.internal   Ready    i3,node   5d18h   v1.14.6
ip-10-132-11-13.us-west-2.compute.internal   Ready    i3,node   5d18h   v1.14.6
ip-10-132-9-182.us-west-2.compute.internal   Ready    i3,node   5d18h   v1.14.6
```

```
kubectl taint nodes -l "beta.kubernetes.io/instance-type=i3.large" storage=i3:NoExecute 
node/ip-10-132-10-25.us-west-2.compute.internal tainted
node/ip-10-132-11-13.us-west-2.compute.internal tainted
node/ip-10-132-9-182.us-west-2.compute.internal tainted
```

I can add this to the `operator.yaml` and get the operator running on the i3 nodes:

```
spec:
  selector:
    matchLabels:
      app: rook-ceph-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: rook-ceph-operator
    spec:
      serviceAccountName: rook-ceph-system
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/instance-type
                operator: In
                values:
                - i3.large
      tolerations:
      - key: "storage"
        operator: Equal
        value: "i3"
      containers:
      - name: rook-ceph-operator
        image: rook/ceph:v1.1.0
```

```
✗  kubectl -n rook-ceph describe pod/rook-ceph-operator-5f5c6b9f66-mbkgm
...
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 storage
...
```

However the operator also fires up three discover nodes, which do not run on the i3 nodes because the toleration is not applied. :(

```
✗  kubectl -n rook-ceph describe pod/rook-discover-gzfzl
...
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
...
```

Next in the `cluster.yaml` I add:
```
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "beta.kubernetes.io/instance-type"
              operator: In
              values:
              - "i3.large"
      podAffinity:
      podAntiAffinity:
      tolerations:
      - key: "storage"
        operator: Exists
    #mgr:
    #  nodeAffinity:
    #  tolerations:
    #mon:
    #  nodeAffinity:
    #  tolerations:
    #osd:
    #  nodeAffinity:
    #  tolerations:
```

I leave mgr, mon, and osd commented out as I do not wish to override the all value; I want all rook-ceph pods on the i3 nodes. The wording in the comments in the `cluster.yaml` is not clear, I did try un-commenting the `mgr`, `mon`, and `osd` sections with the same broken result. I apply this `cluster.yaml`, then:

```
✗  kubectl -n rook-ceph describe pod/rook-ceph-agent-45g9k
...
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
```

The toleration of "storage" I applied in the `cluster.yaml` does not get used. :(

**Environment**:
* OS (e.g. from /etc/os-release):
`Container Linux by CoreOS 2247.5.0 (Rhyolite)`
* Kernel version
`4.19.78-coreos`
* Cloud provider or hardware configuration: AWS / Kops
* Rook version (use `rook version` inside of a Rook Pod):
`image: rook/ceph:v1.1.0`

* Kubernetes version (use `kubectl version`):
Client: 1.14.1
Server: 1.14.6

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
AWS / Kops
