### ISSUE TITLE
K8s logs spamming with "Failed to list *unstructured.Unstructured: the server could not find the requested resource" after deleting operator and common

### ISSUE THREAD

**Issue by zedtux** [rook/rook#4156]
* Bug Report

When applying the `common.yaml`, `operator.yaml`,  and `cluster.yaml` files and then deleting them in the opposite order, on my kubernetes 1.15 cluster, `stern` starts to spam my screen with the following error:

```
kube-system kube-controller-manager-dev-k8s-master-1 kube-controller-manager E1023 14:15:34.803231       1 reflector.go:125] k8s.io/client-go/dynamic/dynamicinformer/informer.go:90: Failed to list *unstructured.Unstructured: the server could not find the requested resource
```

I found [a similar issue](https://github.com/vmware-tanzu/octant/issues/117) about this error in another project which could give some hits.

**Expected behavior:**

Delete in a clean way the objects.

**How to reproduce it (minimal and precise):**

1. `kubectl apply common.yaml`
2. `kubectl apply operator.yaml`
3. `kubectl apply cluster.yaml`
4. `kubectl delete cluster.yaml`
5. `kubectl delete cluster.yaml`
6. `kubectl delete common.yaml`

While deleting `common.yaml` it starts to spam.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  # The name that will be used internally for the Ceph cluster.
  # Most commonly the name is the same as the namespace since multiple clusters
  # are not supported in the same namespace.
  name: rook-ceph
  # The Kubernetes namespace that will be created for the Rook cluster.
  # The services, pods, and other resources created by the operator will be
  # added to this namespace.
  # The common scenario is to create a single Rook cluster.
  # If multiple clusters are created, they must not have conflicting devices or
  # host paths.
  namespace: rook-ceph
spec:
  cephVersion:
    # The image used for running the ceph daemons
    # For the latest ceph images, see https://hub.docker.com/r/ceph/ceph/tags/.
    # To ensure a consistent version of the image is running across all nodes
    # in the cluster, it is recommended to use a very specific image version.
    image: ceph/ceph:v14.2.4-20190917
  dashboard:
    enabled: true
  # The path on the host (hostPath) where config and data should be stored
  # for each of the services.
  # If the directory does not exist, it will be created.
  # Because this directory persists on the host, it will remain after pods
  # are deleted.
  # Following paths and any of their subpaths must not be used:
  #  - /etc/ceph
  #  - /rook
  #  - /var/log/ceph.
  dataDirHostPath: /var/lib/rook
  mon:
    # Set the number of mons to be started.
    # The number should be odd and between 1 and 9.
    # If not specified the default is set to 3 and allowMultiplePerNode is also
    # set to true.
    count: 3
    # Enable (true) or disable (false) the placement of multiple mons on
    # one node.
    # Default is false.
    allowMultiplePerNode: true
  storage:
    # Indicates if all nodes in the cluster should be used for storage according
    # to the cluster level storage selection and configuration values.
    # If individual nodes are specified under the nodes field,
    # then useAllNodes must be set to false.
    useAllNodes: true
    useAllDevices: true
```

**Environment**:
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
