### ISSUE TITLE
detect-version fails when istio mtls is enabled in rook-ceph namespace w/ outboundTrafficPolicy set to REGISTRY_ONLY

### ISSUE THREAD

**Issue by funkypenguin** [rook/rook#4200]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I'm using Istio mTls with outboundTrafficPolicy=REGISTRY_ONLY, which will prevent any pods from accessing URLs not defined in the istio service registry.

When deploying rook-ceph using the helm chart, the `rook-ceph-detect-version` pod never completes, logging the following:

```
root@cn1:~# kubectl logs -n rook-ceph rook-ceph-detect-version-ndm4d cmd-reporter
2019-10-28 02:02:53.611143 I | job-reporter-cmd: running command: /usr/bin/ceph ceph --version
ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
Error: failed to save command output to ConfigMap. failed to determine if ConfigMap rook-ceph-detect-version is preexisting. Get https://10.96.0.1:443/api/v1/namespaces/rook-ceph/configmaps/rook-ceph-detect-version: dial tcp 10.96.0.1:443: connect: connection refused
```

**Expected behavior:**

rook-ceph-detect-version would talk to the Kubernetes API in a means which wouldn't be impacted by istio mtls.

I didn't think I would need to explicitly permit the Kubernetes API endpoint in this regard (cert-manager and external-dns are both able to watch Kubernetes resources without any additional config). Just in case though, I added an Istio service for the API server, as follows:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: k8s-api-ip
  namespace: rook-ceph
spec:
  hosts:
  - kubernetes.default.svc.cluster.local
  addresses:
  - 10.96.0.1/32
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: NONE
  location: MESH_EXTERNAL
```

I tested by launching a pod into the rook-namespace, and curling the same URL that detect-version is failing to reach. As indicated below, this pod successfully received a response (not "connection refused", as reported by `reporter-cmd`):

```
# curl https://10.96.0.1:443 -k
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
/ #
```

**How to reproduce it (minimal and precise):**

1. Deploy istio using helm chart with sidecar injection, enable mtls (`-x global.mtls.enabled=true -x sidecarInjectorWebhook.enabled=true -x global.outboundTrafficPolicy.mode=REGISTRY_ONLY` )
2. Create namespace for rook-ceph, and label it for mtls (`kubectl label namespace rook-ceph istio-injection=enabled`)
3. Deploy rook-ceph into the namespace, using the helm chart

**Environment**:
* Rook Ceph version : v1.1.4
* Installation method : helm chart
* Kubernetes version (use `kubectl version`): 1.16
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare-metal
