### ISSUE TITLE
rook-ceph-detect-version job exits 0 on failure

### ISSUE THREAD

**Issue by redradrat** [rook/rook#4301]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Job exited with 0 and is therefore not retried, resulting in the networking issue to not self-heal.

**Expected behavior:**
Job exits non-zero and thus is retried, as expected from a resilient implementation.

**How to reproduce it (minimal and precise):**

While experiencing network issues, the job in our case failed. Initializing with invalid iptables for example.

**File(s) to submit**:
job log
```
~ >>> k logs rook-ceph-detect-version-bm2pp -c cmd-reporter                       
2019-11-12 14:58:04.398091 I | job-reporter-cmd: running command: /usr/bin/ceph ceph --version
ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
Error: failed to save command output to ConfigMap. failed to determine if ConfigMap rook-ceph-detect-version is preexisting. Get https://172.20.0.1:443/api/v1/namespaces/capabilities/configmaps/rook-ceph-detect-version: dial tcp 172.20.0.1:443: connect: connection refused
Usage:
  rook cmd-reporter [flags]

Flags:
      --command string           The command to run in JSON list syntax. e.g., '["command", "--flag", "value", "arg"]'
      --config-map-name string   The name of the ConfigMap into which the result of the command will be stored.
  -h, --help                     help for cmd-reporter
      --namespace string         The namespace in which to create the ConfigMap.

Global Flags:
      --log-flush-frequency duration   Maximum number of seconds between log flushes (default 5s)
      --log-level string               logging level for logging/tracing output (valid values: CRITICAL,ERROR,WARNING,NOTICE,INFO,DEBUG,TRACE) (default "INFO")
      --operator-image string          Override the image url that the operator uses. The default is read from the operator pod.
      --service-account string         Override the service account that the operator uses. The default is read from the operator pod.

rook error: failed to save command output to ConfigMap. failed to determine if ConfigMap rook-ceph-detect-version is preexisting. Get https://172.20.0.1:443/api/v1/namespaces/capabilities/configmaps/rook-ceph-detect-version: dial tcp 172.20.0.1:443: connect: connection refused
```

job status output:
```
containerStatuses:
  - containerID: docker://acae3fcb2fe627a30a88038f5af614e5d64ee31812298eff5fc5f566ae27556b
    image: ceph/ceph:v14.2.4-20190917
    imageID: docker-pullable://ceph/ceph@sha256:fb86551e52e8909bf938a6d8652e49b61207d8bfb21c63b26ff38fd6736e0322
    lastState: {}
    name: cmd-reporter
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://acae3fcb2fe627a30a88038f5af614e5d64ee31812298eff5fc5f566ae27556b
        exitCode: 0
        finishedAt: "2019-11-12T15:13:15Z"
        reason: Completed
        startedAt: "2019-11-12T15:13:15Z"
```
