### ISSUE TITLE
CephFS CSI configmaps and secrets missing when using external ceph cluster configuration

### ISSUE THREAD

**Issue by mattirantakomi** [rook/rook#4368]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

CephFS backed PVC provisioning is impossible because `rook-ceph-csi-config` configmap and `rook-csi-cephfs-provisioner` and `rook-csi-cephfs-node` secrets containing external Ceph cluster details are missing. 

**Expected behavior:**

Configmap `rook-ceph-csi-config` and secrets `rook-csi-cephfs-provisioner` and `rook-csi-cephfs-node` are created and populated with external cluster details when external cluster configuration is applied. CephFS backed PVC's are created and attached as they should.

**How to reproduce it (minimal and precise):**

Apply common and common external YAMLs:
```
kubectl apply -f https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/common.yaml
kubectl apply -f https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/common-external.yaml
```

Export external cluster environment variables:
```
export NAMESPACE=rook-ceph-external
export ROOK_EXTERNAL_FSID=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
export ROOK_EXTERNAL_ADMIN_SECRET=s3cr37xdja+NDBAAB7qy9MEAr4VLLq4dCIasdf==
export ROOK_EXTERNAL_CEPH_MON_DATA=a=10.11.22.33:6789
```

Import External Ceph cluster details:
```
wget https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/import-external-cluster.sh
chmod +x import-external-cluster.sh
./import-external-cluster.sh
```

Apply external cluster YAML:
```
kubectl apply -f https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster-external.yaml
```

Apply storage class YAML:
```
kubectl apply -f https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/cephfs/storageclass.yaml
```

Check existing configmaps and secrets on `rook-ceph` namespace and notice that `rook-ceph-csi-config` configmap and `rook-csi-cephfs-provisioner` and `rook-csi-cephfs-node` secrets are missing. 

Try to create PVC, describe it and notice the following event:
```
Warning  ProvisioningFailed    35m (x15 over 63m)     rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-77f6f7cf7b-wdxc7_6f1849c2-06a9-11ea-b4f0-eeb13d2d5fb1  failed to provision volume with StorageClass "csi-cephfs": rpc error: code = InvalidArgument desc = failed to fetch monitor list using clusterID (rook-ceph): missing configuration for cluster ID (rook-ceph)
```

Manually populate configmap `rook-ceph-csi-config` with external cluster details:
```
apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"rook-ceph","monitors":["10.11.22.33:6789"]}]'
kind: ConfigMap
metadata:
  name: rook-ceph-csi-config
  namespace: rook-ceph
```

Re-check `kubectl describe pvc` and notice that secrets are missing:
```
  Warning  ProvisioningFailed    0s (x6 over 15s)  rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-asdf  failed to provision volume with StorageClass "csi-cephfs": error getting secret rook-csi-cephfs-provisioner in namespace rook-ceph: secrets "rook-csi-cephfs-provisioner" not found

  Warning  ProvisioningFailed    0s (x6 over 15s)  rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-asdf  failed to provision volume with StorageClass "csi-cephfs": error getting secret rook-csi-cephfs-node in namespace rook-ceph: secrets "rook-csi-cephfs-node" not found
```

Manually populate `rook-csi-cephfs-provisioner` and `rook-csi-cephfs-node` secrets with admin authentication key:
```
apiVersion: v1
data:
  adminID: YWRtaW4=
  adminKey: s3cr3tRkdGQvaEE3REJBQUYrVitrU0JKU2FxTUtqMGFLaDI0ZGcasdf=
  userID: YWRtaW4=
  userKey: s3cr3tRkdGQvaEE3REJBQUYrVitrU0JKU2FxTUtqMGFLaDI0ZGcasdf=
kind: Secret
metadata:
  name: rook-csi-cephfs-provisioner
  namespace: rook-ceph
type: kubernetes.io/rook
```

```
apiVersion: v1
data:
  adminID: YWRtaW4=
  adminKey: s3cr3tRkdGQvaEE3REJBQUYrVitrU0JKU2FxTUtqMGFLaDI0ZGcasdf=
  userID: YWRtaW4=
  userKey: s3cr3tRkdGQvaEE3REJBQUYrVitrU0JKU2FxTUtqMGFLaDI0ZGcasdf=
kind: Secret
metadata:
  name: rook-csi-cephfs-node
  namespace: rook-ceph
type: kubernetes.io/rook
```

After that PVC is succesfully attached and it can be used as it should.

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

* Kernel (e.g. `uname -a`):
`
Linux ip-172-31-32-44 5.0.0-1021-aws #24~18.04.1-Ubuntu SMP Mon Nov 11 12:55:10 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`

* Cloud provider or hardware configuration: 
AWS `m5d` instances

* Rook version (use `rook version` inside of a Rook Pod): 
`rook: v1.1.2`

* Storage backend version (e.g. for ceph do `ceph -v`): 
`ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)`

* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
`Kontena Pharos`

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
`HEALTH_OK`
