### ISSUE TITLE
Ceph: upgrade OSDs in parallel

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#4380]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
When Rook orchestrates an update to Rook or to Ceph, it updates OSDs one-at-a-time in the cluster. This is maximally safe, but it is also the slowest option. For clusters with thousands of OSDs, upgrade/update orchestrations could take a VERY long time. 

As a back-of-napkin calculation, if each OSD takes 5 seconds to update, a 1000-OSD cluster would take nearly 1.5 hours to complete.

**Discussion:**
This was discussed in the container huddle today. A similarly safe but much quicker option would likely be to update OSDs on a node at a time.

**Comment by BlaineEXE** [comment]
Not stale.

**Comment by travisn** [comment]
I'd like to consider broadening the upgrade policy in several ways:
- Move the existing upgrade settings from the top level of the cluster CR underneath an `upgradePolicy` element
- OSD upgrade policy could include options for upgrading up to `n` in parallel, or up to `n` nodes in parallel
- List of Ceph health codes that would either block the upgrade, or allow the upgrade to continue even if they exist.

For example, a rough draft of the settings looks like:
```
upgradePolicy:
  skipUpgradeChecks: false  
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  osds:
    parallelDaemons: 1
    parallelNodes: 1
    waitTimePerDaemonIfPGsUnhealthy: 10m
  healthErrorsToIgnore: 
  - <error1>
```
