### ISSUE TITLE
Operator is not notified by TPRs when not running in the default namespace

### ISSUE THREAD

**Issue by travisn** [rook/rook#440]
TPRs are not namespace-specific, yet the Rook operator is not getting notified of changes to TPRs if the operator is not running in the default namespace.

**Comment by luxas** [comment]
So this is a kubernetes bug or?

**Comment by travisn** [comment]
@luxas good question, i'm still trying to isolate if it's in rook or not

**Comment by travisn** [comment]
it turns out there is not a bug in kubernetes. The pattern is that the rook-operator will watch a certain namespace for TPRs. Even though the TPR definition is namespace-agnostic, the instances of TPRs do belong to a namespace. So when the TPR is created, the yaml should include the namespace where the operator is running. 

For example, if the operator is running in the namespace called `mynamespace` the yaml might be:
```
apiVersion: rook.io/v1beta1
kind: Cluster
metadata:
  name: my-rook
  namespace: mynamespace
spec:
  namespace: rook
  version: latest
  useAllDevices: false
```
