### ISSUE TITLE
Prepare pods pending on OpenShift master and infra nodes

### ISSUE THREAD

**Issue by BostjanBozic** [rook/rook#4428]
**Is this a bug report or feature request?**
* Bug Report (I think, not sure if this is expected behaviour)

**Deviation from expected behavior:**
Ceph prepare pods are not scheduled on Openshift master/infrastructure nodes. Within job, `nodeSelector` is set correctly:
```
nodeSelector:
  kubernetes.io/hostname: okd-master-0.test.eu
```
But pod itself recieves additional selector (combination is never there):
```
nodeSelector:
    kubernetes.io/hostname: okd-master-0.test.eu
    node-role.kubernetes.io/compute: "true"
```

**Expected behavior:**
Prepare pods are run on all cluster nodes and flex driver is installed on all of them. Reason is that e.g. internal repository runs on infrastructure nodes and it requires persistent storage.

**How to reproduce it (minimal and precise):**

Deploy Ceph cluster on OpenShift without any placement settings in `cluster.yaml`.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.4-20190917
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
    port: 8089
    ssl: false
  monitoring:
    enabled: false
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  annotations:
  resources:
  removeOSDsIfOutAndSafeToRemove: false
  storage:
    useAllNodes: true
    useAllDevices: false
    topologyAware: true
    deviceFilter:
    location:
    config:
      storeType: filestore
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
      osdsPerDevice: "1"
    directories:
    - path: /var/lib/rook
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
```
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7.7
* Kernel (e.g. `uname -a`): 3.10.0-957.12.2.el7.x86_64
* Cloud provider or hardware configuration: Cloud provider (Exoscale)
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.1.7`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)`
* Kubernetes version (use `kubectl version`): `v1.11.0+d4cacc0`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift OKD 3.11
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_OK`
