### ISSUE TITLE
ERROR : Module 'rook' has failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618) ?

### ISSUE THREAD

**Issue by pierreilki** [rook/rook#4434]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When i install Rook on my K8S v1.16.3 cluster i got an error in ceph block storage.

I d'ont see any error on rook pods, but if i connect to the "toolbox" pod and run "ceph status", i got this:

```
[root@k8s-3 /]# ceph status
  cluster:
    id:     6f452cf7-36fc-4a66-a97b-008a3af64be1
    health: HEALTH_ERR
            Module 'rook' has failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)

  services:
    mon: 1 daemons, quorum a (age 84s)
    mgr: a(active, since 46s)
    osd: 3 osds: 3 up (since 36s), 3 in (since 36s)

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   14 GiB used, 131 GiB / 145 GiB avail
    pgs:
```

**Expected behavior:**
I should have an healthy Rook Cluster and be very happy to play with it...

**How to reproduce it (minimal and precise):**
Install Rook on a fresh  K8S Cluster by following the official tutorial for release-1.1.
I used *-test.yaml files
I don't see any error on Rook Pods.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu Bionic 64
* Kernel (e.g. `uname -a`): 4.15.0-38-generic
* Cloud provider or hardware configuration:
** 1 master and 3 workers all with 1 VCPU and 4 Go RAM
* Rook version (use `rook version` inside of a Rook Pod): release-1.1
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.4
* Kubernetes version (use `kubectl version`): v1.16.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Agorakube
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
**HEALTH_ERR Module 'rook' has failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)**

Does someone know why this error occures?
I don't know were i have to look for more information...

Thanks for help :)

Have a nice day
