### ISSUE TITLE
Add wal/db device selection in cluster configuration

### ISSUE THREAD

**Issue by woohhan** [rook/rook#4449]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
We have per node configuration for selecting device, but no wal/db device selection. We can add configuration for what device will be used for wal/db device.

```yaml
// current
    nodes:
    - name: "mynode"
      devices:
      - name: "sdb"

// fix to
    nodes:
    - name: "mynode"
      dataDevices:
      - name: "sdb"
      walDevice: nvme0
      dbDevice: nvme1
```

**What is use case behind this feature:**
User can select wal/db device

**Environment**:
NONE
