### ISSUE TITLE
Kubelet reports an error，But all pods are normal

### ISSUE THREAD

**Issue by huntunshule** [rook/rook#4479]
kubernetes version 1.15.2
I installed rook first, but there were some errors, so I uninstalled and reinstalled，Kubelet keeps getting error messages after the new installer
```
[root@centos03 ceph]# kubectl get pod -n rook-ceph
NAME                                           READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-j5zqm                         3/3     Running     0          43m
csi-cephfsplugin-j7944                         3/3     Running     0          43m
csi-cephfsplugin-provisioner-974b566d9-77vwc   4/4     Running     0          43m
csi-cephfsplugin-provisioner-974b566d9-qn8hg   4/4     Running     0          43m
csi-cephfsplugin-zjlzr                         3/3     Running     0          43m
csi-rbdplugin-6wb9p                            3/3     Running     0          43m
csi-rbdplugin-provisioner-579c546f5-nbjf4      5/5     Running     0          43m
csi-rbdplugin-provisioner-579c546f5-srz7c      5/5     Running     0          43m
csi-rbdplugin-q7kvw                            3/3     Running     0          43m
csi-rbdplugin-t8rq7                            3/3     Running     0          43m
rook-ceph-mgr-a-844c4fc6cf-89mg5               1/1     Running     0          42m
rook-ceph-mon-a-f6c8b7f98-7g5jb                1/1     Running     0          43m
rook-ceph-mon-b-6f46fc4fdb-ctvfs               1/1     Running     0          42m
rook-ceph-mon-c-76577c5995-gwzwj               1/1     Running     0          42m
rook-ceph-operator-88866dbf5-r444d             1/1     Running     0          46m
rook-ceph-osd-prepare-centos01-g7kmj           0/1     Completed   0          41m
rook-ceph-osd-prepare-centos02-tvmmr           0/1     Completed   0          41m
rook-ceph-osd-prepare-centos03-qtbzt           0/1     Completed   0          41m
rook-ceph-tools-6cf65f79d8-6c8bm               1/1     Running     0          19s
rook-discover-7tkgk                            1/1     Running     0          46m
rook-discover-fmxsp                            1/1     Running     0          46m
rook-discover-szphh                            1/1     Running     0          46m
[root@centos03 ceph]#
```
```
[root@centos02 /]# ceph status
  cluster:
    id:     e7734d76-b06b-4b7c-a820-cfe29b76da6e
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 44m)
    mgr: a(active, since 43m)
    osd: 0 osds: 0 up, 0 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:
```
and the kubelet log messgae
![image](https://user-images.githubusercontent.com/52652738/70693939-6d099380-1cf9-11ea-93ee-740904f3db8e.png)
