### ISSUE TITLE
All pod is running and ceph cluster is health,but osd is 0

### ISSUE THREAD

**Issue by huntunshule** [rook/rook#4480]
```
[root@centos02 /]# ceph status
  cluster:
    id:     e7734d76-b06b-4b7c-a820-cfe29b76da6e
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 108m)
    mgr: a(active, since 107m)
    osd: 0 osds: 0 up, 0 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:

```
I see that the state of the cluster is healthy, but the OSD is 0. When I go to create a storageclass, the state of the cluster becomes unhealthy

this is storageclass
```
[root@centos03 ceph]# cat storageclass.yaml
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
    # clusterID is the namespace where the rook cluster is running
    clusterID: rook-ceph
    # Ceph pool into which the RBD image shall be created
    pool: replicapool

    # RBD image format. Defaults to "2".
    imageFormat: "2"

    # RBD image features. Available for imageFormat: "2". CSI RBD currently supports only `layering` feature.
    imageFeatures: layering

    # The secrets contain Ceph admin credentials.
    csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
    csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
    csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph

    # Specify the filesystem type of the volume. If not specified, csi-provisioner
    # will set default as `ext4`.
    csi.storage.k8s.io/fstype: xfs

# Delete the rbd volume when a PVC is deleted
reclaimPolicy: Delete
```
```
[root@centos02 /]# ceph status
  cluster:
    id:     e7734d76-b06b-4b7c-a820-cfe29b76da6e
    health: HEALTH_WARN
            Reduced data availability: 8 pgs inactive

  services:
    mon: 3 daemons, quorum a,b,c (age 114m)
    mgr: a(active, since 113m)
    osd: 0 osds: 0 up, 0 in

  data:
    pools:   1 pools, 8 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             8 unknown
```

environment:
kubernetes 1.15.2
rook 1.1
