### ISSUE TITLE
Prometheus monitoring rules don't install when using external ceph cluster

### ISSUE THREAD

**Issue by tuchinsky** [rook/rook#4522]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Prometheus monitoring rules don't install

**Expected behavior:**

Prometheus monitoring rules install in expected namespace

**How to reproduce it (minimal and precise):**

Deploy rook with ceph external cluster and add parameter in CR that enables monitoring

**File(s) to submit**:

cephclusters.ceph.rook.io CR:

```
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph-external
spec:
  external:
    enable: true
  monitoring:
    enabled: true
  dataDirHostPath: /var/lib/rook
  cephVersion:
    image: ceph/ceph:v14.2.4-20190917
```

rook-operator logs:
```
2019-12-16 16:15:15.671229 I | op-cluster: The Cluster CR has changed. diff={v1.ClusterSpec}.Monitoring.Enabled:
	-: false
	+: true
```

**Environment**:

ceph 14.2.4

rook 1.1.8
