### ISSUE TITLE
The StorageClass setting rootPath is not valid

### ISSUE THREAD

**Issue by pog2g** [rook/rook#4554]
* The StorageClass setting rootPath is invalid, and other issue prompts need to set the staticVolume
* Can provide a full case of cephfs create staticVolume, according to this operation can't run successfully
```
https://gist.github.com/ShyamsundarR/f16d32e3edd5b38df50e90106674a943
```

* This is because web static pages need to be stored in a fixed directory in cephfs so that web pages can be passed between the host and the container to nginx

**Comment by leseb** [comment]
Please re-open the issue using the issue template.

**Comment by pog2g** [comment]
* staticVolume template
```
---
# Secret manifest containing ID and key for pre-provisioned subvolume
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-preprov-secret
  namespace: default
data:
  userID: YWRtaW4=
  userKey: AQDDOPxdCyCGCBAA5nBqCfSp45n3F50YciSpBg==
---
# Static persistent volume manifest
apiVersion: v1
kind: PersistentVolume
metadata:
  name: preprov-pv-cephfs-01
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  csi:
    driver: cephfs.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: csi-cephfs-preprov-secret
      namespace: default
    volumeAttributes:
      # New style monitors and FSName specification 1.1.0 (instead of monitors and pool)
      clusterID: rook-ceph
      fsName: myfs
      # Denote the volume as pre-provisioned for the nodeplugin to act appropriately
      preProvisionedVolume: "true"
      rootPath: /www
    volumeHandle: preprov-pv-cephfs-01
  # reclaim policy is to retain, as it is a pre-provisioned volume and would require a PV delete
  # to remove the same from the kubernetes system
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  # claimref tying this PV to a specific PV and namespace
  claimRef:
    name: csi-cephfs-pvc-preprov
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cephfs-pvc-preprov
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # volumeName tying this PCV to a specific PV
  volumeName: preprov-pv-cephfs-01
---
apiVersion: v1
kind: Pod
metadata:
  name: csicephfs-preprov-demo-pod
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: csi-cephfs-pvc-preprov
        readOnly: false
```
*  'clusterID: rook-ceph' is my id
*  The userKey is obtained by running :
```
grep key/etc/ceph /keyring | awk '{print $3} '
```
 directly in the rook-direct-mount container
* error info:
```
error while running "VolumeBinding" filter plugin for pod "csicephfs-preprov-demo-pod": pod has unbound immediate PersistentVolumeClaims
AttachVolume.Attach failed for volume "preprov-pv-cephfs-01" : attachdetachment timeout for volume preprov-pv-cephfs-01
Unable to attach or mount volumes: unmounted volumes=[mypvc], unattached volumes=[mypvc timezone default-token-2jjdj]: timed out waiting for the condition
```
