### ISSUE TITLE
The StaticVolume does not work properly

### ISSUE THREAD

**Issue by pog2g** [rook/rook#4557]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
```
error while running "VolumeBinding" filter plugin for pod "csicephfs-preprov-demo-pod": pod has unbound immediate PersistentVolumeClaims
MountVolume.MountDevice failed for volume "preprov-pv-cephfs-01" : rpc error: code = Internal desc = missing required field monitors
```
**Expected behavior:**

**How to reproduce it (minimal and precise):**

Container running normally
**File(s) to submit**:
```
---
# Secret manifest containing ID and key for pre-provisioned subvolume
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-preprov-secret
  namespace: default
data:
  userID: YWRtaW4=
  userKey: QVFERE9QeGRDeUNHQ0JBQTVuQnFDZlNwNDVuM0Y1MFljaVNwQmc9PQ==
---
# Static persistent volume manifest
apiVersion: v1
kind: PersistentVolume
metadata:
  name: preprov-pv-cephfs-01
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: csi-cephfs-preprov-secret
      namespace: default
    volumeAttributes:
      # New style monitors and FSName specification 1.1.0 (instead of monitors and pool)
      clusterID: rook-ceph
      fsName: myfs
      # Denote the volume as pre-provisioned for the nodeplugin to act appropriately
      preProvisionedVolume: "true"
      rootPath: /www
    volumeHandle: preprov-pv-cephfs-01
  # reclaim policy is to retain, as it is a pre-provisioned volume and would require a PV delete
  # to remove the same from the kubernetes system
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  # claimref tying this PV to a specific PV and namespace
  claimRef:
    name: csi-cephfs-pvc-preprov
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cephfs-pvc-preprov
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # volumeName tying this PCV to a specific PV
  volumeName: preprov-pv-cephfs-01
---
apiVersion: v1
kind: Pod
metadata:
  name: csicephfs-preprov-demo-pod
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: csi-cephfs-pvc-preprov
        readOnly: false
```

 To get logs, use `kubectl -n <namespace> logs <pod name>`
error info:
```
error while running "VolumeBinding" filter plugin for pod "csicephfs-preprov-demo-pod": pod has unbound immediate PersistentVolumeClaims
MountVolume.MountDevice failed for volume "preprov-pv-cephfs-01" : rpc error: code = Internal desc = missing required field monitors
```

**Environment**:
* OS (e.g. from /etc/os-release): centos
* Kernel (e.g. `uname -a`): kernel-3.10.0-1062.9.1.el7.x86_64
* Rook version (use `rook version` inside of a Rook Pod): v1.2.0
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.5-0
* Kubernetes version (use `kubectl version`): v1.17.0
