### ISSUE TITLE
Rook ceph agent not scheduled on OKD 3.11 master nodes

### ISSUE THREAD

**Issue by beelzetron** [rook/rook#4560]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The rook-ceph-agent DaemonSet generates pod definition with `node-selector: node-role.kubernetes.io/compute=true` although this is not defined in the DaemonSet itself.
```
# oc get ds rook-ceph-agent
NAME              DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
rook-ceph-agent   14        11        11        0            11          <none>          20d
```
```
# oc get pod rook-ceph-agent-2tcr2 -o yaml --export
apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: rook-ceph
  creationTimestamp: null
  generateName: rook-ceph-agent-
  labels:
    app: rook-ceph-agent
    controller-revision-hash: "547923670"
    pod-template-generation: "8"
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: rook-ceph-agent
    uid: 4605259b-12b5-11ea-87c5-00505690061e
  selfLink: /api/v1/namespaces/rook-ceph/pods/rook-ceph-agent-2tcr2
spec:
  containers:
  - args:
    - ceph
    - agent
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: AGENT_MOUNT_SECURITY_MODE
      value: Any
    - name: ROOK_ENABLE_SELINUX_RELABELING
      value: "true"
    - name: ROOK_ENABLE_FSGROUP
      value: "true"
    image: rook/ceph:v1.1.8
    imagePullPolicy: IfNotPresent
    name: rook-ceph-agent
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /flexmnt
      name: flexvolume
    - mountPath: /dev
      name: dev
    - mountPath: /sys
      name: sys
    - mountPath: /lib/modules
      name: libmodules
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: rook-ceph-system-token-x7tpz
      readOnly: true
  dnsPolicy: ClusterFirst
  hostNetwork: true
  imagePullSecrets:
  - name: rook-ceph-system-dockercfg-6nfpk
  nodeName: computeossvilcdb01.test.comune.bologna.it
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000150000
    seLinuxOptions:
      level: s0:c12,c9
  serviceAccount: rook-ceph-system
  serviceAccountName: rook-ceph-system
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: ""
    name: flexvolume
  - hostPath:
      path: /dev
      type: ""
    name: dev
  - hostPath:
      path: /sys
      type: ""
    name: sys
  - hostPath:
      path: /lib/modules
      type: ""
    name: libmodules
  - name: rook-ceph-system-token-x7tpz
    secret:
      defaultMode: 420
      secretName: rook-ceph-system-token-x7tpz
status:
  phase: Pending
  qosClass: BestEffort
```

**Expected behavior:**
The rook-ceph-agent daemonset generates pod definition without node-selector and the rook-ceph-agent pods get scheduled on all the cluster nodes.

**How to reproduce it (minimal and precise):**

Install OKD 3.11 cluster, deploy rook ceph 1.1.8 on it, enable flexvolume and check on which nodes the rook-ceph-agent get scheduled

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS: `CentOS Linux 7 (Core)`
* Kernel (e.g. `uname -a`): `3.10.0-1062.4.3.el7.x86_64`
* Cloud provider or hardware configuration: virtual machines on vmware
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.1.8`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)`
* Kubernetes version (use `kubectl version`):
```
openshift v3.11.0+0b8be0c-343
kubernetes v1.11.0+d4cacc0
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OKD (OpenShift)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_OK`
