### ISSUE TITLE
external access to block image

### ISSUE THREAD

**Issue by vahide** [rook/rook#4601]
How can access externally to block image in rook?
I made NodePort for mon-X services and create client in ceph to access block storage but when client want to connect and execute "rbd --pool PoolName ls", error "**connect protocol error (bad banner) on peer**" is printed. client edit /etc/ceph/ceph.conf mon_host with masterIP and NodePorts. 
In general, as object store external access using rgw-external, how can access externally to block storage in rook? 
NodePort type service yaml file is:

```
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mon-X-external-rbd
  namespace: rook-ceph
  labels:
    app: rook-ceph-mon
    ceph_daemon_id: X
    mon: X
    mon_cluster:  rook-ceph
    rook_cluster: rook-ceph
spec:
  type: NodePort
  ports:
  - name: msgr1
    port: 6789
    protocol: TCP
    targetPort: 6789
  - name: msgr2
    port: 3300
    protocol: TCP
    targetPort: 3300
nodePort: 30002
  selector:
    app: rook-ceph-mon
    ceph_daemon_id: X
    mon: X
    mon_cluster:  rook-ceph
    rook_cluster: rook-ceph
  sessionAffinity: None

```
