### ISSUE TITLE
cephcluster changes don't persist

### ISSUE THREAD

**Issue by cann0nf0dder** [rook/rook#4644]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When updating ceph cluster via updated cluster.yaml or via kubectl patch, the changes disappear after a minute or so when trying to set osd memory limits, similar for other changes.
**Expected behavior:**
1. Deploy ceph cluster 
2. Update cluster.yaml osd memory limit (or update it via kubectl patch or via kubectl edit)
3. Query cephcluster and see the changes, query it again in 2-3 minutes to make sure those persist
**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: xxx 
    allowUnsupported: false
  dashboard:
    enabled: true
    port: 8443
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  mgr:
   modules:
  mon:
    count: 5
    allowMultiplePerNode: false
  osd:
    limits:
      memory: "2048Mi"
  monitoring: {}
  network:
    hostNetwork: false
      #provider: ""
      #selectors: null
  rbdMirroring:
    workers: 0
  storage:
    useAllDevices: false
    useAllNodes: true
    deviceFilter: ^sd[^sda]
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
      osdsPerDevice: "1"
      storageClassDeviceSets: null
```

New part added to the yaml since deployment:
```
  osd:
    limits:
      memory: "2048Mi"

```
* Operator's logs, if necessary
No new entries in the operator log after making the updates
* Crashing pod(s) logs, if necessary

OS (e.g. from /etc/os-release):
cat /etc/os-release
NAME=Fedora
VERSION="28 (Twenty Eight)"
ID=fedora
VERSION_ID=28
Kernel (e.g. uname -a):
Linux atl1vmtk8sb5n001 4.19.50-coreos-r1 #1 SMP Mon Jul 1 19:07:03 -00 2019 x86_64 x86_64 x86_64 GNU/Linux
Cloud provider or hardware configuration: on-prem
Rook version (use rook version inside of a Rook Pod):
1.1.2
Storage backend version (e.g. for ceph do ceph -v):
14.2.4
Kubernetes version (use kubectl version):
1.15.6
Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Tectonic/Coreos
Storage backend status (e.g. for Ceph use ceph health in the Rook Ceph toolbox): ceph
