### ISSUE TITLE
Ceph Dashboard not loading with nginx-ingress

### ISSUE THREAD

**Issue by onedr0p** [rook/rook#4649]
Hi, I am new here. I am trying to reverse proxy the Ceph Dashboard but running into an issue. The dashboard is returning the favicon and the HTML header loads however the body is a whitepage. The javascript files do not load they receive a 504.  When I run `kubectl proxy` I can get to the dashboard and log in fine on my local network.

Other services in my cluster do the reverse proxying just fine.

My SSL is terminated outside of my Kubernetes cluster on a Raspberry Pi with HAProxy and with a origin cert from Cloudflare. I have disabled SSL in the `cluster.yaml` and made sure to reverse proxy without TLS in my nginx ingress definition.

Chrome is giving errors on resources like this: 

```
https://rook.$DOMAIN/polyfills.f31db31652a3fd9f4bca.js
net::ERR_HTTP2_PROTOCOL_ERROR 200"
```

Please let me know if there is anything else I need to provide. Logs are not showing anything useful. Does anyone see any reason why this is not working?

**Is this a bug report or feature request?**
* Bug Report

**Expected behavior:**
Nginx ingress to reverse proxy the Ceph Dashboard

**File(s) to submit**:

Here is my ingress definition (domain redacted):

```yaml
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: rook.$DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: rook-ceph-mgr-dashboard
          servicePort: 7000
```

and here is my cluster definition:

```yaml
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.5-20191210
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
    port: 7000
    ssl: false
  # cluster level storage configuration and selection
  resources:
    api:
      requests:
          cpu: 25m
          memory: 250Mi
      limits:
        memory: 512Mi
    mgr:
      requests:
          cpu: 50m
          memory: 300Mi
      limits:
        memory: 512Mi
    mon:
      requests:
          cpu: 35m
          memory: 800Mi
      limits:
        memory: 1024Mi
    osd:
      requests:
        cpu: "35m"
        memory: "2048Mi"
      limits:
        memory: "4096Mi"
    rbdmirror:
      requests:
          cpu: 25m
          memory: 250Mi
      limits:
        memory: 512Mi
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter: 
    location: 
    config:
      metadataDevice: 
      osdsPerDevice: "1"
    nodes:
      - name: "k3s-worker-a"
        devices:
          - name: "nvme0n1"
      - name: "k3s-worker-b"
        devices:
          - name: "nvme0n1"
      - name: "k3s-worker-c"
        devices:
          - name: "nvme0n1"
```

**Environment**:
* OS: Ubuntu 19.10
* Kernel: Linux k3s-worker-c 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Homelab with Intel NUCs
* Rook version: v1.2.1
* Storage backend version: 14.2.5
* Kubernetes version: v1.17.0
* Kubernetes cluster type: k3s
* Storage backend status: HEALTH_OK

**Comment by dkrizic** [comment]
I configured it like this (a while ago)

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph
spec:
  rules:
  - host: ceph.XXXXX
    http:
      paths:
      - backend:
          serviceName: rook-ceph-mgr-dashboard
          servicePort: https-dashboard
        path: /
```

Maybe it helps.

**Comment by onedr0p** [comment]
Adding the following seemed to fix the issue, I don't understand why since I have `ssl: false` in my cluster config, odd.

```yaml
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
```
