### ISSUE TITLE
Can't create TPR when RBAC is enabled

### ISSUE THREAD

**Issue by dimm0** [rook/rook#469]
Trying to install in tectonic k8s

`kubectl create -f rook-operator.yaml` - works fine

Then:
```
Dmitrys-MBP-2:kubernetes dimm$ kubectl create -f rook-cluster.yaml
error: unable to recognize "rook-cluster.yaml": no matches for rook.io/, Kind=Cluster
```

Errors in log:

```
2017-03-10 06:40:14.972140 I | operator: creating rook TPR
2017-03-10 06:40:14.973132 E | operator: failed to create tpr. failed to create TPR. failed to create rook third party resources. the server does not allow access to the requested resource (post thirdpartyresources.extensions). retrying...
```

**Comment by travisn** [comment]
Tectonic has RBAC enabled by default, which means the operator doesn't have sufficient permissions. Can you try adding the following when the operator is started?
```
kind: ClusterRoleBinding
metadata:
  name: rook-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
```
For reference, the etcd operator also had this issue and has documented more of what is necessary to run with RBAC enabled. https://github.com/coreos/etcd-operator/issues/619. We need to similarly document this issue for Rook.

**Comment by dimm0** [comment]
Thanks for the quick response!

I've got:
```
$ kubectl create -f rbac_perm.yaml
error: unable to recognize "rbac_perm.yaml": no matches for /, Kind=ClusterRoleBinding
```

**Comment by dimm0** [comment]
Needed to add the api version. Here's the working one:
```
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: rook-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
```

**Comment by travisn** [comment]
oops, copy/paste error on my part. Good catch!

**Comment by bzub** [comment]
With bootkube I found the admin role equivalent is named `cluster-admin`.  The docs might suggest running `kubectl get clusterrolebinding` to find what to put for `roleRef.name` in the `ClusterRoleBinding` manifest.
```console
$ kubectl get clusterrolebinding
NAME                                       AGE
cluster-admin                              10h
rook-operator                              11m
system:basic-user                          10h
system:controller:replication-controller   10h
system:default-sa                          10h
system:discovery                           10h
system:node                                10h
system:node-proxier                        10h
```

```yaml
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: rook-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
```
