### ISSUE TITLE
Can't unmount cephFS flexVolumes

### ISSUE THREAD

**Issue by dimm0** [rook/rook#4695]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Can't unmount flexVolumes (kill pods) with cephFS after upgrading to 1.2.1

**Expected behavior:**
Volumes can be unmounted clearly

**How to reproduce it (minimal and precise):**
Mount a cephFS folder using flexVolume specification

Logs from kubelet:

`Jan 15 17:35:36 k8s-gpu-02.calit2.optiputer.net kubelet[5308]: E0115 17:35:36.970037    5308 nestedpendingoperations.go:270] Operation for "\"flexvolume-ceph.rook.io/rook/bef2d24e-5917-4f66-9c11-8dde6d1e2fc3-fs-store\" (\"bef2d24e-5917-4f66-9c11-8dde6d1e2fc3\")" failed. No retries permitted until 2020-01-15 17:35:38.969648396 -0800 PST m=+33960.895594722 (durationBeforeRetry 2s). Error: "UnmountVolume.TearDown failed for volume \"fs-store\" (UniqueName: \"flexvolume-ceph.rook.io/rook/bef2d24e-5917-4f66-9c11-8dde6d1e2fc3-fs-store\") pod \"bef2d24e-5917-4f66-9c11-8dde6d1e2fc3\" (UID: \"bef2d24e-5917-4f66-9c11-8dde6d1e2fc3\") : unmount command failed, status: Failure, reason: Unmount volume at mount dir /var/lib/kubelet/pods/bef2d24e-5917-4f66-9c11-8dde6d1e2fc3/volumes/ceph.rook.io~rook/fs-store failed: failed to get persistent volume fs-store: persistentvolumes \"fs-store\" not found"`

**Environment**:
* OS (e.g. from /etc/os-release):
CentOS 7.7
* Kernel (e.g. `uname -a`):
5.3.2
* Cloud provider or hardware configuration:
baremetal
* Rook version (use `rook version` inside of a Rook Pod):
1.2.1
* Storage backend version (e.g. for ceph do `ceph -v`):
14.2.5
* Kubernetes version (use `kubectl version`):
1.17.1

**Comment by dimm0** [comment]
Btw there's no persistent volume, it's defined straight in the pod spec:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-pod3
  namespace: dimm
spec:
  containers:
  - name: vol-container
    image: ubuntu
    args: ["sleep", "36500000"]
    volumeMounts:
    - mountPath: /examplevol
      name: fs-store
  restartPolicy: Never
  volumes:
    - flexVolume:
        driver: ceph.rook.io/rook
        fsType: ceph
        options:
          clusterNamespace: rook
          fsName: nautilusfs
          mountSecret: ceph-fs-secret
          mountUser: dimm
          path: /dimm
      name: fs-store
```
