### ISSUE TITLE
Ceph prepareosd cpu request/limit doesn't seem to get set 

### ISSUE THREAD

**Issue by rmartinez3** [rook/rook#4713]
So not sure if doing something wrong but have been trying to set higher cpu for prepareosd since node im trying to set osd has so many lvm devices . Want to provide more cpu . 

cephcluster crd for resources was set like this 
```
  resources:
    mgr:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi
    mon:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    osd:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi
    prepareosd:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi
```

the job was created with correct memory however only have 1m of cpu

```
        resources:
          limits:
            cpu: 1m
            memory: 2Gi
          requests:
            cpu: 1m
            memory: 2Gi
```

when resources were set to empty limit/requests for cpu and memory was set to 0 

Not sure if anyone else has seen this. Will try to change things around to see if it still occurs
