### ISSUE TITLE
Config generation of discovered ips for each OSD satisfying IP CIDR

### ISSUE THREAD

**Issue by hightoxicity** [rook/rook#4716]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

It would be a must have to be able to set (optionally) on the CephCluster CRD two fields:
- public_network
- cluster_network

Those two configs fields would represent the same one as public network and cluster network in the ceph config global section (that is to say network adresses in the CIDR notation).

Rook could thanks to that try to discover the interface ip addresses to use for each OSD, checking the ip is contained in one of those CIDRs.

Today I am doing something like this using rook-config-override configmap and running an ansible pass outside rook logic.

Generated config looks like:

```
kubectl get cm rook-config-override -n rook-ceph -o yaml
apiVersion: v1
data:
  config: |
    [global]
    public network = 10.205.0.0/16
    cluster network = 10.206.0.0/16
    [osd.1]
    cluster addr = 10.206.0.1
    public ip = 10.205.0.1
    [osd.2]
    cluster addr = 10.206.0.1
    public ip = 10.205.0.1
    [osd.3]
    cluster addr = 10.206.0.1
    public ip = 10.205.0.1
```

The ansible playbook fragment I am currently using to do this looks like the following one:

```
- name: Ceph tasks
  hosts: "{{ groups['kube-master'][0] }}"
  become: true
  tasks:
    - name: Get nodes OSDs
      shell: "kubectl get pods -n rook-ceph --field-selector spec.nodeName={{ item.1 }} -l app=rook-ceph-osd -o=jsonpath='{range .items[*]}{\"[osd.\"}{.metadata.labels.ceph-osd-id}{\"]\\ncluster addr = {{ hostvars[item.1].netplan_configuration.network.ethernets.eno50.addresses[0] | ipaddr('address') }}\\npublic ip = {{ hostvars[item.1].ansible_host }}\\n\"}{end}'"
      changed_when: False
      register: nodes_osds
      with_indexed_items: "{{ groups['all'] }}"
    - k8s_raw:
        state: present
        resource_definition: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: rook-config-override
            namespace: "{{ item }}"
          data:
            config: |
              [global]
              public network = {{ ceph_public_network }}
              cluster network = {{ ceph_cluster_network }}
          {{ nodes_osds.results | map(attribute='stdout') | map('regex_replace', '(.*)', '    \1') | join('\n') | regex_replace('\\n', "\n") }}
        kubeconfig: /etc/kubernetes/admin.conf
        verify_ssl: no
      with_items:
        - "rook-ceph"
```

**What is use case behind this feature:**

It is a good practice with ceph to use two distinct networks, one for ceph client exchanges with the OSDs, another one for data sync between OSDs.

**Environment**:
