### ISSUE TITLE
Improve CSI storageclass user experience

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#4743]
A StorageClass definition using Rook-Ceph's CSI driver looks like below. There are a few points I will comment inline below using `# <<< comment >>>` 

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
    # clusterID is the namespace where the rook cluster is running
    # If you change this namespace, also change the namespace below where the secret namespaces are defined
    # <<< this seems like a poor user experience; why doesn't Rook use the clusterID parameter to inform the '-secret-namespace` params below? >>>
    clusterID: rook-ceph

# ...

    # The secrets contain Ceph admin credentials. These are generated automatically by the operator
    # in the same namespace as the cluster.
    # <<< Rook already knows what secrets it creates and (with clusterID) where it creates them. 
    #     Why can't Rook use what it already knows to inform this instead of making the user do it? >>>
    csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
    csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
    csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
    csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
    # Specify the filesystem type of the volume. If not specified, csi-provisioner
    # will set default as `ext4`.
    csi.storage.k8s.io/fstype: ext4

# ...
```

Tagging @Madhu-1

**Comment by Madhu-1** [comment]
@BlaineEXE the below info will not be passed to CSI driver by external provisioner

```yaml
    csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
    csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
    csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
    csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
```
external-provisioner and external-resizer will fetch the secret from the name and namespace provided in storage class and sends it to the CSI if we want to implement our own logic to fetch the keys we will be bypassing the CSI spec.
