### ISSUE TITLE
rook-operator: Inconsistent host/location in crushmap

### ISSUE THREAD

**Issue by bzub** [rook/rook#478]
The OSD pod's hostname is currently being propagated to represent the `host` type buckets in the crushmap.  So when an OSD pod is recreated, a new randomly generated host bucket is created.  It should be consistent, ideally a name attached to the storage node like the hostname/nodeName.

For now here's how I work around this, by modifying the `osd` DaemonSet.  I set the hostname based on `nodeName` before running rookd.

```yaml
# [...]
      containers:
      - command:
        - /bin/sh
        - -c
        - 'sleep 5;
          echo $(HOSTNAME) > /etc/hostname;
          hostname -F /etc/hostname;
          /usr/bin/rookd
            osd
            --data-dir=/var/lib/rook
            --mon-endpoints=mon2=10.2.247.8:6790,mon0=10.2.136.140:6790,mon1=10.2.6.9:6790
            --cluster-name=rookcluster
            --data-devices=^sd '
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
# [...]
```
