### ISSUE TITLE
EdgeFS: Can't specify more than one path in spec.storage.directories

### ISSUE THREAD

**Issue by st0ne-c0ld** [rook/rook#4782]
* Bug Report

**Deviation from expected behavior:**

when specify more than one directory in spec.storage.directories

```apiVersion: edgefs.rook.io/v1
kind: Cluster
metadata:
  name: rook-edgefs
  namespace: rook-edgefs
spec:
  edgefsImageName: edgefs/edgefs:1.2.156
  dataDirHostPath: /mnt/1/rook-edge-conf
  serviceAccount: rook-edgefs-cluster
  dashboard: {}
  storage:
    useAllNodes: true
    useAllDevices: false
    directories:
      - path: "/mnt/1/rook-edge"
      - path: "/mnt/2/rook-edge"
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "rook-edge-storage"
              operator: Exists
```

we get error message on 'target' pods:

```create Pod rook-edgefs-target-0 in StatefulSet rook-edgefs-target failed error: Pod "rook-edgefs-target-0" is invalid: spec.volumes[5].name: Duplicate value: "rook-edge"```
[operator_logs.txt](https://github.com/rook/rook/files/4135059/operator_logs.txt)

**Expected behavior:**

Targets are able to use more than one directory.

**How to reproduce it (minimal and precise):**
create cluster with more than one path entry in .spec.storage.directories

```
apiVersion: edgefs.rook.io/v1
kind: Cluster
metadata:
  name: rook-edgefs
  namespace: rook-edgefs
spec:
  edgefsImageName: edgefs/edgefs:1.2.156
  dataDirHostPath: /mnt/1/rook-edge-conf
  serviceAccount: rook-edgefs-cluster
  dashboard: {}
  # cluster level storage configuration and selection
  storage:
    useAllNodes: true
    useAllDevices: false
    directories:
      - path: "/mnt/1/rook-edge"
      - path: "/mnt/2/rook-edge"
  # placement
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "rook-edge-storage"
              operator: Exists

```

**Environment**:
* OS (e.g. from /etc/os-release): Oracle Linux Server 7.7
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: Rancher 2.3.4, 3 cp nodes + 3 worker nodes
* Rook version (use `rook version` inside of a Rook Pod):  rook/edgefs:v1.2.2
* Storage backend version (e.g. for ceph do `ceph -v`): edgefs
* Kubernetes version (use `kubectl version`) :v1.17.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher 2.3.4
