### ISSUE TITLE
Define ObjectBucket and ObjectBucketClaim CRDs with sensible support for get and list verbs

### ISSUE THREAD

**Issue by ron1** [rook/rook#4807]
* Bug Report

Define ObjectBucket and ObjectBucketClaim CRDs with sensible RBAC to enable support for get and list verbs

**Deviation from expected behavior:**
A user is unable to get and list ObjectBuckets. A user with view privileges in the namespace is unable to get and list ObjectBucketClaims in that namespace.

**Expected behavior:**
A user is able to get and list ObjectBuckets. A user with view privileges in the namespace is able to get and list ObjectBucketClaims in that namespace.

**How to reproduce it (minimal and precise):**
Install Rook-Ceph 1.2.2
As cluster admin, create a namespace and an OBC within the namespace
As a user with view privileges in the namespace, attempt to list ObjectBuckets and ObjectBucketClaims without success

**Environment**: 
* OS (e.g. from /etc/os-release): rhel 7.7
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: 
* Rook version (use `rook version` inside of a Rook Pod): 1.1.6
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.4-20190917
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift 3.11
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK, osd: 8 osds: 7 up, 7 in

**Comment by travisn** [comment]
@ron1 As I think through this more, my impression is that creating this RBAC should be left up to the admin to create. The only place Rook currently defines RBAC is really in `common.yaml` (or the helm chart). The operator doesn't have privs to create RBAC at runtime. 

Do you have an example of the RBAC that you would expect Rook to create? It's a possibility if we statically included it in `common.yaml`, but that would likely have to open it up to all namespaces instead of just a `RoleBinding` to a single namespace.

**Comment by ron1** [comment]
@travisn I was thinking out-of-the-box edit and view roles would be defined as described here for the example CronTabs CRD: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles.

Specifically, ObjectBucket would have a ClusterRole aggregate-object-bucket-view and ObjectBucketClaim would have both ClusterRoles aggregate-object-bucket-claim-view and aggregate-object-bucket-claim-edit. These would be defined in the Rook-Ceph common.yaml. Since the security semantics  for these two CRDs are well understood, I was think it would make sense to define these roles out-of-the-box.

**Comment by travisn** [comment]
Ah, good point to use the aggregation rules to give the view and edit capabilities.

**Comment by ron1** [comment]
Pls reopen

**Comment by huerlisi** [comment]
I just wanted a user that has a role binding to `editor` in a namespace to create claims, but run into this issue.

I've looked at what well established helm charts like certmanager do and they actually provide such a role binding that provides aggregation.

I got it working with the resource definition below for `ObjectBucketClaim`. But when trying the same thing with `ObjectBucket`, it failed to list them as it seems to call the APIs in the cluster scope. For my use case that's fine (I just want to create claims in a helm chart for my application), and guess it's already worth to integrate this in rooks helm chart.

Here's what the descriptions I used. They are based on the ones from certmanager. I haven't checked (didn't know how:-) which exact verbs are supported and went with the basic "CRUD" ones.

**objectbucket-view.yaml:**
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: objectbucket-view
rules:
- apiGroups:
  - objectbucket.io
  resources:
  - objectbucketclaims
  verbs:
  - get
  - list
  - watch
```

**objectbucket-edit.yaml:**
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: objectbucket-edit
rules:
- apiGroups:
  - objectbucket.io
  resources:
  - objectbucketclaims
  verbs:
  - create
  - update
  - patch
  - delete
  - deletecollection
```
