### ISSUE TITLE
PVC OSD deployment clobbered by non-PVC OSD deployment

### ISSUE THREAD

**Issue by michael-db** [rook/rook#4812]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

With a cluster config including
```
...
  storage:
    useAllNodes: true
    useAllDevices: true
    config:
      databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      osdsPerDevice: "1" # this value can be overridden at the node or device level
    storageClassDeviceSets:
    - name: set1
      count: 0
...
```
change count: to 1 so that a PVC backed OSD deployment is launched.
Within a minute, the new OSD deployment with the appropriate persistentVolumeClaim without a persistentVolumeClaim, which looks just like any of the local device (i.e., non-PVC) deployments, which of course crashes.

From inspection of the source code, what is happening is that handleStatusConfigMapStatus() calls startOSDDaemonsOnNode() for the node on which the PVC-backed OSD is launched (there are other, non-PVC OSDs on the node). That function assumes it is dealing only with non-PVC OSDs and replaces the PVC-backed OSD with a non-PVC one.

If I understand correctly, this is a problem only when there is a mixture of PVC-backed and non-PVC-backed OSDs (I haven't tried with yet with an exclusively PVC-backed cluster), but that is a scenario that is supposed to work.

**Expected behavior:**

The PVC-backed OSD should not be interfered with by the code managing non-PVC OSDs.

**How to reproduce it (minimal and precise):**
as above

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):Ubuntu 18.04.3
* Kernel (e.g. `uname -a`):Linux ubuntu2 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):1.2.3
* Storage backend version (e.g. for ceph do `ceph -v`):14.2.6
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
