### ISSUE TITLE
Unable to see kubelet_volume_* metrics in Prometheus

### ISSUE THREAD

**Issue by onedr0p** [rook/rook#4834]
**Is this a bug report or feature request?**
* Bug Report

I am unable to see kubelet_volume_* metrics in Prometheus, what can I do to help debug my issue?

**Expected behavior:**

Should be able to view kubelet_volume_* metrics in Prometheus

**How to reproduce it:**

Deploy rook-ceph Helm chart on k3s

**File(s) to submit**:

My entire rook-ceph deployment is [here](https://github.com/onedr0p/k3s-gitops/tree/master/deployments/rook-ceph)

The image below shows that I am getting some metrics, but not `kubelet_volume_` ones.

```
rook-ceph/csi-metrics/0 (16/16 up) 
rook-ceph/csi-metrics/1 (16/16 up)
```

![image](https://user-images.githubusercontent.com/213795/73982472-4be0b000-4902-11ea-8662-9c55dbfaf6c2.png)

**Environment**:
* OS: Ubuntu 18.04.03
* Kernel: 4.15.0-76-generic
* Cloud provider or hardware configuration: Bare metal NUCs
* Rook version: v1.2.3
* Storage backend version: ceph version 14.2.6
* Kubernetes version: v1.17.2
* Kubernetes cluster type: k3s
* Storage backend status: HEALTH_OK

**Comment by onedr0p** [comment]
Are these `kubelet_volume_` metrics part of this ServiceAccount? I am just having a hard time figuring out how to debug my issue and the documentation is pretty limited.

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csi-metrics
  namespace: rook-ceph
  labels:
    team: rook
spec:
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: csi-metrics
  endpoints:
    - port: csi-http-metrics
      path: /metrics
      interval: 5s
    # comment csi-grpc-metrics realated information if csi grpc metrics is not enabled
    - port: csi-grpc-metrics
      path: /metrics
      interval: 5s
```
