### ISSUE TITLE
[solved] rook-edgefs-mgr failed to start

### ISSUE THREAD

**Issue by mritd** [rook/rook#4851]
**Is this a bug report or feature request?**

not a bug

**Deviation from expected behavior:**

rook-edgefs-mgr failed to start

**Expected behavior:**

rook-edgefs-mgr is running

**How to reproduce it (minimal and precise):**

OS version： ubuntu 18.04
Kubernetes verison: 1.17.2
Deploy tool: kubeadm

I followed the quick start document and everything worked fine after creating the operator; when creating cluster.yaml, I observed that the rook-edgefs-mgr pod kept outputting logs `Waiting for target to initialize ccow.json file ...` Finally The pod started to restart constantly

I found this line of logs in the container's [startup script](https://github.com/Nexenta/edgefs/blob/master/scripts/edgefs-start.sh#L116), but I don't know why this happens, what component of ccow.json was created ...

**File(s) to submit**:

I just modified cluster.yaml. On each virtual machine node, I created a 100G disk and mounted it to the `/ rook` directory.

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

The configuration file is too long, I first paste the results of `git diff` (the complete configuration is below)

```diff
diff --git a/cluster/examples/kubernetes/edgefs/cluster.yaml b/cluster/examples/kubernetes/edgefs/cluster.yaml
index 76da2db8..f60e2e89 100644
--- a/cluster/examples/kubernetes/edgefs/cluster.yaml
+++ b/cluster/examples/kubernetes/edgefs/cluster.yaml
@@ -130,8 +130,8 @@ metadata:
 spec:
   edgefsImageName: edgefs/edgefs:latest  # specify version here, i.e. edgefs/edgefs:1.2.117 etc
   serviceAccount: rook-edgefs-cluster
-  dataDirHostPath: /var/lib/edgefs
-  #dataVolumeSize: 10Gi
+  dataDirHostPath: /rook
+  #dataVolumeSize: 80Gi
   #devicesResurrectMode: "restoreZapWait"
   #dashboard:
   #  localAddr: 10.3.30.75
@@ -142,18 +142,18 @@ spec:
   #    broker: "enp2s0f0"
   #skipHostPrepare: true
   #maxContainerCapacity: 132Ti
-  #sysRepCount: 1                  # SystemReplicationCount [1..n](default is 3)
-  #failureDomain: "device"         # Cluster's failureDomain ["device", "host", "zone"] (default is "host")
+  sysRepCount: 2                  # SystemReplicationCount [1..n](default is 3)
+  failureDomain: "host"         # Cluster's failureDomain ["device", "host", "zone"] (default is "host")
   #trlogProcessingInterval: 2      # set transaction log processing interval to 2s to speed up ISGW Link delivery
   #trlogKeepDays: 2                # keep up to 2 days of transaction log interval batches to reduce local storage overhead
   #useHostLocalTime: true
   storage: # cluster level storage configuration and selection
     useAllNodes: true
   #  directories:
-  #  - path: /mnt/disks/ssd0
+  #  - path: /data
   #  - path: /mnt/disks/ssd1
   #  - path: /mnt/disks/ssd2
-    useAllDevices: true
+    useAllDevices: false
   #  config:
   #    mdReserved: "30"            # allocate only 30% of offloaded SSD/NVMe slice for Metadata, the rest keep for BCache
   #    hddReadAhead: "2048"        # speed up reads of 2MB+ chunks of HDD (offload use case)
@@ -179,13 +179,13 @@ spec:
   #    config: # configuration can be specified at the node level which overrides the cluster level config
   #      rtPLevelOverride: 8
   #      zone: "2"  # defines failure domain's zone number for specific node(node3074ub16)
-  #resources:
-  #  limits:
-  #    cpu: "2"
-  #    memory: "4096Mi"
-  #  requests:
-  #    cpu: "2"
-  #    memory: "4096Mi"
+  resources:
+    limits:
+      cpu: "1"
+      memory: "1024Mi"
+    requests:
+      cpu: "1"
+      memory: "2048Mi"
   # A key value list of annotations
   #annotations:
   #  all:
```

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: rook-edgefs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-edgefs-cluster
  namespace: rook-edgefs
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-edgefs-cluster
  namespace: rook-edgefs
rules:
- apiGroups: [""]
  resources: ["configmaps", "endpoints"]
  verbs: [ "get", "list", "watch", "create", "update", "delete" ]
- apiGroups: ["edgefs.rook.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: [ "get", "list" ]
- apiGroups: ["extensions"]
  resources: ["deployments/scale"]
  verbs: [ "get", "update" ]
---
# Allow the operator to create resources in this cluster's namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-edgefs-cluster-mgmt
  namespace: rook-edgefs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-edgefs-cluster-mgmt
subjects:
- kind: ServiceAccount
  name: rook-edgefs-system
  namespace: rook-edgefs-system
---
# Allow the pods in this namespace to work with configmaps
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-edgefs-cluster
  namespace: rook-edgefs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-edgefs-cluster
subjects:
- kind: ServiceAccount
  name: rook-edgefs-cluster
  namespace: rook-edgefs
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
  allowedCapabilities:
  - '*'
  hostPID: true
  hostIPC: true
  hostNetwork: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privileged-psp-user
rules:
- apiGroups:
  - apps
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-edgefs-system-psp
  namespace: rook-edgefs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp-user
subjects:
- kind: ServiceAccount
  name: rook-edgefs-system
  namespace: rook-edgefs-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-edgefs-cluster-psp
  namespace: rook-edgefs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp-user
subjects:
- kind: ServiceAccount
  name: rook-edgefs-cluster
  namespace: rook-edgefs
---
apiVersion: edgefs.rook.io/v1
kind: Cluster
metadata:
  name: rook-edgefs
  namespace: rook-edgefs
spec:
  edgefsImageName: edgefs/edgefs:latest  # specify version here, i.e. edgefs/edgefs:1.2.117 etc
  serviceAccount: rook-edgefs-cluster
  dataDirHostPath: /rook
  #dataVolumeSize: 80Gi
  #devicesResurrectMode: "restoreZapWait"
  #dashboard:
  #  localAddr: 10.3.30.75
  #network: # cluster level networking configuration
  #  provider: host
  #  selectors:
  #    server: "enp2s0f0"
  #    broker: "enp2s0f0"
  #skipHostPrepare: true
  #maxContainerCapacity: 132Ti
  sysRepCount: 2                  # SystemReplicationCount [1..n](default is 3)
  failureDomain: "host"         # Cluster's failureDomain ["device", "host", "zone"] (default is "host")
  #trlogProcessingInterval: 2      # set transaction log processing interval to 2s to speed up ISGW Link delivery
  #trlogKeepDays: 2                # keep up to 2 days of transaction log interval batches to reduce local storage overhead
  #useHostLocalTime: true
  storage: # cluster level storage configuration and selection
    useAllNodes: true
  #  directories:
  #  - path: /data
  #  - path: /mnt/disks/ssd1
  #  - path: /mnt/disks/ssd2
    useAllDevices: false
  #  config:
  #    mdReserved: "30"            # allocate only 30% of offloaded SSD/NVMe slice for Metadata, the rest keep for BCache
  #    hddReadAhead: "2048"        # speed up reads of 2MB+ chunks of HDD (offload use case)
  #    rtVerifyChid: "0"           # may improve CPU utilization
  #    lmdbPageSize: "32768"       # larger value can improve stream operations
  #    lmdbMdPageSize: "4096"      # smaller value can improve metadata offload device utilization
  #    useMetadataOffload: "true"  # enable use of SSD device as metadata offload
  #    useBCache: "true"           # enable SSD cache device and read-cache
  #    useBCacheWB: "true"         # enable SSD write-cache
  #    useMetadataMask: "0x7d"     # all metadata on SSD except second level manifests
  #    rtPLevelOverride: "4"       # enable large device partitioning, only needed if automatic not working
  #    sync: "0"                   # highest performance, consistent on pod/software failures, not-consistent on power failures
  #    useAllSSD: "true"           # use only SSDs during deployment
  #    zone: "1"                   # defines failure domain's zone number for all edgefs nodes
  #  nodes:
  #  - name: node3071ub16
  #  - name: node3072ub16
  #  - name: node3073ub16
  #  - name: node3074ub16 # node level storage configuration
  #    devices: # specific devices to use for storage can be specified for each node
  #    - name: "sdb"
  #    - name: "sdc"
  #    config: # configuration can be specified at the node level which overrides the cluster level config
  #      rtPLevelOverride: 8
  #      zone: "2"  # defines failure domain's zone number for specific node(node3074ub16)
  resources:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "1"
      memory: "2048Mi"
  # A key value list of annotations
  #annotations:
  #  all:
  #    key: value
  #  mgr:
  #  prepare:
  #  target:
  #placement:
  #  all:
  #    nodeAffinity:
  #      requiredDuringSchedulingIgnoredDuringExecution:
  #        nodeSelectorTerms:
  #        - matchExpressions:
  #          - key: nodekey
  #            operator: In
  #            values:
  #            - edgefs-target
  #    tolerations:
  #    - key: taintKey
  #      operator: Exists
```

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.4
* Kernel (e.g. `uname -a`): Linux k8s51.node 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: pve vm(kvm)
* Rook version (use `rook version` inside of a Rook Pod): v1.2.4
* Storage backend version (e.g. for ceph do `ceph -v`): 
* Kubernetes version (use `kubectl version`): 1.17.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): pve kvm cluster
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
