### ISSUE TITLE
non-privileged containers can't write to volumes....... for 20-30 minutes... then they can...

### ISSUE THREAD

**Issue by pmbsa** [rook/rook#4855]
**Is this a bug report or feature request?**
* Bug Report

**Bug Report**

**Deviation from expected behavior:**
When a pod consumes a PVC and the volume is mounted, the volume is owned by root:myuser and has the permissions set to drwxr-s---. myuser has no mermissions to write to the volume. HOWEVER, after a period of time (around 20-30 minutes) there is some form of intervension and the permissions change to drwxrws---

**How to reproduce it (minimal and precise):**
On kubernetes cluster (Rancher based in my case) with rook deployed as described in the docs (and the example rook csi storage class created), create a PersistentVolume claim, and a pod that mounts the volume. exec or rsh into the pod and attempt to write to the mounted volume.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: csi-cephfs
  labels:
    app: PaulTest
    provider: fabric8
    version: 0.1-SNAPSHOT
    group: com.pmb.test.service.paul
  name: paultest-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-cephfs

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    organisation: LBG
    app: PaulTest
    provider: fabric8
    version: 0.1-SNAPSHOT
    group: com.pmb.test.service.paul
  name: paultest
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: paultest
      provider: fabric8
      group: com.pmb.test.service.paul
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: paultest
        organisation: LBG
        provider: fabric8
        version: 0.1-SNAPSHOT
        group: com.pmb.test.service.paul
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              key: paultest_spring_profiles_active
              name: service-config
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: my.docker.registry.cloud.test.group/pffc/dpa/services/paultest:0.1-8798238
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /paultest/actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: paultest
        ports:
        - containerPort: 9080
          name: service-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /paultest/actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        resources:
          limits:
            memory: 500Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.1"
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /microservice/data/paultest/h2
          name: paultest-pvc
        - mountPath: /microservice/data/paultest/logs
          name: paultest-pvc
      securityContext:
        fsGroup: 1500
        runAsGroup: 1500
        runAsUser: 1500
      volumes:
      - name: paultest-pvc
        persistentVolumeClaim:
          claimName: paultest-pvc
          readOnly: false
```

**Environment**:
* OS (e.g. from /etc/os-release):
```cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```
* Kernel (e.g. uname -a`):
```
[adddpppd~]# uname -a
Linux adddpppd3.10.0-1062.9.1.el7.x86_64 #1 SMP Mon Dec 2 08:31:54 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

* Cloud provider or hardware configuration:
Hardware configuration 

* Storage backend version (e.g. for ceph do `ceph -v`):
```
ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)
```

* Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Rancher

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox]
```
HEALTH_OK
```
