### ISSUE TITLE
Metadata pool is used for data instead of the Erasure Coded one

### ISSUE THREAD

**Issue by cr1cr1** [rook/rook#4988]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Erasure-coded pool is not used, instead the metadata pool is

**Expected behavior:**
EC pool to be used for data instead of metadata replicated pool.
Listing pools and images, the EC pool has no image, no space used. But the metadata pool is using actual space for data, there is an image created once the k8s pod is up
Either this behavior is wrong, because `dataPool` directive in the Storage Classs was ignored, or there is something hidden and not straightforward.

**How to reproduce it (minimal and precise):**

- Created a storage class using https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/rbd/storageclass-ec.yaml
- 2 pools were created, one EC and one replicated for metadata
- A simple K8S statefulset (e.g. docker registry) was created to use the storage class above:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: docker-registry
    release: test
  name: test-docker-registry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
      release: test
  serviceName: test-docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
        release: test
    spec:
      containers:
      - env:
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        image: registry:2.7
        imagePullPolicy: Always
        name: docker-registry
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/registry
          name: test-docker-registry
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
  volumeClaimTemplates:
  - metadata:
      name: test-docker-registry
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: rook-ceph-block
      volumeMode: Filesystem
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.3 LTS
* Kernel (e.g. `uname -a`): Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: 4CPU, 8 GB RAM, 20GB ceph raw volumes
* Rook version (use `rook version` inside of a Rook Pod): 1.2.5
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)
* Kubernetes version (use `kubectl version`):
    - Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:34:02Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
    - Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Local cluster created with kubespray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

@rami-abu
