### ISSUE TITLE
Ceph: mon: default pod anti-affinity applied multiple times

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#4998]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The Rook operator applies the default rule to spread monitors over different hosts multiple times.
mon-a: has one instance
mon-b: has two instances
mon-c: has 3 instances

This is likely due to an unnecessary `append` in a for loop.

This applies to the mon canary deployments only and not the regular mon deployments

**Expected behavior:**

Each mon deployment/podSpec should only have the default rule applied once

**Comment by travisn** [comment]
A report elsewhere of the same issue. The mons were restarted during an orchestration. The mons had this antiaffinity before the operator restart:
```
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-mon
          topologyKey: failure-domain.beta.kubernetes.io/zone
        weight: 100
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: rook-ceph-mon
        topologyKey: kubernetes.io/hostname
      - labelSelector:
          matchLabels:
            app: rook-ceph-mon
        topologyKey: kubernetes.io/hostname
      - labelSelector:
          matchLabels:
            app: rook-ceph-mon
        topologyKey: kubernetes.io/hostname
      - labelSelector:
          matchLabels:
            app: rook-ceph-mon
        topologyKey: kubernetes.io/hostname
      - labelSelector:
          matchLabels:
            app: rook-ceph-mon
        topologyKey: kubernetes.io/hostname
      - labelSelector:
          matchLabels:
            app: rook-ceph-mon
        topologyKey: kubernetes.io/hostname
      - labelSelector:
          matchLabels:
            app: rook-ceph-mon
        topologyKey: kubernetes.io/hostname
```
And all of those were removed except one after the orchestration update.
