### ISSUE TITLE
failed to load OSD map for epoch after ODS hostname change

### ISSUE THREAD

**Issue by megian** [rook/rook#5041]
* Bug Report

**Bug Report**

Upgraded from a Rook version 0.9.1, after upgrading from Rook 1.2.4 to 1.2.6 the OSDs haven't been upgraded. After enabling

storage:
  useAllNodes: true

the ODS got redeployed and it looks like the used hostname by osd-prepare have changed in the meantime

     rook-ceph-osd-1-69445564f4-fl6xt (host)
     rook-ceph-osd-0-554b65d589-qzctk (host)

     n-asdfd.example.com (host)
        up osd.0 (osd)

     n-opsdd.example.com (host)
        up osd.1 (osd)

     n-wasdf.example.com (host)
        up osd.2 (osd)

     rook-ceph-osd-2-797bd8cf99-b94bc (host)

this caused the ODS didn't came up again, because they got recreated with the same OSD ID but an different crushmap hostname. The OSDs crashed with the error message "failed to load OSD map for epoch 3856, got 0 bytes", which indicates, according [1], that the OSD have been reregistered by the osd-prepare job.

[1] https://tracker.ceph.com/issues/24423

Example of the crushmap osd.0. osd.0 was configured in the host section rook-ceph-osd-0-554b65d589-qzctk and is now in n-asdfd.example.com:
...
host rook-ceph-osd-0-554b65d589-qzctk {
	id -13		# do not change unnecessarily
	id -14 class ssd		# do not change unnecessarily
	# weight 0.000
	alg straw2
	hash 0	# rjenkins1
}
host n-asdfd.example.com {
	id -15		# do not change unnecessarily
	id -16 class ssd		# do not change unnecessarily
	# weight 0.078
	alg straw2
	hash 0	# rjenkins1
	item osd.0 weight 0.078
}
...

To be specific: The K8s node hostnames never changed in the meantime. I think it's a new behavior of the Rook operator.

**Expected behavior:**

Under absolutely NO circumstances a OSD should be registered, if the directory - in this case /var/lib/rook/osd0 - is already in use. If osd-preapre is running at the same time, it can cause downtime up to dataloss.

**Deviation from expected behavior:**

If an unknown OSD setup as this hostname change is detected, the operator must stop with an error and let the admin fix it or redeploy the OSDs.

**How to reproduce it (minimal and precise):**
Seems only be reproachable when upgrading from an older Rook version.

*Cluster CR*
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.8
  crashCollector:
    disable: false
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement: {}
  external:
    enable: false
  mgr:
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    allowMultiplePerNode: true
    count: 3
  monitoring: {}
  network:
    hostNetwork: false
    provider: ""
    selectors: null
  rbdMirroring:
    workers: 0
  removeOSDsIfOutAndSafeToRemove: false
  storage:
    config: null
    nodes:
    - config: null
      name: n-asdfd.example.com
      resources: {}
    - config: null
      name: n-opsdd.example.com
      resources: {}
    - config: null
      name: n-wasdf.example.com
      resources: {}
```
