### ISSUE TITLE
Update ceph examples for the ease of creating a ceph cluster in a different namespace

### ISSUE THREAD

**Issue by binoue** [rook/rook#5049]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The users who want to create a ceph cluster in a different namespace from the operator's one (rook-ceph) will be able to understand what part they need to modify.

**What is use case behind this feature:**
Current [`common.yaml`](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/common.yaml) uses only one namespace rook-ceph for both a ceph cluster and the rook operator.
It has comments for creating a ceph cluster in a different namespace, however, I think there remains a lot of work to modify `common.yaml`.

For example,
the `rolebinding` below has two references to the rook-ceph namespace, but only one (metadata.namespace) of them needs to be modified.
The other one (subjects[0].namespace) indicates where the common service account `rook-ceph-system` resides, so it does not need to be modified.

```yaml
# Allow the operator to create resources in this cluster's namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-cluster-mgmt
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-cluster-mgmt
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph
```

Therefore, I think it is worth doing either of the following.

1. modify `common.yaml` based on the assumption that a ceph cluster is created in a different namespace from that used by the rook operator.
1. keep `common.yaml` as-is and create a new file containing cluster-specific resources with a different namespace.

If this feature request is acceptable, I would be happy to create a pull request for this issue.
