### ISSUE TITLE
rook-ceph fails to support device name with colon

### ISSUE THREAD

**Issue by DifanZhang** [rook/rook#5056]
When using /dev/disk/by-path in Ceph CRD configuration on NVMe disks, the device path will have colon in it, which breaks the `parseDevices` in `cmd/rook/ceph/osd.go`.

Example configuration:

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: <HIDDEN>
  mon:
    count: 3
  network:
    hostNetwork: true
  storage:
    nodes:
    - devices:
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:3d:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:3e:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:3f:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:40:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:b1:00.0-nvme-1
      name: stor2.HIDDEN
    - devices:
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:3d:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:3e:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:3f:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:40:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:b1:00.0-nvme-1
      name: stor3.HIDDEN
    - devices:
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:3d:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:3e:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:3f:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:40:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:b1:00.0-nvme-1
      name: stor4.HIDDEN
    - devices:
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:3d:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:3e:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:3f:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:40:00.0-nvme-1
      - config:
          osdsPerDevice: '4'
        name: /dev/disk/by-path/pci-0000:b1:00.0-nvme-1
      name: stor1.HIDDEN
    useAllDevices: false
    useAllNodes: false
```

rook-ceph version: 1.2.6

```
[20-03-19 12:41:31] h:~> kubectl -n rook-ceph logs rook-ceph-osd-prepare-stor1.HIDDEN-xlxcm
failed to parse device list ("/dev/disk/by-path/pci-0000:3d:00.0-nvme-1:4:::,/dev/disk/by-path/pci-0000:3e:00.0-nvme-1:4:::,/dev/disk/by-path/pci-0000:3f:00.0-nvme-1:4:::,/dev/disk/by-path/pci-0000:40:00.0-nvme-1:4:::,/dev/disk/by-path/pci-0000:b1:00.0-nvme-1:4:::"): error parsing count from devices ("/dev/disk/by-path/pci-0000:3d:00.0-nvme-1:4:::,/dev/disk/by-path/pci-0000:3e:00.0-nvme-1:4:::,/dev/disk/by-path/pci-0000:3f:00.0-nvme-1:4:::,/dev/disk/by-path/pci-0000:40:00.0-nvme-1:4:::,/dev/disk/by-path/pci-0000:b1:00.0-nvme-1:4:::"): strconv.Atoi: parsing "3d": invalid syntax
```
