### ISSUE TITLE
ceph: operator does not update all deployments if update causes existing mon to fail

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#5057]
**Is this a bug report or feature request?**
* Bug Report

The Rook-Ceph operator does not continue updating deployments if a deployment update causes a mon to fall out of quorum after its deployment is updated.

**Deviation from expected behavior:**

In the scenario I tested, I did the following:
- start with a 6+ node cluster
- install Rook-Ceph without any node affinities set
- note where mons are scheduled, and label nodes without mons `ceph-mon-ssd=true`
- add the following affinity to the CephCluster CR
  ```yaml
  placement:
    mon:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: ceph-mon-ssd
              operator: In
              values:
              - "true"
  ```
- observe that Rook updates one of the mon deployments
  - the deployment falls into the "Pending" state, because its node affinity is now set such that it cannot run on its current node due to `ceph-mon-ssd=true` not being present on the node
  - in my test cluster, this was mon C
  - the other 2 mons (A and B in my example) are not updated because C does not become "Ready"
- after the mon health check timeout (a long time), mon D is scheduled, and the "Pending" mon (C in my example) is removed & deleted
- Rook-Ceph operator continues to check the health of the Ceph cluster, but it does not try to update the deployments for the original 2 mons (A and B in my example)

**Expected behavior:**

Rook-Ceph should continue attempting to update deployments if an update fails because the user configuration causes a mon failure during the update.

**Comment by BlaineEXE** [comment]
If the operator pod is deleted (operator restarted), Rook will attempt to update another mon deployment, which falls into "Pending" state just as noted in the original issue.

**Comment by haoxiaoci** [comment]
is this bug gonna be fixed? 
i have this problem too.

**Comment by travisn** [comment]
What exactly is your issue? If the operator stops reconciling when a mon goes out of quorum, it seems like a good thing, otherwise it might cause more outages if it continues with a bad update.

**Comment by haoxiaoci** [comment]
1. add a nodeaffinity in cephcluster spec(i add a nodeaffinity which is on k8s control node. and all ceph mons are in k8s work node).
2. scale rook-operator replicas to 0
3. scale one of the mon replicas to 0, and exec ceph mon rm <mon.id> in rook-ceph-tools
4. scale rook-operator replicas to 1

after operator startup, the other two mon: one got pending, one is still running, ceph monitor only one was working.
i shouldn't execute `ceph mon rm <mon.id>`  right?  when i skip this step. mons'update seems fine.

**Comment by travisn** [comment]
So you're trying to move the mons from the worker nodes to the control nodes? You might need a different approach, such as expand to 5 or 7 mons so you can get mons on the new nodes, then reduce the count back to 3, and scale down the mons on the worker nodes. Check also the topic on [failover mons](https://rook.io/docs/rook/v1.15/Storage-Configuration/Advanced/ceph-mon-health/#failing-over-a-monitor).

**Comment by haoxiaoci** [comment]
yes, i'm trying move ceph mons from k8s worker node to k8s control nodes. i have read rook doc failover mons.
i got some ideas.
1. add a control node nodeaffinity in cephcluster spec.
2. wait rook operator update ceph mons update. 
i keep 3 mons. i have tried this approach many times. it works fine. Is there a greater risk than your approach?

**Comment by travisn** [comment]
Sounds good if this approach is working for you, I just wasn't clear on your approach.

**Comment by haoxiaoci** [comment]
1. add nodeaffinity, in cephcluster spec:
```
    mon:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: Exists

```
2. wait，rook-ceph-operator update mon（update failed, failover, schedule a new one, delete old one..and so on three times)，then i got three new mons.

maybe i should do this `ceph mon rm <mon.id>` , and let's ceph-cluster-controller deal with it. is that clear?
