### ISSUE TITLE
CephFS: Automatic resizing of PersistentVolumes with CSI 2.0 driver does not automatically adjust quota limit

### ISSUE THREAD

**Issue by sebschlue** [rook/rook#5092]
**Is this a bug report or feature request?**
* Bug Report

Tags: ceph, csi

**Deviation from expected behavior:**

CephFS: Automatic resizing of PersistentVolumes with CSI 2.0 driver does not automatically adjust quota limit.

**Expected behavior:**
With CSI 2.0 driver, automatic resizing of PersistentVolumes should "just work".

**How to reproduce it (minimal and precise):**
Install a fresh Ceph cluster release 1.2. Here is the shortened script, I can provide the full script if necessary.

````
git clone --single-branch --branch release-1.2 https://github.com/rook/rook.git
cd rook/cluster/examples/kubernetes/ceph
kubectl apply -f common.yaml
kubectl apply -f operator.yaml
kubectl apply -f cluster.yaml
kubectl apply -f toolbox.yaml
kubectl apply -f filesystem.yaml
ceph osd pool set myfs-data0 pg_num 32
ceph osd pool set myfs-metadata pg_num 32
kubectl apply -f csi/cephfs/storageclass.yaml
````
Then create a PVC and example application (in my case this was Apache HTTPD as DaemonSet where the Pods share the htdocs dir. Here is the PVC, I can provide DaemonSet definition if necessary.

````
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-httpd-htdocs-pvc
  namespace: httpd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cephfs
````

This PVC and its PV now could not be enlarged, so I need to upgrade to CSI 2.0 driver:

Grab cluster/examples/kubernetes/ceph/upgrade-from-v1.2-apply.yaml from master branch and kubectl-apply it.

Update rook ceph operator image version: `kubectl -n rook-ceph set image deploy/rook-ceph-operator rook-ceph-operator=rook/ceph:v1.2.6`

Add the following deployment env variables to rook ceph operator deployment object:

```
env:
    - name: ROOK_CSI_CEPH_IMAGE
        value: "quay.io/cephcsi/cephcsi:v2.0.0"
    - name: ROOK_CSI_REGISTRAR_IMAGE
        value: "quay.io/k8scsi/csi-node-driver-registrar:v1.2.0"
    - name: ROOK_CSI_PROVISIONER_IMAGE
        value: "quay.io/k8scsi/csi-provisioner:v1.4.0"
    - name: ROOK_CSI_SNAPSHOTTER_IMAGE
        value: "quay.io/k8scsi/csi-snapshotter:v1.2.2"
    - name: ROOK_CSI_ATTACHER_IMAGE
        value: "quay.io/k8scsi/csi-attacher:v2.1.0"
    - name: ROOK_CSI_RESIZER_IMAGE
        value: "quay.io/k8scsi/csi-resizer:v0.4.0"
```

I have done this by running `kubectl -n rook-ceph edit deployment rook-ceph-operator` and then editing the yaml.

Then, after all Pods have been restarted, I try to enlarge volume:

First of all, I verify that there is an actual limit by writing a 10GB file (which works) and then writing an additional 1GB file, which does not work, I get "Disk quota exceeded" message. For far, so good.

Before enlargement:

`````
persistentvolume/pvc-1402087d-ef7f-4cbb-855a-4aa08546df31        10Gi       RWX            Delete           Bound    httpd/cephfs-httpd-htdocs-pvc                      csi-cephfs                                       3d22h

persistentvolumeclaim/cephfs-httpd-htdocs-pvc   Bound    pvc-1402087d-ef7f-4cbb-855a-4aa08546df31   10Gi       RWX            csi-cephfs     3d22h
`````

df from inside of Pod:

````
10.43.182.84:6789,10.43.220.98:6789,10.43.46.213:6789:/volumes/csi/csi-vol-a490c790-6acd-11ea-bcfc-b24e4d64b58c/b0d0b73d-0d97-4322-9954-3db10dd40e2d ceph      10G     0   10G   0% /usr/local/apache2/htdocs
````

New enlarge by editing PVC: `kubectl -n httpd edit pvc cephfs-httpd-htdocs-pvc`

At first glance, it seems to work:

````
persistentvolume/pvc-1402087d-ef7f-4cbb-855a-4aa08546df31        20Gi       RWX            Delete           Bound    httpd/cephfs-httpd-htdocs-pvc                      csi-cephfs                                       3d23h

persistentvolumeclaim/cephfs-httpd-htdocs-pvc   Bound    pvc-1402087d-ef7f-4cbb-855a-4aa08546df31   20Gi       RWX            csi-cephfs     3d23h
`````
But quota limit is still in place: I still get "Disk quota exceeded" message and df still shows size of 10GB instead of 20GB.

Restarting the Pods does not help.

````
$ kubectl -n httpd describe pvc cephfs-httpd-htdocs-pvc
Name:          cephfs-httpd-htdocs-pvc
Namespace:     httpd
StorageClass:  csi-cephfs
Status:        Bound
Volume:        pvc-1402087d-ef7f-4cbb-855a-4aa08546df31
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"cephfs-httpd-htdocs-pvc","namespace":"httpd"},"spec...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      20Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    httpd-9f9vm
               httpd-fjjhg
               httpd-nqkjr
               httpd-q2nw7
               httpd-tbhfd
               httpd-xltv4
Events:
  Type     Reason                  Age    From                                            Message
  ----     ------                  ----   ----                                            -------
  Normal   Resizing                6m31s  external-resizer rook-ceph.cephfs.csi.ceph.com  External resizer is resizing volume pvc-1402087d-ef7f-4cbb-855a-4aa08546df31
  Warning  ExternalExpanding       6m31s  volume_expand                                   Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   VolumeResizeSuccessful  6m29s  external-resizer rook-ceph.cephfs.csi.ceph.com  Resize volume succeeded
````

I have already figured out that I need to run the following command:

````
ceph fs subvolume resize myfs csi-vol-a490c790-6acd-11ea-bcfc-b24e4d64b58c 21474836480 csi
````

But this should be done automatically.

**File(s) to submit**:

No files to submit, all infomation included inline in "How to reproduce" paragraph.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7

* Kernel (e.g. `uname -a`): Linux node1.localdomain 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:

* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.2.6
go: go1.11

* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)

* Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3+k3s1", GitCommit:"5b17a175ce333dfb98cb8391afeb1f34219d9275", GitTreeState:"clean", BuildDate:"2020-02-27T07:28:53Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3+k3s1", GitCommit:"5b17a175ce333dfb98cb8391afeb1f34219d9275", GitTreeState:"clean", BuildDate:"2020-02-27T07:28:53Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

k3s

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

HEALTH_OK
