### ISSUE TITLE
[Cassandra] Annotations not being propagated to pods 

### ISSUE THREAD

**Issue by ar-mi6** [rook/rook#5097]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After defining the annotation in cluster.yaml, the annotations are not propagated to the pods.
**Expected behavior:**
Annotations should propagate to the pods
**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary 
[cluster.txt](https://github.com/rook/rook/files/4389698/cluster.txt)
```
# Source: cassandra-cluster/templates/cluster.yaml
apiVersion: cassandra.rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-cassandra
  namespace: "2269-cassandra"
  labels: 
    app.kubernetes.io/name: cassandra-cluster
    helm.sh/chart: cassandra-cluster-0.1.0
    app.kubernetes.io/instance: cassandra-cluster
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/component: rook-cassandra-member
spec:
  version: 3.11.6
  mode: cassandra
  repository: cassandra
  annotations:
    sidecar.istio.io/inject: "false"
  datacenter:
    name: local
    racks:
        - name: local-0
          members: 1
          jmxExporterConfigMapName: cassandra-jmx-exporter
          storage:
            volumeClaimTemplates:
              - metadata:
                  name: local-0-data
                spec:
                  accessModes: [ "ReadWriteOnce" ]
                  storageClassName: 
                  resources:
                    requests:
                      storage: 1Gi
          resources:
            limits:
              cpu: 800m
              memory: 800Mi
            requests:
              cpu: 800m
              memory: 800Mi
          annotations:
            sidecar.istio.io/inject: "false"
          placement:
        - name: local-1
          members: 1
          jmxExporterConfigMapName: cassandra-jmx-exporter
          storage:
            volumeClaimTemplates:
              - metadata:
                  name: local-1-data
                spec:
                  accessModes: [ "ReadWriteOnce" ]
                  storageClassName: 
                  resources:
                    requests:
                      storage: 1Gi
          resources:
            limits:
              cpu: 800m
              memory: 800Mi
            requests:
              cpu: 800m
              memory: 800Mi
          annotations:
            sidecar.istio.io/inject: "false"
          placement:
```
* Operator's logs, if necessary 
[cassandra-operator.log](https://github.com/rook/rook/files/4389703/cassandra-operator.log)

``` 2020-03-26 19:51:26.238197 I | cassandra-controller: handling cluster object: (*v1alpha1.Cluster)(0xc000afc000)({
 TypeMeta: (v1.TypeMeta) &TypeMeta{Kind:,APIVersion:,},
 ObjectMeta: (v1.ObjectMeta) &ObjectMeta{Name:rook-cassandra,GenerateName:,Namespace:2269-cassandra,SelfLink:/apis/cassandra.rook.io/v1alpha1/namespaces/2269-cassandra/clusters/rook-cassandra,UID:8d14e9f4-f5bf-4762-b750-4758bd2d7743,ResourceVersion:334777,Generation:7,CreationTimestamp:2020-03-26 19:50:01 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{app.kubernetes.io/component: rook-cassandra-member,app.kubernetes.io/instance: cassandra-cluster,app.kubernetes.io/managed-by: Tiller,app.kubernetes.io/name: cassandra-cluster,app.kubernetes.io/version: 1.0,helm.sh/chart: cassandra-cluster-0.1.0,},Annotations:map[string]string{kubectl.kubernetes.io/last-applied-configuration: {"apiVersion":"cassandra.rook.io/v1alpha1","kind":"Cluster","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"rook-cassandra-member","app.kubernetes.io/instance":"cassandra-cluster","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"cassandra-cluster","app.kubernetes.io/version":"1.0","helm.sh/chart":"cassandra-cluster-0.1.0"},"name":"rook-cassandra","namespace":"2269-cassandra"},"spec":{"annotations":{"sidecar.istio.io/inject":"false"},"datacenter":{"name":"local","racks":[{"annotations":{"sidecar.istio.io/inject":"false"},"jmxExporterConfigMapName":"cassandra-jmx-exporter","members":1,"name":"local-0","placement":null,"resources":{"limits":{"cpu":"800m","memory":"800Mi"},"requests":{"cpu":"800m","memory":"800Mi"}},"storage":{"volumeClaimTemplates":[{"metadata":{"name":"local-0-data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":null}}]}},{"annotations":{"sidecar.istio.io/inject":"false"},"jmxExporterConfigMapName":"cassandra-jmx-exporter","members":1,"name":"local-1","placement":null,"resources":{"limits":{"cpu":"800m","memory":"800Mi"},"requests":{"cpu":"800m","memory":"800Mi"}},"storage":{"volumeClaimTemplates":[{"metadata":{"name":"local-1-data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":null}}]}}]},"mode":"cassandra","repository":"cassandra","version":"3.11.6"}}
,},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,ManagedFields:[],},
 Spec: (v1alpha1.ClusterSpec) {
  Annotations: (v1alpha2.Annotations) <nil>,
  Version: (string) (len=6) "3.11.6",
  Repository: (*string)(0xc000b07be0)((len=9) "cassandra"),
  Mode: (v1alpha1.ClusterMode) (len=9) "cassandra",
  Datacenter: (v1alpha1.DatacenterSpec) {
   Name: (string) (len=5) "local",
   Racks: ([]v1alpha1.RackSpec) (len=2 cap=2) {
    (v1alpha1.RackSpec) {
     Name: (string) (len=7) "local-0",
     Members: (int32) 1,
     ConfigMapName: (*string)(<nil>),
     Storage: (v1alpha2.StorageScopeSpec) {
      Nodes: ([]v1alpha2.Node) <nil>,
      UseAllNodes: (bool) false,
      NodeCount: (int) 0,
      Config: (map[string]string) <nil>,
      Selection: (v1alpha2.Selection) {
       UseAllDevices: (*bool)(<nil>),
       DeviceFilter: (string) "",
       DevicePathFilter: (string) "",
       Devices: ([]v1alpha2.Device) <nil>,
       Directories: ([]v1alpha2.Directory) <nil>,
       VolumeClaimTemplates: ([]v1.PersistentVolumeClaim) (len=1 cap=1) {
        (v1.PersistentVolumeClaim) &PersistentVolumeClaim{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:local-0-data,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,ManagedFields:[],},Spec:PersistentVolumeClaimSpec{AccessModes:[ReadWriteOnce],Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeName:,Selector:nil,StorageClassName:nil,VolumeMode:nil,DataSource:nil,},Status:PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[],},}
       }
      },
      VolumeSources: ([]v1alpha2.VolumeSource) <nil>,
      StorageClassDeviceSets: ([]v1alpha2.StorageClassDeviceSet) <nil>
     },
     Annotations: (v1alpha2.Annotations) <nil>,
     Placement: (*v1alpha2.Placement)(<nil>),
     Resources: (v1.ResourceRequirements) &ResourceRequirements{Limits:ResourceList{cpu: {{800 -3} {<nil>} 800m DecimalSI},memory: {{838860800 0} {<nil>}  BinarySI},},Requests:ResourceList{cpu: {{800 -3} {<nil>} 800m DecimalSI},memory: {{838860800 0} {<nil>}  BinarySI},},}
    },
    (v1alpha1.RackSpec) {
     Name: (string) (len=7) "local-1",
     Members: (int32) 1,
     ConfigMapName: (*string)(<nil>),
     Storage: (v1alpha2.StorageScopeSpec) {
      Nodes: ([]v1alpha2.Node) <nil>,
      UseAllNodes: (bool) false,
      NodeCount: (int) 0,
      Config: (map[string]string) <nil>,
      Selection: (v1alpha2.Selection) {
       UseAllDevices: (*bool)(<nil>),
       DeviceFilter: (string) "",
       DevicePathFilter: (string) "",
       Devices: ([]v1alpha2.Device) <nil>,
       Directories: ([]v1alpha2.Directory) <nil>,
       VolumeClaimTemplates: ([]v1.PersistentVolumeClaim) (len=1 cap=1) {
        (v1.PersistentVolumeClaim) &PersistentVolumeClaim{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:local-1-data,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,ManagedFields:[],},Spec:PersistentVolumeClaimSpec{AccessModes:[ReadWriteOnce],Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeName:,Selector:nil,StorageClassName:nil,VolumeMode:nil,DataSource:nil,},Status:PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[],},}
       }
      },
      VolumeSources: ([]v1alpha2.VolumeSource) <nil>,
      StorageClassDeviceSets: ([]v1alpha2.StorageClassDeviceSet) <nil>
     },
     Annotations: (v1alpha2.Annotations) <nil>,
     Placement: (*v1alpha2.Placement)(<nil>),
     Resources: (v1.ResourceRequirements) &ResourceRequirements{Limits:ResourceList{cpu: {{800 -3} {<nil>} 800m DecimalSI},memory: {{838860800 0} {<nil>}  BinarySI},},Requests:ResourceList{cpu: {{800 -3} {<nil>} 800m DecimalSI},memory: {{838860800 0} {<nil>}  BinarySI},},}
    }
   }
  },
  SidecarImage: (*v1alpha1.ImageSpec)(<nil>)
 },
 Status: (v1alpha1.ClusterStatus) {
  Racks: (map[string]*v1alpha1.RackStatus) (len=2) {
   (string) (len=7) "local-0": (*v1alpha1.RackStatus)(0xc0009ec840)({
    Members: (int32) 1,
    ReadyMembers: (int32) 1,
    Conditions: ([]v1alpha1.RackCondition) <nil>
   }),
   (string) (len=7) "local-1": (*v1alpha1.RackStatus)(0xc0009ec860)({
    Members: (int32) 1,
    ReadyMembers: (int32) 0,
    Conditions: ([]v1alpha1.RackCondition) <nil>
   })
  }
 }
})
2020-03-26 19:51:26.239402 I | cassandra-controller: 2269-cassandra/rook-cassandra - Successfully cleaned up cluster.
2020-03-26 19:51:26.239712 I | cassandra-controller: Syncing ClusterHeadlessService `rook-cassandra-client` for Cluster `rook-cassandra`
2020-03-26 19:51:26.239767 I | cassandra-controller: Syncing MemberServices for Cluster `rook-cassandra`
2020-03-26 19:51:26.240412 I | cassandra-controller: Updating Status for cluster rook-cassandra in namespace 2269-cassandra
2020-03-26 19:51:26.283813 I | cassandra-controller: Successfully synced '2269-cassandra/rook-cassandra'
```
**Environment**:
* OS (e.g. from /etc/os-release): macOS Catalina 10.15.4
* Kernel (e.g. `uname -a`): Darwin 19.4.0
* Cloud provider or hardware configuration: docker for mac
* Rook version (use `rook version` inside of a Rook Pod): 1.2.6
* Storage backend version (e.g. for ceph do `ceph -v`): Cassandra 3.11.6
* Kubernetes version (use `kubectl version`): 1.15.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): docker for mac
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by gyant** [comment]
Confirmed having the same issue:

```
apiVersion: cassandra.rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-cassandra
spec:
  version: 3.11.1
  mode: cassandra
  # A key/value list of annotations
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  datacenter:
    name: us-east-2
    racks:
      - name: us-east-2a
        members: 1
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        configMapName: cassandra-dev
        storage:
          volumeClaimTemplates:
          - metadata:
              name: rook-cassandra-data
            spec:
              storageClassName: gp2-encrypted
              resources:
                requests:
                  storage: 500Gi
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/region
                    operator: In
                    values:
                      - us-east-2
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - us-east-2a
```

Resulting pod:

```
Name:           rook-cassandra-us-east-2-us-east-2a-0
Namespace:      default
Priority:       0
Node:           ip-10-11-0-76.us-east-2.compute.internal/10.11.0.76
Start Time:     Thu, 21 May 2020 17:38:58 -0700
Labels:         app=rook-cassandra
                app.kubernetes.io/managed-by=rook-cassandra-operator
                app.kubernetes.io/name=rook-cassandra
                cassandra.rook.io/cluster=rook-cassandra
                cassandra.rook.io/datacenter=us-east-2
                cassandra.rook.io/rack=us-east-2a
                controller-revision-hash=rook-cassandra-us-east-2-us-east-2a-644449bc54
                statefulset.kubernetes.io/pod-name=rook-cassandra-us-east-2-us-east-2a-0
Annotations:    kubernetes.io/psp: eks.privileged
                prometheus.io/port: 9180
                prometheus.io/scrape: true
...
```

**Comment by gyant** [comment]
I've tracked the issue back to the golang cache client:

https://github.com/rook/rook/blob/master/pkg/client/listers/cassandra.rook.io/v1alpha1/cluster.go#L85-L94

This is returning null annotations:

```
{
    "metadata": {
        "name": "rook-cassandra",
        "namespace": "default",
        "selfLink": "/apis/cassandra.rook.io/v1alpha1/namespaces/default/clusters/rook-cassandra",
        "uid": "f576796a-f702-45be-aa75-9e4364a8eac5",
        "resourceVersion": "198209",
        "generation": 6,
        "creationTimestamp": "2020-05-22T05:21:55Z",
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"cassandra.rook.io/v1alpha1\",\"kind\":\"Cluster\",\"metadata\":{\"annotations\":{},\"name\":\"rook-cassandra\",\"namespace\":\"default\"},\"spec\":{\"all\":{\"annotations\":{\"cluster-autoscaler.kubernetes.io/safe-to-evict\":\"false\"}},\"annotations\":{\"all\":{\"cluster-autoscaler.kubernetes.io/safe-to-evict\":\"false\"},\"cluster-autoscaler.kubernetes.io/safe-to-evict\":\"false\"},\"datacenter\":{\"name\":\"us-east-2\",\"racks\":[{\"annotations\":{\"cluster-autoscaler.kubernetes.io/safe-to-evict\":\"false\"},\"configMapName\":\"cassandra-dev\",\"members\":1,\"name\":\"us-east-2a\",\"placement\":{\"nodeAffinity\":{\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchExpressions\":[{\"key\":\"failure-domain.beta.kubernetes.io/region\",\"operator\":\"In\",\"values\":[\"us-east-2\"]},{\"key\":\"failure-domain.beta.kubernetes.io/zone\",\"operator\":\"In\",\"values\":[\"us-east-2a\"]}]}]}}},\"resources\":{\"limits\":{\"cpu\":\"500m\",\"memory\":\"512Mi\"},\"requests\":{\"cpu\":\"500m\",\"memory\":\"512Mi\"}},\"storage\":{\"volumeClaimTemplates\":[{\"metadata\":{\"name\":\"rook-cassandra-data\"},\"spec\":{\"resources\":{\"requests\":{\"storage\":\"500Gi\"}},\"storageClassName\":\"gp2-encrypted\"}}]}},{\"configMapName\":\"cassandra-dev\",\"members\":1,\"name\":\"us-east-2b\",\"placement\":{\"nodeAffinity\":{\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchExpressions\":[{\"key\":\"failure-domain.beta.kubernetes.io/region\",\"operator\":\"In\",\"values\":[\"us-east-2\"]},{\"key\":\"failure-domain.beta.kubernetes.io/zone\",\"operator\":\"In\",\"values\":[\"us-east-2b\"]}]}]}}},\"resources\":{\"limits\":{\"cpu\":\"500m\",\"memory\":\"512Mi\"},\"requests\":{\"cpu\":\"500m\",\"memory\":\"512Mi\"}},\"storage\":{\"volumeClaimTemplates\":[{\"metadata\":{\"name\":\"rook-cassandra-data\"},\"spec\":{\"resources\":{\"requests\":{\"storage\":\"500Gi\"}},\"storageClassName\":\"gp2-encrypted\"}}]}},{\"configMapName\":\"cassandra-dev\",\"members\":1,\"name\":\"us-east-2c\",\"placement\":{\"nodeAffinity\":{\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchExpressions\":[{\"key\":\"failure-domain.beta.kubernetes.io/region\",\"operator\":\"In\",\"values\":[\"us-east-2\"]},{\"key\":\"failure-domain.beta.kubernetes.io/zone\",\"operator\":\"In\",\"values\":[\"us-east-2c\"]}]}]}}},\"resources\":{\"limits\":{\"cpu\":\"500m\",\"memory\":\"512Mi\"},\"requests\":{\"cpu\":\"500m\",\"memory\":\"512Mi\"}},\"storage\":{\"volumeClaimTemplates\":[{\"metadata\":{\"name\":\"rook-cassandra-data\"},\"spec\":{\"resources\":{\"requests\":{\"storage\":\"500Gi\"}},\"storageClassName\":\"gp2-encrypted\"}}]}}]},\"mode\":\"cassandra\",\"version\":\"3.11.1\"}}\n"
        }
    },
    "spec": {
        "Annotations": null,
        "version": "3.11.1",
        "mode": "cassandra",
        "datacenter": {
            "name": "us-east-2",
            "racks": [
                {
                    "name": "us-east-2a",
                    "members": 1,
                    "configMapName": "cassandra-dev",
                    "storage": {
                        "config": null,
                        "volumeClaimTemplates": [
                            {
                                "metadata": {
                                    "name": "rook-cassandra-data",
                                    "creationTimestamp": null
                                },
                                "spec": {
                                    "resources": {
                                        "requests": {
                                            "storage": "500Gi"
                                        }
                                    },
                                    "storageClassName": "gp2-encrypted"
                                },
                                "status": {}
                            }
                        ],
                        "storageClassDeviceSets": null
                    },
                    "Annotations": null,
                    "placement": {
                        "nodeAffinity": {
                            "requiredDuringSchedulingIgnoredDuringExecution": {
                                "nodeSelectorTerms": [
                                    {
                                        "matchExpressions": [
                                            {
                                                "key": "failure-domain.beta.kubernetes.io/region",
                                                "operator": "In",
                                                "values": [
                                                    "us-east-2"
                                                ]
                                            },
                                            {
                                                "key": "failure-domain.beta.kubernetes.io/zone",
                                                "operator": "In",
                                                "values": [
                                                    "us-east-2a"
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        }
                    },
                    "resources": {
                        "limits": {
                            "cpu": "500m",
                            "memory": "512Mi"
                        },
                        "requests": {
                            "cpu": "500m",
                            "memory": "512Mi"
                        }
                    }
                },
                {
                    "name": "us-east-2b",
                    "members": 1,
                    "configMapName": "cassandra-dev",
                    "storage": {
                        "config": null,
                        "volumeClaimTemplates": [
                            {
                                "metadata": {
                                    "name": "rook-cassandra-data",
                                    "creationTimestamp": null
                                },
                                "spec": {
                                    "resources": {
                                        "requests": {
                                            "storage": "500Gi"
                                        }
                                    },
                                    "storageClassName": "gp2-encrypted"
                                },
                                "status": {}
                            }
                        ],
                        "storageClassDeviceSets": null
                    },
                    "Annotations": null,
                    "placement": {
                        "nodeAffinity": {
                            "requiredDuringSchedulingIgnoredDuringExecution": {
                                "nodeSelectorTerms": [
                                    {
                                        "matchExpressions": [
                                            {
                                                "key": "failure-domain.beta.kubernetes.io/region",
                                                "operator": "In",
                                                "values": [
                                                    "us-east-2"
                                                ]
                                            },
                                            {
                                                "key": "failure-domain.beta.kubernetes.io/zone",
                                                "operator": "In",
                                                "values": [
                                                    "us-east-2b"
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        }
                    },
                    "resources": {
                        "limits": {
                            "cpu": "500m",
                            "memory": "512Mi"
                        },
                        "requests": {
                            "cpu": "500m",
                            "memory": "512Mi"
                        }
                    }
                },
                {
                    "name": "us-east-2c",
                    "members": 1,
                    "configMapName": "cassandra-dev",
                    "storage": {
                        "config": null,
                        "volumeClaimTemplates": [
                            {
                                "metadata": {
                                    "name": "rook-cassandra-data",
                                    "creationTimestamp": null
                                },
                                "spec": {
                                    "resources": {
                                        "requests": {
                                            "storage": "500Gi"
                                        }
                                    },
                                    "storageClassName": "gp2-encrypted"
                                },
                                "status": {}
                            }
                        ],
                        "storageClassDeviceSets": null
                    },
                    "Annotations": null,
                    "placement": {
                        "nodeAffinity": {
                            "requiredDuringSchedulingIgnoredDuringExecution": {
                                "nodeSelectorTerms": [
                                    {
                                        "matchExpressions": [
                                            {
                                                "key": "failure-domain.beta.kubernetes.io/region",
                                                "operator": "In",
                                                "values": [
                                                    "us-east-2"
                                                ]
                                            },
                                            {
                                                "key": "failure-domain.beta.kubernetes.io/zone",
                                                "operator": "In",
                                                "values": [
                                                    "us-east-2c"
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        }
                    },
                    "resources": {
                        "limits": {
                            "cpu": "500m",
                            "memory": "512Mi"
                        },
                        "requests": {
                            "cpu": "500m",
                            "memory": "512Mi"
                        }
                    }
                }
            ]
        }
    },
    "status": {
        "racks": {
            "us-east-2a": {
                "members": 1,
                "readyMembers": 0
            },
            "us-east-2b": {
                "members": 0,
                "readyMembers": 0
            },
            "us-east-2c": {
                "members": 0,
                "readyMembers": 0
            }
        }
    }
```

**Comment by gyant** [comment]
So, this works if you make the annotation key have a capital 'A'. :joy:

e.g.

```
apiVersion: cassandra.rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-cassandra
  namespace: default
spec:
  Annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  datacenter:
    name: us-east-2
    racks:
    ...
```

Resulting pod:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    kubernetes.io/psp: eks.privileged
    prometheus.io/port: "9180"
    prometheus.io/scrape: "true"
    ...
```
