### ISSUE TITLE
NFS Server should be supported FQDN

### ISSUE THREAD

**Issue by chenlein** [rook/rook#5112]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook.io/nfs-provisioner
  labels:
    app.kubernetes.io/name: broker-ddw
    app.kubernetes.io/version: v2.0.0
  name: broker-ddw-share
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  nfs:
    path: /nfs-server/aaa
    server: nfs-server.rook-nfs.svc.cluster.local
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-share
  volumeMode: Filesystem
```
```
Events:
  Type     Reason       Age        From               Message
  ----     ------       ----       ----               -------
  Normal   Scheduled    <unknown>  default-scheduler  Successfully assigned dmcp-instance/nfs-busybox-755774d446-fxv2w to master-2
  Warning  FailedMount  14s        kubelet, master-2  MountVolume.SetUp failed for volume "broker-ddw-share" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/21475b27-ae57-47c6-8951-ba77353c28b3/volumes/kubernetes.io~nfs/broker-ddw-share --scope -- mount -t nfs nfs-server.rook-nfs.svc.cluster.local:/nfs-server/aaa /var/lib/kubelet/pods/21475b27-ae57-47c6-8951-ba77353c28b3/volumes/kubernetes.io~nfs/broker-ddw-share
Output: Running scope as unit run-17995.scope.
mount.nfs: Failed to resolve server nfs-server.rook-nfs.svc.cluster.local: Name or service not known
mount.nfs: Operation already in progress
  Warning  FailedMount  13s  kubelet, master-2  MountVolume.SetUp failed for volume "broker-ddw-share" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/21475b27-ae57-47c6-8951-ba77353c28b3/volumes/kubernetes.io~nfs/broker-ddw-share --scope -- mount -t nfs nfs-server.rook-nfs.svc.cluster.local:/nfs-server/aaa /var/lib/kubelet/pods/21475b27-ae57-47c6-8951-ba77353c28b3/volumes/kubernetes.io~nfs/broker-ddw-share
Output: Running scope as unit run-18012.scope.
mount.nfs: Failed to resolve server nfs-server.rook-nfs.svc.cluster.local: Name or service not known
mount.nfs: Operation already in progress
  Warning  FailedMount  12s  kubelet, master-2  MountVolume.SetUp failed for volume "broker-ddw-share" : mount failed: exit status 32
```

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 7.4.1708 (Core)
* Kernel (e.g. `uname -a`): Linux master-0 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod):  rook: v1.2.5 go: go1.11
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)
* Kubernetes version (use `kubectl version`): v1.17.1
