### ISSUE TITLE
Operator should watch pool tpr in the cluster namespaces

### ISSUE THREAD

**Issue by travisn** [rook/rook#522]
The cluster and pool TPRs are currently all created in the same namespace where the operator is running. Better would be that the cluster-specific TPRs (pools and others in the future) should be created in the namespace where the cluster is running. This means we don't need two attributes for name and two attributes for namespace, where the metadata attributes have a different interpretation than the spec attributes. The current approach is confusing.

For example, the pool tpr would now look like this:
```
apiVersion: rook.io/v1alpha1
kind: Rookpool
metadata:
  name: replicapool
  namespace: rook
spec:
  replication:
    count: 1
```

**Comment by travisn** [comment]
For the cluster TPR, I would also propose a change to use the metadata Name of the tpr as the namespace where the cluster is created, instead of defining a separate spec property for the namespace. So in this example the `rook` namespace would be created.

```
apiVersion: rook.io/v1beta1
kind: Rookcluster
metadata:
  name: rook
spec:
  version: latest
```

Or we could leave it as today where the metadata name is never used by Rook, and we use the spec namespace property to create the namespace. Again, the namespace would be `rook`, but the metadata name would be ignored.
```
apiVersion: rook.io/v1beta1
kind: Rookcluster
metadata:
  name: rook_ignore_me
spec:
  namespace: rook
  version: latest
```
