### ISSUE TITLE
Cluster health check removes some field from the `CephCluster` objects, which leads to false-positives in kubectl apply reports

### ISSUE THREAD

**Issue by zerkms** [rook/rook#5235]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I don't know the project source code yet, so my apologies if my assumptions point to the wrong place, but the observations are not wrong.

I have noticed that as long as the operator logs this line

    op-cluster: checking health of cluster

some properties of the `CephCluster` object disappear (presumably - during this iteration of reconciliation loop).

A more specific example, with everything but `spec` object stripped (using the output of the `kubectl get -n rook-ceph cephcluster/rook-ceph -o yaml` command):

Here is how the manifest looks right before the health check (this perfectly matches what I have put in the cluster manifest):

```yaml
spec:
  cephVersion:
    allowUnsupported: false
    image: ceph/ceph:v14.2.8
  cleanupPolicy:
    deleteDataDirOnHosts: ""
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  crashCollector:
    disable: false
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    manageMachineDisruptionBudgets: false
    managePodBudgets: false
    osdMaintenanceTimeout: 30
  external:
    enable: false
  mgr: {}
  mon:
    allowMultiplePerNode: false
    count: 3
  monitoring: {}
  network:
    hostNetwork: false
    provider: ""
    selectors: null
  rbdMirroring:
    workers: 0
  removeOSDsIfOutAndSafeToRemove: false
  skipUpgradeChecks: false
  storage:
    config: null
    nodes:
    - devices:
      - name: sdb
      name: <redacted>
    storageClassDeviceSets: null
    useAllDevices: false
    useAllNodes: false
```

and this is how the same object looks immediately after the health check:

```yaml
spec:
  cephVersion:
    image: ceph/ceph:v14.2.8
  cleanupPolicy:
    deleteDataDirOnHosts: ""
  crashCollector:
    disable: false
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    osdMaintenanceTimeout: 30
  external:
    enable: false
  mgr: {}
  mon:
    count: 3
  monitoring: {}
  network:
    hostNetwork: false
    provider: ""
    selectors: null
  rbdMirroring:
    workers: 0
  removeOSDsIfOutAndSafeToRemove: false
  storage:
    config: null
    nodes:
    - config: null
      devices:
      - config: null
        name: sdb
      name: <redacted>
      resources: {}
    storageClassDeviceSets: null
    useAllDevices: false
```

To make it easier to see the difference - here is a diff:

```diff
--- was	2020-04-10 11:55:40.432454201 +1200
+++ now	2020-04-10 11:55:50.264256881 +1200
@@ -1,10 +1,8 @@
 spec:
   cephVersion:
-    allowUnsupported: false
     image: ceph/ceph:v14.2.8
   cleanupPolicy:
     deleteDataDirOnHosts: ""
-  continueUpgradeAfterChecksEvenIfNotHealthy: false
   crashCollector:
     disable: false
   dashboard:
@@ -12,14 +10,11 @@
   dataDirHostPath: /var/lib/rook
   disruptionManagement:
     machineDisruptionBudgetNamespace: openshift-machine-api
-    manageMachineDisruptionBudgets: false
-    managePodBudgets: false
     osdMaintenanceTimeout: 30
   external:
     enable: false
   mgr: {}
   mon:
-    allowMultiplePerNode: false
     count: 3
   monitoring: {}
   network:
@@ -29,13 +24,14 @@
   rbdMirroring:
     workers: 0
   removeOSDsIfOutAndSafeToRemove: false
-  skipUpgradeChecks: false
   storage:
     config: null
     nodes:
-    - devices:
-      - name: sdb
+    - config: null
+      devices:
+      - config: null
+        name: sdb
       name: <redacted>
+      resources: {}
     storageClassDeviceSets: null
     useAllDevices: false
-    useAllNodes: false
```

So, as you can see - most modifications are removed fields, then there are couple added and mutated fields as well.

What it means is that if you now `kubectl apply -f` the same manifest with the `CephCluster` definition - kubectl will report it as `configured`, as if something has changed (because it has), while in practice - I did not change anything.

**Expected behavior:**

Nothing should change.

**How to reproduce it (minimal and precise):**

Create a `CephCluster`, wait for a health check, check its details again.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu bionic
* Kernel (e.g. `uname -a`): `Linux <redacted> 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: bare metal, nothing unique, just a commodity machine with ssds
* Rook version (use `rook version` inside of a Rook Pod): 1.3.0
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.8
* Kubernetes version (use `kubectl version`): 1.17.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): n/a
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
