### ISSUE TITLE
op-cluster: failed to configure external ceph cluster - failed to run ceph version

### ISSUE THREAD

**Issue by piersharding** [rook/rook#5259]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When integrating with an External Ceph cluster, the Operator constantly launches jobs to Detected ceph image version for the external Ceph cluster, which appear to be failing.  The operator logs repeatedly issue errors like the following:
```
2020-04-14 21:12:52.428415 I | op-cluster: Detected ceph image version: "14.2.8-0 nautilus"
2020-04-14 21:12:52.523051 I | op-mon: parsing mon endpoints: a=192.168.100.15:3300,b=192.168.100.74:3300,c=192.168.100.40:3300
2020-04-14 21:12:52.523129 I | op-mon: loaded: maxMonID=2, mons=map[a:0xc0006fcde0 b:0xc0006fce20 c:0xc0006fce60], mapping=&{Node:map[]}
2020-04-14 21:12:52.523470 I | cephconfig: writing config file /var/lib/rook/rook-ceph-external/rook-ceph-external.config
2020-04-14 21:12:52.523605 I | cephconfig: generated admin config in /var/lib/rook/rook-ceph-external
2020-04-14 21:12:52.523748 I | exec: Running command: ceph version --connect-timeout=15 --cluster=rook-ceph-external --conf=/var/lib/rook/rook-ceph-external/rook-ceph-external.config --keyring=/var/lib/rook/rook-ceph-external/client.admin.keyring --format json --out-file /tmp/817422505
2020-04-14 21:12:52.838278 I | exec: [errno 5] error connecting to the cluster
2020-04-14 21:12:52.838421 E | op-cluster: failed to configure external ceph cluster. failed to detect and validate ceph version: failed to validate ceph version between external and local: failed to get ceph mon version: failed to run 'ceph version: exit status 1
```
Even with this error, it is possible to create cephfs, and rbd PersistentVolumes using the CSI provisioners eg: rook-ceph.cephfs.csi.ceph.com, rook-ceph.rbd.csi.ceph.com.

**Expected behavior:**
The Operator is able to correctly launch the detection job and discover the image version for the external Ceph cluster configuration.

**How to reproduce it (minimal and precise):**
External Ceph cluster version: 14.2.8
Rook version: 1.3

env is setup with:
```
export NAMESPACE=rook-ceph
export ROOK_EXTERNAL_FSID=fsid=<external ceph cluster fsid>
export ROOK_EXTERNAL_ADMIN_SECRET=client_admin_key=<external ceph cluster admin secret>
export ROOK_EXTERNAL_CEPH_MON_DATA=a=192.168.100.15:3300,b=192.168.100.74:3300,c=192.168.100.40:3300
export ROOK_EXTERNAL_ADMIN_KEY=<external ceph cluster admin key>
```
Then Rook for Ceph is installed:
```
kubectl -n rook-ceph apply -f common.yaml
kubectl -n rook-ceph apply -f operator.yaml
bash ./import-external-cluster.sh
kubectl apply -f cluster-external.yaml # with name and namespace changed to rook-ceph

# also manually create secrets in rook-ceph namespace for rook-csi-rbd-provisioner rook-csi-rbd-node rook-csi-cephfs-provisioner rook-csi-cephfs-node - similar to described here https://github.com/rook/rook/issues/3962
```

**File(s) to submit**:

* To debug this problem, I tried to simulate the erroring ceph version checking Pod with the following captured Pod spec:
```
apiVersion: v1
kind: Pod
metadata:
  name: rook-ceph-detect-version-test
  namespace: rook-ceph
spec:
  affinity: {}
  containers:
  - args:
    - cmd-reporter
    - --command
    - '{"cmd":["ceph"],"args":["--version"]}'
    - --config-map-name
    - rook-ceph-detect-version
    - --namespace
    - rook-ceph
    command:
    - /rook/copied-binaries/tini
    - --
    - /rook/copied-binaries/rook
    image: ceph/ceph:v14.2.8
    imagePullPolicy: IfNotPresent
    name: cmd-reporter
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /rook/copied-binaries
      name: rook-copied-binaries
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: rook-ceph-cmd-reporter-token-vbjnl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - copy-binaries
    - --copy-to-dir
    - /rook/copied-binaries
    image: rook/ceph:v1.3.1
    imagePullPolicy: IfNotPresent
    name: init-copy-binaries
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /rook/copied-binaries
      name: rook-copied-binaries
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: rook-ceph-cmd-reporter-token-vbjnl
      readOnly: true
  nodeName: piers-test-master-0
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: rook-ceph-cmd-reporter
  serviceAccountName: rook-ceph-cmd-reporter
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: rook-copied-binaries
  - name: rook-ceph-cmd-reporter-token-vbjnl
    secret:
      defaultMode: 420
      secretName: rook-ceph-cmd-reporter-token-vbjnl
```
This appeared to run successfully:
```
$ kubectl -n rook-ceph get pod/rook-ceph-detect-version-test
NAME                            READY   STATUS      RESTARTS   AGE
rook-ceph-detect-version-test   0/1     Completed   0          48m
```
With the following output in the logs:
```
$ kubectl -n rook-ceph logs pod/rook-ceph-detect-version-test
2020-04-14 23:53:14.599974 I | job-reporter-cmd: running command: /usr/bin/ceph ceph --version
ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.4 LTS
* Kernel (e.g. `uname -a`): Linux piers-test-master-0 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:  k8s single node m1.medium
* Rook version (use `rook version` inside of a Rook Pod): v1.3.1
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)
* Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): manual single node installed with kubeadm - v1.18.1, Calico v3.13
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK
