### ISSUE TITLE
Use the cluster TPR name instead of defining a namespace TPR property

### ISSUE THREAD

**Issue by travisn** [rook/rook#526]
For the cluster TPR, it is proposed to use the metadata Name of the tpr as the namespace where the cluster is created, instead of defining a separate spec property for the namespace. 

For example, the `rook` namespace would be created here.
```
apiVersion: rook.io/v1beta1
kind: Rookcluster
metadata:
  name: rook
spec:
  version: latest
```

Or we could leave it as today where the metadata name is never used by Rook, and we use the spec namespace property to create the namespace. The confusing thing is that the metadata name would be ignored. The good thing is it is more obvious that a namespace will be created. 
```
apiVersion: rook.io/v1beta1
kind: Rookcluster
metadata:
  name: rook_ignore_me
spec:
  namespace: rook
  version: latest
```

**Comment by bassam** [comment]
The name of the cluster is useful beyond just the namespace. Its the ceph cluster name too. I propose the behavior be as follows: 

If a name is set but no namespace, create the cluster with specified name and in a new namespace matching the name.

If a name is set an a namespace is set, then create a cluster with the specified name in the specified namespace.

**Comment by travisn** [comment]
Does this example represent what you're suggesting? 
- Ceph cluster name: `rook`
- Kubernetes namespace: `myrook`
- note that the metadata namespace `kube-system` must be set to the namespace where the operator is running.
```
apiVersion: rook.io/v1beta1
kind: Rookcluster
metadata:
  name: rook
  namespace: kube-system
spec:
  namespace: myrook
```

This is confusing since there are two namespace attributes are specified. We can't control the first one, so if we can do without the second one it avoids that confusion.

And do we need to support a different ceph namespace from the k8s namespace? Currently they are the same and it has a nice simplicity about it.

**Comment by bassam** [comment]
> This is confusing since there are two namespace attributes are specified.

can we rename the `namespace` attribute in the spec section to `cluster-namespace` or something like that to reduce the confusion?

> And do we need to support a different ceph namespace from the k8s namespace? Currently they are the same and it has a nice simplicity about it.

Consider the case where I want to run multiple clusters in the same the kubernetes namespace. If at the K8S level i've setup my network policies etc. yet still want to use multiple ceph clusters.

**Comment by travisn** [comment]
hmm, the assumption was one cluster per namespace. We'll need to change a number of areas if we need to support multiple clusters in the same namespace.

**Comment by luxas** [comment]
I'm really in favor for using `.metadata.namespace` instead of baking in a namespace field in the TPR `.spec`.

**Comment by bassam** [comment]
@travis why does `.metadata.namespace` need to be set to the namespace where the operator is running? Is there a way around that? If so then I agree with @luxas it would be simple to just use:

```
apiVersion: rook.io/v1beta1
kind: Rookcluster
metadata:
  name: rook
  namespace: my-rook
```

where `name` is the ceph cluster name and `namespace` is the namespace where the pods will be created for rook. Note that multiple clusters could still be supported in the same namespace here.
