### ISSUE TITLE
The operator cannot upgrade OSDs

### ISSUE THREAD

**Issue by mecseid** [rook/rook#5337]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The operator cannot upgrade the OSDs from v14.2.7-20200206 to v15.2.1-20200410.
The manager, the crash collectors and the monitor pods upgraded successfully.

Current state is:
```
csi-cephfsplugin-provisioner    req/upd/avl: 2/2/2      rook-version=
csi-rbdplugin-provisioner       req/upd/avl: 2/2/2      rook-version=
rook-ceph-crashcollector-k8s-worker-1   req/upd/avl: 1/1/1      rook-version=v1.3.2
rook-ceph-crashcollector-k8s-worker-2   req/upd/avl: 1/1/1      rook-version=v1.3.2
rook-ceph-crashcollector-k8s-worker-3   req/upd/avl: 1/1/1      rook-version=v1.3.2
rook-ceph-crashcollector-k8s-worker-4   req/upd/avl: 1/1/1      rook-version=v1.3.2
rook-ceph-mgr-a         req/upd/avl: 1/1/1      rook-version=v1.3.2
rook-ceph-mon-a         req/upd/avl: 1/1/1      rook-version=v1.3.2
rook-ceph-mon-b         req/upd/avl: 1/1/1      rook-version=v1.3.2
rook-ceph-mon-c         req/upd/avl: 1/1/1      rook-version=v1.3.2
rook-ceph-operator      req/upd/avl: 1/1/1      rook-version=
rook-ceph-osd-0         req/upd/avl: 1/1/1      rook-version=v1.2.7
rook-ceph-osd-1         req/upd/avl: 1/1/1      rook-version=v1.2.7
rook-ceph-osd-2         req/upd/avl: 1/1/1      rook-version=v1.2.7
rook-ceph-osd-3         req/upd/avl: 1/1/1      rook-version=v1.2.7
```

**Expected behavior:**
The operator upgrade the OSDs to the excepted version.

**How to reproduce it (minimal and precise):**
* 3 controller with etcd node and 4 worker nodes
* Rook operator v1.2.7
* Cluster with version v14.2.7-20200206
* Upgrade Rook to v1.3.2
* Upgrade cluster to v15.2.1-20200410

**File(s) to submit**:

* Cluster CR
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.1-20200410
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  dashboard:
    enabled: true
    ssl: false
  network:
    hostNetwork: false
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    modules:
      - name: pg_autoscaler
        enabled: true
  rbdMirroring:
    workers: 0
  resources:
    mon:
      limits:
        memory: 1024Mi
    mgr:
      limits:
        memory: 512Mi
    osd:
      limits:
        memory: 2048Mi
    mds:
      limits:
        memory: 4096Mi
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter: vdb
    config:
      storeType: bluestore
    nodes:
      - name: k8s-worker-1
      - name: k8s-worker-2
      - name: k8s-worker-3
      - name: k8s-worker-4
  disruptionManagement:
    managePodBudgets: false
    manageMachineDisruptionBudgets: false
```

* Operator's logs, if necessary
[ceph-upgrade-log.txt](https://github.com/rook/rook/files/4536083/ceph-upgrade-log.txt)

* Crashing pod(s) logs, if necessary
No crashing pods

**Environment**:
* OS (e.g. from /etc/os-release):
CoreOS 2303.3.0
* Kernel (e.g. `uname -a`):
Linux 4.19.86-coreos
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Rancher provisioned RKE cluster
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
HEALTH_WARN 3 daemons have recently crashed
```
