### ISSUE TITLE
Driver name not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by tvvignesh** [rook/rook#5391]
Hi. I am facing this issue in my GKE cluster: 
```Warning  FailedMount             94s (x21 over 28m)    kubelet, gke-tc-dev-1-default-pool-10e65eb9-0ck0  MountVolume.MountDevice failed for volume "pvc-a7dfc3f5-e719-442d-82cd-68da52c568b2" : driver name rook-ceph.cephfs.csi.ceph.com not found in the list of registered CSI drivers```

Went through github and slack, found these:
https://rook-io.slack.com/archives/CG3HUV94J/p1587383219086500
https://github.com/rook/rook/issues/4183
https://github.com/rook/rook/pull/3957/files#r328846025
https://github.com/rook/rook/issues/3923

(Related to rancher but still same issue mentioned there)

I am running on top of gke csi driver: https://cloud.google.com/kubernetes-engine/docs/how-to/gce-pd-csi-driver

Any ideas on how to fix this error? I tried setting tolerance like this but does not seem to work:

```yml
  CSI_PROVISIONER_TOLERATIONS: |
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      operator: Exists
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      operator: Exists
  CSI_PLUGIN_TOLERATIONS: |
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      operator: Exists
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      operator: Exists
```

I tried restarting deleting the pods in csi-cephfsplugin-provisioner and csi-rbdplugin-provisioner to check if that would work but even that does not seem to work

For edgefs, they have mentioned it in troubleshooting here: https://rook.io/docs/rook/master/edgefs-csi.html but I can't find something similar for ceph-csi in the docs

This has all the yamls which I am using for getting rook setup

[rook.zip](https://github.com/rook/rook/files/4575360/rook.zip)

Kindly help. Thanks.

**Comment by tvvignesh** [comment]
@Madhu-1 helped me solve this problem. It was because of a conflicting port. I changed ports in my operator like this:

```yml
# Configure CSI CSI Ceph FS grpc and liveness metrics port
  CSI_CEPHFS_GRPC_METRICS_PORT: "8800"
  CSI_CEPHFS_LIVENESS_METRICS_PORT: "8802"
  # Configure CSI RBD grpc and liveness metrics port
  CSI_RBD_GRPC_METRICS_PORT: "8804"
  CSI_RBD_LIVENESS_METRICS_PORT: "8806"
```

and deployed and it worked.

Closing this. Thanks.
