### ISSUE TITLE
Documentation Support Request for enabling SSO on Ceph Dashboard.

### ISSUE THREAD

**Issue by crazytera** [rook/rook#5392]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
There is no documentation **Rook Specific** that shows how to setup SSO on the rook dashboard.

**Expected behavior:**
Some sort of documentation on how to control pods better that would allow the enablement of SAML based SSO for ceph. 

**How to reproduce it (minimal and precise):**
The [Ceph Documentation](https://docs.ceph.com/docs/master/mgr/dashboard/#dashboard-sso-support) shows how to setup SSO, but requires an x.509 certificate mounted somewhere on the filesystem. 

**File(s) to submit**:
No changes to default files that relate to this question. 

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 19.10 (Eoan Ermine)
* Kernel (e.g. `uname -a`): `Linux home-cont-01 5.3.0-51-generic #44-Ubuntu SMP Wed Apr 22 21:09:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Bare Metal. 3x nodes varying hardware. >6gb ram each >6 vCpu each.
* Rook version (use `rook version` inside of a Rook Pod): 
```
rook: v1.3.1
go: go1.13.8
```
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)`
* Kubernetes version (use `kubectl version`): 1.18
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare Metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_OK`

**Comment by soleblaze** [comment]
The current ceph/ceph docker images don’t include python3-saml, which prevents sso from working unless you roll your own image with it installed. 

I have keycloak working as my saml provider. I made my own docker image that installed python3-xmlsec with dnf then python3-saml with pip3. After that I was able to enable sso. However, I’m not using x509 certificates. I’m guessing that if it’s a requirement then the chart would need to be updated to allow mounting a secret containing the proper certificates.

**Comment by djds** [comment]
Can this be re-opened? It would be a really nice feature to have in cases where the dashboard is exposed. Alternatively, are there any plans to support SSO via OIDC in the future?

**Comment by parth-gr** [comment]
@crazytera is this something you are still looking for?
cc : @djds

**Comment by Elyytscha** [comment]
I would like to use oidc or saml for the ceph dashboard

**Comment by Nickmman** [comment]
Is configuring SAML SSO something that can be configured via the helm chart?

**Comment by Kernald** [comment]
I would love to see this reopened as well.

**Comment by travisn** [comment]
@rkachach Thoughts on this request related to the dashboard auth?

**Comment by rkachach** [comment]
@travisn this seems be to be related with the legacy SSO support (SAML, not the new OIDC as far as I can tell). Anyway I'll check to see if there's anything to be done from Dashboard side.

**Comment by afreen23** [comment]
Hi @rkachach @travisn 

We do allow support of SAML from dashboard.
But we do understand that the doc to add same in rook is missing, the cert files just need to mounted to pod so that once the sso is configured via toolbox - it can access them and it remains there.

```
ceph dashboard sso setup saml2 <ceph_dashboard_base_url> <idp_metadata> {<idp_username_attribute>} {<idp_entity_id>} {<sp_x_509_cert>} {<sp_private_key>}
```

I can work on testing this in rook and document it.

**Comment by travisn** [comment]
IIRC The mgr pod doesn't currently have a way to mount a cert, we may need something similar to rgw with the [SslCertificateRef setting](https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1/types.go#L1893). 
@BlaineEXE thoughts?

**Comment by BlaineEXE** [comment]
We should figure out whether we need an analogue of `SSLCertificateRef` or `CaBundleRef`. My guess with SSO is that the dashboard needs to auth with the SSO's cert (`CaBundleRef` analogue), rather than the SSO auth'ing with the MGR's cert (`SSLCertificateRef` analogue). I could be wrong here though, or we might need to plan for both.

[Addendum]
@rkachach do you happen to know which "actors" in the system needs which certs for auth? My guess (above) is that the MGR pod (actor 1) needs access to a cert that validates the SSO service (actor 2). Do you know if this is the right logic between these 2 actors? Are there other actors Rook needs to be aware of? Does the SSO service alternately/also need to authenticate the MGR (dashboard)?

**Comment by rkachach** [comment]
> We should figure out whether we need an analogue of `SSLCertificateRef` or `CaBundleRef`. My guess with SSO is that the dashboard needs to auth with the SSO's cert (`CaBundleRef` analogue), rather than the SSO auth'ing with the MGR's cert (`SSLCertificateRef` analogue). I could be wrong here though, or we might need to plan for both.
> 
> [Addendum] [@rkachach](https://github.com/rkachach) do you happen to know which "actors" in the system needs which certs for auth? My guess (above) is that the MGR pod (actor 1) needs access to a cert that validates the SSO service (actor 2). Do you know if this is the right logic between these 2 actors? Are there other actors Rook needs to be aware of? Does the SSO service alternately/also need to authenticate the MGR (dashboard)?

Sorry for the late response @BlaineEXE 

TBH I'm not sure how the roles play out in this case. In general, AFAIK, the mgr pod itself doesn't hold any specific SSL cert; it's the dashboard that hosts and performs the SSO auth logic, both for SAML and for the new OIDC support. I think, in this case, maybe @afreen23 can provide more accurate information.

**Comment by JensErat** [comment]
For SAML, you need to copy the certificates (same as the xml file with IDP configuration) to the active manager pod, but only for running the `ceph mgr dashboard setup` (which you can run from the toolbox pod, which already got all credentials). The authentication is performed by the dashboard code which is running inside the mgr pod.

For OIDC, it's sligthly different. You need to provide your own oauth2-proxy server and properly relabel oauth2-proxy's headers to match what the dashboard expects. The dashboard code will only slightly check some information of the token, but not really validate it any more (as this is already done by oauth2-proxy). You do not need to copy any files to neither mgr nor toolbox pod for oauth2.

**Comment by Elyytscha** [comment]
just to say (as i wrote i need saml) since azure ad provides ways to use oidc instead of saml, i'm not in the need anymore of using saml!

**Comment by rouke-broersma** [comment]
> For OIDC, it's sligthly different. You need to provide your own oauth2-proxy server and properly relabel oauth2-proxy's headers to match what the dashboard expects. The dashboard code will only slightly check some information of the token, but not really validate it any more (as this is already done by oauth2-proxy). You do not need to copy any files to neither mgr nor toolbox pod for oauth2.

I haven't been able to find which headers we need to set for ceph dashboard, would you happen to have a link to the correct docs?

**Comment by JensErat** [comment]
Writing up how to get this connected manually is still on my todo list. If you happen to be at fosdem this weekend, we can have a chat on-site.

**Comment by rouke-broersma** [comment]
I am in the software defined storage track right now actually

**Comment by jhoblitt** [comment]
It appears that the `python3-saml` package is present in the 19.2.3 images.

**Comment by reitermarkus** [comment]
So I tried to make this work, but couldn't quite figure out how. As Identity Provider I am using Pocket ID.

---

Here is what I got so far:

1. Installed OAuth2 Proxy using Helm (https://github.com/oauth2-proxy/manifests) with release name `rook-ceph-cluster-oauth2-proxy` and the following secret and values:
   
    ```yaml
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: oauth2-proxy-provider
    type: Opaque
    stringData:
      client-id: ***
      client-secret: ***
      cookie-secret: ***
    ```
     
    ```yaml
    ---
    config:
      existingSecret: oauth2-proxy-provider
    
    extraArgs:
      provider: oidc
      scope: 'openid email profile groups'
      oidc-issuer-url: https://id.example.org
      insecure-oidc-allow-unverified-email: 'true'
      skip-provider-button: 'true'
      reverse-proxy: 'true'
      cookie-refresh: 1h
      real-client-ip-header: X-Forwarded-For
      redirect-url: https://rook-ceph.example.org/auth/oauth2/callback
      whitelist-domain: '.rook-ceph.example.org'
      cookie-domain: '.rook-ceph.example.org'
      email-domain: '*'
      upstream: static://204
      set-xauthrequest: 'true'
    ```
  
2. Adjust ingress for OAuth2 Proxy. I'm using Traefik, so this looks like:

    ```yaml
    ---
    apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: rook-ceph
    spec:
      entryPoints:
        - websecure
      routes:
        - kind: Rule
          match: Host(`rook-ceph.example.org`) && PathPrefix(`/oauth2`)
          services:
            - name: rook-ceph-cluster-oauth2-proxy
              namespace: rook-ceph
              port: http
        - kind: Rule
          match: Host(`rook-ceph.example.org`)
          services:
            - name: rook-ceph-mgr-dashboard
              namespace: rook-ceph
              port: http-dashboard
      tls: {}
    ```

3. Enable OAuth2:
  
    ```sh
    kubectl exec -it -n rook-ceph deploy/rook-ceph-tools -- ceph dashboard sso enable oauth2
    ```

---

Now, when I open `https://rook-ceph.example.org`, it redirects me to `https://id.example.org` as expected, I log in, and end up at `https://rook-ceph.reiter.ooo/auth/oauth2/login` with the following error:

```json
{"status": "500 Internal Server Error", "detail": "The server encountered an unexpected condition which prevented it from fulfilling the request.", "request_id": "99a2cb86-4be9-4857-b14e-af6848573816"}                                                                                                                                                                                                                                                                                                                        
```

I can see that I am effectively “logged in” since the `_oauth2_proxy` cookie is present for domain `.rook-ceph.example.org`.

I also saw the following issues, so maybe it is related to one of them:

- https://github.com/ceph/ceph/pull/67417
- https://github.com/ceph/ceph/pull/67666

Or maybe it's related to what @JensErat wrote above:

> You need to provide your own oauth2-proxy server and properly relabel oauth2-proxy's headers to match what the dashboard expects.

No idea which headers these are though.

**Comment by ArjonBu** [comment]
Anyone managed to set this up through rook yet?

**Comment by JensErat** [comment]
Not through rook, but together with (with traefik and oauth2proxy already running). Wanted to put together docs for this but didn't have enough time yet. But I can share some snippets if you reach out to me

**Comment by ArjonBu** [comment]
@JensErat maybe you could post them here and everyone could benefit? If you don't have time to write the docs like you mentioned above, you could even feed those files to a LLM, and it could write some docs for you.

Thank you!

**Comment by uhthomas** [comment]
I was able to make it work with envoy gateway.

```cue
#SecurityPolicyList: envoygatewayv1.#SecurityPolicyList & {
	apiVersion: "gateway.envoyproxy.io/v1alpha1"
	kind:       "SecurityPolicyList"
	items: [...{
		apiVersion: "gateway.envoyproxy.io/v1alpha1"
		kind:       "SecurityPolicy"
	}]
}

#SecurityPolicyList: items: [{
	metadata: name: "\(#Name)-envoy-oidc"
	spec: {
		targetRefs: [{
			group: "gateway.networking.k8s.io"
			kind:  "HTTPRoute"
			name:  "\(#Name)-https"
		}]
		oidc: {
			provider: issuer: "https://kanidm.example.com/oauth2/openid/\(#Name)-envoy"
			clientID: "\(#Name)-envoy"
			clientSecret: name: "\(#Name)-envoy-kanidm-oauth2-credentials"
			redirectURL: "https://ceph.example.com/oauth2/callback"
			scopes: ["openid", "email", "profile", "groups"]
			logoutPath: "/logout"
			// Expose the Kanidm ID token to the ceph dashboard so it can
			// auto-provision the user via `ceph dashboard sso enable oauth2`
			// (the dashboard reads the token from a cookie named "token"
			// and decodes it without verifying the signature).
			disableTokenEncryption: true
			cookieNames: idToken:   "token"
		}
	}
}]
```

```cue
#KanidmOAuth2ClientList: {
	apiVersion: "kaniop.rs/v1beta1"
	kind:       "KanidmOAuth2ClientList"
	items: [...{
		apiVersion: "kaniop.rs/v1beta1"
		kind:       "KanidmOAuth2Client"
	}]
}

#KanidmOAuth2ClientList: items: [{
	metadata: name: "\(#Name)-envoy"
	spec: {
		displayname: "Ceph"
		kanidmRef: {
			name:      "kanidm"
			namespace: "kanidm"
		}
		origin: "https://ceph.example.com"
		redirectUrl: ["https://ceph.example.com/oauth2/callback"]
		scopeMap: [{
			group: "ceph_dashboard_users"
			scopes: ["openid", "email", "profile", "groups"]
		}]
		// The ceph dashboard's oauth2 handler reads a `roles` claim from the
		// ID token and maps role strings to ceph system roles. Kanidm doesn't
		// emit `roles` out of the box, so we synthesise it from group
		// membership: ceph_dashboard_users → read-only,
		// ceph_dashboard_admins → administrator. Members of both get both.
		claimMap: [{
			name:         "roles"
			joinStrategy: "array"
			valuesMap: [{
				group: "ceph_dashboard_users"
				values: ["read-only"]
			}, {
				group: "ceph_dashboard_admins"
				values: ["administrator"]
			}]
		}]
		preferShortUsername: true
		secretRotation: {
			enabled:    true
			periodDays: 14
		}
	}
}]
```

**Comment by ArjonBu** [comment]
Thank you @uhthomas! That worked!
One thing I needed to change is `logoutPath: "/oauth2/sign_out"` so when you click logout on the dashboard UI, it actually logs you out. With `logoutPath: "/logout"`, it will show you a 404 when clicking that button.

Also for others, you need to run `ceph dashboard sso enable oauth2` on ceph-tools pod to enable this.

**Comment by br05s** [comment]
@reitermarkus - I figured out that 500 error.

The dashboard controller calls into a service that tries to pull the access token from a cookie called "token" or a header called "X-Access-Token" (https://github.com/ceph/ceph/blob/v21.3.0/src/pybind/mgr/dashboard/services/auth/oauth2.py#L61-L65).

If nothing is returned, a non-descriptive 500 error is thrown (https://github.com/ceph/ceph/blob/v21.3.0/src/pybind/mgr/dashboard/controllers/oauth2.py#L17-L19 - cherrypy.HTTPError() with no argument defaults to 500).

The easiest thing I have found is having the ingress controller set the "X-Access-Token" header to the "x-auth-request-access-token" header of the auth response.

I still haven't moved off of NGINX Ingress on my homelab, so here is an example of a setup I am using for it with Keycloak as my IDP. Everything is working now except logging off due to the Mgr pod needing my internal CA cert, which I haven't found a good solution for yet.

The Rook cluster is deployed using the [rook-ceph-cluster Helm chart](https://github.com/rook/rook/blob/v1.20.3/Documentation/Helm-Charts/ceph-cluster-chart.md) with these values (non-relevant values excluded):
```yaml
ingress:
  dashboard:
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/auth-url: >-
        http://ceph-dashboard-oauth2-proxy.rook-ceph-cluster.svc.cluster.local/oauth2/auth
      nginx.ingress.kubernetes.io/auth-signin: >-
        https://$host/oauth2/start?rd=$scheme://$host$escaped_request_uri
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        auth_request_set $ceph_access_token $upstream_http_x_auth_request_access_token;
        proxy_set_header X-Access-Token $ceph_access_token;
    host:
      name: ceph.apps.example.org
      path: "/"
      pathType: Prefix
    tls:
      - hosts:
          - ceph.apps.example.org
        secretName: dashboard-tls

cephClusterSpec:
  dashboard:
    enabled: true
    ssl: false
```

The important part to avoid the 500 is this under nginx.ingress.kubernetes.io/configuration-snippet:
```yaml
auth_request_set $ceph_access_token $upstream_http_x_auth_request_access_token;
proxy_set_header X-Access-Token $ceph_access_token;
```

OAuth2 Proxy is deployed using [oauth2-proxy Helm chart](https://github.com/oauth2-proxy/manifests/blob/oauth2-proxy-10.7.0/README.md) with these values:
```yaml
fullnameOverride: ceph-dashboard-oauth2-proxy
config:
  existingSecret: oauth2-proxy-provider

extraArgs:
  provider: keycloak-oidc
  provider-ca-file: /etc/ssl/certs/ca-certificates.crt
  oidc-issuer-url: https://auth.example.org/realms/home
  redirect-url: https://ceph.apps.example.org/oauth2/callback
  scope: 'openid email profile roles'
  upstream: static://204
  email-domain: '*'
  skip-provider-button: 'true'
  reverse-proxy: 'true'
  set-xauthrequest: 'true'
  pass-access-token: 'true'
  real-client-ip-header: X-Forwarded-For
  cookie-secure: 'true'
  cookie-name: _ceph_dashboard_oauth2
  cookie-refresh: 1h

ingress:
  enabled: true
  hosts:
    - ceph.apps.example.org
  path: /oauth2/
  pathType: Prefix
  tls:
    - hosts:
        - ceph.apps.example.org
      secretName: dashboard-tls

extraVolumes:
  - name: ca-bundle
    secret:
      secretName: default-ca-bundle    # Secret with my internal CA
      items:
        - key: default-bundle.pem
          path: ca-certificates.crt

extraVolumeMounts:
  - mountPath: /etc/ssl/certs
    name: ca-bundle
```

Keycloak is setup with a client with an id of "ceph-dashboard":
> Root URL: https://ceph.apps.example.org
> Home URL: /
> Valid redirect URIs: /oauth2/callback
> Valid post logout redirect URIs: /oauth2/sign_out
> Web origins: *
> Admin URL: https://ceph.apps.example.org
> Client authentication: On
> Authorization: Off
> Authentication flow: Standard flow
> Require PKCE: Off
> Client Scopes > dedicated > Scope > Full scope allowed: Off
> Roles (not all are needed):
> - administrator
> - block-manager
> - cephfs-manager
> - cluster-manager
> - ganesha-manager
> - pool-manager
> - read-only
> - rgw-manager
> - smb-manager
> - uma_protection

Then enable with the path of where the roles are in the token:
```bash
ceph dashboard sso enable oauth2 \
  'resource_access."ceph-dashboard".roles'
```
