### ISSUE TITLE
(FlexDriver) timeout expired waiting for volumes to attach or mount for pod

### ISSUE THREAD

**Issue by jc-lab** [rook/rook#5430]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

See https://rook.io/docs/rook/v1.2/ceph-block.html and create storageClasses.
Using CSI RBD works well, but using Flex Driver creates problems.

**How to reproduce it (minimal and precise):**
StorageClass:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-flex-1
provisioner: ceph.rook.io/block
parameters:
  blockPool: test-flex-1-pool
  clusterNamespace: rook-ceph
  fstype: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

Statefulset
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-4
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-4
  template:
    metadata:
      labels:
        app: sample-4
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: test-flex-1
```

**File(s) to submit**:
describe pod events
```
Events:
  Type     Reason       Age    From               Message
  ----     ------       ----   ----               -------
  Normal   Scheduled    2m12s  default-scheduler  Successfully assigned test/sample-4-0 to node-9
  Warning  FailedMount  9s     kubelet, node-9    Unable to mount volumes for pod "sample-4-0_test(4058b338-40fd-4392-b2c4-302323e1a190)": timeout expired waiting for volumes to attach or mount for pod "test"/"sample-4-0". list of unmounted volumes=[www]. list of unattached volumes=[www default-token-n686p]
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS
* Kernel (e.g. `uname -a`): 4.15.0-72-generic
* Cloud provider or hardware configuration: On-premise
* Rook version (use `rook version` inside of a Rook Pod): v1.2.7
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)
* Kubernetes version (use `kubectl version`): v1.16.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): native kubernetes
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): *Nothing*
