### ISSUE TITLE
External cephfs expects 'adminID' and 'adminKey' in secrets

### ISSUE THREAD

**Issue by ston1th** [rook/rook#5432]
* Bug Report

I used the `import-external-cluster.sh` script to connect rook to my external ceph cluster.

This script creates the `rook-csi-cephfs-node` and `rook-csi-cephfs-provisioner` secrets with userID and userKey.

**Deviation from expected behavior:**

Provisioner and mount logs:
```
  Warning  ProvisioningFailed    6s (x5 over 13s)  rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-77cd85b75b-2xrvf_1cd197ec-9deb-4a86-8f9c-21aed203dc3c  failed to provision volume with StorageClass "cephfs": rpc error: code = InvalidArgument desc = missing ID field 'adminID' in secrets

  Warning  FailedMount             27s (x8 over 91s)  kubelet, worker1        MountVolume.MountDevice failed for volume "pvc-5c5938a3-5023-44ab-b9ec-fb854d084cf1" : rpc error: code = Internal desc = missing ID field 'adminID' in secrets
```

To fix this I had to add the same secret values but with `adminID` and `adminKey`.

**Expected behavior:**

**How to reproduce it (minimal and precise):**
Connect to an external ceph cluster using `import-external-cluster.sh` and create a cephfs storageclass and PVC:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs
parameters:
  clusterID: rook-ceph-external
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph-external
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph-external
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph-external
  fsName: cephfs
  pool: cephfs_data
provisioner: rook-ceph.cephfs.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cephfs-claim
  namespace: default
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.3.2
go: go1.13.8
