### ISSUE TITLE
mgr not created

### ISSUE THREAD

**Issue by orblazer** [rook/rook#5487]
**Is this a bug report or feature request?**
* Bug Report ?

**Deviation from expected behavior:** The operator is stuck, mgr is never created

**Expected behavior:** Create the cluster without errors

**How to reproduce it (minimal and precise):**
I don't know, i just have follow the quickstart

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.9
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
    ssl: false
  monitoring:
    enabled: true
    rulesNamespace: rook-ceph
  network:
  rbdMirroring:
    workers: 0
  crashCollector:
    disable: false
  cleanupPolicy:
    deleteDataDirOnHosts: ""
  annotations:
  resources:
    mgr:
      limits:
        cpu: "500m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "1024Mi"
  removeOSDsIfOutAndSafeToRemove: false
  storage:
    useAllNodes: true
    useAllDevices: true
    config:
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
```
* Operator's logs, if necessary : https://pastebin.com/pD4HLWu6
* Crashing pod(s) logs, if necessary :

  - The log `rook-ceph-mon-a` : https://pastebin.com/n710zF7E
  - The log `rook-ceph-mon-d` : https://pastebin.com/s0CCarAS
  - The log `rook-ceph-mon-f` : https://pastebin.com/5wUJRDR4

* My disk (with `sudo fdisk -l`) :
```
Disk /dev/sdb: 50 GiB, 53687091200 bytes, 104857600 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.4 LTS
* Kernel (e.g. `uname -a`): Linux master 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: VM on dedicated server on OVH
* Rook version (use `rook version` inside of a Rook Pod): 1.13
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.9
* Kubernetes version (use `kubectl version`): 1.18.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): no respond

UPDATE : i also progress here : https://app.slack.com/client/T47C56S7Q/C46Q5UC05/thread/C46Q5UC05-1589381635.385300
