### ISSUE TITLE
Mon endpoint list using wrong interface

### ISSUE THREAD

**Issue by cortopy** [rook/rook#5495]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I have a ceph cluster configured to use the host network. Each node has two interfaces: one public, and one private. I would like to use the private one. This interface is also the default one for all communication within the kubernetes cluster.

While ceph and kubernetes are properly configured to use the private network, rook defaults to creating config objects "as if" the ceph cluster is using the public network when, in reality all the pods will have IPs in a different interface

If I inspect `rook-ceph-mon-endpoints` configMap I can indeed see that rook "thinks" that the kubernetes cluster and the pods using host network will have the IP from the node's public interface.

This has an impact on how osd pods try to connect to mon pods, as the osd pods will be trying to reach the mons using IPs which are not in their network.

**Expected behavior:**
Rook respects the overriden configuration and uses the provided interface to generate endpoint lists (e.g.: in `rook-ceph-mon-endpoints` configMap)

**How to reproduce it (minimal and precise):**

To make sure that rook and ceph pick the same interface I have created a `rook-config-override` ConfigMap like this:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    public network = 172.17.0.1/32
    cluster network = 172.17.0.1/32
    public addr = ""
    cluster addr = ""
```

Then in the helm values for the operator I have `useOperatorHostNetwork: true` and for the cluster:

```
  network:
    provider: host
```

This results in all the osd and mon pods getting the IP of the host in the configured `172.17.0.1/32` network. And so host networking is working fine and as expected.

However, in the configMap generated by Rook, I can see that the endpoints are wrong:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-csi-config
  namespace: rook-ceph
data:
  csi-cluster-config-json: >-
    [{"clusterID":"rook-ceph","monitors":["49.12.xx.xxx:6789","49.12.xx.xxx:6789","49.12.xx.xxx:6789"]}]
```

In the logs of osd pods I can see that the pods are trying to use the wrong endpoints listed by rook in the configMap and I can read:

```
parsing mon endpoints: c=49.12.xx.xxx:6789,a=49.12.xx.xxx:6789,b=49.12.xx.xxx:6789
cephosd: failed to start osd or shutting down. exit status 1
```

The manager is also failing, in the logs I have:

```
unable to find any IP address in networks '172.17.0.1/32' interfaces ''2020-05-17T19:49:10.822202463+02:00
```
I suspect the monitor is trying to reach mons in the 172.17.0.1/32 network using the wrong ip, which will never work since the latter is just a private network

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu
* Kernel (e.g. `uname -a`): 5.4.0
* Cloud provider or hardware configuration: Hetzner cloud
* Rook version (use `rook version` inside of a Rook Pod): 1.3
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2
* Kubernetes version (use `kubectl version`): 1.17
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `ceph status` hangs in the tools pod
