### ISSUE TITLE
Rook operator doesn't set resource request and limit for CSI pods

### ISSUE THREAD

**Issue by retinio** [rook/rook#5501]
**Is this a bug report or feature request?**
* Bug Report

After changing values.yaml and adding resource request and limit for CSI pod rook operator doesn't set limits.

**helm upgrade --install rook-ceph rook-release/rook-ceph -f operator/values.production.yaml --wait --namespace rook-ceph --version v1.3.3**

**values.yaml**
```
...

csi:
  enableRbdDriver: true
  enableCephfsDriver: true
  enableGrpcMetrics: true
  enableSnapshotter: false
              
  csiCephFSPluginResource:
    - name : driver-registrar
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi  
    - name : csi-cephfsplugin
      resource:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
    - name : liveness-prometheus
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
```
rook operator pod contains define resources

```
    - name: CSI_CEPHFS_PLUGIN_RESOURCE
      value: '[map[name:driver-registrar resource:map[limits:map[memory:256Mi] requests:map[cpu:50m
        memory:128Mi]]] map[name:csi-cephfsplugin resource:map[limits:map[memory:1Gi]
        requests:map[cpu:250m memory:512Mi]]] map[name:liveness-prometheus resource:map[limits:map[memory:256Mi]
        requests:map[cpu:50m memory:128Mi]]]]'
```

But csi-cephfsplugin pod not restart. After a manual restart pod it doesn't contain requests and limits.
```
...
    image: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - rm -rf /registration/rook-ceph.cephfs.csi.ceph.com /registration/rook-ceph.cephfs.csi.ceph.com-reg.sock
    name: driver-registrar
    resources: {}
...
    image: quay.io/cephcsi/cephcsi:v2.1.1
    imagePullPolicy: IfNotPresent
    name: csi-cephfsplugin
    resources: {}
...
    image: quay.io/cephcsi/cephcsi:v2.1.1
    imagePullPolicy: IfNotPresent
    name: liveness-prometheus
    resources: {}
```
Limits/requests don't apply to other csi pod.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux 8 (Core)
* Kernel (e.g. `uname -a`): 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod): 1.3.3
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.9
* Kubernetes version (use `kubectl version`): 1.18.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):  baremetal(kubeadm)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): 
  cluster:
    id:     483f12d6-fee6-4bf9-98d8-313769921520
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 3d)
    mgr: a(active, since 3d)
    mds: rook-filesystem:1 {0=rook-filesystem-a=up:active} 1 up:standby-replay
    osd: 3 osds: 3 up (since 3d), 3 in (since 3d)

  data:
    pools:   3 pools, 96 pgs
    objects: 274 objects, 308 MiB
    usage:   3.8 GiB used, 2.7 TiB / 2.7 TiB avail
    pgs:     96 active+clean
