### ISSUE TITLE
StorageClass definition for shared filesystem ignores pool setting

### ISSUE THREAD

**Issue by psarossy** [rook/rook#5534]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
StorageClass definition ignores pool definition when provisioned by CSI.

**Expected behavior:**
StorageClass definition has a pool definition, it should use that if specified for the volume and PV/PVCs.

**How to reproduce it (minimal and precise):**
1. Create a specific pool (in my case this is an EC coded pool on nvme drives.
2. Define StorageClass as per example config
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme-pool
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  # clusterID is the namespace where operator is deployed.
  clusterID: rook-ceph

  # CephFS filesystem name into which the volume shall be created
  fsName: defaultroot-rep3

  # Ceph pool into which the volume shall be created
  # Required for provisionVolume: "true"
  pool: nvme-ec22

  # Root path of an existing CephFS volume
  # Required for provisionVolume: "false"
  # rootPath: /absolute/path

  # The secrets contain Ceph admin credentials. These are generated automatically by the operator
  # in the same namespace as the cluster.
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph

reclaimPolicy: Retain
```

3. Create a claim
4. Check pool allocation
5. Check layouts via getfattr

The folder created ("volumes") has no pool layout specified at all:
```
$> getfattr -n ceph.dir.layout.pool volumes
volumes: ceph.dir.layout.pool: No such attribute
```

The CSI folder does, but it just inherits the default (explicitly not what I want)
```
$> getfattr -n ceph.dir.layout.pool volumes/csi
# file: volumes/csi
ceph.dir.layout.pool="defaultroot-rep3-data0"
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.4 LTS
* Kernel (e.g. `uname -a`):  4.15.0-99-generic
* Cloud provider or hardware configuration: Bare metal with kubeadm, 5x Dell R720x with 9 drives each
* Rook version (use `rook version` inside of a Rook Pod):  v1.3.1
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.8
* Kubernetes version (use `kubectl version`): v1.18.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): N/A
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_WARN 1 slow ops, oldest one blocked for 188009 sec, mon.e has slow ops
