### ISSUE TITLE
ceph: Enable setting the scheduler name for OSD pods.

### ISSUE THREAD

**Issue by llamerada-jp** [rook/rook#5536]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
- I'd like to set an arbitrary [`.spec.schedulerName`](https://kubernetes.io/docs/reference/scheduling/profiles/#multiple-profiles) for prepare pods and osd pods.
- I expect how to write in `cluster.yml` like below. It is possible to set it in 2 places like `placement`. Does anyone have better ideas?

pattern A:
```
spec:
...
  schedulerNames:
    all: rook-ceph-default-scheduler
    mon: rook-ceph-mon-scheduler
    osd: rook-ceph-osd-scheduler
    mgr: rook-ceph-mgr-scheduler
...
```

pattern B:
```
spec:
...
  storage:
    storageClassDeviceSets:
      - name: ...
        ...
        schedulerName: scheduler-name-for-device-set
...
```

I'd like to make a patch if the community agrees.

**What is use case behind this feature:**

We set `Pod Topology Spread Constraints` because we want to spread OSD pods for each node. However, to spread OSD pods, we need to configure the `weight` parameter on the scheduler. I consulted on [this issue](https://github.com/kubernetes/kubernetes/issues/91234) about how the scheduler works and how to configure the scheduler.
And we need to separate the settings of the scheduler for OSD pods from the settings for other pods. For the above reasons, we need to set a schedulingName on OSD pods.

**Environment**:

Scheduler profile and schedulerName are available from Kubernetes 1.18 or later.
