### ISSUE TITLE
Feature to specify node-affinity and tolleration for cleanup job.

### ISSUE THREAD

**Issue by shikhar7** [rook/rook#5539]
Can we specify some environment variable to generate job like the below ,So that we can run this job on tainted nodes.
```
apiVersion: batch/v1
kind: Job
metadata:
  name: rook-ceph-cleanup-<node-name>
spec:
  template:
    spec:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: {{ .Values.rook_ceph.nodeSelector.key }}
                  operator: In
                  values:
                    - {{ .Values.rook_ceph.nodeSelector.value }}
  #      podAffinity:
  #      podAntiAffinity:
  #      topologySpreadConstraints:
      tolerations:
        - key: {{ .Values.rook_ceph.nodeSelector.key }}
          operator: Equal
          value: {{ .Values.rook_ceph.nodeSelector.value }}
          effect: NoSchedule
      containers:
        - name: rook-ceph-cleanup-<node-name>
          securityContext:
            privileged: true
          image: <rook-image>
          env:
          # if ROOK_DATA_DIR_HOST_PATH is available, then delete the dataDirHostPath
          - name: ROOK_DATA_DIR_HOST_PATH
            value: <dataDirHostPath>
          args: []string{"ceph", "clean"}
          volumeMounts:
            - name: cleanup-volume
              # data dir host path that needs to be cleaned up.
              mountPath: <dataDirHostPath>
      volume:
        - name: cleanup-volume
          hostPath:
            #directory location on the host
            path: <dataDirHostPath>
      restartPolicy: Never 
```

Below are the screenshots of failed jobs.

![image](https://user-images.githubusercontent.com/18174818/82820042-1535a200-9ebf-11ea-8c63-9f41653c29d8.png)

![image](https://user-images.githubusercontent.com/18174818/82820063-1f57a080-9ebf-11ea-876d-7be4d0783fcb.png)
