### ISSUE TITLE
Suggest pruning unknown fields

### ISSUE THREAD

**Issue by anencore94** [rook/rook#5542]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Is there any plan to support pruning rather than preserving unknown fields?(https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#preserving-unknown-fields)

For now, since the pruning is disabled for crds of rook, it only validate known fields, does not check any validation for unknown fields and just store them in etcd.

For example, if i specified some unknown fields for kind CephCluster like this : `spec.aaa : aaa` or `spec.resource : aaa` (*not the 'resources' field)

When I request to create such CephCluster with `kubectl create -f example.yaml`, the response says cephcluster created well. Also, when I request to get such cephcluster, I can see the miswritten field is stored in etcd.

I think the crds which are auto-generated by operator-sdk unset `preserveUnknownFields` by default, so the crds in rook doesn't use pruning. But I think to use pruning unknown fields is powerful to prevent misuse crs.

Is there any plan to apply `preserveUnknownFields : false` (Pruning enabled) on rook's apiextensions.k8s.io/v1beta1_crds ?

**What is use case behind this feature:**

If we use pruning for crds, we can prevent misusing such as typo easily. Since when applying cr with unknown field, the validation error occured. Also, even if user applied cr with unknown field with `kubectl apply --validate=false` option, etcd stores only known fields.

**Environment**:

- rook v1.2.7
- k8s v1.15.3, v1.16.8

**Comment by leseb** [comment]
@anencore94 thanks for pointing this out. I think we should add it. Thanks for the detailed description as well. I'm sending a PR for this.

**Comment by anencore94** [comment]
@leseb Thanks for accept this issue. However, I think the crd need one more field besides `preserveUnknownFields : false`

I guess e2e test will find it anyway. For me, with k8s v1.15.3 need to specify `type:object` every item when i add only `preserveUnknownFields : false`
(such error occured when applying revised crds)

But, in k8s v1.16.3, specifying only `preserveUnknownFields : false` field was allowed.

I guess this happens since the pruning feature is stable with k8s >= v1.16.

**Comment by anencore94** [comment]
For example,
Applying the first yaml with kubectl is allowed in k8s v1.16, but not allowed in v1.15, and the second yaml is allowed in both version. You can see what i'm saying when try applying below yamls, if my test was right.

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephblockpools.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephBlockPool
    listKind: CephBlockPoolList
    plural: cephblockpools
    singular: cephblockpool
  scope: Namespaced
  version: v1
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            failureDomain:
                type: string
            replicated:
              properties:
                size:
                  type: integer
                  minimum: 0
                  maximum: 9
                targetSizeRatio:
                  type: number
                requireSafeReplicaSize:
                  type: boolean
            erasureCoded:
              properties:
                dataChunks:
                  type: integer
                  minimum: 0
                  maximum: 9
                codingChunks:
                  type: integer
                  minimum: 0
                  maximum: 9
            compressionMode:
              type: string
              enum:
              - ""
              - none
              - passive
              - aggressive
              - force
  subresources:
    status: {}
```


```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephblockpools.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephBlockPool
    listKind: CephBlockPoolList
    plural: cephblockpools
    singular: cephblockpool
  scope: Namespaced
  version: v1
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            failureDomain:
                type: string
            replicated:
              type: object
              properties:
                size:
                  type: integer
                  minimum: 0
                  maximum: 9
                targetSizeRatio:
                  type: number
                requireSafeReplicaSize:
                  type: boolean
            erasureCoded:
              type: object
              properties:
                dataChunks:
                  type: integer
                  minimum: 0
                  maximum: 9
                codingChunks:
                  type: integer
                  minimum: 0
                  maximum: 9
            compressionMode:
              type: string
              enum:
              - ""
              - none
              - passive
              - aggressive
              - force
  subresources:
    status: {}
```
