### ISSUE TITLE
Podantiaffinity for rgw

### ISSUE THREAD

**Issue by zerkms** [rook/rook#5564]
**Is this a bug report or feature request?**
* Feature Request

At the moment rgw are created without any `podAntiAffinity` whatsoever.

In my cluster I just created a new `CephObjectStore` with `spec.gateway.instances: 2`.

And they have both been scheduled to run on the same node (while more than one is available).

**What should the feature do:**

The operator should add `podAntiAffinity` for `rgw` to improve availability.

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
@zerkms Agreed rook should add the antiaffinity by default. Until that is done, you can set the antiaffinity in the [placement](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/object.yaml#L67) for the CephObjectStore.

**Comment by ashangit** [comment]
which rook release are you using?
on my side with release 1.2.7/1.3.4 I have appropriate config automatically generated by rook:
```
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: rook-ceph-rgw
            ceph_daemon_id: tt-1
            rgw: tt-1
            rook_cluster: rook-ceph
            rook_object_store: tt-1
        topologyKey: kubernetes.io/hostname
```

**Comment by zerkms** [comment]
It's 1.3.3 here.

Any chance it was changed in 1.3.4 in particular?

**Comment by ashangit** [comment]
This was already working on 1.2.7 at least so I don't think so
Can you share the complete CephObjectStore yaml file, perhaps some config leads to the podAntiAffinity not beeing set?

**Comment by zerkms** [comment]
It's the one from the documentation:

```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: false
  gateway:
    type: s3
    sslCertificateRef:
    port: 80
    securePort:
    instances: 2
```
