### ISSUE TITLE
OSDs and OSD Prepare pods on PVCs need independent settings for placement and resource limits

### ISSUE THREAD

**Issue by jaimehrubiks** [rook/rook#5586]
For some reason, two OSDs end up in the same node.

I have read the discussion here https://github.com/rook/rook/issues/4582 but I am still missing something.

My guess is that there is some issue with availability of resources between osd and osd-prepare, as both use the same resources requests.

I am specifying this on OSD, on 4 core nodes: (once any of these pods is running we only have 1.9 available cpu)
```
      resources:
        limits:
          cpu: "2000m"
          memory: "4Gi"
        requests:
          cpu: "2000m"
          memory: "4Gi"
```

**Expected behavior:**
Each OSD should be deployed on a different node.

**How to reproduce it (minimal and precise):**
You need a 3.99 cpu server (or one with less resources available than double the resources that you are requesting for OSDs)

```
  storage:
    storageClassDeviceSets:
    - name: set1
      count: 3
      portable: false
      tuneSlowDeviceClass: true
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role
                operator: In
                values:
                - ceph-node
        tolerations:
        - key: ceph-node
          operator: Exists
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
        topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-osd
              - rook-ceph-osd-prepare
      resources:
        limits:
          cpu: "2000m"
          memory: "4Gi"
        requests:
          cpu: "2000m"
          memory: "4Gi"
```

**What doesn't work**
Removing  rook-ceph-osd-prepare from affinity rules does not work.
Changing preferred to required on affinity rules does not work.

**Workaround**
As soon as you lower or remove the resources requests, the cluster is deployed as intended.

**Comment by OpsPita** [comment]
Well after trying everything looks like i cant achive each OSD speard to the same node pool (Storage pool)

The storage pool labeled
    with
`usage: storagev2`

i have 3 nodes
`k get nodes | grep storage
gke-dev-platform-storage-poolv2-97ce192e-dfgg         Ready    <none>   174m    v1.16.9-gke.6
gke-dev-platform-storage-poolv2-97ce192e-k00m         Ready    <none>   174m    v1.16.9-gke.6
gke-dev-platform-storage-poolv2-97ce192e-vs85         Ready    <none>   174m    v1.16.9-gke.6`

OSD Spread look like that :
`rook-ceph-osd-0-76986c5d6d-t694h                                  1/1     Running   0          47m    10.1.6.18       gke-dev-platform-storage-poolv2-97ce192e-vs85         <none>           <none>
rook-ceph-osd-1-6f575b9dcc-s8snm                                  1/1     Running   0          67s    10.1.6.19       gke-dev-platform-storage-poolv2-97ce192e-vs85         <none>           <none>
rook-ceph-osd-2-778cdc797-dj5sm                                   1/1     Running   0          14m    10.1.7.21       gke-dev-platform-storage-poolv2-97ce192e-k00m         <none>           <none>`

Cluster Configuration looks like that:

`apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: dev1-ceph
  namespace: rook-ceph
spec:
  dashboard:
    enabled: true
   # urlPrefix: /ceph-dashboard
    #port: 8443
    ssl: false
  monitoring:
    enabled: true
  cephVersion:
    image: ceph/ceph:v14.2.9
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    volumeClaimTemplate:
      spec:
        storageClassName: standard-1
        resources:
          requests:
            storage: 50Gi
  removeOSDsIfOutAndSafeToRemove: true
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  crashCollector:
    disable: false
  storage:
   storageClassDeviceSets:
    - name: storage0
      count: 3
      portable: true
      tuneSlowDeviceClass: true
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 100Gi
          # IMPORTANT: Change the storage class depending on your environment (e.g. local-storage, gp2)
          storageClassName: standard-1
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
      placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: usage
                    operator: In
                    values:
                    - storagev2
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rook-ceph-osd
                  - key: app
                    operator: In
                    values:
                    - rook-ceph-osd-prepare
                topologyKey: kubernetes.io/hostname
            topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                  - rook-ceph-osd-prepare
          mon:
            nodeAffinity:
              RequiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    - key: usage
                      operator: In
                      values:
                      - storagev2
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - rook-ceph-mon
                  topologyKey: kubernetes.io/hostname`


Looking for solution , really looking forward and use rook operator for ceph .
Some day it will be deployed to Production and we looking for infinity scale on the sides of Storage , MultiClustering, Networking

So right now im running it on dev environment

**Comment by travisn** [comment]
Have you tried changing the antiaffinity from `preferredDuringSchedulingIgnoredDuringExecution` to `requiredDuringSchedulingIgnoredDuringExecution`?

**Comment by OpsPita** [comment]
@travisn ill try it right now and update.

**Comment by OpsPita** [comment]
Before changing the cluster state
```
rook-ceph-osd-0-855fd66cbd-8vgkn                                  1/1     Running     0          11m     10.1.6.67       gke-dev-platform-storage-poolv2-97ce192e-vs85         <none>           <none>
rook-ceph-osd-1-7bf6bbb586-r8j8n                                  1/1     Running     0          9m54s   10.1.6.68       gke-dev-platform-storage-poolv2-97ce192e-vs85         <none>           <none>
rook-ceph-osd-2-7f7b69bb86-9chxf                                  1/1     Running     0          7m54s   10.1.7.67       gke-dev-platform-storage-poolv2-97ce192e-k00m         <none>           <none>
```

After editing the cephcluster.yaml the operator kicked in and placed the first osd on other node and all was looking great!
```
rook-ceph-osd-0-5dbf67f97c-nnshr                                  1/1     Running     0          98s     10.1.8.65       gke-dev-platform-storage-poolv2-97ce192e-dfgg         <none>           <none>
rook-ceph-osd-1-7bf6bbb586-r8j8n                                  1/1     Running     0          11m     10.1.6.68       gke-dev-platform-storage-poolv2-97ce192e-vs85         <none>           <none>
rook-ceph-osd-2-7f7b69bb86-9chxf                                  1/1     Running     0          9m38s   10.1.7.67       gke-dev-platform-storage-poolv2-97ce192e-k00m         <none>           <none>
```
But the operator didnt finished the operation so he continue to replace the osd's .

```
rook-ceph-osd-0-5dbf67f97c-nnshr                                  1/1     Running     0          2m11s   10.1.8.65       gke-dev-platform-storage-poolv2-97ce192e-dfgg         <none>           <none>
rook-ceph-osd-1-77cbdcd6d7-lwwh2                                  0/1     Init:0/4    0          20s     <none>          gke-dev-platform-storage-poolv2-97ce192e-dfgg         <none>           <none>
rook-ceph-osd-2-7f7b69bb86-9chxf                                  1/1     Running     0          10m     10.1.7.67       gke-dev-platform-storage-poolv2-97ce192e-k00m         <none>           <none>
```

Looks like there are 2 osd's that attached to each other ?? is it something possible ?

so @travisn , i checked requiredDuringSchedulingIgnoredDuringExecution, and nothing changed .

**Comment by tomaaron** [comment]
@OpsPita did you completely delete the podAntiAffinity rule in placement? I'm also having troubles with the placement.

**Comment by OpsPita** [comment]
@tomaaron
I deployed the cluster
And then after deployment
I edited and deleted the
osd-prepare from podantiaffinity


The osd
And osd prepare
Conflicts there.

 if you deployed it on cloud with vpc
You can apply it. 

Make your osd's portable: true

@travisn
Please consider separation for pod anti affinity for both components

**Comment by travisn** [comment]
Yes, we really do need to have separate placement and resource limits for osd prepare and osd daemons. They are already separate for the non-PVC case, but they were not separated for the PVC case.

**Comment by tomaaron** [comment]
I deployed a fresh cluster and got the correct placement with the following settings:
```
placement:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchLabels:
            app: rook-ceph-osd-prepare
```
and the placements are:
```
rook-ceph-osd-prepare-set1-data-0-vpwmd-xw56c                     0/1     Completed   0          27s    192.168.222.61    tomtest-jnhfxpzw7loc-node-4   <none>           <none>
rook-ceph-osd-prepare-set1-data-1-jxfxj-7cl5f                     0/1     Completed   0          28s    192.168.153.20    tomtest-jnhfxpzw7loc-node-1   <none>           <none>
rook-ceph-osd-prepare-set1-data-2-zpzhh-cp89p                     0/1     Completed   0          27s    192.168.163.166   tomtest-jnhfxpzw7loc-node-0   <none>           <none>
```
