### ISSUE TITLE
Creating a pool CR at the same time as cluster creation results in a pool without PG autoscaling enabled

### ISSUE THREAD

**Issue by surajssd** [rook/rook#5608]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I have following setting on `CephCluster` object which enabled PG autoscler:

```yaml
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
```

(**NOTE**: These commands are run from a toolbox pod)

And I see correct setting in the cluster:

```console
# ceph config dump
WHO       MASK LEVEL    OPTION                             VALUE RO 
global         advanced osd_pool_default_pg_autoscale_mode on       
```

But when I check it on the pool this is what I see, this pool is in `warn` and not `on`:

```console
# ceph osd pool autoscale-status
POOL          SIZE TARGET SIZE RATE RAW CAPACITY  RATIO TARGET RATIO BIAS PG_NUM NEW PG_NUM AUTOSCALE 
replicapool 360.5G              3.0        3241G 0.3336               1.0     32        128 warn
```

**Possible problem**

I think that this is a timing issue. I create `CephCluster` and `CephBlockPool` consecutively and immediately. And maybe there is a race condition of some sort. But I could be wrong here and the underlying issue could be something else.

The workaround right now is to manually change the setting:

```console
# ceph osd pool set replicapool pg_autoscale_mode on
set pool 1 pg_autoscale_mode to on
```

**Expected behavior:**

I expect the pool `replicapool` to be in `on` state and not `warn`.

**How to reproduce it (minimal and precise):**

Create a `CephCluster` with following config, to enable PG autoscler:

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook
spec:
  cephVersion:
    image: ceph/ceph:v14.2.8
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
    ssl: true
  monitoring:
    enabled: true
    rulesNamespace: rook
  network:
  rbdMirroring:
    workers: 0
  crashCollector:
    disable: false
  cleanupPolicy:
    deleteDataDirOnHosts: ""
  removeOSDsIfOutAndSafeToRemove: false
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: true
    config:
      storeType: bluestore
      osdsPerDevice: "1" # this value can be overridden at the node or device level
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
```

And immediately create a `CephBlockPool` as simple as this:

```yaml
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook
spec:
  failureDomain: host
  replicated:
    size: 3
```

Now deploy rook toolbox and run the following commands: 

```bash
ceph config dump | grep autoscale
ceph osd pool autoscale-status
```

And verify if there is any discrepancy.

**Environment**:
* OS:

```console
$ cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2247.7.0
VERSION_ID=2247.7.0
BUILD_ID=2019-11-20-1554
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2247.7.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
```

* Kernel:

```console
$ uname -a
Linux suraj-lk-cluster-monitoring-worker-0 4.19.84-flatcar #1 SMP Wed Nov 20 14:40:21 -00 2019 x86_64 Intel(R) Atom(TM) CPU C2550 @ 2.40GHz GenuineIntel GNU/Linux
```

* Cloud provider or hardware configuration:

Packet Cloud and machine https://www.packet.com/cloud/servers/c2-medium-epyc/

* Rook version:

`v1.3.2`

* Storage backend version:

```console
# ceph -v
ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)
```

* Kubernetes version:

```json
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster type:

Lokomotive https://github.com/kinvolk/lokomotive

* Storage backend status:

```console
# ceph status
  cluster:
    id:     2d726a72-8c3c-497f-b42f-cb9f6648dc45
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 2h)
    mgr: a(active, since 119m)
    osd: 9 osds: 9 up (since 2h), 9 in (since 2h); 12 remapped pgs
 
  data:
    pools:   1 pools, 128 pgs
    objects: 92.59k objects, 361 GiB
    usage:   1.1 TiB used, 2.1 TiB / 3.2 TiB avail
    pgs:     15200/277761 objects misplaced (5.472%)
             116 active+clean
             11  active+remapped+backfill_wait
             1   active+remapped+backfilling
 
  io:
    client:   125 KiB/s wr, 0 op/s rd, 0 op/s wr
    recovery: 158 MiB/s, 39 objects/s
```
