### ISSUE TITLE
unsupported provisioner when reconciling ObjectBucketClaim

### ISSUE THREAD

**Issue by benceszikora** [rook/rook#5675]
**Deviation from expected behavior:**

I have the following claim:
```
kind: ObjectBucketClaim
metadata:
  name: backups
  namespace: metrics
spec:
  bucketName: backups
  storageClassName: rook-ceph-objectstore-bucket
```
This is the matching storageclass:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-objectstore-bucket
parameters:
  objectStoreName: objectstore
  objectStoreNamespace: rook-ceph
  region: fpig
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
```
However, the operator says that `rook-ceph.ceph.rook.io/bucket` is an unsupported provisioner and it doesn't create the bucket:
```
controller.go:203]  "msg"="reconciling claim" "key"="metrics/backups"
helpers.go:80]  "msg"="getting claim for key" "key"="metrics/backups"
helpers.go:181]  "msg"="getting ObjectBucketClaim's StorageClass" "key"="metrics/backups"
helpers.go:186]  "msg"="got StorageClass" "key"="metrics/backups" "name"="rook-ceph-objectstore-bucket"
controller.go:223]  "msg"="unsupported provisioner" "key"="metrics/backups" "got"="rook-ceph.ceph.rook.io/bucket"
```

I know other people had similar issues when migrating and still having the provisioner `ceph.rook.io/bucket`, but this is a brand new rook cluster and didn't have any StorageClasses, buckets or ObjectBucketClaims set up previously.

Any ideas why this might be happening?

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): `1.3.6`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)`
* Kubernetes version (use `kubectl version`): `1.16.2`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `vanilla Kubernetes`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_OK`

**Comment by thotz** [comment]
@benceszikora : please check your operator.yaml and confirm the following is set `ROOK_OBC_WATCH_OPERATOR_NAMESPACE: "true"`

**Comment by benceszikora** [comment]
@thotz Thanks, that did seem to help. I saw that option earlier, but found no docs for it at all so I wasn't sure if it was what I needed. Both the naming of the option and https://github.com/rook/rook/blob/aca541803be331b38a70292ee2009f3d397a947a/pkg/operator/ceph/object/objectstore.go#L353 seems to imply that this will make rook watch only the operator namespace. It would be good to mention the exact purpose of this in the Object Bucket Claim docs.

**Comment by thotz** [comment]
@benceszikora https://github.com/rook/rook/pull/5679

**Comment by benceszikora** [comment]
@thotz maybe I am misunderstanding something here, but my ObjectBucketClaim is neither in my operator or my cluster namespaces, it's in a third one. I got the error I mentioned above when `ROOK_OBC_WATCH_OPERATOR_NAMESPACE` was not set, and it was resolved when I set that to `true`. Based on this, I would think that the option either has some unintended side effects, or that description is not entirely accurate.

**Comment by thotz** [comment]
> @thotz maybe I am misunderstanding something here, but my ObjectBucketClaim is neither in my operator or my cluster namespaces, it's in a third one. I got the error I mentioned above when `ROOK_OBC_WATCH_OPERATOR_NAMESPACE` was not set, and it was resolved when I set that to `true`. Based on this, I would think that the option either has some unintended side effects, or that description is not entirely accurate.

@leseb ^^

**Comment by leseb** [comment]
> @thotz maybe I am misunderstanding something here, but my ObjectBucketClaim is neither in my operator or my cluster namespaces, it's in a third one. I got the error I mentioned above when `ROOK_OBC_WATCH_OPERATOR_NAMESPACE` was not set, and it was resolved when I set that to `true`. Based on this, I would think that the option either has some unintended side effects, or that description is not entirely accurate.

This has nothing to do with the source from where the OBC originated from. Just like you said, the OBC is intended for client consumption so it's almost never in the op or the cephcluster namespace.

What matters is the prefix used in the SC provisioner line. We prefix it with the `rook-ceph` cluster namespace.

You mentioned this was a brand new deployment but likely used an old opetator.yaml since `ROOK_OBC_WATCH_OPERATOR_NAMESPACE` was false. So yes, we can do better by adding more doc to the flag but your configuration was incorrect AFAIK.

**Comment by vc43** [comment]
The same trouble.
I tried to create new ObjectBucketClaim in new rook-ceph cluster deployed by helm chart v1.3.6. I tried both provisioner "ceph.rook.io/bucket" and "rook-ceph.ceph.rook.io/bucket" , but I got an error "msg"="unsupported provisioner" in both cases until i removed the ROOK_OBC_WATCH_OPERATOR_NAMESPACE from rook-ceph-operator deployment. After that it's started to work only with provisioner "ceph.rook.io/bucket".

**Comment by thotz** [comment]
> The same trouble.
> I tried to create new ObjectBucketClaim in new rook-ceph cluster deployed by helm chart v1.3.6. I tried both provisioner "ceph.rook.io/bucket" and "rook-ceph.ceph.rook.io/bucket" , but I got an error "msg"="unsupported provisioner" in both cases until i removed the ROOK_OBC_WATCH_OPERATOR_NAMESPACE from rook-ceph-operator deployment. After that it's started to work only with provisioner "ceph.rook.io/bucket".

What was namespace for the ceph cluster?

**Comment by vc43** [comment]
> What was namespace for the ceph cluster?
"ceph". Also I tried "ceph.ceph.rook.io/bucket".

**Comment by thotz** [comment]
> > What was namespace for the ceph cluster?
> 
> "ceph". Also I tried "ceph.ceph.rook.io/bucket".
> 

Then it should work imo

**Comment by terorie** [comment]
@thotz Our cluster has been through a few Rook upgrades, and still has a StorageClass with the old provisioner. `ceph.rook.io/bucket`

Currently, with Rook v1.4 and v1.5 ObjectBucketClaims reconciliation is broken, same exact error as OP is seeing.

The CephCluster and CephObjectStore are in `rook-ceph`. The ObjectBucketClaims are all in the `default` namespace.

Am I correct in saying the StorageClass provisioner string has changed from `ceph.rook.io/bucket` to `<namespace>.ceph.rook.io/bucket` in some update? I couldn't find anything in the Rook Docs page about this, so I'm not sure.

Trying to update the `StorageClass` results in another error:

```
cephobjectstore.ceph.rook.io/object-store configured
The StorageClass "rook-ceph-bucket" is invalid: provisioner: Forbidden: updates to provisioner are forbidden.
```

I'm not brave enough to recreate the SC because we have about 10 TB of data in buckets, and don't want to risk confusing the operator or losing data. Do you have any advice?

**Resources:**

<details>
<summary>CephObjectStore</summary>

```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: object-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    replicated:
      size: 2
  preservePoolsOnDelete: true
  gateway:
    type: s3
    sslCertificateRef:
    port: 80
    # securePort:
    instances: 1
```

</details>

<details>
<summary>StorageClass</summary>

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-bucket
provisioner: ceph.rook.io/bucket
parameters:
  objectStoreName: object-store
  objectStoreNamespace: rook-ceph
  region: us-west-1
reclaimPolicy: Delete
```
</details>

**Comment by terorie** [comment]
Nevermind, I found the fix.
It was patching `ROOK_OBC_WATCH_OPERATOR_NAMESPACE` to `"false"` to support provisioning OBCs outside the `rook-ceph` namespace.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ceph-cluster.yaml
- ceph-toolbox.yaml
- object.yaml
- _rook/cluster/examples/kubernetes/ceph/operator.yaml
- _rook/cluster/examples/kubernetes/ceph/monitoring/service-monitor.yaml
- _rook/cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
patches:
- target:
    version: v1
    kind: ConfigMap
    namespace: rook-ceph
    name: rook-ceph-operator-config
  patch: |
    - op: replace
      path: /data/ROOK_OBC_WATCH_OPERATOR_NAMESPACE
      value: "false"
```
