### ISSUE TITLE
Rook-EdgeFS: Unable to mount NFS volume on Ubuntu 20.04 (Focal Fossa)

### ISSUE THREAD

**Issue by fjudith** [rook/rook#5688]
**Is this a bug report or feature request?**
* Bug Report

Pods relying on the `edgefs-nfs-csi-storageclass` are unable to mount NFS volumes.

```bash
Mounting arguments: -t nfs -o vers=3,tcp 10.111.118.34:/tenant0/pvc-5b33511a-7c99-43e9-9e9f-10f3b59ff933 /var/lib/kubelet/pods/b702975a-4dc7-4636-a7fd-203e4ca6be81/volumes/kubernetes.io~csi/pvc-5b33511a-7c99-43e9-9e9f-10f3b59ff933/mount
Output: mount.nfs: requested NFS version or transport protocol is not supported
```

**Deviation from expected behavior:**

Rook-EdgeFS tries to mount volume using NFS protocol version 3 instead of 4.

**Expected behavior:**

Volume should be mounted using the NFS version 4.
Local mount from the same node running the nginx pod works.

```bash
mkdir /mnt/test
mount -v -t nfs -o vers=3,tcp 10.111.118.34:/tenant0/pvc-8a1b7f21-43fa-4054-b3b7-6b5cb20cfb37 /mnt/test
```
```text
mount.nfs: timeout set for Tue Jun 23 20:13:38 2020
mount.nfs: trying text-based options 'vers=3,tcp,addr=10.111.118.34'
mount.nfs: prog 100003, trying vers=3, prot=6
mount.nfs: portmap query failed: RPC: Program not registered
mount.nfs: requested NFS version or transport protocol is not supported
```
```bash
mount -v -t nfs -o vers=4,tcp 10.111.118.34:/tenant0/pvc-8a1b7f21-43fa-4054-b3b7-6b5cb20cfb37 /mnt/test
```
```text
mount.nfs: timeout set for Tue Jun 23 20:14:54 2020
mount.nfs: trying text-based options 'tcp,vers=4,addr=10.111.118.34,clientaddr=10.0.1.13'
```

**How to reproduce it (minimal and precise):**

Run the nginx dynamic provisionning example:

```bash
https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/edgefs/csi/nfs/examples/dynamic-nginx.yaml
```

**File(s) to submit**:

```bash
kubectl describe pod nginx

Events:
  Type     Reason       Age                 From             Message
  ----     ------       ----                ----             -------
  Warning  FailedMount  15m (x20 over 72m)  kubelet, node05  Unable to attach or mount volumes: unmounted volumes=[edgefs-nfs-csi-volume], unattached volumes=[edgefs-nfs-csi-volume default-token-rw57n]: timed out waiting for the condition
  Warning  FailedMount  10m (x9 over 74m)   kubelet, node05  Unable to attach or mount volumes: unmounted volumes=[edgefs-nfs-csi-volume], unattached volumes=[default-token-rw57n edgefs-nfs-csi-volume]: timed out waiting for the condition
  Warning  FailedMount  5s (x45 over 76m)   kubelet, node05  MountVolume.SetUp failed for volume "pvc-5b33511a-7c99-43e9-9e9f-10f3b59ff933" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs -o vers=3,tcp 10.111.118.34:/tenant0/pvc-5b33511a-7c99-43e9-9e9f-10f3b59ff933 /var/lib/kubelet/pods/b702975a-4dc7-4636-a7fd-203e4ca6be81/volumes/kubernetes.io~csi/pvc-5b33511a-7c99-43e9-9e9f-10f3b59ff933/mount
Output: mount.nfs: requested NFS version or transport protocol is not supported
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04 (Focal Fossa)
* Kernel (e.g. `uname -a`): Linux node04 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Hetzner CPX41
* Rook version (use `rook version` inside of a Rook Pod): 1.3.6
* Storage backend version (e.g. for ceph do `ceph -v`): docker.io/edgefs/edgefs:1.3.35
* Kubernetes version (use `kubectl version`): 1.18.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): OK

**Comment by fjudith** [comment]
Found the `nfsMountOptions` parameter in the **nexenta/edgefs-csi** wiki.

https://github.com/Nexenta/edgefs-csi/wiki

I'm going to check if it works by adding the following parameter in my `edgefs-nfs-csi-driver-config.yaml`

```yaml
# edgefs-nfs-csi-driver config file to create k8s secret
#
# $ kubectl create secret generic edgefs-nfs-csi-driver-config --from-file=./edgefs-nfs-csi-driver-config.yaml
#

#Edgefs k8s cluster options
k8sEdgefsNamespaces: ["rook-edgefs"] # element 0 is a default edgefs cluster namespace, add more when needed
k8sEdgefsMgmtPrefix: rook-edgefs-mgr # edgefs cluster management prefix

# Edgefs csi operatins options
cluster: cluster0 #substitution edgefs cluster name for csi operations
tenant: tenant0    #substitution edgefs tenant name for csi operations
#serviceFilter: "nfs01" #List of comma delimeted allowed service names to filter

# Edgefs connnection options
username: admin #edgefs k8s cluster grpc connection username
password: admin #edgefs k8s cluster  grpc connection password

# EdgeFS nfs mount options (default "vers=3,tcp)
nfsMountOptions: "vers=4,tcp"

```
