### ISSUE TITLE
by-path format not working

### ISSUE THREAD

**Issue by jc-lab** [rook/rook#5728]
**Is this a bug report or feature request?**
* Bug Report

**Expected behavior:**
The device must be able to be registered through the device path in the form of by-path.

**File(s) to submit**:
* cluster.yaml
```
...
      devices:
      - name: "/dev/disk/by-path/pci-0000:02:00.0-scsi-0:1:0:3:1" # Not working
      - name: "/dev/disk/by-path/pci-0000\\:02:00.0-scsi-0\\:1\\:0\\:3:1" # Not working
```

* LOG (osd-prepare):
```
failed to parse device list ("/dev/disk/by-path/pci-0000\\:02:00.0-scsi-0\\:1\\:0\\:1:1:::,/dev/disk/by-path/pci-0000\\:02:00.0-scsi-0\\:1\\:0\\:2:1:::,/dev/disk/by-path/pci-0000\\:02:00.0-scsi-0\\:1\\:0\\:3:1:::,/dev/disk/by-path/pci-0000\\:02:00.0-scsi-0\\:1\\:0\\:4:1:::,/dev/disk/by-path/pci-0000\\:02:00.0-scsi-0\\:1\\:0\\:5:1:::,/dev/disk/by-path/pci-0000\\:02:00.0-scsi-0\\:1\\:0\\:6:1:::"): error DatabaseSizeMB ("00.0-scsi-0\\") to int: strconv.Atoi: parsing "00.0-scsi-0\\": invalid syntax
```

**Environment**:
* OS (e.g. from /etc/os-release):  20.04 LTS (Focal Fossa)
* Kernel (e.g. `uname -a`): Linux 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: On-premise
* Rook version (use `rook version` inside of a Rook Pod): v1.2.7
* Storage backend version (e.g. for ceph do `ceph -v`):  ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)
* Kubernetes version (use `kubectl version`): v1.16.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
