### ISSUE TITLE
Add basic OSD topology info to the CephCluster CR status

### ISSUE THREAD

**Issue by travisn** [rook/rook#5754]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The deviceClasses of OSDs should be more discoverable so the admin can more easily make the decision to create pools with different deviceClasses. For example, the admin might want to create one pool on ssds and another pool on hdds. Today the admin needs to start the toolbox and run a command such as `ceph osd tree` to see the device classes for each OSD. Instead of making the admin launch the toolbox, Rook could simplify this step by storing information about the OSDs and device classes in the CephCluster CR status.

The sequence would be the following:
- The CephCluster CR is created (or updated)
- Rook reconciles the cluster and creates OSDs
- As each OSD is created, Ceph discovers and assigns the deviceClass
- After the OSD reconcile is completed, the Rook operator would:
   - Query ceph for the deviceClasses on the OSDs
   - Update the status on the CephCluster CR 

The same status structure could also be expanded in the future to include basic configuration stats about the cluster. We shouldn't included anything more than basic info since the prometheus metrics fill that purpose. For example, size and usage info is already included in prometheus data.

To support future expansion of the properties, the status might include the following:
```yaml
  status:
    ceph:
      health: HEALTH_OK
      lastChecked: "2020-07-02T21:24:33Z"
    storage:
      # The device class info to add
      deviceClasses:
      - name: hdd
         count: 6
      - name: ssd
         count: 3
     # Topology attributes to consider
      roots: 1
      zones: 3
      hosts: 3
    version:
      image: ceph/ceph:v15
      version: 15.2.3-0
```

**What is use case behind this feature:**
Simplifying the admin experience to find information about the cluster for creating pools and a quick glance at OSD health.
