### ISSUE TITLE
Rook Ceph Dashboard issue under Nginx Ingress Basic auth

### ISSUE THREAD

**Issue by stepanselyuk** [rook/rook#5757]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Requires basic auth multiple times instead of one. It seems in some moment the backend (i.e. dashboard) sends 401 code which breaks HTTP basic auth session in browsers.

**Expected behavior:**
the dashboard works good when protected by https basic auth.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

My ingress config:
```
metadata:
  name: rook-dashboard
  namespace: rook-ceph
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/cors-allow-headers: '*'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/x-forwarded-prefix: 'true'
spec:
  tls:
    - hosts:
        - rook.k8s.domain.com
      secretName: tls-k8s-domain-com-p
  rules:
    - host: rook.k8s.domain.com
      http:
        paths:
          - backend:
              serviceName: rook-ceph-mgr-dashboard
              servicePort: 8443
status:
  loadBalancer: {}
kind: Ingress
```
