### ISSUE TITLE
rook-ceph-detect-version cannot be scheduled when mon has PodAntiAffinity to place Pods evenly on multiple racks

### ISSUE THREAD

**Issue by tapih** [rook/rook#5810]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I have a k8s cluster running on the nodes in 3 racks.
To make the cluster tolerate rack failure, I add `PodAntiAffinity` to `mon` Pods as shown below to deploy only 1 Pod onto 1 rack (so, 3 `mon`s in total).
Now I successfully deployed 3 `mon`s onto the different racks, but `detect-version` fails to run with the `Pending` state.

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
spec:
...
  placement:
    mon:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: rook-ceph-mon
          topologyKey: topology.kubernetes.io/zone # <- failure domain (e.g. topology.kubernetes.io/zone=rack1)
...
```

**Expected behavior:**

I expect that only 1 `mon` is scheduled on 1 rack and that both the 3 `mon`s and the `detect-version` run successfully.

I looked into https://github.com/rook/rook/pull/3977 and found that `detect-version` has the same `placement` with `mon`'s.
The reason why `detect-version` cannot be deployed seems to be that all the rack has 1 `mon` with `PodAntiAffinity` to prevent more Pods(=`detect-version`) from being deployed.
I would like to avoid using `preferredDuringSchedulingIgnoredDuringExecution` to prevent multiple `mon`s from being deployed onto 1 rack.

**How to reproduce it (minimal and precise):**
1. Create a k8s cluster with 3 worker nodes.

```
$ cat << 'EOF' > kind-cluster.yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta1
  kind: ClusterConfiguration
  metadata:
    name: config
  kubernetesVersion: v1.17.6
  apiServer:
    extraArgs:
      v: 7
  networking:
    serviceSubnet: 10.0.0.0/16
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
EOF

$ kind create cluster --config kind-cluster.yaml
```

2. Add different labels to each node as below:
```
$ kubectl label node kind-worker topology.kubernetes.io/zone=rack1
$ kubectl label node kind-worker2 topology.kubernetes.io/zone=rack2
$ kubectl label node kind-worker3 topology.kubernetes.io/zone=rack3
```

3. Deploy rook operator.

4. Deploy ceph cluster with `PodAntiAffinity` for the `topology.kubernetes.io/zone` label (cf. https://github.com/cybozu-go/neco-apps/blob/f380ea1ae0b5faefba703ebb440bfe13fff5841d/rook/base/ceph-hdd/cluster.yaml#L24-L29).

**File(s) to submit**:

My `cluster.yaml` can be downloaded from [here](https://github.com/cybozu-go/neco-apps/blob/f380ea1ae0b5faefba703ebb440bfe13fff5841d/rook/base/ceph-hdd/cluster.yaml).

**Environment**:
- OS (e.g. from /etc/os-release): CoreOS 2512.3.0
- Kernel (e.g. uname -a): 4.19.123-coreos
- Cloud provider or hardware configuration: x86_64 Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz
- Rook version (use rook version inside of a Rook Pod):  1.3.4
- Storage backend version (e.g. for ceph do ceph -v): 15.2.3
- Kubernetes version (use kubectl version): 1.17.6
- Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): CKE
- Storage backend status (e.g. for Ceph use ceph health in the Rook Ceph toolbox): HEALTH_OK
