### ISSUE TITLE
Monitors IPs got changed and volume mount failed after few restarts of setup

### ISSUE THREAD

**Issue by md-shabbir** [rook/rook#5842]
I have a 6 nodes kubernetes setup with rook-ceph v1.2.7 installed. I have installed rook with 3 mons. After few restart of my VMs, the older mons got deleted and new mons got created along with new services which have new IPs.

The problem is, my all volumes have the older service IPs configured and now volume mount is failing.

Is there any way I can change the IPs of newly created mons service with older one?

**Comment by travisn** [comment]
What client are you using? The CSI driver should pick up the new mon endpoints automatically when there is a failover.

**Comment by md-shabbir** [comment]
@travisn Thanks for your reply.
I am not using CSI driver. Following is the volume section of my pod manifest:
```
  volumes:
  - cephfs:
      monitors:
      - 10.233.16.157:6789
      - 10.233.30.57:6789
      - 10.233.56.86:6789
      path: /
      secretRef:
        name: ceph-secret
      user: admin
```
