### ISSUE TITLE
Failed to define targetSizeRatio with rook 1.3.8

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#5848]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
With rook 1.3.8, try to set "targetSizeRatio", but it gave errors.
1). Without define "targetSizeRatio", it's working.
2). Define the targetSizeRatio as  .4    
```
# knc get CephBlockPool -o yaml
...
  spec:
    compressionMode: ""
    crushRoot: ""
    deviceClass: ""
    erasureCoded:
      algorithm: ""
      codingChunks: 0
      dataChunks: 0
    failureDomain: host
    parameters:
      compression_mode: none
      targetSizeRatio: 0.4
    replicated:
      requireSafeReplicaSize: true
      size: 3
      targetSizeRatio: 0
```
The operator keeps on printing below error messages.
```
E0717 14:29:40.170854       6 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.CephBlockPool: v1.CephBlockPoolList.Items: []v1.CephBlockPool: v1.CephBlockPool.Spec: v1.PoolSpec.Parameters: ReadString: expects " or n, but found 0, error found in #10 byte of ...|zeRatio":0.4},"repli|..., bigger context ...|rs":{"compression_mode":"none","targetSizeRatio":0.4},"replicated":{"requireSafeReplicaSize":true,"s|...
E0717 14:29:41.173459       6 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.CephBlockPool: v1.CephBlockPoolList.Items: []v1.CephBlockPool: v1.CephBlockPool.Spec: v1.PoolSpec.Parameters: ReadString: expects " or n, but found 0, error found in #10 byte of ...|zeRatio":0.4},"repli|..., bigger context ...|rs":{"compression_mode":"none","targetSizeRatio":0.4},"replicated":{"requireSafeReplicaSize":true,"s|...
```
3. Define targetSizeRatio as  '.4'
Operator logs
```
2020-07-17 14:29:51.258414 I | cephclient: setting pool property "targetSizeRatio" to ".4" on pool "csireplpool"
2020-07-17 14:29:52.439956 E | cephclient: failed to set property "targetSizeRatio" to pool "csireplpool" to ".4". failed to set pool property "targetSizeRatio" on pool "csireplpool": exit status 22
(edited)
```

**Expected behavior:**
The targetSizeRatio can be set for block, object and filesystem pools. 

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.3.8
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
