### ISSUE TITLE
ceph: Rook does not add data pools to an already-created filesystem

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#5876]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When a data pool is added  to an already-created filesystem, a new ceph pool is created, but it is not added to the filesystem.

**Expected behavior:**
When adding a data pool to a filesystem, the pool should be both created and added to the filesystem.

**How to reproduce it (minimal and precise):**
Apply the filesystem with one data pool and wait for it to be created.
```yaml
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: cephfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 1
      requireSafeReplicaSize: false
  dataPools:
    - failureDomain: osd
      replicated:
        size: 1
        requireSafeReplicaSize: false
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
```

- Observe with `ceph osd pool ls` that `cephfs-data0` exists.
- Observe `ceph fs ls` returns `name: cephfs, metadata pool: cephfs-metadata, data pools: [cephfs-data0 ]`

Apply changes to the filesystem with a data pool added. 
```yaml
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: cephfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 1
      requireSafeReplicaSize: false
  dataPools:
    - failureDomain: osd
      replicated:
        size: 1
        requireSafeReplicaSize: false
    # add below data pool
    - failureDomain: osd
      replicated:
        size: 1
        requireSafeReplicaSize: false
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
```

- Observe with `ceph osd pool ls` that `cephfs-data0` and `cephfs-data1` both exist.
- Observe `ceph fs ls` still returns `name: cephfs, metadata pool: cephfs-metadata, data pools: [cephfs-data0 ]` (`cephfs-data1` is not added to the fs)

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
