### ISSUE TITLE
Failed to deploy prometheus rule in ceph version v15 (octopus)

### ISSUE THREAD

**Issue by faruryo** [rook/rook#5897]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

PrometheusAlert is not deployed after performing the procedure to enable Ceph Prometheus Alert.
```
$ kubectl get prometheusrule -n rook-ceph
No resources found in rook-ceph namespace.
$ kubectl get servicemonitor -n rook-ceph
NAME            AGE
rook-ceph-mgr   6d
```

[Rook Docs](https://rook.io/docs/rook/v1.3/ceph-monitoring.html)

**Expected behavior:**

The prometheusrule should be deployed.

**How to reproduce it (minimal and precise):**

Deploy the following cephcluster which is set to `spec.cephVersion.image: cephalopods/ceph:v15.2.4`.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    osd_pool_default_size = 1

---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.4
    allowUnsupported: true
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  mon:
    count: 3
    allowMultiplePerNode: true
    volumeClaimTemplate:
      spec:
        storageClassName: topolvm-provisioner
        resources:
          requests:
            storage: 10Gi
  mgr:
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
  monitoring:
    enabled: true
    rulesNamespace: rook-ceph
  crashCollector:
    disable: false
  cleanupPolicy:
    confirmation: ""
  removeOSDsIfOutAndSafeToRemove: false
  storage:
    storageClassDeviceSets:
      - name: set1
        count: 4
        portable: false
        tuneDeviceClass: true
        placement:
          tolerations:
            - operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd-prepare
                  topologyKey: kubernetes.io/hostname
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd
                      - rook-ceph-osd-prepare
        resources:
          limits:
            cpu: "300m"
            memory: "3Gi"
          requests:
            cpu: "300m"
            memory: "3Gi"
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 60Gi
              storageClassName: topolvm-provisioner
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
    useAllNodes: true
    useAllDevices: true
```

* Operator's logs, if necessary
I took an excerpt that looked suspicious.
```
# rook-ceph-operator-685b5459d7-rn2hs
2020-07-23 04:29:27.489859 I | op-mgr: dashboard service already exists
2020-07-23 04:29:27.766810 I | op-mgr: mgr metrics service already exists
2020-07-23 04:29:27.766892 I | op-mgr: starting monitoring deployment
W0723 04:29:27.767184       6 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2020-07-23 04:29:27.773565 I | op-mgr: servicemonitor enabled
2020-07-23 04:29:27.773737 E | op-mgr: failed to deploy prometheus rule. prometheus rule could not be deployed: prometheusRules file could not be fetched. open /etc/ceph-monitoring/prometheus-ceph-v15-rules.yaml: no such file or directory
```

It appears to be due to the fact that only v14 rules exist in the rook/ceph image.

- [rook/Makefile at 44725847265eeba9da0f0dda0d3698ef451e78dd · rook/rook](https://github.com/rook/rook/blob/44725847265eeba9da0f0dda0d3698ef451e78dd/images/ceph/Makefile#L46)
- https://github.com/rook/rook/tree/44725847265eeba9da0f0dda0d3698ef451e78dd/cluster/examples/kubernetes/ceph/monitoring

**Environment**:
* Kernel (e.g. `uname -a`)
I ran it on a kubernetes node.
```
Linux nucknode01 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
* Rook version (use `rook version` inside of a Rook Pod):rook: v1.3.8 / go: go1.13.8
* Storage backend version (e.g. for ceph do `ceph -v`):
```
[root@rook-ceph-tools-7959b9f77c-rg4lx /]# ceph -v
ceph version 14.2.10 (b340acf629a010a74d90da5782a2c5fe0b54ac20) nautilus (stable)

[root@rook-ceph-tools-7959b9f77c-rg4lx /]# ceph tell osd.* version
osd.0: {
    "version": "15.2.4",
    "release": "octopus",
    "release_type": "stable"
}
osd.1: {
    "version": "15.2.4",
    "release": "octopus",
    "release_type": "stable"
}
osd.2: {
    "version": "15.2.4",
    "release": "octopus",
    "release_type": "stable"
}
osd.3: {
    "version": "15.2.4",
    "release": "octopus",
    "release_type": "stable"
}
```

* Kubernetes version (use `kubectl version`):v1.18.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):kubespray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_WARN 1 pool(s) have no replicas configured
