### ISSUE TITLE
OSDs are not spread evenly across the nodes

### ISSUE THREAD

**Issue by kesavanvt** [rook/rook#5926]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
with storageClassDeviceSets count as 6, the OSD placement is not even across 3 worker node in openshift cluster even after specifying the podAntiAffinity and topologySpreadConstraints.

node1 : 3 OSDs
node2 : 3 OSDs
node3 : 0 OSDs

Here gp2 is used as Storage class

**Expected behavior:**
OSD pods should be evenly distributed based on the placements (i.e 2 OSDs per node here) 

**How to reproduce it (minimal and precise):**
On an AWS Openshift Cluster

- Apply common.yaml, operator-openshift.yaml
- Apply cluster-on-pvc.yaml (modify storageClassDeviceSets count as 6)

**File(s) to submit**:

Here is the OSD pod placement
```
oc get pods -l app=rook-ceph-osd -o wide 
NAME                               READY   STATUS    RESTARTS   AGE   IP            NODE                                         NOMINATED NODE   READINESS GATES
rook-ceph-osd-0-85f56c94c6-wl84v   1/1     Running   0          17m   10.128.2.25   ip-10-0-153-239.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-1-bcf6555dc-xc5bz    1/1     Running   0          17m   10.131.0.31   ip-10-0-138-193.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-2-5cf5d55d94-5xdmr   1/1     Running   0          17m   10.131.0.30   ip-10-0-138-193.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-3-684f7cb445-gbtjk   1/1     Running   0          17m   10.131.0.29   ip-10-0-138-193.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-4-8bdb7b65c-jkrbt    1/1     Running   0          17m   10.128.2.27   ip-10-0-153-239.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-5-7ffcd7b78b-fxnqj   1/1     Running   0          17m   10.128.2.26   ip-10-0-153-239.us-east-2.compute.internal   <none>           <none>
```

* cluster-on-pvc.yaml
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: gp2
        resources:
          requests:
            storage: 10Gi
  cephVersion:
    image: ceph/ceph:v15.2.4
    allowUnsupported: false
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
    ssl: true
  crashCollector:
    disable: false
  storage:
    storageClassDeviceSets:
    - name: set1
      count: 6
      portable: true
      tuneDeviceClass: true
      placement:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
        topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-osd
              - rook-ceph-osd-prepare
      resources:
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 10Gi
          storageClassName: gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
```

**Environment**:
* Cloud provider or hardware configuration: aws
* Rook version (use `rook version` inside of a Rook Pod): v1.3.0
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.4
* Kubernetes version (use `kubectl version`): v1.17.1+f63db30
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK
