### ISSUE TITLE
OSDs get into pending state with topologySpreadConstraints

### ISSUE THREAD

**Issue by kesavanvt** [rook/rook#5932]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
with topologySpreadConstraints and storageClassDeviceSets count as 6, some of the OSDs gets into pending state

I believe its something related to #5586, as the osds and osd prepare job shares the same placement config

**Expected behavior:**
OSD pods should be evenly distributed based on the topologySpreadConstraints provided (i.e 2 OSDs per node here)

**How to reproduce it (minimal and precise):**
On an AWS Openshift Cluster

- Apply common.yaml, operator-openshift.yaml
- Apply cluster-on-pvc.yaml as below

**File(s) to submit**:
* cluster-on-pvc.yaml
``` yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: gp2
        resources:
          requests:
            storage: 10Gi
  cephVersion:
    image: ceph/ceph:v15.2.4
    allowUnsupported: false
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
    ssl: true
  crashCollector:
    disable: false
  storage:
    storageClassDeviceSets:
    - name: set1
      count: 6
      portable: true
      tuneDeviceClass: true
      placement:
        topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-osd
              - rook-ceph-osd-prepare
      resources:
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 10Gi
          storageClassName: gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
```

* When both `rook-ceph-osd` and `rook-ceph-osd-prepare` provided as labelselector for topologySpreadConstraints
```
oc get pods -l 'app in (rook-ceph-osd,rook-ceph-osd-prepare)' -o wide 
NAME                                            READY   STATUS      RESTARTS   AGE   IP            NODE                                         NOMINATED NODE   READINESS GATES
rook-ceph-osd-0-977bfcf48-v8kp8                 0/1     Pending     0          22m   <none>        <none>                                       <none>           <none>
rook-ceph-osd-1-7bb84dbb49-6lm86                1/1     Running     0          22m   10.128.2.22   ip-10-0-206-137.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-2-d56cbd9fb-kl894                 1/1     Running     0          21m   10.131.0.21   ip-10-0-186-216.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-3-69b98dd94c-rz8pd                1/1     Running     0          21m   10.129.2.17   ip-10-0-139-123.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-prepare-set1-data-0-hvtk2-89jgq   0/1     Completed   0          22m   10.131.0.19   ip-10-0-186-216.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-prepare-set1-data-1-9mqqw-l48ld   0/1     Completed   0          22m   10.128.2.21   ip-10-0-206-137.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-prepare-set1-data-2-j8nrr-dmf2b   0/1     Completed   0          22m   10.129.2.15   ip-10-0-139-123.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-prepare-set1-data-3-sjbwt-stmnb   0/1     Completed   0          22m   10.129.2.16   ip-10-0-139-123.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-prepare-set1-data-4-vgcl8-86sc9   0/1     Pending     0          22m   <none>        <none>                                       <none>           <none>
rook-ceph-osd-prepare-set1-data-5-jxwf9-zk2lw   0/1     Pending     0          22m   <none>        <none>                                       <none>           <none>
```
* When `rook-ceph-osd` is provided as labelselector for topologySpreadConstraints
```
oc get pods -l 'app in (rook-ceph-osd,rook-ceph-osd-prepare)' -o wide
NAME                                            READY   STATUS      RESTARTS   AGE     IP            NODE                                         NOMINATED NODE   READINESS GATES
rook-ceph-osd-0-74b9455f8f-f2q7w                1/1     Running     0          2m30s   10.128.2.33   ip-10-0-206-137.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-1-7766f8c69b-r5pwn                0/1     Pending     0          2m27s   <none>        <none>                                       <none>           <none>
rook-ceph-osd-2-7d7bc6ccf6-jf8zr                1/1     Running     0          2m22s   10.129.2.29   ip-10-0-139-123.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-3-64c9b9f7b-bkhq4                 0/1     Pending     0          2m20s   <none>        <none>                                       <none>           <none>
rook-ceph-osd-4-86568dc8b9-2kwk8                0/1     Pending     0          2m17s   <none>        <none>                                       <none>           <none>
rook-ceph-osd-5-5948f5844d-mx9g8                0/1     Pending     0          2m15s   <none>        <none>                                       <none>           <none>
rook-ceph-osd-prepare-set1-data-0-5x9fs-7xv66   0/1     Completed   0          2m51s   10.129.2.26   ip-10-0-139-123.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-prepare-set1-data-1-9tgvl-s7jrn   0/1     Completed   0          2m50s   10.128.2.30   ip-10-0-206-137.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-prepare-set1-data-2-w6spn-4n66m   0/1     Completed   0          2m50s   10.129.2.27   ip-10-0-139-123.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-prepare-set1-data-3-r5vph-cjznr   0/1     Completed   0          2m49s   10.129.2.28   ip-10-0-139-123.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-prepare-set1-data-4-s4fpc-h9bfb   0/1     Completed   0          2m49s   10.128.2.31   ip-10-0-206-137.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-prepare-set1-data-5-kv6zg-57kz9   0/1     Completed   0          2m48s   10.129.2.25   ip-10-0-139-123.us-east-2.compute.internal   <none>           <none>
```
**Workarounds:**
The OSDs tends to be running and evenly distributed by the following workarounds

workaround 1

- Making whenUnsatisfiable as `ScheduleAnyway` and with `rook-ceph-osd `and `rook-ceph-osd-prepare` as labelSelector.
I am not sure if its guaranteed to provide even spread for variable counts since it has ScheduleAnyway. 

workaround 2
- With only `rook-ceph-osd-prepare` as labelSelector and whenUnsatisfiable as `DoNotSchedule`

looking for the suggestion on the ideal way for consistent even spread

**Environment**:
* Cloud provider or hardware configuration: aws
* Rook version (use `rook version` inside of a Rook Pod): v1.3.0
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.4
* Kubernetes version (use `kubectl version`): v1.18.3+3107688
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK
