### ISSUE TITLE
ReadWriteMany PVC remains pending

### ISSUE THREAD

**Issue by avarf** [rook/rook#5936]
**Is this a bug report or feature request?**

I chose Ceph because at k8s docs (https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) they mentioned that ceph is one of the volumes that supports `ReadWriteMany`. For dev purposes I created a single-node rook-ceph cluster on my machine. It works fine with `ReadWriteOnce` PVCs but the `ReadWriteMany` PVC remains pending (they are all in one file as below):
```yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: rtspdata-claim
    namespace: {{ .Release.Namespace }}
  spec:
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: registry-claim
    namespace: {{ .Release.Namespace }}
  spec:
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: gstreamer-claim
    namespace: {{ .Release.Namespace }}
  spec:
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: postgres-claim
    namespace: {{ .Release.Namespace }}
  spec:
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
```

I built the rook-ceph cluster using `cluster-test.yaml` which is creating a single node cluster. I also used block storage for it and based on ceph docs block is supporting `ReadWriteMany`: "specifying Block for volumeMode can support ReadWriteOnce, ReadWriteMany, and ReadOnlyMany accessMode claims." (https://docs.ceph.com/docs/master/rbd/rbd-kubernetes/#create-a-persistentvolumeclaim)

**Deviation from expected behavior:**
`ReadWriteMany` PVC remains pending

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary --> I used the official cluster-test.yaml

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04

* Kernel (e.g. `uname -a`):
Linux odin 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration: bare metal

* Rook version (use `rook version` inside of a Rook Pod): v1.3

* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 1.16
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): built using kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
