### ISSUE TITLE
Unable to access ceph dashboard

### ISSUE THREAD

**Issue by SpontaneousDuck** [rook/rook#5960]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Dashboard does not seem to be started. When I view the logs on the `rook-ceph-mgr` pod and sort by serving I only see: 
```
[03/Aug/2020:23:20:51] ENGINE Serving on 0.0.0.0:9283
```
There is no mention of port `8443` in the logs even though the dashboard is enabled in `cluster.yml`. Observing the whole log it does not throw any errors on startup. Is there anything else I should be checking?

**Expected behavior:**
Dashboard is acessible externally
**How to reproduce it (minimal and precise):**
Installed with:
```
helm install --namespace rook-ceph --name rook-ceph --version v1.2.7 rook-release/rook-ceph
kubectl create -f services/rook-cluster.yml
```
`services/rook-cluster.yml` contains:
```
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # For the latest ceph images, see https://hub.docker.com/r/ceph/ceph/tags
    image: ceph/ceph:v14.2
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  storage:
    useAllNodes: true
    useAllDevices: true
    directories:
      - path: /data/rook
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
   annotations:
     storageclass.kubernetes.io/is-default-class: "true"
# based on https://rook.io/docs/rook/master/ceph-block.html
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  # clusterID is the namespace where the rook cluster is running
  clusterID: rook-ceph
  # Ceph pool into which the RBD image shall be created
  pool: replicapool
  # RBD image format. Defaults to "2".
  imageFormat: "2"
  # RBD image features. Available for imageFormat: "2". CSI RBD currently supports only `layering` feature.
  imageFeatures: layering
  # The secrets contain Ceph admin credentials.
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  # Specify the filesystem type of the volume. Default is "ext4"
  csi.storage.k8s.io/fstype: xfs
  # Default is "Delete", https://kubernetes.io/docs/concepts/storage/storage-classes/
reclaimPolicy: Retain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
  labels:
    app: rook-ceph-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: rook-ceph-tools
        image: rook/ceph:v1.2.7
        command: ["/tini"]
        args: ["-g", "--", "/usr/local/bin/toolbox.sh"]
        imagePullPolicy: IfNotPresent
        env:
          - name: ROOK_ADMIN_SECRET
            valueFrom:
              secretKeyRef:
                name: rook-ceph-mon
                key: admin-secret
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /dev
            name: dev
          - mountPath: /sys/bus
            name: sysbus
          - mountPath: /lib/modules
            name: libmodules
          - name: mon-endpoint-volume
            mountPath: /etc/rook
      # if hostNetwork: false, the "rbd map" command hangs, see https://github.com/rook/rook/issues/2021
      hostNetwork: true
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: sysbus
          hostPath:
            path: /sys/bus
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: mon-endpoint-volume
          configMap:
            name: rook-ceph-mon-endpoints
            items:
            - key: data
              path: mon-endpoints
---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: cephfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 1
  dataPools:
    - replicated:
        size: 1
      #failureDomain: osd
  metadataServer:
    activeCount: 1
    activeStandby: true
---
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mgr-dashboard-external-https
  namespace: rook-ceph
  labels:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
spec:
  ports:
  - name: dashboard
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
  sessionAffinity: None
  type: NodePort
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.4 LTS
* Kernel (e.g. `uname -a`): 4.15.0-112-generic
* Cloud provider or hardware configuration: Baremetal
* Rook version (use `rook version` inside of a Rook Pod): 1.2.7
* Storage backend version (e.g. for ceph do `ceph -v`): ceph 14.2.10
* Kubernetes version (use `kubectl version`): 1.18.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Baremetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_WARN 3 pool(s) have no replicas configured`
