### ISSUE TITLE
Recreate an OSD pool failed

### ISSUE THREAD

**Issue by norman-kern** [rook/rook#6064]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
* Receate a ceph osd pool failed.

**Expected behavior:**
* Receate a ceph osd pool successfully.

**How to reproduce it (minimal and precise):**

1. create a ec osd pool successfully
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rbd-test
  namespace: cactusio
spec:
  failureDomain: osd
  erasureCoded:
    dataChunks: 2
    codingChunks: 1
```
2. rm the osd pool
3. recreate a replica pool using the same name
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rbd-test
  namespace: cactusio
spec:
  failureDomain: osd
  replicated:
    size: 3
```
4. using lspools, no pool created
```
Name:         rbd-test
Namespace:    cactusio
Labels:       <none>
Annotations:  <none>
API Version:  ceph.rook.io/v1
Kind:         CephBlockPool
Metadata:
  Creation Timestamp:  2020-08-13T08:54:58Z
  Finalizers:
    cephblockpool.ceph.rook.io
  Generation:        34
  Resource Version:  346969
  Self Link:         /apis/ceph.rook.io/v1/namespaces/cactusio/cephblockpools/rbd-test
  UID:               c935cfb4-0d30-4206-83ba-b5fe74e17e81
Spec:
  Compression Mode:  
  Crush Root:        
  Device Class:      
  Erasure Coded:
    Algorithm:      
    Coding Chunks:  0
    Data Chunks:    0
  Failure Domain:   osd
  Replicated:
    Require Safe Replica Size:  false
    Size:                       3
    Target Size Ratio:          0
Status:
  Phase:  ReconcileFailed
Events:   <none>
```
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 16.04
* Kernel (e.g. `uname -a`): 4.15.0
* Cloud provider or hardware configuration: Dell R740
* Rook version (use `rook version` inside of a Rook Pod): v1.2.1
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.5
* Kubernetes version (use `kubectl version`): v1.15.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): N/a
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): Healthy
