### ISSUE TITLE
SmokeSuite is failing in master with test pod failing to mount a volume

### ISSUE THREAD

**Issue by travisn** [rook/rook#6151]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Master builds are failing consistently in the CephSmokeSuite since [build 2198/2199](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/master/2199/pipeline/63/) after #5740 was merged. 

The CSI driver may be failing to mount the volume as seen in [this log](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/master/runs/2200/nodes/63/steps/130/log/?start=0).

```
--- FAIL: TestCephSmokeSuite (1465.75s)
    --- PASS: TestCephSmokeSuite/TestARookClusterInstallation_SmokeTest (0.03s)
    --- FAIL: TestCephSmokeSuite/TestBlockStorage_SmokeTest (945.79s)
        ceph_base_block_test.go:175: 
            	Error Trace:	ceph_base_block_test.go:175
            	            				ceph_base_block_test.go:86
            	            				ceph_smoke_test.go:111
            	Error:      	Should be true
            	Test:       	TestCephSmokeSuite/TestBlockStorage_SmokeTest
            	Messages:   	make sure block-test pod is in running state
```

**Expected behavior:**
Master builds should be green

**How to reproduce it (minimal and precise):**

Run the master build

**Comment by Madhu-1** [comment]
The rbd map might be failing due to multus integration?

**Comment by rohan47** [comment]
> The rbd map might be failing due to multus integration?

The CI is not testing with multus. So the multus code will not be triggered

**Comment by Madhu-1** [comment]
daemonset  template from  CI tests

```yaml
kubectl get ds -nsmoke-ns-system csi-rbdplugin -oyaml |grep host
            f:hostPID: {}
              k:{"name":"host-dev"}:
                f:hostPath:
              k:{"name":"host-run-mount"}:
                f:hostPath:
              k:{"name":"host-sys"}:
                f:hostPath:
                f:hostPath:
                f:hostPath:
                f:hostPath:
                f:hostPath:
                f:hostPath:
          name: host-dev
          name: host-sys
          name: host-run-mount
      hostPID: true
      - hostPath:
      - hostPath:
      - hostPath:
      - hostPath:
      - hostPath:
        name: host-dev
      - hostPath:
        name: host-sys
      - hostPath:
      - hostPath:
        name: host-run-mount
```
Daemonset template from 1.4.0 deployment

```yaml
kuberc get ds csi-rbdplugin -oyaml |grep host
            f:hostNetwork: {}
            f:hostPID: {}
              k:{"name":"host-dev"}:
                f:hostPath:
              k:{"name":"host-run-mount"}:
                f:hostPath:
              k:{"name":"host-sys"}:
                f:hostPath:
                f:hostPath:
                f:hostPath:
                f:hostPath:
                f:hostPath:
                f:hostPath:
          name: host-dev
          name: host-sys
          name: host-run-mount
      hostNetwork: true
      hostPID: true
      - hostPath:
      - hostPath:
      - hostPath:
      - hostPath:
      - hostPath:
        name: host-dev
      - hostPath:
        name: host-sys
      - hostPath:
      - hostPath:
        name: host-run-mount
```

i don't see `hostNetwork: true` in daemonset template in CI.
