### ISSUE TITLE
Not able to upgrade from Rook 1.2 to 1.3

### ISSUE THREAD

**Issue by alexcpn** [rook/rook#6154]
Followed the procedure here https://rook.io/docs/rook/v1.3/ceph-upgrade.html

Cluster is partly updated from 1.25 to rook 1.3.9 Waited for 30 mts and restarted pods  to check. 

```
rook-ceph-crashcollector-green--2       req/upd/avl: 1/1/1      rook-version=v1.3.9
rook-ceph-crashcollector-green--3       req/upd/avl: 1/1/1      rook-version=v1.3.9
rook-ceph-crashcollector-green--4       req/upd/avl: 1/1/1      rook-version=v1.3.9
rook-ceph-crashcollector-green--5       req/upd/avl: 1/1/1      rook-version=v1.3.9
rook-ceph-mgr-a         req/upd/avl: 1/1/1      rook-version=v1.3.9
rook-ceph-mon-a         req/upd/avl: 1/1/1      rook-version=v1.3.9
rook-ceph-mon-b         req/upd/avl: 1/1/1      rook-version=v1.3.9
rook-ceph-mon-c         req/upd/avl: 1/1/1      rook-version=v1.3.9
rook-ceph-mon-e         req/upd/avl: 1/1/1      rook-version=v1.3.9
rook-ceph-mon-f         req/upd/avl: 1/1/1      rook-version=v1.3.9
rook-ceph-mon-g         req/upd/avl: 1/1/1      rook-version=v1.3.9
rook-ceph-osd-0         req/upd/avl: 1/1/1      rook-version=v1.2.5
rook-ceph-osd-1         req/upd/avl: 1/1/1      rook-version=v1.2.5
rook-ceph-osd-2         req/upd/avl: 1/1/1      rook-version=v1.2.5
rook-ceph-osd-3         req/upd/avl: 1/1/       rook-version=v1.2.5
rook-ceph-osd-4         req/upd/avl: 1/1/1      rook-version=v1.3.9
rook-ceph-osd-5         req/upd/avl: 1/1/1      rook-version=v1.2.5
rook-ceph-rgw-my-store-a        req/upd/avl: 1/1/1      rook-version=v1.3.9


```
Other than OSD logs showing this, Ceph toolbox was HEALTH_OK 

```
020-08-25 10:25:41.567 7fccd87a1a80 -1 Falling back to public interface
2020-08-25 10:25:43.044 7fccd87a1a80 -1 osd.2 168 log_to_monitors {default=true}
2020-08-25 10:25:43.077 7fcccad92700 -1 osd.2 168 set_numa_affinity unable to identify public interface 'eth0' numa node: (2) No such file or directory
````

```
[root@rook-ceph-tools-7d764c8647-slvfx /]# ceph osd status
+----+----------+-------+-------+--------+---------+--------+---------+----------------+
| id |   host   |  used | avail | wr ops | wr data | rd ops | rd data |     state      |
+----+----------+-------+-------+--------+---------+--------+---------+----------------+
| 0  | green--2 | 1616M | 47.4G |    0   |     0   |    0   |     0   |   exists,up    |
| 1  | green--2 | 2369M | 46.6G |    0   |     0   |    0   |     0   |   exists,up    |
| 2  | green--3 | 2714M | 46.3G |    0   |     0   |    0   |     0   |   exists,up    |
| 3  |          |    0  |    0  |    0   |     0   |    0   |     0   | autoout,exists |
| 4  | green--4 | 2396M | 46.6G |    0   |     0   |    1   |     0   |   exists,up    |
| 5  | green--5 | 2780M | 46.2G |    0   |     0   |    1   |     0   |   exists,up    |
+----+----------+-------+-------+--------+---------+--------+---------+----------------+
[root@rook-ceph-tools-7d764c8647-slvfx /]# ceph health
HEALTH_OK
```

**Comment by leseb** [comment]
Operator's log please.

**Comment by alexcpn** [comment]
[opertor.zip](https://github.com/rook/rook/files/5123594/opertor.zip)
Opertor logs

**Comment by travisn** [comment]
@alexcpn The operator log shows that the osd is not safe to stop, so the operator stops the upgrade.
```
failed to check if we can stop the deployment rook-ceph-osd-0: failed to check if rook-ceph-osd-0 was ok to stop: deployment rook-ceph-osd-0 cannot be stopped: exit status 16
```
which means the OSD is busy
```
16 | EBUSY | Device or resource busy
```
To continue the upgrade, I would recommend you set [continueUpgradeAfterChecksEvenIfNotHealthy: true](https://github.com/rook/rook/blob/release-1.4/cluster/examples/kubernetes/ceph/cluster.yaml#L40):

**Comment by alexcpn** [comment]
Thanks, did that and restarted deployment - still the same
```
kubectl -n rook-ceph edit CephCluster rook-ceph

#
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ceph.rook.io/v1","kind":"CephCluster","metadata":{"annotations":{},"name":"rook-ceph","namespace":"rook-ceph"},"spec":{"cephVersion":{"allowUnsupported":true,"image":"ceph/ceph:v14.2.7"},"continueUpgradeAfterChecksEvenIfNotHealthy":true,"crashCollector":{"disable":false},"dashboard":{"enabled":true,"ssl":true},"dataDirHostPath":"/var/lib/rook","mgr":{"modules":[{"enabled":true,"name":"pg_autoscaler"}]},"mon":{"allowMultiplePerNode":true,"count":6},"monitoring":{"enabled":false,"rulesNamespace":"rook-ceph"},"network":{"hostNetwork":false},"rbdMirroring":{"workers":0},"skipUpgradeChecks":false,"storage":{"config":{"databaseSizeMB":"1024","journalSizeMB":"1024","osdsPerDevice":"1"},"nodes":[{"devices":[{"name":"vdb"},{"name":"vdc"}],"name":"green--2"},{"devices":[{"name":"vdb"}],"name":"green--3"},{"devices":[{"name":"vdb"}],"name":"green--4"},{"devices":[{"name":"vdb"}],"name":"green--5"},{"devices":[{"name":"vdb"}],"name":"green--6"}],"useAllDevices":false,"useAllNodes":false}}}
  creationTimestamp: "2020-03-11T09:56:50Z"
```
  
  
kubectl -n rook-ceph  rollout restart deployment rook-ceph-operator
deployment.apps/rook-ceph-operator restarted


opertor  Logs 
[logsrookOperator.gz](https://github.com/rook/rook/files/5127812/logsrookOperator.gz)

seems error is same, even with the setting

 ```
2020-08-26 05:07:56.101501 I | util: retrying after 1m0s, last error: failed to check if we can stop the deployment rook-ceph-osd-0: failed to check if rook-ceph-osd-0 was ok to stop: deployment rook-ceph-osd-0 cannot be stopped: exit status 16
2020-08-26 05:08:04.919786 W | op-mon: skipping mon health check since cluster details are not initialized
...
2020-08-26 05:22:40.396456 I | op-mon: checking if we can stop the deployment rook-ceph-osd-5
2020-08-26 05:22:42.704830 I | util: retrying after 1m0s, last error: failed to check if we can stop the deployment rook-ceph-osd-5: failed to check if rook-ceph-osd-5 was ok to stop: deployment rook-ceph-osd-5 cannot be stopped: exit status 16
```
