### ISSUE TITLE
The Rook Operator fails to create an an Object Bucket from an Object Bucket Claim

### ISSUE THREAD

**Issue by kadomino** [rook/rook#6245]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The title says is all.
**Expected behavior:**
The OB should be created
**How to reproduce it (minimal and precise):**

* Create a self hosted (bootkube) K8S cluster with a non-default dnsDomain (different from "cluster.local").

* Install Rook 1.4.2, a Ceph cluster, pools, storage classes, S3 Store etc... Up to this point everything works fine - pools, cephfs, dashboard, etc... The storageClass for buckets is:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-buckets
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: s3store
  objectStoreNamespace: rook-ceph
```

* Apply an OBC like this:

```yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: zalando
  namespace: rook-ceph
spec:
  generateBucketName: zalando
  storageClassName: ceph-buckets
  additionalConfig:
    S3_PROVIDER: Ceph
    S3_ENDPOINT: http://rook-ceph-rgw-s3store.rook-ceph
```
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary

The Operator creates a Ceph User and tries to create the Object Bucket, which fails. Here is the relevant snippet:

```bash
2020-09-13 16:18:06.248862 E | op-bucket-prov: error creating bucket "zalando-2fed6b9d-18ca-464d-bc08-6d0c44030544": failed to create bucket "zalando-2fed6b9d-18ca-464d-bc08-6d0c44030544": RequestError: send request failed
caused by: Put http://rook-ceph-rgw-s3store.rook-ceph.svc.cluster.local:80/zalando-2fed6b9d-18ca-464d-bc08-6d0c44030544: dial tcp: lookup rook-ceph-rgw-s3store.rook-ceph.svc.cluster.local on 10.97.0.10:53: no such host
```

After the failure, the Operator (I suppose, correctly) deletes the Ceph User.

Obviously, the Operator fails because it uses "cluster.local" which is nowhere to be found on my cluster. The questions are:

* why does it force "......svc.cluster.local" instead of letting its pod's resolver do its thing?
* where does the string "cluster.local" come from, given that the cluster is configured with a different dnsDomain? I checked the correctness of the the resolv.conf files, of the coreDNS configuration and of the kubelet "--cluster_domain=" argument. Is there another place to check or is "cluster.local" hard-coded in the Operator?

* Crashing pod(s) logs, if necessary
NA
 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**: HA Kubernetes on premises with 3 masters and 8 workers
* OS (e.g. from /etc/os-release): The latest flatcar stable - 2512.4.0
* Kernel (e.g. `uname -a`): 4.19.143-flatcar
* Cloud provider or hardware configuration: 2 hypervisors with libvirt/KVM
* Rook version (use `rook version` inside of a Rook Pod): v1.4.2
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.4-20200819
* Kubernetes version (use `kubectl version`): v1.18.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): On premice, selfhosted (except ETCD), created with Terraform provider libvirt and bootkube.
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): Healthy
