### ISSUE TITLE
failed to configure Drive Group: failed ceph-volume call

### ISSUE THREAD

**Issue by stuartpb** [rook/rook#6323]
**Is this a bug report or feature request?**
* Bug Report

After resolving #6315, two of my nodes had their pod preparation perform smoothly: however, the third has had the preparation job consistently fail every time. [Here are the logs from the job's pod](https://gist.github.com/stuartpb/2fd851ba38fb664ac483377eac2be952) - it's not exactly clear where the errors start, but here are some parts that look symptomatic:

- `ceph-volume lvm batch: error: unrecognized arguments: --data`
- `[ceph_volume.process][INFO  ] stderr Failed to find physical volume "/dev/sda".`
- `[ceph_volume.process][INFO  ] stderr unable to read label for /dev/sda: (2) No such file or directory`

## Cluster YAML

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # see the "Cluster Settings" section below for more details on which image of ceph to run
    image: ceph/ceph:v15.2.5
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  monitoring:
    enabled: true
  mon:
    count: 3
    allowMultiplePerNode: true
  driveGroups:
  - name: storberry
    spec:
      data_devices:
        all: true
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: st8s.testtrack4.com/storage-group
              operator: In
              values:
              - storberry
```

## Environment

* OS (e.g. from /etc/os-release): OpenSUSE Kubic
* Kernel (e.g. `uname -a`): 5.8.7-1-default aarch64
* Cloud provider or hardware configuration: Bare metal heterogeneous cluster
* Rook version (use `rook version` inside of a Rook Pod): 1.4.3
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.5
* Kubernetes version (use `kubectl version`): 1.19.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm

## Possibly related issue

https://github.com/rook/rook/issues/5996#issuecomment-675342818 has the only other instance of "failed to find physical volume" in this repo's issues, though it's not clear if the two issues share any degree of common cause - unlike that issue, this is *not* an intermittent failure (the job consistently fails in the exact same fashion each time).
