### ISSUE TITLE
clusterrole "rook-ceph-system-psp-user" not found in v1.4.6

### ISSUE THREAD

**Issue by irizzant** [rook/rook#6448]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I cannot find clusterrole `rook-ceph-system-psp-user` in the [helm chart](https://github.com/rook/rook/tree/fc60241c880b7fa84d8170ca8d538a4bf57596d6/cluster/charts/rook-ceph/templates).

I see there is the [clusterrolebinding](https://github.com/rook/rook/blob/fc60241c880b7fa84d8170ca8d538a4bf57596d6/cluster/charts/rook-ceph/templates/clusterrolebinding.yaml#L3) but not the clusterrole.

**Expected behavior:**
`rook-ceph-system-psp-user` clusterrole should be in the helm chart.

**How to reproduce it (minimal and precise):**
1. `helm template rook-ceph --namespace rook-ceph --include-crds -f values.yaml rook-release/rook-ceph > output.yaml`

```yaml
image:
  prefix: rook
  repository: maven-repo.sdb.it:18080/rook/ceph
  tag: v1.4.6
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi
rbacEnable: true
pspEnable: true
csi:
  provisionerNodeAffinity: "role=storage-node"
agent:
  nodeAffinity: "role=storage-node"
discover:
  nodeAffinity: "role=storage-node"
```

1. look for clusterrole `rook-ceph-system-psp-user` 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18 LTS
* Kernel (e.g. `uname -a`): `Linux sdbit-k8s-worker3 4.15.0-121-generic #123-Ubuntu SMP Mon Oct 5 16:16:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: on-prem
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.4.6
go: go1.13.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubespray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by billimek** [comment]
Confirming the same here with rook 1.5.0.

We can clearly see the _reference_ to it in the ClusterRoleBinding [here](https://github.com/rook/rook/blob/release-1.5/cluster/charts/rook-ceph/templates/clusterrolebinding.yaml#L145-L148).  I'm more than happy to PR the addition to this to the `templates/clusterrole.yaml` in the chart, if that's the proper direction to take.

The temporarily remediation O use is to manually install the ClusterRole out-of-band from the helm chart:

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: 'rook-ceph-system-psp-user'
  labels:
    operator: rook
    storage-backend: ceph
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - 00-rook-ceph-operator
  verbs:
  - use
```

**Comment by irizzant** [comment]
@billimek If you have the PR ready I think it's a good idea to submit it
Thanks

**Comment by BlaineEXE** [comment]
From what I see, the PSP in the manifests doesn't match what's in the helm chart. There is no mention of `rook-ceph-system-psp-user` outside of the helm chart. I wonder if what really should happen is that we re-synchronize what is in the helm charts to match what is in the raw manifests. 🤷‍♀️

**Comment by irizzant** [comment]
activity!

**Comment by irizzant** [comment]
activity!

**Comment by BlaineEXE** [comment]
We have been synchronizing helm and crds since Rook v1.6. @irizzant are you still using v1.4? If so, what is preventing you from upgrading to v1.6?

**Comment by irizzant** [comment]
@BlaineEXE  I see, I had not received any updates about this. I've updated to the last version (1.7.1) and the `psp:rook` `ClusterRole` has been created.

Thank you

**Comment by imle** [comment]
This still seems to be a problem in 1.7.5

**Comment by irizzant** [comment]
@imle look for ClusterRole psp:rook
`kubectl get clusterrole psp:rook`

**Comment by imle** [comment]
So this resource exists in my cluster:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    chart: rook-ceph-v1.7.5
    helm.toolkit.fluxcd.io/name: rook-ceph
    helm.toolkit.fluxcd.io/namespace: rook-ceph
    operator: rook
    storage-backend: ceph
  name: rook-ceph-system-psp-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-system-psp-user.   # the missing ClusterRole
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph
```

Beyond that, the latest version of the chart (v1.7.5) includes a reference to the resource here:
`rook-ceph/templates/clusterrolebinding.yaml:164`

The error message I was seeing is no longer reproducible but the operator was producing logs saying it did not have the right privileges and that somehow the missing ClusterRole was the issue.

I am looking at the latest master branch and it looks like it was removed. But I have put up a PR (#8955) here to remove it from the 1.7 release branch. I am not sure what to tag it as since its a helm chart change.
