### ISSUE TITLE
Recreated CephFilesystem is inaccessible *even when preservePoolsOnDelete is set*

### ISSUE THREAD

**Issue by LalitMaganti** [rook/rook#6492]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When a CephFilesystem CRD is deleted and `preservePoolsOnDelete` is set, recreating the CRD with identical settings leads to a filesystem with no data on it.

**Expected behavior:**
Recreating the CRD should allow the data in the system to be accessible.

**How to reproduce it (minimal and precise):**

1. Create a CephCluster and CephFilesystem (metadata replicated with size 3, data pool erasure encoded with 2 data chunks and 1 coding chunks) *and preservePoolsOnDelete* set, 1 metadataServer). I am also using `hostNetwork: true` but I don't think that is relevant.
2. Mount the CephFilesystem somewhere and write some files to it. Since I'm using `hostNetwork, I'm mounting on my development machine directly.
3. Unmount the filesystem
4. Delete the CephFilesystem CRD
5. Recreate the CephFilesystem CRD
6. Mount the CephFilesystem
7. Notice that any files which were created appear to be gone. Checking the ceph stats using `rados df` suggests the data pool has not been touched - the metadata however has been changed in in some way to make the data inaccessible (the size goes down + the write ops go up according to rados df).

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.5
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    volumeClaimTemplate:
      spec:
        storageClassName: ssd-fs
        resources:
          requests:
            storage: 1Gi
  dashboard:
    enabled: true
    ssl: true
  network:
    hostNetwork: true
  monitoring:
    enabled: false
    rulesNamespace: rook-ceph
  storage:
    storageClassDeviceSets:
    - name: hdd-set
      count: 3
      portable: false
      volumeClaimTemplates:
      - spec:
          resources:
            requests:
              storage: 1Gi
          storageClassName: hdd
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
--
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: main-fs
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 2
  dataPools:
    - failureDomain: osd
      erasureCoded:
        dataChunks: 2
        codingChunks: 1
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
```

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Arch Linux
* Kernel (e.g. `uname -a`): 5.9.1-arch1-1
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod): v1.4.6
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"archive", BuildDate:"2020-10-16T20:58:56Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
