### ISSUE TITLE
Omission in documentation of Consume the Shared Filesystem: K8s Registry Sample leads to PVCs not provisioned

### ISSUE THREAD

**Issue by pascal71** [rook/rook#6513]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The file in cluster/examples/kubernetes/ceph/csi/cephfs/kube-registry.yaml that is referenced is correct. However the listed yaml file at the example Consume the Shared Filesystem: K8s Registry Sample is missing the namespace. Should be kube-system.

E.g.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
```

**Expected behavior:**

Should be:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
```

as the registry deployment will also be done in kube-system. People copy-n-pasting the example without further thinking will get unexpected behaviour, the PVC will not probe provisioned, the PODs will stay in pending state.,

**How to reproduce it (minimal and precise):**

Documentation issue; read the fine documents :)

I can submit a PR if you'd like.

Kind regards,

   Pascal van Dam
