### ISSUE TITLE
kubectl delete cephobjectstore.ceph.rook.io gets stuck forever

### ISSUE THREAD

**Issue by alexclear** [rook/rook#6528]
I created an instance of CephObjectStore using the following definition:
```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: test-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 2
  preservePoolsOnDelete: true
  gateway:
    type: s3
    sslCertificateRef:
    port: 80
    securePort:
    instances: 1
    annotations:
    placement:
    resources:
```
I am trying to delete it using the following command:
`kubectl delete cephobjectstore.ceph.rook.io test-store -n rook-ceph`
It gets stuck forever, nothing is deleted:
```
➜  ~ kubectl get cephobjectstore.ceph.rook.io -n rook-ceph
NAME         AGE
test-store   14d
➜  ~
```
