### ISSUE TITLE
How can I test whether Ceph NFS is working fine or not? 

### ISSUE THREAD

**Issue by Siddhu1096** [rook/rook#6636]
We are having an AKS cluster. I have configured Rook and enabled Ceph cluster. I am now working on integrating Ceph NFS to the AKS cluster. Currently, I ran filesystem.yaml and nfs.yaml from the https://rook.github.io/docs/rook/v1.4/ceph-quickstart.html#tldr  (latest stable release). 

This is the output of my current running pods
```
kubectl get pods -n rook-ceph
NAME                                                              READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-provisioner-56ffddfcb5-nc76t                     6/6     Running     0          22h
csi-cephfsplugin-provisioner-56ffddfcb5-z2mc2                     6/6     Running     0          22h
csi-cephfsplugin-tbhwp                                            3/3     Running     0          22h
csi-cephfsplugin-xq24q                                            3/3     Running     0          22h
csi-cephfsplugin-z9ntf                                            3/3     Running     0          22h
csi-cephfsplugin-zzdgj                                            3/3     Running     0          22h
csi-rbdplugin-26d4x                                               3/3     Running     0          22h
csi-rbdplugin-2fdvt                                               3/3     Running     0          22h
csi-rbdplugin-4fhmp                                               3/3     Running     0          22h
csi-rbdplugin-provisioner-7897f5855-n2bss                         6/6     Running     0          22h
csi-rbdplugin-provisioner-7897f5855-qf8n9                         6/6     Running     0          22h
csi-rbdplugin-xv55d                                               3/3     Running     0          22h
rook-ceph-crashcollector-aks-agentpool-25228689-vmss000001vw2gv   1/1     Running     0          51m
rook-ceph-crashcollector-aks-npstorage-25228689-vmss000000bkwz2   1/1     Running     0          22h
rook-ceph-crashcollector-aks-npstorage-25228689-vmss000001k4hnp   1/1     Running     0          22h
rook-ceph-crashcollector-aks-rstudiomed-25228689-vmss000006hnnq   1/1     Running     0          22h
rook-ceph-mds-myfs-a-6fdf94f4fd-txczm                             1/1     Running     0          24m
rook-ceph-mds-myfs-b-6d8d959d5d-d4t9l                             1/1     Running     0          24m
rook-ceph-mgr-a-5f97c8bd5d-s6sv7                                  1/1     Running     0          22h
rook-ceph-mon-a-67f9766db5-x4vm2                                  1/1     Running     0          22h
rook-ceph-mon-b-84dfdc5d6-nnf8n                                   1/1     Running     0          22h
rook-ceph-mon-c-69f4b6848c-tqfpw                                  1/1     Running     0          22h
rook-ceph-nfs-my-nfs-a-79fb86c7c5-pwlvn                           2/2     Running     0          21m
rook-ceph-nfs-my-nfs-b-6b97959b74-92xmt                           2/2     Running     0          21m
rook-ceph-nfs-my-nfs-c-5f9cf8dd9-nff6r                            2/2     Running     0          21m
rook-ceph-operator-db86df8cf-pff76                                1/1     Running     0          22h
rook-ceph-osd-0-5c97479b59-s5h2v                                  1/1     Running     0          22h
rook-ceph-osd-1-67cd98f965-zvt2b                                  1/1     Running     0          22h
rook-ceph-osd-2-79d6d8d784-brp6c                                  1/1     Running     0          22h
rook-ceph-osd-3-6dcf9d569-2hpx8                                   1/1     Running     0          22h
rook-ceph-osd-prepare-set1-data-0-mjjr4-b2tbt                     0/1     Completed   0          22h
rook-ceph-osd-prepare-set1-data-1-6dm7g-6srmm                     0/1     Completed   0          22h
rook-ceph-osd-prepare-set1-data-2-fbk5j-ldbkq                     0/1     Completed   0          22h
rook-ceph-osd-prepare-set1-data-3-vpppm-66q79                     0/1     Completed   0          22h
rook-ceph-tools-6b767c5566-6jzr9                                  1/1     Running     0          20h
rook-discover-6xnb5                                               1/1     Running     0          22h
rook-discover-7plc6                                               1/1     Running     0          22h
rook-discover-l6tn7                                               1/1     Running     0          22h
rook-discover-wrrrh                                               1/1     Running     0          22h
```
And these are the services running

```
kubectl get svc -n rook-ceph
NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
csi-cephfsplugin-metrics   ClusterIP   10.242.252.54    <none>        8080/TCP,8081/TCP   22h
csi-rbdplugin-metrics      ClusterIP   10.242.252.84    <none>        8080/TCP,8081/TCP   22h
rook-ceph-mgr              ClusterIP   10.242.252.41    <none>        9283/TCP            22h
rook-ceph-mgr-dashboard    ClusterIP   10.240.252.196   <none>        8443/TCP            22h
rook-ceph-mon-a            ClusterIP   10.242.256.142   <none>        6789/TCP,3300/TCP   22h
rook-ceph-mon-b            ClusterIP   10.242.251.243   <none>        6789/TCP,3300/TCP   22h
rook-ceph-mon-c            ClusterIP   10.242.259.195   <none>        6789/TCP,3300/TCP   22h
rook-ceph-nfs-my-nfs-a     ClusterIP   10.242.272.87    <none>        2049/TCP            22m
rook-ceph-nfs-my-nfs-b     ClusterIP   10.242.232.108   <none>        2049/TCP            22m
rook-ceph-nfs-my-nfs-c     ClusterIP   10.242.222.70    <none>        2049/TCP            22m
```
```
kubectl get cephnfs.ceph.rook.io -n rook-ceph
NAME     AGE
my-nfs   27m
 kubectl get cephfilesystem.ceph.rook.io -n rook-ceph
NAME   ACTIVEMDS   AGE
myfs   1           30m

```
How can I test whether NFS is working fine or not? Also, I am not able to view the NFS on the dashboard, but I can the filesystem there. 

Any help would be appreciated.

**Comment by Siddhu1096** [comment]
@travisn @Madhu-1 @andyzhangx Can anyone of you kindly take a look?

**Comment by andyzhangx** [comment]
I think you could follow this example, it's using in-tree `nfs` plugin:
https://matthiasomisore.com/linux/how-to-map-an-nfs-drive-as-persistent-volume-in-kubernetes/

There is also NFS CSI driver which could provide dynamic provisioning: https://github.com/kubernetes-csi/csi-driver-nfs, I am the maintainer of this project. Let me know if you want to try this driver.

**Comment by leseb** [comment]
Changed the title as it was misleading. There is nothing "not working" as far as I can tell.

**Comment by Siddhu1096** [comment]
@andyzhangx  We have already set up a ceph cluster and our requirement is to integrate NFS on top of this ceph cluster. 
For that, first I have created a file system.yaml file and nfs.yaml file. Here be attaching the code

**filesystem.yaml**
```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
  namespace: rook-ceph
spec:
  # The metadata pool spec. Must use replication.
  metadataPool:
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      # Inline compression mode for the data pool
      # Further reference: https://docs.ceph.com/docs/nautilus/rados/configuration/bluestore-config-ref/#inline-compression
      compression_mode: none
        # gives a hint (%) to Ceph in terms of expected consumption of the total cluster capacity of a given pool
      # for more info: https://docs.ceph.com/docs/master/rados/operations/placement-groups/#specifying-expected-pool-size
      #target_size_ratio: ".5"
  # The list of data pool specs. Can use replication or erasure coding.
  dataPools:
    - failureDomain: host
      replicated:
        size: 3
        # Disallow setting pool with replica 1, this could lead to data loss without recovery.
        # Make sure you're *ABSOLUTELY CERTAIN* that is what you want
        requireSafeReplicaSize: true
      parameters:
        # Inline compression mode for the data pool
        # Further reference: https://docs.ceph.com/docs/nautilus/rados/configuration/bluestore-config-ref/#inline-compression
        compression_mode: none
          # gives a hint (%) to Ceph in terms of expected consumption of the total cluster capacity of a given pool
        # for more info: https://docs.ceph.com/docs/master/rados/operations/placement-groups/#specifying-expected-pool-size
        #target_size_ratio: ".5"
  # Whether to preserve metadata and data pools on filesystem deletion
  preservePoolsOnDelete: true
  # The metadata service (mds) configuration
  metadataServer:
    # The number of active MDS instances
    activeCount: 1
    # Whether each active MDS instance will have an active standby with a warm metadata cache for faster failover.
    # If false, standbys will be available, but will not have a warm cache.
    activeStandby: true
    # The affinity rules to apply to the mds deployment
    placement:
    #  nodeAffinity:
    #    requiredDuringSchedulingIgnoredDuringExecution:
    #      nodeSelectorTerms:
    #      - matchExpressions:
    #        - key: role
    #          operator: In
    #          values:
    #          - mds-node
    #  topologySpreadConstraints:
    #  tolerations:
    #  - key: mds-node
    #    operator: Exists
    #  podAffinity:
       podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rook-ceph-mds
            # topologyKey: kubernetes.io/hostname will place MDS across different hosts
            topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-mds
              # topologyKey: */zone can be used to spread MDS across different AZ
              # Use <topologyKey: failure-domain.beta.kubernetes.io/zone> in k8s cluster if your cluster is v1.16 or lower
              # Use <topologyKey: topology.kubernetes.io/zone>  in k8s cluster is v1.17 or upper
              topologyKey: topology.kubernetes.io/zone
    # A key/value list of annotations
    annotations:
    #  key: value
    # A key/value list of labels
    labels:
    #  key: value
    resources:
    # The requests and limits set here, allow the filesystem MDS Pod(s) to use half of one CPU core and 1 gigabyte of memory
    #  limits:
    #    cpu: "500m"
    #    memory: "1024Mi"
    #  requests:
    #    cpu: "500m"
    #    memory: "1024Mi"
    # priorityClassName: my-priority-class

```

**nfs.yaml**
```
apiVersion: ceph.rook.io/v1
kind: CephNFS
metadata:
  name: my-nfs
  namespace: rook-ceph
spec:
  rados:
    # RADOS pool where NFS client recovery data is stored.
    # In this example the data pool for the "myfs" filesystem is used.
    # If using the object store example, the data pool would be "my-store.rgw.buckets.data".
    pool: myfs-data0
    # RADOS namespace where NFS client recovery data is stored in the pool.
    namespace: nfs-ns
  # Settings for the NFS server
  server:
    # the number of active NFS servers
    active: 3
    # where to run the NFS server
    placement:
    #  nodeAffinity:
    #    requiredDuringSchedulingIgnoredDuringExecution:
    #      nodeSelectorTerms:
    #      - matchExpressions:
    #        - key: role
    #          operator: In
    #          values:
    #          - mds-node
    #  topologySpreadConstraints:
    #  tolerations:
    #  - key: mds-node
    #    operator: Exists
    #  podAffinity:
    #  podAntiAffinity:
    # A key/value list of annotations
    annotations:
    #  key: value
    # The requests and limits set here allow the ganesha pod(s) to use half of one CPU core and 1 gigabyte of memory
    resources:
    #  limits:
    #    cpu: "500m"
    #    memory: "1024Mi"
    #  requests:
    #    cpu: "500m"
    #    memory: "1024Mi"
    # the priority class to set to influence the scheduler's pod preemption
    priorityClassName:

```
