### ISSUE TITLE
Prometheus monitoring is not working

### ISSUE THREAD

**Issue by c35sys** [rook/rook#6680]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When enabling monitoring during Ceph cluster creation, Prometheus can't scrap data.

**Expected behavior:**
Prometheus is collecting monitoring data.

**How to reproduce it (minimal and precise):**

* Deploy rook using helm
* Create a ceph cluster with monitoring entries below
* Prometheus was installed using kube-prometheus-stack helm

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
cluster.yaml excerpt
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  ...
  monitoring:
    # requires Prometheus to be pre-installed
    enabled: true
  ...
```

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04
* Kernel (e.g. `uname -a`): 5.4.0-26-generic
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.4.7
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.4
* Kubernetes version (use `kubectl version`): v1.19.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): rke
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTHY

**Comment by c35sys** [comment]
**How I resolved it temporarily**
Prometheus installed with kube-prometheus-stack search for the following label: **release: prometheus**.
The rook-ceph-operator contains the `/etc/ceph-monitoring/service-monitor.yaml` used to create the `rook-ceph-mgr` ServiceMonitor.

So I added the needed label:
```
  labels:
    team: rook
    release: prometheus
```
I deleted  the `rook-ceph-mgr` ServiceMonitor, then the operator recreated it with the good labels.

It seems the `service-monitor.yaml` is copied from examples to create the docker image, so it may be the solution to modify this file upstream.

**Comment by travisn** [comment]
@c35sys To get this to work, you're saying you had to add this label to the service-monitor.yaml [here](https://github.com/rook/rook/blob/release-1.5/cluster/examples/kubernetes/ceph/monitoring/service-monitor.yaml#L6)?
```yaml
release: prometheus
```

**Comment by c35sys** [comment]
@travisn yes exactly.

This file is copied here when building Docker image: https://github.com/rook/rook/blob/release-1.5/images/ceph/Makefile#L50

**Comment by travisn** [comment]
@c35sys Sounds good, where did you find this label requirement? I'm not seeing it in the prometheus docs, but certainly could be overlooking it.

**Comment by c35sys** [comment]
It sounds like I had the wrong approach.

My prometheus CRD was like:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
...
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
...
```
The chart applies a `matchLabel` with the helm release name as `serviceMonitorSelectorNilUsesHelmValues: true` which is set by default.

Ref:
- https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-11.1.1/charts/kube-prometheus-stack/values.yaml#L1794
- https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-11.1.1/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L104

So my problem came from the prometheus deployed configuration.

I update using helm the Prometheus deployment with new values in values.yaml`:
```
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
```
Then Prometheus doesn't have any selector for serviceMonitor.

So I close the bug report as it is Prometheus related.
