### ISSUE TITLE
InvalidAccessKeyId with Traefik ingress controller

### ISSUE THREAD

**Issue by mellotron** [rook/rook#673]
Hello,

I have Traefik running as an ingress controller in my kubernetes cluster - this is also tied to Let's Encrypt so I have a valid cert on the domain.

I set up the object store per the documentation and then set up an ingress for RGW with:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: rgw-ingress
 namespace: rook
spec:
 rules:
   - host: rgw.mycompany.com
     http:
       paths:
         - path: /
           backend:
             serviceName: rgw
             servicePort: 53390
```

I've also tried rgw-external for serviceName.

I use the values from and set:

```
export AWS_HOST=rgw.mycompany.com
export AWS_ENDPOINT=rgw.mycompany.com
export AWS_ACCESS_KEY_ID=long-string
export AWS_SECRET_ACCESS_KEY=even-longer-string
```

And then do:

```
$ s3cmd mb --host=rgw.mycompany.com s3://rookbucket
```

But this always returns:

```
ERROR: S3 error: 403 (InvalidAccessKeyId): The AWS Access Key Id you provided does not exist in our records.
```

Interestingly, I am able to use the object storage if I set the AWS_ENDPOINT to the NodePort the rgw-external service has however this doesn't come with TLS.
