### ISSUE TITLE
1.4->1.5 upgrade guide issues

### ISSUE THREAD

**Issue by dimm0** [rook/rook#6730]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
For older clusters the namespace renaming instructions in the yamls are missing.

Also it would be nice to have it scripted for the case of several clusters (rook-system operator namespace and rook-a, rook-b, rook-c ceph clusters namespaces)

**Comment by travisn** [comment]
It's been a few releases since we've included the variables `ROOK_NAMESPACE` and `ROOK_SYSTEM_NAMESPACE` in the upgrade yamls such [upgrade-from-v1.0-apply.yaml#](https://github.com/rook/rook/blob/release-1.1/cluster/examples/kubernetes/ceph/upgrade-from-v1.0-apply.yaml#L106). In the releases since then, the namespace-specific resources have been relatively simple. @dimm0 In the past few upgrades, have you just searched and replaced manually `namespace: rook-ceph` for your namespace(s)?

The approach of the 1.5 upgrades to apply all of common.yaml was a nice simplification, but it certainly only works for those clusters that are using the default rook-ceph namespace for both the operator and the cluster CR. The only way I see this working for clusters in the non-default namespace (and not using the helm chart) is to revert to our previous pattern that provides the changed resources in the `upgrade-from-v1.x-apply.yaml`.

**Comment by BlaineEXE** [comment]
If we want to have our cake and eat it too, we could still keep things in `crd.yaml` and identify `rook-ceph-system` resources with a special comment that comes after the `namespace`. We could have a `sed` line in the upgrade guide for such installs.

**Comment by dimm0** [comment]
> @dimm0 In the past few upgrades, have you just searched and replaced manually `namespace: rook-ceph` for your namespace(s)?

Hmm, in the last one I though there was only the system upgrades... I didn't see anything related to the cluster-local one. If there were ones, I guess I have extra unused service accounts in rook-system and old non-updated stuff in other namespaces.

**Comment by travisn** [comment]
Agreed, `crds.yaml` should be fine since the CRDs are cluster resources. For `common.yaml`, sounds great to find `sed` instructions to replace the namespaces for rook-ceph-system or the cluster namespace. We may just need some special comments/annotations similar to what we do for the OLM generation.

**Comment by BlaineEXE** [comment]
Oops. Yeah, I forgot crds are cluster-scoped. But yes, I think we can identify whether something is a Rook system namespace by comment still in our manifests. I think only `common.yaml` and `operator.yaml` resources would apply. I can take this up tomorrow.

**Comment by BlaineEXE** [comment]
@dimm0 are you able to take a look at #6809 and see if the updates meet your needs?

**Comment by dimm0** [comment]
Looks good on the first glance. The only question is how to create configs for multiple ceph clusters, is that covered?

**Comment by BlaineEXE** [comment]
I added the following:

> These methods should work for any number of Rook-Ceph clusters and Rook Operators as long as you
parameterize the environment correctly. Merely repeat these steps for each Rook-Ceph cluster
(`ROOK_CLUSTER_NAMESPACE`), and be sure to update the `ROOK_OPERATOR_NAMESPACE` parameter each time
if applicable.

**Comment by dimm0** [comment]
Ok that works!

**Comment by dimm0** [comment]
> I added the following just now:
> 
> > These methods should work for any number of Rook-Ceph clusters and Rook Operators as long as you
> > parameterize the environment correctly. Merely repeat these steps for each Rook-Ceph cluster
> > (`ROOK_CLUSTER_NAMESPACE`), and be sure to update the `ROOK_OPERATOR_NAMESPACE` parameter each time
> > if applicable.

I'm going to update, and seems like this statement is not true.

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-mgr-system
  namespace: rook-system  # namespace:operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-mgr-system
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook # namespace:cluster
```

This rolebinding will be wiped if I iterate over several clusters.

Should I manually copy and verify all 30+ definitions over my 5 ceph cluster? No clean way to upgrade?

**Comment by dimm0** [comment]
BTW why isn't operator managing roles and CRDs?

**Comment by travisn** [comment]
Right, with multiple clusters managed by a single operator you would need a unique name on the resources in the operator namespace or else they would be overwritten. @BlaineEXE wdyt? Shall we add another replacement term such as this on the `name` of the applicable resources? Then a script could add a suffix to the name.
```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-mgr-system # namespace:cluster-suffix
  namespace: rook-system  # namespace:operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-mgr-system
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook # namespace:cluster
```

> BTW why isn't operator managing roles and CRDs?

In the early days of Rook the operator actually had full cluster privileges and we didn't have the separate RBAC, but we made the change fairly soon after the project was created. For security best practices the operator should only be given the privileges it needs. The answer is basically that Helm manages the RBAC during upgrades, but for clusters deployed without Helm that doesn't help. Today, neither does the helm chart handle installing the RBAC to multiple namespaces.

**Comment by dimm0** [comment]
I'd prefer having 

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-mgr-system # namespace:cluster-suffix
  namespace: rook-system  # namespace:operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-mgr-system
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook1 # namespace:cluster
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook2 # namespace:cluster
```

rather than several bindings

Are those managed manually in the repo or there's some template now, like jsonnet or kustomize?
