### ISSUE TITLE
Fall back to apply OSD resources for device sets to the .spec.resources.osd.requests

### ISSUE THREAD

**Issue by llamerada-jp** [rook/rook#6789]
**Is this a bug report or feature request?**

* Bug Report

**Deviation from expected behavior:**

* To apply the resources parameter for the OSD pod, we set `.spec.resources.osd` in cluster.yaml like below, but the resources did not reflect the value.

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: ceph-ssd
  namespace: ceph-ssd
spec:
  dataDirHostPath: /var/lib/rook
  resources:
...
    osd:
      requests:
        cpu: "500m"
        memory: "2Gi"
...
```

Also, we have confirmed that setting `.spec.storage.storageClassDeviceSets.[].resources` will reflect the resources parameter for the OSD pod.

**Expected behavior:**

* We expect the resources parameter for the OSD pod to be set as described in the documentation below.

https://rook.io/docs/rook/v1.5/ceph-cluster-crd.html#cluster-wide-resources-configuration-settings

**How to reproduce it (minimal and precise):**

Created a cluster using the [`cluster.yaml`](https://github.com/rook/rook/files/5657709/cluster.txt) file attached to this issue.

The following command was used to verify the OSD pod configuration.

```
kubectl get pod -n ceph-ssd <osd pod name> -o yaml
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS: Flatcar Container Linux 2605.8.0
* Kernel: Linux rack0-cs4 5.4.77-flatcar #1 SMP Wed Nov 18 17:29:43 -00 2020 x86_64 Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz GenuineIntel GNU/Linux
* Cloud provider or hardware configuration: baremetal
* Rook version: v1.4.0-alpha.0.482.g26832970
* Storage backend version: ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)
* Kubernetes version: 1.18.9
* Kubernetes cluster type:  [CKE](https://github.com/cybozu-go/cke)
* Storage backend status:
  ```
  $ kubectl exec -it -n ceph-ssd rook-ceph-tools-6cdbf6b4b5-trc72 -- ceph status
  cluster:
    id:     af6c99fc-b835-4bac-856b-b17045a3e622
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 28m)
    mgr: a(active, since 28m)
    osd: 3 osds: 3 up (since 27m), 3 in (since 27m)

  data:
    pools:   1 pools, 1 pgs
    objects: 0 objects, 0 B
    usage:   3.0 GiB used, 12 GiB / 15 GiB avail
    pgs:     1 active+clean
  ```

**Comment by travisn** [comment]
@llamerada-jp Agreed, this has been confusing for storageClassDeviceSets to not pick up the resources from the same place as other daemons. This was done so that device sets could be created with OSDs of different sizes or resource constraints if desired. How about the following for applying device set resources...
- If `.spec.storage.storageClassDeviceSets.[].resources` is set, apply it
- Else if `.spec.resources.osd` is set, apply it

**Comment by llamerada-jp** [comment]
Hi @travisn ,
I think the behavior I'm expecting is just as you commented. I'd like to check, but I don't think the `.spec.resources.osd` field is reflected in the OSD at the moment, is that correct?

**Comment by travisn** [comment]
Correct, there is no fallback behavior to pick up `.spec.resources.osd` currently

**Comment by subhamkrai** [comment]
can I take this up?

**Comment by saranicole** [comment]
This issue appears to apply to tolerations as well in that `placement: all:` tolerations do not apply to OSDs, resulting in the OSDs needing tolerations added separately.

A workaround for this is to add tolerations in both places, like so
```
  storage:
   storageClassDeviceSets:
    - name: set1
      count: 3
      placement:
        podAntiAffinity:
        topologySpreadConstraints:
        tolerations:
          - key: "name"
            operator: "Equal"
            effect: "NoExecute"
            value: "rook-pool-taint"
          - key: "name"
            operator: "Equal"
            effect: "NoSchedule"
            value: "rook-pool-taint"
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 10Gi
          # IMPORTANT: Change the storage class depending on your environment (e.g. local-storage, gp2)
#          storageClassName: local-storage
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
      resources:
        # These are the OSD daemon limits. For OSD prepare limits, see the separate section below for "prepareosd" resources
        limits:
          cpu: "500m"
          memory: "4Gi"
        requests:
          cpu: "500m"
          memory: "4Gi"
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - rook-pool
      podAffinity:
      podAntiAffinity:
      topologySpreadConstraints:
      tolerations:
        - key: "name"
          operator: "Equal"
          effect: "NoExecute"
          value: "rook-pool-taint"
        - key: "name"
          operator: "Equal"
          effect: "NoSchedule"
          value: "rook-pool-taint"
```

The desired behavior is that tolerations added under `placement: all:` should apply to all pods including OSDs.
