### ISSUE TITLE
Host based OSDs and PVC based OSDs in the same ceph cluster does not work

### ISSUE THREAD

**Issue by paalkr** [rook/rook#6836]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rook does not create OSDs for host devices if the cluster spec contains both host based devices and PVC based devices

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.7
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  storage:
    useAllNodes: true
    useAllDevices: true
   storageClassDeviceSets:
    - name: set1
      count: 3
      portable: true
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 305Gi
          storageClassName: ebs-gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
```

**Expected behavior:**

I would expect rook to provision host based OSDs in addition to the PVC-based, which are created and added to the cluster as expected.

In a three node k8s cluster with nodes having local ephemeral volumes (like EC2 ephemeral volumes), the above config should create 6 OSDs, but only the 3 PVC based OSDs are created.

The rook-discover daemon does detect the ephemeral volume (in addition to the EBS PVC that are created by the `storageClassDeviceSets`).

```
[
    {Name:nvme1n1 Parent: HasChildren: false DevLinks:/dev/disk/by-id/nvme-nvme.1d0f-4157534233303033463031303644423832354536-416d617a6f6e20454332204e564d6520496e7374616e63652053746f72616765-00000001 /dev/disk/by-id/nvme-Amazon_EC2_NVMe_Instance_Storage_AWSB3003F0106DB825E6 /dev/disk/by-path/pci-0000: 00: 1f.0-nvme-1 Size: 2500000000000 UUID:c0c5f1ef-947e-42e0-8982-4a11da70c043 Serial:Amazon EC2 NVMe Instance Storage_AWSB3003F0106DB825E6 Type:disk Rotational: false Readonly: false Partitions: [] Filesystem: Vendor: Model:Amazon EC2 NVMe Instance Storage WWN:nvme.1d0f-4157534233303033463031303644423832354536-416d617a6f6e20454332204e564d6520496e7374616e63652053746f72616765-00000001 WWNVendorExtension: Empty: true CephVolumeData: {
            "path": "/dev/nvme1n1",
            "available": true,
            "rejected_reasons": [],
            "sys_api": {
                "removable": "0",
                "ro": "0",
                "vendor": "",
                "model": "Amazon EC2 NVMe Instance Storage",
                "rev": "",
                "sas_address": "",
                "sas_device_handle": "",
                "support_discard": "512",
                "rotational": "0",
                "nr_requests": "127",
                "scheduler_mode": "none",
                "partitions": {},
                "sectors": 0,
                "sectorsize": "512",
                "size": 2500000000000.0,
                "human_readable_size": "2.27 TB",
                "path": "/dev/nvme1n1",
                "locked": 0
            },
            "lvs": []
        } RealPath:/dev/nvme1n1 KernelName:nvme1n1 Encrypted: false
    } {Name:nvme2n1 Parent: HasChildren: false DevLinks:/dev/disk/by-path/pci-0000: 00:1e.0-nvme-1 /dev/disk/by-id/nvme-nvme.1d0f-766f6c3034613438336236393965616437643963-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001 /dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol04a483b699ead7d9c Size: 327491256320 UUID:d93f5ffe-542e-4ba6-8f2a-960b8a94673b Serial:Amazon Elastic Block Store_vol04a483b699ead7d9c Type:disk Rotational: false Readonly: false Partitions: [] Filesystem:ceph_bluestore Vendor: Model:Amazon Elastic Block Store WWN:nvme.1d0f-766f6c3034613438336236393965616437643963-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001 WWNVendorExtension: Empty: false CephVolumeData: {
            "path": "/dev/nvme2n1",
            "available": false,
            "rejected_reasons": [
                "Has BlueStore device label"
            ],
            "sys_api": {
                "removable": "0",
                "ro": "0",
                "vendor": "",
                "model": "Amazon Elastic Block Store",
                "rev": "",
                "sas_address": "",
                "sas_device_handle": "",
                "support_discard": "0",
                "rotational": "0",
                "nr_requests": "31",
                "scheduler_mode": "none",
                "partitions": {},
                "sectors": 0,
                "sectorsize": "512",
                "size": 327491256320.0,
                "human_readable_size": "305.00 GB",
                "path": "/dev/nvme2n1",
                "locked": 0
            },
            "lvs": []
        } RealPath:/dev/nvme2n1 KernelName:nvme2n1 Encrypted: false
    }
]
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS
* Kernel (e.g. `uname -a`): 5.4.0-1009-aws
* Cloud provider or hardware configuration: storage nodes i3en.xlarge (with 2,3TB of ephemeral instance storage)
* Rook version (use `rook version` inside of a Rook Pod): 1.4.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph v15.2.4
* Kubernetes version (use `kubectl version`): 1.17.13
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kops on AWS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
[root@rook-ceph-tools-65bb4db9df-4f9vt /]# ceph status
  cluster:
    id:     74cbfd02-44f9-4843-bcde-cc7f5ce858a2
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum j,t,v (age 12h)
    mgr: a(active, since 16m)
    osd: 3 osds: 3 up (since 37m), 3 in (since 21h)

  data:
    pools:   4 pools, 97 pgs
    objects: 3.79k objects, 14 GiB
    usage:   24 GiB used, 891 GiB / 915 GiB avail
    pgs:     97 active+clean

  io:
    client:   19 KiB/s wr, 0 op/s rd, 1 op/s wr
```
