### ISSUE TITLE
I cannot be configured with logicalDevices.

### ISSUE THREAD

**Issue by ycy1766** [rook/rook#6876]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
* I used logicalDevices to designate wal,db created in advance, but it is not applied.

**Expected behavior:**
* Ceph cluster is composed of previously created wal,db devices

**How to reproduce it (minimal and precise):**

* kubectl create -f crds.yaml -f common.yaml
* kubectl create -f operator.yaml
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
 ```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: true
  monitoring:
    enabled: true
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: false
  dashboard:
    enabled: true
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      storeType: bluestore
    nodes:
    - name: cy09-ceph001
      logicalDevices:
      - db: ceph_ssd_db_lv_1
        wal: ceph_ssd_wal_lv_1
        data: ceph_sas_data_lv_1
        dbVolumeGroup: ceph_ssd_db_vg_1
        walVolumeGroup: ceph_ssd_wal_vg_1
        dataVolumeGroup: ceph_sas_data_vg_1 
    - name: cy09-ceph002
      logicalDevices:
      - db: ceph_ssd_db_lv_1
        wal: ceph_ssd_wal_lv_1
        data: ceph_sas_data_lv_1
        dbVolumeGroup: ceph_ssd_db_vg_1
        walVolumeGroup: ceph_ssd_wal_vg_1
        dataVolumeGroup: ceph_sas_data_vg_1 
    - name: cy09-ceph003
      logicalDevices:
      - db: ceph_ssd_db_lv_1
        wal: ceph_ssd_wal_lv_1
        data: ceph_sas_data_lv_1
        dbVolumeGroup: ceph_ssd_db_vg_1
        walVolumeGroup: ceph_ssd_wal_vg_1
        dataVolumeGroup: ceph_sas_data_vg_1                         

```

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
* Crashing pod(s) logs, if necessary
* kubectl  get pod -n rook-ceph
```
NAME                                                     READY   STATUS      RESTARTS   AGE
csi-rbdplugin-cklrr                                      3/3     Running     0          28m
csi-rbdplugin-dzpwh                                      3/3     Running     0          28m
csi-rbdplugin-f4sd2                                      3/3     Running     0          28m
csi-rbdplugin-gpwp6                                      3/3     Running     0          28m
csi-rbdplugin-pfq9z                                      3/3     Running     0          28m
csi-rbdplugin-provisioner-54d48757b4-59pr6               6/6     Running     0          28m
csi-rbdplugin-provisioner-54d48757b4-c7tw8               6/6     Running     0          28m
csi-rbdplugin-qd4cl                                      3/3     Running     0          28m
rook-ceph-crashcollector-cy09-ceph001-5f657bdbd5-5sgr8   1/1     Running     0          28m
rook-ceph-crashcollector-cy09-ceph002-7957454ff6-sf55x   1/1     Running     0          27m
rook-ceph-crashcollector-cy09-ceph003-7d76b88dd7-mfzlf   1/1     Running     0          27m
rook-ceph-mgr-a-858b587658-h2j84                         1/1     Running     0          27m
rook-ceph-mon-a-9797d78f8-bclp8                          1/1     Running     0          28m
rook-ceph-mon-b-56bc77444d-9xnsp                         1/1     Running     0          27m
rook-ceph-mon-c-6865d96f7c-z279b                         1/1     Running     0          27m
rook-ceph-operator-88b89d9f4-rmdhl                       1/1     Running     0          29m
rook-ceph-osd-prepare-cy09-ceph001-29wvz                 0/1     Completed   0          27m
rook-ceph-osd-prepare-cy09-ceph002-xbhfb                 0/1     Completed   0          27m
rook-ceph-osd-prepare-cy09-ceph003-bkrxw                 0/1     Completed   0          27m

```
* kubectl  get  cephcluster rook-ceph -n rook-ceph -o yaml
```
...
  storage:
    config:
      storeType: bluestore
    nodes:
    - config: null
      name: cy09-ceph001
      resources: {}
    - config: null
      name: cy09-ceph002
      resources: {}
    - config: null
      name: cy09-ceph003
      resources: {}
...
```
 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):  CentOS Linux release 8.3.2011
* Kernel (e.g. `uname -a`): 4.18.0-240.1.1.el8_3.x86_64
* Cloud provider or hardware configuration: kvm
* Rook version (use `rook version` inside of a Rook Pod):  v1.5.4
* Storage backend version (e.g. for ceph do `ceph -v`): 
* Kubernetes version (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubespray 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
