### ISSUE TITLE
NFS pods crashed for fsec running in 1.5.4 and filesystem does work

### ISSUE THREAD

**Issue by rockkoca** [rook/rook#6895]
**Is this a bug report or feature request?**
* Bug Report
NFS pods crashed for filesystem-ec  after applying nfs-ec.yaml
rook-ceph-ec-block and rook-ceph-block are working well. But, I need to use readWriteMany. So, I wanted to set up a nfs server.
**Deviation from expected behavior:**
One NFS pod started but crashed. Nothing happened after applying filesystem.yaml
**Expected behavior:**
NFS pods running after applying nfs.yaml
filesystem running after applying filesystem.yaml

**How to reproduce it (minimal and precise):**

`kubectl apply -f filesystem.yaml 
`
`cephfilesystem.ceph.rook.io/myfs created`

But, no pods were launched... Then, I tried to use filesystem-ec.yaml.

```
kubectl apply -f filesystem-ec.yaml
kubectl apply -f nfs-ec.yaml
```
filesystem-ec pods launched. But, nfs pods crashed

**File(s) to submit**:
filesystem.yaml 
```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
  namespace: rook-ceph # namespace:cluster
spec:
  # The metadata pool spec. Must use replication.
  metadataPool:
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      compression_mode: none
  dataPools:
    - failureDomain: host
      replicated:
        size: 3
        requireSafeReplicaSize: true
      parameters:
        compression_mode: none
  preserveFilesystemOnDelete: true
  # The metadata service (mds) configuration
  metadataServer:
    # The number of active MDS instances
    activeCount: 1
    activeStandby: true
    placement:
       podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rook-ceph-mds
            topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-mds
              topologyKey: topology.kubernetes.io/zone
    # A key/value list of annotations
    annotations:
    #  key: value
    # A key/value list of labels
    labels:
    #  key: value
    resources:

```
filesystem-ec.yaml 
```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs-ec
  namespace: rook-ceph # namespace:cluster
spec:
  # The metadata pool spec
  metadataPool:
    replicated:
      # You need at least three OSDs on different nodes for this config to work
      size: 3
  # The list of data pool specs
  dataPools:
    # You need at least three `bluestore` OSDs on different nodes for this config to work
    - erasureCoded:
        dataChunks: 2
        codingChunks: 1
      # Inline compression mode for the data pool
      parameters:
        compression_mode: none
  # Whether to preserve filesystem after CephFilesystem CRD deletion
  preserveFilesystemOnDelete: true
  # The metadata service (mds) configuration
  metadataServer:
    # The number of active MDS instances
    activeCount: 1
    activeStandby: true
    placement:
       podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rook-ceph-mds
            # topologyKey: kubernetes.io/hostname will place MDS across different hosts
            topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rook-ceph-mds
                topologyKey: topology.kubernetes.io/zone
    # A key/value list of annotations
    annotations:
    labels:
    #  key: value
    resources:
```
nfs-ec.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephNFS
metadata:
  name: my-nfs
  namespace: rook-ceph # namespace:cluster
spec:
  rados:
    pool: myfs-ec-data0
    namespace: nfs-ns
  # Settings for the NFS server
  server:
    # the number of active NFS servers
    active: 3
    # where to run the NFS server
    placement:
    annotations:
    resources:
    logLevel: NIV_INFO

```
* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

```
kubectl -n rook-ceph get pod -o wide
NAME                                              READY   STATUS        RESTARTS   AGE   IP              NODE     NOMINATED NODE   READINESS GATES
csi-cephfsplugin-provisioner-8658f67749-hwm4c     6/6     Running       1          20h   10.1.35.67      node2   <none>           <none>
csi-cephfsplugin-provisioner-8658f67749-62r66     6/6     Running       0          20h   10.1.0.232      node3   <none>           <none>
rook-ceph-mon-a-5fd7bb9cb9-fw7zq                  1/1     Running       0          20h   10.1.35.106     node2   <none>           <none>
rook-ceph-tools-f579cb58c-mwhpg                   1/1     Running       0          20h   10.1.82.21      node    <none>           <none>
rook-ceph-mon-b-cd4df7956-sq27b                   1/1     Running       0          20h   10.1.0.234      node3   <none>           <none>
rook-ceph-mon-c-6bcdfb8595-9fjw8                  1/1     Running       0          20h   10.1.82.18      node    <none>           <none>
rook-ceph-crashcollector-node3-c785956c4-bhq6g   1/1     Running       0          20h   10.1.0.236      node3   <none>           <none>
rook-ceph-mgr-a-84b7ccc89f-7tpsm                  1/1     Running       0          20h   10.1.82.23      node    <none>           <none>
csi-cephfsplugin-lnvqx                            3/3     Running       0          12h   xxx.xxx.xx.122   node2   <none>           <none>
csi-cephfsplugin-xwmsh                            3/3     Running       0          12h   10.0.1.3        node3   <none>           <none>
csi-cephfsplugin-bq22x                            3/3     Running       0          12h   10.0.1.4        node    <none>           <none>
csi-rbdplugin-sxbkc                               3/3     Terminating   0          12h   xxx.xxx.xx.125   up2      <none>           <none>
csi-cephfsplugin-bcxc8                            3/3     Running       0          12h   xxx.xxx.xx.125   up2      <none>           <none>
csi-rbdplugin-7fk9r                               3/3     Running       0          11h   10.0.1.3        node3   <none>           <none>
csi-rbdplugin-9jbs4                               3/3     Running       0          11h   xxx.xxx.xx.122   node2   <none>           <none>
csi-rbdplugin-lc2gm                               3/3     Running       0          11h   10.0.1.4        node    <none>           <none>
csi-rbdplugin-provisioner-d8959bd7c-jmbw2         6/6     Running       0          11h   10.1.82.46      node    <none>           <none>
csi-rbdplugin-provisioner-d8959bd7c-vl77l         6/6     Running       0          11h   10.1.35.89      node2   <none>           <none>
rook-ceph-osd-0-5bbc597df4-s7fp2                  1/1     Running       0          10h   10.1.82.6       node    <none>           <none>
rook-ceph-osd-1-6854ff8c7f-l44n2                  1/1     Running       0          10h   10.1.0.217      node3   <none>           <none>
rook-ceph-osd-2-745c4b65b-vjpgx                   1/1     Running       0          10h   10.1.35.71      node2   <none>           <none>
rook-ceph-operator-69f6bc957f-zsp8h               1/1     Running       0          20h   10.1.82.14      node    <none>           <none>
rook-ceph-osd-prepare-node3-v7vww                0/1     Completed     0          21m   10.1.0.220      node3   <none>           <none>
rook-ceph-osd-prepare-node2-vhm6f                0/1     Completed     0          21m   10.1.35.84      node2   <none>           <none>
rook-ceph-osd-prepare-node-5lpl4                 0/1     Completed     0          21m   10.1.82.30      node    <none>           <none>
rook-ceph-mds-myfs-ec-a-7c669c6fc8-xdvdz          1/1     Running       0          30s   10.1.35.103     node2   <none>           <none>
rook-ceph-mds-myfs-ec-b-7d6c95dfbd-4sqrc          1/1     Running       0          29s   10.1.82.29      node    <none>           <none>
rook-ceph-crashcollector-node2-949ff488f-s4b6s   1/1     Running       0          29s   10.1.35.96      node2   <none>           <none>
rook-ceph-crashcollector-node-8596c6d74f-r7mgr   1/1     Running       0          28s   10.1.82.31      node    <none>           <none>
rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg           1/2     CrashLoopBackOff   1          14s    10.1.0.221      node3   <none>           <none>
```
I got the following logs from dashboard for pod rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg
```

02/01/2021 13:53:33 : epoch 5ff07add : rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg : nfs-ganesha-1[main] main :MAIN :EVENT :nfs-ganesha Starting: Ganesha Version 3.3
02/01/2021 13:53:33 : epoch 5ff07add : rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg : nfs-ganesha-1[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
02/01/2021 13:53:33 : epoch 5ff07add : rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg : nfs-ganesha-1[main] init_fds_limit :INODE LRU :INFO :Setting the system-imposed limit on FDs to 65536.
02/01/2021 13:53:33 : epoch 5ff07add : rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg : nfs-ganesha-1[main] init_server_pkgs :NFS STARTUP :INFO :State lock layer successfully initialized
02/01/2021 13:53:33 : epoch 5ff07add : rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg : nfs-ganesha-1[main] init_server_pkgs :NFS STARTUP :INFO :IP/name cache successfully initialized
02/01/2021 13:53:33 : epoch 5ff07add : rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg : nfs-ganesha-1[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
02/01/2021 13:53:33 : epoch 5ff07add : rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg : nfs-ganesha-1[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
02/01/2021 13:53:33 : epoch 5ff07add : rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg : nfs-ganesha-1[main] nfs4_recovery_init :CLIENT ID :INFO :Recovery Backend Init for rados_cluster
02/01/2021 13:53:33 : epoch 5ff07add : rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg : nfs-ganesha-1[main] rados_cluster_init :CLIENT ID :EVENT :Cluster membership check failed: -2
02/01/2021 13:53:33 : epoch 5ff07add : rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg : nfs-ganesha-1[main] main :NFS STARTUP :CRIT :Recovery backend initialization failed!
02/01/2021 13:53:33 : epoch 5ff07add : rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg : nfs-ganesha-1[main] main :NFS STARTUP :FATAL :Fatal errors.  Server exiting...
```
log with NIV_FULL_DEBUG
[ rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg.full.log](https://github.com/rook/rook/files/5760421/rook-ceph-nfs-my-nfs-a-6cd9fb49bd-8fllg.full.log)

ceph status
```
  cluster:
    id:     9e825ba1-99b9-4410-a7b9-d1b6395c85d9
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 20h)
    mgr: a(active, since 46m)
    mds: myfs-ec:1 {0=myfs-ec-a=up:active} 1 up:standby-replay
    osd: 3 osds: 3 up (since 10h), 3 in (since 10h)
 
  data:
    pools:   7 pools, 225 pgs
    objects: 32 objects, 3.3 KiB
    usage:   3.1 GiB used, 27 TiB / 27 TiB avail
    pgs:     225 active+clean
 
  io:
    client:   852 B/s rd, 1 op/s rd, 0 op/s wr
```
**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.1 LTS
* Kernel (e.g. `uname -a`): Linux k-nas 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: bare-metal
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.5.4
go: go1.13.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable)
* Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T11:09:22Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-37+7ab055a22f5440", GitCommit:"7ab055a22f5440dbdcd1d41095b7db95d98fc1c3", GitTreeState:"clean", BuildDate:"2020-12-10T18:59:05Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):bare-metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): ceph health
HEALTH_OK
