### ISSUE TITLE
root-ceph-operator  CrashLoopBackOff

### ISSUE THREAD

**Issue by billy98** [rook/rook#6897]
I deployed the Rook-Ceph version 1.5.4 and started the Operator using the following command。
```
kubectl apply -f common.yaml 
kubectl apply -f operator.yaml
```

```
[root@k8s-master-01 rook-ceph]# kubectl get pod -n rook-ceph
NAME                                  READY   STATUS             RESTARTS   AGE
rook-ceph-operator-656644b5d4-lbtpz   0/1     CrashLoopBackOff   7          19m
```

```
[root@k8s-master-01 rook-ceph]# kubectl describe pod -n rook-ceph
Name:         rook-ceph-operator-656644b5d4-lbtpz
Namespace:    rook-ceph
Priority:     0
Node:         k8s-node-01/192.168.8.114
Start Time:   Mon, 04 Jan 2021 18:27:38 +0800
Labels:       app=rook-ceph-operator
              pod-template-hash=656644b5d4
Annotations:  <none>
Status:       Running
IP:           10.244.1.55
IPs:
  IP:           10.244.1.55
Controlled By:  ReplicaSet/rook-ceph-operator-656644b5d4
Containers:
  rook-ceph-operator:
    Container ID:  docker://47e604d30da37cce905be2fc26bed17bcef91cdd8ccf725d2c0b540fbd2225bf
    Image:         rook/ceph:v1.5.4
    Image ID:      docker-pullable://rook/ceph@sha256:4262eec37095f0602cefe78f60898f60ef0d990bdc3f73c4705068a1b5019ad7
    Port:          <none>
    Host Port:     <none>
    Args:
      ceph
      operator
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   failed to run operator
: unable to run the controller-runtime manager: [no matches for kind "CephCluster" in version "ceph.rook.io/v1", failed waiting for all runnables to end within grace period of 30s: context deadline exceeded]
      Exit Code:    1
      Started:      Mon, 04 Jan 2021 18:42:22 +0800
      Finished:     Mon, 04 Jan 2021 18:42:55 +0800
    Ready:          False
    Restart Count:  7
    Environment:
      ROOK_CURRENT_NAMESPACE_ONLY:               false
      ROOK_ALLOW_MULTIPLE_FILESYSTEMS:           false
      ROOK_LOG_LEVEL:                            INFO
      ROOK_DISCOVER_DEVICES_INTERVAL:            60m
      ROOK_HOSTPATH_REQUIRES_PRIVILEGED:         false
      ROOK_ENABLE_SELINUX_RELABELING:            true
      ROOK_ENABLE_FSGROUP:                       true
      ROOK_DISABLE_DEVICE_HOTPLUG:               false
      DISCOVER_DAEMON_UDEV_BLACKLIST:            (?i)dm-[0-9]+,(?i)rbd[0-9]+,(?i)nbd[0-9]+
      ROOK_ENABLE_FLEX_DRIVER:                   false
      ROOK_ENABLE_DISCOVERY_DAEMON:              false
      ROOK_UNREACHABLE_NODE_TOLERATION_SECONDS:  5
      NODE_NAME:                                  (v1:spec.nodeName)
      POD_NAME:                                  rook-ceph-operator-656644b5d4-lbtpz (v1:metadata.name)
      POD_NAMESPACE:                             rook-ceph (v1:metadata.namespace)
    Mounts:
      /etc/ceph from default-config-dir (rw)
      /var/lib/rook from rook-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-system-token-cb855 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  rook-config:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-config-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  rook-ceph-system-token-cb855:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-system-token-cb855
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                             From               Message
  ----     ------     ----                            ----               -------
  Normal   Scheduled  19m                             default-scheduler  Successfully assigned rook-ceph/rook-ceph-operator-656644b5d4-lbtpz to k8s-node-01
  Normal   Pulled     <invalid> (x5 over <invalid>)   kubelet            Container image "rook/ceph:v1.5.4" already present on machine
  Normal   Created    <invalid> (x5 over <invalid>)   kubelet            Created container rook-ceph-operator
  Normal   Started    <invalid> (x5 over <invalid>)   kubelet            Started container rook-ceph-operator
  Warning  BackOff    <invalid> (x52 over <invalid>)  kubelet            Back-off restarting failed container
```

**Environment**:
* OS (e.g. from /etc/os-release):CentOS 7
* Kernel (e.g. `uname -a`):Linux k8s-master-01 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:4core 8G memory
* Rook version (use `rook version` inside of a Rook Pod):1.5.4
* Kubernetes version (use `kubectl version`):v1.18.14
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):kubeadm

**Comment by subhamkrai** [comment]
@billy98 please see this https://rook.io/docs/rook/v1.5/ceph-quickstart.html#deploy-the-rook-operator

`kubectl create -f crds.yaml -f common.yaml -f operator.yaml`

**Comment by billy98** [comment]
rook-ceph-osd-prepare CrashLoopBackOff
![image](https://user-images.githubusercontent.com/13307862/103632516-63e00a00-4f7f-11eb-9237-15e0c3082544.png)

cluster.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.8
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
    ssl: true
  monitoring:
    enabled: false
    rulesNamespace: rook-ceph
  network:
  crashCollector:
    disable: false
  cleanupPolicy:
    confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
    allowUninstallWithVolumes: false
  annotations:
  labels:
  resources:
  removeOSDsIfOutAndSafeToRemove: false
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter: sdb
    config:
    nodes:
    - name: "k8s-node-01"
      config:
        storeType: bluestore
       devices:
       - name: "sdb"
    - name: "k8s-node-02"
      config:
        storeType: bluestore
       devices:
       - name: "sdb"
    - name: "k8s-node-03"
      config:
        storeType: bluestore
       devices:
       - name: "sdb"
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api

  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
```

```
[root@k8s-master-01 new]# kubectl -n rook-ceph describe pod  rook-ceph-osd-prepare-k8s-node-02-lpf8b
Name:         rook-ceph-osd-prepare-k8s-node-02-lpf8b
Namespace:    rook-ceph
Priority:     0
Node:         k8s-node-02/192.168.8.115
Start Time:   Tue, 05 Jan 2021 17:52:33 +0800
Labels:       app=rook-ceph-osd-prepare
              ceph.rook.io/pvc=
              controller-uid=c466f69d-7cd7-462b-a0a0-7eb8ceafc95e
              job-name=rook-ceph-osd-prepare-k8s-node-02
              rook_cluster=rook-ceph
Annotations:  <none>
Status:       Running
IP:           10.244.2.43
IPs:
  IP:           10.244.2.43
Controlled By:  Job/rook-ceph-osd-prepare-k8s-node-02
Init Containers:
  copy-bins:
    Container ID:  docker://329c5a7027806b46efcb375825de2d7e9956d68543a8564e6d8f413f4bc3a804
    Image:         rook/ceph:v1.5.4
    Image ID:      docker-pullable://rook/ceph@sha256:4262eec37095f0602cefe78f60898f60ef0d990bdc3f73c4705068a1b5019ad7
    Port:          <none>
    Host Port:     <none>
    Args:
      copy-binaries
      --copy-to-dir
      /rook
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 05 Jan 2021 17:52:34 +0800
      Finished:     Tue, 05 Jan 2021 17:52:34 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /rook from rook-binaries (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-osd-token-6fcm6 (ro)
Containers:
  provision:
    Container ID:  docker://69d18f19bcdec8aacdab91db4d04475daac689c60aa1088af30eeae611aa2baa
    Image:         ceph/ceph:v15.2.8
    Image ID:      docker-pullable://ceph/ceph@sha256:37939a3739e4e037dcf1b1f5828058d721d8c6de958212609f9e7d920b9c62bf
    Port:          <none>
    Host Port:     <none>
    Command:
      /rook/tini
    Args:
      --
      /rook/rook
      ceph
      osd
      provision
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Message:      binary "lvm" does not exist on the host, make sure lvm2 package is installed: binary "lvm" does not exist on the host
      Exit Code:    1
      Started:      Tue, 05 Jan 2021 17:55:26 +0800
      Finished:     Tue, 05 Jan 2021 17:55:26 +0800
    Ready:          False
    Restart Count:  5
    Environment:
      ROOK_NODE_NAME:               k8s-node-02
      ROOK_CLUSTER_ID:              b611463a-6688-4962-a0b5-4b5bcb0f4385
      ROOK_PRIVATE_IP:               (v1:status.podIP)
      ROOK_PUBLIC_IP:                (v1:status.podIP)
      POD_NAMESPACE:                rook-ceph
      ROOK_MON_ENDPOINTS:           <set to the key 'data' of config map 'rook-ceph-mon-endpoints'>  Optional: false
      ROOK_MON_SECRET:              <set to the key 'mon-secret' in secret 'rook-ceph-mon'>          Optional: false
      ROOK_CEPH_USERNAME:           <set to the key 'ceph-username' in secret 'rook-ceph-mon'>       Optional: false
      ROOK_CEPH_SECRET:             <set to the key 'ceph-secret' in secret 'rook-ceph-mon'>         Optional: false
      ROOK_CONFIG_DIR:              /var/lib/rook
      ROOK_CEPH_CONFIG_OVERRIDE:    /etc/rook/config/override.conf
      ROOK_FSID:                    <set to the key 'fsid' in secret 'rook-ceph-mon'>  Optional: false
      NODE_NAME:                     (v1:spec.nodeName)
      ROOK_CRUSHMAP_ROOT:           default
      ROOK_CRUSHMAP_HOSTNAME:       k8s-node-02
      CEPH_VOLUME_DEBUG:            1
      CEPH_VOLUME_SKIP_RESTORECON:  1
      DM_DISABLE_UDEV:              1
      ROOK_OSDS_PER_DEVICE:         1
      ROOK_LOG_LEVEL:               DEBUG
      ROOK_DATA_DEVICE_FILTER:      sdb
      ROOK_CEPH_VERSION:            ceph version 15.2.8-0 octopus
      ROOK_OSD_CRUSH_DEVICE_CLASS:  
    Mounts:
      /dev from devices (rw)
      /etc/ceph from ceph-conf-emptydir (rw)
      /rook from rook-binaries (rw)
      /rootfs from rootfs (ro)
      /run/udev from udev (rw)
      /var/lib/ceph/crash from rook-ceph-crash (rw)
      /var/lib/rook from rook-data (rw)
      /var/log/ceph from rook-ceph-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-osd-token-6fcm6 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  rook-data:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook
    HostPathType:  
  ceph-conf-emptydir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  rook-ceph-log:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook/rook-ceph/log
    HostPathType:  
  rook-ceph-crash:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook/rook-ceph/crash
    HostPathType:  
  rook-binaries:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  devices:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  
  udev:
    Type:          HostPath (bare host directory volume)
    Path:          /run/udev
    HostPathType:  
  rootfs:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:  
  rook-ceph-osd-token-6fcm6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-osd-token-6fcm6
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/hostname=k8s-node-02
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                            From               Message
  ----     ------     ----                           ----               -------
  Normal   Scheduled  3m23s                          default-scheduler  Successfully assigned rook-ceph/rook-ceph-osd-prepare-k8s-node-02-lpf8b to k8s-node-02
  Normal   Pulled     <invalid>                      kubelet            Container image "rook/ceph:v1.5.4" already present on machine
  Normal   Created    <invalid>                      kubelet            Created container copy-bins
  Normal   Started    <invalid>                      kubelet            Started container copy-bins
  Warning  BackOff    <invalid> (x7 over <invalid>)  kubelet            Back-off restarting failed container
  Normal   Pulled     <invalid> (x5 over <invalid>)  kubelet            Container image "ceph/ceph:v15.2.8" already present on machine
  Normal   Created    <invalid> (x5 over <invalid>)  kubelet            Created container provision
  Normal   Started    <invalid> (x5 over <invalid>)  kubelet            Started container provision
```
