### ISSUE TITLE
Allow configuring multiple MGRs

### ISSUE THREAD

**Issue by jshen28** [rook/rook#6955]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Allow user configuring multiple ceph managers.

**What is use case behind this feature:**

The use case is simple, users could be allowed to configure multiple ceph
managers as they want.

**Environment**:

**Comment by jshen28** [comment]
Sorry for bringing this up again, and I hope I am aware and understand the discussion of #1796. And I think we actually do not need to worry about k8s service's load balancing. I think we could configure prometheus to collect metrics from each of ceph managers and since only one of them return metrics, the other two are actually idle and I think it is fine.

**Comment by jshen28** [comment]
For example, prometheus could be configured like follows,

```yaml
    - job_name: 'ceph-mgr'
      kubernetes_sd_configs:
      - role: endpoints # <---- instead of pulling from service, use endpoints
        namespaces:
          names:
          - rook-ceph
      relabel_configs:
      - action: keep
        source_labels:
        - __meta_kubernetes_service_name
        regex: telegraf
      - action: keep
        source_labels:
        - __meta_kubernetes_endpoint_port_name
        regex: http-metrics
```
