### ISSUE TITLE
Rancher CephCluster state shows error while ready

### ISSUE THREAD

**Issue by electrical** [rook/rook#6977]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rancher CephCluster resource details show confusing status.
The cluster is up and running fine and there are no errors further, but the 'error' state can be very confusing.

Screenshot: 

![Screenshot 2021-01-14 at 19 16 28](https://user-images.githubusercontent.com/271677/104638980-c7181d80-569e-11eb-962f-4898b7464767.png)

**Environment**:

* Rook version (use `rook version` inside of a Rook Pod): 1.5.5

**Comment by travisn** [comment]
From the [slack discussion](https://rook-io.slack.com/archives/CK9CF5H2R/p1610650897015100), it seems the problem is that the `ProgressingCompleted` condition is set to `false` instead of `true`.
```
 - lastHeartbeatTime: "2021-01-14T18:47:11Z"
    lastTransitionTime: "2021-01-14T18:45:43Z"
    message: Cluster progression is completed
    reason: ProgressingCompleted
    status: "False"
 ```

**Comment by electrical** [comment]
Here is the full yaml output of the CephCluster resource https://gist.github.com/electrical/4276dd79df2886d2e84229739c9e6e85

**Comment by travisn** [comment]
I believe this is fixed by #7059 in the v1.5.6 rook release last week. @electrical Do you see it is fixed now after upgrading?

**Comment by electrical** [comment]
I'll verify as soon as possible. Thanks!

**Comment by electrical** [comment]
@travisn I've done a fresh deployment on a new cluster and it's not fixed.

Output of the cephClusters resource: https://gist.github.com/electrical/c2f489f8f96da6adb562930bc1eb5be7

**Comment by travisn** [comment]
The "Ready" action is "true" since the cluster is done being configured and the "Progressing" action is "false" because it has completed. Is Rancher expecting "Progressing" to be "True"? That doesn't seem right either.
```
  - lastHeartbeatTime: "2021-02-03T19:49:07Z"
    lastTransitionTime: "2021-02-03T19:44:58Z"
    message: Cluster progression is completed
    reason: ProgressingCompleted
    status: "False"
    type: Progressing
  - lastHeartbeatTime: "2021-02-03T19:49:06Z"
    lastTransitionTime: "2021-02-03T19:49:06Z"
    message: Cluster created successfully
    reason: ClusterCreated
    status: "True"
    type: Ready
```

**Comment by electrical** [comment]
I think it's related to the `lastHeartbeatTime ` from what can see ?

**Comment by electrical** [comment]
As an example, this is from the remote cluster connecting to the ceph cluster:
In this case the`lastHeartbeatTime` for the connected status is after the connecting status.

```
  conditions:
  - lastHeartbeatTime: "2021-02-03T23:03:35Z"
    lastTransitionTime: "2021-02-03T23:03:35Z"
    message: Cluster is connecting
    reason: ClusterConnecting
    status: "True"
    type: Connecting
  - lastHeartbeatTime: "2021-02-03T23:03:45Z"
    lastTransitionTime: "2021-02-03T23:03:45Z"
    message: Cluster connected successfully
    reason: ClusterConnected
    status: "True"
    type: Connected
```
