### ISSUE TITLE
Overriding ceph cluster livenessProbe should not require all fields

### ISSUE THREAD

**Issue by viceice** [rook/rook#6980]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rook operator ignores `livenessProbe` cluster settings.

```yml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
...
  healthCheck:
    livenessProbe:
      mon:
        timeoutSeconds: 5
        failureThreshold: 5
      mgr:
        timeoutSeconds: 5
        failureThreshold: 5
      osd:
        timeoutSeconds: 5
        failureThreshold: 5
```

```
2021-01-14 20:34:33.331006 I | ceph-cluster-controller: CR has changed for "rook-ceph". diff=  v1.ClusterSpec{
  	... // 19 identical fields
  	RemoveOSDsIfOutAndSafeToRemove: false,
  	CleanupPolicy:                  {},
  	HealthCheck: v1.CephClusterHealthCheckSpec{
  		DaemonHealth:  {Status: {Interval: "60s"}, Monitor: {Interval: "45s"}, ObjectStorageDaemon: {Interval: "60s"}},
- 		LivenessProbe: nil,
+ 		LivenessProbe: map[v1.KeyType]*v1.ProbeSpec{"mgr": &{}, "mon": &{}, "osd": &{}},
  	},
  	Security:     {},
  	LogCollector: {},
  }
```

**Expected behavior:**
I expect that the cepth cluster is respecting my `livenessProbe` overrides and propagate them to the pods..

**How to reproduce it (minimal and precise):**

Simply add the cluster `healthCheck` settings above. Rook is deployed by official helm chart.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.1 LTS
* Kernel (e.g. `uname -a`): 5.4.0-1036-azure
* Cloud provider or hardware configuration: Hyper-V gen 2 vm
* Rook version (use `rook version` inside of a Rook Pod): v1.5.4 and v1.5.5
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.8
* Kubernetes version (use `kubectl version`): v1.20.0+k3s2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s (1 master + 3 worker)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_WARN:2 daemons have recently crashed

**Comment by viceice** [comment]
OK, looks like it not supported 😕 
https://github.com/rook/rook/blob/85ff00f046ac5f424298c41530135ba8d5066368/pkg/apis/rook.io/v1/types.go#L84-L87

**Comment by travisn** [comment]
Try this schema, you might just be missing the `probe` element.
```yaml
  healthCheck:
    livenessProbe:
      mon:
        probe:     
          timeoutSeconds: 5
          failureThreshold: 5
```

**Comment by viceice** [comment]
sadly i need to override `exec` and `initialDelaySeconds` too

```yml

    livenessProbe:
      mon:
        probe:
          exec:
            command:
              - env
              - '-i'
              - sh
              - '-c'
              - ceph --admin-daemon /run/ceph/ceph-mon.a.asok mon_status
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
```

**Comment by travisn** [comment]
Ah right, specifying the probe requires all the properties, so you could look at the defaults set by rook and then specify those.

**Comment by viceice** [comment]
And hope the next update don't change them 😕 

It would be nice to allow overriding the seconds and thresholds only.

**Comment by travisn** [comment]
> It would be nice to allow overriding the seconds and thresholds only.

Right, that should be very doable. @leseb?

**Comment by leseb** [comment]
> > It would be nice to allow overriding the seconds and thresholds only.
> 
> Right, that should be very doable. @leseb?

Yes and No, unless we want to start exposing specific fields of the liveness probe. We don't want that, because today someone wants to override the seconds, then tomorrow it's the timeout, then the retries. We don't want to create a precedent. That's why we expose the entire definition and not specific fields.

**Comment by travisn** [comment]
I'm thinking the liveness probe spec in the CR wouldn't change. After Rook deserializes the Probe struct, if any fields are empty or 0, Rook could set its defaults on those individual fields.

**Comment by evankanderson** [comment]
I was trying to customize `timeoutSeconds` and ran into this... the workaround of copying the probe values from an existing deployment turns out not to be such a good idea, as the probe encodes a particular `osd` or `mon` index in the health check, so you end up with *all* your health or liveness checks pointing to a single `osd` or `mon`, which doesn't work if it's not on the same host.

**Comment by travisn** [comment]
@evankanderson This will be included in the 1.5.8 release later this week, it should fix this issue for you!

**Comment by 2fst4u** [comment]
> @evankanderson This will be included in the 1.5.8 release later this week, it should fix this issue for you!

Now that we're well past this release, could you please elaborate on how to implement this? I've tried the above changes and I also get errors on v1.6 with pods failing. Removing the changes gets them to work again.

**Comment by travisn** [comment]
@2fst4u It is expected to work as in the example at the top of this issue:
```yaml
spec:
...
  healthCheck:
    livenessProbe:
      mon:
        timeoutSeconds: 5
        failureThreshold: 5
      mgr:
        timeoutSeconds: 5
        failureThreshold: 5
      osd:
        timeoutSeconds: 5
        failureThreshold: 5
```

**Comment by 2fst4u** [comment]
> @2fst4u It is expected to work as in the example at the top of this issue:
> ```yaml
> spec:
> ...
>   healthCheck:
>     livenessProbe:
>       mon:
>         timeoutSeconds: 5
>         failureThreshold: 5
>       mgr:
>         timeoutSeconds: 5
>         failureThreshold: 5
>       osd:
>         timeoutSeconds: 5
>         failureThreshold: 5
> ```

I see. I was adding the `probe` line too. Would that break it now that this syntax is supported? It caused continual errors when I tried it with probe.

**Comment by travisn** [comment]
@2fst4u What is your yaml that is failing?

**Comment by 2fst4u** [comment]
> @2fst4u What is your yaml that is failing?

It's [https://www.github.com/rook/rook/tree/master/cluster%2Fexamples%2Fkubernetes%2Fceph%2Fcluster.yaml](The example cluster.yaml) With only minor changes to other fields. That line is the beginning of the changes you note, adding `timeoutSeconds` and `failureThreshold`. Removing those back out lets the file parse.

**Comment by travisn** [comment]
@2fst4u The syntax failure only happens when you specify the probe? If you don't specify the probe, does it let you specify the other properties such as `failureThreshold`? If only the probe fails, do you see a need to override the probe? Or you're just reporting that the probe failed?

**Comment by 2fst4u** [comment]
> @2fst4u The syntax failure only happens when you specify the probe? If you don't specify the probe, does it let you specify the other properties such as `failureThreshold`? If only the probe fails, do you see a need to override the probe? Or you're just reporting that the probe failed?

No sorry let me clarify.

The following syntax does not parse:

```
spec​:
...
  healthCheck:
    ​livenessProbe:
      mon:
        disabled: false
        timeoutSeconds: 5
        failureThreshold: 5
      mgr:
        disabled: false
        timeoutSeconds: 5
        failureThreshold: 5
      osd:
        disabled: false
        timeoutSeconds: 5
        failureThreshold: 5

```

As it gives the error `error converting YAML to JSON: yaml: line 284: mapping values are not allowed in this context` line 284 in this instance is the "mgr" line so it looks like it doesn't like the timeoutSeconds and failureThreshold.

Ignore the addition of `probe` like I mentioned before, last time I tried that may have been before I upgraded to v1.6. Adding it doesn't parse either.

**Comment by 2fst4u** [comment]
> @2fst4u The syntax failure only happens when you specify the probe? If you don't specify the probe, does it let you specify the other properties such as `failureThreshold`? If only the probe fails, do you see a need to override the probe? Or you're just reporting that the probe failed?

Sorry I deleted the previous comment to avoid incorrect information. I think there might be a sy tax issue in the example you pasted (tabs potentially?) So I just typed it from scratch and it parses.

But after changing the yaml to the following:


```
spec​:
...
  healthCheck:
    ​livenessProbe:
      mon:
        disabled: false
        timeoutSeconds: 5
        failureThreshold: 5
      mgr:
        disabled: false
        timeoutSeconds: 5
        failureThreshold: 5
      osd:
        disabled: false
        timeoutSeconds: 5
        failureThreshold: 5

```

It doesn't change it in the pod when I do a `kubectl describe pod`. It gives the following under "liveness"

```
Liveness:  exec [env -i sh -c ceph --admin-daemon /run/ceph/ceph-mon.c.asok mon_status] delay=10s timeout=1s period=10s #success=1 #failure=3
```

Which appears to still be default?

**Comment by travisn** [comment]
@subhamkrai Can you take a look at whether the values override the defaults in this case?

**Comment by subhamkrai** [comment]
@2fst4u there was a problem with the syntax missing `probe`, I tried with the following it is working as expected
```
healthCheck:
    ---
    # Change pod liveness probe, it works for all mon,mgr,osd daemons
    livenessProbe:
      mon:
        probe:
          initialDelaySeconds: 8
          timeoutSeconds: 3
          periodSeconds: 0
          successThreshold: 0
          failureThreshold: 5
      mgr:
        disabled: false
      osd:
        disabled: false
```
```
Liveness:       exec [env -i sh -c ceph --admin-daemon /run/ceph/ceph-mon.a.asok mon_status] delay=8s timeout=3s period=10s #success=1 #failure=5
```
