### ISSUE TITLE
Fix ProgressingCompleted CephCluster status condition creation to always have a type

### ISSUE THREAD

**Issue by ron1** [rook/rook#7055]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
CephCluster status condition with reason "ProgressingCompleted" is created without a type. GitOps engines such as Rancher Fleet appear to get confused when they encounter status conditions without a type field.

**Expected behavior:**
CephCluster status condition with reason "ProgressingCompleted" is always created with a type. According to function  `checkConditionFalse` that includes the following line of code: https://github.com/rook/rook/blob/c84d42871b4cdc631c436bde90ff8d4647e8c0ae/pkg/operator/ceph/config/conditions.go#L149 it seems the type should always be set to `cephv1.ConditionProgressing`. Inserting the following line of code before this line should fix the problem. I am happy to submit a PR if you agree with this fix.
```
tempCondition = cephv1.ConditionProgressing
```

**How to reproduce it (minimal and precise):**
Create a CephCluster custom resource. Notice its list of conditions below includes multiple entries with reason `ProgressingCompleted`, each of which has no type:

```
status:
  ceph:
    capacity:
      bytesAvailable: 315630157824
      bytesTotal: 322097381376
      bytesUsed: 6467223552
      lastUpdated: "2020-12-15T08:54:16Z"
    health: HEALTH_OK
    lastChecked: "2020-12-15T08:54:16Z"
  conditions:
  - lastHeartbeatTime: "2020-12-15T08:41:59Z"
    lastTransitionTime: "2020-12-15T08:39:06Z"
    message: Cluster progression is completed
    reason: ProgressingCompleted
    status: "False"
    type: Progressing
  - lastHeartbeatTime: "2020-12-15T08:41:59Z"
    lastTransitionTime: "2020-12-15T08:41:59Z"
    message: Cluster created successfully
    reason: ClusterCreated
    status: "True"
    type: Ready
  - lastHeartbeatTime: "2020-12-15T08:42:02Z"
    lastTransitionTime: "2020-12-15T08:42:02Z"
    message: Cluster progression is completed
    reason: ProgressingCompleted
    status: "False"
  message: Cluster created successfully
  phase: Ready
  state: Created
  storage:
    deviceClasses:
    - name: hdd
  version:
    image: ceph/ceph:v15.2.7
    version: 15.2.7-0
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.5.4
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.7
* Kubernetes version (use `kubectl version`): 1.18
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher RKE2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
