### ISSUE TITLE
Cant deploy rook cluster

### ISSUE THREAD

**Issue by Sarga** [rook/rook#706]
Hello.

I'm trying to deploy rook with the following config which I grab from the documentation at: https://github.com/rook/rook/blob/master/Documentation/kubernetes.md

I have Kubernetes v1.5.3 cluster

```
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  versionTag: v0.3.1-117-ge01d34f
  dataDirHostPath:
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    metadataDevice:
    location:
    storeConfig:
      storeType: filestore
      databaseSizeMB:
      journalSizeMB:
    nodes:
    - name: "10.10.10.83"
      directories:
      - path: "/ceph/rook"
    - name: "10.10.10.85"
      directories:
      - path: "/ceph/rook"
    - name: "10.10.10.89"
      directories:
      - path: "/ceph/rook"
```

`
Error from server (NotFound): error when creating "rook-cluster.yaml": the server could not find the requested resource
`
