### ISSUE TITLE
Setting "min_size" in CephBlockPool parameters is ignored

### ISSUE THREAD

**Issue by partcyborg** [rook/rook#7073]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When creating a CephBlockPool with the parameter `min_size: 2`, this value is not inserted into the crushmap.

**Expected behavior:**
`min_size` should be set correctly

**How to reproduce it (minimal and precise):**
Here is my CephBlockPool:
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
spec:
  compressionMode: none
  enableRBDStats: true
  failureDomain: zone
  parameters:
    min_size: "2"
  replicated:
    replicasPerFailureDomain: 1
    requireSafeReplicaSize: true
    size: 3
    subFailureDomain: host
```

When creating the above `CephBlockPool`, I saw the following in the logs and assumed it worked correctly:
```
2021-01-26 22:00:20.885796 I | cephclient: setting pool property "min_size" to "2" on pool "replicapool"
```

However, when examining the current crushmap using `rook-ceph-toolbox`, `min_size` for the new replicapool is set to 1:
```
[root@rook-ceph-tools-747b6cf66c-jw4bm /]# ceph osd getcrushmap -o /tmp/crush.bin
[root@rook-ceph-tools-747b6cf66c-jw4bm /]# crushtool -d /tmp/crush.bin -o /tmp/crush.txt
[root@rook-ceph-tools-747b6cf66c-jw4bm /]# grep -A9 replicapool /tmp/crush.txt
rule replicapool {
	id 1
	type replicated
	min_size 1
	max_size 10
	step take default
	step choose firstn 0 type zone
	step chooseleaf firstn 2 type host
	step emit
}
```

For reference, here is my CephCluster
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
spec:
  annotations: null
  cephVersion:
    allowUnsupported: false
    image: quay.global.bitmex/bitmex/ceph-ceph:v15.2.7
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  crashCollector:
    disable: false
  dashboard:
    enabled: true
    port: 8443
    ssl: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    manageMachineDisruptionBudgets: false
    managePodBudgets: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mgr:
        disabled: false
      mon:
        disabled: false
      osd:
        disabled: false
  labels:
    all: {}
    cleanup: {}
    mon: {}
    osd: {}
    prepareOsd: {}
  mgr:
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    allowMultiplePerNode: false
    count: 3
  monitoring:
    enabled: true
    rulesNamespace: rook-ceph
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - i3.metal
      tolerations:
      - effect: NoSchedule
        key: storage
        operator: Exists
    mon:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app: rook-ceph-mon
            topologyKey: topology.kubernetes.io/zone
          weight: 80
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: rook-ceph-mon
          topologyKey: kubernetes.io/hostname
  removeOSDsIfOutAndSafeToRemove: false
  resources:
    mgr:
      requests:
        cpu: 2
        memory: 1Gi
    mon:
      requests:
        cpu: 1
        memory: 1Gi
    osd:
      requests:
        cpu: 2
        memory: 16Gi
  skipUpgradeChecks: false
  storage:
    config: null
    deviceFilter: nvme[1-8]n1
    useAllDevices: false
    useAllNodes: true
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 8
* Kernel (e.g. `uname -a`): Linux rook-ceph-tools-747b6cf66c-jw4bm 4.19.123-coreos #1 SMP Fri May 22 19:21:11 -00 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: AWS i3.metal instances
* Rook version (use `rook version` inside of a Rook Pod): v1.5.5
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable)
* Kubernetes version (use `kubectl version`): v1.17.6-1+a8884f7132317c
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Self Hosted
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK
