### ISSUE TITLE
osd deplyment name

### ISSUE THREAD

**Issue by hhstu** [rook/rook#7099]
now, each of osd  deployment names  just like:   rook-ceph-osd-1, rook-ceph-osd-2 and so on, it`s  not fulfilling， I can`t get  more  info form it.    I want  osd deployment name just  like this:    ceph-osd-{nodename}-{dev name} , for example:   rook-ceph-node001-sdc .  how do you think about it?

for chinese:
目前的osd deployment的名字在命名上没有任何意义，如： rook-ceph-osd-1    rook-ceph-osd-2 ，我们无法根据 name 简单的获取到 这个osd进程的 详细信息。希望命名规范改成： ceph-osd-{nodename}-{dev name} , 例如： rook-ceph-node001-sdc

**Comment by travisn** [comment]
@hhstu For the node name, there are a couple of ways to find the node, even if it is not in the pod name:
- The node selector on an OSD pins it to a node
- There are topology labels that could be queried on each of the OSD pods such as:

```yaml
    topology-location-host: myhost
    topology-location-rack: rack1
    topology-location-region: region1
    topology-location-root: default
    topology-location-zone: b
```

To find which device corresponds to the OSD, it would definitely be useful to add that label to the OSD pods if possible. I see in the osd prepare job (see the end of the osd log) we get the path being used for the OSDs such as: `BlockPath:/dev/ceph-389cb6fa-8057-4054-b7c7-d1d1bd09fe7f/osd-block-c48ea901-b8f5-4d13-bd19-7129fc12b668`. However, we can't set that as a label because it is too long and contains invalid characters for a label. At a minimum we should document in the [OSD management](https://rook.github.io/docs/rook/v1.5/ceph-osd-mgmt.html) how to identify the device for the OSD.
@satoru-takeuchi thoughts on this?
