### ISSUE TITLE
Placement of device set OSDs are merged with the .spec.resources.osd

### ISSUE THREAD

**Issue by paalkr** [rook/rook#7176]
Seems like https://github.com/rook/rook/pull/6918 introduced a regression when using both PVC OSDs and raw device OSDs in the same ceph cluster, which was added in https://github.com/rook/rook/pull/6822

If the raw device OSDs and the PVC OSDs have different resource requests and placement config, the .spec.resources.osd merges with what's defined at the deviceset placement spec.

cluster spec to illustrate the problem
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false 
  continueUpgradeAfterChecksEvenIfNotHealthy: true
  # removeOSDsIfOutAndSafeToRemove: true
  mon:
    count: 3
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: ebs-gp2
        resources:
          requests:
            storage: 10Gi
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true 
    - name: balancer
      enabled: true                  
  placement:
    mon:
      podAntiAffinity:   
        preferredDuringSchedulingIgnoredDuringExecution:        
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rook-ceph-mon
            topologyKey: failure-domain.beta.kubernetes.io/zone
    osd:
      tolerations:
      - key: k8s.gdo.aws/role
        operator: Equal
        value: storage-ephemeral
        effect: NoSchedule
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kops.k8s.io/instancegroup
              operator: In
              values:
              - storage-a-ephemeral 
              - storage-b-ephemeral
              - storage-c-ephemeral
    prepareosd:
      tolerations:
      - key: k8s.gdo.aws/role
        operator: Equal
        value: storage-ephemeral
        effect: NoSchedule
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kops.k8s.io/instancegroup
              operator: In
              values:
              - storage-a-ephemeral 
              - storage-b-ephemeral
              - storage-c-ephemeral
  resources:
    osd:
      limits:
        cpu: "3500m"
        memory: "25Gi"
      requests:
        cpu: "2500m"
        memory: "12Gi"
    prepareosd:
      limits:
        cpu: "500m"
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "1Gi"
  cephVersion:
    image: ceph/ceph:v15.2.4
    allowUnsupported: false
  dashboard:
    enabled: true
    urlPrefix: /ceph-dashboard
    port: 8443
    ssl: false
  monitoring:
    # requires Prometheus to be pre-installed
    enabled: true
    # namespace to deploy prometheusRule in. If empty, namespace of the cluster will be used.
    # Recommended:
    # If you have a single rook-ceph cluster, set the rulesNamespace to the same namespace as the cluster or keep it empty.
    # If you have multiple rook-ceph clusters in the same k8s cluster, choose the same namespace (ideally, namespace with prometheus
    # deployed) to set rulesNamespace for all the clusters. Otherwise, you will get duplicate alerts with multiple alert definitions.
    rulesNamespace: rook-ceph    
  network:
    hostNetwork: false
  crashCollector:
    disable: false
  # healthChecks
  # Valid values for daemons are 'mon', 'osd', 'status'
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    # Change pod liveness probe, it works for all mon,mgr,osd daemons
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false  
  storage:
    topologyAware: true
    useAllNodes: true
    useAllDevices: true
    config:
      # osdsPerDevice: "1"
      deviceClass: nvme
    storageClassDeviceSets:
    - name: zone-a
      count: 1
      portable: true
      tuneDeviceClass: true
      resources:
        limits:
          cpu: "3500m"
          memory: "7Gi"
        requests:
          cpu: "3000m"
          memory: "6.5Gi"
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k8s.gdo.aws/zone
                operator: In
                values:
                - a 
              - key: k8s.gdo.aws/role
                operator: In
                values:
                - storage   
        tolerations:
        - key: k8s.gdo.aws/role
          operator: Equal
          value: storage
          effect: NoSchedule                
      volumeClaimTemplates:
      - metadata:
          name: data
          annotations:
            crushDeviceClass: ssd
        spec:
          resources:
            requests:
              storage: 305Gi
          storageClassName: ebs-gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
    - name: zone-b
      count: 1
      portable: true
      tuneDeviceClass: true
      resources:
        limits:
          cpu: "3500m"
          memory: "7Gi"
        requests:
          cpu: "3000m"
          memory: "6.5Gi"
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k8s.gdo.aws/zone
                operator: In
                values:
                - b
              - key: k8s.gdo.aws/role
                operator: In
                values:
                - storage  
        tolerations:
        - key: k8s.gdo.aws/role
          operator: Equal
          value: storage
          effect: NoSchedule                
      volumeClaimTemplates:
      - metadata:
          name: data
          annotations:
            crushDeviceClass: ssd
        spec:
          resources:
            requests:
              storage: 305Gi
          storageClassName: ebs-gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce 
    - name: zone-c
      count: 1
      portable: true
      tuneDeviceClass: true
      resources:
        limits:
          cpu: "3500m"
          memory: "7Gi"
        requests:
          cpu: "3000m"
          memory: "6.5Gi"
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k8s.gdo.aws/zone
                operator: In
                values:
                - c
              - key: k8s.gdo.aws/role
                operator: In
                values:
                - storage 
        tolerations:
        - key: k8s.gdo.aws/role
          operator: Equal
          value: storage
          effect: NoSchedule
      volumeClaimTemplates:
      - metadata:
          name: data
          annotations:
            crushDeviceClass: ssd
        spec:
          resources:
            requests:
              storage: 305Gi
          storageClassName: ebs-gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
```

The rendered pvc OSD deployment for deviceset `zone-a` ends up with this affinity rules, which will not satisfy any of the nodes in the cluster. 

deployment for DeviceSet `zone-a`
```
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: k8s.gdo.aws/zone
              operator: In
              values:
              - a
            - key: k8s.gdo.aws/role
              operator: In
              values:
              - storage
            - key: kops.k8s.io/instancegroup
              operator: In
              values:
              - storage-a-ephemeral
              - storage-b-ephemeral
              - storage-c-ephemeral
```

deployment for DeviceSet `zone-b`
```
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: k8s.gdo.aws/zone
              operator: In
              values:
              - b
            - key: k8s.gdo.aws/role
              operator: In
              values:
              - storage
            - key: kops.k8s.io/instancegroup
              operator: In
              values:
              - storage-a-ephemeral
              - storage-b-ephemeral
              - storage-c-ephemeral
```

deployment for DeviceSet `zone-c`
```
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: k8s.gdo.aws/zone
              operator: In
              values:
              - c
            - key: k8s.gdo.aws/role
              operator: In
              values:
              - storage
            - key: kops.k8s.io/instancegroup
              operator: In
              values:
              - storage-a-ephemeral
              - storage-b-ephemeral
              - storage-c-ephemeral
```

**Comment by travisn** [comment]
To allow for the specifying different node affinity for the non-PVC OSDs and the PVC OSDs, it seems we cannot merge the affinity if specified in both places. 
@subhamkrai Could you look at not merging the affinity in this fallback case? For example, if the affinity is specified in the storageClassDeviceSet, it wouldn't fallback to merge the main OSD affinity.

**Comment by paalkr** [comment]
Thanks for looking into this.

The case applies to resource requests/limits, nodeAffinity and toleration. In my opinion the values defined in the storageClassDeviceSets should not be  merged or altered in any way if specified. If not configured, applying the global osd config make sense.

**Comment by travisn** [comment]
I thought that only the nodeAffinity was being merged, while the resource requests/limits and tolerations would just use one or the other without merging. You're observing they are all being merged?

**Comment by paalkr** [comment]
Sorry, I didn't put that very clear. I'm not sure if the merge problem actually applies to tolerations and requests. I was just pointing out that we should check if it did, and make sure to not touche any defined config in the deviceSets. So probably the issue only applies to the nodeAffinity. I can only recall to have observed nodeAffinity config being merged.

**Comment by subhamkrai** [comment]
> To allow for the specifying different node affinity for the non-PVC OSDs and the PVC OSDs, it seems we cannot merge the affinity if specified in both places.
> @subhamkrai Could you look at not merging the affinity in this fallback case? For example, if the affinity is specified in the storageClassDeviceSet, it wouldn't fallback to merge the main OSD affinity.

I believe with [this](https://github.com/rook/rook/commit/369ad40cf437001ce547c67c6a1f8fec1eca9479#diff-da51f1d1cd0bcb44d1bfec78f7fbc3f63eae4baa2173b7c404144b7cbeea3b61R612-R616) check will not merge any `NodeAffinity, PodAffinity...`.

**Comment by paalkr** [comment]
@travisn , unfortunately https://github.com/rook/rook/pull/7192 didn't fix this issue. Now with the 1.5.8 release the node affinity and toleration from the placement (device OSDs) are applied to the PVC OSDs, and the affinity and toleration in the deviceSet are totally ignored.

**Comment by travisn** [comment]
> @travisn , unfortunately #7192 didn't fix this issue. Now with the 1.5.8 release the node affinity and toleration from the placement (device OSDs) are applied to the PVC OSDs, and the affinity and toleration in the deviceSet are totally ignored.

Ok, the combinations are proving difficult... How about reopening this issue or opening a new one, also with a more detailed example of the unexpected behavior? thanks

**Comment by paalkr** [comment]
Sorry, but I do not have the permission to reopen this issue

Given the cluster spec in the original message, the PVC OSD now ended up with
```
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kops.k8s.io/instancegroup
              operator: In
              values:
              - storage-a-ephemeral
              - storage-b-ephemeral
              - storage-c-ephemeral
```
Which is only the nodeAffinity from the device OSD, not the PVC OSD.

**Comment by subhamkrai** [comment]
@paalkr then please open a new issue as Travis said. Thanks.

**Comment by travisn** [comment]
@paalkr A couple more questions:
1. What was the node affinity you expected on the PVC OSD?
2. Was the device OSD affinity correct?

**Comment by paalkr** [comment]
Thanks for reopening @travisn 

1. I expected the device OSD affinity and toleration to be
deployment for DeviceSet `zone-a`
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k8s.gdo.aws/zone
                operator: In
                values:
                - a
              - key: k8s.gdo.aws/role
                operator: In
                values:
                - storage
      tolerations:
      - effect: NoSchedule
        key: k8s.gdo.aws/role
        operator: Equal
        value: storage
```
deployment for DeviceSet `zone-b`
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k8s.gdo.aws/zone
                operator: In
                values:
                - b
              - key: k8s.gdo.aws/role
                operator: In
                values:
                - storage
      tolerations:
      - effect: NoSchedule
        key: k8s.gdo.aws/role
        operator: Equal
        value: storage
```

deployment for DeviceSet `zone-c`
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k8s.gdo.aws/zone
                operator: In
                values:
                - c
              - key: k8s.gdo.aws/role
                operator: In
                values:
                - storage
      tolerations:
      - effect: NoSchedule
        key: k8s.gdo.aws/role
        operator: Equal
        value: storage
```

2. The reconcile loop failed before modifying the device OSDs, so I'm not sure. I can try to execute another experiment, to see if the device ODSs are rendered correctly.

**Comment by travisn** [comment]
Ok, understood now. @subhamkrai Let's discuss, thanks.

**Comment by subhamkrai** [comment]
@travisn  I was looking into this and here I think we are overriding the device set placement with spec.placement. 

https://github.com/rook/rook/blob/c0eacc89d50d4dbe4fc9b5606241a62c676ccca0/pkg/operator/ceph/cluster/osd/spec.go#L659-L663

First device set placement is applied and then it is overridden by spec.placement(if applied).

**Comment by subhamkrai** [comment]
I had this configuration 
```
spec:
  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - us-east-1d
                - us-east-1c
  storage:
    storageClassDeviceSets:
      ---
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                    - us-east-1a
                    - us-east-1b
```

and I see my osd are on zone c and d only. I think this confirms my assumption on overriding? @travisn
