### ISSUE TITLE
Warning: Detected changes to resource object-store which is currently being deleted.

### ISSUE THREAD

**Issue by OPSTime** [rook/rook#7200]
Version：
kubernetes：v1.20.2
rook/ceph: v1.5.6  

$  kubectl apply -f object.yaml 
Warning: Detected changes to resource object-store which is currently being deleted.
cephobjectstore.ceph.rook.io/object-store configured

$ cat object.yaml |grep -v '#'
```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: object-store
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      compression_mode: none
      target_size_ratio: ".5"
  dataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      compression_mode: force
      target_size_ratio: ".5"
  preservePoolsOnDelete: false
  gateway:
    type: s3
    sslCertificateRef:
    port: 80
    instances: 1
    placement:
    annotations:
    labels:
    resources:
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
    livenessProbe:
      disabled: false
```
