### ISSUE TITLE
Unable to force the creation of OSDs each on different AZ

### ISSUE THREAD

**Issue by ahmedTouati** [rook/rook#7252]
I want to create a cluster-on-pvc using Rook and CephFS with 3 OSDs, when using the default configuration i can get each OSD on different AZ when i have 3 nodes in my cluster with each on different AZ, but when i have only two nodes running in the cluster i expected that one of the 3 OSDs will remain in the pending state until a new node with the corresponding AZ is added, but i can see that the third OSD is scheduled any way (on the same node with another OSD), i tried using this config.

**Expected behavior:**

The creation of each OSD on different AZ
**File(s) to submit**:

```
storage:
    storageClassDeviceSets:
    - name: set1
      # The number of OSDs to create from this device set
      count: 1
      # IMPORTANT: If volumes specified by the storageClassName are not portable across nodes
      # this needs to be set to false. For example, if using the local storage provisioner
      # this should be false.
      portable: true
      # Certain storage class in the Cloud are slow
      # Rook can configure the OSD running on PVC to accommodate that by tuning some of the Ceph internal
      # Currently, "gp2" has been identified as such
      tuneDeviceClass: true
      # Certain storage class in the Cloud are fast
      # Rook can configure the OSD running on PVC to accommodate that by tuning some of the Ceph internal
      # Currently, "managed-premium" has been identified as such
      tuneFastDeviceClass: false
      # whether to encrypt the deviceSet or not
      encrypted: true
      # Since the OSDs could end up on any node, an effort needs to be made to spread the OSDs
      # across nodes as much as possible. Unfortunately the pod anti-affinity breaks down
      # as soon as you have more than one OSD per node. The topology spread constraints will
      # give us an even spread on K8s 1.18 or newer.
      preparePlacement:
        nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
              - eu-west-1a
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
            topologyKey: kubernetes.io/hostname
      resources:
      # These are the OSD daemon limits. For OSD prepare limits, see the separate section below for "prepareosd" resources
         limits:
           cpu: "500m"
           memory: "4Gi"
         requests:
           cpu: "500m"
           memory: "1Gi"
      volumeClaimTemplates:
      - metadata:
          name: data
          # if you are looking at giving your OSD a different CRUSH device class than the one detected by Ceph
          # annotations:
          #   crushDeviceClass: hybrid
        spec:
          resources:
            requests:
              storage: 2Gi
          # IMPORTANT: Change the storage class depending on your environment (e.g. local-storage, gp2)
          storageClassName: gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
    - name: set2
      # The number of OSDs to create from this device set
      count: 1
      # IMPORTANT: If volumes specified by the storageClassName are not portable across nodes
      # this needs to be set to false. For example, if using the local storage provisioner
      # this should be false.
      portable: true
      # Certain storage class in the Cloud are slow
      # Rook can configure the OSD running on PVC to accommodate that by tuning some of the Ceph internal
      # Currently, "gp2" has been identified as such
      tuneDeviceClass: true
      # Certain storage class in the Cloud are fast
      # Rook can configure the OSD running on PVC to accommodate that by tuning some of the Ceph internal
      # Currently, "managed-premium" has been identified as such
      tuneFastDeviceClass: false
      # whether to encrypt the deviceSet or not
      encrypted: true
      # Since the OSDs could end up on any node, an effort needs to be made to spread the OSDs
      # across nodes as much as possible. Unfortunately the pod anti-affinity breaks down
      # as soon as you have more than one OSD per node. The topology spread constraints will
      # give us an even spread on K8s 1.18 or newer.
      preparePlacement:
        nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
              - eu-west-1b
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
            topologyKey: kubernetes.io/hostname
      resources:
      # These are the OSD daemon limits. For OSD prepare limits, see the separate section below for "prepareosd" resources
         limits:
           cpu: "500m"
           memory: "4Gi"
         requests:
           cpu: "500m"
           memory: "1Gi"
      volumeClaimTemplates:
      - metadata:
          name: data
          # if you are looking at giving your OSD a different CRUSH device class than the one detected by Ceph
          # annotations:
          #   crushDeviceClass: hybrid
        spec:
          resources:
            requests:
              storage: 2Gi
          # IMPORTANT: Change the storage class depending on your environment (e.g. local-storage, gp2)
          storageClassName: gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
    - name: set3
      # The number of OSDs to create from this device set
      count: 1
      # IMPORTANT: If volumes specified by the storageClassName are not portable across nodes
      # this needs to be set to false. For example, if using the local storage provisioner
      # this should be false.
      portable: true
      # Certain storage class in the Cloud are slow
      # Rook can configure the OSD running on PVC to accommodate that by tuning some of the Ceph internal
      # Currently, "gp2" has been identified as such
      tuneDeviceClass: true
      # Certain storage class in the Cloud are fast
      # Rook can configure the OSD running on PVC to accommodate that by tuning some of the Ceph internal
      # Currently, "managed-premium" has been identified as such
      tuneFastDeviceClass: false
      # whether to encrypt the deviceSet or not
      encrypted: true
      # Since the OSDs could end up on any node, an effort needs to be made to spread the OSDs
      # across nodes as much as possible. Unfortunately the pod anti-affinity breaks down
      # as soon as you have more than one OSD per node. The topology spread constraints will
      # give us an even spread on K8s 1.18 or newer.
      preparePlacement:
        nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
              - eu-west-1c
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
            topologyKey: kubernetes.io/hostname
      resources:
      # These are the OSD daemon limits. For OSD prepare limits, see the separate section below for "prepareosd" resources
         limits:
           cpu: "500m"
           memory: "4Gi"
         requests:
           cpu: "500m"
           memory: "1Gi"
      volumeClaimTemplates:
      - metadata:
          name: data
          # if you are looking at giving your OSD a different CRUSH device class than the one detected by Ceph
          # annotations:
          #   crushDeviceClass: hybrid
        spec:
          resources:
            requests:
              storage: 2Gi
          # IMPORTANT: Change the storage class depending on your environment (e.g. local-storage, gp2)
          storageClassName: gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
```

**Environment**:
* OS (e.g. from /etc/os-release): 
* Kernel (e.g. `uname -a`): 4.14
* Cloud provider or hardware configuration: AWS EKS
* Rook version (use `rook version` inside of a Rook Pod): master
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.18
* Kubernetes version (use `kubectl version`): 1.18
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
