### ISSUE TITLE
1.5.7: Object Gateway health checks fail when TLS is enabled + Cannot disable heath checks

### ISSUE THREAD

**Issue by schantaraud** [rook/rook#7288]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

`kubectl describe CephObjectStore ceph-object-store  -n rook-ceph`:
```
Status:
  Bucket Status:
    Details:  failed to run bucket health checks for object store "ceph-object-store": failed to create bucket "rook-ceph-bucket-checker-cebac00d-d086-49f4-8852-1c6ccb784c27" for object store "ceph-object-store": failed to create bucket "rook-ceph-bucket-checker-cebac00d-d086-49f4-8852-1c6ccb784c27": RequestError: send request failed
caused by: Put http://rook-ceph-rgw-ceph-object-store.rook-ceph.svc:443/rook-ceph-bucket-checker-cebac00d-d086-49f4-8852-1c6ccb784c27: EOF
    Health:        Failure
    Last Checked:  2021-02-22T20:22:51Z
  Info:
    Endpoint:  https://rook-ceph-rgw-ceph-object-store.rook-ceph.svc:443
  Phase:       Failure
```

Note that the endpoint is correct but the error shows that the health check is trying to use HTTP on port 443.

Operator logs:
```
2021-02-22 20:36:38.864211 E | ceph-object-controller: failed to delete object from bucket. RequestError: send request failed
caused by: Delete http://rook-ceph-rgw-ceph-object-store.rook-ceph.svc:443/rook-ceph-bucket-checker-36b05a5a-ad3f-4cb4-a834-e0186e2304b1/rookHealthCheckTestObject: dial tcp 100.71.166.222:443: connect: connection refused
```

Also, setting `healthCheck.bucket.disabled: true` on the CRD is ignored (it doesn't show when I get the CRD back after editing it)

**Expected behavior:**

- Health check uses HTTPS on port 443
- setting `healthCheck.bucket.disabled: true` disables health checks 

**How to reproduce it (minimal and precise):**

```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: ceph-object-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
  dataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
  preservePoolsOnDelete: false
  healthCheck:
    bucket:
      disabled: true
  gateway:
    type: s3
    port: 0 # Disabled
    sslCertificateRef: rook-ceph-rgw-ceph-object-store-tls
    securePort: 443
    instances: 3
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - storage
    annotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/ca-cert: /run/secrets/kubernetes.io/serviceaccount/ca.crt
      vault.hashicorp.com/role: ceph-rgw
```

Note that the error is the same with both HTTP and HTTPS enabled (`port: 80`)

**Environment**:
* OS (e.g. from /etc/os-release): Linux Ubuntu
* Kernel (e.g. `uname -a`): 5.4.0-1021-aws
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod):  1.5.7
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.8
* Kubernetes version (use `kubectl version`): 1.19.7
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kops
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK
