### ISSUE TITLE
ci: improve github action writing

### ISSUE THREAD

**Issue by leseb** [rook/rook#7376]
We have a lot of places where code is duplicated. It would be nice to factor everything into a bash script that will be called with arguments where each argument is the line we are looking at.

Something like:

```yaml
    - name: install deps
      run: ci-helper.sh install-deps

     - name: use local disk
     run: ci-helper.sh use-local-disk
```

Then `ci-helper.sh` will have functions that can be called independently.
