### ISSUE TITLE
Allow the NFS service to be configured as a load balancer

### ISSUE THREAD

**Issue by tibbe** [rook/rook#7720]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Allow for the NFS service, generated implicitly by the NFS operator from the NFS configs [described in Network Filesystem (NFS)](https://rook.io/docs/rook/v1.6/nfs.html), to be configured as a load balancer with an IP set through `spec.loadBalancerIP`. As a consequence of allowing an external IP, the generated NFS-Ganesha config might also need to change to allow connections from outside the cluster.

I believe the latter is needed as I tried adding a second (load balancer) service to expose the pod created by the Rook NFS operator, which resulted in hosts on the *host* network (e.g. 192.168.1.0/24) to be able to connect to the load balancer service while hosts (e.g. 172.19.27.38) outside that network couldn't. This is the config I used:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-nfs
  name: rook-nfs-external
  namespace: rook-nfs
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.11
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
    targetPort: 2049
  - name: rpc
    port: 111
    protocol: TCP
    targetPort: 111
  selector:
    app: rook-nfs
```

(This is the same as https://github.com/rook/rook/issues/7674 but for the regular, non-Ceph-specific, Rook NFS support.)

**What is use case behind this feature:**

Expose NFS outside the cluster through an IP.

**Environment**:
