### ISSUE TITLE
OSDs not having the expected device class applied from the cluster config in version 1.6

### ISSUE THREAD

**Issue by cyclops8456** [rook/rook#7753]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Setting a cluster up with version 1.5.10 of the Rook operator with device classes specified in the cluster CR results in the OSDs having the device class as expected.  Using the same cluster config for version 1.6.1 of the operator results in the OSDs all having the device class of hdd.

```
ceph osd tree (1.5)
```
```
ID   CLASS  WEIGHT   TYPE NAME                                   STATUS  REWEIGHT  PRI-AFF
 -1         2.63667  root default                                                         
 -5         0.87889      host node1                           
  6    hdd  0.39059          osd.6                                   up   1.00000  1.00000
  3   nvme  0.29300          osd.3                                   up   1.00000  1.00000
  0    ssd  0.19530          osd.0                                   up   1.00000  1.00000
-13         0.87889      host node2                           
  8    hdd  0.39059          osd.8                                   up   1.00000  1.00000
  5   nvme  0.29300          osd.5                                   up   1.00000  1.00000
  2    ssd  0.19530          osd.2                                   up   1.00000  1.00000
 -9         0.87889      host node3                           
  7    hdd  0.39059          osd.7                                   up   1.00000  1.00000
  4   nvme  0.29300          osd.4                                   up   1.00000  1.00000
  1    ssd  0.19530          osd.1                                   up   1.00000  1.00000
```

```
ceph osd tree (1.6)
```
```
ID  CLASS  WEIGHT   TYPE NAME                                   STATUS  REWEIGHT  PRI-AFF
-1         2.63667  root default                                                         
-3         0.87889      host node1                           
 0    hdd  0.19530          osd.0                                 down   1.00000  1.00000
 3    hdd  0.29300          osd.3                                 down   1.00000  1.00000
 6    hdd  0.39059          osd.6                                 down   1.00000  1.00000
-7         0.87889      host node2                           
 2    hdd  0.29300          osd.2                                 down   1.00000  1.00000
 4    hdd  0.39059          osd.4                                 down   1.00000  1.00000
 8    hdd  0.19530          osd.8                                 down   1.00000  1.00000
-5         0.87889      host node3                           
 1    hdd  0.39059          osd.1                                 down   1.00000  1.00000
 5    hdd  0.19530          osd.5                                 down   1.00000  1.00000
 7    hdd  0.29300          osd.7                                 down   1.00000  1.00000
```
**Expected behavior:**

OSDs should have the device class set as per the cluster config in the same manner as 1.5.x

**How to reproduce it (minimal and precise):**

1) Create cluster with version 1.5
2) Observe device classes set against OSDs via the toolbox.
3) Tear down cluster and wipe disks involved
4) Create cluster with version 1.6
5) Observer wrong device classes against OSDs (presumably default) and in down status.

**File(s) to submit**:
Relevant section of the cluster config

```
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "node1"
      devices:
      - name: "/dev/sdb"
        config:
          deviceClass: hdd
      - name: "/dev/sdc"
        config:
          deviceClass: ssd
      - name: "/dev/sdd"
        config:
          deviceClass: nvme
    - name: "node2"
      devices:
      - name: "/dev/sdb"
        config:
          deviceClass: hdd
      - name: "/dev/sdc"
        config:
          deviceClass: ssd
      - name: "/dev/sdd"
        config:
          deviceClass: nvme
    - name: "node3"
      devices:
      - name: "/dev/sdb"
        config:
          deviceClass: hdd
      - name: "/dev/sdc"
        config:
          deviceClass: ssd
      - name: "/dev/sdd"
        config:
          deviceClass: nvme
```

**Environment**:
* OS (e.g. from /etc/os-release): **CentOS **Linux** 8**
* Kernel (e.g. `uname -a`): **4.18.0-240.22.1.el8_3.x86_64**
* Cloud provider or hardware configuration: **Bare metal**
* Rook version (use `rook version` inside of a Rook Pod): **rook: v1.6.1**
* Storage backend version (e.g. for ceph do `ceph -v`): **ceph version 16.2.1 (afb9061ab4117f798c858c741efa6390e48ccf10) pacific (stable)**
* Kubernetes version (use `kubectl version`): **1.21.0**
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): **Vanilla Kubernetes**
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): **HEALTH_WARN**

**Comment by cyclops8456** [comment]
From the OSD prepare logs, it looks like the deviceClass is still being passed in correctly.

```
{"Entries":{"sdc":{"Data":-1,"Metadata":null,"Config":{"Name":"/dev/sdc","OSDsPerDevice":1,"MetadataDevice":"","DatabaseSizeMB":0,"DeviceClass":"ssd","InitialWeight":"",.....
```

**Comment by cyclops8456** [comment]
Using Ceph image version 15.2.11 results in:

1) Wrong device class set against the OSD
2) Status down
3) HEALTH_WARN

Using Ceph image version 16.2.1 results in:

1) Wrong device class set against the OSD
2) Status down
3) HEALTH_OK

**Comment by travisn** [comment]
Since the correct device class is still seen in the osd prepare logs, the CRD schema must be preserving the value. The CRD schema also looks correct for preserving the config settings under `nodes`. 
@cyclops8456 Please share more of the osd prepare log, in particular where the ceph-volume command is called and should specify the device class.

**Comment by zamnuts** [comment]
Hit this bug today, while i don't have prepare logs, i can provide more details:

- `ceph -v`: `ceph version 16.2.2 (e8f22dde28889481f4dda2beb8a07788204821d3) pacific (stable)`
- `ceph health`: `HEALTH_OK`
- kubernetes: vanilla, 1.20.8
- No issues on rook@1.5 as the SSD OSDs had the proper device class.
- A fresh install of 1.6 now includes a nvme metadata device per host, which caused the OSD prepare pods to start creating LVM on the block devices. Prior to this fresh install using 1.5 and _no nvme metadata device_, there were no LVM partitions, and the device class was properly set to ssd.

https://access.redhat.com/solutions/3341491 provides a workaround, albeit not zero-touch:
1. fire up the toolbox: https://rook.io/docs/rook/v1.6/ceph-toolbox.html
1. `ceph osd df tree` to get the osd id need to change class and confirm the class is `hdd`
2. remove the class using `rm-device-class`, this uses osd id 8: `ceph osd crush rm-device-class osd.8`
3. associate the right class using `set-device-class`, again with osd id 8: `ceph osd crush set-device-class ssd osd.8`
4. `ceph osd df tree` to confirm the class for the osd is now `ssd`

**Comment by travisn** [comment]
@zamnuts Does your cluster CR specify the `nodes.devices.config.deviceClass` property similar to the original issue reported? I'm not clear if ceph's auto-detection for the device class is not working for you, or if the deviceClass from the cluster CR is not being applied.

**Comment by zamnuts** [comment]
@travisn yes, I tried both with and without. I initially started _without_ explicit `deviceClass` and found that SSDs were being given the `hdd` class. I purged the cluster (as in all of rook, including zeroing disks, removing /var/rook, etc.), and tried again while explicitly declaring the `deviceClass` which still marked my SSDs as `hdd`.

I use an NVMe metadata device, automatically partitioned by ceph (I disagree w/ the default computed partition sizing, so i hardcode that - topic for another day), and that gets picked up and used properly by ceph. This means that ceph is seeing the NVMe as a _faster_ device class than the `hdd` and `ssd`, otherwise (per the docs) it wouldn't use it for my `hdd` nor `ssd` class devices, right?

```
# k get cephcluster -n rook-ceph rook-ceph -oyaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
# ...
spec:
# ...
  storage:
    nodes:
    - config:
        databaseSizeMB: "488000"
        metadataDevice: /dev/nvme0n1
      devices:
      - config:
          deviceClass: hdd
        name: /dev/disk/by-id/scsi-SMercury_Elite_Pro_Quad_A_400987654321
      - config:
          deviceClass: hdd
        name: /dev/disk/by-id/scsi-SMercury_Elite_Pro_Quad_B_900987654321
      - config:
          deviceClass: ssd
        name: /dev/disk/by-id/scsi-SMercury_Elite_Pro_Quad_D_510987654321
      name: nuc700
```

**Comment by travisn** [comment]
@zamnuts In a quick test I see that the deviceClass was applied as expected to the OSDs. This was my yaml:
```
    nodes:
      - name: "minikube"
        devices: # specific devices to use for storage can be specified for each node
          - name: "sdb"
            config:
               deviceClass: myclass
          - name: "sdc"
            config:
               deviceClass: otherclass
```

Is it working for you now perhaps in a later release?
