### ISSUE TITLE
ceph.conf cannot be configured in rgw pod

### ISSUE THREAD

**Issue by ycy1766** [rook/rook#7761]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I created rgw pod using cephobjectsore in rook 1.6.1 (ceph pacific).
By the way, `rgw_dns_name`  and `rgw_dns_s3website_name` are set in rook-config-override.yaml, but check using ` radosgw-admin --show-config `in rgw pod, it is not applied.
However, it was confirmed that it is applied in rook.1.5.10 with the same configuration.

**Expected behavior:**
rook-config-override.yaml  configuration is applied to the rgw pod.

**How to reproduce it (minimal and precise):**

rook-config-override.yaml
```
 apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    public network =  10.20.2.0/24
    cluster network = 10.20.3.0/24
    public addr = ""
    cluster addr = ""

    #[client.stg1.obs.*]
    # RGW LOG
    rgw_ops_log_rados = false
    rgw_enable_ops_log = false
    rgw_enable_usage_log = true
    rgw_log_http_headers = http_x_forwarded_for

    #RGW WEB SITE
    rgw_enable_static_website = true
    #rgw_dns_s3website_name = kr-website.cafe24cloud.kr
    rgw_dns_s3website_name = ws.cyuucloud.xyz

    # RGW DNS
    #rgw dns name= obs.cafe24cloud.kr
    rgw_dns_name= rgw.cyuucloud.xyz
    #rgw_resolve_cname = false
    rgw_resolve_cname = true

    # RGW SEETING
    rgw_max_objs_per_shard = 50000000
    rgw_override_bucket_index_max_shards = 20
    rgw_list_buckets_max_chunk = 2000
```
rgw.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: test-obs
  namespace: rook-ceph
spec:
  metadataPool:
    crushRoot: default
    deviceClass: hdd
    failureDomain: host
    replicated:
      size: 1
  dataPool:
    crushRoot: default
    deviceClass: hdd
    failureDomain: host
    replicated:
      size: 1
  preservePoolsOnDelete: false
  gateway:
    type: s3
    port: 80
    instances: 1
```
in rook-1.5.10 rgw pod 
```
[root@cy02-ceph026 /]# radosgw-admin  --show-config  | grep dns
parse error setting 'cluster_addr' to ''
parse error setting 'public_addr' to ''
mon_dns_srv_name = ceph-mon
rgw_dns_name = rgw.cyuucloud.xyz
rgw_dns_s3website_name = ws.cyuucloud.xyz
```
in rook-1.6.1 rgw pod 
```
[root@cy02-ceph026 /]# radosgw-admin  --show-config  | grep dns
mon_dns_srv_name = ceph-mon
rgw_dns_name =
rgw_dns_s3website_name =
```
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):  Ubuntu 20.04.2 LTS
* Kernel (e.g. `uname -a`):  5.4.0-65-generic
* Cloud provider or hardware configuration: hardware 
* Rook version (use `rook version` inside of a Rook Pod): 1.6.1
* Storage backend version (e.g. for ceph do `ceph -v`):  ceph version 16.2.1 
* Kubernetes version (use `kubectl version`): v1.19.9
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): vanila
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): OK
