### ISSUE TITLE
rook-ceph 1.6.1 CRD requires spec.mon.count for external cluster

### ISSUE THREAD

**Issue by electrical** [rook/rook#7788]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
CephCluster CRD doesn't work anymore for external cluster.
It requires spec.mon.count value while this is not expected

**Expected behavior:**
To work :-)

**How to reproduce it (minimal and precise):**
Apply simple external cluster resource:

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph-external
  namespace: rook-ceph-external # namespace:cluster
spec:
  external:
    enable: true
  dataDirHostPath: /var/lib/rook
  # providing an image is required, if you want to create other CRs (rgw, mds, nfs)
  cephVersion:
    image: ceph/ceph:v15.2.11 # Should match external cluster version
```

**File(s) to submit**:

relevant change of the CRD around mon properties

1.5:
```
count:
  maximum: 9
  minimum: 0
  type: integer
```

1.6:
```
count:
  description: Count is the number of Ceph monitors
  minimum: 1
  type: integer
```

**Environment**:
rook-ceph 1.6.1

**Comment by electrical** [comment]
After some debugging found the following. Some older version of rook-ceph must have added a lot of empty fields to the CephCluster resource after creation since I had this as the resulting spec:

```
spec:
  cephVersion:
    image: ceph/ceph:v15.2.8
  cleanupPolicy:
    sanitizeDisks: {}
  crashCollector:
    disable: false
  dashboard: {}
  dataDirHostPath: /var/lib/rook
  disruptionManagement: {}
  external:
    enable: true
  healthCheck:
    daemonHealth:
      mon: {}
      osd: {}
      status: {}
  logCollector: {}
  mgr: {}
  mon: {}
  monitoring: {}
  network:
    hostNetwork: false
    ipFamily: IPv4
    provider: ""
    selectors: null
  removeOSDsIfOutAndSafeToRemove: false
  security:
    kms: {}
  storage:
    config: null
    storageClassDeviceSets: null
```

These fields are not used and confused the updated CRD.

Solution was to remove everything under the `spec` key and replace it with the original content of my cluster definition.
This solved the issue and allowed it to deploy the updated version.
