### ISSUE TITLE
Changing liveness probe values causes pod crashes

### ISSUE THREAD

**Issue by 2fst4u** [rook/rook#7842]
**Is this a bug report or feature request?**
* Bug Report *

**Deviation from expected behaviour**

When changing the liveness probe fields from default, the relevant pods go into crashloopbackoff with the error `Liveness probe failed: admin_socket: exception getting command descriptions: [Errno 2] No such file or directory`

The settings do apply, as can be shown when doing a `kubectl describe` on the pods.

**Expected behavior:**

Liveness probe settings shouldn't cause pod crashes

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

Attached are files are my cluster.yaml (note the commented out values are uncommented when I apply it and get errors) and also a mon pod's logs

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.2 LTS
* Kernel (e.g. `uname -a`): Linux 5.4.0-1034-raspi
* Cloud provider or hardware configuration: 3 X Raspberry Pi 4B 8GB booting from SD
* Rook version (use `rook version` inside of a Rook Pod): v1.6.1
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.9
* Kubernetes version (use `kubectl version`): v1.20.4+k3s1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): K3S
* Storage backend status: `HEALTH_WARN 12 daemons have recently crashed` but that's an outcome rather than a symptom. I've cleared this so it's healthy before starting and it causes the crashes.
   

I fear my strategy may be completely wrong but of note is that I have a very low power cluster. Under default values my cluster gives continual `Liveness Probe Failed` but doesn't crash and just carries on. I was hoping to prevent these warnings by giving more conservative values. No matter the values I give, the pods always go into a crashloopbackoff and I have to go through a recovery of the cluster.

Am I going about this wrong? It's a subject I can't find much on at all unfortunately.

**Comment by 2fst4u** [comment]
[kubectl log.txt](https://github.com/rook/rook/files/6432788/kubectl.log.txt)

[cluster.yaml.txt](https://github.com/rook/rook/files/6432794/cluster.yaml.txt)

**Comment by subhamkrai** [comment]
@2fst4u please check your syntax, I tried with the same value

`rook-ceph-mon-a-85cbcf5c96-4wxrz                         1/1     Running    0          50s`
```   
Liveness:       exec [env -i sh -c ceph --admin-daemon /run/ceph/ceph-mon.a.asok mon_status] delay=20s timeout=10s period=20s #success=1 #failure=3
```
my schema
```
    livenessProbe:
      mon:
        disabled: false
        probe:
          initialDelaySeconds: 20
          timeoutSeconds: 10
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
      mgr:
        disabled: false
        probe:
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
      osd:
        disabled: false
        probe:
          initialDelaySeconds: 45
          timeoutSeconds: 10
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
```
the problem is your syntax you are putting `probe` field inside `disabled`
