### ISSUE TITLE
update Ingress to apiVersion: networking.k8s.io/v1

### ISSUE THREAD

**Issue by fzhan** [rook/rook#7905]
**Is this a bug report or feature request?**
* Feature Request
update ingress yaml to adept apiVersion: networking.k8s.io/v1
**What should the feature do:**
- current setup doesn't work under k8s 1.20

**What is use case behind this feature:**
- after update to the following code, URL responded with code 503
***Sample Code***
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph # namespace:cluster
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
spec:
  ingressClassName: public
  tls:
    - hosts:
        - rook.services.local
      secretName: rook.services.local
  rules:
    - host: rook.services.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rook-ceph-mgr-dashboard
                port:
                  name: https-dashboard
```

**Environment**:
rook-ceph v release-1.6
k8s: 1.20.4
