### ISSUE TITLE
Cannot Mount CephFS No Timeout, mount error 5 = Input/output error

### ISSUE THREAD

**Issue by icpenguins** [rook/rook#7994]
# Bug Report

**Deviation from expected behavior:**
On most hosts, mounting the CephFS will not succeed. On one host, a Raspberry PI 4, it did mount. However, immediately after mounting, a simple `cp filea.txt /cephfs/filea.txt` fails. Creating a directory did work, but the `mkdir /cephfs/test` hangs.

***Ceph mon stat***
```shell
e30: 3 mons at {b=[v2:10.102.28.116:3300/0,v1:10.102.28.116:6789/0],n=[v2:10.101.151.140:3300/0,v1:10.101.151.140:6789/0],p=[v2:10.102.247.49:3300/0,v1:10.102.247.49:6789/0]}, election epoch 722, leader 0 b, quorum 0,1,2 b,n,p
```

***Dmesg output***
```shell
[45567.875725] Key type ceph registered
[45567.878545] libceph: loaded (mon/osd proto 15/24)
[45567.885258] FS-Cache: Netfs 'ceph' registered for caching
[45567.885263] ceph: loaded (mds proto 32)
[45567.903786] libceph: mon0 (1)10.102.28.116:6789 session established
[45567.904552] libceph: mon0 (1)10.102.28.116:6789 socket closed (con state OPEN)
[45567.904566] libceph: mon0 (1)10.102.28.116:6789 session lost, hunting for new mon
[45567.908889] libceph: mon1 (1)10.102.28.116:6789 session established
[45567.909875] libceph: client7984614 fsid 5d44c1b2-3fa7-42a1-827b-c4fb1b4a8e76
[46597.917058] libceph: mon2 (1)10.102.247.49:6789 session established
[46597.918225] libceph: mon2 (1)10.102.247.49:6789 socket closed (con state OPEN)
[46597.918236] libceph: mon2 (1)10.102.247.49:6789 session lost, hunting for new mon
[46597.921514] libceph: mon1 (1)10.102.28.116:6789 session established
```

**Expected behavior:**
Mounting a CephFS filesystem on a Linux server should happen quickly and not result in a `mount error 5 = Input/output error` or show failures in `dmesg`. It should also succeed if the session has been established correctly.

**How to reproduce it (minimal and precise):**

Create CephFS

```yaml
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: cephfs-test
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    deviceClass: ssd
    replicated:
      size: 3
  dataPools:
    - erasureCoded:
        dataChunks: 2
        codingChunks: 2
      failureDomain: host
      deviceClass: hdd
  metadataServer:
    activeCount: 1
    activeStandby: true
    placement:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - rook-ceph-mds
            # topologyKey: kubernetes.io/hostname will place MDS across different hosts
            topologyKey: kubernetes.io/hostname
  preserveFilesystemOnDelete: true
```

Download latest `ceph-common`

```shell
wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
sudo apt-add-repository 'deb https://download.ceph.com/debian-pacific/ focal main'
sudo apt install ceph-common
```

Attempt to mount CephFS

```shell
sudo mount -t ceph 10.102.28.116:6789,10.101.151.140:6789,10.102.247.49:6789:/ /cephfs -o name=aaa,secret=xxxx
```

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
* Kernel (e.g. `uname -a`):
Linux k8s-mon 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
4 Intel NUC in a bare metal cluster running Calico for IPAM and BGP
* Rook version (use `rook version` inside of a Rook Pod):
rook-version=v1.6.2
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 16.2.4 (3cbe25cde3cfa028984618ad32de9edc4c1eaed0) pacific (stable)
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
  cluster:
    id:     5d44c1b2-3fa7-42a1-827b-c4fb1b4a8e76
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum b,n,p (age 5h)
    mgr: a(active, since 5h)
    mds: 1/1 daemons up, 1 hot standby
    osd: 12 osds: 12 up (since 5h), 12 in (since 10w)

  data:
    volumes: 1/1 healthy
    pools:   6 pools, 161 pgs
    objects: 172.61k objects, 670 GiB
    usage:   1.4 TiB used, 32 TiB / 34 TiB avail
    pgs:     161 active+clean

  io:
    client:   1.2 KiB/s rd, 57 KiB/s wr, 2 op/s rd, 5 op/s wr
