### ISSUE TITLE
CephObjectStore with zone specified throws unmarshal json errors

### ISSUE THREAD

**Issue by walkamongus** [rook/rook#8052]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When creating a CephObjectStore with spec.zone.name set (after declaring a CephObjectRealm, CephObjectZoneGroup, and CephObjectZone), multiple errors are thrown around parsing/unmarshaling json. The object store is never successfully created.

**Expected behavior:**
Object store is created and joined to multisite zone

**How to reproduce it (minimal and precise):**

Deploy the following in correct order:

```
---
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: myrealm
  namespace: rook-ceph
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: zg1
  namespace: rook-ceph
spec:
  realm: myrealm
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: z1
  namespace: rook-ceph
spec:
  zoneGroup: zg1
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: osd
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: test
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  zone:
    name: z1
  preservePoolsOnDelete: true
  gateway:
    port: 80
    instances: 1
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
```
ceph-object-controller: failed to reconcile failed to create object store deployments: failed to configure multisite for object store: failed join ceph multisite in zone "z1": failed to parse zone id: failed to unmarshal json: invalid character '2' after top-level value
```

```
ceph-object-controller: failed to reconcile failed to create object store deployments: failed to configure multisite for object store: failed join ceph multisite in zone "z1": failed to create realm system user "myrealm-system-user" for reason: <huge string of RGWRados::pool_iterate output>
```

```
ceph-object-controller: failed to reconcile failed to create object store deployments: failed to configure multisite for object store: failed join ceph multisite in zone "z1": failed to parse zonegroup get json: failed to unmarshal json: invalid character '2' after top-level value
```

```
ceph-object-controller: failed to reconcile failed to create object store deployments: failed to configure multisite for object store: failed join ceph multisite in zone "z1": failed to find out whether zone group "zg1" in is the master zone group: failed to parse master zone id: failed to unmarshal json: invalid character '2' after top-level value
```

```
ceph-object-controller: failed to reconcile failed to create object store deployments: failed to configure multisite for object store: failed to parse zones list: failed to unmarshal json: invalid character '2' after top-level value
```

**Environment**:
* OS (e.g. from /etc/os-release): RHEL 7.9
* Kernel (e.g. `uname -a`): 3.10.0-1160.25.1.el7.x86_64
* Cloud provider or hardware configuration: 
* Rook version (use `rook version` inside of a Rook Pod): v1.6.2
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.2
* Kubernetes version (use `kubectl version`): 1.20.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): vanilla
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK
