### ISSUE TITLE
Use a more common pattern to parse the ceph --version output. 

### ISSUE THREAD

**Issue by sp98** [rook/rook#8100]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Use a more common pattern to extract `ceph --version` output

**What is use case behind this feature:**
`ceph --version` output looks like : `ceph version 14.2.11-139 (5c0dc966af809fd1d429ec7bac48962a746af243) nautilus (stable)` 

Rook has three regex patterns to parse the `ceph --version` output. 
`versionPattern`  --> matches `14.2.11` from above output.
`buildVersionPattern` ---> matches  `14.2.11-139` from above output
`commitIDPattern` ---> matches `5c0dc966af809fd1d429ec7bac48962a746af243` from above output

It would be good to use a more common pattern to parse the ceph version. 

So `commitIDPattern` and `versionPattern` can be used as one. 

But this would also cause issues in places where we extract the ceph version from the `CephCluster` status because that does not contain the commit ID. For example:
```
...
 message: Cluster created successfully
  phase: Ready
  state: Created
  storage:
    deviceClasses:
    - name: hdd
  version:
    image: ceph/ceph:v16.2.4
    version: 16.2.4-0
```

For example, [while creating pool,](https://github.com/rook/rook/blob/e17fa5be51efb176166ab8aad2dbec3c40909942/pkg/operator/ceph/pool/controller.go#L245) we check the ceph version from cephCluster status. 

Possible Solution(s):
1. Update `cephCluster` status to use `commitID` as well. For example:
```
message: Cluster created successfully
  phase: Ready
  state: Created
  storage:
    deviceClasses:
    - name: hdd
  version:
    image: ceph/ceph:v16.2.4
    version: 16.2.4-0
    commitID: 5c0dc966af809fd1d429ec7bac48962a746af243
```
   
**Environment**:
