### ISSUE TITLE
ceph-mon volumeclaims  are of type Filesystem

### ISSUE THREAD

**Issue by robvanmieghem** [rook/rook#8113]
* Bug Report

**Deviation from expected behavior:**
Using a Persistent volume with volumemode: Block
The ceph-mon persistent volume claim keeps in state pending ( it does not bind), which is logical since the volumemode is FileSystem

**Expected behavior:**
The pvc for the ceph mon is bound

**How to reproduce it (minimal and precise):**
helm install --namespace rook-ceph rook-ceph rook-release/rook-ceph
Create a PV with volumeMode Block:
```yaml
spec:
  capacity:
    storage: 1700Gi
  hostPath:
    path: /dev/sda
    type: BlockDevice
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Block
status:
  phase: Available
```

cluster defintion:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.13
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
    port: 8443
    ssl: false
  monitoring:
    enabled: true
    rulesNamespace: "rook-ceph"
  mon:
    #set to 3 for production
    count: 1
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: local-storage
        resources:
          requests:
            storage: 100Gi
  storage:
    storageClassDeviceSets:
      - name: set1
        #set to 3 for propduction
        count: 1
        portable: false
        encrypted: false
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 100Gi
              # IMPORTANT: Change the storage class depending on your environment (e.g. local-storage, gp2)
              storageClassName: local-storage
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
```

**Environment**:
* Ubuntu 20.04.2:
* Rook version : rook/ceph:v1.6.4
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version:v1.20.1
