### ISSUE TITLE
v1.6: CephCluster is now merging/appending OSD placements instead of overwriting, making OSDs unscheduleable

### ISSUE THREAD

**Issue by sfynx** [rook/rook#8135]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In v1.5 of the operator it was possible to override the `all` placement settings for a different service, for example this configuraton will put all services on nodes with a `system` role, except for the mons which will get placed on nodes with a `storage` role:

```
spec:
  placement:
    all:
      nodeAffinity:
        # Restrict to system nodes
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - system
    mon:
      nodeAffinity:
        # Restrict to storage nodes
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - storage
```

This works because the `matchExpressions` part gets overwritten, leaving only one:
```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: role
                operator: In
                values:
                  - storage
```

However in v1.6 something has changed, causing them to get merged like this:

```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: role
                operator: In
                values:
                  - system
              - key: role
                operator: In
                values:
                  - storage
```
This will cause the workload to become unscheduleable as it requires two different values to be present for the same key.

**Expected behavior:**
Not sure, because you could make a case for both strategies. As already discussed with @travisn in Slack, perhaps we could keep the new behavior and allow users to switch to the old behavior using a CR option, e.g. `mergeAllPlacement: true | false` (default `true`).

**How to reproduce it (minimal and precise):**

1. Create node label affinity for `all` placement, override it for the same label for another service (e.g. `mon`).
2. Upgrade operator from v1.5 to v1.6 

**Environment**:
* OS (e.g. from /etc/os-release): GKE, COS image
* Cloud provider or hardware configuration: Google (GKE)
* Rook version (use `rook version` inside of a Rook Pod): 1.6.4
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.13
* Kubernetes version (use `kubectl version`): 1.19
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE
