### ISSUE TITLE
Feature request: add support for ingress resources for dashboard to helm chart.

### ISSUE THREAD

**Issue by jhoblitt** [rook/rook#8188]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Follow the defacto standard for managing ingress resources via a chart for the dashboard.  There is an in tree example of an ingress resource: https://github.com/rook/rook/blob/master/Documentation/ceph-dashboard.md

Note that on my clusters, I need slightly different annotations:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
spec:
  tls:
   - hosts:
     - rook-ceph.example.org
     secretName: tls-rook-ceph-ingress
  rules:
  - host: rook-ceph.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rook-ceph-mgr-dashboard
            port:
              name: https-dashboard
```

**What is use case behind this feature:**

To allow the chart to stand up an accessible dashboard without manual intervention.
