### ISSUE TITLE
document how to mount CephNFS/ganesha exports into a pod

### ISSUE THREAD

**Issue by jhoblitt** [rook/rook#8232]
It seems that the nfs driver as used via a pod spec inline ephemeral volume, does name resolution via the host and not through the k8s clusters internal name resolution.  At least this is true for rke.  Search engine results suggest this is true for most k8s distros but possibly not the case with gke.  In any event, this pod spec will fail:

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: cephnfs-demo
  labels:
    app: cephnfs-demo
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
      volumeMounts:
        - name: foo
          mountPath: /data/foo
  volumes:
    - name: foo
      nfs:
        path: /foo
        server: rook-ceph-nfs-foo-a.rook-ceph.svc.cluster.local
```
It took me several hours to figure out a satisfactory way of making this work.  I settled on creating my own svc for the NFS exports with type loadbalancer and setting up an external DNS record.

The options I identified that could make this work are:

* The svc IP needs to be hardcoded
* The nfs CSI driver can be used but not with the inline ephemeral syntax. See: https://github.com/kubernetes-csi/csi-driver-nfs/issues/211 
* Use an svc with type loadbalancer and create an externally resolvable DNS record
* [Maybe] modify the nfs driver to use k8s internal name resolution...

I think this requires enough effort to sort out that a solution should be provided in the example documentation.
