### ISSUE TITLE
parameter to control CephNFS svc type

### ISSUE THREAD

**Issue by jhoblitt** [rook/rook#8234]
I am manually creating a `type: loadbalancer` svc for `CephNFS` server instances in order to allow for access to NFS export external to k8s.  E.g.:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-ceph-nfs
    ceph_daemon_type: nfs
    ceph_nfs: jhome
    rook_cluster: rook-ceph
  name: rook-ceph-nfs-jhome
  namespace: rook-ceph
spec:
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
    targetPort: 2049
  selector:
    app: rook-ceph-nfs
    ceph_daemon_type: nfs
    ceph_nfs: jhome
    rook_cluster: rook-ceph
  type: LoadBalancer
```

I would be convenient if it was possible to make an externally accessible export with a parameter on the `CephNFS` CRD.

Related to #8232 #8233
