### ISSUE TITLE
rook-ceph-cluster chart toolbox.enabled causes template error if cephClusterSpec.network.provider is not set

### ISSUE THREAD

**Issue by jhoblitt** [rook/rook#8251]
I am testing the version of `rook-ceph-cluster` currently published in the `rook-master` repo. Which is showing as version `0`.

I was able to sucessfully create clusters by migrating over my existing cephCluster.spec.  However, when I add the following block into the yaml:

```yaml
toolbox:
  enabled: true
  image: "rook/ceph:v1.6.6"
  tolerations:
    - key: "node.kubernetes.io/unreachable"
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 5
    - key: role
      operator: Equal
      value: storage-node
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
                - storage-node
```
I get this error from helm as `cephClusterSpec.network.provider` is undefined in my helm override values and is also not set in the charts default `vaules.yaml`.

```
Error: UPGRADE FAILED: template: rook-ceph-cluster/templates/deployment.yaml:19:25: executing "rook-ceph-cluster/templates/deployment.yaml" at <.Values.cephClusterSpec.network.provider>: nil pointer evaluating interface {}.provider
```

https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph-cluster/templates/deployment.yaml#L20

Is the intent that `cephClusterSpec.network.provider` is mandatory? It is unset on my `CehCluster` resource and things seem to be working.

```bash
-bash-4.2$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```
