### ISSUE TITLE
Mon failover: post mon failover, wrong mon mappings updated in mon-endpoints configmap and secret 

### ISSUE THREAD

**Issue by sharafcmr** [rook/rook#8277]
**Is this a bug report or feature request?**
* Bug Report
We had three mons in a cluster(a,b & c), due to some issue operator detected mon-b as down  and failover by scaling down mon-b pod and creating mon-d. Post failover a,c & d are the mons running in cluster. However the rook-ceph-mon-endpoints config map and rook-ceph-config secret was showing 4 mons in the map as below.
configMap
```
3604211@3604211-60546 ceph % cat rook-ceph-mon-endpoints
apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"rook-ceph","monitors":["172.11.210.231:6789","172.11.210.203:6789","172.11.210.235:6789","172.11.210.203:6789"]}]'
  data: d=172.11.210.203:6789,a=172.11.210.231:6789,b=172.11.210.203:6789,c=172.11.210.235:6789
  mapping: '{"node":{"a":{"Name":"csi-test-worker-v8","Hostname":"csi-test-worker-v8","Address":"172.11.210.231"},"b":{"Name":"csi-test-worker-v9","Hostname":"csi-test-worker-v9","Address":"172.11.210.203"},"c":{"Name":"csi-test-worker-v12","Hostname":"csi-test-worker-v12","Address":"172.11.210.235"},"d":{"Name":"csi-test-worker-v9","Hostname":"csi-test-worker-v9","Address":"172.11.210.203"}}}'
  maxMonId: "3"
```
rook-ceph-config Secret output decoded:
```
mon_host: [v2:172.11.210.231:3300,v1:172.11.210.231:6789],[v2:172.11.210.203:3300,v1:172.11.210.203:6789],[v2:172.11.210.235:3300,v1:172.11.210.235:6789],[v2:172.11.210.203:3300,v1:172.11.210.203:6789
mon_initial_members: a,b,c,d
```
Output of ceph mon stat shows only three in the map:
```
[root@rook-ceph-tools-7b96766574-4f2h6 /]# ceph mon stat
e4: 3 mons at {a=[v2:172.11.210.231:3300/0,v1:172.11.210.231:6789/0],c=[v2:172.11.210.235:3300/0,v1:172.11.210.235:6789/0],d=[v2:172.11.210.203:3300/0,v1:172.11.210.203:6789/0]}, election epoch 938, leader 0 a, quorum 0,1,2 a,c,d

```
**Impact**
Post failover any  rbd mirror or osd pods  restarted were getting in to crash loopback off with the below exception. Similar error were noticed in the cephcluster status  as well. Cluster reconciliation was getting failed
```
2021-07-07 14:41:34.307166 I | ceph-spec: ceph-block-pool-controller: CephCluster "rook-ceph" found but skipping reconcile since ceph health is &{Health:HEALTH_ERR Details:map[error:{Severity:Urgent Message:failed to get status. . /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.2/rpm/el8/BUILD/ceph-16.2.2/src/mon/MonMap.h: In function 'void MonMap::add(const mon_info_t&)' thread 7f8512904700 time 2021-07-07T14:27:00.239705+0000
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.2/rpm/el8/BUILD/ceph-16.2.2/src/mon/MonMap.h: 221: FAILED ceph_assert(addr_mons.count(a) == 0)
 ceph version 16.2.2 (e8f22dde28889481f4dda2beb8a07788204821d3) pacific (stable)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x158) [0x7f85189ae59c]
 2: /usr/lib64/ceph/libceph-common.so.2(+0x2767b6) [0x7f85189ae7b6]
 3: (MonMap::add(mon_info_t const&)+0x78) [0x7f8518d61438]
 4: (MonMap::add(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, entity_addrvec_t const&, unsigned short, unsigned short)+0x15a) [0x7f8518d6169a]
 5: (MonMap::init_with_addrs(std::vector<entity_addrvec_t, std::allocator<entity_addrvec_t> > const&, bool, std::basic_string_view<char, std::char_traits<char> >)+0x9b) [0x7f8518d5c1bb]
 6: (MonMap::init_with_ips(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::basic_string_view<char, std::char_traits<char> >)+0x94) [0x7f8518d5c404]
 7: (MonMap::build_initial(ceph::common::CephContext*, bool, std::ostream&)+0x676) [0x7f8518d5e786]
 8: (MonClient::build_initial_monmap()+0x140) [0x7f8518d3e9d0]
 9: (MonClient::get_monmap_and_config()+0x62) [0x7f8518d48a62]
 10: /lib64/librados.so.2(+0xb92a8) [0x7f85216c32a8]
 11: rados_connect()
 12: /usr/lib64/python3.6/site-packages/rados.cpython-36m-x86_64-linux-gnu.so(+0xcda2c) [0x7f8521a84a2c]
 13: /usr/lib64/python3.6/site-packages/rados.cpython-36m-x86_64-linux-gnu.so(+0x3332c) [0x7f85219ea32c]
 14: _PyObject_FastCallDict()
 15: /lib64/libpython3.6m.so.1.0(+0x10dc70) [0x7f85248d1c70]

```
**Deviation from expected behavior:**
The mon mapping in the configmap and secret is(shows four mon entries) not matching with the actual mon map in the cluster

**Expected behavior:**
Any ceph daemons(ceph-osd pods, cephrbdmirro pods..etc) restart triggered by end user should not get stuck  as long as the mons are having quorum. Even if a mon failover happens it should not have any impact on the lifecycle of other ceph damons or pods.
Mon map should be consistent across all resources where it is referred
**How to reproduce it (minimal and precise):**
- Deploy ceph cluster with three mons (a,b,c)
- Deploy a cephrbdmirror
- Trigger a mon failover for one of the mons so that a new mon d gets started
- Post failover try deleting/restarting rbdmirror pod or any of the osd pods
- Check the output of "ceph mon stats" and verify the configmap and secret

**Work around**
- Scale down the operator to 0
- Update the rook-ceph-config secret and rook-ceph-mon-endpoints config map
- Delete the pod which is in crashloopbackoff state
-
**Environment**:
* Cloud provider or hardware configuration: vmWare
* Rook version : v1.6.5
* Storage backend version: Ceph 15.2.13
* Kubernetes version :v1.20.6
* Kubernetes cluster type: rancher
