### ISSUE TITLE
Using the same cephfs PVC twice in spec.volumes causes mount timeout

### ISSUE THREAD

**Issue by tibbe** [rook/rook#8284]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Using the same cephfs PVC twice in `spec.volumes` on a single pod causing mounting to fail (timeout).

**Expected behavior:**
It should be possible to use the same cephfs  PVC twice in `spec.volumes` on a single pod.

**How to reproduce it (minimal and precise):**

Use the same cephfs, as per the example ceph fs config in this repo, PVC twice in the `spec.volumes` section.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  ...
  template:
    metadata:
      labels:
        app: kube-plex
        release: kube-plex
    spec:
      ...
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: plex/data
        - name: config
          mountPath: /config
          subPath: plex/config
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: "cephfs-pvc"
      - name: config
        persistentVolumeClaim:
          claimName: "cephfs-pvc"
```

Changing this to only have 1 entry in `volumes` (e.g. `data`) that's referred to twice in `volumeMounts` works.

The PVC is RWX:

```
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cephfs-pvc   Bound    pvc-965fdfaa-c19b-4379-aaf1-1e46acf6bb3e   50Gi       RWX            rook-cephfs    34h
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.2 LTS (Focal Fossa)
* Kernel (e.g. `uname -a`): Linux pi0 5.4.0-1038-raspi # 41-Ubuntu SMP PREEMPT Thu Jun 17 14:14:11 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.6.4
go: go1.16.3
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 16.2.2 (e8f22dde28889481f4dda2beb8a07788204821d3) pacific (stable)
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7+k3s1", GitCommit:"aa768cbdabdb44c95c5c1d9562ea7f5ded073bc0", GitTreeState:"clean", BuildDate:"2021-05-20T00:57:15Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/arm64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_WARN mons are allowing insecure global_id reclaim; 15 daemons have recently crashed
