### ISSUE TITLE
Unable to create cluster CEPH

### ISSUE THREAD

**Issue by putianhui** [rook/rook#8314]
```
E0714 05:46:59.968563       6 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167: Failed to watch *v1.CephCluster: failed to list *v1.CephCluster: v1.CephClusterList.Items: []v1.CephCluster: v1.CephCluster.Spec: v1.ClusterSpec.Storage: v1.StorageScopeSpec.Config: ReadString: expects " or n, but found [, error found in #10 byte of ...|{"nodes":[{"devices"|..., bigger context ...|pgradeChecks":false,"storage":{"config":{"nodes":[{"devices":[{"name":"vdb"},{"name":"vdc"}],"name":|...
```

cluster.yaml
```
operatorNamespace: rook-ceph
toolbox:
  enabled: false
  image: rrook/ceph:v1.6.7
  tolerations: []
  affinity: {}

monitoring:
  enabled: false
  rulesNamespaceOverride:

cephClusterSpec:
  cephVersion:
    image: ceph/ceph:v16.2.4
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  waitTimeoutForHealthyOSDInMinutes: 10
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    ssl: false
    prot: 7000
  #network:
  # enable host networking
  #provider: host
  # EXPERIMENTAL: enable the Multus network provider
  #provider: multus
  #selectors:
  # The selector keys are required to be `public` and `cluster`.
  # Based on the configuration, the operator will do the following:
  #   1. if only the `public` selector key is specified both public_network and cluster_network Ceph settings will listen on that interface
  #   2. if both `public` and `cluster` selector keys are specified the first one will point to 'public_network' flag and the second one to 'cluster_network'
  #
  # In order to work, each selector value must match a NetworkAttachmentDefinition object in Multus
  #
  #public: public-conf --> NetworkAttachmentDefinition object name in Multus
  #cluster: cluster-conf --> NetworkAttachmentDefinition object name in Multus
  # Provide internet protocol version. IPv6, IPv4 or empty string are valid options. Empty string would mean IPv4
  #ipFamily: "IPv6"
  # Ceph daemons to listen on both IPv4 and Ipv6 networks
  #dualStack: false
  # enable the crash collector for ceph daemon crash collection
  crashCollector:
    disable: false
  cleanupPolicy:
    confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
    allowUninstallWithVolumes: false
  removeOSDsIfOutAndSafeToRemove: false
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    #deviceFilter:
    config:
    # crushRoot: "custom-root" # specify a non-default root label for the CRUSH map
    # metadataDevice: "md0" # specify a non-rotational storage so ceph-volume will use it as block db device of bluestore.
    # databaseSizeMB: "1024" # uncomment if the disks are smaller than 100 GB
    # journalSizeMB: "1024"  # uncomment if the disks are 20 GB or smaller
    # osdsPerDevice: "1" # this value can be overridden at the node or device level
    # encryptedDevice: "true" # the default value for this option is "false"
      nodes:
      - name: "cn-zhangjiakou.172.16.1.113"
        devices: # specific devices to use for storage can be specified for each node
        - name: "vdb"
        - name: "vdc" # multiple osds can be created on high performance devices
  #        config:
  #          osdsPerDevice: "5"
  #      - name: "/dev/disk/by-id/ata-ST4000DM004-XXXX" # devices can be specified using full udev paths
  #      config: # configuration can be specified at the node level which overrides the cluster level config
  #    - name: "172.17.4.301"
  #      deviceFilter: "^sd."
  # The section for configuring management of daemon disruptions during upgrade or fencing.
      - name: "cn-zhangjiakou.172.16.1.114"
        devices:
        - name: "vdb"
        - name: "vdc"
      - name: "cn-zhangjiakou.172.16.1.115"
        devices:
        - name: "vdb"
        - name: "vdc"
  disruptionManagement:
    # If true, the operator will create and manage PodDisruptionBudgets for OSD, Mon, RGW, and MDS daemons. OSD PDBs are managed dynamically
    # via the strategy outlined in the [design](https://github.com/rook/rook/blob/master/design/ceph/ceph-managed-disruptionbudgets.md). The operator will
    # block eviction of OSDs by default and unblock them safely when drains are detected.
    managePodBudgets: true
    # A duration in minutes that determines how long an entire failureDomain like `region/zone/host` will be held in `noout` (in addition to the
    # default DOWN/OUT interval) when it is draining. This is only relevant when  `managePodBudgets` is `true`. The default value is `30` minutes.
    osdMaintenanceTimeout: 30
    # A duration in minutes that the operator will wait for the placement groups to become healthy (active+clean) after a drain was completed and OSDs came back up.
    # Operator will continue with the next drain if the timeout exceeds. It only works if `managePodBudgets` is `true`.
    # No values or 0 means that the operator will wait until the placement groups are healthy before unblocking the next drain.
    pgHealthCheckTimeout: 0
    # If true, the operator will create and manage MachineDisruptionBudgets to ensure OSDs are only fenced when the cluster is healthy.
    # Only available on OpenShift.
    manageMachineDisruptionBudgets: false
    # Namespace in which to watch for the MachineDisruptionBudgets.
    machineDisruptionBudgetNamespace: openshift-machine-api

  # healthChecks
  # Valid values for daemons are 'mon', 'osd', 'status'
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    # Change pod liveness probe, it works for all mon,mgr,osd daemons
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
```

Use the following node configuration to succeed

```
storage: # cluster level storage configuration and selection
  useAllNodes: true
  useAllDevices: true
```

**Comment by putianhui** [comment]
I want to create a cluster by specifying datanode and device of datanode

However, once specified, it cannot be created successfully

Use all nodes and all devices to create successfully

```
storage: # cluster level storage configuration and selection
  useAllNodes: true
  useAllDevices: true
```

**Comment by travisn** [comment]
From the error it appears you have a yaml format error. It's possible you have `nodes` indented too far.

**Comment by putianhui** [comment]
> 从错误看来，你有一个 yaml 格式错误。您可能`nodes`缩进得太远了。

您好，nodes配置段是和config配置段对齐吗？
是否像下面一样？
```
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    #deviceFilter:
    config:
    # crushRoot: "custom-root" # specify a non-default root label for the CRUSH map
    # metadataDevice: "md0" # specify a non-rotational storage so ceph-volume will use it as block db device of bluestore.
    # databaseSizeMB: "1024" # uncomment if the disks are smaller than 100 GB
    # journalSizeMB: "1024"  # uncomment if the disks are 20 GB or smaller
    # osdsPerDevice: "1" # this value can be overridden at the node or device level
    # encryptedDevice: "true" # the default value for this option is "false"
    nodes:
      - name: "cn-zhangjiakou.172.16.1.113"
        devices: # specific devices to use for storage can be specified for each node
        - name: "vdb"
        - name: "vdc" # multiple osds can be created on high performance devices
  #        config:
  #          osdsPerDevice: "5"
  #      - name: "/dev/disk/by-id/ata-ST4000DM004-XXXX" # devices can be specified using full udev paths
  #      config: # configuration can be specified at the node level which overrides the cluster level config
  #    - name: "172.17.4.301"
  #      deviceFilter: "^sd."
  # The section for configuring management of daemon disruptions during upgrade or fencing.
      - name: "cn-zhangjiakou.172.16.1.114"
        devices:
        - name: "vdb"
        - name: "vdc"
      - name: "cn-zhangjiakou.172.16.1.115"
        devices:
        - name: "vdb"
        - name: "vdc"
```
