### ISSUE TITLE
Creation of PVC stayes in pending (failed to provision volume with StorageClass...)

### ISSUE THREAD

**Issue by lweberru** [rook/rook#8315]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
creating of a pvc fails. PVC stays in state Pending with error message:
failed to provision volume with StorageClass "nfs-premium-perf4": nfsservers.nfs.rook.io "rook-nfs" not found

```
kubectl describe --namespace wordpress pvc wp-pv-claim
Name:          wp-pv-claim
Namespace:     wordpress
StorageClass:  nfs-premium-perf4
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: nfs.rook.io/rook-nfs-provisioner
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                   From                                                                              Message
  ----     ------                ----                  ----                                                                              -------
  Normal   Provisioning          14m (x11 over 95m)    nfs.rook.io/rook-nfs-provisioner_rook-nfs-0_72e7a42e-b955-4f7c-b517-f477d6f50974  External provisioner is provisioning volume for claim "wordpress/wp-pv-claim"
  Warning  ProvisioningFailed    14m (x11 over 95m)    nfs.rook.io/rook-nfs-provisioner_rook-nfs-0_72e7a42e-b955-4f7c-b517-f477d6f50974  failed to provision volume with StorageClass "nfs-premium-perf4": nfsservers.nfs.rook.io "rook-nfs" not found
  Normal   ExternalProvisioning  116s (x301 over 76m)  persistentvolume-controller                                                       waiting for a volume to be created, either by external provisioner "nfs.rook.io/rook-nfs-provisioner" or manually created by system administrator
```

**Expected behavior:**
pvc is getting created without error message.

**How to reproduce it (minimal and precise):**

skipping nfs-common.yaml, nfs-operator.yaml nfs-psp.yaml and nfs-rbac.yaml as they are just applied with default values.

nfs-server.yaml:
```
---
# A storage class with name premium-perf0-stackit must be present.
# The storage class must be has xfs filesystem type  and prjquota mountOptions.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: premium-perf4-volume
  namespace: rook-nfs
spec:
  storageClassName: "premium-perf4-stackit"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: rook-nfs
  namespace: rook-nfs
spec:
  replicas: 1
  exports:
  - name: premium-perf4-share
    server:
      accessMode: ReadWrite
      squash: "none"
    # A Persistent Volume Claim must be created before creating NFS CRD instance.
    persistentVolumeClaim:
      claimName: premium-perf4-volume
  # A key/value list of annotations
  annotations:
    rook: nfs
```
nfs-storageclass.yaml:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: rook-nfs
  name: nfs-premium-perf4
parameters:
  exportName: premium-perf4-share
  nfsServerName: rook-nfs
  nfsServerNamespace: root-nfs
provisioner: nfs.rook.io/rook-nfs-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
shared-volume.yaml:
```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-pv-claim
  namespace: wordpress
spec:
  storageClassName: "nfs-premium-perf4"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```

install with:
```
kubectl apply -f nfs-common.yaml --wait=true
kubectl apply -f nfs-operator.yaml --wait=true
kubectl apply -f nfs-psp.yaml --wait=true
kubectl apply -f nfs-rbac.yaml --wait=true
kubectl apply -f nfs-server.yaml --wait=true
kubectl apply -f nfs-storageclass.yaml --wait=true
kubectl apply -f shared-volume.yaml --wait=true
```

**File(s) to submit**:

all pods are not showing any errors (logs are empty). All other components are in a fine and running state

```
kubectl get all --namespace rook-nfs-system
NAME                                     READY   STATUS    RESTARTS   AGE
pod/rook-nfs-operator-5cc679885d-xttw5   1/1     Running   0          39m

NAME                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rook-nfs-operator   1/1     1            1           39m

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/rook-nfs-operator-5cc679885d   1         1         1       39m
```
```
kubectl get all --namespace rook-nfs
NAME             READY   STATUS    RESTARTS   AGE
pod/rook-nfs-0   2/2     Running   1          38m

NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)            AGE
service/rook-nfs   ClusterIP   100.68.68.145   <none>        2049/TCP,111/TCP   38m

NAME                        READY   AGE
statefulset.apps/rook-nfs   1/1     38m
```
```
kubectl get storageclasses
NAME                              PROVISIONER                        RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
nfs-premium-perf4                 nfs.rook.io/rook-nfs-provisioner   Delete          Immediate           false                  41m
premium-perf0-stackit (default)   cinder.csi.openstack.org           Delete          Immediate           true                   128d
premium-perf1-stackit             cinder.csi.openstack.org           Delete          Immediate           true                   128d
premium-perf2-stackit             cinder.csi.openstack.org           Delete          Immediate           true                   128d
premium-perf4-stackit             cinder.csi.openstack.org           Delete          Immediate           true                   128d
premium-perf6-stackit             cinder.csi.openstack.org           Delete          Immediate           true                   128d
```

```
kubectl get pv
NAME                                                                 CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM                           STORAGECLASS            REASON   AGE
pv-shoot--48djmrpipp--lukas-2-15883ab1-2e45-4890-9ea3-2d03d667f751   100Gi      RWO            Delete           Bound         rook-nfs/premium-perf4-volume   premium-perf4-stackit            124m
```

```
kubectl get pvc -A
NAMESPACE   NAME                   STATUS    VOLUME                                                               CAPACITY   ACCESS MODES   STORAGECLASS            AGE
rook-nfs    premium-perf4-volume   Bound     pv-shoot--48djmrpipp--lukas-2-15883ab1-2e45-4890-9ea3-2d03d667f751   100Gi      RWO            premium-perf4-stackit   125m
wordpress   wp-pv-claim            Pending                                                                                                  nfs-premium-perf4       115m
```

**Environment**:
* running within kubernetes version: v1.19.2
* kubernetes cluster type: ske (gardener based on STACKIT)
* cloud provider is csi with openstack cinder as storage backend
* Rook version: rook: v1.6.7 / go: go1.16.3
