### ISSUE TITLE
rook-ceph-osd pod crashes after kubernetes node reboot when setting encryptedDevice to true 

### ISSUE THREAD

**Issue by younesehb** [rook/rook#8498]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When deploying rook-ceph chart and the ceph-cluster configuration with the encryptedDevice set to true, the osd pods are created correctly and the partition is correctly encrypted. After rebooting one of the kubernetes worker nodes the linked osd fails to startup. 

 ! Deploying rook-ceph without encryption works fine even when rebooting multiple times. !

**Expected behavior:**
The osd pod should run and the osd should successfully join the ceph cluster after a kubernetes node reboot.

**How to reproduce it (minimal and precise):**
Set the encryption to true in the ceph cluster CRD configuration and reboot a kubernetes worker node. 

**File(s) to submit**:

osd error log: 
rook-ceph-osd-0-7df67f6f4f-59snr
```bash
debug 2021-08-05T15:05:21.377+0000 7f6288ecaf00 -1 bluefs _check_new_allocations invalid extent 1: 0x668e10000~400000: wasn't given but allocated for ino 1
debug 2021-08-05T15:05:21.377+0000 7f6288ecaf00 -1 bluefs mount failed to replay log: (14) Bad address
debug 2021-08-05T15:05:21.377+0000 7f6288ecaf00 -1 bluestore(/var/lib/ceph/osd/ceph-1) _open_bluefs failed bluefs mount: (14) Bad address
debug 2021-08-05T15:05:21.377+0000 7f6288ecaf00 1 bdev(0x559822b68000 /var/lib/ceph/osd/ceph-1/block) close
debug 2021-08-05T15:05:21.657+0000 7f6288ecaf00 -1 osd.1 0 OSD:init: unable to mount object store
debug 2021-08-05T15:05:21.657+0000 7f6288ecaf00 -1 ** ERROR: osd init failed: (14) Bad address
```

cluster.yaml with encryptedDevice enabled:

```yaml
kind: CephCluster
apiVersion: ceph.rook.io/v1
metadata:
  finalizers:
    - cephcluster.ceph.rook.io
  generation: 4
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: 'ceph/ceph:v15.2'
  cleanupPolicy:
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  crashCollector:
    disable: false
  dashboard:
    enabled: true
    ssl: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    osdMaintenanceTimeout: 30
  external:
    enable: false
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 60s
      status:
        interval: 60s
    livenessProbe:
      mgr: {}
      mon: {}
      osd: {}
  logCollector: {}
  mgr:
    modules:
      - enabled: true
        name: pg_autoscaler
  mon:
    count: 3
  monitoring:
    rulesNamespace: rook-ceph
  network:
    hostNetwork: false
    provider: ''
    selectors: null
  removeOSDsIfOutAndSafeToRemove: true
  security:
    kms: {}
  storage:
    config:
      encryptedDevice: 'true'
    storageClassDeviceSets: null
    useAllDevices: true
    useAllNodes: true

```

**Encryption**
```
root@worker1:/var/lib/rook/rook-ceph/log# lsblk
NAME                                                                                                   MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
loop0                                                                                                    7:0    0 32.3M  1 loop  /snap/snapd/12704
loop1                                                                                                    7:1    0 70.4M  1 loop  /snap/lxd/19647
loop2                                                                                                    7:2    0 32.3M  1 loop  /snap/snapd/11588
loop3                                                                                                    7:3    0 55.5M  1 loop  /snap/core18/1997
loop4                                                                                                    7:4    0 55.5M  1 loop  /snap/core18/2074
loop5                                                                                                    7:5    0 70.3M  1 loop  /snap/lxd/21029
vda                                                                                                    252:0    0  100G  0 disk  
├─vda1                                                                                                 252:1    0 46.5G  0 part  /
├─vda2                                                                                                 252:2    0 53.4G  0 part  
│ └─ceph--26b414eb--3b04--44ee--885e--23efc5dce573-osd--data--3ebd4cb4--6db1--48ec--b53e--e34129c67b2f 253:0    0 53.4G  0 lvm   
│   └─SBuujF-F7M0-TP4Q-JTrR-V4t6-Ut4M-P8TX2e                                                           253:1    0 53.4G  0 crypt 
├─vda14                                                                                                252:14   0    4M  0 part  
└─vda15                                                                                                252:15   0  106M  0 part  /boot/efi
root@worker1:/var/lib/rook/rook-ceph/log#

```
**Environment**:
* OS: Linux Ubuntu 20.04 LTS 64-bit
* Kernel: 5.4.0-80-generic
* Rook version: v1.5.5
* Ceph version: v15.2.7
* Kubernetes version : v1.21.3
* Kubernetes type: Kubespray
