### ISSUE TITLE
ceph: Number of ProvisionerReplicas should be picked up on the basis of nodeSelector in K8s cluster

### ISSUE THREAD

**Issue by deekshaaneja** [rook/rook#8535]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
If Node Selector has only 1 node, then 1 replica should be created for Provisioner

**How to reproduce it (minimal and precise):**
This is related to ceph

This is related to issue:#6443

1. Create a 2 worker setup
2. label a worker  with Label="ceph-sa"
`kubectl label node <worker-name> node=ceph-sa`
3. try to install operator with defined NodeAffinity
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node
                operator: In
                values:
                - ceph-sa
```
4. Intention is to create only 1 replica of provisioner. So number of nodes for provisioner should be picked up by checking Node Selector rather than just number of nodes.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
