### ISSUE TITLE
Failed to update cephcluster from 1.5.7 to 1.6.8 due to CRD change

### ISSUE THREAD

**Issue by yan636** [rook/rook#8550]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The deployed cephcluster in v1.5.7 is upgraded to 1.6.8. After the rook operator image update ( w/o cephcluster image change), the operator prints beow error message continuously.
```
2021-08-17 15:15:30.929409 E | ceph-spec: failed to update cluster condition to {Type:Ready Status:True Reason:ClusterCreated Message:Cluster created successfully LastHeartbeatTime:2021-08-17 15:15:30.909571077 +0000 UTC m=+3062.783021420 LastTransitionTime:2021-08-17 14:16:29 +0000 UTC}. failed to update object "rook-ceph" status: CephCluster.ceph.rook.io "rook-ceph" is invalid: spec.storage.devices.config: Invalid value: "null": spec.storage.devices.config in body must be of type object: "null"
```
**Expected behavior:**
The above change seems related to the cephclusters CRD change. In v1.5.7, the " spec.storage.devices.config" has "nullable: true" but in v1.6.8, the above item is removed. 

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```
spec:
  cephVersion:
    image: csf-docker-delivered.repo.lab.pl.alcatel-lucent.com/ceph/ceph:v15.2.8-20201217
  cleanupPolicy:
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  continueUpgradeAfterChecksEvenIfNotHealthy: true
  crashCollector:
    disable: true
  dashboard:
    enabled: true
    port: 8443
    ssl: true
  dataDirHostPath: /data0/rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    osdMaintenanceTimeout: 30
  external:
    enable: false
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 60s
      status:
        interval: 60s
    livenessProbe:
      mgr: {}
      mon: {}
      osd: {}
  logCollector:
    periodicity: 24h
  mgr:
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    count: 3
  monitoring:
    rulesNamespace: rook-ceph
  network:
    hostNetwork: false
    ipFamily: IPv4
    provider: ""
    selectors: null
  placement:
    all:
      tolerations:
      - effect: NoExecute
        key: is_control
        operator: Equal
        value: "true"
  removeOSDsIfOutAndSafeToRemove: false
  resources:
    mgr: {}
    mon: {}
    osd: {}
  security:
    kms: {}
  skipUpgradeChecks: true
  storage:
    config:
      metadataDevice: ""
      osdsPerDevice: "1"
      storeType: bluestore
    devices:
    - config: null
      name: vdd
    storageClassDeviceSets: null
    useAllDevices: false
    useAllNodes: true
  waitTimeoutForHealthyOSDInMinutes: 10

```
* Operator's logs, if [necessary]
[operator.storage.config.null.log](https://github.com/rook/rook/files/7001191/operator.storage.config.null.log)

* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): centos7
* Kernel (e.g. `uname -a`): 4.18.0-193.19.1.2009211817.el7_8.emrs.altmvl.x86_64 
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):  15.2.8
* Kubernetes version (use `kubectl version`): v1.19.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Tectonic
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
