### ISSUE TITLE
Helm: Error converting YAML to JSON when storageClass.enabled:true

### ISSUE THREAD

**Issue by cjprinse** [rook/rook#8559]
* Bug Report

**Deviation from expected behavior:**
Error: YAML parse error on rook-ceph-cluster/templates/cephblockpool.yaml: error converting YAML to JSON: yaml: line 12: could not find expected ':'

**Expected behavior:**
To install the helm chart with storageClass

**How to reproduce it (minimal and precise):**
Helm Values:
```yaml
--- 
cephBlockPools: 
  - 
    name: hdd-data
    spec: 
      deviceClass: hdd-data
      failureDomain: host
      replicated: 
        size: 2
    storageClass: 
      allowVolumeExpansion: true
      enabled: true
      isDefault: false
      name: hdd-data
      reclaimPolicy: Delete
cephClusterSpec: 
  cephVersion: 
    image: "quay.io/ceph/ceph:v16.2.5"
  dashboard: 
    enabled: true
    port: 8080
    ssl: false
  dataDirHostPath: /var/lib/rook/ceph-alpha
  mgr: 
    count: 2
    modules: 
      - 
        enabled: true
        name: pg_autoscaler
  mon: 
    allowMultiplePerNode: true
    count: 3
  placement: 
    mon: 
      nodeAffinity: 
        preferredDuringSchedulingIgnoredDuringExecution: 
          - 
            preference: 
              matchExpressions: 
                - 
                  key: node-role.kubernetes.io/master
                  operator: Exists
            weight: 5
      tolerations: 
        - 
          effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
  storage: 
    config: 
      databaseSizeMB: "1024"
      metadataDevice: ~
    deviceFilter: ~
    nodes: 
      - 
        config: ~
        devices: 
          - 
            name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi10
          - 
            name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi11
        name: kubernetes-worker-01
      - 
        devices: 
          - 
            name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi10
          - 
            name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi11
        name: kubernetes-worker-02
    useAllDevices: false
    useAllNodes: false
clusterName: ceph-alpha
ingress: 
  dashboard: 
    annotations: 
      kubernetes.io/ingress.class: haproxy
    host: 
      name: some.host.path
      path: /
toolbox: 
  enabled: true
```
helm template-f=/values.yml rook-ceph-cluster rook/rook-ceph-cluster --dry-run

**File(s) to submit**:
See above for helm yaml

**Environment**:
* OS (e.g. from /etc/os-release):
* NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Armbian 21.05.4 Focal"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

* Kernel (e.g. `uname -a`):  Linux kubernetes-master-01 5.10.43-meson64 #21.05.4 SMP PREEMPT Wed Jun 16 08:12:48 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

* Cloud provider or hardware configuration: NaN
* Rook version (use `rook version` inside of a Rook Pod): 1.7.1
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable)
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:40:09Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/arm64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): BareMetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
@cjprinse It seems to be a yaml formatting issue in your values.yaml instead of in the helm chart. Try removing the blank lines after the dash. For example, instead of this:
```
--- 
cephBlockPools: 
  - 
    name: hdd-data
```

Set this:
```yaml
--- 
cephBlockPools: 
  - name: hdd-data
```
