### ISSUE TITLE
ceph mgr dashboard sso with saml2 behind istio gateway

### ISSUE THREAD

**Issue by tareqhs** [rook/rook#8633]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Ceph dashboard shows this error when configured behind an istio gateway:

> {"is_authenticated": false, "errors": ["invalid_response"], "reason": "The response was received at http://myhostname/auth/saml2 instead of https://myhostname/auth/saml2"}

**Expected behavior:**

Ceph dashboard works being in-cluster reverse proxy.

**How to reproduce it (minimal and precise):**

Configure SAML via the toolbox:
```
ceph dashboard sso setup saml2 https://myhostname https://myidp/saml2/metadata
```
Verify that SSO is enabled
```
$ ceph dashboard sso status
SSO is "enabled" with "SAML2" protocol.
```
Add required trust in my idp
```
 login endpoint: https://myhost/auth/saml2
logout endpoint: https://myhost/auth/saml2/logout
```
Add istio VirtualService:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rook-ceph-dashboard
  namespace: rook-ceph
spec:
  gateways:
  - mygateway
  hosts:
  - myhost
  http:
  - route:
    - destination:
        host: rook-ceph-mgr-dashboard
        port:
          number: 7000
```
Then launch dashboard in browser.  Th following happens:
1. land at dashboard home, landing page with ceph logo shows up correctly
2. SSO flow engages and redirect to idp saml sso endpoint correct
3. redirect back to dashboard `https://myhost/auth/saml2` fails the dashboard shows a blank page with this text:
> {"is_authenticated": false, "errors": ["invalid_response"], "reason": "The response was received at http://myhostname/auth/saml2 instead of https://myhostname/auth/saml2"}

as it seems the TLS termination in the reverse proxy causes the dashboard to think it is being addressed incorrectly
