### ISSUE TITLE
Helm Chart not creating provisioner secrets

### ISSUE THREAD

**Issue by samuel-butcher** [rook/rook#8640]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Secrets
```rook-csi-cephfs-provisioner```
```rook-csi-rbd-provisioner```
are not created when the rook-ceph helm chart is run

**Expected behavior:**
Secrets
```rook-csi-cephfs-provisioner```
```rook-csi-rbd-provisioner```
are created when the rook-ceph helm chart is run

**How to reproduce it (minimal and precise):**

On a machine controlling a single-node kubernetes cluster:
```helm install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph```
```helm install --create-namespace --namespace rook-ceph rook-ceph-cluster --set operatorNamespace=rook-ceph rook-release/rook-ceph-cluster -f values-override.yaml```
where the contents of values-override.yaml are based on https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster-test.yaml and are as follows:
```
configOverride: |
  [global]
  osd_pool_default_size = 1
  mon_warn_on_pool_no_redundancy = false
  bdev_flock_retry = 20
  bluefs_buffered_io = false
cephClusterSpec:
  dataDirHostPath: /var/lib/rook
  cephVersion:
    image: quay.io/ceph/ceph:v16
    allowUnsupported: true
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  crashCollector:
    disable: true
  storage:
    useAllNodes: true
    useAllDevices: true
    #deviceFilter:
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
        timeout: 600s
  disruptionManagement:
    managePodBudgets: true
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
* Kernel (e.g. `uname -a`): Linux 3.10.0-1127.el7.x86_64
* Cloud provider or hardware configuration: Openstack
* Rook version (use `rook version` inside of a Rook Pod): 1.71
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable)
* Kubernetes version (use `kubectl version`): 
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): Unresponsive when running `ceph health`
