### ISSUE TITLE
Improve SecurityContextConstraints rules

### ISSUE THREAD

**Issue by leseb** [rook/rook#8713]
Looking at our current `scc.yaml`, I feel like we could do better and restrict further some of the permissions.
I won't look for the ceph-csi one as I don't have enough rationale.

Taking the SCC:

```yaml
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: rook-ceph
allowPrivilegedContainer: true
allowHostNetwork: true # should we have a special file when host networking will be enabled?
allowHostDirVolumePlugin: true # is it for Flex?
priority:
allowedCapabilities: []
allowHostPorts: true # is for host networking? then same question, should we have a special file when host networking will be enabled?
allowHostPID: true # this is gone soon in Nautilus removal PR
allowHostIPC: true# should we have a special file when cluster wide encryption will be enabled?
readOnlyRootFilesystem: false
requiredDropCapabilities: []
defaultAddCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
allowedFlexVolumes: # Why is flex needed if we have ceph-csi, especially on OCP
  - driver: "ceph.rook.io/rook"
  - driver: "ceph.rook.io/rook-ceph"
volumes:
  - configMap
  - downwardAPI # Does anyone know why?
  - emptyDir
  - flexVolume # Why is flex needed if we have ceph-csi, especially on OCP
  - hostPath
  - persistentVolumeClaim
  - projected
  - secret
users:
  - system:serviceaccount:rook-ceph:rook-ceph-system
  - system:serviceaccount:rook-ceph:default
  - system:serviceaccount:rook-ceph:rook-ceph-mgr # WHY?
  - system:serviceaccount:rook-ceph:rook-ceph-osd
```

I'm leaving comments.

@BlaineEXE @travisn opening the discussion.

**Comment by BlaineEXE** [comment]
I  believe `downwardAPI` allows us to create deployments/pods/etc. that reference POD_NAME, NODE_NAME, POD_MEMORY_LIMIT, etc. in env vars.

As for FlexVolume, I think we can remove it.

Don't we need `hostDirVolume` for `dataDirHostPath` and other `hostPath` volumes?

`system:serviceaccount:rook-ceph:rook-ceph-mgr` I'm not so sure about. But we do have a `rook-ceph-mgr` serviceaccount, and I wonder if removing this would break that?

I do think it is worth it to always keep the minimal permissions possible. (Aside: even outside of SCC, I think we could do some cleanup regarding permissions when host networking is used, though that would be easier to do with Helm charts.) It would be nice if we could have a base file (this file) and an add-on file for when we need host networking permissions, but I'm not sure that's possible.

We could use composable service accounts to optionally give (or remove) some permissions from the `rook-ceph-mgr` serviceaccount if we want to disable the rook mgr module in OCS, if we want to consider that.

**Comment by travisn** [comment]
> We could use composable service accounts to optionally give (or remove) some permissions from the rook-ceph-mgr serviceaccount if we want to disable the rook mgr module in OCS, if we want to consider that

Agreed, having minimal privs for the mgr would really be good for when the rook mgr module is not enabled. That's where most of the privs for the mgr service account come from.

**Comment by BlaineEXE** [comment]
Somewhat related, PodSecurityPolicies are deprecated in K8s v1.21 and may be removed by k8s v1.25 (https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/). There is a replacement KEP (in alpha in v1.22) https://github.com/kubernetes/enhancements/issues/2579. Beta is targeted for v1.23.

**Comment by Madhu-1** [comment]
```diff
diff --git a/cluster/examples/kubernetes/ceph/operator-openshift.yaml b/cluster/examples/kubernetes/ceph/operator-openshift.yaml
index 930554d0f..47c0da86b 100644
--- a/cluster/examples/kubernetes/ceph/operator-openshift.yaml
+++ b/cluster/examples/kubernetes/ceph/operator-openshift.yaml
@@ -55,17 +55,23 @@ kind: SecurityContextConstraints
 apiVersion: security.openshift.io/v1
 metadata:
   name: rook-ceph-csi
+# To allow running privilegedContainers
 allowPrivilegedContainer: true
+# CSI daemonset pod needs hostnetworking
 allowHostNetwork: true
+# This need to be set to true as we use HostPath
 allowHostDirVolumePlugin: true
 priority:
-allowedCapabilities: ["*"]
+# SYS_ADMIN is needed for rbd to execture rbd map command
+allowedCapabilities: ["SYS_ADMIN"]
+# Needed as we run liveness container on daemonset pods
 allowHostPorts: true
+# Needed as we are setting this in RBD plugin pod
 allowHostPID: true
-allowHostIPC: true
+# Set to false as we write to RootFilesystem inside csi containers
 readOnlyRootFilesystem: false
-requiredDropCapabilities: []
-defaultAddCapabilities: []
 runAsUser:
   type: RunAsAny
 seLinuxContext:
@@ -74,10 +80,12 @@ fsGroup:
   type: RunAsAny
 supplementalGroups:
   type: RunAsAny
-allowedFlexVolumes:
-  - driver: "ceph.rook.io/rook"
-  - driver: "ceph.rook.io/rook-ceph"
-volumes: ["*"]
+# The type of volumes which are mounted to csi pods
+volumes:
+  - configMap
+  - projected
+  - emptyDir
+  - hostPath
```

## New CSI SCC

```yaml
# scc for the CSI driver
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: rook-ceph-csi
# To allow running privilegedContainers
allowPrivilegedContainer: true
# CSI daemonset pod needs hostnetworking
allowHostNetwork: true
# This need to be set to true as we use HostPath
allowHostDirVolumePlugin: true
priority:
# SYS_ADMIN is needed for rbd to execture rbd map command
allowedCapabilities: ["SYS_ADMIN"]
# Needed as we run liveness container on daemonset pods
allowHostPorts: true
# Needed as we are setting this in RBD plugin pod
allowHostPID: true
# Set to false as we write to RootFilesystem inside csi containers
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
# The type of volumes which are mounted to csi pods
volumes:
  - configMap
  - projected
  - emptyDir
  - hostPath
users:
  # A user needs to be added for each rook service account.
  # This assumes running in the default sample "rook-ceph" namespace.
  # If other namespaces or service accounts are configured, they need to be updated here.
  - system:serviceaccount:rook-ceph:rook-csi-rbd-plugin-sa # serviceaccount:namespace:operator
  - system:serviceaccount:rook-ceph:rook-csi-rbd-provisioner-sa # serviceaccount:namespace:operator
  - system:serviceaccount:rook-ceph:rook-csi-cephfs-plugin-sa # serviceaccount:namespace:operator
  - system:serviceaccount:rook-ceph:rook-csi-cephfs-provisioner-sa # serviceaccount:namespace:operator
```
Added diff for the CSI pods and this is the minimum SCC required for CSI pods

cc @obnoxxx
