### ISSUE TITLE
Selecting db/data devices by size without driveGroups

### ISSUE THREAD

**Issue by stuartpb** [rook/rook#8724]
I was just checking the [1.6 release notes](https://blog.rook.io/rook-v1-6-storage-enhancements-2d5144c21b6a) after moving to update my cluster configuration, and I found that the `driveGroups` configuration is no longer supported. The [issue that deprecated driveGroups](https://github.com/rook/rook/issues/7275) said "We will make it clear in documentation how to transition from using Drive Groups to using storage", but [that documentation](https://rook.io/docs/rook/v1.6/ceph-upgrade.html#migrate-the-drive-group-spec) does not address this aspect. I'm trying to understand how to recreate this configuration that I had, within the parameters of the `storage` field:

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v16.2.5
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  monitoring:
    enabled: true
  mon:
    count: 3
    allowMultiplePerNode: true
  driveGroups:
  - name: storberry
    spec:
      db_devices:
        size: ':128G'
      data_devices:
        size: '1T:'
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: st8s.testtrack4.com/storage-group
              operator: In
              values:
              - storberry
```
