### ISSUE TITLE
OSD-level resources configuration for host-based cluster

### ISSUE THREAD

**Issue by dungdm93** [rook/rook#8752]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
OSD-level resources configuration for host-based cluster

**What is use case behind this feature:**
My existing host-based rook-ceph cluster has mixed SSDs and HDDs nodes. And now I'd like to config resources for each kind of disk differently.
Currently, rook-ceph only support config resources at host-level:
```yaml
- name: node1
  resources:
    limits:
      cpu: "5"
      memory: "10Gi"
  devices:
  - name: sdb
  - name: sdc
  - name: sdd
``` 
It's would be help if osd-level resources config is supported like:
```yaml
- name: node1
  resources: # default for all OSDs in this node
    limits:
      cpu: "5"
      memory: "10Gi"
  devices:
  - name: sdb
    resources: # add resources requests; limits use host-level configs
      requests:
        cpu: "1"
        memory: "2Gi"
  - name: sdc
    resources:
      limits:
        cpu: "8" # overwrite limits.cpu at host-level config
  - name: sdd # use default values at host-level
```

**Comment by travisn** [comment]
That would be tedious to add resource limits per node or per-device. What about a `osd-ssd` and `osd-hdd` key under the `placement` of the cluster CR? Then:
1. The osd prepare job would discover if a disk is rotational or not
2. If rotational and the `osd-ssd` key is found, apply those limits. Otherwise, apply the `osd` limits.
3. If non-rotational and the `osd-hdd` key is found, apply those limits. Otherwise, apply the `osd` limits.

**Comment by dungdm93** [comment]
Actually, we also have nodes with different resources (because of historical reason). So hard coding `osd-ssd` & `osd-hdd` seem not working.  
@travisn WDYT about `resourcesClass` like this?
```yaml
storage:
  resourcesClass:
  - name: class1
    resources:
      limits:
        cpu: "3"
        memory: "5Gi"
  - name: class2
    resources:
      limits:
        cpu: "6"
        memory: "10Gi"
  nodes:
  - name: node1
    deviceFilter: ^sd[a-h]
    resourcesClass: class1 # apply class1 for all OSD in node1
  - name: node2
    resourcesClass: class1 # class2 is default for OSD in node2
    devices:
    - name: sda
      resourcesClass: class2
    - name: sdb # no resourcesClass, use node-level resourcesClass
```
