### ISSUE TITLE
allow `CephObjectStoreUser` in any namespace

### ISSUE THREAD

**Issue by yanovich** [rook/rook#8792]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

`rook-operator` should be able to create object store users to any namespace. Now it is only possible in the operator's namespace, usually `rook-ceph`.

**What is use case behind this feature:**

```
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: gitlab
  namespace: gitlab
spec:
  store: my-store
  displayName: gitlab s3 user
```

**Environment**:
Now this fails with
```
021-09-22 13:58:19.283528 E | ceph-object-store-user-controller: failed to set object store user "rook-ceph/gitlab" status to "". failed to update object "rook-ceph/gitlab" status: Operation cannot be fulfilled on cephobjectstoreusers.ceph.rook.io "gitlab": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by leseb** [comment]
The displayed error does not match the description of the PR. `ROOK_CURRENT_NAMESPACE_ONLY` is false by default so this should not happen anyway. Did the value change?

**Comment by travisn** [comment]
@yanovich Instead of the cephobjectuser CR, try the OBCs, which create the user in other namespaces. See the [OBC doc](https://rook.github.io/docs/rook/v1.7/ceph-object-bucket-claim.html)

**Comment by yanovich** [comment]
I can create OBCs in the workspace I want, but not the user. CephObjectStoreUser has to be in `rook-ceph` namespace now. Here is the full file:
```
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: git-lfs-bucket
  namespace: gitlab
spec:
  bucketName: git-lfs
  storageClassName: rook-ceph-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-artifacts-bucket
  namespace: gitlab
spec:
  bucketName: gitlab-artifacts
  storageClassName: rook-ceph-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-uploads-bucket
  namespace: gitlab
spec:
  bucketName: gitlab-uploads
  storageClassName: rook-ceph-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-mr-diffs-bucket
  namespace: gitlab
spec:
  bucketName: gitlab-mr-diffs
  storageClassName: rook-ceph-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-terraform-state-bucket
  namespace: gitlab
spec:
  bucketName: gitlab-terraform-state
  storageClassName: rook-ceph-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-dependency-proxy-bucket
  namespace: gitlab
spec:
  bucketName: gitlab-dependency-proxy
  storageClassName: rook-ceph-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-backups-bucket
  namespace: gitlab
spec:
  bucketName: gitlab-backups
  storageClassName: rook-ceph-bucket
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: gitlab
  namespace: rook-ceph
spec:
  store: my-store
  displayName: gitlab s3 user
  quotas:
    maxBuckets: 64
    maxSize: 128G
  capabilities:
    bucket: read, write
```
