### ISSUE TITLE
values.yaml cephClusterSpec.storage.nodes documentation

### ISSUE THREAD

**Issue by wgerlach** [rook/rook#8800]
This looks like a bug in the documentation:
https://github.com/rook/rook/blob/4583a8000172d99e5b4c1744b3b1957ed2b4600d/cluster/charts/rook-ceph-cluster/values.yaml#L254

Should this not rather look like:

```yaml
- name: node1
  - devices:
     - name: "/dev/disk/by-id/ata-ST4000DM004-XXXX" # devices can be specified using full udev paths
  config: # configuration can be specified at the node level which overrides the cluster level config
```

Also I noticed `devices.fullpath` is not documented, but that might be intentional.

**Comment by parth-gr** [comment]
```
    nodes:
      - name: "172.17.4.201"
        devices: # specific devices to use for storage can be specified for each node
          - name: "sdb"
          - name: "nvme01" # multiple osds can be created on high performance devices
            config:
              osdsPerDevice: "5"
          - name: "/dev/disk/by-id/ata-ST4000DM004-XXXX" # devices can be specified using full udev paths
        config: # configuration can be specified at the node level which overrides the cluster level config
      - name: "172.17.4.301"
        deviceFilter: "^sd."
```

The correct indentation is like, verified from types.go[ storageScopeSpec](https://github.com/rook/rook/blob/12506c7918cb770543d5196cbad8af3121ed6130/pkg/apis/ceph.rook.io/v1/types.go#L1945)
