### ISSUE TITLE
Affinity doesn't apply to mds and mgr

### ISSUE THREAD

**Issue by alirezaDavid** [rook/rook#890]
We set `placement` property in rook-cluster.yaml like this:

```
  placement:
   all:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: type
             operator: In
             values:
             - ceph
   api:
     nodeAffinity:
     tolerations:
   mds:
     nodeAffinity:
     tolerations:
   mon:
     nodeAffinity:
     tolerations:
   osd:
     nodeAffinity:
     tolerations:
   rgw:
     nodeAffinity:
     tolerations:
```
Then check all auto generate obbject (api, mgr, mds, osd) like this:
` kubectl -n rook get deployment rook-ceph-mds -o yaml`
` kubectl -n rook get deployment rook-ceph-api -o yaml`
` kubectl -n rook get deployment rook-ceph-mgr0 -o yaml`

for example, `affinity` exists in `rook-ceph-mgr0` object yaml file:
```
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-api
      rook_cluster: rook
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rook-api
        rook_cluster: rook
      name: rook-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - ceph
      containers:
```

But in `mds` and `mgr` objects, `affinity` property, it doesn't exist.

rook version: 0.5
k8s version: 1.6.7
