### ISSUE TITLE
Tolerations in mon pods not being set

### ISSUE THREAD

**Issue by yusanshui** [rook/rook#8946]
**Is this a bug report or feature request?**
* Bug Report
```
# Tolerations for the rook-ceph-operator to allow it to run on nodes with particular taints
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master

csi:
  # The CSI provisioner would be best to start on the same nodes as other ceph daemons. 
  provisionerTolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  # Set pluginTolerations and pluginNodeAffinity for plugin daemonset pods.
  # The CSI plugins need to be started on all the nodes where the clients need to mount the storage.
  pluginTolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  rbdProvisionerTolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  rbdPluginTolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  cephFSProvisionerTolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  cephFSPluginTolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master

## Rook Agent configuration
## toleration: NoSchedule, PreferNoSchedule or NoExecute
## tolerationKey: Set this to the specific key of the taint to tolerate
## tolerations: Array of tolerations in YAML format which will be added to agent deployment
agent:
  toleration: NoSchedule
  tolerationKey: node-role.kubernetes.io/master 
  tolerations:
    - key: node-role.kubernetes.io/master 
      effect: NoSchedule


## Rook Discover configuration
## toleration: NoSchedule, PreferNoSchedule or NoExecute
## tolerationKey: Set this to the specific key of the taint to tolerate
## tolerations: Array of tolerations in YAML format which will be added to agent deployment
## nodeAffinity: Set to labels of the node to match
discover:
  toleration: NoSchedule
  tolerationKey: node-role.kubernetes.io/master
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule

admissionController:
  # Set tolerations and nodeAffinity for admission controller pod.
  # The admission controller would be best to start on the same nodes as other ceph daemons.
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule

```
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph # namespace:cluster
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    # Set the number of mons to be started. Generally recommended to be 3.
    # For highest availability, an odd number of mons should be specified.
    count: 3
    # The mons should be on unique nodes. For production, at least 3 nodes are recommended for this reason.
    # Mons should only be allowed on the same node for test environments where data loss is acceptable.
    allowMultiplePerNode: false
    # A volume claim template can be specified in which case new monitors (and
    # monitors created during fail over) will construct a PVC based on the
    # template for the monitor's primary storage. Changes to the template do not
    # affect existing monitors. Log data is stored on the HostPath under
    # dataDirHostPath. If no storage requirement is specified, a default storage
    # size appropriate for monitor data will be used.
    volumeClaimTemplate:
      spec:
        storageClassName: rook-monitor
        resources:
          requests:
            storage: 500Mi
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.5
    allowUnsupported: false
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mgr:
    count: 1
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    ssl: true
  crashCollector:
    disable: false
  storage:
    storageClassDeviceSets:
      - name: set1
        # The number of OSDs to create from this device set
        count: 3
        # IMPORTANT: If volumes specified by the storageClassName are not portable across nodes
        # this needs to be set to false. For example, if using the local storage provisioner
        # this should be false.
        portable: false
        # Certain storage class in the Cloud are slow
        # Rook can configure the OSD running on PVC to accommodate that by tuning some of the Ceph internal
        # Currently, "gp2" has been identified as such
        tuneDeviceClass: true
        # Certain storage class in the Cloud are fast
        # Rook can configure the OSD running on PVC to accommodate that by tuning some of the Ceph internal
        # Currently, "managed-premium" has been identified as such
        tuneFastDeviceClass: false
        # whether to encrypt the deviceSet or not
        encrypted: false
        # Since the OSDs could end up on any node, an effort needs to be made to spread the OSDs
        # across nodes as much as possible. Unfortunately the pod anti-affinity breaks down
        # as soon as you have more than one OSD per node. The topology spread constraints will
        # give us an even spread on K8s 1.18 or newer.
        placement:
          all:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          mgr:
            nodeAffinity:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          mon:
            nodeAffinity:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          osd:
            nodeAffinity:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd
        preparePlacement:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd-prepare
                  topologyKey: kubernetes.io/hostname
          all:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          mgr:
            nodeAffinity:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          mon:
            nodeAffinity:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          osd:
            nodeAffinity:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          topologySpreadConstraints:
            - maxSkew: 1
              # IMPORTANT: If you don't have zone labels, change this to another key such as kubernetes.io/hostname
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd-prepare
        resources:
        # These are the OSD daemon limits. For OSD prepare limits, see the separate section below for "prepareosd" resources
        #   limits:
        #     cpu: "500m"
        #     memory: "4Gi"
        #   requests:
        #     cpu: "500m"
        #     memory: "4Gi"
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 256Mi
              # IMPORTANT: Change the storage class depending on your environment
              storageClassName: rook-data
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
    onlyApplyOSDPlacement: false
  resources:
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
 ```
```
[root@localhost ~]# ./kubectl -n rook-ceph describe pod rook-ceph-mon-c-canary-678d9d7484-f5g2j 
Name:           rook-ceph-mon-c-canary-678d9d7484-f5g2j
Namespace:      rook-ceph
Priority:       0
Node:           <none>
Labels:         app=rook-ceph-mon
                ceph_daemon_id=c
                ceph_daemon_type=mon
                mon=c
                mon_canary=true
                mon_cluster=rook-ceph
                pod-template-hash=678d9d7484
                pvc_name=rook-ceph-mon-c
                pvc_size=500Mi
                rook_cluster=rook-ceph
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/rook-ceph-mon-c-canary-678d9d7484
Containers:
  mon:
    Image:      rook/ceph:v1.7.3
    Port:       6789/TCP
    Host Port:  0/TCP
    Command:
      /tini
    Args:
      --
      sleep
      3600
    Environment:
      CONTAINER_IMAGE:                quay.io/ceph/ceph:v16.2.5
      POD_NAME:                       rook-ceph-mon-c-canary-678d9d7484-f5g2j (v1:metadata.name)
      POD_NAMESPACE:                  rook-ceph (v1:metadata.namespace)
      NODE_NAME:                       (v1:spec.nodeName)
      POD_MEMORY_LIMIT:               node allocatable (limits.memory)
      POD_MEMORY_REQUEST:             0 (requests.memory)
      POD_CPU_LIMIT:                  node allocatable (limits.cpu)
      POD_CPU_REQUEST:                0 (requests.cpu)
      ROOK_CEPH_MON_HOST:             <set to the key 'mon_host' in secret 'rook-ceph-config'>             Optional: false
      ROOK_CEPH_MON_INITIAL_MEMBERS:  <set to the key 'mon_initial_members' in secret 'rook-ceph-config'>  Optional: false
      ROOK_POD_IP:                     (v1:status.podIP)
    Mounts:
      /etc/ceph from rook-config-override (ro)
      /etc/ceph/keyring-store/ from rook-ceph-mons-keyring (ro)
      /var/lib/ceph/crash from rook-ceph-crash (rw)
      /var/lib/ceph/mon/ceph-c from ceph-daemon-data (rw,path="data")
      /var/log/ceph from rook-ceph-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-g4qwr (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  rook-config-override:
    Type:               Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:      rook-config-override
    ConfigMapOptional:  <nil>
  rook-ceph-mons-keyring:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-mons-keyring
    Optional:    false
  rook-ceph-log:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook/rook-ceph/log
    HostPathType:  
  rook-ceph-crash:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook/rook-ceph/crash
    HostPathType:  
  ceph-daemon-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  rook-ceph-mon-c
    ReadOnly:   false
  kube-api-access-g4qwr:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 5s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  28s   default-scheduler  0/3 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 2 node(s) didn't find available persistent volumes to bind.
```
**Deviation from expected behavior:**
I'm able to schedule mon pod on master with this definition of tolerations 
**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
kind
* OS (e.g. from /etc/os-release):
centos 8
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by yusanshui** [comment]
> @yusanshui ^^^

Thank you very much. But I can not understand how modify my yaml.Like this, is right?It cannot work.
Should I use mon replace component?
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph # namespace:cluster
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    # Set the number of mons to be started. Generally recommended to be 3.
    # For highest availability, an odd number of mons should be specified.
    count: 3
    # The mons should be on unique nodes. For production, at least 3 nodes are recommended for this reason.
    # Mons should only be allowed on the same node for test environments where data loss is acceptable.
    allowMultiplePerNode: false
    # A volume claim template can be specified in which case new monitors (and
    # monitors created during fail over) will construct a PVC based on the
    # template for the monitor's primary storage. Changes to the template do not
    # affect existing monitors. Log data is stored on the HostPath under
    # dataDirHostPath. If no storage requirement is specified, a default storage
    # size appropriate for monitor data will be used.
    volumeClaimTemplate:
      spec:
        storageClassName: rook-monitor
        resources:
          requests:
            storage: 500Mi
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.5
    allowUnsupported: false
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mgr:
    count: 1
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    ssl: true
  crashCollector:
    disable: false
  storage:
    storageClassDeviceSets:
      - name: set1
        # The number of OSDs to create from this device set
        count: 3
        # IMPORTANT: If volumes specified by the storageClassName are not portable across nodes
        # this needs to be set to false. For example, if using the local storage provisioner
        # this should be false.
        portable: false
        # Certain storage class in the Cloud are slow
        # Rook can configure the OSD running on PVC to accommodate that by tuning some of the Ceph internal
        # Currently, "gp2" has been identified as such
        tuneDeviceClass: true
        # Certain storage class in the Cloud are fast
        # Rook can configure the OSD running on PVC to accommodate that by tuning some of the Ceph internal
        # Currently, "managed-premium" has been identified as such
        tuneFastDeviceClass: false
        # whether to encrypt the deviceSet or not
        encrypted: false
        # Since the OSDs could end up on any node, an effort needs to be made to spread the OSDs
        # across nodes as much as possible. Unfortunately the pod anti-affinity breaks down
        # as soon as you have more than one OSD per node. The topology spread constraints will
        # give us an even spread on K8s 1.18 or newer.
        placement:
          all:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          mgr:
            nodeAffinity:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          mon:
            nodeAffinity:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          osd:
            nodeAffinity:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd
        preparePlacement:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd-prepare
                  topologyKey: kubernetes.io/hostname
          all:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          mgr:
            nodeAffinity:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          mon:
            nodeAffinity:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          osd:
            nodeAffinity:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
          topologySpreadConstraints:
            - maxSkew: 1
              # IMPORTANT: If you don't have zone labels, change this to another key such as kubernetes.io/hostname
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd-prepare
        resources:
        # These are the OSD daemon limits. For OSD prepare limits, see the separate section below for "prepareosd" resources
        #   limits:
        #     cpu: "500m"
        #     memory: "4Gi"
        #   requests:
        #     cpu: "500m"
        #     memory: "4Gi"
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 256Mi
              # IMPORTANT: Change the storage class depending on your environment
              storageClassName: rook-data
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
    onlyApplyOSDPlacement: false
  resources:
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
```
I would appreciate if you could help me modify my yaml file~

**Comment by travisn** [comment]
@yusanshui The `placement` is a top-level setting as seen in [this example](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L138). Something like this:

```yaml
spec:
  placement:
    all:
      tolerations:
      - key: node-role.kubernetes.io/master
         effect: NoSchedule
    mgr:
      nodeAffinity:
        tolerations:
         - key: node-role.kubernetes.io/master
            effect: NoSchedule
    mon:
      nodeAffinity:
        tolerations:
        - key: node-role.kubernetes.io/master
           effect: NoSchedule
  storage:
    storageClassDeviceSets:
      - name: set1
         placement:
           nodeAffinity:
             tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
```
