### ISSUE TITLE
failed to reconcile CephObjectStore because system user not found

### ISSUE THREAD

**Issue by olivierbouffet** [rook/rook#9100]
**Is this a bug report or feature request?**
* Bug Report

Hello,

When deploying 2 objectstores in the same rook cluster, rook operator always tries to reconcile the second objectstore

```2021-11-04 13:13:32.081274 I | ceph-object-controller: reconciling object store deployments
2021-11-04 13:13:32.123781 I | ceph-object-controller: Zone "ch-gva-nvme-d3" found in Ceph cluster will include object store "green-s3-d3-nvme"
2021-11-04 13:13:32.139267 I | ceph-object-controller: ceph object store gateway service running at XX.XX.XX.XXX
2021-11-04 13:13:32.139281 I | ceph-object-controller: setting multisite settings for object store "green-s3-d3-nvme"
2021-11-04 13:13:32.486858 I | ceph-object-controller: there are no changes to commit for RGW configuration period for CephObjectStore "rook-ceph/green-s3-d3-nvme"
2021-11-04 13:13:32.486876 I | ceph-object-controller: added object store "green-s3-d3-nvme" to realm "ik-s3-nvme", zonegroup "ch-gva-nvme", zone "ch-gva-nvme-d3"
2021-11-04 13:13:32.652930 E | ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/green-s3-d3-nvme". failed to create object store deployments: failed to configure multisite for object store: failed join ceph multisite in zone "ch-gva-nvme-d3": failed to create realm system user ["ik-s3-nvme-system-user" "could not create user: unable to parse parameters, user: ik-s3-nvme-system-user exists. "] for reason: %!q(MISSING): exit status 17
```

but the user exists 

``` radosgw-admin user info --uid=ik-s3-nvme-system-user --rgw-realm=ik-s3-nvme
{
    "user_id": "ik-s3-nvme-system-user",
    "display_name": "ik-s3-nvme.user",
    "email": "",
    "suspended": 0,
    "max_buckets": 1000,
    "subusers": [],
    "keys": [
        {
            "user": "ik-s3-nvme-system-user",
            "access_key": "xxxxxxxxxxxxxxxx",
            "secret_key": "YYYYYYYYYYYYYYYYYYYYY"
        }
    ],
    "swift_keys": [],
    "caps": [],
    "op_mask": "read, write, delete",
    "system": "true",
    "default_placement": "",
    "default_storage_class": "",
    "placement_tags": [],
    "bucket_quota": {
        "enabled": false,
        "check_on_raw": false,
        "max_size": -1,
        "max_size_kb": 0,
        "max_objects": -1
    },
    "user_quota": {
        "enabled": false,
        "check_on_raw": false,
        "max_size": -1,
        "max_size_kb": 0,
        "max_objects": -1
    },
    "temp_url_keys": [],
    "type": "rgw",
    "mfa_ids": []
}
```

This is probably due to missing `realmArg` at the folowing line
https://github.com/rook/rook/blob/master/pkg/operator/ceph/object/objectstore.go#L494

OS (e.g. from /etc/os-release): debian 10
Kernel (e.g. uname -a): Linux hostname 5.10.0-0.bpo.8-amd64 Monitor bootstrapping with libcephd #1 SMP Debian 5.10.46-4~bpo10+1 (2021-08-07) x86_64 GNU/Linux
Cloud provider or hardware configuration: bare metal
Rook version (use rook version inside of a Rook Pod): v1.7.6
Storage backend version (e.g. for ceph do ceph -v): ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)
Kubernetes version (use kubectl version): v1.21.5

**Comment by BlaineEXE** [comment]
@olivierbouffet thanks for filling in the detailed "Environment" info and looking at the code for a possible root cause. 

Could you provide us with both manifests you are using for the `CephObjectStore`s? Additionally, if you are using any `CephObjectZoneGroup`, `CephObjectZone`, or `CephObjectRealm` resources, please include those as well. We need to be able to repro in order to confirm a fix, and we will likely include a regression test in our CI.

Attaching the output from `kubectl -n rook-ceph describe CephObjectStore` should be sufficient for our needs, and feel free to redact anything sensitive for your organization.

**Comment by olivierbouffet** [comment]
Hello,

Yes I am using all CephObjectZoneGroup, CephObjectZone,  CephObjectRealm. Please find below the 2 objectstores definitions.

01_first_object_realm.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: ik-s3
  namespace: rook-ceph
```
02_first_object_zonegroup.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: ch-gva
  namespace: rook-ceph
spec:
  realm: ik-s3
```
03_first_object_zone.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: ch-gva-d3
  namespace: rook-ceph
spec:
  zoneGroup: ch-gva
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    deviceClass: ssd
    preservePoolsOnDelete: true
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
    deviceClass: ssd
    preservePoolsOnDelete: true
```
04_first_objectstore_multisite.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: green-s3-d3
  namespace: rook-ceph # namespace:cluster
spec:
  gateway:
    port: 80
    # securePort: 443
    instances: 2
    placement:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-rgw
              # topologyKey: */zone can be used to spread RGW across different AZ
              # Use <topologyKey: failure-domain.beta.kubernetes.io/zone> in k8s cluster if your cluster is v1.16 or lower
              # Use <topologyKey: topology.kubernetes.io/zone>  in k8s cluster is v1.17 or upper
              topologyKey: kubernetes.io/hostname
    resources:
    # The requests and limits set here, allow the object store gateway Pod(s) to use half of one CPU core and 1 gigabyte of memory
      limits:
        cpu: "1000m"
        memory: "4096Mi"
      requests:
        cpu: "500m"
        memory: "2048Mi"
    # priorityClassName: my-priority-class
  zone:
    name: ch-gva-d3
  # service endpoint healthcheck
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
    # Configure the pod liveness probe for the rgw daemon
    livenessProbe:
      disabled: false
```
05_second_object_realm.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: ik-s3-nvme
  namespace: rook-ceph
```
06_second_object_zonegroup.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: ch-gva-nvme
  namespace: rook-ceph
spec:
  realm: ik-s3-nvme
```
07_second_object_zone.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: ch-gva-nvme-d3
  namespace: rook-ceph
spec:
  zoneGroup: ch-gva-nvme
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    deviceClass: nvme
    preservePoolsOnDelete: true
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 2
    deviceClass: nvme
    preservePoolsOnDelete: true
```
08_second_objectstore_multisite.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: green-s3-d3-nvme
  namespace: rook-ceph # namespace:cluster
spec:
  gateway:
    port: 80
    # securePort: 443
    instances: 2
    placement:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-rgw
              # topologyKey: */zone can be used to spread RGW across different AZ
              # Use <topologyKey: failure-domain.beta.kubernetes.io/zone> in k8s cluster if your cluster is v1.16 or lower
              # Use <topologyKey: topology.kubernetes.io/zone>  in k8s cluster is v1.17 or upper
              topologyKey: kubernetes.io/hostname
    resources:
    # The requests and limits set here, allow the object store gateway Pod(s) to use half of one CPU core and 1 gigabyte of memory
      limits:
        cpu: "10000m"
        memory: "16384Mi"
      requests:
        cpu: "4000m"
        memory: "4096Mi"
    # priorityClassName: my-priority-class
  zone:
    name: ch-gva-nvme-d3
  # service endpoint healthcheck
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
    # Configure the pod liveness probe for the rgw daemon
    livenessProbe:
      disabled: false
```

```
kubectl -n rook-ceph describe CephObjectStore
Name:         green-s3-d3
Namespace:    rook-ceph
Labels:       ceph_version=16.2.6-0-pacific
Annotations:  API Version:  ceph.rook.io/v1
Kind:         CephObjectStore
Metadata:
  Creation Timestamp:  2021-09-28T07:53:00Z
  Finalizers:
    cephobjectstore.ceph.rook.io
  Generation:  7
  Managed Fields:
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:gateway:
          .:
          f:instances:
          f:placement:
            .:
            f:podAntiAffinity:
              .:
              f:preferredDuringSchedulingIgnoredDuringExecution:
          f:port:
          f:resources:
            .:
            f:limits:
            f:requests:
              .:
              f:cpu:
        f:healthCheck:
          .:
          f:bucket:
          f:livenessProbe:
        f:zone:
          .:
          f:name:
    Manager:      kubectl
    Operation:    Update
    Time:         2021-11-01T15:57:11Z
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"cephobjectstore.ceph.rook.io":
        f:labels:
          .:
          f:ceph_version:
      f:spec:
        f:dataPool:
          .:
          f:compressionMode:
          f:erasureCoded:
            .:
            f:codingChunks:
            f:dataChunks:
          f:mirroring:
          f:quotas:
          f:replicated:
            .:
            f:size:
          f:statusCheck:
            .:
            f:mirror:
        f:gateway:
          f:resources:
            f:limits:
              f:cpu:
              f:memory:
            f:requests:
              f:memory:
        f:healthCheck:
          f:bucket:
            f:interval:
        f:metadataPool:
          .:
          f:compressionMode:
          f:erasureCoded:
            .:
            f:codingChunks:
            f:dataChunks:
          f:mirroring:
          f:quotas:
          f:replicated:
            .:
            f:size:
          f:statusCheck:
            .:
            f:mirror:
      f:status:
        .:
        f:bucketStatus:
          .:
          f:details:
          f:health:
          f:lastChanged:
          f:lastChecked:
        f:info:
          .:
          f:endpoint:
        f:phase:
    Manager:         rook
    Operation:       Update
    Time:            2021-11-02T15:45:17Z
  Resource Version:  21271805
  UID:               cd6a4acc-55c6-431a-8961-f73ea37ea752
Spec:
  Data Pool:
    Compression Mode:  none
    Erasure Coded:
      Coding Chunks:  0
      Data Chunks:    0
    Mirroring:
    Quotas:
    Replicated:
      Size:  0
    Status Check:
      Mirror:
  Gateway:
    Instances:  2
    Placement:
      Pod Anti Affinity:
        Preferred During Scheduling Ignored During Execution:
          Pod Affinity Term:
            Label Selector:
              Match Expressions:
                Key:       app
                Operator:  In
                Values:
                  rook-ceph-rgw
            Topology Key:  kubernetes.io/hostname
          Weight:          100
    Port:                  80
    Resources:
      Limits:
        Cpu:     1
        Memory:  4Gi
      Requests:
        Cpu:     500m
        Memory:  2Gi
  Health Check:
    Bucket:
      Interval:  1m0s
    Liveness Probe:
  Metadata Pool:
    Compression Mode:  none
    Erasure Coded:
      Coding Chunks:  0
      Data Chunks:    0
    Mirroring:
    Quotas:
    Replicated:
      Size:  0
    Status Check:
      Mirror:
  Zone:
    Name:  ch-gva-d3
Status:
  Bucket Status:
    Details:       failed to get details from ceph object user "rook-ceph-internal-s3-user-checker-cd6a4acc-55c6-431a-8961-f73ea37ea752": NoSuchBucket tx00000000000000001e3a0-006184d1ae-7242d3-ch-gva-d3 7242d3-ch-gva-d3-ch-gva
    Health:        Failure
    Last Changed:  2021-11-05T06:39:42Z
    Last Checked:  2021-11-05T06:39:42Z
  Info:
    Endpoint:  http://rook-ceph-rgw-green-s3-d3.rook-ceph.svc:80
  Phase:       Failure
Events:        <none>


Name:         green-s3-d3-nvme
Namespace:    rook-ceph
Labels:       ceph_version=16.2.6-0-pacific
Annotations:  API Version:  ceph.rook.io/v1
Kind:         CephObjectStore
Metadata:
  Creation Timestamp:  2021-11-03T11:49:36Z
  Finalizers:
    cephobjectstore.ceph.rook.io
  Generation:  2
  Managed Fields:
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:gateway:
          .:
          f:instances:
          f:placement:
            .:
            f:podAntiAffinity:
              .:
              f:preferredDuringSchedulingIgnoredDuringExecution:
          f:port:
          f:resources:
            .:
            f:limits:
            f:requests:
        f:healthCheck:
          .:
          f:bucket:
          f:livenessProbe:
        f:zone:
          .:
          f:name:
    Manager:      kubectl
    Operation:    Update
    Time:         2021-11-03T11:49:36Z
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"cephobjectstore.ceph.rook.io":
        f:labels:
          .:
          f:ceph_version:
      f:spec:
        f:dataPool:
          .:
          f:erasureCoded:
            .:
            f:codingChunks:
            f:dataChunks:
          f:mirroring:
          f:quotas:
          f:replicated:
            .:
            f:size:
          f:statusCheck:
            .:
            f:mirror:
        f:gateway:
          f:resources:
            f:limits:
              f:cpu:
              f:memory:
            f:requests:
              f:cpu:
              f:memory:
        f:healthCheck:
          f:bucket:
            f:interval:
        f:metadataPool:
          .:
          f:erasureCoded:
            .:
            f:codingChunks:
            f:dataChunks:
          f:mirroring:
          f:quotas:
          f:replicated:
            .:
            f:size:
          f:statusCheck:
            .:
            f:mirror:
      f:status:
        .:
        f:bucketStatus:
          .:
          f:details:
          f:health:
          f:lastChanged:
          f:lastChecked:
        f:phase:
    Manager:         rook
    Operation:       Update
    Time:            2021-11-04T06:37:38Z
  Resource Version:  21271956
  UID:               b65cfa03-1ef0-4df4-98a9-4ba7241892bb
Spec:
  Data Pool:
    Erasure Coded:
      Coding Chunks:  0
      Data Chunks:    0
    Mirroring:
    Quotas:
    Replicated:
      Size:  0
    Status Check:
      Mirror:
  Gateway:
    Instances:  2
    Placement:
      Pod Anti Affinity:
        Preferred During Scheduling Ignored During Execution:
          Pod Affinity Term:
            Label Selector:
              Match Expressions:
                Key:       app
                Operator:  In
                Values:
                  rook-ceph-rgw
            Topology Key:  kubernetes.io/hostname
          Weight:          100
    Port:                  80
    Resources:
      Limits:
        Cpu:     10
        Memory:  16Gi
      Requests:
        Cpu:     4
        Memory:  4Gi
  Health Check:
    Bucket:
      Interval:  1m0s
    Liveness Probe:
  Metadata Pool:
    Erasure Coded:
      Coding Chunks:  0
      Data Chunks:    0
    Mirroring:
    Quotas:
    Replicated:
      Size:  0
    Status Check:
      Mirror:
  Zone:
    Name:  ch-gva-nvme-d3
Status:
  Bucket Status:
    Details:       failed to get details from ceph object user "rook-ceph-internal-s3-user-checker-b65cfa03-1ef0-4df4-98a9-4ba7241892bb": NoSuchBucket tx000000000000000013f76-006184d1d3-7490a4-ch-gva-nvme-d3 7490a4-ch-gva-nvme-d3-ch-gva-nvme
    Health:        Failure
    Last Changed:  2021-11-05T06:40:19Z
    Last Checked:  2021-11-05T06:40:19Z
  Phase:           Failure
Events:
  Type     Reason           Age                 From                         Message
  ----     ------           ----                ----                         -------
  Warning  ReconcileFailed  29m (x39 over 42h)  rook-ceph-object-controller  failed to create object store deployments: failed to configure multisite for object store: failed join ceph multisite in zone "ch-gva-nvme-d3": failed to create realm system user ["ik-s3-nvme-system-user" "could not create user: unable to parse parameters, user: ik-s3-nvme-system-user exists. "] for reason: %!q(MISSING): exit status 17
```

I have these errors but the objectstores have been provisionned correctly, and are functionnal.

Thanks for your help.
