### ISSUE TITLE
failed to configure devices: failed to generate osd keyring: failed to get or create auth key for client.bootstrap-osd: failed get-or-create-key client.bootstrap-osd:

### ISSUE THREAD

**Issue by Perhurb** [rook/rook#9172]
When I deploy rook-ceph cluster in my kubernetes. I meet an issue I can't solve. I'm not invited in Slack, so I ask questions here and hope someone could help me.

**Environment**:
* OS (CentOS7.8.2003):
* Kernel (5.4.159-1.el7.elrepo.x86_64):
* Rook version (release1.7):
* Kubernetes version (1.19):

I do deploy rook-ceph as what https://www.rook.io/docs/rook/v1.7/quickstart.html tell me to do. But my osd pod failed to stared. OSD Pod is partly not started. When I get logs:
2021-11-15 12:55:47.896793 I | cephosd: skipping device "sda1" because it contains a filesyste
2021-11-15 12:55:47.896798 I | cephosd: skipping device "sda2" because it contains a filesyste
2021-11-15 12:55:47.896805 D | exec: Running command: lsblk /dev/sdb --bytes --nodeps --pairs 
2021-11-15 12:55:47.900831 D | exec: Running command: ceph-volume inventory --format json /dev
2021-11-15 12:55:48.604314 I | cephosd: device "sdb" is available.
2021-11-15 12:55:48.604379 I | cephosd: skipping 'dm' device "dm-0"
2021-11-15 12:55:48.604386 I | cephosd: skipping 'dm' device "dm-1"
2021-11-15 12:55:48.614544 I | cephosd: configuring osd devices: {"Entries":{"sdb":{"Data":-1,DatabaseSizeMB":0,"DeviceClass":"","InitialWeight":"","IsFilter":false,"IsDevicePathFilter":faasChildren":false,"devLinks":"/dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:1:0","size":53687091,"rotational":true,"readOnly":false,"Partitions":null,"filesystem":"","vendor":"VMware_","modepath":"/dev/sdb","kernel-name":"sdb"}}}}
2021-11-15 12:55:48.614632 I | cephclient: getting or creating ceph auth key "client.bootstrap
2021-11-15 12:55:48.614651 D | exec: Running command: ceph auth get-or-create-key client.bootsk-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/
failed to configure devices: failed to generate osd keyring: failed to get or create auth key for client.bootstrap-osd: failed get-or-create-key client.bootstrap-osd: exit status 1

I want to know what happened?  How should I do to configure my device?

**Comment by BlaineEXE** [comment]
This could be an issue with the provisioner not able to connect to the mons. Show us the output from `kubectl -n rook-ceph get cephcluster -o yaml` and from `kubectl -n rook-ceph get pod`.

**Comment by travisn** [comment]
@Perhurb For Slack, try going [here](http://slack.rook.io/) to register.

**Comment by Perhurb** [comment]
> This could be an issue with the provisioner not able to connect to the mons. Show us the output from `kubectl -n rook-ceph get cephcluster -o yaml` and from `kubectl -n rook-ceph get pod`.

When I exec `kubectl -n rook-ceph get pod` and the output is as follow:
```
NAME                                               READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-5pbgf                             3/3     Running     0          14h
csi-cephfsplugin-d6l6h                             3/3     Running     0          14h
csi-cephfsplugin-kz6bw                             3/3     Running     0          14h
csi-cephfsplugin-provisioner-5fb84dfcf8-7xhjx      6/6     Running     0          14h
csi-cephfsplugin-provisioner-5fb84dfcf8-qxpq6      6/6     Running     0          14h
csi-rbdplugin-28z25                                3/3     Running     0          14h
csi-rbdplugin-bt2q5                                3/3     Running     0          14h
csi-rbdplugin-provisioner-bcd8b595b-lbp4q          6/6     Running     0          14h
csi-rbdplugin-provisioner-bcd8b595b-mttg4          6/6     Running     0          14h
csi-rbdplugin-ts77v                                3/3     Running     0          14h
rook-ceph-crashcollector-master-7c797995d7-wdlql   1/1     Running     0          13h
rook-ceph-crashcollector-node1-7cbbffd4b8-v9fg5    1/1     Running     0          14h
rook-ceph-crashcollector-node2-55f65dc8c9-xnwb2    1/1     Running     0          14h
rook-ceph-mgr-a-648bfc946f-n88gs                   1/1     Running     245        14h
rook-ceph-mon-a-5d598d864-7bkxh                    1/1     Running     0          14h
rook-ceph-mon-g-79c9b54b57-ct2kj                   1/1     Running     0          18m
rook-ceph-operator-6866d8fb9b-nshmb                1/1     Running     0          13h
rook-ceph-osd-0-86f9bc497-sfp8l                    1/1     Running     0          14h
rook-ceph-osd-prepare-node1-2rh2s                  0/1     Completed   0          13h
rook-ceph-tools-99779cb98-82vcl                    1/1     Running     0          8m21s
```
The mgr pod always restart and the monitor pod is also restarting periodically. I detect the ceph health using toolbox pod.
```
# kubectl -n rook-ceph exec -it deploy/rook-ceph-tools -- ceph status
  cluster:
    id:     294da5c6-2f18-4795-9975-13eacb3a4106
    health: HEALTH_WARN
            no active mgr
 
  services:
    mon: 1 daemons, quorum a (age 14h)
    mgr: no daemons active
    osd: 1 osds: 1 up (since 14h), 1 in (since 14h)
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     
```
I also watch the cluster status using `kubectl -n rook-ceph get cephcluster -o yaml`
```
status:
    ceph:
      capacity: {}
      details:
        MGR_DOWN:
          message: no active mgr
          severity: HEALTH_WARN
      health: HEALTH_WARN
      lastChecked: "2021-11-16T02:52:51Z"
      versions:
        mon:
          ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable): 1
        osd:
          ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable): 1
        overall:
          ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable): 2
    conditions:
    - lastHeartbeatTime: "2021-11-15T12:58:13Z"
      lastTransitionTime: "2021-11-15T12:58:13Z"
      message: Processing OSD 0 on node "node1"
      reason: ClusterProgressing
      status: "True"
      type: Progressing
    - lastHeartbeatTime: "2021-11-16T02:52:51Z"
      lastTransitionTime: "2021-11-15T12:09:50Z"
      message: Cluster created successfully
      reason: ClusterCreated
      status: "True"
      type: Ready
    message: Cluster created successfully
    phase: Ready
    state: Created
    storage:
      deviceClasses:
      - name: hdd
    version:
      image: quay.io/ceph/ceph:v16.2.6
      version: 16.2.6-0
```
I describe mgr pod:
```
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  Unhealthy  49m (x711 over 14h)    kubelet  Liveness probe failed: admin_socket: exc
  Normal   Pulled     34m (x242 over 14h)    kubelet  Container image "quay.io/ceph/ceph:v16.2
  Warning  BackOff    4m6s (x2983 over 14h)  kubelet  Back-off restarting failed container
```
I read the Ceph Common Issues. And run `rm -rf /var/lib/ceph/` and restart cluster and operator. But it does not run correctly.  All files I use come from github, and I just modify the images. What's wrong and what should I do?
