### ISSUE TITLE
Dashboard unable to start - rook 1.7.7（v16.2.6-20210927)

### ISSUE THREAD

**Issue by skycyan** [rook/rook#9182]
centos 7.9
K8S 1.22.3
rook 1.7.7（quay.io/ceph/ceph:v16.2.6-20210927） 

The port configured in CephCluster cannot be started.
The port configured in CephCluster is 8446, but the port printed in the log turned out to be 8443. Does the configuration fail to take effect?

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  external:
    enable: false
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.6-20210927
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  waitTimeoutForHealthyOSDInMinutes: 10
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 1
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:                                    #### Dashboard 
    enabled: true
    urlPrefix: /ceph-dashboard
    port: 8446
    ssl: true
......
```

```
# kubectl -n rook-ceph logs rook-ceph-mgr-a-66bfc949f5-r9zfw
debug 2021-11-16T07:52:27.557+0000 7f0ca8a61700  0 [dashboard INFO root] server: ssl=yes host=172.66.14.93 port=8443
debug 2021-11-16T07:52:27.557+0000 7f0ca8a61700  0 [dashboard INFO root] Config not ready to serve, waiting: no certificate configured
debug 2021-11-16T07:52:32.558+0000 7f0ca8a61700  0 [dashboard INFO root] server: ssl=yes host=172.66.14.93 port=8443
debug 2021-11-16T07:52:32.558+0000 7f0ca8a61700  0 [dashboard INFO root] Config not ready to serve, waiting: no certificate configured

```

```
Listening port（mgr）
# ss -lnptu
Netid                       State                        Recv-Q                       Send-Q                                             Local Address:Port                                             Peer Address:Port                       Process                       
tcp                         LISTEN                       0                            5                                                   172.66.14.93:9283                                                  0.0.0.0:*                                                        
tcp                         LISTEN                       0                            128                                                 172.66.14.93:6800                                                  0.0.0.0:*                                                        
tcp                         LISTEN                       0                            128                                                 172.66.14.93:6801                                                  0.0.0.0:*
```
.
.
.
.
# Solution（Turn off SSL）：
You need to turn off SSL through the command line because there is a problem with the CephCluster CRD.
```
# ceph config set mgr mgr/dashboard/ssl false
```

**Comment by travisn** [comment]
@skycyan Do you see the port setting in the toolbox? Rook should set this to the port in the cluster CR. Something like this:
```
ceph config get mgr.a mgr/dashboard/server_port
```

Does restarting the mgr pod help?

**Comment by skycyan** [comment]
> @skycyan Do you see the port setting in the toolbox? Rook should set this to the port in the cluster CR. Something like this:
> 
> ```
> ceph config get mgr.a mgr/dashboard/server_port
> ```
> 
> Does restarting the mgr pod help?

# 1.This setting is invalid in mgr (restarting pod(mgr) is useless).
```
  dashboard:                                    #### Dashboard 
    enabled: true
    urlPrefix: /ceph-dashboard
    port: 8443
    ssl: true
```

# 2.The following command does not work（Setting the port does not work. restarting pod(mgr) is useless.）。
```
$ ceph config set mgr mgr/dashboard/server_addr $IP
$ ceph config set mgr mgr/dashboard/server_port $PORT
$ ceph config set mgr mgr/dashboard/ssl_server_port $PORT
```

# 3.【Solution】Only after closing dashboardSSL through the command line, mgr automatically starts port 8443
```
$ ceph config set mgr mgr/dashboard/ssl false
```

# 4. When the CephCluster CRD cannot set the dashboard, this is a bug.  Disabling SSL via the command line is only a temporary solution.

**Comment by travisn** [comment]
@skycyan I was able to see a custom port configured for the dashboard. Here are my steps, though I am not sure what is different in your cluster.

1. Set the cluster CR with the following:
```yaml
  dashboard:
    enabled: true
    port: 8555
    ssl: true
```

2. Waited a few minutes for the setting to be applied by the operator.
3. Queried in the toolbox that the setting was applied:
```
[rook@rook-ceph-tools-555c879675-vdx7q /]$ ceph config get mgr.a mgr/dashboard/server_port
8555
```
4. Verified that the service endpoint was updated:
```
$ kn get svc -l app=rook-ceph-mgr
NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
rook-ceph-mgr             ClusterIP   10.110.133.212   <none>        9283/TCP   23h
rook-ceph-mgr-dashboard   ClusterIP   10.109.204.235   <none>        8555/TCP   23h
```
5. The mgr pod log showed the port:
```
[dashboard INFO root] server: ssl=yes host=0.0.0.0 port=8555
```
6. I could connect to the dashboard.

**Comment by c-yco** [comment]
I can reproduce that dashboard settings are not applied all as they should from the cluster cr: 
```` yaml
     dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
````

In ceph toolbox:
````
[rook@rook-ceph-tools-555c879675-x6vkn /]$ ceph config get mgr.a mgr/dashboard/ssl
true
````
Therefore the dashboard is not available as no cert is configured, but tls is enabled.

My complete helm chart value is here: [https://github.com/c-yco/k3s-homecluster/blob/ee5f4ccced9d2c340d75cc21b0c79d6ded8b54ee/cluster/core/rook-ceph/cluster/helm-release.yaml]

Cluster specs: 
Ubuntu 21.04
K3s
Arm64 on Raspi 4
