### ISSUE TITLE
rgw flags set to storeName even for multisite deployment

### ISSUE THREAD

**Issue by olivierbouffet** [rook/rook#9248]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Hello,

When creating a multisite objectstore the rgw_zone and rgw_zonegroup flags are set to objectstore name instead of zone and zonegroup.

**How to reproduce it (minimal and precise):**
create realm : 
```
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: realm-1
  namespace: rook-ceph
```

create a zonegroup:
```
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: realm-1
  namespace: rook-ceph
root@dockerdev-263:/home/code# cat 05_zg-1.yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: zonegroup-1
  namespace: rook-ceph
spec:
  realm: realm-1
```

create a zone : 
```
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: realm-1
  namespace: rook-ceph
root@dockerdev-263:/home/code# cat 05_zg-1.yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: zonegroup-1
  namespace: rook-ceph
spec:
  realm: realm-1
root@dockerdev-263:/home/code# cat 06_oz-1.yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: zone-1
  namespace: rook-ceph
spec:
  zoneGroup: zonegroup-1
  metadataPool:
    replicated:
      size: 1
      requireSafeReplicaSize: false
    preservePoolsOnDelete: false
  dataPool:
    replicated:
      size: 1
      requireSafeReplicaSize: false
    preservePoolsOnDelete: false
```

create a multisite object store : 
```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: object-multi-1
  namespace: rook-ceph # namespace:cluster
spec:
  gateway:
    port: 80
    # securePort: 443
    instances: 1
  zone:
    name: zone-1
  # service endpoint healthcheck
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
    # Configure the pod liveness probe for the rgw daemon
    livenessProbe:
      disabled: false
```

and then get the ceph config dump : 
```
[root@rook-ceph-tools-5b54fb98c-k5qk9 /]# ceph config dump | grep rgw
    client.rgw.object.multi.1.a        advanced  rgw_enable_usage_log                   true
    client.rgw.object.multi.1.a        advanced  rgw_log_nonexistent_bucket             true
    client.rgw.object.multi.1.a        advanced  rgw_log_object_name_utc                true
    client.rgw.object.multi.1.a        advanced  rgw_zone                               object-multi-1                            *
    client.rgw.object.multi.1.a        advanced  rgw_zonegroup                          object-multi-1                            *
```

**Environment**:
* OS (e.g. from /etc/os-release): debian 10 buster
* Kernel (e.g. `uname -a`): 
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.7.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.6
* Kubernetes version (use `kubectl version`): 
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):
