### ISSUE TITLE
Dashboard: data on object-storage throws error. 

### ISSUE THREAD

**Issue by suneclausen** [rook/rook#9268]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I have applied the Helm charts for rook-ceph and rook-ceph-cluster, respectively. Afterwards I apply yaml for cephObjectStore, cephObjectStoreUser, obc, sc to get object-storage.  It is intentional not to inject values with respect to object storage into the valuefile to the charts as it is desired to get a user and bucket with unique credentials. 

```yaml

apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-store-1
  namespace: rook-ceph
spec:
  dataPool:
    failureDomain: host
    replicated:
      size: 1
  gateway:
    instances: 2
    port: 80
  metadataPool:
    failureDomain: host
    replicated:
      size: 1

--- 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-store-1-storageclass
parameters:
  objectStoreName: my-store-1
  objectStoreNamespace: rook-ceph
  region: us-east-1
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete

--- 
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: my-store-1-user
  namespace: rook-ceph
spec:
  displayName: my-store-1-display-name
  quotas:
    maxBuckets: 100
    maxObjects: 10000
    maxSize: 10G
  store: my-store-1

--- 
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: my-store-1-my-bucket-1
  namespace: rook-ceph
spec:
  additionalConfig:
    maxObjects: "10"
  bucketName: my-bucket-1
  storageClassName: my-store-1-storageclass
```

The dashboard is exposed using a virtualService, with the values to the chart: 
```yaml 
cephClusterSpec:
  dashboard:
    enabled: true
    port: 7000
    ssl: false
```

When entering the dashboard the UI is nicely presented and it shows that it has noticed the 2 rgw-instances configured as expected, but when entering the page about object storage it throws an error in the mgr-log about no route to host at host='192.168.200.11', port=8080 as shown in the logs. This makes the UI say: "Error connecting to Object Gateway. Please consult the documentation on how to configure and enable the Object Gateway management functionality." 

**Expected behavior:**
The dashboard is enabled to work with object storage without throwing errors such that data can be rendered in the dashboard.  

**How to reproduce it (minimal and precise):**

- Have a running ceph-cluster based on chart for version 1.7.8
- Apply the yaml files and wait for RGW pods to start
- Enter the dashboard and click on "Object Gateway" 
- See the error being thrown in the logs for the mgr-pod

**Environment**:
* OS: Centos8
* Rook version: 1.7.8 
* Ceph version: 16.2.6
* Kubernetes version: 1.21.3
* ceph status: 'health_ok'

Logs:
- [mgr-log.txt](https://github.com/rook/rook/files/7618681/mgr-log.txt)
- [operator-log.txt](https://github.com/rook/rook/files/7618700/operator-log.txt)

**Comment by travisn** [comment]
@jmolmo can you take a look?

**Comment by thotz** [comment]
I guess there is an issue with rgw itself, I can see a lot of failures in rook-operator logs wrt admins-ops operations

**Comment by jmolmo** [comment]
After initial analysis it seems that dashboard is not getting the right port for the RGW daemons. The port configured for the RGW daemons is '80', 

```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
...
  gateway:
    instances: 2
    port: 80
```

but the dashboard detect  the daemons using port 8080.

```
debug 2021-11-29T14:06:35.129+0000 7f9298dcd700  0 [dashboard INFO rgw_client] Found RGW daemon with configuration: host=192.168.200.11, port=8080, ssl=False
debug 2021-11-29T14:06:35.129+0000 7f9298dcd700  0 [dashboard INFO rgw_client] Found RGW daemon with configuration: host=192.168.200.11, port=8080, ssl=False
```
I will try to reproduce, but it would be nice to have a little bit more of information about the issue. 

@suneclausen , would you mind to provide the output of the command `ceph mgr services` ?
