### ISSUE TITLE
Can't write to a 2-replica hybrid storage pool when i lose one node

### ISSUE THREAD

**Issue by francesco995** [rook/rook#9298]
I have a 3-node rook cluster with 2 osds each, one ssd and one spinning disk, for a total of 6 osds

my ceph-filesystem is setup like this with the operator

```
- name: ceph-filesystem
        spec:
          metadataPool:
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              parameters:
                min_size: "1"
              replicated:
                size: 2
                hybridStorage:
                  primaryDeviceClass: ssd
                  secondaryDeviceClass: hdd
          metadataServer:
            activeCount: 1
            activeStandby: true
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          reclaimPolicy: Delete
          parameters:
            # The secrets contain Ceph admin credentials.
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            # Specify the filesystem type of the volume. If not specified, csi-provisioner
            # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
            # in hyperconverged settings where the volume is mounted on the same node as the osds.
            csi.storage.k8s.io/fstype: ext4

```

i would expect that losing one node should not impact the cluster operation, instead i can't write to the rdb or the filesystem
i set the min_size to 1 to allow writes to the cluster if 1 of the 2 replicas fail (please note that this is not a production cluster)

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
losing one node prevents writes to the cluster

**Expected behavior:**
if i lose one node, all operations should continue to work

**How to reproduce it (minimal and precise):**

**File(s) to submit**:
version is rook-ceph-v1.7.8

this is my ceph cluster
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  annotations:
    meta.helm.sh/release-name: rook-ceph-cluster
    meta.helm.sh/release-namespace: rook-ceph
  creationTimestamp: "2021-11-08T21:48:34Z"
  finalizers:
  - cephcluster.ceph.rook.io
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: rook-ceph
  namespace: rook-ceph
  resourceVersion: "20950971"
  uid: 631e6ebd-d2ad-4bce-93fa-4bbe55eb343a
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.5
  cleanupPolicy:
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  crashCollector: {}
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  external: {}
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 1m0s
      status:
        interval: 1m0s
    livenessProbe:
      mgr: {}
      mon: {}
      osd: {}
  logCollector: {}
  mgr:
    count: 1
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    count: 3
  monitoring:
    enabled: true
    rulesNamespace: rook-ceph
  network: {}
  security:
    kms: {}
  storage:
    nodes:
    - devices:
      - config:
          deviceClass: hdd
        name: /dev/disk/by-id/scsi-SVMware_Virtual_disk_6000c295fd21a00ebf13e859663b32fc
      - config:
          deviceClass: ssd
        name: /dev/disk/by-id/scsi-SVMware_Virtual_disk_6000c29c65a21ff65a047b88b76511ec
      name: dev01
      resources: {}
    - devices:
      - config:
          deviceClass: hdd
        name: /dev/disk/by-id/scsi-SVMware_Virtual_disk_6000c29c1215beb93ca246cc9c581a71
      - config:
          deviceClass: ssd
        name: /dev/disk/by-id/scsi-SVMware_Virtual_disk_6000c29780b978f39f0a05c9e3a2e5c0
      name: dev02
      resources: {}
    - devices:
      - config:
          deviceClass: hdd
        name: /dev/disk/by-id/scsi-SVMware_Virtual_disk_6000c29ad59cc2f161e270430cf7cc91
      - config:
          deviceClass: ssd
        name: /dev/disk/by-id/scsi-SVMware_Virtual_disk_6000c29c21c16ae507a97051610749a9
      name: dev03
      resources: {}
    useAllDevices: false
  waitTimeoutForHealthyOSDInMinutes: 10
status:
  ceph:
    capacity:
      bytesAvailable: 144666574848
      bytesTotal: 257672871936
      bytesUsed: 113006297088
      lastUpdated: "2021-12-02T17:41:03Z"
    health: HEALTH_OK
    lastChanged: "2021-12-02T17:37:56Z"
    lastChecked: "2021-12-02T17:41:03Z"
    previousHealth: HEALTH_WARN
    versions:
      mds:
        ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable): 2
      mgr:
        ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable): 1
      mon:
        ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable): 3
      osd:
        ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable): 6
      overall:
        ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable): 12
  conditions:
  - lastHeartbeatTime: "2021-12-02T17:41:04Z"
    lastTransitionTime: "2021-11-08T21:52:27Z"
    message: Cluster created successfully
    reason: ClusterCreated
    status: "True"
    type: Ready
  message: Cluster created successfully
  phase: Ready
  state: Created
  storage:
    deviceClasses:
    - name: hdd
    - name: ssd
  version:
    image: quay.io/ceph/ceph:v16.2.5
    version: 16.2.5-0
```

this is my ceph filesystem crd
```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  annotations:
    meta.helm.sh/release-name: rook-ceph-cluster
    meta.helm.sh/release-namespace: rook-ceph
  creationTimestamp: "2021-11-08T21:48:34Z"
  finalizers:
  - cephfilesystem.ceph.rook.io
  generation: 4
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ceph-filesystem
  namespace: rook-ceph
  resourceVersion: "20937676"
  uid: e9364f77-4821-4c99-9a83-4238adbfe785
spec:
  dataPools:
  - failureDomain: host
    parameters:
      min_size: "1"
    replicated:
      hybridStorage:
        primaryDeviceClass: ssd
        secondaryDeviceClass: hdd
      size: 2
  metadataPool:
    erasureCoded:
      codingChunks: 0
      dataChunks: 0
    mirroring: {}
    quotas: {}
    replicated:
      size: 3
    statusCheck:
      mirror: {}
  metadataServer:
    activeCount: 1
    activeStandby: true
    placement: {}
    resources: {}
  statusCheck:
    mirror: {}
status:
  phase: Ready
```

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): NAME="Ubuntu" VERSION="20.04.3 LTS (Focal Fossa)"
* Kernel (e.g. `uname -a`):Linux dev01 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: kubernetes cluster on rke2 
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.7.3
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.5 
* Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6+rke2r1",
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): rke2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
@francesco995 
- Does the ceph pool show that the min_size was applied? For example: `ceph osd pool ls detail`. 
- If you used replica 3 on the pools, do you see the same behavior? Or this only affects clusters with a replica 2 pool?

**Comment by francesco995** [comment]
this is the result of the ls detail command

pool 1 'device_health_metrics' replicated size 3 min_size 2 crush_rule 0 object_hash rjenkins pg_num 1 pgp_num 1 autoscale_mode on last_change 2612 flags hashpspool stripe_width 0 pg_num_min 1 application mgr_devicehealth
pool 2 'ceph-blockpool' replicated size 2 min_size 1 crush_rule 1 object_hash rjenkins pg_num 128 pgp_num 128 autoscale_mode on last_change 2910 lfor 0/0/441 flags hashpspool,selfmanaged_snaps stripe_width 0 application rbd
pool 3 'ceph-filesystem-metadata' replicated size 3 min_size 2 crush_rule 2 object_hash rjenkins pg_num 32 pgp_num 32 autoscale_mode on last_change 2915 flags hashpspool stripe_width 0 pg_autoscale_bias 4 pg_num_min 16 recovery_priority 5 application cephfs
pool 4 'ceph-filesystem-data0' replicated size 2 min_size 1 crush_rule 3 object_hash rjenkins pg_num 32 pgp_num 32 autoscale_mode on last_change 2918 flags hashpspool stripe_width 0 application cephfs

if i drain one node to simulate a failure, this is the new result of the command

pool 1 'device_health_metrics' replicated size 3 min_size 2 crush_rule 0 object_hash rjenkins pg_num 1 pgp_num 1 autoscale_mode on last_change 2612 flags hashpspool stripe_width 0 pg_num_min 1 application mgr_devicehealth
pool 2 'ceph-blockpool' replicated size 2 min_size 1 crush_rule 1 object_hash rjenkins pg_num 59 pgp_num 55 pg_num_target 32 pgp_num_target 32 autoscale_mode on last_change 3432 lfor 0/3425/3423 flags hashpspool,selfmanaged_snaps stripe_width 0 application rbd
pool 3 'ceph-filesystem-metadata' replicated size 3 min_size 2 crush_rule 2 object_hash rjenkins pg_num 32 pgp_num 32 autoscale_mode on last_change 2915 flags hashpspool stripe_width 0 pg_autoscale_bias 4 pg_num_min 16 recovery_priority 5 application cephfs
pool 4 'ceph-filesystem-data0' replicated size 2 min_size 1 crush_rule 3 object_hash rjenkins pg_num 32 pgp_num 32 autoscale_mode on last_change 2918 flags hashpspool stripe_width 0 application cephfs

when one node was unavailable i lost read/write access to all rdb volumes, but i could write to the ceph-filesystem this time

i will try scaling the replica size to 3 for all data nodes

**Comment by francesco995** [comment]
the node that i bring down has 2 osds and one mon. i tried again with 3 replicas and this time i could not write to the block pools or the filesystem

this is the ceph osd pool ls detail output from this time

pool 1 'device_health_metrics' replicated size 3 min_size 2 crush_rule 0 object_hash rjenkins pg_num 1 pgp_num 1 autoscale_mode on last_change 2612 flags hashpspool stripe_width 0 pg_num_min 1 application mgr_devicehealth
pool 2 'ceph-blockpool' replicated size 3 min_size 2 crush_rule 1 object_hash rjenkins pg_num 128 pgp_num 32 pgp_num_target 128 autoscale_mode on last_change 3831 lfor 0/3638/3831 flags hashpspool,selfmanaged_snaps stripe_width 0 application rbd
pool 3 'ceph-filesystem-metadata' replicated size 3 min_size 2 crush_rule 2 object_hash rjenkins pg_num 32 pgp_num 32 autoscale_mode on last_change 3666 flags hashpspool stripe_width 0 pg_autoscale_bias 4 pg_num_min 16 recovery_priority 5 application cephfs
pool 4 'ceph-filesystem-data0' replicated size 3 min_size 2 crush_rule 3 object_hash rjenkins pg_num 32 pgp_num 32 autoscale_mode on last_change 3667 flags hashpspool stripe_width 0 application cephfs


from the ui this is the status of the blockpool, it shows as "updating"

32 active+clean, 1 active+recovery_wait+undersized+degraded+remapped, 81 active+undersized+degraded, 2 active+undersized+degraded+remapped+backfill_wait, 10 undersized+degraded+peered, 1 undersized+degraded+remapped+backfill_wait+peered, 1 undersized+degraded+remapped+backfilling+peered
49.29%

**Comment by travisn** [comment]
Can you confirm the failure domain of the crush rules on the pool? They should be `host` rather than `osd`. The default is `host` so it should be set as such even if you didn't specify `failureDomain: host` on some of the pools in the CRs, but just to double check. The crush dump should show that there is a step with `"type": "host"`.
`
$ ceph osd crush dump
...
                    "op": "chooseleaf_firstn",
                    "num": 0,
                    "type": "host"
...

**Comment by francesco995** [comment]
this is my crush dump, could it be something related to the hybrid storage?

```
{
  "devices": [
    {
      "id": 0,
      "name": "osd.0",
      "class": "hdd"
    },
    {
      "id": 1,
      "name": "osd.1",
      "class": "hdd"
    },
    {
      "id": 2,
      "name": "osd.2",
      "class": "ssd"
    },
    {
      "id": 3,
      "name": "osd.3",
      "class": "ssd"
    },
    {
      "id": 4,
      "name": "osd.4",
      "class": "hdd"
    },
    {
      "id": 5,
      "name": "osd.5",
      "class": "ssd"
    }
  ],
  "types": [
    {
      "type_id": 0,
      "name": "osd"
    },
    {
      "type_id": 1,
      "name": "host"
    },
    {
      "type_id": 2,
      "name": "chassis"
    },
    {
      "type_id": 3,
      "name": "rack"
    },
    {
      "type_id": 4,
      "name": "row"
    },
    {
      "type_id": 5,
      "name": "pdu"
    },
    {
      "type_id": 6,
      "name": "pod"
    },
    {
      "type_id": 7,
      "name": "room"
    },
    {
      "type_id": 8,
      "name": "datacenter"
    },
    {
      "type_id": 9,
      "name": "zone"
    },
    {
      "type_id": 10,
      "name": "region"
    },
    {
      "type_id": 11,
      "name": "root"
    }
  ],
  "buckets": [
    {
      "id": -1,
      "name": "default",
      "type_id": 11,
      "type_name": "root",
      "weight": 15333,
      "alg": "straw2",
      "hash": "rjenkins1",
      "items": [
        {
          "id": -4,
          "weight": 5111,
          "pos": 0
        },
        {
          "id": -7,
          "weight": 5111,
          "pos": 1
        },
        {
          "id": -10,
          "weight": 5111,
          "pos": 2
        }
      ]
    },
    {
      "id": -2,
      "name": "default~hdd",
      "type_id": 11,
      "type_name": "root",
      "weight": 7665,
      "alg": "straw2",
      "hash": "rjenkins1",
      "items": [
        {
          "id": -5,
          "weight": 2555,
          "pos": 0
        },
        {
          "id": -8,
          "weight": 2555,
          "pos": 1
        },
        {
          "id": -11,
          "weight": 2555,
          "pos": 2
        }
      ]
    },
    {
      "id": -3,
      "name": "default~ssd",
      "type_id": 11,
      "type_name": "root",
      "weight": 7665,
      "alg": "straw2",
      "hash": "rjenkins1",
      "items": [
        {
          "id": -6,
          "weight": 2555,
          "pos": 0
        },
        {
          "id": -9,
          "weight": 2555,
          "pos": 1
        },
        {
          "id": -12,
          "weight": 2555,
          "pos": 2
        }
      ]
    },
    {
      "id": -4,
      "name": "dev03",
      "type_id": 1,
      "type_name": "host",
      "weight": 5110,
      "alg": "straw2",
      "hash": "rjenkins1",
      "items": [
        {
          "id": 0,
          "weight": 2555,
          "pos": 0
        },
        {
          "id": 2,
          "weight": 2555,
          "pos": 1
        }
      ]
    },
    {
      "id": -5,
      "name": "dev03~hdd",
      "type_id": 1,
      "type_name": "host",
      "weight": 2555,
      "alg": "straw2",
      "hash": "rjenkins1",
      "items": [
        {
          "id": 0,
          "weight": 2555,
          "pos": 0
        }
      ]
    },
    {
      "id": -6,
      "name": "dev03~ssd",
      "type_id": 1,
      "type_name": "host",
      "weight": 2555,
      "alg": "straw2",
      "hash": "rjenkins1",
      "items": [
        {
          "id": 2,
          "weight": 2555,
          "pos": 0
        }
      ]
    },
    {
      "id": -7,
      "name": "dev02",
      "type_id": 1,
      "type_name": "host",
      "weight": 5110,
      "alg": "straw2",
      "hash": "rjenkins1",
      "items": [
        {
          "id": 1,
          "weight": 2555,
          "pos": 0
        },
        {
          "id": 3,
          "weight": 2555,
          "pos": 1
        }
      ]
    },
    {
      "id": -8,
      "name": "dev02~hdd",
      "type_id": 1,
      "type_name": "host",
      "weight": 2555,
      "alg": "straw2",
      "hash": "rjenkins1",
      "items": [
        {
          "id": 1,
          "weight": 2555,
          "pos": 0
        }
      ]
    },
    {
      "id": -9,
      "name": "dev02~ssd",
      "type_id": 1,
      "type_name": "host",
      "weight": 2555,
      "alg": "straw2",
      "hash": "rjenkins1",
      "items": [
        {
          "id": 3,
          "weight": 2555,
          "pos": 0
        }
      ]
    },
    {
      "id": -10,
      "name": "dev01",
      "type_id": 1,
      "type_name": "host",
      "weight": 5110,
      "alg": "straw2",
      "hash": "rjenkins1",
      "items": [
        {
          "id": 5,
          "weight": 2555,
          "pos": 0
        },
        {
          "id": 4,
          "weight": 2555,
          "pos": 1
        }
      ]
    },
    {
      "id": -11,
      "name": "dev01~hdd",
      "type_id": 1,
      "type_name": "host",
      "weight": 2555,
      "alg": "straw2",
      "hash": "rjenkins1",
      "items": [
        {
          "id": 4,
          "weight": 2555,
          "pos": 0
        }
      ]
    },
    {
      "id": -12,
      "name": "dev01~ssd",
      "type_id": 1,
      "type_name": "host",
      "weight": 2555,
      "alg": "straw2",
      "hash": "rjenkins1",
      "items": [
        {
          "id": 5,
          "weight": 2555,
          "pos": 0
        }
      ]
    }
  ],
  "rules": [
    {
      "rule_id": 0,
      "rule_name": "replicated_rule",
      "ruleset": 0,
      "type": 1,
      "min_size": 1,
      "max_size": 10,
      "steps": [
        {
          "op": "take",
          "item": -1,
          "item_name": "default"
        },
        {
          "op": "chooseleaf_firstn",
          "num": 0,
          "type": "host"
        },
        {
          "op": "emit"
        }
      ]
    },
    {
      "rule_id": 1,
      "rule_name": "ceph-blockpool",
      "ruleset": 1,
      "type": 1,
      "min_size": 1,
      "max_size": 10,
      "steps": [
        {
          "op": "take",
          "item": -3,
          "item_name": "default~ssd"
        },
        {
          "op": "chooseleaf_firstn",
          "num": 1,
          "type": "host"
        },
        {
          "op": "emit"
        },
        {
          "op": "take",
          "item": -2,
          "item_name": "default~hdd"
        },
        {
          "op": "chooseleaf_firstn",
          "num": 0,
          "type": "host"
        },
        {
          "op": "emit"
        }
      ]
    },
    {
      "rule_id": 2,
      "rule_name": "ceph-filesystem-metadata",
      "ruleset": 2,
      "type": 1,
      "min_size": 1,
      "max_size": 10,
      "steps": [
        {
          "op": "take",
          "item": -1,
          "item_name": "default"
        },
        {
          "op": "chooseleaf_firstn",
          "num": 0,
          "type": "host"
        },
        {
          "op": "emit"
        }
      ]
    },
    {
      "rule_id": 3,
      "rule_name": "ceph-filesystem-data0",
      "ruleset": 3,
      "type": 1,
      "min_size": 1,
      "max_size": 10,
      "steps": [
        {
          "op": "take",
          "item": -3,
          "item_name": "default~ssd"
        },
        {
          "op": "chooseleaf_firstn",
          "num": 1,
          "type": "host"
        },
        {
          "op": "emit"
        },
        {
          "op": "take",
          "item": -2,
          "item_name": "default~hdd"
        },
        {
          "op": "chooseleaf_firstn",
          "num": 0,
          "type": "host"
        },
        {
          "op": "emit"
        }
      ]
    }
  ],
  "tunables": {
    "choose_local_tries": 0,
    "choose_local_fallback_tries": 0,
    "choose_total_tries": 50,
    "chooseleaf_descend_once": 1,
    "chooseleaf_vary_r": 1,
    "chooseleaf_stable": 1,
    "straw_calc_version": 1,
    "allowed_bucket_algs": 54,
    "profile": "jewel",
    "optimal_tunables": 1,
    "legacy_tunables": 0,
    "minimum_required_version": "jewel",
    "require_feature_tunables": 1,
    "require_feature_tunables2": 1,
    "has_v2_rules": 0,
    "require_feature_tunables3": 1,
    "has_v3_rules": 0,
    "has_v4_buckets": 1,
    "require_feature_tunables5": 1,
    "has_v5_rules": 0
  },
  "choose_args": {}
}

```

**Comment by travisn** [comment]
Ah yes I believe the hybrid rules explain the issue. Since The second level of the CRUSH rule must not be respecting the failure domain of the first level, which means you could have two replicas of the data ending up on an ssd and hdd on the same node, which would make the data unavailable when that node goes down.

**Comment by francesco995** [comment]
did i configure something wrong in my cluster fs config? i followed the examples on this repo

```
      - name: ceph-filesystem
        spec:
          metadataPool:
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              replicated:
                size: 3
                hybridStorage:
                  primaryDeviceClass: ssd
                  secondaryDeviceClass: hdd
          metadataServer:
            activeCount: 1
            activeStandby: true
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          reclaimPolicy: Delete
          parameters:
            # The secrets contain Ceph admin credentials.
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            # Specify the filesystem type of the volume. If not specified, csi-provisioner
            # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
            # in hyperconverged settings where the volume is mounted on the same node as the osds.
            csi.storage.k8s.io/fstype: ext4
```
