### ISSUE TITLE
Prevent multiple clusters in the same namespace

### ISSUE THREAD

**Issue by travisn** [rook/rook#940]
Each Rook cluster must be defined in its own Kubernetes namespace. When multiple clusters are defined in the same namespace, Rook should reject all but the first instance of the CRD in that namespace. The current behavior is that multiple instances of the CRD are allowed in the same namespace, but Rook effectively only treats them as a single cluster. Rook will initialize the first cluster and effectively interpret the remaining instances as the same cluster. 

The expected behavior is that Rook would reject multiple instances in the same namespace. 

For example, you can create two clusters with these definitions:
```yaml
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  versionTag: master
```

```yaml
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-duplicate
  namespace: rook
spec:
  versionTag: master
```

But you only end up with a single cluster in the `rook` namespace.

Expected is that the `rook-duplicate` instance would be rejected by rook.
