### ISSUE TITLE
dataPool and metadataPool parameters are not propagated

### ISSUE THREAD

**Issue by zerkms** [rook/rook#9443]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I have set

```
kind: CephObjectStore
apiVersion: ceph.rook.io/v1
metadata:
  name: test-store
spec:
  metadataPool:
    deviceClass: rook
    failureDomain: host
    parameters:
      min_size: 1
    replicated:
      size: 3
  dataPool:
    deviceClass: rook
    failureDomain: host
    parameters:
      min_size: 1
    replicated:
      size: 3
```

And apply it - the operator says the cluster was reconciled, but the min_size is not changed and still shows `replicated size 3 min_size 2` in `ceph osd pool ls detail`.

The corresponding properties for the `CephBlockPool` work fine

**Expected behavior:**

I think it should reconcile and change the min size to 1.

**How to reproduce it (minimal and precise):**

Create a `CephObjectStore` with replica size 3, then add `parameters.min_size: 1`

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 20.04
* Kernel (e.g. `uname -a`): `5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: bare metal
* Rook version (use `rook version` inside of a Rook Pod): 1.7.7
* Storage backend version (e.g. for ceph do `ceph -v`): 
* Kubernetes version (use `kubectl version`): `ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by travisn** [comment]
@zerkms Do you see any errors in the operator log? Please confirm the setting is applied in the CR by querying `kubectl -n rook-ceph get cephobjectstore -o yaml`. I suspect it isn't actually applied since the parameters are strings and the min_size value is an integer. So you may need to specify quotes like this: `min_size: "1"`, or maybe the indentation is just off.

**Comment by zerkms** [comment]
There were no errors.

And my apologies - in my infrastructure the yaml manifests are generated from templates, in template they are surely strings (otherwise it does not pass the crd validation), and I made a mistake when crafting an example for report.

So, yes, `CephObjectStore` in the API has those parameters applied, and no errors in the operator log and the values are indeed strings.

**Comment by travisn** [comment]
@zerkms I was able to see the min_size set to 1 on the object store data pool with the following:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-store
  namespace: rook-ceph # namespace:cluster
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 3
    parameters:
      min_size: "1"
  dataPool:
    failureDomain: osd
    replicated:
      size: 3
    parameters:
      min_size: "1"
  preservePoolsOnDelete: false
  gateway:
    port: 80
    instances: 1
```

Do you see a message similar to this in the operator log?
```
setting pool property "min_size" to "1" on pool "my-store.rgw.buckets.data"
```
