### ISSUE TITLE
Helm: CephFilesystem, CephObjectStore & CrashCollector doesn't respect tolerations and affinity in cephClusterSpec.placement.all

### ISSUE THREAD

**Issue by brovoca** [rook/rook#9445]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

All pods are scheduled on nodes labeled `app=system` and tainted `CriticalAddonsOnly=true:NoSchedule` except for the CephFilesystem (`rook-ceph-mds-ceph-filesystem-a`, `rook-ceph-mds-ceph-filesystem-b`), CephObjectStore (`rook-ceph-rgw-ceph-objectstore-a`) & CrashCollector (`rook-ceph-crashcollector-aks-apps-39326844-vmss000001`)

**Expected behavior:**

All pods are scheduled on nodes labeled `app=system` and tainted `CriticalAddonsOnly=true:NoSchedule` when the `nodeAffinity` `tolerations` in `cephClusterSpec.placement.all` are set accordingly.

**How to reproduce it (minimal and precise):**

1. Taint and label a set of nodes on which Rook should run.

2. Deploy rook:
  
    ```sh
    helm install rook-ceph rook-release/rook-ceph-cluster -n rook-ceph --create-namespace -f operator-values.yaml
    helm install rook-ceph-cluster rook-release/rook-ceph-cluster -n rook-ceph -f cluster-values.yaml
    ```

**File(s) to submit**:

[operator-values.yaml](https://github.com/rook/rook/files/7726398/operator-values.yaml.txt)
[cluster-values.yaml](https://github.com/rook/rook/files/7726368/cluster-values.yaml.txt)

**Environment**:
* Cloud provider or hardware configuration: Azure
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.8.0, go: go1.16.10`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)`
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): AKS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): `HEALTH_OK`

**Comment by travisn** [comment]
@brovoca Try adding the placement settings to the [filesystem CR](https://github.com/rook/rook/blob/master/deploy/examples/filesystem.yaml#L53) and the [objectstore CR](https://github.com/rook/rook/blob/master/deploy/examples/object.yaml#L58). Agreed it would make more sense if `all` also applied to the separate CRs, but today `all` doesn't apply to those daemons.

**Comment by brovoca** [comment]
@travisn I've ended up patching it using Kustomize, as I want to avoid changing the defaults.

**Comment by subhamkrai** [comment]
@brovoca changing across multiple CR from one CR(cephCluster) is not good practice, in past, we tried to merge/change a few placements we had multiple follow-up issues. I would suggest using a specific CR for placement and close this issue. Thanks.

**Comment by travisn** [comment]
> @brovoca changing across multiple CR from one CR(cephCluster) is not good practice, in past, we tried to merge/change a few placements we had multiple follow-up issues. I would suggest using a specific CR for placement and close this issue. Thanks.

While we could choose to merge the placement across CRs since the cluster CR is considered the parent for all the other CRs in the namespace, beyond the implementation concern, it could also cause duplicate merges if we now implemented this feature and existing clusters had already specified the affinity/tolerations in the filesystem and object CRs. 
@brovoca You have it working with the current approach, right? Shall we close this issue?

**Comment by brovoca** [comment]
@travisn Yes, the current approach is working, but it's inconvenient. I would prefer to keep this dialogue open for a little while to see what can be done.

The question which must be asked is; Should everyone have to patch using Kustomize if they don't want to maintain their own CR? Setting the affinity/tolerations for the MDS is an important thing considering the high load of the service. One is expected to use only one of Helm or Kustomize, but not both. Thankfully it's possible to patch Helm releases, but it adds complexity which Helm should remove.

I would suggest adding `mds`, `rgw` and `cc` (CephFilesystem, CephObjectStore & CrashCollector) to [`cephClusterSpec.placement`](https://www.rook.io/docs/rook/v1.7/ceph-cluster-crd.html#placement-configuration-settings), with the exception that those would not be affected when using `all`. Once people have been given time to adopt their affinity/tolerations with `cephClusterSpec.placement`, if would be _safer_ to also include them in `cephClusterSpec.placement.all`.

It would also be reasonable to add it here (and probably more places which I've missed):
- https://www.rook.io/docs/rook/v1.7/ceph-cluster-crd.html#annotations-and-labels
- https://www.rook.io/docs/rook/v1.7/ceph-cluster-crd.html#cluster-wide-resources-configuration-settings

However, the only reason to avoid adding it to `cephClusterSpec.placement.all` right away is your stated concern:

>it could also cause duplicate merges if we now implemented this feature and existing clusters had already specified the affinity/tolerations in the filesystem and object CRs.

... but is that really an issue? Would `cephClusterSpec.placement.all` actually be injected into user defined CRs where e.g. `cephFileSystems[0].configuration.spec.metadataServer.placement` already is defined?

Thanks :-)

**Comment by travisn** [comment]
@brovoca Since you can define the nodeAffinity and tolerations as part of the CephFilesystem CR, everything can be included in the cluster helm chart today, right? For example:
```yaml
cephClusterSpec:
    placement:
      all:
        tolerations:
          ...
        nodeAffinity:
          ...
cephFilesystems:
  - name: ceph-filesystem
    spec:
      metadataServer:
        placement:
          tolerations:
            ...
          nodeAffinity:
            ...
```

The placement for the metadataServer was not included in the example values.yaml, so maybe that wasn't clear. But if you're saying something else, can you clarify the need to use kustomize?

**Comment by brovoca** [comment]
@travisn I am aware that I can specify `cephFilesystems` in the cluster Helm values, but in that case I need to provide a full config of a CephFilesystem/CephObjectStore, rather than _only_ supplying the affinity and toleration. Since I prefer not to touch the default values, I used a Kustomize patch (through FluxCD) in order to add the affinity and tolerations to the default CephFilesystem and CephObjectStore.

This is my cluster-release.yaml for FluxCD:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 4h
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
  chart:
    spec:
      chart: rook-ceph-cluster
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  ## Using default values from https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml
  values:
    cephClusterSpec:
      # ...

  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: ceph.rook.io/v1
            kind: CephFilesystem
            metadata:
              name: ceph-filesystem
            spec:
              metadataServer:
                placement:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                      - matchExpressions:
                        - key: app
                          operator: In
                          values:
                          - system
                  tolerations:
                  - effect: NoSchedule
                    key: CriticalAddonsOnly
                    operator: Exists
                resources:
                  requests:
                    cpu: "500m"
                    memory: "4Gi"
          - apiVersion: ceph.rook.io/v1
            kind: CephObjectStore
            metadata:
              name: ceph-objectstore
            spec:
              gateway:
                placement:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                      - matchExpressions:
                        - key: app
                          operator: In
                          values:
                          - system
                  tolerations:
                  - effect: NoSchedule
                    key: CriticalAddonsOnly
                    operator: Exists
```

**Comment by BlaineEXE** [comment]
None of the research or suggestions I have seen in the Kubernetes community say that it is wrong to use Kustomize with Helm as you are doing. On the contrary, I often see it being recommended, and so I think you are using the best solution available currently. See where this is recommended by the Helm project here: https://helm.sh/docs/topics/advanced/#post-rendering

**Comment by brovoca** [comment]
@BlaineEXE I know this is a suggested approach in cases where the Helm chart doesn't provide some functionality in itself, but in this case I think this should be incorporated and we could avoid using the postRenderer.

**Comment by travisn** [comment]
Ok that helps understand your goal of using the defaults as much as possible, then only overriding certain values. 

There is a basic assumption with the cluster chart that default values won't apply to most clusters, and it is just an example. This sentence in the [helm install guide](https://rook.github.io/docs/rook/v1.8/helm-ceph-cluster.html#installing) attempts to summarize that point: "The defaults are only an example and not likely to apply to your cluster."

Instead of jumping through hoops to pick up the defaults, I'd recommend just copying the defaults then modifying as needed. The defaults only include the basic and critical settings to get things working. You can always change your settings later if needed. For example, if a feature is added later that you want to enable, you would anyway need to update the spec which would differ from the defaults.

**Comment by brovoca** [comment]
@travisn I understand. In the end I still would wish for the tolerations and affinity to be applied to these specs too. I hope that is something that will find its way into the chart. Thank you for the good work on this project!

**Comment by willzhang** [comment]
> @brovoca由于您可以将 nodeAffinity 和 tolerations 定义为 CephFilesystem CR 的一部分，因此今天所有内容都可以包含在集群 helm 图表中，对吧？例如：
> 
> ```yaml
> cephClusterSpec:
>     placement:
>       all:
>         tolerations:
>           ...
>         nodeAffinity:
>           ...
> cephFilesystems:
>   - name: ceph-filesystem
>     spec:
>       metadataServer:
>         placement:
>           tolerations:
>             ...
>           nodeAffinity:
>             ...
> ```
> 
> metadataServer 的位置未包含在示例 values.yaml 中，因此可能不清楚。但是，如果您要说别的，您能澄清一下使用 kustomize 的必要性吗？

not effiect

```
root@node1:/data/rook# helm install rook-ceph-cluster --namespace rook-ceph --create-namespace \
  -f rook-ceph-cluster-values.yaml rook-release/rook-ceph-cluster
Error: template: rook-ceph-cluster/templates/cephfilesystem.yaml:11:32: executing "rook-ceph-cluster/templates/cephfilesystem.yaml" at <$filesystem.storageClass.enabled>: nil pointer evaluating interface {}.enabled
```

```
operatorNamespace: rook-ceph
clusterName: rook-ceph
toolbox:
  enabled: true
  image: dockerhub.kubekey.local/rook-ceph/ceph:v1.10.1
  tolerations: []
  affinity: {}
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "128Mi"

cephClusterSpec:
  cephVersion:
    image: dockerhub.kubekey.local/ceph/ceph:v17.2.3
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
    allowMultiplePerNode: false
  dashboard:
    enabled: true
    ssl: true
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - storage-node
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
  resources:
    mgr:
      limits:
        cpu: "1000m"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "512Mi"
    mon:
      limits:
        cpu: "2000m"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "1Gi"
    osd:
      limits:
        cpu: "2000m"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "1Gi"
    prepareosd:
      limits:
        cpu: "500m"
        memory: "400Mi"
      requests:
        cpu: "500m"
        memory: "50Mi"
    mgr-sidecar:
      limits:
        cpu: "500m"
        memory: "100Mi"
      requests:
        cpu: "100m"
        memory: "40Mi"
    crashcollector:
      limits:
        cpu: "500m"
        memory: "60Mi"
      requests:
        cpu: "100m"
        memory: "60Mi"
    logcollector:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "100Mi"
    cleanup:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "100Mi"
  storage:
    useAllNodes: true
    useAllDevices: false
    #deviceFilter:
    nodes:
      - name: "192.168.72.30"
        devices:
          - name: "sdb"
            config:
              osdsPerDevice: "1"
      - name: "192.168.72.31"
        devices:
          - name: "sdb"
            config:
              osdsPerDevice: "1"
      - name: "192.168.72.32"
        devices:
          - name: "sdb"
            config:
              osdsPerDevice: "1"

cephFileSystems:
  - name: ceph-filesystem
    spec:
      metadataServer:
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                  - storage-node
          tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists
```
