### ISSUE TITLE
Rook cluster chart not creating all resources

### ISSUE THREAD

**Issue by avekrivoy** [rook/rook#9602]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I'm using rook-ceph operator and rook-ceph-cluster charts v1.8.1 to create a cluster. From time to time on different environments I face an issue that resources like ceph-fs provisioner and csi-driver are not being created

```
NAME                                                      READY   STATUS      RESTARTS   AGE
rook-ceph-crashcollector-kube-worker-1-769cd78955-mxqtc   1/1     Running     0          58m
rook-ceph-crashcollector-kube-worker-2-84f9b4f988-8vxpb   1/1     Running     0          57m
rook-ceph-crashcollector-kube-worker-3-57fbdf9f47-sfk62   1/1     Running     0          57m
rook-ceph-mds-ceph-filesystem-hdd-a-7f58879878-5znxn      1/1     Running     0          155m
rook-ceph-mds-ceph-filesystem-hdd-b-778b9d8db5-btrd6      1/1     Running     0          155m
rook-ceph-mds-ceph-filesystem-ssd-a-7c96bb79d8-7bfb5      1/1     Running     0          154m
rook-ceph-mds-ceph-filesystem-ssd-b-845fc77f47-lkxqc      1/1     Running     0          154m
rook-ceph-mgr-a-55fc44d55b-n2wrm                          2/2     Running     0          155m
rook-ceph-mgr-b-7d7d448759-hjf67                          2/2     Running     0          155m
rook-ceph-mon-a-5794585485-rjlvh                          1/1     Running     0          156m
rook-ceph-mon-b-6bf546b879-jq6s4                          1/1     Running     0          156m
rook-ceph-mon-c-b6676bd76-lwfcr                           1/1     Running     0          155m
rook-ceph-operator-7fcc449f58-r9xlb                       1/1     Running     0          17m
rook-ceph-osd-0-9bcdc5bcf-bs2d4                           1/1     Running     0          155m
rook-ceph-osd-1-7569bd499c-f74cv                          1/1     Running     0          155m
rook-ceph-osd-2-6bc7fbc55c-92hv7                          1/1     Running     0          147m
rook-ceph-osd-prepare-kube-worker-1-h6l9j                 0/1     Completed   0          16m
rook-ceph-osd-prepare-kube-worker-2-zj4wt                 0/1     Completed   0          16m
rook-ceph-osd-prepare-kube-worker-3-2pqcf                 0/1     Completed   0          16m
rook-ceph-tools-f894666f4-kmxtl                           1/1     Running     0          156m

```

```
kubectl get csidrivers.storage.k8s.io 
No resources found
```
Looks like ceph cluster is healthy and alive
```
ceph status
  cluster:
    id:     06261267-436b-4a59-8aaf-043ecb55bd3e
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 2h)
    mgr: a(active, since 2h), standbys: b
    mds: 1/1 daemons up, 2 standby, 1 hot standby
    osd: 3 osds: 3 up (since 2h), 3 in (since 2h)
 
  data:
    volumes: 1/1 healthy
    pools:   5 pools, 129 pgs
    objects: 23 objects, 2.8 KiB
    usage:   23 MiB used, 59 GiB / 59 GiB avail
    pgs:     129 active+clean
 
  io:
    client:   853 B/s rd, 1 op/s rd, 0 op/s wr

```
```
kubectl get  cephclusters.ceph.rook.io  -n rook-ceph 
NAME        DATADIRHOSTPATH   MONCOUNT   AGE    PHASE   MESSAGE                        HEALTH      EXTERNAL
rook-ceph   /var/lib/rook     3          160m   Ready   Cluster created successfully   HEALTH_OK   
```
```
kubectl get pods rook-ceph-operator-7fcc449f58-r9xlb -n rook-ceph -o yaml
```
```
spec:
  containers:
  - args:
    - ceph
    - operator
    env:
    - name: ROOK_CURRENT_NAMESPACE_ONLY
      value: "true"
    - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
      value: "false"
    - name: ROOK_LOG_LEVEL
      value: INFO
    - name: ROOK_ENABLE_SELINUX_RELABELING
      value: "true"
    - name: ROOK_DISABLE_DEVICE_HOTPLUG
      value: "false"
    - name: ROOK_CSI_ENABLE_RBD
      value: "true"
    - name: ROOK_CSI_ENABLE_CEPHFS
      value: "true"
    - name: CSI_ENABLE_CEPHFS_SNAPSHOTTER
      value: "true"
    - name: CSI_ENABLE_RBD_SNAPSHOTTER
      value: "true"
    - name: CSI_PLUGIN_PRIORITY_CLASSNAME
    - name: CSI_PROVISIONER_PRIORITY_CLASSNAME
    - name: CSI_ENABLE_OMAP_GENERATOR
      value: "false"
    - name: CSI_ENABLE_VOLUME_REPLICATION
      value: "false"
    - name: CSI_PLUGIN_ENABLE_SELINUX_HOST_MOUNT
      value: "false"
    - name: CSI_RBD_FSGROUPPOLICY
      value: ReadWriteOnceWithFSType
    - name: CSI_CEPHFS_FSGROUPPOLICY
      value: None
    - name: ROOK_CSI_ENABLE_GRPC_METRICS
      value: "false"
    - name: CSI_FORCE_CEPHFS_KERNEL_CLIENT
      value: "true"
    - name: CSI_LOG_LEVEL
      value: "5"
    - name: CSI_PROVISIONER_REPLICAS
      value: "2"
    - name: ROOK_ENABLE_DISCOVERY_DAEMON
      value: "true"
    - name: ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS
      value: "15"
    - name: ROOK_OBC_WATCH_OPERATOR_NAMESPACE
      value: "true"

```

**Expected behavior:**
Cephfs provisioner and csi driver is being created during chart deployment

**Environment**:
* OS (e.g. from /etc/os-release): ```Ubuntu 20.04.3 LTS```
* Kernel (e.g. `uname -a`): ```Linux kube-master-1 5.4.0-94-generic 106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```
* Cloud provider or hardware configuration: ```Proxmox Hypervisor / raw block devices```
* Rook version (use `rook version` inside of a Rook Pod): ```v1.8.1```
* Storage backend version (e.g. for ceph do `ceph -v`): ```ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)```
* Kubernetes version (use `kubectl version`): ```Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubernetes
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_OK
