### ISSUE TITLE
Enable further customization of prometheus metrics labels

### ISSUE THREAD

**Issue by svolland-csgroup** [rook/rook#9618]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The operator actually supports an undocumented (?) monitoring label `rook.io/managedBy` that is used to add a `managedBy` label to the prometheus metrics.
```yaml
spec:
  labels:
    monitoring:
      rook.io/managedBy: some-value
```
The operator adds a relabeling to the ServiceMonitor for this specific label, this is implemented in function [`applyMonitoringLabels` in mgr.go](https://github.com/rook/rook/blob/d0d83edc5fd174deeb6242e694ecf347e2f2d1c9/pkg/operator/ceph/cluster/mgr/mgr.go#L550).
The new feature shall enable to define a list of fully customizable labels to add to the metrics (instead of a single fixed-named one).

This could also be implemented by leveraging the `targetLabels` feature of the ServiceMonitor. In this case the labels already specified in the clusterspec for the mgr could also be applied to the Service spec of the mgr daemon (they are actually only applied to the mgr deployment/pods). Then one could pick theses labels by configuring the list of 'targetLabels`.

**What is use case behind this feature:**
The use case is the need to add extra labels to prometheus metrics, this is particularly useful when the operator is managing more than one cluster to distinguish the metrics by using more functional label meanings that the currently available metric labels that might serve this purpose (e.g. namespace, instance or pod) .

**Comment by travisn** [comment]
@svolland-csgroup The `monitoring` labels are currently only applied if the label is `rook.io/mangedBy`, but I don't recall why that was so strict with #8355. Would it solve the issue if we just allow any label to be applied instead of only that specific label? That makes sense to me for most flexibility, unless you're saying another change is also needed for `targetLabgels`.

@anmolsachan Do you recall why only `rook.io/managedBy` was allowed?

**Comment by svolland-csgroup** [comment]
Applying any label would solve the issue and only require little code changes.

Leveraging the `targetLabels` feature would be a nicer solution because it uses the prometheus operator functionality that would generate appropriate configuration (instead of directly generating custom prometheus relabeling configurations), but it requires more changes:
- the monitoring labels must be added to the mgr service resource (`targetLabels` exploits labels on the service)
- then, depending on the degree of customization wanted:
  - either generate a `targetLabels` in the mgr ServiceMonitor with all label keys specified in the `labels.monitoring` config 
  - or only add a configurable subset of these label keys (but that would require a specific configuration section in the cluster spec)

Care must be taken that the labels specified in `labels.monitoring` do not overwrite those already existing in the service (i.e. app, ceph_daemon_id, rook_cluster), see the example below.

Configuration:
```yaml
spec:
  labels:
    monitoring:
      my-monitoring-label: my-value
```
generated mgr service:
```yaml
apiVersion: v1                                                                                                                                                                                                              
kind: Service                                                                                                                                                                                                               
metadata:                                                                                                                                                                                                                   
  labels:                                                                                                                                                                                                                   
    app: rook-ceph-mgr                                                                                                                                                                                                      
    ceph_daemon_id: a                                                                                                                                                                                                       
    rook_cluster: my-cluster
    my-monitoring-label: my-value
  name: rook-ceph-mgr    
[...]
```
generated ServiceMonitor:
```yaml
apiVersion: monitoring.coreos.com/v1                                                                                                                                                                                        
kind: ServiceMonitor                                                                                                                                                                                                        
metadata:                                                                                                                                                                                                                   
  name: rook-ceph-mgr                                                                                                                                                                                                       
spec:                                                                                                                                                                                                                       
[...]
  targetLabels:
    - my-monitoring-label
```
