### ISSUE TITLE
Operator CLBO when modifying `device-health-metrics` from `cluster-test.yaml` and using multus

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#9623]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**
1. Install minikube with --cni=flannel
2. Install multus on minikube with the following script and file:</br>
**networks.yaml**
```yaml
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: public-net
  namespace: rook-ceph
  labels:
  annotations:
spec:
  config:  '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth0", "mode": "bridge", "ipam": { "type": "whereabouts", "range": "192.168.20.0/24" } }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cluster-net
  namespace: rook-ceph
  labels:
  annotations:
spec:
  config:  '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth0", "mode": "bridge", "ipam": { "type": "whereabouts", "range": "192.168.21.0/24" } }'
```
```sh
#!/usr/bin/env bash

# download the multus daemonset, and remove mem and cpu limits
curl https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick-plugin.yml \
  | sed -e 's/cpu: /# cpu: /g' -e 's/memory: /# memory: /g' \
  | kubectl apply -f -

# install whereabouts
kubectl apply \
  -f https://raw.githubusercontent.com/k8snetworkplumbingwg/whereabouts/master/doc/crds/daemonset-install.yaml \
  -f https://raw.githubusercontent.com/k8snetworkplumbingwg/whereabouts/master/doc/crds/ip-reconciler-job.yaml \
  -f https://github.com/k8snetworkplumbingwg/whereabouts/raw/master/doc/crds/whereabouts.cni.cncf.io_ippools.yaml \
  -f https://github.com/k8snetworkplumbingwg/whereabouts/raw/master/doc/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml

# install networks
kubectl create namespace rook-ceph || true
kubectl apply -f networks.yaml
```
3. Deploy rook using `CSI_ENABLE_HOST_NETWORK: "false"`
4. Deploy Ceph from `cluster-test.yaml` with the following networking config:
```yaml
  network:
    provider: multus
    selectors:
      public: rook-ceph/public-net
      cluster: rook-ceph/cluster-net
```
5. At the same time, deploy `csi/rbd/storageclass-test.yaml`
6. Rook should deploy the ceph cluster successfully, then start a new reconcile and enter CrashLoopBackoffState

**File(s) to submit**:

Crashing operator logs:
```
2022-01-20 21:54:37.714212 I | ceph-block-pool-controller: initializing pool "device_health_metrics"
2022-01-20 21:54:37.829524 I | op-mon: parsing mon endpoints: a=10.109.190.205:6789
2022-01-20 21:54:37.829574 D | op-mon: loaded: maxMonID=0, mons=map[a:0xc0011f69a0], assignment=&{Schedule:map[a:0xc00002f000]}
2022-01-20 21:54:38.030259 D | exec: ExecWithOptions {Command:[timeout 15 rbd pool init device_health_metrics] Namespace:rook-ceph PodName:rook-ceph-mgr-a-7d7d66c96f-vrkvx ContainerName:cmd-proxy Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17b4af7]

goroutine 811 [running]:
github.com/rook/rook/pkg/daemon/ceph/client.(*CephToolCommand).run(0xc000cd6250, 0xc0011fe270, 0x2030f20, 0x14, 0xc000cd61f0, 0x1)
	/Users/blaine/go/src/github.com/rook/rook/pkg/daemon/ceph/client/command.go:170 +0x297
github.com/rook/rook/pkg/daemon/ceph/client.(*CephToolCommand).Run(...)
	/Users/blaine/go/src/github.com/rook/rook/pkg/daemon/ceph/client/command.go:192
github.com/rook/rook/pkg/operator/ceph/pool.createPool(0xc0005360b0, 0xc000f7e000, 0xc000cd74b8, 0xc000cd6438, 0xc000cd6500, 0x0)
	/Users/blaine/go/src/github.com/rook/rook/pkg/operator/ceph/pool/controller.go:384 +0x405
github.com/rook/rook/pkg/operator/ceph/pool.(*ReconcileCephBlockPool).reconcileCreatePool(0xc000037e00, 0xc000f7e000, 0xc000cd74b8, 0xc000bc6a00, 0xc000db1f34, 0xa, 0x0, 0x0)
	/Users/blaine/go/src/github.com/rook/rook/pkg/operator/ceph/pool/controller.go:344 +0x14c
github.com/rook/rook/pkg/operator/ceph/pool.(*ReconcileCephBlockPool).reconcile(0xc000037e00, 0xc000efed20, 0x9, 0xc0000f2558, 0x15, 0x30, 0x1edb3e0, 0xc00085c701, 0xc000707650)
	/Users/blaine/go/src/github.com/rook/rook/pkg/operator/ceph/pool/controller.go:268 +0xafe
github.com/rook/rook/pkg/operator/ceph/pool.(*ReconcileCephBlockPool).Reconcile(0xc000037e00, 0x23a83f8, 0xc000707650, 0xc000efed20, 0x9, 0xc0000f2558, 0x15, 0xc000707650, 0xc0007075f0, 0xc0008eadb0, ...)
	/Users/blaine/go/src/github.com/rook/rook/pkg/operator/ceph/pool/controller.go:136 +0x66
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0000dcdc0, 0x23a83f8, 0xc0007075f0, 0xc000efed20, 0x9, 0xc0000f2558, 0x15, 0xc000707500, 0x0, 0x0, ...)
	/Users/blaine/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:114 +0x247
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000dcdc0, 0x23a8350, 0xc000978540, 0x1e26100, 0xc000c5cac0)
	/Users/blaine/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:311 +0x305
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000dcdc0, 0x23a8350, 0xc000978540, 0x7d7b3a2265707900)
	/Users/blaine/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0002a41d0, 0xc0000dcdc0, 0x23a8350, 0xc000978540)
	/Users/blaine/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/Users/blaine/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:223 +0x425
```
