### ISSUE TITLE
Add support for topologyConstrainedPools to rook

### ISSUE THREAD

**Issue by sbskas** [rook/rook#9648]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
In the ceph-csi, there is an alpha feature present since 2020 called topologyContrainedPools. It allows to select the proper pool according to some conditions specified in the storageclass.
The requested feature is to activate this feature through some attributes in the rook crd.
This request is linked with a request I made with ceph-csi to [move this feature to beta status](https://github.com/ceph/ceph-csi/issues/2823).

**What is use case behind this feature:**
This feature is needed for implement multi-zone clusters with storage.
In this use case, the cluster is deployed on different locations (the zones) and zone local ceph pools are created to ensure good latency and bandwidth for the i/os.
Then, using topologcySpreadConstraints, one can create sts that scales through all zones.
Right now, the feature is usable but it could be largely improved if rook was aware of it.
First, one has to enable the feature on the rook-ceph-rbdplugin-provsioner deployment by adding the --feature-gates=Topology=true.
Second, one has to add the topology domain labels on the cmdline for the rbdplugin daemonset.
Third, 3 similars pools should be created, one on each zone.
Fourth, one has to create a storageclass with a topologyConstrainedPools attribute (example is given below).

**Example**:

```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: poolzone1
  namespace: rook-ceph
spec:
  replicated:
    size: 3
  crushRoot: zone1
  failureDomain: host
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: poolzone2
  namespace: rook-ceph
spec:
  replicated:
    size: 3
  crushRoot: zone2
  failureDomain: host
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: poolzone3
  namespace: rook-ceph
spec:
  replicated:
    size: 3
  crushRoot: zone3
  failureDomain: host
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block-topology-replicated
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
    clusterID: rook-ceph
    pool: repldefault
    imageFormat: "2"
    imageFeatures: layering
    topologyConstrainedPools: |
      [{"poolName":"poolzone1",
        "domainSegments":[
          {"domainLabel":"zone","value":"zone1"}]},
       {"poolName":"poolzone2",
        "domainSegments":[
          {"domainLabel":"zone","value":"zone2"}]},
       {"poolName":"poolzone3",
        "domainSegments":[
          {"domainLabel":"zone","value":"zone3"}]}
      ]
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-headless
 labels:
   run: my-nginx
spec:
 ports:
 - port: 80
   name: web
 clusterIP: None
 selector:
   run: my-nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
spec:
  serviceName: "nginx-headless"
  replicas: 0
  selector:
    matchLabels:
      run: my-nginx
  template:
    metadata:
      labels:
        run: my-nginx      
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: www
          mountPath: /var/www/
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            run: my-nginx
  volumeClaimTemplates:
  - metadata:
     name: www
    spec:
      storageClassName: rook-ceph-block-topology-replicated
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi

```

**Comment by travisn** [comment]
@sbskas Are you installing rook with the helm charts? This seems like a great use case where the building blocks are already there in the CRs, and we could enable this in the helm chart without even touching the operator code.

**Comment by sbskas** [comment]
I'm installing rook with the operator helm chart and a cephcluster object.

We already discussed with the ceph-csi about the missing parts for topologysupport in ceph-csi :
[Make ceph-csi domainLabels usable with Rook](https://github.com/ceph/ceph-csi/issues/2962).
For this to work, one has to give the topology label on the ceph-csi-attacher command line which is not configurable in rook.
For now, we've separated the rook cluster management from the ceph-csi management by disabling rbd-plugin in the rook config file and creating another ceph-csi daemonset.

**Comment by travisn** [comment]
@sbskas Could you open a new issue for this? We'd much rather support the option in rook than to require anyone to install the csi driver separately. :)

**Comment by blackliner** [comment]
Your pools use different crushRoots, is this required for all of this to work?

By default, you get a single crush root `default`, and the individual OSD's are assigned according to their "location", e.g. region, zone, rack etc, see below.

But then how does a pool get assigned to a certain zone? If I use the `default` crush root, and no other hints on zone etc, I fail to understand how ceph should know. (Also, the pool fails to get provisioned, which might be related)

```
ID   CLASS  WEIGHT     TYPE NAME                                        STATUS  REWEIGHT  PRI-AFF
 -1         877.54993  root default
-33          17.46544      region us-west-2
-32          17.46544          zone us-west-2-zone1
-31          17.46544              host host-domain-com
 98    ssd    3.49309                  osd.98                               up   1.00000  1.00000
 99    ssd    3.49309                  osd.99                               up   1.00000  1.00000
100    ssd    3.49309                  osd.100                              up   1.00000  1.00000
101    ssd    3.49309                  osd.101                              up   1.00000  1.00000
102    ssd    3.49309                  osd.102                              up   1.00000  1.00000
```

**Comment by travisn** [comment]
Yes for Rook to configure the topology constraint pool, it currently requires different crush roots, and the pool would be created with the corresponding `crushRoot` name. Otherwise, a custom CRUSH rule would be needed. It's certainly a possibility for Rook to implement such a CRUSH rule in the future if there is a need.

**Comment by blackliner** [comment]
But one OSD can only be part of one crush root at a time, correct? So I would need to separate some OSDs out and assign them to new crush roots that represent the zones, and the actual zone bucket loose any of their meaning (other than for failureDomain?)

**Comment by travisn** [comment]
That will also be a challenge because all names in the CRUSH map must be unique. In that example, you have multiple zones named `us-west-2`, which would not be allowed by ceph. 

It sounds like what you want is a property on the CephBlockPool CR such as the following, where Rook would generate the CRUSH rule for all replicas of the data to be placed in that topology:
```yaml
topologyConstraint: 
  name: zone
  value: use-west-2
```

@blackliner Want to open a new issue for this? This is a different issue from the CSI-defined topology constraints, which assume the pools already are created with the needed crush rules.
