### ISSUE TITLE
Cluster network using Multus+SRIOV: can't specify sriov resources requests/limits

### ISSUE THREAD

**Issue by sprat** [rook/rook#9653]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I am trying to use Multus+SR-IOV to set up a cluster network. The SR-IOV plugin requires that SR-IOV resources requests/limits are defined in the target pods. However, when I try to define the SR-IOV resources in the OSD resources definition of the cluster, they do not seem to be passed into the OSD pods, as you can see in the attached logs obtained when performing a `kubectl describe` on a OSD pod, which leads to a "cryptic" Multus error when the network is attached.

**Expected behavior:**

I would expect to see the SR-IOV resources defined in the OSD pods

**How to reproduce it (minimal and precise):**

I used the helm charts to deploy the cluster.

Here is the `resources` definition I used in the `cephClusterSpec`:
```yaml
  resources:
    osd:
      requests:
        cpu: "3"
        memory: "4Gi"
        intel.com/sriov_net_in: '1'  # does not appear in the pod
      limits:
        cpu: "4"
        memory: "8Gi"
        intel.com/sriov_net_in: '1'
```

I have confirmed that the cpu request I changed was properly applied to the OSD pods, so I'm pretty sure I didn't messed up here.

Now, the network part:
```yaml
  network:
    provider: multus
    selectors:
      cluster: cluster-net
```

Here is the network attachment definition for the cluster network:
```yaml
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cluster-net
  annotations:
    k8s.v1.cni.cncf.io/resourceName: "intel.com/sriov_net_in"
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "sriov_net_in",
    "type": "sriov",
    "spoofchk": "off",
    "trust": "on",
    "ipam": {
      "type": "whereabouts",
      "range": "192.168.120.0/22",
      "range_start": "192.168.122.0",
      "range_end": "192.168.122.32",
      "gateway": "192.168.120.1"
    }
  }'
```

I have confirmed that I can launch a test pod with this network attachment.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS-7.9 
* Kernel (e.g. `uname -a`): Linux tpl-qa-node-23 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: -
* Rook version (use `rook version` inside of a Rook Pod): rook/ceph:v1.8.2
* Storage backend version (e.g. for ceph do `ceph -v`): quay.io/ceph/ceph:v16.2.7
* Kubernetes version (use `kubectl version`): v1.20.11
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): NA
