### ISSUE TITLE
Failed to provision volume with StorageClass "rook-cephfs"

### ISSUE THREAD

**Issue by mhcastro** [rook/rook#9721]
**Is this a bug report or feature request?**
Bug Report

**Deviation from expected behavior:**
When creating a PVC in OpenShift using the sample Rook/Ceph cluster quick start published at https://github.com/rook/rook/blob/master/Documentation/quickstart.md, the PVC is still in Pending state and it is throwing the following event error.

```
Generated from rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-6f54f6c477-pwk9f_19a21aef-2edf-477d-86b6-b0303e5495aa

failed to provision volume with StorageClass "rook-cephfs": rpc error: code = InvalidArgument desc = volume not found
```

**Expected behavior:**
PVC to be created and bound to the storageclass `rook-cephfs`.

**How to reproduce it (minimal and precise):**
Apply this simple yaml. The storageclass `rook-cephfs` is configured as `default`.

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  namespace: test
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
```

**Environment**:
* OS (e.g. from /etc/os-release): `Red Hat Enterprise Linux CoreOS 48.84.202112162303-0`
* Kernel (e.g. `uname -a`): `Linux version 4.18.0-305.30.1.el8_4.x86_64 (mockbuild@x86-vm-07.build.eng.bos.redhat.com) (gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)) #1 SMP Tue Nov 30 13:13:11 EST 2021`
* Cloud provider or hardware configuration: `AMD64, 8 cores x 16GB`
* Rook version (use `rook version` inside of a Rook Pod): `v1.8.0-alpha.0.284.g4c6378586`
* Storage backend version (e.g. for ceph do `ceph -v`): `16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)`
* Kubernetes version (use `kubectl version`): `1.21`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `OpenShift`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):
```
ceph status
  cluster:
    id:     effeba0d-9207-4745-b17c-be9c14fa08cc
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 22h)
    mgr: a(active, since 22h)
    osd: 3 osds: 3 up (since 22h), 3 in (since 22h)

  data:
    pools:   1 pools, 1 pgs
    objects: 0 objects, 0 B
    usage:   15 MiB used, 600 GiB / 600 GiB avail
```

Thanks in advance.
