### ISSUE TITLE
osd-pod always crashes every few days

### ISSUE THREAD

**Issue by df-bingo** [rook/rook#9819]
* Bug Report
Yes I think so

**How to reproduce it (minimal and precise):**
osd-pod always crashes every few days, the problem still exists after upgrading from 1.7 to 1.8

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
[53.log](https://github.com/rook/rook/files/8168332/53.log)
https://pan.baidu.com/s/1aSDM40VPghv9UIWr-jsYQQ?pwd=ccsn

**Environment**:
* OS :Ubuntu 20.04.2 LTS
* Kernel :5.4.0-73-generic 82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Rook version :v1.8.2
* Storage backend version :16.2.7-0
* Kubernetes version :v1.22.1
* Storage backend status :
cluster:
    id:     e6067ce0-2756-4934-b4c6-76539806bddd
    health: HEALTH_WARN
            noscrub,nodeep-scrub flag(s) set
            Degraded data redundancy: 5437767/2396071200 objects degraded (0.227%), 155 pgs degraded, 17 pgs undersized
            943 pgs not deep-scrubbed in time
            712 pgs not scrubbed in time
 
  services:
    mon: 3 daemons, quorum a,b,c (age 2h)
    mgr: b(active, since 2d), standbys: a
    osd: 61 osds: 61 up (since 15m), 61 in (since 8h); 110 remapped pgs
         flags noscrub,nodeep-scrub
    rgw: 3 daemons active (3 hosts, 1 zones)
 
  data:
    pools:   9 pools, 2104 pgs
    objects: 798.69M objects, 6.3 TiB
    usage:   29 TiB used, 383 TiB / 412 TiB avail
    pgs:     5437767/2396071200 objects degraded (0.227%)
             74423900/2396071200 objects misplaced (3.106%)
             1869 active+clean
             124  active+recovery_wait+degraded
             75   active+remapped+backfill_wait
             14   active+recovery_wait+degraded+remapped
             8    active+undersized+degraded+remapped+backfill_wait
             8    active+recovery_wait+undersized+degraded+remapped
             4    active+remapped+backfilling
             1    active+recovering+undersized+degraded+remapped
             1    active+recovery_wait
 
  io:
    client:   2.0 MiB/s rd, 5.1 MiB/s wr, 2.03k op/s rd, 6.13k op/s wr
    recovery: 275 KiB/s, 26.37k keys/s, 32 objects/s

**Comment by travisn** [comment]
@df-bingo I don't see a crash in those osd logs. What does `kubectl describe pod <osd-pod>` show for the liveness probe? Perhaps the liveness probe is killing the osd? If needed, you could try disabling the osd liveness probe [here](https://github.com/rook/rook/blob/master/deploy/examples/cluster.yaml#L279-L280).

**Comment by df-bingo** [comment]
It's true that the liveness probe is killing the osd, but why does this happen? Can I only choose to turn off the liveness probe?

> debug 2022-03-02T00:59:42.698+0000 7f5e73198080  0 _get_class not permitted to load sdk
debug 2022-03-02T00:59:42.698+0000 7f5e73198080  0 _get_class not permitted to load lua
debug 2022-03-02T00:59:42.698+0000 7f5e73198080  0 _get_class not permitted to load kvs
debug 2022-03-02T00:59:42.698+0000 7f5e73198080  1 osd.53 64898 warning: got an error loading one or more classes: (1) Operation not permitted
debug 2022-03-02T00:59:42.698+0000 7f5e73198080  0 osd.53 64898 crush map has features 432629239337189376, adjusting msgr requires for clients
debug 2022-03-02T00:59:42.698+0000 7f5e73198080  0 osd.53 64898 crush map has features 432629239337189376 was 8705, adjusting msgr requires for mons
debug 2022-03-02T00:59:42.698+0000 7f5e73198080  0 osd.53 64898 crush map has features 3314933000854323200, adjusting msgr requires for osds
debug 2022-03-02T00:59:42.698+0000 7f5e73198080  1 osd.53 64898 check_osdmap_features require_osd_release unknown -> pacific

Does the above error have any effect?

**Comment by travisn** [comment]
The liveness probe thresholds can actually be customized, there is an example in the docs [here](https://rook.github.io/docs/rook/v1.8/ceph-cluster-crd.html#health-settings). For example:
```yaml
  livenessProbe:
    osd:
      disabled: false
      probe:
        initialDelaySeconds: 3
        periodSeconds: 3
```

> Does the above error have any effect?

This seems unrelated, not sure it's an issue.

**Comment by BlaineEXE** [comment]
It may be that your nodes are a little bit short on resources. An OSD could be getting starved of CPU cycles by other processes, which could result in the liveness probe not returning quickly. Setting pod limits and requests might help.

**Comment by travisn** [comment]
Good point, you might also need to set resource limits on the OSD. See [this topic](https://rook.github.io/docs/rook/v1.8/ceph-cluster-crd.html#cluster-wide-resources-configuration-settings).

**Comment by df-bingo** [comment]
thank you all!I will try again.

**Comment by df-bingo** [comment]
After adjusting according to your method, there is no problem for several days, but after the server restarts, the same situation occurs again, and several osds have crashloopbackoff.

kubectl -n rook-ceph get pod|grep osd|grep -i crash

```
rook-ceph-osd-17-657bbdf5b5-9sgnx                  0/1     CrashLoopBackOff   1456 (3m26s ago)   5d3h
rook-ceph-osd-25-68b599dfb4-8fbfp                  0/1     CrashLoopBackOff   14 (3m19s ago)     5d3h
rook-ceph-osd-37-85fdbbcfc7-2tcds                  0/1     CrashLoopBackOff   1457 (3m38s ago)   5d3h
rook-ceph-osd-52-6bcd99545d-72dq6                  0/1     CrashLoopBackOff   6 (4m22s ago)      14m
rook-ceph-osd-53-d6457cfb8-8jx4b                   0/1     CrashLoopBackOff   1456 (3m55s ago)   5d3h
rook-ceph-osd-59-f6b6bc459-2pkdq                   0/1     CrashLoopBackOff   14 (3m25s ago)     5d3h
rook-ceph-osd-62-847d455644-zrlm5                  0/1     CrashLoopBackOff   1456 (3m43s ago)   5d3h
rook-ceph-osd-63-78dbf4b68-b2gx7                   0/1     CrashLoopBackOff   14 (3m24s ago)     5d3h
rook-ceph-osd-64-dd445cd86-6s529                   0/1     CrashLoopBackOff   1456 (3m35s ago)   5d3h
```

kubectl -n rook-ceph edit cephclusters.ceph.rook.io

```
healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mgr:
        disabled: false
      mon:
        disabled: false
      osd:
        disabled: false
        probe:
          initialDelaySeconds: 3
          periodSeconds: 3


resources:
    crashcollector:
      limits:
        cpu: "1"
        memory: 150Mi
      requests:
        cpu: 500m
        memory: 60Mi
    mgr:
      limits:
        cpu: "1"
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi
    mgr-sidecar:
      limits:
        cpu: "1"
        memory: 100Mi
      requests:
        cpu: 500m
        memory: 40Mi
    mon:
      limits:
        cpu: "1"
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi
    osd:
      requests:
        cpu: 500m
        memory: 2048Mi
    prepareosd:
      limits:
        cpu: "1"
        memory: 120Mi
      requests:
        cpu: 500m
        memory: 50Mi
```

kubectl -n rook-ceph describe pod rook-ceph-osd-63-78dbf4b68-b2gx7
[rook-ceph-osd-63-78dbf4b68-b2gx7.txt](https://github.com/rook/rook/files/8212558/rook-ceph-osd-63-78dbf4b68-b2gx7.txt)

kubectl -n rook-ceph logs  rook-ceph-osd-63-78dbf4b68-b2gx7
[rook-ceph-osd-63-78dbf4b68-b2gx7.log](https://github.com/rook/rook/files/8212568/rook-ceph-osd-63-78dbf4b68-b2gx7.log)
