### ISSUE TITLE
osdsPerDevice not working

### ISSUE THREAD

**Issue by sl1288** [rook/rook#9822]
Settings:

```
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "k3shost"
        devices:
          - name: "nvme0n1"
            config:
              osdsPerDevice: "2"
          - name: "nvme0n2"
            config:
              osdsPerDevice: "2"
          - name: "nvme0n3"
            config:
              osdsPerDevice: "3"
```
ceph osd tree
```
ID  CLASS  WEIGHT   TYPE NAME         STATUS  REWEIGHT  PRI-AFF
-1         0.30667  root default
-3         0.30667      host k3shost
 0   nvme  0.09769          osd.0         up   1.00000  1.00000
 1   nvme  0.10840          osd.1         up   1.00000  1.00000
 2   nvme  0.10059          osd.2         up   1.00000  1.00000
```
kubectl get all -A | grep osd
```
rook-ceph     pod/rook-ceph-osd-0-69fb4b8c9d-wjfwg                    1/1     Running     4 (43m ago)    133m
rook-ceph     pod/rook-ceph-osd-1-fcbc76895-5d7nx                     1/1     Running     2 (43m ago)    109m
rook-ceph     pod/rook-ceph-osd-2-6dc8df4949-kcq8l                    1/1     Running     0              31m
rook-ceph     pod/rook-ceph-osd-prepare-k3shost--1-8l8fd              0/1     Completed   0              31m
rook-ceph     deployment.apps/rook-ceph-osd-0                    1/1     1            1           133m
rook-ceph     deployment.apps/rook-ceph-osd-1                    1/1     1            1           109m
rook-ceph     deployment.apps/rook-ceph-osd-2                    1/1     1            1           31m
rook-ceph     replicaset.apps/rook-ceph-osd-0-69fb4b8c9d                    1         1         1       133m
rook-ceph     replicaset.apps/rook-ceph-osd-1-fcbc76895                     1         1         1       109m
rook-ceph     replicaset.apps/rook-ceph-osd-2-6dc8df4949                    1         1         1       31m
rook-ceph     job.batch/rook-ceph-osd-prepare-k3shost   1/1           15s        31m
```

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Only 1 osd is created per device

**Expected behavior:**
2 or 3 osds per device as configured

**Environment**:
* OS: Alpine Linux
* Kernel (e.g. `uname -a`): `Linux k3shost 5.15.16-0-lts #1-Alpine SMP Wed, 26 Jan 2022 16:46:12 +0000 x86_64 Linux`
* Cloud provider or hardware configuration: VM in VMware Workstation
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.8.6 go: go1.16.14
* Storage backend version (e.g. for ceph do `ceph -v`): quay.io/ceph/ceph:v16.2.7
* Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_OK

**Comment by BlaineEXE** [comment]
Could you show logs from the `rook-ceph-osd-prepare` pod as well? And ideally run the Rook operator with `ROOK_LOG_LEVEL=DEBUG`.

**Comment by mtt0** [comment]
> Could you show logs from the `rook-ceph-osd-prepare` pod as well? And ideally run the Rook operator with `ROOK_LOG_LEVEL=DEBUG`.

I experience this yesterday and give it up finally, didn't keep log files... 

`rook-ceph-osd-prepare` find devices and shows that osdPerDevice is 1, didn't take configuration in `values.yaml`

**Comment by sl1288** [comment]
I reset my VM to provide you clean logs.
Settings:
```
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "k3shost"
        devices:
          - name: "nvme0n1"
            config:
              osdsPerDevice: "3"
```

[rook-ceph-operator.log](https://github.com/rook/rook/files/8177030/rook-ceph-operator.log)
[rook-ceph-osd-prepare.log](https://github.com/rook/rook/files/8177035/rook-ceph-osd-prepare.log)

ceph osd tree
```
ID  CLASS  WEIGHT   TYPE NAME         STATUS  REWEIGHT  PRI-AFF
-1         0.09769  root default
-3         0.09769      host k3shost
 0   nvme  0.09769          osd.0         up   1.00000  1.00000
```
