### ISSUE TITLE
CephFS storage class should use named data pool instead of default data pool

### ISSUE THREAD

**Issue by mtt0** [rook/rook#9826]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

PVC Pending

**Expected behavior:**

PVC Bound

**How to reproduce it (minimal and precise):**

1. Install rook cluster with named data pool like
```yaml
cephFileSystems:
  - name: ceph-filesystem
    # see https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem-crd.md#filesystem-settings for available configuration
    spec:
      metadataPool:
        replicated:
          size: 3
      dataPools:
        - name: pool0
          failureDomain: rack
          replicated:
            size: 1
            requireSafeReplicaSize: false
          deviceClass: ssd
          parameters:
            target_size_ratio: "2.0"
      metadataServer:
        activeCount: 1
        activeStandby: true
      preserveFilesystemOnDelete: true
    storageClass:
      enabled: true
      isDefault: true
      name: ceph-filesystem
      reclaimPolicy: Retain
      allowVolumeExpansion: true
      mountOptions: []
      # see https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem.md#provision-storage for available configuration
      parameters:
        # The secrets contain Ceph admin credentials.
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
        # Specify the filesystem type of the volume. If not specified, csi-provisioner
        # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
        # in hyperconverged settings where the volume is mounted on the same node as the osds.
        csi.storage.k8s.io/fstype: ext4
```

so we got:
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/17849741/156512219-384b6c79-2a54-4413-b82a-65bada376720.png">

2. Create PVC
```shell
cat <<EOF > test-pvc-cf.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    cattle.io/creator: norman
  name: test-pvc-fs
  namespace: test-ceph
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
EOF

kubectl create namespace test-ceph
kubectl create -f test-pvc-cf.yaml

kubectl describe pvc -n test-ceph test-pvc-cf
```

Output:
```
Name:          test-pvc-cf
Namespace:     test-ceph
StorageClass:  ceph-filesystem
Status:        Pending
Volume:
Labels:        cattle.io/creator=norman
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                 From                                                                                                              Message
  ----     ------                ----                ----                                                                                                              -------
  Normal   Provisioning          3m (x12 over 11m)   rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-6f54f6c477-8xzgh_63b40f5e-a564-4c95-ba62-c1aeea742b12  External provisioner is provisioning volume for claim "test-ceph/test-pvc-cf"
  Warning  ProvisioningFailed    3m (x12 over 11m)   rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-6f54f6c477-8xzgh_63b40f5e-a564-4c95-ba62-c1aeea742b12  failed to provision volume with StorageClass "ceph-filesystem": rpc error: code = Internal desc = rados: ret=-22, Invalid argument: "invalid pool layout 'ceph-filesystem-data0' -- need a valid data pool"
  Normal   ExternalProvisioning  78s (x42 over 11m)  persistentvolume-controller                                                                                       waiting for a volume to be created, either by external provisioner "rook-ceph.cephfs.csi.ceph.com" or manually created by system administrator
```

Root cause maybe: `invalid pool layout 'ceph-filesystem-data0' -- need a valid data pool`

**File(s) to submit**: None

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): 
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.8.6
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)`
* Kubernetes version (use `kubectl version`): v1.22.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubespray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): `HEALTH_WARN 3 pool(s) have no replicas configured`

**Comment by sathieu** [comment]
This is probably related: rook removes the `dataPool`'s `name`:

```diff
 spec:
   dataPools:
-    - name: replicated
+    - compressionMode: ''
+      crushRoot: ''
+      deviceClass: ''
+      erasureCoded:
+        codingChunks: 0
+        dataChunks: 0
+      failureDomain: ''
       replicated:
+        requireSafeReplicaSize: false
         size: 3
   metadataPool:
     replicated:
       size: 3
   metadataServer:
     activeCount: 1
     activeStandby: true
   preserveFilesystemOnDelete: true
```

**Comment by travisn** [comment]
@mtt0 The storage class specifies the cephfs data pool, did you change the value [here](https://github.com/rook/rook/blob/master/deploy/examples/csi/cephfs/storageclass.yaml#L17)?

**Comment by mtt0** [comment]
> This is probably related: rook removes the `dataPool`'s `name`:
> 
> ```diff
>  spec:
>    dataPools:
> -    - name: replicated
> +    - compressionMode: ''
> +      crushRoot: ''
> +      deviceClass: ''
> +      erasureCoded:
> +        codingChunks: 0
> +        dataChunks: 0
> +      failureDomain: ''
>        replicated:
> +        requireSafeReplicaSize: false
>          size: 3
>    metadataPool:
>      replicated:
>        size: 3
>    metadataServer:
>      activeCount: 1
>      activeStandby: true
>    preserveFilesystemOnDelete: true
> ```

https://github.com/rook/rook/blob/v1.8.6/Documentation/ceph-filesystem.md#create-the-filesystem
https://github.com/rook/rook/blob/v1.8.6/Documentation/ceph-filesystem-crd.md#pools

Rook v1.8.6 docs: dataPool's name is **optional, and highly recommended**

**Comment by sathieu** [comment]
@mtt0 I have specified the name, but it was removed (probably from the controller). No idea why ..

**Comment by sathieu** [comment]
I've upgraded to 1.8.6 and problem is gone for me (so this is not the same problem). Sorry for the noise.

**Comment by mtt0** [comment]
> I've upgraded to 1.8.6 and problem is gone for me (so this is not the same problem). Sorry for the noise.

Never mind~

**Comment by travisn** [comment]
@mtt0 If the name is being removed from the CR, you must not have the latest CRD schema. Have you applied the latest v1.8.6 crds.yaml? Or if you install with helm, have you upgraded to the latest operator helm chart?

**Comment by travisn** [comment]
Ah, I see this is a helm chart issue as fixed by #9838

**Comment by brathina-spectro** [comment]
For anyone else checking about this problem, we ran into this when upgrading from rook-ceph 1.8.0 > 1.18.3

CephFileSystem spec in 1.8.0
```
  apiVersion: ceph.rook.io/v1
  kind: CephFilesystem
  metadata:
    name: myfs
    namespace: rook-ceph # namespace:cluster
  spec:
    # The metadata pool spec. Must use replication.
    metadataPool:
      replicated:
        size: 3
        requireSafeReplicaSize: true
      parameters:
        # Inline compression mode for the data pool
        # Further reference: https://docs.ceph.com/docs/master/rados/configuration/bluestore-config-ref/#inline-compression
        compression_mode:
          none
        # gives a hint (%) to Ceph in terms of expected consumption of the total cluster capacity of a given pool
        # for more info: https://docs.ceph.com/docs/master/rados/operations/placement-groups/#specifying-expected-pool-size
        #target_size_ratio: ".5"
    # The list of data pool specs. Can use replication or erasure coding.
    dataPools:
      - name: replicated
        failureDomain: host
        replicated:
          size: 3
          # Disallow setting pool with replica 1, this could lead to data loss without recovery.
          # Make sure you're *ABSOLUTELY CERTAIN* that is what you want
          requireSafeReplicaSize: true
        parameters:
          # Inline compression mode for the data pool
          # Further reference: https://docs.ceph.com/docs/master/rados/configuration/bluestore-config-ref/#inline-compression
          compression_mode:
            none
          # gives a hint (%) to Ceph in terms of expected consumption of the total cluster capacity of a given pool
          # for more info: https://docs.ceph.com/docs/master/rados/operations/placement-groups/#specifying-expected-pool-size
          #target_size_ratio: ".5"
    # Whether to preserve filesystem after CephFilesystem CRD deletion
    preserveFilesystemOnDelete: true
    # The metadata service (mds) configuration
    metadataServer:
      # The number of active MDS instances
      activeCount: 1
      # Whether each active MDS instance will have an active standby with a warm metadata cache for faster failover.
      # If false, standbys will be available, but will not have a warm cache.
      activeStandby: true
      # The affinity rules to apply to the mds deployment
      placement:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-mds
              # topologyKey: kubernetes.io/hostname will place MDS across different hosts
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - rook-ceph-mds
                # topologyKey: */zone can be used to spread MDS across different AZ
                # Use <topologyKey: failure-domain.beta.kubernetes.io/zone> in k8s cluster if your cluster is v1.16 or lower
                # Use <topologyKey: topology.kubernetes.io/zone>  in k8s cluster is v1.17 or upper
                topologyKey: topology.kubernetes.io/zone
      # A key/value list of annotations
      annotations:
      #  key: value
      # A key/value list of labels
      labels:
      #  key: value
      resources:
        # The requests and limits set here, allow the filesystem MDS Pod(s) to use half of one CPU core and 1 gigabyte of memory
        #  limits:
        #    cpu: "500m"
        #    memory: "1024Mi"
        #  requests:
        #    cpu: "500m"
        #    memory: "1024Mi"
        # priorityClassName: my-priority-class
        # Filesystem mirroring settings
        # mirroring:
        # enabled: true
        # list of Kubernetes Secrets containing the peer token
        # for more details see: https://docs.ceph.com/en/latest/dev/cephfs-mirroring/#bootstrap-peers
        # peers:
        #secretNames:
        #- secondary-cluster-peer
        # specify the schedule(s) on which snapshots should be taken
        # see the official syntax here https://docs.ceph.com/en/latest/cephfs/snap-schedule/#add-and-remove-schedules
        # snapshotSchedules:
        #   - path: /
        #     interval: 24h # daily snapshots
        #     startTime: 11:55
        # manage retention policies
        # see syntax duration here https://docs.ceph.com/en/latest/cephfs/snap-schedule/#add-and-remove-retention-policies
        # snapshotRetention:
        #   - path: /
        #     duration: "h 24"
```
**Filesystem created:**

[rook@rook-ceph-tools-846884d59b-j5zbn /]$ ceph fs ls
name: myfs, metadata pool: myfs-metadata, data pools: [myfs-data0 ]
