### ISSUE TITLE
CephFS: allowMultipleFilesystems seems not work? 

### ISSUE THREAD

**Issue by mtt0** [rook/rook#9840]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

As [Ceph: multifs](https://docs.ceph.com/en/pacific/cephfs/multifs/) says that:

```
Beginning with the Pacific release, multiple file system support is stable and ready to use. This functionality allows configuring separate file systems with full data separation on separate pools.
```

But rook ceph seems not. I only got one:

<img width="887" alt="image" src="https://user-images.githubusercontent.com/17849741/156753065-3fd8ce50-9e65-4d18-9491-bb0c4a79927f.png">

**Expected behavior:**

Multiple Ceph filesystems in the same cluster and work properly

**How to reproduce it (minimal and precise):**

1. Install operator
```shell
helm install --create-namespace --namespace rook-ceph rook-ceph-cluster rook-release/rook-ceph-cluster --version v1.8.6 -f values.yaml
```

values.yaml:
```yaml
allowMultipleFilesystems: true
```

2. Install cluster

```shell
helm install --create-namespace --namespace rook-ceph rook-ceph-cluster rook-release/rook-ceph-cluster --version v1.8.6 -f values.yaml
```

values.yaml:
```yaml
cephFileSystems:
  - name: ceph-filesystem
    # see https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem-crd.md#filesystem-settings for available configuration
    spec:
      metadataPool:
        failureDomain: rack
        replicated:
          size: 3
        deviceClass: ssd
      dataPools:
        - name: data0
          failureDomain: rack
          replicated:
            size: 3
          deviceClass: ssd
          parameters:
            target_size_ratio: "3.0"
      metadataServer:
        activeCount: 1
        activeStandby: true
      preserveFilesystemOnDelete: true
    storageClass:
      enabled: true
      isDefault: true
      name: ceph-filesystem
      reclaimPolicy: Retain
      allowVolumeExpansion: true
      mountOptions: []
      # see https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem.md#provision-storage for available configuration
      parameters:
        ...
  - name: erasure-coded-ceph-filesystem
    # see https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem-crd.md#filesystem-settings for available configuration
    spec:
      metadataPool:
        failureDomain: rack
        replicated:
          size: 3
        deviceClass: ssd
      dataPools:
        - name: data0
          failureDomain: rack
          erasureCoded:
            dataChunks: 2
            codingChunks: 1
          deviceClass: ssd
          parameters:
            target_size_ratio: "1.5"
      metadataServer:
        activeCount: 1
        activeStandby: true
      preserveFilesystemOnDelete: true
    storageClass:
      enabled: true
      isDefault: false
      name: clod-ceph-filesystem
      reclaimPolicy: Retain
      allowVolumeExpansion: true
      mountOptions: []
      # see https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem.md#provision-storage for available configuration
      parameters:
        ...
```

3. Test CephFS

```shell
cat <<EOF > test-pvc-cf.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    cattle.io/creator: norman
  name: test-pvc-cf
  namespace: test-ceph
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    cattle.io/creator: norman
  name: clod-test-pvc-cf
  namespace: test-ceph
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: clod-ceph-filesystem
EOF

kubectl create ns test-ceph
kubectl create -f test-pvc-cf.yaml
```

Check result:
```shell
kubectl get pvc -n test-ceph
# Output
NAME               STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS           AGE
clod-test-pvc-cf   Pending                                                                        clod-ceph-filesystem   18m
test-pvc-cf        Bound     pvc-9afac193-28a8-4036-b400-e6222aed6d74   1Gi        RWX            ceph-filesystem        18m
```

`kubectl describe pvc -n test-ceph clod-test-pvc-cf` outputs:
```
Name:          clod-test-pvc-cf
Namespace:     test-ceph
StorageClass:  clod-ceph-filesystem
Status:        Pending
Volume:
Labels:        cattle.io/creator=norman
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                  From                                                                                                              Message
  ----     ------                ----                 ----                                                                                                              -------
  Normal   Provisioning          3m2s (x13 over 16m)  rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-6f54f6c477-pt4sg_74417bf3-d39e-4277-afae-69b775e289ad  External provisioner is provisioning volume for claim "test-ceph/clod-test-pvc-cf"
  Warning  ProvisioningFailed    3m2s (x13 over 16m)  rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-6f54f6c477-pt4sg_74417bf3-d39e-4277-afae-69b775e289ad  failed to provision volume with StorageClass "clod-ceph-filesystem": rpc error: code = InvalidArgument desc = volume not found
  Normal   ExternalProvisioning  84s (x63 over 16m)   persistentvolume-controller                                                                                       waiting for a volume to be created, either by external provisioner "rook-ceph.cephfs.csi.ceph.com" or manually created by system administrator
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* `kubectl --namespace rook-ceph get cephcluster -o yaml`: [cluster.txt](https://github.com/rook/rook/files/8185479/cluster.txt)
* Operator's logs, if necessary: [rook-ceph_rook-ceph-operator-7fb44b6566-zztnk_rook-ceph-operator.log](https://github.com/rook/rook/files/8185529/rook-ceph_rook-ceph-operator-7fb44b6566-zztnk_rook-ceph-operator.log)
* Crashing pod(s) logs, if necessary

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 21.10`
* Kernel (e.g. `uname -a`): `Linux control-plane-01 5.13.0-30-generic #33-Ubuntu SMP Fri Feb 4 17:03:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): `v1.8.6`
* Storage backend version (e.g. for ceph do `ceph -v`):
`ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)`
* Kubernetes version (use `kubectl version`): `v1.22.5`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubespray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): `HEALTH_OK`
