### ISSUE TITLE
ReadWriteMany PVC is behaving like ReadWriteOnce

### ISSUE THREAD

**Issue by AdarshdeepCheema** [rook/rook#9893]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
PVC share volume is only accessible from the latest pod( pod that is created at last)

**Expected behavior:**
PVC share volume should be accessible from the all the pods

**How to reproduce it (minimal and precise):**
**1 . Create a PVC using rook-cephs storage class**

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myfsclaim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 75Gi
  storageClassName: rook-cephfs
```

**2. now create a pod like below that used this PVC**
```
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-1
spec:
  replicas: 2
  nodeName: worker2.xxx.xxx.xxx.com
  containers:
    - env:
      name: web-server
      image: quay.io/ocsci/nginx:latest
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: myfsclaim
        readOnly: false
```
        
Now try to get into the pod via : **oc exec --stdin --tty demo-pod-1 -- /bin/bash**
and do **cd /var/lib/www/html**
you will be able to get into the directory

**3. now create another similar pod like below that used the same PVC**

```
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-2
spec:
  replicas: 2
  nodeName: worker2.xxx.xxx.xxx.com
  containers:
    - env:
      name: web-server
      image: quay.io/ocsci/nginx:latest
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: myfsclaim
        readOnly: false
```

a)Now try to get into the pod via : **oc exec --stdin --tty demo-pod-2  -- /bin/bash**
b)and do **cd /var/lib/www/html**
you will be able to get into the directory
c) exit from this pod and go into the first pod via : **oc exec --stdin --tty demo-pod-1  -- /bin/bash**
d)and do **cd /var/lib/www/html**
you will see PERMISSION DENIED error

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
it is an openshift ENV with below versions info:
Client Version: v4.2.0-alpha.0-657-g51011e4
Server Version: 4.7.40
Kubernetes Version: v1.20.11+c343126

I am using 1.8.6 rook release

* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by Madhu-1** [comment]
I dont think there is an issue with the CSI driver here. this could be a problem with the SCC and service accounts. cephcsi nor Rook will do the SELinux labeling/relabeling in the kubernetes.

**Comment by AdarshdeepCheema** [comment]
@Madhu-1 we are using the below YAML to create the service account and doing Role-binding to privileges SCC
```

apiVersion: v1
kind: ServiceAccount
metadata:
  name: zowe-sa
  namespace: zowe
  labels:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/managed-by: manual
automountServiceAccountToken: false
---  
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zowe-role
  namespace: zowe
  labels:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/managed-by: manual
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["privileged"]
    verbs: ["use"]

---
  kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: zowe-role-binding
    namespace: zowe
    labels:
      app.kubernetes.io/name: zowe
      app.kubernetes.io/instance: zowe
      app.kubernetes.io/managed-by: manual
  subjects:
   - kind: ServiceAccount
     name: zowe-sa
  roleRef:
    kind: Role
    name: zowe-role
    apiGroup: rbac.authorization.k8s.io
```
