### ISSUE TITLE
osd-prepare job failing due to false error from `sgdisk`

### ISSUE THREAD

**Issue by smuth4** [rook/rook#9948]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

After a restart of the operator pod, the osd-prepare job started failing for one of the hosts:
```
...truncated...
2022-03-26 16:38:49.134123 D | exec: Running command: lsblk /dev/mapper/ceph--3ab6549f--9c8a--4f7a--8696--dbabb3e787d4-osd--block--67480886--ed6f--471a--96fe--9196893de1a2 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2022-03-26 16:38:49.137521 D | exec: Running command: sgdisk --print /dev/mapper/ceph--3ab6549f--9c8a--4f7a--8696--dbabb3e787d4-osd--block--67480886--ed6f--471a--96fe--9196893de1a2
2022-03-26 16:38:49.155220 C | rookcmd: failed to configure devices: failed to get device already provisioned by ceph-volume raw: failed to get device info for "/dev/mapper/ceph--3ab6549f--9c8a--4f7a--8696--dbabb3e787d4-osd--block--67480886--ed6f--471a--96fe--9196893de1a2": exit status 2
```
The operator does notice that the job has failed, but everything else completes:
```
2022-03-26 18:21:04.862866 I | op-osd: waiting... 2 of 3 OSD prepare jobs have finished processing and 68 of 68 OSDs have been updated
```
Here's the output from the sgdisk command:
```
Caution: invalid main GPT header, but valid backup; regenerating main header
from backup!

Error! Couldn't seek to partition table!
Caution! After loading partitions, the CRC doesn't check out!
Warning! One or more CRCs don't match. You should repair the disk!
Main header: ERROR
Backup header: OK
Main partition table: ERROR
Backup partition table: ERROR

Invalid partition data!
```

This same sgdisk errors shows up for 5 devices total on the same host, which all have OSDs that have been up and running for a while with no issue. As far as I can tell, bluestore just happened to write a sequence of bytes that throws off sgdisk for these devices.

So far it's not causing any actual problems, but I haven't tried making any changes to the cluster either.

**How to reproduce it (minimal and precise):**
I can't tell when this might have started or what triggered this condition, it didn't happen during a recent upgrade to 1.8.7.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.4 LTS
* Kernel (e.g. `uname -a`): 5.4.0-104-generic x86_64 GNU/Linux
* Cloud provider or hardware configuration: bare metal, heterogeneous disks
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.8.7
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)

**Comment by satoru-takeuchi** [comment]
@smuth4 It might be caused by #9701. I have some questions and requests.

* What is the previous Rook version?
* Have you add new disks/osds after upgrading to v1.8.7?
* Could.you provide your cluster.yaml?
* Could you provide the log of operator and the failed osd-prepare-pod?

**Comment by smuth4** [comment]
Sorry for the delay @satoru-takeuchi, it looks similar to the atari issue but not quite the same. It's only sgdisk that reports the phantom partitions, other tools used in the prepare job work as expected:
```
# lsblk /dev/mapper/ceph--3ab6549f--9c8a--4f7a--8696--dbabb3e787d4-osd--block--67480886--ed6f--471a--96fe--9196893de1a2 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
SIZE="8001561821184" ROTA="1" RO="0" TYPE="lvm" PKNAME="" NAME="/dev/mapper/ceph--3ab6549f--9c8a--4f7a--8696--dbabb3e787d4-osd--block--67480886--ed6f--471a--96fe--9196893de1a2" KNAME="/dev/dm-6"
# fdisk -l /dev/mapper/ceph--3ab6549f--9c8a--4f7a--8696--dbabb3e787d4-osd--block--67480886--ed6f--471a--96fe--9196893de1a2
Disk /dev/mapper/ceph--3ab6549f--9c8a--4f7a--8696--dbabb3e787d4-osd--block--67480886--ed6f--471a--96fe--9196893de1a2: 7.28 TiB, 8001561821184 bytes, 15628050432 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
```

* The previous rook version was 1.8.6, I tried downgrading and still encountered the issue. I don't mind upgrading but it doesn't look like that fix is in 1.8.8.
* I have not, I do have one ready to be added but wanted to avoid making cluster changes until this was resolved. There was a disk I had to pull for unrelated reasons, which is indicated in the operator logs by the remapped/backfilling PGs.
* cluster.yaml, trimmed a little for brevity:
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  labels:
    tanka.dev/environment: d9abae3ece1ad7bef5b83d9b36cb12521a2bc87bacd60f18
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.7
  cleanupPolicy:
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  crashCollector: {}
  dashboard:
    enabled: true
    ssl: false
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  external: {}
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 1m0s
      status:
        interval: 1m0s
    livenessProbe:
      mgr: {}
      mon: {}
      osd:
        disabled: true
  logCollector: {}
  mgr:
    count: 1
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    count: 3
  monitoring:
    enabled: true
    rulesNamespace: rook-ceph
  network:
    hostNetwork: true
    ipFamily: IPv4
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/storage
              operator: Exists
  resources:
    osd:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 250m
        memory: 1Gi
  security:
    kms: {}
  storage:
    nodes: ...trimmed for brevity...
    useAllDevices: false
    useAllNodes: false
  waitTimeoutForHealthyOSDInMinutes: 10
```
* [rook-ceph-osd-prepare.log](https://github.com/rook/rook/files/8393999/rook-ceph-osd-prepare.log)
[operator.log](https://github.com/rook/rook/files/8394000/operator.log)
